### ISSUE TITLE
Unique constraint error inside a transaction throws unparsed error (but works fine when using Node API)

### ISSUE THREAD

**Issue by kripod** [prisma/prisma#7326] opened 2021-05-28 13:55 UTC
### Bug description

While trying to auto-generate slugs for user-made pages at [Copyfolio](https://copyfol.io), we noticed that unique constraint violation errors aren’t caught properly inside a `prisma.$transaction`.

### How to reproduce

1. Have a model with a unique constraint, e.g. a `Site` with a globally unique URL `slug`.

2. Run some code which is meant to detect unique `slug` constraint violation errors – and then auto-generate a new slug to try with, but that isn’t part of the code below:

```ts
/* Fill our database with some initial data */
await prisma.site.create({ id: "1", slug: "taken-by-1" });
await prisma.site.create({ id: "2", slug: "another" });

try {
  await prisma.$transaction([
    prisma.site.updateMany({
      where: { id: "2" },
      data: { slug: "taken-by-1" },
    }),

    /* Any other site update is required for the test to fail */
    prisma.site.update({
      where: { id: "2" },
      data: { id: "2" },
    }),
  ]);
} catch (error) {
  if (
    error instanceof PrismaClientKnownRequestError &&
    error.code === "P2002"
  ) {
    console.debug("Unique constraint violation detection works");
  } else {
    console.error("Unknown error, as violation detection fails");
    throw error;
  }
}
```

It should throw an unknown error, which isn’t the expected behavior. However, then using `previewFeatures = ["nApi"]`, the code above works as expected.

### Prisma information

```prisma
model Site {
  id   String @id @default(cuid())
  slug String @unique
}
```

### Environment & setup

- OS: mac OS v11.4
- Database: PostgreSQL 12/13
- Node.js version: v14.16.1

### Prisma Version

```
prisma               : 2.23.0
@prisma/client       : 2.23.0
Current platform     : darwin
Query Engine         : query-engine adf5e8cba3daf12d456d911d72b6e9418681b28b (at node_modules/@prisma/engines/query-engine-darwin)
Migration Engine     : migration-engine-cli adf5e8cba3daf12d456d911d72b6e9418681b28b (at node_modules/@prisma/engines/migration-engine-darwin)
Introspection Engine : introspection-core adf5e8cba3daf12d456d911d72b6e9418681b28b (at node_modules/@prisma/engines/introspection-engine-darwin)
Format Binary        : prisma-fmt adf5e8cba3daf12d456d911d72b6e9418681b28b (at node_modules/@prisma/engines/prisma-fmt-darwin)
Default Engines Hash : adf5e8cba3daf12d456d911d72b6e9418681b28b
Studio               : 0.393.0
```

**Comment by pantharshit00** [comment] 2021-05-28 14:19
I can reproduce this. Looks like we aren't serializing the error properly for child process version and it is properly serialized in the NAPI implementation.

We should fix this as NAPI is not stable yet.

**Comment by matthewmueller** [comment] 2021-06-02 12:01
Just to clarify because it took me a couple reads.

- This isn't a bug with NAPI it's a problem with our existing protocole
- We should fix this because NAPI is not yet the default
- Even when NAPI is the default, we'll still keep the older protocol around

**Comment by matthewmueller** [comment] 2021-06-28 14:23
Could this be related to: https://github.com/prisma/prisma/issues/6705?

**Comment by Sytten** [comment] 2021-06-28 20:12
I would favour a breaking change in the http protocol vs a keeping a broken implementation around.

**Comment by millsp** [comment] 2021-07-31 04:52
Hey @kripod, I'm so happy to see you here! This is fixed in the upcoming https://github.com/prisma/prisma/pull/8384

**Closed** 2021-08-09 16:24 UTC
Labels: bug/2-confirmed, kind/bug, topic: error, topic: transactionApi, topic: transaction, team/client
