### ISSUE TITLE
UpdatedAt date set by default to epoch (1970..) rather than insertion time on create?

### ISSUE THREAD

**Issue by Jolg42** [prisma/prisma#3895] opened 2020-10-12 08:47 UTC
## Bug description

From a user report

- used a simple schema and initialized it with migrate
- why is the updatedAt set by default to epoch (1970..) rather than insertion time on create (inserting a row using client), isn't creation an update?

## Expected behavior

updatedAt and createdAt with the same value.

## Environment & setup

- OS: 🤷 
- Database: PostgreSQL
- Node.js version: 🤷 
- Prisma version: probably latest

```
model Post {
  id        String   @id
  updatedAt DateTime @updatedAt
  createdAt DateTime @default(now())
}
```

**Comment by pantharshit00** [comment] 2020-10-12 09:12
I am unable to reproduce this.
![image](https://user-images.githubusercontent.com/22195362/95727030-4b6d9580-0c97-11eb-9c9a-d22131d55504.png)


Migrate sets no default on updatedAt by default and the query engine correctly populates the database with the current timestamp when you insert a record.

**Comment by Jolg42** [comment] 2020-10-12 12:12
One more info I just got is this was the result of following the quickstart with `postgres:12.3-alpine`

**Comment by pantharshit00** [comment] 2020-10-31 02:58
Still no avail, I will close this now.

**Closed by pantharshit00** 2020-10-31 02:58 UTC
Labels: bug/0-needs-info, kind/bug
