### ISSUE TITLE
Internal error: Attempted to serialize empty result.

### ISSUE THREAD

**Issue by amitpatel12** [prisma/prisma#25057] opened 2024-08-21 06:44 UTC
### Bug description

  ```const createPages = data?.data.map((item) => {
      return prisma.pages.upsert({
        where: {
          pageName: item.title,
        },
        update: {},
        create: {
          pageName: item.title,
          slug: item.buttonUrl,
          PageComponents: {
            createMany: {
              data: [
                {
                  componentId: 10,
                  position: 1,
                },
                {
                  componentId: 20,
                  dataValue: {
                    title: item.title,
                    data: "",
                  },
                  position: 0,
                },
              ],
            },
          },
        },
      });
    });
    ```
 first time it's working fine but when redundant data then got this error " Internal error: Attempted to serialize empty result."
 
 

### How to reproduce

got this error
thread 'tokio-runtime-worker' panicked at query-engine\core\src\response_ir\ir_serializer.rs:57:40:
Internal error: Attempted to serialize empty result.
---> An error occurred at /admission/addFormControl:
Invalid `prisma.pageComponents.update()` invocation:

Internal error: Attempted to serialize empty result.

This is a non-recoverable error which probably happens when the Prisma Query Engine has a panic.

### Prisma information

```prisma

model Pages {
  pageId         Int              @id @default(autoincrement())
  pageName       String           @unique
  slug           String           @unique
  isActive       Boolean          @default(true)
  createdAt      DateTime         @default(now())
  updatedAt      DateTime         @updatedAt
  PageComponents PageComponents[]
  parentPageId   Int?
  draftPage      Pages?           @relation("DraftPage", fields: [parentPageId], references: [pageId], onDelete: NoAction, onUpdate: NoAction)
  draftPages     Pages[]          @relation("DraftPage")

  @@index([parentPageId])
}

model PageComponents {
  pageComponentId Int        @id @default(autoincrement())
  pageId          Int
  componentId     Int
  position        Int        @default(0)
  dataValue       Json?
  isActive        Boolean    @default(true)
  page            Pages      @relation(fields: [pageId], references: [pageId], onDelete: NoAction, onUpdate: NoAction)
  component       Components @relation(fields: [componentId], references: [componentId], onDelete: NoAction, onUpdate: NoAction)

  @@index([componentId])
  @@index([pageId])
}
```

```ts
// Add your code using Prisma Client
```

### Environment & setup

- OS: windows
- Database: mysql
- Node.js version:  20.6

### Prisma Version

```
"prisma": "^5.12.1"
```

**Comment by jkomyno** [comment] 2024-12-30 15:44
This issue is a duplicate of https://github.com/prisma/prisma/issues/17982, which was fixed in Prisma 5.13.0

**Closed by jkomyno** 2024-12-30 15:44 UTC
Labels: bug/1-unconfirmed, kind/bug, topic: mysql, domain/client, topic: upsert, topic: Attempted to serialize empty result.
