### ISSUE TITLE
Prisma Client for Java

### ISSUE THREAD

**Issue by nikolasburk** [prisma/prisma#1616] opened 2020-02-17 08:55 UTC
This is a feature request for a Java version of Prisma Client. Please leave a 👍 on the issue or comment if you're interested in Prisma Client for Java.

Also, if you have ideas or considerations regarding the API or the implementation of Prisma Client in Java, please let us know in the comments as well!

**Comment by janknieling** [comment] 2020-03-12 18:38
+1

**Comment by benmccann** [comment] 2020-04-22 03:26
The thing that seems hardest to match in Java is handling results of queries with field selection. For example, consider the following query:
```
const result = await prisma.user.findOne({
  where: { id: 1 },
  select: {
    name: true,
    profileViews: true,
  },
})
```

I'm a TypeScript beginner. How does Prisma handle this with TypeScript? Is `result` of type `any` or does it return a `User` object where all fields are optional? It looks to me like it's the former since the generated client is a `.js` file. You can't have an untyped object with fields in Java, so that's where we'll end up with a bit of a mismatch

In Java, I can think of two ways to handle this. You either return a full `User` object with all fields null except `name` and `profileViews` or you return something like `Record2` that holds two fields (where you could have `Record3`, `Record4`, etc. for selecting three or four fields). You could also support both APIs, which is what jOOQ does

**Comment by pantharshit00** [comment] 2020-04-22 04:24
You can watch https://www.youtube.com/watch?v=PJjeHzvi_VQ for an explanation on how we handle this in TS. Basically it is a combination of mapped types, conditional type and generics and everything is type safe, it does not return any.

**Comment by benmccann** [comment] 2020-04-22 04:34
Ah thanks. Yeah, unfortunately I don't think anything like that is possible in Java

**Comment by Sytten** [comment] 2020-04-22 12:44
I used JOOQ in the past and it is very good, any new API should take what they have learned since it's been there for a long time (might be hard to displace). One thing that I remember being annoying is the missing auto-update of `createdAt` and other features requiring per-processing of records.

**Comment by jregistr** [comment] 2021-03-09 13:02
> In Java, I can think of two ways to handle this. You either return a full User object with all fields null except name and profileViews or you return something like Record2 that holds two fields (where you could have Record3, Record4, etc. for selecting three or four fields). You could also support both APIs, which is what jOOQ does

On the topic of type strictness in Java, would it be possible to have Prisma generate classes/records based on the queries rather than solely on the SQL schema?

**Comment by GNVageesh** [comment] 2021-09-13 01:35
+1 for prisma and java

**Comment by bollo-omar** [comment] 2022-01-11 16:07
Bring prisma support in JVM languages

**Comment by davide-malagoli** [comment] 2022-03-04 22:36
+1

**Comment by arrbrk1** [comment] 2022-04-14 16:18
+1

**Comment by PaulFWatts** [comment] 2022-04-24 10:11
+1

**Comment by Klapeks** [comment] 2022-08-21 20:22
+1

**Comment by FeldrinH** [comment] 2023-03-29 13:47
One approach to handling fetching of only a subset of fields is to have all fields be getters and setters, where calling the getter or setter of an unfetched field throws an exception. This solves the problem of accidentally mutating/reading unloaded fields. For an example of this in prior art, this approach

**Comment by izakdvlpr** [comment] 2023-10-11 14:54
+1

**Comment by jkomyno** [comment] 2024-12-06 13:35
Hi there,

As part of our effort to clean up our GitHub repo, we’re closing this issue to help focus on features and improvements that align with our focus areas and those of our community. 

If this is issue is still important to you, feel free to reopen the issue and get like-minded users to upvote as we will prioritize fixing issues based on community interest. If you do reopen the issue, please ensure that there’s a clear method for us to reproduce it. 

For more insight into our priorities and how we’re thinking about the future of the Prisma ORM, please see our recent blog post: https://www.prisma.io/blog/prisma-orm-manifesto.

Thank you for your understanding and support!

**Closed by jkomyno** 2024-12-06 13:35 UTC
Labels: kind/feature, topic: prisma-client, topic: generator, topic: language, domain/client
