### ISSUE TITLE
Prisma schema

### ISSUE THREAD

**Issue by rishabhraj291196** [prisma/prisma#10550] opened 2021-12-03 08:16 UTC
## Problem

how can split prisma schema. its difficult to handle large schema file.

## Suggested solution

Provide some feature where we can split prisma schema. it can be automated or  manually

**Comment by HeavenOSK** [comment] 2021-12-08 09:06
@rishabhraj291196 
I encountered the same problem. I took a workaround based on following comment.
https://github.com/prisma/prisma/issues/2377#issuecomment-974662122

**Comment by pantharshit00** [comment] 2021-12-08 10:40
Hi,

Thanks for reporting this! It has already been reported before, so I am going to close this as a duplicate of #2377 as noted by @HeavenOSK

**Closed by pantharshit00** 2021-12-08 10:40 UTC
