### ISSUE TITLE
PANIC in query-engine\core\src\interpreter\query_interpreters\inmemory_record_processor.rs:111:80called `Result::unwrap()` on an `Err` value: FieldNotFound { name: "name", model: "Field not found in record Record { values: [String(\"cklmlpomm00000vmm2gmol6u2\"), Int(6)], parent_id: None }. Field names are: [\"id\", \"shop\"], looking for: \"name\"" }

### ISSUE THREAD

**Issue by jamesBeeProg** [prisma/prisma#6048] opened 2021-03-10 15:07 UTC
Hi Prisma Team! My Prisma Client just crashed. This is the report:
## Versions

| Name            | Version            |
|-----------------|--------------------|
| Node            | v12.18.4           | 
| OS              | windows            |
| Prisma Client   | 2.17.0             |
| Query Engine    | query-engine 3c463ebd78b1d21d8fdacdd27899e280cf686223|
| Database        | undefined|

## Query
```
query {
  findManyEntry(distinct: [name, year]) {
    shop
  }
}
```

## Logs
```
m{
  prisma:engine   error: Error: read ECONNRESET
  prisma:engine       at TCP.onStreamRead (internal/stream_base_commons.js:205:27) {
  prisma:engine     errno: 'ECONNRESET',
  prisma:engine     code: 'ECONNRESET',
  prisma:engine     syscall: 'read'
  prisma:engine   }
  prisma:engine }  
  prisma:engine {
  prisma:engine   error: Error: connect ECONNREFUSED 127.0.0.1:53750
  prisma:engine       at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1141:16) {
  prisma:engine     errno: 'ECONNREFUSED',
  prisma:engine     code: 'ECONNREFUSED',
  prisma:engine     syscall: 'connect',
  prisma:engine     address: '127.0.0.1',
  prisma:engine     port: 53750
  prisma:engine   }
  prisma:engine }  +2s
  prisma:engine There is a child that still runs and we want to start again  
  prisma:engine { cwd: 'C:\\Users\\jamesclark\\Projects\\step-counter\\prisma' }  
  prisma:engine Search for Query Engine in C:\Users\jamesclark\Projects\step-counter\node_modules\.prisma\client  
  prisma:engine {
  prisma:engine   flags: [
  prisma:engine     '--enable-experimental=groupBy',
  prisma:engine     '--enable-raw-queries',
  prisma:engine     '--port',
  prisma:engine     '53761'
  prisma:engine   ]
  prisma:engine }  
  prisma:engine stdout  Starting a postgresql pool with 1 connections.  
  prisma:engine stdout  Started http server on http://127.0.0.1:53761  +2s
  prisma:engine Search for Query Engine in C:\Users\jamesclark\Projects\step-counter\node_modules\.prisma\client  
  prisma:engine Client Version: 2.17.0  
  prisma:engine Engine Version: query-engine 3c463ebd78b1d21d8fdacdd27899e280cf686223  
  prisma:engine Active provider: postgresql  
  prisma:engine stdout  PANIC in query-engine\core\src\interpreter\query_interpreters\inmemory_record_processor.rs:111:80
called `Result::unwrap()` on an `Err` value: FieldNotFound { name: "name", model: "Field not found in record Record { values: [String(\"cklmlpomm00000vmm2gmol6u2\"), Int(6)], parent_id: None }. Field names are: [\"id\", \"shop\"], looking for: \"name\"" }  
  prisma:engine TypeError: this.currentRequestPromise.cancel is not a function
  prisma:engine     at NodeEngine.handlePanic (C:\Users\jamesclark\Projects\step-counter\node_modules\@prisma\client\runtime\index.js:26601:36)
  prisma:engine     at NodeEngine.setError (C:\Users\jamesclark\Projects\step-counter\node_modules\@prisma\client\runtime\index.js:26547:16)
  prisma:engine     at LineStream.<anonymous> (C:\Users\jamesclark\Projects\step-counter\node_modules\@prisma\client\runtime\index.js:26837:24)
  prisma:engine     at LineStream.emit (events.js:315:20)
  prisma:engine     at addChunk (_stream_readable.js:295:12)
  prisma:engine     at readableAddChunk (_stream_readable.js:271:9)
  prisma:engine     at LineStream.Readable.push (_stream_readable.js:212:10)
  prisma:engine     at LineStream.Transform.push (_stream_transform.js:152:32)
  prisma:engine     at LineStream._pushBuffer (C:\Users\jamesclark\Projects\step-counter\node_modules\@prisma\client\runtime\index.js:23722:19)
  prisma:engine     at LineStream._transform (C:\Users\jamesclark\Projects\step-counter\node_modules\@prisma\client\runtime\index.js:23716:10)
  prisma:engine     at LineStream.Transform._read (_stream_transform.js:191:10)
  prisma:engine     at LineStream.Transform._write (_stream_transform.js:179:12)
  prisma:engine     at doWrite (_stream_writable.js:403:12)
  prisma:engine     at writeOrBuffer (_stream_writable.js:387:5)
  prisma:engine     at LineStream.Writable.write (_stream_writable.js:318:11)
  prisma:engine     at Socket.ondata (_stream_readable.js:716:22)  {"timestamp":"Mar 10 10:02:32.737","level":"ERROR","fields":{"message":"PANIC","reason":"called `Result::unwrap()` on an `Err` value: FieldNotFound { name: \"name\", model: \"Field not found in record Record { values: [String(\\\"cklmlpomm00000vmm2gmol6u2\\\"), Int(6)], parent_id: None }. Field names are: [\\\"id\\\", \\\"shop\\\"], looking for: \\\"name\\\"\" }","file":"query-engine\\core\\src\\interpreter\\query_interpreters\\inmemory_record_processor.rs","line":111,"column":80},"target":"query_engine","span":{"name":"execute_single_operation"},"spans":[{"name":"execute_single_operation"}]}  
  prisma:engine {
  prisma:engine   error: Error: read ECONNRESET
  prisma:engine       at TCP.onStreamRead (internal/stream_base_commons.js:205:27) {
  prisma:engine     errno: 'ECONNRESET',
  prisma:engine     code: 'ECONNRESET',
  prisma:engine     syscall: 'read'
  prisma:engine   }
  prisma:engine }  
```

## Client Snippet
```ts
    const query = await prisma.entry.findMany({
        select: {
            shop: true,
        },
        distinct: ['name', 'year'],
    });
```

## Schema
```prisma
datasource db {
    provider = "postgresql"
    url      = env("DATABASE_URL")
}

generator client {
    provider = "prisma-client-js"
    previewFeatures = ["groupBy"]
}

model Entry {
    id       String   @id @default(cuid())
    name     String
    year     Int
    shop     Int
    steps    Int
    date     DateTime
    proofUrl String
}
```

**Comment by pantharshit00** [comment] 2021-03-10 15:23
Hi,

Thanks for reporting this! It has already been reported before, so I am going to close this as a duplicate of https://github.com/prisma/prisma/issues/5969

**Closed by pantharshit00** 2021-03-10 15:23 UTC
