### ISSUE TITLE
Only get SQL queries instead of executing them

### ISSUE THREAD

**Issue by nahtnam** [prisma/prisma#2805] opened 2020-06-19 09:59 UTC
## Problem
I am currently working with retool.com which allows me to interface with my postgres database in a dashboard. The first thing I reached for was Prisma! I was able to generate a query using intellisense pretty quickly, but the problem was I had to run the query and look in the logs to see what the sql was. This is problematic if the query is an insert/update/delete/etc.

## Suggested solution

```ts
const sql = await prisma.feed.findMany({
  // complex stuff here
}).toSQL();

console.log(sql); // => SELECT .....
```

## Alternatives
Currently you can just run your server, throw in some random clause that you know isn't true like `id: 99999999` and then remove it from the query.

## Additional context
One problem I noticed is that sometimes Prisma splits the `findMany` into two actual SQL queries instead of doing a join. This wouldn't work as the user is expecting one SQL statement so Prisma would need additional logic to stop this from happening.

**Comment by Jolg42** [comment] 2020-08-18 07:38
Closing as duplicate of https://github.com/prisma/prisma-client-js/issues/746 

Thanks for the issue!

**Closed by Jolg42** 2020-08-18 07:38 UTC
Labels: kind/feature, topic: prisma-client
