### ISSUE TITLE
Prisma Datamodel: Primary key as a combination of two relational models

### ISSUE THREAD

**Issue by devautor** [prisma/prisma#3553] opened 2018-11-19 13:03 UTC
I have a problem in Prisma data modeling where I have **to constrain that a user can submit only one review for a product**.  I have **following design for the non-constrained situation**.

> Should `Customer` and `Product` be combined into a primary key in `ProductReview` model, or should this constraint be imposed at the application server level, and not at the database level?

Datamodel for now (non-constrained version):

    type Product {
      id: ID! @unique
      title: String!
      reviews: [ProductReview!]! @relation(name: "ProductReviews", onDelete: CASCADE)
    }

    type Customer {
      id: ID! @unique
      email: String @unique
    }

    type ProductReview {
      id: ID! @unique
      forProduct: Product! @relation(name: "ProductReviews", onDelete: SET_NULL)
      byCustomer: Customer!
      review: String!
      ratinng: Float!
    }

**Describe the solution you'd like**
It would help to have a model similar to my ER diagram, that is, a set of fields selected as the primary key.

**Describe alternatives you've considered**
As suggested in answers to my [stackoverflow question](https://stackoverflow.com/questions/53373101/prisma-datamodel-primary-key-as-a-combination-of-two-relational-models/53373425) on this issue, I should handle this constraint at the application server level.

**Comment by mavilein** [comment] 2018-11-19 17:00
Hey @devautor ,

thanks for reaching out to us and providing such a thorough feature request! 🙏 
I think your issue could be adressed through combined unique indexes. They are not implemented yet but we already have a [spec](https://github.com/prisma/prisma/issues/3405) for it. I would be curious to hear if you think that this feature could solve your problems.

**Comment by devautor** [comment] 2018-11-19 17:18
Hello @mavilein Thanks for your kind response! I did go through that spec, and it certainly seems to be the answer. On my own, I was trying to make a `Type` like the following, before realizing that `@unique` is reserved for scalar fields only:
```
type ProductReview {
  id: ID! @unique
  primaryKey:  ProductCustomerKey!  @unique
  review: String!
  ratinng: Float!
}

type ProductCustomerKey {
  forProduct: Product! 
  byCustomer: Customer!
}
```

**Comment by nikolasburk** [comment] 2018-11-20 08:30
Hey @devautor, thanks so much for opening this issue. When I asked you on SO to create this FR I was not aware that we already had an open FR for this, you can find it [here](https://github.com/prisma/prisma/issues/171). I'm going to close this issue as a duplicate of #171, please leave your +1 on the other FR 👍 🙂

**Closed by nikolasburk** 2018-11-20 08:30 UTC

**Comment by mahmudemam** [comment] 2019-11-30 12:49
@devautor  This solution doesn't work because Prisma requires @id for one of each type field, which makes the
