### ISSUE TITLE
One-to-many relation fields are always nullable, not taking in account the datamodel

### ISSUE THREAD

**Issue by nikis05** [prisma/prisma#3867] opened 2019-01-15 12:19 UTC
**Describe the bug**
With the following datamodel:

```graphql
type User {
  sessions: [Session!]! @relation(name: "UserToSessions", onDelete: CASCADE)
  ...
}

type Session {
  user: User! @relation(name: "UserToSessions")
  ...
}
```

Why is "sessions" field on type "user" nullable in the resulting Prisma API?
```graphql
type User {
sessions(...): [Session!]
...
}
```

I've checked multiple cases, this effect always persists in one-to-many relations. The one-to-many relation field is always nullable, regardless of whether it is marked as nullable or non-nullable in the datamodel. Thanks in advance!

**To Reproduce**
1. Create a datamodel with a one-to-many relation field, mark the field as required
2. Deploy to Prisma Cloud
3. Open Prisma playground
4. Open type definition for type that contains the one-to-many relation field

**Expected behavior**
Prisma should pay attention to whether the relation is nullable or non-nullable in datamodel.
Non-nullable relation in datamodel:
```graphql
type User {
  sessions: [Session!]! @relation(name: "UserToSessions", onDelete: CASCADE)
  ...
}
```
is expected to make Prisma create a non-nullable relation field:
```graphql
type User {
sessions(...): [Session!]!
...
}
```

Nullable relation in datamodel:
```graphql
type User {
  sessions: [Session!] @relation(name: "UserToSessions", onDelete: CASCADE)
  ...
}
```

is expected to make Prisma create a nullable relation field:
```graphql
type User {
sessions(...): [Session!]
...
}
```

Nullable
**Versions (please complete the following information):**
 - Connector: N/A (cloud)
 - Prisma Server: 1.25-beta-1 (cloud)
 - OS: N/A (cloud)
 - CLI: v1.24.0

**Comment by FrankSandqvist** [comment] 2019-01-21 08:40
Yes, this is strange. Things started breaking for me all of a sudden, this has got to have come with a recent version.

**Comment by pantharshit00** [comment] 2019-02-16 16:24
@FrankSandqvist

I tested it out and the behaviour is same across all versions.

**Comment by pantharshit00** [comment] 2019-04-04 15:27
I investigated it more. This behaviour is defined in the openCRUD spec that we follow:

![image](https://user-images.githubusercontent.com/22195362/55567853-2dc38580-571c-11e9-8c43-4f9d9726e3e4.png)


Also, closing as duplicate of #3674

**Closed by pantharshit00** 2019-04-04 15:27 UTC
Labels: area/cli, bug/2-confirmed
