### ISSUE TITLE
Error on Aggregate Count - MySQL - TypeScript - Prisma 1.25

### ISSUE THREAD

**Issue by Mercurial** [prisma/prisma#3946] opened 2019-01-28 21:28 UTC
I am trying to run this code

![image](https://user-images.githubusercontent.com/585569/51867493-a4dc4680-2386-11e9-985d-baf66502ccc0.png)

but I am getting this error 

![image](https://user-images.githubusercontent.com/585569/51867510-b02f7200-2386-11e9-8875-1a69d75ae4d8.png)

i have to change the code to this for it to work

![image](https://user-images.githubusercontent.com/585569/51867535-c0475180-2386-11e9-814c-ce24130754ea.png)

not sure if thats intended

**Comment by pantharshit00** [comment] 2019-01-29 12:53
This is fixed as a patch in the latest stable (1.25.4). Please install it via yarn add prisma-client-lib.

Closing as duplicate of #3919

**Closed by pantharshit00** 2019-01-29 12:53 UTC

**Comment by Mercurial** [comment] 2019-01-29 15:14
hello @pantharshit00 I am still getting it even after upgrading to 1.25.4

prisma-client-lib 1.25.4
prisma (docker image 1.25.4)
prisma cli 1.25.4
