### ISSUE TITLE
thread '<unnamed>' panicked at 'assertion failed: `(left == right)`

### ISSUE THREAD

**Issue by spg** [prisma/prisma#17954] opened 2023-02-15 22:53 UTC
When running tests with Vitest, I have the following error:

```
[...snip...]
 ❯ src/authorization/authorization.endpoints.integration-test.ts (3)
   ❯ Authorization API endpoints (3)
     ⠸ [ beforeAll ]
     · GET /v1/authorization/training (3)
thread '<unnamed>' panicked at 'assertion failed: `(left == right)`
  left: `1`,
 right: `0`: failed to delete napi ref', query-engine/query-engine-node-api/src/engine.rs:131:1
stack backtrace:
   0:        0x11cf0eea8 - _napi_register_module_v1
   1:        0x11c8dab4c - <unknown>
   2:        0x11ceed3c8 - _napi_register_module_v1
   3:        0x11cf122f4 - _napi_register_module_v1
   4:        0x11cf11f54 - _napi_register_module_v1
   5:        0x11cf12e2c - _napi_register_module_v1
   6:        0x11cf129b8 - _napi_register_module_v1
   7:        0x11cf12928 - _napi_register_module_v1
   8:        0x11cf12904 - _napi_register_module_v1
   9:        0x11d192618 - _napi_register_module_v1
  10:        0x11d1927fc - _napi_register_module_v1
  11:        0x11d199f20 - _napi_register_module_v1
  12:        0x11c844450 - <unknown>
fatal runtime error: failed to initiate panic, error 5
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by janpio** [comment] 2023-02-16 13:37
Can you help us with some more inforamtion how we could reproduce this?
Does this happen all the times or just sometimes?
What database are you using? What version of Prisma?

**Comment by rizen** [comment] 2023-03-04 08:06
I'm having the same problem. I'm running prima and @prisma/client 4.11.0 (which is the latest at the time of this post). 

This is on a MySQL 5.7 database.

It happens from a single query like 

prisma.user.count({ where : { id : 'xxx'}})

**Comment by rcbevans** [comment] 2023-04-02 06:26
I'm seeing the same issue causing intermittent test failures during deployment.

There I'm running against pg14.

**Comment by rizen** [comment] 2023-04-02 13:29
Mine turned out to be that I was missing an await somewhere

**Comment by rcbevans** [comment] 2023-04-03 20:00
@rizen how did you track that down?

I've just reverted our tests back to jest because our CI builds were failing almost every time without multiple manual retries of the test run.

**Comment by rizen** [comment] 2023-04-03 20:09
Unfortunately it was painful to find it. I created a copy of my app, and kept ripping out parts until I had the smallest part possible and the error was still happening. Even when I got down to less than 50 lines of code, it was still not easily apparent to me. I even showed several other devs and nobody saw it. 

I even tried rewriting the app to not use inheritance, as I was thinking maybe mixins were the problem. 

I eventually [created a repo to submit a bug report to prisma](https://github.com/rizen/prisma-inheritance-seg-fault/blob/main/inheritance.test.ts) and still didn't see it at that point. But then after sleeping on it for a weekend, I took another look and sure enough I forgot an await on a super() call. You can see it on line 24 here: https://github.com/rizen/prisma-inheritance-seg-fault/blob/main/inheritance.test.ts

**Comment by aqrln** [comment] 2023-06-06 10:16
What version of Prisma were you on? Could you retry with the latest Prisma? The error looks similar to an issue that should be fixed as of Prisma 4.13.0 and later.

**Comment by aqrln** [comment] 2023-06-06 11:55
@rizen the problem in your repro looks a bit different than the error you were initially getting, and a segfault happening because of a missing await on your side is still a bug on our side that must be fixed. I can reproduce this with the latest Prisma and your repo. I'll open a separate issue for that.

**Comment by jkomyno** [comment] 2024-12-11 11:03
Hi there,

As part of our effort to clean up our GitHub repo, we’re closing this issue to help focus on features and improvements that align with our focus areas and those of our community. We recommend using [this workaround](https://github.com/prisma/prisma/issues/17954#issuecomment-1578706995) by our colleague @aqrln.

---

If this is issue is still important to you, feel free to reopen the issue and get like-minded users to upvote as we will prioritize fixing issues based on community interest. If you do reopen the issue, please ensure that there’s a clear method for us to reproduce it. 

For more insight into our priorities and how we’re thinking about the future of the Prisma ORM, please see our recent blog post: https://www.prisma.io/blog/prisma-orm-manifesto.

Thank you for your understanding and support!

**Closed by jkomyno** 2024-12-11 11:03 UTC
Labels: bug/2-confirmed, kind/bug, topic: tests, domain/client, topic: vitest

**Comment by aqrln** [comment] 2024-12-11 11:16
fwiw vitest now uses child processes rather than worker threads by default so this issue is unlikely to affect many people even if the bug still exists (not to mention that it might already be fixed even for worker threads given that napi-rs has been updated multiple times)
