### ISSUE TITLE
Compiling with `@vercel/ncc` does not copy the `schema.prisma` file.

### ISSUE THREAD

**Issue by medz** [prisma/prisma#12503] opened 2022-03-24 11:06 UTC
### Bug description

Compiling with [`vercel/ncc`](https://github.com/vercel/ncc) does not copy the schema.prisma` file

### How to reproduce

1. Create a using Prisma project
2. install `prisma` and `@prisma/client`
3. install `vercel/ncc`
4. run `npx ncc build test.ts -o dist`
5. copy `dist` to Other locations other than the project

### Prisma information

```
prisma                  : 3.11.0
@prisma/client          : 3.11.0
Current platform        : darwin
Query Engine (Node-API) : libquery-engine b371888aaf8f51357c7457d836b86d12da91658b (at node_modules/@prisma/engines/libquery_engine-darwin.dylib.node)
Migration Engine        : migration-engine-cli b371888aaf8f51357c7457d836b86d12da91658b (at node_modules/@prisma/engines/migration-engine-darwin)
Introspection Engine    : introspection-core b371888aaf8f51357c7457d836b86d12da91658b (at node_modules/@prisma/engines/introspection-engine-darwin)
Format Binary           : prisma-fmt b371888aaf8f51357c7457d836b86d12da91658b (at node_modules/@prisma/engines/prisma-fmt-darwin)
Default Engines Hash    : b371888aaf8f51357c7457d836b86d12da91658b
Studio                  : 0.458.0
```

### Environment & setup

- OS: 
- Database: 
- Node.js version: 

### Prisma Version

```
3.11.0
```

**Comment by janpio** [comment] 2022-03-24 21:58
I am pretty sure I know what you are talking about, but to make sure:
What error are you getting where because of this?
What `schema.prisma` file should be copied where exactly when?

**Comment by medz** [comment] 2022-03-25 03:05
> I am pretty sure I know what you are talking about, but to make sure: What error are you getting where because of this? What `schema.prisma` file should be copied where exactly when?

@janpio When packaging with NCC , you need to copy the `schema.prisma` file for the output directory . This error comes from what I know about Prisma , and I got it right earlier when I packaged with Prisma + NCC . Forget when , the schema . Prisma definition of `@prisma/client` is no longer valid . I noticed that this problem came from my project . After I successfully packaged it with NCC , I copied the output file to the place I want to run (not in project ) , and prompted me to need a `schema.prisma` file .

**Comment by janpio** [comment] 2022-03-25 13:46
For our reproduction of this: Anything special about `test.ts`? I assume you have something in your schema and ran `prisma generate` at least once so the Client got generated?

**Comment by medz** [comment] 2022-03-26 04:36
@janpio I further tested it, and the newly created pure ts or js project does not have this problem, but using the NestJS framework does not copy `schema.prisma` to the output directory! Maybe it's not a Prisma problem, I need to investigate further.

**Comment by codeprefect** [comment] 2022-11-26 11:45
@medz, for NestJS, you can do the following:

1. move the `schema.prisma` file to somewhere within the source directory
2. update `package.json` to point to the new location
    
  ```[json]
  // package.json
  "prisma": {
     "schema": "src/schema.prisma"
  }
  ```
3. add the following to your `nest-cli.json` file
  
  ```[json]
  // nest-cli.json
  "compilerOptions": {
    "assets": ["**/schema.prisma"]
  }
  ```

**Comment by Jolg42** [comment] 2022-12-07 16:46
Note: `@vercel/ncc` is used in next.js repo
https://github.com/search?q=repo%3Avercel%2Fnext.js+vercel%2Fncc&type=code

**Comment by janpio** [comment] 2023-01-28 00:42
I created a simple project:
```
mkdir foo && cd foo && npm init -y && npm install prisma @prisma/client @vercel/ncc ts-node && npx prisma init
```
Then copied over `script.ts` and `tsconfig.json` from our example project https://github.com/prisma/prisma-examples/tree/latest/typescript/script
Then:
```
PS C:\Users\Jan\Documents\throwaway\ncc> npx ncc build script.ts -o dist    
ncc: Version 0.36.1
ncc: Compiling file index.js into CJS
ncc: Using typescript@4.9.4 (local user-provided)
Error: [tsl] ERROR in C:\Users\Jan\Documents\throwaway\ncc\script.ts(1,30)
      TS2792: Cannot find module '@prisma/client'. Did you mean to set the 'moduleResolution' option to 'node', or to add aliases to the 'paths' option?
    at C:\Users\Jan\Documents\throwaway\ncc\node_modules\@vercel\ncc\dist\ncc/index.js.cache.js:37:1870077
    at C:\Users\Jan\Documents\throwaway\ncc\node_modules\@vercel\ncc\dist\ncc/index.js.cache.js:37:383620
    at _done (eval at create (C:\Users\Jan\Documents\throwaway\ncc\node_modules\@vercel\ncc\dist\ncc/index.js.cache.js:20:75523), <anonymous>:9:1)
    at eval (eval at create (C:\Users\Jan\Documents\throwaway\ncc\node_modules\@vercel\ncc\dist\ncc/index.js.cache.js:20:75523), <anonymous>:34:22)
```
After fixing that by adding `"moduleResolution":"node"` to tsconfig I get:
```
PS C:\Users\Jan\Documents\throwaway\ncc> npx ncc build script.ts -o dist
ncc: Version 0.36.1
ncc: Compiling file index.js into CJS
ncc: Using typescript@4.9.4 (local user-provided)
    1kB  dist\schema.prisma
 1185kB  dist\index.js
16357kB  dist\client/query_engine-windows.dll.node
17543kB  [2238ms] - ncc 0.36.1
```

Then inside `/dist` I can run the script with `nodex index.js`:
```
PS C:\Users\Jan\Documents\throwaway\ncc\dist> node .\index.js
PrismaClientInitializationError: 
Invalid `prisma.user.create()` invocation in
C:\Users\Jan\Documents\throwaway\ncc\dist\index.js:33783:37

  33780 // A `main` function so that we can use async/await
  33781 async function main() {
  33782     // Seed the database with users and posts
→ 33783     const user1 = await prisma.user.create(
Query engine library for current platform "windows" could not be found.
You incorrectly pinned it to windows

This probably happens, because you built Prisma Client on a different platform.
(Prisma Client looked in "C:\Users\Jan\Documents\throwaway\ncc\dist\query_engine-windows.dll.node")

Searched Locations:

  C:\Users\Jan\Documents\.prisma\client
  C:\Users\Jan\Documents\throwaway\ncc\node_modules\@prisma\client
  C:\Users\Jan\Documents\throwaway\ncc
  C:\Users\Jan\Documents\throwaway\ncc\dist
  C:\Users\Jan\Documents\throwaway\ncc\dist
  /tmp/prisma-engines
  C:\Users\Jan\Documents\throwaway\ncc\dist


To solve this problem, add the platform "windows" to the "binaryTargets" attribute in the "generator" block in the "schema.prisma" file:
generator client {
  provider      = "prisma-client-js"
  binaryTargets = ["native"]
}

Then run "prisma generate" for your changes to take effect.
Read more about deploying Prisma Client: https://pris.ly/d/client-generator
    at RequestHandler.handleRequestError (C:\Users\Jan\Documents\throwaway\ncc\dist\index.js:32160:13)
    at RequestHandler.handleAndLogRequestError (C:\Users\Jan\Documents\throwaway\ncc\dist\index.js:32118:12)
    at C:\Users\Jan\Documents\throwaway\ncc\dist\index.js:32663:25
    at async PrismaClient._executeRequest (C:\Users\Jan\Documents\throwaway\ncc\dist\index.js:33227:22)
    at async PrismaClient._request (C:\Users\Jan\Documents\throwaway\ncc\dist\index.js:33199:16)
    at async main (C:\Users\Jan\Documents\throwaway\ncc\dist\index.js:33783:19) {
  clientVersion: '4.9.0',
  errorCode: undefined
}
```

The schema file though is copied correctly to `dist/schema.prisma` and can successfully be read by the bundled Prisma Client. It's just that Query Engine that is unexpectedly in a folder `client`.

(Same when I copy the `dist` folder somewhere else.)

**Comment by yaacov-commenda** [comment] 2023-02-09 10:58
@janpio, I am hitting the exact same problem you just described, where the Query Engine gets copied into the `client` folder.

As a workaround I added 

`cp dist/client/libquery_engine-*.node dist/`

to my build step after running ncc.

**Comment by janpio** [comment] 2023-02-09 13:04
What exactly is your setup @yaacov-commenda? Can you maybe share your project or a minimal reproduction? There are _so_ many factors that play into this - so we better know what we are dealing with here.

**Comment by yaacov-commenda** [comment] 2023-02-10 10:22
Fair enough! 

I am using a yarn monorepo with prisma in a package that's shared between the next.js apps. I just added a node.js server and tried to use ncc to pull in the node_modules from the monorepo. Just as you described in your case, the generated query engine gets copied into some `client` directory. 

I am not able to share my project unfortunately. I was hoping you knew why the query engine is getting copied into `client` in your case, so that I could see whether I was having the same issue. If not, don't worry about it, I have a workaround for now 🙂

**Comment by jeffreys-cat** [comment] 2023-08-09 06:44
has any updated?

**Comment by jkomyno** [comment] 2024-12-13 09:58
Hi there,

As part of our effort to clean up our GitHub repo, we’re closing this issue to help focus on features and improvements that align with our focus areas and those of our community. 
This is an issue on `@vercel/ncc`'s side, not Prisma. In particular, it's a bundler limitation of ncc.

---

If this is issue is still important to you, feel free to reopen the issue and get like-minded users to upvote as we will prioritize fixing issues based on community interest. If you do reopen the issue, please ensure that there’s a clear method for us to reproduce it. 

For more insight into our priorities and how we’re thinking about the future of the Prisma ORM, please see our recent blog post: https://www.prisma.io/blog/prisma-orm-manifesto.

Thank you for your understanding and support!

**Closed by jkomyno** 2024-12-13 09:58 UTC
Labels: bug/1-unconfirmed, kind/bug, domain/client, topic: bundler, topic: NestJS, topic: deployment/vercel
