### ISSUE TITLE
prisma:client:operation takes too long

### ISSUE THREAD

**Issue by radoslavirha** [prisma/prisma#15314] opened 2022-09-14 08:04 UTC
### Bug description

Hi,

we have less used dev environment and when i create first request to API, opentelemetry traces are showing prisma is really slow.

I'm not sure what is causing ^^... PostgreSQL, Docker, Hapi ? Anybody experienced similar behavior?

Thanks

### How to reproduce

Not sure, may be specific for my APIs

Grafana:

![Screenshot 2022-09-14 at 9 47 26](https://user-images.githubusercontent.com/23722745/190095987-648ec73a-2c15-40b6-861b-7b270524680b.png)

### Expected behavior

First query after some time to be faster

### Prisma information

usually first API request calls `findFirst` (organization based on URL) ... not sure if field is indexed currently, but there is less than 100 rows today...so index should not be an issue now.

### Environment & setup

- OS: Debian
- Database: PostgreSQL
- Node.js version: 16

### Prisma Version

```
4.2.0
```

**Comment by Radik24** [comment] 2022-09-14 15:17
Yeah, and it's simple query. I need to identify an issue. As i said, if I call this endpoint after some time of inactivity (some testing env) it takes too long, but if I call it again later, the same query takes e.g. 50 ms which is fine I would say.

So i don't know if prisma is closing connections, or I have some issue from DB?

Thanks

**Comment by janpio** [comment] 2022-09-14 16:50
Looking at the spans, it seems that the query itself is actually done very quickly - and then "nothing" happens for a long time? Or is there maybe something further down that did not make it into the screenshot?

**Comment by Sakhro** [comment] 2022-09-25 16:14
We probably have the same issue

In dev env after the first call, if we wait for some time, the second call would take more than 30 sec to resolve. After that, the next calls will work fine until we wait for some time (1-2 min) again.

Here are some logs that we cached:
```
 prisma:client  Prisma Client call: +3m
  prisma:client  prisma.listing.findUnique({
  where: {
    id: 'cl7yz1etz10960muzlm2xqb6y'
  }
}) +0ms
  prisma:client  Generated request: +0ms
  prisma:client  query {
  findUniqueListing(where: {
    id: "cl7yz1etz10960muzlm2xqb6y"
  }) {
    id
    createdAt
    updatedAt
    amount
    signature
    hash
    txHash
    isSold
    isDisabled
    createdById
    nftId
    purchasedById
    itemId
    marketAddress
  }
}
 +0ms
  prisma:client:libraryEngine  sending request, this.libraryStarted: true +3m
```
And then it will take like 30 sec to resolve the query. And this is only if we set pool_timeout=0. In other case, we will get p2024 error.

On the other hand, the same version, but on production, will have issues only with findUnique and only for specific records that have a specific field (in our case `marketAddress`) value. If we change the value of this field for another it immediately starts to work

For me, it sounds crazy. I could try to create an example if needed, but it's so random that I don't know if I would be able to without showing production code

Also maybe its also connected to this https://github.com/prisma/prisma/issues/15334

**Comment by Radik24** [comment] 2022-09-26 06:13
Hi @janpio. Sorry I thought I replied. Yeah there is another span below, but it always takes few μs.

**Comment by janpio** [comment] 2022-09-26 14:57
@Sakhro Can you maybe enable tracing? That would give you similar graphs than what @Radik24 posted: https://www.prisma.io/docs/concepts/components/prisma-client/opentelemetry-tracing
Are you also on PostgreSQL?

@Radik24 Super weird. I do not even know what further information to ask for. Is this reproducible consistently?

**Comment by laplab** [comment] 2024-01-25 14:07
Closing this for now, because we have no additional information for investigation. If somebody gets the same problem, please write a comment below with more details and we will investigate.

**Closed** 2024-01-25 14:07 UTC
Labels: bug/1-unconfirmed, kind/bug, topic: performance, topic: previewFeatures, team/client, topic: postgresql, topic: tracing
