### ISSUE TITLE
Expose types to the frontend for Next.js

### ISSUE THREAD

**Issue by itstheandre** [prisma/prisma#3252] opened 2020-08-09 22:30 UTC
## Bug description

I am playing around with prisma and getting that async_hooks error and its a rather weird thing. Let me explain:
If i have this:
```js
import { prisma } from "../utils/prismaClient";

import { startingForm } from "../utils/startingForm";
```
Nothing breaks. here, prisma is jsut a new PrismaClient(). Nothing else. In this application I am just using prisma for the getStaticProps of Next.js

However, if I add a index.js to the utils folder and just do:
```js
import { prisma, startingForm } from '../utils"
```
I get the error again. Is there a reason for this?

You can take a look at the repo here:

https://github.com/itstheandre/build-cv-messing-around

Not a lot of code written. Just a little small thing I was messing around to build a resume and the async_hooks issue came up again. Now I know I am not using prisma on the frontend per se. I am only using it in the api of Next.js.
Any idea of what might be happening?

## Prisma information

Prisma Schema
```prisma
datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

generator client {
  provider = "prisma-client-js"
}

model Experience {
  id          Int     @default(autoincrement()) @id
  name        String
  company     String?
  personal    Boolean @default(false)
  from        String?
  to          String?
  description String
  website     String?

}

```

Prisma Query -> Literally the only query I am doing
```ts
const experiences = await prisma.experience.findMany({})

```
## Environment & setup

```
- OS: Mac OS
- Database: PostgreSQL
- Node.js version: 12.16.3
- Prisma version:  2.4.1

```

**Comment by jamesonev** [comment] 2020-08-11 13:52
I'm having a similar issue where trying to compile throws 
```
Failed to compile.

ModuleNotFoundError: Module not found: Error: Can't resolve 'async_hooks' in '/Users/jamesonevans/myproject/node_modules/@prisma/client/runtime'
```
I'm running Prisma `2.4.0` on MacOS Catalina `10.15.6` with Postgres and Node `14.5.0`. I'm also writing a next.js project.

**Comment by pantharshit00** [comment] 2020-08-12 21:37
I can confirm this. Looks like this is caused by https://github.com/prisma/prisma/pull/3181

I will say this is more of a bug in next js but we will look into this.

**Comment by itstheandre** [comment] 2020-08-13 00:26
It has been figured out :)
So, Next.Js is importing everythihg, but it bundles everything in its own way. here: ```prisma``` is backend code, but the startingForm is frontend code. and next js is importing them from the same file, which causes the idea that both ```can``` be used on the frontend, which it cant

**Comment by timsuchanek** [comment] 2020-08-13 07:12
Thanks for reporting!
I just tried it out in an older version, concretely `2.1.0` and a different native node package fails then - `child_process`.

This means, that the code elimination of Next fails in this case.
So this is not a regression, but a problem in Next's code elimination in general.
This happens, because in your example, the `utils/index.js` exports both a Node.js module and a frontend module, which seems to confuse the code elimination.

**Comment by timsuchanek** [comment] 2020-08-13 07:27
Here's the Next.js issue: https://github.com/vercel/next.js/issues/16153

**Comment by timsuchanek** [comment] 2020-08-13 07:29
@itstheandre you can also fix the issue but directly importing from the `./utils/prismaClient` in your frontend code. The problem is really the mixed export, there the code elimination gets stuck.

We'll update here once it's resolved :)

**Comment by itstheandre** [comment] 2020-08-13 17:13
@timsuchanek its fine. In this the only thing I am doing is getting , like you said, importing from a different path.
In a monorepo i have a package that is node stuff only and this way it wont also clash.

Thanks!

**Comment by stefnnn** [comment] 2020-09-13 19:34
I hit this bug as well. Digging deeper for me the issue was, that I use generated types from @prisma/client quite a lot in the frontend code, which works well enough for type checking. However, when I use an Enum in the frontend code (generated from my prisma schema), then the async_hooks error from above comes up.

**Comment by stefnnn** [comment] 2020-09-13 20:38
just wondering @timsuchanek if the reason for the enums not working is that they are generated as «export const» and not typescript enums. see also this post: https://ncjamieson.com/dont-export-const-enums/

**Comment by Siilwyn** [comment] 2020-09-23 09:15
Just stumbled on this issue in a different environment: not using TypeScript. But would love to import the possible values I can use from an enum in my frontend.

**Comment by jca41** [comment] 2020-11-06 01:06
Was also facing this issue when trying to use apollo-link-schema to directly query Prisma on getStaticProps.
Solved the issue by dynamically importing the file that was causing the error inside getStaticProps.

```
export async function getStaticProps() {
  const client = (await import('../services/graphql/apollo-client-ssr')).default;
  await client.query({ query: myQuery });
  return {
    props: {
      a: client.cache.extract(),
    },
  };
}
```

**Comment by hyusetiawan** [comment] 2020-11-10 11:12
I am having the same issue after upgrading to 2.10.2 and trying to render in a next.js (10) environment though I am not sure if the prisma update is the main cause because I updated a bunch of other packages.

The error thrown is similar to the ones listed above, with async_hooks is being required but does not exist. I am working around that by `import type` as much as I can, and type the variables then use string literal values instead.

Though there is a working workaround, to me this is a land mine that if we accidentally import an enum from @prisma/client, it would just break in other places and it's hard to trace down unless you do the process of elimination.

**Comment by cyrus-za** [comment] 2020-12-09 16:34
@timsuchanek any reason why you closed this issue? I am still running into it on 2.13.0

**Comment by jamesonev** [comment] 2020-12-09 17:16
You can get around this by using interfaces. In `interfaces/index.ts`, I import types from Prisma and then re-export them to the frontend. Then just update all frontend imports to come from `interfaces`. Here's an example of my `interfaces/index.ts`:
```
import {
  Foo as _Foo,
  Bar as _Bar,
} from "@prisma/client";

export type Foo = _Foo;
export interface FooBarr {
foo: Foo
bar: Bar
}
```

**Comment by timsuchanek** [comment] 2020-12-09 17:21
@cyrus-za yes, we fixed this and also mentioned it in the release notes - https://github.com/prisma/prisma/releases/tag/2.13.0
I should have mentioned it in the issue here.

What exact issue are you facing? Which frontend framework are you using?

**Comment by cyrus-za** [comment] 2020-12-10 08:53
@timsuchanek I experienced it in 2.12.0 then upgraded to 2.13.0 yesterday and the error changed from async_hooks issue to importing prisma client.

```sh
Error: PrismaClient is unable to be run in the browser.
In case this error is unexpected for you, please report it in https://github.com/prisma/prisma-client-js/issues
```

I am using nextjs with nx.dev and created a nx lib for the data layer which uses prisma. The only react code that imports prisma client is inside getStaticProps. 

I am using enums in prisma and defined types from those and exported the types on the lib, which is imported in the render method, but that is not making the error go away.

**Comment by cyrus-za** [comment] 2020-12-11 09:06
Update: I've solved my issue by not instantiating the prisma client in the export itself, but to rather export the class and then calling `new PrismaClient()` inside `getStaticProps` for each and every page. Kind of annoying as it would mean that multiple db connections will be made at build time.

**Comment by williamluke4** [comment] 2020-12-11 10:02
@cyrus-za Could you create a new issue for this with an example of the code you were trying to use. I have tried to reproduce this but can not.

**Closed by williamluke4** 2020-12-11 10:02 UTC
Labels: kind/feature, tech/typescript, topic: framework

**Comment by itstheandre** [comment] 2020-12-30 09:06
Hey there!
I just tried and got the same error as @cyrus-za .
Basically if I have a file that exports `export const prisma = new PrismaClient()` like this then I get the error that was previously displayed. 

I guess that to mitigate that issue, after each getStaticProps we can maybe directly disconnect?

Ideally, the goal would be (at least for me) to instantiate prisma just once and then keep that connection opened on all the nextjs pages files, but i guess that wont be possible

**Comment by williamluke4** [comment] 2020-12-30 09:47
> @cyrus-za Could you create a new issue for this with an example of the code you were trying to use. I have tried to reproduce this but can not.
@itstheandre Could you please create a separate issue for this and link it here. If you want this fixed/looked into fast it really helps if you can provide a minimal reproduction.

**Comment by flybayer** [comment] 2021-01-01 22:50
@itstheandre probably you want to do like this:

```ts
// prisma.ts
import {PrismaClient} from "@prisma/client"
export * from "@prisma/client"

export default function prisma(): PrismaClient {
  globalThis.prisma = globalThis.prisma || new PrismaClient()
  return globalThis.prisma
}
```
and use like
```ts
// api.ts
import prisma from './prisma'

await prisma().user.findMany()
```

**Comment by cyrus-za** [comment] 2021-01-06 12:59
yep I am doing exactly what @flybayer suggested above. It works, but it is annoying

**Comment by flybayer** [comment] 2021-01-14 18:02
**A way to get Types in frontend without using `prisma()`:**

```ts
import {PrismaClient} from "@prisma/client"
export * from "@prisma/client"

const ProxyPrisma = new Proxy(PrismaClient, {
  construct(target, args) {
    if (typeof window !== "undefined") return {}
    globalThis["db"] = globalThis["db"] || new target(...args)
    return globalThis["db"]
  },
})

const prisma = new ProxyPrisma()

export default prisma
```

**Comment by cyrus-za** [comment] 2021-01-15 11:16
Sweet. I didn't even thing of using Proxy api.

**Comment by heibel** [comment] 2021-01-18 09:09
@flybayer Very useful comment!

**Comment by Baldrani** [comment] 2021-03-17 06:09
@flybayer Hey ! Your solution works for me but I'm not sure of what I am reading, would you be so kind just to make us a little explanation it would be so helpful !! Thank you in any case !
