### ISSUE TITLE
update() returning { count: 1 }

### ISSUE THREAD

**Issue by dan003400** [prisma/prisma#5852] opened 2021-02-25 19:42 UTC
```
const user = await context.prisma.user.update({
  where: {
    id: localGlobalID,
  },
  data: {
    title,
  },
});

console.log("updated user", user);

// Output
updated user { count: 1 }
```

**Comment by ryands17** [comment] 2021-02-26 07:21
@dan003400 👋 
Could you share your `prisma` and `@prisma/client` version? Also if you're using TypeScript, what does the return type denote when you hover over the `user` variable?

**Comment by dan003400** [comment] 2021-02-27 04:45
2.17.0 - not sure about that, Im not using vscode.

**Comment by nikolasburk** [comment] 2021-02-27 08:13
Hey Dan, thank you for raising this issue! As we [discussed on Slack](https://prisma.slack.com/archives/CKQTGR6T0/p1614412548375800?thread_ts=1614387619.368500&cid=CKQTGR6T0), for _some_ reason your `update` method seems to be understood by TypeScript as an `updateMany`, which definitely seems very strange! `update` and `updateMany` have different input arguments and different return types, so we're keen on understanding what exactly is wrong with your code and helping you resolve the issue.

However, with the information that we have right now it is impossible for us to reproduce the problem. Would you mind sharing a couple of more infos, such as:

- the relevant models of your Prisma schema
- the [SQL queries that are generated by Prism Client](https://www.prisma.io/docs/concepts/components/prisma-client/debugging)
- Prisma's [debugging](https://www.prisma.io/docs/about/faq#how-can-i-see-the-generated-queries-that-prisma-client-sends-to-my-database) output

Also, are you able to reproduce the problem in an isolated environment or does it only happen in the context of your project? Since your `prisma` instance is attached to a `context` object, I assume this error occurs inside of a GraphQL resolver? What happens if you run this Prisma Client query outside of a resolver in the same project? Do you still see the error?

**Comment by dan003400** [comment] 2021-02-27 08:16
Sounds like you might be referring to this issue (#5884) not this issue?

**Comment by nikolasburk** [comment] 2021-02-27 08:21
I think it probably applies to both, since both seem to have the same problem: "For some reason it seems that my client is generating some updateMany types/functions for my singular update function?"

This is very mundane advice, but did you try clearing `node_modules`?

```
rm -rf node_modules
npm install
```

**Comment by dan003400** [comment] 2021-02-27 08:21
Haha yes, I actually tried this a number of times with different version of prisma to see if that was the issue.

**Comment by dan003400** [comment] 2021-02-27 08:29
Actually - I take that back, this is the same model that we saw the original issue with return type being `{ count: 1 }`.

So it sounds like this model in our schema generators is messed up.

**Comment by nikolasburk** [comment] 2021-03-03 07:32
Closing this one as well as it was the same underlying issue as https://github.com/prisma/prisma/issues/5884

**Closed by nikolasburk** 2021-03-03 07:32 UTC
