### ISSUE TITLE
Error installing Prisma throws sha256 mismatch error for @prisma/engines 

### ISSUE THREAD

**Issue by eliliam** [prisma/prisma#16244] opened 2022-11-11 18:15 UTC
While trying to install prisma via `npm install prisma`, the installation fails in the step where it installs `@prisma/engines` and tries to download the `migration-engine.gz` binary. When it compares the hash with what it's "supposed" to be, the comparison fails causing the whole installation to fail.

<img width="1728" alt="Screenshot 2022-11-11 at 11 09 08 AM" src="https://user-images.githubusercontent.com/14301439/201402465-a458d749-1cb7-463e-954b-46c3a42ec298.png">

**Comment by janpio** [comment] 2022-11-11 19:02
Duplicate of https://github.com/prisma/prisma/issues/16233, will repost your details there.

**Closed by janpio** 2022-11-11 19:02 UTC
