### ISSUE TITLE
v5.9.0 / Don't generate type. And the error from the previous version is still there

### ISSUE THREAD

**Issue by localer** [prisma/prisma#22896] opened 2024-01-31 14:55 UTC
### Bug description

Don't generate type.(All model types are any.)
And the error from the previous version is still there. ([v5.8.1 / I suddenly couldn't connect. #22895](https://github.com/prisma/prisma/issues/22895))

### How to reproduce

- run: `npx prisma generate --no-engine`
- All generated types are any...

### Expected behavior

Types are defined as in previous versions

### Prisma information

```prisma
// Add your schema.prisma

generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider  = "postgresql"
  url       = env("DATABASE_URL")
  directUrl = env("DIRECT_URL")
}

model User {
  id             Int              @id @default(autoincrement())
  username       String
  nickname       String?
  description    String?
  discordId      String?
  createdAt      DateTime         @default(now())
  email          String
  password       String
  student        Boolean          @default(false)
  iconURL        String?
  bannned        BanReport?
  followers      Follows[]        @relation("follower")
  following      Follows[]        @relation("following")
  thread         Thread[]
  thread_message Thread_Message[]
  role           Role[]           @relation("RoleToUser")
  sessions       Session[]
}

model Session {
  token     String   @unique
  userId    Int
  user      User     @relation(fields: [userId], references: [id])
  expiresAt DateTime
}

model BanReport {
  reportId  Int      @id @default(autoincrement())
  userId    Int      @unique
  reason    String?
  createdAt DateTime @default(now())
  user      User     @relation(fields: [userId], references: [id])
}

model Role {
  id            Int     @id @default(autoincrement())
  name          String
  description   String?
  thread_edit   Boolean @default(false)
  thread_remove Boolean @default(false)
  user_ban      Boolean @default(false)
  user_edit     Boolean @default(false)
  user_remove   Boolean @default(false)
  users         User[]  @relation("RoleToUser")
}

model Follows {
  followerId  Int
  followingId Int
  follower    User @relation("follower", fields: [followerId], references: [id])
  following   User @relation("following", fields: [followingId], references: [id])

  @@id([followerId, followingId])
}

model Thread {
  thread_id Int              @id @default(autoincrement())
  authorId  Int
  title     String
  content   String
  createdAt DateTime         @default(now())
  author    User             @relation(fields: [authorId], references: [id])
  message   Thread_Message[]
}

model Thread_Message {
  message_id Int    @id @default(autoincrement())
  thread_id  Int
  authorId   Int
  author     User   @relation(fields: [authorId], references: [id])
  thread     Thread @relation(fields: [thread_id], references: [thread_id])
}
```

```ts
// Add your code using Prisma Client

import { PrismaClient } from '@prisma/client/edge';
import { withAccelerate } from '@prisma/extension-accelerate'

export const prisma = new PrismaClient().$extends(withAccelerate());
```

### Environment & setup

- OS: Linux
- Database: PostgreSQL
- Node.js version: v20.11.0

### Prisma Version

```
5.8.1
```

**Comment by Jolg42** [comment] 2024-01-31 15:19
@localer thanks for the report.

This looks like a duplicate of 
https://github.com/prisma/prisma/issues/22888
https://github.com/prisma/prisma/issues/22870

The fix is https://github.com/prisma/prisma/pull/22876

You can try the following versions `5.10.0-integration-fix-nodenext.2` and `5.9.1-dev.1`
Both should fix the issue.

If you can let us know if that indeed fixes the problem for you, that would be great.
Stay tuned later for the official patch release.

**Comment by sandrodesouza** [comment] 2024-01-31 15:27
5.9.1-dev.1 worked for me

**Closed** 2024-01-31 22:48 UTC
Labels: bug/1-unconfirmed, kind/regression, topic: client types, tech/typescript, team/client, 5.9.0

**Comment by jkomyno** [comment] 2024-01-31 22:50
Hi! About the "All model types are any" problem I confirm that:
- this is a duplicate of https://github.com/prisma/prisma/issues/22870
- I'm only able to observe this problem when my `tsconfig.json` file contains:
  ```json
  "moduleResolution": "bundler",
  "module": "esnext",
  ```
  The following, for instance, makes types work again:
  ```json
  "moduleResolution": "node",
  "module": "ES2022",
  ```

**Comment by localer** [comment] 2024-02-01 03:37
solved. thank you

**Comment by Jolg42** [comment] 2024-02-01 16:04
https://github.com/prisma/prisma/releases/tag/5.9.1 is now available with the fix ✨ 

Please create [a new issue](https://github.com/prisma/prisma/issues/new/choose) if you find a bug.
