### ISSUE TITLE
RUST error, Did not find a relation for model UserDetail and field userid,   Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

### ISSUE THREAD

**Issue by CGerAJ** [prisma/prisma#2214] opened 2020-04-17 07:11 UTC
## How to reproduce

where i run 
```
npx prisma migrate save --name init --experimental
npx prisma migrate up --experimental
```

database sucess create tables!
```
CREATE TABLE `UserDetail` (
  `apptheme` varchar(191) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `backfortune` int(11) DEFAULT NULL,
  `createdAt` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `flower` int(11) NOT NULL DEFAULT '0',
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `language` varchar(191) COLLATE utf8mb4_unicode_ci DEFAULT 'CN',
  `membersTimeEnd` varchar(191) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `membersTimeStart` varchar(191) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `membersType` varchar(191) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `modules` varchar(191) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `saveFlower` int(11) NOT NULL DEFAULT '0',
  `tofortune` int(11) NOT NULL DEFAULT '0',
  `updatedAt` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `userId` int(11) NOT NULL,
  `xiuxing` int(11) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  UNIQUE KEY `UserDetail.userId` (`userId`),
  CONSTRAINT `UserDetail_ibfk_1` FOREIGN KEY (`userId`) REFERENCES `Users` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;


CREATE TABLE `Users` (
  `acceptmsg` tinyint(1) NOT NULL DEFAULT '0',
  `autologin` tinyint(1) NOT NULL DEFAULT '1',
  `avatar` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `birthday` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '202006080100',
  `createdAt` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `deviceid` varchar(191) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `isKnowHour` tinyint(1) NOT NULL DEFAULT '1',
  `isLeapMonth` tinyint(1) NOT NULL DEFAULT '0',
  `loginDays` int(11) NOT NULL DEFAULT '0',
  `lunisolar` tinyint(1) NOT NULL DEFAULT '0',
  `mobile` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `name` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `password` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '2ETIPWZa1R4+LJRW3nahQw==',
  `sex` int(11) NOT NULL,
  `tourist` tinyint(1) NOT NULL DEFAULT '0',
  `updatedAt` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `userOs` varchar(191) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`id`,`mobile`),
  UNIQUE KEY `Users.id` (`id`),
  UNIQUE KEY `Users.mobile` (`mobile`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;


CREATE TABLE `WechatUserRelatioId` (
  `city` varchar(191) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `country` varchar(191) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `createdAt` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `nickname` varchar(191) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `openid` varchar(191) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `province` varchar(191) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `sex` int(11) DEFAULT NULL,
  `unionid` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `updatedAt` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `userId` int(11) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `WechatUserRelatioId.userId` (`userId`),
  UNIQUE KEY `WechatUserRelatioId.unionid` (`unionid`),
  CONSTRAINT `WechatUserRelatioId_ibfk_1` FOREIGN KEY (`userId`) REFERENCES `Users` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

```

then i run 
```
npx prisma generate
```

get a error 

```
thread 'main' panicked at 'Did not find a relation for model UserDetail and field userid', libs/prisma-models/src/datamodel_converter.rs:83:29
stack backtrace:
   0: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
   1: core::fmt::write
   2: std::io::Write::write_fmt
   3: std::panicking::default_hook::{{closure}}
   4: std::panicking::default_hook
   5: std::panicking::rust_panic_with_hook
   6: rust_begin_unwind
   7: std::panicking::begin_panic_fmt
   8: prisma_models::datamodel_converter::DatamodelConverter::convert_fields::{{closure}}::{{closure}}
   9: <core::iter::adapters::Map<I,F> as core::iter::traits::iterator::Iterator>::fold
  10: <core::iter::adapters::Map<I,F> as core::iter::traits::iterator::Iterator>::fold
  11: prisma_models::datamodel_converter::DatamodelConverter::convert
  12: query_engine::cli::CliCommand::dmmf
  13: query_engine::main::{{closure}}
  14: <std::future::GenFuture<T> as core::future::future::Future>::poll
  15: tokio::runtime::enter::Enter::block_on
  16: tokio::runtime::context::enter
  17: tokio::runtime::handle::Handle::enter
  18: query_engine::main
  19: std::rt::lang_start::{{closure}}
  20: std::panicking::try::do_call
  21: __rust_maybe_catch_panic
  22: std::rt::lang_start_internal
  23: main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

```

## Prisma information

```prisma
generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "mysql"
  url      = env("DATABASE_URL")
}

model Users {
  id Int @default(autoincrement()) @unique
  acceptmsg Boolean @default(false)
  autologin Boolean @default(true)
  avatar String
  deviceid String?
  name String
  password String 
  mobile String @unique
  sex Int
  isKnowHour Boolean @default(true)
  isLeapMonth Boolean @default(false)
  lunisolar Boolean @default(false)
  birthday String
  tourist Boolean @default(false)
  loginDays Int @default(0)
  userOs String?
  createdAt  DateTime  @default(now())
  updatedAt  DateTime  @default(now())
  @@id([id, mobile])
}


model UserDetail {
  id Int @default(autoincrement())
  userid Users  @relation(fields: [userId], references: [id])
  userId Int @unique
  apptheme String?
  backfortune Int?
  flower Int @default(0)
  language String? @default("CN")
  membersTimeEnd String?
  membersTimeStart String?
  membersType String?
  modules String?
  saveFlower Int @default(0)
  tofortune Int @default(0)
  xiuxing Int @default(0)
  createdAt  DateTime  @default(now())
  updatedAt  DateTime  @default(now())

  @@id([id])
}

model WechatUserRelatioId {
  id Int @default(autoincrement())
  userid Users  @relation(fields: [userId], references: [id])
  userId Int  @unique
  openid String?
  unionid String @unique
  nickname String?
  sex Int?
  country String?
  province String?
  city String?
  createdAt  DateTime  @default(now())
  updatedAt  DateTime  @default(now())

  @@id([id])
}

```

## Environment & setup

- OS: [e.g. Mac OS, Windows, Debian, CentOS, ...]
- Database: [PostgreSQL, MySQL, MariaDB or SQLite]
- Prisma version: [Run `prisma -v` to see your Prisma version]
- Node.js version: [Run `node -v` to see your Node.js version]

- OS:  Mac OS
- Database: MySQL
- Prisma version: 
@prisma/cli          : 2.0.0-beta.2
Current platform     : darwin
- Node.js version:  v12.16.2

**Comment by pantharshit00** [comment] 2020-04-18 04:49
I tried this out in the latest alpha and I can reproduce this even after adding relations on the other side.

Not sure if this is a schema misuse issue or a parser bug. We will need to investigate further.

**Comment by pantharshit00** [comment] 2020-04-18 04:52
The modified schema that I tried with the alpha version and got the same panic:
```prisma
model Users {
  id                  Int                 @default(autoincrement()) @unique
  acceptmsg           Boolean             @default(false)
  autologin           Boolean             @default(true)
  avatar              String
  deviceid            String?
  name                String
  password            String
  mobile              String              @unique
  sex                 Int
  isKnowHour          Boolean             @default(true)
  isLeapMonth         Boolean             @default(false)
  lunisolar           Boolean             @default(false)
  birthday            String
  tourist             Boolean             @default(false)
  loginDays           Int                 @default(0)
  userOs              String?
  createdAt           DateTime            @default(now())
  updatedAt           DateTime            @default(now())
  details             UserDetail
  wechatUserRelatioId WechatUserRelatioId

  @@id([id, mobile])
}

model UserDetail {
  id               Int      @default(autoincrement())
  userid           Users    @relation(fields: [userId], references: [id])
  userId           Int      @unique
  apptheme         String?
  backfortune      Int?
  flower           Int      @default(0)
  language         String?  @default("CN")
  membersTimeEnd   String?
  membersTimeStart String?
  membersType      String?
  modules          String?
  saveFlower       Int      @default(0)
  tofortune        Int      @default(0)
  xiuxing          Int      @default(0)
  createdAt        DateTime @default(now())
  updatedAt        DateTime @default(now())

  @@id([id])
}

model WechatUserRelatioId {
  id        Int      @default(autoincrement())
  userid    Users    @relation(fields: [userId], references: [id])
  userId    Int      @unique
  openid    String?
  unionid   String   @unique
  nickname  String?
  sex       Int?
  country   String?
  province  String?
  city      String?
  createdAt DateTime @default(now())
  updatedAt DateTime @default(now())

  @@id([id])
}
```

**Comment by mavilein** [comment] 2020-04-23 16:33
Fixed in https://github.com/prisma/prisma-engines/pull/708

**Closed by mavilein** 2020-04-23 16:33 UTC
Labels: bug/2-confirmed, kind/bug, team/engines, topic: schema

**Comment by CGerAJ** [comment] 2020-04-27 00:59
tks

**Comment by brielov** [comment] 2021-01-02 18:54
I have the same exact problem on prisma `2.13.1`.

```prisma
model Movie {
  id       String           @id @default(cuid())
  title    String
  slug     String           @unique
  synopsis String
  year     Int
  runtime  Int
  imdb     String           @unique
  rating   Float
  poster   String
  genres   String[]
  cast     ActorsOnMovies[] @relation("ActorsOnMovies")

  createdAt DateTime @default(now())
  updatedAt DateTime @updatedAt
}

model Actor {
  id     String           @id @default(cuid())
  imdb   String           @unique
  name   String
  movies ActorsOnMovies[] @relation("ActorsOnMovies")

  createdAt DateTime @default(now())
  updtedAt  DateTime @updatedAt
}

model ActorsOnMovies {
  actorId   String
  actor     Actor  @relation("ActorsOnMovies", fields: [actorId], references: [id])
  movieId   String
  movie     Movie  @relation("ActorsOnMovies", fields: [movieId], references: [id])
  character String


  @@id([actorId, movieId])
}
```

Then I run `prisma db push --force --preview-feature` and I get:

```
Running generate... (Use --skip-generate to skip the generators)
Error: Schema parsing
thread 'main' panicked at 'Did not find a relation for model Actor and field movies', libs/prisma-models/src/datamodel_converter.rs:80:29
stack backtrace:
   0: _rust_begin_unwind
   1: std::panicking::begin_panic_fmt
   2: prisma_models::datamodel_converter::DatamodelConverter::convert_fields::{{closure}}::{{closure}}
   3: <core::iter::adapters::Map<I,F> as core::iter::traits::iterator::Iterator>::fold
   4: <core::iter::adapters::Map<I,F> as core::iter::traits::iterator::Iterator>::fold
   5: prisma_models::datamodel_converter::DatamodelConverter::convert
   6: query_engine::main::main::{{closure}}::main::{{closure}}
   7: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
   8: std::thread::local::LocalKey<T>::with
   9: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  10: async_io::driver::block_on
  11: tokio::runtime::context::enter
  12: tokio::runtime::handle::Handle::enter
  13: std::thread::local::LocalKey<T>::with
  14: std::thread::local::LocalKey<T>::with
  15: async_std::task::builder::Builder::blocking
  16: query_engine::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by janpio** [comment] 2021-01-08 14:56
Please open a new issue @brielov for this - so much changed from 3/4 of a year ago that this is most probably because of a different reason. Please fill the full issue template.
