### ISSUE TITLE
prisma files

### ISSUE THREAD

**Issue by stephanlevi** [prisma/prisma#2343] opened 2020-04-30 17:30 UTC
## Problem
i want to write the schema of the data models in a ts/js file

## Solution
have the ability to write my data models in a ts/js file

## Alternatives
none i can think of

**Comment by pantharshit00** [comment] 2020-05-04 11:01
Hi,

Thanks for reporting this! It has already been reported before, so I am going to close this as a duplicate of https://github.com/prisma/prisma/issues/1396

**Closed by pantharshit00** 2020-05-04 11:01 UTC
