### ISSUE TITLE
mysql: Incorrect returned value when calling stored procedure

### ISSUE THREAD

**Issue by nicosampler** [prisma/prisma#2275] opened 2020-04-22 20:09 UTC
## Bug description
I'm executing a raw query like so:
`
 return ctx.prisma.raw('CALL increaseShopCounter("2f58dbe793ad4d821fe");')
`
It executes the query correctly in the DB but the returned value is incorrect.
It always returns `"1"`

```
{
  "data": {
    "requestAppointment": "1"
  }
}
```
## Expected behavior

When I execute the stored procedure against mysql it returns
![image](https://user-images.githubusercontent.com/4376509/80028680-e0978a80-84bb-11ea-81b6-353c59b14f14.png)

## Prisma information

- Prisma version: 
```
@prisma/cli          : 2.0.0-beta.3, 2.0.0-beta.2, 2.0.0-beta.1
Current platform     : debian-openssl-1.1.x
Query Engine         : query-engine 2fb8f444d9cdf7c0beee7b041194b42d7a9ce1e6 (at /home/nicosampler/develop/cauda/node_modules/@prisma/cli/query-engine-debian-openssl-1.1.x)
Migration Engine     : migration-engine-cli 2fb8f444d9cdf7c0beee7b041194b42d7a9ce1e6 (at /home/nicosampler/develop/cauda/node_modules/@prisma/cli/migration-engine-debian-openssl-1.1.x)
Introspection Engine : introspection-core 2fb8f444d9cdf7c0beee7b041194b42d7a9ce1e6 (at /home/nicosampler/develop/cauda/node_modules/@prisma/cli/introspection-engine-debian-openssl-1.1.x)
```
- Node.js version: v10.16.3

**Comment by pantharshit00** [comment] 2020-04-24 07:48
Hi,

Thanks for reporting this! It has already been reported before, so I am going to close this as a duplicate of https://github.com/prisma/prisma/issues/2208

Basically right now, query-engine only returns data if your query start with a select statement. Please see https://github.com/prisma/prisma/issues/2208#issuecomment-616086097 for more details

**Closed by pantharshit00** 2020-04-24 07:48 UTC
Labels: 2.0.0-beta.3, topic: raw
