### ISSUE TITLE
Dash (-) in UNIQUE key leads to error of TS file

### ISSUE THREAD

**Issue by Akxe** [prisma/prisma#2393] opened 2020-05-07 14:54 UTC
## How to reproduce

* Have a database model with (unique) key with name containing dash (`no-dupes` in my example).
* run `prisma introspect`
* run `prisma generate`

```
CREATE TABLE `obobyPoznamky` (
  `idPozn` smallint(5) unsigned NOT NULL,
  `idOsoby` smallint(5) unsigned NOT NULL,
  PRIMARY KEY (`idPozn`),
  UNIQUE KEY `no-dupes` (`idPozn`,`idOsoby`) /*!80000 INVISIBLE */,
  KEY `osoby` (`idOsoby`),
) ENGINE=InnoDB DEFAULT CHARSET=cp1250 COLLATE=cp1250_czech_cs;
```

```
model obobyPoznamky {
  idOsoby  Int
  idPozn   Int      @id
  osoby    osoby    @relation(fields: [idOsoby], references: [idOsoby])
  poznamky poznamky @relation(fields: [idPozn], references: [idPozn])

  @@index([idOsoby], name: "osoby")
  @@unique([idPozn, idOsoby], name: "no-dupes")
}
```

## Expected behavior

Expected the key name to be renamed to not create invalid TS file.

## Environment & setup

Database MySQL, but I suppose it will be a problem with all of them.

```
@prisma/cli          : 2.0.0-beta.4
Current platform     : windows
Query Engine         : query-engine afd294205618b1c825b013ba6f5a6ebe4aa4a514 
Migration Engine     : migration-engine-cli afd294205618b1c825b013ba6f5a6ebe4aa4a514 
Introspection Engine : introspection-core afd294205618b1c825b013ba6f5a6ebe4aa4a514 
```

**Comment by janpio** [comment] 2020-05-11 13:19
What problem does this cause? The model looks fine to me.

**Comment by Akxe** [comment] 2020-05-11 13:24
@janpio The error is when running `prisma generate`. It will create an invalid TS type.

```
export type no-dupesCompoundUniqueInput = {
  idPozn: Int
  idOsoby: Int
}
```

**Comment by pantharshit00** [comment] 2020-05-12 07:41
I can confirm this issue in ` 2.0.0-alpha.1204`

**Comment by do4gr** [comment] 2020-07-23 16:46
I looked into this issue and the problem is not only limited to `-`, but a full sanitation of the names is necessary. 

A couple of questions came up for me:
* Why do we only allow naming the constraint in @@unique but not in @@id? Is that intentional? It is a nice functionality since it allows you to have custom names for compound inputs instead of the concatenated fieldnames.
* Introspect could sanitize @@unique names, we would then need an equivalent to `@map` there in order for migrate not to be confused by the changed name. This would necessitate new syntax along the lines of `@@unique([a, b], name: "valid", map: "in-valid")`

Depending on what we choose to do, there will be changes needed in the validator, migrate,    introspection and QE.

**Comment by mavilein** [comment] 2020-07-24 08:56
Re the questions:
* The missing name for `@@id` was probably not intentional. I think we just forgot it.
* Yes we would need an equivalent for `@map`. The `name` argument was originally only intended to represent the name of a compound input the client API. However we also started to use it to represent the name of an index in the underlying database. This looks intuitive at first but leads to those problems. We never reached an agreement how the argument for the name in db should be called and that is why we are in this situation now.

**Comment by Akxe** [comment] 2020-07-24 09:38
> * Why do we only allow naming the constraint in `@@unique` but not in `@@id`? Is that intentional? It is a nice functionality since it allows you to have custom names for compound inputs instead of the concatenated fieldnames.

Can I somehow rename `@@index` and `@relation`? As they get usually created by the workbench, they have really bad names.
Some even have `?` ex: `@@index([idAgent], name: "svoo?agent_idx")`

**Comment by tomhoule** [comment] 2020-07-24 10:13
I agree we should clarify this, especially with the current work on migrations. There are two crucial questions related to migrations and names of ids, unique constraints and relations:

- What names should we expect to be in sync between the prisma schema and the database? (what names should we migrate)
- In case we do want to take these names into account for migrations, can we expect these names to be exhaustively populated by introspection? Are there implicit defaults for these constraints that we can assume if they are left implict in the prisma schema?

My preference would be to have defaults we know and apply when migrating with migrate. When the constraint names do not match the defaults, we write them into the introspected schema, so migrate (which needs them) knows them without introspecting the database.

**Comment by matthewmueller** [comment] 2020-07-24 14:42
```
@@unique([idPozn, idOsoby], name: "no_dupes", map: "no-dupes")
```

Seems reasonable.

**Comment by Akxe** [comment] 2020-07-24 21:50
@matthewmueller I know it is trouout now, but map does not convey any meaning... "original" would be much more explanatory than "map"

**Comment by pantharshit00** [comment] 2021-05-04 12:42
Closing in favour of https://github.com/prisma/prisma/issues/6680

**Closed by pantharshit00** 2021-05-04 12:42 UTC
Labels: bug/2-confirmed, kind/bug, status/needs-action, team/migrations, tech/engines, topic: introspection
