### ISSUE TITLE
Import .prisma files inside .prisma file

### ISSUE THREAD

**Issue by onursagir** [prisma/prisma#2628] opened 2020-06-01 11:18 UTC
## Problem

When creating a prisma file it would be nice to import from node_modules or other prisma files for example we could allow users to import enums

```
import {CountryCodes} from 'some-package'

model SomeModel {
  id             Int      @id @default(autoincrement())
  country        CountryCodes
}
```
Or in some cases we could allow for entire models to be imported for example for a rights and roles packages that we can just import and use. 
```
import {UserRoles} from '@prisma/roles-package'

model Users {
  id           Int      @id @default(autoincrement())
  roles        UserRoles
}
```
This would allow us to create an ecosystem around prisma. As an example this package [Laravel Permissions](https://github.com/spatie/laravel-permission) in a way does what I previously described, and I know you can't compare Laravel with Prisma, but the thing I am trying to go at is that it would be nice to be able to share our models, seeds ands complete solutions with other people

**Comment by pantharshit00** [comment] 2020-06-01 11:29
Closing as a duplicate of https://github.com/prisma/prisma/issues/2377

**Closed by pantharshit00** 2020-06-01 11:29 UTC
