### ISSUE TITLE
Prisma client can't generate schema

### ISSUE THREAD

**Issue by tomitrescak** [prisma/prisma#3151] opened 2018-09-20 06:00 UTC
**Describe the bug**

I'm trying to generate a schema for but it fails. this is the schema:

```graphql
type AccessCondition {
  organisationId: ID
  roleId: ID
  userId: ID
}

type Access {
  id: ID! @unique
  createdById: ID!
  createdOn: DateTime
  modifiedById: ID
  modifiedOn: DateTime
  read: [AccessCondition!]! @relation(name: "CanRead", onDelete: CASCADE)
  write: [AccessCondition!]! @relation(name: "CanWrite", onDelete: CASCADE)
  execute: [AccessCondition!]! @relation(name: "CanExecute", onDelete: CASCADE)
}
```

This is the error:

```
Error: Opposite side of relation directive "CanRead" found at "Access.read" is missing on type "AccessCondition"
    at Function.DatamodelParser.parseFromSchema (/Users/tomi/Github/apps/corporatorts/node_modules/prisma-generate-schema/src/datamodel/parser.ts:132:19)
    at Function.DatamodelParser.parseFromSchemaString (/Users/tomi/Github/apps/corporatorts/node_modules/prisma-generate-schema/src/datamodel/parser.ts:22:28)
    at parseInternalTypes (/Users/tomi/Github/apps/corporatorts/node_modules/prisma-generate-schema/src/index.ts:13:26)
    at generateCRUDSchema (/Users/tomi/Github/apps/corporatorts/node_modules/prisma-generate-schema/src/index.ts:23:17)
    at Object.generateCRUDSchemaString [as default] (/Users/tomi/Github/apps/corporatorts/node_modules/prisma-generate-schema/src/index.ts:36:22)
    at GenereateCommand.<anonymous> (/Users/tomi/Github/apps/corporatorts/node_modules/prisma-cli-core/src/commands/generate/generate.ts:47:52)
    at step (/Users/tomi/Github/apps/corporatorts/node_modules/prisma-cli-core/dist/commands/generate/generate.js:42:23)
    at Object.next (/Users/tomi/Github/apps/corporatorts/node_modules/prisma-cli-core/dist/commands/generate/generate.js:23:53)
    at fulfilled (/Users/tomi/Github/apps/corporatorts/node_modules/prisma-cli-core/dist/commands/generate/generate.js:14:58)
```

**To Reproduce**

Use the schema above and run `prisma generate` with 1.17.beta24

**Expected behavior**

Prisma generates the schema

**Screenshots**

**Versions (please complete the following information):**
 - OS:OS X High Sierra
 - prisma/1.17.0-beta.24 (darwin-x64) node-v10.9.0

**Comment by Errorname** [comment] 2018-09-20 07:47
It isn't explicit in the documentation, but I think that for a relation to work, you need to declare both sides of the relation.

This means that your AccessCondition also needs to define attributes with the @relation directives. (One for "CanRead", one for "CanWrite" and one for "CanExecute")

Also,  I see that you have the createdOn and modifiedOn attributes. In the documentation, you can see:
```
The id, createdAt and updatedAt fields are managed by Prisma and read-only in the exposed Prisma API (meaning they can not be altered via mutations).
`
``
Maybe you could use that.

**Comment by marktani** [comment] 2018-09-20 08:16
Duplicate of #3143.

**Closed by marktani** 2018-09-20 08:16 UTC
