### ISSUE TITLE
PANIC: called `Option::unwrap()` on a `None` value in query-engine/core/src/query_document/parser.rs:250:87

### ISSUE THREAD

**Issue by mostafa7904** [prisma/prisma#8225] opened 2021-07-11 17:44 UTC
Hi Prisma Team! My Prisma Client just crashed. This is the report:
This happened after I added the nApi previewFeature.
I'm also using a PaaS to deploy. I have no info about their server config. 
I had no issues on own PC.

## Versions

| Name            | Version            |
|-----------------|--------------------|
| Node            | v14.15.0           | 
| OS              | debian-openssl-1.1.x|
| Prisma Client   | 2.26.0             |
| Query Engine    | 0.1.0              |
| Database        | mysql              |

## Query
```
{"X":{}}
```

## Logs
```
    at LibraryEngine.logger (/app/node_modules/@prisma/client/runtime/index.js:22751:32)
    at /app/node_modules/@prisma/client/runtime/index.js:22721:36
prisma:client:napi sending request, this.libraryStarted: true
prisma:client:napi library already starting, this.libraryStarted: true
prisma:client:napi graphQLToJSError
prisma:client:fetcher Error: called `Option::unwrap()` on a `None` value
    at LibraryEngine.prismaGraphQLToJSError (/app/node_modules/@prisma/client/runtime/index.js:22870:14)
    at LibraryEngine.request (/app/node_modules/@prisma/client/runtime/index.js:22885:24)
    at async cb (/app/node_modules/@prisma/client/runtime/index.js:33866:26)
    at async Object.exports.updateUser (/app/modules/users/model.js:51:20)
    at async exports.updateUser (/app/modules/users/controller.js:44:20)
```

## Client Snippet
```js
const user = await db.user.findFirst({
      where: {
        deleted: {
          equals: false,
        },
        OR: [
          {
            email: {
              equals: email,
            },
          },
          {
            username: {
              equals: email,
            },
          },
        ],
      },
      select: {
        id: true,
        avatar: true,
        username: true,
        email: true,
        password: true,
        profile_completed: true,
        profession: true,
        email_verified: true,
        bio: true,
        social_media: true,
        header_img: true,
        full_name: true,
      },
    });
```

## Schema
```prisma
model User {
  id                Int              @id @default(autoincrement())
  username          String           @unique @db.VarChar(255)
  email             String           @unique @db.VarChar(255)
  password          String           @db.VarChar(255)
  created_at        DateTime         @default(now()) @db.DateTime(6)
  updated_at        DateTime         @updatedAt
  deleted           Boolean          @default(false)
  type              Roles            @default(USER)
  avatar            String?          @db.VarChar(250)
  header_img        String?          @db.VarChar(250)
  bio               String?          @db.Text
  full_name         String?          @db.VarChar(250)
  posts             Post[]           @relation(name: "posts")
  likes             Likes[]          @relation(name: "userLikes")
  bookmarks         Bookmarks[]      @relation(name: "userBookmarks")
  comments          Comments[]
  commentLikes      commentLikes[]
  commentReplies    commentReplies[]
  pollVotes         PollVotes[]
  verified          Boolean          @default(false)
  email_verified    Boolean          @default(false)
  profile_completed Boolean          @default(false)
  social_media      Json?

  @@index([email, username])
  @@map("users")
}

```

**Comment by pantharshit00** [comment] 2021-07-11 20:46
Hello @mostafa7904 

I am unable to reproduce this when I tried this locally. As you mentioned you are using a PaaS, so can you please tell me which PaaS you are using so that we may try it there? 

Also, I noticed you are using `napi` preview, can you please try disabling and report if this is still happening.

**Comment by mostafa7904** [comment] 2021-07-11 20:57
I disabled the nApi and so far there is no error. So i guess it is because of nApi. I make sure to inform you if anything happens.
Btw i forgot to mention this error happened after a few queries. So the first couple of queries worked fine and then this happened.
I'm using an Iranian PaaS called [Liara](liara.ir). Everything is in Persian so you might have a difficult time understanding things. Tell me if you need any help with that.

**Comment by pantharshit00** [comment] 2021-07-29 14:17
I will close this for as I can't reproduce this NAPI as well with 2.28. Please let us know if this happens again. 

Hosting platform shouldn't matter here.

**Closed by pantharshit00** 2021-07-29 14:17 UTC
Labels: bug/0-needs-info, kind/bug, team/client, topic: basic error report

**Comment by mostafa7904** [comment] 2021-08-13 09:13
Hi again.
I'm getting errors in **local** on my own PC now. There are no issues in production.

```bash
(node:5568) UnhandledPromiseRejectionWarning: 
Error: {"is_panic":false,"message":"Can't modify an already connected engine.","backtrace":"   0: napi_register_module_v1\n  
 1: napi_register_module_v1\n   2: napi_register_module_v1\n   3: <unknown>\n   4: <unknown>\n   5: <unknown>\n   6: <unknown>\n   7: <unknown>\n   8: <unknown>\n   9: napi_register_module_v1\n  10: napi_register_module_v1\n  11: napi_register_module_v1\n  12: napi_register_module_v1\n  13: napi_register_module_v1\n  14: napi_register_module_v1\n  15: napi_register_module_v1\n  16: napi_register_module_v1\n  17: napi_register_module_v1\n  18: napi_register_module_v1\n  19: napi_register_module_v1\n  20: BaseThreadInitThunk\n  21: RtlUserThreadStart\n"}
```

I'm using nodemon and when I stop it and start it immediately this error happens. It finally goes away after a few nodemon restarts. Note: This doesn't happen in normal nodemon updates, it only happens when I completely restart nodemon.

I've also **changed my database from MySQL to PostgreSQL**. Everything else is still the same. just added nApi and postgress.

**Comment by janpio** [comment] 2021-08-13 09:59
Can you maybe open a new issue about this and provide all the information it asks for? Optimal would be some code for us to easily reproduce the error. Assume we don't know much about how to use nodemon or how it works. Super eager to look into this!
