### ISSUE TITLE
@@map not working on postgress enums starting version 4.6.0

### ISSUE THREAD

**Issue by Siegrift** [prisma/prisma#16209] opened 2022-11-09 20:34 UTC
### Bug description

The latest `prisma@4.6.0` stops recognizing `@@map` expressions on enums, while `prisma@4.5.0` does.

### How to reproduce

This is my `schema.prisma` file:
```prisma
datasource db {
  url      = "postgresql://postgres:password@localhost:5432/postgres"
  provider = "postgresql"
}

generator client {
  provider = "prisma-client-js"
}

model Table {
  id    String @id
  field MyEnum

  @@map("table")
}

enum MyEnum {
  A
  B

  @@map("my_enum")
}
```

When I create a migration with `prisma@4.6.0` using `npx prisma migrate dev --name initial --create-only`  I get the following:
```sql
-- CreateEnum
CREATE TYPE "MyEnum" AS ENUM ('A', 'B');

-- CreateTable
CREATE TABLE "table" (
    "id" TEXT NOT NULL,
    "field" "MyEnum" NOT NULL,

    CONSTRAINT "table_pkey" PRIMARY KEY ("id")
);
``` 

When I create a migration with `prisma@4.5.0` using `npx prisma migrate dev --name initial --create-only` I get the following:
```sql
-- CreateEnum
CREATE TYPE "my_enum" AS ENUM ('A', 'B');

-- CreateTable
CREATE TABLE "table" (
    "id" TEXT NOT NULL,
    "field" "my_enum" NOT NULL,

    CONSTRAINT "table_pkey" PRIMARY KEY ("id")
);
```

### Expected behavior

The same migration as with version 4.5.0.

### Prisma information

already shared.

### Environment & setup

- OS: macOS
- Database: PostgreSQL
- Node.js version: 18.12.1

### Prisma Version

```
4.6.0
```

**Comment by alexisbellido** [comment] 2022-11-09 22:20
Could this be related to https://github.com/prisma/prisma/issues/16180 ?

**Comment by SevInf** [comment] 2022-11-10 09:54
Confirmed as duplicate of #16180.
I am going to close this issue, you can follow the progress in #16180. Patch version with a fix would be published later today.

**Closed by SevInf** 2022-11-10 09:54 UTC
Labels: bug/2-confirmed, kind/bug, team/schema, topic: enums
