### ISSUE TITLE
External error with reported id was not registered

### ISSUE THREAD

**Issue by mrenoyou** [prisma/prisma#21787] opened 2023-11-06 09:39 UTC
### Bug description

```
---> An error occurred while adding employee /addEmployee: External error with reported id was not registered. This should never happen. If you see this error, please, open an issue at https://github.com/prisma/prisma/issues/new?assignees=&labels=kind%2Fbug&projects=&template=bug_report.yml 

Error: External error with reported id was not registered. This should never happen. If you see this error, please, open an issue at https://github.com/prisma/prisma/issues/new?assignees=&labels=kind%2Fbug&projects=&template=bug_report.yml
    at _r (/Users/myousuf/Projects/iimleic-prod/node_modules/@prisma/client/runtime/library.js:26:712)
    at mr.buildQueryError (/Users/myousuf/Projects/iimleic-prod/node_modules/@prisma/client/runtime/library.js:115:1142)
    at mr.request (/Users/myousuf/Projects/iimleic-prod/node_modules/@prisma/client/runtime/library.js:114:4091)
    at async Object.singleLoader (/Users/myousuf/Projects/iimleic-prod/node_modules/@prisma/client/runtime/library.js:123:5333)
    at async Cn.request (/Users/myousuf/Projects/iimleic-prod/node_modules/@prisma/client/runtime/library.js:123:5825)
    at async l (/Users/myousuf/Projects/iimleic-prod/node_modules/@prisma/client/runtime/library.js:128:9968)
    at async Promise.all (index 141)
    at async handler (webpack-internal:///(api)/./pages/api/hr/addEmployee.js:106:9)
    at async Object.apiResolver (/Users/myousuf/Projects/iimleic-prod/node_modules/next/dist/server/api-utils/node.js:372:9)
    at async DevServer.runApi (/Users/myousuf/Projects/iimleic-prod/node_modules/next/dist/server/next-server.js:514:9)
    at async Object.fn (/Users/myousuf/Projects/iimleic-prod/node_modules/next/dist/server/next-server.js:828:35)
    at async Router.execute (/Users/myousuf/Projects/iimleic-prod/node_modules/next/dist/server/router.js:243:32)
    at async DevServer.runImpl (/Users/myousuf/Projects/iimleic-prod/node_modules/next/dist/server/base-server.js:432:29)
    at async DevServer.run (/Users/myousuf/Projects/iimleic-prod/node_modules/next/dist/server/dev/next-dev-server.js:831:20)
    at async DevServer.handleRequestImpl (/Users/myousuf/Projects/iimleic-prod/node_modules/next/dist/server/base-server.js:375:20)
    at async /Users/myousuf/Projects/iimleic-prod/node_modules/next/dist/server/base-server.js:157:99 {
  clientVersion: '5.5.2'
}
```

### Expected behavior

should add the employee

### Prisma information
    
```prisma
model staffmain {
  id                                    Int            @id @unique
  employeeId                            String         @unique
  status                                staffStatus    @default(active)
  title                                 String?
  firstName                             String
  middleName                            String?
  lastName                              String
  gender                                studentGender?
  isPermanent                           Boolean?       @default(true)
  reportingManagerId                    Int?
  reportingManager                      staffmain?     @relation("reportingManager", fields: [reportingManagerId], references: [id], onDelete: NoAction, onUpdate: NoAction)
  directReports                         staffmain[]    @relation("reportingManager")
  departmentName                        String
  subDepartmentName                     String
  designation                           String?
  schoolId                              Int?
  employeeType                          employeeType
  religion                              religion?
  caste                                 caste?
  minority                              Boolean?
  differentlyAbled                      Boolean?
  dateOfBirth                           String?
  panNumber                             String?        @db.Text
  aadharNumber                          String?        @db.Text
  profilePic                            String?        @db.Text
  contactPhone                          String         @unique
  contactEmail                          String         @unique
  alternateContactPhone                 String?        @unique
  contactWhatsapp                       String?
  fatherName                            String?        @db.Text
  fatherNumber                          String?        @db.Text
  motherName                            String?        @db.Text
  motherNumber                          String?        @db.Text
  maritalStatus                         maritalStatus  @default(Single)
  spouseName                            String?
  spuseNumber                           String?
  noOfChildren                          Int?
  noOfSiblings                          Int?
  childrenName                          String?
  address_line1                         String?
  address_line2                         String?
  address_line3                         String?
  city                                  String?
  pincode                               Int?
  district                              String?
  state                                 String?
  country                               String?        @default("India")
  emergencyContactName                  String?        @db.Text
  emergencyContactNumber                String?        @db.Text
  bloodGroup                            bloodGroup?
  nrtsNumber                            String?        @db.Text
  sameAsCurrent                         Boolean?
  permanentAddressLine1                 String?        @db.Text
  permanentAddressLine2                 String?        @db.Text
  permanentAddressLine3                 String?        @db.Text
  permanentCity                         String?        @db.Text
  permanentDistrict                     String?        @db.Text
  permanentPincode                      Int?
  permanentState                        String?        @db.Text
  registrationNumber                    String?
  cca_sports                            String?
  cca_NSS                               Boolean?
  cca_NCC                               Boolean?
  cca_others                            String?
  cca_workProfile                       String?
  cca_designation                       String?
  cca_department                        String?
  cca_school                            String?
  salary_fixedScale                     String?
  salary_compositeScale                 String?
  salary_consolidated                   String?
  salary_pf                             String?
  salary_bankName                       String?
  salary_bankAccountNumber              String?
  salary_bankIFSC                       String?
  salary_ESI                            String?
  dateOfJoining                         String?
  dateOfLeaving                         String?        @db.Text
  leavingReason                         String?        @db.Text
  grossSalary                           String?        @db.Text
  onScale                               String?        @db.Text
  consolidated                          String?        @db.Text
  postDoc                               Boolean?
  postDoc_university                    String?
  postDoc_specialization                String?
  phD                                   String?
  University                            String?
  phdYear                               String?
  isFullTime                            Boolean?
  areaOfSpecialization                  String?
  pgDegree                              Boolean?
  pgDegree_nameOfDegree                 String?
  pgDegree_course                       String?
  pgDegree_university                   String?
  pgDegree_year                         String?
  pgDegree_marks                        String?
  pgDegree_wasFullTime                  Boolean?
  pgDegree_rank                         String?
  graduationDegree_nameOfDegree         String?
  graduationDegree_course               String?
  graduationDegree_university           String?
  graduationDegree_year                 String?
  graduationDegree_marks                String?
  graduationDegree_wasFullTime          Boolean?
  graduationDegree_rank                 String?
  class12                               String?
  xii_nameOfDegree                      String?
  xii_board                             String?
  xii_school                            String?
  xii_year                              String?
  xii_marks                             String?
  xii_rank                              String?
  class10                               String?
  x_nameOfDegree                        String?
  x_board                               String?
  x_school                              String?
  x_year                                String?
  x_marks                               String?
  x_rank                                String?
  competitiveExams                      String?
  otherExams                            String?
  net                                   Boolean?
  netYear                               String?
  slet                                  Boolean?
  sletYear                              String?
  gate                                  Boolean?
  gateYear                              String?
  set                                   Boolean?
  setYear                               String?
  pgDegree_collegeName                  String?        @db.Text
  graduationDegree_collegeName          String?        @db.Text
  teachingExp                           Int?
  researchExp                           Int?
  industryExp                           Int?
  totalWorkExp                          Int?
  detailsWorkExp                        String?
  incNumber                             String?
  pciNumber                             String?
  coaNumber                             String?
  nationalJournals                      String?        @db.Text
  internationalJournals                 String?        @db.Text
  papersPresentedNationalConference     String?        @db.Text
  apersPresentedInternationalConference String?        @db.Text
  bookChaptersContributed               String?        @db.Text
  booksEdited                           String?        @db.Text
  booksAuthored                         String?        @db.Text
  patentsApplied                        String?        @db.Text
  patentsPublished                      String?        @db.Text
  patentsAwarded                        String?        @db.Text
  patentsCommercialized                 String?        @db.Text
  transferTechnology                    String?        @db.Text
  createdAt                             String?
  createdBy                             String?
  updatedAt                             String?        @db.Text
  updatedBy                             String?        @db.Text
  jrfEligibility                        Boolean?
  lecturshipEligibility                 Boolean?
  mediclaimNo                           String?
  pTaxApplicable                        Boolean?       @default(true)
  //salary stuff
  basicPay                              Int?
  grossPay                              Int?
  hra                                   Float?
  da                                    Float?
  hraClaimed                            Boolean?       @default(true)
  transportAvailed                      Boolean?       @default(false)
  securityDepositInstallment            Int?           @default(0)
  securityDepositCollected              Int?           @default(0)
  securityDepositMonthsRemaining        Int?           @default(0)

  npsYearToDate          Float?            @default(0)
  npsTillLastYear        Float?            @default(0)
  //leaves
  casualLeaveBalance     Float?            @default(0)
  medicalLeaveBalance    Float?            @default(0)
  earnedLeaveBalance     Float?            @default(0)
  specialLeaveBalance    Float?            @default(0)
  maternityLeaveBalance  Float?            @default(0)
  paternityLeaveBalance  Float?            @default(0)
  sabbaticalLeaveBalance Float?            @default(0)
  otherLeaveBalance      Float?            @default(0)
  workFromHomeBalance    Float?            @default(1000)
  onDutyBalance          Float?            @default(1000)
  //approvals
  level1ApproverId       Int?
  level2ApproverId       Int?
  level3ApproverId       Int?
  level4ApproverId       Int?
  level1Approver         staffmain?        @relation("level1Approver", fields: [level1ApproverId], references: [id], onDelete: NoAction, onUpdate: NoAction)
  level2Approver         staffmain?        @relation("level2Approver", fields: [level2ApproverId], references: [id], onDelete: NoAction, onUpdate: NoAction)
  level3Approver         staffmain?        @relation("level3Approver", fields: [level3ApproverId], references: [id], onDelete: NoAction, onUpdate: NoAction)
  level4Approver         staffmain?        @relation("level4Approver", fields: [level4ApproverId], references: [id], onDelete: NoAction, onUpdate: NoAction)
  level1Report           staffmain[]       @relation("level1Approver")
  level2Report           staffmain[]       @relation("level2Approver")
  level3Report           staffmain[]       @relation("level3Approver")
  level4Report           staffmain[]       @relation("level4Approver")
  substitutions          Leave[]           @relation("substitute")
  //relations
  courses                course[]
  subjects               subject[]
  department             department        @relation(fields: [departmentName], references: [name])
  subDepartment          subDepartment?    @relation(fields: [subDepartmentName], references: [name])
  staffAttendance        staffAttendance[]
  salaryDetails          SalaryDetail[]
  lop                    lop[]
  school                 school?           @relation(fields: [schoolId], references: [schoolId])

  paySlip         paySlip[]
  holidayCalender holidayCalender[]
  leaves          Leave[]
  finalAttendance finalAttendance[]
  issuedLogs      itemLog[]         @relation("IssuedLogs")
  receivedLogs    itemLog[]         @relation("ReceivedLogs")
  createdItems    item[]

  acceptedTerms Boolean? @default(false)

  @@index([departmentName])
  @@index([subDepartmentName])
  @@index([schoolId])
  @@index([reportingManagerId])
  @@index([level1ApproverId])
  @@index([level2ApproverId])
  @@index([level3ApproverId])
  @@index([level4ApproverId])
}
```

### Environment & setup

- OS: 
- Database: 
- Node.js version: 

### Prisma Version

```

```
    "@prisma/adapter-planetscale": "^5.5.2",
    "@prisma/client": "^5.5.2",

**Comment by janpio** [comment] 2023-11-06 09:55
(Error text comes from Library Engine: https://github.com/prisma/prisma/blob/52b2332d7a4532da5bd077e0e632bddb4720d423/packages/client/src/runtime/core/engines/library/LibraryEngine.ts#L565)

**Comment by SevInf** [comment] 2023-11-06 10:29
@mrenoyou could you please provide the exact code snippet you are trying to execute? We are Prisma developers, not your coworkers, empty "how to reproduce" and "should add the employee" as expected behavior does not help us with reproducing or fixing the issue.
Thank you!

**Comment by SevInf** [comment] 2024-01-15 09:30
Hey @mrenoyou  ,

Did you get a chance to have a look at my previous comment? It'd be helpful for us to move your issue forward.

Without further information, we'll have to close this issue. Thank you 🙏

**Comment by aqrln** [comment] 2024-02-02 20:03
Hi @mrenoyou,

Since we couldn't reach out to you to get the information required for reproduction and investigation, we unfortunately have to close this issue at this time. Please open a new issue with more details if you are still facing this problem.

**Closed by aqrln** 2024-02-02 20:03 UTC
Labels: bug/0-unknown, kind/bug, team/client, topic: database-provider/planetscale, topic: query-crash, topic: driverAdapters
