### ISSUE TITLE
 The edge runtime does not support Node.js 'crypto' module. - when trying to use `@prisma/adapter-pg` in Next.js middleware

### ISSUE THREAD

**Issue by liuhuapiaoyuan** [prisma/prisma#24386] opened 2024-06-02 11:44 UTC
### Bug description

Why does a qualified error occur again in `nextjs`'s `middleware`?

### How to reproduce

```

generator client {
  provider = "prisma-client-js"
  previewFeatures = ["driverAdapters"]

} 
datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
} 
```

### Expected behavior

Why did it go wrong when I wrote it completely according to the demo code?

### Prisma information

```prisma
 
generator client {
  provider = "prisma-client-js"
  previewFeatures = ["driverAdapters"]

} 
datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
} 
model User {
  id            String          @id @default(cuid())
  name          String?
  email         String          @unique
  emailVerified DateTime?
  image         String?
  accounts      Account[]
  sessions      Session[]
  // Optional for WebAuthn support
  Authenticator Authenticator[]
 
  createdAt DateTime @default(now())
  updatedAt DateTime @updatedAt
}
```

```ts
import { PrismaPg } from '@prisma/adapter-pg';
import { PrismaClient } from "@prisma/client";
import { Pool } from 'pg';

const connectionString = `${process.env.DATABASE_URL}`

const prismaClientSingleton = () => {
    const pool = new Pool({ connectionString })
    const adapter = new PrismaPg(pool)
    return new PrismaClient({ adapter })
};

type PrismaClientSingleton = ReturnType<typeof prismaClientSingleton>;

const globalForPrisma = globalThis as unknown as {
  prisma: PrismaClientSingleton | undefined;
};

const prisma = globalForPrisma.prisma ?? prismaClientSingleton();

export default prisma;

if (process.env.NODE_ENV !== "production") globalForPrisma.prisma = prisma;

```

### Environment & setup

- OS:  windows
- Database:  PostgreSQL
- Node.js version: v19.0.0

### Prisma Version

```
prisma                  : 5.14.0
@prisma/client          : 5.14.0
Computed binaryTarget   : windows
Operating System        : win32
Architecture            : x64
Node.js                 : v19.0.0
Query Engine (Node-API) : libquery-engine e9771e62de70f79a5e1c604a2d7c8e2a0a874b48 (at node_modules\.pnpm\@prisma+engines@5.14.0\node_modules\@prisma\engines\query_engine-windows.dll.node)       
Schema Engine           : schema-engine-cli e9771e62de70f79a5e1c604a2d7c8e2a0a874b48 (at node_modules\.pnpm\@prisma+engines@5.14.0\node_modules\@prisma\engines\schema-engine-windows.exe)
Schema Wasm             : @prisma/prisma-schema-wasm 5.14.0-25.e9771e62de70f79a5e1c604a2d7c8e2a0a874b48
Default Engines Hash    : e9771e62de70f79a5e1c604a2d7c8e2a0a874b48
Studio                  : 0.500.0
Preview Features        : driverAdapters
```

**Comment by janpio** [comment] 2024-06-03 09:40
Can you share a reproduction project of the problem you are describing, please?

**Comment by janpio** [comment] 2024-06-05 10:26
@liuhuapiaoyuan Are you using this in a Next.js context? If so, can you share the version and setup of your project please? Thanks.

**Comment by liuhuapiaoyuan** [comment] 2024-06-06 05:56
只是再`middleware`中使用`adapter`就会出现这个错误！

**Comment by janpio** [comment] 2024-06-06 07:17
This is the same problem as described here: https://github.com/prisma/prisma/issues/24430#issuecomment-2149505070

Unfortunately it seems that the pg database driver is not compatible with the Next.js middlewares.
Here is an issue for that in the `pg` repository: https://github.com/brianc/node-postgres/issues/3206

**Comment by janpio** [comment] 2024-06-06 17:13
Closing this as a duplicate of https://github.com/prisma/prisma/issues/24430 - latest update in https://github.com/prisma/prisma/issues/24430#issuecomment-2153025329

**Closed by janpio** 2024-06-06 17:13 UTC
Labels: bug/2-confirmed, kind/bug, topic: Next.js, team/client, topic: Next.js middleware, topic: driverAdapters, status/blocked-by-dependency, topic: @prisma/adapter-pg
