### ISSUE TITLE
Explicit many-to-many relations and the `update()` has error

### ISSUE THREAD

**Issue by shanliangdeYWJ** [prisma/prisma#22753] opened 2024-01-22 17:37 UTC
### Bug description

I use Prisma to create rbac permission management in the MySQL database

```prisma/schema.prisma
model User {
  id    Int        @id @default(autoincrement())
  email String     @unique
  name  String?
  roles UserRole[]
  // roles Role[]

  @@map("user")
}

model Role {
  id       Int        @id @default(autoincrement())
  roleName String     @unique
  users    UserRole[]
  menus    RoleMenu[]
  // users User[]
  // menus Menu[]

  @@map("role")
}

model Menu {
  id       Int        @id @default(autoincrement())
  menuName String     @unique
  roles    RoleMenu[]
  // roles Role[]

  @@map("menu")
}

model UserRole {
  id     Int   @id @default(autoincrement())
  roleId Int   @map("role_id")
  userId Int   @map("user_id")
  user   User? @relation(fields: [userId], references: [id])
  role   Role? @relation(fields: [roleId], references: [id])

  @@index([userId])
  @@index([roleId])
  @@map("user_role")
}

model RoleMenu {
  id     Int  @id @default(autoincrement())
  roleId Int  @map("role_id")
  menuId Int  @map("menu_id")
  menu   Menu @relation(fields: [menuId], references: [id])
  role   Role @relation(fields: [roleId], references: [id])

  @@index([menuId])
  @@index([roleId])
  @@map("role_menu")
}
```

I need to assign roles to users
How should I write code? 
The following code will report an error

```bash
54 // const connect = roles.filter(role => role.id > 2)
  55 // const disconnect = roles.filter(role => role.id < 3)
  56 
→ 57 await prisma.user.update(
The required connected records were not found. Expected 1 records to be connected after connect operation on one-to-many relation 'UserToUserRole', found 0.
```

```javascript
 const users = await prisma.user.createMany({
    data: [
      { name: 'Alice', email: 'alice@prisma.io', },
      { name: 'Bob', email: 'bob@prisma.io', },
      { name: 'Boby', email: 'boby@prisma.io', },
    ],
  })
  
  const roles = await prisma.role.createMany({
    data: [
      { roleName: 'admin' },
      { roleName: 'editor' },
      { roleName: 'user' },
    ]
  })
 //  This does not support where: {name:'xxxx '}, I must use where: {id: number}
  await prisma.user.update({
    where: { id: 3 },
    data: {
      roles: {
        connect: [{ id: 1 }],
        disconnect: [{ id: 2 }, { id: 3 }],
      },
    },
    include: {
      roles: true,
    },
  })
```
I do not want to use implicit many-to-many relations, I couldn't find a solution in the issue, How should this be written?

### Expected behavior

Based on the queried users and existing roles in the database, after such writing, their respective IDs will be inserted into the middle table and unwanted IDs will be deleted. If set is used, the database will only retain the passed in ids

Previously, I used sequence, so I just needed to make associations and set roles for the queried users. The semantics are very easy to understand.

```javascript
    const role = await Role.findOne({
      where: { username: 'xxxx' },
      attributes: ['id', 'roleName']
    })
    const setMenus = await Menu.findAll({
      where: { id: [1, 2, 3, 4, 100, 101,] },
    })

    await role && role.setMenus(setMenus)
```
My friend recommended Prisma to me and he said it was very useful, so I came to try it out. However, it has been a day and I haven't found the way to write it. Even in official document, there is no clear case of encountering this

### Prisma information

```prisma
// Add your schema.prisma
```

```ts
// Add your code using Prisma Client
```

### Environment & setup

- OS: 
- Database: 
- Node.js version: 

### Prisma Version

```

```

**Comment by Druue** [comment] 2024-06-10 12:03
Hey @shanliangdeYWJ!

A couple things:
Prisma only supports `where` clauses without a unique key in `updateMany` calls, i.e.
```prisma
model User {
  id    Int        @id @default(autoincrement())
  email String     @unique
  name  String?
  roles UserRole[]

  @@map("user")
}
```
```ts
await prisma.user.update({
  where: { id: 3 },               // Works
  where: { id: 3, name: "name" }, // Works
  where: { name: "name" },        // Does not work
  ..
})

await prisma.user.updateMany({
  where: { name: "name" },       // Works
  ..
})
```

Prisma does not yet support updating relations in `updateMany` calls yet either. You can track the feature request [here](https://github.com/prisma/prisma/issues/3143)

Currently you would need to either connect roles on the individual [creation of users](https://www.prisma.io/docs/orm/prisma-client/queries/relation-queries#update-or-create-a-related-record), or via an [update](https://www.prisma.io/docs/orm/prisma-client/queries/relation-queries#update-or-create-a-related-record), after they've been created

Example:
```ts
await prisma.user.create({
    data: {
      email,
      name,
      roles: {
        // Note the extra layer of create here as it's creating the entry in _UserRole_
        // which then connects to a specific role
        create: [{ role: { connect: { id: 1 } } }],
      },
    },
    include: { roles: true },
  });
```

---

It doesn't seem to me that what you encounter is actually a bug and is just the difference between Prisma's implicit and explicit m2m api

Is there a specific reason that you're looking to use explicit m2m relations instead of implicit and does the above clarify things for you?

---

If you were otherwise using _implicit_ m2m relations, you would not need the extra layer of indirection:
```ts
await prisma.user.create({
    data: {
      email,
      name,
      roles: {
        connect: [{ id: 1 }],
      },
    },
    include: { roles: true },
  });
```

Which would then let you do something along the lines of:
```ts
const users: userData[] = [
    { name: "Alice", email: "alice@prisma.io", userRoles: ["admin"] },
    { name: "Bob", email: "bob@prisma.io", userRoles: ["editor"] },
    { name: "Boby", email: "boby@prisma.io", userRoles: ["user"] },
  ];

await Promise.all(
    users.map(async ({ name, email, userRoles }) => {
      const filteredRoles = roles
        .filter((role) => userRoles.includes(role.roleName))
        .map((role) => ({ id: role.id }));

      console.log(filteredRoles);

      await prisma.user.create({
        data: {
          email,
          name,
          roles: {
            connect: filteredRoles,
          },
        },
        include: { roles: true },
      });
    })
  );
```

**Comment by shanliangdeYWJ** [comment] 2024-06-11 03:54
> 嘿@shanliangdeYWJ！
> 
> 有几件事： Prisma 仅支持在调用`where`中没有唯一键的子句，即`updateMany`
> 
> ```prisma
> model User {
>   id    Int        @id @default(autoincrement())
>   email String     @unique
>   name  String?
>   roles UserRole[]
> 
>   @@map("user")
> }
> ```
> 
> ```ts
> await prisma.user.update({
>   where: { id: 3 },               // Works
>   where: { id: 3, name: "name" }, // Works
>   where: { name: "name" },        // Does not work
>   ..
> })
> 
> await prisma.user.updateMany({
>   where: { name: "name" },       // Works
>   ..
> })
> ```
> 
> Prisma 还不支持在调用中更新关系。你可以[在此处](https://github.com/prisma/prisma/issues/3143)`updateMany`跟踪功能请求[](https://github.com/prisma/prisma/issues/3143)
> 
> 目前，您需要在单独[创建用户](https://www.prisma.io/docs/orm/prisma-client/queries/relation-queries#update-or-create-a-related-record)时连接角色，或者在创建用户后通过[更新来连接角色](https://www.prisma.io/docs/orm/prisma-client/queries/relation-queries#update-or-create-a-related-record)
> 
> 例子：
> 
> ```ts
> await prisma.user.create({
>     data: {
>       email,
>       name,
>       roles: {
>         // Note the extra layer of create here as it's creating the entry in _UserRole_
>         // which then connects to a specific role
>         create: [{ role: { connect: { id: 1 } } }],
>       },
>     },
>     include: { roles: true },
>   });
> ```
> 
> 在我看来，你遇到的实际上不是一个错误，而只是 Prisma 的隐式和显式 m2m api 之间的差异
> 
> 您希望使用显式 m2m 关系而不是隐式关系是否有特定原因，上述内容是否为您澄清了这一点？
> 
> 如果您使用_隐式_m2m 关系，则不需要额外的间接层：
> 
> ```ts
> await prisma.user.create({
>     data: {
>       email,
>       name,
>       roles: {
>         connect: [{ id: 1 }],
>       },
>     },
>     include: { roles: true },
>   });
> ```
> 
> 然后你就可以做类似的事情了：
> 
> ```ts
> const users: userData[] = [
>     { name: "Alice", email: "alice@prisma.io", userRoles: ["admin"] },
>     { name: "Bob", email: "bob@prisma.io", userRoles: ["editor"] },
>     { name: "Boby", email: "boby@prisma.io", userRoles: ["user"] },
>   ];
> 
> await Promise.all(
>     users.map(async ({ name, email, userRoles }) => {
>       const filteredRoles = roles
>         .filter((role) => userRoles.includes(role.roleName))
>         .map((role) => ({ id: role.id }));
> 
>       console.log(filteredRoles);
> 
>       await prisma.user.create({
>         data: {
>           email,
>           name,
>           roles: {
>             connect: filteredRoles,
>           },
>         },
>         include: { roles: true },
>       });
>     })
>   );
> ```

Implicit many to many cannot customize table names. Many old projects have issues with using Prisma implicit connections. In addition, displaying many to many requires additional nested intermediate table queries, resulting in an extra layer of returned results. We hope to optimize this

**Comment by shanliangdeYWJ** [comment] 2024-06-11 03:56
> Hey @shanliangdeYWJ!
> 
> A couple things: Prisma only supports `where` clauses without a unique key in `updateMany` calls, i.e.
> 
> ```prisma
> model User {
>   id    Int        @id @default(autoincrement())
>   email String     @unique
>   name  String?
>   roles UserRole[]
> 
>   @@map("user")
> }
> ```
> 
> ```ts
> await prisma.user.update({
>   where: { id: 3 },               // Works
>   where: { id: 3, name: "name" }, // Works
>   where: { name: "name" },        // Does not work
>   ..
> })
> 
> await prisma.user.updateMany({
>   where: { name: "name" },       // Works
>   ..
> })
> ```
> 
> Prisma does not yet support updating relations in `updateMany` calls yet either. You can track the feature request [here](https://github.com/prisma/prisma/issues/3143)
> 
> Currently you would need to either connect roles on the individual [creation of users](https://www.prisma.io/docs/orm/prisma-client/queries/relation-queries#update-or-create-a-related-record), or via an [update](https://www.prisma.io/docs/orm/prisma-client/queries/relation-queries#update-or-create-a-related-record), after they've been created
> 
> Example:
> 
> ```ts
> await prisma.user.create({
>     data: {
>       email,
>       name,
>       roles: {
>         // Note the extra layer of create here as it's creating the entry in _UserRole_
>         // which then connects to a specific role
>         create: [{ role: { connect: { id: 1 } } }],
>       },
>     },
>     include: { roles: true },
>   });
> ```
> 
> It doesn't seem to me that what you encounter is actually a bug and is just the difference between Prisma's implicit and explicit m2m api
> 
> Is there a specific reason that you're looking to use explicit m2m relations instead of implicit and does the above clarify things for you?
> 
> If you were otherwise using _implicit_ m2m relations, you would not need the extra layer of indirection:
> 
> ```ts
> await prisma.user.create({
>     data: {
>       email,
>       name,
>       roles: {
>         connect: [{ id: 1 }],
>       },
>     },
>     include: { roles: true },
>   });
> ```
> 
> Which would then let you do something along the lines of:
> 
> ```ts
> const users: userData[] = [
>     { name: "Alice", email: "alice@prisma.io", userRoles: ["admin"] },
>     { name: "Bob", email: "bob@prisma.io", userRoles: ["editor"] },
>     { name: "Boby", email: "boby@prisma.io", userRoles: ["user"] },
>   ];
> 
> await Promise.all(
>     users.map(async ({ name, email, userRoles }) => {
>       const filteredRoles = roles
>         .filter((role) => userRoles.includes(role.roleName))
>         .map((role) => ({ id: role.id }));
> 
>       console.log(filteredRoles);
> 
>       await prisma.user.create({
>         data: {
>           email,
>           name,
>           roles: {
>             connect: filteredRoles,
>           },
>         },
>         include: { roles: true },
>       });
>     })
>   );
> ```

Implicit many to many cannot customize table names. Many old projects have issues with using Prisma implicit connections. In addition, displaying many to many requires additional nested intermediate table queries, resulting in an extra layer of returned results. We hope to optimize this

**Comment by SevInf** [comment] 2024-06-12 13:18
@shanliangdeYWJ `update` requires unique field because `update`'s contract is updating one an only one record at a time.

As far as we concerned, this is not a bug.
We have two feature requests that might be interesting to you. First, as my co-worker mentioned, solution to your problem might be `updateMany` supporting nesting updates. You can track this request [here](https://github.com/prisma/prisma/issues/5088).

Another option is some kind of `updateFirst` method that will not require unique constraint, but will provide less strict guarantees. This feature request you can track [here](https://github.com/prisma/prisma/issues/4349).

We are not going to change `update` behavior, so I am going to close this issue. Please, follow any of the two issues I linked instead.

**Closed by SevInf** 2024-06-12 13:18 UTC
Labels: bug/1-unconfirmed, kind/bug, topic: mysql, domain/client, topic: m:n, topic: update()
