### ISSUE TITLE
`generate` does not work in folders with spaces

### ISSUE THREAD

**Issue by janpio** [prisma/prisma#1973] opened 2020-03-27 23:15 UTC
```
C:\Users\Jan\Downloads\prisma chinook master cli-demo>npx prisma2 generate
'C:\Users\Jan\Downloads\prisma' is not recognized as an internal or external command,
operable program or batch file.
Error: Cannot call write after a stream was destroyed
```

with `DEBUG=*` set:

```
C:\Users\Jan\Downloads\prisma chinook master cli-demo>set DEBUG=*

C:\Users\Jan\Downloads\prisma chinook master cli-demo>npx prisma2 generate
  prisma .env loaded from ./prisma/.env +0ms
  getos { platform: 'win32', libssl: undefined } +0ms
  download Getting version of C:\Users\Jan\Downloads\prisma chinook master cli-demo\node_modules\@prisma\cli\query-engine-windows.exe. Result:  {
  command: 'C:\\Users\\Jan\\Downloads\\prisma chinook master cli-demo\\node_modules\\@prisma\\cli\\query-engine-windows.exe --version',
  exitCode: 0,
  stdout: 'prisma d35b3d764e66598164f3b8ce821d452b09d4a613',
  stderr: '',
  all: undefined,
  failed: false,
  timedOut: false,
  isCanceled: false,
  killed: false
} +0ms
  download Getting version of C:\Users\Jan\Downloads\prisma chinook master cli-demo\node_modules\@prisma\cli\query-engine-windows.exe. Result:  prisma d35b3d764e66598164f3b8ce821d452b09d4a613 +3ms
  download { works: true } +0ms
  download { needsToBeDownloaded: false } +1ms
  download Getting version of C:\Users\Jan\Downloads\prisma chinook master cli-demo\node_modules\@prisma\cli\migration-engine-windows.exe. Result:  {
  command: 'C:\\Users\\Jan\\Downloads\\prisma chinook master cli-demo\\node_modules\\@prisma\\cli\\migration-engine-windows.exe --version',
  exitCode: 0,
  stdout: 'migration-engine-cli d35b3d764e66598164f3b8ce821d452b09d4a613',
  stderr: '',
  all: undefined,
  failed: false,
  timedOut: false,
  isCanceled: false,
  killed: false
} +8ms
  download Getting version of C:\Users\Jan\Downloads\prisma chinook master cli-demo\node_modules\@prisma\cli\migration-engine-windows.exe. Result:  migration-engine-cli d35b3d764e66598164f3b8ce821d452b09d4a613 +15ms
  download { works: true } +2ms
  download { needsToBeDownloaded: false } +0ms
  download Getting version of C:\Users\Jan\Downloads\prisma chinook master cli-demo\node_modules\@prisma\cli\introspection-engine-windows.exe. Result:  {
  command: 'C:\\Users\\Jan\\Downloads\\prisma chinook master cli-demo\\node_modules\\@prisma\\cli\\introspection-engine-windows.exe --version',
  exitCode: 0,
  stdout: 'introspection-core d35b3d764e66598164f3b8ce821d452b09d4a613',
  stderr: '',
  all: undefined,
  failed: false,
  timedOut: false,
  isCanceled: false,
  killed: false
} +2ms
  download Getting version of C:\Users\Jan\Downloads\prisma chinook master cli-demo\node_modules\@prisma\cli\introspection-engine-windows.exe. Result:  introspection-core d35b3d764e66598164f3b8ce821d452b09d4a613 +2ms
  download { works: true } +0ms
  download { needsToBeDownloaded: false } +0ms
  getos { platform: 'win32', libssl: undefined } +128ms
  getos { platform: 'win32', libssl: undefined } +19ms
  download Getting version of C:\Users\Jan\Downloads\prisma chinook master cli-demo\node_modules\@prisma\cli\query-engine-windows.exe. Result:  {
  command: 'C:\\Users\\Jan\\Downloads\\prisma chinook master cli-demo\\node_modules\\@prisma\\cli\\query-engine-windows.exe --version',
  exitCode: 0,
  stdout: 'prisma d35b3d764e66598164f3b8ce821d452b09d4a613',
  stderr: '',
  all: undefined,
  failed: false,
  timedOut: false,
  isCanceled: false,
  killed: false
} +75ms
  download Getting version of C:\Users\Jan\Downloads\prisma chinook master cli-demo\node_modules\@prisma\cli\query-engine-windows.exe. Result:  prisma d35b3d764e66598164f3b8ce821d452b09d4a613 +5ms
  download { works: true } +1ms
  download { needsToBeDownloaded: false } +0ms
  getGenerators {
  getGenerators   binaryPathsWithEngineType: {
  getGenerators     'query-engine': {
  getGenerators       windows: 'C:\\Users\\Jan\\Downloads\\prisma chinook master cli-demo\\node_modules\\@prisma\\cli\\query-engine-windows.exe'
  getGenerators     }
  getGenerators   }
  getGenerators } +0ms
  engineCommands getDMMF, override prismaPath = C:\Users\Jan\Downloads\prisma chinook master cli-demo\node_modules\@prisma\cli\query-engine-windows.exe +0ms
  engineCommands getConfig, override prismaPath = C:\Users\Jan\Downloads\prisma chinook master cli-demo\node_modules\@prisma\cli\query-engine-windows.exe +97ms
  getos { platform: 'win32', libssl: undefined } +242ms
{
  prismaClientDir: 'C:\\Users\\Jan\\Downloads\\prisma chinook master cli-demo\\node_modules\\@prisma\\client'
}
  getGenerators {
  getGenerators   outputPath: 'C:\\Users\\Jan\\Downloads\\prisma chinook master cli-demo\\node_modules\\@prisma\\client',
  getGenerators   generatorPath: 'C:\\Users\\Jan\\Downloads\\prisma chinook master cli-demo\\node_modules\\@prisma\\client\\generator-build\\index.js'
  getGenerators } +218ms
'C:\Users\Jan\Downloads\prisma' is not recognized as an internal or external command,
operable program or batch file.
  Generator:C:\Users\Jan\Downloads\prisma chinook master cli-demo\node_modules\@prisma\client\generator-build\index.js Sending "getManifest" rpc to generator +0ms
Error: Error [ERR_STREAM_DESTROYED]: Cannot call write after a stream was destroyed
    at doWrite (_stream_writable.js:413:19)
    at writeOrBuffer (_stream_writable.js:401:5)
    at Socket.Writable.write (_stream_writable.js:301:11)
    at GeneratorProcess.sendMessage (C:\Users\Jan\Downloads\prisma chinook master cli-demo\node_modules\@prisma\cli\build\index.js:2:549432)
    at C:\Users\Jan\Downloads\prisma chinook master cli-demo\node_modules\@prisma\cli\build\index.js:2:549706
    at new Promise (<anonymous>)
    at GeneratorProcess.getManifest (C:\Users\Jan\Downloads\prisma chinook master cli-demo\node_modules\@prisma\cli\build\index.js:2:549558)
    at Generator.<anonymous> (C:\Users\Jan\Downloads\prisma chinook master cli-demo\node_modules\@prisma\cli\build\index.js:2:745695)
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\Jan\Downloads\prisma chinook master cli-demo\node_modules\@prisma\cli\build\index.js:2:744975)
```

After renaming the folder to not contain spaces, everything works:

```
C:\Users\Jan\Downloads\prismachinookmastercli-demo>npx prisma2 generate
✔ Generated Prisma Client to .\node_modules\@prisma\client in 248ms

You can now start using Prisma Client in your code:

`
import { PrismaClient } from '@prisma/client'
// or const { PrismaClient } = require('@prisma/client')

const prisma = new PrismaClient()
`

Explore the full API: http://pris.ly/d/client


C:\Users\Jan\Downloads\prismachinookmastercli-demo>
```

version:
```
C:\Users\Jan\Downloads\prisma chinook master cli-demo>npx prisma2 --version
@prisma/cli          : 2.0.0-alpha.978
Current platform     : windows
Query Engine         : prisma d35b3d764e66598164f3b8ce821d452b09d4a613 (at C:\Users\Jan\Downloads\prisma chinook master cli-demo\node_modules\@prisma\cli\query-engine-windows.exe)
Migration Engine     : migration-engine-cli d35b3d764e66598164f3b8ce821d452b09d4a613 (at C:\Users\Jan\Downloads\prisma chinook master cli-demo\node_modules\@prisma\cli\migration-engine-windows.exe)
Introspection Engine : introspection-core d35b3d764e66598164f3b8ce821d452b09d4a613 (at C:\Users\Jan\Downloads\prisma chinook master cli-demo\node_modules\@prisma\cli\introspection-engine-windows.exe)
```

**Comment by pantharshit00** [comment] 2020-03-30 22:22
I can confirm this on my windows machine as well.

**Comment by pramodsvidyarthi** [comment] 2020-04-04 05:35
This issues holds true for a mac as well.

**Comment by ivankhm** [comment] 2020-04-04 10:15
Confirming, on Mac OS 10.14.1 with **Prisma 2 beta 1**
Here is my `package.json`

```json
{
  "name": "api-server-experemental",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "@prisma/cli": "^2.0.0-beta.1",
    "@types/node": "^13.11.0",
    "ts-node": "^8.8.1",
    "typescript": "^3.8.3"
  },
  "dependencies": {
    "@prisma/client": "^2.0.0-beta.1"
  }
}
```

I store my projects in folder "VSCode Projects", and just by following quickstart tutorial got same error, here is debug log:
```
MacBook-Pro-Evan:api-server-experemental Evan$  DEBUG="*" npx prisma generate
  prisma .env loaded from ./prisma/.env +0ms
(node:4610) ExperimentalWarning: The fs.promises API is experimental
  getos { platform: 'darwin', libssl: undefined } +0ms
  download { cachedFile:
  download    '/Users/Evan/.cache/prisma/master/2accb9c7eacdc984874eaeb63377fe705dfd3203/darwin/query-engine' } +0ms
  download { cachedFile:
  download    '/Users/Evan/.cache/prisma/master/2accb9c7eacdc984874eaeb63377fe705dfd3203/darwin/migration-engine' } +2ms
  download { cachedFile:
  download    '/Users/Evan/.cache/prisma/master/2accb9c7eacdc984874eaeb63377fe705dfd3203/darwin/introspection-engine' } +1ms
  getos { platform: 'darwin', libssl: undefined } +9ms
  getos { platform: 'darwin', libssl: undefined } +0ms
  download { cachedFileSize: 16570608, targetFileSize: 16570608 } +1ms
  download { cachedFileSize: 14816616, targetFileSize: 14816616 } +46ms
  download { cachedFileSize: 11202264, targetFileSize: 11202264 } +5ms
  download { cachedFile:
  download    '/Users/Evan/.cache/prisma/master/2accb9c7eacdc984874eaeb63377fe705dfd3203/darwin/query-engine' } +6ms
  download { cachedFileSize: 16570608, targetFileSize: 16570608 } +2ms
  download Getting version of /Users/Evan/Documents/VSCode Projects/52hospital/api-server-experemental/node_modules/@prisma/cli/query-engine-darwin. Result:  { command:
   '/Users/Evan/Documents/VSCode Projects/52hospital/api-server-experemental/node_modules/@prisma/cli/query-engine-darwin --version',
  exitCode: 0,
  stdout: 'prisma 2accb9c7eacdc984874eaeb63377fe705dfd3203',
  stderr: '',
  all: undefined,
  failed: false,
  timedOut: false,
  isCanceled: false,
  killed: false } +43ms
  download Getting version of /Users/Evan/Documents/VSCode Projects/52hospital/api-server-experemental/node_modules/@prisma/cli/query-engine-darwin. Result:  prisma 2accb9c7eacdc984874eaeb63377fe705dfd3203 +28ms
  download { works: true } +0ms
  download { needsToBeDownloaded: false } +1ms
  download Getting version of /Users/Evan/Documents/VSCode Projects/52hospital/api-server-experemental/node_modules/@prisma/cli/migration-engine-darwin. Result:  { command:
   '/Users/Evan/Documents/VSCode Projects/52hospital/api-server-experemental/node_modules/@prisma/cli/migration-engine-darwin --version',
  exitCode: 0,
  stdout:
   'migration-engine-cli 2accb9c7eacdc984874eaeb63377fe705dfd3203',
  stderr: '',
  all: undefined,
  failed: false,
  timedOut: false,
  isCanceled: false,
  killed: false } +6ms
  download Getting version of /Users/Evan/Documents/VSCode Projects/52hospital/api-server-experemental/node_modules/@prisma/cli/migration-engine-darwin. Result:  migration-engine-cli 2accb9c7eacdc984874eaeb63377fe705dfd3203 +0ms
  download { works: true } +0ms
  download { needsToBeDownloaded: false } +0ms
  download Getting version of /Users/Evan/Documents/VSCode Projects/52hospital/api-server-experemental/node_modules/@prisma/cli/introspection-engine-darwin. Result:  { command:
   '/Users/Evan/Documents/VSCode Projects/52hospital/api-server-experemental/node_modules/@prisma/cli/introspection-engine-darwin --version',
  exitCode: 0,
  stdout:
   'introspection-core 2accb9c7eacdc984874eaeb63377fe705dfd3203',
  stderr: '',
  all: undefined,
  failed: false,
  timedOut: false,
  isCanceled: false,
  killed: false } +1ms
  download Getting version of /Users/Evan/Documents/VSCode Projects/52hospital/api-server-experemental/node_modules/@prisma/cli/introspection-engine-darwin. Result:  introspection-core 2accb9c7eacdc984874eaeb63377fe705dfd3203 +0ms
  download { works: true } +0ms
  download { needsToBeDownloaded: false } +0ms
  download Getting version of /Users/Evan/Documents/VSCode Projects/52hospital/api-server-experemental/node_modules/@prisma/cli/query-engine-darwin. Result:  { command:
   '/Users/Evan/Documents/VSCode Projects/52hospital/api-server-experemental/node_modules/@prisma/cli/query-engine-darwin --version',
  exitCode: 0,
  stdout: 'prisma 2accb9c7eacdc984874eaeb63377fe705dfd3203',
  stderr: '',
  all: undefined,
  failed: false,
  timedOut: false,
  isCanceled: false,
  killed: false } +2ms
  download Getting version of /Users/Evan/Documents/VSCode Projects/52hospital/api-server-experemental/node_modules/@prisma/cli/query-engine-darwin. Result:  prisma 2accb9c7eacdc984874eaeb63377fe705dfd3203 +1ms
  download { works: true } +0ms
  download { needsToBeDownloaded: false } +0ms
  getGenerators { binaryPathsWithEngineType:
  getGenerators    { 'query-engine':
  getGenerators       { darwin:
  getGenerators          '/Users/Evan/Documents/VSCode Projects/52hospital/api-server-experemental/node_modules/@prisma/cli/query-engine-darwin' } } } +0ms
  engineCommands getDMMF, override prismaPath = /Users/Evan/Documents/VSCode Projects/52hospital/api-server-experemental/node_modules/@prisma/cli/query-engine-darwin +0ms
  engineCommands getConfig, override prismaPath = /Users/Evan/Documents/VSCode Projects/52hospital/api-server-experemental/node_modules/@prisma/cli/query-engine-darwin +43ms
  getos { platform: 'darwin', libssl: undefined } +220ms
{ prismaClientDir:
   '/Users/Evan/Documents/VSCode Projects/52hospital/api-server-experemental/node_modules/@prisma/client' }
  getGenerators { outputPath:
  getGenerators    '/Users/Evan/Documents/VSCode Projects/52hospital/api-server-experemental/node_modules/@prisma/client',
  getGenerators   generatorPath:
  getGenerators    '/Users/Evan/Documents/VSCode Projects/52hospital/api-server-experemental/node_modules/@prisma/client/generator-build/index.js' } +80ms
  Generator:/Users/Evan/Documents/VSCode Projects/52hospital/api-server-experemental/node_modules/@prisma/client/generator-build/index.js Sending "getManifest" rpc to generator +0ms
Error: Error [ERR_STREAM_DESTROYED]: Cannot call write after a stream was destroyed
    at doWrite (_stream_writable.js:406:19)
    at writeOrBuffer (_stream_writable.js:394:5)
    at Socket.Writable.write (_stream_writable.js:294:11)
    at GeneratorProcess.sendMessage (/Users/Evan/Documents/VSCode Projects/52hospital/api-server-experemental/node_modules/@prisma/cli/build/index.js:2:549424)
    at Promise (/Users/Evan/Documents/VSCode Projects/52hospital/api-server-experemental/node_modules/@prisma/cli/build/index.js:2:549698)
    at new Promise (<anonymous>)
    at GeneratorProcess.getManifest (/Users/Evan/Documents/VSCode Projects/52hospital/api-server-experemental/node_modules/@prisma/cli/build/index.js:2:549550)
    at Generator.<anonymous> (/Users/Evan/Documents/VSCode Projects/52hospital/api-server-experemental/node_modules/@prisma/cli/build/index.js:2:745671)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/Evan/Documents/VSCode Projects/52hospital/api-server-experemental/node_modules/@prisma/cli/build/index.js:2:744951)
```
After changing folder name to "VSCodeProjects" it works fine.

Versions: 
```
MacBook-Pro-Evan:api-server-experemental Evan$ npx prisma --version
(node:4702) ExperimentalWarning: The fs.promises API is experimental
@prisma/cli          : 2.0.0-beta.1
Current platform     : darwin
Query Engine         : prisma 2accb9c7eacdc984874eaeb63377fe705dfd3203 (at /Users/Evan/Documents/VSCodeProjects/52hospital/api-server-experemental/node_modules/@prisma/cli/query-engine-darwin)
Migration Engine     : migration-engine-cli 2accb9c7eacdc984874eaeb63377fe705dfd3203 (at /Users/Evan/Documents/VSCodeProjects/52hospital/api-server-experemental/node_modules/@prisma/cli/migration-engine-darwin)
Introspection Engine : introspection-core 2accb9c7eacdc984874eaeb63377fe705dfd3203 (at /Users/Evan/Documents/VSCodeProjects/52hospital/api-server-experemental/node_modules/@prisma/cli/introspection-engine-darwin)
```

**Comment by pantharshit00** [comment] 2020-04-07 17:05
I got a different error on mac.
<img width="1438" alt="image" src="https://user-images.githubusercontent.com/22195362/78698437-f768a980-791f-11ea-87be-c9cb1aef731c.png">

**Comment by ivoilic** [comment] 2020-04-08 22:02
Can confirm. Same issue on OSX with Prisma 2 beta 2

**Comment by cmakohon** [comment] 2020-04-10 20:17
I have been struggling with this issue for the better part of the day, and I can't believe it was as simple as removing a space from the parent path. Works for me now on Mac, thanks so much!

**Comment by Vandivier** [comment] 2020-04-12 05:15
not so easy to fix for me on windows as the space is in my user folder
![image](https://user-images.githubusercontent.com/5559355/79061146-079fc200-7c5b-11ea-8c5e-a405a9dbd419.png)

**Comment by timsuchanek** [comment] 2020-04-15 16:25
Thanks a lot for reporting 🙏
This issue is fixed in the latest alpha version of `@prisma/cli`.
You can try it out with `npm i -g @prisma/cli@alpha`.

In case it’s not fixed for you - please let us know and we’ll reopen this issue!

**Comment by steebchen** [comment] 2020-05-25 08:07
We should add a test for this

**Comment by steebchen** [comment] 2020-06-02 08:54
There's still no tests for this specific case.

**Closed** 2020-06-02 09:44 UTC
Labels: bug/2-confirmed, kind/bug, team/typescript, topic: cli-generate, topic: windows
