### ISSUE TITLE
Bun: Prisma fails silently when seeding with bun with top level async function

### ISSUE THREAD

**Issue by c-sleanshot** [prisma/prisma#21324] opened 2023-10-03 18:25 UTC
### Bug description

I'm using Prisma in an app running on Bun.sh + Elysia. I just added Prisma and configured a seeding script that looks like this: 

```
import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient({
    log: [
      {
        emit: 'event',
        level: 'query',
      },
      {
        emit: 'stdout',
        level: 'error',
      },
      {
        emit: 'stdout',
        level: 'info',
      },
      {
        emit: 'stdout',
        level: 'warn',
      },
    ],
  })
  
  prisma.$on('query', (e) => {
    console.log('Query: ' + e.query)
    console.log('Params: ' + e.params)
    console.log('Duration: ' + e.duration + 'ms')
  })
async function main() {
  const client = await prisma.client.create({
    data: data, // ommited for brevity
  });

  const codes = await prisma.countryCode.createMany({
    data: countryCodes, // ommited for brevity
  });
}

main()
  .then(async () => {
    console.log("Successfully seeded DB");
    await prisma.$disconnect();
  })
  .catch(async (e) => {
    console.error(e);
    await prisma.$disconnect();
    process.exit(1);
  });
```

The problem is that when I run `bunx prisma db seed`, the process fails silently on the first create operation. No errors, nothing. The logs output this:

```
bunx prisma db seed
  prisma:engines  binaries to download libquery-engine, schema-engine +0ms
  prisma:loadEnv  project root found at /Users/.../package.json +0ms
  prisma:tryLoadEnv  Environment variables loaded from /Users/.../.env +0ms
Environment variables loaded from .env
  prisma:migrate:seed  {
  prismaConfig: {
    data: { seed: 'bun prisma/seed.ts' },
    packagePath: '/Users/.../package.json'
  }
} +0ms
Running seed command `bun prisma/seed.ts` ...
  prisma:tryLoadEnv  Environment variables loaded from /Users/.../.env +0ms
  prisma:client  checkPlatformCaching:postinstall undefined +0ms
  prisma:client  checkPlatformCaching:ciName undefined +0ms
  prisma:tryLoadEnv  Environment variables loaded from /Users/.../.env +26ms
  prisma:client  dirname /Users/.../node_modules/.prisma/client +0ms
  prisma:client  relativePath ../../../prisma +0ms
  prisma:client  cwd /Users/.../prisma +0ms
  prisma:client  clientVersion 5.3.1 +0ms
  prisma:client:libraryEngine  internalSetup +0ms
  prisma:client  Prisma Client call: +5ms
  prisma:client  prisma.client.create({
  data: {
    ....
  }
}) +1ms
  prisma:client  Generated request: +0ms
  prisma:client  {
  "modelName": "Client",
  "action": "createOne",
  "query": {
    "arguments": {
      "data": {
        ...
      }
    },
    "selection": {
      "$composites": true,
      "$scalars": true
    }
  }
}
 +0ms
  prisma:client:libraryEngine  sending request, this.libraryStarted: false +6ms
  prisma:client:engines:resolveEnginePath  enginePath /Users/.../node_modules/.prisma/client/libquery_engine-darwin-arm64.dylib.node +0ms
  prisma:client:libraryEngine  library starting +27ms

🌱  The seed command has been executed.
  prisma:getConfig  Using getConfig Wasm +0ms
  prisma:getConfig  config data retrieved without errors in getConfig Wasm +8ms
```

And that's it, it finishes the process but nothing else happens.

### How to reproduce

1. Use a bun.sh environment with Postgresql and integrate Prisma.
2. Create a seeding script.
3. Insert some data
4. See described behavior.

### Expected behavior

Prisma should insert the records or generate an error if something goes wrong.

### Prisma information

```prisma
generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}
```

```ts
Code added in the main body of this issue.
```

### Environment & setup

- OS: macOS
- Database: PostgreSQL
- Node.js version: v20.6.1

### Prisma Version

```
5.3.1
```

**Comment by janpio** [comment] 2023-10-04 12:39
I assume the same script executed with Node succeeds in creating the data successfully?

**Comment by c-sleanshot** [comment] 2023-10-04 18:57
I can't test it with node, the script uses some of Bun's cryptography libraries to generate the data for seeding. If I try to run it with node, I'd have to rewrite it.

**Comment by aqrln** [comment] 2023-10-05 12:49
@c-sleanshot 

> I can't test it with node, the script uses some of Bun's cryptography libraries to generate the data for seeding

Unless I'm missing something, the script you posted as a reproduction doesn't use anything specific to Bun. So either you should be able to run it in Node.js to confirm if it's an bug in Prisma or in Bun, or this script doesn't actually reproduce the issue and we can't use it even with Bun to do that. Can you confirm if the script you posted works as a reproduction?

**Comment by c-sleanshot** [comment] 2023-10-05 17:47
Hello again! I did some experimentation, and these are my findings:
1. I removed everything Bun-related from the script and ran it with node. It behaved as expected.
2. I put the Bun imports back into the script (note to @aqrln, I shared an abridged version of the script; I was using Bun.CryptoHasher to generate some hashed as part of the seeding), and that's when trouble started.
3. I tried to make ts-node and bun work together by using `bunx prisma db seed` and `ts-node prisma/seed.mts` in my package.json, but this led nowhere. First, ts-node couldn't resolve Bun, then after some tinkering with the compileOptions it worked, but other libraries failed to be resolved. Either the dependencies broke, or the module rejected my code.

Thus, I don't believe the issue is related to Prisma. I think it is related to how Bun runs scripts and its incompatibility with ts-node. I think I'll ditch Bun in favor of Node until this behaves properly and avoid you guys wasting any more time on this.

**Comment by aqrln** [comment] 2023-10-06 09:03
> I put the Bun imports back into the script (note to @aqrln, I shared an abridged version of the script; I was using Bun.CryptoHasher to generate some hashes as part of the seeding), and that's when trouble started.

But does this "abridged version" work in Bun or only in Node.js?

> Thus, I don't believe the issue is related to Prisma. I think it is related to how Bun runs scripts

From the look of it, this does likely sound like a Bun issue which would be nice to properly isolate and report to Bun. That said, we still want to reproduce it and see what happens. Ultimately our goal is to help everyone running Prisma regardless of their JS runtime, so we should take a look and see if there's anything actionable from our side or not.

**Comment by mathieuarthur** [comment] 2023-10-07 23:42
Hey ! I just created a public repo with two folders, They are significantly the same but with light changes that make it work for node but not for bun (I am doing this since it was asked after my thread on the discord)

[prismaBun-Debug repo](https://github.com/mathieuarthur/prismabun-debug)

A readme explains how to reproduce, if I made things bad tell me !

**Comment by janpio** [comment] 2023-10-08 07:12
Thank you. With that, it was easy to isolate the problem:
```
cd bun-bugged
# set `DATABASE_URL="mongo://foo/bar"` in .env
bun i
bun generate
bun utils/seed.ts
``` 

So the problem is not Prisma's seeding, but that bun does not return any error when Prisma throws one.

In Node, the same looks like this:
```
> ts-node utils/seed.ts
PrismaClientInitializationError: 
Invalid `prisma.user.create()` invocation in
C:\Users\Jan\Documents\throwaway\prismabun-debug\node-working\utils\seed.ts:7:23

  4
  5 async function main()
  6 {
→ 7     await prisma.user.create(
The provided database string is invalid. MongoDB connection string error: invalid connection string scheme: mongo in database URL. Please refer to the documentation in https://www.prisma.io/docs/reference/database-reference/connection-urls for constructing a correct connection string. In some cases, certain characters must be escaped. Please check the string for any illegal characters.
    at Cn.handleRequestError (C:\Users\Jan\Documents\throwaway\prismabun-debug\node-working\node_modules\@prisma\client\runtime\library.js:123:7090)
    at Cn.handleAndLogRequestError (C:\Users\Jan\Documents\throwaway\prismabun-debug\node-working\node_modules\@prisma\client\runtime\library.js:123:6206)
    at Cn.request (C:\Users\Jan\Documents\throwaway\prismabun-debug\node-working\node_modules\@prisma\client\runtime\library.js:123:5926)    
    at async l (C:\Users\Jan\Documents\throwaway\prismabun-debug\node-working\node_modules\@prisma\client\runtime\library.js:128:9968)       
    at async main (C:\Users\Jan\Documents\throwaway\prismabun-debug\node-working\utils\seed.ts:7:5) {
  clientVersion: '5.4.1',
  errorCode: undefined
}
```

So either bun expects different logic in `seed.ts`, or you found a bug in Bun. 

I can't imagine how this could be a problem with Prisma, considering the minimal script we have in `seed.ts`. Or do you disagree?

If we agree that this is most probably a Bun problem, this should probably be reported to the bun team, so they can investigate.

**Comment by janpio** [comment] 2023-10-08 07:16
Okay, this rang a bell so I dug into our `topic: bun` issues:

https://github.com/prisma/prisma/issues/21108

This is being tracked over at bun at https://github.com/oven-sh/bun/issues/3137

So the solution is to use this script with a top level `await` instead of the `main` function:

```
import { PrismaClient } from "@prisma/client"

const prisma = new PrismaClient()

try {
    console.log("main")
    await prisma.user.create({
        data:
        {
            name: "John Dough",
            email: `john-${Math.random()}@example.com`
        },
    })
    console.log("after create")
    const count = await prisma.user.count()

    console.log(`There are ${count} users in the database.`)
} catch (error) {
    console.error(error);
    await prisma.$disconnect();
    process.exit(1);
}
```

**Comment by mathieuarthur** [comment] 2023-10-08 14:41
Hey ! Cool ! Saw you linked this to the bun issues too.

Do you have anything more from my hand to figure out how to fix it  maybe ?

**Comment by jharrell** [comment] 2023-10-08 19:21
> Hey ! Cool ! Saw you linked this to the bun issues too.
> 
> Do you have anything more from my hand to figure out how to fix it maybe ?

It looks like this is an issue in Bun. We unfortunately cannot solve it beyond suggesting the above workaround 

https://github.com/prisma/prisma/issues/21108#issuecomment-1724151158

**Comment by mathieuarthur** [comment] 2023-10-09 19:33
As I talked with js expert, he found really strange that in a js / ts you used a main function for the seeder (cf: see your [documentation](https://www.prisma.io/docs/guides/migrate/seed-database)

By default no main function is needed in this languages, so why use it ?

As bun work pretty much like node / native js we shouldn't call the top level await a "workaround" but the effective and intended way in js to perform this.

Tbh I don't think bun should fix anything (maybe add the good behaviour inside a function but it is not mandatory) and you should edit the documentation to follow what the new [bun documentation](https://bun.sh/guides/ecosystem/prisma) tell, so no "main" function

Like this : 

```ts
import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

// create a new user
await prisma.user.create({
  data: {
    name: "John Dough",
    email: `john-${Math.random()}@example.com`,
  },
});

// count the number of users
const count = await prisma.user.count();
console.log(`There are ${count} users in the database.`);
```

Coming from the official doc / link in my comment.

**Comment by aqrln** [comment] 2023-10-09 21:08
@mathieuarthur 

> By default no main function is needed in this languages, so why use it ?

Top-level await is only possible in native ESM while lots of folks still use CommonJS and transpile ESM syntax into it, doubly so back in the day when these docs were written. Wrapping everything into an async function ensures everyone can copy this code as is and it will always work.

> Tbh I don't think bun should fix anything

This is a real bug that certainly has to be fixed. Regardless of your stylistic preferences, this is incorrect behaviour, and can lead to issues in many other scenarios as well.

**Comment by cholasimmons** [comment] 2023-12-18 07:10
I have this super simplified code that I use.
I'm guessing the issue was sorted in the 2 months that have passed.
I did however have to change my extension from .ts to .mjs
```typescript
import { PrismaClient } from '@prisma/client';

export const db = new PrismaClient()


async function main() {
    await db.role.createMany({
      data: [
        { name: 'GUEST' },
        { name: 'USER' },
        { name: 'MODERATOR' },
        { name: 'ADMIN' }
      ]
    });
  }

main()
  .catch((e) => {
    console.error('seed: ',e);
    
    throw e;
  })
  .finally(async () => {
    await db.$disconnect();
  });
```

**Comment by why06** [comment] 2023-12-30 23:29
Spent hours figuring this out. It would be great if the Prisma documentation would mention something about this. The issue also exist for higher versions of Node with top-level await, it's not just a bun issue. But I need to do more testing.

I ended up just awaiting the main function like so:
```
await main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
    console.log("Disconnected from database.");
  });
```

I like this a bit better as it stays closer to the source documentation using promise chaining and disconnects in the finally block.

**Comment by janpio** [comment] 2024-02-05 18:35
https://github.com/oven-sh/bun/issues/3137#issuecomment-1927726343

> As of Bun v1.0.26, this has been fixed. If you're still experiencing this issue, let us know and we'll re-open the issue.
> 
> ```
> ❯ bun index.ts
> foo
> cheese
> 0
> ```

Can someone confirm?

**Comment by wanosoft** [comment] 2024-02-07 06:53
Issue persist using `bun v1.0.26`

**Comment by ahmafi** [comment] 2024-03-23 15:52
I have the similar issue on `bun v1.0.35`. Using `await` on the `main` function call solves it.

**Comment by komarapc** [comment] 2024-04-29 07:06
It's work 
```typescript
import { PrismaClient } from '@prisma/client'
import {nanoid} from "nanoid";
import {faker} from "@faker-js/faker";
import * as bcrypt from 'bcrypt'
const prisma = new PrismaClient()

type User = {
  id: string
  email: string
  name: string
  password: string
  createdAt: Date
  updatedAt: Date
  deletedAt?: Date
}
const users: User[] = Array.from({length:100},()=>({
  id: nanoid(),
  name: faker.person.fullName(),
  email: faker.internet.email(),
  password: bcrypt.hashSync("password", 10),
  createdAt: new Date(),
  updatedAt: new Date()
}))

try {
  await  prisma.$connect()
  await prisma.user.createMany({data: users})
  console.log("Seed data created")
} catch (err) {
  await prisma.$disconnect()
  console.error(err)
}
```

**Comment by janpio** [comment] 2024-06-07 13:13
Again, Bun thinks this problem is resolved: https://github.com/oven-sh/bun/issues/3137#issuecomment-2016373579
Can someone confirm that?
I am closing this issue now here.

If this is still broken for you, do you have a reproduction?
Then please open an issue for Bun so they can fix it and link to your Bun issue here as context. Thank you.

**Closed by janpio** 2024-06-07 13:13 UTC
Labels: bug/2-confirmed, kind/bug, tech/typescript, team/client, topic: prisma db seed, topic: seeding, topic: bun, status/blocked-by-dependency

**Comment by fzn0x** [comment] 2024-06-07 22:54
@janpio  this is still not solved in Bun

Confirm that .env already filled -> insert not working
root@02fab7ab7a19:/usr/src/app# bun run prisma/seed.ts 
🔐 Loading environment variables...
✅ Environment variables loaded
(nothing happens, no updated records)

**Comment by fzn0x** [comment] 2024-06-07 22:59
I think the bug reappears in Bun v1.1.12

Using this workaround https://github.com/prisma/prisma/issues/21324#issuecomment-1751945478, it's fixed

**Comment by fzn0x** [comment] 2024-06-07 23:02
I don't know why they keep confirm issue is fixed while it's not 😆

**Comment by janpio** [comment] 2024-06-08 08:32
@fzn0x I feared so. Please open an issue for bun with a minimal reproduction using your minimal Prisma code - and I am sure they will try to fix it, and I can also re-open this issue as soon as we have a link that shows this not working in a reproducible way.

**Comment by fs-99** [comment] 2025-02-21 13:28
> Okay, this rang a bell so I dug into our `topic: bun` issues:
> 
> [#21108](https://github.com/prisma/prisma/issues/21108)
> 
> This is being tracked over at bun at [oven-sh/bun#3137](https://github.com/oven-sh/bun/issues/3137)
> 
> So the solution is to use this script with a top level `await` instead of the `main` function:
> 
> ```
> import { PrismaClient } from "@prisma/client"
> 
> const prisma = new PrismaClient()
> 
> try {
>     console.log("main")
>     await prisma.user.create({
>         data:
>         {
>             name: "John Dough",
>             email: `john-${Math.random()}@example.com`
>         },
>     })
>     console.log("after create")
>     const count = await prisma.user.count()
> 
>     console.log(`There are ${count} users in the database.`)
> } catch (error) {
>     console.error(error);
>     await prisma.$disconnect();
>     process.exit(1);
> }
> ```

Also, when you're using bun, don't forget you can just run typescript files:
```json
"prisma": {
    "seed": "bun run prisma/seed.ts"
},
```
Just put that in the `package.json` and then use that top-level await solution.
