### ISSUE TITLE
Error: Failure during a migration command: Connector error. (error: Error querying the database: Error querying the database: Server error: `ERROR 42S01 (1050): Table './<table-name>/City' already exists' 

### ISSUE THREAD

**Issue by divyenduz** [prisma/prisma#4724] opened 2020-08-21 15:33 UTC
Command: `prisma migrate up --experimental`
Version: `2.5.0`
Binary Version: `9a670138b1db276001d785a2adcba1584c869d24`
Report: https://prisma-errors.netlify.app/report/10459 
OS: `x64 darwin 19.5.0`

JS Stacktrace:
```
Error: Failure during a migration command: Connector error. (error: Error querying the database: Error querying the database: Server error: `ERROR 42S01 (1050): Table './<folder-name>/City' already exists'
   0: migration_core::api::ApplyMigration
           with migration_id="20200723100056-test"
             at migration-engine/core/src/api.rs:79)
    at Object.<anonymous> (/path/node_modules/@prisma/cli/build/index.js:2:2145445)
    at MigrateEngine.handleResponse (/path/node_modules/@prisma/cli/build/index.js:2:2143653)
    at LineStream.<anonymous> (/path/node_modules/@prisma/cli/build/index.js:2:2145110)
    at LineStream.emit (events.js:311:20)
    at LineStream.EventEmitter.emit (domain.js:482:12)
    at addChunk (_stream_readable.js:294:12)
    at readableAddChunk (_stream_readable.js:275:11)
    at LineStream.Readable.push (_stream_readable.js:209:10)
    at LineStream.Transform.push (_stream_transform.js:152:32)
    at LineStream._pushBuffer (/path/node_modules/@prisma/cli/build/index.js:2:1813582)
```

Rust Stacktrace:
```
Failure during a migration command: Connector error. (error: Error querying the database: Error querying the database: Server error: `ERROR 42S01 (1050): Table './<folder-name>/City' already exists'
   0: migration_core::api::ApplyMigration
           with migration_id="20200723100056-test"
             at migration-engine/core/src/api.rs:79)
```

**Comment by DavideCarvalho** [comment] 2021-02-19 11:50
I'm having this issue with prisma and prisma/client at 2.17.0

as you can see on migrations folder, the first migration is creating the tables and the second is trying to recreate them - and then drops them

first migration:
![image](https://user-images.githubusercontent.com/15630886/108500926-421cb700-728f-11eb-93fa-05846c38c527.png)

second migration:
![image](https://user-images.githubusercontent.com/15630886/108501009-67112a00-728f-11eb-9a84-7bcd692c979b.png)

repo: https://github.com/NewSchoolApp/marketplace

cli error:
![image](https://user-images.githubusercontent.com/15630886/108500682-ef42ff80-728e-11eb-9e67-cf01275a9d26.png)

**Comment by dopefatimah** [comment] 2021-02-20 13:08
+1 @DavideCarvalho  Having the same issue too. Windows, MySQL and Prisma 2.17.0. It is always trying to create existing tables as is. It doesn't detect changes.

**Comment by tomhoule** [comment] 2021-02-25 10:43
Hi @dopefatimah and @DavideCarvalho the code to detect mysql installations of windows in migrate (they are broken otherwise because it's the only environment where table names are lower cased automatically by the database) has a regression in 2.17.0. It will be fixed in 2.18.0. For now, the solution to your problem would 1. reverting to 2.16.0, or 2. use `prisma@dev`.

**Comment by DavideCarvalho** [comment] 2021-02-25 10:46
Do you guys have a release date for 2.18.0?

**Comment by dopefatimah** [comment] 2021-02-25 11:00
> Hi @dopefatimah and @DavideCarvalho the code to detect mysql installations of windows in migrate (they are broken otherwise because it's the only environment where table names are lower cased automatically by the database) has a regression in 2.17.0. It will be fixed in 2.18.0. For now, the solution to your problem would 1. reverting to 2.16.0, or 2. use `prisma@dev`.

Will check and revert. Thanks!

**Comment by tomhoule** [comment] 2021-02-25 11:03
> Do you guys have a release date for 2.18.0?

Next tuesday :)

**Comment by dopefatimah** [comment] 2021-02-25 11:16
> > Do you guys have a release date for 2.18.0?
> 
> Next tuesday :)

Works, thanks! Looking forward to 2.18.0 🥳

**Comment by tomhoule** [comment] 2021-03-02 09:11
Since we can't reproduce the original report and the discussion went way off-topic, let's close this issue. Please open a new one if you think you are experiencing the original problem.

**Closed by tomhoule** 2021-03-02 09:11 UTC
Labels: bug/1-repro-available, kind/bug, process/candidate, team/migrations, topic: windows
