### ISSUE TITLE
Support for two or more databases with Prisma2

### ISSUE THREAD

**Issue by MarcelMalik** [prisma/prisma#2229] opened 2020-04-19 19:26 UTC
## Problem
I have different PostgreSQL databases. But with Prisma2, I can apparently only use one database per app.

## Solution
Support more then one database (maybe with separate Prima Clients?).

## Additional context
I try to generate separate Prisma Clients with separate schema files:
file db1-schema.prisma:
```
generator client {
  provider = "prisma-client-js"
  output   =  "../components/database/db1"
}
```
file db2-schema.prisma:
```
generator client {
  provider = "prisma-client-js"
  output   =  "../components/database/db2"
}
```
generate schemas:
```
npx prisma introspect --schema=./prisma/db1-schema.prisma
npx prisma introspect --schema=./prisma/db2-schema.prisma

```
geneate separate prisma clients:
```
npx prisma generate --schema=./prisma/db1-schema.prisma
npx prisma generate --schema=./prisma/db2-schema.prisma
```

But unfortunately I only get error messages when using it. Can that even work?

**Comment by pantharshit00** [comment] 2020-04-20 23:16
Related: https://github.com/prisma/prisma/issues/1487


Prisma multi-tenant can be used here: https://github.com/errorname/prisma-multi-tenant

**Comment by albertoperdomo** [comment] 2020-08-28 17:03
This would be covered by https://github.com/prisma/prisma/issues/1274 which is related to having multiple datasources.

**Comment by janpio** [comment] 2020-08-28 17:30
This is actually about a different problem: @MarcelMalik wants to use two different Prisma Clients in his app, each talking to a different database. That should in theory just work today the way he described it above.

**Comment by albertoperdomo** [comment] 2020-08-31 09:39
What I perceive is that using two databases with separate clients is a valid workaround for @MarcelMalik.

Another solution would be to use separate clients as described here. Indeed, if it's possible we should reproduce and ensure this is properly documented.

**Comment by pantharshit00** [comment] 2020-08-31 10:51
I am unable to reproduce this. I am able to use two different prisma client which points to two different databases in the code.

![image](https://user-images.githubusercontent.com/22195362/91712703-ee65c680-eba5-11ea-9c39-802bdbc4a549.png)


Since this issue is a bit old, please try again with the latest version of prisma.

**Comment by blazestudios23** [comment] 2020-10-29 17:18
I'm trying to do this with Nexus/Schema. 

I don't see a way for Nexus to recognize multiple clients. 

Is this possible?

**Comment by pantharshit00** [comment] 2020-10-31 01:33
Well if you are using the Prisma plugin for nexus, I don't it can do that right now. 

Please open an issue in the nexus repository underlying your use case if you want that feature.

**Comment by pantharshit00** [comment] 2020-11-03 14:03
Closing in favour of https://github.com/prisma/prisma/issues/1274

**Closed by pantharshit00** 2020-11-03 14:03 UTC
Labels: bug/0-needs-info, kind/bug, team/support
