### ISSUE TITLE
Unneeded select query on update and connect

### ISSUE THREAD

**Issue by P4sca1** [prisma/prisma#3983] opened 2020-10-20 20:43 UTC
## Bug description
Not quite sure if this is intended behaviour for some kind of validation, but I noticed that prisma generates queries, which seem unneeded to me, such as
```sql
# prisma.model.update(). Why select an id we already have?
SELECT `test`.`User`.`id` FROM `test`.`User` WHERE `test`.`User`.`id` = ? LIMIT ? OFFSET ?
```
or
```sql
# prisma.model.create() with connect. Why select an id we already have?
SELECT `test`.`User`.`id` FROM `test`.`User` WHERE `test`.`User`.`id` = ?
```
when calling `prisma.model.update()` or using `connect` (e.g. in `prisma.model.create()`.

If this is intended behaviour, please see this issue as a question on why it generates those query and perhaps a request to add info about it to the docs. I came across this while analyzing the queries prisma generates to potentially find bottlenecks in my application.

## How to reproduce

1. Create empty directory
2. Run `prisma init`
3. Copy the prisma schema from below to `prisma/schema.prisma` (it will use sqlite for simpler reproduction).
4. Run `prisma generate`
5. Run `prisma migrate save --experimental`. Chose any name you want, such as `init`.
6. Run `prisma migrate up --experimental`
7. Copy `index.js` from below
8. Run `node index.js`
9. Watch the output for the queries prisma generates.

**index.js:**
```js
const { PrismaClient } = require('@prisma/client')

const prisma = new PrismaClient({
    log: ['query', 'info', 'warn'],
})

async function main() {
    try {
        let user = await prisma.user.create({ data: { name: 'test' }})
        console.log('Created user', user)

        user = await prisma.user.update({
            where: { id: user.id },
            data: { name: 'test2' }
        })
        console.log('udpated user', user)

        let post = await prisma.post.create({
            data: {
                user: {
                    connect: { id: user.id }
                }
            }
        })
        console.log('created post on user', post)
    } catch (err) {
        console.error(err)
    }
}

main()
```

## Expected behavior
Prisma should not generate those select queries as they seem unneeded?

## Prisma information

**schema.prisma:**
```prisma
datasource db {
  provider = "sqlite"
  url      = "file:./test.db"
}

generator client {
  provider = "prisma-client-js"
}

model User {
  id    Int    @id @default(autoincrement())
  name  String
  posts Post[]
}

model Post {
  id     Int  @id @default(autoincrement())
  userId Int
  user   User @relation(fields: [userId], references: [id])
}
```

## Environment & setup

- OS: MacOS
- Database: SQLite
- Node.js version: 12.16.2
- Prisma version:

```
@prisma/cli          : 2.9.0
@prisma/client       : 2.9.0
Current platform     : darwin
Query Engine         : query-engine 369b3694b7edb869fad14827a33ad3f3f49bbc20 (at ../../.npm/_npx/84515/lib/node_modules/@prisma/cli/query-engine-darwin)
Migration Engine     : migration-engine-cli 369b3694b7edb869fad14827a33ad3f3f49bbc20 (at ../../.npm/_npx/84515/lib/node_modules/@prisma/cli/migration-engine-darwin)
Introspection Engine : introspection-core 369b3694b7edb869fad14827a33ad3f3f49bbc20 (at ../../.npm/_npx/84515/lib/node_modules/@prisma/cli/introspection-engine-darwin)
Format Binary        : prisma-fmt 369b3694b7edb869fad14827a33ad3f3f49bbc20 (at ../../.npm/_npx/84515/lib/node_modules/@prisma/cli/prisma-fmt-darwin)
Studio               : 0.296.0
```

**Comment by pantharshit00** [comment] 2020-10-30 09:55
Hi,

Thanks for reporting this! It has already been reported before, so I am going to close this as a duplicate of https://github.com/prisma/prisma-client-js/issues/652

**Closed by pantharshit00** 2020-10-30 09:55 UTC
Labels: kind/discussion, topic: performance
