### ISSUE TITLE
Nextjs app deployed to vercel: `@prisma/client/edge did not initialize yet. You need to either enable Accelerate or the Data Proxy.`

### ISSUE THREAD

**Issue by Danubius1st** [prisma/prisma#20485] opened 2023-08-01 18:53 UTC
### Discussed in https://github.com/prisma/prisma/discussions/20483

<div type='discussions-op-text'>

<sup>Originally posted by **Danubius1st** August  1, 2023</sup>
I have an Nextjs app deployed to vercel.
At runtime I get this error:
```
Error: @prisma/client/edge did not initialize yet. You need to either enable Accelerate or the Data Proxy.
Enable Accelerate via `prisma generate --accelerate` or the Data Proxy via `prisma generate --data-proxy.`

```
Which is not true.
/lib/prisma.ts:
`import { PrismaClient } from '@prisma/client/edge';
`
/prisma/schema.prisma:
```
datasource db {
  provider     = "mysql"
  url          = env("PrismaDB")
  directUrl    = env("DATABASE_DEV_URL")
  relationMode = "prisma"
}
```
where `PrismaDB=prisma://...`
package.json:
```
  "scripts": {
        "vercel-data-proxy-build": "npx prisma generate --data-proxy && next build",
```
What's wrong ?

I have to say that on localhost the app works well with PrismaDB.</div>

**Comment by janpio** [comment] 2023-08-02 00:50
What version of Prisma are you using @Danubius1st?
Did this work before or have you never successfully deployed?
If this worked before, what changed?

**Comment by Danubius1st** [comment] 2023-08-02 11:19
Using Prisma 5.1.0
Not sure but I'm afraid it only worked locally.

**Comment by janpio** [comment] 2023-08-02 14:46
Can you maybe set up a minimal project with Next.js that shows this behavior, put it on GitHub and share it with us? Thanks.

**Comment by Jolg42** [comment] 2023-08-02 14:57
@Danubius1st Can you try renaming your script from `vercel-data-proxy-build` to `vercel-build`? Because Vercel only reads `vercel-build` automatically.

**Comment by Danubius1st** [comment] 2023-08-02 17:56
@Jolg42 Deployment works: the app is working on vercel, except prisma. And I watched the circleci deployment log also, who does his job.
@janpio OK, working on it. I will need a email.

**Comment by janpio** [comment] 2023-08-02 20:09
Optimally you can just make it a public repository that anyone can access. A minimal reproduction should not have any sensitive data. (But I am my first name @prisma.io if needed)

**Comment by Danubius1st** [comment] 2023-08-03 12:47
https://github.com/Danubius1st/nextjs-prisma-test

**Comment by janpio** [comment] 2023-08-06 13:05
Here is a PR that brings the project to a state that locally `npm run start` works: 
https://github.com/Danubius1st/nextjs-prisma-test/pull/1

**Comment by janpio** [comment] 2023-08-06 13:10
Your `vercel-build` npm script was missing the `prisma generate --data-proxy` command, so as the error message said you did not actually generate your `@prisma/client/edge` yet. With it added before `next build´, the project builds fine on Vercel. 

See the deployed app at https://nextjs-prisma-test-h86mj3t4n-prisma-orm.vercel.app/.

**Comment by Danubius1st** [comment] 2023-08-07 12:45
I saw the app you deployed at [https://nextjs-prisma-test-h86mj3t4n-prisma-orm.vercel.app/](url)
I have bad news. I got the message `Oh no... Response not successful: Received status code 405. Check if database is awake`.
Is the message that appears in the browser when I cannot connect to prisma db (probably because the same reason).

**Comment by janpio** [comment] 2023-08-07 13:14
Thanks, I can look into that. First time you mention that the error happens on that URL.

**Comment by janpio** [comment] 2023-08-07 13:53
Ok, seems I messed up slightly yesterday, good catch.

Here is the correct deployment with fixed `vercel-build`: https://nextjs-prisma-test-b1q8lx2a8-prisma-orm.vercel.app/admin/dictionary
This is the PR of the changes this branch has: https://github.com/Danubius1st/nextjs-prisma-test/pull/2
The only relevant to the problem you opened this issue for should be the edit in `package.json` to run `prisma generate --data-proxy` explicitly during deployment.

You still get an error message on `/admin/dictionary`, but this time with this error message:
```
[31mERR[0m ReferenceError: prisma is not defined
    at resolve (/var/task/.next/server/pages/api/graphql.js:58:78)
    at resolve (file:///var/task/node_modules/@pothos/plugin-prisma/esm/field-builder.js:21:20)
    at executeField (file:///var/task/node_modules/@graphql-tools/executor/esm/execution/execute.js:295:24)
    at executeFields (file:///var/task/node_modules/@graphql-tools/executor/esm/execution/execute.js:243:28)
    at executeOperation (file:///var/task/node_modules/@graphql-tools/executor/esm/execution/execute.js:209:18)
    at file:///var/task/node_modules/@graphql-tools/executor/esm/execution/execute.js:61:37
    at new ValueOrPromise (/var/task/node_modules/value-or-promise/build/main/ValueOrPromise.js:14:21)
    at executeImpl (file:///var/task/node_modules/@graphql-tools/executor/esm/execution/execute.js:61:12)
    at execute (file:///var/task/node_modules/@graphql-tools/executor/esm/execution/execute.js:47:12)
    at file:///var/task/node_modules/@graphql-tools/executor/esm/execution/normalizedExecutor.js:12:37 {
  path: [ 'Dictionary' ],
  locations: [ { line: 2, column: 3 } ],
  extensions: [Object: null prototype] {}
}
```
This seems like a more general problem in the app, or something that I caused via all the stuff I had to comment out even to get it to work. Agree @Danubius1st?

**Comment by janpio** [comment] 2023-08-07 19:20
(Closing as there was no actual problem, and we could help @Danubius1st fix the oversight in the build command.)

**Closed by janpio** 2023-08-07 19:20 UTC
Labels: bug/1-unconfirmed, kind/bug, team/client, topic: deployment/vercel, topic: prisma-client-edge

**Comment by Danubius1st** [comment] 2023-08-07 20:15
No need to import again `prisma`: as you can see `/graphql/Dictionary/types.ts` imports builder, which imports `prisma`.
But I tried to modify `/lib/prisma` like this:

```
import { PrismaClient } from '@prisma/client/edge';

let prisma: PrismaClient;

declare global {
  var prisma: PrismaClient;
}

if (!global.prisma) {
  global.prisma = new PrismaClient();
}
prisma = global.prisma;
```

export default prisma;

I kept my `/prisma/schema.prisma`:
```
datasource db {
  url          = env("PrismaDB")
...
}
```
So data proxy is enabled!
As result my app worked locally in both development an production mode.
I checked Environment Variables in settings for the nth time.
Except, in vercel I got the old error message:
`@prisma/client/edge did not initialize yet. You need to either enable Accelerate or the Data Proxy`

**Comment by janpio** [comment] 2023-08-07 20:50
I quickly migrated a database and configured it in Data Proxy, to show you a working (but empty) app:
https://nextjs-prisma-test-l538ons3i-prisma-orm.vercel.app/admin/dictionary
<img width="503" alt="image" src="https://github.com/prisma/prisma/assets/183673/d802c3fe-d345-4879-8aa5-eac27fbc6c7d">
This is a direct deployment of the code of https://github.com/Danubius1st/nextjs-prisma-test/pull/2.

**Comment by Danubius1st** [comment] 2023-08-11 15:25
Found the error: wrong config.yml.
