### ISSUE TITLE
Migrate dev fails

### ISSUE THREAD

**Issue by Sharlaan** [prisma/prisma#4870] opened 2021-01-04 10:52 UTC
## Bug description

Hello
I am following this [NestJS + Prisma / PostgreSQL tutorial](https://docs.nestjs.com/recipes/prisma#set-the-database-connection)  until this command fails :  
```sh
npx prisma migrate dev --name init --preview-feature
```
... using this env variable :  
```
DATABASE_URL="postgresql://postgres:postgres@localhost:5432/testdb?schema=public"
```
results in :  
> Environment variables loaded from .env
Prisma schema loaded from prisma\schema.prisma
Datasource "db": PostgreSQL database "testdb", schema "public" at "localhost:5432"
**Error: P1001: Can't reach database server at `localhost`:`5432`**
Please make sure your database server is running at `localhost`:`5432`.
...

I tried with other ORMs, `pg` and vanilla `psql createdb` without issue, using same connection string.

i also tried modifying `pg_hba.conf` to allow local and host for all with trust method, without success ...

## Expected behavior

I expect Prisma to connect properly, like with Sequelize/Typeorm/pg/psql ... and create the database `testdb`.

## Environment & setup

- OS: Windows 10.0.19042
- Database: PostgreSQL 13.1 (freshly installed from scratch)
- Node.js version: 15.5.0
- Prisma version: using `npx prisma` so latest 2.13.1
```

```

**Comment by tomhoule** [comment] 2021-01-04 12:47
Hi @Sharlaan, thanks for the report!

What happens if you try to connect with `psql --user postgres --password --host=127.0.0.1`? I am thinking that this could be related to socket connections vs tcp connections

**Comment by Sharlaan** [comment] 2021-01-05 18:04
Hi @tomhoule , thanks for your answer !

Works flawlessly with vanilla psql :
![image](https://user-images.githubusercontent.com/2692027/103682024-96423500-4f88-11eb-9eaa-c70dd20ed726.png)

**Comment by jthn** [comment] 2021-01-11 17:29
> I am following this [NestJS + Prisma / PostgreSQL tutorial](https://docs.nestjs.com/recipes/prisma#set-the-database-connection) until this command fails :

@Sharlaan, I could be mistaken about this (and would love clarification if I am wrong), but I don't believe that the migrate command creates the initial database.

Also, the tutorial you linked is using SQLite, which doesn't require anything except a file (don't quote me on that, but it is much simpler). You might note in the expanded section on MySQL/Postgres, they reference the process for creating a database.

When I have set this up on my end, I had to create the database myself. To be honest, I'd love it if the tool would take care of creation for me (one less thing to document), but I don't think it does.

**Comment by pantharshit00** [comment] 2021-01-15 16:52
@Sharlaan I am unable to reproduce as well. Can you try `127.0.0.1` instead of localhost once? Maybe host is blocked somehow.

**Comment by Jolg42** [comment] 2021-02-02 15:23
Closing for now, happy to reopen if needed.

**Closed by Jolg42** 2021-02-02 15:23 UTC
Labels: bug/0-needs-info, kind/bug, team/migrations, topic: migrate

**Comment by ryanhefner** [comment] 2021-03-30 19:46
@Jolg42 @pantharshit00 I have been running into this issue for the past day or so, no matter what I set for the `DATABASE_URL=postgresql://postgres:postgres@database:5432/prisma`, I keep getting the following error:

```
Error: P1001: Can't reach database server at `database`:`5432`
```

Seems to be associated with updating from `@prisma/cli` to `prisma`, but I’m not 100% sure about that. I have tried, `database`, `127.0.0.1` and `localhost`, all resulting in the same error. I would occasionally run into it previously, but not so much when running migrations, just if the Docker containers were up for a while, but restarting the `database` server would typically resolve it.

Any help or insights would be greatly appreciated. Thanks!

**Comment by janpio** [comment] 2021-03-30 21:57
Does `prisma db pull` work @ryanhefner? Or using Prisma Client?

**Comment by ryanhefner** [comment] 2021-03-31 00:39
@janpio Actually, I think this, #6321, will solve the issue I am having. Or, at least get me a bit closer to solving the issue. Any idea when you plan on releasing that fix?

**Comment by janpio** [comment] 2021-03-31 07:33
Today, but I do not see any relation to this problem here at all. The PR you linked to only fixes a problem you have when running a global installation of Prisma with the newest version 2.20.0, via `npm install -g prisma`.

**Comment by ryanhefner** [comment] 2021-03-31 12:02
@janpio Well, it’s kind of a two parter. And, I wasn't sure if the older version of `prisma` that I was targeting previously `2.19.1` due to the issues in `2.20.0` supported what I was/am trying to do. I was able to work around it, but based on conversations I have seen in other threads, it sounds like following `DATABASE_URL=postgresql://postgres:postgres@database:5432/prisma` should be supported, but I am getting the following error when running, `npx prisma migrate dev --name init`:

``` 
(node:486) [DEP0131] DeprecationWarning: The legacy HTTP parser is deprecated.
Prisma schema loaded from prisma/schema.prisma
Datasource "db": PostgreSQL database "prisma", schema "public" at "database:5432"

Error: P1001

Can't reach database server at `database`:`5432`

Please make sure your database server is running at `database`:`5432`.
```

My setup is in Docker, I have three individual services running, `client`, `database`, `graphql`. I am trying to run that command from the `graphql` CLI.

Since that wasn't working, I ended up running the command from outside the Docker instance, `cd`ing into my `services/graphql` directory in my project and running the following:

```
export DATABASE_URL=postgresql://postgres:postgres@127.0.0.1:5432/prisma
npx prisma migrate dev --name init
```

This same approach was working previously, but I was having issues with the `@prisma/client` being able to connect to `postgresql://postgres:postgres@database:5432/prisma`, but it seems to be working now. Just not for the `prisma` CLI...🤷‍♂️

I hope that clears up what I was running into, and happy to share more details about my setup to try to help solve the issue. I also forked the `prisma` repo and am checking out the code as well to see if I can pinpoint what is going on.

**Comment by Jolg42** [comment] 2021-03-31 12:18
@ryanhefner so if you still have an issue with Prisma CLI creating [a separate issue](https://github.com/prisma/prisma/issues/new/choose) with more info would help.

**Comment by ryanhefner** [comment] 2021-03-31 13:36
@Jolg42 Oh, sorry, I figured it might be better to reference this old issue, since it still applies, opposed to opening a new one. Just based on what you said above:

> Closing for now, happy to reopen if needed.

But, I can open a separate issue if that works better for you.

**Comment by Jolg42** [comment] 2021-03-31 13:41
@ryanhefner Indeed! No worries, please open a new one since your problem might be different and we couldn't reproduce this "old" issue with the current information provided by the original author.

**Comment by janpio** [comment] 2021-03-31 21:27
And please include the answer to these questions in the issue: https://github.com/prisma/prisma/issues/4870#issuecomment-810604284

**Comment by sylque** [comment] 2022-09-29 12:51
I had the same issue and solved it by manually creating the database, as the migrate command doesn't do it. Thanks for the tip @jthn.

I think this issue should be reoppened, as the prisma error message is wrong and misleading: "Error: P1001: Can't reach database server at localhost:5432" should rather be "Error: non-existent database 'mydb'".
