### ISSUE TITLE
Wrong query when using "every" on many-to-many relation

### ISSUE THREAD

**Issue by redeyecz** [prisma/prisma#6441] opened 2021-04-07 08:41 UTC
## Bug description

When using "every" filter in many-to-many reference, the produced query is wrong and returns wrong data

### Either:
1. clone https://github.com/redeyecz/prisma-bug2
2. run docker-compose up
3. go to http://localhost:3000
4. check logs - validate query, see that it's wrong

### Or:

1. Create prisma schema like this one
```prisma
model Account {
  id         BigInt   @id @default(autoincrement())
  name       String
  dateInsert DateTime @default(now())

  accountSubjects   AccountSubject[]
  subjects          Subject[]
  @@map("account")
}

model AccountSubject {
  id         BigInt    @id @default(autoincrement())
  accountId  BigInt
  subjectId  BigInt

  account Account @relation(fields: [accountId], references: [id])
  subject Subject @relation(fields: [subjectId], references: [id])

  @@map("account_subject")
}

model Subject {
  id              BigInt   @id @default(autoincrement())
  accountInsertId BigInt
  accountInsert   Account  @relation(fields: [accountInsertId], references: [id])

  accountSubjects   AccountSubject[]
  @@map("subject")
}
```

2. insert a new account and new subject, but NO accountSubject
3. run this query, expecting zero results
```javascript
this.prisma.subject.findMany({
  where: {
    accountSubjects: {
      every: {
        accountId: account.id, /* set the id */
      },
    },
  },
});
```
4. be sad, because it returns subject even though it has no links
5. check query logs and be surprised to see this query (shortened select and prefixes for more clarity)
```sql
SELECT *
FROM "subject" s
WHERE (s."id") NOT IN (SELECT "t0"."id" /* <<<<========= What? Why is it negating? */
    FROM "subject" AS "t0"
    INNER JOIN "account_subject" AS "j0" ON ("j0"."subjectId") = ("t0"."id")
    WHERE ((NOT "j0"."accountId" = $1) AND "t0"."id" IS NOT NULL)) /* <<<<<============ what is that "NOT" doing there? :| */
OFFSET $2
```

## Expected behavior

The docs imply that "every" in this case should return no records of subject, since no accountSubject with accountId = X exist

## Environment & setup
Node 14.16

OS: Windows running WSL2, Docker-engine running Debian 10 (buster) based linux
Database: Postgres 13.2 (Docker based on alpine image)
Node.js version: v14.16.0
Prisma version: 2.20.1

```
prisma               : 2.20.1
@prisma/client       : 2.20.1
Current platform     : debian-openssl-1.1.x
Query Engine         : query-engine 60ba6551f29b17d7d6ce479e5733c70d9c00860e (at node_modules/@prisma/engines/query-engine-debian-openssl-1.1.x)
Migration Engine     : migration-engine-cli 60ba6551f29b17d7d6ce479e5733c70d9c00860e (at node_modules/@prisma/engines/migration-engine-debian-openssl-1.1.x)
Introspection Engine : introspection-core 60ba6551f29b17d7d6ce479e5733c70d9c00860e (at node_modules/@prisma/engines/introspection-engine-debian-openssl-1.1.x)
Format Binary        : prisma-fmt 60ba6551f29b17d7d6ce479e5733c70d9c00860e (at node_modules/@prisma/engines/prisma-fmt-debian-openssl-1.1.x)
Default Engines Hash : 60ba6551f29b17d7d6ce479e5733c70d9c00860e
Studio               : 0.365.0
```

**Comment by matthewmueller** [comment] 2021-04-14 12:42
Might be related to https://github.com/prisma/prisma/issues/6456

**Comment by pantharshit00** [comment] 2021-04-14 12:55
Closing as duplicate of #6456. That bug is confirmed and it describes the same issue as this one.

**Closed by pantharshit00** 2021-04-14 12:55 UTC
Labels: bug/1-repro-available, kind/bug, team/client
