### ISSUE TITLE
ERROR: permission denied for database xxxxx

### ISSUE THREAD

**Issue by ChukkyKatz** [prisma/prisma#4568] opened 2019-05-20 21:54 UTC
Prisma does not connect to external database and throw exception (no problems with connectivity using any database management tools):

prisma-server_1  | No log level set, defaulting to INFO.
prisma-server_1  | Exception in thread "main" org.postgresql.util.PSQLException: ERROR: permission denied for database mydatabase
prisma-server_1  |      at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2433)
prisma-server_1  |      at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2178)
prisma-server_1  |      at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:306)
prisma-server_1  |      at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:441)
prisma-server_1  |      at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:365)
prisma-server_1  |      at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:155)
prisma-server_1  |      at org.postgresql.jdbc.PgPreparedStatement.execute(PgPreparedStatement.java:144)
prisma-server_1  |      at slick.jdbc.StatementInvoker.results(StatementInvoker.scala:38)
prisma-server_1  |      at slick.jdbc.StatementInvoker.iteratorTo(StatementInvoker.scala:21)
prisma-server_1  |      at slick.jdbc.Invoker.first(Invoker.scala:30)
prisma-server_1  |      at slick.jdbc.Invoker.first$(Invoker.scala:29)
prisma-server_1  |      at slick.jdbc.StatementInvoker.first(StatementInvoker.scala:15)
prisma-server_1  |      at slick.jdbc.StreamingInvokerAction$HeadAction.run(StreamingInvokerAction.scala:52)
prisma-server_1  |      at slick.jdbc.StreamingInvokerAction$HeadAction.run(StreamingInvokerAction.scala:51)
prisma-server_1  |      at slick.dbio.DBIOAction$$anon$4.$anonfun$run$3(DBIOAction.scala:239)
prisma-server_1  |      at scala.collection.Iterator.foreach(Iterator.scala:937)
prisma-server_1  |      at scala.collection.Iterator.foreach$(Iterator.scala:937)
prisma-server_1  |      at scala.collection.AbstractIterator.foreach(Iterator.scala:1425)
prisma-server_1  |      at scala.collection.IterableLike.foreach(IterableLike.scala:70)
prisma-server_1  |      at scala.collection.IterableLike.foreach$(IterableLike.scala:69)
prisma-server_1  |      at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
prisma-server_1  |      at slick.dbio.DBIOAction$$anon$4.run(DBIOAction.scala:239)
prisma-server_1  |      at slick.dbio.DBIOAction$$anon$4.run(DBIOAction.scala:237)
prisma-server_1  |      at slick.basic.BasicBackend$DatabaseDef$$anon$2.liftedTree1$1(BasicBackend.scala:275)
prisma-server_1  |      at slick.basic.BasicBackend$DatabaseDef$$anon$2.run(BasicBackend.scala:275)
prisma-server_1  |      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
prisma-server_1  |      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
prisma-server_1  |      at java.lang.Thread.run(Thread.java:748)

docker-compose.yml:
~~~
version: "3"

services:

  prisma-server:
    image: prismagraphql/prisma:1.32
    restart: always
    ports:
      - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        managementApiSecret: ${PRISMA_MANAGEMENT_API_SECRET}
        port: 4466
        databases:
          default:
            connector: postgres
            host: my.app.db
            port: 5432
            database: mydatabase
            schema: myschema
            user: testuser
            password: testuser
            migrations: false
    networks:
      my-network:
        aliases:
          - my.prisma.server

networks:
  my-network:
    external: true
~~~

Granted permissions:
    CREATE ROLE testuser NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT LOGIN ENCRYPTED PASSWORD 'testuser';
    CREATE DATABASE mydatabase;
    GRANT CONNECT on DATABASE mydatabase TO testuser;
    CREATE SCHEMA IF NOT EXISTS myschema AUTHORIZATION testuser;
    GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA myschema TO testuser;

 - Connector: postgres
 - Prisma Server: 1.27, 1.32
 - `prisma` CLI: any
 - OS: Ubuntu 16.04
 - PostgreSQL database: 11.3

**Comment by divyenduz** [comment] 2019-05-22 15:19
Closing this as the duplicate of https://github.com/prisma/prisma/issues/4520

Please re-open a new issue if you think that this issue is separate from the other one.

**Closed by divyenduz** 2019-05-22 15:19 UTC
Labels: area/deploy

**Comment by brankoterzicinstana** [comment] 2020-11-26 11:29
The link is borked

**Comment by divyenduz** [comment] 2020-11-26 13:23
Thanks, fixed it
