### ISSUE TITLE
Allow inline many-to-many relation syntax for mongoDB

### ISSUE THREAD

**Issue by tomhoule** [prisma/prisma#10105] opened 2021-11-04 12:19 UTC
There is an untested feature on mongodb that the query engine relies on: embedded inline many-to-many relations:

```prisma
model A {
    id  String  @id @map("_id") @db.ObjectId
    gql String?

    b_ids String[] @db.Array(ObjectId)
    bs    B[]      @relation(fields: [b_ids])
}

model B {
    id  String  @id @map("_id") @db.ObjectId
    gql String?

    a_ids String[] @db.Array(ObjectId)
    as    A[]      @relation(fields: [a_ids])
}
```

We improved relation validations recently, and that case that slipped through now triggers a working validation error. Unfortunately, this version of many to many relations on mongo doesn't follow the same pattern and it became impossible to write it the way the Query Engine expects it. We should stop validating that the types of the referencing fields match the referenced fields on MongoDB as a first fix, then validate that the type of the embedded IDs in the array match the type of the id field in the referenced records, maybe as a second pull request. We could assume it is always ObjectId, but I don't have enough mongo knowledge to say if that assumption will hold, so let's do go with the laxer solution first.

**Comment by Jolg42** [comment] 2021-11-05 08:35
We just released a patch, you can now use the [`3.4.1`](https://github.com/prisma/prisma/releases/tag/3.4.1) version that includes the fix.

**Comment by tomhoule** [comment] 2021-11-05 08:39
Let's reopen this, because there is more work to be done for a proper solution. The patch release fix simply skipped the validation, but we should adapt it.

**Comment by janpio** [comment] 2022-01-28 23:20
Internal discussion lead to a decision here, and the work will most probably be represented in a new issue. When that is created, we can close this one.

**Comment by floelhoeffel** [comment] 2022-02-02 10:06
Duplicate of #11553

**Closed by floelhoeffel** 2022-02-02 10:06 UTC
Labels: bug/2-confirmed, kind/bug, process/candidate, topic: schema validation, engines/data model parser, team/migrations, topic: mongodb, team/psl-wg
