### ISSUE TITLE
Rename connect/disconnect to link/unlink (or something else)

### ISSUE THREAD

**Issue by steebchen** [prisma/prisma#4360] opened 2020-11-25 16:21 UTC
## Problem

There's $connect and $disconnect. Setting foreign keys is also called connect and disconnect, which I think is confusing.

## Suggested solution

- Deprecate `connect` and `disconnect`.
- Introduce `link` and `unlink` respectively, or think of another naming.

**Comment by janpio** [comment] 2021-04-07 12:14
Duplicate of https://github.com/prisma/prisma/issues/5327

**Closed by janpio** 2021-04-07 12:14 UTC
Labels: kind/improvement, team/client
