### ISSUE TITLE
Invalid client generation when use model named "Record"

### ISSUE THREAD

**Issue by oceandrama** [prisma/prisma#5500] opened 2021-02-05 18:40 UTC
## Bug description

If you use model named `Record` in your `schema.prisma`, this leads to errors
For example, there is `_Strict` type in `.prisma/client/index.d.ts` file:
```
type _Strict<U, _U = U> = U extends unknown ? U & OptionalFlat<Record<Exclude<Keys<_U>, keyof U>, never>> : never;
```
You can see using type `Record` which should be described in `typesript/lib/lib.es5.d.ts`
But if you have your own `Record` model, its type shadowed typescript definition, and many types in `.prisma/client/index.d.ts` file are inferred incorrectly

## How to reproduce

1. Create a schema with `User` and `Record` models
2. Generate prisma client
3. Try to call `prisma.user.count()`

## Expected behavior

Result type should be `number`

## Environment & setup
- OS: Windows
- Database: PostgreSQL
- Node.js version: 14.15.4
- Prisma version: 2.16.0

**Comment by oceandrama** [comment] 2021-02-11 03:41
@timsuchanek Can you please investigate this? It's blocking update to Prisma v 2.16.0 and further

**Comment by pantharshit00** [comment] 2021-02-11 13:30
I can confirm this. Looks like similar problem to https://github.com/prisma/prisma/issues/4892. We should fix this.

**Comment by timsuchanek** [comment] 2021-02-11 17:33
Thanks a lot for reporting 🙏
This issue is fixed in the latest dev version of `@prisma/client`.
You can try it out with `npm i @prisma/client@dev`.

In case it’s not fixed for you - please let us know and we’ll reopen this issue!

**Closed** 2021-02-11 17:32 UTC
Labels: bug/2-confirmed, kind/bug, team/client, tech/typescript, topic: types

**Comment by pimeys** [comment] 2021-02-12 14:33
Tested with 2.17.0-dev.60:

```prisma
datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

generator client {
  provider = "prisma-client-js"
}

model User {
  id     Int   @id @default(autoincrement())
  userId Int?
  user   User? @relation(fields: [userId], references: [id])
}

model Record {
  id Int @id @default(autoincrement())
}
```

code:

```javascript
import { PrismaClient } from '@prisma/client'

const prisma = new PrismaClient()

async function main() {
  let count = await prisma.user.count();
  console.log(count)
}

main()
  .catch(e => {
    throw e
  })
  .finally(async () => {
    await prisma.$disconnect()
  })
```

and out comes a number.
