### ISSUE TITLE
OR operator behaving like AND

### ISSUE THREAD

**Issue by Akxe** [prisma/prisma#4831] opened 2020-12-31 01:03 UTC
## Bug description

Generated query with `OR` uses `AND` instead.

## How to reproduce

With any schema, use query with `OR` in ˙where˙.

```ts
const carriersToProcess = await prisma.carrier.findMany({
	select: {
		carrierID: true,
		lat: true,
		lng: true,
	},
	where: {
		lat: { gt: 0 },
		lng: { gt: 0 },
		origin: { not: { equals: 'S' } },
		OR: {
			regionID: { equals: null },
			districtID: { equals: null },
		},
	},
})
```

## Actual behavior

```sql
SELECT `db`.`carrier`.`carrierID`, `db`.`carrier`.`lat`, `db`.`carrier`.`lng` FROM `db`.`carrier` 
WHERE (
`db`.`carrier`.`lat` > ? AND 
`db`.`carrier`.`lng` > ? AND 
`db`.`carrier`.`Zdroj` <> ? AND (
  `db`.`carrier`.`regionID` IS NULL AND 
  `db`.`carrier`.`districtID` IS NULL )
) 
ORDER BY `db`.`carrier`.`carrierID` ASC LIMIT ? OFFSET ?
```

## Expected behavior

```sql
SELECT `db`.`carrier`.`carrierID`, `db`.`carrier`.`lat`, `db`.`carrier`.`lng` FROM `db`.`carrier` 
WHERE (
`db`.`carrier`.`lat` > ? AND 
`db`.`carrier`.`lng` > ? AND 
`db`.`carrier`.`Zdroj` <> ? AND (
  `db`.`carrier`.`regionID` IS NULL OR 
  `db`.`carrier`.`districtID` IS NULL )
) 
ORDER BY `db`.`carrier`.`carrierID` ASC LIMIT ? OFFSET ?
```

## Environment & setup

- OS: Windows
- Database: MySQL
- Node.js version: v12.16.1
- Prisma version:

```
@prisma/cli          : 2.12.1
@prisma/client       : 2.12.1
Current platform     : windows
Query Engine         : query-engine cf0680a1bfe8d5e743dc659cc7f08009f9587d58 (at node_modules\@prisma\engines\query-engine-windows.exe)
Migration Engine     : migration-engine-cli cf0680a1bfe8d5e743dc659cc7f08009f9587d58 (at node_modules\@prisma\engines\migration-engine-windows.exe)
Introspection Engine : introspection-core cf0680a1bfe8d5e743dc659cc7f08009f9587d58 (at node_modules\@prisma\engines\introspection-engine-windows.exe)
Format Binary        : prisma-fmt cf0680a1bfe8d5e743dc659cc7f08009f9587d58 (at node_modules\@prisma\engines\prisma-fmt-windows.exe)
Studio               : 0.322.0
```

**Comment by Sytten** [comment] 2020-12-31 18:23
This is the expected behaviour, pass an array of objects to the OR instead of one object.

**Comment by Akxe** [comment] 2020-12-31 20:08
Why is the object slowed then? Shouldn't it require an array of objects?

**Comment by Sytten** [comment] 2021-01-01 00:23
Don't know, @timsuchanek most likely has an answer. I would guess there is a particular query that needs a single object.

**Comment by Akxe** [comment] 2021-01-01 13:36
It is really confusing behaviour to me. It this is a wanted solution I would suggest having more info on it in docs

**Comment by pantharshit00** [comment] 2021-01-01 14:56
This is expected as pointed out by @Sytten 

All filters on a single level is joined via `AND`. Top level filters are joined via `AND` and filters inside of `OR` is joined via `AND` on a single array item level. OR connects each object of filters on an array with the `OR` operator. 

This is documented via https://github.com/prisma/prisma/issues/2126 which I opened a while ago. 

But the bug here is we shouldn't be having `OR` as enumerable as per https://github.com/prisma/prisma-client-js/issues/657 which changed the behaviour but looks like it got reverted in refactoring so I am marking this as a bug and I will talk to relevant people here.

**Comment by Sytten** [comment] 2021-01-01 17:16
@pantharshit00 correction on your comment for clarity, it should only be an array. You wrote the inverse :)

**Comment by timsuchanek** [comment] 2021-01-06 13:28
We need to change this in the DMMF, therefore this is an engines issue.

**Comment by williamluke4** [comment] 2021-01-06 15:54
![image](https://user-images.githubusercontent.com/10773719/103789017-9574d600-5050-11eb-8d98-322d6036a8e9.png)

**Closed** 2021-01-14 17:37 UTC
Labels: bug/2-confirmed, kind/bug, team/client, tech/engines, topic: filter
