### ISSUE TITLE
called `Option::unwrap()` on a `None` value

### ISSUE THREAD

**Issue by Shakib448** [prisma/prisma#21661] opened 2023-10-28 12:14 UTC
Hi Prisma Team! My Prisma Client just crashed. This is the report:
## Versions

| Name            | Version            |
|-----------------|--------------------|
| Node            | v18.15.0           | 
| OS              | darwin-arm64       |
| Prisma Client   | 5.5.2              |
| Query Engine    | aebc046ce8b88ebbcb45efe31cbe7d06fd6abc0a|
| Database        | postgresql         |

## Logs
```
d: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
```

## Client Snippet
```ts
  async findOne(id: number) {
    const exists = await this.prisma.products.findFirst({
      where: { id },
      include: {
        admin: { select: { id: true, full_name: true } },
        brands: {
          select: {
            name: true,
            logo: true,
            banner: true,
            meta_description: true,
          },
        },
        units: {
          select: {
            name: true,
          },
        },
        categories: true,
        variations: {
          include: {
            attributes: true,
            attribute_values: true,
          },
        },
      },
    });

    if (!exists) throw new ForbiddenException('No product found');

    return exists;
  }
```

## Schema
```prisma
model products {
  id                  Int      @id @default(autoincrement())
  name                String   @db.VarChar(200)
  origin              String?  @db.VarChar(255)
  brand_id            Int?
  images              String?  @db.VarChar(2000)
  img                 String[]
  thumbnail_img       String?  @db.VarChar(2000)
  is_variant          Int      @default(0) @db.SmallInt
  stock               Int      @default(0)
  price               Float    @default(0)
  lowest_price        Float    @default(0)
  highest_price       Float    @default(0)
  purchase_price      Float    @default(0)
  tags                String?
  description         String?
  rating              Int      @default(5)
  published           Boolean  @default(true)
  pre_order           Boolean  @default(false)
  best_selling        Boolean  @default(false)
  featured            Boolean  @default(false)
  premium             Boolean  @default(false)
  unit_id             Int?
  sku                 String?  @db.VarChar(255)
  alert_qty           Int?
  discount            Float?
  discount_type       String?  @db.VarChar(50)
  discount_start_date String?  @db.VarChar(255)
  discount_end_date   String?  @db.VarChar(255)
  info                String?  @db.VarChar(255)
  meta_title          String?
  meta_description    String?
  meta_img            String?  @db.VarChar(2000)
  slug                String?
  has_offer           Boolean  @default(false)
  ever_offered        Boolean  @default(false)
  offer_image         String?  @db.VarChar(100)
  duplicate_counter   Int      @default(0)
  expiry_date         String?  @db.VarChar(255)
  created_at          DateTime @default(now()) @db.Timestamptz(6)
  updated_at          DateTime @default(now()) @db.Timestamptz(6)

  admin_id            Int?
  admin               admin?                @relation(fields: [admin_id], references: [id])
  brands              brands?               @relation(fields: [brand_id], references: [id])
  units               units?                @relation(fields: [unit_id], references: [id])
  attributes          attributes[]          @relation("product_attributes")
  categories          categories[]          @relation("product_categories")
  variations          variations[]          @relation("product_variations")
  highlight           highlight[]           @relation("product_highlight")
  stocks              stocks[]
  stock_order_history stock_order_history[]
  order_details       order_details[]

  @@index([id, name, slug])
}

```

## Prisma Engine Query
```
{"X":true}}}}}
```

**Comment by miguelff** [comment] 2023-10-30 11:51
Thanks for your report @Shakib448 

I notice the schema file is incomplete, and we cannot reproduce the issue would you mind linking a full reproduction? in particular a schema containing the data source, and generator block, and the models involved in the offending query?

Thank you so much.

**Comment by millsp** [comment] 2023-11-07 02:17
@Shakib448 did you see the message from @miguelff ? Without additional information to be able to reproduce, we would later close this issue as part of our issue process.

**Comment by Shakib448** [comment] 2023-11-07 02:29
@millsp Sorry for late reply. After update prisma version the issue was fixed. Thanks for your response.

**Closed** 2023-11-07 12:21 UTC
Labels: bug/0-unknown, kind/bug, team/client, topic: rust panic, 5.5.x
