### ISSUE TITLE
Type safety for Json

### ISSUE THREAD

**Issue by pandaniell** [prisma/prisma#4628] opened 2020-12-14 10:09 UTC
## Problem
When you use a Json type, any set of properties are accepted, it would be nice to generate types for that as well
```prisma
model Shop {
  paymentInfo Json
}
```

```ts
prisma.shop.create({ paymentInfo: { } })
```

## Suggested solution
Allow specific types to be created
```prisma
type PaymentInfo: Json {
  holder String
  address String
  name String?
}

model Shop {
  paymentInfo PaymentInfo
}
```

```ts
prisma.shop.create({
  paymentInfo: {
    holder: ""
    // Error, address missing
  }
})
```

## Alternatives
A generic parameter for common methods (not really a solution, still causes duplicate code)
```ts
interface PaymentInfo {
  holder: string
  address: string
  name?: string
}

prisma.shop.create<{ paymentInfo: PaymentInfo }>()
```

**Comment by pantharshit00** [comment] 2020-12-15 13:34
Hi,

Thanks for reporting this! It has already been reported before, so I am going to close this as a duplicate of https://github.com/prisma/prisma/issues/3219

**Closed by pantharshit00** 2020-12-15 13:34 UTC
