### ISSUE TITLE
Sort by relational fields

### ISSUE THREAD

**Issue by ragnorc** [prisma/prisma#2090] opened 2020-04-04 10:56 UTC
Is there currently the possibility to sort by attributes of relational fields?

**Comment by pantharshit00** [comment] 2020-04-07 17:19
Hi,

Thanks for reporting this! It has already been reported before, so I am going to close this as a duplicate of https://github.com/prisma/prisma-client-js/issues/249

**Closed by pantharshit00** 2020-04-07 17:19 UTC
