### ISSUE TITLE
Enable support for Amazon Aurora Serverless Data API

### ISSUE THREAD

**Issue by imankamyabi** [prisma/prisma#6438] opened 2021-04-06 22:51 UTC
## Problem

Amazon RDS (Aurora Serverless) Data API feature provides an HTTP endpoint and uses IAM roles to authenticate to that endpoint. So the ask here is to support that form of authentication. Since the public endpoint is not available for Aurora serverless, this feature is required in order to use/authenticate to a serverless rds cluster.

## Suggested solution

Once the SQL is generated, instantiate an AWS RDS client and execute the SQL query:
https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/rds.html#client

**Comment by janpio** [comment] 2021-04-07 10:14
Duplicate of https://github.com/prisma/prisma/issues/1964

**Closed by janpio** 2021-04-07 10:14 UTC
