### ISSUE TITLE
Introspection: Automatic map columns to something sane

### ISSUE THREAD

**Issue by Notaduck** [prisma/prisma#16000] opened 2022-10-26 08:44 UTC
## Problem

I'm working with multiple databases made by different people and the formatting of tables and columns is not consistent.

## Suggested solution

I know we have the `@map(.....` property, but it would be nice if we could set a default config for prisma so when we do an `prisma introspect` and it would automaticly map `SOME_TABLE` to `some_table` or `someTable` instead of doing that manually if the database has 100 tables and each table has +5 coulmns.

**Comment by Jolg42** [comment] 2022-10-26 09:46
I think this request might be a duplicate of https://github.com/prisma/prisma/issues/1934 / https://github.com/prisma/prisma/issues/1705

What do you think @Notaduck ?

**Comment by itayperry** [comment] 2023-07-04 14:12
+1
This would be an amazing feature!

**Comment by Notaduck** [comment] 2023-07-07 11:26
@Jolg42 sorry for the VERY late reply, I totally missed it. But you are absolutely right! That is more or less what I asked for.

**Comment by janpio** [comment] 2023-07-09 09:33
Let's track it via those issues then 👍

**Closed by janpio** 2023-07-09 09:33 UTC
Labels: kind/feature, topic: introspection, topic: dx, topic: introspection-configuration, team/schema, topic: prisma db pull, topic: @map
