### ISSUE TITLE
`$on` query event subscriptions for extended clients actually get applied to the underlying base client

### ISSUE THREAD

**Issue by mziwisky** [prisma/prisma#18724] opened 2023-04-13 06:48 UTC
### Bug description

with an express app, I want to log every SQL query with its associated request ID (e.g. see https://github.com/prisma/prisma/issues/7596).  i thought i might be able to pull this off by creating an extended client per request [as suggested here](https://github.com/prisma/prisma/issues/6882#issuecomment-1377637971), but when i attach a `'query'` event listener to the extended client, it actually gets applied to the base client instead.

same thing is described here: https://github.com/prisma/prisma/issues/16500#issuecomment-1432958524 (the comment right after that one requests that the poster open a new issue for this, but i couldn't find one, so i'm opening this one)

### How to reproduce

```js
const extended1 = prismaClient.$extends({});
extended1.$on('query', (e) => {
  console.log('query from ext1');      
});
const extended2 = prismaClient.$extends({});
extended2.$on('query', (e) => {
  console.log('query from ext2');      
});
await extended1.user.count()
// log: query from ext1
// log: query from ext2
```

### Expected behavior

there should only be one log line, `query from ext1`

### Prisma information

issue is independent of any particular prisma schema

### Environment & setup

- OS: macOS
- Database: PostgreSQL
- Node.js version: v16.14.0

### Prisma Version

```
prisma                  : 4.7.1
@prisma/client          : 4.7.1
Current platform        : darwin-arm64
Query Engine (Node-API) : libquery-engine 272861e07ab64f234d3ffc4094e32bd61775599c (at node_modules/@prisma/engines/libquery_engine-darwin-arm64.dylib.node)
Migration Engine        : migration-engine-cli 272861e07ab64f234d3ffc4094e32bd61775599c (at node_modules/@prisma/engines/migration-engine-darwin-arm64)
Introspection Engine    : introspection-core 272861e07ab64f234d3ffc4094e32bd61775599c (at node_modules/@prisma/engines/introspection-engine-darwin-arm64)
Format Binary           : prisma-fmt 272861e07ab64f234d3ffc4094e32bd61775599c (at node_modules/@prisma/engines/prisma-fmt-darwin-arm64)
Format Wasm             : @prisma/prisma-fmt-wasm 4.7.1-1.272861e07ab64f234d3ffc4094e32bd61775599c
Default Engines Hash    : 272861e07ab64f234d3ffc4094e32bd61775599c
Studio                  : 0.477.0
```

**Comment by SevInf** [comment] 2024-08-08 09:34
Hi @mziwisky.
At the time, it was sort of by design. As of now, we actually disallow using `$on` after extends — all event handlers are supposed to be added to the client before any extensions. So, I am going to close this issue for now since it is no longer possible to do in a recent versions

**Closed by SevInf** 2024-08-08 09:34 UTC
Labels: bug/1-unconfirmed, kind/bug, tech/typescript, domain/client, topic: extend-client
