### ISSUE TITLE
Having model "ModelName" and "ModelNameUpdate" does not throw an error, but overwrites type

### ISSUE THREAD

**Issue by Nmans01** [prisma/prisma#20011] opened 2023-06-29 17:35 UTC
### Bug description

In my project, I had models WorkOrder and WorkOrderUpdate. When writing client queries, I was getting errors when trying to include fields from WorkOrderUpdate while finding many WorkOrders. This is because the WorkOrderUpdate type was referring to the type meant for calling workOrder.update() rather than the type for querying.

### How to reproduce

1. Create models "ModelName" and "ModelNameUpdate" with relation in schema, and generate client.
2. Prisma generates client types, presumably writes over ModelNameUpdate twice.
3. Call `prisma.modelName.findMany({include: {modelNameUpdateRelationName: { sender: true }})`
4. Since sender is a field on ModelNameUpdate but not on ModelName update, TypeScript should give an error

### Expected behavior

Throw an error in the schema when I have a model X and I try to make another model called XUpdate.

### Prisma information

```prisma
// Add your schema.prisma

model WorkOrder {
  id                String            @id @default(uuid())
  number            Int               @default(autoincrement())
  apartment         Apartment         @relation(fields: [apartmentId], references: [id])
  apartmentId       String
  subject           String
  description       String
  creator           User              @relation(name: "creator", fields: [creatorId], references: [id])
  creatorId         String
  assignee          User?             @relation(fields: [assigneeId], references: [id])
  assigneeId        String? // Must be user of type Contractor or Landlord
  currentStatus     WorkOrderUpdate   @relation(name: "pointsToCurrentStatus", fields: [currentStatusId], references: [id])
  currentStatusId   String            @unique
  completed         Boolean
  created           DateTime          @default(now())
  updates           WorkOrderUpdate[]
  userId            String
}

model WorkOrderUpdate {
  id                String     @id @default(uuid())
  workOrder         WorkOrder  @relation(fields: [workOrderId], references: [id])
  workOrderId       String
  user              User       @relation(fields: [userId], references: [id])
  userId            String
  message           String?
  status            Status?
  created           DateTime   @default(now())
  currentStatusOf   WorkOrder? @relation("pointsToCurrentStatus")
  currentStatusOfId String?
}
```

```ts
// Add your code using Prisma Client

this.prisma.workOrder.findMany({
          include: {
            creator: true,
            apartment: true,
            currentStatus: { include: { 
                   user: true // <------- Error line here: Object literal may only specify known properties, and 'user' does not exist in type 'WorkOrderInclude<DefaultArgs>'.ts(2322)
             } }
          }
        });
```

### Environment & setup

- OS:  Windows
- Database: PostgreSQL
- Node.js version: v18.16.0

### Prisma Version

```
4.16.1
```

**Comment by SevInf** [comment] 2023-06-30 07:33
Duplicate of #9568 
I am going to close this issue in favor of the older one. You can track progress there.

**Closed by SevInf** 2023-06-30 07:33 UTC
Labels: kind/bug
