### ISSUE TITLE
Can't reach database server at public ip `xxx.x.xx.xx` on Node 18 only

### ISSUE THREAD

**Issue by joshuacue** [prisma/prisma#18640] opened 2023-04-05 18:29 UTC
### Bug description

After upgrading to Node v18.12.1 I'm getting this intermittent issue with 1 out of 10 chance of working when refreshing, I also tried adding the connection_timeout to the DATABASE_URL but it didn't solve it for me. However, reverting to Node 16.18.1 solved the issue, but I want to upgrade to Node 18.12.1:

```
https://next-auth.js.org/errors#session_error 
Invalid `p.session.findUnique()` invocation in
/Users/user/App/my-app/node_modules/@next-auth/prisma-adapter/dist/index.js:24:52

  21     where: { provider_providerAccountId },
  22 }),
  23 async getSessionAndUser(sessionToken) {
→ 24     const userAndSession = await p.session.findUnique(
Can't reach database server at `XX.XX.XX.XX`:`xxxx`

Please make sure your database server is running at `XX.XX.XX.XX`:`xxxx`.
    at fn.handleRequestError (/Users/user/App/my-app/node_modules/@prisma/client/runtime/library.js:174:6750)
    at fn.handleAndLogRequestError (/Users/user/App/my-app/node_modules/@prisma/client/runtime/library.js:174:5907)
    at /Users/user/App/my-app/node_modules/@prisma/client/runtime/library.js:177:3087
    at async /Users/user/App/my-app/node_modules/@prisma/client/runtime/library.js:177:3294 {
  name: 'GetSessionAndUserError',
  code: undefined
}

```

My schema.prisma
```
generator client {
  provider        = "prisma-client-js"
  previewFeatures = ["filterJson"]
}

datasource db {
  provider = "mysql"
  url      = env("DATABASE_URL")
}

model Account {
  id                String  @id @default(cuid())
  userId            String
  type              String
  provider          String
  providerAccountId String
  refresh_token     String? @db.Text
  access_token      String? @db.Text
  expires_at        Int?
  token_type        String?
  scope             String?
  id_token          String? @db.Text
  session_state     String?

  user User @relation(fields: [userId], references: [id], onDelete: Cascade)

  @@unique([provider, providerAccountId])
}

model Session {
  id           String   @id @default(cuid())
  sessionToken String   @unique
  userId       String
  expires      DateTime
  user         User     @relation(fields: [userId], references: [id], onDelete: Cascade)
}

model User {
  id                    String                 @id @default(cuid())
  name                  String?
  email                 String?                @unique
  emailVerified         DateTime?
  image                 String?
  accounts              Account[]
  sessions              Session[]
  UserProfile           UserProfile?
  UserRole              UserRole[]
  Property              Property[]
  RenterContract        Contract[]             @relation("RenterContract")
  HomeOwnerContract     Contract[]             @relation("HomeOwnerContract")
  Transaction           Transaction[]
  RentRequest           RentRequest[]
  SenderNotification    Notification[]         @relation("SenderNotification")
  RecipientNotification Notification[]         @relation("RecipientNotification")
  NotificationSettings  NotificationSettings[]
  CreatedDate           DateTime?              @default(now())
}

model VerificationToken {
  identifier String
  token      String   @unique
  expires    DateTime

  @@unique([identifier, token])
}

....
```

### Expected behavior

It should work the same as when using Node v16.18.1

### Prisma information

```prisma
generator client {
  provider        = "prisma-client-js"
  previewFeatures = ["filterJson"]
}

datasource db {
  provider = "mysql"
  url      = env("DATABASE_URL")
}

model Account {
  id                String  @id @default(cuid())
  userId            String
  type              String
  provider          String
  providerAccountId String
  refresh_token     String? @db.Text
  access_token      String? @db.Text
  expires_at        Int?
  token_type        String?
  scope             String?
  id_token          String? @db.Text
  session_state     String?

  user User @relation(fields: [userId], references: [id], onDelete: Cascade)

  @@unique([provider, providerAccountId])
}

model Session {
  id           String   @id @default(cuid())
  sessionToken String   @unique
  userId       String
  expires      DateTime
  user         User     @relation(fields: [userId], references: [id], onDelete: Cascade)
}

model User {
  id                    String                 @id @default(cuid())
  name                  String?
  email                 String?                @unique
  emailVerified         DateTime?
  image                 String?
  accounts              Account[]
  sessions              Session[]
  UserProfile           UserProfile?
  UserRole              UserRole[]
  Property              Property[]
  RenterContract        Contract[]             @relation("RenterContract")
  HomeOwnerContract     Contract[]             @relation("HomeOwnerContract")
  Transaction           Transaction[]
  RentRequest           RentRequest[]
  SenderNotification    Notification[]         @relation("SenderNotification")
  RecipientNotification Notification[]         @relation("RecipientNotification")
  NotificationSettings  NotificationSettings[]
  CreatedDate           DateTime?              @default(now())
}

model VerificationToken {
  identifier String
  token      String   @unique
  expires    DateTime

  @@unique([identifier, token])
}
```

```ts
import { PrismaAdapter } from '@next-auth/prisma-adapter';
import { db } from '../../../prisma';
import NextAuth from 'next-auth';
import GoogleProvider from 'next-auth/providers/google';
import FacebookProvider from 'next-auth/providers/facebook';

export default NextAuth({
  adapter: PrismaAdapter(db),
  // Configure one or more authentication providers
  providers: [
    FacebookProvider({
      clientId: process.env.FACEBOOK_CLIENT_ID,
      clientSecret: process.env.FACEBOOK_CLIENT_SECRET,
    }),
    GoogleProvider({
      clientId: process.env.GOOGLE_CLIENT_ID,
      clientSecret: process.env.GOOGLE_CLIENT_SECRET,
    }),
  ],
  secret: process.env.SECRET,
  callbacks: {
    async signIn({ account, profile, user }) {
      console.log('signIn-account', account, profile, user);
      if (account.provider === 'google') {
        return profile.email_verified;
      }
      return true; // Do different verification for other providers that don't have `email_verified`
    },
    async session({ session, token, user }) {
      // Send properties to the client, like an access_token from a provider.
      // session.complete_profile = false;
      console.log('Session', session, user);
      const userId = await user.id
      session.user.id = userId;
      return session;
    },
  },
  pages: {
    signIn: '/signin',
  },
});
```

### Environment & setup

- OS: macOS Ventura
- Database: MySQL
- Node.js version: 18.12.1

### Prisma Version

```
"@prisma/client": "^4.12.0
"@next-auth/prisma-adapter": "^1.0.5",
"prisma": "^4.12.0",
"next-auth": "^4.21.1"
```

**Comment by jkomyno** [comment] 2023-04-06 22:58
Hi @joshuacue, could you please share where is that MySQL server hosted? E.g., is it on PlanetScale, AWS, or on a VPS you have access to? Do you observe the same 1/10 chance with `node.js 18.15.0`?

**Comment by joshuacue** [comment] 2023-04-13 19:47
> Hi @joshuacue, here are some questions to better assess this issue.
> 
> 1. Could you please share where is that MySQL server hosted? E.g., is it on PlanetScale, AWS, or on a VPS you have access to?
> 
> 2. Do you observe the same 1/10 chance with `node.js 18.15.0`?
> 
> 3. Roughly, how many users are you processing with Prisma + NextAuth?

Hi,
1. It is on google cloud
2. Yes it is the same, something new came up, it only fails on mac m1 pro so it may also be an ARM related issue?
3. All 3 devs that connects to our staging ip, but the other 2 is on windows and it works well ontheir machine so maybe this is also ARM issue? Node 16 is acting weird now too and almost the same as the node 18.15.0 failing connections.

**Comment by joshuacue** [comment] 2023-04-13 19:49
> @jkomyno, I know this thread is not about my issue, but I wand to add to it as this is happening with my project as well.
> 
> 
> 
> I'm having the exact same issue with node v16.20.0 and I tested with v18.x too (I tested deploying it with 4 different node versions of both v16 and v18 and none worked, which make me believe it may not be node the culprit). My stack is with AWS Lambda and Mysql on RDS (multi-zone with high availability). I use prisma since version 1 (I was very glad to remove the containers) and I keep migrating every now and then.
> 
> 
> 
> My case was: I upgraded from 4.7.1 to 4.12 and it totally broke our staging, then after trying to isolate the cause deplying it every day with a new node version to confirm I finally rolled it back to 4.7.1 which made it all stable again (I haven't tested 4.11 to confirm.
> 
>  
> 
> When version 4.12 was used I checked every single log that AWS generates and only the @prisma/client was throwing the error from the request. I could connect to the DB normally from cli, dbeaver or workbench, our user load is about 10k/day. I noticed a similar behavior of it "dropping" some requests, it looks like some sort of pooling or threading that after a while it stops fetching and serving the data and only gives the connection error.
> 
> 
> 
> I was not able to find the root cause or dig in prisma source code, but I'm glad to help check if you point me where to look.

Thank you for this, I will check this as soon as I get to back to work later.

**Comment by benevbright** [comment] 2023-05-06 21:10
We're having a similar issue. The database connection is closed at some point and doesn't recover. It happens rarely but couldn't figure out when/what/why it's happening. We're using `4.9.0` version.

**Comment by Weakky** [comment] 2023-07-13 14:23
Hey @joshuacue,

Are you still experiencing this issue? Do you perhaps have any more information that could help us narrow down where the problem's coming from?

Thank you 🙏

**Comment by joshuacue** [comment] 2023-07-13 15:27
> Hey @joshuacue,
> 
> Are you still experiencing this issue? Do you perhaps have any more information that could help us narrow down where the problem's coming from?
> 
> Thank you 🙏

Hey man, unfortunately yes, and that project is done already. But I made a work around to judt connect to the local db only. I would love to give more details but Im no longer part of that project. Sorry.

**Comment by jharrell** [comment] 2023-07-26 14:26
@joshuacue thank you for your reply and your patience! We're going to close this as can't reproduce.

**Closed by jharrell** 2023-07-26 14:26 UTC
Labels: bug/0-unknown, kind/bug, team/schema
