### ISSUE TITLE
PANIC: timer has gone away

### ISSUE THREAD

**Issue by Md-Yousuf-sheikh** [prisma/prisma#25041] opened 2024-08-17 19:57 UTC
Hi Prisma Team! My Prisma Client just crashed. This is the report:
## Versions

| Name            | Version            |
|-----------------|--------------------|
| Node            | v18.20.3           | 
| OS              | debian-openssl-1.0.x|
| Prisma Client   | 5.18.0             |
| Query Engine    | 4c784e32044a8a016d99474bd02a3b6123742169|
| Database        | mysql              |

## Logs
```
prisma:tryLoadEnv Environment variables not found at null
prisma:tryLoadEnv Environment variables not found at /home/bhaira5/unifydaily-admin.wishnow.app/.env
prisma:tryLoadEnv No Environment variables loaded
prisma:client checkPlatformCaching:postinstall false
prisma:client checkPlatformCaching:ciName 
prisma:tryLoadEnv Environment variables not found at null
prisma:tryLoadEnv Environment variables not found at /home/bhaira5/unifydaily-admin.wishnow.app/.env
prisma:tryLoadEnv No Environment variables loaded
prisma:client dirname /home/bhaira5/unifydaily-admin.wishnow.app/node_modules/.prisma/client
prisma:client relativePath ../../../prisma
prisma:client cwd /home/bhaira5/unifydaily-admin.wishnow.app/prisma
prisma:client clientVersion 5.18.0
prisma:client:libraryEngine internalSetup
prisma:get-platform Don't know any platform-specific paths for "undefined" on x64 (x86_64)
prisma:get-platform Falling back to "ldconfig" and other generic paths
prisma:client:libraryEngine sending request, this.libraryStarted: false
prisma:get-platform Command "ldconfig -p | sed "s/.*=>s*//" | sed "s|.*/||" | grep libssl | sort | grep -v "libssl.so.0"" successfully returned "libssl3.so
libssl.so
libssl.so.10
libssl.so.1.1
"
prisma:get-platform Found libssl.so file using "ldconfig" or other generic paths: libssl3.so
libssl.so
libssl.so.10
libssl.so.1.1

prisma:get-platform The parsed libssl version is: 1.0.x
prisma:get-platform Distro is "undefined". Falling back to Prisma engines built for "debian".
prisma:client:engines:resolveEnginePath enginePath /home/bhaira5/unifydaily-admin.wishnow.app/node_modules/.prisma/client/libquery_engine-debian-openssl-1.0.x.so.node
prisma:client:libraryEngine library starting
```

## Client Snippet
```ts
// PLEASE FILL YOUR CODE SNIPPET HERE

const createUserIntoDB = async (props: User) => {
  const isUserExist = await prisma.user.findUnique({
    where: {
      phoneNumber: props?.phoneNumber as string,
    },
  });
  //  check is user
  if (isUserExist) {
    throw new ApiError(httpStatus.BAD_REQUEST, 'This user already existed!');
  }

  const newPassword = await isUserPasswordConvertBcrypt(props?.password);
  // database
  const res = await prisma.user.create({
    data: {
      ...props,
      password: newPassword,
    },
    select: UserSelect,
  });

  return res;
};
const loginUserWithDB = async (props: User) => {
  // database
  const res = await prisma.user.findUnique({
    where: {
      phoneNumber: props?.phoneNumber as string,
    },
  });

  if (!res) {
    throw new ApiError(httpStatus.BAD_REQUEST, "User doesn't exist!");
  }
  //
  const { password, ...responseWithoutPassword } = res;

  //
  const isMatchPassword = await isUserPasswordMatch(props?.password, password);

  if (!isMatchPassword) {
    throw new ApiError(httpStatus.BAD_REQUEST, "Password doesn't match.");
  }

  //  email and roll
  const { role, phoneNumber, id } = responseWithoutPassword;

  //  create access and refresh tokens
  const accessToken = jwtHelpers.createToken(
    { phoneNumber, role, id },
    config.jwt.secret as Secret,
    config.jwt.expires_in as string
  );
  // refresh Token
  const refreshToken = jwtHelpers.createToken(
    { phoneNumber, role, id },
    config.jwt.refresh_secret as Secret,
    config.jwt.refresh_expires_in as string
  );

  return {
    user: responseWithoutPassword,
    accessToken: accessToken,
    refreshToken: refreshToken,
  };
};
```

## Schema
```prisma
// PLEASE ADD YOUR SCHEMA HERE IF POSSIBLE
// This is your Prisma schema file,
// learn more about it in the docs: https://pris.ly/d/prisma-schema

generator client {
  provider = "prisma-client-js"
  binaryTargets = ["native","debian-openssl-1.0.x"]
}

datasource db {
  provider = "mysql"
  url      = env("DATABASE_URL")
}

// Define Role Enum
enum UserRole {
  admin
  agent
  user
}

// Define OrderStatus Enum
enum OrderStatus {
  success
  pending
  cancel
}

// Define VisitStatus Enum
enum VisitStatus {
  success
  pending
  cancel
}

model User {
  id          String        @id @default(uuid())
  name        String?
  email       String?       @unique
  phoneNumber String?       @unique
  password    String
  role        UserRole      @default(agent)
  address     String?
  profileImg  String?
  createdAt   DateTime      @default(now()) @db.Timestamp(6)
  updatedAt   DateTime      @updatedAt @db.Timestamp(6)
  Outlet      Outlet[]
  AssignRoad  AssignRoad[]
  AgentTarget AgentTarget[]

  @@map("users")
}

model Outlet {
  id           String      @id @default(uuid())
  banner       String
  visitingArea String
  location     String
  businessType String
  businessName String
  ownerName    String
  phoneNumber  String
  nextFollowup String?
  remarks      String?
  visitStatus  VisitStatus @default(pending)
  geoLocation  String?
  agentId      String
  agent        User        @relation(fields: [agentId], references: [id])

  createdAt DateTime @default(now()) @db.Timestamp(6)
  updatedAt DateTime @updatedAt @db.Timestamp(6)

  @@map("outlets")
}

model AssignRoad {
  id        String @id @default(uuid())
  agentId   String
  agent     User   @relation(fields: [agentId], references: [id])
  location  String
  startDate String
  endDate   String

  createdAt DateTime @default(now()) @db.Timestamp(6)
  updatedAt DateTime @updatedAt @db.Timestamp(6)

  @@map("assignRoads")
}

model AgentTarget {
  id          String @id @default(uuid())
  agentId     String
  agent       User   @relation(fields: [agentId], references: [id])
  month       Int
  outlet      Int
  workingDays Int
  flowUp      Int

  createdAt DateTime @default(now()) @db.Timestamp(6)
  updatedAt DateTime @updatedAt @db.Timestamp(6)

  @@map("agentTargets")
}

```

## Prisma Engine Query
```

```

**Comment by sorenbs** [comment] 2024-08-19 10:52
Hi there,

Could you try if any of these steps help?

1. First and foremost, check your .env file. Make sure it exists in the project root directory (/home/bhaira5/unifydaily-admin.wishnow.app/.env) and contains the correct DATABASE_URL.
2. Verify that your MySQL database is running and accessible using the connection string in your .env file.
3. Run npx prisma generate to ensure your Prisma Client is up-to-date with your schema.
4. If you've made any recent changes to your Prisma schema, run npx prisma migrate dev to apply those changes to your database.
5. Consider upgrading your system's OpenSSL version, as 1.0.x is quite old and might be causing compatibility issues.
6. Double-check that your Node.js version (v18.20.3) is fully compatible with Prisma 5.18.0. You might want to consider upgrading Node.js if necessary.
7. To get more detailed logs for troubleshooting, you can set the environment variable DEBUG="prisma:*" before running your application.

**Comment by SevInf** [comment] 2024-10-15 15:36
Hi @Md-Yousuf-sheikh 
Unfortunately, your code snipped is missing a lot of context needed for us to run it. Could you please provide a bug reproduction in isolated github repository?
Thank you!

**Comment by jkomyno** [comment] 2024-12-30 15:20
Closing this as a duplicate of https://github.com/prisma/prisma/issues/25526, which has more context than this discussion thread right here.

**Closed by jkomyno** 2024-12-30 15:20 UTC
Labels: bug/0-unknown, kind/bug, domain/client
