### ISSUE TITLE
Prisma Migrate CLI - Apply "Up To" Migration

### ISSUE THREAD

**Issue by adarnon** [prisma/prisma#7448] opened 2021-06-03 23:42 UTC
## Problem

I would like the ability to apply all migrations up to a specific migration. This would be immensely helpful when manually adjusting migration `.sql` files. Currently there isn't an easy way to "set up" the DB to the state before the latest migration has been applied, to test edge cases.

## Suggested solution

Add an option argument to the `prisma migrate` CLI. For example:

```
prisma migrate deploy --up-to 20200602_xxx
```

## Alternatives

The only option now is to delete the migration files you don't want to apply, deploy all migrations, then restore the files, make DB changes and deploy again.

**Comment by Jolg42** [comment] 2021-06-04 08:59
Thanks for your suggestion!
I think this is a duplicate of https://github.com/prisma/prisma/issues/6267 so I'll close this and mention your suggestion there.

**Closed** 2021-06-04 09:00 UTC
Labels: kind/feature, team/migrations, topic: migrate, topic: migrate deploy
