### ISSUE TITLE
Make Update mutations backward compatible

### ISSUE THREAD

**Issue by srisub1** [prisma/prisma#3714] opened 2020-09-20 02:21 UTC
## Problem

I am SUPER frustrated that in 2.6.x, all of a sudden, the update syntax changed. This requires a major change to my entire client code base, and so i am simply not going to upgrade from 2.5.1 for a while. 

Most of the time i just want to set a new value, esp for strings, so can we default to set. 

Instead of passing down:
```
{
   field1: value,
   submodel: { 
      update: {
        subfield1: value
     }
}
```
I have to now pass down:
```
{
    field1: { set value },
    submodel: {
       update: {
          subfield1: { set: value }
      }
   }
}
```

## Suggested solution

Please support the old syntax, and implicitly take it as "set".

**Comment by janpio** [comment] 2020-09-21 12:46
What version are you testing this with @srisub1? 2.6.x got two patch releases 2.6.1 and 2.6.2 as these changes were unwanted.

Using 2.6.2 or any of the 2.7.x releases you should not observe these differences any more.

**Comment by srisub1** [comment] 2020-09-21 13:13
I updated to 2.7.1 and I got these errors.

**Comment by janpio** [comment] 2020-09-21 16:17
Did you also `prisma generate` a new client? That should totally not be the case. Can you provide a reproduction of this in any way?

**Comment by pantharshit00** [comment] 2020-09-21 17:30
Also, @srisub1, are you using nexus framework? That might be relevant here as I remember it doesn't do this inlining yet.

**Comment by srisub1** [comment] 2020-09-21 17:33
Yes i am using nexus framework which does strange things with prisma, such
as asking to remove @prisma/client. So i did the following:

I did the following:

removed @prisma/cli and @prisma/client from package.json
npm upgrade nexus-plugin-prisma # which installs prisma 2.7.0
rm -rf node_modules; npm install
npx prisma generate

My system is very involved, so unable to provide isolated code sample. But
to reproduce, all you have to do is:

1. Create a model M1 with string field f1 say, and persist in db
2. Create an instance of the model
3. Try to update the instance, When i make the graphql call from client,
and nexus tries to respond, i get:
expecting {"errors":[{"message":"Variable \"$data\" got invalid value
\"value\" at \"data.f1\"; Expected type StringFieldUpdateOperationsInput to
be an object."

**Comment by pantharshit00** [comment] 2020-09-22 05:00
Yeah this does seem to be duplicate of https://github.com/graphql-nexus/nexus-plugin-prisma/issues/830. Pleas follow that issue, it has gained quite a lot of upvotes so it is likely to be addressed. Thanks!

I am going to close this here.

**Closed by pantharshit00** 2020-09-22 05:00 UTC
Labels: bug/0-needs-info, kind/bug
