### ISSUE TITLE
Repeat generation “ ALTER COLUMN "rechargeAt" SET DEFAULT '2020-06-06 06:06:06 +00:00'; ” in migrations file

### ISSUE THREAD

**Issue by youxdd** [prisma/prisma#10077] opened 2021-11-03 07:58 UTC
### Bug description

1、I added in the schema.prisma file  < rechargeAt   DateTime    @default("2020-06-06T06:06:06.000Z") >；
2、Every time it is executed < npx prisma migrate dev > will produce < ALTER TABLE "UserWealth" ALTER COLUMN "rechargeAt" SET DEFAULT '2020-06-06 06:06:06 +00:00'; > , But I did not modify  <rechargeAt>

### Prisma information

model UserWealth {
  id                String              @id
  rechargeAt        DateTime            @default("2020-06-06T06:06:06.000Z")
}

### Environment & setup

- OS: 
- Database: 
- Node.js version: 
Mac OS
PostgreSQL 12
node v14.17.3

### Prisma Version

```
3.4.0
```

**Comment by janpio** [comment] 2021-11-08 18:45
Could this be a duplicate of https://github.com/prisma/prisma/issues/5892?

**Comment by youxdd** [comment] 2021-11-09 03:39
> Could this be a duplicate of #5892?

Presumably yes

**Closed** 2021-11-09 11:12 UTC
Labels: kind/bug, topic: dates
