### ISSUE TITLE
Error in Migration Engine

### ISSUE THREAD

**Issue by cyberdavinci** [prisma/prisma#17793] opened 2023-02-07 21:07 UTC
Hi Prisma Team! The following command just crashed.

## Command

`db pull`
`db push`

## Versions
      
| Name        | Version            |
|-------------|--------------------|
| Platform    | windows  11          | 
| Node        | v18.14.0           | 
| Prisma CLI  | 4.10.0             | 
| Engine      | ca7fcef713137fa11029d519a9780db130cca91d| 

## Error
```
Error: Error in migration engine.
Reason: 
```

Please create an issue with your `schema.prisma` at
https://github.com/prisma/prisma/issues/new

**Comment by janpio** [comment] 2023-02-07 23:54
Thanks @cyberdavinci. Did Prisma work for you with an earlier version, and stopped working with the update to 4.10.0?
Can you give us some more information about your project?
Does it also fail when you create a new project, and install Prisma there with `npm install prisma && npx prisma init`?

**Comment by leoalves** [comment] 2023-02-09 15:38
This is happening to me as well.  
On windows 11 following the instructions from the getting started from scratch guide
https://www.prisma.io/docs/getting-started/quickstart

The error is a permission error in the migration engine.exe file
Error: Migration engine exited. Error: Command failed with EPERM: C:\prismaapp\node_modules\@prisma\engines\migration-engine-windows.exe cli --datasource <REDACTED> can-connect-to-database

Thanks

**Comment by leoalves** [comment] 2023-02-09 15:57
Sorry, at least for me, I think the issue is the internal monitoring tool (CrowdStrike) blocking the execution of the file `migration-engine-windows.exe`.  Just got an alert from IT.  
Thanks

**Comment by janpio** [comment] 2023-02-09 20:05
Can you open a new issue for this @leoalves and give us some more information? We would be very interested in learning how that looks like, what it complains about - so we can optimally prevent it happenign in the future!

**Comment by janpio** [comment] 2023-02-09 20:05
@cyberdavinci The new Prisma CLI 4.10.1 should give you more information than just `Error in migration engine.`.

**Comment by cyberdavinci** [comment] 2023-02-11 17:36
It was a DLL issue, I downloaded the Microsoft Visual C++ and installed
then problem solved.

**Comment by Weakky** [comment] 2023-07-13 13:54
Hey @cyberdavinci,

As you've fixed your issue, we're not closing it. Thanks for reporting 🙏

**Closed by Weakky** 2023-07-13 13:54 UTC
Labels: bug/0-unknown, kind/bug, topic: sqlite, topic: windows, tech/engines/migration engine, team/schema, topic: prisma db push, topic: prisma db pull, topic: engine
