### ISSUE TITLE
freeBSD 13 custom engine binaries, but it doesn't work properly.

### ISSUE THREAD

**Issue by ilovebsd** [prisma/prisma#17357] opened 2023-01-15 10:12 UTC
I build freeBSD 13 custom engine binaries, but it doesn't work properly.

In the project directory I created the .env file and set the binary engine configuration, but I keep trying to download the engine and it fails.

**/workspace/orm# export PRISMA2_BINARY_PATH="/workspace/orm/prisma/binaries/"**
**/workspace/orm# export PRISMA_BINARY_PATH="/workspace/orm/prisma/binaries/"**

**/workspace/orm# npx prisma init**
```
Warning Precompiled engine files are not available for freebsd13. Read more about building your own engines at https://pris.ly/d/build-engines Downloading Prisma engines for Node-API for freebsd13 [                    ] 0% Error: Not Found https://binaries.prisma.sh/all_commits/d6e67a83f971b175a593ccc12e15c4a757f93ffe/freebsd13/introspection-engine.gz
```

Other CLI commands also give the same error.
Why do I keep trying to download??  what did i do wrong??

**/workspace/orm/prisma/binaries# test-cli introspect --file-path prisma/schema.prisma**
```
reading the prisma schema from prisma/schema.prisma
Error: Some(Object {"is_panic": Bool(false), "message": String("\u{1b}[1;91merror\u{1b}[0m: \u{1b}[1mEnvironment variable not found: DATABASE_URL.\u{1b}[0m\n  \u{1b}[1;94m-->\u{1b}[0m  \u{1b}[4mschema.prisma:4\u{1b}[0m\n\u{1b}[1;94m   | \u{1b}[0m\n\u{1b}[1;94m 3 | \u{1b}[0m  // url      = \"postgresql://test:test@127.0.0.1:5443/test?schema=public\"\n\u{1b}[1;94m 4 | \u{1b}[0m  url      = \u{1b}[1;91menv(\"DATABASE_URL\")\u{1b}[0m\n\u{1b}[1;94m   | \u{1b}[0m\n"), "meta": Object {"full_error": String("\u{1b}[1;91merror\u{1b}[0m: \u{1b}[1mEnvironment variable not found: DATABASE_URL.\u{1b}[0m\n  \u{1b}[1;94m-->\u{1b}[0m  \u{1b}[4mschema.prisma:4\u{1b}[0m\n\u{1b}[1;94m   | \u{1b}[0m\n\u{1b}[1;94m 3 | \u{1b}[0m  // url      = \"postgresql://test:test@127.0.0.1:5443/test?schema=public\"\n\u{1b}[1;94m 4 | \u{1b}[0m  url      = \u{1b}[1;91menv(\"DATABASE_URL\")\u{1b}[0m\n\u{1b}[1;94m   | \u{1b}[0m\n")}, "error_code": String("P1012")})
```

**.env**
```
PRISMA_CLI_QUERY_ENGINE_TYPE=binary
PRISMA_QUERY_ENGINE_BINARY=./prisma/binaries/query-engine
PRISMA_MIGRATION_ENGINE_BINARY=./prisma/binaries/migration-engine
PRISMA_INTROSPECTION_ENGINE_BINARY=./prisma/binaries/introspection-engine
PRISMA_FMT_BINARY=./prisma/binaries/prisma-fmt
PRISMA_QUERY_ENGINE_LIBRARY=./prisma/binaries/libquery_engine.so
DATABASE_URL="postgresql://test:test@127.0.0.1:5443/test?schema=public"
```

**package.json**
```
{
  "name": "orm",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "dependencies": {
    "dotenv": "^16.0.3"
  },
  "devDependencies": {
    "prisma": "^4.8.1"
  }
}
```

**/workspace/orm# ls -l**
```
total 24
-rw-r--r--  1 root  wheel   435 Jan 16 03:57 .env
drwxr-xr-x  2 root  wheel     3 Jan 15 14:56 .vscode
-rw-r--r--  1 root  wheel    81 Jan 16 03:26 index.js
drwxr-xr-x  6 root  wheel     7 Jan 16 02:06 node_modules
-rw-r--r--  1 root  wheel  2341 Jan 16 02:06 package-lock.json
-rw-r--r--  1 root  wheel   317 Jan 16 02:59 package.json
drwxr-xr-x  3 root  wheel     4 Jan 16 02:55 prisma
-rw-r--r--  1 root  wheel    70 Jan 15 14:47 prisma.code-workspace
```

**/workspace/orm/prisma/binaries# ls -l**
```
total 57669
-rwxr-xr-x  1 root  wheel  14523472 Jan 15 18:33 introspection-engine
-rwxr-xr-x  1 root  wheel    314832 Jan 15 18:34 libprisma_fmt_build.so
-rwxr-xr-x  1 root  wheel  14669112 Jan 15 18:34 libquery_engine.so
-rwxr-xr-x  1 root  wheel  11756136 Jan 15 18:35 libquery_test_macros.so
-rwxr-xr-x  1 root  wheel   3133216 Jan 15 18:35 libtest_macros.so
-rwxr-xr-x  1 root  wheel   3109696 Jan 15 18:36 libuser_facing_error_macros.so
-rwxr-xr-x  1 root  wheel  16355776 Jan 15 18:37 migration-engine
-rwxr-xr-x  1 root  wheel   3174112 Jan 15 18:37 prisma-fmt
-rwxr-xr-x  1 root  wheel  16771192 Jan 15 18:38 query-engine
-rwxr-xr-x  1 root  wheel  16337176 Jan 15 18:38 test-cli
```

**Comment by pimeys** [comment] 2023-01-19 08:25
Usually this kind of error happens if either the env vars are not actually set in your environment (check that they are), or if the paths don't point to the correct location.

One issue I see here is how your library is called `libquery_engine.so`. You should rename it to `libquery_engine.node` so it can be loaded correctly. This probably is not the reason for the issue, but will cause issues later on.

You can take a look how we handle these variables for NixOS:

https://github.com/prisma/prisma-engines/blob/main/nix/cli-shell.nix

**Comment by janpio** [comment] 2023-01-19 10:26
What output do you get on `prisma -v`? That will tell you if the environment variables are correctly picked up and if it tries to correctly run the correct paths. I should also give some more input what might be going wrong.

**Comment by ilovebsd** [comment] 2023-01-19 12:53
npm prisma -v
8.19.1

**Comment by ilovebsd** [comment] 2023-01-19 22:40
`# export PRISMA_CLI_QUERY_ENGINE_TYPE="binary"
# export PRISMA2_BINARY_PATH="/workspace/orm/prisma/binaries"
# export PRISMA_BINARY_PATH="/workspace/orm/prisma/binaries"
# export PRISMA_QUERY_ENGINE_BINARY="/workspace/orm/prisma/binaries/query-engine"`

`# echo $PRISMA_CLI_QUERY_ENGINE_TYPE
binary
# echo $PRISMA2_BINARY_PATH
/workspace/orm/prisma/binaries
# echo $PRISMA_BINARY_PATH
/workspace/orm/prisma/binaries
# echo $PRISMA_QUERY_ENGINE_BINARY
/workspace/orm/prisma/binaries/query-engine`

`# npx prisma -v
Warning Precompiled engine files are not available for freebsd13. Read more about building your own engines at https://pris.ly/d/build-engines
> Downloading Prisma engines for freebsd13 [                    ] 0%Error: Not Found https://binaries.prisma.sh/all_commits/d6e67a83f971b175a593ccc12e15c4a757f93ffe/freebsd13/prisma-fmt.gz`

**Comment by pimeys** [comment] 2023-01-20 07:29
Did you set _all_ the needed variables?

- `PRISMA_MIGRATION_ENGINE_BINARY`: The executable migration engine in a working path.
- `PRISMA_QUERY_ENGINE_BINARY`: The executable query engine in a working path.
- `PRISMA_QUERY_ENGINE_LIBRARY`: The Node API library file, `.so` renamed to `.node`.
- `PRISMA_INTROSPECTION_ENGINE_BINARY`: The executable introspection engine in a working path.
- `PRISMA_FMT_BINARY`: The executable formatter in a working path.

They all have to be set and working for the binary bypass to work.

**Comment by ilovebsd** [comment] 2023-01-20 09:47
After `export` all binary engines, the contents of the `.env` are recognized and operate normally. 😂
I think need to update the custom engine binaries tutorial.
Thank you @pimeys  

```
⋊> export PRISMA_CLI_QUERY_ENGINE_TYPE="binary"
⋊> export PRISMA_QUERY_ENGINE_BINARY="/workspace/orm/prisma/binaries/query-engine"
⋊> export PRISMA_MIGRATION_ENGINE_BINARY="/workspace/orm/prisma/binaries/migration-engine"
⋊> export PRISMA_INTROSPECTION_ENGINE_BINARY="/workspace/orm/prisma/binaries/introspection-engine"
⋊> export PRISMA_FMT_BINARY="/workspace/orm/prisma/binaries/prisma-fmt"
⋊> export PRISMA_QUERY_ENGINE_LIBRARY="/workspace/orm/prisma/binaries/libquery_engine.node"
```

**⋊> env | grep PRISMA**
```
PRISMA_FMT_BINARY=/workspace/orm/prisma/binaries/prisma-fmt
PRISMA_CLI_QUERY_ENGINE_TYPE=binary
PRISMA_MIGRATION_ENGINE_BINARY=/workspace/orm/prisma/binaries/migration-engine
PRISMA_QUERY_ENGINE_BINARY=/workspace/orm/prisma/binaries/query-engine
PRISMA_INTROSPECTION_ENGINE_BINARY=/workspace/orm/prisma/binaries/introspection-engine
PRISMA_QUERY_ENGINE_LIBRARY=/workspace/orm/prisma/binaries/libquery_engine.node
```

**⋊> cat /workspace/orm/.env**
```
PRISMA_CLI_QUERY_ENGINE_TYPE=binary
PRISMA_QUERY_ENGINE_BINARY=./prisma/binaries/query-engine
PRISMA_MIGRATION_ENGINE_BINARY=./prisma/binaries/migration-engine
PRISMA_INTROSPECTION_ENGINE_BINARY=./prisma/binaries/introspection-engine
PRISMA_FMT_BINARY=./prisma/binaries/prisma-fmt
PRISMA_QUERY_ENGINE_LIBRARY=./prisma/binaries/libquery_engine.node
DATABASE_URL=postgresql://test:test@127.0.0.1:5443/test?schema=public
```

**⋊> npx prisma -v**
```
Warning Precompiled engine files are not available for freebsd13. Read more about building your own engines at https://pris.ly/d/build-engines
Environment variables loaded from .env
prisma                : 4.8.1
@prisma/client        : 4.9.0
Current platform      : freebsd13
Query Engine (Binary) : query-engine 8216abc56c0f2a7e0bf05489a7555da4b7ed1999 (at prisma/binaries/query-engine, resolved by PRISMA_QUERY_ENGINE_BINARY)
Migration Engine      : migration-engine-cli 8216abc56c0f2a7e0bf05489a7555da4b7ed1999 (at prisma/binaries/migration-engine, resolved by PRISMA_MIGRATION_ENGINE_BINARY)
Introspection Engine  : introspection-core 8216abc56c0f2a7e0bf05489a7555da4b7ed1999 (at prisma/binaries/introspection-engine, resolved by PRISMA_INTROSPECTION_ENGINE_BINARY)
Format Binary         : prisma-fmt 8216abc56c0f2a7e0bf05489a7555da4b7ed1999 (at prisma/binaries/prisma-fmt, resolved by PRISMA_FMT_BINARY)
Format Wasm           : @prisma/prisma-fmt-wasm 4.8.0-61.d6e67a83f971b175a593ccc12e15c4a757f93ffe
Default Engines Hash  : d6e67a83f971b175a593ccc12e15c4a757f93ffe
Studio                : 0.479.0
```

**Comment by janpio** [comment] 2023-01-20 18:42
So there is not bug?
What exactly needs to be updated where?

**Comment by ilovebsd** [comment] 2023-01-21 04:21
In the tutorial.I have information about `env,` but I don't think I've seen any information about OS shell environment settings, so I think it would be good to supplement that.

**Comment by janpio** [comment] 2023-01-21 18:12
Which tutorial do you mean exactly?

**Comment by ilovebsd** [comment] 2023-01-22 00:20
As a result of the test, there is no need to set `.env`. only set the environment variable globally.
In my case, I had to set up all the engines because it was a FreeBSD environment, but how would it work if I used a specific custom engine?

[https://www.prisma.io/docs/concepts/components/prisma-engines#setting-the-environment-variable](url)

**Comment by janpio** [comment] 2023-01-23 23:48
`.env` is just a file where you can define environment variable and their values - Prisma CLI reads that file and loads these into the environment. There is nothing magic. Anything you can to via "global environment variables" you can also do with `.env`.

**Comment by alibomba** [comment] 2024-04-06 09:07
Would you mind sharing those engine files for FreeBSD13? I have the same problem but I don't know how to build the engines.

**Comment by SevInf** [comment] 2024-09-05 09:44
As per last message, closing the issue as it is not a bug.

**Closed** 2024-09-05 09:43 UTC
Labels: bug/1-unconfirmed, kind/bug, topic: prisma init, topic: binary, topic: freebsd, domain/client, topic: engine
