### ISSUE TITLE
When using Ubuntu 22.04 with OpenSSL version 3.0.2, and running "prisma generate," it detects that it needs "debian-openssl-1.1.x."

### ISSUE THREAD

**Issue by Lce-Lemon** [prisma/prisma#21236] opened 2023-09-27 07:44 UTC
### Bug description

When using Ubuntu 22.04 with OpenSSL version 3.0.2, and running "prisma generate," it detects that it needs "debian-openssl-1.1.x."
After reviewing the source code, I found that Prisma first looks for "libssl." When "libssl" is found, it won't search for "openssl." How can I specify that Prisma uses "debian-openssl-3.0.x" instead of "debian-openssl-1.1.x"?

### How to reproduce

See bug description.

### Prisma information

```prisma
// Add your schema.prisma
```

```ts
// Add your code using Prisma Client
```

### Environment & setup

- OS: Ubuntu22.04.2
- Database: PostgreSQL
- Node.js version: 18.16.1

### Prisma Version

```
4.13.0
```

**Comment by janpio** [comment] 2023-09-27 12:53
Does your system not have OpenSSL 1.1.x?

**Comment by Lce-Lemon** [comment] 2023-09-27 23:21
> Does your system not have OpenSSL 1.1.x?

Yes, I don't have OpenSSL 1.1.x in my system, but I have libssl1.1.
You can download libssl1.1 from [this address](http://security.ubuntu.com/ubuntu/pool/main/o/openssl/) and install it on your Ubuntu 22.04 system to reproduce this issue. My question is how can I specify the use of OpenSSL 3.0.x?

**Comment by aqrln** [comment] 2023-10-02 13:43
@Lce-Lemon 

> Yes, I don't have OpenSSL 1.1.x in my system, but I have libssl1.1.

What do you mean by this? `libssl1.1` is OpenSSL 1.1.x.

> You can download libssl1.1 from [this address](http://security.ubuntu.com/ubuntu/pool/main/o/openssl/) and install it on your Ubuntu 22.04 system to reproduce this issue.

To clarify: what exactly is the issue here? Does Prisma break because of this, or is it just you'd prefer for OpenSSL 3 to be used rather than OpenSSL 1.1?

> My question is how can I specify the use of OpenSSL 3.0.x?

It's unfortunately not possible right now to override the result of the detection. Please open a feature request for this, as it comes up occasionally in comments and discussions but it's not currently in our backlog in any way.

**Comment by aqrln** [comment] 2023-10-02 13:45
One thing I missed in the original post:

> After reviewing the source code, I found that Prisma first looks for "libssl." When "libssl" is found, it won't search for "openssl."

FWIW, I don't think Prisma looks for OpenSSL CLI binary anymore, it used to but it didn't make a lot of sense since it was irrelevant to Prisma. Current versions should only look for the library as it is what's important for Prisma.

**Comment by sfabruz** [comment] 2023-10-03 16:12
Hello everyone, I'm writing here because I've the same problem.

> To clarify: what exactly is the issue here? Does Prisma break because of this, or is it just you'd prefer for OpenSSL 3 to be used rather than OpenSSL 1.1?

The problem is that Prisma breaks itself. I have three machines with ubuntu installed and they should be the same with each other, one creating the build and deploying it to the other two machines. On one of these two the app with prisma works like a charm, on the second one it doesn't and returns this error

```
PrismaClientInitializationError: Prisma Client could not locate the Query Engine for runtime "debian-openssl-1.1.x".
This happened because Prisma Client was generated for "debian-openssl-3.0.x", but the actual deployment required "debian-openssl-1.1.x".
Add "debian-openssl-1.1.x" to `binaryTargets` in the "schema.prisma" file and run `prisma generate` after saving it:
generator client {
   provider      = "prisma-client-js"
   binaryTargets = ["native", "debian-openssl-1.1.x"]
 }
```

> It's unfortunately not possible right now to override the result of the detection. Please open a feature request for this, as it comes up occasionally in comments and discussions but it's not currently in our backlog in any way.

I can undestand this, but in my case, I want to understand what Prisma is looking for in making this decision, so that I can find where the two machines are different from each other

Environment & setup

- OS: Ubuntu22.04.2
- Database: MySQL
- Node.js version: 18.16.1

Prisma Version
5.2.0

Thanks very much :)

**Comment by janpio** [comment] 2023-10-04 12:02
You should open your own issue then @sfabruz - then we can have this discussion. Thank you.

**Comment by sfabruz** [comment] 2023-10-04 12:17
Thanks for your reply @janpio 
I'll but I don't want and I shouldn't duplicate the same problem with another issue.

**Comment by janpio** [comment] 2023-10-04 12:50
Thanks for creating the issue anyway @sfabruz: https://github.com/prisma/prisma/issues/21340

**Comment by Lce-Lemon** [comment] 2023-10-04 13:46
Thank you for everyone’s responses. I have checked #21340, and I believe the issue I encountered is the same as his. It may have been my description that was inaccurate, and I apologize for that.

**Comment by janpio** [comment] 2023-10-04 13:53
@Lce-Lemon Alexey has asked you some questions, it would still be useful to hear your answers to that so we can evaluate this.

**Comment by Lce-Lemon** [comment] 2023-10-07 03:11
> @aqrln 
> 
> > Yes, I don't have OpenSSL 1.1.x in my system, but I have libssl1.1.
> 
>>> What do you mean by this? `libssl1.1` is OpenSSL 1.1.x.
> 
> Sorry, I didn't know that before
> > You can download libssl1.1 from [this address](http://security.ubuntu.com/ubuntu/pool/main/o/openssl/) and install it on your Ubuntu 22.04 system to reproduce this issue.
> 
> >> To clarify: what exactly is the issue here? Does Prisma break because of this, or is it just you'd prefer for OpenSSL 3 to be used rather than OpenSSL 1.1?
> 
> > My question is how can I specify the use of OpenSSL 3.0.x?
> 
> >>It's unfortunately not possible right now to override the result of the detection. Please open a feature request for this, as it comes up occasionally in comments and discussions but it's not currently in our backlog in any way.
>
> Because my program needs to run on an offline Ubuntu 22.04 system, I added debian-openssl-3.0.x to binaryTargets, as shown in issue #21340. Other applications installed libssl1.1, which caused my application to not function properly.
>
>Note: My program can run normally after adding debian-openssl-1.1.x to binaryTargets, but this will increase the size of my application package

**Comment by Lce-Lemon** [comment] 2023-10-08 02:46
@aqrln @janpio 
In addition, I also need to use 'prisma db push,' which requires the offline use of the Migration Engine. My build environment includes only the debian-openssl-3.0.x version of the Migration Engine. When I run my program on a server that includes openssl1.1, Prisma searches for the debian-openssl-1.1.x version of the Migration Engine, causing my program to not function properly.

Do I need to manually download the openssl1.1 version of the Migration Engine? 
If other applications depend on openssl1.0, do I also need to include the openssl1.0 version of the Migration Engine in my application?

**Comment by janpio** [comment] 2023-10-08 07:54
https://www.prisma.io/docs/reference/api-reference/environment-variables-reference#prisma_cli_binary_targets will let you configure the platforms/binaryTargets the CLI will consider and download.

If your build and deployment platforms are the same, you should not have any problems.

**Comment by Lce-Lemon** [comment] 2023-10-08 08:30
> https://www.prisma.io/docs/reference/api-reference/environment-variables-reference#prisma_cli_binary_targets将允许您配置 CLI 将考虑和下载的平台/binaryTargets。
> 
> 如果您的构建和部署平台相同（包括安装了 OpenSSL 版本），那么您应该不会有任何问题。

Yes, but I can't guarantee that the build environment and the runtime environment will remain consistent. Are there any other solutions?

Another issue here is that after configuring binaryTargets, only the Query Engine is downloaded during the build, and the Migration Engine is not downloaded. Because my application needs to use 'prisma db push' in an offline environment, configuring binaryTargets doesn't solve my problem.

See https://github.com/prisma/prisma/issues/21236#issuecomment-1751900386

**Comment by Lce-Lemon** [comment] 2023-10-08 08:32
> https://www.prisma.io/docs/reference/api-reference/environment-variables-reference#prisma_cli_binary_targets will let you configure the platforms/binaryTargets the CLI will consider and download.
> 
> If your build and deployment platforms are the same (including with OpenSSL versions are installed), you should not have any problems.

Yes, but I can't guarantee that the build environment and the runtime environment will remain consistent. Are there any other solutions?

Another issue here is that after configuring binaryTargets, only the Query Engine is downloaded during the build, and the Migration Engine is not downloaded. Because my application needs to use 'prisma db push' in an offline environment, configuring binaryTargets doesn't solve my problem.

See https://github.com/prisma/prisma/issues/21236#issuecomment-1751900386

**Comment by janpio** [comment] 2023-10-08 09:03
Yes it does. `binaryTargets` in the Prisma schema affects the engines required for Prisma Client, the environment variable `PRISMA_CLI_BINARY_TARGETS` affects the engines required for Prisma CLI. These are independent, but when using both you should be able to affect both Prisma CLI and Client to have the engines you require.

**Comment by Lce-Lemon** [comment] 2023-10-08 09:42
> Yes it does. `binaryTargets` in the Prisma schema affects the engines required for Prisma Client, the environment variable `PRISMA_CLI_BINARY_TARGETS` affects the engines required for Prisma CLI. These are independent, but when using both you should be able to affect both Prisma CLI and Client to have the engines you require.

Thank you very much. After testing, this approach is proven to be effective.

Now, I need to add all possible versions in both `binaryTargets` and `PRISMA_CLI_BINARY_TARGETS`, which will significantly increase the size of my application.

**Comment by janpio** [comment] 2023-10-08 10:32
There is unfortunately no way around that with native, platform-dependent code - unless of course not building for other platforms, but letting the platform built themselves (and in this case download the correct Prisma engine files).

**Comment by Lce-Lemon** [comment] 2023-10-09 06:02
> There is unfortunately no way around that with native, platform-dependent code - unless of course not building for other platforms, but letting the platform built themselves (and in this case download the correct Prisma engine files).

When using Prisma offline, how do I specify the engine cache directory?

Because I need to use Prisma offline, I have to pre-download the query engine and migration engine. Upon examining the source code, I noticed that when downloading the query engine and migration engine, they are cached in different directories for different executing users. Is it possible to make this cache directory a configurable option, allowing for the configuration of this cache directory so that multiple users can use the same cache?

**Comment by janpio** [comment] 2023-10-09 08:31
I don't think so. If you download the engine files manually and provide them to Prisma via environment variables, the cache directory should not be used at all optimally.

**Comment by Lce-Lemon** [comment] 2023-10-09 09:10
> I don't think so. If you download the engine files manually and provide them to Prisma via environment variables, the cache directory should not be used at all optimally.

I'm very sorry, my description may have been inaccurate. Because I need to use Prisma offline, I have to package the engine files cached by Prisma into my application (I package both my program and the "~/.cache/prisma" folder). Upon inspecting Prisma's source code for engine downloads (prisma/build/index.js:92419), I noticed that Prisma fetches the current user's directory and places the downloaded engine files in the "~/.cache/prisma" folder. So, when I package my application using user A, the engine files are downloaded to "/home/A/.cache/prisma". However, when I deploy the application to another server and run it with user B, I cannot access the engine files from "/home/B/.cache/prisma" (due to the inability to retrieve engine files from the cache directory and because the server is not connected to the internet).

**Comment by janpio** [comment] 2023-10-09 09:26
There is currently not mechanism to statically provide the engine files for multiple platforms in an offline environment. The environment variables have to choose one specific file. You can of course potentially set the environment variables dynamically. (Messing with the cache is not the correct approach, there is no guarantee the cache will be used. It is an internal implementation detail.)

**Comment by millsp** [comment] 2023-11-07 03:26
@Lce-Lemon did you read @janpio's comment, and have you tried investigating his [suggested](https://www.prisma.io/docs/reference/api-reference/environment-variables-reference#prisma_query_engine_library) approach?

**Comment by SevInf** [comment] 2024-01-15 09:23
@Lce-Lemon did you have a chance to try what @janpio suggested? Without further assistance and no way to reproduce the issue, we might have to close it.
Thank you!

**Comment by jkomyno** [comment] 2024-02-12 10:19
As we've tried to reach @Lce-Lemon twice without success, we're now closing this issue.
Please leave a comment below with a reply to [this message](https://github.com/prisma/prisma/issues/21236#issuecomment-1752637787) if you see this issue, and we'll reopen it. Thanks!

**Closed by jkomyno** 2024-02-12 10:19 UTC
Labels: bug/0-unknown, kind/bug, tech/typescript, team/client, topic: openssl, topic: os detection
