### ISSUE TITLE
CockroachDB: Query Engine panics when attempting to atomically update a BigInt ID value

### ISSUE THREAD

**Issue by RobertCraigie** [prisma/prisma#16612] opened 2022-12-04 10:36 UTC
### Bug description

When attempting to atomically increment a `BigInt` field, the Query Engine will panic.

As far as I can tell I've tracked the cause of the issue down to this line: https://github.com/prisma/prisma-engines/blob/367cade6e458212277bcb5d5579acb639587ded5/libs/prisma-value/src/arithmetic.rs#L26 which is missing handling for the `BigInt` case.

### How to reproduce

1. Setup database using provided schema
2. Run the provided script

### Expected behavior

The Query Engine should not panic.

### Prisma information

```prisma
generator client {
  provider = "prisma-client-js"
}

datasource client {
  provider = "cockroachdb"
  url      = env("DB_URL")
}

model Types {
  id     BigInt  @id @default(sequence())
}
```

```ts
import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient({ log: ["query", "info", "error", "warn"] });

async function main() {
  const record = await prisma.types.create({ data: {} });
  const updated = await prisma.types.update({
    where: { id: record.id },
    data: { id: { increment: 500 } },
  });
  console.log(updated);
}

main()
  .catch((e) => {
    throw e;
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
```

### Environment & setup

- OS:  MacOS
- Database:  CockroachDB
- Node.js version:  `v16.14.2`

### Prisma Version

```
prisma                  : 4.7.1
@prisma/client          : 4.7.1
Current platform        : darwin-arm64
Query Engine (Node-API) : libquery-engine 272861e07ab64f234d3ffc4094e32bd61775599c (at node_modules/@prisma/engines/libquery_engine-darwin-arm64.dylib.node)
Migration Engine        : migration-engine-cli 272861e07ab64f234d3ffc4094e32bd61775599c (at node_modules/@prisma/engines/migration-engine-darwin-arm64)
Introspection Engine    : introspection-core 272861e07ab64f234d3ffc4094e32bd61775599c (at node_modules/@prisma/engines/introspection-engine-darwin-arm64)
Format Binary           : prisma-fmt 272861e07ab64f234d3ffc4094e32bd61775599c (at node_modules/@prisma/engines/prisma-fmt-darwin-arm64)
Format Wasm             : @prisma/prisma-fmt-wasm 4.7.1-1.272861e07ab64f234d3ffc4094e32bd61775599c
Default Engines Hash    : 272861e07ab64f234d3ffc4094e32bd61775599c
Studio                  : 0.477.0
```

**Comment by laplab** [comment] 2024-03-19 12:09
Thank you for reporting the issue, @RobertCraigie! Unfortunately, I was not able to reproduce it on Prisma 5.11.0. Can you please confirm if the issue is still relevant on the latest version?

**Comment by laplab** [comment] 2024-04-02 09:13
Hey @RobertCraigie, we are going to close this issue for now, as we are not able to reproduce it. If you continue experiencing the same problem, please feel free to open a new issue.

**Closed by laplab** 2024-04-02 09:13 UTC
Labels: bug/1-unconfirmed, kind/bug, tech/engines/query engine, topic: bigints, team/client, topic: rust panic, topic: cockroachdb
