### ISSUE TITLE
Invalid invocation

### ISSUE THREAD

**Issue by asmuxlow** [prisma/prisma#8289] opened 2021-07-14 21:33 UTC
### Bug description

I get an error trying to write the very first post transaction to the DB following the guide. Here is my error:

```
PrismaClientUnknownRequestError2 [PrismaClientUnknownRequestError]: 
Invalid `prisma.post.create()` invocation in
/Users/ali/Documents/Work/ViaVid/Prisma/blog/index.ts:9:21

   6 await prisma.$connect()
   7 
   8 // Create the first post
→  9 await prisma.post.create(
  Error in connector: Database error. error code: unknown, error message: Transactions are not supported by this deployment
    at cb (/Users/ali/Documents/Work/ViaVid/Prisma/blog/node_modules/@prisma/client/runtime/index.js:34804:17)
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {
  clientVersion: '2.27.0'
}
```

### How to reproduce

Run `npx prisma generate > run npx ts-node index.ts` for the very first time following the MongoDB guide

### Expected behavior

Connect to MongoDB instance & create a post

### Prisma information

Schema etc all like the guide

### Environment & setup

- OS: Mac OSX 11.4
- Database:MongoDB
- Node.js version: 14.17.1

### Prisma Version

```
2.27.0
```

**Comment by matthewmueller** [comment] 2021-07-15 13:33
Thanks for the issue, this is something we hope to improve soon. This is a duplicate of https://github.com/prisma/prisma/issues/8289. You'll find a few workarounds in that issue.

**Closed by matthewmueller** 2021-07-15 13:33 UTC
Labels: bug/0-needs-info, kind/bug, topic: mongodb

**Comment by unlight** [comment] 2021-07-15 13:35
Step to reproduce:
1. Get example from https://github.com/prisma/prisma-examples/tree/latest/databases/mongodb
2. Start `docker-compose up`
3. Edit prisma/schema.prisma, update db section: `url      = "mongodb://localhost:27017/prisma_example_mongodb"`
4. install ts-node `npm i -D ts-node`
5. node -r ts-node/register/transpile-only src/prisma-examples/1-create-user.ts

Env: 
```
prisma@2.28.0-dev.3
OS: Windows 10
```

**Comment by janpio** [comment] 2021-07-15 13:39
@unlight That is unexpected I think. Can you make it a new issue though please? Then someone can look into it. Thanks.

**Comment by asmuxlow** [comment] 2021-07-15 17:08
Hi there,

I had tried the workaround with another DB and I got the following error:

PrismaClientUnknownRequestError2 [PrismaClientUnknownRequestError]: 
Invalid `prisma.post.create()` invocation in
/Users/ali/Documents/Work/ViaVid/Prisma/blog/index.ts:9:21

   6 await prisma.$connect()
   7 
   8 // Create the first post
→  9 await prisma.post.create(
  Error occurred during query execution:
ConnectorError(ConnectorError { user_facing_error: None, kind: RawError { code: "263", message: "Cannot create namespace dev101.Post in multi-document transaction." } })
    at cb (/Users/ali/Documents/Work/ViaVid/Prisma/blog/node_modules/@prisma/client/runtime/index.js:34804:17)
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {
  clientVersion: '2.27.0'
}

**Comment by janpio** [comment] 2021-07-15 17:11
The original issue is documented at https://pris.ly/d/mongodb-troubleshooting-transactions now with our advice for workarounds.

**Comment by janpio** [comment] 2021-07-15 17:11
@asmuxlow Can you please open a new issue about this? That looks new and unexpected as well, so we want to investigate! Thanks.
