### ISSUE TITLE
`prisma:engine stdout Unknown error`

### ISSUE THREAD

**Issue by janpio** [prisma/prisma#8052] opened 2021-07-04 10:57 UTC
Recently the `prisma:engine` logging is full with `Unknown error` message:

```
...
  prisma:engine stdout Fetched a connection from the pool +10ms
  prisma:engine stdout Unknown error +23ms
prisma:query BEGIN
  prisma:engine stdout Unknown error +61ms
prisma:query SELECT "public"."BuyerGroup"."id" FROM "public"."BuyerGroup" WHERE 1=1 OFFSET $1
  prisma:engine stdout Unknown error +63ms
prisma:query SELECT "public"."BuyerGroup"."id" FROM "public"."BuyerGroup" WHERE 1=1
  prisma:engine stdout Unknown error +22ms
prisma:query COMMIT
...
```

Logging can be achieved with `DEBUG=*` and 
```
const prisma = new PrismaClient({
  log: ['query', 'info', `warn`, `error`],
})
```

**Comment by pantharshit00** [comment] 2021-07-22 16:35
@janpio any specifics that is required for a reproduction? I can't reproduce this on a simple local project.

**Comment by Jolg42** [comment] 2021-07-26 09:03
Maybe NodeAPI flag @janpio?

**Comment by janpio** [comment] 2021-07-28 10:24
That would be possible, no recollection after 4 weeks. Will observe if I see it again.

**Comment by pantharshit00** [comment] 2021-07-28 21:15
I will close it for now

**Comment by Jolg42** [comment] 2021-09-02 07:08
@tehnorm Which version of `prisma` and `@prisma/client` are you using and could you share your Prisma Client query and schema maybe?

along with:

- OS: 
- Database: 
- Node.js version: 

It will help to reproduce this.

**Comment by tehnorm** [comment] 2021-09-02 16:57
Hi @Jolg42 - here are those details:

- OS: Mac OS - 10.15.1
- Database: PostgreSQL 13
- Node.js version: v15.0.1

**Comment by janpio** [comment] 2021-09-02 18:10
Can you also share your `npx prisma -v` output @tehnorm please?

**Comment by tehnorm** [comment] 2021-09-02 21:20
```
npx prisma -v
npx prisma -v
Environment variables loaded from .env
prisma               : 2.29.1
@prisma/client       : 2.29.1
Current platform     : darwin
Query Engine         : query-engine 1be4cd60b89afa04b192acb1ef47758a39810f3a (at node_modules/@prisma/engines/query-engine-darwin)
Migration Engine     : migration-engine-cli 1be4cd60b89afa04b192acb1ef47758a39810f3a (at node_modules/@prisma/engines/migration-engine-darwin)
Introspection Engine : introspection-core 1be4cd60b89afa04b192acb1ef47758a39810f3a (at node_modules/@prisma/engines/introspection-engine-darwin)
Format Binary        : prisma-fmt 1be4cd60b89afa04b192acb1ef47758a39810f3a (at node_modules/@prisma/engines/prisma-fmt-darwin)
Default Engines Hash : 1be4cd60b89afa04b192acb1ef47758a39810f3a
Studio               : 0.419.0
```

**Comment by janpio** [comment] 2021-09-02 21:54
Weird, that looks perfectly fine. Can you maybe create a small reproduction project with the minimal setup required to reproduce this? Would be really helpful for us.

**Comment by janpio** [comment] 2021-09-05 17:45
This also popped up over here: https://github.com/prisma/prisma/discussions/9115

**Comment by tehnorm** [comment] 2021-09-10 23:36
I haven't had time to recreate this but I can confirm it's happening somewhere in `getBacktraceFromLog()` https://i.imgur.com/jbVxih1.png

**Comment by tehnorm** [comment] 2021-09-10 23:47
Here is a little more info: https://i.imgur.com/DcqnDEn.png - This is logging `log4`.

**Comment by janpio** [comment] 2021-09-11 13:47
Thanks. That makes total sense, the problem is that we do not fully understand how this is happening. Can you maybe copy the text of your second screenshot and post it here? That might be useful. What kind of queries are you executing for this to happen?

**Comment by pantharshit00** [comment] 2022-06-02 12:17
Sorry for the ping @tehnorm but is this still relevant? We can close this otherwise.

**Comment by kristinlindquist** [comment] 2022-11-18 01:09
I also got "Unknown error" logged from prisma:engine - https://github.com/prisma/prisma/discussions/16329

**Comment by miguelff** [comment] 2024-01-19 17:30
I tried reproducing and no luck.

The only instance of "Unknown error" in the code, in any of prisma and prisma-engines is imposible it is related to this problem as it a WASM specific code added very recently.

```
query-engine/driver-adapters/src/wasm/error.rs
11:        .unwrap_or_else(|| "Unknown error".to_string());
```

The history of commits that added or removed that expression "Unknown error" in both prisma or prisma-engines have been inspected and don't contain any smoking gun. 

I'm going to close this as I can't reproduce anymore. And it's uncertain whether this is still an issue.

**Closed by miguelff** 2024-01-19 17:30 UTC
Labels: bug/1-unconfirmed, kind/regression, tech/typescript, team/client, topic: logging, topic: engineType = binary
