### ISSUE TITLE
Remove the implicit "native" binaryTarget

### ISSUE THREAD

**Issue by DusanDimitric** [prisma/prisma#12691] opened 2022-04-06 12:03 UTC
### Bug description

I want to leave out my "native" binaryTarget, and build the client explicitly for the targets I declard in `schema.prisma`.

This is a problem because when multiple people (with different Operating Systems) are working on the same codebase will generate different clients - but they should be exactly the same.

Doc links:
https://www.prisma.io/docs/reference/api-reference/prisma-schema-reference#specify-custom-binarytargets-to-ensure-compatibility-with-the-os

### How to reproduce

For example, in this case:

```
generator client {
  provider      = "prisma-client-js"
  binaryTargets = ["rhel-openssl-1.0.x"]
}
```

I want the client built ONLY for `"rhel-openssl-1.0.x"` and not for my `"native"` target as well.

The `"native"` target is added implicitly for some reason.

### Prisma information

`schema.prisma`:
```
generator client {
  provider      = "prisma-client-js"
  binaryTargets = ["rhel-openssl-1.0.x"]
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

model User {
  uuid      String   @id @db.Uuid
  createdAt DateTime @default(now())
}
```

### Environment & setup

- OS: Mac/Ubuntu/Windows
- Database: PostgreSQL (not relevant)
- Node.js version: v16.13.2

### Prisma Version

package.json:
```
    ...
    "@prisma/client": "^3.12.0",
    "prisma": "^3.12.0",
    ...
```

**Comment by janpio** [comment] 2022-04-06 13:36
This would indeed be the logical behavior, based on how `native` is documented: https://www.prisma.io/docs/reference/api-reference/prisma-schema-reference#specify-the-prisma-client-js-generator-with-the-default-output-previewfeatures-enginetype-and-binarytargets

**Comment by DusanDimitric** [comment] 2022-04-06 15:12
The thing is - when I specify:
```
binaryTargets = ["debian-openssl-1.1.x"]
```
I want only the `"debian-openssl-1.1.x"` client to be created.

I am on MacOS and my Colleague on Debian - when we generate Prisma Clients we get different output - it should be the same with the configuration above, right?

**Comment by janpio** [comment] 2022-04-06 20:14
Yes, that is what I confirmed (or tried to at least) with my comment above 😆 We'll look into this. 
Changing this of course would not be that easy, as quite a few setups out there of course could rely on this current behavior - accidentally or by design.

**Comment by dejanvasic85** [comment] 2022-09-09 22:58
I'm finding that binaryTargets would be a better fit as a CLI argument where deployment targets may differ from local. Locally I may be using "darwin" but I want to deploy "rhel-openssl-1.0.x".

So during deploy having this flag:
```
npx prisma genearate --binaryTargets "rhel-openssl-1.0.x"
```
This means I don't have to have many targets in my schema committed in source control which would end up generating large binaries and potentially cause issues in deployments like lambda. 

Our current situation:

```
 63K 10 Sep 08:08 index.js
 32M 10 Sep 08:08 libquery_engine-darwin.dylib.node
 40M 10 Sep 08:08 libquery_engine-debian-openssl-1.1.x.so.node
 42M 10 Sep 08:08 libquery_engine-rhel-openssl-1.0.x.so.node
 110B 10 Sep 08:08 package.json
 9.4K 10 Sep 08:08 schema.prisma
```

**Comment by janpio** [comment] 2022-09-10 16:23
That's a pretty good suggestion. Can you turn it into a new feature request issue please @dejanvasic85? Thanks.

**Comment by aqrln** [comment] 2023-04-20 13:45
I can't reproduce this neither with latest Prisma nor with reported 3.12.0. For me Prisma is working exactly the way that this issue requests: `native` is only added when the list is empty, otherwise the client is generated only for the exact list of the requested platforms (and a warning is printed if the list doesn't include `native`):

````
STEP 15/17: RUN npx prisma generate
Environment variables loaded from .env
Prisma schema loaded from prisma/schema.prisma
Warning: Your current platform `debian-openssl-1.1.x` is not included in your generator's `binaryTargets` configuration ["rhel-openssl-1.0.x"].
To fix it, use this generator config in your schema.prisma:
generator client {
  provider      = "prisma-client-js"
  binaryTargets = ["native", "rhel-openssl-1.0.x"]
}
Note, that by providing `native`, Prisma Client automatically resolves `debian-openssl-1.1.x`.
Read more about deploying Prisma Client: https://github.com/prisma/prisma/blob/main/docs/core/generators/prisma-client-js.md


✔ Generated Prisma Client (3.12.0 | library) to ./node_modules/@prisma/client in 59ms
You can now start using Prisma Client in your code. Reference: https://pris.ly/d/client
```
import { PrismaClient } from '@prisma/client'
const prisma = new PrismaClient()
```
--> ece9324bb957
STEP 16/17: RUN npx prisma -v
Environment variables loaded from .env
prisma                  : 3.12.0
@prisma/client          : 3.12.0
Current platform        : debian-openssl-1.1.x
Query Engine (Node-API) : libquery-engine 22b822189f46ef0dc5c5b503368d1bee01213980 (at node_modules/@prisma/engines/libquery_engine-debian-openssl-1.1.x.so.node)
Migration Engine        : migration-engine-cli 22b822189f46ef0dc5c5b503368d1bee01213980 (at node_modules/@prisma/engines/migration-engine-debian-openssl-1.1.x)
Introspection Engine    : introspection-core 22b822189f46ef0dc5c5b503368d1bee01213980 (at node_modules/@prisma/engines/introspection-engine-debian-openssl-1.1.x)
Format Binary           : prisma-fmt 22b822189f46ef0dc5c5b503368d1bee01213980 (at node_modules/@prisma/engines/prisma-fmt-debian-openssl-1.1.x)
Default Engines Hash    : 22b822189f46ef0dc5c5b503368d1bee01213980
Studio                  : 0.459.0
--> e0f5eb5d4341
STEP 17/17: RUN ls node_modules/.prisma/client
index-browser.js
index.d.ts
index.js
libquery_engine-rhel-openssl-1.0.x.so.node
package.json
schema.prisma
````

Note that the generator doesn't automatically delete any extraneous files present in the output directory, so if you generate the client multiple times for different platforms into the same directory without cleaning up the output in between, you will get all of those engines accumulated there. Could that be the reason you are facing this issue?

**Comment by miguelff** [comment] 2023-07-17 13:54
@DusanDimitric Is this still an issue on recent versions of prisma? FWIW @aqrln provided a reproduction by which the problem didn't existed? Could you please confirm by commenting and reopening if you are still observing the same behavior?

**Closed by miguelff** 2023-07-17 13:54 UTC
Labels: bug/0-unknown, kind/bug, topic: generator, team/client, topic: binaryTargets, topic: breaking change

**Comment by DimiTech** [comment] 2023-12-11 13:25
I'm sorry @miguelff, but I'm no longer using Prisma so I can't confirm this. Thanks for all the help, appreciate it :)
