### ISSUE TITLE
Netlify Debian Issue

### ISSUE THREAD

**Issue by eli-front** [prisma/prisma#13548] opened 2022-05-29 00:41 UTC
Any Suggestions?

`prisma-cli`: 3.14.0

## error message from netlify
```
7:32:06 PM: > Build error occurred
7:32:06 PM: Error: Query engine library for current platform "debian-openssl-1.1.x" could not be found.
7:32:06 PM: You incorrectly pinned it to debian-openssl-1.1.x
7:32:06 PM: This probably happens, because you built Prisma Client on a different platform.
7:32:06 PM: (Prisma Client looked in "/opt/build/repo/node_modules/@prisma/client/runtime/libquery_engine-debian-openssl-1.1.x.so.node")
7:32:06 PM: Searched Locations:
7:32:06 PM:   /opt/build/repo/node_modules/.prisma/client
7:32:06 PM:   /opt/build/repo/node_modules/@prisma/client
7:32:06 PM:   /opt/build/repo/node_modules/@prisma/client
7:32:06 PM:   /opt/build/repo/node_modules/.prisma/client
7:32:06 PM:   /opt/build/repo/prisma
7:32:06 PM:   /tmp/prisma-engines
7:32:06 PM:   /opt/build/repo/node_modules/.prisma/client
7:32:06 PM: You already added the platforms "debian-openssl-1.1.x", "debian-openssl-1.1.x" to the "generator" block
7:32:06 PM: in the "schema.prisma" file as described in https://pris.ly/d/client-generator,
7:32:06 PM: but something went wrong. That's suboptimal.
7:32:06 PM: Please create an issue at https://github.com/prisma/prisma/issues/new
7:32:06 PM:     at Object.request (/opt/build/repo/node_modules/@prisma/client/runtime/index.js:45411:15)
7:32:06 PM:     at async PrismaClient._request (/opt/build/repo/node_modules/@prisma/client/runtime/index.js:46301:18)
7:32:06 PM:     at async getStaticPaths (/opt/build/repo/.next/server/pages/poll/[id].js:176:20)
7:32:06 PM:     at async buildStaticPaths (/opt/build/repo/node_modules/next/dist/build/utils.js:491:31)
7:32:06 PM:     at async /opt/build/repo/node_modules/next/dist/build/utils.js:632:119
7:32:06 PM:     at async Span.traceAsyncFn (/opt/build/repo/node_modules/next/dist/trace/trace.js:79:20) {
7:32:06 PM:   type: 'PrismaClientInitializationError',
7:32:06 PM:   clientVersion: '3.14.0'
7:32:06 PM: }
7:32:07 PM: error Command failed with exit code 1. (https://ntl.fyi/exit-code-1)
7:32:07 PM: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

## curent schema

```
generator client {
  provider      = "prisma-client-js"
  binaryTargets = ["native", "debian-openssl-1.1.x"]
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}
```

**Comment by pantharshit00** [comment] 2022-05-30 15:06
Can you please share a small reproduction? You can probably follow this guide: https://www.prisma.io/docs/guides/deployment/deployment-guides/deploying-to-netlify as starting point.

**Comment by SevInf** [comment] 2022-07-01 14:54
I'm going to close this as the duplicate of #13548

**Closed by SevInf** 2022-07-01 14:54 UTC
Labels: bug/1-unconfirmed, kind/bug, team/client, topic: You incorrectly pinned it to ...
