### ISSUE TITLE
TypeScript types are not reloaded in editors

### ISSUE THREAD

**Issue by timsuchanek** [prisma/prisma#2962] opened 2020-07-08 11:23 UTC
When changing the schema and regenerating the client, VSCode and other editors don't pick up the change in the TypeScript types.
This is not necessarily a bug in Prisma, but it significantly affects the developer experience.

## Reproduction
```bash
mkdir repro
cd repro
npx @timsuchanek/auto prisma
// open vscode and open main.ts
// edit schema.prisma
// run prisma generate
// types are not updated
// try to trigger reload by hand like so:
rm -rf node_modules && yarn
// now PrismaClient is even typed `any`

```

**Comment by Jolg42** [comment] 2020-07-08 12:30
@timsuchanek is that a duplicate of https://github.com/prisma/prisma/issues/2771 ?

**Comment by timsuchanek** [comment] 2020-07-08 12:38
@Jolg42 no, this is an actionable specific issue with a reproduction that can be closed, while #2771 is a more general issue.

**Comment by carmenberndt** [comment] 2020-07-28 15:32
This issue is fixed by https://github.com/prisma/language-tools/pull/357 for VSCode.

**Comment by otaviobps** [comment] 2021-02-12 12:37
Any way to fix it in Webstorm? I'm having the exact same issue, and I have to delete `node_modules` and install again

**Comment by janpio** [comment] 2021-02-12 19:47
I think this is a workaround for Webstorm: https://github.com/prisma/prisma/issues/2359#issuecomment-739921212

**Comment by pantharshit00** [comment] 2021-05-29 12:35
I am going to close this as this no longer happens in VSCode. If this is happening for your editor, please open a new issue about that.

**Closed by pantharshit00** 2021-05-29 12:35 UTC
Labels: bug/2-confirmed, kind/bug, status/needs-action, team/client, tech/typescript, topic: editor

**Comment by Jolg42** [comment] 2021-05-31 09:33
@pantharshit00 I think this still happens with VS Code but is solved by using the Prisma extension:
https://marketplace.visualstudio.com/items?itemName=Prisma.prisma
