### ISSUE TITLE
ARM / Raspberry Pi Builds unable to Install

### ISSUE THREAD

**Issue by ACregan** [prisma/prisma#10920] opened 2022-01-03 04:07 UTC
### Bug description

I have a project developed on Windows/WSL that I wish to deploy and run on Raspberry Pi 4b running Ubuntu 21.10 and, Node v17.2.0. It installs successfully but fails when running ```npx prisma generate``` with the following error:

``` Download Prisma engines for Node-API for linux-arm-openssl-1.1.X - Error: Not Found https://binaries.prisma.sh/all_commits/3383b0f8f1fe9052cf9a00e9761c9dc097a63c/linux-arm-openssl-1.1.x/migration-engine.gz ```

### How to reproduce

Install Ubuntu 21.10 on Raspberry Pi 4
Install Node v17.2.0
Attempt to run 'npx prisma generate' on a project using prisma 3.3.0

### Expected behavior

Prisma to download the required engines and successfully generate ARM compatible executables for use with my project.

### Prisma information

```

generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "sqlite"
  url      = "file:./dev.db"
}

model User {
  id              String      @id @default(uuid())
  firstname       String
  surname         String
  email           String      @unique
  password        String
  avatarUrl       String?
  privilege       String      @default("AUTHOR")
  articles        Article[]   @relation(name: "articles")
  group           Group[]
  contributingTo  Article[]   @relation(name: "contributingTo")
}

model Group {
  id              String      @id @default(uuid())
  name            String      @unique
  url             String?     @unique
  admin           User        @relation(fields: [adminId], references: [id])
  adminId         String
  articles        Article[]
}

model Article {
  id              String      @id @default(uuid())
  createdAt       DateTime    @default(now())
  title           String?     @default("New Article")
  summary         String?
  content         String?
  updatedAt       DateTime?
  url             String?
  status          String      @default("DRAFT")
  author          User        @relation(name: "articles", fields: [authorId], references: [id])
  authorId        String
  group           Group       @relation(fields: [groupId], references: [id])
  groupId         String
  contributors    User[]      @relation(name: "contributingTo")
}
```

### Environment & setup

- Hardware: Raspberry Pi 4b
- OS: Ubuntu 21.10
- Database: SQL Lite
- Node.js version: v17.2.0

### Prisma Version

```
v 3.3.0
```
(... in my projects package.json but running ```prisma -v``` does not work as it is not successfully generated)

**Comment by ACregan** [comment] 2022-01-03 04:16
I should not I have tried v3.2.1 also with no success.

**Comment by janpio** [comment] 2022-01-03 12:54
Is `linux-arm-openssl-1.1.x` a platform Prisma is supposed to support?

**Comment by pantharshit00** [comment] 2022-01-04 11:02
This is expected. We don't support Raspberry Pi 32 bit arm. i would consider this duplicate of https://github.com/prisma/prisma/issues/5379 and https://github.com/prisma/prisma/issues/5497

**Closed by pantharshit00** 2022-01-04 11:02 UTC
Labels: bug/0-needs-info, kind/bug, team/client, topic: arm

**Comment by aqrln** [comment] 2022-01-04 13:43
@ACregan since Raspberry Pi 4 has a Cortex-A72 CPU, you should be able to install ARM64 version of Ubuntu and use Prisma without issues, since we do support ARM64.

**Comment by ACregan** [comment] 2022-01-06 03:31
@pantharshit00 @aqrln @janpio: Thats fantastic, I've installed Ubuntu 21.10 ARM64 on raspberry pi and can confirm it now works as expected. Thanks for your help with this. 

Prisma is fantastic, thanks for the great work you do!
