### ISSUE TITLE
Can't save longer Strings into mysql, limit on varchar(191) with STRING definition

### ISSUE THREAD

**Issue by ChristophDietrich** [prisma/prisma#1975] opened 2020-03-27 23:27 UTC
## Bug description
By trying to save LONGTEXT which has more than 191 chars prisma throws an error:

```javascript
Invalid `const user = await prisma.user.create()` invocation in .....

   3 const prisma = new PrismaClient();
   4 
   5 
   6 const func = async () => {
→  7     const user = await prisma.user.create(

Error occurred during query execution:
ConnectorError(ConnectorError { user_facing_error: None, kind: QueryError(Server(ServerError { code: 1406, message: "Data too long for column \'comment\' at row 1", state: "22001" })) })
```

## How to reproduce
1. Setup a clean preview025 standard env 
2. Use schema
3. Generate prisma client
4. Run test script

```javascript
const { PrismaClient } = require('@prisma/client');
const prisma = new PrismaClient();

const userCreate = async () => {
    const user = await prisma.user.create({
        data: {
            name: 'Test Name'
            comment: 'LongerThan191CharsDC8kWJewhGcFFUOsXJB56OnWwbZCxmBrxtGxbY0zYDwRRaBfdJYKw8aVxtD9WI0c9IIIa27M6Ut5C7M1POtrlVgXQ3oUZ0e4gOeZRF0173EoUGXciBfzKY9ubLhkRm4ZcNkjMKIPO9S2k2mSlkWiW7i2PN0pTVFKG4F5EVe92hR6zpBJPF7wmo36KGRjX233232323232'
            }
        }
    }).catch(res => {
        console.log('Error', res);
    });
    console.log(user);
};

userCreate();
```

## Expected behavior
It should be possible to specify longer STRING definitions in schema like:
- TEXT
- LONGTEXT
- MEDIUMTEXT
- TINYTEXT
to save longer texts for saving comments or others information like, web server header request information, bigger log information for a device analyse.

## Prisma information 
```javascript
datasource mysql {
    provider = "mysql"
    url      = "mysql://user:password@localhost:3307/prisma"
}

generator client {
    provider = "prisma-client-js"
  }

model User {
    id                      Int                 @id @default(autoincrement())
    name                String
    comment         String
}
```

## Environment & setup
On my local Macbook Pro, macOS 10.15.3 

- OS: Mac OS
- Database: MySQL
- Prisma version: preview025
- Node.js version: v12.16.1

**Comment by webnoob** [comment] 2020-03-30 12:29
See: https://github.com/prisma/prisma2/discussions/1940

Will be sorted for #446

**Comment by pantharshit00** [comment] 2020-03-31 14:45
Hi,

Thanks for reporting this! It has already been reported before, so I am going to close this as a duplicate of https://github.com/prisma/prisma/issues/1952

**Closed by pantharshit00** 2020-03-31 14:45 UTC
Labels: topic: types
