### ISSUE TITLE
Invalid response data: the query result was required, but an empty Object((Weak)) was returned instead (allsquare)

### ISSUE THREAD

**Issue by divyenduz** [prisma/prisma#1772] opened 2020-03-06 11:09 UTC
Error: `PANIC: internal error: entered unreachable code` on running a create operation from the client:

```
2020-03-05T16:56:56.120Z prisma-client Requests:
2020-03-05T16:56:56.121Z prisma-client [
  'mutation {\n' +
    '  createOneahoy_events(data: {\n' +
    '    created_at: "2024-06-26T14:40:10.450Z"\n' +
    '    id: "ba000471-eabd-55d2-8b42-8ac91ec57e13"\n' +
    '    name: "sab"\n' +
    '    properties: "ziwiwwuh"\n' +
    '    time: "2077-02-06T12:02:57.325Z"\n' +
    '    type: "zeenejom"\n' +
    '    updated_at: "2034-04-09T19:09:04.015Z"\n' +
    '    user_id: 2091163462\n' +
    '    visit_id: "mahbu"\n' +
    '  }) {\n' +
    '    created_at\n' +
    '    id\n' +
    '    name\n' +
    '    properties\n' +
    '    time\n' +
    '    type\n' +
    '    updated_at\n' +
    '    user_id\n' +
    '    visit_id\n' +
    '  }\n' +
    '}'
]
2020-03-05T16:56:56.680Z engine stdout {
  timestamp: 'Mar 05 16:56:56.679',
  level: 'ERROR',
  target: 'prisma',
  fields: {
    message: 'PANIC',
    reason: 'internal error: entered unreachable code',
    file: 'query-engine/core/src/response_ir/mod.rs',
    line: 281,
    column: 38
  }
}
2020-03-05T16:56:56.682Z engine {
  error: Error: socket hang up
      at connResetException (internal/errors.js:604:14)
      at Socket.socketOnEnd (_http_client.js:460:23)
      at Socket.emit (events.js:323:22)
      at Socket.EventEmitter.emit (domain.js:482:12)
      at endReadableNT (_stream_readable.js:1204:12)
      at processTicksAndRejections (internal/process/task_queues.js:84:21) {
    code: 'ECONNRESET'
  }
}
2020-03-05T16:56:56.684Z prisma-client Error: PANIC: internal error: entered unreachable code
    at /home/runner/work/introspection-engine-output/introspection-engine-output/clients/mysql_public_test_utils/allsquare/runtime/index.js:1:17381
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at Dataloader.loader (/home/runner/work/introspection-engine-output/introspection-engine-output/clients/mysql_public_test_utils/allsquare/index.js:56:23)
2020-03-05T16:56:56.684Z printStack callsite Error
    at new ahoy_eventsClient (/home/runner/work/introspection-engine-output/introspection-engine-output/clients/mysql_public_test_utils/allsquare/index.js:2856:21)
    at Object.ahoy_events.create (/home/runner/work/introspection-engine-output/introspection-engine-output/clients/mysql_public_test_utils/allsquare/index.js:2738:7)
    at /home/runner/work/introspection-engine-output/prisma-test-utils/src/static/seed.ts:973:45
    at Generator.next (<anonymous>)
    at /home/runner/work/introspection-engine-output/prisma-test-utils/dist/static/seed.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/home/runner/work/introspection-engine-output/prisma-test-utils/dist/static/seed.js:4:12)
    at iterate (/home/runner/work/introspection-engine-output/prisma-test-utils/dist/static/seed.js:635:24)
    at /home/runner/work/introspection-engine-output/prisma-test-utils/src/static/seed.ts:998:30
    at Generator.next (<anonymous>)
PrismaClientUnknownRequestError: 
Invalid `prisma.ahoy_events.create()` invocation in
/home/runner/work/introspection-engine-output/introspection-engine-output/clients/mysql_public_test_utils/allsquare/index.js:2738:7

PANIC: internal error: entered unreachable code
    at PrismaClientFetcher.request (/home/runner/work/introspection-engine-output/introspection-engine-output/clients/mysql_public_test_utils/allsquare/index.js:90:17)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

This is the code being executed there:

```
async function main() {
  const data = await prisma.ahoy_events.create({
    data: {
      created_at: '2024-06-26T14:40:10.450Z',
      //   id: 'ba000471-eabd-55d2-8b42-8ac91ec57e13', // ConnectorError(ConnectorError { user_facing_error: None, kind: QueryError(Server(ServerError { code: 1406, message: "Data too long for column \'id\' at row 1", state: "22001" })) })
      id: 'ba000471',
      name: 'sab',
      properties: 'ziwiwwuh',
      time: '2077-02-06T12:02:57.325Z',
      type: 'zeenejom',
      updated_at: '2034-04-09T19:09:04.015Z',
      user_id: 2091163462,
      visit_id: 'mahbu',
    },
  })
  console.log({ data })
}

```

All information like schema, datamodel, code etc see this reproduction repo: https://github.com/divyendu-test/p2-1772

Most likely coming from here: https://github.com/prisma/prisma-engines/blob/master/query-engine/core/src/response_ir/mod.rs#L281

**Comment by tomhoule** [comment] 2020-03-06 12:38
With the same schema, running directly against the query engine with the following query, I didn't encounter any error:

```graphql
mutation {
  createOneahoy_events(
    data: {
      created_at: "2024-06-26T14:40:10.450Z"
      id: "ba000471-eabd-55d2-8b42-8ac91ec57e14"
      # id: "ba000471",
      name: "sab"
      properties: "ziwiwwuh"
      time: "2077-02-06T12:02:57.325Z"
      type: "zeenejom"
      updated_at: "2034-04-09T19:09:04.015Z"
      user_id: 2091163462
      visit_id: "mahbu"
    }
  ) {
    created_at
  }
}
```

I'm going to try again with the JS client.

**Comment by tomhoule** [comment] 2020-03-06 12:47
I haven't managed to reproduce the `unreachable` crash yet, but the error about data being too long is an issue. The schema in the repro repository has `binary(16)` as an id column type. It would be enough to hold a binary uuid, but we try to insert it as text and that doesn't work. I don't think we could do the right thing in that case because we're missing the type information.

**Comment by tomhoule** [comment] 2020-03-06 13:01
I have a minimal reproduction for the crash, working on it.

**Comment by tomhoule** [comment] 2020-03-06 14:28
After a bit of investigation:

- We most likely won't be able to make that model work without native database types, because the `id` column is fixed-length (`binary(16)`), so when it is inserted, MySQL will pad it with null bytes. We would need the type information to pad the value ourselves when fetching it back.
- I'm going to open a PR to give a better error message in that case.

**Comment by janpio** [comment] 2020-03-06 15:01
> * We most likely won't be able to make that model work without native database types, because the `id` column is fixed-length (`binary(16)`), so when it is inserted, MySQL will pad it with null bytes. We would need the type information to pad the value ourselves when fetching it back.

This is causing `PANIC: internal error: entered unreachable code`?

**Comment by tomhoule** [comment] 2020-03-06 15:03
yep

**Comment by divyenduz** [comment] 2020-03-11 13:23
In the latest alpha, the error message has changed. I will change the title to reflect that

![image](https://user-images.githubusercontent.com/746482/76421318-7de5a600-63c9-11ea-847b-20d2c5c57729.png)

**Comment by tomhoule** [comment] 2020-03-18 10:28
I am going to unassign myself from this issue, since giving a better error message there is deep internal query engine work that I do not attempt by myself.

**Comment by tomhoule** [comment] 2020-03-18 10:28
@dpetrick  is aware of the issue.

**Comment by janpio** [comment] 2020-03-18 11:24
Running the reproduction locally we do not even get the `Object((Weak))` error message, so it is unclear if this problem really exists the way we think. We will reproduce this again as soon as Introspection CI and test-utils has been cleaned up by @divyenduz

**Comment by pimeys** [comment] 2020-03-19 13:45
I was trying this out in the database a bit, how to actually query these. I'm using the schema above in mysql8, and wrote one item to the database:

``` sql
MySQL [prisma]> select * from ahoy_events where binary visit_id = convert('bang', binary(16));
+------------------+------------------+---------+------+------------+------+------+------------+------------+
| id               | visit_id         | user_id | name | properties | type | time | created_at | updated_at |
+------------------+------------------+---------+------+------------+------+------+------------+------------+
| ba000471         | bang             |       1 | Foo  | None       | Gone | NULL | NULL       | NULL       |
+------------------+------------------+---------+------+------------+------+------+------------+------------+
```

Now if we query

``` sql
SELECT id, visit_id, user_id, name FROM ahoy_events WHERE id = 'ba000471'
```

we get nothing back due to our query term being a varchar and the column a constant-sized binary. In MySQL we can cast our query term to the exact type, which allows querying and returns the result we want:

``` sql
MySQL [prisma]> select id, visit_id, user_id, name from ahoy_events where binary id = convert('ba000471', binary(16));
+------------------+------------------+---------+------+
| id               | visit_id         | user_id | name |
+------------------+------------------+---------+------+
| ba000471         | bang             |       1 | Foo  |
+------------------+------------------+---------+------+
1 row in set (0.001 sec)
```

This requires the datamodel to hold more accurate type information, or let's call it type hints of the underlying datamodel. And this only works with MySQL, while the other databases have different ways of converting and more importantly different datatype names and possibilities to convert between them.

**Comment by pantharshit00** [comment] 2020-07-24 13:44
This is not stale. Removing the label.

**Comment by pimeys** [comment] 2021-02-09 18:48
This kind of changes with the native types. The database in the linked ticket is introspected as:

```prisma
datasource db {
  provider = "mysql"
  url      = "mysql://root:prisma@localhost:3307/prisma"
}

model ahoy_events {
  id         Bytes     @id @db.Binary(16)
  visit_id   Bytes?    @db.Binary(16)
  user_id    Int?
  name       String?   @db.VarChar(255)
  properties String?   @db.Text
  type       String?   @db.Text
  time       DateTime? @db.DateTime(0)
  created_at DateTime? @db.DateTime(0)
  updated_at DateTime? @db.DateTime(0)

  @@index([id], name: "index_ahoy_events_on_id")
  @@index([time], name: "index_ahoy_events_on_time")
  @@index([user_id], name: "index_ahoy_events_on_user_id")
  @@index([visit_id], name: "index_ahoy_events_on_visit_id")
}
```

So, now when inserting, the binary params must be sent as bytes and the bytes can be converted to and from with e.g. the [uuid library](https://www.npmjs.com/package/uuid):

```javascript
import { PrismaClient } from '@prisma/client'
import { parse as uuidParse } from 'uuid'

const prisma = new PrismaClient()

async function main() {
    let user = await prisma.ahoy_events.create({
        data: {
            id: Buffer.from(uuidParse('ba000471-eabd-55d2-8b42-8ac91ec57e13')),
        }
    });

    console.log(user)
}

main()
    .catch(e => {
        throw e
    })

    .finally(async () => {
        await prisma.$disconnect()
    })
```

Would this be enough to support `binary(16)` uuid values? If not, we might want to introduce a new type: `Uuid`.

**Comment by pantharshit00** [comment] 2021-05-04 16:28
I guess we can close this now.

**Closed by pantharshit00** 2021-05-04 16:28 UTC
Labels: bug/2-confirmed, kind/bug, status/needs-action, team/client, tech/engines, topic: test-utils
