### ISSUE TITLE
Allow Specifying prisma.yml path and make datamodel property optional

### ISSUE THREAD

**Issue by BenoitRanque** [prisma/prisma#4047] opened 2019-02-13 15:29 UTC
## Use Case
I am setting up an apollo graphql server that must consume two prisma services and present them as one. The first service is for server data, the second service for auth.
The auth service is defined in a separate repo and is used by multiple services

## Problem
The issue is generating the prisma client or bindings. Prisma.yml by design only allows for configuring a single service, and as far as I can tell cannot be renamed.

## Solution
One possible solution would be making two changes to the prisma cli:
* Allow specifying name and path for prisma.yml when executing a command
* Make datamodel property in prisma.yml optional. When absent the prisma.yml cannot modify the underlying schema.

This would make the following possible:

```bash
prisma -f path/to/prisma.yml generate
```
This would run the `generate` command using the `prisma.yml` found found at `path/to/`

## Fallback
For now I am considering falling back to `graphql get-schema`

**Comment by pantharshit00** [comment] 2019-02-14 14:59
Just realized that this is a duplicate of # 3140.

There is already a PR now that will implement this #4053 

Closing as duplicate

**Closed by pantharshit00** 2019-02-14 14:59 UTC
Labels: area/cli, kind/feature, rfc/0-needs-spec
