### ISSUE TITLE
Export import fails

### ISSUE THREAD

**Issue by tomitrescak** [prisma/prisma#3183] opened 2018-09-25 04:49 UTC
**Describe the bug**

I am trying to import exported data from the server and I am getting may errors of `Failure inserting RelayRow with Id: spbk0000004. Cause: .SQLIntegrityConstraintViolationException: (conn=30124) Duplicate entry 'spbk0002502' for key 'PRIMARY'`. 

I am sure that the data is correct, or at least I cannot find two rows with the same id.

**To Reproduce**

Use following NDF dump:

[prisma.zip](https://github.com/prisma/prisma/files/2413797/prisma.zip)

With the following schema:

```
type super_book {
  id: ID! @unique
  super_book_title: String
  keywords: String
  parisian_keyword: String
  illegality: String
  bannedBy: manuscript_titles_illegal @relation(name: "BannedBook")
}

type manuscript_book {
  id: ID! @unique
  super_book_title: String
  keywords: String
  parisian_keyword: String
  illegality: String
}

type manuscript_titles_illegal {
  id: ID! @unique
  UUID: String!
  illegal_super_book_code: String!
  illegal_full_book_title: String!
  illegal_author_code: String!
  illegal_author_name: String!
  illegal_date: String!
  illegal_folio: String!
  illegal_notes: String!
  record_status: String!
  bastille_book_category: String!
  bastille_imprint_full: String!
  bastille_total_volumes: String!
  bastille_current_volumes: String!
  bastille_copies_number: String!
  bans: super_book @relation(name: "BannedBook")
}
```

**Expected behavior**
Data import executes correctly

**Versions (please complete the following information):**
 - OS: OS X High Sierra
 - prisma/1.17.0-beta.30 (darwin-x64) node-v10.9.0

**Additional context**

**Comment by do4gr** [comment] 2019-03-01 12:02
Hey, 
this sounds like a case where there could be data already in the db. 
What was your process for exporting/importing? 
Did you export and import from the same project?
Did you wipe the data from the db in between? How? With Prisma reset? Or did you just restart the db container?

If you have a current reproduction available @k0ff33 or @tomitrescak, I'll look into it.

**Comment by tomitrescak** [comment] 2019-03-03 22:39
@do4gr there is repro attached to this issue. The data was wiped clean from the DB.

**Comment by do4gr** [comment] 2019-03-06 13:56
Hey @tomitrescak, 
I finally got around to look into the issue. Sorry it took so long. I got the same Relay table error for the following id: `spbk0005097`. The Relay table used to power the node query that lets you request any node just by it's id, without providing the type. 

I then checked how often this id is present in the nodes. That id is being used twice, once for a manuscript_book and once for a super-book. The RelayId table has a mapping from every id to the corresponding type and has a unique constraint on the id and therefore then fails. 

With datamodel v.1.1 we will remove the Relay table and this would not error anymore during import. But you would run the risk of getting a wrong response from the node query since it still assumes global uniqueness for ids and would just return the first item with that id it finds, not both. 

We therefore strongly recommend keeping ids globally unique and not just unique per type. Maybe in your case you could prepend or append something type specific to the ids to make them globally unique?

**Comment by do4gr** [comment] 2019-03-06 13:58
@k0ff33 , your problem sounds like a separate issue since it does not only affect the Relay table. If you have a import file to help me reproduce it I'll look into it as well.

**Comment by k0ff33** [comment] 2019-03-07 11:20
Hi @do4gr, here's an import file along with with a schema: [prisma-export-bug.zip](https://github.com/prisma/prisma/files/2940917/prisma-export-bug.zip).

Sorry for the amount of data, it's literally a dump of my dev db.

```
$ prisma reset
? Are you sure that you want to reset the data of prisma-export-bug in stage dev? y/N y
Resetting prisma-export-bug@dev 7716ms

$ prisma import --data export-2019-03-07T10:26:42.282Z.zip
Unzipping 81ms
Validating data 702ms

Uploading nodes...
[
  "Failure inserting ProductCategory with Id: cjribd41w0d800850vhb6zmgz. Cause: .SQLIntegrityConstraintViolationException: (conn=107484) Duplicate entry 'T-shirt' for key 'name_UNIQUE'"
]
```

**Comment by do4gr** [comment] 2019-03-07 12:21
Hey, no worries, that'll hopefully help me pinpoint the issue. Thanks!

**Comment by do4gr** [comment] 2019-03-15 12:19
Hey @k0ff33 ,

I looked into your import. Your datamodel defines Productcategory like this: 

```graphql
type ProductCategory {
  id: ID! @unique
  name: String! @unique
  products: [Product!]! @relation(name: "ProductCategory")
}
```

But you try to import this data: 

```
"_typeName":"ProductCategory","id":"cjribd41w0d800850vhb6zmgz","name":"T-shirt","updatedAt":"2019-01-29T22:08:39.612Z","createdAt":"2019-01-29T22:08:39.612Z"},

{"_typeName":"ProductCategory","id":"cjqsdo36w01xl0837hj6hs00k","name":"T-Shirt","updatedAt":"2019-01-11T18:31:10.359Z","createdAt":"2019-01-11T18:31:10.359Z"}
```

You then get a unique violation when trying to import the data which looks ok to me since you defined name as being unique.

**Comment by biels** [comment] 2019-03-21 04:45
But if he is importing and exporting using prisma export/import, why is the data being duplicated at some point? It is clearly not the data's fault since it comes from the same db that is enforcing those constraints.

The same is still happening to me when I try to export, reset and import on prisma 1.29. Please solve, this is a blocker.

**Comment by do4gr** [comment] 2019-03-21 15:16
Hey, @biels 

one case where I could see this happening going from Prisma to Prisma is if the Prisma instances are using different underlying databases. They treat string comparison differently as I wrote. 

Can you provide me with a reproduction repo for your issue please? Then I can look into it.

**Comment by biels** [comment] 2019-03-21 16:08
I was using the same exact prisma instance that operated on the same postgres instance. 
The apparent reason it was not working is because the docker volume that contained the postgres data was full / not allowed to grow by docker. I fixed it by cleaning unused images and volumes. Maybe a guide on how to configure the docker volume appropriately to store arbitrary amounts of data would be helpful.

**Comment by divyenduz** [comment] 2019-03-22 10:32
@biels : Thanks for raising this issue and as we sorted it out in the slack conversation, this was related to the docker mount point being full, I am closing this issue. Please feel free to open a new issue, if required.

**Closed by divyenduz** 2019-03-22 10:32 UTC
Labels: bug/1-repro-available

**Comment by k0ff33** [comment] 2019-04-01 15:44
Hi @do4gr, just to follow up, the database indeed was manually migrated from MySQL to Postgres, so I guess the data was duplicated at some point after the migration (it's user-generated). Thanks for checking the dump, it makes sense now.
