### ISSUE TITLE
postgresql column type date error

### ISSUE THREAD

**Issue by sunkainj** [prisma/prisma#1541] opened 2020-02-06 10:00 UTC
```
Reason: Error occurred during query execution:
ConnectorError(ConnectorError { user_facing_error: None, kind: QueryError(Error { kind: FromSql(1), cause: Some(WrongType { postgres: Type(Date), rust: "core::option::Option<alloc::string::String>" }) }) })

generated model
model account {
  avatarpath     String
  birthday       DateTime
  email          String
  emailisvalid   Boolean  @default(false)
  gender         Boolean
  id             Int      @id
  lastactiveip   String
  lastactivetime DateTime
  mobile         String
  mobileisvalid  Boolean  @default(false)
  password       String
  qq             String
  realname       String
  regip          String
  regtime        DateTime
  roleid         Int
  username       String
  wx             String
}

table sql
-- DROP TABLE public.account;

CREATE TABLE public.account
(
    id integer NOT NULL DEFAULT nextval('account_id_seq'::regclass),
    username character varying(64) COLLATE pg_catalog."default" NOT NULL,
    password character varying(64) COLLATE pg_catalog."default" NOT NULL,
    email character varying(140) COLLATE pg_catalog."default" NOT NULL,
    mobile character varying(140) COLLATE pg_catalog."default" NOT NULL,
    gender boolean NOT NULL,
    birthday date NOT NULL,
    roleid integer NOT NULL DEFAULT (10)::smallint,
    avatarpath character varying(20) COLLATE pg_catalog."default" NOT NULL,
    regtime timestamp without time zone NOT NULL,
    regip character varying(15) COLLATE pg_catalog."default" NOT NULL,
    lastactivetime timestamp without time zone NOT NULL,
    lastactiveip character varying(15) COLLATE pg_catalog."default" NOT NULL,
    qq character varying(140) COLLATE pg_catalog."default" NOT NULL,
    wx character varying(140) COLLATE pg_catalog."default" NOT NULL,
    realname character varying(50) COLLATE pg_catalog."default" NOT NULL,
    mobileisvalid boolean NOT NULL DEFAULT false,
    emailisvalid boolean NOT NULL DEFAULT false,
    CONSTRAINT account_pkey PRIMARY KEY (id)
)
WITH (
    OIDS = FALSE
)
TABLESPACE pg_default;

ALTER TABLE public.account
    OWNER to postgres;
```

node.js code
```
const { PrismaClient } = require('@prisma/client')

const prisma = new PrismaClient()

async function main() {
  const account = await prisma.account.findOne({ where: { id: 1 } })
  console.log(account)
}
main()
```

column birthday error occurred 

I changed birthday type to timestamp without time zone, it works.

**Comment by janpio** [comment] 2020-02-06 12:47
Thanks @sunkainj, can you provide some more information what command throws this error message? 
What exactly was `birthday` before, and to what exactly did you change it? What command did you run then?

**Comment by sunkainj** [comment] 2020-02-06 14:36
I follow Getting started and find step 4 and 6  is npx prisma2 introspect and npx prisma2 generate.
table sql, and node.js code is above.
my postgresql version is latest 12.1

1,create a table
```
-- Table: public.account

-- DROP TABLE public.account;

CREATE TABLE public.account
(
    id integer NOT NULL,
    birthday date NOT NULL,
    CONSTRAINT account_pkey PRIMARY KEY (id)
)

TABLESPACE pg_default;

ALTER TABLE public.account
    OWNER to postgres;
```
2,insert data
`insert into account (id, birthday) values (1, '1980/1/1')`

3,follow Getting started of prisma2
and run node.js code 
```
const { PrismaClient } = require('@prisma/client')

const prisma = new PrismaClient()

async function main() {
  const account = await prisma.account.findOne({ where: { id: 1 } })
  console.log(account)
}
main()
```
4,You will find error!
```
Reason: Error occurred during query execution:
ConnectorError(ConnectorError { user_facing_error: None, kind: QueryError(Error { kind: FromSql(0), cause: Some(WrongType { postgres: Type(Date), rust: "core::option::Option<alloc::string::String>" }) }) })
```
5, change postgresql column type is:
```
ALTER TABLE public.account
    ALTER COLUMN birthday TYPE timestamp without time zone ;
```
6，run node.js code, it works.

**Comment by janpio** [comment] 2020-02-06 14:40
Can you please investigate @pantharshit00 and see what is going on here? Thanks.

**Comment by pantharshit00** [comment] 2020-02-08 01:19
Yeah, so I can confirm this. I think this is related to #446 and there is also a related issue in quaint: https://github.com/prisma/quaint/issues/64

But I do think we might look into supporting `date` as it is a common database type via introspection so marking this as a bug.

**Comment by janpio** [comment] 2020-02-08 14:47
Can you please document how exactly you reproduce this @pantharshit00?

**Comment by pantharshit00** [comment] 2020-02-08 15:10
I used the exact steps mentioned by @sunkainj in his second comment

**Comment by albertoperdomo** [comment] 2021-02-03 15:04
Looks like a client-side error but this is old and this may no longer be an issue with the native types implementation.

**Comment by pimeys** [comment] 2021-02-09 19:05
Can confirm. This now works with native types on, the introspected data model:

```prisma
generator client {
  provider        = "prisma-client-js"
  previewFeatures = ["nativeTypes"]
}

datasource db {
  provider = "postgresql"
  url      = "postgres://postgres:prisma@localhost:5432/postgres"
}

model account {
  id             Int      @id @default(autoincrement())
  username       String   @db.VarChar(64)
  password       String   @db.VarChar(64)
  email          String   @db.VarChar(140)
  mobile         String   @db.VarChar(140)
  gender         Boolean
  birthday       DateTime @db.Date
  roleid         Int      @default(dbgenerated("(10)::smallint"))
  avatarpath     String   @db.VarChar(20)
  regtime        DateTime @db.Timestamp(6)
  regip          String   @db.VarChar(15)
  lastactivetime DateTime @db.Timestamp(6)
  lastactiveip   String   @db.VarChar(15)
  qq             String   @db.VarChar(140)
  wx             String   @db.VarChar(140)
  realname       String   @db.VarChar(50)
  mobileisvalid  Boolean  @default(false)
  emailisvalid   Boolean  @default(false)
}
```

I can query the birthday and I can get a datetime out (with the time set to zero).

**Comment by pimeys** [comment] 2021-02-11 09:52
Closing the issue. It's tested and works with native types on.

**Closed by pimeys** 2021-02-11 09:52 UTC
Labels: bug/2-confirmed, kind/bug, team/client, topic: native database types
