### ISSUE TITLE
Unclear Introspection error message: Error parsing attribute "@id": Fields that are marked as id must be required.

### ISSUE THREAD

**Issue by janpio** [prisma/prisma#1368] opened 2020-01-17 13:34 UTC
Introspecting SQLite:

```
CREATE TABLE "playlist_track" (
	"PlaylistId"	INTEGER NOT NULL,
	"TrackId"	INTEGER NOT NULL,
	"id"	INTEGER PRIMARY KEY AUTOINCREMENT,
	FOREIGN KEY("PlaylistId") REFERENCES "playlists"("PlaylistId") ON DELETE NO ACTION ON UPDATE NO ACTION,
	FOREIGN KEY("TrackId") REFERENCES "tracks"("TrackId") ON DELETE NO ACTION ON UPDATE NO ACTION
)
```

Creates error message:

```
 ERROR  Oops, an unexpected error occured!
Schema parsing

error: Error parsing attribute "@id": Fields that are marked as id must be required.
  -->  schema.prisma:126
   |
125 |   TrackId    tracks
126 |   id         Int?      @id
   |
```

Error message does not include name of table/model for context.

**Comment by janpio** [comment] 2020-01-30 16:26
Problem: No NOT NULL on `id`.

**Comment by janpio** [comment] 2020-02-04 14:27
Investigation into how SQLite works:

Create a table with this SQL:
```
CREATE TABLE "testing" (
	"id"	INTEGER,
	PRIMARY KEY("id")
);
```

Executing `INSERT INTO testing (id) VALUES (NULL)` creates a column with the `id` filled with the next auto increment value.

## Decision

Integer PKs should therefore be inferred as Autoincrement NOT NULL.

**Comment by sorenbs** [comment] 2020-02-04 15:04
For clarification:

The consequence of inferring Integer PKs as Autoincrement NOT NULL (or as it would look like in the schema.prisma file: `Int @id @default(autoincrement())`) is that the id would be optional when writing, and non-null when reading.

DECISION: this is excellent!

See also https://github.com/prisma/specs/issues/176#issuecomment-561289686 for context on autoincrement syntax.

**Comment by divyenduz** [comment] 2020-05-26 14:39
I could observe this issue in introspection CI. Re-opening it to re-triage.

**Comment by divyenduz** [comment] 2020-05-26 14:56
This is not observed any longer for simple example like: 

```
CREATE TABLE "testing" (
	"id"	INTEGER,
	PRIMARY KEY("id")
);
```

However, it is still observed in the following schema: https://github.com/prisma/database-schema-examples/tree/master/sqlite/sql-mysteries

**Comment by pantharshit00** [comment] 2020-05-27 13:42
@divyenduz I am unable to reproduce the error in the latest alpha:
![image](https://user-images.githubusercontent.com/22195362/83027544-da15a900-a04d-11ea-9fbb-1f5313f4ce13.png)

It passed through introspection without any error, there are warning for the model which doesn't have an identifier.

Introspected schema result:
```prisma
datasource db {
  provider = "sqlite"
  url      = "file:./schema.db"
}

// The underlying table does not contain a unique identifier and can therefore currently not be handled.
// model crime_scene_report {
  // city        String?
  // date        Int?
  // description String?
  // type        String?
// }

model drivers_license {
  age          Int?
  car_make     String?
  car_model    String?
  eye_color    String?
  gender       String?
  hair_color   String?
  height       Int?
  id           Int      @default(autoincrement()) @id
  plate_number String?
  person       person[]
}

model person {
  address_number      Int?
  address_street_name String?
  id                  Int                  @default(autoincrement()) @id
  license_id          Int?
  name                String?
  ssn                 Int?
  drivers_license     drivers_license?     @relation(fields: [license_id], references: [id])
  get_fit_now_member  get_fit_now_member[]
}

// The underlying table does not contain a unique identifier and can therefore currently not be handled.
// model facebook_event_checkin {
  // date       Int?
  // event_id   Int?
  // event_name String?
  // person_id  Int?
  // person     person? @relation(fields: [person_id], references: [id])
// }

// The underlying table does not contain a unique identifier and can therefore currently not be handled.
// model interview {
  // person_id  Int?
  // transcript String?
  // person     person? @relation(fields: [person_id], references: [id])
// }

model get_fit_now_member {
  id                    String? @id
  membership_start_date Int?
  membership_status     String?
  name                  String?
  person_id             Int?
  person                person? @relation(fields: [person_id], references: [id])
}

// The underlying table does not contain a unique identifier and can therefore currently not be handled.
// model get_fit_now_check_in {
  // check_in_date      Int?
  // check_in_time      Int?
  // check_out_time     Int?
  // membership_id      String?
  // get_fit_now_member get_fit_now_member? @relation(fields: [membership_id], references: [id])
// }

model income {
  annual_income Int?
  ssn           Int  @default(autoincrement()) @id
}

// The underlying table does not contain a unique identifier and can therefore currently not be handled.
// model solution {
  // user  Int?
  // value String?
// }
```

Version used:
```
@prisma/cli          : 2.0.0-beta.6
Current platform     : debian-openssl-1.1.x
Query Engine         : query-engine c48b94aa8d1d9a0e5582dcd14e25202b76303dca (at /home/harshit/.nvm/versions/node/v12.16.3/lib/node_modules/@prisma/cli/query-engine-debian-openssl-1.1.x)
Migration Engine     : migration-engine-cli c48b94aa8d1d9a0e5582dcd14e25202b76303dca (at /home/harshit/.nvm/versions/node/v12.16.3/lib/node_modules/@prisma/cli/migration-engine-debian-openssl-1.1.x)
Introspection Engine : introspection-core c48b94aa8d1d9a0e5582dcd14e25202b76303dca (at /home/harshit/.nvm/versions/node/v12.16.3/lib/node_modules/@prisma/cli/introspection-engine-debian-openssl-1.1.x)
Format Binary        : prisma-fmt c48b94aa8d1d9a0e5582dcd14e25202b76303dca (at /home/harshit/.nvm/versions/node/v12.16.3/lib/node_modules/@prisma/cli/prisma-fmt-debian-openssl-1.1.x)
```

**Comment by divyenduz** [comment] 2020-05-27 13:57
Your output has and optional ID, so, `generate` should fail (I should have mentioned that sorry)

```
model get_fit_now_member {
  id                    String? @id
```

**Comment by pantharshit00** [comment] 2020-05-27 22:03
Oh yes, thanks for catching

**Comment by do4gr** [comment] 2020-11-04 10:18
Introspection delivers the correct representation of the db schema here. Then generate and the schema validation rightfully fail with the proper error that the id needs to be required. I looked at the underlying sql schema for the sqlite db and that id field should really be required I think. 

The only improvement I could see here is to comment that model out already during introspection since we cannot handle it anyways. I think only sqlite is affected so I'd see that as a minor bugfix.

**Comment by tomhoule** [comment] 2021-02-11 10:45
This will probably lead to an `@@ignore` on the model now, but work. To be confirmed.

**Comment by tomhoule** [comment] 2021-02-17 09:58
Scheduling for this release to confirm that `@ignore` fixes this.

**Comment by do4gr** [comment] 2021-03-18 11:34
This can only occur on SQLite since only there are optional id fields valid DDL. Models with an optional Id will now be marked as @@ignore during introspection and won't cause a validation error. If a model is handwritten with an optional id and without @@ignore, you'll still get the same validation error which is then clear enough.

**Closed** 2021-03-18 17:28 UTC
Labels: bug/2-confirmed, kind/bug, team/migrations, topic: introspection
