### ISSUE TITLE
Foreign key indexes are not well changed by prisma

### ISSUE THREAD

**Issue by bigTeethLi** [prisma/prisma#12288] opened 2022-03-12 00:54 UTC
### Bug description

If I initially create a 1:1 relation and then need to change it to a many-to-many relation, the foreign key index does not change from unique to non-unique. And need to drop the table and then re-create, the foreign key index can be updated.

### How to reproduce

1. Create a `1:1 relation`
2. Run `prisma generate && prisma db push`
3. Change the `1:1 relation` to `Many-to-Many relation`
4. Run `prisma generate && prisma db push`
5. See error, the foreign key is still a unique index
![image](https://user-images.githubusercontent.com/101170394/157794781-89fee53d-3aff-4e34-a49b-14855c000130.png)
7. Then I drop the table and run `prisma generate && prisma db push`, the foreign key can only be changed to non-unique indexes
![image](https://user-images.githubusercontent.com/101170394/157796436-a9cacf29-10ef-4aa1-bd07-ad991f90bf3e.png)

### Prisma information

1:1 relation(use [Official document example](https://www.prisma.io/docs/concepts/components/prisma-schema/relations/many-to-many-relations))
```prisma
model Post {
  id         Int                 @id @default(autoincrement())
  title      String
  categories CategoriesOnPosts?
}

model Category {
  id    Int                 @id @default(autoincrement())
  name  String
  posts CategoriesOnPosts?
}

model CategoriesOnPosts {
  post       Post     @relation(fields: [postId], references: [id])
  postId     Int // relation scalar field (used in the `@relation` attribute above)
  category   Category @relation(fields: [categoryId], references: [id])
  categoryId Int // relation scalar field (used in the `@relation` attribute above)
  assignedAt DateTime @default(now())
  assignedBy String

  @@id([postId, categoryId])
}
```

Then change to `Many-to-Many relation`(only "?" to "[]"):
```prisma
model Post {
  id         Int                 @id @default(autoincrement())
  title      String
  categories CategoriesOnPosts[]
}

model Category {
  id    Int                 @id @default(autoincrement())
  name  String
  posts CategoriesOnPosts[]
}

model CategoriesOnPosts {
  post       Post     @relation(fields: [postId], references: [id])
  postId     Int // relation scalar field (used in the `@relation` attribute above)
  category   Category @relation(fields: [categoryId], references: [id])
  categoryId Int // relation scalar field (used in the `@relation` attribute above)
  assignedAt DateTime @default(now())
  assignedBy String

  @@id([postId, categoryId])
}
```

### Environment & setup

- OS: MAC OS
- Database: MySQL
- Node.js version: v16.13.2

### Prisma Version

```
prisma: "3.9.1"
```

**Comment by Alverrt** [comment] 2022-04-18 21:22
I have the similar issue. Here is my model.

![Screen Shot 2022-04-19 at 00 18 22](https://user-images.githubusercontent.com/57076713/163879633-0b89d690-9d61-4d39-a2c2-dbba884ca31b.png)

Then I type `npx prisma db push`. And cli says everything is fine. Then I type `npx prisma db pull`. The `@unique` attribute keep coming back.

![Screen Shot 2022-04-19 at 00 21 24](https://user-images.githubusercontent.com/57076713/163880063-82617031-32ab-464c-8815-f356849f9950.png)

**Comment by janpio** [comment] 2022-04-20 18:45
Just to confirm: Are you also on MySQL @Alverrt?

**Comment by janpio** [comment] 2022-04-20 18:53
I can not reproduce your simplified case @Alverrt:

I start with this schema:
```prisma
generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "mysql"
  url      = env("DATABASE_URL")
}

model Foo {
  id  Int @id @default(autoincrement())
  bar Int @unique
}
```

Migrate via `db push`, and see that indeed a unique key was created.

Then I remove the `@unique` for this schema:
```prisma
generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "mysql"
  url      = env("DATABASE_URL")
}

model Foo {
  id  Int @id @default(autoincrement())
  bar Int
}
```

Running `db push` indeed does remove the unique constraint, and running `db pull` again does not change the schema.

Adding another field and then an unique that covers both fields, does not change the outcome:

```prisma
model Foo {
  id  Int @id @default(autoincrement())
  baz Int
  bar Int @unique

  @@unique([baz, bar])
}
```

I suggest you create a new issue @Alverrt so we can investigate this better. Thanks!

**Comment by janpio** [comment] 2022-04-20 19:03
Hey @bigTeethLi, I tested this with Prisma 3.12.0 and unfortunately could not reproduce:

I started with this schema file:
```prisma
generator client {
  provider        = "prisma-client-js"
  previewFeatures = ["referentialIntegrity"]
}

datasource db {
  provider             = "mysql"
  url                  = env("DATABASE_URL")
  referentialIntegrity = "prisma"
}

model Post {
  id         Int                @id @default(autoincrement())
  title      String
  categories CategoriesOnPosts?
}

model Category {
  id    Int                @id @default(autoincrement())
  name  String
  posts CategoriesOnPosts?
}

model CategoriesOnPosts {
  post       Post     @relation(fields: [postId], references: [id])
  postId     Int // relation scalar field (used in the `@relation` attribute above)
  category   Category @relation(fields: [categoryId], references: [id])
  categoryId Int // relation scalar field (used in the `@relation` attribute above)
  assignedAt DateTime @default(now())
  assignedBy String

  @@id([postId, categoryId])
}
```

When formatting the Prisma schema file, Prisma automatically added the `@unique` explicitly to the two fields:

```prisma
model CategoriesOnPosts {
  post       Post     @relation(fields: [postId], references: [id])
  postId     Int      @unique // relation scalar field (used in the `@relation` attribute above)
  category   Category @relation(fields: [categoryId], references: [id])
  categoryId Int      @unique // relation scalar field (used in the `@relation` attribute above)
  assignedAt DateTime @default(now())
  assignedBy String

  @@id([postId, categoryId])
}
```

Then I ran `db push` and got 2 unique constraints created:

```sql
CREATE TABLE `CategoriesOnPosts` (
  `postId` int NOT NULL,
  `categoryId` int NOT NULL,
  `assignedAt` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `assignedBy` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  PRIMARY KEY (`postId`,`categoryId`),
  UNIQUE KEY `CategoriesOnPosts_postId_key` (`postId`),
  UNIQUE KEY `CategoriesOnPosts_categoryId_key` (`categoryId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
```

Then I changed the models:

```prisma
model Post {
  id         Int                 @id @default(autoincrement())
  title      String
  categories CategoriesOnPosts[]
}

model Category {
  id    Int                 @id @default(autoincrement())
  name  String
  posts CategoriesOnPosts[]
}

model CategoriesOnPosts {
  post       Post     @relation(fields: [postId], references: [id])
  postId     Int // relation scalar field (used in the `@relation` attribute above)
  category   Category @relation(fields: [categoryId], references: [id])
  categoryId Int // relation scalar field (used in the `@relation` attribute above)
  assignedAt DateTime @default(now())
  assignedBy String

  @@id([postId, categoryId])
}
```

(This time formatting did not add any `@unique`, as it should not).

Then I ran `db push` and the two constraints were removed in the database as well:

```sql
CREATE TABLE `CategoriesOnPosts` (
  `postId` int NOT NULL,
  `categoryId` int NOT NULL,
  `assignedAt` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `assignedBy` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  PRIMARY KEY (`postId`,`categoryId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
```

Can you maybe try to reproduce your problem again with the newest Prisma version?

**Comment by janpio** [comment] 2022-07-28 18:18
Ping @Alverrt + @bigTeethLi - is this still a problem? Or did it go away?

**Comment by janpio** [comment] 2022-10-05 21:42
Hey, last ping @Alverrt and @bigTeethLi - we would love to fix this bug if it is real, but with no further information we have no way of doign that. We would really love if you could help us here. Otherwise we will have to close this issue until someone reports it again 😢

**Comment by Jolg42** [comment] 2022-10-11 09:07
We are closing this but we're happy to reopen if you have more information.

**Closed by Jolg42** 2022-10-11 09:07 UTC
Labels: bug/0-unknown, kind/bug, topic: migrate, tech/engines, topic: mysql, topic: indexes, team/schema
