### ISSUE TITLE
Cannot merge arrays in prisma.$transaction

### ISSUE THREAD

**Issue by P4sca1** [prisma/prisma#3958] opened 2020-10-17 12:39 UTC
Relates to https://github.com/prisma/prisma/issues/3104

## Bug description

When you have a transaction that uses `updateMany` or `deleteMany` (operations on multiple objects) together with `create`, `update`, `upsert` or `delete` (operations on a single object), you cannot use the array spread operator without a TypeScript error.

```
No overload matches this call.
  The last overload gave the following error.
    Argument of type '(Prisma__UserClient<User> | Promise<BatchPayload>)[]' is not assignable to parameter of type 'Iterable<User | PromiseLike<User>>'.
      The types returned by '[Symbol.iterator]().next(...)' are incompatible between these types.
        Type 'IteratorResult<Prisma__UserClient<User> | Promise<BatchPayload>, any>' is not assignable to type 'IteratorResult<User | PromiseLike<User>, any>'.
          Type 'IteratorYieldResult<Prisma__UserClient<User> | Promise<BatchPayload>>' is not assignable to type 'IteratorResult<User | PromiseLike<User>, any>'.
            Type 'IteratorYieldResult<Prisma__UserClient<User> | Promise<BatchPayload>>' is not assignable to type 'IteratorYieldResult<User | PromiseLike<User>>'.
              Type 'Prisma__UserClient<User> | Promise<BatchPayload>' is not assignable to type 'User | PromiseLike<User>'.
                Type 'Promise<BatchPayload>' is not assignable to type 'User | PromiseLike<User>'.
                  Type 'Promise<BatchPayload>' is not assignable to type 'PromiseLike<User>'.
                    Types of property 'then' are incompatible.
                      Type '<TResult1 = BatchPayload, TResult2 = never>(onfulfilled?: ((value: BatchPayload) => TResult1 | PromiseLike<TResult1>) | null | undefined, onrejected?: ((reason: any) => TResult2 | PromiseLike<...>) | ... 1 more ... | undefined) => Promise<...>' is not assignable to type '<TResult1 = User, TResult2 = never>(onfulfilled?: ((value: User) => TResult1 | PromiseLike<TResult1>) | null | undefined, onrejected?: ((reason: any) => TResult2 | PromiseLike<...>) | null | undefined) => PromiseLike<...>'.
                        Types of parameters 'onfulfilled' and 'onfulfilled' are incompatible.
                          Types of parameters 'value' and 'value' are incompatible.
                            Type 'BatchPayload' is missing the following properties from type 'User': id, username, email, password, and 6 more.ts(2769)
lib.es2015.iterable.d.ts(226, 5): The last overload is declared here.
```

## How to reproduce

```ts
const test = [
  prisma.user.create({
    data: { username: 'test', email: 'test@example.com', password: 'test' },
  }),
]

// This gives a TypeScript error
prisma.$transaction([
  // deleteMany or updateMany
  prisma.user.deleteMany({
    where: { id: 1 },
  }),
  // Cannot be mixed with create, upsert, update or delete when using array spread operator
  ...test,
])
```

## Expected behavior

The above code should not give a TypeScript error and work the same way as the following code does:
```ts
// This does not give a TypeScript error
prisma.$transaction([
  prisma.user.deleteMany({
    where: { id: 1 },
  }),
  prisma.user.create({
    data: { username: 'test', email: 'test@example.com', password: 'test' },
  }),
])
```

## Prisma information

```
generator client {
  provider        = "prisma-client-js"
  output          = "./src/graphql/generated/prisma-client"
  binaryTargets   = ["native", "debian-openssl-1.1.x"]
  previewFeatures = ["transactionApi"]
}

datasource db {
  provider = "mysql"
  url      = env("DATABASE_URL")
}

model User {
  id                     Int                     @id @default(autoincrement())
  username               String                  @unique
  email                  String                  @unique
  password               String

  @@map("user")
}
```

## Environment & setup

- OS: Mac OS
- Database: MySQL
- Node.js version: 12.16.2
- Prisma version:

```
@prisma/cli          : 2.9.0
@prisma/client       : 2.9.0
Current platform     : darwin
Query Engine         : query-engine 369b3694b7edb869fad14827a33ad3f3f49bbc20 (at node_modules/@prisma/cli/query-engine-darwin)
Migration Engine     : migration-engine-cli 369b3694b7edb869fad14827a33ad3f3f49bbc20 (at node_modules/@prisma/cli/migration-engine-darwin)
Introspection Engine : introspection-core 369b3694b7edb869fad14827a33ad3f3f49bbc20 (at node_modules/@prisma/cli/introspection-engine-darwin)
Format Binary        : prisma-fmt 369b3694b7edb869fad14827a33ad3f3f49bbc20 (at node_modules/@prisma/cli/prisma-fmt-darwin)
Studio               : 0.296.0
```

**Comment by P4sca1** [comment] 2020-10-17 12:45
The error also occurs when using `.concat`:
```ts
prisma.$transaction(
  [
    prisma.user.deleteMany({
      where: { id: 1 },
    }),
  // This also gives a TypeScript error
  ].concat(test)
)
```

**Comment by vrg-success** [comment] 2020-10-17 14:30
@P4sca1  Dude I wrote 2 issue, and I didn't get answer, I forced back to typeorm...  key factor for me became flexibility transaction

**Comment by pantharshit00** [comment] 2020-10-19 13:49
I can reproduce this and this has been reported before.

Closing as duplicate of https://github.com/prisma/prisma-client-js/issues/894

**Closed by pantharshit00** 2020-10-19 13:49 UTC
Labels: bug/0-needs-info, kind/bug, topic: previewFeatures, topic: transactionApi
