### ISSUE TITLE
Invalid enum - if it starts with lower case

### ISSUE THREAD

**Issue by divyenduz** [prisma/prisma#3128] opened 2018-09-18 12:57 UTC
**Describe the bug**
Prisma server 1.17-beta rejects enum starting with lower case sometimes. 

**To Reproduce**
Please follow:- 
https://github.com/divyenduz/prisma-3128

**Expected behavior**
All enums are valid. Lower case enums should be accepted. 

**Screenshots**
![screen shot 2018-09-18 at 2 56 09 pm](https://user-images.githubusercontent.com/746482/45688946-ffe96b80-bb52-11e8-8c32-aacd421d6090.png)

**Versions (please complete the following information):**
 - OS: `OS X High Sierra`
 - `prisma` CLI: `prisma/1.17.0-beta.12 (darwin-x64) node-v10.4.0`
 - Prisma Server: `prisma:1.17-beta`

**Additional context**
Happened while generating schemas for test cases of 
https://github.com/prisma/prisma/tree/beta/cli/packages/prisma-generate-schema

**Comment by marktani** [comment] 2018-09-18 15:45
The datamodel in your repository is invalid. Actually, it is a valid Prisma _schema_, but not a valid Prisma _datamodel_.

For example, it contains this input type:

```graphql
input BillingInfoWithoutConnectionCreateInput {
  account: String!
}
```

Nevertheless, I can confirm that this error message is returned for this datamodel:

```graphql
type A {
  id: ID! @unique
  string: String!
}

enum MyEnum {
  someValue
  Value
}
```

```
Deploying service `invalid-enum` to stage `dev` to server `local` 57ms

Errors:

  MyEnum
    ✖ The enum type `MyEnum` contains invalid enum values. The first character of each value must be an uppercase letter.
```

This seems to be the behaviour at least for the last 10 months, see https://github.com/prisma/prisma/blob/a08fa68d3181d05d7732b6e78dadf155306b26f2/server/servers/deploy/src/main/scala/com/prisma/deploy/migration/validation/DeployResults.scala#L189.

It seems to be the currently expected behaviour to enforce capital enum values. This should be added to the documentation [here](https://www.prisma.io/docs/data-model-and-migrations/data-model-knul/#naming-conventions).

Feel free to close this issue, or turn it into a feature request.

**Comment by marktani** [comment] 2018-09-20 09:32
I created this feature request: https://github.com/prisma/prisma/issues/3155

The docs should be updated to the current state.

**Comment by nikolasburk** [comment] 2018-09-26 10:14
This is already documented [here](https://www.prisma.io/docs/data-model-and-migrations/data-model-knul/#enum):

![image](https://user-images.githubusercontent.com/4058327/46073632-bff33b80-c185-11e8-8931-de29d427b6c7.png)

**Closed by nikolasburk** 2018-09-26 10:14 UTC
Labels: component/docs

**Comment by marktani** [comment] 2018-09-26 10:51
amazing didn't see that before. Thanks @nikolasburk 🙏

**Comment by Esya** [comment] 2019-06-03 17:35
Reopening this with the new MySQL introspection feature - We have some country code enum values which are iso codes (such as `fr` or `en`) therefore the model created by `prisma introspect` fails to `prisma deploy`, how should we handle this?

Thanks
