### ISSUE TITLE
Wrong type for $on method in PrismaClient

### ISSUE THREAD

**Issue by igor-mardari-ft** [prisma/prisma#6279] opened 2021-03-27 08:46 UTC
## Bug description

When using `prisma.$on('error'` I get error a compilation error 
![image](https://user-images.githubusercontent.com/68684530/112715112-3b650d80-8ee7-11eb-81db-280c940293b9.png)

## How to reproduce

1. Just do somewhere in the code `prisma.$on('error'`. Instead of `error` it could be any `LogLevel`.

## Expected behaviour

I shouldn't get a compilation error when using `'error'` because it's matching `LogLevel` type.

## Prisma information

I've investigated the issue a little bit and it comes from the `GetLogType` 
![image](https://user-images.githubusercontent.com/68684530/112715207-ce05ac80-8ee7-11eb-9690-e366953dc0d2.png)

If I change
```
T['emit'] extends string
```
instead of 
```
T['emit'] extends 'event'
```
then, the error is gone. 

No matter what configuration I set to `log` property. It could be `LogLevel` or `LogDefinition` or nothing. It behaves the same. In this case, it doesn't make any sense to have such a complex type if it doesn't work properly.

At a simple level, this line,:
```
$on<V extends (U | 'beforeExit')>
```
could be rewritten to 
```
$on<V extends (LogLevel | 'beforeExit')>
```

## Environment & setup

- OS: MacOs
- Database: PostgreSQL
- Node.js version: v12.18.3
- Prisma version: 2.19.0

**Comment by GarryOne** [comment] 2021-03-27 09:40
EDIT: I found this similar issue: https://github.com/prisma/prisma/issues/4746 now, if I add 
```<Prisma.PrismaClientOptions, 'error'>``` it works, but this info is nowhere in the documentation. Would be helpful to be included asa example because it's not an obvious thing.

Thanks.

**Comment by pabacham** [comment] 2021-03-27 10:40
The same issue happens with such construction in Nest.js
import { Injectable, OnModuleInit, OnModuleDestroy } from '@nestjs/common';
import { PrismaClient } from '@prisma/client';
import { logQueryDuration } from './middlewares/logQueryDuration';

@Injectable()
export class PrismaService
  extends PrismaClient
  implements OnModuleInit, OnModuleDestroy {
  constructor() {
    super({
      log: [
        {
          emit: 'event',
          level: 'query',
        },
        {
          emit: 'stdout',
          level: 'error',
        },
        {
          emit: 'stdout',
          level: 'info',
        },
        {
          emit: 'stdout',
          level: 'warn',
        },
      ],
    });

    this.$on('query', (e) => {
      console.log('Query: ' + e.query);
      console.log('Duration: ' + e.duration + 'ms');
    });
  }
  async onModuleInit() {
    await this.$connect();
    logQueryDuration(this);
  }

  async onModuleDestroy() {
    await this.$disconnect();
  }
}

**Comment by pabacham** [comment] 2021-03-27 10:43
> EDIT: I found this similar issue: #4746 now, if I add
> `<Prisma.PrismaClientOptions, 'error'>` it works, but this info is nowhere in the documentation. Would be helpful to be included as an example because it's not an obvious thing.
> 
> Thanks.

`extends PrismaClient<Prisma.PrismaClientOptions, 'query'>`
works for me. Thanks.

**Comment by DennieMello** [comment] 2021-04-13 21:30
The problem is indeed solved, but what if I want to add both "query" and "warn" at the same time?

![Снимок экрана 2021-04-14 в 00 30 22](https://user-images.githubusercontent.com/39631512/114623967-a1f47480-9cb8-11eb-8211-360c77e17cf0.jpg)

**Comment by pantharshit00** [comment] 2021-04-14 12:26
@DennieMello You should be able to do `extends PrismaClient<Prisma.PrismaClientOptions, 'query' | 'warn`>

I am going to close this one and open a docs issue about this: https://github.com/prisma/docs/issues/1564

**Closed by pantharshit00** 2021-04-14 12:26 UTC
Labels: bug/0-needs-info, kind/bug, team/client, topic: types

**Comment by nikelborm** [comment] 2024-05-08 23:52
May be related https://github.com/prisma/prisma/pull/24133
