### ISSUE TITLE
$transaction breaking when using $use

### ISSUE THREAD

**Issue by leerle** [prisma/prisma#13837] opened 2022-06-15 11:55 UTC
### Bug description

when using middleware, the transaction will failure;

```
import { PrismaClient } from '@prisma/client'
const prisma = new PrismaClient()

prisma.$use(async (params, next) => {
    return next(params)
})
```

### Environment & setup

- OS: 
- Database: 
- Node.js version: 

### Prisma Version

```

```

**Comment by garrensmith** [comment] 2022-06-15 11:57
@leerle thanks for the bug report. Would you mind sharing a schema file and the transaction code so that we can reproduce this.

**Comment by leerle** [comment] 2022-06-15 12:02
prisma schema:

```
generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "mysql"
  url      = env("DATABASE_URL")
}
```

transaction is usual:

```
const [posts, totalPosts] = await prisma.$transaction([
  prisma.post.findMany({ where: { title: { contains: 'prisma' } } }),
  prisma.post.count(),
])
```

**Comment by leerle** [comment] 2022-06-15 12:05
I temporarily avoided execution by making judgments in middleware

```
prisma.$use(async (params, next) => {
    if(!params.runInTransaction){
        ******
        return next(params)
    }})
```

**Comment by leerle** [comment] 2022-06-15 12:06
the prisma version is 3.8.0

**Comment by garrensmith** [comment] 2022-06-15 12:06
Can you upgrade to the latest version of Prisma and see if you still have this problem

**Comment by leerle** [comment] 2022-06-15 12:10
V3.15.1 Still bad

**Comment by garrensmith** [comment] 2022-06-15 12:18
Ok thanks. We will look into it.

**Comment by leerle** [comment] 2022-06-15 12:18
thank you

**Comment by janpio** [comment] 2022-06-16 09:40
Can you try adding an `await` before your `next` call and see if that changes anything?
```
prisma.$use(async (params, next) => {
    return await next(params)
})
```

**Comment by leerle** [comment] 2022-06-18 09:38
@janpio Nothing changed

**Comment by millsp** [comment] 2022-09-09 20:51
Hey @leerle, I am not able to reproduce this. Can you please provide us with more information (some code, the database, node version, the error, as well as some logs). Thank you!

**Comment by jharrell** [comment] 2023-08-07 18:01
Hi @leerle 

Unfortunately, without further info we'll have to close this issue. As always, please feel free to leave a comment and/or open a new issue with the information requested above. Thank you!

**Closed by jharrell** 2023-08-07 18:01 UTC
Labels: bug/0-unknown, kind/bug, topic: transaction, topic: middleware, team/client
