### ISSUE TITLE
`Decimal` to `Double` migration crashes: `result_row.rs:59:64] index out of bounds: the len is 1 but the index is 1`

### ISSUE THREAD

**Issue by benheckmann** [prisma/prisma#19464] opened 2023-05-26 08:19 UTC
Hi Prisma Team! The following command just crashed. I wanted to change columns with type `Decimal` to `Double` in my database, which contains ~100 M rows.

## Command

`db push`

## Versions
      
| Name        | Version            |
|-------------|--------------------|
| Platform    | darwin-arm64       | 
| Node        | v18.15.0           | 
| Prisma CLI  | 4.13.0             | 
| Engine      | 1e7af066ee9cb95cf3a403c78d9aab3e6b04f37a| 

## Error
```
Error: Error in migration engine.
Reason: [/Users/runner/.cargo/git/checkouts/quaint-9f01e008b9a89c14/5a70831/src/connector/result_set/result_row.rs:59:64] index out of bounds: the len is 1 but the index is 1

Please create an issue with your `schema.prisma` at
https://github.com/prisma/prisma/issues/new

```

**Comment by aqrln** [comment] 2023-08-24 17:32
@benheckmann I couldn't reproduce this so far, could you please provide more information:
* which database are you using?
* is this only reproducible with a big number of rows?
* were there any warnings or any other output before crashing?
* which other fields you have in the model in question?

Potentially related: https://github.com/prisma/prisma/issues/18237

**Comment by janpio** [comment] 2023-10-29 21:10
Did you see Alexey's message @benheckmann? We need some more information to reproduce.

**Comment by SevInf** [comment] 2024-02-02 10:32
Hey @benheckmann ,
 

With the lack of information and our inability to reproduce this issue, we're now closing it. Feel free to comment if you have any updates about it.
 
Thank you 🙏

**Closed by SevInf** 2024-02-02 10:32 UTC
Labels: bug/1-unconfirmed, kind/bug, topic: migrate, team/schema, topic: prisma db push, topic: Decimal
