### ISSUE TITLE
Feature Request: Autogenerate ER diagram based off of Prisma schema

### ISSUE THREAD

**Issue by efreila** [prisma/prisma#7362] opened 2021-05-30 20:14 UTC
## Problem

A lot of the times, developers want to visually see their database schemas through Entity-Relationship (ER) diagrams. This allows them to more easily see the relationships between different tables in their designs. 

If we want to achieve this today, we have to recreate our whole database design through some third-party tool (e.g. draw.io, dbdiagram.io) in order to have a visual representation of our database.

## Suggested solution

In order to use Prisma, we already create a Prisma schema file that contains all of our models, enums, etc. Prisma can create a mechanism to autogenerate a visual ER diagram by introspecting the existing Prisma schema file. 

This can be a CLI command that will work very similarly to `npx prisma studio`. When this command is run (e.g. `npx prisma diagram`), Prisma would create a visual representation of the existing schema file so that developers can quickly and easily have instant access to an ER diagram of their current design. 

Similar to how Prisma Studio has a GUI that allows users to make changes to the data in their databases, this diagramming tool can be extended to allow users to make changes to their Prisma schema through the tool. The left-hand side could be a text editor that loads up the user's schema file, while the right-hand side would be their diagram. When a user makes changes to the schema file, the ER diagram would "recompile" and the changes would be saved to their local Prisma schema file.

## Alternatives

An alternative solution is to provide this diagramming tool somewhere on Prisma's website. It would be implemented very similarly to the GraphQL Nexus SDL converter. 

Users will be able to access this tool through Prisma's website and simply upload their Prisma schema files. The visual diagram would then be created. Users can be given the ability to download this diagram or share it as a link so that it's accessible by others.

## Additional context

N/A

**Comment by pantharshit00** [comment] 2021-05-31 13:29
Checkout this community generator: https://github.com/notiz-dev/prisma-dbml-generator

It generates DBML from the schema which you can use to make an ER diagram easily.


On a bigger note, I will close this as duplicate of https://github.com/prisma/studio/issues/198

**Closed by pantharshit00** 2021-05-31 13:29 UTC

**Comment by joshtin2505** [comment] 2024-11-07 15:26
**here you can paste your prisma.schema like in dbdiagram**: https://prisma-editor.vercel.app/
**too**: https://prismaliser.app/
**vs code extencion**: https://marketplace.visualstudio.com/items?itemName=bocovo.prisma-erd-visualizer
**interctive creator**: https://www.prismabuilder.io/
