### ISSUE TITLE
GeneratorError: Error: ENOENT: no such file or directory,

### ISSUE THREAD

**Issue by nikolasburk** [prisma/prisma#1724] opened 2020-02-28 08:56 UTC
I just ran into an error after performing the following steps locally:

1. `yarn add prisma2`
1. `yarn prisma2 init`
1. Set env `DATABASE_URL` to my local Postgres DB: `DATABASE_URL="postgresql://nikolasburk:nikolasburk@localhost:5432/comp?schema=public"`
1. Add this model to my Prisma schema:
    ```prisma
    model User {
      firstName String
      lastName String

      @@id([firstName, lastName])
    }
    ```
1. Migrate:
    ```
    yarn prisma2 migrate save --name 'init' --experimental
    yarn prisma2 migrate up --experimental
    ```
1. Generate:
    ```
    yarn prisma2 generate
    ```

Now I'm getting this error (and the CLI command doesn't terminate and still hangs in my terminal):

~~~
$ yarn prisma2 generate
yarn run v1.22.0
warning package.json: No license field
$ /Users/nikolasburk/Desktop/composite-ids/node_modules/.bin/prisma2 generate
warning package.json: No license field
warning No license field
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 🔨  Building fresh packages...
success Saved lockfile.
warning No license field
success Saved 1 new dependency.
info Direct dependencies
└─ prisma2@2.0.0-preview022
info All dependencies
└─ prisma2@2.0.0-preview022
warning package.json: No license field
warning No license field
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 🔨  Building fresh packages...
success Saved lockfile.
warning No license field
success Saved 1 new dependency.
info Direct dependencies
└─ @prisma/client@2.0.0-preview022
info All dependencies
└─ @prisma/client@2.0.0-preview022

✔ Installed the @prisma/client and prisma2 packages in your project
GeneratorError: Error: ENOENT: no such file or directory, copyfile '/Users/nikolasburk/Desktop/composite-ids/node_modules/prisma2/query-engine-darwin' -> '/Users/nikolasburk/Desktop/composite-ids/node_modules/@prisma/client/runtime/query-engine-darwin'
    at GeneratorProcess.handleResponse (/Users/nikolasburk/Desktop/composite-ids/node_modules/prisma2/build/index.js:2:177310)
    at LineStream.<anonymous> (/Users/nikolasburk/Desktop/composite-ids/node_modules/prisma2/build/index.js:2:176926)
    at LineStream.emit (events.js:196:13)
    at LineStream.EventEmitter.emit (domain.js:471:20)
    at addChunk (_stream_readable.js:290:12)
    at readableAddChunk (_stream_readable.js:271:11)
    at LineStream.Readable.push (_stream_readable.js:226:10)
    at LineStream.Transform.push (_stream_transform.js:150:32)
    at LineStream._pushBuffer (/Users/nikolasburk/Desktop/composite-ids/node_modules/prisma2/build/index.js:2:840724)
    at LineStream._transform (/Users/nikolasburk/Desktop/composite-ids/node_modules/prisma2/build/index.js:2:840543) {
  code: -32000,
  data: null
}

You can now start using Prisma Client in your code:

```
import { PrismaClient } from '@prisma/client'
// or const { PrismaClient } = require('@prisma/client')

const prisma = new PrismaClient()
```      

Explore the full API: http://pris.ly/d/client
~~~

**Comment by pantharshit00** [comment] 2020-02-28 09:49
I am unable to reproduce this with `prisma2@2.0.0-alpha.841, binary version: 6cf3607cbc7213fac25b732e5323089fdd824611` and `prisma2@2.0.0-preview022, binary version: f608db3b9e4f50f9a384356e532357b0a525969a`

From the error message, it looks like binaries are missing. We improved our binary ensuring logic in alpha so try again with that.

**Comment by matthewmueller** [comment] 2020-08-24 09:34
Closing since this is old. If it's still an issue, it'll come up again.

**Closed by matthewmueller** 2020-08-24 09:34 UTC
Labels: bug/0-needs-info, kind/bug, status/needs-action, topic: cli-generate
