### ISSUE TITLE
MySQL `time` type not working

### ISSUE THREAD

**Issue by steebchen** [prisma/prisma#1657] opened 2020-02-19 16:42 UTC
SQL

```sql
CREATE TABLE `User` (
	id integer PRIMARY KEY,
	time time,
);
```

Prisma Schema

```prisma
model User {
  id        Int       @id
  time      DateTime?
}
```

Code
```ts
const date = new Date('2015-01-01T00:00:00Z')

const data: UserCreateInput = {
	id: 1,
	date: date,
	datetime: date,
	time: date,
	timestamp: date,
}

await client.user.create({
	data,
})
```

reproduction available at https://github.com/prisma/datetime-experiments

```
ConnectorError(ConnectorError { user_facing_error: None, kind: ConversionError(Custom { kind: InvalidData, error: "DateTime value not stored as datetime, int or text" }

   0: backtrace::backtrace::trace
   1: backtrace::capture::Backtrace::new_unresolved
   2: failure::backtrace::internal::InternalBacktrace::new
   3: <failure::backtrace::Backtrace as core::default::Default>::default
   4: sql_query_connector::row::row_value_to_prisma_value
   5: <quaint::connector::result_set::result_row::ResultRow as sql_query_connector::row::ToSqlRow>::to_sql_row
   6: <std::future::GenFuture<T> as core::future::future::Future>::poll
   7: <std::future::GenFuture<T> as core::future::future::Future>::poll
   8: std::future::poll_with_tls_context
   9: <std::future::GenFuture<T> as core::future::future::Future>::poll
  10: <std::future::GenFuture<T> as core::future::future::Future>::poll
  11: <std::future::GenFuture<T> as core::future::future::Future>::poll
  12: <std::future::GenFuture<T> as core::future::future::Future>::poll
  13: <std::future::GenFuture<T> as core::future::future::Future>::poll
  14: <std::future::GenFuture<T> as core::future::future::Future>::poll
  15: <std::future::GenFuture<T> as core::future::future::Future>::poll
  16: <std::future::GenFuture<T> as core::future::future::Future>::poll
  17: std::future::poll_with_tls_context
  18: <std::future::GenFuture<T> as core::future::future::Future>::poll
  19: <std::future::GenFuture<T> as core::future::future::Future>::poll
  20: std::panicking::try::do_call
  21: __rust_maybe_catch_panic
  22: <std::future::GenFuture<T> as core::future::future::Future>::poll
  23: tokio::task::core::Core<T>::poll
  24: std::panicking::try::do_call
  25: __rust_maybe_catch_panic
  26: tokio::task::harness::Harness<T,S>::poll
  27: tokio::runtime::thread_pool::worker::GenerationGuard::run_task
  28: tokio::runtime::thread_pool::worker::GenerationGuard::run
  29: std::thread::local::LocalKey<T>::with
  30: tokio::runtime::thread_pool::worker::Worker::run
  31: tokio::task::core::Core<T>::poll
  32: std::panicking::try::do_call
  33: __rust_maybe_catch_panic
  34: tokio::task::harness::Harness<T,S>::poll
  35: tokio::runtime::context::enter
  36: std::sys_common::backtrace::__rust_begin_short_backtrace
  37: std::panicking::try::do_call
  38: __rust_maybe_catch_panic
  39: core::ops::function::FnOnce::call_once{{vtable.shim}}
  40: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
  41: std::sys::unix::thread::Thread::new::thread_start
  42: _pthread_start
) })
```

**Comment by ghyath5** [comment] 2020-05-20 21:48
I have same issue.
Any updates ?

**Comment by tomhoule** [comment] 2020-05-20 22:05
Is it exactly the same error @ghyath5 ? We did some work on this, and `time` won't work in all cases because MySQL is ambiguous about what this type represents, it can be a duration or a time of the day. Prisma is currently opinionated and treats it as a time of the day, so negative values or values greater than 24 hours won't work.

**Comment by ghyath5** [comment] 2020-05-20 22:14
@tomhoule 
I'm using Postgres database
I'm trying to select some fields from prisma like:

   `
  const select = new PrismaSelect(info).value`
    `let data = await ctx.prisma.users.findMany({
      ...args,
      ...select
    })`
  `  return data`
Then this error show me: `DateTime value not stored as datetime, int or text`
Knowing that when I was using `includes` instead of `select` there were no errors

**Comment by tomhoule** [comment] 2020-05-20 22:30
Hmm this is a different bug then, we should look into it. Can you open an issue? :pray:

**Comment by ghyath5** [comment] 2020-05-20 22:33
Well, I will

**Comment by pantharshit00** [comment] 2021-04-13 09:35
Unable to reproduce this crash with 2.21.0-dev.37 but problem reported in https://github.com/prisma/prisma/issues/2734 is reproducible so closing in favour of that.

**Closed by pantharshit00** 2021-04-13 09:35 UTC
Labels: bug/2-confirmed, kind/bug, team/client, topic: dates, topic: types
