### ISSUE TITLE
Regression in prisma migrate

### ISSUE THREAD

**Issue by internalfx** [prisma/prisma#6366] opened 2021-04-01 15:50 UTC
I've noticed a regression in Prisma migrate. It worked fine in version 2.16, but later versions seem to have this issue.

Ran with version `2.19.0`
```
: prisma migrate dev
Running node v14.16.0 (npm v6.14.11)
Prisma schema loaded from prisma/schema.prisma
Datasource "db": SQLite database "reviews.sqlite" at "file:../reviews.sqlite"

⚠️  Warnings:

  • You are about to drop the column `vendor` on the `products` table, which still contains 16 non-null values.

✔ Are you sure you want create and apply this migration? Some data will be lost. … yes
✔ Name of migration … remove vendor
Error: Database error: Timed out during query execution.
   0: migration_core::commands::apply_migrations::Applying migration
           with migration_name="20210401145435_remove_vendor"
             at migration-engine/core/src/commands/apply_migrations.rs:72
   1: migration_core::api::ApplyMigrations
             at migration-engine/core/src/api.rs:75

```

After rolling back to version `2.16.0`. I can re-run the same migration without error.

```
: npx prisma migrate dev --preview-feature
Running node v14.16.0 (npm v6.14.11)
Prisma schema loaded from prisma/schema.prisma
Datasource "db": SQLite database "reviews.sqlite" at "file:../reviews.sqlite"

The following migration(s) have been applied:

migrations/
  └─ 20210401145435_remove_vendor/
    └─ migration.sql


Everything is now in sync.
```

## Bug description

Prisma migrate fails with a timeout error

## How to reproduce

Modify an existing table with prisma migrate.

## Environment & setup

- OS: Ubuntu
- Database: SQLite
- Node.js version: 14
- Prisma version: 2.16, 2.19

**Comment by internalfx** [comment] 2021-04-01 15:59
Tried it again with prisma `2.20.1`

I tried adding the column back. Basically, prisma migrate is completely broken for versions > `2.16`

```
: prisma migrate dev
Running node v14.16.0 (npm v6.14.11)
Prisma schema loaded from prisma/schema.prisma
Datasource "db": SQLite database "reviews.sqlite" at "file:../reviews.sqlite"

✔ Name of migration … add vendor
Error: Database error
Timed out during query execution.
   0: migration_core::commands::apply_migrations::Applying migration
           with migration_name="20210401155700_add_vendor"
             at migration-engine/core/src/commands/apply_migrations.rs:71
   1: migration_core::api::ApplyMigrations
             at migration-engine/core/src/api.rs:73
```

**Comment by janpio** [comment] 2021-04-01 20:52
Can you share the migration file that is trying to be applied here?
Can you possible recreate the migration using the newest version?

**Comment by internalfx** [comment] 2021-04-21 18:11
@janpio I started building a test repo to make finding the bug much easier for your team.

In the process of narrowing it down to the smallest test case, I ran across another issue. I was able to get it to work with an empty database. However, my "test" database with data was where a new break occurs.

```
nvm exec npx prisma migrate dev
Found '/home/bmorris/internalfx/projects/prisma-migrate-test/.nvmrc' with version <14>
Running node v14.16.1 (npm v7.9.0)
Prisma schema loaded from prisma/schema.prisma
Datasource "db": SQLite database "dev.sqlite" at "file:../dev.sqlite"

✔ Drift detected: Your database schema is not in sync with your migration history.

We need to reset the SQLite database "dev.sqlite" at "file:../dev.sqlite".
Do you want to continue? All data will be lost. … yes

Error: Database error
Error querying the database: database disk image is malformed
   0: migration_core::api::ApplyMigrations
             at migration-engine/core/src/api.rs:73
```

As you can see prisma thinks the database is malformed, and after running this command it is! I can confirm that the database works fine before this command but is corrupted after.

I can also run `db push` successfully.

```
nvm exec npx prisma db push --preview-feature
Found '/home/bmorris/internalfx/projects/prisma-migrate-test/.nvmrc' with version <14>
Running node v14.16.1 (npm v7.9.0)
Prisma schema loaded from prisma/schema.prisma
Datasource "db": SQLite database "dev.sqlite" at "file:../dev.sqlite"

The database is already in sync with the Prisma schema.

✔ Generated Prisma Client (2.21.2) to ./node_modules/@prisma/client in 260ms
```

A test database that breaks and a prisma schema are available for you here: https://github.com/internalfx/prisma-migrate-test

**Comment by pantharshit00** [comment] 2021-05-28 14:04
Thanks for the reproduction repo @internalfx . I can confirm this.

**Comment by tomhoule** [comment] 2021-06-09 14:18
Hi @internalfx ! Thanks for the report. I played a bit with the reproduction repository (thanks for that), and I do get the same errors with the databases committed in the repo, but I can't reproduce it with a fresh sqlite (deleting the existing one, and starting a new one). I'll continue investigating.

**Comment by internalfx** [comment] 2021-06-09 14:48
@tomhoule Thanks Tom! If I can be of help let me know.

**Closed** 2022-09-02 08:39 UTC
Labels: bug/2-confirmed, kind/bug, topic: sqlite, tech/engines, status/needs-action, team/schema, topic: prisma migrate dev
