### ISSUE TITLE
Connections from repl.it repls randomly failing with various errors

### ISSUE THREAD

**Issue by khrj** [prisma/prisma#5333] opened 2021-01-28 16:09 UTC
## Bug description

Prisma connections from a lot of my [repl.it](https://repl.it/) repls randomly fail with various errors due to unknown reasons.

Here are the errors I've seen (Descending order of frequency):
```
[ERROR] : 
Invalid `prisma.workspace.findUnique()` invocation:
  Can't reach database server at `ec2-50-19-32-202.compute-1.amazonaws.com`:`5432`
Please make sure your database server is running at `ec2-50-19-32-202.compute-1.amazonaws.com`:`5432`.
```
```
Invalid `prisma.workspace.findUnique()` invocation:
  Error creating a database connection. (Operation timed out (mobc timeout))
    at new AuthorizationError (/home/runner/InfoBot-old-2/node_modules/@slack/oauth/dist/errors.js:71:28)
    at InstallProvider.<anonymous> (/home/runner/InfoBot-old-2/node_modules/@slack/oauth/dist/index.js:158:31)
    at step (/home/runner/InfoBot-old-2/node_modules/@slack/oauth/dist/index.js:44:23)
    at Object.throw (/home/runner/InfoBot-old-2/node_modules/@slack/oauth/dist/index.js:25:53)
    at rejected (/home/runner/InfoBot-old-2/node_modules/@slack/oauth/dist/index.js:17:65)
```
```
Invalid `prisma.channel.upsert()` invocation:
  Timed out fetching a new connection from the pool. Please consider reducing the number of requests or increasing the `connection_limit` parameter (https://www.prisma.io/docs/concepts/components/prisma-client/connection-management#connection-pool). Current limit: 5, amount of connections currently in use: 0.
    at Object.asCodedError (/home/runner/HackClubKarma/node_modules/@slack/bolt/dist/errors.js:23:12)
    at App.handleError (/home/runner/HackClubKarma/node_modules/@slack/bolt/dist/App.js:442:43)
    at App.processEvent (/home/runner/HackClubKarma/node_modules/@slack/bolt/dist/App.js:435:25)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

## Note

I've already spoken to folks at repl.it and @nikolasburk -- here's some context:

![Screenshot of message from @nikolasburk with text: "All right, thanks for sharing! I've just checked back with our engineers and I think the best way to tackle this is to create an issue so that someone from the engineering team can look into this properly. It seems like nobody really has experience with repl.it yet but we definitely want to make sure that it's properly supported! Ideally we even get to a point where we can say Prisma reliably works on repl.it and can add it to our e2e tests. Does that sound ok to you?" ](https://user-images.githubusercontent.com/44947946/106165388-18510280-61b1-11eb-9b6e-9b871c409ce0.png)

## How to reproduce

Not always reproducible. Occurs randomly and can only fixed by creating a fresh copy of (forking) the repl

### Affected repls:
- https://repl.it/@KhushrajRathod/InfoBot-old-3
- https://repl.it/@KhushrajRathod/InfoBot-old-2
- https://repl.it/@KhushrajRathod/InfoBot-old
- https://repl.it/@KhushrajRathod/LightningDelete-old
- https://repl.it/@KhushrajRathod/The-Overseer-Frontend

## Expected behavior

- Prisma can connect to the database (since it works locally and via `psql`)

## Prisma information

```prisma
datasource db {
    url      = env("DATABASE_URL")
    provider = "postgresql"
}

generator client {
    provider = "prisma-client-js"
}

model Workspace {
    id           String @id
    installation String
}
```

## Environment & setup

- OS: Linux
- Database: PostgreSQL
- Node.js version: v12.16.1
- Prisma version: 2.14.0

**Comment by KhushrajRathod** [comment] 2021-01-28 16:41
The error occured in another repl right now so I decided to experiment and I’ve found additional info:
- Starting and stopping the node.js process doesn’t get rid of the error. However, restarting the repl completely (kill 1) does solve the error. This makes me think that there are somehow multiple processes running at once? Or there are stalled connections to the database somehow. I know for a fact that heroku limits maximum connections to 20, so this could be related

**Comment by janpio** [comment] 2021-01-28 20:28
Error 2 and 3 should be mutually exclusive, as we replaced #2 with #3 in version 2.15.0 - so you possibly ran one deployment with a newer version of Prisma.

Are there any steps we can run to reproduce the behavior you are seeing? What are you doing when this happens to you?

**Comment by KhushrajRathod** [comment] 2021-01-29 03:39
> Are there any steps we can run to reproduce the behavior you are seeing?

I believe no 😕 , unless you host something frequently using prisma on repl.it yourself

> What are you doing when this happens to you?

I'm just calling a slack slash command that calls prisma.workspace.findUnique to fetch the installation tokens. It usually works, but sometimes the slash command fails, so I look at the repl logs and see that prisma failed to connect to the server.

> Is your code doing anything in parallel (many queries at the same time)?
Not that I'm aware of, unless multiple people call a slash command at the exact same time (not likely to happen often)

**Comment by pantharshit00** [comment] 2021-01-29 07:23
For the first error, I would suspect AWS firewall might be blocking repl it connections. Since repl's must change after some time, EC2 refuses the connection. Can you make sure that connection from everywhere is allowed to your instance by setting the inbound CIDR to `0.0.0.0/0`. 


Now regarding the other two error, we had some error reports recently where database connection was not acquired before the timeout hence the error. 

Can you please follow this comment of mine and see if this is fixed for you? https://github.com/prisma/prisma/issues/4280#issuecomment-769178520

Let me know if these still occur even after this. Then I can try setting up the infra myself and try investigating this further.

**Comment by sorenbs** [comment] 2021-02-09 10:33
@KhushrajRathod - are you still experiencing this issue after following the steps suggested here?

**Comment by KhushrajRathod** [comment] 2021-02-09 11:25
Hi, sorry for the lack of updates

---

> For the first error, I would suspect AWS firewall might be blocking repl it connections. Since repl's must change after some time, EC2 refuses the connection. Can you make sure that connection from everywhere is allowed to your instance by setting the inbound CIDR to 0.0.0.0/0.

I'm using **Heroku PostgreSQL** and I haven't set up allowlists / blocklists so believe that's already the case

> Now regarding the other two errors, we had some error reports recently where database connection was not acquired before the timeout hence the error.

I haven't encountered the mobc timeout error after 2.16, so that seems to be fixed

However I still occasionally (like before) get the timeout error

```
[ERROR] : 
Invalid `prisma.workspace.findUnique()` invocation:
  Can't reach database server at `ec2-50-19-32-202.compute-1.amazonaws.com`:`5432`
Please make sure your database server is running at `ec2-50-19-32-202.compute-1.amazonaws.com`:`5432`.
```

**Comment by sorenbs** [comment] 2021-02-09 15:42
Thank you @KhushrajRathod!

If you have the time, it would be very helpful if you could try to explicitly call the `disconnect` in your code. This way we can ensure there are no dangling connections and see if the problem persists. A pattern for doing that is detailed here: https://www.prisma.io/docs/concepts/components/prisma-client/connection-management#calling-disconnect-explicitly

As Niko mentioned, we will be scheduling engineering time to make sure repl.it is a first class supported platform, but it might be a while before we get to it.

**Comment by KhushrajRathod** [comment] 2021-02-10 03:42
> If you have the time, it would be very helpful if you could try to explicitly call the disconnect in your code. This way we can ensure there are no dangling connections and see if the problem persists. A pattern for doing that is detailed here: https://www.prisma.io/docs/concepts/components/prisma-client/connection-management#calling-disconnect-explicitly

Hi, I'll surely try that but I'm not sure how long it will take to know if the problem is solved, since the issue randomly reproduces

**Comment by KhushrajRathod** [comment] 2021-02-14 18:30
@sorenbs It happened again, even with calling disconnect explicitly -- my code is at https://github.com/KhushrajRathod/LightningDelete

**Comment by sorenbs** [comment] 2021-02-14 18:55
Thank yo @KhushrajRathod!

That really should work. We will look into this and figure out what is going on.

My understanding is that repl.it runs a full container on Kubernetes-like infrastructure. On the "Starter" plan they will be suspended after a while. That might have an impact. Can you confirm that you are on the "Starter" plan?

**Comment by KhushrajRathod** [comment] 2021-02-15 03:16
> Can you confirm that you are on the "Starter" plan?

That's not correct -- I'm on the hacker plan and my repl is set to 'Always-on' (from what I understand, it's not actually always on, but the container is immediately restarted after it's destroyed -- repl.it containers are periodically destroyed)

@sorenbs

**Comment by pantharshit00** [comment] 2021-05-05 11:59
Hey @KhushrajRathod 

If you still have this project around, can you try again with latest version of Prisma once? I remember we fixed a lot of bugs in this area.

**Comment by garrensmith** [comment] 2022-04-01 07:42
Hey @KhushrajRathod, I think this could be fixed. Would you be able to try with out with `prisma@dev`

**Comment by jkomyno** [comment] 2023-07-13 14:17
Hey @khrj, according to [this comment](https://github.com/prisma/prisma/issues/5333#issuecomment-1085541053), this issue is already fixed. Can you please try again, with a recent version of Prisma (`4.16.2` or `5.0.0`)? Thanks!

**Comment by khrj** [comment] 2023-07-13 17:46
Hey!

I don't happen to use repl.it anymore, and since this issue isn't reproducible without actually running services on repl.it for an extended period of time I'm not sure how to test it out. Feel free to close the issue!

**Comment by petradonka** [comment] 2023-07-23 14:51
Thanks for getting back to us @khrj! 🙏 

We'll close this issue now, but happy to reopen if new information surfaces.

**Closed by petradonka** 2023-07-23 14:51 UTC
Labels: bug/0-unknown, kind/bug, topic: deployment-platform, status/needs-action, team/client, topic: connection pool

**Comment by Sheikhfarid1** [comment] 2025-04-27 04:30
nice
