### ISSUE TITLE
Serializable Isolation Level on $transaction not being respected when queries.length === 1

### ISSUE THREAD

**Issue by huumn** [prisma/prisma#20408] opened 2023-07-26 23:53 UTC
### Bug description

When I set `isolationLevel: Prisma.TransactionIsolationLevel.Serializable` in `$transaction` passed a single `[query]` the isolation level as seen by the `plpgsql` function run in the transaction is `read committed` ***not*** `serializable`. 

### How to reproduce

1. Create the following migration:
```plpgsql
create or replace function ASSERT_SERIALIZED() returns void as $$
BEGIN
    IF (select current_setting('transaction_isolation') <> 'serializable') THEN
        RAISE EXCEPTION 'NOT_SERIALIZABLE: %', current_setting('transaction_isolation');
    END IF;
END;
$$ language plpgsql;
```
2. Call it
```js
const [result] = await prisma.$transaction([prisma.$executeRaw`SELECT ASSERT_SERIALIZED()`], { isolationLevel: Prisma.TransactionIsolationLevel.Serializable })
```
3. It raises the exception: `NOT_SERIALIZABLE: read committed`

### Expected behavior

For the transaction isolation to be enforced regardless of the number of queries passed. When I pass more than one query it works as expected:

```js
const [result] = await prisma.$transaction([prisma.$executeRaw`SELECT ASSERT_SERIALIZED()`, query], { isolationLevel: Prisma.TransactionIsolationLevel.Serializable })
```

### Prisma information

n/a

### Environment & setup

- OS:  macOS ventura
- Database: postgres 13.2
- Node.js version: 16.16

### Prisma Version

```
prisma                  : 4.16.2
@prisma/client          : 4.16.2
Current platform        : darwin-arm64
Query Engine (Node-API) : libquery-engine 4bc8b6e1b66cb932731fb1bdbbc550d1e010de81 (at node_modules/@prisma/engines/libquery_engine-darwin-arm64.dylib.node)
Migration Engine        : migration-engine-cli 4bc8b6e1b66cb932731fb1bdbbc550d1e010de81 (at node_modules/@prisma/engines/migration-engine-darwin-arm64)
Format Wasm             : @prisma/prisma-fmt-wasm 4.16.1-1.4bc8b6e1b66cb932731fb1bdbbc550d1e010de81
Default Engines Hash    : 4bc8b6e1b66cb932731fb1bdbbc550d1e010de81
Studio                  : 0.484.0
```

**Comment by SevInf** [comment] 2023-08-03 12:42
Hey @huumn.
Thanks for the reproduction. We already have an issue open about that specific problem, so I am going to close this one as a duplicate of #17555.

**Closed by SevInf** 2023-08-03 12:42 UTC
Labels: bug/1-unconfirmed, kind/bug, team/client, topic: $transaction([...])
