### ISSUE TITLE
Reduce the number of generated SQL statements for Updates/Inserts

### ISSUE THREAD

**Issue by benawad** [prisma/prisma#5043] opened 2020-04-14 22:19 UTC
I'm not sure if there is a good reason for how it currently works, but it looks like you could reduce the number of SQL statements generated for `update`.

## Problem
The following code:
```ts
  const updatedPost = await prisma.post.update({
    where: {
      id: 1,
    },
    data: {
      published: true,
    },
  });
```
Generates this SQL:
```sql
prisma:query BEGIN
prisma:query SELECT `dev`.`Post`.`id` FROM `dev`.`Post` WHERE `dev`.`Post`.`id` = ?
prisma:query UPDATE `dev`.`Post` SET `published` = ? WHERE `dev`.`Post`.`id` IN (?)
prisma:query SELECT `dev`.`Post`.`id`, `dev`.`Post`.`title`, `dev`.`Post`.`content`, `dev`.`Post`.`published`, `dev`.`Post`.`authorId` FROM `dev`.`Post` WHERE `dev`.`Post`.`id` = ? LIMIT ? OFFSET ?
prisma:query COMMIT
```

## Solution
In PostgreSQL, I would normally write this as:
```sql
update `dev`.`Post` set published = ? where id = ? returning *
```

## Additional context
You could use `returning` on inserts too.

**Comment by pimeys** [comment] 2021-01-14 13:52
Actually, PostgreSQL and SQL Server support `RETURNING` or `OUTPUT` in inserts, updates and deletes.

Also, this would help reducing errors coming from an overly saturated pool in https://github.com/prisma/prisma/issues/4280

**Comment by Sytten** [comment] 2021-01-14 21:33
Lets note that the returning doesn't do anything if the update doesn't update a row. So it's debatable is the first select should be left in place or not. It also won't work if other tables are requested in the select/include.

**Comment by benawad** [comment] 2021-01-16 18:24
maybe have it as an option to where you can set returning to true

**Comment by pimeys** [comment] 2021-03-01 18:01
If we'd be able to cut a simple insert into one query utilizing returning or output, we could then skip the transaction from that query. This would mean that instead of four queries:

- `BEGIN` to start a transaction
- `INSERT INTO` to insert your data
- `SELECT FROM` to query the data and
- `COMMIT` to end the transaction

we would just do `INSERT INTO ... RETURNING`. If you have any roundtrip between the application server and the database, this would cut the response times tremendously, reducing the need for more connections in certain scenarios.

**Comment by jan4984** [comment] 2021-05-31 03:00
any update? I think performance is important for database middlewares like Prisma.

**Comment by alienself** [comment] 2022-03-28 01:19
Any updates on this issue? This looks like a major problem that should be fixed asap.

**Comment by janpio** [comment] 2022-03-29 10:53
> When I say "slow", above, these queries took multiple seconds to run when they worked almost instantly when running entirely on my mac.
> 
> My understanding of the problem is that joins will often waterfall, so the deeper the joins, the more round trips the data has to take to complete all the queries. This is basically broken from what I can tell, unless the latency is extremely low between app and database servers. Even having the app and database server in the same region was not enough. I do not exactly understand the networking aspect, but my rough understanding/assumption is that if the servers are not configured to do otherwise (e.g. by using the same VPC), they will round trip to the internet for each trip. This will very quickly get too slow to be usable.

This sounds like a _concrete_ problem we would love to have an issue about with a reproduction project we can try out ourselves. As you are on PlanetScale, there could be some cross effect of the `referentialIntegrity = prisma` mode for example - so we really want to be able to look into what is going on. Please open that standalone issue and provide the information we need to  be able to reproduce and understand. Thanks.

**Comment by chrbala** [comment] 2022-03-30 09:28
> Please open that standalone issue and provide the information we need to be able to reproduce and understand. Thanks.

Done! See: #12582

**Comment by AradAlvand** [comment] 2022-05-03 01:25
No updates on this one yet? :(

**Comment by rohanrajpal** [comment] 2022-08-12 10:56
Would love to have this. Whats the best way to do an update without selects right now?

**Comment by ChristianIvicevic** [comment] 2022-08-15 00:25
@rohanrajpal If I am not mistaken `updateMany` does update without returning, even though it's debatable whether it's a good solution spreading this in your codebase since the semantics of that function are different and might cause other readers of your code to question why you are not using `update` in the first place.

**Comment by rohanrajpal** [comment] 2022-08-15 16:23
> @rohanrajpal If I am not mistaken `updateMany` does update without returning, even though it's debatable whether it's a good solution spreading this in your codebase since the semantics of that function are different and might cause other readers of your code to question why you are not using `update` in the first place.

Yeah right, didn't know `updateMany` does update without returning, tho yes wouldn't prefer to give up readability for it.

**Comment by oscarcoding** [comment] 2022-08-30 09:26
Please be aware that this does not work in MS SQL Server if your table has triggers.  

See https://stackoverflow.com/questions/13198476/cannot-use-update-with-output-clause-when-a-trigger-is-on-the-table for details.

So if this is added, there must also be an option to turn it off via some configuration setting. 

I ran into this problem on a previous project using Knex/Bookshelf.js as the ORM and this option was not configurable, so we had to fork the whole project and make the change ourselves.

**Comment by adrianbienias** [comment] 2023-06-13 20:19
I found that [upsert](https://www.prisma.io/docs/reference/api-reference/prisma-client-reference#upsert) uses only one query instead of three when making an update, and also it uses `RETURNING`.

**Closed** 2023-07-28 11:23 UTC
Labels: kind/improvement, topic: performance, team/client, topic: performance/queries

**Comment by Weakky** [comment] 2023-08-01 14:52
Hey folks, this should be now available for Postgres & CockroachDB on the lastest Prisma 5.1. Have a look at the release notes for more information! Cheers
