### ISSUE TITLE
Prisma generate --watch errors `Error: write EPIPE`

### ISSUE THREAD

**Issue by malekjaroslav** [prisma/prisma#1816] opened 2020-03-11 07:27 UTC
When running `prisma generate --watch`, this error sometimes kills it:

```
node_modules/prisma2/build/index.js:2
module.exports=function(e,t){"use strict";var r={};function __webpack_require__(t){if(r[t]){return r[t].exports}var n=r[t]={i:t,l:false,exports:{}};e[t].call(n.exports,n,n.exports,__webpack_require__);n.l=true;return n.exports}__webpack_require__.ab=__dirname+"/";function startup(){return __webpack_require__(4653)}t(__webpack_require__);return startup()}({2:function(e,t,r){"use strict";var n=r(5622);var i=r(3382);var o=r(7707);var s=r(2080);e.exports=function(e,t){if(typeof e!=="string"){t=e;e=null}var r=o({cwd:process.cwd()},t);e=e||r.type;var u=n.resolve(r.cwd,".git/config");if(e==="global"){u=n.join(s(),".gitconfig")}if(!i(u)){if(typeof e==="string"){return null}u=n.join(s(),".config/git/config")}return i(u)?u:null}},9:function(e,t){"use strict";const r=t.encode=((e,t)=>{if(!Number.isSafeInteger(e))throw Error("cannot encode number outside of javascript safe integer range");else if(e<0)i(e,t);else n(e,t);return t});c

Error: write EPIPE
    at WriteWrap.afterWrite [as oncomplete] (net.js:789:14)
error Command failed with exit code 7.
```

**Comment by pantharshit00** [comment] 2020-03-16 11:24
I can confirm this. 

Steps for reproduction:
1. Bootstrap an empty Prisma 2 project
2. Add the following model:
```prisma
// This is your Prisma schema file,
// learn more about it in the docs: https://pris.ly/d/prisma-schema

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

generator client {
  provider = "prisma-client-js"
}

model User {
  id String @id @default(cuid())
  name String
}
```
3. Run `prisma2 generate --watch`
4. Change your model to the following:
```prisma
// This is your Prisma schema file,
// learn more about it in the docs: https://pris.ly/d/prisma-schema

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

generator client {
  provider = "prisma-client-js"
}

model User {
  id String @id @default(cuid())
  name String
  test String
}
```
5. See the error.

From my investigation so far, this only happens if your generate run creates a package.json file.

Version: `prisma2@2.0.0-preview024, binary version: 377df4fe30aa992f13f1ba152cf83d5770bdbc85`

**Comment by Jolg42** [comment] 2020-05-19 15:39
It looks like I can't reproduce it. (in latest alpha)

I'm closing it for now, feel free to comment here if you think it's still an issue 😃

**Comment by Jolg42** [comment] 2020-05-28 08:58
It just happened to me on macOS I will try to get a clear reproduction.

**Comment by Jolg42** [comment] 2020-06-23 15:02
Closing for now as I couldn't get a proper reproduction. So if anyone can reproduce in a reliable way that would be great 🙏

**Closed by Jolg42** 2020-06-23 15:02 UTC
Labels: bug/1-repro-available, kind/regression, team/typescript, topic: cli-generate
