### ISSUE TITLE
.transaction([]) fails with Request Timeout Error

### ISSUE THREAD

**Issue by pbelbin** [prisma/prisma#2957] opened 2020-07-08 02:15 UTC
## Bug description

Using the new `.transaction([])`, I am seeing this on the client (JavaScript):

```
{ Error: Request Timeout Error
    at PrismaClientFetcher._request (/app/node_modules/@prisma/client/runtime/index.js:1:213208) code: 'UND_ERR_REQUEST_TIMEOUT', meta: undefined }
```

## How to reproduce

Add multiple child records to an existing parent record.

```
const requests = [];

// loop that creates around 30 different requests, each with perhaps 500 to 1000 and puts them in the array like this:

requests.push(prisma.{entity}.update({
where: { id: {id that exists}},
data: {
  {related entity name}: {
create: [
 { between 500 and 1000 individual entities },
]
},
})

await prisma.transaction(requests);
```

## Expected behavior

Should complete without throwing the exception.

## Prisma information

Sorry, I can not share this information.
But, I can tell you it's just doing basic inserts.

## Environment & setup

- OS: macOS 10.15.5
- Database: MySQL 5.7.x
- Prisma version: 2.2.0
- Node.js version: v14.5.0

**Comment by pantharshit00** [comment] 2020-07-10 16:19
I am unable to reproduce this. I used the following datamodel for the reproduction:
```prisma
generator client {
  provider             = "prisma-client-js"
  experimentalFeatures = ["transactionApi"]
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

model User {
  id    String @id @default(cuid())
  name  String
  posts Post[]
}

model Post {
  id     String @id @default(cuid())
  title  String
  user   User   @relation(fields: [userId], references: [id])
  userId String
}
```

The script that I used:
```ts
import { PrismaClient } from "@prisma/client";
import * as faker from "faker";

async function main() {
  const client = new PrismaClient();
  const requests = [];
  let idData = await client.user.findMany({ select: { id: true } }); // 31 users
  let ids = idData.map((x) => x.id);
  let createLength = Math.floor(Math.random() * 1000 - 500 + 1 + 500);
  console.log(createLength);

  for (let id of ids) {
    requests.push(
      client.user.update({
        where: { id },
        data: {
          posts: {
            create: Array.from({
              length: createLength,
            }).map(() => ({
              title: faker.lorem.slug(),
            })),
          },
        },
      })
    );
  }
  console.log(requests.length);
  let tData = await client.transaction(requests);
  console.log(tData);
  client.disconnect();
}

main();
```

Result:
![image](https://user-images.githubusercontent.com/22195362/87175869-e3ee2580-c2f6-11ea-9d8d-147db7d59f45.png)


Rows inserted in the database:
<img width="679" alt="image" src="https://user-images.githubusercontent.com/22195362/87175922-f36d6e80-c2f6-11ea-819f-9878fcf0a50f.png">

Can you please try this again with the latest dev version? I used `2.3.0-dev.9`

If that doesn't work, we require more information so that we can reproduce this. If you are not comfortable sharing you exact query and datamodel over here, you can send it to "schemas@prisma.io". We can also sign a NDA if you want.

**Comment by pbelbin** [comment] 2020-07-29 19:49
Hmmmm.  I am still seeing this error with 2.3.0

```
Request Timeout Error
    at PrismaClientFetcher.request (/app/node_modules/@prisma/client/runtime/index.js:1:209296) code: 'UND_ERR_REQUEST_TIMEOUT', meta: undefined }
```

I am using a mysql (5.7.x) instance that's within a minikube instance.

When I build the mysql container with `DEBUG=*` defined, I also see this output:

```
2020-07-29T19:42:22.102Z engine { error:
   { RequestTimeoutError: Request Timeout Error
       at Timeout.Request.timeout.e (/app/node_modules/@prisma/client/runtime/index.js:1:176781)
       at ontimeout (timers.js:438:13)
       at tryOnTimeout (timers.js:300:5)
       at listOnTimeout (timers.js:263:5)
       at Timer.processTimers (timers.js:223:10)
     name: 'RequestTimeoutError',
     code: 'UND_ERR_REQUEST_TIMEOUT',
     message: 'Request Timeout Error' } }
2020-07-29T19:42:22.108Z prisma-client RequestTimeoutError: Request Timeout Error
    at Timeout.Request.timeout.e (/app/node_modules/@prisma/client/runtime/index.js:1:176781)
    at ontimeout (timers.js:438:13)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
2020-07-29T19:42:22.130Z prisma-client RequestTimeoutError: Request Timeout Error
    at Timeout.Request.timeout.e (/app/node_modules/@prisma/client/runtime/index.js:1:176781)
    at ontimeout (timers.js:438:13)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
2020-07-29T19:42:22.138Z prisma-client RequestTimeoutError: Request Timeout Error
    at Timeout.Request.timeout.e (/app/node_modules/@prisma/client/runtime/index.js:1:176781)
    at ontimeout (timers.js:438:13)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
2020-07-29T19:42:22.140Z prisma-client RequestTimeoutError: Request Timeout Error
    at Timeout.Request.timeout.e (/app/node_modules/@prisma/client/runtime/index.js:1:176781)
    at ontimeout (timers.js:438:13)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
2020-07-29T19:42:22.141Z prisma-client RequestTimeoutError: Request Timeout Error
    at Timeout.Request.timeout.e (/app/node_modules/@prisma/client/runtime/index.js:1:176781)
    at ontimeout (timers.js:438:13)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
2020-07-29T19:42:22.142Z prisma-client RequestTimeoutError: Request Timeout Error
    at Timeout.Request.timeout.e (/app/node_modules/@prisma/client/runtime/index.js:1:176781)
    at ontimeout (timers.js:438:13)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
2020-07-29T19:42:22.143Z prisma-client RequestTimeoutError: Request Timeout Error
    at Timeout.Request.timeout.e (/app/node_modules/@prisma/client/runtime/index.js:1:176781)
    at ontimeout (timers.js:438:13)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
2020-07-29T19:42:22.144Z prisma-client RequestTimeoutError: Request Timeout Error
    at Timeout.Request.timeout.e (/app/node_modules/@prisma/client/runtime/index.js:1:176781)
    at ontimeout (timers.js:438:13)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
2020-07-29T19:42:22.144Z prisma-client RequestTimeoutError: Request Timeout Error
    at Timeout.Request.timeout.e (/app/node_modules/@prisma/client/runtime/index.js:1:176781)
    at ontimeout (timers.js:438:13)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
2020-07-29T19:42:22.145Z prisma-client RequestTimeoutError: Request Timeout Error
    at Timeout.Request.timeout.e (/app/node_modules/@prisma/client/runtime/index.js:1:176781)
    at ontimeout (timers.js:438:13)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
2020-07-29T19:42:22.145Z prisma-client RequestTimeoutError: Request Timeout Error
    at Timeout.Request.timeout.e (/app/node_modules/@prisma/client/runtime/index.js:1:176781)
    at ontimeout (timers.js:438:13)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
2020-07-29T19:42:22.146Z prisma-client RequestTimeoutError: Request Timeout Error
    at Timeout.Request.timeout.e (/app/node_modules/@prisma/client/runtime/index.js:1:176781)
    at ontimeout (timers.js:438:13)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
2020-07-29T19:42:22.147Z prisma-client RequestTimeoutError: Request Timeout Error
    at Timeout.Request.timeout.e (/app/node_modules/@prisma/client/runtime/index.js:1:176781)
    at ontimeout (timers.js:438:13)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
2020-07-29T19:42:22.147Z prisma-client RequestTimeoutError: Request Timeout Error
    at Timeout.Request.timeout.e (/app/node_modules/@prisma/client/runtime/index.js:1:176781)
    at ontimeout (timers.js:438:13)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
2020-07-29T19:42:22.149Z prisma-client RequestTimeoutError: Request Timeout Error
    at Timeout.Request.timeout.e (/app/node_modules/@prisma/client/runtime/index.js:1:176781)
    at ontimeout (timers.js:438:13)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
2020-07-29T19:42:22.150Z prisma-client RequestTimeoutError: Request Timeout Error
    at Timeout.Request.timeout.e (/app/node_modules/@prisma/client/runtime/index.js:1:176781)
    at ontimeout (timers.js:438:13)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
2020-07-29T19:42:22.150Z prisma-client RequestTimeoutError: Request Timeout Error
    at Timeout.Request.timeout.e (/app/node_modules/@prisma/client/runtime/index.js:1:176781)
    at ontimeout (timers.js:438:13)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
2020-07-29T19:42:22.153Z prisma-client RequestTimeoutError: Request Timeout Error
    at Timeout.Request.timeout.e (/app/node_modules/@prisma/client/runtime/index.js:1:176781)
    at ontimeout (timers.js:438:13)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
2020-07-29T19:42:22.153Z prisma-client RequestTimeoutError: Request Timeout Error
    at Timeout.Request.timeout.e (/app/node_modules/@prisma/client/runtime/index.js:1:176781)
    at ontimeout (timers.js:438:13)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
2020-07-29T19:42:22.153Z prisma-client RequestTimeoutError: Request Timeout Error
    at Timeout.Request.timeout.e (/app/node_modules/@prisma/client/runtime/index.js:1:176781)
    at ontimeout (timers.js:438:13)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)

```

**Comment by pbelbin** [comment] 2020-07-29 22:45
Ok, so, I played around a bit, and came up with this example of the problem:

Yes, some of the names have been changed, because they collided with my existing model
schema.prisma:
```
model User2 {
  @@map("prisma_user")
  
  id    String @id @default(cuid())
  name  String
  posts Post2[]
}

model Post2 {
  @@map("prisma_post")
  
  id     String @id @default(cuid())
  title  String
  user   User2   @relation(fields: [userId], references: [id])
  userId String
}
```

and here is the code:

```typescript
import { PrismaClient } from "@prisma/client";
import * as faker from "faker";


function uniqueName() {
	let name;
	
	do {
		name = faker.name.firstName() + ' ' + faker.name.firstName() + ' ' + faker.name.lastName();
	} while (names.has(name));
	
	names.add(name);
	
	return name;
}
	
async function main() {
	// Initialize
	const client = new PrismaClient();
	const names = new Set<string>();
	

	// Remove old data
	await client.executeRaw('delete from prisma_post');
	await client.executeRaw('delete from prisma_user');
	
	
	// Create new users with posts
	const requests = [];
	
	for (let iUser = 0; iUser < 5000; iUser++) {
		const name = uniqueName();
		
		requests.push(
			client.user2.create({
				data: {
					name: name,

					posts: {
						create: Array.from({
							length: 500,
						}).map(() => ({
							title: name + ' ' + faker.lorem.slug(),
						})),
					},
				},
			})
		);
	}
	
	await client.transaction(requests);
	client.disconnect();
}

main();

```

**Comment by pbelbin** [comment] 2020-07-31 20:26
Hey there @pantharshit00 , hopefully now you have enough information to reproduce the issue.  Please confirm.

**Comment by pantharshit00** [comment] 2020-08-07 12:38
Hello @pbelbin 

I am able to reproduce a `EPIPE` with 300,000 inserts which you script does.

You script had some non-existant method used on arrays like `.has` and `.add` so I had to modify it a bit.

![image](https://user-images.githubusercontent.com/22195362/89644596-dddb6c80-d8d5-11ea-862a-1ed56fdb3198.png)

Here is a reproduction for internal use, we will look into this now: https://github.com/harshit-test-org/prisma-issue-2957

**Comment by jshimko** [comment] 2020-08-07 15:04
I can also consistently reproduce this with any prisma-client version _after_ 2.1.3.  I unfortunately rely on the transaction API for some bulk jobs that run daily in our app (~10k inserts), so my current solution is to just pin to 2.1.3 (which works every time).  In case it hasn't already been narrowed down, 2.2.0 is where this issue was introduced for me and I've tested every new release since then with no changes.

**Comment by pbelbin** [comment] 2020-08-07 18:43
> You script had some non-existant methods used on arrays like `.has` and `.add` so I had to modify it a bit.
> 
Yeah, that's fine.  I was using TypeScript and a Set<> rather than an Array, but that's fine.  The main thing is that it's reproducing the issue.

**Comment by cameronspeakflash** [comment] 2020-08-07 20:20
I have also recently run into the "Request Timeout Error" UND_ERR_REQUEST_TIMEOUT error. It happens intermittently so it's hard to know exactly what's causing it, but this is the only prisma code I have on that endpoint. FYI I'm working on migrating from TypeORM to Prisma so I'm currently mixing libraries, not sure if that affects anything. On 2.3.1 right now
`
interface IType {
  date: string;
  count: string;
}

export const fetchCountsByMonth: (
  userId: number,
  mediaId: number,
  context: GraphContext
) => Promise<IType[]> = async (userId, mediaId, context) => {
  const result = await context.prisma.queryRaw<IType[]>(`
    SELECT
      date_trunc('month', "word_study".last_update)::date AS "date",
      COUNT("word_study".id) as count
    FROM
      "media"
      INNER JOIN
        "media_vocabs_vocab" ON "media".id = "media_vocabs_vocab"."mediaId"
      INNER JOIN
        "vocab" ON "media_vocabs_vocab"."vocabId" = "vocab".id
      INNER JOIN
        "word_study" ON "word_study"."vocabId" = "vocab".id
      INNER JOIN
        "user" ON "user".id = "word_study"."userId"
    WHERE
      "user".id = ${userId}
      AND
      "media".id = ${mediaId}
      AND
      ("word_study".last_update > NOW() - 366 * INTERVAL '1 DAY')
    GROUP BY
      1
    ORDER BY
      1
  `);
  return result;
};
`

**Comment by cameronspeakflash** [comment] 2020-08-08 04:49
Looks like this error is getting thrown by Undici which has a default 30s request timeout. Believe it's pulled in here:
https://github.com/prisma/prisma/blob/4c7af2970acfec2557f0f88d9470896e7d6cc980/src/packages/engine-core/src/undici.ts

https://github.com/mcollina/undici/blob/4f9f3932d31dc61936e31f9df752cfc57d60b3fe/README.md

Strange that my query resolves in about a second if I run it directly. Could this be an issue where queries are getting batched and the whole thing is taking longer than 30 seconds? My initial page load is unoptimized and currently about a minute. Also strange that I only get this with NODE_ENV = production.

**Comment by jshimko** [comment] 2020-08-11 13:51
I see the fix for this has just been committed (https://github.com/prisma/prisma/commit/4a3f7b0b3412d4f70fa257c03b4947a97e7e9481).  Any idea on when this might be released?  This has been a big blocker for us being able to upgrade from Prisma 2.1.3 (and get all the great new features in the last few versions!).  

Sorry to nudge for this one.  We just really need the transactions API for our large bulk inserts (10k+) _and_ we need the new support for sorting by multiple fields in `orderBy`.  Unfortunately, no currently released version of Prisma supports both (without this bug).  

And thanks for the fix!  Absolutely LOVE working with Prisma!

**Comment by Sytten** [comment] 2020-08-11 14:27
@jshimko If it merged that means it will be available in the nightly build, just use that since it will most likely be included in 2.5.0. Maybe @timsuchanek can create a patch version for this fix since it is pretty annoying though.

**Closed** 2020-08-11 15:46 UTC
Labels: bug/2-confirmed, kind/bug, process/candidate, team/support, topic: previewFeatures, topic: transactionApi

**Comment by Jolg42** [comment] 2020-08-11 16:57
Yes indeed the fix will be released in the 2.5.0 release planned for Tuesday 18th, no patch planned right now.

**Comment by jshimko** [comment] 2020-08-11 16:59
@Jolg42 Will I be able to get it in a dev build before then?  I see those goes out fairly often, but it wasn't clear what triggers those.

**Comment by Jolg42** [comment] 2020-08-11 17:14
@jshimko A dev build is normally triggered after a new git commit so you can already get it if you want from 
`npm i --save-dev @prisma/cli@dev`

The current process is that every two weeks the dev build gets promoted to latest, and when we do that we make sure the build is "good". So by taking a dev build there is always a risk that you get a "not so good build", so I would not recommend you to run it in production, it's a dev build after all 😃

**Comment by jshimko** [comment] 2020-08-11 19:33
Great.  Thanks @Jolg42!  Things will be in development on my end too for at least the next week, so it'll be nice to at least be able to get stuff tested while I wait for the official release.

Thanks again!

**Comment by janpio** [comment] 2020-08-18 21:39
FYI: 2.5.0 has been released.

**Comment by durdenx** [comment] 2020-10-09 17:41
I get this error in v2.8.1

```
_p [Error]: 
Invalid `prisma.injection.upsert()` invocation in
webpack-internal:///./src/pages/api/injection/index.ts:191:79


  Request Timeout Error
    at Jw.request (/Users/user/project/node_modules/@prisma/client/runtime/index.js:210:54)
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {
  code: 'UND_ERR_REQUEST_TIMEOUT',
  meta: undefined
}
{
  "code": "UND_ERR_REQUEST_TIMEOUT"
}
```

if I use `prisma.$transation` on a large dataset (25k) and if i use `Promise.all`on the same dataset it works.

**Comment by janpio** [comment] 2020-10-09 18:53
Please open a new issue with this error @durdenx and we are happy to look into that.

**Comment by durdenx** [comment] 2020-10-12 08:17
@janpio I've opened an issue #3892
