### ISSUE TITLE
Prisma client generate wrong where condition in query

### ISSUE THREAD

**Issue by CANHBK** [prisma/prisma#3987] opened 2020-10-21 08:15 UTC
## Bug description

Prisma generate `1=1` where condition while actual my where query is 
`where:{
date: dayjs(date).format('YYYY-MM-DD')
}`

## How to reproduce
My table:
![image](https://user-images.githubusercontent.com/37535071/96692175-f1b04e00-13af-11eb-96f2-d9404c08cd89.png)
My model:
![image](https://user-images.githubusercontent.com/37535071/96692137-e78e4f80-13af-11eb-8dbd-028328d33c30.png)
My query:
![image](https://user-images.githubusercontent.com/37535071/96693075-ffb29e80-13b0-11eb-98bc-cba94034cd26.png)
Wrong generated query:
![image](https://user-images.githubusercontent.com/37535071/96692470-4358d880-13b0-11eb-9dbe-d7bc4c50ea9c.png)

This is my work around:
![image](https://user-images.githubusercontent.com/37535071/96693409-68018000-13b1-11eb-8e6a-67106b5e15af.png)

## Expected behavior

Prisma generate where query like date = '2020-10-21' instead '1=1'

## Environment & setup

- OS: Windows
- Database: MySQL
- Node.js version: v12.18.3
- Prisma version:

```
@prisma/cli          : 2.9.0
@prisma/client       : 2.9.0
Current platform     : windows
Query Engine         : query-engine 369b3694b7edb869fad14827a33ad3f3f49bbc20 (at node_modules\@prisma\cli\query-engine-windows.exe)
Migration Engine     : migration-engine-cli 369b3694b7edb869fad14827a33ad3f3f49bbc20 (at node_modules\@prisma\cli\migration-engine-windows.exe)
Introspection Engine : introspection-core 369b3694b7edb869fad14827a33ad3f3f49bbc20 (at node_modules\@prisma\cli\introspection-engine-windows.exe)
Format Binary        : prisma-fmt 369b3694b7edb869fad14827a33ad3f3f49bbc20 (at node_modules\@prisma\cli\prisma-fmt-windows.exe)
Studio               : 0.296.0
Preview Features     : connectOrCreate
```

**Comment by pantharshit00** [comment] 2020-10-30 14:47
Hey @CANHBK 

I have confirmed another issue #3985 and looks like this issue is duplicate of that now. 

So I am going to close this, please follow that issue now

**Closed by pantharshit00** 2020-10-30 14:47 UTC
