### ISSUE TITLE
Raw queries do not update `updatedAt`

### ISSUE THREAD

**Issue by ryands17** [prisma/prisma#7952] opened 2021-06-30 11:46 UTC
### Bug description

When using raw queries, the `updatedAt` is not updated.

### How to reproduce

1. Create schema:

```prisma
model User {
  id        Int      @id @default(autoincrement())
  name      String
  createdAt DateTime @default(now())
  updatedAt DateTime @updatedAt
}
```

2. Run the following query:

```ts
  await prisma.user.create({ data: { name: 'user1' } })

  await sleep(10) // simulating delay

  await prisma.$queryRaw`update "User" set "name" = 'user 2' where "id" = 1`
```

The `updatedAt` doesn't get updated.

### Expected behavior

The `updatedAt` should get updated.

### Prisma information

prisma               : 2.26.0
@prisma/client       : 2.26.0
Current platform     : darwin

### Environment & setup

- OS: Mac OS
- Database: PostgreSQL
- Node.js version: 14.17.0

### Prisma Version

prisma               : 2.26.0
@prisma/client       : 2.26.0
Current platform     : darwin

**Comment by Sytten** [comment] 2021-06-30 14:14
I would categorize that as works as intended. I really don't want prisma to start modifying my raw queries to update timestamps or send other update queries.

**Comment by pantharshit00** [comment] 2021-07-21 22:21
I will also consider that expected behaviour. I am going to close this.

**Closed by pantharshit00** 2021-07-21 22:21 UTC
Labels: kind/bug

**Comment by Noitidart** [comment] 2022-10-03 01:35
I had this same issue. The solution I came up with was to give the "updatedAt" column a default value same as "createdAt" like this:

```
model User {
  id        Int      @id @default(autoincrement())
  name      String
  createdAt DateTime @default(now())
  updatedAt DateTime @updatedAt @default(now())
}
```

The only problem is when the timezone of system of the postgres database is not UTC, it will not match the "createdAt" timestamp.
