### ISSUE TITLE
Allow filtering and sorting by raw SQL expressions

### ISSUE THREAD

**Issue by blocka** [prisma/prisma#11568] opened 2022-02-02 11:57 UTC
## Problem

Given a table with two fields, first_name and last_name, I'd like to filter by `first_name || ' ' || last_name`. Basically I'd like to filter via a raw sql expression (and sort).

**Comment by pantharshit00** [comment] 2022-02-04 13:23
Closing as duplicate of #5848

**Closed by pantharshit00** 2022-02-04 13:23 UTC

**Comment by anubhavrajpoot8** [comment] 2023-09-15 05:14
await transaction.$queryRaw`SELECT *,
      CAST(created_by AS int) AS created_by,
      CAST(updated_by AS int) AS updated_by
      FROM site_contractor
      WHERE
      (
      (type = '${types}') AND
      (
        name ILIKE '%' || '${globalSearch}' || '%' OR
        description ILIKE '%' || '${globalSearch}' || '%' OR
        address->>'street' ILIKE '%' || '${globalSearch}' || '%' OR
        address->>'city' ILIKE '%' || '${globalSearch}' || '%' OR
        address->>'state' ILIKE '%' || '${globalSearch}' || '%' OR
        address->>'pin_code' ILIKE '%' || '${globalSearch}' || '%' OR
        address->>'country' ILIKE '%' || '${globalSearch}' || '%'
      )
      )
      AND (is_delete = ${is_delete})
      ORDER BY ${order_by_column} ${order_by_direction}
      LIMIT ${limit}
      OFFSET ${offset}`
    ;
    when i run this why its throw error as syntax error
