### ISSUE TITLE
NextJs 12.2.3 middleware (after update nextJs to 12.2.3 can't make request inside middleware)

### ISSUE THREAD

**Issue by eposha** [prisma/prisma#14474] opened 2022-07-24 13:34 UTC
### Bug description

NextJs 12.2.3 middleware (after update nextJs to 12.2.3 can't make request inside middleware)

NextJs 12.1.6 don't have problem with using prisma inside middleware

- OS: Mac OS
- Database: PostgreSQL
- Node.js version: 16

### Prisma Version

```
4.1
```

**Comment by aqrln** [comment] 2022-07-25 08:58
Hi @eposha! Could you please elaborate more on what the issue is and provide some information for reproduction? Thank you!

**Comment by eposha** [comment] 2022-07-26 14:15
@aqrln 

<---- schema.prisma ---->


```
datasource db {
  provider = "postgresql"
  url      = env("NEXT_PUBLIC_DATABASE_URL")
}

generator client {
  provider   = "prisma-client-js"
  engineType = "dataproxy"
}
```



<---- import prisma from 'lib/prisma'; ---->

```
import { PrismaClient } from '@prisma/client/edge';

let prisma: PrismaClient;

if (process.env.NODE_ENV === 'production') {
  prisma = new PrismaClient();
} else {
  let globalWithPrisma = global as typeof globalThis & {
    prisma: PrismaClient;
  };
  if (!globalWithPrisma.prisma) {
    globalWithPrisma.prisma = new PrismaClient();
  }
  prisma = globalWithPrisma.prisma;
}

export default prisma;
```



<---- middleware ---->

```
import { NextResponse } from 'next/server';
import type { NextRequest } from 'next/server';

import prisma from 'lib/prisma';

// RegExp for public files
const PUBLIC_FILE = /\.(.*)$/;

export const middleware = async (req: NextRequest) => {
  const url = req.nextUrl.clone();
  const { pathname } = url;

  if (
    pathname.startsWith('/_next') ||
    pathname.startsWith('/api') ||
    pathname.startsWith('/static') ||
    PUBLIC_FILE.test(pathname) ||
    pathname.includes('.')
  ) {
    const response = NextResponse.next();

    return response;
  }

  try {
    const user = await prisma.user.findFirst({
      where: {
        id: 'cl614s9q000100cpredrwjaml',
      },
    });

    console.log('user', user);
  } catch (error) {
    console.log(error);
  }
};

```

<---- error ---->
```

error - unhandledRejection: Error: aborted
    at connResetException (node:internal/errors:691:14)
    at abortIncoming (node:_http_server:596:17)
    at socketOnClose (node:_http_server:590:3)
    at Socket.emit (node:events:402:35)
    at TCP.<anonymous> (node:net:687:12) {
  code: 'ECONNRESET'
}
{ [Error: 
Invalid `prisma.user.findFirst()` invocation:


  Cannot fetch data from service:
fetch failed] code: 'P5010', clientVersion: '4.1.0', meta: undefined }
```

**Comment by eposha** [comment] 2022-07-26 14:16
> Hi @eposha! Could you please elaborate more on what the issue is and provide some information for reproduction? Thank you!


@aqrln  Hi

<---- schema.prisma ---->


```
datasource db {
  provider = "postgresql"
  url      = env("NEXT_PUBLIC_DATABASE_URL")
}

generator client {
  provider   = "prisma-client-js"
  engineType = "dataproxy"
}
```



<---- import prisma from 'lib/prisma'; ---->

```
import { PrismaClient } from '@prisma/client/edge';

let prisma: PrismaClient;

if (process.env.NODE_ENV === 'production') {
  prisma = new PrismaClient();
} else {
  let globalWithPrisma = global as typeof globalThis & {
    prisma: PrismaClient;
  };
  if (!globalWithPrisma.prisma) {
    globalWithPrisma.prisma = new PrismaClient();
  }
  prisma = globalWithPrisma.prisma;
}

export default prisma;
```



<---- middleware ---->

```
import { NextResponse } from 'next/server';
import type { NextRequest } from 'next/server';

import prisma from 'lib/prisma';

// RegExp for public files
const PUBLIC_FILE = /\.(.*)$/;

export const middleware = async (req: NextRequest) => {
  const url = req.nextUrl.clone();
  const { pathname } = url;

  if (
    pathname.startsWith('/_next') ||
    pathname.startsWith('/api') ||
    pathname.startsWith('/static') ||
    PUBLIC_FILE.test(pathname) ||
    pathname.includes('.')
  ) {
    const response = NextResponse.next();

    return response;
  }

  try {
    const user = await prisma.user.findFirst({
      where: {
        id: 'cl614s9q000100cpredrwjaml',
      },
    });

    console.log('user', user);
  } catch (error) {
    console.log(error);
  }
};

```

<---- error ---->
```

error - unhandledRejection: Error: aborted
    at connResetException (node:internal/errors:691:14)
    at abortIncoming (node:_http_server:596:17)
    at socketOnClose (node:_http_server:590:3)
    at Socket.emit (node:events:402:35)
    at TCP.<anonymous> (node:net:687:12) {
  code: 'ECONNRESET'
}
{ [Error: 
Invalid `prisma.user.findFirst()` invocation:


  Cannot fetch data from service:
fetch failed] code: 'P5010', clientVersion: '4.1.0', meta: undefined }
```

**Comment by garrensmith** [comment] 2022-07-28 13:13
The P5010 means the Prisma Client cannot connect to the data proxy. Could you check the client is generated correctly and the connection string is correct.

**Comment by eposha** [comment] 2022-07-28 16:40
> The P5010 means the Prisma Client cannot connect to the data proxy. Could you check the client is generated correctly and the connection string is correct.

The Prisma configuration is set correctly, because only in the middleware this error occurs, in other parts of the application the Prisma works correctly

**Comment by garrensmith** [comment] 2022-07-29 17:50
Could you open a ticket on next.JS. We haven’t changed anything around that. This could be something that has changed in next.js
________________________________

**Comment by sannajammeh** [comment] 2022-08-04 03:23
Getting the same thing here. My route hangs for about 1 minute before I get this error logged.

```
Invalid `prisma.purchases.findFirst()` invocation:


  Cannot fetch data from service:
fetch failed] code: 'P5010', clientVersion: '4.1.1', meta: undefined }
```

**Comment by sannajammeh** [comment] 2022-08-04 03:30
@eposha Confirmed this is working on my codebase installing `next@canary`.

Must've been some issue with their middleware.

**Comment by Weakky** [comment] 2022-08-04 12:51
Hey, @sannajammeh, do you confirm this issue is fixed for you? If so, we'll close it 👍

**Closed** 2022-08-04 12:51 UTC
Labels: bug/0-unknown, kind/bug, team/client

**Comment by ctjlewis** [comment] 2023-04-17 03:40
```
  Cannot fetch data from service:
  The "listener" argument must be of type function. Received an instance of Object
...
code: 'P5010',
clientVersion: '4.12.0',
```

The equivalent `.create()` runs in Prisma Data console and there don't seem to be issues in production but it's a very confusing error. 

Seems to be an error that was reintroduced in a newer version, since August's canary has been production for months. Repro'd on latest canary.

cc @leerob

**Comment by ctjlewis** [comment] 2023-04-17 03:44
Actually this reproes even on `next@12.3.1`, a Sept 2022 release. 

I don't think this should be closed, this should be investigated. I created a new Data Proxy URL to try to flush it out and nothing is fixing this, and it's entirely idiopathic.

**Comment by ctjlewis** [comment] 2023-04-17 04:00
It's clearly an issue with Next's dev server - I worked around by offloading Prisma logic to an Edge function, but this is definitely a problem that needs both teams to address and it does impact paid services so I would take it seriously.

**Comment by janpio** [comment] 2023-04-18 16:59
How about you open a new bug report then if you think this still exists with a modern Next.js version? Very happy to take another look if you provide all the information the issue template asks for, and optimally also provide a full reproduction of the issue. Thanks!

**Comment by ctjlewis** [comment] 2023-04-18 17:01
Oh, I don’t have to do that Jan, I paid you guys money! 

Your job is to investigate it, and you’re already way behind, trying to shove the work off.

Work with Vercel to identify the issue and fix it.

**Comment by sabinadams** [comment] 2023-04-18 19:12
Hey there @ctjlewis 👋🏻

We certainly don't want to sweep any bugs under the rug or ignore them. A reproduction in a separate issue would help us get to the bottom of the error quicker as it would give us more information about effectively reproducing the problem. That's usually a good starting point to begin troubleshooting.

I would also recommend creating an issue in NextJS's issues [here](https://github.com/vercel/next.js/issues) in the meantime.

I understand the frustration, given you have paid to use Data Proxy, however in cases such as these, external entities are something we don't have much control over until we get a good reproduction to initiate collaboration between the two parties.

Thanks!
