### ISSUE TITLE
[Driver Adapters] PrismaClient for CockroachDB provider is broken since version  >= 5.16

### ISSUE THREAD

**Issue by ad6025b** [prisma/prisma#24996] opened 2024-08-11 12:05 UTC
### Bug description

CockroachDB provider is broken since version  >= 5.16.

The  line:

`const prisma = new PrismaClient({ adapter });
`

**thrown error:**
**PrismaClientInitializationError**: The Driver Adapter `@prisma/adapter-pg`, based on `postgres`, is not compatible with the provider `cockroachdb` specified in the Prisma schema.

### How to reproduce

You can use your own example:
https://github.com/prisma/ecosystem-tests/tree/dev/driver-adapters-wasm/pg-cf-basic

change the provider to "cockroachdb", and  you will see the error thrown when you get to line

`const prisma = new PrismaClient({ adapter }); `

=====================================================

@jkomyno @Jolg42  the root cause is the merge/pr below.
     -> https://github.com/prisma/prisma/issues/21864 
          ->(https://github.com/prisma/prisma/pull/24481  (v 5.16)    <===  this is the merge that broke cockroachdb

![image](https://github.com/user-attachments/assets/1a46d3d5-6c09-4667-ba1d-9c8a4cc3a589)

the bug in the merge introduced is in the function getPrismaClient in file getPrismaClient.ts   (see screenshot below)
At line 383, you need to check for postressql or cockroachdb 
  -> this pattern of checking for both [postgres or cockroachdb] is in other parts of the code (since they share the same postgres driver), but forgotten to be here)
      -> so PrismaClientInitializationError error is thrown if the provider = cockroachdb

![image](https://github.com/user-attachments/assets/aa0edde7-81bb-4afa-84ab-0f0febca6c75)

### Expected behavior

the command below should work for cockroachdb
`const prisma = new PrismaClient({ adapter }); `

### Prisma information

const prisma = new PrismaClient({ adapter });

datasource db {
  provider = "cockroachdb"
   url = "..."
}

### Environment & setup

OS: windows 10
Database: [PostgreSQL]
Node.js version: v18.16.0

### Prisma Version

```
prisma 5.18   (or 5.16 or 5.17)
@prisma/client 5.18   (or 5.16 or 5.17)
@prisma/adapter-pg  5.18   (or 5.16 or 5.17)
```

**Comment by ad6025b** [comment] 2024-08-12 09:45
@jkomyno  @SevInf  there is a similar logic error (checking for both [ postgres or cockroachdb ].  
 ->this ticket has same logic error for cockroachdb -> https://github.com/prisma/prisma/issues/24475
     --> can we fix this ticket as well?

**Comment by jkomyno** [comment] 2024-08-12 17:20
Hi @ad6025b, thanks for raising this. I’d like to clarify that `provider = "cockroachdb"` is currently not part of the `driverAdapters` preview feature. Currently, we support Driver Adapters for the most popular database providers: `postgresql`, `sqlite`, `mysql`. We are currently working on stabilising support for these providers, before focusing on other database families.

In fact, we do not mention CockroachDB at all in our [Driver Adapters docs](https://www.prisma.io/docs/orm/overview/databases/database-drivers#how-to-use-driver-adapters).
(`cockroachdb`, despite being similar to `postgresql` in nature, actually behaves differently in scenarios that go beyond the simplest queries and database schemas.)

Hence, https://github.com/prisma/prisma/pull/24481 and similar PRs validating the `provider` attribute are actually implemented as intended, so I will close this ticket for now.

Thank you for expressing your interest in a CockroachDB-compatible Driver Adapter though! May you please open a new feature request for that, so that we can track it for the future? Thanks!

**Closed by jkomyno** 2024-08-12 17:20 UTC
Labels: kind/bug
