### ISSUE TITLE
PANIC in query-engine/connectors/sql-query-connector/src/database/operations/write.rs:73:22 Could not figure out an ID in create

### ISSUE THREAD

**Issue by Stallion67** [prisma/prisma#15066] opened 2022-08-29 17:40 UTC
Hi Prisma Team! My Prisma Client just crashed. This is the report:
## Versions

| Name            | Version            |
|-----------------|--------------------|
| Node            | v12.21.0           | 
| OS              | rhel-openssl-1.0.x |
| Prisma Client   | 2.30.3             |
| Query Engine    | query-engine b8c35d44de987a9691890b3ddf3e2e7effb9bf20|
| Database        | undefined|

## Logs
```
aphQLToJSError (/app/node_modules/@prisma/client/runtime/index.js:30059:16)
    at BinaryEngine.request (/app/node_modules/@prisma/client/runtime/index.js:29944:24)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async cb (/app/node_modules/@prisma/client/runtime/index.js:36464:26)
prisma:client:fetcher Error: The column `famunera_db.planner_lists.balance` does not exist in the current database.
    at BinaryEngine.graphQLToJSError (/app/node_modules/@prisma/client/runtime/index.js:30059:16)
    at BinaryEngine.request (/app/node_modules/@prisma/client/runtime/index.js:29944:24)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async cb (/app/node_modules/@prisma/client/runtime/index.js:36464:26)
prisma:client:fetcher Error: The column `famunera_db.planner_lists.balance` does not exist in the current database.
    at BinaryEngine.graphQLToJSError (/app/node_modules/@prisma/client/runtime/index.js:30059:16)
    at BinaryEngine.request (/app/node_modules/@prisma/client/runtime/index.js:29944:24)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async cb (/app/node_modules/@prisma/client/runtime/index.js:36464:26)
prisma:client:fetcher Error: The column `famunera_db.planner_lists.balance` does not exist in the current database.
    at BinaryEngine.graphQLToJSError (/app/node_modules/@prisma/client/runtime/index.js:30059:16)
    at BinaryEngine.request (/app/node_modules/@prisma/client/runtime/index.js:29944:24)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async cb (/app/node_modules/@prisma/client/runtime/index.js:36464:26)
prisma:client:fetcher Error: The column `famunera_db.planner_lists.balance` does not exist in the current database.
    at BinaryEngine.graphQLToJSError (/app/node_modules/@prisma/client/runtime/index.js:30059:16)
    at BinaryEngine.request (/app/node_modules/@prisma/client/runtime/index.js:29944:24)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async cb (/app/node_modules/@prisma/client/runtime/index.js:36464:26)
prisma:engine stdout  PANIC in query-engine/connectors/sql-query-connector/src/database/operations/write.rs:73:22
Could not figure out an ID in create
prisma:engine {
  error: SocketError: other side closed
      at Socket.onSocketEnd (/app/node_modules/@prisma/client/runtime/index.js:27696:24)
      at Socket.emit (events.js:326:22)
      at Socket.EventEmitter.emit (domain.js:483:12)
      at endReadableNT (_stream_readable.js:1241:12)
      at processTicksAndRejections (internal/process/task_queues.js:84:21) {
    code: 'UND_ERR_SOCKET'
  }
}
prisma:engine { cwd: '/app/prisma' }
prisma:engine Search for Query Engine in /app/node_modules/.prisma/client
plusX Execution permissions of /app/node_modules/.prisma/client/query-engine-rhel-openssl-1.0.x are fine
prisma:engine { flags: [ '--enable-raw-queries', '--port', '46243' ] }
prisma:engine stdout  Starting a mysql pool with 3 connections.
prisma:engine stdout  Started http server on http://127.0.0.1:46243
prisma:engine Search for Query Engine in /app/node_modules/.prisma/client
plusX Execution permissions of /app/node_modules/.prisma/client/query-engine-rhel-openssl-1.0.x are fine
prisma:engine Client Version: 2.30.3
prisma:engine Engine Version: query-engine b8c35d44de987a9691890b3ddf3e2e7effb9bf20
prisma:engine Active provider: mysql
prisma:engine stdout  PANIC in query-engine/connectors/sql-query-connector/src/database/operations/write.rs:73:22
Could not figure out an ID in create
prisma:engine {
  error: SocketError: other side closed
      at Socket.onSocketEnd (/app/node_modules/@prisma/client/runtime/index.js:27696:24)
      at Socket.emit (events.js:326:22)
      at Socket.EventEmitter.emit (domain.js:483:12)
      at endReadableNT (_stream_readable.js:1241:12)
      at processTicksAndRejections (internal/process/task_queues.js:84:21) {
    code: 'UND_ERR_SOCKET'
  }
}
prisma:engine {
  error: Error: connect ECONNREFUSED 127.0.0.1:46243
      at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1144:16) {
    errno: 'ECONNREFUSED',
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '127.0.0.1',
    port: 46243
  }
}
```

## Client Snippet
```ts
// PLEASE FILL YOUR CODE SNIPPET HERE
```

## Schema
```prisma
// PLEASE ADD YOUR SCHEMA HERE IF POSSIBLE
```

=

**Comment by garrensmith** [comment] 2022-08-30 07:45
@Stallion67 could you include your schema and the code you did to create this error?

**Comment by Stallion67** [comment] 2022-08-30 08:41
I am having an issue with my  ID

**Comment by Stallion67** [comment] 2022-08-30 10:23
: "\nInvalid `prisma.users.create()` invocation:\n\n\n  PANIC in query-engine/connectors/sql-query-connector/src/database/operations/write.rs:73:22\nCould not figure out an ID in create\n\nThis is a non-recoverable error which probably happens when the Prisma Query Engine has a panic.\

**Comment by danstarns** [comment] 2022-08-30 11:30
@Stallion67 Please share your Prisma schema and a way for us to replicate the issue you're having.

**Comment by Stallion67** [comment] 2022-08-30 12:02
Schema

model users {
  ID                    Int                  @id @default(autoincrement())
  username              String
  fullname              String?
  email                 String?              @unique
  phone                 String?              @unique 
  role                  String?
  partnerId             Int?                  @default(10)
  IsOutGrower           Int?                  @default(0)
  IsAggregator          Int?                  @default(0)
  aggregatorID          Int?                  @default(34571)
  FarmAcreage           Int?                  @default(0)
  password_old          String?
  password              String?
  id_no                 String?
  services              String?
  phone_activation_code String?
  phone_status          users_phone_status?  @default(not_verified)
  email_activation_code String?
  email_status          users_email_status   @default(not_verified)
  account_status        users_account_status @default(not_verified)
  subscription_status   Int                  @default(1)
  wallet_amount         String               @default("0")
  password_reset_key    String?
  online_status         Int?
  last_seen             String?
  search_rank           String?
  old_email             String?
  deleted               Int                  @default(0)
  country               String               @default("Uganda")
  gender                String               @default("male")
  dob                   String?
  pro_dealin            String?
  size_scale            String?
  looking_for           String?
  cover_picture         String?
  profile_picture       String?
  other_contacts        String?
  website               String?
  user_documents        String?
  address               String?
  reg_time              String
  order_meta            order_meta[]
  referral_partner      referral_partner[]
  outgrowerproduct      outgrowerproduct[]
  
}

**Comment by Stallion67** [comment] 2022-08-30 12:03
> @Stallion67 Please share your Prisma schema and a way for us to replicate the issue you're having.

Schema
model users {
ID Int @id @default(autoincrement())
username String
fullname String?
email String? https://github.com/unique
phone String? https://github.com/unique
role String?
aggregatorID Int? @default(34571)
FarmAcreage Int? @default(0)
password_old String?
password String?
id_no String?
services String?
phone_activation_code String?
phone_status users_phone_status? @default(not_verified)
email_activation_code String?
email_status users_email_status @default(not_verified)
account_status users_account_status @default(not_verified)
subscription_status Int @default(1)
wallet_amount String @default("0")
password_reset_key String?
online_status Int?
last_seen String?
search_rank String?
old_email String?
deleted Int @default(0)
country String @default("Uganda")
gender String @default("male")
dob String?
pro_dealin String?
size_scale String?
looking_for String?
cover_picture String?
profile_picture String?
other_contacts String?
website String?
user_documents String?
address String?
reg_time String

}

**Comment by danstarns** [comment] 2022-09-06 15:33
@Stallion67 Thanks for getting back with your schema, what query did you perform?

**Comment by Stallion67** [comment] 2022-09-06 23:30
prisma create query,
however my databasealready contains data so the query is trying to begin withID index 0 
this is after migration

**Comment by Stallion67** [comment] 2022-09-06 23:30
> prisma create query,
> however my databasealready contains data so the query is trying to begin withID index 0
> this is after migration

prisma create query,
however my databasealready contains data so the query is trying to begin withID index 0
this is after migration

**Comment by janpio** [comment] 2022-09-07 08:40
Similar to the other issue @Stallion67 the underlying problem here also seems to be missing columns in the database:
https://github.com/prisma/prisma/issues/15075#issuecomment-1239059270

In this case:
```
prisma:client:fetcher Error: The column `famunera_db.planner_lists.balance` does not exist in the current database.
```

I would suggest you also update to a much more recent version of Prisma, as it is very possible that this is a known bug in this year old version of Prisma. We can only support more recent versions.

**Comment by janpio** [comment] 2022-09-23 16:41
Any success with updating @Stallion67?

**Comment by janpio** [comment] 2022-10-19 17:29
Ping @Stallion67 - can you confirm this was caused by a mismatch between your database and schema? That would mean we can close this issue. Thanks.

**Comment by janpio** [comment] 2022-11-25 00:16
Closing then until someone provides more information. Please comment or open a new issue. Thanks!

**Closed by janpio** 2022-11-25 00:16 UTC
Labels: bug/0-unknown, kind/bug, team/client, topic: rust panic
