### ISSUE TITLE
primsa migrate dev bug with mysql provider

### ISSUE THREAD

**Issue by yamiM0NSTER** [prisma/prisma#7334] opened 2021-05-28 21:33 UTC
### Bug description

I ran today into an issue when I tried to deploy project using prisma with mysql on my server. Generated migration file had different table name casing than initial migration file that creates tables and mysql server immediately reported an error.
I created example repository showcasing the issue. All that has to be done is simple table starting with uppercase and then a simple edit on one of fields.

### How to reproduce

Reproduction process described here:
https://github.com/yamiM0NSTER/prisma-migrate-bug

### Expected behavior

Either table names should be lower case from the very beginning or generated migrations should use same name casing.

### Prisma information

Described in linked repository

### Environment & setup

OS: Ubuntu 18.04.2 LTS
Database MySQL
Node.js: v14.16.1

### Prisma Version

```
2.23.0
```

**Comment by pantharshit00** [comment] 2021-05-28 22:10
This is related to this mysql option: https://dev.mysql.com/doc/refman/8.0/en/identifier-case-sensitivity.html

Are you using Windows and WSL by any chance? 

If yes, we will close this as duplicate of https://github.com/prisma/prisma/issues/7250

**Comment by yamiM0NSTER** [comment] 2021-05-28 22:44
Another inconsistency with that is generated PrismaClient class
![image](https://user-images.githubusercontent.com/22958062/120048274-f65c7500-c016-11eb-8a49-b2a0deecd2f9.png)

**Comment by pantharshit00** [comment] 2021-05-28 22:44
MySQL will automatically lowercase everything by default on windows. We can't really do anything about it. If your production environment is not MySQL windows, we do not recommend using MySQL windows for development and you should use docker. Otherwise, you can also change that option in mysql config(https://dev.mysql.com/doc/refman/8.0/en/identifier-case-sensitivity.html)

I will close this as duplicate of https://github.com/prisma/prisma/issues/6972

**Closed by pantharshit00** 2021-05-28 22:44 UTC
Labels: bug/0-needs-info, kind/bug, team/client, topic: mysql
