### ISSUE TITLE
`libraryEngine` silently fails to start (crash in container on Compute Engine) 

### ISSUE THREAD

**Issue by bryceAebi** [prisma/prisma#15678] opened 2022-10-05 22:34 UTC
### Bug description

I have a Docker container running on Compute Engine. I can confirm with `psql` that my db connection string is correct. When I run a typscript script, the script exits with no output. With console.log statements, I can see that the script ceases execution silently at my first Prisma query. I've also tried running Prisma queries manually via `tsx` but running a query causes `tsx` to immediately  exit with no error.

I have tried deleting and reinstalling node modules and I have tried rerunning `prisma generate`, but to no avail.

The script works in the same docker container on my M1 Mac. In the Debug info I notice the following in the Cloud Engine container: 
```
  prisma:client:libraryEngine:loader  Searching for Query Engine Library in /usr/src/app/node_modules/.prisma/client +0ms
  prisma:client:libraryEngine:loader  loadEngine using /usr/src/app/node_modules/.prisma/client/libquery_engine-debian-openssl-1.1.x.so.node +1ms  
  prisma:client:libraryEngine  library starting +0ms
```
Note that in the debug output above, the library does not start. I see the following on my M1 mac
```
  
  prisma:client:libraryEngine:loader  Searching for Query Engine Library in /usr/src/app/node_modules/.prisma/client +0ms
  prisma:client:libraryEngine:loader  loadEngine using /usr/src/app/node_modules/.prisma/client/libquery_engine-linux-arm64-openssl-1.1.x.so.node
prisma:client:libraryEngine  library starting +0ms
  prisma:client:libraryEngine  library started +12ms
```

I'm using the standard "Container Optimized OS" that Google pre-selects when passing a VM a docker image during setup.

### How to reproduce
```
/**
* Command I run: `npx tsx src/scripts/reset-progress-for-user.ts`
* / 


/**
* Prisma debug output
*/
DEBUG=* npx tsx src/scripts/reset-progress-for-user.ts aouoa aoeu 
  agentkeepalive sock[0#registry.npmjs.org:443::::::::true:::::::::::::] create, timeout 300001ms +0ms
  agentkeepalive sock[0#registry.npmjs.org:443::::::::true:::::::::::::](requests: 1, finished: 1) free +189ms
  prisma:tryLoadEnv  Environment variables loaded from /usr/src/app/.env +0ms
  prisma:tryLoadEnv  Environment variables loaded from /usr/src/app/.env +2s
  prisma:client  dirname /usr/src/app/node_modules/.prisma/client +0ms
  prisma:client  relativePath ../../../prisma +0ms
  prisma:client  cwd /usr/src/app/prisma +1ms
  prisma:client  clientVersion 4.2.1 +0ms
  prisma:client  clientEngineType library +1ms
  prisma:client:libraryEngine  internalSetup +0ms
  prisma:client:libraryEngine:loader  Searching for Query Engine Library in /usr/src/app/node_modules/.prisma/client +0ms
  prisma:client:libraryEngine:loader  loadEngine using /usr/src/app/node_modules/.prisma/client/libquery_engine-debian-openssl-1.1.x.so.node +1ms
  prisma:client  Prisma Client call: +460ms
  prisma:client  prisma.user.findUnique({
  where: {
    id: 'aouoa'
  }
}) +2ms
  prisma:client  Generated request: +1ms
  prisma:client  query {
  findUniqueUser(where: {
    id: "aouoa"
  }) {
 ... omitted ...
  }
}
 +0ms
  prisma:client:libraryEngine  sending request, this.libraryStarted: false +464ms
  prisma:client:libraryEngine  library starting +1ms
```

### Expected behavior

I would expect the script to execute successfully.

### Prisma information

```prisma
// This is your Prisma schema file,
// learn more about it in the docs: https://pris.ly/d/prisma-schema

generator client {
  provider      = "prisma-client-js"
  binaryTargets = ["native", "linux-musl"]
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

model User {
  ... omitted ...

  @@map("users")
}

```

```ts
/**
 * .ts script
 */

import { PrismaClient } from '@prisma/client'

const prisma = new PrismaClient()

const main = async () => {
  const users = await prisma.user.findMany()
  console.log("USERS QUERY COMPLETED") // <= Code never executes
}

main()
  .then(async () => {
    await prisma.$disconnect()
  })
  .catch(async (e) => {
    console.error(e)
    await prisma.$disconnect()
    process.exit(1)
  })
```

### Environment & setup

- OS: debian 11.5
- Database: Postgresql via Cloud SQL
- Node.js version: 
v18.9.1

### Prisma Version

4.2.1. Same error after upgrading to 4.4.0

**Comment by millsp** [comment] 2022-10-06 21:46
Could you try with the following to see if it shows any other errors?
```ts
generator client {
  provider = "prisma-client-js"
  engineType = "binary"
}
```
After that can you also try with `libraryEngine` again but on Node 16?

**Comment by bryceAebi** [comment] 2022-10-07 01:23
@millsp using the above snippet the code is now working! Thank you for the help.

Could you explain what's going on? Does it make sense for me to leave my schema.prisma config in this new state?

Included are the debug logs from the successful run of the script. I omitted all of the `prisma:client` logs



```
user@instance-1:/usr/src/app# DEBUG=* npx tsx src/scripts/add-missing-routines-to-users.ts 
  agentkeepalive sock[0#registry.npmjs.org:443::::::::true:::::::::::::] create, timeout 300001ms +0ms
  agentkeepalive sock[0#registry.npmjs.org:443::::::::true:::::::::::::](requests: 1, finished: 1) free +97ms
  prisma:tryLoadEnv  Environment variables loaded from /usr/src/app/.env +0ms
  prisma:tryLoadEnv  Environment variables loaded from /usr/src/app/.env +2s
  prisma:client  dirname /usr/src/app/node_modules/.prisma/client +0ms
  prisma:client  relativePath ../../../prisma +0ms
  prisma:client  cwd /usr/src/app/prisma +1ms
  prisma:client  clientVersion 4.4.0 +0ms
  prisma:client  clientEngineType binary +1ms
  prisma:engine  Search for Query Engine in /usr/src/app/node_modules/.prisma/client +0ms
  prisma:engine  Search for Query Engine in /usr/src/app/node_modules/.prisma/client +1ms
  plusX  Execution permissions of /usr/src/app/node_modules/.prisma/client/query-engine-debian-openssl-1.1.x are fine +0ms
  plusX  Execution permissions of /usr/src/app/node_modules/.prisma/client/query-engine-debian-openssl-1.1.x are fine +16ms
  prisma:client  Prisma Client call: +274ms
  prisma:client  prisma.user.findMany(undefined) +2ms
  prisma:client  Generated request: +0ms
  prisma:client  query {
  findManyUser {
    id
    email
    password
    nameFirst
    nameLast
    stripeId
    isPaying
    createdAt
    updatedAt
    deletedAt
    isAdmin
  }
}
 +0ms
  prisma:engine  { cwd: '/usr/src/app/prisma' } +144ms
  prisma:engine  Search for Query Engine in /usr/src/app/node_modules/.prisma/client +2ms
  plusX  Execution permissions of /usr/src/app/node_modules/.prisma/client/query-engine-debian-openssl-1.1.x are fine +130ms
  prisma:engine  {
  flags: [
    '--enable-raw-queries',
    '--enable-metrics',
    '--enable-open-telemetry',
    '--port',
    '43753'
  ]
} +3ms
  prisma:engine  stdout Starting a postgresql pool with 3 connections. +32ms
  prisma:engine  stdout Started query engine http server on http://127.0.0.1:43753 +81ms
  prisma:engine  Search for Query Engine in /usr/src/app/node_modules/.prisma/client +13ms
  plusX  Execution permissions of /usr/src/app/node_modules/.prisma/client/query-engine-debian-openssl-1.1.x are fine +135ms
  prisma:engine  Client Version: 4.4.0 +26ms
  prisma:engine  Engine Version: query-engine f352a33b70356f46311da8b00d83386dd9f145d6 +0ms
  prisma:engine  Active provider: postgresql +1ms
  prisma:client  Prisma Client call: +189ms


  ......

  Omit a bunch of the query logs
  
   ....



  prisma:engine  Stopping Prisma engine +769ms
  prisma:engine  Waiting for start promise +0ms
  prisma:engine  Done waiting for start promise +0ms

```

**Comment by millsp** [comment] 2022-10-10 13:22
We always recommend using the default. `binary` is still supported of course, but it might add a bit of overhead compared to `library`. So we'll need to investigate this further. Could you please try `library` again on Node 16?

**Comment by bryceAebi** [comment] 2022-10-10 16:41
Ok, I tried bulding with the node-16-slim image and the scripts are working as expected. Here is the debug output for what it's worth.

instance-2-test-for-prisma:/usr/src/app# DEBUG=* npx tsx src/scripts/add-missing-routines-to-users.ts 
  agentkeepalive sock[0#registry.npmjs.org:443::::::::true:::::::::::::] create, timeout 300001ms +0ms
  agentkeepalive sock[0#registry.npmjs.org:443::::::::true:::::::::::::](requests: 1, finished: 1) free +101ms
  prisma:tryLoadEnv  Environment variables loaded from /usr/src/app/.env +0ms
  prisma:tryLoadEnv  Environment variables loaded from /usr/src/app/.env +2s
  prisma:client  dirname /usr/src/app/node_modules/.prisma/client +0ms
  prisma:client  relativePath ../../../prisma +1ms
  prisma:client  cwd /usr/src/app/prisma +0ms
  prisma:client  clientVersion 4.4.0 +1ms
  prisma:client  clientEngineType library +0ms
  prisma:client:libraryEngine  internalSetup +0ms
  prisma:client:libraryEngine:loader  Searching for Query Engine Library in /usr/src/app/node_modules/.prisma/client +0ms
  prisma:client:libraryEngine:loader  loadEngine using /usr/src/app/node_modules/.prisma/client/libquery_engine-debian-openssl-1.1.x.so.node +1ms
  prisma:client  Prisma Client call: +112ms
  prisma:client  prisma.user.findMany(undefined) +2ms
  prisma:client  Generated request: +0ms
  prisma:client  query {
  findManyUser {
   ... omitted ...
  }
}
 +1ms
  prisma:client:libraryEngine  sending request, this.libraryStarted: false +115ms
  prisma:client:libraryEngine  library starting +0ms
  prisma:client:libraryEngine  library started +30ms
  prisma:client  Prisma Client call: +39ms
  prisma:client  prisma.routineTracker.findFirst({
  where: {


   ... Query logs omitted ...

  prisma:client:libraryEngine  sending request, this.libraryStarted: true +3ms
  prisma:client:libraryEngine  library stopping +9ms
  prisma:client:libraryEngine  library stopped +1ms
  prisma:client:libraryEngine:exitHooks  exit event received: beforeExit +0ms
  prisma:client:libraryEngine:exitHooks  exit event received: exit +0ms

**Comment by aqrln** [comment] 2022-10-13 13:48
Thank you for the report and for checking things @bryceAebi. This looks like the same issue as https://github.com/prisma/prisma/issues/10649 and other linked issues, so I'm going to go ahead and close this issue in favor of it so it's easier to keep track of everything.

The reason why the same container with the same database is not crashing for you locally is because the issue only happens on x86_64 CPUs, but not on ARM.

While we are looking for the best way to fix or prevent the underlying problem, the recommended workaround is to make sure that the versions of OpenSSL used by Node.js and the system OpenSSL match:
* either by downgrading Node.js to 16.x,
* or by upgrading the operating system (or Docker image) to use OpenSSL 3 (for example, by using Ubuntu 22.04 instead of Debian 11).

If your distribution provides a build of Node.js 18 with OpenSSL 1.1.1, you can use that instead of the upstream Node.js build that vendors OpenSSL 3. This is the case on Alpine, where you can install `nodejs-current` from repository `community`: it provides Node.js 18 linked with OpenSSL 1.1.1q, and the issue is not reproducible when using it.

Alternatively, if you can't do any of that and you need to stay with the upstream build of Node.js 18 on a system with OpenSSL 1.1.x, you can switch to the [binary engine](https://www.prisma.io/docs/concepts/components/prisma-engines/query-engine#defining-the-query-engine-type-for-prisma-client) in Prisma.

**Closed by aqrln** 2022-10-13 13:48 UTC
Labels: bug/0-unknown, kind/bug, tech/engines, tech/engines/query engine, team/client, topic: node-api, topic: google cloud
