### ISSUE TITLE
Schema validation error mentions `Error parsing attribute "@id"` but it's actually about `@@id`

### ISSUE THREAD

**Issue by Jolg42** [prisma/prisma#10566] opened 2021-12-03 16:37 UTC
Given this schema
```prisma
generator js {
  provider        = "prisma-client-js"
  previewFeatures = ["extendedIndexes"]
}

datasource db {
  provider = "mysql"
  url      = env("DATABASE_URL")
}

model Post {
  title    String @db.VarChar(300)
  abstract String @db.VarChar(3000)

  @@id([title(sort: Desc)])
}
```

it errors when running `npx prisma@latest validate` with
```
//without preview feature
Error: Schema parsing
error: Error parsing attribute "@id": The sort and length args are not yet available
  -->  schema.prisma:13
   |
12 |
13 |   @@id([title(sort: Desc)])
   |
error: Error parsing attribute "@id": The sort argument is not supported in the primary key with the current connector
  -->  schema.prisma:13
   |
12 |
13 |   @@id([title(sort: Desc)])
   |

Validation Error Count: 2
```

```
with preview feature
Error: Schema parsing
error: Error parsing attribute "@id": The sort argument is not supported in the primary key with the current connector
  -->  schema.prisma:14
   |
13 |
14 |   @@id([title(sort: Desc)])
   |

Validation Error Count: 1
```

The correct error should look like this with `@@id` instead of `@id`?
```diff
-	error: Error parsing attribute "@id": The sort argument is not supported in the primary key with the current connector
+	error: Error parsing attribute "@@id": The sort argument is not supported in the primary key with the current connector
```

**Comment by janpio** [comment] 2021-12-03 18:00
Can reproduce. 

Additionally, in VSCode the red squiggly lines do not include the `@@` but start at `index` only. These should probably be included, or only the attribute (and possibly its value) should be underlined.

**Comment by pimeys** [comment] 2021-12-07 12:14
The leaking error gets fixed now, for proper spans for length/sort etc. please file a new issue due to its being more work.

**Comment by Jolg42** [comment] 2021-12-07 14:26
This issue is actually about the `@@id` / `@id` issue

**Closed** 2022-05-06 13:58 UTC
Labels: bug/2-confirmed, kind/bug, topic: error, topic: schema validation, tech/engines, team/schema, topic: extendedIndexes
