### ISSUE TITLE
Reason: Error in connector: Error creating a database connection.

### ISSUE THREAD

**Issue by aputinski** [prisma/prisma#882] opened 2019-11-04 19:02 UTC
I'm using `2.0.0-alpha.280` (upgrading from `2.0.0-preview-12`) and now I'm getting `Reason: Error in connector: Error creating a database connection`. I did some various logging in the Photon client / engine and I can see my database connection string is being passed correctly. This was working in preview 12 and I haven't changed anything besides upgrading Prisma and fixing various typing errors.

This happens both locally and in my Firebase Functions deployment. I'm using Google Cloud SQL with Postgres.

**Comment by pantharshit00** [comment] 2019-11-08 17:57
Are you receiving "certificate was not trusted" in the error message?

If so this might be a duplicate of #884

**Comment by alexwine36** [comment] 2019-11-11 21:33
I ran into the same error with 2.0.0-preview016.2 on Windows. 
I also tried adding the sslaccept=accept_invalid_cert flag to Postgres uri to no avail.
Postgres installation is on AWS

**Comment by pantharshit00** [comment] 2019-11-13 10:10
Hey @alexwine36, can you please tell me what exact error you are getting. Maybe you can open a new issue for your problem :).

**Comment by alexwine36** [comment] 2019-11-13 17:34
After install the client generates without error
using 
    "nexus": "0.12.0-beta.14",
    "nexus-prisma": "0.5.0",
    "prisma2": "2.0.0-preview016.2"

This error appears after starting and attempting to run a query
```
Error:
Invalid `photon.()` invocation in C:\Users\awine\Documents\Programming\Node\customer-survey-prisma-v3\node_modules\nexus-prisma\src\builder.ts:236:18



Reason: Error in connector: Error creating a database connection.

    at PhotonFetcher.<anonymous> (C:\Users\awine\Documents\Programming\Node\customer-survey-prisma-v3\node_modules\@generated\photon\index.js:54:27)
    at Generator.throw (<anonymous>)
    at rejected (C:\Users\awine\Documents\Programming\Node\customer-survey-prisma-v3\node_modules\@generated\photon\index.js:6:65)
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
```

**Comment by sejr** [comment] 2019-11-14 04:35
I am seeing this issue as well.

**Comment by PhilippvH1** [comment] 2019-11-19 15:58
Same here.

**Comment by greben99** [comment] 2019-11-20 07:59
Same here, lift up and generate all works fine, connects. When I run the query it has an Error creating a database connection.

**Comment by pantharshit00** [comment] 2019-11-20 14:49
Can you please try adding `&sslaccept=accept_invalid_certs` to your url and trying this again

**Comment by naveen-bharathi** [comment] 2020-01-28 02:53
I've got this same issue in **`prisma2@2.0.0-preview020.3`**. But when I add **`&sslaccept=accept_invalid_certs`** to the URL it works fine.

**Comment by pantharshit00** [comment] 2020-04-21 04:46
@naveen-bharathi Can you reproduce this in the latest version ?

**Comment by naveen-bharathi** [comment] 2020-04-21 05:05
No the issue didn’t occur for me in the latest beta

**Comment by pantharshit00** [comment] 2020-04-21 05:38
I am going to close this issue now. Anyone still facing this, please comment here or open a new issue

**Closed by pantharshit00** 2020-04-21 05:38 UTC
Labels: bug/0-needs-info, kind/bug

**Comment by barkinunal** [comment] 2020-10-27 13:37
I am seeing this issue as well.

**Comment by janpio** [comment] 2020-10-27 13:52
Can you please open a new issue with more information @barkinunal? Thanks.
