### ISSUE TITLE
Prisma Data Proxy connection limit and pool timeout in serverless environment (AWS + Serverless Framework + Prisma ORM)

### ISSUE THREAD

**Issue by mikeSyn** [prisma/prisma#19365] opened 2023-05-21 08:03 UTC
### Discussed in https://github.com/prisma/prisma/discussions/19364

<div type='discussions-op-text'>

<sup>Originally posted by **mikeSyn** May 21, 2023</sup>
Hi, 
I'm trying to use `connection_limit` and `pool_timeout` Prisma Data proxy with specific values, but it seems to ignore them.
I'm using PostgreSQL in AWS RDS.

My current connection test is:

`prisma://aws-eu-central-1.prisma-data.com/?connection_limit=5&pool_timeout=120&api_key=<API_KEY>`

When it occurs an timeout, I get this error:

`Timed out fetching a new connection from the connection pool. More info: http://pris.ly/d/connection-pool (Current connection pool timeout: 10, connection limit: 3)`

As you can see, the limits are ignored (10 instead of 120 and 3 instead of 5).

We really did a lot of tests. Can anyone help us figuring why?

</div>

**Comment by janpio** [comment] 2023-06-05 22:36
Duplicate of https://github.com/prisma/prisma/discussions/19364

**Closed by janpio** 2023-06-05 22:36 UTC
Labels: bug/1-unconfirmed, kind/bug, team/client, topic: pool_timeout
