### ISSUE TITLE
Aggregate ignores @map value of field, generating an incorrect query

### ISSUE THREAD

**Issue by ConneXNL** [prisma/prisma#3425] opened 2020-08-25 09:46 UTC
When doing an aggregation on the following field:
`field_name             Int             @map("actual_column_name")`

```
    const result = await prisma.example.aggregate({
        avg: {
            field_name: true
        }
    });
```

An invalid query is generated: 
```SELECT AVG(`field_name`) ```

rather than 
```SELECT AVG(`actual_column_name`)```

(tested in MYSQL)

**Comment by pantharshit00** [comment] 2020-08-27 14:54
I can confirm this bug. Looks like we are ignoring the map directive.

https://github.com/harshit-test-org/prisma-issue-3425

**Comment by dpetrick** [comment] 2020-08-28 09:43
Fixed with https://github.com/prisma/prisma-engines/pull/1080, will be in the 2.6 release.

**Closed by dpetrick** 2020-08-28 09:43 UTC
Labels: bug/2-confirmed, kind/bug, team/engines, topic: aggregateApi
