### ISSUE TITLE
Error: connect EADDRNOTAVAIL 127.0.0.1 when Azure function app using Prisma, VNet integration enabled

### ISSUE THREAD

**Issue by inertica** [prisma/prisma#5844] opened 2021-02-25 15:55 UTC
## Bug description

Azure function app uses Prisma 2 to select data from MySQL database server on virtual private network. When querying the data, function app crashes with the following error message with changing port number:

```
2021-02-25T09:21:33.515 [Error] Executed 'Functions.offline-data-exporter' (Failed, Id=b4889147-xxxx-xxxx-xxx-
xxxxxxxxxxx, Duration=1554ms)
Result: FailureException: Error:Invalid `prisma.disconnector.findMany()` invocation 
in D:\home\site\wwwroot\dist\shared\offline-data-exporter.js:15:84
connect EADDRNOTAVAIL 127.0.0.1 - Local (0.0.0.0:50306)Stack: Error:Invalid `prisma.disconnector.findMany()`
invocation in D:\home\site\wwwroot\dist\shared\offline-data-exporter.js:15:84
connect EADDRNOTAVAIL 127.0.0.1 - Local (0.0.0.0:50306)at PrismaClientFetcher.request 
(D:\home\site\wwwroot\node_modules\@prisma\client\runtime\index.js:78585:15)at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

## How to reproduce

1. Use Azure App Service Plan: Elastic Premium EP1 to use VNet integration
2. Configure VNet Integration to function app (database is in 10.0.0.x, function subnet is 10.0.100.x)
3. Deploy Azure function app using Prisma client
4. Run export function which queries the MySQL database server
5. See error above

## Expected behavior

Database disconnector table query results should be returned normally. 

Database querying has been working properly with the same setup until the beginning of February. Upgrading or downgrading Prisma, or even deploying the last known working version of function app does not solve the problem. Creating a new app with similar settings does not work either.

The same exporter code works fine on two other Azure environments using Azure MySQL for database without VNet integration enabled in function app. 

Using mysql2 to connect and query disconnector data from VNet database server works ok. 

## Prisma information

prisma.schema:
```
datasource network {
  provider = "mysql"
  url      = "mysql://user:pass@10.0.0.x/database?connection_limit=1&sslmode=disable" // sample, read from env, see below
}

generator client {
  provider = "prisma-client-js"
}

model Disconnector {
  code               String    @id
  name               String
  protectiveEarthing Float?    @map(name: "protective_earthing")
  systemEarthing     Float?    @map(name: "system_earthing")
  totalEarthing      Float?    @map(name: "combined_earthing")
  measurementDate    DateTime? @map(name: "measure_date")
  data               Json

  @@map(name: "disconnector")
}
```

data-exporter.ts:
```
const prisma = new PrismaClientFactory().create(network);
try {
      await prisma.$connect();
      const disconnectors = this.asDisconnectorDto(
        await prisma.disconnector.findMany(),
        await prisma.$queryRaw<
          LocationData[]
        >`SELECT code, ST_AsText(loc) AS spatialData FROM disconnector;`,
        projection
      );
      await prisma.$disconnect();
  ....
} finally {
      await prisma.$disconnect();
}
```

prisma-client-factory.ts - code from last known working commit using Prisma v2.10.2. Reads connection string from env and replaces the database portion:

```
export class PrismaClientFactory {
  create(network: string): PrismaClient {
    const database = `abcdef_${network}`;
    const prisma = new PrismaClient({
      // log: ["query", "info"],
      datasources: {
        network: {
          url: process.env.MYSQL_CONNECTION_STRING?.replace(
            "${database}",
            database
          ),
          provider: "mysql",
        },
      },
    });
    return prisma;
  }
}
```

## Environment & setup

- OS: Azure function app on Windows machine with VNet integration enabled
- Database: MySQL 5.7 on private virtual network 
- Node.js version: v12.18.0, also tested with setting Node 14 LTS in Azure function app settings
- Prisma version: 2.10.2 and 2.17.0 both tested

`tcpping` can reach database server and port 3306 from function app console.

See MySQL connection string example format in Prisma schema code.

## Additional checks done

The following have been checked:
* database connection string is ok and database user can connect to database and has sufficient rights
* deployed function app has been stopped and restarted 
* database query works normally using mysql2 library
* VNet integration subnet 10.0.100.x is connected and working correctly on other function apps not using Prisma

The following have been tried and none of these have worked:
* upgrading Prisma version to 2.17.0 and re-deploying the function app
* downgrading back to 2.10.2 and re-deploying the function app
* building release from the last known working commit and re-deploying the function app
* deploying code to new function app with similar configuration built from ground up
* removing `connection_limit` and `sslmode` from MySQL connection string

**Comment by pantharshit00** [comment] 2021-03-05 06:46
@inertica Looks like http bridge is getting closed. Can you please try this workaround? 

https://github.com/prisma/prisma/issues/5533#issuecomment-788016345

**Comment by inertica** [comment] 2021-03-05 08:51
@pantharshit00 we tried the workaround, but it does not work as the platform deployed on Azure is Windows. Prisma 2.10 was working previously, and UDS problem was introduced in 2.15 according to the referenced issue.

Here is the error:
```
Executed 'Functions.offline-data-exporter' (Failed, Id=59e4df7b-1451-4775-af14-52ae91ba4848, Duration=5510ms)
Result: FailureException: Error: Unix sockets not supported on this platform
Stack: Error: Unix sockets not supported on this platform
at LineStream.<anonymous> (D:\home\site\wwwroot\node_modules\@prisma\client\runtime\index.js:27139:31)
at LineStream.emit (events.js:315:20)at addChunk (_stream_readable.js:295:12)
at readableAddChunk (_stream_readable.js:271:9)
at LineStream.Readable.push (_stream_readable.js:212:10)
at LineStream.Transform.push (_stream_transform.js:152:32)
at LineStream._pushBuffer (D:\home\site\wwwroot\node_modules\@prisma\client\runtime\index.js:24055:19)
at LineStream._transform (D:\home\site\wwwroot\node_modules\@prisma\client\runtime\index.js:24049:10)
at LineStream.Transform._read (_stream_transform.js:191:10)
at LineStream.Transform._write (_stream_transform.js:179:12)
```

**Comment by pantharshit00** [comment] 2021-03-13 17:36
Hmm, this seems unrelated to binary process then. Try increasing the connection timeout once. It might be failing before attaining a connection. 

Add this to your connection string: `?connect_timeout=30&pool_timeout=30&socket_timeout=30`

**Comment by inertica** [comment] 2021-03-22 09:24
Increasing the timeouts did not make a difference. The EADDRNOTAVAIL error is returned usually right after (less than 1 second) the DB query is executed.

**Comment by pantharshit00** [comment] 2021-05-16 13:45
Hey @inertica 

Are you able to still reproduce this in the latest version of Prisma?

**Comment by inertica** [comment] 2021-05-20 16:19
We migrated to another ORM due to this problem. I'll let you know if we have time to test this in production at some point, but probably it will take a while.

**Comment by DavidChristiansen** [comment] 2021-06-21 22:41
Please propose a fix for this

**Comment by janpio** [comment] 2021-06-22 14:21
A fix for what exactly? Do you have the same problem that inertica had in the beginning? Can you help us to get to a reproduction?

**Comment by DavidChristiansen** [comment] 2021-06-22 22:42
Yes, Same issue - Azure Function (Windows) with VNET Integration.   Happy to create a reproduction to aid testing.

**Comment by inertica** [comment] 2021-06-23 08:56
@DavidChristiansen it would be excellent if you could assist with the reproduction of the issue on your environment. At this point, our production environment is not available to set up testing for this and we have already extensively switched ORM to another one to keep production up, running and updateable.

**Comment by stianl** [comment] 2021-08-16 15:04
I also get the same `Error: connect EADDRNOTAVAIL 127.0.0.1` error when the first query is run. Using Azure App Service with windows container.

**Comment by BeGj** [comment] 2021-09-13 09:51
Why does prisma need internet connection when generating the client?
It's requesting `......../windows/query.engine.dll.node.gz.sha256`.

**Comment by janpio** [comment] 2021-09-13 12:33
That sounds pretty unrelated @BeGj. Please open a new issue or discussion about this for you unexpected behavior so we can look into it.

**Comment by BeGj** [comment] 2021-09-13 13:49
@janpio  Sorry. This was the most related issue I were able to find.. Trying again in a  newdiscussion https://github.com/prisma/prisma/discussions/9228

**Comment by garrensmith** [comment] 2022-08-22 13:03
I'm closing this since I think Prisma 4 will fix this with n-api.

**Closed by garrensmith** 2022-08-22 13:03 UTC
Labels: bug/0-unknown, kind/bug, topic: deployment-platform, status/needs-action, team/client
