### ISSUE TITLE
Prisma introspect during "migrate" upgrade process re-formatted and schema and removed comments/structure

### ISSUE THREAD

**Issue by Southclaws** [prisma/prisma#4742] opened 2020-12-19 20:54 UTC
## Bug description

We're doing a migration and found the tooling updated so I started going through this: https://www.prisma.io/docs/guides/prisma-guides/prisma-migrate-guides/add-prisma-migrate-to-a-project

When I ran `prisma introspect` my schema was re-formatted and all the fields moved around and comments were removed:

```diff
 model Server {
-  id String @id @default(uuid())
-
-  // essential data (short names to save data!)
-  ip String  @unique
-  hn String
-  pc Int
-  pm Int
-  gm String
-  la String
-  pa Boolean
-  vn String
-  ru Rule[]
-
-  // domain name for de-duplication purposes
-  domain String?
-
-  // rich data (entered by server owners via the web UI)
+  id          String   @id @default(uuid())
+  ip          String   @unique
+  hn          String
+  pc          Int
+  pm          Int
+  gm          String
+  la          String
+  pa          Boolean
+  vn          String
+  domain      String?
   description String?
   banner      String?
-
-  // user who owns this server
-  User   User?   @relation(fields: [userId], references: [id])      
-  userId String?
-
-  active    Boolean
-  updatedAt DateTime @updatedAt
+  userId      String?
+  active      Boolean
+  updatedAt   DateTime @updatedAt
+  User        User?    @relation(fields: [userId], references: [id])
+  ru          Rule[]
 }
```

I'm not sure if there were any necessary changes here that are required by the upgrade process.

## How to reproduce

I'm guessing you just do a migrate on a slightly outdated prisma project. You can repro it with our open source project: https://github.com/openmultiplayer/web

## Expected behavior

I didn't expect the introspect command to actually edit the schema, and if it did, I would have assumed comments and structure would not be touched.

## Prisma information

https://github.com/openmultiplayer/web

## Environment & setup

- OS: Windows
- Database: PostgreSQL
- Node.js version: v12.18.3
- Prisma version:
```
web on  master [✘!] via 🐹 v1.15.6 via ⬢ v12.18.3 took 7m24s 
❯ prisma version
Environment variables loaded from .env
@prisma/cli          : 2.13.1
@prisma/client       : Not found
Current platform     : windows
Query Engine         : query-engine fcbc4bb2d306c86c28014f596b1e8c7980af8bd4 (at C:\Users\Southclaws\AppData\Roaming\npm\node_modules\@prisma\cli\node_modules\@prisma\engines\query-engine-windows.exe)
Migration Engine     : migration-engine-cli fcbc4bb2d306c86c28014f596b1e8c7980af8bd4 (at C:\Users\Southclaws\AppData\Roaming\npm\node_modules\@prisma\cli\node_modules\@prisma\engines\migration-engine-windows.exe)
Introspection Engine : introspection-core fcbc4bb2d306c86c28014f596b1e8c7980af8bd4 (at C:\Users\Southclaws\AppData\Roaming\npm\node_modules\@prisma\cli\node_modules\@prisma\engines\introspection-engine-windows.exe)
Format Binary        : prisma-fmt fcbc4bb2d306c86c28014f596b1e8c7980af8bd4 (at C:\Users\Southclaws\AppData\Roaming\npm\node_modules\@prisma\cli\node_modules\@prisma\engines\prisma-fmt-windows.exe)
Studio               : 0.329.0
```

**Comment by pantharshit00** [comment] 2020-12-24 19:03
I can reproduce this by checkout to `26170dd317c0223c2a10e70884fe5541ab85ff64` commit of the repository, bootstrapping the database using the old migrate and the running `prisma introspect`. 


The formatting changes happened as prisma introspect produces an output formatted by our opinionated  formatter(You can manually run the formatter using `npx prisma format` or use it via the VSCode/Vim extension) to the output. Since your schema wasn't formatted already, the schema printer produced an output which produced a diff, which is expected. 

What is not expected is removal of comments, we should fix that part. 

Also, you actually doesn't need to run `prisma introspect` since your already have a schema which represents your database. I guess you have already completed the migration to the new migrate after analyzing your repo commits.

**Comment by Southclaws** [comment] 2020-12-25 13:08
Yeah the reason for the introspect was because I was doing the process again because I was already doing a migration for a new schema when all the tooling got updated (our docker image just installs the latest prisma cli) so things broke a little. It's fine now though, apart from this unexpected removal of comments.

I do use the formatter too, it formats on save - favourite feature - but that format process doesn't remove comments or re-organise models.

**Comment by do4gr** [comment] 2021-01-04 18:46
Thanks for reporting this. It seems there is a bug where we do not recognize comments with double slashes, but only ones with three. We'll fix this.

**Comment by albertoperdomo** [comment] 2021-01-07 10:08
It seems fixing the double slash comments issue is more complex than we anticipated. Three slashes seems to work better. Hopefully we can look into this soon.

**Comment by Jolg42** [comment] 2021-03-25 11:14
@do4gr to confirm that 2 // are ignored now.

**Comment by pantharshit00** [comment] 2021-06-28 13:48
I can confirm this is fixed now. We correct parse `//` in the engines now so this is fixed.

**Closed by pantharshit00** 2021-06-28 13:48 UTC
Labels: bug/2-confirmed, kind/bug, status/needs-action, team/migrations, topic: introspection, topic: re-introspection
