### ISSUE TITLE
Switching between `referentialIntegrity` modes makes migration history obsolete

### ISSUE THREAD

**Issue by janpio** [prisma/prisma#15225] opened 2022-09-07 09:20 UTC
Old migrations that either do have FKs or do not have FKs (depending on the old/new setting) will not be valid in the new situation.

**Comment by Jolg42** [comment] 2022-10-05 10:13
@janpio Do you have more details about this?

**Comment by Jolg42** [comment] 2022-10-05 10:59
This should be easy to reproduce in a brownfield project:

- start a project and use `mysql` provider 
- create some migrations
- decide to switch to PlanetScale database which is "MySQL"
- add `referentialIntegrity=prisma`
- `prisma migrate` 💥 because past migrations were created with Foreign Keys which is not supported by PlanetScale

The opposite should be a bit different:

- start a project and use `mysql` provider with PlanetScale with the `referentialIntegrity` preview feature
- create some migrations
- decide to switch to MySQL
- remove the `referentialIntegrity` preview feature
- 💥 because past migrations were created without Foreign Keys and next migration will try to create them all


To explore:
We only record the `provider` inside the `migration_lock.toml`, it could make sense to also have the `relationMode` like
```migration_lock.toml
# Please do not edit this file manually
provider = "mysql"
relationMode = "prisma"
```

So Migrate could know in advance that the migrations files would not work and tell the user that the migrations history needs to be recreated = fresh baselining.

**Comment by janpio** [comment] 2022-10-05 21:56
I think this is actually related: https://github.com/prisma/prisma/issues/10843

**Comment by Jolg42** [comment] 2022-10-06 13:19
Reproduction in a sample project

## mysql to planetscale

- start a project from scratch and use `mysql` provider 
- create initial migration with `npx prisma migrate dev` (contains Foreign keys)
- decide to switch to PlanetScale database which is "MySQL"
- add `referentialIntegrity=prisma`
- create a new migration with `npx prisma migrate dev` -> drops Foreign Keys!
```
-- DropForeignKey
ALTER TABLE `Post` DROP FOREIGN KEY `Post_authorId_fkey`;

-- DropForeignKey
ALTER TABLE `Profile` DROP FOREIGN KEY `Profile_userId_fkey`;
```
- `prisma migrate deploy` 💥 because past migrations were created with Foreign Keys which is not supported by PlanetScale
```
2 migrations found in prisma/migrations

Applying migration `20221006125949_`
Error: P3018

A migration failed to apply. New migrations cannot be applied before the error is recovered from. Read more about how to resolve migration issues in a production database: https://pris.ly/d/migrate-resolve

Migration name: 20221006125949_

Database error code: 1317

Database error:
Foreign keys cannot be created on this database. Learn more how to handle this: https://pris.ly/d/migrate-no-foreign-keys

Please check the query number 4 from the migration file.
```

## planetscale to mysql
- start a project from scratch and use `mysql` provider with a planetscale connection string
- create initial migration with `npx prisma migrate dev` but errors since a shadow database is required
```
Error: P3014

Prisma Migrate could not create the shadow database. Please make sure the database user has permission to create databases. Read more about the shadow database (and workarounds) at https://pris.ly/d/migrate-shadow

Original error: 
create database is not supported
   0: migration_core::state::DevDiagnostic
             at migration-engine/core/src/state.rs:251
```
- Use `npx prisma db push` which is what we recommend
- decide to switch to PlanetScale database which is "MySQL"
- remove `referentialIntegrity=prisma`
- Either
	- use `npx prisma db push` ✅ will create the Foreign Keys
	- create a new migration file with `npx prisma migrate dev` ✅ will create the Foreign Keys


Alternatively 
- create initial migration with `npx prisma migrate dev` (Without Foreign Keys)
- decide to switch to PlanetScale database which is "MySQL"
- remove `referentialIntegrity=prisma`
- create a new migration file with `npx prisma migrate dev` 
	- reset is needed
	- the migration file adds the Foreign Keys

**Comment by jkomyno** [comment] 2022-10-06 13:54
(Note: the "Prisma Migrate could not create the shadow database" error message is already tracked in this other issue: https://github.com/prisma/prisma/issues/13275)

**Comment by Jolg42** [comment] 2022-10-10 12:24
Tom:
I agree with the diagnostic and that the proposed mechanism with the key in migration_lock.toml would work.
My only doubt is whether we should really error out. Here's my reasoning:
- Migrations are about managing changes on the one or several databases where you store your important data.
- When you change your relation mode, it can be one of two scenarios:
	- You are moving to a new database provider. For example from mysql to planetscale. You do not need to carry over your migrations history: you have a new planetscale instance, it does not need your past migrations.
	- You are changing your existing database to (not) use foreign keys. In this case you do want the migration that is going to drop / add them.
In the first scenario, adding that Prisma error makes us error earlier, instead of when you will try applying your existing migrations to your new empty database. But this is rare enough that I think docs might be a better fit.
In the second case, erroring out may be the wrong behaviour.

Joël:
So if we want to support the second scenario, we can’t error.
We could still track the referentialIntegrity setting but only warn
- as a comment inside the new migration that drops the foreign keys
- in the terminal/CLI when the new migration is created

Maybe it’s better to document this (as a first step) and see if we want to do something later.

**Comment by janpio** [comment] 2022-10-10 16:27
### Conclusion

Document the following: When switching from default to `relationMode=prisma` you need to decide if you want and can keep the existing migration history for your use case (fine when MySQL but want to foreign keys, not fine when Planetscale (Side comment: We actually discourage `migrate dev` for PlanetScale)).

**Comment by Jolg42** [comment] 2022-10-11 16:17
Closing this in favor of docs issue https://github.com/prisma/docs/issues/3882

**Closed by Jolg42** 2022-10-11 16:17 UTC
Labels: bug/2-confirmed, kind/bug, team/schema, topic: referentialIntegrity/relationMode
