### ISSUE TITLE
Ballooning of Prepared_stmt_count on MYSQL

### ISSUE THREAD

**Issue by rasberrylasagna** [prisma/prisma#6872] opened 2021-04-30 16:51 UTC
## Bug description
Hey guys, I hope you all are doing well!

I'm running prisma @ 2.14 on MySQL, and after updating to and trying multiple versions (2.18, 2.20.1, 2.21.1), I'm running into issues where my Prepared_stmt_count global MySQL variable is increased by a huge factor compared to 2.14, which leads to me hitting the MAX_PREPARED_STATEMENTS limit. It seems like there is a difference in behavior of these prepared statements from 2.14 and onwards.

Just to reiterate, this is not a problem on 2.14, and was I wondering if there was anything I could do to get the old behavior back on a newer version.

Thank you!

## How to reproduce

I'm running this on a production kube deployment, so I'm unsure what specific queries may be triggering this, but I do know that 2.14 and previous never had this behavior

1. Be on similar env ?
2. Use normally (create/update/delete) (many)

## Expected behavior
Expect the Prepared_stmt_count to stay low, this is the current behavior on 2.14.

![image](https://user-images.githubusercontent.com/62729455/116726524-b5574d80-a9e3-11eb-8152-18aadd7ba6d9.png)

## Actual behavior
Prepared statement count balloons, and stays that way for a long enough time to where my set MAX_PREPARED_STMT_COUNT gets triggered and hangs the db. Note that the actual value in prod gets to 64000+.

![Screen Shot 2021-04-22 at 11 39 35 AM](https://user-images.githubusercontent.com/62729455/116726434-8fca4400-a9e3-11eb-9aaa-af305625623d.png)
## Environment & setup

- OS: Mac / Ubuntu
- Database: MySQL 8.0.21
- Node.js version: 12.16.1
- Prisma version: Tested on 2.17, 2.18, 2.20.x, 2.21.x

```
prisma               : 2.17.0
@prisma/client       : 2.17.0
Current platform     : darwin
Query Engine         : query-engine 3c463ebd78b1d21d8fdacdd27899e280cf686223 (at node_modules/@prisma/engines/query-engine-darwin)
Migration Engine     : migration-engine-cli 3c463ebd78b1d21d8fdacdd27899e280cf686223 (at node_modules/@prisma/engines/migration-engine-darwin)
Introspection Engine : introspection-core 3c463ebd78b1d21d8fdacdd27899e280cf686223 (at node_modules/@prisma/engines/introspection-engine-darwin)
Format Binary        : prisma-fmt 3c463ebd78b1d21d8fdacdd27899e280cf686223 (at node_modules/@prisma/engines/prisma-fmt-darwin)
Studio               : 0.353.0
```

**Comment by janpio** [comment] 2021-04-30 17:29
Interesting, I was not aware there is a limit on the # of prepared statements. What does the error/crash look like?

**Comment by rasberrylasagna** [comment] 2021-04-30 17:45
> Interesting, I was not aware there is a limit on the # of prepared statements. After 2.14 we probably changed the usage and behavior of queries. We most probably did not consider this limitation yet, or did not expect it to be relevant.
> 
> Is this limit per connection or per server (restart)?
> What does the error/crash look like?

Hey there!

I actually had no idea it was a thing either until I ran into this.

It's a per server limit, that can be potentially fixed by raising the limit (a global var in MySQL), but I didn't know if this was a symptom of something bigger and didn't want to band-aid something that may continue getting (much) bigger.

So the "normal" behavior (as of 2.14) was that the prepared statement count rises gradually through use, and quickly resets itself back down to <100 values.

Unfortunately I don't have a great error, but this is a snippet of it.

```
 INFO - [ERROR_LOG] - Message: Error occurred during query execution:; ConnectorError(ConnectorError { user_facing_error: None, kind: QueryError(Server(ServerError { code: 1461, message: "Can\'t create more than max_prepared_stmt_count statements (current value: 16382)", state: "42000" })) });
```

This would lead to huge drops in coverage as no queries can go through, effectively halting all traffic.

**Comment by janpio** [comment] 2021-04-30 18:11
Ok, it is a per server limit but I think the prepared statements are held by connection - so "rotating" the connections could probably help. You could do so by getting a new `PrismaClient` instance - depending on your application that might be as simple as restarting, or maybe writing some logic that every x hours a new `prisma` is created and used (and the old calls `prisma.$disconnect()` first). 

There is nothing really in the 2.15 release notes that pop out to me: https://github.com/prisma/prisma/releases/tag/2.15.0

Can you tell us a bit more about the queries your application is running?
How many connections to the database are open at any time?
How many app servers? Prisma connection_limit (/pool size)? Serverless?

**Comment by rasberrylasagna** [comment] 2021-04-30 18:26
> Ok, it is a per server limit but I think the prepared statements are held by connection - so "rotating" the connections could probably help. You could do so by getting a new `PrismaClient` instance - depending on your application that might be as simple as restarting, or maybe writing some logic that every x hours a new `prisma` is created and used (and the old calls `prisma.$disconnect()` first).
> 
> There is nothing really in the 2.15 release notes that pop out to me: https://github.com/prisma/prisma/releases/tag/2.15.0
> 
> Can you tell us a bit more about the queries your application is running?
> How many connections to the database are open at any time?
> How many app servers? Prisma connection_limit (/pool size)? Serverless?

That's fair. I'm happy to adapt and implement workarounds if the changes here are actually intended / a necessary side effect.

And understood. Before continuing, I'm actually just going to verify and make sure that 2.15 breaks it or if it's a later version to potentially make troubleshooting easier, and report back with findings.

I might have went straight to 2.17 to test a preview feature with groupBy/filter on relationals.

I'll test with 2.15 all the way up to my first confirmed version where I come across this issue.

Thanks again for the receptive help.

**Comment by janpio** [comment] 2021-04-30 18:56
These workarounds are of course only meant as temporary fixes to allow you to upgrade your Prisma version - we will obviously still try to understand and fix this as soon as possible. Right now we are a bit lost though as first manual reproductions did not show an increasing prepared statement count.

**Comment by rasberrylasagna** [comment] 2021-05-06 10:34
> These workarounds are of course only meant as temporary fixes to allow you to upgrade your Prisma version - we will obviously still try to understand and fix this as soon as possible. Right now we are a bit lost though as first manual reproductions did not show an increasing prepared statement count.

Ahh understood. Much appreciated.
The results from my findings is that 2.15 is indeed where the issue starts.

It is a GQL based backend that handles all of the traffic for a production deployment, so it runs about 6 pods that use prisma.

I don't think we do anything special with our prisma deployment, we strictly just use the client feature (no migrate etc) and we use all the basic CRUD functionality, as well as groupBy/aggregate queries. We have used default config for connection limit/pool size (didn't edit it). We also utilize the basic dataloader as implemented here: https://github.com/graphql/dataloader for most of our nested gql resolvers. 

Regarding to the things that connect to the DB, there are other things that connect to the database as well, so that bumps the total number up to 10, with between 40-55 simultaneous connections. There are no serverless access to the db.

Thank you!

**Comment by Simskii** [comment] 2021-05-12 07:53
We migrated from Prisma 1 to prisma 2.20 yesterday and came across this issue aswell.
We had our app running for about 20 minutes until we hit the prepared statement limit.

However if we downgrade to 2.14 it works like expected and the prepared statements keeps reseting and we do not hit the limit.

**Comment by olif** [comment] 2021-05-12 09:17
We have the same issue, the `Prepared_stmt_count` gets exhausted and reaches the `max_prepared_stmt_count` limit after a while. The `prepared_stmt_count` is monotonically increasing which means that this limit will finally be reached regardless of load and/or number of connections.

From what I can tell, it seems like the connection-pooling did not work in `prisma 2.14` which meant that new connections where spawned and olds ones closed. When the old connections where closed, the prepared statements belonging to that connection/session where dropped by MySql.

**Comment by janpio** [comment] 2021-05-12 09:23
Thanks, we will look into this soon.

**Comment by ericluwj** [comment] 2021-05-18 01:28
Also facing this same issue with prisma `2.21.0`

**Comment by Simskii** [comment] 2021-05-25 13:23
When is a fix for this planned?
We are currently stuck on 2.14 for the moment.

**Comment by pantharshit00** [comment] 2021-05-25 15:39
I am unable to reproduce this with `2.23`. I also tried with `2.21.1` and `2.14`. I ran a full 15 min load test with k6 and hit all the endpoints from this example: https://github.com/prisma/prisma-examples/tree/latest/typescript/rest-express

Here are the results that I am getting:

![image](https://user-images.githubusercontent.com/22195362/119526929-75467900-bd9d-11eb-938c-6f77d5488b59.png)

Can anyone share a more concrete reproduction?

**Comment by olif** [comment] 2021-05-26 11:07
The problem is that prisma is using prepared statements when making the request to the mysql db and never drops them. Mysql has a default limit of about 16000 prepared statements which put's an upper limit on how many _different_ prepared statements are allowed to be used globally for the db engine.

For instance, when querying the `/post/:id` endpoint the resulting parameterized query is
```
prisma:query SELECT `db`.`Post`.`id`, `db`.`Post`.`createdAt`, `db`.`Post`.`updatedAt`, `db`.`Post`.`title`, `db`.`Post`.`content`, `db`.`Post`.`published`, `db`.`Post`.`viewCount`, `db`.`Post`.`authorId` FROM `db`.`Post` WHERE `db`.`Post`.`id` = ? LIMIT ? OFFSET ?
```

and it will be sent by the prisma engine to the database as a prepared statement. If the exact same query is run again but with other parameters the prepared statement will be reused by mysql. However, if the query is slightly modified, for instance by adding a new statement in the `WHERE` clause, it will be cached by mysql as a new prepared statement.

The prepared statements belongs to the session/connection so if we have multiple instances of the same app and also a connection pool, each session/connection will have their prepared statements cached and these statements will no be dropped until the connection is closed.

This means that the overall number of _different_ queries that an application can have is limited to `16000/(nr of app instances * size of connection pool)`.

To make things worse, prepared statements will be created for each size of parameters of an IN statement. For instance, this handler:
```
app.get(`/posts`, async(req, res) => {
  const queryParams = req.query
  const ids = queryParams.ids as string[]
  const post = await prisma.post.findMany({
    where: {
      id: {
        in: ids.map(x => Number(x))
      }
    }
  })

  res.json(post)
})
```
will issue a new prepared statement for every number of provided ids.

```
$> curl 'localhost:3000/posts?ids[]=1'

SELECT `db`.`Post`.`id`, `db`.`Post`.`createdAt`, `db`.`Post`.`updatedAt`, `db`.`Post`.`title`, `db`.`Post`.`content`, `db`.`Post`.`published`, `db`.`Post`.`viewCount`, `db`.`Post`.`authorId` FROM `db`.`Post` WHERE `db`.`Post`.`id` IN (?)

Prepared_stmt_count=1
```

```
$> curl 'localhost:3000/posts?ids[]=1&ids[]=2'

SELECT `db`.`Post`.`id`, `db`.`Post`.`createdAt`, `db`.`Post`.`updatedAt`, `db`.`Post`.`title`, `db`.`Post`.`content`, `db`.`Post`.`published`, `db`.`Post`.`viewCount`, `db`.`Post`.`authorId` FROM `db`.`Post` WHERE `db`.`Post`.`id` IN (?,?)

Prepared_stmt_count=2
```

which further reduces the number of queries possible in the application since they are treated as different prepared statements.

As I said earlier, the reason this problem arises in versions of prisma > 2.14 is that the connection pool did not work in earlier versions which resulted in a new connection per request (which then dropped the associated prepared statements).

I don't know if I would classify this as a bug but since we don't have control over which queries are sent as prepared statements or not it has a severe negative impact on our scaling possibilities. Also, since `IN` clauses also are sent as prepared_statements it is hard to determine an upper bound that is guaranteed to cover the `Prepared_stmt_count`.

**Comment by janpio** [comment] 2021-05-26 15:08
Yes, this is a clear bug as it impact your ability to use Prisma - and we want you to be able to use Prisma 😄 

Your explanation makes a lot of sense, can you help us craft a reproduction app that is optimally set up to reproduce the hitting the limit? We always want to have these before we hand issues like this one over to an Engineer. It will also allow us to test and evaluate quick fixes and workarounds (e.g. a middleware to catch this error, that then instantly cycles the connections somehow and so on). That would be _very_ helpful.

**Comment by olif** [comment] 2021-05-27 07:18
I have forked the prisma-examples repo and added repro instructions together with some utilities to demonstrate the issue. The easiest way I came up with was to lower the `max_prepared_stmt_count` so that you can reproduce the issue on a smaller scale. The main issue is as I said that the prepared statement cache never is released so the only difference by having a larger value on `max_prepared_stmt_count` is that it will take much longer time until the limit eventually is reached, i.e it is a scaling issue.

https://github.com/Voady/prisma-examples/tree/latest/typescript/rest-express

**Comment by janpio** [comment] 2021-05-28 13:50
Thanks, @pantharshit00 will take another look at this reproduction. If he can reproduce, we will try some instant workarounds and kick of the work on fixing this properly (unclear to me how this _really_ would look like to be honest - how do other ORMs do this?).

**Comment by pantharshit00** [comment] 2021-05-28 20:36
I wasn't able to reliably reproduce and I was only able to reproduce after I added some concurrency but I still think we should review our cache implementation.

![image](https://user-images.githubusercontent.com/22195362/120039409-7805d000-c022-11eb-95f9-53d6ddd1d214.png)

cc @pimeys

**Comment by pimeys** [comment] 2021-05-28 20:50
We should maybe also not do those large IN statements and instead join in the database.

Caching is handled by mysql_async, but I think the bigger culprit is that we just run way too many different queries. The limit is quite large and we still hit it...

**Comment by janpio** [comment] 2021-05-28 22:39
What experience should we be expecting in the case of a low limit @olif? I honestly do not know how we should decide to "clean" a connection without having to read the config value first and then actively monitor the number of executed queries and so on.

**Comment by olif** [comment] 2021-05-31 07:02
So I investigated this a bit further and I think the problem is that the db-session is not reseted when picking a connection from the pool. I can't see any reason to let `prepared statements` live longer than a single session.

So my proposal to fix the problem is to issue the [COM_RESET_CONNECTION](https://dev.mysql.com/doc/dev/mysql-server/8.0.11/page_protocol_com_reset_connection.html) CMD before returning a connection from the pool. This is perhaps a driver issue (not sure if prisma or the underlying driver handles the pool).

Trying to monitor the queries seems fragile to me.

**Comment by pimeys** [comment] 2021-05-31 07:06
The pool and the driver are separate libraries and do not hold a way to communicate between each other. I doubt we get a pull request through; you definitely want to reuse the statements between different users for better performance.

**Comment by olif** [comment] 2021-05-31 08:02
@pimeys I thought the rationale behind using prepared statements in Prisma was to prevent sql-injections and not as a performance booster? 

Prepared statements only offer significant performance benefits when running the same command many many times on the same connection. Since the commands/statements are not correlated with a connection by the connection pool, the performance benefits when reusing statements are _eventual_ at the cost of having a monotonically increasing cache which in our environment gives us around 20 minutes before the cache is saturated (default `max_pre_stmt_count`).

From that I can tell, the usual way to solve this is to clear the session cache when returning a connection from the pool.

As it is now, we are running Prisma 2.14 without any possibility to upgrade until this issue is resolved.

**Comment by pimeys** [comment] 2021-05-31 08:42
@olif would it help if we'd provide you an ability to control the statement cache size? I think the current default (1000) is too large, but you should test this param in your use if you find something that helps. I'm also considering lowering the cache to a more reasonable 32 statements.

https://github.com/prisma/quaint/pull/296 please read the code to see how it works, we still have time to get this to 2.24.0.

**Comment by olif** [comment] 2021-05-31 08:52
@pimeys Haha I was just around digging in the quaint source code. Yes it would definitely help having a way to control the cache-size if it gets reflected in the db-server. What is the behaviour when reaching the limit? Is the connection resetted then?

**Comment by pimeys** [comment] 2021-05-31 08:59
I just read the source code of our mysql crate, and it uses LRU + closes statements when they're dropped.

https://github.com/blackbeam/mysql_async/blob/master/src/queryable/mod.rs#L119-L129

Meaning the least used statement gets dropped. If off, it will not store statements.

**Comment by pimeys** [comment] 2021-05-31 09:03
This is a quick first fix, and the second fix is to not generate that many different queries: I'm looking at you, large IN statements. We have our own LRU for postgres, and there you can set `statement_cache_size=X`. I add the same param for MySQL too. If not set, defaults to 32. If set to `0`, turns the cache off.

**Comment by olif** [comment] 2021-05-31 09:07
Yeah, this would most probably solve our problems. Ping me when you have a prisma build available so I can try it out. Thank you for your patience and your help.

**Comment by pimeys** [comment] 2021-05-31 09:08
Tomorrow 2.24.0 will have it, maybe a dev later today, but I'm having a terribly busy day so I doubt I have time to really test and ping :)

**Comment by pimeys** [comment] 2021-05-31 09:25
I set that PR to close this issue. Please reopen if it doesn't fix it, possibly before Wednesday so we can candidate it to the normal sprint schedule.

**Comment by janpio** [comment] 2021-05-31 11:18
> and the second fix is to not generate that many different queries: I'm looking at you, large IN statements.

Please open a new issue about this @pimeys. This might the source of this problem, but is fundamentally not related to _this_ problem here. Even if you do that, there is still a way to get into _this_ situation here.



> I add the same param for MySQL too. If not set, defaults to 32. If set to `0`, turns the cache off.

What was the previous behavior?

**Comment by pimeys** [comment] 2021-05-31 11:20
> > and the second fix is to not generate that many different queries: I'm looking at you, large IN statements.
> 
> Please open a new issue about this @pimeys. This might the source of this problem, but is fundamentally not related to _this_ problem here. Even if you do that, there is still a way to get into _this_ situation here.

https://github.com/prisma/prisma-engines/issues/1514

> 
> > I add the same param for MySQL too. If not set, defaults to 32. If set to `0`, turns the cache off.
> 
> What was the previous behavior?

1000, which is definitely way too much.

**Comment by janpio** [comment] 2021-05-31 11:52
@pantharshit00 We need a better and confirmed reproduction of the problem actual users (see above) are reporting, so we can test any implementation on our side to make sure it indeed improves the behavior. The problem is not that we do create prepared statements, but that they are never released to make space. Right now it looks like the number will always only increase for them.

@rasberrylasagna and @olif, you were reporting Prisma hitting _much_ higher numbers than the default of 1000 prepared statements per connection. How many server are you running? How many connections are these servers using? We need to double check the math here if this could really be the reason for this.

**Comment by olif** [comment] 2021-05-31 12:38
@janpio In our prod setup (k8s) we have around 8 node instances and 6-8 connections per instance/pool. If the current default cache-stmt limit is set to 1000 it will result in ~ 50,000 prepared statements to compare with the default in mysql 5.7 of 16382.

**Comment by pimeys** [comment] 2021-05-31 12:42
I can replicate this. It's not because of LRU.

Steps:

```prisma
datasource chinook {
  provider = "mysql"
  url      = "mysql://root:prisma@localhost:3308/prisma?statement_cache_size=0"
}

model Album {
  id       Int     @id @default(autoincrement())
  Title    String  @default("TestDefaultTitle")
}
```
(doesn't really matter the dm). Execute query engine http bridge, and then run:
```
#!/bin/sh

while true
do
	curl 'http://localhost:4466/' -H 'User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:88.0) Gecko/20100101 Firefox/88.0' -H 'Accept: */*' -H 'Accept-Language: en-US,en;q=0.5' --compressed -H 'Referer: http://localhost:4466/' -H 'content-type: application/json' -H 'Origin: http://localhost:4466' -H 'DNT: 1' -H 'Connection: keep-alive' --data-raw '{"operationName":null,"variables":{},"query":"mutation {\n  queryRaw(query: \"SELECT 1\")\n}\n"}'
done
```
This will eat up all statements and crash eventually.

**Comment by pimeys** [comment] 2021-05-31 14:19
So, this is a bug in the mysql library we use. Their LRU leaks statements, and I need to probably fix it and do a PR for them.

Meanwhile, for the next release, I'm introducing this parameter `statement_cache_size`. By default it's 1000 and this is a reason you're probably the first one that gets this problem. If you reach this limit, it starts dropping queries, replacing them with new ones. This drop doesn't actually clean them from the database, meaning when the cache gets full, every subsequent query will leak one from the cache. Eventually you hit the hard limit and crash.

I'd suggest, if I don't get a proper fix through to the library today (which I highly suspect), that you try to set this parameter to something like 5000 or 10000 until we get the leak PR through to this crate.

**Comment by janpio** [comment] 2021-05-31 16:54
That would also explain why the reported numbers are so much higher than a possible `server x connections x 1000`  could explain 👍

**Comment by rasberrylasagna** [comment] 2021-05-31 17:52
> @rasberrylasagna and @olif, you were reporting Prisma hitting _much_ higher numbers than the default of 1000 prepared statements per connection. How many server are you running? How many connections are these servers using? We need to double check the math here if this could really be the reason for this.

Although you guys have figured it out, I'm just confirming, we were on 3-6 instances on two separate environments with similar sized pools as olif. We were hitting 60k+ prepared statements on our env with 6 nodes.

**Comment by pimeys** [comment] 2021-06-02 07:03
I've been able to reproduce this when we set the driver cache size to zero, but never when the cache is on. It's a good chance there is a bug in the driver, so for the next step we now try the following:

- Disable the driver cache
- Use our own LRU that we use in our PostgreSQL connector
- Handle statement drops manually

Today or early next week there will be a dev version available. Would be great if one of you having the problems would test it out.

**Comment by pimeys** [comment] 2021-06-03 12:28
Hey @rasberrylasagna and @olif, could you test the development build `prisma@2.25.0-dev.9` to see if the problem still exists. You can try it with default settings, and by adding `statement_cache_size=N` to the connection string, where N is the preferred maximum number of statements to store in a connection (multiplied by the pool size). Set that to zero to disable it, the default value is for legacy reasons 1000.

**Comment by olif** [comment] 2021-06-08 06:32
Hi, sorry for the late response.

I have tested the `prisma@2.25.0-dev.9` locally and now it seems to work.

First I tried it with `statement_cache_size=20` and `connection_limit=1` and the `Prepared_stmt_count` was below 20, then i tried it with `statement_cache_size=0` and then no statements where cached. I also tried it out with the `prisma@2.24.0` version to confirm that the issue was there.

Good work!

**Comment by rasberrylasagna** [comment] 2021-06-08 18:05
Confirming this, wasn't able to repro. Thanks again Jan & Prisma Team!

**Comment by janpio** [comment] 2021-06-08 19:25
@pimeys did all the work - I just made him take a look at this after your description and analysis. Thanks for that, we made Prisma better for everyone (and actually fixed quite a nasty bug).

Now only to figure out what we do with that crazy previous default of 1000... Does not seem like a good idea in hindsight 🤣 What do you think a reasonable number would be?

**Comment by rasberrylasagna** [comment] 2021-06-09 16:14
> @pimeys did all the work - I just made him take a look at this after your description and analysis. Thanks for that, we made Prisma better for everyone (and actually fixed quite a nasty bug).
> 
> Now only to figure out what we do with that crazy previous default of 1000... Does not seem like a good idea in hindsight 🤣 What do you think a reasonable number would be?

Maybe not ...🤣. 

How about the default of mysql_async (32)?

**Comment by pimeys** [comment] 2021-06-17 13:47
Looks like this is fixed then :)

**Closed by pimeys** 2021-06-17 13:47 UTC
Labels: bug/2-confirmed, kind/bug, team/client, topic: core query optimization, topic: mysql, topic: performance

**Comment by pimeys** [comment] 2021-06-17 14:10
Yes

**Comment by omar-dulaimi** [comment] 2021-07-10 16:12
Hey @pimeys 
I'm facing the same issue with v2.19
But can't upgrade to 2.25(or 2.26) yet.

What value do you recommend for `max_prepared_stmt_count` parameter?

**Comment by omar-dulaimi** [comment] 2021-07-10 16:13
Also, I don't see this fix part of 2.25 release logs.

**Comment by omar-dulaimi** [comment] 2021-07-10 16:21
> Now only to figure out what we do with that crazy previous default of 1000... Does not seem like a good idea in hindsight rofl What do you think a reasonable number would be?
ProxySQL allocates 20 prepared statements per connection.

This explanation by it's author might help: 
https://github.com/sysown/proxysql/issues/1251#issuecomment-345514019

**Comment by janpio** [comment] 2021-07-11 09:17
2.25.0 added a configuration to change this:

> You can try it with default settings, and by adding `statement_cache_size=N` to the connection string, where N is the preferred maximum number of statements to store in a connection (multiplied by the pool size). Set that to zero to disable it, the default value is for legacy reasons 1000.

We might change the default value via https://github.com/prisma/prisma/issues/7727

**Comment by thomaschaaf** [comment] 2021-08-23 15:32
I actually believe this is actually caused by #8870

**Comment by cclaflin89** [comment] 2022-02-16 06:56
I'm also having the same max_prepared_stmt_count issue after setting `connection_pool_timeout=0` on prisma 3.7.0. Let me set `statement_cache_size=0` and see how it works.

**Comment by janpio** [comment] 2022-02-16 11:28
- `pool_timeout=0` is a way to make sure all the underlying errors have a chance to bubble up and not be swallowed by the timeout.
- `statement_cache_size=0` also is the big hammer, completely disabling the statement cache. You should do some math instead to see what value you can set here (per container/pod/server) that will still fit into your overall `prepared_stmt_count` limit of your MySQL installation.

**Comment by chanlito** [comment] 2022-04-05 04:14
We're currently experiencing this issue. Is there a recommended approach to handle this?

**Comment by janpio** [comment] 2022-04-05 10:56
That should be enough (if the # of applications/servers using Prisma Client, multiplicated by the configured cache size is lower than the limit). If you are still getting the error, you probably have more applications created prepared statements or something else is weird.

**Comment by ygoyal25** [comment] 2023-05-04 04:38
Hi,

We are still facing this issue for prisma version 4.10.1 the prepared_statement_count blows up on production. We have tried setting statement_cache_size value as well but it doesn't seem to work.
