### ISSUE TITLE
DateTime values wrongly typed in Prisma Client

### ISSUE THREAD

**Issue by huzaifahj** [prisma/prisma#12540] opened 2022-03-26 11:50 UTC
### Bug description

When using `start` as an ISO string in a date library, I get this error. There are no runtime errors as it's actually a string:
```ts
// Argument of type [see below] is not assignable to parameter of type 'string'
DateTime.fromISO(start)
```

#### Prisma schema
```prisma
start          DateTime
```

#### Lets `console.log(start)`
```
1970-01-01T00:00:00.000Z
```

#### TypeScript type for `start`
```ts
start: {
    toString: () => string;
    toDateString: () => string;
    toTimeString: () => string;
    toLocaleString: {
        (): string;
        (locales?: string | string[] | undefined, options?: Intl.DateTimeFormatOptions | undefined): string;
    };
    ... 40 more ...;
    [Symbol.toPrimitive]: {
        ...;
    };
}
```

### Prisma Version

```
prisma                  : 3.11.1
@prisma/client          : 3.11.1
Current platform        : debian-openssl-1.1.x
Query Engine (Node-API) : libquery-engine 1a2506facaf1a4727b7c26850735e88ec779dee9 (at node_modules/@prisma/engines/libquery_engine-debian-openssl-1.1.x.so.node)
Migration Engine        : migration-engine-cli 1a2506facaf1a4727b7c26850735e88ec779dee9 (at node_modules/@prisma/engines/migration-engine-debian-openssl-1.1.x)
Introspection Engine    : introspection-core 1a2506facaf1a4727b7c26850735e88ec779dee9 (at node_modules/@prisma/engines/introspection-engine-debian-openssl-1.1.x)
Format Binary           : prisma-fmt 1a2506facaf1a4727b7c26850735e88ec779dee9 (at node_modules/@prisma/engines/prisma-fmt-debian-openssl-1.1.x)
Default Engines Hash    : 1a2506facaf1a4727b7c26850735e88ec779dee9
Studio                  : 0.458.0
Preview Features        : fullTextSearch
```

**Comment by marc-on-github** [comment] 2022-03-31 18:08
I just have the same problem

**Comment by huzaifahj** [comment] 2022-03-31 18:28
Temporary workaround: 
```ts
DateTime.fromISO(start as unknown as string)
```

**Comment by huzaifahj** [comment] 2022-04-11 12:59
@janpio Any update on this?

**Comment by ekerik220** [comment] 2022-04-13 04:12
Same issue here. DateTime fields are being cast as Date in typescript, but they're actually a string. It should either actually be a Date object, or be typed as a string.

**Comment by aqrln** [comment] 2022-05-09 12:13
I can't reproduce it neither with latest Prisma nor with 3.11.1, I get the proper Date objects and not strings.

Could you please provide more information for reproduction (minimal schema, which database you use, and which Prisma method you use for querying the database) or, ideally, a clonable repo?

This sounds like a bad bug and I'd like to get it fixed, but unfortunately there's not enough context in this issue.

**Comment by aqrln** [comment] 2022-05-11 07:34
@ekerik220 thank you! I'll take a look.

**Comment by aqrln** [comment] 2022-05-11 14:12
@ekerik220 in your case Prisma returns a Date. It is then lost and converted to a string due to serialization to JSON by Remix. You can see what's happening by adding some logs on the server side as well.

Logs:

```
createdAt type in getNote: object
createdAt instanceof Date: true
createdAt data type in component: string
```

Diff:

```diff
diff --git a/app/models/note.server.ts b/app/models/note.server.ts
index ba56b53..4f23cc0 100644
--- a/app/models/note.server.ts
+++ b/app/models/note.server.ts
@@ -4,15 +4,18 @@ import { prisma } from "~/db.server";
 
 export type { Note } from "@prisma/client";
 
-export function getNote({
+export async function getNote({
   id,
   userId,
 }: Pick<Note, "id"> & {
   userId: User["id"];
 }) {
-  return prisma.note.findFirst({
+  const note = await prisma.note.findFirst({
     where: { id, userId },
   });
+  console.log("createdAt type in getNote:", typeof note?.createdAt);
+  console.log("createdAt instanceof Date:", note?.createdAt instanceof Date);
+  return note;
 }
 
 export function getNoteListItems({ userId }: { userId: User["id"] }) {
diff --git a/app/routes/notes/$noteId.tsx b/app/routes/notes/$noteId.tsx
index b326f37..da07201 100644
--- a/app/routes/notes/$noteId.tsx
+++ b/app/routes/notes/$noteId.tsx
@@ -36,7 +36,7 @@ export default function NoteDetailsPage() {
   const data = useLoaderData() as LoaderData;
 
   // Typescript says createdAt is a Date, but the console log says it's a string.
-  console.log("createdAt data type:", typeof data.note.createdAt);
+  console.log("createdAt data type in component:", typeof data.note.createdAt);
 
   return (
     <div>
```

**Comment by ekerik220** [comment] 2022-05-12 03:49
Ah, of course! I'm so used to working with unix timestamps for dates from the backend. Sorry for the false alarm!

On a related note, I really love how with Prisma we can just write @default (now()) and @updatedAt for DateTimes. I don't suppose it's possible to do something similar for unix timestamps...?

**Comment by aqrln** [comment] 2022-05-12 12:05
Yeah, I don't think there's a built-in way to do that, unfortunately. Potentially something usable might be possible with a custom middleware though.

**Comment by aqrln** [comment] 2022-05-24 12:39
I'll close the issue for now to reduce the backlog. Don't hesitate to reopen it or submit a new issue if anyone is still facing it!

**Closed by aqrln** 2022-05-24 12:39 UTC
Labels: bug/0-unknown, kind/bug, topic: client types, topic: dates / DateTime, team/client, topic: remix
