### ISSUE TITLE
Document the update usage properly / Fix the usage

### ISSUE THREAD

**Issue by Sytten** [prisma/prisma#2248] opened 2020-04-20 22:36 UTC
## Problem
Currently the typing says that you can `null` or `undefined` to pretty much every field, but that is not true. Typing should better and the documentation should explain the behaviour difference between `null` and `undefined`. Finally, the array don't allow a `set` of undefined.

## Solution
- Document the default behaviour of undefined which is to ignore the field in the update (stays at the same value).
- If a field is not nullable, it should not be able to the set it to null (currently all the fields are `U | null | undefined`.
- Fix the the fact that when trying to use `set` on an array, it will not accept undefined like (it should to simplify the life of developers doing CRUD). This would eliminate the need for:
```typescript
if (myArray) {
  data.myArray = {
    set: myArray
  };
}
```

**Comment by Sytten** [comment] 2020-04-21 00:44
I traced by the typing issue to a limitation of GraphQL from which the DMMF seems to inherit. basically there is not distinction between an `undefined` and a `null`. Thus the engine returns `is_required` at `false` to allow an update that would not contain the field, but it does not return anything to specify the nullability of said field. The fix requires a change to the protocol to include a new flag `is_nullable`.

**Comment by pantharshit00** [comment] 2020-04-21 04:05
Right now the behaviour is that any value that is `undefined` will be removed from the selection set and `null` is being treated as a empty nil value.

null vs undefined is something that we have discussed internally and it is ongoing product work. I think we need to discuss this further before making a change in the DMMF.

**Comment by dpetrick** [comment] 2020-04-21 07:43
Duplicate of https://github.com/prisma/prisma-engines/issues/678. This is known and is scheduled to be tackled by me soon.

**Closed** 2020-04-21 07:43 UTC
Labels: kind/discussion, topic: dmmf
