### ISSUE TITLE
Break up generated client files into multiple smaller files

### ISSUE THREAD

**Issue by blevine** [prisma/prisma#9071] opened 2021-09-01 18:47 UTC
I have prisma-client-js/index.d.ts that is about 5Megs and associated index.js that is 8Megs. Some IDEs encounter performance problems when dealing with files of that size.  For example, IntelliJ IDEA takes 6 seconds to open the index.d.ts file and uses up quite a bit of memory. Admittedly, an IDE's inability to handle a large file is the IDE's bug, not yours.  However, it would still enhance the developer experience if these files were broken up into multiple files. I was thinking a file per-model might make sense.

**Comment by pantharshit00** [comment] 2021-09-02 07:56
Hi,

Thanks for reporting this! It has already been reported before, so I am going to close this as a duplicate of https://github.com/prisma/prisma/issues/4807

**Closed by pantharshit00** 2021-09-02 07:56 UTC
