### ISSUE TITLE
Could not find a declaration file for module  '@prisma/client/runtime/index'

### ISSUE THREAD

**Issue by dortzur** [prisma/prisma#14337] opened 2022-07-16 19:34 UTC
### Bug description

Could not find a declaration file for module '@prisma/client/runtime/index'. '/Users/dor-home/data/dev/stocky-server/node_modules/@prisma/client/runtime/index.js' implicitly has an 'any' type.   If the '@prisma/client' package actually exposes this module, try adding a new declaration (.d.ts) file containing `declare module '@prisma/client/runtime/index';`

### How to reproduce

Happens to me in a project which import "join" and "sql" 
`import { join, sql } from '@prisma/client';`

### Expected behavior

project shouldn't fail

### Prisma information

``const toValues = (obj: Record<string, any>, keys: string[]) =>
  sql`(${join(keys.map((key) => obj[key]))})`;``

### Environment & setup

- OS: MacOS
- Database: PostgreSQL
- Node.js version: v18.6.0

### Prisma Version

```
4.0.0
```

**Comment by aqrln** [comment] 2022-07-18 14:29
There are two separate  problems that I can see here.

First of all, the import statement is not correct. `join` and `sql` functions don't exist at the top level of the module, they are defined in the `Prisma` namespace.

You can change the import to the following:

```ts
import { Prisma } from "@prisma/client";
```

and then either do

```ts
const { join, sql } = Prisma;
```

or change your function to

```ts
const toValues = (obj: Record<string, any>, keys: string[]) => Prisma.sql`(${Prisma.join(keys.map((key) => obj[key]))})`;
```

That said, has `import { join, sql } from '@prisma/client'` worked for you before? If yes, in which version of Prisma?

Secondly, the error message you get is unexpected and doesn't seem to be related to the previous problem. What would've been expected was if you got this:

```
error TS2305: Module '"@prisma/client"' has no exported member 'join'.
error TS2305: Module '"@prisma/client"' has no exported member 'sql'.
```

Instead, the error that you got looks like TypeScript couldn't find the runtime bundle. Is your project organized as a monorepo? Could you possibly make a minimal reproduction you could push to GitHub?

**Comment by garrensmith** [comment] 2022-07-28 12:55
I'm closing this, please open it again if the fix above doesn't fix it. 
Can you also confirm you have generated the client.

**Closed by garrensmith** 2022-07-28 12:55 UTC
Labels: bug/0-unknown, kind/bug, tech/typescript, team/client
