### ISSUE TITLE
Error in migration engine. Timed out during query execution. 

### ISSUE THREAD

**Issue by jkomyno** [prisma/prisma#15247] opened 2022-09-09 08:37 UTC
Command: `prisma db push`
Version: `4.3.1`
Binary Version: `c875e43600dfe042452e0b868f7a48b817b9640b`
Report: https://prisma-errors.netlify.app/report/14283 
OS: `x64 win32 10.0.22000`

**Comment by tomhoule** [comment] 2022-09-09 09:11
closing this as a duplicate of https://github.com/prisma/prisma/issues/15015

**Closed by tomhoule** 2022-09-09 09:11 UTC
Labels: bug/1-unconfirmed, kind/bug, topic: sqlite, topic: error reporting, team/schema
