### ISSUE TITLE
Unique constraint failed during `$transaction([deleteMany, createMany])`

### ISSUE THREAD

**Issue by eannam** [prisma/prisma#9678] opened 2021-10-08 11:08 UTC
### Bug description

I have a prisma transaction which first runs a `deleteMany` operations followed by a `createMany` operation.

However, occasionally the data in the `createMany` operation violates a unique constraint (a combination of two fields).

The application code should ensure that uniqueness is guaranteed in the data being passed and logging the actual data confirms there are no duplicates on the fields that the error indicates.

Is it possible that the `deleteMany` operation is not completing fully before the `createMany` begins? As there would be overlap across the data being removed and the data being created (relates to refreshing a user's feed).

My understanding is that each operation in a transaction is fully awaited before beginning the next but this is the only thing I can think of.

### Expected behavior

That the `deleteMany` operation completes fully before `createMany` begins and there is no unique constraint violation.

### Environment & setup

- OS: Ubuntu 18.04.5 LTS
- Database: PostgreSQL
- Node.js version: 12.22.6

### Prisma Version

```
prisma                  : 3.0.2
@prisma/client          : 3.0.2
Current platform        : debian-openssl-1.1.x
Query Engine (Node-API) : libquery-engine 2452cc6313d52b8b9a96999ac0e974d0aedf88db (at node_modules/@prisma/engines/libquery_engine-debian-openssl-1.1.x.so.node)
Migration Engine        : migration-engine-cli 2452cc6313d52b8b9a96999ac0e974d0aedf88db (at node_modules/@prisma/engines/migration-engine-debian-openssl-1.1.x)
Introspection Engine    : introspection-core 2452cc6313d52b8b9a96999ac0e974d0aedf88db (at node_modules/@prisma/engines/introspection-engine-debian-openssl-1.1.x)
Format Binary           : prisma-fmt 2452cc6313d52b8b9a96999ac0e974d0aedf88db (at node_modules/@prisma/engines/prisma-fmt-debian-openssl-1.1.x)
Default Engines Hash    : 2452cc6313d52b8b9a96999ac0e974d0aedf88db
Studio                  : 0.423.0
Preview Features        : fullTextSearch
```

**Comment by janpio** [comment] 2021-10-08 11:34
Can you share your code? Do you `await` both function calls?

**Comment by eannam** [comment] 2021-10-18 17:42
Following up here, I replaced the transaction with two individually awaited calls to the DB, i.e.

```    await prisma.playlistStack.deleteMany({ where: { playlistId } });
    await prisma.playlistStack.createMany({ data: playlistStackData });```

I am still occasionally getting the `Unique constraint failed on the fields: (`stackId`,`playlistId`)` error but there are no duplicates in the new data being created (I am sure of this since the operation succeeds on retrying.)

It seems totally random when this error is thrown. Is there any possibility that there is some sort fo race condition where the `deleteMany` does not fully complete before `createMany`, resulting in duplicates?

**Comment by colinricardo** [comment] 2021-10-18 22:40
I am also experiencing this issue

**Comment by Nassim-mesdour** [comment] 2022-06-06 21:48
Hello, i'm getting the same issue when i run seed on my db with `createMany`.
And i think it comes from the schema when adding `@default()`

```diff
model Organization {
  id           String   @id @default(uuid())
--licenceBasic Int?     @default(1) // fails with error : Unique constraint failed on the fields: (`licenceBasic`)
++licenceBasic Int?     // runs successfully
  name         String   @unique
  address      String?
  createdAt    DateTime @default(now())
  updatedAt    DateTime @updatedAt
}
```
hope this will help !

**Comment by Nassim-mesdour** [comment] 2022-06-08 21:36
@janpio as i was creating the issue, i figured out that it was not a bug, i just did not push new migration. my bad 🙏. i also deleted my previous comment to prevent confusion. Thank you

**Comment by NgocLe1001RP** [comment] 2022-07-06 02:56
I'm facing same issue. Can anyone resolve it please?

**Comment by alexboboc** [comment] 2022-07-10 23:44
Same here. Running on PostgreSQL with the following Prisma version:

```
prisma                  : 4.0.0
@prisma/client          : 4.0.0
Current platform        : darwin
Query Engine (Node-API) : libquery-engine da41d2bb3406da22087b849f0e911199ba4fbf11 (at node_modules/@prisma/engines/libquery_engine-darwin.dylib.node)
Migration Engine        : migration-engine-cli da41d2bb3406da22087b849f0e911199ba4fbf11 (at node_modules/@prisma/engines/migration-engine-darwin)
Introspection Engine    : introspection-core da41d2bb3406da22087b849f0e911199ba4fbf11 (at node_modules/@prisma/engines/introspection-engine-darwin)
Format Binary           : prisma-fmt da41d2bb3406da22087b849f0e911199ba4fbf11 (at node_modules/@prisma/engines/prisma-fmt-darwin)
Default Engines Hash    : da41d2bb3406da22087b849f0e911199ba4fbf11
Studio                  : 0.465.0
```

**Comment by alonbilu** [comment] 2022-07-14 14:48
Same here with psql as well.

**Comment by alonbilu** [comment] 2022-07-14 14:49
Seems to be related to this:
https://github.com/prisma/prisma/issues/3242

**Comment by janpio** [comment] 2022-08-23 16:14
Anyone have any good way to reproduce this? Is creating a minimal schema with 1 model, and then deleteing a few entries and recreating them later enough? Or are these models super big with many fields, or expensive via referential actions (so the database has to do things in the background when something got removed) or anything like that? Can someone share real world schemas and data that causes this?

**Comment by millsp** [comment] 2022-09-05 13:14
Internal discussion https://prisma-company.slack.com/archives/C040N0UADF0/p1662163795742029

**Comment by millsp** [comment] 2022-09-05 13:18
Reproduction https://github.com/prisma/prisma/pull/15162

**Comment by janpio** [comment] 2022-09-27 18:09
Hey, release 4.4.0 just added the tools to handle this better.

**But before we get into that, a bit of analysis.** I'll just quote from an internal document:

> Even though it sounds confusing at a first glance, this is expected behaviour with default isolation level on postgres and SQL Server — `ReadCommited`. This isolation level does not guarantee repeatable reads, so if another transaction got committed between `deleteMany` and `createMany` calls, currently running transaction might observe newly created rows.
> 
> Example:
> 
> 1. Suppose there are 2 transactions, running code above concurrently
> 2. TransactionA performs `deleteMany` operation and removes all rows that would cause a conflict
> 3. TransactionB performs `deleteMany` operation.
> 4. TransactionB performs `createMany` operation, creating a new set of rows.
> 5. TransactionB is committed
> 6. TransactionA performs `createMany` operation. Newly inserted rows conflicts with the rows TransactionB had committed previously.
> 
> Higher isolation level  – either `RepeatableRead` or `Serializable` – would’ve allowed to avoid this error.

So in a concurrent setup (with multiple requests at the same time) with the default isolation levels, it is expected that this can happen as you described above.

**And now how you probably want to handle this starting with Prisma 4.4.0:**

1. Use the new `isolationLevel` second parameter for `$transaction([...])` to change to the higher `Prisma.TransactionIsolationLevel.Serializable`. This will ensure that multiple concurrent or parallel transactions are really only commited as if they had been run serially (or throw an error otherwise) - no matter what the default setting of your database server is.
2. If a concurrent transaction is forced to throw such an error, it will be a `P2034` with the error message `Transaction failed due to a write conflict or a deadlock. Please retry your transaction`. That will allow you to explicitly handle that expect error case for higher isolation levels.

When you combine these two, you should easily be able to build a simple retry around your transaction that now uses the `Serializable` isolation level. For example (from our release notes):

```
import { Prisma, PrismaClient } from '@prisma/client'

const prisma = new PrismaClient()
async function main() {
  const MAX_RETRIES = 5
  let retries = 0;

  let result;
  while (retries < MAX_RETRIES) {
    try {
      result = await prisma.$transaction(
        [
          prisma.user.deleteMany({ where: { /**  args */ } }),
          prisma.post.createMany({ data: { /**  args */ } })
        ],
        {
          isolationLevel: Prisma.TransactionIsolationLevel.Serializable
        }
      )
    } catch (error) {
      if (error.code === 'P2034') {
        retries++
        continue
      }
      throw error
    }
  }
}
```

Please let us know if this works for you. I am going to close the issue for now, but if anything does not work as described please do not hesitate to comment on this issue or opoen a new one. Thanks!

**Closed by janpio** 2022-09-27 18:09 UTC
Labels: bug/2-confirmed, kind/bug, tech/engines, topic: transaction, team/client, topic: query race condition
