### ISSUE TITLE
PANIC: called `Option::unwrap()` on a `None` value in query-engine/core/src/query_document/parser.rs:250:87

### ISSUE THREAD

**Issue by Arman-Hosseini** [prisma/prisma#13048] opened 2022-04-28 07:27 UTC
Hi Prisma Team! My Prisma Client just crashed. This is the report:
## Versions

| Name            | Version            |
|-----------------|--------------------|
| Node            | v12.22.11          | 
| OS              | debian-openssl-1.1.x|
| Prisma Client   | 3.8.0              |
| Query Engine    | 0.1.0              |
| Database        | postgresql         |

## 
I used this value `99999999999999999999999` for my target variable which has the type `number` and the server crashed :)

**Comment by janpio** [comment] 2022-04-28 07:36
Looks like a duplicate of https://github.com/prisma/prisma/issues/10586

**Closed by janpio** 2022-04-28 07:36 UTC
