### ISSUE TITLE
2.6.0 Broke some of my update queries

### ISSUE THREAD

**Issue by fchu** [prisma/prisma#3497] opened 2020-09-01 23:59 UTC
## Bug description

Upgrading to 2.6.0 required me to rewrite my upsert/update queries.
After doing so, engine will complain about missing fields while compile-time check doesn't.

## How to reproduce

0. Setup:
```prisma
model User {
  id         Int      @default(autoincrement()) @id
  externalId String   @default(dbgenerated())

  displayName String
  imageUrl    String?

  source  SourceInfo?
}

model SourceInfo {
  baseUrl String @id

  user   User? @relation(fields: [userId], references: [id])
  userId Int?  @unique
}
```

Queries:
```ts
export const updateOne = async (
  userId: number,
  displayName: string,
  canonicalUrl: string,
  imageUrl: string | null) => {
  return prisma().user.update({
    where: {
      id: userId,
    },
    data: {
      displayName,
      imageUrl,
      source: {
        update: {
          baseUrl: canonicalUrl,  // [A]
        },
      },
    }
  });
};
```

1. Upgrade to 2.6.0 & generate client
```sh
npm install @prisma/client
npm install --save-dev @prisma/cli
npx prisma generate
```

2. Observe compilation error referring to line [A].
```
Type 'string' is not assignable to type 'StringFieldUpdateOperationsInput | undefined'
```

3. Fix compilation to replace line [A] as follows:
```ts
          baseUrl: canonicalUrl,
```
to
```ts
          baseUrl: { set: canonicalUrl },
```

4. Get error when calling `updateOne`:
```
Missing a required value at `Mutation.updateOneUser.data.UserUpdateInput.imageUrl`
```

## Expected behavior
1. Ideally update should not introduce unannounced breaking changes
2. Update should succeed, like it did on 2.5.1

## Prisma information

2.5.1 to 2.6.0

## Environment & setup

- OS: macOS 10.15.6
- Database: PostgreSQL
- Node.js version: v12.16.2
- Prisma version:
```
@prisma/cli          : 2.6.0
Current platform     : darwin
Query Engine         : query-engine 650b5d0348ec38ae61e1e7db69bb54808418ede4 (at node_modules/@prisma/cli/query-engine-darwin)
Migration Engine     : migration-engine-cli 650b5d0348ec38ae61e1e7db69bb54808418ede4 (at node_modules/@prisma/cli/migration-engine-darwin)
Introspection Engine : introspection-core 650b5d0348ec38ae61e1e7db69bb54808418ede4 (at node_modules/@prisma/cli/introspection-engine-darwin)
Format Binary        : prisma-fmt 650b5d0348ec38ae61e1e7db69bb54808418ede4 (at node_modules/@prisma/cli/prisma-fmt-darwin)
Studio               : 0.272.0
```

**Comment by janpio** [comment] 2020-09-02 00:10
Thanks for reporting this, certainly unexpected. Someone will look into this as soon as possible. Looks like an unwanted regression on first sight.

**Comment by SharadKumar** [comment] 2020-09-02 02:13
Yes, I confirm... broke on my `Json?` column too... rolling back to `2.5.1` fixed them!

Schema:
```js
generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}
model Customer {
  id            String    @default(cuid()) @id
  email         String
  name          String?
  address       Json?
  timezone      String?
  createdAt     DateTime  @default(now()) @map(name: "created_at")
  updatedAt     DateTime  @default(now()) @map(name: "updated_at")
}
```

Mutation:
```js
const customer = await prisma.customer.update({
            data: {address},
           ...
          })
```

Error:
```
You've encountered a problem. 
[Invalid [1m`prisma.customer.update()`[
 invocation in[
[[webpack-internal:///./pages/api/profile.ts:57:52[[ Failed to validate the query `Error occurred during query validation & transformation: Mutation (object) ↳ updateOneCustomer (field) ↳ data (argument) ↳ CustomerUpdateInput (object) ↳ address (field) ↳ 
Value types mismatch. 
Have: String("{\"line1\":\"123\",\"unit\":\"\",\"city\":\"\",\"state\":\"\",\"pincode\":\"\"}"), 
want: Object((Weak))` at `.Mutation.updateOneCustomer.data.CustomerUpdateInput.address`

```

**Comment by pizzafox** [comment] 2020-09-02 07:42
Having (vaguely) similar errors after updating to 2.6.0 when updating a `DateTime` value called `MY_DATE_TIME_VALUE` in my model `MY_MODEL`:

```
Error while running command: Error: Error in query graph construction: QueryParserError(ObjectValidationError { object_name: "Mutation", inner: FieldValidationError { field_name: "updateOneMY_MODEL", inner: ArgumentValidationError { argument: "data", inner: ObjectValidationError { object_name: "MY_MODELUpdateInput", inner: FieldValidationError { field_name: "MY_DATE_TIME_VALUE", inner: ValueTypeMismatchError { have: String("2020-09-02T07:39:49.913Z"), want: Object((Weak)) } } } } } })
    at /srv/node_modules/@prisma/engine-core/dist/NodeEngine.js:879:1
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

**Comment by Jolg42** [comment] 2020-09-02 14:39
Thanks for the issue, we now have a fix coming soon, so I'll update you when you can try it 😃

**Comment by johhansantana** [comment] 2020-09-02 18:29
> Thanks for the issue, we now have a fix coming soon, so I'll update you when you can try it 😃

Is there any unreleased version that we can use in the meantime that fixes this issue?

**Comment by Jolg42** [comment] 2020-09-03 09:35
So we have a fix in our development build `2.6.1-dev.2` (not recommended for production usage) it will be part of the official `2.6.1` patch release soon.

**Comment by JuanM04** [comment] 2020-09-03 14:42
I updated Prisma to v2.6.1, removed my node-modules, run `prisma generate`, and the error persists

**Comment by JuanM04** [comment] 2020-09-03 15:11
The error is the same that @fchu reported: `Missing a required value at `Mutation.updateOneUser.data.UserUpdateInput.imageUrl``

The problem happens when I try (using the example above):
```js
prisma.user.update({
  where: {id: 1},
  data: { imageUrl: null }
})
```

Before 2.6.0, that was working, but now it isn't

**Comment by Jolg42** [comment] 2020-09-03 15:12
Thanks @JuanM04 we will investigate that!

**Comment by Jolg42** [comment] 2020-09-03 15:33
We have a reproduction and are working on a fix.

**Comment by jsbrain** [comment] 2020-09-03 20:13
Still not fixed on 2.6.1:

Related piece of schema:
```prisma
model User {
  id          String     @id @default(cuid())
  slackUser   SlackUser  @relation(fields: [slackUserId], references: [userId])
  slackUserId String     @unique
  binomUser   BinomUser? @relation(fields: [binomUserId], references: [id])
  binomUserId String?    @unique
  createdAt   DateTime   @default(now())
  updatedAt   DateTime   @updatedAt
}

model BinomUser {
  id             String               @id @default(cuid())
  apiKey         String               @unique
  trackerUrl     String
  user           User
  /// Traffic sources that have been configured and connected with Slack
  trafficSources BinomTrafficSource[]
  createdAt      DateTime             @default(now())
  updatedAt      DateTime             @updatedAt
}
```

Not working code:
```ts
import { PrismaClient, User } from '@prisma/client';

const prisma = new PrismaClient();

function notWorkingFunction(prismaUser: User) {
  const nums = [1, 2, 3];
  if (!prismaUser.binomUserId) return null;

  prisma.binomUser.update({
    where: { id: prismaUser.binomUserId }, // <- works
    data: {},
  });

  const p = nums.map(n => {
    return prisma.binomUser.update({
      where: { id: prismaUser.binomUserId }, // <- does not work ¯\_(ツ)_/¯
      data: {}, //^^^ Type 'string | null' is not assignable to type 'string | undefined'
    });
  });
}
```

<img width="889" alt="Screen Shot 2020-09-03 at 22 09 07" src="https://user-images.githubusercontent.com/20225909/92162473-837cef80-ee32-11ea-8853-b3280d400afc.png">

Hope that helps :)

**Comment by vadim-shilov** [comment] 2020-09-03 22:51
prisma 2.6.1
macOS 10.15.5
db sqlite
node 14.9.0

Mutation (object)
  ↳ upsertOneBook (field)
    ↳ update (argument)
      ↳ BookUpdateInput (object)
        ↳ availableDate (field)
          ↳ Value types mismatch. Have: String("2015-06-15T05:21:51.000Z"), want: Object((Weak))` at `.Mutation.upsertOneBook.update.BookUpdateInput.availableDate`
    at PrismaClientFetcher.request (/Users/vadim/Projects/middleware/node_modules/@prisma/client/runtime/index.js:1:228179)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async run (/Users/vadim/Projects/middleware/src/parsers/index.js:37:13)

**Comment by alan345** [comment] 2020-09-03 22:58
I guess it is related to https://github.com/prisma/prisma/issues/3512

**Comment by Jolg42** [comment] 2020-09-04 09:18
So we have a fix in our development build 2.6.2-dev.1 (not recommended for production usage) it will be part of the official 2.6.2 patch release soon.

**Comment by Jolg42** [comment] 2020-09-04 14:24
`2.6.2` is released 😃 

https://github.com/prisma/prisma/releases/tag/2.6.2

**Closed by Jolg42** 2020-09-04 14:24 UTC
Labels: bug/2-confirmed, kind/regression, team/typescript, topic: types

**Comment by kevrat** [comment] 2020-09-15 07:21
You guys forgot about upsert.
Same for upsert on 2.6.2 and nexus-plugin-prisma 0.18.2
My package.json:
```
  "dependencies": {
    "@nexus/schema": "^0.15.0",
    "apollo-server": "^2.17.0",
    "graphql-relay": "^0.6.0",
    "nexus-plugin-prisma": "^0.18.2"
  },
  "devDependencies": {
    "@types/graphql-relay": "^0.6.0",
    "ts-node-dev": "^1.0.0-pre.52",
    "typescript": "^4.0.2"
  },
  "resolutions": {
    "@prisma/cli": "^2.6.2",
    "@prisma/client": "^2.6.2"
  }
```

**Comment by pantharshit00** [comment] 2020-09-15 09:14
@kevrat 

Please open a new issue with a reproduction. I was unable to reproduce this. Also, make sure you ran `prisma generate` after upgrading

**Comment by kevrat** [comment] 2020-09-15 09:34
> @kevrat
> 
> Please open a new issue with a reproduction. I was unable to reproduce this. Also, make sure you ran `prisma generate` after upgrading

I think this is because I am using `prisma migrate`
So my complete command for deployment is:
```
prisma migrate save --name init --create-db --experimental  && prisma migrate up --auto-approve --create-db --experimental && prisma generate --schema='./prisma/schema.prisma
```

**Comment by kevrat** [comment] 2020-09-15 10:05
Anyone using `nexus-plugin-prisma`. it is not related to the prisma
https://github.com/graphql-nexus/nexus-plugin-prisma/issues/830

**Comment by redblue9771** [comment] 2021-02-01 02:27
in v2.15.0
`Expected value of type \"StringFieldUpdateOperationsInput\", found \"test\".`

**Comment by pantharshit00** [comment] 2021-02-01 11:28
@redblue9771 Please open a new issue about this with a minimal reproduction.
