### ISSUE TITLE
Yarn 2 can't find command `prisma2` after updating to 2.0.0-preview025

### ISSUE THREAD

**Issue by nnennajohn** [prisma/prisma#2013] opened 2020-03-30 22:51 UTC
## Bug description
On yarn berry, after updating to the latest 2.0.0-preview025, yarn can no longer find the command prisma2. Any suggestions as to why? Thank you.
 

## How to reproduce
Setup project with yarn 2. Install @prisma/cli@2.0.0-preview025, and attempt to run any command with prisma2.

## Expected behavior
This was working properly prior to updating to 2.0.0-preview025. Expect yarn to find command prisma2.

## Prisma information 
Any query

## Environment & setup
- OS: Mac OS
- Database: PostgreSQL
- Prisma version: @prisma/cli 2.0.0-preview025
- Node.js version: 12

<img width="1003" alt="Screen Shot 2020-03-30 at 3 28 16 PM" src="https://user-images.githubusercontent.com/1761197/77969294-40748a00-729e-11ea-958e-a7ba0683e3f0.png">

**Comment by Sm03leBr00t** [comment] 2020-03-31 09:33
Is it global installed?

**Comment by nnennajohn** [comment] 2020-03-31 17:02
@Sm03leBr00t , no. The docs recommended to install it locally.

**Comment by pantharshit00** [comment] 2020-03-31 17:14
I can reproduce this but we really haven't tested out prisma with yarn 2 so please also follow this issue: #1439

**Comment by nnennajohn** [comment] 2020-03-31 17:33
Ok @pantharshit00. Do I close this issue after following #1439? Thanks.

**Comment by Sm03leBr00t** [comment] 2020-03-31 17:39
Great to hear that your issue has been kinda resolved 👍 And @pantharshit00 what a Name 😂😂😂

**Comment by pantharshit00** [comment] 2020-03-31 17:51
> Ok @pantharshit00. Do I close this issue after following #1439? Thanks.

No, leave this open :)

**Comment by janpio** [comment] 2020-07-31 10:27
I am not actually closing this as a duplicate of https://github.com/prisma/prisma/issues/1439 - but really just because `preview`s is a long time ago and we will jsut make sure that it works with current version in the future.

Thanks for reporting @nnennajohn - and following https://github.com/prisma/prisma/issues/1439 should notify you of changes.

**Closed by janpio** 2020-07-31 10:27 UTC
Labels: bug/2-confirmed, kind/bug, status/needs-action, topic: cli

**Comment by nnennajohn** [comment] 2020-07-31 21:44
Thank you @janpio
