### ISSUE TITLE
Prisma generates DMMF with invalid type names

### ISSUE THREAD

**Issue by MichalLytek** [prisma/prisma#6150] opened 2021-03-17 15:07 UTC
## Bug description

When I use the default, implicit index name:

```prisma
model Category {
  name   String
  slug   String
  number Int

  @@unique([slug, number])
}
```

Prisma generates normal input type name, like `CategorySlugNumberCompoundUniqueInput`.

However, when I provide a custom one, which may contain some invalid JS characters (like `@@unique([slug, number], name: "slug.number")`), it generates input type and field name without sanitizing it:

![image](https://user-images.githubusercontent.com/10618781/111489065-1b408c00-873a-11eb-81f6-e74d1dba6cb2.png)

## How to reproduce

Run prisma generate when model unique index has own name with special characters.

## Expected behavior

Prisma should sanitize the name string or maybe even parse it by converting common cases like `snake_case` or `snake.case` to `SnakeCase`.

## Prisma information

```prisma
model Category {
  name   String
  slug   String
  number Int

  @@unique([slug, number], name: "slug.number")
}
```

## Environment & setup

- OS:  Windows 10 WSL2 @ Ubuntu 20.04
- Database:  PostgreSQL
- Node.js version:  15.8
- Prisma version:

```
prisma               : 2.19.0
@prisma/client       : 2.19.0
Current platform     : debian-openssl-1.1.x
Query Engine         : query-engine c1455d0b443d66b0d9db9bcb1bb9ee0d5bbc511d (at node_modules/@prisma/engines/query-engine-debian-openssl-1.1.x)
Migration Engine     : migration-engine-cli c1455d0b443d66b0d9db9bcb1bb9ee0d5bbc511d (at node_modules/@prisma/engines/migration-engine-debian-openssl-1.1.x)
Introspection Engine : introspection-core c1455d0b443d66b0d9db9bcb1bb9ee0d5bbc511d (at node_modules/@prisma/engines/introspection-engine-debian-openssl-1.1.x)
Format Binary        : prisma-fmt c1455d0b443d66b0d9db9bcb1bb9ee0d5bbc511d (at node_modules/@prisma/engines/prisma-fmt-debian-openssl-1.1.x)
Studio               : 0.358.0
Preview Features     : groupBy, createMany, orderByRelation
```

**Comment by Jolg42** [comment] 2021-03-17 16:40
Thanks for the nice report!

I think it's a duplicate of https://github.com/prisma/prisma/issues/3193

I will close and recommend to subscribe there, happy to reopen if needed 😃

**Closed by Jolg42** 2021-03-17 16:40 UTC
