### ISSUE TITLE
PANIC: called `Option::unwrap()` on a `None` value in query-engine/core/src/query_document/parser.rs:250:87

### ISSUE THREAD

**Issue by Sakhro** [prisma/prisma#11588] opened 2022-02-03 10:03 UTC
Hi Prisma Team! My Prisma Client just crashed. This is the report:
## Versions

| Name            | Version            |
|-----------------|--------------------|
| Node            | v16.13.2           | 
| OS              | debian-openssl-1.1.x|
| Prisma Client   | 3.8.1              |
| Query Engine    | 0.1.0              |
| Database        | postgresql         |

## Logs
```
:31.833Z prisma:client:libraryEngine requestBatch
prisma:client:libraryEngine requestBatch
prisma:client:libraryEngine requestBatch
prisma:client:libraryEngine requestBatch
prisma:client:libraryEngine requestBatch
prisma:client:libraryEngine requestBatch
prisma:client:libraryEngine requestBatch
prisma:client:libraryEngine requestBatch
prisma:client:libraryEngine requestBatch
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine requestBatch
prisma:client:libraryEngine requestBatch
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine requestBatch
prisma:client:libraryEngine requestBatch
prisma:client:libraryEngine requestBatch
prisma:client:libraryEngine requestBatch
prisma:client:libraryEngine requestBatch
prisma:client:libraryEngine requestBatch
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine requestBatch
prisma:client:libraryEngine requestBatch
prisma:client:libraryEngine requestBatch
prisma:client:libraryEngine requestBatch
prisma:client:libraryEngine requestBatch
prisma:client:libraryEngine requestBatch
prisma:client:libraryEngine requestBatch
prisma:client:libraryEngine requestBatch
prisma:client:libraryEngine requestBatch
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine requestBatch
prisma:client:libraryEngine requestBatch
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine requestBatch
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine requestBatch
prisma:client:libraryEngine requestBatch
prisma:client:libraryEngine requestBatch
prisma:client:libraryEngine requestBatch
prisma:client:libraryEngine requestBatch
prisma:client:libraryEngine requestBatch
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine requestBatch
prisma:client:libraryEngine requestBatch
prisma:client:libraryEngine requestBatch
prisma:client:libraryEngine requestBatch
prisma:client:libraryEngine requestBatch
prisma:client:libraryEngine requestBatch
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine requestBatch
prisma:client:libraryEngine requestBatch
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine requestBatch
prisma:client:libraryEngine requestBatch
prisma:client:libraryEngine requestBatch
prisma:client:libraryEngine requestBatch
prisma:client:libraryEngine requestBatch
prisma:client:libraryEngine requestBatch
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine requestBatch
prisma:client:libraryEngine requestBatch
prisma:client:libraryEngine requestBatch
prisma:client:libraryEngine requestBatch
prisma:client:libraryEngine requestBatch
prisma:client:libraryEngine requestBatch
prisma:client:libraryEngine requestBatch
prisma:client:libraryEngine requestBatch
prisma:client:libraryEngine requestBatch
prisma:client:libraryEngine sending request, this.libraryStarted: true
```

## Client Snippet
```ts
let nftWhereInput: Prisma.NftWhereInput = {};

  if (where) {
    nftWhereInput = {
      isFeatured: where.isFeatured,
      chainId: where.chainId,
      itemId: where.itemId,
      isDisabled: where.isDisabled,
      marketAddress: where.marketAddress,
    };
  }

  if (where?.categories?.length) {
    nftWhereInput.category = {
      in: where.categories,
    };
  }

  if (where.search) {
    nftWhereInput.OR = [
      {
        name: {
          contains: where.search,
          mode: "insensitive",
        },
      },
      {
        description: {
          contains: where.search,
          mode: "insensitive",
        },
      },
    ];

    if (isValidNumber(Number(where.search))) {
      nftWhereInput.OR.push({
        itemId: {
          equals: Number(where.search),
        },
      });
      nftWhereInput.OR.push({
        tokenId: {
          equals: Number(where.search),
        },
      });
    }
  }

  const offerWhereInput: Prisma.ListingWhereInput = {
    nft: nftWhereInput,
    isAuction: where.isAuction,
    createdById: where.createdById,
    isSold: where.isSold,
    isDisabled: where.isDisabled,
  };

  if (where?.currencyId) {
    if (where.minPrice && where.maxPrice) {
      offerWhereInput.prices = {
        some: {
          currencyId: where.currencyId,
          AND: [
            {
              amount: {
                lte: where.maxPrice,
              },
            },
            {
              amount: {
                gte: where.minPrice,
              },
            },
          ],
        },
      };
    } else if (where.minPrice) {
      offerWhereInput.prices = {
        some: {
          currencyId: where.currencyId,
          amount: {
            gte: where.minPrice,
          },
        },
      };
    } else if (where.maxPrice) {
      offerWhereInput.prices = {
        some: {
          currencyId: where.currencyId,
          amount: {
            lte: where.maxPrice,
          },
        },
      };
    } else {
      offerWhereInput.prices = {
        some: {
          currencyId: where.currencyId,
        },
      };
    }
  }

  return ctx.db.listing.findMany({
    skip,
    take,
    orderBy,
    where: offerWhereInput,
  });
```

## Schema
```prisma
model Price {
  id        String   @id @default(cuid())
  createdAt DateTime @default(now()) @map("created_at")
  updatedAt DateTime @updatedAt

  amount Float

  currency   Currency @relation(fields: [currencyId], references: [id])
  currencyId String   @map("currency_id")

  listing   Listing? @relation(fields: [listingId], references: [id])
  listingId String?  @map("listing_id")
  bid       Bid?

  @@index([amount])
  @@index([currencyId])
  @@index([amount, currencyId])
  @@map("prices")
}

model Listing {
  id        String   @id @default(cuid())
  createdAt DateTime @default(now()) @map("created_at")
  updatedAt DateTime @updatedAt

  amount       Int       @default(1)
  isAuction    Boolean   @default(false) @map("is_auction")
  isSold       Boolean   @default(false) @map("is_sold")
  isDisabled   Boolean   @default(false) @map("is_disabled")
  auctionEndAt DateTime? @map("action_end_at")

  createdBy     User    @relation("created_listings", fields: [createdById], references: [id])
  createdById   String  @map("createdBy_id")
  nft           Nft?    @relation(fields: [nftId], references: [id])
  nftId         String? @map("nft_id")
  purchasedBy   User?   @relation(fields: [purchasedById], references: [id])
  purchasedById String?

  prices Price[]
  bids   Bid[]

  @@index([createdById, isAuction])
  @@index([createdById, isSold])
  @@index([isAuction, isDisabled])
  @@index([isAuction, isSold, isDisabled])
  @@index([isAuction, createdById, isSold, isDisabled])
  @@map("listings")
}

model Nft {
  id        String   @id @default(cuid())
  createdAt DateTime @default(now()) @map("created_at")
  updatedAt DateTime @updatedAt

  txHash        String  @map("tx_hash")
  name          String
  description   String
  itemAddress   String  @map("item_address")
  uri           String
  itemId        Int     @map("item_id")
  tokenId       Int     @map("token_id")
  isFeatured    Boolean @default(false) @map("is_featured")
  isDisabled    Boolean @default(false) @map("is_disabled")
  category      String
  tokenUri      String  @map("token_uri")
  marketAddress String  @map("market_address")
  type          String?
  amount        Int     @default(1)

  chain       Chain  @relation(fields: [chainId], references: [id])
  chainId     Int    @map("chain_id")
  createdBy   User   @relation(fields: [createdById], references: [id])
  createdById String @map("created_by_id")

  listings Listing[]
  owners   Owner[]

  @@index([itemId])
  @@index([marketAddress])
  @@index([itemId, marketAddress])
  @@index([isDisabled])
  @@index([isDisabled, isFeatured])
  @@index([isDisabled, isFeatured, category])
  @@index([isFeatured, chainId, itemId, isDisabled, marketAddress])
  @@map("nfts")
}

```

## Prisma Engine Query
```
{"X":{}}
```

**Comment by Sakhro** [comment] 2022-02-03 11:45
Seems like we fix it by specifying the node version at package.json for our server

**Comment by Sakhro** [comment] 2022-02-03 21:09
No, prev workaround doesn’t help. Still having this issue

**Comment by pantharshit00** [comment] 2022-02-04 09:31
Can you please paste the actual error returned here? The error report wasn't able to collect the whole context.

**Comment by Sakhro** [comment] 2022-02-04 09:33
Unfortunately only error message for now 
```
PANIC: called `Option::unwrap()` on a `None` value in query-engine/core/src/query_document/parser.rs:250:87

This is a non-recoverable error which probably happens when the Prisma Query Engine has a panic.

https://github.com/prisma/prisma/issues/new?body=Hi+Prisma+Team%21+My+Prisma+Client+just+crashed.+This+is+the+report%3A%0A%23%23+Versions%0A%0A%7C+Name++++++++++++%7C+Version++++++++++++%7C%0A%7C-----------------%7C--------------------%7C%0A%7C+Node++++++++++++%7C+v17.4.0++++++++++++%7C+%0A%7C+OS++++++++++++++%7C+debian-openssl-1.1.x%7C%0A%7C+Prisma+Client+++%7C+3.8.1++++++++++++++%7C%0A%7C+Query+Engine++++%7C+0.1.0++++++++++++++%7C%0A%7C+Database++++++++%7C+postgresql+++++++++%7C%0A%0A%0A%0A%23%23+Logs%0A%60%60%60%0At%3AlibraryEngine+sending+request%2C+this.libraryStarted%3A+true%0Aprisma%3Aclient%3AlibraryEngine+sending+request%2C+this.libraryStarted%3A+true%0Aprisma%3Aclient%3AlibraryEngine+requestBatch%0Aprisma%3Aclient%3AlibraryEngine+requestBatch%0Aprisma%3Aclient%3AlibraryEngine+requestBatch%0Aprisma%3Aclient%3AlibraryEngine+requestBatch%0Aprisma%3Aclient%3AlibraryEngine+requestBatch%0Aprisma%3Aclient%3AlibraryEngine+requestBatch%0Aprisma%3Aclient%3AlibraryEngine+sending+request%2C+this.libraryStarted%3A+true%0Aprisma%3Aclient%3AlibraryEngine+sending+request%2C+this.libraryStarted%3A+true%0Aprisma%3Aclient%3AlibraryEngine+sending+request%2C+this.libraryStarted%3A+true%0Aprisma%3Aclient%3AlibraryEngine+requestBatch%0Aprisma%3Aclient%3AlibraryEngine+requestBatch%0Aprisma%3Aclient%3AlibraryEngine+requestBatch%0Aprisma%3Aclient%3AlibraryEngine+requestBatch%0Aprisma%3Aclient%3AlibraryEngine+requestBatch%0Aprisma%3Aclient%3AlibraryEngine+requestBatch%0Aprisma%3Aclient%3AlibraryEngine+sending+request%2C+this.libraryStarted%3A+true%0Aprisma%3Aclient%3AlibraryEngine+requestBatch%0Aprisma%3Aclient%3AlibraryEngine+requestBatch%0Aprisma%3Aclient%3AlibraryEngine+requestBatch%0Aprisma%3Aclient%3AlibraryEngine+requestBatch%0Aprisma%3Aclient%3AlibraryEngine+requestBatch%0Aprisma%3Aclient%3AlibraryEngine+requestBatch%0Aprisma%3Aclient%3AlibraryEngine+sending+request%2C+this.libraryStarted%3A+true%0Aprisma%3Aclient%3AlibraryEngine+sending+request%2C+this.libraryStarted%3A+true%0Aprisma%3Aclient%3AlibraryEngine+sending+request%2C+this.libraryStarted%3A+true%0Aprisma%3Aclient%3AlibraryEngine+sending+request%2C+this.libraryStarted%3A+true%0Aprisma%3Aclient%3AlibraryEngine+sending+request%2C+this.libraryStarted%3A+true%0Aprisma%3Aclient%3AlibraryEngine+requestBatch%0Aprisma%3Aclient%3AlibraryEngine+requestBatch%0Aprisma%3Aclient%3AlibraryEngine+sending+request%2C+this.libraryStarted%3A+true%0Aprisma%3Aclient%3AlibraryEngine+requestBatch%0Aprisma%3Aclient%3AlibraryEngine+requestBatch%0Aprisma%3Aclient%3AlibraryEngine+requestBatch%0Aprisma%3Aclient%3AlibraryEngine+requestBatch%0Aprisma%3Aclient%3AlibraryEngine+requestBatch%0Aprisma%3Aclient%3AlibraryEngine+requestBatch%0Aprisma%3Aclient%3AlibraryEngine+sending+request%2C+this.libraryStarted%3A+true%0Aprisma%3Aclient%3AlibraryEngine+sending+request%2C+this.libraryStarted%3A+true%0Aprisma%3Aclient%3AlibraryEngine+sending+request%2C+this.libraryStarted%3A+true%0Aprisma%3Aclient%3AlibraryEngine+requestBatch%0Aprisma%3Aclient%3AlibraryEngine+requestBatch%0Aprisma%3Aclient%3AlibraryEngine+sending+request%2C+this.libraryStarted%3A+true%0Aprisma%3Aclient%3AlibraryEngine+sending+request%2C+this.libraryStarted%3A+true%0Aprisma%3Aclient%3AlibraryEngine+requestBatch%0Aprisma%3Aclient%3AlibraryEngine+requestBatch%0Aprisma%3Aclient%3AlibraryEngine+requestBatch%0Aprisma%3Aclient%3AlibraryEngine+requestBatch%0Aprisma%3Aclient%3AlibraryEngine+requestBatch%0Aprisma%3Aclient%3AlibraryEngine+requestBatch%0Aprisma%3Aclient%3AlibraryEngine+sending+request%2C+this.libraryStarted%3A+true%0Aprisma%3Aclient%3AlibraryEngine+sending+request%2C+this.libraryStarted%3A+true%0Aprisma%3Aclient%3AlibraryEngine+requestBatch%0Aprisma%3Aclient%3AlibraryEngine+requestBatch%0Aprisma%3Aclient%3AlibraryEngine+requestBatch%0Aprisma%3Aclient%3AlibraryEngine+requestBatch%0Aprisma%3Aclient%3AlibraryEngine+requestBatch%0Aprisma%3Aclient%3AlibraryEngine+requestBatch%0Aprisma%3Aclient%3AlibraryEngine+sending+request%2C+this.libraryStarted%3A+true%0Aprisma%3Aclient%3AlibraryEngine+sending+request%2C+this.libraryStarted%3A+true%0Aprisma%3Aclient%3Afetcher+Error%3A+called+%60Option%3A%3Aunwrap%28%29%60+on+a+%60None%60+value%0A++++at+prismaGraphQLToJSError+%28%2Fapp%2Fnode_modules%2F%40prisma%2Fclient%2Fruntime%2Findex.js%3A35966%3A10%29%0A++++at+Object.request+%28%2Fapp%2Fnode_modules%2F%40prisma%2Fclient%2Fruntime%2Findex.js%3A36327%3A17%29%0A++++at+async+cb+%28%2Fapp%2Fnode_modules%2F%40prisma%2Fclient%2Fruntime%2Findex.js%3A38661%3A26%29%0Aprisma%3Aclient%3AlibraryEngine+sending+request%2C+this.libraryStarted%3A+true%0A%60%60%60%0A%0A%23%23+Client+Snippet%0A%60%60%60ts%0A%2F%2F+PLEASE+FILL+YOUR+CODE+SNIPPET+HERE%0A%60%60%60%0A%0A%23%23+Schema%0A%60%60%60prisma%0A%2F%2F+PLEASE+ADD+YOUR+SCHEMA+HERE+IF+POSSIBLE%0A%60%60%60%0A%0A%23%23+Prisma+Engine+Query%0A%60%60%60%0A%7B%22X%22%3A%7B%7D%7D%0A%60%60%60%0A&title=PANIC%3A+called+%60Option%3A%3Aunwrap%28%29%60+on+a+%60None%60+value+in+query-engine%2Fcore%2Fsrc%2Fquery_document%2Fparser.rs%3A250%3A87&template=bug_report.md

If you want the Prisma team to look into it, please open the link above 🙏
To increase the chance of success, please post your schema and a snippet of
how you used Prisma Client in the issue. 

```

**Comment by pantharshit00** [comment] 2022-02-04 13:10
Looks like this would be a duplicate of https://github.com/prisma/prisma/issues/10586 which is related to Float handling and your snippets confirm that. I would advise you to subscribe to that issue.

**Closed by pantharshit00** 2022-02-04 13:10 UTC
Labels: bug/0-unknown, kind/bug, team/client, topic: basic error report
