### ISSUE TITLE
Cascade delete

### ISSUE THREAD

**Issue by Mark-Panda** [prisma/prisma#4198] opened 2020-11-09 03:11 UTC
MySQL foreign key is CASCADE, but using delete still shows
 ``` { Error: 
Invalid `prisma.mother.delete()` invocation in
/Users/maxianfei/Desktop/prismaProject/webserverPrisma/node_modules/nexus-plugin-prisma/dist/schema/builder.js:202:105

  198         locallyComputedInputs: publisherConfig.locallyComputedInputs,
  199     });
  200 }
  201 args = this.paginationStrategy.resolve(args);
→ 202 return prismaClient[mappedField.prismaClientAccessor][mappedField.operation](args)


  The change you are trying to make would violate the required relation 'MotherToMtext' between the `Mother` and `Mtext` models.
    at iy.request (/Users/maxianfei/Desktop/prismaProject/webserverPrisma/node_modules/@prisma/client/runtime/index.js:196:54)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  code: 'P2014',
  meta:
   { relation_name: 'MotherToMtext',
     model_a_name: 'Mother',
     model_b_name: 'Mtext' } }```

**Comment by diegozuber** [comment] 2020-11-10 09:09
Same probleme here.

**Comment by pantharshit00** [comment] 2020-11-10 11:31
Hi,

Thanks for reporting this! It has already been reported before, so I am going to close this as a duplicate of https://github.com/prisma/prisma/issues/2810

**Closed by pantharshit00** 2020-11-10 11:31 UTC

**Comment by diegozuber** [comment] 2020-11-10 15:20
@pantharshit00 That means this guide is outdated and does not work anymore?

https://www.prisma.io/docs/guides/database-workflows/cascading-deletes/mysql

**Comment by pantharshit00** [comment] 2020-11-11 13:29
That guide should still work. This above case is kind of "limitation" of the query engine where is currently validates relations in memory before send the queries.

**Comment by diegozuber** [comment] 2020-11-11 13:56
@pantharshit00 the guide doesn't work for me. If I try this part (https://www.prisma.io/docs/guides/database-workflows/cascading-deletes/mysql#82-validating-cascade) I'm always getting the same error as above.
