### ISSUE TITLE
Allow `findMany` with multiple compound id values

### ISSUE THREAD

**Issue by uhyunpark** [prisma/prisma#18527] opened 2023-03-28 02:28 UTC
## Problem
I made a model with a compound @@unique / @@id field, and want to query them with an array. 

```prisma
model student {
  regionName String
  schoolName String
  classNumber Int
  isVerified Boolean

  @@id([regionName, schoolName, classNumber], name: 'unique_class_id')
}
```

## Suggested solution
```typescript
const ids = []
await prisma.student.findMany({
  where: { 
    unique_class_id: {
      IN: ids
    } 
  }
})
```

## Additional context
I saw a [similar request](https://github.com/prisma/prisma/issues/16979) about compound ids here.

**Comment by lounsbrough** [comment] 2023-11-06 17:29
This would be helpful for our project as well.

**Comment by janpio** [comment] 2023-11-06 18:34
Do I understand correctly that the request here is to be able to provide a list id IDs to be filtered via `IN` instead of just being able to provide one specific value?

**Comment by lounsbrough** [comment] 2023-11-06 18:36
That is correct for our use case.

**Comment by janpio** [comment] 2023-11-06 18:43
Thanks, then I think this is a full duplicate of https://github.com/prisma/prisma/issues/16979 (now that I made `findMany` explicit there) and I think we should close this one and use the other issue instead (as it has a few upvotes already). Agree @lounsbrough? @uhyunpark Did we capture your intent as well?

**Comment by lounsbrough** [comment] 2023-11-06 18:44
Yeah that sounds good

**Closed** 2023-11-06 18:46 UTC
Labels: kind/feature, team/client, topic: client api, topic: composite ids, topic: findMany()
