### ISSUE TITLE
Duplicate type names generated with table FooBah and table Foo with relation bah

### ISSUE THREAD

**Issue by BryceDalbey** [prisma/prisma#17007] opened 2022-12-24 07:42 UTC
### Bug description

When model has table Foo with relation column bah and another table FooBah, duplicate FooBahArgs types are generated. The relation doesn't need to be to the FooBah table.

### How to reproduce

Generate client with following model:

```
generator client {
  provider = "prisma-client-js"
  output   = "./generated"
}

datasource db {
  provider = "mysql"
  url      = env("DB_URL")
}

model Foo {
  id   Int        @id
  bah Baz[]
}

model Baz {
  id     Int  @id 
  fooId Int  
  foo   Foo @relation(fields: [fooId], references: [id])
}

model FooBah {
 id Int @id

}
```

### Expected behavior

Client shouldn't generate duplicate type names, or should give warning of invalid naming scheme.

### Prisma information

See above

### Environment & setup

- OS: Windows 10
- Database: MySQL
- Node.js version: 16.14.2

### Prisma Version

```
$ npx prisma -v
prisma                  : 4.8.0
@prisma/client          : 4.8.0
Current platform        : windows
Query Engine (Node-API) : libquery-engine d6e67a83f971b175a593ccc12e15c4a757f93ffe (at ..\..\node_modules\@prisma\engines\query_engine-windows.dll.node)
Migration Engine        : migration-engine-cli d6e67a83f971b175a593ccc12e15c4a757f93ffe (at ..\..\node_modules\@prisma\engines\migration-engine-windows.exe)
Introspection Engine    : introspection-core d6e67a83f971b175a593ccc12e15c4a757f93ffe (at ..\..\node_modules\@prisma\engines\introspection-engine-windows.exe)
Format Binary           : prisma-fmt d6e67a83f971b175a593ccc12e15c4a757f93ffe (at ..\..\node_modules\@prisma\engines\prisma-fmt-windows.exe)
Format Wasm             : @prisma/prisma-fmt-wasm 4.8.0-61.d6e67a83f971b175a593ccc12e15c4a757f93ffe
Default Engines Hash    : d6e67a83f971b175a593ccc12e15c4a757f93ffe
Studio                  : 0.479.0
```

**Comment by BryceDalbey** [comment] 2022-12-24 19:45
https://github.com/prisma/prisma/issues/17005#issue-1509857634 may be the same issue

**Comment by jkomyno** [comment] 2022-12-27 11:46
Hi @BryceDalbey, I confirm this is a duplicate of #17005.
Please, stick with `prisma@4.7.1` while we fix this type regression.

**Closed by jkomyno** 2022-12-27 11:46 UTC
Labels: kind/bug
