### ISSUE TITLE
Detection of the foreign key names with prisma migrate

### ISSUE THREAD

**Issue by alan345** [prisma/prisma#9011] opened 2021-08-30 15:32 UTC
### Bug description

After updating Prisma from `2.27.0` to `2.30.0` I have this issue in my dev env:
```
> npx prisma migrate dev

? Drift detected: Your database schema is not in sync with your migration history.

The following is a summary of the differences between the expected database schema given your migrations files, and the actual schema of the database.

It should be understood as the set of changes to get from the expected schema to the actual schema.

[*] Changed the `Addresse` table
  [-] Removed foreign key on columns (companieId)
  [-] Removed foreign key on columns (userId)
  [+] Added foreign key on columns (companieId)
  [+] Added foreign key on columns (userId)

[*] Changed the `AuthDevice` table
  [-] Removed foreign key on columns (userId)
  [+] Added foreign key on columns (userId)

[*] Changed the `Balance` table
  [-] Removed foreign key on columns (companieId)
  [+] Added foreign key on columns (companieId)

[*] Changed the `Campaign` table
  [-] Removed foreign key on columns (userId)
  [+] Added foreign key on columns (userId)

[*] Changed the `CampaignHistoric` table
  [-] Removed foreign key on columns (campaignId)
  [-] Removed foreign key on columns (companieId)
  [-] Removed foreign key on columns (userId)
  [+] Added foreign key on columns (campaignId)
  [+] Added foreign key on columns (companieId)
  [+] Added foreign key on columns (userId)

[*] Changed the `Cardholder` table
  [-] Removed foreign key on columns (companieId)
  [-] Removed foreign key on columns (userId)
  [+] Added foreign key on columns (companieId)
  [+] Added foreign key on columns (userId)

[*] Changed the `Charge` table
  [-] Removed foreign key on columns (invoiceId)
  [-] Removed foreign key on columns (sourceId)
  [+] Added foreign key on columns (invoiceId)
  [+] Added foreign key on columns (sourceId)

...
// same pattern for my entire database


We need to reset the MySQL database "nacho@prod" at "localhost:3306".
Do you want to continue? All data will be lost. … no

Reset cancelled.
```

So I decided to update my schema, as it looks like my database changed (with `npx prisma db pull `)  => No changed made in the schema. I ran again `npx prisma migrate dev`, I got the same result described above.

I decided to move ahead and compare the table `Address` after reseting the database in dev.

```
CREATE TABLE `Addresse` (
  `id` char(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `type` enum('BILLING','SHIPPING','MAILING','HOME','PAYMENT_SOURCE_BILLING_ADDRESS') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `address1` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `address2` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `city` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `zip` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `state` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `country` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `updatedAt` datetime(3) NOT NULL,
  `createdAt` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `name` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `userId` char(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `companieId` char(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `companieId` (`companieId`),
  KEY `userId` (`userId`),
  CONSTRAINT `Addresse_ibfk_1` FOREIGN KEY (`companieId`) REFERENCES `Companie` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `Addresse_ibfk_2` FOREIGN KEY (`userId`) REFERENCES `User` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
```

changed to:
```
CREATE TABLE `Addresse` (
  `id` char(30) COLLATE utf8mb4_unicode_ci NOT NULL,
  `type` enum('BILLING','SHIPPING','MAILING','HOME','PAYMENT_SOURCE_BILLING_ADDRESS') COLLATE utf8mb4_unicode_ci NOT NULL,
  `address1` mediumtext COLLATE utf8mb4_unicode_ci NOT NULL,
  `address2` mediumtext COLLATE utf8mb4_unicode_ci NOT NULL,
  `city` mediumtext COLLATE utf8mb4_unicode_ci NOT NULL,
  `zip` mediumtext COLLATE utf8mb4_unicode_ci NOT NULL,
  `state` mediumtext COLLATE utf8mb4_unicode_ci NOT NULL,
  `country` mediumtext COLLATE utf8mb4_unicode_ci NOT NULL,
  `updatedAt` datetime(3) NOT NULL,
  `createdAt` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `name` mediumtext COLLATE utf8mb4_unicode_ci,
  `userId` char(30) COLLATE utf8mb4_unicode_ci NOT NULL,
  `companieId` char(30) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `companieId` (`companieId`),
  KEY `userId` (`userId`),
  CONSTRAINT `addresse_ibfk_1` FOREIGN KEY (`companieId`) REFERENCES `Companie` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `addresse_ibfk_2` FOREIGN KEY (`userId`) REFERENCES `User` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
```

It looks like Prisma needs to have a lower case for the name of the foreign key? Why?
`Addresse_ibfk_1` vs `addresse_ibfk_1`

### How to reproduce

1. Set a MYSQL Database with 2 table and 1 relationship. The Name of the foreign key should be UpperCase
2. run ` npx prisma migrate dev`

### Expected behavior

IT should work, no waning like this should be triggered
```
[*] Changed the `Addresse` table
  [-] Removed foreign key on columns (companieId)
  [-] Removed foreign key on columns (userId)
  [+] Added foreign key on columns (companieId)
  [+] Added foreign key on columns (userId)
```

### Environment & setup

- OS: Mac OS
- Database: MySQL
- Node.js version: v12.18.3

### Prisma Version

```
2.30.0
```

it works fine with version `2.27.0`, `2.28.0`, `2.29.0` but not `2.30.0`

```
✔ Generated Prisma Client (2.27.0) to ./node_modules/@prisma/client in 1.95s
✔ Generated Prisma Client (2.28.0) to ./node_modules/@prisma/client in 1.98s
✔ Generated Prisma Client (2.29.0) to ./node_modules/@prisma/client in 1.99s
```

**Comment by tomhoule** [comment] 2021-08-31 08:00
Are you using the `namedConstraints` preview feature?

**Comment by pimeys** [comment] 2021-09-01 17:31
Ok, so I hate when somebody tells me "can't reproduce this", but this is what I got out of this issue today. Having seen this many times is usually the person testing is wrong and there is a bug, so I write my findings and let @pantharshit00 to see if he can get a reproduction.

Setup:
- Prisma versions 2.30.0, latest master and 2.29.0
- NixOS, MySQL 5.7 on docker

Created this manually to the database:

```sql
CREATE TABLE A (
    id int PRIMARY KEY,
    bId int NOT NULL
);

CREATE TABLE B (
    id int PRIMARY KEY
);

ALTER TABLE A ADD CONSTRAINT A_ibfk_1 FOREIGN KEY (bId) REFERENCES B(id);
```

And this data model:

```prisma
generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "mysql"
  url      = "mysql://root:prisma@localhost:3306/prisma"
}

model A {
  id  Int @id
  bId Int
  B   B   @relation(fields: [bId], references: [id])

  @@index([bId], name: "A_ibfk_1")
}

model B {
  id Int @id
  A  A[]
}
```

Then created an empty migration file and added the schema above to it. `npx prisma migrate dev` sees no drift... We'll get back to you with this when we get a good reproduction.

**Comment by alan345** [comment] 2021-09-01 17:47
In my schema, the name of the index is not the name of the relation.
This is the model used in `schema.prisma`

```
model Addresse {
  id         String        @id @default(cuid()) @db.Char(30)
  type       Addresse_type
  address1   String        @db.MediumText
  address2   String        @db.MediumText
  city       String        @db.MediumText
  zip        String        @db.MediumText
  state      String        @db.MediumText
  country    String        @db.MediumText
  updatedAt  DateTime      @updatedAt
  createdAt  DateTime      @default(now())
  name       String?       @db.MediumText
  userId     String        @db.Char(30)
  companieId String?       @db.Char(30)
  companie   Companie?     @relation(fields: [companieId], references: [id])
  user       User          @relation(fields: [userId], references: [id])

  @@index([companieId], name: "companieId")
  @@index([userId], name: "userId")
}
```

**Comment by janpio** [comment] 2021-09-01 17:48
@alan345 Can you share the full schema maybe? Then we can just try to migrate that ourselves from nothing and see what happens. If the database was created outside of Prisma initially, can you share a SQL schema dump of it?

**Comment by tomhoule** [comment] 2021-09-01 17:50
> In my schema, the name of the index is not the name of the relation.

I would need to spend more time investigating, but I think this may be the key.

**Comment by pantharshit00** [comment] 2021-09-02 09:15
I can't also reproduce this. Reproducing drifts are hard, if you can share actual contents of the `migrations` folder that would be great.

**Comment by alan345** [comment] 2021-09-02 14:53
Give me an email so i can send you everything. I'm not comfortable to post
it here publicly
Thanks

**Comment by pantharshit00** [comment] 2021-09-02 15:25
@alan345 Send it to "schemas@prisma.io"

**Comment by alan345** [comment] 2021-09-02 15:45
email sent to schemas@prisma.io

**Comment by alan345** [comment] 2021-09-09 01:12
Hello,
Let me know how is it going and if anyhow I can help you solve this.

**Comment by pantharshit00** [comment] 2021-09-09 14:09
Hello @alan345 

Looks like this is fixed by `namedConstraints` which was introduced to solve these kind of problems with foreign key naming where we don't depend on a convention and rather  store the name of constraint in the schema.

What I did is tried to replicate your setup using the dump you shared and ran `npx prisma introspect` with `3.0.1` which has named constraint enabled by default. That will add `map` key to indexes and relations where needed:
```prisma
model Address {
// ..
// ..
  companie   Companie?     @relation(fields: [companieId], references: [id], map: "Addresse_ibfk_1")
  user       User          @relation(fields: [userId], references: [id], onDelete: Cascade, map: "Addresse_ibfk_2")

  @@index([companieId], map: "companieId")
  @@index([userId], map: "userId")
}
``` 

(Notice the `map` in `@@index` and in `@relation`.

After introspecting I ran `npx prisma migrate dev` and I only got the following change:
```sql
ALTER TABLE `Product` ADD COLUMN `youtubeLinkProduct` VARCHAR(191) NOT NULL DEFAULT '';
```

I guess this is the field that you were trying to add when you got the drift. 

So please try again with namedConstraint feature and report back.

**Comment by pantharshit00** [comment] 2021-09-09 14:41
You might find this document useful when enabling `namedConstraints`: https://www.prisma.io/docs/guides/upgrade-guides/upgrading-versions/upgrading-to-prisma-3/named-constraints

**Comment by Jolg42** [comment] 2023-01-13 15:55
Note: Closing as this should work with Prisma 3 and up.

**Closed by Jolg42** 2023-01-13 15:55 UTC
Labels: bug/0-unknown, kind/bug, tech/engines, topic: mysql, team/schema, topic: drift
