### ISSUE TITLE
PrismaClient.model.count should allow filtering

### ISSUE THREAD

**Issue by ranjan-purbey** [prisma/prisma#2088] opened 2020-04-04 03:14 UTC
## Problem
Currently the `count` method available on a Prisma model client returns the total number of records. It doesn't allow to count the number of records that satisfy a certain criterion.

## Solution
The `count` method should accept a `where` option like `findMany` to allow filtering of records on database level.

 ## Alternatives
As of now, the `findMany` method can be used to achieve the same. But SQL `select` statements are generally sub-optimal when all that is required is the count.

**Comment by Sytten** [comment] 2020-04-04 03:23
Duplicate of https://github.com/prisma/prisma-client-js/issues/252, it will be in the next beta.

**Closed** 2020-04-04 06:52 UTC
