### ISSUE TITLE
Switch PostgreSQL schema in a query context

### ISSUE THREAD

**Issue by laspinacristian** [prisma/prisma#5257] opened 2021-01-24 09:35 UTC
## Problem

Prisma doesn't give the ability to change Postgres schema in a query context. 

I'm developing a SAAS app and I would have liked to use Prisma, but when developing my app I have a lot of tables for each tenant so i use the following postgresql schemas:

- public: for tables and data related to every tenant
- tenant1: for tables and data related to tenant1 only
- tenant2: for tables and data related to tenant2 only
- tenantN: so on...

So I'm using Knex + Objection.js which give me the ability to select postgres schema in a query context, like so:

```js
const person = await Person.query().withSchema("tenant1").findById(1);
```

Is there something am I missing in the prisma docs or was this feature already discussed?

**Comment by pantharshit00** [comment] 2021-01-27 19:36
Related: https://github.com/prisma/prisma/issues/1122

**Comment by janpio** [comment] 2023-06-17 18:11
I think this is effectively a duplicate of https://github.com/prisma/prisma/issues/12420

**Closed by janpio** 2023-06-17 18:11 UTC
Labels: kind/feature, team/client, topic: client api, topic: postgresql, topic: multi-tenant
