### ISSUE TITLE
called `Option::unwrap()` on a `None` value

### ISSUE THREAD

**Issue by AgniShiva** [prisma/prisma#23295] opened 2024-02-27 12:31 UTC
Hi Prisma Team! My Prisma Client just crashed. This is the report:
## Versions

| Name            | Version            |
|-----------------|--------------------|
| Node            | v20.10.0           | 
| OS              | windows            |
| Prisma Client   | 5.3.1              |
| Query Engine    | 61e140623197a131c2a6189271ffee05a7aa9a59|
| Database        | mongodb            |

## Logs
```
prisma:tryLoadEnv Environment variables loaded from \.env
prisma:client checkPlatformCaching:postinstall 
prisma:client checkPlatformCaching:ciName 
prisma:tryLoadEnv Environment variables loaded from \.env
prisma:client dirname \node_modules\.prisma\client
prisma:client relativePath ../../../prisma
prisma:client cwd \prisma
prisma:client clientVersion 5.3.1
prisma:client:libraryEngine internalSetup
prisma:client:engines:resolveEnginePath enginePath \node_modules\.prisma\client\query_engine-windows.dll.node
prisma:client:libraryEngine sending request, this.libraryStarted: false
prisma:client:libraryEngine library starting
prisma:client:libraryEngine library started
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
```

## Client Snippet
```ts
// PLEASE FILL YOUR CODE SNIPPET HERE
```

## Schema
```prisma
// PLEASE ADD YOUR SCHEMA HERE IF POSSIBLE
```

## Prisma Engine Query
```
{"X":true}}}
```

**Comment by millsp** [comment] 2024-02-28 00:12
Hey @AgniShiva, could you please provide us  with a reproduction? Ideally your schema and the query that caused this crash. Thanks!

**Comment by AgniShiva** [comment] 2024-02-28 04:16
const updateProduct = {
          display_name: rowData[2],
          barcode: rowData[4],
          mrp: Number(rowData[5]),
          sale_price: Number(rowData[6]),
        };

        const updateQuery = {
          data: updateProduct,
          where: {
            product_sku: String(rowData[3]),
            warehouse_id: String(val),
          },
        };
        
        
        


export const updateProducts = async (updateData: any) => {

  const updates = updateData.map((operation: any) =>
  
    prisma.products.updateMany({
      where: operation.where,
      data: operation.data,
    })
  );
  await Promise.all(updates);
};



Schema:



model products {
    id                   String                 @id @default(auto()) @map("_id") @db.ObjectId
    vendor_id            String                 @db.ObjectId
    warehouse_id         String?                @db.ObjectId
    warehouse_code       String?
    product_name         String
    display_name         String?
    product_sku          String
    barcode              String
    image                String?
    mrp                  Float                  @default(0.00)
    sale_price           Float                  @default(0.00)
    status               Int                    @default(0)
    created_by           String?
    updated_by           String?
    created_at           DateTime               @default(now()) @map("created_at")
    updated_at           DateTime?              @updatedAt @map("updated_at")
    inward_bin_mapping   inward_bin_mapping[]
    product_bin_mappings product_bin_mappings[]
    vendors              vendors                @relation(fields: [vendor_id], references: [id])
    warehouses           warehouses?            @relation(fields: [warehouse_id], references: [id])

    @@index([barcode], map: "barcode")
    @@index([product_sku], map: "product_sku")
    @@index([vendor_id], map: "vendor_id")
    @@index([warehouse_id], map: "warehouse_id")
}

**Comment by AgniShiva** [comment] 2024-02-28 05:48
Above using excel update with 1000 records.

**Comment by Weakky** [comment] 2024-05-23 09:22
Hey @AgniShiva, thanks for sharing a reproduction with us. Unfortunately, it's missing the actual data you're trying to update. We don't need the full excel sheet, just the one row that makes your query crash. Thank you 🙏

**Comment by SevInf** [comment] 2024-06-20 08:54
Hey @AgniShiva  ,

Did you get a chance to have a look at my collegues comment? It'd be helpful for us to move your issue forward.

Without further information, we'll have to close this issue. Thank you 🙏

**Comment by jkomyno** [comment] 2024-07-10 12:47
We're closing this issue due to inactivity. Please leave a comment below, ideally with a reproduction repository, if you have more actionable feedback about this issue. Thanks!

**Closed by jkomyno** 2024-07-10 12:47 UTC
Labels: bug/0-unknown, kind/bug, tech/engines, domain/client, topic: mongodb, topic: unwrap error
