### ISSUE TITLE
multiSchema issue

### ISSUE THREAD

**Issue by amarparekh26** [prisma/prisma#17175] opened 2023-01-07 08:24 UTC
Hi Prisma Team! The following command just crashed.

## Command

`db pull`

## Versions
      
| Name        | Version            |
|-------------|--------------------|
| Platform    | windows            | 
| Node        | v16.15.1           | 
| Prisma CLI  | 4.8.1              | 
| Engine      | d6e67a83f971b175a593ccc12e15c4a757f93ffe| 

## Error
```
Error: [libs\sql-schema-describer\src\mssql.rs:223:96] called `Option::unwrap()` on a `None` value
```

**Comment by mcbethio** [comment] 2023-01-09 11:19
This is duplicate of https://github.com/prisma/prisma/issues/17176. Please re-open this issue if that is not the case.

**Closed by mcbethio** 2023-01-09 11:19 UTC
