### ISSUE TITLE
prisma client doesn't work with serverless-next.js

### ISSUE THREAD

**Issue by jeremygottfried** [prisma/prisma#6032] opened 2021-03-09 15:43 UTC
[Serverless-next.js](https://github.com/serverless-nextjs/serverless-next.js) doesn't work with prisma client. It seems like the issue is the binaries either don't have the correct permissions or they're not in the correct location.

The serverless.com component deploys NextJS to AWS lambda edge, S3 and cloudfront. The issue seems to occur in the lambda execution environment.

Error:
> ERROR	[next-auth][error][get_user_by_provider_account_id_error] 
https://next-auth.js.org/errors#get_user_by_provider_account_id_error PrismaClientInitializationError2 [PrismaClientInitializationError]: Query engine binary for current platform "rhel-openssl-1.0.x" could not be found.
This probably happens, because you built Prisma Client on a different platform.
(Prisma Client looked in "/tmp/query-engine-rhel-openssl-1.0.x")

> Searched Locations:
> 
> 
> 
> You already added the platforms "native", "rhel-openssl-1.0.x" to the "generator" block
> in the "schema.prisma" file as described in https://pris.ly/d/client-generator,
> but something went wrong. That's suboptimal.
> 
> Please create an issue at https://github.com/prisma/prisma-client-js/issues/new
>     at PrismaClientFetcher.request (/var/task/pages/api/auth/[...nextauth].js:151931:15)
>     at processTicksAndRejections (internal/process/task_queues.js:97:5) {
>   clientVersion: '2.16.1'
> }

This issue seems to be well documented for various use cases.
- [serverless-next.js#843]( https://github.com/serverless-nextjs/serverless-next.js/issues/843)
- [prisma/docs#841](https://github.com/prisma/docs/issues/841)
- [next-auth#1191](https://github.com/nextauthjs/next-auth/issues/1191)
- [prisma/prisma#2195](https://github.com/prisma/prisma/issues/2195)
- [prisma-client-js#616](https://github.com/prisma/prisma-client-js/issues/616)
- [prisma/prisma#5392](https://github.com/prisma/prisma/issues/5392)

I spent 2 days trying to debug this using many different solutions, proposed in the issues above, but I haven't fixed it yet. All the solutions have either caused the deployment to error out, or didn't change anything.

The proposed solutions have been:
1. Use WebpackCopyPlugin to copy prisma client files in correct location
2. Use a postinstall script to generate prisma client manually
3. use a post build script to generate prisma client manually
4. Override `node.__dirname` to be false in production (for nextjs webpack config)
5. Move @prisma/cli to dependencies instead of devDependencies
6. Use WebpackPermissionsPlugin to change binary fileMode to `755` (for prisma client files)
7. Copy prisma client files to tmp during execution
8. Set `useServerlessTraceTarget: true` in serverless.yml
9. Change prisma output parameter so it's generated outside of node_modules
10. Try the latest alpha release of serverless-next.js

Again, none of these solutions have fixed it for me. If anyone has a workaround that will fix this universally, I would be very grateful!

Prisma client setup: 

```prisma
generator client {
  provider      = "prisma-client-js"
  binaryTargets = ["native", "rhel-openssl-1.0.x"]
}
```

- OS/Environment: macOS Catalina 10.15.1
- @sls-next/serverless-component version: 1.18.0 and latest alpha version
- Next.js version: 10.0.5
- prisma client version: 2.16.1
- prisma version: 2.16.1
- serverless components version: 3.4.2

serverless.yml
```yml
myNextApp:
  org: myOrg
  stage: prod
  component: "@sls-next/serverless-component@1.18.0" # it is recommended you pin the latest stable version of serverless-next.js
  inputs:
    bucketName: myApp-nextjs
    name: myApp
```

@achraf-boussaada, @jonahallibone, @vaskevich, @colinhacks seemed to be facing similar issues, so if any of you have ideas, that would be helpful!

**Comment by janpio** [comment] 2021-03-09 18:02
Possibly related: https://github.com/prisma/prisma/issues/6020

**Comment by s-kris** [comment] 2021-03-12 17:54
similar issue on netlify: https://github.com/prisma/prisma/issues/6051

**Comment by pantharshit00** [comment] 2021-03-18 12:00
Can you share a reproduction repository which we can use to test this out?

**Comment by jeremygottfried** [comment] 2021-03-18 17:23
I tried to create one, but now I can't even get it to deploy. I'm hitting a new error, which also seems to be caused by prisma:

> > Build error occurred
TypeError: debugLib is not a function
    at Object.<anonymous> (/Users/jeremygottfried/Development/nextjs-prisma-serverless-bug/nextjs-prisma-serverless-bug/.next/serverless/pages/index.js:3452:15)
    at Object.6Z5O (/Users/jeremygottfried/Development/nextjs-prisma-serverless-bug/nextjs-prisma-serverless-bug/.next/serverless/pages/index.js:3642:30)
    at __webpack_require__ (/Users/jeremygottfried/Development/nextjs-prisma-serverless-bug/nextjs-prisma-serverless-bug/.next/serverless/pages/index.js:23:31)
    at Object.<anonymous> (/Users/jeremygottfried/Development/nextjs-prisma-serverless-bug/nextjs-prisma-serverless-bug/.next/serverless/pages/index.js:41404:65)
    at Object.Kg+b (/Users/jeremygottfried/Development/nextjs-prisma-serverless-bug/nextjs-prisma-serverless-bug/.next/serverless/pages/index.js:41416:30)
    at __webpack_require__ (/Users/jeremygottfried/Development/nextjs-prisma-serverless-bug/nextjs-prisma-serverless-bug/.next/serverless/pages/index.js:23:31)
    at Object.1ygI (/Users/jeremygottfried/Development/nextjs-prisma-serverless-bug/nextjs-prisma-serverless-bug/.next/serverless/pages/index.js:1742:72)
    at __webpack_require__ (/Users/jeremygottfried/Development/nextjs-prisma-serverless-bug/nextjs-prisma-serverless-bug/.next/serverless/pages/index.js:23:31)
    at Module.23aj (/Users/jeremygottfried/Development/nextjs-prisma-serverless-bug/nextjs-prisma-serverless-bug/.next/serverless/pages/index.js:1768:69)
    at __webpack_require__ (/Users/jeremygottfried/Development/nextjs-prisma-serverless-bug/nextjs-prisma-serverless-bug/.next/serverless/pages/index.js:23:31) {
  type: 'TypeError'
}
info  - Loaded env from /Users/jeremygottfried/Development/nextjs-prisma-serverless-bug/nextjs-prisma-serverless-bug/.env
info  - Creating an optimized production build...
info  - Collecting page data...

https://github.com/jeremygottfried/nextjs-prisma-serverless-bug

If you can help me fix that error, then I can reproduce the original bug. I commented out the next-auth code in index.tsx, but ideally dependencies that use prisma should also work on serverless.

**Comment by s-kris** [comment] 2021-03-18 19:19
@jeremygottfried @pantharshit00 error seems to be consistent with #6051

**Comment by jeremygottfried** [comment] 2021-03-18 20:23
> @jeremygottfried @pantharshit00 error seems to be consistent with #6051

Yup that makes sense because I originally had the bug on prisma 2.16.1, but the new repo is on 2.19.0

**Comment by jdcookie** [comment] 2021-03-19 03:35
I am seeing the same issue just trying to run serverless:offline - nothing to do with serverless-nextjs
```
offline: GET /dev/hello (λ: hello)
offline: Failure: debugLib is not a function
TypeError: debugLib is not a function
```

**Comment by pantharshit00** [comment] 2021-03-19 06:39
I will consider this blocked by #6051, we will patch that first then we can have another look here and hopefully this will be fixed as well.

**Comment by jonahallibone** [comment] 2021-03-19 08:09
@jeremygottfried AFAIK the solution I mentioned in my issue still works, (even though it's not ideal depending on binary size). I haven't heard from anyone about how to preserve or change the permissions after then fact from your deploy script. I am wondering if a solution like [this](https://stackoverflow.com/questions/8756639/how-do-i-use-chmod-with-node-js) is possible to use instead of my copying to '/tmp' but I haven't tried it.

**Comment by millsp** [comment] 2021-05-10 20:24
I turns out that the binaries were not copied into the lambda. I have set a template up for [prisma + serverless-next.js](https://github.com/millsp/prisma-nextjs-serverlessnextjs) which adds a `postBuildCommands` script to do just that.

**Comment by pantharshit00** [comment] 2021-05-23 22:48
Hello everyone

Can you please also try reproducing this with the latest version?

**Comment by jeremygottfried** [comment] 2021-05-25 01:22
> Hello everyone
> 
> Can you please also try reproducing this with the latest version?

@pantharshit00 I think @KimPinot  was referring to the `debugLib` bug, not the "binary could not be found" issue.

**Comment by KimPinot** [comment] 2021-05-25 01:25
> > Hello everyone
> 
> > 
> 
> > Can you please also try reproducing this with the latest version?
> 
> 
> 
> @pantharshit00 I think @KimPinot  was referring to the `debugLib` bug, not the "binary could not be found" issue.

Oh sorry. I forgot to mention it.
Thanks.

Also. I used prisma '2.22.1'.

**Comment by millsp** [comment] 2021-06-08 22:31
Marking this as solved as it is a configuration problem

> I turns out that the binaries were not copied into the lambda. This could be solved by adding a script that triggers before upload. I have set a template up for [prisma + serverless-next.js](https://github.com/millsp/prisma-nextjs-serverlessnextjs) which adds a `postBuildCommands` (`serverless.yml`) script to do just that.

**Closed by millsp** 2021-06-08 22:31 UTC
Labels: bug/1-repro-available, kind/bug, team/client, topic: aws lambda, topic: binary, topic: nextjs, topic: prisma-client, topic: serverless, topic: serverless framework, topic: webpack
