### ISSUE TITLE
Full-text search does not work in count

### ISSUE THREAD

**Issue by hgeldenhuys** [prisma/prisma#11593] opened 2022-02-03 13:20 UTC
### Bug description

When full-text search is enabled, it works on a `findMany`, but the equivalent `count`, search is ignored.

### How to reproduce

```typescript

const where = { field: {search: "abc"} }

const count = await noun.count({ where })
const data = await noun.findMany({ where })

```

data will have fewer records than the count

### Expected behavior

Count should equal the same amount of records as findMany

### Prisma information

```
generator client {
  provider = "prisma-client-js"
  previewFeatures = ["fullTextSearch"]
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}
```

### Environment & setup

- OS: Any
- Database: PostgreSQL
- Node.js version: v16.13.0

### Prisma Version

```
prisma                  : 3.9.0
@prisma/client          : 3.9.0
Current platform        : darwin-arm64
Query Engine (Node-API) : libquery-engine bcc2ff906db47790ee902e7bbc76d7ffb1893009 (at node_modules/.pnpm/@prisma+engines@3.9.0-58.bcc2ff906db47790ee902e7bbc76d7ffb1893009/node_modules/@prisma/engines/libquery_engine-darwin-arm64.dylib.node)
Migration Engine        : migration-engine-cli bcc2ff906db47790ee902e7bbc76d7ffb1893009 (at node_modules/.pnpm/@prisma+engines@3.9.0-58.bcc2ff906db47790ee902e7bbc76d7ffb1893009/node_modules/@prisma/engines/migration-engine-darwin-arm64)
Introspection Engine    : introspection-core bcc2ff906db47790ee902e7bbc76d7ffb1893009 (at node_modules/.pnpm/@prisma+engines@3.9.0-58.bcc2ff906db47790ee902e7bbc76d7ffb1893009/node_modules/@prisma/engines/introspection-engine-darwin-arm64)
Format Binary           : prisma-fmt bcc2ff906db47790ee902e7bbc76d7ffb1893009 (at node_modules/.pnpm/@prisma+engines@3.9.0-58.bcc2ff906db47790ee902e7bbc76d7ffb1893009/node_modules/@prisma/engines/prisma-fmt-darwin-arm64)
Default Engines Hash    : bcc2ff906db47790ee902e7bbc76d7ffb1893009
Studio                  : 0.457.0
Preview Features        : fullTextSearch

```

**Comment by pantharshit00** [comment] 2022-02-04 12:00
Hello @hgeldenhuys 

This is not specific to `fullTextSearch` but we have a whole regression where `count` wasn't working in version `3.9.0`. Can you please try again with version `3.9.1`. 

I am going to close this as duplicate of https://github.com/prisma/prisma/issues/11556

If the problem persists, please comment here and we can reopen this.

**Closed by pantharshit00** 2022-02-04 12:00 UTC
Labels: kind/bug
