### ISSUE TITLE
Create queries using prisma helpers

### ISSUE THREAD

**Issue by Arlen22** [prisma/prisma#20198] opened 2023-07-12 21:27 UTC
## Problem

I occasionally need to write a custom SQL query, function, stored procedure, or trigger which always needs to be manually reviewed and tested to ensure that it is still functioning properly. In one case I needed to write a query which got all the customers unpaid charges in 30-day aggregate, which wasn't possible with the client. 

Now the query is outdated and I need to take the time to rewrite it from scratch to make sure I don't miss anything, but if just one field changed that could easily be missed. 

My primary use case for this would be to build guard triggers, since I need a way to throw errors if anything about my triggers change. 

## Suggested solution

It would be really useful if there was a way to generate SQL snippets using the standard JSON select and where formats so that compile-time errors would show up when the schema changes. Simple join queries with nested select statements and where statements with separate field references on each side of the operator would be equally useful. 

Ideally, Prisma should also be able to detect when the output changes and update the database as part of a migration, but that's probably a long way down the road. I'm not sure what the best solution is for joins in the meantime, and maybe just using a javascript Proxy that returns the joined path of field references would help.

## Alternatives

I don't really know that there is an alternative besides just writing the query myself, spinning my own type-guarded functions, or looking for another library to handle this specific part of the process.

**Comment by millsp** [comment] 2023-07-13 19:06
Hey @Arlen22, am I understanding correctly that you would like to have something like a type-safe query builder?

**Comment by Arlen22** [comment] 2023-07-14 13:08
I guess so? That sounds like it describes it pretty well. I want a way for things like where clauses and foreign key joins to be type safe, as well as the list of columns to select.

**Comment by Jolg42** [comment] 2023-07-31 07:59
Maybe duplicate of https://github.com/prisma/prisma/issues/13017?

**Comment by janpio** [comment] 2024-02-08 22:30
I indeed agree this would be a SQL Query Builder, so is tracked via #13017 already. 

Thanks for opening the issue @Arlen22! Make sure that all your requests are reflected in the other issue and make sure to follow it for updates.

**Closed by janpio** 2024-02-08 22:30 UTC
Labels: kind/feature, topic: raw, tech/typescript, team/client, topic: sql query builder
