### ISSUE TITLE
`RuntimeError: panicked at 'internal error: entered unreachable code', query-engine/prisma-models/src/field/scalar.rs:85:50`

### ISSUE THREAD

**Issue by UAHector** [prisma/prisma#18168] opened 2023-03-01 23:49 UTC
Hi Prisma Team! The following command just crashed.

## Command

`db push`

## Versions
      
| Name        | Version            |
|-------------|--------------------|
| Platform    | windows            | 
| Node        | v18.14.2           | 
| Prisma CLI  | 4.11.0             | 
| Engine      | 8fde8fef4033376662cad983758335009d522acb| 

## Error
```
Error: RuntimeError: panicked at 'internal error: entered unreachable code', query-engine/prisma-models/src/field/scalar.rs:85:50
```

**Comment by janpio** [comment] 2023-03-02 00:54
Thanks @UAHector. Can you provide some more information that might allow us to reproduce the query that crashed for you? Thanks.

**Comment by Jolg42** [comment] 2024-03-07 08:50
Let us know if you have anything that could help us reproduce this.
See Jan's comment, additionally the database provider would be helpful.

Since this is old, I will close it, we're happy to reopen later if needed.

**Closed by Jolg42** 2024-03-07 08:50 UTC
Labels: bug/0-unknown, kind/bug, team/client, topic: basic error report, topic: entered unreachable code
