### ISSUE TITLE
prisma instance from transaction does not inherit config

### ISSUE THREAD

**Issue by henriqueArrazao** [prisma/prisma#10886] opened 2021-12-28 15:14 UTC
```ts
new PrismaClient({
  log: ["query"],
  rejectOnNotFound: false,
});
```

```ts
ctx.prisma.$transaction<User | null>(async (prisma) => {
  user = await prisma.user.upsert({
          create: {
            [...]
          },
          update: {},
          where: {
             [...]
          },
        });
});
```

error
```
An operation failed because it depends on one or more records that were required but not found. Record to update not found.
```

This error occurs only when using "prisma.$transaction" with "interactiveTransactions" enabled, probably a bug.

**Comment by janpio** [comment] 2022-01-03 12:51
Do I understand correctly that you would expect `rejectOnNotFound: false` to apply to the `prisma.user.upsert` call?

**Comment by millsp** [comment] 2022-02-08 20:14
Hey @henriqueArrazao, `upsert` should be successful even when the `where` clause did not match any records. The result you posted looks like a typical error coming from `update`. I have tried to put a reproduction up but with no success:

```ts
  const prisma = new PrismaClient({
    log: ["query"],
    rejectOnNotFound: false,
  });

  const user = await prisma.$transaction(async (prisma) => {
    const users = await prisma.user.upsert({
      create: {
        email:  Date.now() + "c",
      },
      update: {
        email:  Date.now() + "u",
      },
      where: {
        email: 'email',
      }
    });

    return users
  })

  console.log(user);

  prisma.$disconnect();
```

I do get your error if I use `update`, but fails the same way regardless of `rejectOnNotFound` or `interactiveTransaction`. I am closing this issue as the tx instance does inherit from the config. Feel free to re-open with more information, or ping me for any help. Thank you!

**Closed by millsp** 2022-02-08 20:14 UTC
Labels: bug/0-unknown, kind/bug, tech/typescript, topic: transaction, team/client, topic: interactiveTransactions
