### ISSUE TITLE
Prisma Migrate just crashed. 

### ISSUE THREAD

**Issue by raghuthakur683** [prisma/prisma#5460] opened 2021-02-04 08:24 UTC
Hi Prisma Team! Prisma Migrate just crashed. 

## Versions
      
| Name        | Version            |
|-------------|--------------------|
| Platform    | debian-openssl-1.1.x| 
| Node        | v10.19.0           | 
| Prisma CLI  | 2.15.0             | 
| Binary      | e51dc3b5a9ee790a07104bec1c9477d51740fe54| 

## Error
```
Error: Error in migration engine.
Reason: [/root/build/migration-engine/core/src/commands/diagnose_migration_history.rs:101:26] Failed to read migration script: ReadMigrationScriptError(Os { code: 2, kind: NotFound, message: "No such file or directory" }, SpanTrace [{ target: "migration_connector::migrations_directory", name: "read_migration_script", fields: "self=MigrationDirectory { path: \"/var/www/html/lifology_backend/prisma/migrations/20210202091637_\" }", file: "migration-engine/connectors/migration-connector/src/migrations_directory.rs", line: 235 }, { target: "migration_connector::migrations_directory", name: "matches_checksum", fields: "self=MigrationDirectory { path: \"/var/www/html/lifology_backend/prisma/migrations/20210202091637_\" } checksum_str=\"138407d0e3bf9bb0ec5b9724c2fa4c3a6b894682b52135f8b936279ba124\"", file: "migration-engine/connectors/migration-connector/src/migrations_directory.rs", line: 209 }, { target: "migration_core::api", name: "DevDiagnostic", file: "migration-engine/core/src/api.rs", line: 100 }])

Please create an issue in the migrate repo with
your `schema.prisma` and the prisma command you tried to use 🙏:
https://github.com/prisma/prisma/issues/new

```

**Comment by pantharshit00** [comment] 2021-02-04 12:42
Looks like duplicate of https://github.com/prisma/prisma/issues/5459

Can you provide a reproduction for this please?

**Comment by tomhoule** [comment] 2021-02-11 10:25
Hi @raghuthakur683 — starting in 2.17.0, we will return a better error there. This happens when the `migration.sql` was deleted but not the parent folder. The solution is to delete the empty folder.

**Closed by tomhoule** 2021-02-11 10:25 UTC
Labels: bug/0-needs-info, kind/bug, team/migrations, topic: basic error report
