### ISSUE TITLE
Prisma delete fails with remote deployments

### ISSUE THREAD

**Issue by kainolophobia** [prisma/prisma#4581] opened 2019-05-24 21:47 UTC
**Describe the bug**
`prisma delete -f` appears to do nothing for remote deployments, even though it appears successful on the command line. 
 
When attempting to run a remote deploy after calling `prisma delete -f` we would expect to see migrations run, however we instead see:
```bash
Service is already up to date.
```

**To Reproduce**
1. Create a remote Prisma service (we're using Docker in AWS, tied to an RDS Postgres instance)
2. Deploy Prisma service
3. Run `prisma delete -f`
```shell
Deleting service REMOTE_HOST from default 655ms
```
4. See that Postgres schema and tables still exist

**Expected behavior**
When running locally, calling `prisma delete` removes the Postgres schema and tables. We expect this behavior to work the same for remote hosts. Furthermore, if the command isn't successful, we would expect to receive an error. 

**Versions (please complete the following information):**
 - Connector: `Postgres`
 - Prisma Server: `1.33.0`
 - `prisma` CLI: `prisma/1.33.0 (darwin-x64) node-v11.12.0`
 - OS: Local: `OS X High Sierra` Remote: `Amazon Linux AMI` running Docker with the `prismagraphql/prisma:1.33` image

**Additional context**
When running `prisma delete` without the `--force` flag, we run into the following error:
```shell
? Are you sure that you want to delete REMOTE_HOST? y/N y
Deleting service REMOTE_HOST from default !

ERROR: GraphQL Error (Code: 400)

{
  "error": "<!DOCTYPE html>\n<html>\n  <head>\n    <meta charset=\"utf-8\">\n    <title>Bad Request – 400</title>\n    <style>\n      html, body {\n        margin: 0;\n        width: 100%;\n        height: 100%;\n        display: flex;\n        justify-content: center;\n        align-items: center;\n      }\n\n      body {\n        font-family: -apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, Helvetica, Arial, sans-serif, \"Apple Color Emoji\", \"Segoe UI Emoji\", \"Segoe UI Symbol\";\n        font-size: 15px;\n      }\n\n      .Error {\n        font-size: 1.35em;\n        \n          color: #6061BE;\n        \n      }\n\n      .Error .message {\n        font-weight: 200;\n        letter-spacing: 0.095em;\n      }\n\n      .Error .message a {\n        text-decoration: none;\n        color: inherit;\n        \n          border-bottom: 1px dotted #6061BE;\n        \n      }\n\n      .Error .status {\n        font-weight: 700;\n      }\n\n      .Error .code {\n        display: none;\n      }\n\n      .Error .dot {\n        font-weight: 100;\n      }\n\n      @media screen and (max-width: 800px) {\n        body {\n          font-size: 10px;\n        }\n\n        .Error {\n          display: flex;\n          flex-direction: column;\n        }\n\n        .Error .status {\n          font-size: 1.1em;\n        }\n\n        .Error .dot {\n          display: none\n        }\n      }\n    </style>\n  </head>\n  <body>\n    <div class=\"Error\">\n      <span class=\"status\">Bad Request</span>\n      <span class=\"code\">400</span>\n      <span class=\"dot\">•</span>\n      \n        <span class=\"message\">Please try your request again or contact support.</span>\n      \n    </div>\n  </body>\n</html>",
  "status": 400
}
```

**Possibly related issues**
https://github.com/prisma/prisma/issues/4312
https://github.com/prisma/prisma/issues/4451
https://github.com/prisma/prisma/issues/2303

**Comment by pantharshit00** [comment] 2019-05-28 17:24
I think this is duplicate of #4451 that Prisma is not deleting the db. For now, delete it manually.

**Closed by pantharshit00** 2019-05-28 17:24 UTC

**Comment by omar-dulaimi** [comment] 2020-03-27 16:19
> I think this is duplicate of #4451 that Prisma is not deleting the db. For now, delete it manually.

how???
