### ISSUE TITLE
`[2] InterpretationError("Error for binding \'4\': DomainError(ConversionFailure(\"record identifier\", \"assimilated record identifier\"))")` (after upgrade to beta)

### ISSUE THREAD

**Issue by chrisdrackett** [prisma/prisma#2029] opened 2020-04-01 04:39 UTC
I recently upgraded from the alpha to beta and followed the migration guides. When I start my app however I get the following error:

```
[2] Invalid `prisma.log.upsert()` invocation in
[2] /Users/cwd/src/calm/server/src/schema/Log.ts:34:29
[2] 
[2] Error occurred during query execution:
[2] InterpretationError("Error for binding \'4\': DomainError(ConversionFailure(\"record identifier\", \"assimilated record identifier\"))")
[2]     at PrismaClientFetcher.request (/Users/cwd/src/calm/node_modules/@prisma/client/runtime/index.js:1:51485)
[2]     at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

I'm guessing I've missed something in my schema, but if I run an introspection it looks the same to me. More than anything I feel like the above error could possibly be more helpful :D

anyways, here is my current schema:

```
datasource postgresql {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

generator client {
  provider = "prisma-client-js"
  output   = "../node_modules/@prisma/client"
}

model User {
  id           String    @default(cuid()) @id
  createdAt    DateTime  @default(now())
  updatedAt    DateTime  @updatedAt

  fireIdDev    String?   @unique
  fireIdStage  String?   @unique
  fireIdProd   String?   @unique

  name         String?
  email        String    @unique

  logs         Log[]     @relation("UserLogs")
  projects     Project[] @relation("CreatedProjects")

  items        Item[]    @relation("OwnedItems")
  itemsCreated Item[]    @relation("CreatedItems")
}

model Item {
  id             String    @default(cuid()) @id
  createdAt      DateTime  @default(now())
  updatedAt      DateTime  @updatedAt
  isDeleted      Boolean   @default(false)
  deletedAt      DateTime?

  // User relationships
  creator        User      @relation("CreatedItems", fields: [creatorId], references: [id])
  creatorId      String

  owner          User      @relation("OwnedItems", fields: [ownerId], references: [id])
  ownerId        String

  // Item info
  title          String?
  type           ItemType

  // Meta info
  checkIn        CheckIn?  @relation("ItemCheckin", fields: [checkInId], references: [id])
  checkInId      String?   @unique

  // Where does this item live
  log            Log?      @relation("ItemLog", fields: [logId], references: [id])
  logId          String?

  project        Project?  @relation("ItemProject", fields: [projectId], references: [id])
  projectId      String?

  // Timeline
  previousItem   Item?     @relation("PreviousNext", fields: [previousItemId], references: [id])
  nextItem       Item?     @relation("PreviousNext")
  previousItemId String?   @unique

  lastItem       Item?     @relation("ItemHistory", fields: [lastItemId], references: [id])
  history        Item[]    @relation("ItemHistory")
  lastItemId     String?

  // Task Fields
  isComplete     Boolean   @default(false)
  completedAt    DateTime?
}

model Log {
  id        String   @id
  createdAt DateTime @default(now())
  updatedAt DateTime @updatedAt

  owner     User     @relation("UserLogs", fields: [ownerId], references: [id])
  ownerId   String

  type      LogType
  date      String

  items     Item[]   @relation("ItemLog")
}

model Project {
  id        String    @default(cuid()) @id
  createdAt DateTime  @default(now())
  updatedAt DateTime  @updatedAt
  isDeleted Boolean   @default(false)
  deletedAt DateTime?

  title     String

  creator   User      @relation("CreatedProjects", fields: [creatorId], references: [id])
  creatorId String

  items     Item[]    @relation("ItemProject")
}

model CheckIn {
  id        String   @default(cuid()) @id
  createdAt DateTime @default(now())
  updatedAt DateTime @updatedAt

  item      Item?    @relation("ItemCheckin")

  latitude  Float
  longitude Float

  location  String?
  weather   String?
}

enum ItemType {
  A
  B
  C
  D
}

enum LogType {
  A
  B
  C
}
```

**Comment by alexvilchis** [comment] 2020-04-01 05:10
I have the same issue when migrating from `preview25` to `beta`

**Comment by SameerChorge94** [comment] 2020-04-01 05:15
I have the same issue for normal mutation also

**Example:**
```
prisma.post.create({
    data: {
        title :"User1 First Post",
        User : {
            create: {
                FirstName : "user2"
            }
        }
    }
}).then((createdPost) => {
    console.log("createdPost");
    console.dir(createdPost);
});
```

**Comment by janpio** [comment] 2020-04-01 07:47
@chrisdrackett Can you please share your Client query that is causing this?

**Comment by pantharshit00** [comment] 2020-04-01 14:49
Yes, please share a complete reproduction, preferably in a git repository.

**Comment by chrisdrackett** [comment] 2020-04-01 16:19
ok, I think I figured this out (for me anyways). I think I had forgotten to run `generate` after updating my models. This wasn't super apparent as everything in the app appears to work even without a generate, but I'm guessing this is because the alpha and beta schema are very close to the same all things considered.

**Comment by jayanth1991** [comment] 2020-04-01 21:17
I have the same issue with `upsert` as well
- `schema.prisma`
```prisma
datasource mysql {
  provider = "mysql"
  url      = env("DATABASE_URL")
}

generator client {
  provider = "prisma-client-js"
}

model Vendor {
  id        Int      @id @default(autoincrement())
  email     String   @unique
  imageUrl String?
  name      String?
  role      Role     @default(VENDOR)
  vendorStrings     VendorString[]
  createdAt DateTime @default(now())
  updatedAt DateTime @updatedAt
}

model VendorString {
  id         Int        @id @default(autoincrement())
  createdAt  DateTime   @default(now())
  updatedAt  DateTime   @updatedAt
  name      String  @unique
  associatedVendor     Vendor?      @relation(references: [id])
}
```

- `resolver.js`
```js
async upsertVendor(root, { input }, { prisma, internalAuth }) {
      if (!internalAuth) {
        throw new AuthenticationError('User must authentcate');
      }

      const { email, vendorStrings, name } = input;
      const vendor = await prisma.vendor.upsert({
        where: {
          email
        },
        update: {
          email,
          name
        },
        create: {
          email,
          name
        }
      });


      const vendorStringConnect = await vendorStrings.map(async s => prisma.vendorString.upsert(
        {
          where: {
            name: s
          },
          update: {
            name: s,
            associatedVendor: {
              connect: {
                email: vendor.email
              }
            }
          },
          create: {
            name: s,
            associatedVendor: {
              connect: {
                email: vendor.email
              }
            }
          }
        }
      ));
      await Promise.all(vendorStringConnect);
      return vendor;
    }
```

The `prisma.vendor.upsert` works with no errors `prisma.vendorString.upsert` fails with this error:
```sh
Invalid `prisma.vendorString.upsert()` invocation in
C:\Documents\vendordashboard\src\graphql\accounts\resolver.js:62:90

Error occurred during query execution:
InterpretationError("Error for binding \'2\': DomainError(ConversionFailure(\"record identifier\", \"assimilated record identifier\"))")]
```

On Windows.

**Comment by jayanth1991** [comment] 2020-04-01 22:42
I am also quite a bit confused about the relationship not being reflected in the DB when i use `prisma migrate up --experimental`
```mysql
mysql> describe Vendor;
+-----------+------------------------+------+-----+-------------------+----------------+
| Field     | Type                   | Null | Key | Default           | Extra          |
+-----------+------------------------+------+-----+-------------------+----------------+
| createdAt | datetime               | NO   |     | CURRENT_TIMESTAMP |                |
| email     | varchar(191)           | NO   | UNI | NULL              |                |
| id        | int(11)                | NO   | PRI | NULL              | auto_increment |
| imageUrl  | varchar(191)           | YES  |     | NULL              |                |
| name      | varchar(191)           | YES  |     | NULL              |                |
| role      | enum('VENDOR','ADMIN') | NO   |     | VENDOR            |                |
| updatedAt | datetime(3)            | NO   |     | NULL              |                |
+-----------+------------------------+------+-----+-------------------+----------------+
7 rows in set (0.00 sec)

mysql> describe VendorString;
+-----------+--------------+------+-----+-------------------+----------------+
| Field     | Type         | Null | Key | Default           | Extra          |
+-----------+--------------+------+-----+-------------------+----------------+
| createdAt | datetime     | NO   |     | CURRENT_TIMESTAMP |                |
| id        | int(11)      | NO   | PRI | NULL              | auto_increment |
| name      | varchar(191) | NO   | UNI | NULL              |                |
| updatedAt | datetime(3)  | NO   |     | NULL              |                |
+-----------+--------------+------+-----+-------------------+----------------+
4 rows in set (0.00 sec)
```

Where is the `associatedVendor`?

**Comment by janpio** [comment] 2020-04-01 23:01
Please open a new issue for the second problem @jayanth1991 and include all the information to investigate your problem on its own. Thanks.

**Comment by alexvilchis** [comment] 2020-04-02 15:47
@chrisdrackett Re-generating the client didn't fix it for me. Did you do anything else?

**Comment by jayanth1991** [comment] 2020-04-02 15:50
I was able to resolve my issues by following @janpio suggestion on a different issue.

Modify your `schema.prisma` model relations to the ones described here: https://github.com/prisma/prisma/releases/tag/2.0.0-beta.1

**Comment by alexvilchis** [comment] 2020-04-02 18:24
@jayanth1991 Thank you, I read it and it seems to be fixed for now.

**Comment by hatchli** [comment] 2020-04-06 17:53
Fixed it for me as well! Thanks @jayanth1991 (and @janpio )!

**Comment by pantharshit00** [comment] 2020-04-08 06:24
Closing this now as this seems to be fixed for all posters.

Please open a new issue if you are still facing this.

**Closed by pantharshit00** 2020-04-08 06:24 UTC
Labels: bug/0-needs-info, kind/bug
