### ISSUE TITLE
`prisma-lib` should work without `graphql` dependency

### ISSUE THREAD

**Issue by nikolasburk** [prisma/prisma#2975] opened 2018-08-29 17:40 UTC
**Is your feature request related to a problem? Please describe.**

Currently it's required to install the `graphql` dependency to use `prisma-lib`.

**Describe the solution you'd like**

Don't requite installing the `graphql` dependency to use `prisma-lib`.

**Comment by schickling** [comment] 2018-11-17 19:16
Duplicate of #3201

**Closed by schickling** 2018-11-17 19:16 UTC
Labels: component/client/js, kind/discussion
