### ISSUE TITLE
`ConnectionError(Timed out during query execution.)` error when using `Promise.all` for SQLite

### ISSUE THREAD

**Issue by kyuhakyuk** [prisma/prisma#11789] opened 2022-02-13 18:59 UTC
### Bug description

Just like the title explains,, when I use Promise.all to delete (in my case), it throws timed out error.

Never had the same issue with other db such as postgres and mysql.  But for sqlite, i am getting this issue.

Is there any workaround or legit solution that I am not aware of for this error?

### How to reproduce

```
model Category {
  id                          String                      @id @default(cuid())
  description                 String?
  name                        String                      @unique
  slug                        String                      @unique
  // *************** RELATIONS *****************
  subcategories               Category[]                  @relation("SuperCategoriesSubCategories", references: [id])
  supercategories             Category[]                  @relation("SuperCategoriesSubCategories", references: [id])
  // *******************************************
  createdAt                   DateTime                    @default(now())
  updatedAt                   DateTime                    @default(now())
  deletedAt                   DateTime?
}
```

```
// For front
Promise.all([
  ...send multiple delete request
])
```

```
// For backend
prisma.category.delete({
      where: {
        id,
      }
})
```

### Expected behavior

Delete all passed categories

### Environment & setup

- OS: 
- Database: 
- Node.js version: 

### Prisma Version

```
3.9.2
```

**Comment by janpio** [comment] 2022-02-14 10:43
Is it possible this was previously reported under https://github.com/prisma/prisma/issues/9562? Can you please check?

**Comment by janpio** [comment] 2022-09-09 22:11
Note: there are multiple issues about this now all grouped under https://github.com/prisma/prisma/issues?q=is%3Aissue+is%3Aopen+label%3A%22topic%3A+Timed+out+during+query+execution%22 One of them is https://github.com/prisma/prisma/issues/10403 which points out that our error message here is currently highly misleading and should be changed/fixed.

**Comment by gengjiawen** [comment] 2023-06-28 03:34
Same here prisma 4.16.1 with sqlite as driver.

**Comment by richtermb** [comment] 2023-06-28 19:11
> Same here prisma 4.16.1 with sqlite as driver.

@gengjiawen did you end up resolving this?

**Comment by gengjiawen** [comment] 2023-06-29 01:22
> > Same here prisma 4.16.1 with sqlite as driver.
> 
> @gengjiawen did you end up resolving this?

Nope, I changed db driver to mysql, problem goes away.

**Comment by Polo123456789** [comment] 2023-06-29 16:38
@gengjiawen Thanks

**Comment by Weakky** [comment] 2023-07-13 12:44
Internal note: A lot of similar issues are grouped into [this cluster](https://github.com/prisma/prisma/issues?q=is%3Aissue+is%3Aopen+label%3A%22topic%3A+Timed+out+during+query+execution%22+sort%3Aupdated-desc.). https://github.com/prisma/prisma/issues/9562 Looks like a good candidate for reproduction.

**Comment by edge-rps** [comment] 2023-07-29 21:17
Update ✅: After hours of troubleshooting Prisma and Drizzle, I tried [Sequelize](https://github.com/sequelize/sequelize) and found out it works flawlessly with SQLITE and also supports WAL mode via a query command. 


```
import {
    Sequelize,
    DataTypes
} from "sequelize";

const sequelize = new Sequelize({
    dialect: "sqlite",
    storage: "test.db", // Replace with the path to your SQLite database file
});

const User = sequelize.define("User", {
    username: DataTypes.STRING,
    birthday: DataTypes.DATE,
});

// migrate schema to file
await User.sync();

// enable wal mode (optional)
await sequelize.query("PRAGMA journal_mode=WAL;");

const jane = await User.create({
    username: "janedoe",
    birthday: new Date(1980, 6, 20),
});

const users = await User.findAll();

console.log(jane.username, users.length);
```

**Comment by Nedi11** [comment] 2023-08-16 08:07
Bump

**Comment by luluhoc** [comment] 2023-09-29 17:13
5.2.0 still getting the same error with sqlite

**Comment by fwRelik** [comment] 2023-10-03 14:00
@luluhoc 
There may be other processes working with the database, I had the same problem. 
After terminating the unnecessary process, the problem was solved.

**Comment by birgersp** [comment] 2023-11-13 10:19
Getting the same error on my end. But I am not using Promise.all. I am calling `myClient.$transaction` multiple times. I guess they are trying to run in parallell and Prisma doesn't play nice with paralell requests on SQLite... ?

**Comment by is-it-ayush** [comment] 2023-11-21 04:08
Can confirm, the issue occurs on the usage of `$transaction` with SQLite if you use more than one `$transaction` or many individual changes inside `$transaction`. I don't really have to anything to add expect I too suspect prisma isn't playing well with SQLite.

**Comment by zaquas77** [comment] 2023-11-25 18:08
Hi, I have the same problem with sqlite/prisma and express. I expose my update procedure through a router in express. When called in the same time for different record, prisma and sqlite throw the error.

For now the only thing that mitigate the problem it been put the route in syncronic  mode trought a middleware but in this way I lost the performace of node and express.

**Comment by valerius21** [comment] 2023-11-26 20:31
I can confirm this issue exists when invoking a `delete()` procedure in express and elysia js

**Comment by crishoj** [comment] 2023-11-28 22:07
In case it's helpful to anyone affected by this: 

A workaround until the issue is fixed appears to be enabling WAL mode in SQLite _and_ appending `?connection_limit=1` to the connection string in `schema.prisma`. See https://github.com/prisma/prisma/issues/10403#issuecomment-1500770484 for details.

**Comment by zaquas77** [comment] 2023-11-29 07:07
Hi @crishoj what you suggest is correct if you open the file only one time and maintain open for all write or update. But, as in my case, if you have to opened and closed ripetuttaly the file the problem is araise again.

In this way it works
```
const prisma = new PrismaClient();
async function updatetUser(id: number) {
  let user: User;
  try {
    user = await prisma.user.update({
      where: {id,},
      data: {email: `${crypto.randomUUID()}@test.it`},
    });
  } catch (error) {
    console.log(error);
  } finally {
   // await prisma.$disconnect();
  }
  return user;
}
```
in this way not
```
async function updatetUser(id: number) {
  let user: User;
  const prisma = new PrismaClient();
  try {
    user = await prisma.user.update({
      where: {id,},
      data: {email: `${crypto.randomUUID()}@test.it`},
    });
  } catch (error) {
    console.log(error);
  } finally {
   await prisma.$disconnect();
  }
  return user;
}
```

thanks for your suggest

**Comment by Jolg42** [comment] 2024-01-19 17:02
I found out, after reproducing this error with concurrent queries in https://github.com/prisma/prisma/pull/22723

That `?connection_limit=1` to the `url` made this error disappear -> The queries were failing and are successful with the added parameter.

Example
```prisma
generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "sqlite"
  url      = "file:./dev.db?connection_limit=1"
}
```

If you try that, let us know if that works for you, or not, we're curious to hear from you 🙌🏼

**Comment by Jolg42** [comment] 2024-01-19 17:13
I'm closing this issue as a duplicate of https://github.com/prisma/prisma/issues/9562

**Closed by Jolg42** 2024-01-19 17:13 UTC
Labels: bug/2-confirmed, kind/bug, topic: sqlite, team/client, topic: Promise.all, topic: Timed out during query execution
