### ISSUE TITLE
Cannot access engine inside vercel/pkg

### ISSUE THREAD

**Issue by wallkie** [prisma/prisma#8449] opened 2021-07-23 15:07 UTC
Dear community, 

I'm having a problem to use prisma inside a [vercel/pkg](https://github.com/vercel/pkg) in which i'm getting an `ENOENT` error like:
```
spawn /snapshot/enoent-problem/node_modules/.prisma/client/query-engine-debian-openssl-1.1.x ENOENT 
```
To narrow down the issue i've created a sample application [here](https://github.com/wallkie/enoent-problem)

## To reproduce the issue:
I'm running the packaged app as :
```sh
npm i
npx prisma generate
npx pkg package.json --debug --output bin/exe > log-pkg.log
env -i DEBUG_PKG=1 bin/exe
```
and getting the following error 
```
spawn called cwd: <exec_path>/enoent-problem and dirname: /snapshot/enoent-problem
[Arguments] {
  '0': '/snapshot/enoent-problem/node_modules/.prisma/client/query-engine-debian-openssl-1.1.x',
  '1': [ 'cli', 'get-config' ],
  '2': {
    maxBuffer: 100000000,
    buffer: true,
    stripFinalNewline: true,
    extendEnv: true,
    preferLocal: false,
    localDir: '/snapshot/enoent-problem/node_modules/.prisma/client',
    execPath: '<exec_path>/enoent-problem/bin/exe-node16-linuxstatic',
    encoding: 'utf8',
    reject: true,
    cleanup: true,
    all: false,
    windowsHide: true,
    env: {
      DATABASE_URL: 'postgresql://postgres:postgres@localhost:5432/<table_name>?schema=public',
      PRISMA_DML_PATH: '/snapshot/enoent-problem/node_modules/.prisma/client/schema.prisma',
      RUST_BACKTRACE: '1',
      RUST_LOG: 'info',
      LOG_QUERIES: 'true',
      OVERWRITE_DATASOURCES: '[]'
    },
    cwd: '/snapshot/enoent-problem/node_modules/.prisma/client',
    stdio: [ undefined, undefined, undefined ]
  }
}
spawn called cwd: <exec_path>/enoent-problem and dirname: /snapshot/enoent-problem
[Arguments] {
  '0': '/snapshot/enoent-problem/node_modules/.prisma/client/query-engine-debian-openssl-1.1.x',
  '1': [ '--enable-raw-queries', '--port', '33491' ],
  '2': {
    env: {
      DATABASE_URL: 'postgresql://postgres:postgres@localhost:5432/<table_name>?schema=public',
      PRISMA_DML_PATH: '/snapshot/enoent-problem/node_modules/.prisma/client/schema.prisma',
      RUST_BACKTRACE: '1',
      RUST_LOG: 'info',
      LOG_QUERIES: 'true',
      OVERWRITE_DATASOURCES: '[]'
    },
    cwd: '/snapshot/enoent-problem/node_modules/.prisma/client',
    windowsHide: true,
    stdio: [ 'ignore', 'pipe', 'pipe' ]
  }
}
prisma:error  in Could not start query engine
spawn /snapshot/enoent-problem/node_modules/.prisma/client/query-engine-debian-openssl-1.1.x ENOENT
Error:  PrismaClientKnownRequestError2 [PrismaClientKnownRequestError]: 
Invalid `prisma.challenge.findMany()` invocation:


  spawn /snapshot/enoent-problem/node_modules/.prisma/client/query-engine-debian-openssl-1.1.x ENOENT
    at cb (/snapshot/enoent-problem/node_modules/@prisma/client/runtime/index.js:34800:17)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  code: 'ENOENT',
  clientVersion: '2.27.0',
  meta: undefined
}
```
I've confirmed that binary has been copied inside the pkg (with `pkg --debug`) and make sure it's there in virtual fs (with `DEBUG_PKG=1` env) but still couldn't figure out the cause of the error. And I can execute the same app without and problem outside pkg with `npm start` or spawn other binaries inside pkg. I tried so far:
- To specify `PRISMA_QUERY_ENGINE_BINARY` outside pkg
- Different engines and different pkg targets but no dice.

So I'd appreciate if you can help me to figure out what the binary compatibility problem in pkg environment is. Thanks!

**Comment by steebchen** [comment] 2021-07-26 15:38
@wallkie Did you try specifying all engines? That means query engine, migration engine, introspection engine, and also prisma-fmt. That's what we're doing right now and what should work.

**Comment by wallkie** [comment] 2021-07-26 15:40
@steebchen `prisma generate` only downloads query engine binary. Should I point other env vars to the same binary?

**Comment by steebchen** [comment] 2021-07-26 15:47
I'm not sure if that would work or not, you can surely give it a shot. AFAIK all engines are downloaded on Prisma install though, so they should be in node_modules

**Comment by steebchen** [comment] 2021-07-26 15:50
BTW, I'm curious about your use-case, if you're open to share that

**Comment by janpio** [comment] 2021-07-26 18:20
> But still getting the `ENOENT` exception. So I'm suspecting something in `engine` binary blocking the call.

Our Engines don't do anything like that, it is more probably that something inside pkg does not know how to handle how to call a binary or resolve that path.

The Go Client, which uses pkg to package the CLI, downloads all Engines manually and sets the environment variables (https://www.prisma.io/docs/reference/api-reference/environment-variables-reference#binary-environment-variables) to known paths outside of the package CLI - that seems to work. 

(We currently suspect that our e2e tests for pkg only work, as the temporary location where pkg parks the files when creating the package, is still present when we execute the test: https://github.com/prisma/e2e-tests/tree/dev/binaries/pkg)

**Comment by wallkie** [comment] 2021-07-26 22:19
@janpio Thanks for your response and information. Using binary generated by pkg I can execute the following block:
```js
const cp = require("child_process");
const t = process.env.PRISMA_QUERY_ENGINE_BINARY;
cp.spawn(t, ['-V']).stdout.pipe(process.stdout);
```
and get binary version `query-engine cdba6ec525e0213cce26f8e4bb23cf556d1479bb` without problem. Which proves pkg can invoke the binary. My previous `spawn` attempt  [below](#issuecomment-886480269) was using a wrong link. 

After checking your e2e test I tried with `node12-linux` target but still query attempt through PrismaClient generates `ENOENT` error. The only difference I can see in between is e2e test calling pkg command with input `node_modules/prisma` while I'm providing `package.json` as input. (which follows bin as `index.js` as entrypoint). So is there any chance PrismaClient generated before pkg interferes path resolution even if environment variables are correct? 

@steebchen We'd like to use prisma as an ORM for a backed application using psql db. For security and portability reasons we're deploying node based services as single binaries to prod.

**Comment by hughobrien** [comment] 2021-07-28 01:01
possibly related pkg issue](https://github.com/vercel/pkg/issues/342) I think pkg may have issues with spawn calls.

**Comment by hughobrien** [comment] 2021-07-28 03:13
the `hello-prisma` example from the getting [started page](https://www.prisma.io/docs/getting-started/setup-prisma/start-from-scratch/relational-databases-typescript-postgres) with @wallkie 's spawn trick

```typescript
import { PrismaClient } from '@prisma/client'

const prisma = new PrismaClient()

const cp = require("child_process");
const t = process.env.PRISMA_QUERY_ENGINE_BINARY;
cp.spawn(t, ['-V']).stdout.pipe(process.stdout);

async function main() {
 await prisma.user.create({
    data: {
      name: 'Alice',
      email: 'alice@prisma.io',
```

```tsc --build
pnpx pkg --targets=node16-alpine-x64 --output pkgbin dist/index.js
```
`move pkgbin into an alpine:3.11 container`

```bash
/ # PRISMA_QUERY_ENGINE_BINARY=/app/query-engine-linux-musl /app/pkgbin
query-engine cdba6ec525e0213cce26f8e4bb23cf556d1479bb
node:internal/process/promises:246
          triggerUncaughtException(err, true /* fromPromise */);
          ^

Error: spawn /app/query-engine-linux-musl ENOENT
    at Process.ChildProcess._handle.onexit (node:internal/child_process:282:19)
    at onErrorNT (node:internal/child_process:480:16)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'spawn /app/query-engine-linux-musl',
  path: '/app/query-engine-linux-musl',
  spawnargs: [ '--enable-raw-queries', '--port', '36877' ]
}
/ #
```

**Comment by janpio** [comment] 2021-07-29 12:23
(Honestly, you lost me along the way somewhere. We are aware our use of `pkg` is pretty crappy, but could never figure it out how to really improve and fix it - so if you have a better understanding how it works and what it does - or what we could do to improve this ourselves, please help us out here. Would be very welcome.)

**Comment by hughobrien** [comment] 2021-08-03 02:35
I think your `getPrismaPath` method returns an absolute path, certainly if it's set by an envvar, so I think if you remove the cwd flag from the spawn call (linked above) it should unbreak pkg without breaking any existing integration.

**Comment by hughobrien** [comment] 2021-08-03 02:37
What's happening (IMO), is that the cwd is within pkg's snapshot/virtual FS, but the query engine is external. I think the current implementation (with `cwd`) is unintentionally preventing the spawn call from accessing the binary.

**Comment by janpio** [comment] 2021-08-04 18:34
Without looking at the code: Wouldn't that mean that using the env var should _never_ work ever?

**Comment by hughobrien** [comment] 2021-08-06 23:30
I'm not sure we're talking about the same thing :( 

[THIS](https://github.com/vercel/pkg/issues/342#issuecomment-386904763) appears to be another instance of the issue, which seems mostly to be due to pkg. 

```text
Executing anything outside actually works as expected as long as you either omit cwd or specify an absolute path outside the snapshot file system.```

I don't know why the absolute path fails for us, perhaps it's being influenced/reinterpreted in the context of the cwd.

**Comment by hughobrien** [comment] 2021-08-06 23:39
here's a pithy attempt: https://github.com/prisma/prisma/pull/8634

**Comment by garrensmith** [comment] 2022-08-09 05:03
I'm closing this. Our documentation has been updated.

**Closed by garrensmith** 2022-08-09 05:03 UTC
Labels: team/support-engineering, kind/support, topic: pkg

**Comment by ParseDark** [comment] 2023-07-08 10:50
> 

It's not work for me.

**Comment by janpio** [comment] 2023-07-08 11:19
Open a new discussion please @ParseDark where you describe your problem.

**Comment by ParseDark** [comment] 2023-07-08 13:04
> Open a new discussion please @ParseDark where you describe your problem.↳

Got it. Will create a simple project for reproduce this issue. Thanks.
