### ISSUE TITLE
`npx prisma introspect` errors with `[libs/sql-schema-describer/src/mysql.rs:353:27] column_name` on indexes using expressions (MySQL 8.0.13+)

### ISSUE THREAD

**Issue by Bene-Graham** [prisma/prisma#3089] opened 2020-07-21 00:45 UTC
## Bug description

Getting the following error when running `npx prisma introspect`
```
$ DEBUG="*" npx prisma introspect
Environment variables loaded from prisma/.env

Introspecting based on datasource defined in prisma/schema.prisma …
  IntrospectionEngine:rpc starting introspection engine with binary: projectFolder/node_modules/@prisma/cli/introspection-engine-darwin +0ms
  IntrospectionEngine:rpc SENDING RPC CALL {"id":1,"jsonrpc":"2.0","method":"introspect","params":[{"schema":"// This is your Prisma schema file,\n// learn more about it in the docs: https://pris.ly/d/prisma-schema\n\ndatasource db {\n  provider = \"mysql\"\n  url      = env(\"DATABASE_URL\")\n}\n\ngenerator client {\n  provider = \"prisma-client-js\"\n}\n"}]} +8ms
  IntrospectionEngine:stderr {"is_panic":true,"message":"[libs/sql-schema-describer/src/mysql.rs:353:27] column_name","backtrace":"   0: backtrace::backtrace::trace\n   1: backtrace::capture::Backtrace::new\n   2: user_facing_errors::Error::new_in_panic_hook\n   3: user_facing_errors::panic_hook::set_panic_hook::{{closure}}\n   4: std::panicking::rust_panic_with_hook\n   5: _rust_begin_unwind\n   6: core::panicking::panic_fmt\n   7: core::option::expect_failed\n   8: <sql_schema_describer::mysql::SqlSchemaDescriber as sql_schema_describer::SqlSchemaDescriberBackend>::describe::__describe::{{closure}}\n   9: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll\n  10: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll\n  11: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll\n  12: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll\n  13: <futures_util::compat::compat03as01::Compat<Fut> as futures::future::Future>::poll\n  14: <futures::future::map::Map<A,F> as futures::future::Future>::poll\n  15: <futures::future::either::Either<A,B> as futures::future::Future>::poll\n  16: futures::future::chain::Chain<A,B,C>::poll\n  17: <futures::future::then::Then<A,B,F> as futures::future::Future>::poll\n  18: <futures::future::map::Map<A,F> as futures::future::Future>::poll\n  19: <futures::future::either::Either<A,B> as futures::future::Future>::poll\n  20: <futures::future::map::Map<A,F> as futures::future::Future>::poll\n  21: futures::task_impl::std::set\n  22: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll\n  23: tokio::runtime::enter::Enter::block_on\n  24: tokio::runtime::context::enter\n  25: tokio::runtime::handle::Handle::enter\n  26: introspection_engine::main\n  27: std::rt::lang_start::{{closure}}\n  28: std::rt::lang_start_internal\n  29: _main\n"} +0ms
The above error occurred in the <TabIndexProvider> component:
    in TabIndexProvider
    in App

React will try to recreate this component tree from scratch using the error boundary you provided, App.
Warning: App: Error boundaries should implement getDerivedStateFromError(). In that method, return a state update to display an error message or fallback UI.
  prisma TypeError: Cannot read property 'Symbol(keypress-decoder)' of undefined
  prisma     at Object.emitKeypressEvents (readline.js:1104:13)
  prisma     at Object.useStdin (projectFolder/node_modules/@prisma/cli/build/index.js:2:2913327)
  prisma     at TabIndexProvider (projectFolder/node_modules/@prisma/cli/build/index.js:2:2313126)
  prisma     at renderWithHooks (projectFolder/node_modules/@prisma/cli/build/index.js:2:2706893)
  prisma     at mountIndeterminateComponent (projectFolder/node_modules/@prisma/cli/build/index.js:2:2736840)
  prisma     at beginWork$1 (projectFolder/node_modules/@prisma/cli/build/index.js:2:2752820)
  prisma     at Object._s (projectFolder/node_modules/@prisma/cli/build/index.js:2:2767616)
  prisma     at invokeGuardedCallback (projectFolder/node_modules/@prisma/cli/build/index.js:2:2770115)
  prisma     at Ou (projectFolder/node_modules/@prisma/cli/build/index.js:2:2812237)
  prisma     at performUnitOfWork (projectFolder/node_modules/@prisma/cli/build/index.js:2:2801113) +0ms
```

## How to reproduce
Was following the guide: https://www.prisma.io/docs/getting-started/setup-prisma/add-to-existing-project-typescript-mysql

got to the to the point where it ask to run `npx prisma introspect`

## Expected behavior

No error to occur :)

## Environment & setup

- OS: MAC OS Catalina
- Database: MySQL 8
- Prisma version: 2.2.2
- Node.js version: 12.18.2

**Comment by Jolg42** [comment] 2020-08-05 16:43
So the tracking issue about the bad error handling about `<TabIndexProvider> ` is here https://github.com/prisma/migrate/issues/521

In your case it looks like the original error message is `[libs/sql-schema-describer/src/mysql.rs:353:27] column_name`
```
{"is_panic":true,"message":"[libs/sql-schema-describer/src/mysql.rs:353:27] column_name","backtrace":"   0: backtrace::backtrace::trace\n   1: backtrace::capture::Backtrace::new\n   2: user_facing_errors::Error::new_in_panic_hook\n   3: user_facing_errors::panic_hook::set_panic_hook::{{closure}}\n   4: std::panicking::rust_panic_with_hook\n   5: _rust_begin_unwind\n   6: core::panicking::panic_fmt\n   7: core::option::expect_failed\n   8: <sql_schema_describer::mysql::SqlSchemaDescriber as sql_schema_describer::SqlSchemaDescriberBackend>::describe::__describe::{{closure}}\n   9: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll\n  10: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll\n  11: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll\n  12: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll\n  13: <futures_util::compat::compat03as01::Compat<Fut> as futures::future::Future>::poll\n  14: <futures::future::map::Map<A,F> as futures::future::Future>::poll\n  15: <futures::future::either::Either<A,B> as futures::future::Future>::poll\n  16: futures::future::chain::Chain<A,B,C>::poll\n  17: <futures::future::then::Then<A,B,F> as futures::future::Future>::poll\n  18: <futures::future::map::Map<A,F> as futures::future::Future>::poll\n  19: <futures::future::either::Either<A,B> as futures::future::Future>::poll\n  20: <futures::future::map::Map<A,F> as futures::future::Future>::poll\n  21: futures::task_impl::std::set\n  22: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll\n  23: tokio::runtime::enter::Enter::block_on\n  24: tokio::runtime::context::enter\n  25: tokio::runtime::handle::Handle::enter\n  26: introspection_engine::main\n  27: std::rt::lang_start::{{closure}}\n  28: std::rt::lang_start_internal\n  29: _main\n"}
```

**Comment by Jolg42** [comment] 2020-08-05 16:45
@do4gr Do you know what could be the cause? Could it be fixed in latest?

**Comment by Bene-Graham** [comment] 2020-08-05 16:56
@Jolg42 I just tried it on 2.4.1 and it still errors out.

```json
{
    "is_panic": true,
    "message": "[libs/sql-schema-describer/src/mysql.rs:349:27] column_name",
    "backtrace": "   0: backtrace::backtrace::trace\n   1: backtrace::capture::Backtrace::new\n   2: user_facing_errors::Error::new_in_panic_hook\n   3: user_facing_errors::panic_hook::set_panic_hook::{{closure}}\n   4: std::panicking::rust_panic_with_hook\n   5: _rust_begin_unwind\n   6: core::panicking::panic_fmt\n   7: core::option::expect_failed\n   8: <sql_schema_describer::mysql::SqlSchemaDescriber as sql_schema_describer::SqlSchemaDescriberBackend>::describe::__describe::{{closure}}\n   9: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll\n  10: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll\n  11: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll\n  12: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll\n  13: <futures_util::compat::compat03as01::Compat<Fut> as futures::future::Future>::poll\n  14: <futures::future::map::Map<A,F> as futures::future::Future>::poll\n  15: <futures::future::either::Either<A,B> as futures::future::Future>::poll\n  16: futures::future::chain::Chain<A,B,C>::poll\n  17: <futures::future::then::Then<A,B,F> as futures::future::Future>::poll\n  18: <futures::future::map::Map<A,F> as futures::future::Future>::poll\n  19: <futures::future::either::Either<A,B> as futures::future::Future>::poll\n  20: <futures::future::map::Map<A,F> as futures::future::Future>::poll\n  21: futures::task_impl::std::set\n  22: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll\n  23: tokio::runtime::enter::Enter::block_on\n  24: tokio::runtime::context::enter\n  25: tokio::runtime::handle::Handle::enter\n  26: introspection_engine::main\n  27: std::rt::lang_start::{{closure}}\n  28: std::rt::lang_start_internal\n  29: _main\n"
}
```

**Comment by janpio** [comment] 2020-08-05 17:46
Can you share your schema with us @Bene-Graham? Then it would be easier for us to recreate.

**Comment by Bene-Graham** [comment] 2020-08-05 17:53
@janpio 

Unfortunately I cannot. But I was digging through the github repo: https://github.com/prisma/prisma-engines/blob/master/libs/sql-schema-describer/src/mysql.rs

I ran the query there and noticed that 3 of the row have NULL coming back in the COLUMN_NAME column.

The rows seems to be part of 2 different Unique indexes. The weird thing is other unique indexes in the system don't have this issue.

**Comment by Bene-Graham** [comment] 2020-08-05 18:03
@janpio 

Those index use Expressions as part of defining the index. This is new as of MySQL 8.0.13
https://dev.mysql.com/doc/refman/8.0/en/create-index.html#create-index-unique

This is an example of the index that was created in my database
```sql
ALTER TABLE \`MyTable\`
ADD UNIQUE INDEX \`myTableUniqueIndexName\`
(
    \`ClientId\` ASC,
    \`name\` ASC,
    (IFNULL(\`ParentId\`, -1)) ASC,
    (IFNULL(\`deletedAt\`, '')) ASC
) VISIBLE;
```

Those columns that are expressions, show up as NULL column_names

**Comment by janpio** [comment] 2020-08-05 18:38
Awesome find. Can you share just the SQL for this one `MyTable` (or a reproduction of it with just the necessary columns)? Then we can just try to `introspect` that one ourselves. If not, we will try to reproduce the table manually and get to a state where we get the same error.

**Comment by Bene-Graham** [comment] 2020-08-05 18:47
This should do the trick.

```SQL
-- MySQL dump 10.13  Distrib 8.0.21, for macos10.15 (x86_64)
--
-- Host: 127.0.0.1    Database: testDB
-- ------------------------------------------------------
-- Server version	8.0.19

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!50503 SET NAMES utf8 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

--
-- Table structure for table `SampleTable`
--

DROP TABLE IF EXISTS `SampleTable`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `SampleTable` (
  `id` int NOT NULL,
  `name` varchar(45) DEFAULT NULL,
  `parentId` int DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `SampleTableUniqueIndexName` (`name`,(ifnull(`parentId`,-(1))))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Dumping data for table `SampleTable`
--

LOCK TABLES `SampleTable` WRITE;
/*!40000 ALTER TABLE `SampleTable` DISABLE KEYS */;
/*!40000 ALTER TABLE `SampleTable` ENABLE KEYS */;
UNLOCK TABLES;

--
-- Dumping routines for database 'testDB'
--
/*!40103 SET TIME_ZONE=@OLD_TIME_ZONE */;

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;

-- Dump completed on 2020-08-05 14:46:18

```
This causes the introspection to fail. If I manually delete the `SampleTableUniqueIndexName` the introspection works.

**Comment by janpio** [comment] 2020-08-05 18:51
Thanks - now someone can try to reproduce this with MySQL 8.0.13+ (otherwise you get `* SQL Error (1064): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '(ifnull(`parentId`,-(1))))) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8' at line 6 *//` 🙈 )

**Comment by pantharshit00** [comment] 2020-08-05 20:42
I can reproduce this with the schema that you shared: 
<img width="962" alt="image" src="https://user-images.githubusercontent.com/22195362/89461644-deff8300-d789-11ea-85e2-b8f59d9009a0.png">

Report: https://prisma-errors.netlify.app/report/9833

I used MySQL `8.0.21` which I spun up using this docker image:
```yaml
version: '3.1'

services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3307:3306

```

**Comment by janpio** [comment] 2020-08-05 21:22
Good news: We know what is happening.
Bad new: This is technically a new feature that we just do not support yet.

Two things to do here now:
1. Make it not crash.
2. See if and how we can support these new types of indexes.

**Comment by do4gr** [comment] 2020-08-06 11:39
Making it not crash by just not including the index for now should be a straightforward fix. I'll have a look.

**Closed** 2020-08-11 11:19 UTC
Labels: bug/2-confirmed, kind/bug, team/engines, team/support, topic: introspection, topic: tabindexprovider
