### ISSUE TITLE
PANIC in query-engine/connectors/mongodb-query-connector/src/root_queries/read.rs:101:74called `Option::unwrap()` on a `None` value

### ISSUE THREAD

**Issue by andrelandgraf** [prisma/prisma#7701] opened 2021-06-15 21:48 UTC
I am using mongoDB early-access and have noticed that the prisma client is not working. I was able to replicate the issue in a little demo app. Please find the autogenerated report and my code snippets below. 

@matthewmueller, you asked me to create a feature request for one-directional relationships and to report a bug regarding my prisma client issue. Please see below my prisma schema and my thoughts on it in the comments. If prisma client works, I really don't mind how prisma is handling the relationships internally and I am fine with the two-directional relationship in the prisma.schema. But again, from a mongoose / mongoDB perspective, the pointer back from the other relationship (Ingredient) is kind of unnecessary. I hope that thought process makes sense! But also, it really doesn't matter as long as its not shown in the DB and prisma client works! 💯  Thanks for your support! 🙏

Hi Prisma Team! My Prisma Client just crashed. This is the report:

## Versions

| Name            | Version            |
|-----------------|--------------------|
| Node            | v14.15.4           | 
| OS              | undefined|
| Prisma Client   | in-memory          |
| Query Engine    | query-engine c838e79f39885bc8e1611849b1eb28b5bb5bc922|
| Database        | undefined|

## Query
```
query {
  findManyIngredient(
    take: 5
    skip: 5
  ) {
    id
    name
    type
    createdAt
    updatedAt
    defaultIn {
      id
      name
      createdAt
      updatedAt
      ingredientIds
      substitutionIds
    }
    alternativeFor {
      id
      name
      createdAt
      updatedAt
      ingredientIds
      substitutionIds
    }
  }
}
```

## Logs
```
raf/.npm/_npx/2778af9cee32ff87/node_modules/prisma/engines/c838e79f39885bc8e1611849b1eb28b5bb5bc922/query-engine-darwin are fine  
  prisma:engine { flags: [ '--enable-raw-queries', '--port', '60387' ] }  
  plusX Execution permissions of /Users/andrelandgraf/.npm/_npx/2778af9cee32ff87/node_modules/prisma/engines/c838e79f39885bc8e1611849b1eb28b5bb5bc922/query-engine-darwin are fine  
  plusX Execution permissions of /Users/andrelandgraf/.npm/_npx/2778af9cee32ff87/node_modules/prisma/engines/c838e79f39885bc8e1611849b1eb28b5bb5bc922/query-engine-darwin are fine  
  prisma:engine { flags: [ '--enable-raw-queries', '--port', '60388' ] }  
  prisma:engine stdout  Started http server on http://127.0.0.1:60387  
  prisma:engine stdout  Started http server on http://127.0.0.1:60388  
  plusX Execution permissions of /Users/andrelandgraf/.npm/_npx/2778af9cee32ff87/node_modules/prisma/engines/c838e79f39885bc8e1611849b1eb28b5bb5bc922/query-engine-darwin are fine  
  plusX Execution permissions of /Users/andrelandgraf/.npm/_npx/2778af9cee32ff87/node_modules/prisma/engines/c838e79f39885bc8e1611849b1eb28b5bb5bc922/query-engine-darwin are fine  
  prisma:engine Client Version: in-memory  
  prisma:engine Engine Version: query-engine c838e79f39885bc8e1611849b1eb28b5bb5bc922  
  prisma:engine Active provider: mongodb  
  prisma:engine Client Version: in-memory  
  prisma:engine Engine Version: query-engine c838e79f39885bc8e1611849b1eb28b5bb5bc922  
  prisma:engine Active provider: mongodb  
  prisma:engine stdout  PANIC in query-engine/connectors/mongodb-query-connector/src/root_queries/read.rs:101:74
called `Option::unwrap()` on a `None` value  
  prisma:engine {
  prisma:engine   error: SocketError: other side closed
  prisma:engine       at Socket.onSocketEnd (/Users/andrelandgraf/.npm/_npx/2778af9cee32ff87/node_modules/prisma/prisma-client/runtime/index.js:25736:24)
  prisma:engine       at Socket.emit (events.js:327:22)
  prisma:engine       at Socket.EventEmitter.emit (domain.js:467:12)
  prisma:engine       at endReadableNT (internal/streams/readable.js:1327:12)
  prisma:engine       at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  prisma:engine     code: 'UND_ERR_SOCKET'
  prisma:engine   }
  prisma:engine }  
  prisma:engine {
  prisma:engine   error: Error: connect ECONNREFUSED 127.0.0.1:60388
  prisma:engine       at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1146:16) {
  prisma:engine     errno: -61,
  prisma:engine     code: 'ECONNREFUSED',
  prisma:engine     syscall: 'connect',
  prisma:engine     address: '127.0.0.1',
  prisma:engine     port: 60388
  prisma:engine   }
  prisma:engine }  
  prisma:engine { cwd: '/Users/andrelandgraf/workspaces/demo/prisma' }  
  plusX Execution permissions of /Users/andrelandgraf/.npm/_npx/2778af9cee32ff87/node_modules/prisma/engines/c838e79f39885bc8e1611849b1eb28b5bb5bc922/query-engine-darwin are fine  
  prisma:engine { flags: [ '--enable-raw-queries', '--port', '60400' ] }  
  prisma:engine Stopping Prisma engine4  
  prisma:engine Waiting for start promise  
  prisma:engine Done waiting for start promise  
  prisma:engine stdout  Started http server on http://127.0.0.1:60400  
  plusX Execution permissions of /Users/andrelandgraf/.npm/_npx/2778af9cee32ff87/node_modules/prisma/engines/c838e79f39885bc8e1611849b1eb28b5bb5bc922/query-engine-darwin are fine  
  prisma:engine Client Version: in-memory  
  prisma:engine Engine Version: query-engine c838e79f39885bc8e1611849b1eb28b5bb5bc922  
  prisma:engine Active provider: mongodb  
  prisma:engine stdout  PANIC in query-engine/connectors/mongodb-query-connector/src/root_queries/read.rs:101:74
called `Option::unwrap()` on a `None` value  
  prisma:engine {
  prisma:engine   error: SocketError: other side closed
  prisma:engine       at Socket.onSocketEnd (/Users/andrelandgraf/.npm/_npx/2778af9cee32ff87/node_modules/prisma/prisma-client/runtime/index.js:25736:24)
  prisma:engine       at Socket.emit (events.js:327:22)
  prisma:engine       at Socket.EventEmitter.emit (domain.js:467:12)
  prisma:engine       at endReadableNT (internal/streams/readable.js:1327:12)
  prisma:engine       at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  prisma:engine     code: 'UND_ERR_SOCKET'
  prisma:engine   }
  prisma:engine }  
```

## Client Snippet
```ts
import { Ingredient, Recipe, FoodType } from '@prisma/client'
import prisma from '../db.server';

  //  in my case that I try to simplify here, there would be separate forms, so lets make separate queries 
  const ingredient = await prisma.ingredient.create({ data: {
    name: ingredientName,
    type: FoodType.dairy // we only support dairy for now...
  } });
  const alternative = await prisma.ingredient.create({ data: {
    name: alternativeName,
    type: FoodType.dairy
  }})
 // recipe will be created somewhen later. Ingredients have to be able to "live" without them!
 // const recipe = await prisma.recipe.create({ data: {
 //   name,
 //   ingredientIds: [ingredient.id],
 //   substitutionIds: [alternative.id]
 //  }})
```

## Schema
```prisma
datasource db {
  provider = "mongodb"
  url      = env("DATABASE_URL")
}

generator client {
  provider = "prisma-client-js"
  previewFeatures = ["mongodb"]
}

enum FoodType {
  veggie
  fruit
  meat
  dairy
}


model Ingredient {
  id    String @id @default(dbgenerated()) @map("_id") @db.ObjectId
  name String @unique
  type FoodType
  createdAt DateTime @default(now())
  updatedAt DateTime @updatedAt
  // fields below would not be necessary in mongoose / NoSQL-land
  // but I guess they don't hurt either
  // maybe it even provides some nice basic for advanced analytics
  defaultIn Recipe[] @relation("DefaultIntegredients")
  alternativeFor Recipe[]  @relation("HealthierIntegredients")
}

model Recipe {
  id    String @id @default(dbgenerated()) @map("_id") @db.ObjectId
  name String @unique
  createdAt DateTime @default(now())
  updatedAt DateTime @updatedAt
  // the default ingredients for this recipe
  ingredients Ingredient[] @relation("DefaultIntegredients", fields: [ingredientIds], references: [id])
  ingredientIds String[] @db.ObjectId
  substitutions Ingredient[] @relation("HealthierIntegredients", fields: [ingredientIds], references: [id])
  substitutionIds String[] @db.ObjectId
}
```

**Comment by andrelandgraf** [comment] 2021-06-15 21:54
I just realised the error logs are a bit different for my actual project, so as a comparison, let me also paste them here:

```
Query:
  prisma.ingredient.findMany({
  take: 100,
  skip: 0,
  select: {
    id: true,
    name: true,
    type: true,
    defaultIn: true,
    alternativeFor: true,
  }
})
```

Please not that I do not have any recipes, so both `defaultIn` and `alternativeFor` would be null. 

I guess this is where the unwrap error comes from?

```
PANIC in query-engine/connectors/mongodb-query-connector/src/root_queries/read.rs:101:74
called `Option::unwrap()` on a `None` value
```

**Comment by andrelandgraf** [comment] 2021-06-15 23:32
One more hint, could it be that my schema is just wrong? 

```
meta: { message: "Failed to convert 'List([])' to 'ObjectId'." }
```

Do I have to change this line `ingredientIds String[] @db.ObjectId` somehow?

This might be related to https://github.com/prisma/prisma/issues/7119

**Comment by dimaip** [comment] 2021-06-16 03:19
> Do I have to change this line ingredientIds String[] @db.ObjectId somehow? 

I guess it has to be smth along the lines of `@db.Array("String")`?

**Comment by andrelandgraf** [comment] 2021-06-16 10:01
That shows me the following warning: Error parsing attribute "@relation": The type of the field `ingredientIds ` in the model `Recipe` is not matching the type of the referenced field `id` in model `Ingredient`.

**Comment by crazydev901** [comment] 2021-06-17 07:04
Same issue here

**Comment by andrelandgraf** [comment] 2021-06-17 15:35
Workaround suggested by @matthewmueller  https://github.com/prisma/prisma/issues/7119#issuecomment-863046631

**Comment by matthewmueller** [comment] 2021-06-17 15:58
Thanks for linking these! Closing as a duplicate of #7119.

**Closed by matthewmueller** 2021-06-17 15:58 UTC
Labels: bug/1-repro-available, kind/bug, process/candidate, team/developer-productivity, topic: mongodb
