### ISSUE TITLE
Useless migration when @default(dbgenerated("CURRENT_TIMESTAMP"))

### ISSUE THREAD

**Issue by iamel89** [prisma/prisma#25477] opened 2024-10-22 09:23 UTC
### Bug description

Using  `@default(dbgenerated("CURRENT_TIMESTAMP"))` couses that prisma can't stop generating migration like
```sql
-- AlterTable
ALTER TABLE "user" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP;
```

After applying it prisma generates this migration again and again when run `npx prisma migrate dev`.

### How to reproduce

`mkdir test`
`cd test`
`npm i prisma`
`npx prisma init`
fill `.env` with your credentials
fill schema
`npx prisma migrate dev`
`npx prisma migrate dev`
`npx prisma migrate dev`
...

### Prisma information

```prisma
generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

model user {
  id Int @id @default(autoincrement())
  name String

  created_at DateTime @default(dbgenerated("CURRENT_TIMESTAMP"))
}
```

### Environment & setup

- OS: Windows, Ubuntu
- Database: PostgreSQL
- Node.js version: v18.17.1, v20.13

### Prisma Version

```
prisma                  : 5.21.1
@prisma/client          : 5.21.1
Computed binaryTarget   : windows
Operating System        : win32
Architecture            : x64
Node.js                 : v20.13.0
Query Engine (Node-API) : libquery-engine bf0e5e8a04cada8225617067eaa03d041e2bba36 (at node_modules\@prisma\engines\query_engine-windows.dll.node)
Schema Engine           : schema-engine-cli bf0e5e8a04cada8225617067eaa03d041e2bba36 (at node_modules\@prisma\engines\schema-engine-windows.exe)
Schema Wasm             : @prisma/prisma-schema-wasm 5.21.1-1.bf0e5e8a04cada8225617067eaa03d041e2bba36
Default Engines Hash    : bf0e5e8a04cada8225617067eaa03d041e2bba36
Studio                  : 0.503.0
```
```
prisma                  : 5.21.1
@prisma/client          : 5.21.1
Computed binaryTarget   : debian-openssl-3.0.x
Operating System        : linux
Architecture            : x64
Node.js                 : v18.17.1
Query Engine (Node-API) : libquery-engine bf0e5e8a04cada8225617067eaa03d041e2bba36 (at node_modules/@prisma/engines/libquery_engine-debian-openssl-3.0.x.so.node)
Schema Engine           : schema-engine-cli bf0e5e8a04cada8225617067eaa03d041e2bba36 (at node_modules/@prisma/engines/schema-engine-debian-openssl-3.0.x)
Schema Wasm             : @prisma/prisma-schema-wasm 5.21.1-1.bf0e5e8a04cada8225617067eaa03d041e2bba36
Default Engines Hash    : bf0e5e8a04cada8225617067eaa03d041e2bba36
Studio                  : 0.503.0
```

**Comment by marvinruder** [comment] 2024-11-09 10:00
I have a similar issue. My schema contains

```
model Session {
  id        Bytes    @id @default(dbgenerated("gen_random_bytes(32)"))
  user      User     @relation(fields: [email], references: [email], onUpdate: Cascade, onDelete: Cascade)
  email     String   @db.VarChar(255)
  createdAt DateTime @default(now()) @db.Timestamp(6)
  expiresAt DateTime @default(dbgenerated("date_add(now(), '1 hour')")) @db.Timestamp(6)
}
```

and the generated SQL includes

```sql
-- CreateTable
CREATE UNLOGGED TABLE "Session" ( -- I manually added that “UNLOGGED” statement, but left the rest unchanged
    "id" BYTEA NOT NULL DEFAULT gen_random_bytes(32),
    "email" VARCHAR(255) NOT NULL,
    "createdAt" TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "expiresAt" TIMESTAMP(6) NOT NULL DEFAULT date_add(now(), '1 hour'),

    CONSTRAINT "Session_pkey" PRIMARY KEY ("id")
);
```

The `psql` output for `\d+ "Session"` reads:

```
                                                             Unlogged table "rating-tracker.Session"
  Column   |              Type              | Collation | Nullable |                Default                | Storage  | Compression | Stats target | Description 
-----------+--------------------------------+-----------+----------+---------------------------------------+----------+-------------+--------------+-------------
 id        | bytea                          |           | not null | gen_random_bytes(32)                  | extended |             |              | 
 email     | character varying(255)         |           | not null |                                       | extended |             |              | 
 createdAt | timestamp(6) without time zone |           | not null | CURRENT_TIMESTAMP                     | plain    |             |              | 
 expiresAt | timestamp(6) without time zone |           | not null | date_add(now(), '01:00:00'::interval) | plain    |             |              | 
Indexes:
    "Session_pkey" PRIMARY KEY, btree (id)
Foreign-key constraints:
    "Session_email_fkey" FOREIGN KEY (email) REFERENCES "User"(email) ON UPDATE CASCADE ON DELETE CASCADE
Access method: heap
```

The next migration script contains the changes I made to the schema and the unrelated

```sql
-- AlterTable
ALTER TABLE "Session" ALTER COLUMN "expiresAt" SET DEFAULT date_add(now(), '1 hour');
```

**Comment by marvinruder** [comment] 2024-11-25 09:01
This issue has been open for some time now, without tags or comments from maintainers.

@janpio May I kindly ask for a triage?

**Comment by aqrln** [comment] 2024-11-29 15:29
I can reproduce, the problem happens because the `dbgenerated` value as introspected back doesn't correspond exactly to what's written in the schema, and Migrate can't figure out they're equivalent when diffing.

@iamel89 in your case, `@default(dbgenerated("CURRENT_TIMESTAMP"))` is introspected as `@default(now())`.

@marvinruder in your case, `@default(dbgenerated("date_add(now(), '1 hour')"))` is introspected as `@default(dbgenerated("date_add(now(), '01:00:00'::interval)"))`.

The workaround is to specify it in the schema exactly the way Prisma sees it in the database (you can use `prisma db pull` to check it).

**Comment by iamel89** [comment] 2024-11-29 20:12
@aqrln thanks a lot! ) In my case I [can](https://www.prisma.io/docs/orm/reference/prisma-schema-reference#relational-databases-8) use `@default(now())` indeed

**Comment by marvinruder** [comment] 2024-11-30 00:07
@aqrln Thanks, everything works fine with `'01:00:00'::interval`.

**Comment by jkomyno** [comment] 2024-12-30 15:27
Closing this as a duplicate in favour of https://github.com/prisma/prisma/issues/12574.

**Closed by jkomyno** 2024-12-30 15:27 UTC
Labels: bug/2-confirmed, kind/bug, topic: migrate, domain/schema, topic: dbgenerated
