### ISSUE TITLE
Error: `Env var PRISMA_QUERY_ENGINE_LIBRARY is provided but provided path (...) can't be resolved.`

### ISSUE THREAD

**Issue by pyton-jajko** [prisma/prisma#16993] opened 2022-12-23 09:10 UTC
@aqrln Thanks for your support. That was the exact problem with environmentals! I think I'm almost there, but I have just one error left:
```
Error: Env var PRISMA_QUERY_ENGINE_LIBRARY is provided but provided path /home/pytonJajko/bin/prisma-engines/target/release/libquery_engine.so.node can't be resolved.
```

I tried to move binaries to project root folder, but the problem won't vanished.

_Originally posted by @pyton-jajko in https://github.com/prisma/prisma/issues/3091#issuecomment-1346605482_

I still cannot reach why Prisma can't resolve the file being present on the provided location. I think this is the last thing that separates me from running the app. If anyone have any suggestions about the issue, please share.

**Comment by jkomyno** [comment] 2022-12-27 11:30
Hi @pyton-jajko, can you please run

```sh


```sh
ls -al /home/pytonJajko/bin/prisma-engines/target/release
```

and paste the results of such command here? It seems the `libquery_engine.so.node` file doesn't exist in that directory.

If indeed it exists, can you please run

```sh
ldd /home/pytonJajko/bin/prisma-engines/target/release/libquery_engine.so.node
```

and post here the output?

**Comment by Jolg42** [comment] 2023-01-03 08:30
Note: the code is here https://github.com/prisma/prisma/blob/3bd452291d3a5e7d7c66bfe117cb54e9adcbbf72/packages/fetch-engine/src/download.ts#L393-L399
This error is thrown when `fs.existsSync(envVarPath)` is falsy, when the path provided does not exist.

**Comment by Scrum** [comment] 2023-11-10 19:00
I also encountered this problem, maybe there is already a solution?

**Comment by Jolg42** [comment] 2023-11-10 21:08
@Scrum Did you check that the path to the artifact exists?

Try running `ls -la $PRISMA_QUERY_ENGINE_LIBRARY`

**Comment by Scrum** [comment] 2023-11-10 21:42
> @Scrum Did you check that the path to the artifact exists?
> 
> 
> 
> Try running `ls -la $PRISMA_QUERY_ENGINE_LIBRARY` 

yes, he cannot resolve the path I specified

**Comment by Jolg42** [comment] 2023-11-10 22:52
@Scrum What do you mean? The path exists?
Also, is it a symlink maybe? It could be related to file permissions.

**Comment by Scrum** [comment] 2023-11-11 09:27
> @Scrum What do you mean? The path exists?
> 
> Also, is it a symlink maybe? It could be related to file permissions.

this is a physical file that exists and is not a link

**Comment by Jolg42** [comment] 2023-11-13 15:58
@Scrum You could try to debug using Node.js like this, here it's a one liner:
```
PRISMA_QUERY_ENGINE_LIBRARY=./path/to/your/library-engine node -e "const envVar = 'PRISMA_QUERY_ENGINE_LIBRARY'; const envVarPath = path.resolve(process.cwd(), process.env[envVar]); console.log('\nenvVar:', envVar, '\nenvVarPath:', envVarPath, '\nfs.existsSync:', fs.existsSync(envVarPath))"
```
It would print, for example:
```
envVar: PRISMA_QUERY_ENGINE_LIBRARY 
envVarPath: /Users/nickname/some-path/path/to/your/library-engine
fs.existsSync: true
```
Where `fs.existsSync: true` means that Node.js can access it.

**Comment by Scrum** [comment] 2023-11-14 07:43
It looks like it was a problem in my environment, I didn’t understand what happened but it worked :)

```bash 
node -e "const envVar = 'PRISMA_QUERY_ENGINE_LIBRARY'; const envVarPath = path.resolve(process.cwd(), process.env[envVar]); console.log('\nenvVar:', envVar, '\nenvVarPath:', envVarPath, '\nfs.existsSync:', fs.existsSync(envVarPath))"
```

```bash
envVar: PRISMA_QUERY_ENGINE_LIBRARY 
envVarPath: /app/prisma/binaries/debian-openssl-1.1.x/libquery_engine.so.node.gz 
fs.existsSync: true
```

**Comment by Jolg42** [comment] 2023-11-15 09:58
@Scrum you need to set `PRISMA_QUERY_ENGINE_LIBRARY` with the path to the uncompressed file, named `libquery_engine.so.node`.
Here `libquery_engine.so.node.gz` shows that you used the compressed `.gz` file.

**Comment by Scrum** [comment] 2023-11-15 11:07
> @Scrum you need to set `PRISMA_QUERY_ENGINE_LIBRARY` with the path to the uncompressed file, named `libquery_engine.so.node`. Here `libquery_engine.so.node.gz` shows that you used the compressed `.gz` file.

It works for me now with these values
```
ENV PRISMA_SCHEMA_ENGINE_BINARY=./prisma/binaries/debian-openssl-1.1.x/schema-engine.gz
ENV PRISMA_QUERY_ENGINE_LIBRARY=./prisma/binaries/debian-openssl-1.1.x/libquery_engine.so.node.gz
```

**Comment by janpio** [comment] 2023-11-15 18:39
@pyton-jajko Did you see @jkomyno's message asking for more information? We need your help to debug your problem. Thanks.

**Comment by pyton-jajko** [comment] 2023-11-15 19:04
> @pyton-jajko Did you see @jkomyno's message asking for more information? We need your help to debug your problem. Thanks.

I don't have those binaries no more on the server - I need some time to build them again. I'll let you know after I test it.

**Comment by SevInf** [comment] 2024-01-16 09:17
@pyton-jajko did you have a change to look at this?

**Comment by SevInf** [comment] 2024-02-16 10:38
Hey @pyton-jajko ,
 

With the lack of information and our inability to reproduce this issue, we're now closing it. Feel free to comment if you have any updates about it.
 
Thank you 🙏

**Closed by SevInf** 2024-02-16 10:38 UTC
Labels: bug/1-unconfirmed, kind/bug, topic: env, team/schema, topic: engine download

**Comment by bruceniyibitanga** [comment] 2024-10-23 13:15
Hey, I'm trying to build a docker image on my Raspberry Pi 4B `uname -m = aarch64`. I am very new and don't know much but I've tried implement suggestions from [here](https://github.com/prisma/prisma/issues/17284#issuecomment-1384006240) 

This what my Dockerfile looks like:
![image](https://github.com/user-attachments/assets/1a8bfcc7-ecaa-4411-9c66-5007f2036491)

My file structure with the engines folder is like so:
![image](https://github.com/user-attachments/assets/97adf0ff-2746-4987-819c-0f1dbe114d36)

I've run: `PRISMA_QUERY_ENGINE_LIBRARY=./engines/libquery_engine.so node -e "const envVar = 'PRISMA_QUERY_ENGINE_LIBRARY'; const envVarPath = path.resolve(process.cwd(), process.env[envVar]); console.log('\nenvVar:', envVar, '\nenvVarPath:', envVarPath, '\nfs.existsSync:', fs.existsSync(envVarPath))"

envVar: PRISMA_QUERY_ENGINE_LIBRARY
envVarPath: /home/bruce/Desktop/next-portfolio-main/engines/libquery_engine.so
fs.existsSync: true`

However still getting the same error:

![image](https://github.com/user-attachments/assets/6d132767-df87-4f01-a3a4-0b5b565ee20a)

Again, I very new to coding in general, and don't know what I am missing. Your help is match appreciated!
