### ISSUE TITLE
[ssr] Error: PrismaClient is unable to be run in the browser.

### ISSUE THREAD

**Issue by VinceERS** [prisma/prisma#20095] opened 2023-07-06 15:22 UTC
`[ssr] Error: PrismaClient is unable to be run in the browser.`

I am using prisma in astro with ssr and the deno adapter.  Running the app in local dev does not throw this error, api endpoints which call prisma are correctly running server side.

However when running the production build of the app, these same endpoints will show errors in the console, not in the browser.  I do not know if using the deno adapter for astro is running prisma as middleware or something like that, but I am following the documentation: [Best practice for instantiating PrismaClient with Next.js](https://www.prisma.io/docs/guides/other/troubleshooting-orm/help-articles/nextjs-prisma-client-dev-practices).

Relevant dependencies:

```js
"@astrojs/deno": "^4.2.0",
"astro": "^2.7.3",
"prisma": "^4.16.0",
```

_Originally posted by @VinceERS in https://github.com/prisma/prisma/issues/19500#issuecomment-1623014485_

**Comment by janpio** [comment] 2023-07-06 15:44
Can you help us understand a bit better what your app looks like? 
The Deno Adapter for Astro is a new thing for us.

**Comment by VinceERS** [comment] 2023-07-06 15:50
Yeah, I just set up a new repo to illustrate this, hope it helps show how the app is structured:
https://github.com/eventrentalsystems/astro-deno-prisma

This basic astro config looks like this:

```js
export default defineConfig({
  output: "server",
  adapter: deno()
});
```

The script for running this with `npm run preview` or `npm run pkg` looks like this: `astro build && deno run --allow-net --allow-read --allow-env ./dist/server/entry.mjs`

The endpoint that runs prisma is at `src/pages/index.ts`

```ts
import type { APIRoute } from "astro";
import { prisma } from "../db";

export const get: APIRoute = async function get({ params, request }) {
  const user = await prisma.user.findFirst();

  return {
    body: JSON.stringify(user),
  };
};
```

And the prisma client setup according to the docs is at `src/db.ts`

```ts
import { PrismaClient } from "@prisma/client";

const globalForPrisma = globalThis as unknown as {
  prisma: PrismaClient | undefined;
};

export const prisma = globalForPrisma.prisma ?? new PrismaClient();

if (process.env.NODE_ENV !== "production") globalForPrisma.prisma = prisma;
```

**Comment by Druue** [comment] 2023-08-17 13:33
Hey @VinceERS can you run through the steps that you took to have this error show?
I cloned the repo you mentioned and am instead running into the following error (I've never used astro before, fwiw).
<img width="612" alt="image" src="https://github.com/prisma/prisma/assets/29753584/324bac2d-5c17-43f6-b018-fb5724259fa9">

Steps I took:
- Cloned the repo
- npm i
- add `.env` with `DATABASE_URL=...`¹
- npm run build
- npm run dev

¹ I just added a `.env` file to the root with a `DATABASE_URL` var pointing to a local instance of mysql on docker.

**Comment by VinceERS** [comment] 2023-08-17 20:36
@Druue I'm not sure about your problem but I added an .env.example which should work for connecting to a local mysql database.  It looks like the error you're getting is that the `DATABASE_URL` isn't set properly.

**Comment by Druue** [comment] 2023-08-18 11:55
Okay, something seems to have fixed, no longer seeing that error.
`npm run start` puts me here. What is your exact workflow for hitting the error you mentioned?
<img width="1417" alt="image" src="https://github.com/prisma/prisma/assets/29753584/a3f6ae62-3ed8-46ce-a1a6-b83f18391dcc">

**Comment by janpio** [comment] 2023-10-29 21:17
@VinceERS Did you see Soph's last message? We need your help here.

**Comment by Druue** [comment] 2024-03-01 12:37
Hey @VinceERS,

With the lack of information and our inability to reproduce this issue, we're now closing it. Please feel free to create a new issue if this is problem persists.
 
Thank you 🙏

**Closed by Druue** 2024-03-01 12:37 UTC
Labels: bug/1-unconfirmed, kind/bug, team/client, topic: deno, topic: PrismaClient is unable to be run in browser, topic: astro
