### ISSUE TITLE
Preserve comments from .prisma in generated typescript code

### ISSUE THREAD

**Issue by safareli** [prisma/prisma#8485] opened 2021-07-28 17:41 UTC
It would be great to preserve comments made on `.prisma` models and model fields in generated Typescript code.

For example, if you have this in `schema.prisma`:
```prisma
/// Comment of Account
model Account {
  /// Comment of ID field
  id   BigInt   @id @default(autoincrement())
}
```

As of now you get this in generated typescript:

```ts
/**
 * Model Account 
 */
export type Account = {
  id: bigint
}
```

Instead I would like to see:

```ts
/**
 * Model Account
 * 
 * Comment of Account
 */
export type Account = {
  /**
   * Comment of ID field
   */
  id: bigint
}
```

**Comment by pantharshit00** [comment] 2021-07-29 10:19
Hi,

Thanks for reporting this! It has already been reported before, so I am going to close this as a duplicate of https://github.com/prisma/prisma/issues/5113

**Closed by pantharshit00** 2021-07-29 10:19 UTC
Labels: kind/feature, team/client, topic: prisma-client
