### ISSUE TITLE
Huge RSS when `$queryRawUnsafe` large rowset

### ISSUE THREAD

**Issue by BCsabaEngine** [prisma/prisma#19703] opened 2023-06-12 08:35 UTC
### Bug description

We use prisma to update our database row by row and once a day we generate a large CSV file to export actual data.

```const rows = await prisma.$queryRaw()``` get 600k rows, the exported file size is about 40Mb, but the memory allocation is very large.

```
time: 32251ms
heapUsed: +642Mb/748Mb
heapTotal: +652Mb/780Mb
rss: +1847Mb/2067Mb
arrayBuffers: -463kb/2Mb
external: -463kb/3Mb
```
Heap usage is under a normal value, but out K8S kills ou process, because RSS exceeds 2Gi limit. This is only for a 40Mb result set.

With "native" pg (npm i pg) RSS value stays at very low. It here any problem with prisma rust engine under-the-hood?

### How to reproduce

Run a 600k resultset with queryRaw or queryRawUnsafe

### Expected behavior

RSS would be stay low.

### Prisma information
```prisma
generator client {
  provider        = "prisma-client-js"
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

model InvolvedParty {
  id               String    @id @db.VarChar(100)
  bankCode         String    @db.VarChar(20)
  systemCode       String    @db.VarChar(20)
  legacyId         String    @db.VarChar(100)
...
```
```ts
const prisma = new PrismaClient();

const rows = await prisma.$queryRaw`
```

### Environment & setup

- OS: MacOS and K8S
- Database: PostgreSQL
- Node.js version: v18.16.0

### Prisma Version

```
prisma                  : 4.15.0
@prisma/client          : 4.15.0
Current platform        : darwin-arm64
Query Engine (Node-API) : libquery-engine 8fbc245156db7124f997f4cecdd8d1219e360944 (at node_modules/@prisma/engines/libquery_engine-darwin-arm64.dylib.node)
Migration Engine        : migration-engine-cli 8fbc245156db7124f997f4cecdd8d1219e360944 (at node_modules/@prisma/engines/migration-engine-darwin-arm64)
Format Wasm             : @prisma/prisma-fmt-wasm 4.15.0-28.8fbc245156db7124f997f4cecdd8d1219e360944
Default Engines Hash    : 8fbc245156db7124f997f4cecdd8d1219e360944
Studio                  : 0.484.0
```

**Comment by BCsabaEngine** [comment] 2023-06-12 08:45
We do not use transaction, we do not use query params (SQL is a simple string), we do not use any preview feature.

**Comment by BCsabaEngine** [comment] 2023-06-12 08:46
SQL is like that:
```
    SELECT
        ip."technicalGroupId" as super_id,
        ip."systemCode" as system_code,
        ip."legacyId" as system_id,
        a.giro as account,
        a.iban,
        a."accountClass" as account_class,
        'active' as status
    FROM "InvolvedParty" ip
```

Each row is about 70 bytes.

**Comment by BCsabaEngine** [comment] 2023-06-12 08:49
.ENV

```
DATABASE_URL="postgresql://user:pass@127.0.0.1:5432/ms-name?schema=ms-name"
```

**Comment by BCsabaEngine** [comment] 2023-06-12 10:36
It looks like that: https://github.com/prisma/prisma/issues/16912

**Comment by janpio** [comment] 2023-08-26 08:39
Do I understand correctly that you run 1 `SELECT` SQL query via `prisma.$queryRaw` that returns roughly 40MB of data, but Prisma jumps to use ~2GB of RSS usage when doing so @BCsabaEngine?

This is happening with Prisma 4.15.0, on MacOS and K8S (What OS and version?) running Node v18.16.0 with PostgreSQL (which version?). Can you reliably reproduce this locally?

If so, could you maybe share your Prisma Schema, Prisma Client query and an example of the data (optimally in a way so we can easily import it) with us? If you can't share that publicly, I am my first name @prisma.io for email. (We can also do NDA if necessary)

**Comment by BCsabaEngine** [comment] 2023-08-26 18:43
I have created a small repo to demonstrate the potential bug: https://github.com/BCsabaEngine/prisma-test 
Every package is uptodate, app runs on a mac with node v18.17.1 and connected to a dockered PG (PostgreSQL 13.7
PostgreSQL 13.7 on x86_64-pc-linux-gnu, compiled by gcc (Debian 10.2.1-6) 10.2.1 20210110, 64-bit), so can reproduce it locally in my machine.

**Comment by janpio** [comment] 2023-08-29 08:23
Thanks @BCsabaEngine, I can reproduce this. I also see that the Prisma Client executed raw query is a lot slower than the `pg` one, which is also unexpected. We're going to investigate this.

**Comment by BCsabaEngine** [comment] 2023-10-14 18:47
With prisma v5.4.2 the error still exists, but RSS reduced to lower
```
Start RSS: 214 Mb
Extract finished - 1000000 rows
Concat - 25 Mb
End RSS: 1879 Mb
```

**Comment by BCsabaEngine** [comment] 2023-12-13 10:21
With prisma v5.7.0 the error still exists
```
Start RSS: 223 Mb
Extract finished - 1000000 rows
Concat - 25 Mb
End RSS: 1958 Mb
```

**Comment by BCsabaEngine** [comment] 2023-12-13 10:21
With prisma v5.7.0 the error still exists
```
Start RSS: 223 Mb
Extract finished - 1000000 rows
Concat - 25 Mb
End RSS: 1958 Mb
```

**Comment by romoore** [comment] 2024-06-20 18:10
Is this still an issue? We seem to be running into a similar issue.  In our case, the RSS size is never reclaimed until we allow the Prisma object to be garbage collected. Otherwise, memory grows with each request.

We're using `$queryRaw` with `toSql` for vectors in PostgreSQL and `pgvector`. We're trying to understand why Prisma appears to be retaining massive amounts of memory in our AWS Lambda instances.   Our raw queries are bulk inserts (due to vectors). Inserting around 1,500 vectors of 1.5k dimensions each is resulting in huge amounts of RSS being allocated. 

We can fix the issue by discarding our Prisma objects on each request, but that means we have to reconnect to the DB each time and that's slow.

* Prisma client 5.12.1
* Node 20.x on AWS Lambda with 1024 MB memory allocated.

**Comment by Weakky** [comment] 2024-07-16 10:25
Hey folks, we're about to release Prisma 5.17.0 and it comes with perf & memory usage improvements on queryRaw. I won't close this issue because the memory usage improvement is mostly a side effect of the work we've done, but perhaps you might want to give it a try nonetheless once it's out.

**Comment by BCsabaEngine** [comment] 2024-07-26 12:10
With prisma 5.17.0 the result is:
```
Start RSS: 227 Mb
Extract finished - 1000000 rows
Concat - 25 Mb
End RSS: 845 Mb
```
so memory consumption is much lower.

With native pg lib: 
```
Start RSS: 245 Mb
Extract finished - 1000000 rows
Concat - 25 Mb
End RSS: 515 Mb
```

The difference is no considerable. The speed of this query is considerable but this issue is/was about memory.

**Closed** 2024-07-26 12:10 UTC
Labels: bug/2-confirmed, kind/bug, topic: performance, topic: raw, domain/client, topic: postgresql, topic: performance/memory
