### ISSUE TITLE
Uncompilable typescript generated when index name contains a . (period)

### ISSUE THREAD

**Issue by revsend** [prisma/prisma#6997] opened 2021-05-09 01:39 UTC
### Bug description

The types generated after running `prisma generate` contain syntactical errors when the name of an index contains a `.`, for example
```ts
  @@unique([giftId, productId], name: "GiftItem.gift_product")
```

<img width="544" alt="Screen Shot 2021-05-08 at 6 30 33 PM" src="https://user-images.githubusercontent.com/61167132/117557779-7b152e00-b02b-11eb-859d-7259165dd1f0.png">

### How to reproduce

1. Create an unique index with a name containing the `.` character
2. run `prisma generate`
3. Attempt to compile typescript using the client 

### Expected behavior

Either throw a validation error (at least when running prisma validate) or compile to working typescript. 

### Prisma information

version: 2.21.2

### Environment & setup

- OS: Mac OS
- Database: MySQL
- Node.js version: v12.18.4
- Prisma version: version: 2.21.2

**Comment by janpio** [comment] 2021-05-10 16:00
Similar to https://github.com/prisma/prisma/issues/6292

**Comment by pantharshit00** [comment] 2021-05-13 16:16
This is reproducible and should be patched. 
![image](https://user-images.githubusercontent.com/22195362/118154421-a6858780-b434-11eb-8a7e-bcd4ab2d4e6e.png)

**Comment by pantharshit00** [comment] 2021-05-13 16:17
This might be also related to https://github.com/prisma/prisma/issues/6680 where `map` will use the dot notation which name will contain the programming language mapping

**Comment by do4gr** [comment] 2021-08-11 12:46
A fix for this issue is now available via the `namedConstraints` preview flag since 2.29. See https://www.prisma.io/docs/guides/upgrade-guides/upgrading-to-use-preview-features/enabling-named-constraints

**Closed by do4gr** 2021-08-11 12:46 UTC
Labels: bug/2-confirmed, kind/bug, topic: schema, topic: indexes, team/migrations, topic: namedConstraints
