### ISSUE TITLE
Lambda Cold Start, influenced by schema size

### ISSUE THREAD

**Issue by revmischa** [prisma/prisma#11266] opened 2022-01-19 14:21 UTC
### Bug description

Continuing from #10724 - please see there for more details. It contains data I gathered while profiling lambda cold starts with prisma.

Problem: lambda cold starts are increased by importing prisma. 

I believe part of the problem is that despite us having a medium-sized DB schema, a very large DMMF string (6,492,708 characters) is produced which must be parsed at startup. The difference in startup between an empty DMMF string and a large one is [around one second](https://github.com/prisma/prisma/issues/10724#issuecomment-998760587).

Please see the repro repo: https://github.com/jetbridge/prisma-bundle-size

Using the repro repo you can observe the difference in startup time for two lambdas, one without prisma and one that imports prisma and tries to do a query with `DATABASE_URL=file:./dev.db` set. 

My goal is to reduce the cold start time of my lambda functions that use prisma as much as possible.

<img width="943" alt="Screen Shot 2022-01-19 at 13 36 53" src="https://user-images.githubusercontent.com/245131/150149530-9a979ab2-0708-4484-9425-b19883f5ef39.png">

<img width="1232" alt="Screen Shot 2022-01-19 at 14 01 48" src="https://user-images.githubusercontent.com/245131/150149579-50899e00-9bdb-4da6-93f7-22c9974b2a53.png">

<img width="1458" alt="Screen Shot 2022-01-19 at 14 01 45" src="https://user-images.githubusercontent.com/245131/150149592-0f4a237f-3581-4fc5-941e-727db2b7257c.png">

### How to reproduce

See [repo README](https://github.com/jetbridge/prisma-bundle-size#readme)

### Prisma information

3.8.0

### Environment & setup

- OS: 
- Database: 
- Node.js version: 

NodeJS 14 on AWS Lambda

### Prisma Version

```
prisma                  : 3.8.1
@prisma/client          : 3.7.0
Current platform        : darwin
Query Engine (Node-API) : libquery-engine 34df67547cf5598f5a6cd3eb45f14ee70c3fb86f (at ../../../../usr/local/lib/node_modules/prisma/node_modules/@prisma/engines/libquery_engine-darwin.dylib.node)
Migration Engine        : migration-engine-cli 34df67547cf5598f5a6cd3eb45f14ee70c3fb86f (at ../../../../usr/local/lib/node_modules/prisma/node_modules/@prisma/engines/migration-engine-darwin)
Introspection Engine    : introspection-core 34df67547cf5598f5a6cd3eb45f14ee70c3fb86f (at ../../../../usr/local/lib/node_modules/prisma/node_modules/@prisma/engines/introspection-engine-darwin)
Format Binary           : prisma-fmt 34df67547cf5598f5a6cd3eb45f14ee70c3fb86f (at ../../../../usr/local/lib/node_modules/prisma/node_modules/@prisma/engines/prisma-fmt-darwin)
Default Engines Hash    : 34df67547cf5598f5a6cd3eb45f14ee70c3fb86f
Studio                  : 0.452.0
```

**Comment by janpio** [comment] 2022-01-19 16:26
For the reproduction and our understanding if the DMMF size is indeed the driver behind that time, we should add a third function that has the same Prisma code - but a much smaller schema. Then we can compare no Prisma, small Prisma, big Prisma.

**Comment by revmischa** [comment] 2022-01-20 16:39
I created a mostly empty schema and tested that. It is in the repo although you have to manually change which schema it's pointing at.

Result is a total of 508ms vs the 1.1s for the same function but with the big schema.

<img width="1156" alt="Screen Shot 2022-01-20 at 18 35 22" src="https://user-images.githubusercontent.com/245131/150381988-4503214e-59fa-4b74-ab0c-1e7018c14706.png">

**Comment by janpio** [comment] 2022-01-20 17:36
So we have:

1. No Prisma: 166ms + 1.7ms
2. Prisma with small schema: 405ms + 10ms
3. Prisma with big schema: 772ms + 143ms

**Comment by tonivj5** [comment] 2022-01-20 17:37
I have noticed that the code generated by prisma maybe it's very deoptimized (v8). First use of any method takes a lot of more time than second, thrid, ... My use is a traditional backend, and to reduce the impact for the first call I do a do-nothing-call to "warm" it:
```ts
this.i18n.findFirst({ select: { name: true }, take: 0 });
```

I suppose you're being hit by this, and I think that it's due to the hard to optimize the code by V8

**Comment by janpio** [comment] 2022-01-20 19:53
@tonivj5 When you run a query, even one that returns 0 rows, the database connection is created. If you started your application before that would be expected to take some time - and "warming" that via such a call is a good idea if you can trigger that outside of a request.

**Comment by pabacham** [comment] 2022-01-21 09:03
Let me join this thread. My Prisma schema is around 15k lines and Cold Starts are high

**Comment by tonivj5** [comment] 2022-01-21 15:34
> @tonivj5 When you run a query, even one that returns 0 rows, the database connection is created. If you started your application before that would be expected to take some time - and "warming" that via such a call is a good idea if you can trigger that outside of a request.

@janpio I thought that calling `$connect()` would create the database connection. Is it really necessary to do a dumb query to force the creation of the database connection?

**Comment by janpio** [comment] 2022-01-21 16:27
You did not mention before that you are also calling `$connect()` @tonivj5. That behavior is not fully defined as far as I know, so I would confirm that this is happening and behaving the way you expect.

**Comment by janpio** [comment] 2022-01-21 16:28
@pabacham Can you confirm that you are seeing direct influence of the schema size for the Cold start time? Can you maybe do similar experiments like what Mischa did - your schema, a shorter schema, no Prisma at all and share the number? More number = better.

**Comment by pabacham** [comment] 2022-01-23 11:44
@janpio I am not sure that there is a direct influence. I am about to get access to x-ray from devops, once I get I will provide the results.

**Comment by pabacham** [comment] 2022-01-28 13:52
@janpio 
Framework: serverless-stack (SST) '@prisma/client' and '.prisma' are not a part of bundle, Lambda takes them from a layer.

Prisma layer:
	Folders and files structure - https://monosnap.com/file/qrVf8tnkUeV3PxM3Gn8ilP41x9mQNz
	Total size - 65mb
	Compressed size - 17mb
	Prisma Schema is around 15k lines

Report for simple lambda function with conditions:

1) Simple Lambda function
	Function - https://monosnap.com/file/0xtqAJJ7lluJIJJI5GNdwJ3pgDxr0x
	Report - https://monosnap.com/file/6QNcLCn3gkEQ74yQr5WzyKeLdilZfh

2) Lambda function with attached Prisma Layer + imported Prisma Client in code
	Function - https://monosnap.com/file/2WGONdIqGAvgm1Z1hl0K2Myo0oh84B
	Report - https://monosnap.com/file/BwE5J2FHrDoUqguSBVb7I1yb00aPzv

3) Lambda function with attached Prisma Layer + imported and defined Prisma Client in code
	Function - https://monosnap.com/file/sm15c0UBbo8JcZgHo2YQiOIcPKHWjJ
	Report - https://monosnap.com/file/eKSmk06r7Ld0ceqwF0WPsxXDikYSH1

4) Lambda function with attached Prisma Layer + imported and defined Prisma Client in code 
+ some SQL queries
	Function - https://monosnap.com/file/TScch5bDZ9qdWr7TMKaKWlBgJocsIz
	Report - https://monosnap.com/file/czpWPAud12XPOZ3kOkX4dVsdscbk1K

**Comment by cayter** [comment] 2022-07-02 08:00
The slow cold start issue caused by increasing code size on AWS Lambda is expected. With that said, if prisma is unable to provide a way to minimise/optimise the code size, you should consider using [Provisioned Concurrency](https://aws.amazon.com/blogs/aws/new-provisioned-concurrency-for-lambda-functions/) to avoid the latency-sensitive API endpoints suffering from slow cold start issue.

**Comment by cayter** [comment] 2022-07-02 08:01
The slow cold start issue caused by increasing code size on AWS Lambda is expected as code size determines the download speed which is part of the process in booting up a new Lambda VM to handle the request. 

With that said, if prisma is unable to provide a way to minimise/optimise the code size, you should consider using [Provisioned Concurrency](https://aws.amazon.com/blogs/aws/new-provisioned-concurrency-for-lambda-functions/) to avoid the latency-sensitive API endpoints suffering from slow cold start issue.

**Comment by revmischa** [comment] 2022-07-02 16:15
I upgraded to Prisma 4.0.0. My bundle size is now on average ~1.5MB after the upgraded as opposed to ~11MB on prisma 3.14.0.
Unfortunately the cold start time remains unchanged though.

**Comment by janpio** [comment] 2022-12-20 19:01
Today's release 4.8.0 has _significantly_ (average 50%, on some platforms even more) decreased the size of our engine files, but we also improved the performance of loading bigger schemas:

> **Improved serverless experience — smaller engines size**
>
> In this release, we have decreased the size of our engine files by an average of 50%. The size of the Query Engine used on Debian, with OpenSSL 3.0.x, for example, went from 39MB to 14MB. We will also remove some smaller engines to decrease the total size in future versions.
>
> _Additionally, we have started optimizing how the Prisma schema is loaded in Prisma Client. You should notice a considerable improvement when executing the first query if you're working with a bigger schema with many models and relations._
>
> We will continue investing in this direction in the next releases and further improve the experience with Prisma and serverless environments.

https://github.com/prisma/prisma/releases/tag/4.8.0

We are not even close to where we want to be with that of course, but this is a first step. Expect more improvements in this area soon.

**Comment by janpio** [comment] 2023-02-18 01:17
Please provide some additional information @zomars. How big is your schema? How long does a connection in the same environment to the same database with a smaller schema take? Do you have reliable attribution of the time spent to Prisma Client and its start, or could it just be other time (of e.g. executing queries)? There can be many reasons why the initial request in a serverless function is slow. (Some of them we discussed in a private channel)

**Comment by janpio** [comment] 2023-04-26 01:25
I already posted in the [other similar issue](https://github.com/prisma/prisma/issues/10724) that we published a blog post "[How We Sped Up Serverless Cold Starts with Prisma by 9x](https://www.prisma.io/blog/prisma-and-serverless-73hbgKnZ6t)", so I won't repeat the screenshots of the graphs showing our improvements - just read my other comment for that: https://github.com/prisma/prisma/issues/10724#issuecomment-1521805173

But I applied the new version to the reproduction that @revmischa thankfully provided above and got nice results:

<img width="1079" alt="image" src="https://user-images.githubusercontent.com/183673/234440136-9986a89a-213a-4b3e-9fdc-01a1b409ae0c.png">
<img width="538" alt="image" src="https://user-images.githubusercontent.com/183673/234440351-ec42281c-5006-4148-a9e3-2cc6c01d2fc5.png">

(These are my own measurement for 3.13.0, not the original ones Mischa shared in his screenshots. They are a bit slower because I had to figure out what database was actually used for the tests, and I defaulted to our most popular PostgreSQL - in hindsight, I think that Mischa used SQLite instead. But his original results and my results for 3.13.0 have the same proportion between `no-prisma`, `prisma` and `prisma-empty` - so I am confident in using my 3.13.0 measurement as the baseline for the improvements in newer versions.)

You can see how the impact on "Init" (**= Cold Start**) (baseline on an empty function is ~150ms) went from ~800ms to ~220ms for the big schema, and ~460ms to also ~220ms for the empty schema - which means that there is no more difference between big and empty schema, and that the overhead is down to 50ms right now. 

What is measured as "Function" here (baseline in empty function is ~4ms) is what happens inside the handler, so currently the database connection creation and then a query. That timing is also greatly improved both for the big and empty schema, and also shows that there is no difference anymore between the schema sizes.

We are pretty happy about these results. 🥳 
But we are also not done yet, and will release further improvements on both the Startups ("Init") and the Runtime ("Function") performance soon.

(Theoretically I think I could achieve even better results here by upgrading the functions to Node18, and moving the connection creation outside the handler as a top level await - but as I am stuck on `sst@1.18.4` for now that did not work out today. PRs welcome 😆 https://github.com/janpio/jetbridge-prisma-bundle-size/tree/4.0.0)

**Comment by revmischa** [comment] 2023-04-26 01:39
Great stuff, thank you! I am using postgres.

Moving to top-level await will only speed up the cold start if the function is being kept warm but won't help in most situations.

**Comment by janpio** [comment] 2023-05-26 00:08
I am closing this issue for now. We further improved the cold start time after our blog post and my comment here, and are now generally happy with the cold start time even with massive schemas. `jsonProtocol` will soo be promoted to GA, and with that the default experience of using Prisma should have no negative impacts on cold starts in serverless environments any more compared to other database Clients.

**Closed by janpio** 2023-05-26 00:08 UTC
Labels: bug/1-unconfirmed, kind/bug, tech/engines, topic: serverless, team/client, topic: serverless framework, topic: deployment/aws-lambda, topic: schema-size
