### ISSUE TITLE
Relations not being picked up during create statement

### ISSUE THREAD

**Issue by lucasjohnston** [prisma/prisma#5788] opened 2021-02-22 16:42 UTC
## Bug description

Our `createUser()` function has stopped working, erroring that we aren't providing an `institutionUid` when we are using the `connect` func.
Prisma reports it is using `UserUncheckedCreateInput`, which doesn't have the relations beyond the uid. Not sure why this is now the default.

(I noticed @matthewmueller closed off `uncheckedScalarInputs` as stable [4 hours ago](https://github.com/prisma/prisma/issues/4209), not sure if a change has been made during that time or if that's just a coincidence).

## How to reproduce

1. Run a `prisma.[table-goes-here].create({})` query with a connection, such as:
```
institution: {
  connect: {
    institutionUid: institutionToAdd.institutionUid,
  },
},
```
2. Errors

## Expected behavior

The query to succeed.

## Prisma information
```
PrismaClientValidationError: 
Invalid `prisma.user.create()` invocation:

{
  include: {
    institution: true,
  },
  data: {
    userUid: '374174ea-2204-4a62-b033-9795a3fc31b3',
    institution: {
    ~~~~~~~~~~~
      connect: {
        institutionUid: 'df25802e-6cf5-4c21-bafc-141e2c296d58'
      }
    },
+   institutionUid: String,
  }
}

Unknown arg `institution` in data.institution for type UserUncheckedCreateInput. Did you mean `institutionUid`?
Argument institutionUid for data.institutionUid is missing.
```

## Environment & setup

- OS: macOS
- Database: PostgreSQL
- Node.js version: v12.18.1 (using ts-node version 8.10.2, typescript version 3.9.7)
- Prisma version: 

```
prisma               : 2.17.0
@prisma/client       : 2.16.1
Current platform     : darwin
Query Engine         : query-engine 3c463ebd78b1d21d8fdacdd27899e280cf686223 (at ../../../.config/yarn/global/node_mo
dules/@prisma/engines/query-engine-darwin)
Migration Engine     : migration-engine-cli 3c463ebd78b1d21d8fdacdd27899e280cf686223 (at ../../../.config/yarn/global
/node_modules/@prisma/engines/migration-engine-darwin)
Introspection Engine : introspection-core 3c463ebd78b1d21d8fdacdd27899e280cf686223 (at ../../../.config/yarn/global/n
ode_modules/@prisma/engines/introspection-engine-darwin)
Format Binary        : prisma-fmt 3c463ebd78b1d21d8fdacdd27899e280cf686223 (at ../../../.config/yarn/global/node_modu
les/@prisma/engines/prisma-fmt-darwin)
Studio               : 0.353.0
```
(edit: realised my prisma versions were out of sync so updated the client to `2.17.0`, same issue persists)

**Comment by lucasjohnston** [comment] 2021-02-22 16:46
(Ignore the close + reopen - after posting I suddenly thought I'd made a very oblivious mistake with variable naming, but that didn't make a difference unfortunately.)

**Comment by lucasjohnston** [comment] 2021-02-22 18:02
I've spent the evening looking through our codebase, I can't see any issue on our side. This is a major blocker for us, we can't even use Unchecked elements as it violates fkey restraints at a postgres level. Would really appreciate any help on this as we're supposed to be launching an mvp for friends & family tomorrow 😞

**Comment by Jolg42** [comment] 2021-02-25 08:43
I noticed in your report 
```
prisma               : 2.17.0
@prisma/client       : 2.16.1
```

Maybe try with both on 2.17.0? 

On which version was it working before?

**Comment by lucasjohnston** [comment] 2021-02-25 14:05
Yup, I noticed this too - upgraded, same error.
I'm now on these versions:
```
node: 14.15.5
tsc: 4.1.5
ts-node: 9.1.1
prisma: 2.17.0
@prisma/client: 2.17.0
```

I've now had to refactor the entire codebase to use `UncheckedInput`s for every Prisma entry.

**Comment by lucasjohnston** [comment] 2021-02-25 14:16
Not sure how prisma automatically switches between `Input` and `UncheckedInput` (navigating prisma's codebase is intimidating 😳) but I presume there's a piece of logic failing with schema.

Happy to share more detailed schema privately if it'll help with debugging.
We're on Postgres, using soft-delete middleware ([as per the docs)](https://www.prisma.io/docs/concepts/components/prisma-client/middleware/soft-delete-middleware), as well as prisma migrations. We also have a second prisma environment which generates custom schema on the fly for Jest tests.

An easy stopgap could be to add a `NoUncheckedInput` flag or similar in `schema.prisma` ?

**Comment by Jolg42** [comment] 2021-02-25 15:36
Note: `uncheckedScalarInputs` was released in 2.15 https://github.com/prisma/prisma/issues/4962

**Comment by lucasjohnston** [comment] 2021-03-01 23:31
Yeah - I'm guessing [that conditional](https://github.com/prisma/prisma-engines/pull/1510/files#diff-efb81c57c605b16a3837c43236a54a0e23829880752acb5f03b957d300b862ffR13) isn't behaving as intended.

```
// If the inputs are equal, only use one.
  if checked_input == unchecked_input {
      vec![checked_input]
  } else {
      vec![checked_input, unchecked_input]
  }
```

I don't understand why the `checked_update_many_input_type()` and `unchecked_update_many_input_type()` functions are both supposed to return the same result on a Model for the Client to validate references as `checked`.

Given it seems to be just us experiencing this (not many ppl are interacting with this issue), it would be useful to get more context about the logic of this function so I can attempt to debug what's happening. Do you have any unit tests for `create_objects.rs` that I can use to attempt repro? (cc @dpetrick)

**Comment by brantchoate** [comment] 2021-03-02 20:28
@lucasjohnston I'm having the same issue

**Comment by malekjaroslav** [comment] 2021-03-04 07:32
I have the same issue

**Comment by jrvidotti** [comment] 2021-03-05 21:25
I have the same issue...

**Comment by pantharshit00** [comment] 2021-03-06 05:50
Hey,

I am unable to reproduce this with version `2.18` and with the following code:
```ts
const post = await prisma.post.create({
    data: {
      title: "test",
      content: "test",
      author: {
        connect: {
          id: user.id,
        },
      },
    },
  });
```

Can anyone share your schema + a client call which triggers this so that we can reproduce and fix this?

**Comment by jrvidotti** [comment] 2021-03-06 10:17
I confirm that this error doesn't happen in `2.18`. Only my nexus-plugin-prisma complain version...

**Comment by janpio** [comment] 2021-03-09 17:44
That should be fixed now with the new release @jrvidotti: https://github.com/graphql-nexus/nexus-plugin-prisma/releases/tag/0.32.0

**Comment by andrew-hwahin** [comment] 2021-03-13 03:47
I've upgraded to v2.18 and it's still happening, is it if Prisma detected _postId_ then it'll automatically switch into unchecked mode?

**Comment by andrew-hwahin** [comment] 2021-03-13 04:00
I've just verified in my own codebase, if one of the fields is using the format of _postId_ instead of `post:{connect:{id}}` then it will automatically switch into unchecked mode. Once it switched into unchecked mode, then we're not able to use the `connect` _checked_ method anymore. Hence to use the checked mode, we need to switch all to use the checked method.

**Comment by malekjaroslav** [comment] 2021-03-13 11:14
> I've just verified in my own codebase, if one of the fields is using the format of _postId_ instead of `post:{connect:{id}}` then it will automatically switch into unchecked mode. Once it switched into unchecked mode, then we're not able to use the `connect` _checked_ method anymore. Hence to use the checked mode, we need to switch all to use the checked method.

I am facing exactly the same issue

**Comment by andrew-hwahin** [comment] 2021-03-13 16:12
> I am facing exactly the same issue

@malekjaroslav Did my suggestion solve your issue?

**Comment by pantharshit00** [comment] 2021-03-13 17:17
Can anyone share a minimal example with nexus for a reproduction?

**Comment by asciant** [comment] 2021-05-09 00:27
Hey everyone, I came across this error in my own application and believe that it is not a Prisma bug, but potentially a typing issue in our applications.

I created a repo to provide a little more information and some examples.

https://github.com/asciant/prisma2-unchecked-relations

Essentially, you will encounter issues like this (particularly when connecting 1-n or m-n relations) if your types don't match the input types that Prisma is using when creating, or updating. The types can be found in `./node_modules/.prisma/client/index.d.ts` and personally, I symlink this file to my main application directory because it's handy to refer to when issues arise.

Anyway, hopefully this helps anyone in future who comes across this like I did.

**Comment by pantharshit00** [comment] 2021-05-12 13:30
Thanks for the writeup @asciant

**Comment by matthewmueller** [comment] 2021-06-02 13:14
Closing as it sounds like this has been answered. Happy to re-open though with a reproduction.

**Closed by matthewmueller** 2021-06-02 13:14 UTC
Labels: bug/0-needs-info, kind/bug, team/client

**Comment by OmanCoding** [comment] 2021-07-23 07:35
> I've just verified in my own codebase, if one of the fields is using the format of _postId_ instead of `post:{connect:{id}}` then it will automatically switch into unchecked mode. Once it switched into unchecked mode, then we're not able to use the `connect` _checked_ method anymore. Hence to use the checked mode, we need to switch all to use the checked method.

True, I agree with your explanation,

so like this
``` 
.create({
  data:  {
    field1Id : fieldOneId,
    field2: {connect: {id: fieldTwoId}}
  }
}
```

field2 will cause Unknown arg `field2` in data.field2 for type EntityUncheckedCreateInput

### Solution 1
``` 
.create({
  data:  {
    field1 : {connect: {id: fieldOneId}},
    field2: {connect: {id: fieldTwoId}}
  }
}
```

### Solution 2

do .create() for field1Id, then do .update() for field2



@pantharshit00
@janpio

**Comment by huzaifahj** [comment] 2022-01-12 12:07
I think we should be able to do this, without any errors:

```js
await database.user.create({
        data: {
            organisationId: "1234",
            rooms: {
                connect: [{id: "5678"}, {id: "9012"}]
            }
        }
    })
```

At the very least there should be a clearer error message. I had to find this issue to verify that this error is expected behaviour.

Can someone explain if there is a logical reason for this behaviour?

**Comment by janpio** [comment] 2022-01-12 12:22
Can you be more concrete what you mean exactly @huzaifahj? It is hard to figure out what you refer to from the above.

**Comment by huzaifahj** [comment] 2022-01-12 12:25
@janpio I am not sure why we can't directly set a foreign key and use the `connect` syntax in the same model query.

**Comment by janpio** [comment] 2022-01-12 12:55
Can you open a new bug report issues for this and include a full reproduction and explanation of this? Might be that our types are not flexible enough for this yet but sounds a bit unrelated to what this issue was about and the explanation that caused this issue to be closed.
