### ISSUE TITLE
Allow `.create()` to prescribe ordering of nested sub-graph processing

### ISSUE THREAD

**Issue by pbelbin** [prisma/prisma#2793] opened 2020-06-17 21:17 UTC
## Problem

**The TypeScript client appears to always process nested inserts in alphabetical order**.

Because the definition of the `create()` request is being put into an object, not an array, I guess it makes sense that the ordering of items being added to the object is lost, and using something like `Object.entries()` is then going to offer the contents in alphabetical order.

I don't know if there is any 'intelligence' around the order of the nested inserts being done, but it appears that more is needed.

With a model definition such as:

```
model Group {
  id         Int         @id @default(autoincrement())
  name       String      @unique
  userGroups UserGroup[]

  @@map("group")
  Post Post[]
}

model UserGroup {
  group_id Int
  user_id  Int
  role     GroupMemberRole
  as_of    DateTime        @default(now())

  group Group @relation(fields: [group_id], references: [id])
  user  User  @relation(fields: [user_id], references: [id])

  @@id([group_id, user_id])

  @@map("group_user")
}

enum GroupMemberRole {
  ADMIN
  MEMBER
}

model User {
  id     Int          @default(autoincrement()) @id
  email  String
  name   String
  joined DateTime     @default(now())
  rating user_rating?

  posts      Post[]
  friends    Friend[]
  userGroups UserGroup[]


  @@map("user")
  Friend Friend[] @relation("hub")
}

model Friend {
  user_id   Int
  friend_id Int
  rating    friend_rating

  user   User @relation(name: "hub", fields: [user_id], references: [id])
  friend User @relation(fields: [friend_id], references: [id])

  @@id([user_id, friend_id])
  @@map("friend")
}

model Post {
  author_id Int
  id        Int      @default(autoincrement()) @id
  published Int?     @default(0)
  date      DateTime @default(now())
  group_id  Int

  rating post_rating?
  title  String
  author User         @relation(fields: [author_id], references: [id])
  group  Group        @relation(fields: [group_id], references: [id])

  @@map("post")
  @@index([author_id], name: "author_ix")
}

enum friend_rating {
  SUPER
  SO_SO
  FAIR_WEATHER
}

enum post_rating {
  GOOD
  BAD
  OTHER
}

enum user_rating {
  super
  duper
  good
  really_good  @map("really good")
  meh
  HR12 @map("12HR")
  HR24 @map("24HR")
}


```

and I then proceed to create a user with nested creation of a group, and a reference to that same newly created group via the 'userGroups' and 'posts' nested graphs.  This is so that all of the work will be done within a single transaction.:

```
await prisma.user.create({
    data: {
      name: 'fred flintstone',
      email: 'fred@flintstone.org',
      userGroups: {
        create: [
          {
            role: GroupMemberRole.MEMBER,
            group: {
              create: {
                name: 'group1',
              },
            },
          },
        ],
      },
      posts: {
        create: [
          {
            group: {
              connect: {
                name: 'group1',
              }
            },
            title: 'post 1',
          },
        ],
      },
    }
  });
```

I am greeted with:

```
(node:75240) UnhandledPromiseRejectionWarning: Error: 
Invalid `prisma.user.create()` invocation in
/Users/me/prisma/starter/script.ts:10:21

   6 async function main() {
   7   const allUsers = await prisma.user.findMany();
   8   console.log(allUsers);
   9   
→ 10   await prisma.user.create(
  Query interpretation error. Error for binding '2': AssertionError("[Query Graph] Expected a valid parent ID to be present for a nested connect on a one-to-many relation.")
    at PrismaClientFetcher.request (/Users/me/prisma/starter/node_modules/@prisma/client/src/runtime/getPrismaClient.ts:762:15)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:75240) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:75240) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

```

If I switch the 'connect' and 'create' for the nested creation of the 'group', then all is well, because 'posts' sorts earlier than 'userGroups'.  (the ordering can be seen if you enable DEBUG=* environment variable).  But, this is just one example.   The handling of these nested sub-graph requests in alphabetical order is quite painful.  

## Suggested solution

allow users to optionally provide a list which indicates the order in which the nested builds are to happen.

eg:

```
await prisma.user.create({
nestedOrder: [ 'userGroups','posts' ],
data: { // as above}
})
```

or:
within each nested section, an 'order' property could be set to a value, and this can be used to sort the nested sections before executing them in that order.

eg:

```
.
.
posts: {
  order: 2,
  create: : [...],
},
userGroups: {
  order: 1,
  create: [...],
}
.
.
```

This would provide a way for the caller to tell the engine the order in which the nested sections are to be handled rather than just by alphabetic order as they are now.

**Comment by pantharshit00** [comment] 2020-06-20 03:41
I think you could use the new tranaction API(which will be released in 2.1) here but I think this is something that we can explore. 

Learn more about the new transaction API here: https://github.com/prisma/prisma-client-js/issues/667#issuecomment-643750802 and https://github.com/prisma/prisma/pull/2806

**Comment by pbelbin** [comment] 2020-06-20 04:15
Thank you @pantharshit00 .  When is 2.1 likely to be released?

**Comment by pantharshit00** [comment] 2020-06-20 04:50
It is planned to be released next week. You can also try out that feature in the dev channel(`npm install @prisma/cli@dev @prisma/client@dev`) once #2806 is merged.

**Comment by pbelbin** [comment] 2020-06-30 18:54
Please note, while the use of the new `.transaction([])` can be useful, it's a bit painful to do this, as it pretty much negates the benefit of the nested graph, particularly when you're inserting a new record at the core of the `.create()`.  This is not just a `create` issue, but is likely an issue anywhere the nested logic is able to be used, so it would be really good to see this being addressed sooner rather than later.

**Comment by matthewmueller** [comment] 2020-11-04 16:25
To avoid confusion:

> The TypeScript client appears to always process nested inserts in alphabetical order.

This isn't quite correct. From @dpetrick;

> The user has no influence on the order of operations executed, because there are many instances where we reorder queries to form an executable query graph.

The issue is still valid, how do you connect complex relations together atomically? This will likely be solved if we're able to solve "mutations that depend on each other" in #1844.

**Comment by matthewmueller** [comment] 2020-11-30 12:12
Hey @pbelbin, do you mind sharing what the intended purpose of this query in your application? 

Something like, we're creating a forum where you can post messages without being signed up yet and also you can choose your group where the post will show up.

**Closed** 2020-11-30 12:29 UTC
Labels: kind/feature, tech/typescript, topic: transaction
