### ISSUE TITLE
java.lang.RuntimeException: Encountered unknown SQL type jsonb with column data. IntrospectedColumn(data,jsonb,null,true)

### ISSUE THREAD

**Issue by chris-rock** [prisma/prisma#4591] opened 2019-05-28 12:41 UTC
**Describe the bug**

Prisma crashes as soon as there is a table in a schema that includes a postgres JSONB column. This happens even if the prisma gql spec is not including a definition for the table.

The server throws the following error and the prisma cli is not able to deploy any managed schema updates.

```
java.lang.RuntimeException: Encountered unknown SQL type jsonb with column data. IntrospectedColumn(data,jsonb,null,true)
...
"message":"Encountered unknown SQL type jsonb with column policy. IntrospectedColumn(policy,jsonb,null,false)"}}
java.lang.RuntimeException: Encountered unknown SQL type jsonb with column data. IntrospectedColumn(data,jsonb,null,true)
	at scala.sys.package$.error(package.scala:26)
	at com.prisma.deploy.connector.jdbc.DatabaseInspectorBase.$anonfun$getTable$6(DatabaseInspectorBase.scala:51)
	at scala.Option.getOrElse(Option.scala:121)
	at com.prisma.deploy.connector.jdbc.DatabaseInspectorBase.$anonfun$getTable$5(DatabaseInspectorBase.scala:51)
	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:233)
	at scala.collection.Iterator.foreach(Iterator.scala:937)
	at scala.collection.Iterator.foreach$(Iterator.scala:937)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1425)
	at scala.collection.IterableLike.foreach(IterableLike.scala:70)
	at scala.collection.IterableLike.foreach$(IterableLike.scala:69)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
	at scala.collection.TraversableLike.map(TraversableLike.scala:233)
	at scala.collection.TraversableLike.map$(TraversableLike.scala:226)
	at scala.collection.AbstractTraversable.map(Traversable.scala:104)
	at com.prisma.deploy.connector.jdbc.DatabaseInspectorBase.$anonfun$getTable$4(DatabaseInspectorBase.scala:48)
	at slick.dbio.DBIOAction.$anonfun$map$1(DBIOAction.scala:43)
	at slick.basic.BasicBackend$DatabaseDef.$anonfun$runInContextInline$1(BasicBackend.scala:171)
	at scala.concurrent.Future.$anonfun$flatMap$1(Future.scala:303)
	at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:37)
```

I understand that prisma does not support JSONB queries, but it should not crash if it find an (prisma) unmanaged table.

**To Reproduce**

create a table with:
```
CREATE TABLE "project$latest"."cards" (
  id character varying(25) PRIMARY KEY NOT NULL,
  board_id integer NOT NULL,
  data JSONB
);
```

Then run prisma introspect, which creates
```
type Card @db(name: "cards") {
  id: ID! @id
  boardId: Int! @db(name: "board_id")
  data: Json
}
```

Then run prisma deploy:
```
$ prisma deploy
...
ERROR: Whoops. Looks like an internal server error. Search your server logs for request ID: local:cjw7sajg1lrc607987s1ik2fz

{
  "data": {
    "deploy": null
  },
  "errors": [
    {
      "message": "Whoops. Looks like an internal server error. Search your server logs for request ID: local:cjw7sajg1lrc607987s1ik2fz",
      "path": [
        "deploy"
      ],
      "locations": [
        {
          "line": 2,
          "column": 9
        }
      ],
      "requestId": "local:cjw7sajg1lrc607987s1ik2fz"
    }
  ],
  "status": 200
}
```

Interestingly, that error even happens if the table is not added to the gql spec via introspection.

**Expected behavior**

prisma ignores un-managed tables, or is at least able to deal with unsupported column types in a graceful way.

**Screenshots**
n/a

**Versions (please complete the following information):**
 - Connector: [e.g. `Postgres`, `MySQL`, `MongoDB`]
 - Prisma Server: 1.33
 - `prisma` CLI: prisma/1.33.0 (darwin-x64) node-v11.13.0
 - OS: `OS X High Sierra`

**Additional context**

**Comment by pantharshit00** [comment] 2019-05-28 17:22
Closing as a duplicate of # 4190. Please add this information as a comment there.

**Closed by pantharshit00** 2019-05-28 17:22 UTC
