### ISSUE TITLE
Prisma2 packages causes Yarn install devDependencies on --prod

### ISSUE THREAD

**Issue by turbothinh** [prisma/prisma#1285] opened 2020-01-07 14:09 UTC
I don't know which repo should this issue belong to, but apparently, `prisma` packages causes `yarn --prod` to install all `devDependencies` (not `npm install --prod=true`). Adding either `@prisma/photon` or `nexus-prisma` to `dependencies` cause the wrong yarn behavior, and it is fixed if I moved all `prisma` packages to `devDependencies`.

Please have a look into this Yarn issue I created as well.
https://github.com/yarnpkg/yarn/issues/7801

Could anyone please explain this problem?

**Comment by pantharshit00** [comment] 2020-01-07 18:21
Can you please share your package.json file here?

**Comment by pantharshit00** [comment] 2020-01-07 18:28
I am unable to reproduce this. I used yarn --prod and yarn didn't fetch any devdependencies for me. Maybe try clearing your yarn cache.

![image](https://user-images.githubusercontent.com/22195362/71918969-86431a00-31a9-11ea-8dc8-7c2c2fb503db.png)

**Comment by turbothinh** [comment] 2020-01-08 13:31
@pantharshit00 yep, it doesn't fetch all the devDependencies, it does fetch `prisma2` though.

**Comment by pantharshit00** [comment] 2020-01-09 11:32
Yes, I can reproduce this. I think this is more related to yarn as npm doesn't fetch it and we have correctly listed it as a peer dependency in `nexus-prisma`(which lists `@prisma/photon` as peerDep) and `@prisma/photon`(which lists `prisma2` as peerDep). I think it has to with how yarn resolves peerDependencies but I am not an expert on dependency resolution. I also tested pnpm and it also doesn't grab these packages so clear this is very yarn specific:
<img width="1399" alt="image" src="https://user-images.githubusercontent.com/22195362/72064067-1f387900-3301-11ea-83fc-654cf0024648.png">

Right now as a workaround you can just remove it and use a global install or use it via npx. The size of prisma2 is currently big because we need to ship typescript. 

To understand why we ship typescript here is our current generation process:
1. Call `prisma2 generate` (either from `@prisma/photon`s postinstall hook or from the user directly)
2. `prisma2 generate` now calls the `@prisma/photon` generator located in @prisma/photon/generator-build/index.js. This generator in memory creates an `index.ts` file, including the individual Photon build of the project. Now typescript comes in to play: It turns the `index.ts` file into an `index.js` and `index.d.ts` file. We have it on our todo list to directly generate an `index.js` and `index.d.ts` file, without the use of TypeScript. That will happen fairly soon / hopefully in Q1. That will make the package size more managable.

We require `prisma2` as a peer dep in the first place as `@prisma/photon`'s hook needs prisma2 to run generate. But as soon as the generation is done, prisma2 is not needed anymore. That means when people have the build done, prisma2 is not needed anymore. So that is why it is not a direct dependency but a peerDependency.

**Comment by pantharshit00** [comment] 2020-01-09 11:33
I will wait on yarn maintainers to respond here for now

**Comment by turbothinh** [comment] 2020-01-09 12:18
@pantharshit00 thank you for the response. Using **prisma2** through **npx** or global installation is not solving the problem, a **nexus-prisma** must be in `dependencies` where it allows nexus to use `model` and `crud`. Leaving **nexus-prisma** makes **prisma2** installed as well. We have no problem with moving **photon** to `devDependencies` as we generate **photon** before deployment anyway, so **photon** is actually not causing the problem.

According to [types of dependencies](https://yarnpkg.com/en/docs/dependency-types) from **yarn* * docs, "having a peer dependency means that your package needs a dependency that is the same exact dependency as the person installing your package". This explains why sometimes I got complained sometimes when installing **photon** and **prisma2** in different versions. E.g.
```
    "@prisma/photon": "^2.0.0-preview018",
    "prisma2": "^2.0.0-preview019",
```
Though, it missed the explaination for how **yarn** resolves `peerDependencies` unless that is all it does.

**Comment by pantharshit00** [comment] 2020-01-09 12:27
> This explains why sometimes I got complained when installing photon and prisma2 in different versions. E.g.


Yarn doesn't generate that warning, we doesn. We mark as `prisma2` dep as `*` so yarn won't complain.

---

If you remove `prisma2` from devDependecies, it doesn't install it at all in prod mode:
<img width="1367" alt="image" src="https://user-images.githubusercontent.com/22195362/72067659-4dba5200-3309-11ea-9f69-7527021a6f35.png">


So my workaround here is to remove `prisma2` from package.json and use global cli.

**Comment by turbothinh** [comment] 2020-01-09 12:46
> So my workaround here is to remove `prisma2` from package.json and use global cli.

@pantharshit00 yep, that doesn't install **prisma2** in `node_modules` anymore, but still add `@types` and `@prisma/photon`, even though we have custom output path for **photon**. The final size of `node_modules` excluding **prisma2** is still 90M in this case, which is still way bigger than `npm --prod=true` 40M.

I hope **yarn** would have more explanations on how `peerDependencies` is resolved on their docs.

**Comment by pantharshit00** [comment] 2020-01-09 12:57
Yes, same, I already explained why photon is huge right now and we will take actions to fix it but for now maybe stick with npm.

**Comment by divyenduz** [comment] 2020-01-20 11:40
@turbothinh Thanks for raising this issue, this is indeed reproducible and is being tracked here already https://github.com/prisma/photonjs/issues/388

I will close this one because the other issue has a cleaner reproduction. Please comment here and tag me if you disagree 🙏 

Please follow the other one for a resolution. We are shipping typescript because it is a peer dependency of Prisma client (formerly Photon.js). 

It (and `prisma2` CLI package) can be manually removed for now from `node_modules` before bundling and that should be a workaround for you.

**Comment by pantharshit00** [comment] 2020-01-21 13:17
@divyenduz This issue does touch on the package size for a bit but the actual problem is different here which is yarn install all of our packages when we specify nexus-prisma as a dependency and prisma2 a devDependency in production mode. So I think we should keep this open for now.

**Comment by pantharshit00** [comment] 2020-01-21 13:19
Yarn already confirms this is a bug on their end: https://github.com/yarnpkg/yarn/issues/7801 

Maybe we close this after that is fixed.

**Comment by janpio** [comment] 2021-03-24 18:10
Yarn closed the issue:

> Closing as fixed in v2 where yarn workspaces focus --production only keeps dependencies

**Comment by matthewmueller** [comment] 2021-03-31 14:52
Next step: verify that this works now

**Comment by matthewmueller** [comment] 2021-04-12 14:44
Fellas. I gave up. 

I can confirm this is still a problem as of yarn@1.22.4 but I gave up trying to try it on Yarn 2. Since Yarn 1 is in maintenance mode, I don't see this getting fixed.

**Workarounds:**

- Use NPM
- Try `yarn workspaces focus --production` and report back if it works. 

Closing for now. Time for a drink.

**Closed** 2021-04-12 14:44 UTC
Labels: bug/1-repro-available, kind/bug, team/client, topic: ecosystem
