### ISSUE TITLE
Cannot delete a tuple on which a relation depends

### ISSUE THREAD

**Issue by euberdeveloper** [prisma/prisma#6452] opened 2021-04-07 18:01 UTC
## Bug description

I have a model `Contratto` (contract). Every contract has one or more guests and the relation `ContrattoSuOspite` (contract-on-guests) is a relation made exactly to connect the guests to a contract. There is the **delete cascade**, so there should be no problem in deleting the contract. Instead, I have an error.

## How to reproduce

The (simplified) schema is:

```prisma
model Contratto {
    id Int @id @default(autoincrement()) @map("id")

    dataInizio DateTime @map("data_inizio")
    dataFine   DateTime @map("data_fine")
    checkout Float?   @map("checkout")
    cauzione Float?   @map("cauzione")
    note String? @map("note")

    contrattiSuOspite ContrattoSuOspite[]

    @@map("contratto")
}


model Ospite {
    id Int @id @default(autoincrement()) @map("id")
    nome String @map("nome")
}

model ContrattoSuOspite {
    idContratto Int       @map("id_contratto")
    contratto   Contratto @relation(fields: [idContratto], references: [id])

    idOspite Int    @map("id_ospite")
    ospite   Ospite @relation(fields: [idOspite], references: [id])

    dataCheckin          DateTime? @map("data_checkin")
    dataCheckout         DateTime? @map("data_checkout")

    @@id([idContratto, idOspite])
    @@map("contratto_su_ospite")
}
```

Then I try to delete a contratto:

```ts
await prisma.contratto.delete({ where: { id: 1 } });
```

## Expected behavior

It should delete both the contratto and its contratto-su-ospite (contract-on-guest) tuples.

## Prisma information

I get this error instead:

```
[ERROR] Server error PrismaClientKnownRequestError2 [PrismaClientKnownRequestError]: 
Invalid `prisma.contratto.delete()` invocation:


  The change you are trying to make would violate the required relation 'ContrattoToContrattoSuOspite' between the `Contratto` and `ContrattoSuOspite` models.
    at cb (/home/euber/Github/150/operatn-backend/node_modules/@prisma/client/runtime/index.js:79160:17)
    at processTicksAndRejections (node:internal/process/task_queues:94:5) {
  code: 'P2014',
  clientVersion: '2.18.0',
  meta: {
    relation_name: 'ContrattoToContrattoSuOspite',
    model_a_name: 'Contratto',
    model_b_name: 'ContrattoSuOspite'
  }
}
```

I also do not want to set the relation optional, because it is not and it is not necessary because of the delete cascade.

## Environment & setup

- OS: Ubuntu 20
- Database: Postgres
- Node.js version: 15.11.0
- Prisma version: 2.18

```

```

**Comment by janpio** [comment] 2021-04-07 18:24
Duplicate of https://github.com/prisma/prisma/issues/2328

**Closed by janpio** 2021-04-07 18:24 UTC
