### ISSUE TITLE
Error: binaryTargets.flatMap is not a function

### ISSUE THREAD

**Issue by BitMaster001** [prisma/prisma#13001] opened 2022-04-26 03:24 UTC
### Bug description

```
root@ip-174-34-20-141:/home/ubuntu/nextjsProject/# npx prisma migrate dev --name init
Prisma schema loaded from prisma/schema.prisma
Datasource "database": MySQL database "mydb" at "127.0.0.1:3306"

Applying migration `20220426030157_init`

The following migration(s) have been created and applied from new schema changes:

migrations/
  └─ 20220426030157_init/
    └─ migration.sql

Your database is now in sync with your schema.

Running generate... (Use --skip-generate to skip the generators)
Error: binaryTargets.flatMap is not a function
```

### How to reproduce

`npx prisma generate
`

### Prisma information

```
generator client {
  provider = "prisma-client-js"
  binaryTargets = ["native"]
}

model Winners {
  id      Int     @id @default(autoincrement())
  answer1 String @default("")
}

datasource database {
  provider = "mysql"
  url      = "mysql://user:+1%JbKy*qgG^Du4T@127.0.0.1:3306/mydb"
}
```

### Environment & setup

- OS: Ubuntu
- Database: MySQL
- Node.js version: 16.14.2

### Prisma Version

prisma version: 3.12.0

**Comment by dpetrick** [comment] 2022-04-26 14:30
Next steps: Reproduction

**Comment by BastanR** [comment] 2022-05-02 18:22
@BitMaster001 Had the same issue, looks like my CLI did not apply proper Node version before running the command. Can you maybe run `node -v` before the script itself, so you are sure you are running new Node version?

**Comment by otaviobertucini** [comment] 2022-09-02 22:20
Updating the node version solved the problem to me.

**Comment by aqrln** [comment] 2023-05-17 16:40
I can only reproduce it when switching to Node.js 10, which was not supported by Prisma 3.12. Given this and the above comments, and since there was no follow up from the original reporter, I'll close this issue.

**Closed by aqrln** 2023-05-17 16:40 UTC
Labels: bug/1-unconfirmed, kind/bug, topic: prisma generate, team/client
