### ISSUE TITLE
Cascade delete does not work unless relation is optional

### ISSUE THREAD

**Issue by dodas** [prisma/prisma#2212] opened 2020-04-16 21:12 UTC
## Bug description
When I set db CONSTRAINT to CASCADE on delete and relation is marked as required in schema, prisma errors with
```
The change you are trying to make would violate the required relation 'UserToPost' between the `User` and `Post` models.
```
It works when I set the foreign key and the relation field as optional in prisma schema.

## How to reproduce
1. Set delete behaviour to cascade in db:
```sql
ALTER TABLE public.Post
DROP CONSTRAINT Post_authorId_fkey,
ADD CONSTRAINT Post_authorId_fkey
   FOREIGN KEY (authorId)
   REFERENCES public.User (id)
   ON DELETE CASCADE
   ON UPDATE CASCADE;
```
2. create at least one User and one Post that belongs to him.
3. try to delete that User with prisma client

## Expected behavior
The user and all his posts should be deleted.

## Prisma information
schema:
```
model User {
  id        Int      @id @default(autoincrement())
  posts     Post[]
}

model Post {
  id        Int   @id @default(autoincrement())
  author    User  @relation(fields: [authorId], references: [id])
  authorId  Int
}
```

## Environment & setup
DB: Postgres 11.4
Prisma: 2.0.0-beta.2
Node: 12.2.0

**Comment by pantharshit00** [comment] 2020-04-19 10:06
I can confirm this. We need to loosen the validation in the query engine

**Comment by elliscwc** [comment] 2020-04-19 10:11
I followed the latest docs and have this issue as well when trying to delete an item with graphql 
```
The change you are trying to make would violate the required
relation 'DayToItinerary' between the `Day` and `Itinerary` models.
```

my schema:
```
model Itinerary {
  id            String    @default(cuid()) @id
  name          String
  days          Day[]
  owner         User      @relation(fields: [ownerID], references: [id])
  ownerID       String
}

model Day {
  id           String     @default(cuid()) @id
  date         DateTime?
  description  String?
  itinerary    Itinerary  @relation(fields: [itineraryID], references: [id])
  itineraryID  String
}
```

**Comment by pantharshit00** [comment] 2020-04-19 10:12
SQL of the database for direct reproduction:
```sql
DROP TABLE IF EXISTS "public"."Post";

-- Sequence and defined type
CREATE SEQUENCE IF NOT EXISTS "Post_id_seq";

-- Table Definition
CREATE TABLE "public"."Post" (
    "authorId" int4 NOT NULL,
    "id" int4 NOT NULL DEFAULT nextval('"Post_id_seq"'::regclass),
    PRIMARY KEY ("id")
);

DROP TABLE IF EXISTS "public"."User";
-- Sequence and defined type
CREATE SEQUENCE IF NOT EXISTS "User_id_seq";

-- Table Definition
CREATE TABLE "public"."User" (
    "id" int4 NOT NULL DEFAULT nextval('"User_id_seq"'::regclass),
    PRIMARY KEY ("id")
);

INSERT INTO "public"."Post" ("authorId", "id") VALUES
('1', '1');

INSERT INTO "public"."User" ("id") VALUES
('1');

ALTER TABLE "public"."Post" ADD FOREIGN KEY ("authorId") REFERENCES "public"."User"("id") ON DELETE CASCADE ON UPDATE CASCADE;

```

You can introspect that database and try a deletion query as shown below to reproduce this:
```js
  const del = await prisma.user.delete({
    where: {
      id: 1,
    },
  });
```

**Comment by mavilein** [comment] 2020-04-22 12:28
This is not a bug but by design. We enforce required relations on the Prisma layer. The schema clearly states that `Post.author` is required. The query engine finds a related `Post` record for the user and hence rejects the change.
I see two possible fixes:
1. You could change `Post.author` to be optional for now. (as the title suggests)
2. The real long term fix is to implement cascading deletes. Then the information about cascading deletes would be present in the schema and the query engine could act accordingly.

**Comment by dodas** [comment] 2020-04-22 12:36
Please don't say it's not a bug.
It is clearly [documented](https://prisma2.netlify.app/guides/database-workflows/cascading-deletes/postgresql/) that cascade deleted should work if they are defined on database level.

Changing all relations to optional is no-go, as that would generate TS types as nullable and that means a lot of (previously unnecessary) prop checking in JS.

Hopefully this can be fixed shortly.

Thanks for great work on prisma!

**Comment by mavilein** [comment] 2020-05-12 13:12
duplicate of: https://github.com/prisma/prisma/issues/2057

**Comment by pantharshit00** [comment] 2020-05-14 10:40
Closing as a duplicate of #2057

**Closed by pantharshit00** 2020-05-14 10:40 UTC
Labels: bug/2-confirmed, kind/bug, team/engines, topic: cascade
