### ISSUE TITLE
(Re)Introspection does not respect variables in dotenv file when schema is located in a custom directory

### ISSUE THREAD

**Issue by ExiaSR** [prisma/prisma#2924] opened 2020-07-02 20:19 UTC
## Bug description

When the schema file is located in a custom directory, the dotenv file located in the same directory as the schema file, is not read by the Prisma CLI.

## How to reproduce

Assuming we have the following project structure,

- __test\-prisma\-dotenv__
   - __db__
     - [.env](db/.env)
     - [schema.prisma](db/schema.prisma)
   - [node\_modules](node_modules)
   - [package.json](package.json)
   - [yarn.lock](yarn.lock)

Then run the following command to re-introspect in the project root directory

`yarn prisma introspect --schema db/schema.prisma --experimental-reintrospection`

Results in such error

```
Introspecting based on datasource defined in db/schema.prisma …
Error: Error in datamodel: ErrorCollection { errors: [EnvironmentFunctionalEvaluationError { var_name: "DATABASE_URL", span: Span { start: 160, end: 179 } }] }
```

However, if we run the command without the `--experimental-reintrospection`, it works as expected that the Prisma CLI respects the environment variable in the dotenv file.

## Prisma information

```
// This is your Prisma schema file,
// learn more about it in the docs: https://pris.ly/d/prisma-schema

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

generator client {
  provider = "prisma-client-js"
}
```

## Environment & setup

- OS: 
- Database: 
- Prisma version: 
- Node.js version:

**Comment by pantharshit00** [comment] 2020-07-02 20:43
Thanks for the bug report @ExiaSR. I can confirm this issue. This is not exclusive to reintrospection but it also occurs when I try to use the `--print` flag. We will need to fix this.

![image](https://user-images.githubusercontent.com/22195362/86407484-c3104980-bcd2-11ea-9174-912e361914ab.png)

**Comment by zaunermax** [comment] 2020-07-08 13:52
after updating I also stumbled across this issue, however in my case I do not have a custom directory but a different `.env` file in the root of my project. My workaround is to just put the database connection in the root env file. Not sure if this is intended that way.

**Comment by janpio** [comment] 2020-07-08 20:37
Possibly related: https://github.com/prisma/prisma/issues/2971

**Comment by timsuchanek** [comment] 2020-07-21 09:37
Thanks for reporting! This has been fixed in https://github.com/prisma/prisma/pull/2979

**Closed by timsuchanek** 2020-07-21 09:37 UTC
Labels: bug/2-confirmed, kind/bug, team/typescript, topic: cli-introspect, topic: env, topic: introspection

**Comment by mjknight50** [comment] 2020-09-29 13:16
@timsuchanek  This same error happened for me today.

**Comment by janpio** [comment] 2020-09-29 13:18
Please create a new issue @mjknight50 and supply some more information - best fill the issue template.

**Comment by jamesguan** [comment] 2020-10-07 14:21
> @timsuchanek This same error happened for me today.
> ` ErrorCollection { errors: [EnvironmentFunctionalEvaluationError { var_name: "DATABASE_URL"`
> 
> "@prisma/cli": "^2.8.0",
> "@prisma/client": "^2.6.2",
> 
> My schema is:
> 
> ```
> generator client {
>   provider = "prisma-client-js"
> }
> 
> datasource mysql {
>   provider = "mysql"
>   url      = env("DATABASE_URL")
> }
> ```
> 
> The path is irregular:
> /server/data/prisma/schema.prisma

Hope this helps, I have a `.env` file in a parent directory and tried to delete the .env file that was in the prisma folder. However, it seems that `npx prisma introspect` does not pick up the `.env` file from the parent directory so I had to explicitly define another `.env` file in the prisma folder. Is it the case that the `.env` file has to be in the prisma folder for prisma environment variables?

**Comment by Jolg42** [comment] 2020-10-07 14:39
@jamesguan so the behavior of how the .env is automatically loaded is here https://www.prisma.io/docs/reference/tools-and-interfaces/prisma-schema#using-env-files 😃
