### ISSUE TITLE
Prisma Edge Client + CF Worker `process not defined`

### ISSUE THREAD

**Issue by vidiabtc** [prisma/prisma#13771] opened 2022-06-12 17:34 UTC
### Bug description

Getting `process not found error` when deploying the prisma Edge client to Cloudflare pages. Isn the Edge client supposed to prevent this error from happening? I am only using the client in SvelteKit Endpoints https://kit.svelte.dev/docs/routing#endpoints

NOTE: I am using dot-env package to run the local dev script in package.json as prisma cannot find my .env DATABASE_URL var without this command (Maybe this is related to the issue?)

Err Log: 

` {
        text: 'Uncaught ReferenceError: process is not defined\n' +
          '  at line 8755 in node_modules/.prisma/client/edge.js\n' +
          '  at line 16 in __require2\n' +
          '  at line 8768 in node_modules/@prisma/client/edge.js\n' +
          '  at line 16 in __require2\n' +
          '  at line 8774\n' +
          '  at line 8789\n' +
          ' [code: 10021]'
      }
`

### How to reproduce

1. Set up Prisma data-proxy in SvelteKit following this instructions https://www.prisma.io/docs/concepts/data-platform/data-proxy
2. Deploy to CF pages and see that it builds successfully, but when visiting a page it will have the process not found error

You should be using the Edge Client and --data-proxy option with npx prisma generate. And your database_url should start wit prisma://

### Expected behavior

I'm not executing code that is meant for the server on the client so I dont understand why this error is happening

### Prisma information

I have a demo of the issue here https://github.com/vidiabtc/sveltekit-test

### Environment & setup

- OS: MacOS-->
- Database: MySQL
- Node.js version: v16.7.0

### Prisma Version

```
		"prisma": "^3.15.1",
		"@prisma/client": "^3.15.1",

```

**Comment by agcty** [comment] 2022-06-15 08:25
I'm having the same issue when trying to deploy a Remix application to cloudflare pages. Using the edge client generated with prisma generate --data-proxy, but it always complains that DATABASE_URL isn't found.

Here's how I set my env variables:
"dev:wrangler": "cross-env NODE_ENV=development wrangler pages dev ./public --binding $(cat .env)"

Also tried it with a wrangler.toml file to no avail.

Error:

[dev:*wrangler] [pages:err] ReferenceError: DATABASE_URL is not defined.
[dev:*wrangler] Attempted to access binding using global in modules.
[dev:*wrangler] You must use the 2nd `env` parameter passed to exported handlers/Durable Object constructors, or `context.env` with Pages Functions.

**Comment by diopitis** [comment] 2022-06-15 13:52
I am getting the same issue when deploying a sveltekit application on CF pages.

**Comment by edwinbrowwn** [comment] 2022-06-17 20:30
I'm getting the same problem when deploying on CF Workers

**Comment by drewdecarme** [comment] 2022-06-22 19:16
Wrangler has a bit of a different way of deploying things and since you're deploying the edge with Wrangler you need to account for a few things.

First, you need to make sure you're using `wrangler@2` instead of `@cloudflare/wrangler`. The Cloudflare team made some upgrades and released it under a different package name, BUT with the same CLI reference... which is weird I must admit. For more information on the migration from 1 to 2, check this article out. https://developers.cloudflare.com/workers/wrangler/compare-v1-v2/. Last I checked, the remix bootstrap includes `@cloudflare/wrangler` in their initial dependencies which is definitely confusing.

With that said, you need to add your environment variables to wrangler and via Node which your most likely used to doing. For the catch all, you can set them using `wrangler secret put DATABASE_URL` or if you have an environment you should define the environment you want. So if you have a production environment that you've defined in your `wrangler.toml`, you can set your variables using `wrangler secret put DATABASE_URL --env production`.

Here's an example of how I manage my `wrangler.toml`

```toml
compatibility_date = "2022-01-05"
compatibility_flags = []

name = "woodshop-api"
account_id = "YOUR_ACCOUNT_ID"
workers_dev = true
# [ secrets ] #
# DATABASE_URL
# SHADOW_DATABASE_URL

[env.production]
workers_dev = false
# [ env.production.secrets ] #
# DATABASE_URL
```

And to add environment variables for each of them it's the following:
```bash
# global
wrangler secret put DATABASE_URL
wrangler secret put SHADOW_DATABASE_URL

# production
wrangler secret put DATABASE_URL --env production
```

And to run those in development and production respectively would be
```bash
# dev
wrangler dev --ip 127.0.0.1 --port 8888

# prod (most likely in CI)
wrangler publish ./src/handler.ts --env production
```

The above should take care of your issue.

ON the flip side, the problem with `process` being referenced in an edge environment is still problematic.

**Comment by drewdecarme** [comment] 2022-06-22 19:48
After diving through the documentation a little bit more for Cloudflare Workers, you can add a `node_compat` field to your `wrangler.toml` and that should get you passed the process issue. Again, it's still something that we _technically_ shouldn't have to account for since this is an edge environment, not a node one.

https://developers.cloudflare.com/workers/wrangler/configuration/#configure-wranglertoml

**Comment by edwinbrowwn** [comment] 2022-06-22 21:54
I have all of that set up and I still get the same error.. oddly. https://github.com/edwinbrowwn/cloudflare-gql-api

**Comment by essarn** [comment] 2022-07-05 04:45
> I'm getting the same problem when deploying on CF Workers
> 
> ```
> {
>   text: 'Uncaught Error: InvalidDatasourceError: Could not parse URL of the datasource\n' +
>     '  at line 0\n' +
>     ' [code: 10021]'
> }
> ```

Having the same problem.

**Comment by vladinator1000** [comment] 2022-07-11 02:56
This error happens only in production in a Cloudflare worker for me, even when I explicitly set the URL like this.
```ts
      new PrismaClient({
        datasources: {
          db: {
            url: config.databaseUrl
          }
        }
      })
```

 I triple-checked the database URL in production, it's present and correct. With this shape
 `prisma://aws-eu-central-1.prisma-data.com/?api_key=keyHere`

**Comment by aqrln** [comment] 2022-07-21 11:57
@vladinator1000 overriding the datasource URL in `PrismaClient` constructor arguments is currently not working with the Data Proxy client, the fix for that is not merged yet, but it will be released in Prisma 4.2.0.

**Comment by aqrln** [comment] 2022-07-25 11:26
I've investigated the issue last week, but I didn't write an update here, sorry for that!

Regarding the original issue, the problem happens not just with SvelteKit specifically, but with the new Module Worker format of Cloudflare Workers in general. Prisma assumes the Service Worker format, which used to have global bindings to the environment variables, secrets and KV namespaces, but it doesn’t work like that in the module workers that receive `env` and `ctx` as parameters of the request handler function.

One part of the issue is that the fallback paths where we try to retrieve the value of an environment variable in different ways should be more resilient and shouldn’t explode when assumptions fail.

Another part of the issue is supporting loading the `DATABASE_URL` in Module Workers. It will not be possible to make just `const prisma = new PrismaClient()` work because no equivalent of environment variables exists in the global scope, something will have to be passed to the constructor.

I can see two ways to approach this.

1. Without adding new APIs, it should be possible to manually override the datasource URL with a value from `env` which Prisma doesn't have access to by itself:

   ```ts
   const prisma = new PrismaClient({
     datasources: {
       db: {
         url: env.DATABASE_URL
       }
     }
   })
   ```

   (While this doesn't currently work in Prisma 4.1.0, the fix for this will be released in 4.2.0, we already fixed it in the context of another issue).

   We may document this as a requirement for the Module Workers, at least as a temporary solution.

2. We can add an API to make it a little bit less verbose and get the closest thing possible to how it works in other environments:

   ```ts
   const prisma = new PrismaClient({ env })
   ```

Finally, we should think about how we can help debug the `DATABASE_URL` not being picked up, regardless of whether it happens because of us not picking it up properly or the configuration issue in the project.

**Comment by drzamich** [comment] 2022-07-28 19:45
Before the fix is officially released - is there some workaround maybe?

**Comment by jjjrmy** [comment] 2022-08-02 18:36
I don't understand how this issue moved from `process not defined` to something else.

I'm running into the `process not defined` error when deploying with Wrangler@2

**Comment by alexanderzinolidis** [comment] 2022-08-02 20:15
Yeah, how are you guys getting around the `process not defined` error? This thread is incredibly confusing :-(

**Comment by vladinator1000** [comment] 2022-08-02 20:16
> I don't understand how this issue moved from `process not defined` to something else.
> 
> I'm running into the `process not defined` error when deploying with Wrangler@2

Sorry for hijacking the thread @jjjrmy, @zionili For the process thing, would a polyfill work for you?

I have this setup
```ts
// polyfills.ts
// Prisma uses the process global so we need to enable it https://github.com/evanw/esbuild/issues/1374#issuecomment-861801905
export var process = {
  env: new Proxy(
    {},
    {
      get: () => '',
    },
  ),
}
```

Then I inject it in my ESBuild config:
```ts
const path = require('path')
const { build, analyzeMetafile } = require('esbuild')
const alias = require('esbuild-plugin-alias')

async function buildWorker() {
  try {
    const mode = globalThis.ENVIRONMENT || 'development'

    const result = await build({
      bundle: true,
      minify: mode === 'production',
      sourcemap: true,
      metafile: true,
      treeShaking: true,
      format: 'esm',
      target: 'esnext',
      entryPoints: [path.join(__dirname, '../server/worker.ts')],
      outdir: path.join(__dirname, '../dist'),
      inject: [path.join(__dirname, 'polyfills.js')], // <--- inject here
      plugins: [
        alias({
          '@prisma/client': require.resolve('@prisma/client'),
        }),
      ],
    })
  } catch (err) {
    console.error(err)
    process.exitCode = 1
  }
}

buildWorker()
```

**Comment by jjjrmy** [comment] 2022-08-02 20:22
@vladinator1000 I'm not using any build tools? Is this something I need to use now?

**Comment by vladinator1000** [comment] 2022-08-02 20:23
> @vladinator1000 I'm not using any build tools? Is this something I need to use now?

I used this as a workaround because Prisma was relying on `process`

**Comment by jjjrmy** [comment] 2022-08-02 20:25
@vladinator1000 what does your `wrangler.toml` file look like then?

**Comment by drewdecarme** [comment] 2022-08-02 20:27
If you're using Wrangler@2 and you're using a `.toml` file. you can add this property to get around it. Wrangler spits a nasty warning out at you, but to this point I haven't had an issue in production.

```toml
# Add polyfills for node builtin modules and globals
node_compat = true
```

Here's the docs for it: https://developers.cloudflare.com/workers/wrangler/configuration/. Just scroll down until you see `node_compat`

Just waiting until Prisma fixes this issue.

**Comment by jjjrmy** [comment] 2022-08-02 20:39
@drewdecarme Thanks! Confirmed it works!

**Comment by jjjrmy** [comment] 2022-08-02 22:35
Not sure if this is the same issue you all are having with the `'Uncaught Error: InvalidDatasourceError: Could not parse URL of the datasource'`. It only seems to happen when using module exports. Is there a solution for this yet?

**Not Working:**
```js
import { PrismaClient } from '@prisma/client';
const prisma = new PrismaClient();

export default {
    async fetch(request: Request): Promise<Response> {
      return new Response('hello');
    },
};
```

**Working:**
```js
import { PrismaClient } from '@prisma/client';
const prisma = new PrismaClient();

addEventListener('fetch', (event: FetchEvent, env: any) => {
   event.respondWith(handleRequest(event))
});
```

**Comment by aqrln** [comment] 2022-08-03 17:34
Reopening since it depends on one more PR being merged (which is coming soon too).

**Comment by aqrln** [comment] 2022-08-03 17:57
This issue is now fixed and the fix will be released in Prisma 4.2.0. Prisma won't crash trying to access `process.env` when using the new Module Workers format of Cloudflare Workers (including the SvelteKit use case). You shouldn't need the workaround with `node_compat` shared earlier in this thread anymore.

Please note that with Module Workers there are no global bindings for secrets and environment variables that Prisma could use (see [this comment](https://github.com/prisma/prisma/issues/13771#issuecomment-1193925560) for more details). Instead, the `env` object is passed as a parameter to the `fetch` handler:

```ts
interface Env {
  DATABASE_URL: string | undefined
}

export default {
  async fetch(request: Request, env: Env /* <-- here it is! */, ctx: ExecutionContext): Promise<Response> {
    // ...
  }
}
```

See Cloudlfare docs for more details: https://developers.cloudflare.com/workers/learning/migrating-to-module-workers/

The implications are:

1. Prisma Client must be created inside the handler and not on the module level. This is a Cloudlfare limitation which we cannot work around. You can cache the created Prisma Client instance using a module-level variable though, and only create it inside the handler once if it's null.
2. The datasource URL has to be passed like this:

    ```ts
    const prisma = new PrismaClient({
      datasources: {
        db: {
          url: env.DATABASE_URL
        }
      }
    })
    ```

    We may come up with an API to make it less verbose in the future, but for now overriding the datasource URL with the value from the `env` parameter of the `fetch` handler is the official guideline when using Prisma with Module Workers. We will work on the guide and add it to the documentation.

Finally, we added an error to assist you debugging a missing environment variable (e.g., if you forgot to add a `secret` using `wrangler`). Instead of not very helpful `InvalidDatasourceError: Could not parse URL of the datasource` you will get more explicit `InvalidDatasourceError: Datasource "db" references an environment variable "DATABASE_URL" that is not set`.

**Closed** 2022-08-03 17:57 UTC
Labels: bug/2-confirmed, kind/bug, kind/regression, team/client, topic: cloudflare workers, topic: data proxy

**Comment by ciocan** [comment] 2022-09-06 12:23
Still have the same issue when running on Cloudflare Functions:

> [pages:err] ReferenceError: DATABASE_URL is not defined.


```Typescript
import { PrismaClient } from "@prisma/client/edge";

export async function onRequestGet({ env }) {
  console.log(env.DATABASE_URL);
  const prisma = new PrismaClient({
    datasources: {
      db: {
        url: env.DATABASE_URL,
      },
    },
  });

  return new Response(`ok`);
}
```

Running with:
    "prisma": "^4.3.1",
    "@prisma/client": "^4.3.1",

Running script:
    "dev": "wrangler pages dev ./dist",


The DATABASE_URL is added to wrangler secrets and set in .env / .dev.vars

Does anyone make it work with Cloudflare Functions?

**Comment by OlegSuncrown** [comment] 2022-09-11 07:51
@ciocan Maybe try in `schema.prisma` change `url` to empty string, like this:
```
datasource db {
  provider = "mongodb"
  url      = env("")
}
```

**Comment by yamiteru** [comment] 2022-09-19 15:14
Idk who tested this but it still doesn't work even in the beta versions.

**Comment by OlegSuncrown** [comment] 2022-09-19 15:47
@yamiteru worked for me, check this video
https://youtu.be/4nacpK9odjs

**Comment by yamiteru** [comment] 2022-09-19 15:56
@OlegSuncrown Well you use it with Angular. I need it to run locally without connecting to Cloudflare and I need to have CF Workers exposed as a separate app. I've already spent 6 hours trying to figure it out but with no luck.

**Comment by OlegSuncrown** [comment] 2022-09-19 16:05
@yamiteru Angular, React or simply webpack like [here](https://www.prisma.io/docs/guides/deployment/deployment-guides/deploying-to-cloudflare-workers), should work.

**Comment by janpio** [comment] 2022-09-19 16:14
If you can not get it to work, please open an issue @yamiteru and include all the information the issue template asks for. We are more than happy to take a look. We can always miss individual combinations.

**Comment by matbrgz** [comment] 2024-01-03 01:19
```
[wrangler:inf] Ready on http://localhost:8788
✘ [ERROR] Error: PrismaClient is unable to run in Vercel Edge Functions. As an alternative, try Accelerate: https://pris.ly/d/accelerate.

  If this is unexpected, please open an issue: https://github.com/prisma/prisma/issues
      at Object.get
  (file:///home/cooper/dev/meta-uclock/.vercel/output/static/_worker.js/__next-on-pages-dist__/functions/api/v1/[collection]/[slug].func.js:13:1359)
      at w
  (file:///home/cooper/dev/meta-uclock/.vercel/output/static/_worker.js/__next-on-pages-dist__/functions/api/v1/[collection]/[slug].func.js:1:5096)
      at W
  (file:///home/cooper/dev/meta-uclock/.vercel/output/static/_worker.js/__next-on-pages-dist__/functions/api/v1/[collection]/[slug].func.js:1:5185)
      at null.<anonymous>
  (file:///home/cooper/dev/meta-uclock/.vercel/output/static/_worker.js/__next-on-pages-dist__/webpack/2f3c2e13c8d7574161eb030c293751df.js:10:58276)
      at null.<anonymous>
  (file:///home/cooper/dev/meta-uclock/.vercel/output/static/_worker.js/__next-on-pages-dist__/webpack/2f3c2e13c8d7574161eb030c293751df.js:10:36706)
      at r.with
  (file:///home/cooper/dev/meta-uclock/.vercel/output/static/_worker.js/__next-on-pages-dist__/webpack/2f3c2e13c8d7574161eb030c293751df.js:10:121097)
      at s.with
  (file:///home/cooper/dev/meta-uclock/.vercel/output/static/_worker.js/__next-on-pages-dist__/webpack/2f3c2e13c8d7574161eb030c293751df.js:10:115296)
      at s.startActiveSpan
  (file:///home/cooper/dev/meta-uclock/.vercel/output/static/_worker.js/__next-on-pages-dist__/webpack/2f3c2e13c8d7574161eb030c293751df.js:10:130329)
      at r.startActiveSpan
  (file:///home/cooper/dev/meta-uclock/.vercel/output/static/_worker.js/__next-on-pages-dist__/webpack/2f3c2e13c8d7574161eb030c293751df.js:10:130863)
      at null.<anonymous>
  (file:///home/cooper/dev/meta-uclock/.vercel/output/static/_worker.js/__next-on-pages-dist__/webpack/2f3c2e13c8d7574161eb030c293751df.js:10:36555)


[wrangler:inf] GET /api/v1/uclock/1 500 Internal Server Error (36ms)

```

**Comment by matbrgz** [comment] 2024-01-03 03:47
CloudFlare Pages

My call:
```
import { PrismaClient } from "@prisma/client/edge";
import { withAccelerate } from "@prisma/extension-accelerate";

export const runtime = "edge";

const prisma = new PrismaClient().$extends(withAccelerate());

```

prisma.schema
```
generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "sqlite"
  url      = env("DATABASE_URL")
}

// my schema code ...
```

When I run: `npx prisma generate --data-proxy && yarn build && npx wrangler pages dev .vercel/output/static --compatibility-flag=nodejs_compat --local`
```
[wrangler:inf] Ready on http://localhost:8788
✘ [ERROR] Error: PrismaClient is unable to run in Vercel Edge Functions. As an alternative, try Accelerate: https://pris.ly/d/accelerate.

  If this is unexpected, please open an issue: https://github.com/prisma/prisma/issues
      at Object.get
  (file:///home/cooper/dev/meta/.vercel/output/static/_worker.js/__next-on-pages-dist__/functions/api/v1/[collection]/[slug].func.js:13:1359)
      at w
  (file:///home/cooper/dev/meta/.vercel/output/static/_worker.js/__next-on-pages-dist__/functions/api/v1/[collection]/[slug].func.js:1:5096)
      at W
  (file:///home/cooper/dev/meta/.vercel/output/static/_worker.js/__next-on-pages-dist__/functions/api/v1/[collection]/[slug].func.js:1:5185)
      at null.<anonymous>
  (file:///home/cooper/dev/meta/.vercel/output/static/_worker.js/__next-on-pages-dist__/webpack/2f3c2e13c8d7574161eb030c293751df.js:10:58276)
      at null.<anonymous>
  (file:///home/cooper/dev/meta/.vercel/output/static/_worker.js/__next-on-pages-dist__/webpack/2f3c2e13c8d7574161eb030c293751df.js:10:36706)
      at r.with
  (file:///home/cooper/dev/meta/.vercel/output/static/_worker.js/__next-on-pages-dist__/webpack/2f3c2e13c8d7574161eb030c293751df.js:10:121097)
      at s.with
  (file:///home/cooper/dev/meta/.vercel/output/static/_worker.js/__next-on-pages-dist__/webpack/2f3c2e13c8d7574161eb030c293751df.js:10:115296)
      at s.startActiveSpan
  (file:///home/cooper/dev/meta/.vercel/output/static/_worker.js/__next-on-pages-dist__/webpack/2f3c2e13c8d7574161eb030c293751df.js:10:130329)
      at r.startActiveSpan
  (file:///home/cooper/dev/meta/.vercel/output/static/_worker.js/__next-on-pages-dist__/webpack/2f3c2e13c8d7574161eb030c293751df.js:10:130863)
      at null.<anonymous>
  (file:///home/cooper/dev/meta/.vercel/output/static/_worker.js/__next-on-pages-dist__/webpack/2f3c2e13c8d7574161eb030c293751df.js:10:36555)


[wrangler:inf] GET /api/v1/aaa/1 500 Internal Server Error (36ms)

```

**Comment by nurul3101** [comment] 2024-01-18 11:21
@matbrgz In case you are still observing this issue, I would recommend sending an email to support@prisma.io so that we can further investigate. It looks like you are using the deprecated `--data-proxy` flag while running the command: `npx prisma generate --data-proxy`. I would suggest trying the recommended flag `--no-engine` instead.
