### ISSUE TITLE
MSSql or SQL server with instance connection problem

### ISSUE THREAD

**Issue by nizar-zouaoui** [prisma/prisma#6845] opened 2021-04-28 20:00 UTC
## Bug description
When I try to connect to a remote microsoft server database that requires an instance name it fails to connect

## How to reproduce
Just try the following connexion string:
`sqlserver://HOST:PORT;instanceName=instanceNme;database=database;user=user;password=password;`

## Prisma information
latest version

## Environment & setup

- OS:  Windows
- Database: MSSQL
- Node.js version: v14.16.1
- Prisma version: 2.21.2

```

```

**Comment by pimeys** [comment] 2021-04-29 10:16
Hey @nizar-zouaoui,

So, how we implemented the connection string is from the Microsoft documentation:

https://docs.microsoft.com/en-us/sql/connect/jdbc/building-the-connection-url?view=sql-server-ver15

Minus the `jdbc:` prefix, you should be fine following the instructions in the link, meaning your connection string would then be like:

```
 sqlserver://HOST:PORT\instanceNme;database=database;user=user;password=password;
````

**Comment by nader2560** [comment] 2021-04-29 16:31
Hello @pimeys,

Thanks for your fast response, I have though that it should've been written that way and I have in fact tried to use the connection string in that fashion although, it responded with the following error:

![image](https://user-images.githubusercontent.com/22282341/116585654-858b4580-a910-11eb-8f96-e09515b66e9e.png)

and even in the IDE (VSCode) it was underlined in red saying 

`Error validating: This line is not a valid definition within a datasource.` 

Thanks again for your response.

PS: I am the same person that posted this issue it's just that I posted it using a friend's computer.

**Comment by pimeys** [comment] 2021-04-29 16:36
Did you try double-backslash? Might be some of the javascript libraries take a single backslash as an escape character...

```
host\\INSTANCE:port;...
```

**Comment by nader2560** [comment] 2021-04-29 17:11
@pimeys Again thank you for being fast on the trigger, You are absolutely right the double backslash solved the issue, although another one appeared :
`Error: Error in connector: Error querying the database: Error querying the database: Error querying the database: Conversion error: SQL browser timeout during resolving instance instanceName`

Needless to say that I am using pretty much the same connection string that I am currently using in production using sequelize as an ORM, of course on sequelize's end the data is destructured  like so :
```
const sequelize = new Sequelize(process.env.DATABASE_NAME, process.env.DATABASE_USER, process.env.DATABASE_PASSWORD, {
  host: process.env.DATABASE_HOST,
  dialect: 'mssql',
  dialectOptions: {
    options: { instanceName: process.env.INSTANCE_NAME },
  },
  trustServerCertificate: true,
});
```
and it works perfectly fine here

**Comment by pimeys** [comment] 2021-04-29 17:14
You are running all of this on a Windows machine?

**Comment by nader2560** [comment] 2021-04-29 17:16
Yes @pimeys  I am doing this on Windows

**Comment by pimeys** [comment] 2021-04-29 17:16
What I'm now thinking is do you have the correct port set? Usually the SQL Browser listens in a different port than the actual server.

**Comment by nader2560** [comment] 2021-04-29 17:18
Yes in fact as I told you I am using the same parameters that I have used for sequelize which perfectly works to this moment, and as you can see I did not set a port in sequelize making it default back to 1433

**Comment by pimeys** [comment] 2021-04-29 17:25
Maybe @pantharshit00 a reproduction before we step forward? I think the error message at least sucks here. And the best case is that we have something we don't document correctly.

If this turns out a bug, I'm extending our SQL Server CI.

**Comment by Jolg42** [comment] 2021-04-30 07:38
> Did you try double-backslash? Might be some of the javascript libraries take a single backslash as an escape character...
> 
> ```
> host\\INSTANCE:port;...
> ```

Note: @pimeys The screenshot shows an error from `Get config` in engines here, no JS involved

**Comment by pimeys** [comment] 2021-04-30 07:49
> > Did you try double-backslash? Might be some of the javascript libraries take a single backslash as an escape character...
> > ```
> > host\\INSTANCE:port;...
> > ```
> 
> Note: @pimeys The screenshot shows an error from `Get config` in engines here, no JS involved

Well, "some library somewhere" which means whatever reads a `\` as an escape character. But does this change the idea of my answer?

**Comment by nader2560** [comment] 2021-04-30 08:04
> > > Did you try double-backslash? Might be some of the javascript libraries take a single backslash as an escape character...
> > > ```
> > > host\\INSTANCE:port;...
> > > ```
> > 
> > 
> > Note: @pimeys The screenshot shows an error from `Get config` in engines here, no JS involved
> 
> Well, "some library somewhere" which means whatever reads a `\` as an escape character. But does this change the idea of my answer?

@pimeys Your answer for that part of the problem was right on point! It worked like a charm and we got past that part of the issue, now as you said in your last comment I am also thinking that the problem is with the engine

**Comment by pimeys** [comment] 2021-04-30 08:08
It probably is, and when @pantharshit00 has time, he'll get us a reproduction to work for. Then we'll candidate the issue and somebody fixes it. First it's important to get some info is it something to do with the server setup or anything. As I said we do run [SQL Browser on our CI](https://github.com/prisma/tiberius/runs/2296265742?check_suite_focus=true#step:11:337), otherwise I wouldn't ask for confirmation first.

**Comment by nader2560** [comment] 2021-04-30 08:32
Great do you need any more information from my end?

**Comment by pimeys** [comment] 2021-04-30 08:34
Actually, I just have some slack today so I booted to Windows to see what's up. If I can't see anything in a few hours, I'll put the issue to the normal rotation.

**Comment by nader2560** [comment] 2021-04-30 08:40
I am open to organize a call if you wish to show you what's going on from my end if it could help https://meetings.hubspot.com/nader-zouaoui here's a link for us to schedule a meeting

**Comment by pantharshit00** [comment] 2021-04-30 10:10
@nader2560 Can you please tell us where this database is hosted?

**Comment by pimeys** [comment] 2021-04-30 11:20
So I did some tests today.

- Windows 10 Enterprise Edition
- Installed SQL Server 2019 Developer Edition
- Enabled TCP and SQL Browser
- Default instance name: `MSSQLSERVER`

My data model:

```prisma
datasource chinook {
  provider = "sqlserver"
  url      = env("DATABASE_URL")
}

generator client {
  provider = "prisma-client-js"
  previewFeatures = ["microsoftSqlServer"]
}

model Album {
  id       Int     @id @default(autoincrement())
  Title    String  @default("TestDefaultTitle")
  ArtistId Int
}
```

Testing from lowest level up:

- Tiberius, works fine with:

```rust
let jdbc = "jdbc:sqlserver://localhost\\MSSQLSERVER;user=SA;password=Prisma123Prisma123;TrustServerCertificate=true;database=master";
let config = Config::from_jdbc_string(jdbc)?;

let tcp = TcpStream::connect_named(&config).await?;
tcp.set_nodelay(true)?;

let mut client = Client::connect(config, tcp.compat_write()).await?;

let stream = client.query("SELECT @P1", &[&1i32]).await?;
let row = stream.into_row().await?.unwrap();
```

- Then step up to Quaint, this also works:

```rust
#[tokio::main]
async fn main() -> Result<(), Box<dyn std::error::Error + Send + Sync + 'static>> {
    let s = "jdbc:sqlserver://localhost\\MSSQLSERVER:1434;user=SA;password=Prisma123Prisma123;TrustServerCertificate=true;database=master";
    let pool = Quaint::builder(s)?.build();
    let conn = pool.check_out().await?;
    let res = conn.query_raw("SELECT 1", &[]).await?;

    dbg!(res);

    Ok(())
}
```

- Climbing up, to the Query Engine (which starts and works with the datamodel above)
- Creating a test app with Prisma 2.21.1, here I found the first issues. Still investigating and keeping you up to date if I find anything.

**Comment by pimeys** [comment] 2021-04-30 11:28
Also, I couldn't do `npx prisma migrate dev` with a `.env` using a datamodel with backslashes, but they work great when using the Query Engine directly.

**Comment by nader2560** [comment] 2021-04-30 12:04
@pimeys I'm happy that you have located the problem, at least as they say describing the problem is halfway to the solution. Great Job! @pimeys

**Comment by pimeys** [comment] 2021-04-30 12:10
Btw, a quick question. Did you use port `1433` or `1434` when connecting? The SQL Browser typically listens `1434`.

**Comment by nader2560** [comment] 2021-04-30 12:22
I used 1433

**Comment by nader2560** [comment] 2021-04-30 12:23
and the second I tried 1434 it worked like a charm 🥇

**Comment by pimeys** [comment] 2021-04-30 12:33
So, problem solved? What I see from our tracing logs when using port 1434:

```
[2021-04-30T12:09:51Z TRACE tiberius::sql_browser::tokio] Connecting to instance `MSSQLSERVER` using SQL Browser
[2021-04-30T12:09:51Z TRACE mio::poll] registering event source with poller: token=Token(0), interests=READABLE | WRITABLE
[2021-04-30T12:09:51Z TRACE tiberius::sql_browser::tokio] Found port `1433` from SQL Browser
```

And it gives me back port 1433, which is the TCP port of the SQL Server.

Sorry for slow debug, I'm mostly comfortable on the Linux side, so these Windows issues take their time :)

**Comment by nader2560** [comment] 2021-04-30 12:34
No man Thank you for solving my issue So I think we can go ahead and close this issue, and again thanks a lot for your help @pimeys !!!

**Comment by pimeys** [comment] 2021-04-30 12:34
Great, have a nice weekend!

**Closed by pimeys** 2021-04-30 12:34 UTC
Labels: bug/0-needs-info, kind/bug, topic: sql server
