### ISSUE TITLE
`prisma:engine` spans is missing on NestJS + Apollo

### ISSUE THREAD

**Issue by ishii1648** [prisma/prisma#19338] opened 2023-05-18 06:10 UTC
I am currently implementing `PrismaInstrumentation` with NestJS+Apollo(GraphQL). 
I want to retrieve spans about prisma, but `prisma:engine` is missing(retrieve only `prisma:client`).

Could anyone tell me how to retrieve `prisma:engine`?

tracer.ts
```typescript
import { SemanticResourceAttributes } from '@opentelemetry/semantic-conventions';
import { registerInstrumentations } from '@opentelemetry/instrumentation';
import {
  SimpleSpanProcessor,
} from '@opentelemetry/sdk-trace-base';
import { NodeTracerProvider } from '@opentelemetry/sdk-trace-node';
import { OTLPTraceExporter } from '@opentelemetry/exporter-trace-otlp-http';
import { PrismaInstrumentation } from '@prisma/instrumentation';
import { FastifyInstrumentation } from '@opentelemetry/instrumentation-fastify';
import { HttpInstrumentation } from '@opentelemetry/instrumentation-http';
import { GraphQLInstrumentation } from '@opentelemetry/instrumentation-graphql';
import { Resource } from '@opentelemetry/resources';

(() => {
  // Configure the trace provider
  const provider = new NodeTracerProvider({
    resource: new Resource({
      [SemanticResourceAttributes.SERVICE_NAME]: 'allabout-aggregation-api',
    }),
  });
  provider.register();
  provider.addSpanProcessor(new SimpleSpanProcessor(new OTLPTraceExporter()));

  // Register your auto-instrumentors
  registerInstrumentations({
    tracerProvider: provider,
    instrumentations: [
      new HttpInstrumentation(),
      new FastifyInstrumentation(),
      new GraphQLInstrumentation(),
      new PrismaInstrumentation(),
    ],
  });
})();
```

main.ts
```typescript
import './tracer';
import { NestFactory } from '@nestjs/core';
import {
  FastifyAdapter,
  NestFastifyApplication,
} from '@nestjs/platform-fastify';
import { AppModule } from './app.module';

async function bootstrap() {
  const app = await NestFactory.create<NestFastifyApplication>(
    AppModule,
    new FastifyAdapter(),
    {
      logger: ['error', 'warn'],
    },
  );
}
bootstrap();
```

The following image represents the content displayed in Jaeger. While `prisma:client` is visible, `prisma:engine` is not being displayed.

![スクリーンショット 2023-05-18 14 55 46](https://github.com/prisma/prisma/assets/7684738/4585d566-c426-4fcc-9b0d-7d57cf9d45e8)

### Prisma Version

```
4.8.0
```

**Comment by aqrln** [comment] 2023-05-19 12:24
Could you please provide more information about what version of Prisma are you using, and whether you are using Data Proxy or the local query engine? Could you please also post contents of the `generator` block from your schema file? Thank you!

**Comment by ishii1648** [comment] 2023-05-22 02:34
Thank you for your you reply.

I use `Prisma: 4.8.0`, and local query engine. I have defined the `generator` block as follows.

```prisma
generator client {
  provider        = "prisma-client-js"
  // 2022年2月現在preview機能だが、findUniqueをdeletedAtで絞るため仕方なく使っている
  previewFeatures = ["extendedWhereUnique", "tracing"]
}
```

**Comment by janpio** [comment] 2023-06-05 22:39
Can you try upgrading to a more recent version to see if that fixes the missing spans?

**Comment by morlz** [comment] 2023-06-07 08:35
Same behavior but only on OSX m1

**Comment by janpio** [comment] 2023-06-07 10:27
Is that also true for you @ishii1648 or are you on another OS and platform?

**Comment by georgewitteman** [comment] 2023-07-25 18:08
I'm also seeing only `prisma:client:*` traces but nothing for `prisma:engine:*`. I'm testing with prisma v5.0.0 and Datadog using a setup like this: https://github.com/DataDog/dd-trace-js/issues/1244#issuecomment-1648606069.

**Comment by larskarbo** [comment] 2023-08-22 06:13
I have also been having this issue. Turns out that defining multiple `new PrismaClient` instances messes things up a bit. My gut feel is that this error can be related. Tracked here: https://github.com/prisma/prisma/issues/20779

**Comment by aqrln** [comment] 2023-08-24 19:00
Given https://github.com/prisma/prisma/issues/20779, I assumed that maybe hot reloading in NestJS triggers this issue, but I still couldn't reproduce this after a few tries:

<img width="1294" alt="image" src="https://github.com/prisma/prisma/assets/4923335/02415ea9-71eb-46a5-a489-4421dc069ed5">

Compared to the original report, my reproduction didn't include Apollo in the stack, so maybe that's relevant.

@ishii1648 could you please share a reproduction we could run?

**Comment by millsp** [comment] 2023-11-07 17:01
@ishii1648 @larskarbo @morlz could you please help us with a reproduction?

**Comment by gboudreau** [comment] 2024-01-13 16:39
I am also facing this issue with NestJS (without Apollo) (details [here](https://github.com/prisma/prisma/discussions/22642)).
Since the issue seems related to #20779, I tried the workaround mentioned there: adding `engineType = "binary"` in my generator, and that fixed the issue.

Of note: I implemented the access to the PrismaClient [as recommended by NestJS](https://docs.nestjs.com/recipes/prisma), using a service:

```ts
import { Injectable, OnModuleInit } from '@nestjs/common';
import { PrismaClient } from '@prisma/client';

@Injectable()
export class PrismaService extends PrismaClient implements OnModuleInit {
  async onModuleInit() {
    await this.$connect();
  }
}
```

And then I use this service in various other services/modules.
I traced that class and found that `onModuleInit()` is called multiple times when the NestJS app starts, so I guess that for each module or service where I use PrismaService, a new PrismaClient is created, which makes this issue a duplicate of #20779.
I'll try to see with NestJS if that (`onModuleInit()` being called multiple times) is expected. There might be a bug there too.

**Comment by jkomyno** [comment] 2024-02-12 10:28
As we've tried to reach @ishii1648 twice without success, we're now closing this issue.
For future readers, we recommend trying out [this answer](https://github.com/prisma/prisma/issues/19338#issuecomment-1890588223).

Please leave a comment below with a minimal reproduction repository if you see this issue, and we'll reopen it. Thanks!

**Closed by jkomyno** 2024-02-12 10:28 UTC
Labels: bug/0-unknown, kind/bug, tech/typescript, team/client, topic: tracing, topic: NestJS
