### ISSUE TITLE
Deploying to Heroku

### ISSUE THREAD

**Issue by sabovyan** [prisma/prisma#4730] opened 2020-12-18 09:58 UTC
https://www.prisma.io/docs/guides/deployment/deploying-to-heroku

npx prisma migrate dev --create-only --name "init" --preview-feature 

```
❯ npx prisma migrate dev --create-only --name "init" --preview-feature


Prisma schema loaded from prisma/schema.prisma
Datasource "db": PostgreSQL database "d6mmq5a0ijqmkd", schema "public" at "ec2-3-211-176-230.compute-1.amazonaws.com:5432"

**Error**: A migration failed when applied to the shadow database:


Database error: Error querying the database: db error: ERROR: permission denied to create database
   0: sql_migration_connector::flavour::postgres::sql_schema_from_migration_history
             at migration-engine/connectors/sql-migration-connector/src/flavour/postgres.rs:172
   1: sql_migration_connector::sql_database_migration_inferrer::calculate_drift
             at migration-engine/connectors/sql-migration-connector/src/sql_database_migration_inferrer.rs:59
   2: migration_core::api::DiagnoseMigrationHistory
             at migration-engine/core/src/api.rs:148`

**Comment by pantharshit00** [comment] 2020-12-21 14:03
Hi,

Thanks for reporting this! It has already been reported before, so I am going to close this as a duplicate of https://github.com/prisma/prisma/issues/4571 and https://github.com/prisma/prisma/issues/4751

**Closed by pantharshit00** 2020-12-21 14:03 UTC
