### ISSUE TITLE
Filter include using query data

### ISSUE THREAD

**Issue by danshapir** [prisma/prisma#11483] opened 2022-01-29 17:09 UTC
How can you filter by part of the query in an include?

Like:
 SELECT * FROM A INNER JOIN B on B.aId = A.id AND B.amount < A.price

Or:
 SELECT * FROM A INNER JOIN B on a.aId = A.id WHERE B.amount < A.price

Meaning your query’s filter parameter is part of the query itself.

I couldn’t figure anyway to do it and it’s crazy… This is a super basic SQL capability.

**Comment by pantharshit00** [comment] 2022-02-04 15:35
Hello,

Yes indeed, this hasn't been worked on yet. I am going to close this as duplicate of https://github.com/prisma/prisma/issues/5048. You will need to use raw query here.

**Closed by pantharshit00** 2022-02-04 15:35 UTC
