### ISSUE TITLE
your logo

### ISSUE THREAD

**Issue by Henri-1** [prisma/prisma#12201] opened 2022-03-08 13:03 UTC
### Bug description

Your logo is a pyramid but your name is prisma

### How to reproduce

look at you logo 
then look at you name

### Prisma information

look at you logo 
then look at you name

### Environment & setup

Samsung s21 chrome browser

### Prisma Version

current build

**Comment by pantharshit00** [comment] 2022-03-09 08:54
Closing as duplicate of https://github.com/prisma/prisma/issues/10242

**Closed by pantharshit00** 2022-03-09 08:54 UTC
Labels: kind/bug
