### ISSUE TITLE
Vercel deployment files with version 2.20.1 because of the size of query-engine-rhel-openssl-1.0.x has increased

### ISSUE THREAD

**Issue by rubenkaiser** [prisma/prisma#6746] opened 2021-04-23 09:57 UTC
Deploying to vercel with prisma 2.20.1 may result in the following error:

```
Error: The Serverless Function "" is XX.Xmb which exceeds the maximum size limit of 50mb. Learn More: https://vercel.link/serverless-function-size
```

To solve it for now you can use prisma 2.19.0 in which the size of query-engine-rhel-openssl-1.0.x is about 25MB whereas the same engine has a size of about 45MB in version 2.20.1.

There is already an issue for this aimed at serverless framework. But others working with Vercel might overlook that one, therefore this separate issue.

**Comment by janpio** [comment] 2021-04-23 14:04
Thanks @rubenkaiser, that is indeed true that the binary size increased - but usually this does not pose an actual problem. There are usually solutions to decrease the archive size - but we are not doing a good job at documenting those. We need to get better here. I think your project might be a good example to go through these, as you are having a concrete problem, and figure out what we should put into our documentation (and if possible even into the code so it happens automatically).

Can you tell us a bit more about your project?
How are you packaging your application that the packaged size in total is >50MB?
What do your dependencies (and dev dependencies) look like?

**Comment by Jolg42** [comment] 2021-05-11 11:28
Could be related to https://github.com/prisma/prisma/issues/6932

**Comment by rubenkaiser** [comment] 2021-05-12 07:15
We are using nextjs, not nexus or nexus-plugin-prisma.

As for the "better output". We're not seeing this. I checked the thread and @styxlab is indeed getting more output from Vercel than me. No idea why he's getting more details.

I'm seeing:
```
2021-05-12T07:05:38.640Z  Traced Next.js server files in: 31.092s
2021-05-12T07:06:04.620Z  Created all serverless functions in: 25.979s
```

As to his output is more clarifying:
```
2021-05-11T13:36:45.278Z  Traced Next.js server files in: 2.640s
2021-05-11T13:37:29.021Z  Warning: Max serverless function size of 50 MB compressed or 250 MB uncompressed hit
2021-05-11T13:37:29.022Z  Serverless Function's page: api/core/v1/graphql.js
2021-05-11T13:37:29.026Z  Large Dependencies                  Uncompressed size  Compressed size
2021-05-11T13:37:29.027Z  node_modules/@prisma/engines                   113 MB          39.6 MB
2021-05-11T13:37:29.027Z  node_modules/.prisma/client                   45.4 MB          16.1 MB
2021-05-11T13:37:29.027Z  node_modules/prisma/build                      5.3 MB          1.09 MB
2021-05-11T13:37:29.027Z  node_modules/@prisma/client                   3.93 MB           823 kB
2021-05-11T13:37:29.027Z  node_modules/busboy/deps                       618 kB           196 kB
2021-05-11T13:37:29.027Z  node_modules/micro/node_modules                360 kB           190 kB
2021-05-11T13:37:29.027Z  node_modules/encoding/node_modules             328 kB           179 kB
2021-05-11T13:37:29.027Z  node_modules/lodash/lodash.js                  544 kB          96.4 kB
2021-05-11T13:37:29.027Z  
2021-05-11T13:37:29.027Z  All dependencies                               173 MB          59.1 MB
2021-05-11T13:37:29.028Z  Max serverless function size was exceeded for 1 function
2021-05-11T13:37:29.202Z  Created all serverless functions in: 43.924s
```

**Comment by janpio** [comment] 2021-05-12 07:20
In _theory_ that should mean that it could successfully be uploaded and deployed - but of course you also posted the error message above, so this is weird.

Try setting `NEXT_DEBUG_FUNCTION_SIZE=1` in your Vercel app. Brand new feature from Vercel to get the same output even on successful deploys - maybe that also unlocks the table for you.

**Comment by rubenkaiser** [comment] 2021-05-12 08:12
@janpio your suggestion for debugging allowed me to get all the output. I did not find that in the docs. I have contacted the Vercel team a couple of weeks ago about this issue and they only pointed to the function dashboard in Vercel on which you can see the total size (on a succesfull deployment). If they had only sent me NEXT_DEBUG_FUNCTION_SIZE...

I have a monorepo with several workspaces. One of the workspaces contains the Prisma stuff, which is used in the other workspaces. With the debugging enabled you can see that the root contains a node_modules/.prisma folder as well as the individual workspaces.

```
09:24:43.497 | node_modules/.prisma/client                   45.6 MB          16.1 MB
09:24:43.497 | admin/node_modules/.prisma                    45.2 MB          16.1 MB
```

Don't know why the workspace itself also contains node_modules when deploying. But adding a simple `rm -rf ./node_modules/.prisma` did the trick (Think I can also remove the whole folder).

```
10:01:47.951 | All dependencies                              57.7 MB          19.1 MB
```

**Comment by janpio** [comment] 2021-05-12 09:27
> If they had only sent me NEXT_DEBUG_FUNCTION_SIZE...

We paired with Vercel on that only yesterday night - it did not exist before :D Now that you confirm it works for actual users, we can document this in an upcoming "Prisma and Vercel" help thing I will be working on next week.


> One of the workspaces contains the Prisma stuff, which is used in the other workspaces. With the debugging enabled you can see that the root contains a node_modules/.prisma folder as well as the individual workspaces.
> Don't know why the workspace itself also contains node_modules when deploying. 

That is weird, but make sense. Can you maybe quickly create a simple reproduction repository with the minimal setup similar to your project, so we (and Vercel) can reproduce this? Monorepos do funny things sometimes, and as there are so many possible variations we also usually have trouble reproducing and fixing, so this would be a _huge_ help.

> But adding a simple `rm -rf ./node_modules/.prisma` did the trick (Think I can also remove the whole folder).

Just for others reading here, how and where did you add this?

**Comment by rubenkaiser** [comment] 2021-05-12 09:59
@janpio in that case I spoke to soon.. Still liking prisma and Vercel 😛 

In my solution I already had a simple .sh script in which I was adding logging to see what was happening (My version of NEXT_DEBUG_FUNCTION_SIZE).

I adjusted it and added a clean script to my package json (in the deploying app workspace)
```
"clean": "./prisma-clean.sh",
```

In the `prisma-clean.sh` file I only remove some stuff from the deployment that I don't need and that has significant file size.

```
echo Removing unnecessary prisma files

rm -rf ../node_modules/@prisma/engines
rm -rf ../node_modules/typescript

# remove the local prisma folder
rm -rf ./node_modules/.prisma
```

(be sure the chmod the file `chmod +x prisma-clean.sh`)

In the Vercel project settings we override the build command to first generate the prisma stuff in the prisma workspace, and then build the app, after which the cleanup in the app workspace is performed.

```
npm run generate && npm run build && npm run clean
```

To be clear the first `generate` command that builds our prisma in another workspace is performed by going up into the root folder (so we have to enable "Include source files outside of the Root Directory in the Build Step." and have the root directory setup to be the directory/workspace in which the app lives) 
```
"generate": "yarn --cwd ../ prisma:generate"
``` 

And in the root folder the package.json has the following script to generate prisma in its own workspace by specifying the schema.
```
"prisma:generate": "npx prisma generate --schema [prisma-workspace-name]/schema.prisma",
```

I've just verified the solution in another project of mine. Doing the exact same there also enables me to use the latest prisma version without the size errors. In this project (also workspaces) again two .prisma folders were generated. Removing the one in the deploying workspace makes the size go down enough to deploy.

```
11:55:18.249 | node_modules/.prisma/client              49.9 MB          16.2 MB
11:55:18.249 | [workspace_name]/node_modules/.prisma      45.2 MB          16.1 MB
```

I will try to find some time this week to create an example project.

**Comment by rubenkaiser** [comment] 2021-05-12 10:20
There is still something weird going on here. I have two projects that both have the same setup. The first project was updated with the remove scripts I mentioned and started deploying again. 

I wanted to update the second project but forgot the remove script and it instantly deployed without any issues. (also with `"prisma": "2.22.1",`)

Because of that I decided to checkout the first projects output again and it seems like the lambda limit does not resemble the logs.

Log output:
```
09:24:43.497 | Large Dependencies                  Uncompressed size  Compressed size
09:24:43.497 | node_modules/.prisma/client                   45.6 MB          16.1 MB
09:24:43.497 | [workspace_name]/node_modules/.prisma                    45.2 MB          16.1 MB
09:24:43.497 | node_modules/highlight.js/lib                 1.41 MB           458 kB
09:24:43.497 | node_modules/@prisma/client                   1.17 MB           243 kB
09:24:43.497 | node_modules/typeorm/driver                    1.6 MB           214 kB
09:24:43.497 | node_modules/encoding/node_modules             328 kB           179 kB
09:24:43.497 | All dependencies                              98.9 MB          34.1 MB
```

Error:
```
09:25:13.180 | Error: The Serverless Function "api/auth/[...nextauth]" is 68.01mb which exceeds the maximum size limit of 50mb. Learn More: https://vercel.link/serverless-function-size
```

How is the 68.01 MB calculated?

My second project, that deploys out of the box now, has a much larger size:
```
11:55:18.250 | All dependencies                                          140 MB          41.8 MB
```

**Comment by cyrus-za** [comment] 2021-05-13 21:16
I am also confused with that. I got 50.11mb (tiny bit over limit) but the lgos also show a much larget number for `All dependencies` and 45mb for prisma binary. 

Is there a way to delete part of the binary to get it smaller?

**Comment by cyrus-za** [comment] 2021-05-13 21:38
Seems like the 60.01mb (in the case for @rubenkaiser) is the compressed size's total

What ended up fixing it for me was enabling `napi`
![image](https://user-images.githubusercontent.com/1845861/118190380-53670100-b443-11eb-8911-c45c9bd52de4.png)

**Comment by janpio** [comment] 2021-05-18 11:46
@cyrus-za: Using the n-api preview feature is just a workaround and can lead to a lot of unrelated problems - so please make sure you are fine running preview code in your project and environment.

If you open a new issue about your specific project and problem, I am happy to debug it together with you to figure out why Vercel is including file and packages it should not really include. (Note: If you are using `nexus-plugin-prisma`, then this behavior will only be fixed with the 2.23.0 release which will happen later today. Upgrading your Prisma dependencies to that should make it work again automatically)

**Comment by janpio** [comment] 2022-02-11 18:20
Is this still a problem?

**Comment by Dilven** [comment] 2022-02-18 15:17
@janpio I have exactly the same problem when I'm trying to deploy my next.js application on Vercel. All of my functions exceed size. I have `@prisma/clinet` in dependencies and `prisma` in devDependencies and I use correct import in every places 
`import { TypeModel } from '@prisma/client'`

**Comment by Dilven** [comment] 2022-02-18 16:29
@janpio okay I will do it, thanks!

**Comment by Dilven** [comment] 2022-02-18 20:21
@janpio Of course it turned out to be my bad :D It was related to `binaryTargets`. We had a lot of binaryTargets because some of our developers work on M1 and our prisma config looks in this way

`binaryTargets = ["native", "debian-openssl-1.1.x", "linux-arm64-openssl-1.1.x"]`

Probably the best solution is to set it via the environment variable. Anyway, this was the reason for the package size.

**Comment by pantharshit00** [comment] 2022-03-02 11:21
I think we can close this due to inactivity from original author and further followups from others have been solved. Please comment if you still facing this or preferably open a new issue.

**Closed by pantharshit00** 2022-03-02 11:21 UTC
Labels: bug/1-unconfirmed, kind/bug, topic: deployment-platform, topic: serverless, team/client, topic: deployment/vercel, topic: monorepo
