### ISSUE TITLE
Error with Views on reset

### ISSUE THREAD

**Issue by serlf3** [prisma/prisma#17447] opened 2023-01-20 16:27 UTC
### Bug description

Hi!

I'm having an issue with the recently added 'views' feature.

The problem appear to happen when the DB is reset having your app already up. 

The following error is thrown:

```
PrismaClientUnknownRequestError: 
Invalid `prisma.myView.findMany()` invocation:


Error occurred during query execution:
ConnectorError(ConnectorError { user_facing_error: None, kind: QueryError(Error { kind: Db, cause: Some(DbError { severity: "ERROR", parsed_severity: Some(Error), code: SqlState(EXX000), message: "cache lookup failed for type 710388", detail: None, hint: None, position: None, where_: Some("unnamed portal parameter $2"), schema: None, table: None, column: None, datatype: None, constraint: None, file: Some("lsyscache.c"), line: Some(2904), routine: Some("getTypeBinaryInputInfo") }) }), transient: false })
    at RequestHandler.handleRequestError (/db-package-path/dist/runtime/index.js:31950:13)
    at RequestHandler.handleAndLogRequestError (/db-package-path/dist/runtime/index.js:31913:12)
    at RequestHandler.request (/db-package-path/dist/runtime/index.js:31908:12)
    at async PrismaClient._request (/db-package-path/dist/runtime/index.js:32994:16)
    at async getMyView (file:///app-path/services/myService.ts:32:22)
    at async Object.getMyViewController (file:///app-path/controller/myController.ts:41:18)
```

### Prisma information

```prismaview 
myView {
  id String
  name String
  last_time_connected DateTime
}
```
```ts
PrismaOrm.myView.findMany()
```

### Environment & setup

- OS: macOS
- Database: PostgreSQL
- Node.js version: 16.17

### Prisma Version

```
    "prisma": "^4.9.0",
    "@prisma/client": "^4.9.0"
```

**Comment by janpio** [comment] 2023-01-20 19:10
> The problem appear to happen when the DB is reset having your app already up.

What exactly do you mean by that @serlf3? Are you removing the existing view from the database?

(I assume the `view` key word is missing from the `Prisma information` schema section?)

**Comment by janpio** [comment] 2023-02-01 01:02
Ping @serlf3

**Comment by gibso** [comment] 2023-06-29 05:32
I think this is more a problem of postgres than of prisma. Postgres is using a buffer cache to cache data. This cache becomes obviously stale or invalid when you reset the database with prisma. Here are some more information to the topic:  https://stackoverflow.com/a/1223421/4077001

**Comment by g-borgulya** [comment] 2023-09-01 20:26
I had a similar issue with integration tests:
1. instantiating the prisma client
2. reseting prisma (cli)
3. reusing the prisma client

threw the same error.

Instead, using:
1. await client.$disconnect();
2. // reseting prisma (cli)
3. await client.$connect();

solved the problem.

**Comment by SevInf** [comment] 2024-09-05 09:31
Hey, the solution of this problem is to re-establish the connection after DB reset. Since it is not a problem caused by Prisma we are closing this issue. Thank you!

**Closed by SevInf** 2024-09-05 09:31 UTC
Labels: bug/1-unconfirmed, kind/bug, domain/schema, domain/client, topic: postgresql, topic: views
