### ISSUE TITLE
Know when the Client is using the data proxy

### ISSUE THREAD

**Issue by matthewmueller** [prisma/prisma#9958] opened 2021-10-26 17:46 UTC
## Problem

It’s hard to understand/confirm if an app is using the binary or the proxy version of Prisma Client. 

## Suggested solution

**At build time:**

```sh
$ PRISMA_CLIENT_ENGINE_TYPE=dataproxy npx prisma generate
✔ Generated Prisma Client (3.3.0 | dataproxy) to ./node_modules/@prisma/client in 2.00s 
```

**At runtime:**

It would be nice to add a bit of DEBUG logging at runtime as well to see whether or not you're running queries through the data proxy.

**Comment by janpio** [comment] 2021-11-22 17:42
Runtime part of this issue is probably not included in that PR.

**Comment by janpio** [comment] 2021-11-22 19:09
One option, would fit if this will also be fixed in this sprint (so the issue is still closed before and can find a place in the release notes). Alternatively open a new sub issue for just the runtime part and apply the same labels - that can then be planned and implemented independently from this, potentially in a future sprint.

**Closed** 2021-11-23 12:32 UTC
Labels: kind/improvement, topic: previewFeatures, team/client, topic: data proxy
