### ISSUE TITLE
performance improvement: sqlite create does insert then select instead of RETURNING clause

### ISSUE THREAD

**Issue by andykais** [prisma/prisma#8948] opened 2021-08-26 16:17 UTC
### Bug description

Outlined in this discussion https://github.com/prisma/prisma/discussions/8873, I discovered that a call to `.create` will perform an insert and then a select inside a transaction. This can likely be avoided by just performing a single INSERT and returning data with the RETURNING clause.

```
prisma:query BEGIN
prisma:query INSERT INTO `main`.`User` (`name`, `created_at`, `updated_at`) VALUES (?,?,?) RETURNING id
prisma:query SELECT `main`.`User`.`id`, `main`.`User`.`name`, `main`.User`.`created_at`, `main`.`User`.`updated_at` FROM `main`.`User` WHERE `main`.`User`.`id` = ? LIMIT ? OFFSET ?
prisma:query COMMIT
```

### How to reproduce

show debug logs and call create on any table.
```ts
const prisma = new PrismaClient({log:  ['query',]})
const user = await client.user.create({ data: { name: 'John Smith' }})
```

### Expected behavior

prisma just performs a single insert

```
prisma:query INSERT INTO `main`.`User` (`name`, `created_at`, `updated_at`) VALUES (?,?,?) RETURNING id, name, created_at
```

### Prisma information

```prisma
datasource db {
  provider = "sqlite"
  url      = env("DATABASE_URL")
}

generator client {
  provider = "prisma-client-js"
}

model Tag {
  id         Int      @id @default(autoincrement())
  name       String   @unique
  created_at DateTime @default(now())
  updated_at DateTime @updatedAt
}
```

### Environment & setup

- OS: Mac OS
- Database: SQLite
- Node.js version: v16.3.0

### Prisma Version

```
Environment variables loaded from .env
prisma               : 2.29.1
@prisma/client       : 2.29.1
Current platform     : darwin
Query Engine         : query-engine 1be4cd60b89afa04b192acb1ef47758a39810f3a (at node_modules/.pnpm/@prisma+engines@2.29.0-34.1be4cd60b89afa04b192acb1ef47758a39810f3a/node_modules/@prisma/engines/query-engine-darwin)
Migration Engine     : migration-engine-cli 1be4cd60b89afa04b192acb1ef47758a39810f3a (at node_modules/.pnpm/@prisma+engines@2.29.0-34.1be4cd60b89afa04b192acb1ef47758a39810f3a/node_modules/@prisma/engines/migration-engine-darwin)
Introspection Engine : introspection-core 1be4cd60b89afa04b192acb1ef47758a39810f3a (at node_modules/.pnpm/@prisma+engines@2.29.0-34.1be4cd60b89afa04b192acb1ef47758a39810f3a/node_modules/@prisma/engines/introspection-engine-darwin)
Format Binary        : prisma-fmt 1be4cd60b89afa04b192acb1ef47758a39810f3a (at node_modules/.pnpm/@prisma+engines@2.29.0-34.1be4cd60b89afa04b192acb1ef47758a39810f3a/node_modules/@prisma/engines/prisma-fmt-darwin)
Default Engines Hash : 1be4cd60b89afa04b192acb1ef47758a39810f3a
Studio               : 0.419.0
```

**Comment by pantharshit00** [comment] 2021-09-02 13:55
I think we can consider this as duplicate of https://github.com/prisma/prisma/issues/5043

We will pick this up when we will start optimizing queries per connector basis.

**Closed by pantharshit00** 2021-09-02 13:55 UTC
Labels: kind/bug
