### ISSUE TITLE
`TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received an instance of Object` when old `@prisma/client` in parent folder

### ISSUE THREAD

**Issue by janpio** [prisma/prisma#6372] opened 2021-04-01 19:05 UTC
1. new folder
2. `npm init -y`
3. `npm install prisma`
4. `npx prisma init`
5. adapt schema file:
```
datasource db {
  provider = "sqlite"
  url      = "file:./dev.db"
}

generator client {
  provider = "prisma-client-js"
}

model User {
  id        Int       @id @default(autoincrement())
  name      String
}
```
6. `npx prisma db push --preview-feature`
7. `db push` works, but then generation fails with:
```
C:\Users\Jan\Documents\throwaway\pathtypestring  (pathtypestring@1.0.0)
λ npx prisma db push --preview-feature
Environment variables loaded from .env
Prisma schema loaded from prisma\schema.prisma
Datasource "db": SQLite database "dev.db" at "file:./dev.db"

SQLite database dev.db created at file:./dev.db


Your database is now in sync with your schema. Done in 57ms

TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received an instance of Object
    at new NodeError (node:internal/errors:329:5)
    at validateString (node:internal/validators:129:11)
    at Object.join (node:path:397:7)
    at getDotPrismaDir (C:\Users\Jan\Documents\throwaway\node_modules\@prisma\client\generator-build\index.js:72820:33)
    at Object.generateClient (C:\Users\Jan\Documents\throwaway\node_modules\@prisma\client\generator-build\index.js:72842:49)
    at Object.onGenerate (C:\Users\Jan\Documents\throwaway\node_modules\@prisma\client\generator-build\index.js:78035:34)
    at LineStream.<anonymous> (C:\Users\Jan\Documents\throwaway\node_modules\@prisma\client\generator-build\index.js:2802:40)
    at LineStream.emit (node:events:369:20)
    at addChunk (node:internal/streams/readable:313:12)
    at readableAddChunk (node:internal/streams/readable:288:9)
```

---

```
C:\Users\Jan\Documents\throwaway\pathtypestring  (pathtypestring@1.0.0) 
λ cat package.json                                                      
{                                                                       
  "name": "pathtypestring",                                             
  "version": "1.0.0",                                                   
  "description": "",                                                    
  "main": "index.js",                                                   
  "scripts": {                                                          
    "test": "echo \"Error: no test specified\" && exit 1"               
  },                                                                    
  "keywords": [],                                                       
  "author": "",                                                         
  "license": "ISC",                                                     
  "dependencies": {                                                     
    "prisma": "^2.20.1"                                                 
  }                                                                     
}                                                                       
```

---

```
C:\Users\Jan\Documents\throwaway\pathtypestring  (pathtypestring@1.0.0)
λ npx prisma -v
Environment variables loaded from .env
prisma               : 2.20.1
@prisma/client       : 2.15.0-dev.73
Current platform     : windows
Query Engine         : query-engine 60ba6551f29b17d7d6ce479e5733c70d9c00860e (at node_modules\@prisma\engines\query-engine-windows.exe)
Migration Engine     : migration-engine-cli 60ba6551f29b17d7d6ce479e5733c70d9c00860e (at node_modules\@prisma\engines\migration-engine-windows.exe)
Introspection Engine : introspection-core 60ba6551f29b17d7d6ce479e5733c70d9c00860e (at node_modules\@prisma\engines\introspection-engine-windows.exe)
Format Binary        : prisma-fmt 60ba6551f29b17d7d6ce479e5733c70d9c00860e (at node_modules\@prisma\engines\prisma-fmt-windows.exe)
Default Engines Hash : 60ba6551f29b17d7d6ce479e5733c70d9c00860e
Studio               : 0.365.0
```

⚠️ Note how this lists `@prisma/client       : 2.15.0-dev.73`.
Turns out there was a `package.json` in a parent folder with this old @prisma/client version.

Expectation would be to at least get a warning about this incompatible version.

(I assume that using this dependency from the parent folder is "normal" in Node?)

**Comment by CITGuru** [comment] 2021-04-03 20:56
I am having this issue as well any update on this

**Comment by janpio** [comment] 2021-04-04 08:54
The solution is to update both CLI and Client to the same version.

**Comment by pantharshit00** [comment] 2021-04-16 11:07
Duplicate of https://github.com/prisma/prisma/issues/6535 although a different error. 

I can confirm though.

**Comment by janpio** [comment] 2021-04-16 12:44
Yup, this is indeed the same problem. Having it from a different package.json somehow triggers a different error message. No idea why and how.

**Comment by narenarjun** [comment] 2021-04-24 11:39
just got this same issue when ran `yarn prisma db push --preview-feature`, 

`db push` worked, but the `yarn prisma generate` is failing.

**Comment by janpio** [comment] 2021-04-24 11:40
Update your `@prisma/client` to the same version as your `prisma` CLI dependency @narenarjun.

**Comment by narenarjun** [comment] 2021-04-24 11:46
i have  `"@prisma/client": "^2.8.1"` and ` "prisma": "^2.21.2"`, in the respective versions, so do i bump up @prisma/client to 2.21.2 or bring prisma to 2.8.1 ??

**Comment by narenarjun** [comment] 2021-04-24 11:52
> 
> 
> i have `"@prisma/client": "^2.8.1"` and ` "prisma": "^2.21.2"`, in the respective versions, so do i bump up @prisma/client to 2.21.2 or bring prisma to 2.8.1 ??

updated  `@prisma/client` to `2.21.2` and the  command `yarn prisma generate` didn't throw any error 👍👍 thanks @janpio

**Comment by shafikhaan** [comment] 2021-04-24 17:53
@narenarjun i have `prisma/client` and `prisma` both set to `2.21.2`, i did installed yarn but still having the same issue :

```
✔ Generated Prisma Client (2.21.2) to ./node_modules/@prisma/client in 111ms

TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string or an instance of Buffer or URL. Received an instance of Object
```

**Comment by narenarjun** [comment] 2021-04-24 21:23
@shafikhaan the log say `Generated Prisma Client` , have you checked if the imports are working correctly or looked into the `./node_modules/@prisma/client` folder to see whether it was generated as the message shown ? 


The error thrown can be completely due to a new issue too, so without a full details of the code structure I have no way of giving further what to do.

**Comment by shafikhaan** [comment] 2021-04-24 21:46
@narenarjun yes, client was generated successfully, I can confirm that.

**Comment by janpio** [comment] 2021-04-24 22:29
I think that is a third party generator problem @shafikhaan - we will debug this in your own issue that you created: https://github.com/prisma/prisma/issues/6770

**Comment by charles161** [comment] 2021-05-10 11:39
I changed the versions and it worked:
`
"dependencies": {
    ...
    "@prisma/client": "2.22.1"
  },
"devDependencies": {
    ...
    "prisma": "2.22.1",
  }

`
Thanks @janpio for the suggestion

**Comment by dpetrick** [comment] 2021-05-19 14:54
Closing in favor of https://github.com/prisma/prisma/issues/6535

**Closed by dpetrick** 2021-05-19 14:54 UTC
Labels: bug/2-confirmed, kind/bug, process/candidate, team/client, topic: cli-generate, topic: db push

**Comment by felix28** [comment] 2024-08-08 05:37
> The solution is to update both CLI and Client to the same version.

Thank you. it works!

**Comment by priteshpoddar** [comment] 2024-08-17 10:40
For anyone looking now, I was using 
prisma       : 5.0.0
@prisma/client    : 5.18.0
node     : 20.12.1 

On downgrading node to 18.17.0, it started working.

**Comment by invisiblekid15** [comment] 2024-08-23 13:23
Issue with me was in dependencies carat symbol was added

"prisma": "^5.15.0",
"@prisma/client": "^5.15.0",

npm auto updated prisma to 5.18.0 and client was at 5.15.0 due to which this error was coming. Removing carat symbol solved the problem

**Comment by DipakKhade** [comment] 2024-11-09 14:43
@narenarjun Thank u sir , yarn prisma generate works for me!
