### ISSUE TITLE
`DEFAULT` value in update queries

### ISSUE THREAD

**Issue by wanjas** [prisma/prisma#8438] opened 2021-07-26 11:12 UTC
## Problem

It's probably a rare case but sometimes when updating it's preferred to leave DEFAULT value generation logic to the database instead of creating new value in the client code.  
What I want to run is basically `UPDATE "Table" set "fieldName" = DEFAULT WHERE ...`

## Suggested solution

```javascript
DEFAULT_VALUE = Symbol('DEFAULT');

prisma.table.update({
  data: {
    field: Prisma.DEFAULT_VALUE
  }
})
```

## Additional context

There is not much context. Now we can use the special value `NULL` but can't `DEFAULT`. 

One thing to mention is that MongoDb's implementation is probably going to be "special" or unsupported.

**Comment by pantharshit00** [comment] 2021-07-26 11:14
Hi,

Thanks for reporting this! It has already been reported before, so I am going to close this as a duplicate of https://github.com/prisma/prisma/issues/7603

**Closed by pantharshit00** 2021-07-26 11:14 UTC
