### ISSUE TITLE
UUID Cursor Pagination

### ISSUE THREAD

**Issue by TLadd** [prisma/prisma#2855] opened 2020-06-25 18:30 UTC
## Problem

If you have non-sequential UUID's as your primary key, the take/cursor prisma pagination API doesn't work. I believe it actually did with the old first/after/before/last API (could be wrong here but it seemed to prior to beta.7).

In such cases, you can paginate using a query similar to this:
```
SELECT * FROM events 
  WHERE (created,id) >= ($<after>,$<id>)
  ORDER BY created ASC ,id ASC LIMIT 10
```

## Suggested solution

A cursor combining the uuid id field and a created_at field works when passed in as the cursor to prisma.

## Alternatives

You can almost implement an equivalent query using just `where/order by` but [it is not currently possible to pass multiple fields to `orderBy`](https://github.com/prisma/prisma-client-js/issues/702).

**Comment by Sytten** [comment] 2020-06-26 05:18
Can you define what not working means? Does it work if you provide an explicit order by? It must be that it is missing one somewhere so the data is not always ordered the same between requests.

**Comment by TLadd** [comment] 2020-06-26 15:00
Apologies for the initial lack of detail. I initially thought this just wasn't supported at all because the docs explicitly state the cursor needs to be sequential. So this might be a bug vs a feature; not sure. Did some digging and it looks like this almost works but there are issues when `createdAt` (the field being ordered by) is not unique. So here's my dataset of 20 items:

```javascript
let first20 = await prisma.bookmark.findMany({ take: 20, orderBy: { createdAt: "desc" }, select: { id: true, createdAt: true }, where: { readerId: "55a56470-d026-4c42-a24b-30b692b747e2" } });
[
  {
    id: '7e00aa78-5951-4c05-8e42-4edb0927e964',
    createdAt: 2020-06-25T20:05:38.599Z
  },
  {
    id: '84c01d52-838d-4cdd-9035-c09cf54a06a0',
    createdAt: 2020-06-25T19:44:50.760Z
  },
  {
    id: '3e7d6b95-c62d-4e66-bb8c-66a317386e40',
    createdAt: 2020-06-19T21:32:11.877Z
  },
  {
    id: '99f1734d-6ad1-4cf0-b851-2ed551cbabc6',
    createdAt: 2020-06-19T21:32:02.488Z
  },
  {
    id: '9505b8a9-45a1-4aae-a284-5bacfe9f835c',
    createdAt: 2020-06-19T21:31:51.635Z
  },
  {
    id: 'ea732052-aac6-429b-84ea-976ca1f645d0',
    createdAt: 2020-06-11T22:34:15.797Z
  },
  {
    id: '13394728-24a6-4a37-aa6e-369e7f70c10b',
    createdAt: 2020-06-10T21:52:26.998Z
  },
  {
    id: '16fa1ce3-5243-4a30-970e-8ec98d077810',
    createdAt: 2020-06-10T21:52:26.998Z
  },
  {
    id: '36e88f2e-9f4c-4e26-9add-fbf76e404959',
    createdAt: 2020-06-10T21:52:26.998Z
  },
  {
    id: '3c0f269f-0796-427e-af67-8c1a99f3524d',
    createdAt: 2020-06-10T21:52:26.998Z
  },
  {
    id: '517e8f7f-980a-44bf-8500-4e279a120b72',
    createdAt: 2020-06-10T21:52:26.998Z
  },
  {
    id: '620d09a6-f5bd-48b5-bbe6-d55fcf341392',
    createdAt: 2020-06-10T21:52:26.998Z
  },
  {
    id: '755f5bba-25e3-4510-a991-e0cfe02d864d',
    createdAt: 2020-06-10T21:52:26.998Z
  },
  {
    id: '8a49e477-1f12-4a81-953f-c7b0ca5696dc',
    createdAt: 2020-06-10T21:52:26.998Z
  },
  {
    id: '8c7a3864-285c-4f06-9c9a-273e19e19a05',
    createdAt: 2020-06-10T21:52:26.998Z
  },
  {
    id: 'bae99648-bdad-440f-953b-ddab33c6ea0b',
    createdAt: 2020-06-10T21:52:26.998Z
  },
  {
    id: 'eb8c5a20-ae61-402b-830f-f9518957f195',
    createdAt: 2020-06-10T21:52:26.998Z
  },
  {
    id: '79066f5a-3640-42e9-be04-2a702924f4c6',
    createdAt: 2020-06-04T16:00:21.858Z
  },
  {
    id: 'a4b0472a-52fc-4b2d-8c44-4c401c18f469',
    createdAt: 2020-06-03T21:13:57.776Z
  },
  {
    id: 'fc34b132-e376-406e-ab89-10ee35b4d58d',
    createdAt: 2020-05-12T12:30:12.224Z
  }
]
```

I'm then going to paginate through these results 5 at a time.

First 5 are correct
```
let first5 = await prisma.bookmark.findMany({ take: 5, orderBy: { createdAt: "desc" }, select: { id: true, createdAt: true }, where: { readerId: "55a56470-d026-4c42-a24b-30b692b747e2" } });
[
  {
    id: '7e00aa78-5951-4c05-8e42-4edb0927e964',
    createdAt: 2020-06-25T20:05:38.599Z
  },
  {
    id: '84c01d52-838d-4cdd-9035-c09cf54a06a0',
    createdAt: 2020-06-25T19:44:50.760Z
  },
  {
    id: '3e7d6b95-c62d-4e66-bb8c-66a317386e40',
    createdAt: 2020-06-19T21:32:11.877Z
  },
  {
    id: '99f1734d-6ad1-4cf0-b851-2ed551cbabc6',
    createdAt: 2020-06-19T21:32:02.488Z
  },
  {
    id: '9505b8a9-45a1-4aae-a284-5bacfe9f835c',
    createdAt: 2020-06-19T21:31:51.635Z
  }
]
```

Second 5 are correct (notice that the last 4 results here have the same createdAt date)
```
let second5 = await prisma.bookmark.findMany({ take: 5, cursor: { id: '9505b8a9-45a1-4aae-a284-5bacfe9f835c' }, skip: 1,  orderBy: { createdAt: "desc" }, select: { id: true, createdAt: true }, where: { readerId: "55a56470-d026-4c42-a24b-30b692b747e2" } });
[
  {
    id: 'ea732052-aac6-429b-84ea-976ca1f645d0',
    createdAt: 2020-06-11T22:34:15.797Z
  },
  {
    id: '13394728-24a6-4a37-aa6e-369e7f70c10b',
    createdAt: 2020-06-10T21:52:26.998Z
  },
  {
    id: '16fa1ce3-5243-4a30-970e-8ec98d077810',
    createdAt: 2020-06-10T21:52:26.998Z
  },
  {
    id: '36e88f2e-9f4c-4e26-9add-fbf76e404959',
    createdAt: 2020-06-10T21:52:26.998Z
  },
  {
    id: '3c0f269f-0796-427e-af67-8c1a99f3524d',
    createdAt: 2020-06-10T21:52:26.998Z
  }
]
```

Third 5 are not correct. The first three results are included in the second page. Notice that the cursor passed in is actually included as the third item.
```
let third5 = await prisma.bookmark.findMany({ take: 5, cursor: { id: '3c0f269f-0796-427e-af67-8c1a99f3524d' }, skip: 1,  orderBy: { createdAt: "desc" }, select: { id: true, createdAt: true }, where: { readerId: "55a56470-d026-4c42-a24b-30b692b747e2" } });
[
  {
    id: '16fa1ce3-5243-4a30-970e-8ec98d077810',
    createdAt: 2020-06-10T21:52:26.998Z
  },
  {
    id: '36e88f2e-9f4c-4e26-9add-fbf76e404959',
    createdAt: 2020-06-10T21:52:26.998Z
  },
  {
    id: '3c0f269f-0796-427e-af67-8c1a99f3524d',
    createdAt: 2020-06-10T21:52:26.998Z
  },
  {
    id: '517e8f7f-980a-44bf-8500-4e279a120b72',
    createdAt: 2020-06-10T21:52:26.998Z
  },
  {
    id: '620d09a6-f5bd-48b5-bbe6-d55fcf341392',
    createdAt: 2020-06-10T21:52:26.998Z
  }
]
```

The fourth 5 is identical to the third 5, despite passing in a later cursor. Again, the cursor appears in the result set.
```
let fourth5 = await prisma.bookmark.findMany({ take: 5, cursor: { id: '620d09a6-f5bd-48b5-bbe6-d55fcf341392' }, skip: 1,  orderBy: { createdAt: "desc" }, select: { id: true, createdAt: true }, where: { readerId: "55a56470-d026-4c42-a24b-30b692b747e2" } });
[
  {
    id: '16fa1ce3-5243-4a30-970e-8ec98d077810',
    createdAt: 2020-06-10T21:52:26.998Z
  },
  {
    id: '36e88f2e-9f4c-4e26-9add-fbf76e404959',
    createdAt: 2020-06-10T21:52:26.998Z
  },
  {
    id: '3c0f269f-0796-427e-af67-8c1a99f3524d',
    createdAt: 2020-06-10T21:52:26.998Z
  },
  {
    id: '517e8f7f-980a-44bf-8500-4e279a120b72',
    createdAt: 2020-06-10T21:52:26.998Z
  },
  {
    id: '620d09a6-f5bd-48b5-bbe6-d55fcf341392',
    createdAt: 2020-06-10T21:52:26.998Z
  }
]
```

So what it looks like is happening is if the `ORDER BY` field used in conjunction with the cursor is not unique, it will return all results with that matching value and not just the ones that follow the cursor. That's why I'm ending up with the cursor item appearing in the query result. The `skip: 1` skips the first item with that value (in this case, `13394728-24a6-4a37-aa6e-369e7f70c10b` is excluded from `third5` and `fourth5`). But since I have more than 5 items with the same createdAt, it basically gets stuck here in the pagination.

**Comment by Sytten** [comment] 2020-06-26 15:45
Great, so basically the problem is when the `orderBy` has some duplicates. Otherwise it is fine right? I believe this is not a unique problem to prisma, but the problem is that you can't `orderBy` two fields (tracked by https://github.com/prisma/prisma-client-js/issues/702). So until the other issue is resolved, there isn't much to do :S
Once it is possible, it will allow to order by both `createdAt` and `id` so that will resolve your problem.

**Comment by TLadd** [comment] 2020-06-26 16:18
Yes, if there are no duplicates it would work. Being able to pass multiple orderBy's would likely allow it to work as well. If I look at the query that's running though, it seems like it's already trying to order by both fields in the raw sql, so I was thinking there might be some adjustment here that would allow it to work without allowing multiple orderBy's from prisma. 

```
SELECT "public"."bookmark"."id", "public"."bookmark"."created_at" FROM "public"."bookmark" WHERE ("public"."bookmark"."reader_id" = $1 AND ((("public"."bookmark"."created_at") = (SELECT "public"."bookmark"."created_at" FROM "public"."bookmark" WHERE ("public"."bookmark"."id") = ($2)) AND ("public"."bookmark"."id") >= ($3)) OR ("public"."bookmark"."created_at") <= (SELECT "public"."bookmark"."created_at" FROM "public"."bookmark" WHERE ("public"."bookmark"."id") = ($4)))) ORDER BY "public"."bookmark"."created_at" DESC, "public"."bookmark"."id" ASC LIMIT $5 OFFSET $6
```

I guess to me it seems like the query I'm issuing should work without having to manually tell it to also orderBy the id field (even when the capability exists), since it's implied by the fact it's a cursor.

**Comment by Sytten** [comment] 2020-06-26 18:58
Agreed, that looks weird to me. The SQL looks fine apart from the weird WHERE case, so my best guess would a reorder of the items in the engine maybe @mavilein?

**Comment by mavilein** [comment] 2020-06-29 07:29
ping @dpetrick :-)

**Comment by gersomvg** [comment] 2020-06-29 13:13
I'm trying to achieve the same. For now I'll just fallback to offset/limit, since I don't really need cursor based pagination (yet). I'll just implement my opaque cursor with offset/limit for now, so it's easy to switch later.

I found this StackOverflow comment helpful in explaining how a multi-column cursor query would look like:
https://stackoverflow.com/questions/38017054/mysql-cursor-based-pagination-with-multiple-columns/38017813#38017813

**Comment by dpetrick** [comment] 2020-06-29 15:23
A fix is available from `2.2.0-dev.19` onwards.

**Comment by pantharshit00** [comment] 2020-07-01 15:13
I can confirm this is fixed in `2.2.0-dev.19`

**Closed** 2020-07-01 15:26 UTC
Labels: bug/2-confirmed, kind/bug, topic: pagination

**Comment by gersomvg** [comment] 2020-07-02 07:44
@dpetrick What's the implication of the fix? Is it now that you can orderBy only a date and have an ID as cursor? Does it behind the scenes first sort on date and after that on id?

If so, the docs should also reflect this, since it mentions that you need to orderBy the cursor. Happy to make a docs PR.

**Comment by onderonur** [comment] 2020-08-14 01:45
> @dpetrick What's the implication of the fix? Is it now that you can orderBy only a date and have an ID as cursor? Does it behind the scenes first sort on date and after that on id?
> 
> If so, the docs should also reflect this, since it mentions that you need to orderBy the cursor. Happy to make a docs PR.

I use `nanoid` as my id generator. So, it creates non-sequential ids. I've tried setting `cursor` as `id` and ordered by `createdAt`.
It worked like I expected. Right items are returned as the result of the cursor based query. 
It's like this:
```ts
async findCommentConnectionByPostId(
    postId: ID,
    { first, after }: PostCommentsArgs,
  ) {
    const where: CommentWhereInput = { postId };
    const cursor: FindManyCommentArgs['cursor'] = after
      ? { id: after }
      : undefined;
    const totalCount = await prisma.comment.count({ where });

    const comments = await prisma.comment.findMany({
      where,
      take: typeof first === 'number' ? first + 1 : undefined,
      // https://www.prisma.io/docs/reference/tools-and-interfaces/prisma-client/pagination#do-i-always-have-to-skip-1
      // If you do not skip: 1, your result set will include your previous cursor.
      skip: cursor ? 1 : undefined, // Skip the cursor
      orderBy: {
        createdAt: 'desc',
      },
      cursor,
    });

    const hasNextPage =
      typeof first === 'number' ? comments.length > first : false;
    // Removing the last item.
    // We only needed it to know if there are more
    // items than the requested count.
    if (hasNextPage) {
      comments.pop();
    }
    const edges = comments.map((comment) => ({
      node: comment,
      cursor: db.comment.getCursor(comment),
    }));
    const lastEdge = getLastOfArray(edges);
    const endCursor = lastEdge?.cursor;

    return {
      edges,
      pageInfo: {
        hasNextPage,
        endCursor,
      },
      totalCount,
    };
  }
```

But as you mentioned, docs say that you need to order by your cursor and it should be a unique, sequential value.
I guess this was fixed but the docs are a little bit out of date.
Or this was just a very, very lucky experiment. 😀

**Comment by 0xsven** [comment] 2021-09-03 10:02
It even seems to work for me without orderBy ? not sure how ?
