### ISSUE TITLE
Prisma edge client can't read env vars from `.env` file

### ISSUE THREAD

**Issue by kelbyfaessler** [prisma/prisma#18542] opened 2023-03-28 23:29 UTC
### Bug description

When I import "@prisma/client" it reads my env vars (e.g. DATABASE_URL).

Using the same .env file, when I import "@prisma/client/edge" it can't read them anymore and I get
`InvalidDatasourceError: Datasource "db" references an environment variable "DATABASE_URL" that is not set`

This is the local dev server for a sveltekit app, so not even trying to deploy it yet.

The schema code that reads env looks like this:

```
datasource db {
  provider = "mysql"
  url      = env("DATABASE_URL")
  // directUrl = env("DIRECT_URL")
  relationMode = "prisma"
}
```

### How to reproduce

Create sveltekit skeleton project
Verify it works
Add prisma, a schema (reads `DATABASE_URL` from env) with a table, and a row of data (mysql planetscale db)
Add a .env file with the database url string
Verify you can query the database and run the local dev server, see the data in the page
Change to the prisma edge client
You'll see the error above

### Prisma information

Relevant parts of schema already provided

### Environment & setup

- OS: Fedora
- Database: PlanetScale
- Node.js version: 18.7.0

### Prisma Version

```
4.10.0
```

**Comment by kelbyfaessler** [comment] 2023-03-30 11:06
I don't even necessarily need a solution to this problem (although I'll take one if you have it). I just need some ways to debug what is going wrong because right now I don't have any ideas besides reading prisma source code, since that's most of the stacktrace.

Speaking of stacktrace, here it is:
```
InvalidDatasourceError: Datasource "db" references an environment variable "DATABASE_URL" that is not set
    at Ar.resolveDatasourceURL (<myproject>/node_modules/@prisma/client/runtime/edge.js:25:8662)
    at Ar.extractHostAndApiKey (<myproject>/node_modules/@prisma/client/runtime/edge.js:25:7743)
    at new DataProxyEngine (<myproject>/node_modules/@prisma/client/runtime/edge.js:25:3535)
    at t.getEngine (<myproject>/node_modules/@prisma/client/runtime/edge.js:88:3273)
    at new PrismaClient (<myproject>/node_modules/@prisma/client/runtime/edge.js:88:2867)
    at <myproject>/src/lib/server/prisma.ts:4:34
    at async instantiateModule (file://<myproject>/node_modules/vite/dist/node/chunks/dep-3007b26d.js:52400:9)
```

**Comment by kelbyfaessler** [comment] 2023-03-31 23:35
I just created a new sveltekit skeleton project, added prisma with a single table in the schema, confirmed I could query the database (planetscale) with an actual row of data, then switched to the prisma edge client and it stopped working with the same env var error message above.

This definitely appears to be a prisma issue with sveltekit/planetscale

**Comment by jkomyno** [comment] 2023-04-03 10:09
Hi @kelbyfaessler, this issue is indeed a duplicate of https://github.com/prisma/prisma/issues/15958, so I would close this new issue and redirect future communications there.

[This](https://github.com/prisma/prisma/issues/15958#issuecomment-1492611719) seems to be one possible workaround, but we're currently looking for better solutions.

**Comment by kelbyfaessler** [comment] 2023-04-03 14:11
Hi @jkomyno, would you mind sharing your reasoning for why you think this is a duplicate?

**Comment by kelbyfaessler** [comment] 2023-04-03 14:18
A minimal example that reproduces the issue:

https://github.com/kelbyfaessler/prisma-env-var

**Comment by janpio** [comment] 2023-04-03 21:24
See no connection to Cloudflare either.

The edge Client does not load the `.env` file. Does it work if you manually set the environment variable? Or load it via `dotenv-cli` first when starting your server?

**Comment by kelbyfaessler** [comment] 2023-04-05 00:25
@janpio it works if I pass the env var to the client constructor like in the CF issue thread. Not sure why that would make a difference, especially for local dev, but it does.

Still trying to get deployment to vercel edge functions working (also has errors)

**Comment by kelbyfaessler** [comment] 2023-04-08 00:33
The deployment to vercel edge functions now works with the same solution of passing database url env var to the prisma client constructor like this:

```
import { DATABASE_URL } from "$env/static/private";

  new PrismaClient({
    datasources: {
      db: {
        url: DATABASE_URL
      }
    }
  });
```

But the issue remains for why it's necessary to do that when switching to the edge client

**Comment by ticup** [comment] 2023-05-01 11:04
I had the same problem, the proposed workaround works, thanks.

**Comment by Danubius1st** [comment] 2023-07-27 20:45
In my opinion it's still a bug.
I changed the name of a environment variable in vercel settings, and in schema.prisma in my app.
At runtime the log keep saying the old variable name is not set:
`InvalidDatasourceError: Datasource "db" references an environment variable "***" that is not set`
I tried to reverse the changes: same message.

**Comment by janpio** [comment] 2023-07-28 13:43
That sounds like an unrelated problem @Danubius1st. I renamed the issue here to make clearer what this is really about.
Please open a new discussion or issue with your problem, and we can try to figure out what is going on for you.

**Comment by janpio** [comment] 2023-08-07 17:40
@kelbyfaessler I took another look at this, and the explanation is much simpler:

- `@prisma/client` loads the `.env` file and makes its values available as environment variables.
- `@prisma/client/edge` is designed for edge environments where no files can be accessed or read, so it does not try to interact with the `.env` file at all.

So when using `@prisma/client/edge` in your app you have to load the environment variables some other way, and they will be available in your code: 
- In deployment platforms like Lambda, Netlify or Vercel Serverless Functions you can define the environment variables via some UI - and they are then available in `process.env` to your app, which Prisma will read.
- In some other deployment environments like Cloudflare Workers (with the module workers) you do not get the environment variable values you defined in `process.env`, but in e.g. [a param of your handler](https://developers.cloudflare.com/workers/configuration/environment-variables/). In those cases you need to [programmatically override the `url` in the `PrismaClient()` constructor](https://www.prisma.io/docs/reference/api-reference/prisma-client-reference#programmatically-override-a-datasource-url).
- And finally, locally or in other environments where you don't have a nice UI, you need to set it outside of your app for the whole system, or use something like `dotenv-cli` before you execute your app.

That means that on Vercel Edge Functions for example the workaround you posted above should not be necessary.

**Comment by janpio** [comment] 2023-08-07 17:49
(Closing this issue now as `@prisma/client/edge` works as expected - we will still try to improve this situation of course)

**Closed by janpio** 2023-08-07 17:49 UTC
Labels: bug/1-unconfirmed, kind/bug, team/client, topic: .env, topic: data proxy, topic: prisma-client-edge
