### ISSUE TITLE
Error in migration engine: We should only be setting a changed default if there was one on the previous schema and in the next with the same enum. 

### ISSUE THREAD

**Issue by jkomyno** [prisma/prisma#15927] opened 2022-10-21 11:14 UTC
Command: `prisma migrate dev`
Version: `4.5.0`
Binary Version: `0362da9eebca54d94c8ef5edd3b2e90af99ba452`
Report: https://prisma-errors.netlify.app/report/14387 
OS: `arm64 darwin 21.6.0`

Rust Stacktrace:
```
Starting migration engine RPC server
Analysis run in 26ms
[migration-engine/connectors/sql-migration-connector/src/sql_renderer/postgres_renderer.rs:1011:22] We should only be setting a changed default if there was one on the previous schema and in the next with the same enum.
```

## Context

This error is happening because we're attempting to unwrap a `None` value into `default_str` via an `expect()` call:

https://github.com/prisma/prisma-engines/blob/1efe6d372597cdb48067c5dd1f441702a1b0861e/migration-engine/connectors/sql-migration-connector/src/sql_renderer/postgres_renderer.rs#L1006-L1020

## Potential Solution

I think we should conditionally apply the `SET DEFAULT` expression in the pushed statement only when `default_str` is a `Some(_)`. I could easily do that as a side task.

**Comment by tomhoule** [comment] 2022-10-24 05:17
I am pretty sure this is a duplicate of https://github.com/prisma/prisma/issues/15927

**Closed by tomhoule** 2022-10-24 05:17 UTC
Labels: kind/bug, process/candidate, tech/engines/datamodel, topic: error reporting, team/schema, topic: postgresql
