### ISSUE TITLE
Improve error message when client fails to connect to a mongodb database

### ISSUE THREAD

**Issue by josh-hemphill** [prisma/prisma#6760] opened 2021-04-23 20:02 UTC
Hi Prisma Team! My Prisma Client just crashed. This is the report:
## Versions

| Name            | Version            |
|-----------------|--------------------|
| Node            | v14.16.1           | 
| OS              | debian-openssl-1.1.x (WSL) |
| Prisma Client   | 2.21.2             |
| Query Engine    | query-engine e421996c87d5f3c8f7eeadd502d4ad402c89464d|
| Database        | undefined|

## Query
```
query {
  findManyusers {
    id
    username
    collapsed
    darktheme
  }
}
```

## Logs
```
isma:engine stdout  Started http server on http://127.0.0.1:44611  
  prisma:engine Search for Query Engine in /home/jhemphill/data-model/node_modules/.prisma/client  
  plusX Execution permissions of /home/jhemphill/data-model/node_modules/.prisma/client/query-engine-debian-openssl-1.1.x are fine  
  prisma:engine Client Version: 2.21.2  
  prisma:engine Engine Version: query-engine e421996c87d5f3c8f7eeadd502d4ad402c89464d  
  prisma:engine Active provider: mongodb  
  prisma:engine stderr  [query-engine/connectors/mongodb-query-connector/src/error.rs:28] &self = DriverError(  +30s
  prisma:engine stderr      Error {  
  prisma:engine stderr          kind: ServerSelectionError {  
  prisma:engine stderr              message: "Server selection timeout: No available servers. Topology: { Type: Unknown, Servers: [ { Address: localhost:27017, Type: Unknown, Error: Connection refused (os error 111) }, ] }",  
  prisma:engine stderr          },  
  prisma:engine stderr          labels: [],  
  prisma:engine stderr      },  
  prisma:engine stderr  )  
  prisma:engine stdout  PANIC in query-engine/connectors/mongodb-query-connector/src/error.rs:115:75
not yet implemented  
  prisma:engine {
  prisma:engine   error: SocketError: other side closed
  prisma:engine       at Socket.onSocketEnd (/home/jhemphill/data-model/node_modules/@prisma/client/runtime/index.js:25205:24)
  prisma:engine       at Socket.emit (events.js:327:22)
  prisma:engine       at Socket.EventEmitter.emit (domain.js:467:12)
  prisma:engine       at endReadableNT (internal/streams/readable.js:1327:12)
  prisma:engine       at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  prisma:engine     code: 'UND_ERR_SOCKET'
  prisma:engine   }
  prisma:engine }  
  prisma:engine { cwd: '/home/jhemphill/ciwi/data-model/prisma' }  
  prisma:engine Search for Query Engine in /home/jhemphill/data-model/node_modules/.prisma/client  
  plusX Execution permissions of /home/jhemphill/data-model/node_modules/.prisma/client/query-engine-debian-openssl-1.1.x are fine  +30s
  prisma:engine {
  prisma:engine   flags: [
  prisma:engine     '--enable-experimental=microsoftSqlServer,mongodb,mongodb',
  prisma:engine     '--enable-raw-queries',
  prisma:engine     '--port',
  prisma:engine     '42905'
  prisma:engine   ]
  prisma:engine }  
  prisma:engine stdout  Started http server on http://127.0.0.1:42905  
  prisma:engine Search for Query Engine in /home/jhemphill/data-model/node_modules/.prisma/client  
  plusX Execution permissions of /home/jhemphill/data-model/node_modules/.prisma/client/query-engine-debian-openssl-1.1.x are fine  
  prisma:engine Client Version: 2.21.2  
  prisma:engine Engine Version: query-engine e421996c87d5f3c8f7eeadd502d4ad402c89464d  
  prisma:engine Active provider: mongodb  
  prisma:engine stderr  [query-engine/connectors/mongodb-query-connector/src/error.rs:28] &self = DriverError(  +30s
  prisma:engine stderr      Error {  
  prisma:engine stderr          kind: ServerSelectionError {  
  prisma:engine stderr              message: "Server selection timeout: No available servers. Topology: { Type: Unknown, Servers: [ { Address: localhost:27017, Type: Unknown, Error: Connection refused (os error 111) }, ] }",  
  prisma:engine stderr          },  
  prisma:engine stderr          labels: [],  
  prisma:engine stderr      },  
  prisma:engine stderr  )  
  prisma:engine stdout  PANIC in query-engine/connectors/mongodb-query-connector/src/error.rs:115:75
not yet implemented  
  prisma:engine {
  prisma:engine   error: SocketError: other side closed
  prisma:engine       at Socket.onSocketEnd (/home/jhemphill/data-model/node_modules/@prisma/client/runtime/index.js:25205:24)
  prisma:engine       at Socket.emit (events.js:327:22)
  prisma:engine       at Socket.EventEmitter.emit (domain.js:467:12)
  prisma:engine       at endReadableNT (internal/streams/readable.js:1327:12)
  prisma:engine       at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  prisma:engine     code: 'UND_ERR_SOCKET'
  prisma:engine   }
  prisma:engine }  
```

## Client Snippet
```ts
import { PrismaClient } from '.prisma/client/index.js';

const prisma = new PrismaClient();

async function main() {
	const allUsers = await prisma.users.findMany();
	console.log(allUsers);
}

main()
	.catch((e) => {
		throw e;
	})
	.finally(async () => {
		await prisma.$disconnect();
	});
```

## Schema
```prisma
datasource db {
    provider = "mongodb"
    url      = env("DATABASE_URL")
}

generator client {
    provider        = "prisma-client-js"
    previewFeatures = ["microsoftSqlServer", "mongodb"]
}

model users {
    id        String @id @default(dbgenerated()) @map("_id") @db.ObjectId
    username  String @unique
    collapsed String
    darktheme String
}
```

**Comment by janpio** [comment] 2021-04-24 10:50
> ```
>   prisma:engine stderr  [query-engine/connectors/mongodb-query-connector/src/error.rs:28] &self = DriverError(  +30s
>   prisma:engine stderr      Error {  
>   prisma:engine stderr          kind: ServerSelectionError {  
>   prisma:engine stderr              message: "Server selection timeout: No available servers. Topology: { Type: Unknown, Servers: [ { Address: localhost:27017, Type: Unknown, Error: Connection refused (os error 111) }, ] }",  
>   prisma:engine stderr          },  
>   prisma:engine stderr          labels: [],  
>   prisma:engine stderr      },  
>   prisma:engine stderr  )  
>   prisma:engine stdout  PANIC in query-engine/connectors/mongodb-query-connector/src/error.rs:115:75
> ```

Should there have been a sercer available at this address?

(Error message is of course confusing and should be fixed.)

**Comment by josh-hemphill** [comment] 2021-04-25 07:24
> Should there have been a sercer available at this address?

I don't know. I just tried running the client for the first time.

**Comment by janpio** [comment] 2021-04-26 20:35
> > Should there have been a sercer available at this address?
> 
> I don't know. I just tried running the client for the first time.

Ha, that would of course know if the MongoDB server is indeed reachable at that address. Can you maybe try with another client that could verify your credentials are correct?

**Comment by josh-hemphill** [comment] 2021-04-26 21:04
That would be it. I was running in WSL and the server was in the host, so my MongoDB compass connected fine, but I had to run the nodejs mongo driver and try connecting in WSL to realize it wasn't reachable.

**Comment by janpio** [comment] 2021-04-26 21:07
Ok thanks. Now we know the circumstances, still a bug as you did not get a good error message but the Engine panicked instead. We can fix that.

**Comment by pantharshit00** [comment] 2021-05-17 13:53
Its not a panic now in version `2.23.0-dev.37` but it is still ugly. We should improve it:
![image](https://user-images.githubusercontent.com/22195362/118500382-5dd81200-b745-11eb-8ed5-3890253a5414.png)

**Comment by janpio** [comment] 2022-01-28 23:40
Duplicate of https://github.com/prisma/prisma/issues/8966 now that this is not a panic any more.

**Comment by matthewmueller** [comment] 2022-02-16 22:53
Closing in favor of #8966

**Closed by matthewmueller** 2022-02-16 22:53 UTC
Labels: bug/2-confirmed, kind/bug, topic: error, team/client, topic: rust panic, topic: mongodb
