### ISSUE TITLE
[Engine PANIC] 6 or more upserts in a row causes PANIC, less than 6 is OK. Only for versions > 2.0.0

### ISSUE THREAD

**Issue by allesklarbeidir** [prisma/prisma#3056] opened 2020-07-17 10:59 UTC
Dear Prisma Team,

## Bug description

I discovered a weird error which occurred when upserting many rows, when they are already present in the database.

``Error: PANIC: called `Option::unwrap()` on a `None` value``

Is thrown when I run more than 5 upserts in a row. The 6th upsert crashes the engine.
Also this does not happen when using prisma 2.0.0, only upwards.

I'd image that there may be some issue with the caching of prepared statements because I also had an error where prisma was complaining about a missing ID in a nested create->connect write even if I hardcoded the value. And that error also was only present if I used prisma > 2.0.0. However, since I have no reproduceable example for that, this report is more about the 6-upsert-crash issue.

**Note that in version 2.1.3 the error only occurs when running the 6 upserts via graphql.
In 2.2.0 the error even occurs when using the prisma client directly, without graphql....**

## How to reproduce

I have prepared a repo here: https://github.com/allesklarbeidir/prisma-panic-6-upsert

## Expected behavior

It should just run fine without any error, like in version 2.0.0

## Prisma information

It's all in the repo: https://github.com/allesklarbeidir/prisma-panic-6-upsert

## Environment & setup

- OS: Mac OS 10.15.5
- Database: PostgreSQL
- Prisma version 2.0.0 is ok, upwards there's the described error
- Node.js version: v12.14.0

**Comment by divyenduz** [comment] 2020-07-29 12:30
I am unable to reproduce this with `2.4.0-dev.29` when using Prisma client directly. I used the following script.

Test this script with other versions and also testing the original GraphQL repro now. 

```ts
const { PrismaClient } = require('@prisma/client')

const prisma = new PrismaClient()

async function main() {
  const five = await Promise.all(
    [1, 2, 3, 4, 5].map(async (i) => {
      return await prisma.keyValuePair.upsert({
        update: {},
        where: {
          name: `test_${i}`,
        },
        create: {
          name: `test_${i}`,
          description: `description_${i}`,
        },
      })
    }),
  )
  console.log({ five })

  const six = await Promise.all(
    [1, 2, 3, 4, 5, 6].map(async (i) => {
      return await prisma.keyValuePair.upsert({
        update: {},
        where: {
          name: `test_${i}`,
        },
        create: {
          name: `test_${i}`,
          description: `description_${i}`,
        },
      })
    }),
  )
  console.log({ six })
}

main()

```

**Comment by divyenduz** [comment] 2020-07-29 12:34
Update: I am also unable to reproduce this with 2.2.0 and the provided reproduction.

**Comment by ryands17** [comment] 2020-07-29 12:57
Unable to reproduce this on version `2.3.0`. Tried it with these approaches:

```ts
  for (let i of [1, 2, 3, 4, 5, 6]) {
    await prisma.user.upsert({
      update: {
        name: `user ${i} updated`,
      },
      create: {
        email: `user${i}@g.com`,
        name: `user ${i}`,
      },
      where: {
        id: i,
      },
    })
  }
```

and

```
const users = [7, 8, 9, 10, 11, 12, 13].map((i) =>
    prisma.user.upsert({
      update: {
        name: `user ${i}`,
      },
      create: {
        email: `user${i}@g.com`,
        name: `user ${i}`,
      },
      where: {
        id: i,
      },
    })
  )
  await Promise.all(users)
```

**Comment by pantharshit00** [comment] 2020-08-05 09:52
Hey @allesklarbeidir 

Can you please try this again with the latest version and report back? Thanks!

**Comment by allesklarbeidir** [comment] 2020-08-05 12:38
Hey, thank you guys for looking into this!
I've been away for a week, so I'm looking again into this right now.
Setting up a clean environment, so I can isolate the error better.

I'll post feedback as soon as I have some news.

**Comment by allesklarbeidir** [comment] 2020-10-23 15:05
Hey @pantharshit00,

it took me some time to re-investigate on this in a structured way, but now I got some new insights.

Meanwhile I built a testsuite for my microservice-architecture where I have multiple graphql servers with nexus + prisma and with this testsuite I was able to debug multiple version-combinations, all with an always fresh and clean environment.

One important note (I didn't know that'd be important when I opened the issue):
I use YugaByteDB – I have seen an issue where you declare, that prisma is unfortunately not working with YugaByte and that you don't have the resources to fix that right now, and I completely understand that but **please do not solely dismiss this as unsolvable due to YugaByte --> I have an idea :)**


Originally this issue even caused my database to crash, I found out a little later after more debugging, then I used an older version of YugaByte and it did not crash anymore. So for a while I thought the error was gone, but it wasn't.
I have created a new minimal example for reproducing the error:
[https://github.com/allesklarbeidir/yb-prisma-error-reproduce](url)

I have watched the YugaByte Postgres log file when running the tests and there I can see that prisma is mostly generating transactions for the queries. Especially if using a nested "connect".


The error happens in the following way:

1. Insert row a in relation A. 
    (model KeyValuePair in the "yb-prisma-error-reproduce" repo)

2. Insert row b in relation B with a foreign key to row a in relation A.
    (model ReferenceKeyValuePair in the "yb-prisma-error-reproduce" repo)

3. (This is probably optional)
     Delete row b.
     Delete row a.

4. Repeat


Now, this is fine with prisma 2.0.0 no mater how often you repeat the process.

But if you use prisma >= 2.1.0 an error occurs in the 6th iteration. YugaByte seems to fail to return row a for the nested "connect-check" when prisma wants to insert row b with a transaction (checking if row a exists before the insert).
I can see this in the postgres logs:


First the `0-test-5` and `0-test-6` KeyValuePair is inserted:
```
LOG:  statement: BEGIN

LOG:  execute s0: INSERT INTO "public"."KeyValuePair" ("name","description") VALUES ($1,$2) RETURNING "public"."KeyValuePair"."name"

DETAIL:  parameters: $1 = '0-test-5', $2 = '0-some-description-5'

LOG:  execute s1: SELECT "public"."KeyValuePair"."name", "public"."KeyValuePair"."description" FROM "public"."KeyValuePair" WHERE "public"."KeyValuePair"."name" = $1 LIMIT $2 OFFSET $3

DETAIL:  parameters: $1 = '0-test-5', $2 = '1', $3 = '0'

LOG:  statement: COMMIT

LOG:  statement: BEGIN

LOG:  execute s0: INSERT INTO "public"."KeyValuePair" ("name","description") VALUES ($1,$2) RETURNING "public"."KeyValuePair"."name"

DETAIL:  parameters: $1 = '0-test-6, $2 = '0-some-description-6'

LOG:  execute s1: SELECT "public"."KeyValuePair"."name", "public"."KeyValuePair"."description" FROM "public"."KeyValuePair" WHERE "public"."KeyValuePair"."name" = $1 LIMIT $2 OFFSET $3

DETAIL:  parameters: $1 = '0-test-6', $2 = '1', $3 = '0'

LOG:  statement: COMMIT
```

Then the `0-test-5` ReferenceKeyValuePair is inserted, **which works fine.**
```
LOG:  execute s2: SELECT "public"."KeyValuePair"."name" FROM "public"."KeyValuePair" WHERE "public"."KeyValuePair"."name" = $1 OFFSET $2

DETAIL:  parameters: $1 = '0-test-5', $2 = '0'

LOG:  execute s3: INSERT INTO "public"."ReferenceKeyValuePair" ("kvpId","someId") VALUES ($1,$2) RETURNING "public"."ReferenceKeyValuePair"."kvpId", "public"."ReferenceKeyValuePair"."someId"

DETAIL:  parameters: $1 = '0-test-5', $2 = '0-someid-5'

LOG:  execute s4: SELECT "public"."ReferenceKeyValuePair"."kvpId", "public"."ReferenceKeyValuePair"."someId" FROM "public"."ReferenceKeyValuePair" WHERE ("public"."ReferenceKeyValuePair"."kvpId" = $1 AND "public"."ReferenceKeyValuePair"."someId" = $2) LIMIT $3 OFFSET $4

DETAIL:  parameters: $1 = '0-test-5', $2 = '0-someid-5', $3 = '1', $4 = '0'

LOG:  statement: COMMIT
```

Then the `0-test-6` ReferenceKeyValuePair is inserted, **which is rolled back because the 'row a' reference is not found.**
```
LOG:  statement: BEGIN

LOG:  execute s2: SELECT "public"."KeyValuePair"."name" FROM "public"."KeyValuePair" WHERE "public"."KeyValuePair"."name" = $1 OFFSET $2

DETAIL:  parameters: $1 = '0-test-6', $2 = '0'

LOG:  statement: ROLLBACK

```


So then the 6th insert with a nested connects fails. To me it clearly looks like an YugaByte issue, and I will report it there, because if I use YugaByte >= 2.2.0 the database even crashes and is not just not returning the previously inserted 'row a'.

**But I'd like to ask you**, if you guys can help tracking the error down by pointing me in a direction on how I can disable the **Prepared statement caching for PostgreSQL** prisma-feature which was introduced in **prisma 2.1.0** because I suspect it may be related to the error in YB and even a hacky workaround would be super helpful for me right now, so that I might use new prisma versions with **disabled Prepared statement caching for PostgreSQL**.

I can't imagine any other change from prisma 2.0.0 to 2.1.0 to be causing this issue.

**Comment by pantharshit00** [comment] 2020-11-03 13:44
@allesklarbeidir 

You can disable statement caching by setting the cache size to zero using `statement_cache_size=0` parameter in the connection string.
```
postgresql://test:test@testhost:5432/mydb?schema=public&statement_cache_size=0
```

Regarding usage of yugabyte, I will recommend you to not run this in a critical production setup as our CI pipeline failed when we tried to test against yugabyte(https://github.com/prisma/prisma-engines/pull/1139) so some bugs can bite you really hard down the road. But still, best of luck with your investigation.

**Comment by allesklarbeidir** [comment] 2020-11-11 12:08
@pantharshit00 

Thank you very much for the `statement_cache_size=0` instructions!
I just tested the error-reproduction repo I provided with that parameter in the connection string and the error is completely gone 🎉 !
I tested all the versions in the repo (prisma 2.0.0, 2.1.3, 2.2.0) without and with the `statement_cache_size=0` parameter and once I add the parameter to the connection string all the prisma versions are working with yugabyte, not only the 2.0.0 version. I ran it with yugabyte 2.1.5 and 2.2.0 like all the tests I ran during my investigation.

I also tested the latest version of prisma (2.11.0) and yugabyte (2.3.3.0-b106) and it's working if add the parameter.

If I find some time, I'll try to run your testsuite to see if this changes anything for your tests as well. But you could check that out yourself... I guess you're faster with setting up your tests with yugabyte + the `statement_cache_size=0` parameter 😉

With this knowledge the guys at yugabyte might also find it easier to fix the bug, we'll see. Would be awesome to have prisma working together with yugabyte in stable way.

I'll report back as soon as I have some news :)

**Comment by janpio** [comment] 2021-03-23 19:22
I am going to close this now. Happy to take a look again if we get more information.

**Closed by janpio** 2021-03-23 19:22 UTC
Labels: bug/0-needs-info, kind/bug, status/needs-action, team/support-engineering

**Comment by krishna-yb** [comment] 2025-03-06 05:53
@ankur-arch I tested this with the latest version of YugabyteDB, and it works as expected. I successfully performed CRUD operations on over 100 rows without any issues.
