### ISSUE TITLE
after migrating new schema, photon doesn't know the argument

### ISSUE THREAD

**Issue by gaspan** [prisma/prisma#1443] opened 2020-01-27 08:49 UTC
my firsrt table :

| column       | Type |
| ------------- |:-------------:|
| employee_id      | String |
| payrol    | String     |   

in my schema.prisma 

```
model EmployeePayroll {
  id          String    @default(cuid()) @id
  employee_id Employee?
  payrol      String
  createdAt   DateTime  @default(now())
  updatedAt   DateTime  @updatedAt
}

```

then i changed the schema to 

| column       | Type |
| ------------- |:-------------:|
| employee_id      | String |
| payrol    | String     |   
| status    | Int |   
| note    | String     |   

in my schema.prisma

```
model EmployeePayroll {
  id          String    @default(cuid()) @id
  employee_id Employee?
  status      Int
  note        String
  payrol      String
  createdAt   DateTime  @default(now())
  updatedAt   DateTime  @updatedAt
}

```

after i run the command 

```
$ npx prisma2 lift save --name 'init'
$ npx prisma2 lift up
$ npx prisma2 generate
$ npm -s run generate
$ npm run build

```

then i call the graphql it responsed like this: 

```json
{
    "errors": [
        {
            "message": "\nInvalid `photon.employeePayrolls.create()` invocation in Product\\prisma-hcm-apollo\\functions\\lib\\types\\mutations\\Payroll.js:146:48\n\n{\n  data: {\n    employee_id: {\n      connect: {\n        id: 'ck5hmwpnr000040uqppjwe08t'\n      }\n    },\n    payrol: '{\"salaryDelails\":{\"employmentType\":\"Intern\",\"basicSalary\":3000000},\"allowance\":[{\"name\":\"meal\",\"amount\":20000,\"type\":\"monthly\"},{\"name\":\"transport\",\"amount\":20000,\"type\":\"daily\"}],\"deduction\":[{\"name\":\"absent\",\"amount\":20000,\"type\":\"daily\"}]}',\n    status: 1\n    ~~~~~~\n  }\n}\n\nUnknown arg `status` in data.status for type EmployeePayrollCreateInput. Did you mean `select`? Available args:\ntype EmployeePayrollCreateInput {\n  id?: ID\n  payrol: String\n  createdAt?: DateTime\n  updatedAt?: DateTime\n  employee_id?: EmployeeCreateOneWithoutEmployee_idInput\n}\n\n",
            "locations": [
                {
                    "line": 2,
                    "column": 3
                }
            ],
            "path": [
                "createEmployeePayrollHR"
            ],
            "extensions": {
                "code": "INTERNAL_SERVER_ERROR",
                "exception": {
                    "stacktrace": [
                        "Error: ",
                        "Invalid `photon.employeePayrolls.create()` invocation in Product\\prisma-hcm-apollo\\functions\\lib\\types\\mutations\\Payroll.js:146:48",
                        "",
                        "{",
                        "  data: {",
                        "    employee_id: {",
                        "      connect: {",
                        "        id: 'ck5hmwpnr000040uqppjwe08t'",
                        "      }",
                        "    },",
                        "    payrol: '{\"salaryDelails\":{\"employmentType\":\"Intern\",\"basicSalary\":3000000},\"allowance\":[{\"name\":\"meal\",\"amount\":20000,\"type\":\"monthly\"},{\"name\":\"transport\",\"amount\":20000,\"type\":\"daily\"}],\"deduction\":[{\"name\":\"absent\",\"amount\":20000,\"type\":\"daily\"}]}',",
                        "    status: 1",
                        "    ~~~~~~",
                        "  }",
                        "}",
                        "",
                        "Unknown arg `status` in data.status for type EmployeePayrollCreateInput. Did you mean `select`? Available args:",
                        "type EmployeePayrollCreateInput {",
                        "  id?: ID",
                        "  payrol: String",
                        "  createdAt?: DateTime",
                        "  updatedAt?: DateTime",
                        "  employee_id?: EmployeeCreateOneWithoutEmployee_idInput",
                        "}",
                        "",
                        "",
                        "    at Document.validate (D:\\Gtalent Product\\prisma-hcm-apollo\\functions\\lib\\node_modules\\@prisma\\photon\\runtime\\index.js:40664:23)",
                        "    at EmployeePayrollClient.get _document [as _document] (D:\\Gtalent Product\\prisma-hcm-apollo\\functions\\lib\\node_modules\\@prisma\\photon\\index.js:1440:22)",
                        "    at EmployeePayrollClient.then (D:\\Gtalent Product\\prisma-hcm-apollo\\functions\\lib\\node_modules\\@prisma\\photon\\index.js:1461:63)",
                        "    at process._tickCallback (internal/process/next_tick.js:189:7)"
                    ]
                }
            }
        }
    ],
    "data": null
}

```

how i fix this ? is this kind a bug?

**Comment by gaspan** [comment] 2020-01-27 08:59
solved,
it must to define new type base one schema

**Comment by pantharshit00** [comment] 2020-01-29 09:40
Can you please paste here what exact query that you are running? The provided information is insufficent for a reproduction. Maybe you can provide me with a git repository that I can use for a minimal reproduction of this issue.

**Comment by janpio** [comment] 2020-09-02 02:28
Hey @gaspan , could you have another look at this after @pantharshit00 could not reproduce this? With a newer Prisma version this should definitely not happen any more. If you can not reproduce this, we would like to close the issue (or you can do that for us).

**Comment by janpio** [comment] 2021-03-23 19:21
I am going to close this now. Happy to take a look again if we get more information.

**Closed by janpio** 2021-03-23 19:21 UTC
Labels: bug/0-needs-info, kind/bug, status/needs-action
