### ISSUE TITLE
Error: Not Found https://binaries.prisma.sh/all_commits/[hash]/linux-arm-openssl-1.1.x/introspection-engine.gz

### ISSUE THREAD

**Issue by jonahsnider** [prisma/prisma#9503] opened 2021-09-29 09:23 UTC
### Bug description

Running `prisma generate` in an Alpine Linux container with `armv7` CPU architecture causes this error:

```
Error: Not Found https://binaries.prisma.sh/all_commits/c22652b7e418506fab23052d569b85d3aec4883f/linux-arm-openssl-1.1.x/introspection-engine.gz
```

### How to reproduce

1. Clone [this reproduction repo](https://github.com/jonahsnider/prisma-bug-9503)
2. Follow the instructions in the README

### Expected behavior

The command should not error

### Prisma information

N/A

### Environment & setup

- OS: Alpine Linux `v3.13`
- Database: N/A
- Node.js version: v16.10.0

### Prisma Version

Best I can tell you is `v3.1.1`, running `prisma -v` crashes with `Error: Not Found https://binaries.prisma.sh/all_commits/c22652b7e418506fab23052d569b85d3aec4883f/linux-arm-openssl-1.1.x/introspection-engine.gz`

**Comment by jonahsnider** [comment] 2021-10-04 02:50
I have updated the issue description with a minimal viable reproduction: https://github.com/jonahsnider/prisma-bug-9503

**Comment by pantharshit00** [comment] 2021-10-04 09:59
This is expected. We don't officially compile for armv7 (32 bit ARM). There was a bug where ARM64 platform was only named `arm` which got recently fixed: https://github.com/prisma/prisma/issues/8653

If you need ARM v7 binaries, you can download them from here(not officially supported): https://github.com/pantharshit00/prisma-rpi-builds

**Comment by pantharshit00** [comment] 2021-10-04 09:59
I closed this as duplicate of https://github.com/prisma/prisma/issues/5497

**Closed by pantharshit00** 2021-10-04 09:59 UTC
Labels: bug/0-needs-info, kind/bug, team/client, topic: engine download, topic: arm
