### ISSUE TITLE
`new PrismaClient()` allow path to schema as constructor argument to override config 

### ISSUE THREAD

**Issue by tcharlat** [prisma/prisma#9676] opened 2021-10-08 09:16 UTC
## Problem

* After generating the client from the schema
* When I import the client constructor and instantiate a client and  I don't have the prisma.schema in the current working directory
* Then the generated code throws after failing to find a schema (in the first folder from a readdirsync)

We have this issue in many scenario :

* we run tests from the root of the repository and not in the folder where the prisma.schema is
* we build the application and the output build searches for a prisma.schema in incorrect locations at runtime
* we share the prisma client between several packages and want to use lerna to expose the client as a dependency

Our workarounds imply to copy the schema from its `source of truth` location in the repository to a location where the runtime will search for it.

It's a hack and even as such it's a little weird because the runtime searches in the list of folders in the current working directory and will throw after the first unsuccessful search.

```sh
  ● Test suite failed to run

    ENOENT: no such file or directory, open '/Users/###/##-service/backend/api/.data/schema.prisma'
```

If I create a new folder `!data` in the directory I launch my test script from :

```sh
  ● Test suite failed to run

    ENOENT: no such file or directory, open '/Users/###/##-service/backend/api/!data/schema.prisma'
```

So if we want the runtime to successfuly instantiate a client we not only need to copy the schema but to create a target directory for the copy, prefixed with`_` or `!` to garantee it's the first hit in a readdirSync sorted list of folders.
We are currently only working on macos in our team but I fear that this "hack" may break on another os if the sorting does not strictly follow the same rule.

## Suggested solution

I see two solutions:

* When building the client with prisma generate, instead of copying the schema in the output folder, include the schema in the output code as a string, like in a schema.js exporting the string as if from a `readFileSync`. That way instead of searching the filesystem at run time, just load the schema from the build. 
* Or, if the capability to change the schema between the build time and the run time has to be supported, allow to give the path to the schema or the string of the schema when instantiating a new client :

```typescript
  const client = new PrismaClient({schema: readFileSync(schemaLocation)})

  // or

  const client = new PrismaClient({schemaPath: schemaLocation})
```

**Comment by tcharlat** [comment] 2021-10-09 07:39
@janpio 

Ok I'm on it.

> That sounds like a bug. Do you have a reproduction of this? If so, can you please open a new bug issue here and supply all the information it asks for? We should fix that.

For further understanding, do you consider the bug to be "loading the schema at runtime", or "incorrect location" ?

**Comment by janpio** [comment] 2021-10-11 13:45
Incorrect location. Usually the schema should be included in the generated Client, and be loaded from there.

**Comment by jaridmargolin** [comment] 2021-11-06 22:07
I am also running into `prisma.schema` resolution issues due to a shared client inside of a monorepo. While I have limited knowledge of other potential moving parts within the system, it does seem like the suggested solution could sidestep a host of runtime resolution problems.

> When building the client with prisma generate, instead of copying the schema in the output folder, include the schema in the output code as a string, like in a schema.js exporting the string as if from a readFileSync. That way instead of searching the filesystem at run time, just load the schema from the build.

**Comment by homoky** [comment] 2021-11-11 10:22
I have the same issue. I have prisma as separate lib in monorepo and when building nextjs app prisma try to locate schema from nextjs app folder instead of the prisma lib folder where it is located. 

It was working in 2.26.0, not working in 3.4.2.

**Comment by homoky** [comment] 2021-11-18 07:30
Same on 3.5.0.

**Comment by janpio** [comment] 2021-11-18 09:24
Do you have a reproduction of this? Then optimally open a new issue @homoky so we can try the reproduction and confirm if it works. With that it will be much easier for us to fix the problem. Thanks.

**Comment by mervinjin** [comment] 2021-11-20 00:54
@janpio I open a new issue with reproduction  #10361

**Comment by andyjy** [comment] 2021-11-20 02:30
> I have the same issue. I have prisma as separate lib in monorepo and when building nextjs app prisma try to locate schema from nextjs app folder instead of the prisma lib folder where it is located.

figured out a workaround, at least for now: https://github.com/prisma/prisma/issues/9435#issuecomment-974576800

**Comment by homoky** [comment] 2021-11-24 22:27
I can confirm that solution that @andyjy mentioned really works.

**Comment by pantharshit00** [comment] 2022-06-02 13:53
Looks like this is resolved and #9435 is also closed. So I am also going to close this.

**Closed by pantharshit00** 2022-06-02 13:53 UTC
Labels: bug/0-unknown, kind/bug, team/client

**Comment by cjmaria** [comment] 2023-09-11 16:50
I still see a need for this feature. In the general case it will be simpler than @andyjy 's approach, and also it will support some scenarios that the workaround does not apply to, such as when trying to use the prisma client in a [SAM lambda](https://github.com/prisma/prisma/issues/18858).

**Comment by janpio** [comment] 2023-09-11 17:43
A Prisma Client that does not include a Prisma schema file in the expected location is a bug, and something we need to fix. Please open a new issue and describe your problem so we can solve that bug properly. Thanks.
