### ISSUE TITLE
Ability to Split Schema into multiple files for Prisma 2

### ISSUE THREAD

**Issue by volkankorkmaz** [prisma/prisma#7347] opened 2021-05-29 13:31 UTC
Maybe someone has asked before. In Prisma 1 it was possible to split Schema files. I couldn't see that in Prisma 2! Are there any development plans for this?

Thanks

**Comment by pantharshit00** [comment] 2021-05-29 14:24
Hi,

Thanks for reporting this! It has already been reported before, so I am going to close this as a duplicate of https://github.com/prisma/prisma/issues/2377

**Closed by pantharshit00** 2021-05-29 14:24 UTC
