### ISSUE TITLE
introspection crashed

### ISSUE THREAD

**Issue by yashbothra-kointrack** [prisma/prisma#15055] opened 2022-08-29 06:18 UTC
Hi Prisma Team! Prisma Migrate just crashed. 

## Command

`db pull`

## Versions
      
| Name        | Version            |
|-------------|--------------------|
| Platform    | windows            | 
| Node        | v16.15.1           | 
| Prisma CLI  | 4.2.1              | 
| Engine      | 2920a97877e12e055c1333079b8d19cee7f33826| 

## Error
```
Error: [introspection-engine\connectors\sql-introspection-connector\src\re_introspection.rs:489:14] Could not find relation field exchange_metadata on model Tags.
```

**Comment by janpio** [comment] 2022-08-29 09:51
Do I understand correctly that you have a Prisma schema where you accidentally used the same relation name on two different relations in a model, and then when running (Re-)Introspection again you get this error message?

**Comment by jkomyno** [comment] 2023-02-17 12:47
(Internal): This happens on `introspection` as well, according to [this report](https://prisma-errors.netlify.app/report/14527)

**Comment by tomhoule** [comment] 2023-02-17 13:53
This is likely fixed, we should try to confirm that.

**Comment by Weakky** [comment] 2023-07-13 13:36
Hey @yashbothra-kointrack,

Could you please confirm whether you're still experiencing this issue?

Thank you 🙏

**Comment by jharrell** [comment] 2023-07-25 14:59
Closing as duplicate of #10453

**Closed by jharrell** 2023-07-25 14:59 UTC
Labels: bug/0-unknown, kind/bug, topic: migrate, team/schema, topic: prisma db pull
