### ISSUE TITLE
called `Option::unwrap()` on a `None` value

### ISSUE THREAD

**Issue by chouzzy** [prisma/prisma#18924] opened 2023-04-25 14:00 UTC
Hi Prisma Team! My Prisma Client just crashed. This is the report:
## Versions

| Name            | Version            |
|-----------------|--------------------|
| Node            | v16.17.1           | 
| OS              | windows            |
| Prisma Client   | 4.7.1              |
| Query Engine    | 272861e07ab64f234d3ffc4094e32bd61775599c|
| Database        | mongodb            |

## Logs
```
prisma:tryLoadEnv Environment variables loaded from C:\Users\mathf\Documents\awer\Backend\cursinho\helpAwer\.env
prisma:tryLoadEnv Environment variables loaded from C:\Users\mathf\Documents\awer\Backend\cursinho\helpAwer\.env
prisma:client dirname C:\Users\mathf\Documents\awer\Backend\cursinho\helpAwer\node_modules\.prisma\client
prisma:client relativePath ..\..\..\prisma
prisma:client cwd C:\Users\mathf\Documents\awer\Backend\cursinho\helpAwer\prisma
prisma:client clientVersion 4.7.1
prisma:client clientEngineType library
prisma:client:libraryEngine internalSetup
prisma:client:libraryEngine:loader Searching for Query Engine Library in C:\Users\mathf\Documents\awer\Backend\cursinho\helpAwer\node_modules\.prisma\client
prisma:client:libraryEngine:loader loadEngine using C:\Users\mathf\Documents\awer\Backend\cursinho\helpAwer\node_modules\.prisma\client\query_engine-windows.dll.node
prisma:client:libraryEngine sending request, this.libraryStarted: false
prisma:client:libraryEngine library starting
prisma:client:libraryEngine library started
```

## Client Snippet
```ts
// PLEASE FILL YOUR CODE SNIPPET HERE
```

## Schema
```prisma
// PLEASE ADD YOUR SCHEMA HERE IF POSSIBLE
```

## Prisma Engine Query
```
{"X":{}}
```

**Comment by jkomyno** [comment] 2023-04-26 09:27
Hi, could you please fill the missing fields of this issue, and add the stacktrace of this panic?
Without those, we're neither able to reproduce this issue nor to understand which line of code in [prisma-engines](https://github.com/prisma/prisma-engines) led to this problem.

Thanks!

**Comment by chouzzy** [comment] 2023-07-13 12:54
Hey guys sorry to bother, the problem was a new attribute i created on my database, it was conflicting with the older documents wich hasn't this new attribute.

I kinda oppened this github topic without noticing it, sorry boudat

**Comment by janpio** [comment] 2023-07-14 18:35
That is actually amazing @chouzzy, as I think we can all agree that our error message there was terrible - but if you could explain to us what exactly you did and optimally how to reproduce this, we would love to improve that error message and avoid this confusion for anyone else doing the same steps as you in the future. We "just" need your help to do so 😆

**Comment by millsp** [comment] 2023-07-27 13:41
Hey @chouzzy, did you get a chance to look at Jan's comment?

**Comment by chouzzy** [comment] 2023-07-27 13:58
Sure! (thanks @millsp for the reminder btw)

The problem was this: 

- I created a document on my MongoDB Atlas database with a few attributes, for example: id, name, address, phoneNumber. That was ok, working fine.

- A few days later, in my local server i added a new attribute on my prisma model, for example: id, name, address, **gender**, phoneNumber. When i tried to POST a new user on my atlas, prisma returned this message, and wasn't clear what i was supposed to do. A few minutes later, i understood that the problem was this conflict on my MongoDB Atlas Document. 

To fix it i just deleted the existing document withoud the new attribute, and worked fine. Another way to fix t would be adding manually the new attribute in the existing documents too.

(i hope i was clear here, i'm from Brasil so my english sucks haha)

**Comment by millsp** [comment] 2023-08-01 22:08
Thanks, that provides a clear way for us to create a reproduction.

**Comment by chouzzy** [comment] 2023-08-03 15:08
@jkomyno can you try the following steps?

- Create a Prisma Schema Model with _id, name and gender. 
- Use Prisma Generate 
- Use prisma.test.create({...}) to create a table in Atlas database with those attributes (id, name and gender)
- Change the Prisma Schema Model adding a new attribute, age for example
- Use Prisma Generate
- And then, in your local server, try to prisma.test.update({}) with your new attribute (age).

I think that should bring the error

If it don't, please let me make a few tests on my new prisma project, i'm creating a new project with it and i'll try to reproduce this bug for you guys

**Comment by jkomyno** [comment] 2023-08-25 09:23
Hey @chouzzy, I'm afraid I still can't reproduce the panic.
However, I could tweak your reproduction steps and trigger an error when I perform a `find*` query before the latest step (i.e., before running `prisma.test.update({})`):

```
Invalid `prisma.test.findFirst()` invocation in
/Users/jkomyno/work/prisma/prisma/reproductions/issue-18924/index.ts:15:38
  12 })
  13 */
  14 
→ 15 const user = await prisma.test.findFirst(
Error converting field "age" of expected non-nullable type "Int", found incompatible value of "null".
 ELIFECYCLE  Test failed. See above for more details.
❯ pnpm generate
```

I've used `prisma@4.7.1`, as you've indicated, but I would also encourage you to try the reproduction steps with `prisma@5.2.0`.

My initial schema was:
```prisma
datasource db {
  provider = "mongodb"
  url      = env("TEST_MONGO_URI")
}

model Test {
  id     String @id @map("_id") @default(cuid())
  name   String
  gender String
}
```

My final schema was:
```prisma
datasource db {
  provider = "mongodb"
  url      = env("TEST_MONGO_URI")
}

model Test {
  id     String @id @map("_id") @default(cuid())
  name   String
  gender String
  age    Int
}
```

**Comment by millsp** [comment] 2023-11-07 16:52
Hey @chouzzy did you get a chance to read @jkomyno's comment?

**Comment by jkomyno** [comment] 2024-02-12 10:26
As we've tried to reach @chouzzy twice without success, we're now closing this issue.
Please leave a comment below with the [required information](https://github.com/prisma/prisma/issues/18924#issuecomment-1693055653) if you see this issue, and we'll reopen it. Thanks!

**Closed by jkomyno** 2024-02-12 10:26 UTC
Labels: bug/0-unknown, kind/bug, topic: windows, topic: error reporting, team/schema, topic: mongodb, topic: unwrap error
