### ISSUE TITLE
`nativeTypes` Preview Feature not Recognized in Generator Block

### ISSUE THREAD

**Issue by Karl-EdwardFPJeanMehu** [prisma/prisma#7363] opened 2021-05-30 21:49 UTC
### Bug description

When trying to use a native database type, an error indicates that the `nativeTypes` feature must first be enabled in the `Datasource` block:

![image](https://user-images.githubusercontent.com/7329138/120120542-e30eee00-c16b-11eb-8578-80fc4dc951d0.png)

 However, at runtime or when migrating, seeding and etc., an error suggests that previewFeatures should only be placed in the `generator` block:

![image](https://user-images.githubusercontent.com/7329138/120119364-57925e80-c165-11eb-904f-4a9c5fa0cd09.png)

Entering the `nativeTypes` feature in the expected `generator block` does not validate any native type fields, like `@db.Uuid`.

### How to reproduce

1. First, try generating the client with the schema as is with. `prisma generate`. You'll get the error mentioned above.
2. Move the ` previewFeatures = ["nativeTypes"]` line to the `datasource block`, you'll notice no error is shown for the native type `@db.Uuid` but will throw an error once you try to do `prisma generate`.

### Expected behavior

It should run and recognize any or all native data types without throwing errors

### Prisma information

```
datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

generator client {
  provider = "prisma-client-js"
  previewFeatures = ["nativeTypes"]
}

model User {
  id    String     @id @db.Uuid @default(dbgenerated("uuid_generate_v4()"))
  email String  @unique
  name  String?
}
```

### Environment & setup

- OS: MacOS
- Database: PostGreSQL
- Node.js version: v14.15.3

### Prisma Version

```
- Prisma: v2.23.0
- Prisma Client: v2.23.0
```

**Comment by janpio** [comment] 2021-05-30 22:57
Something is really weird with your setup. Native types have not been a feature flags for many versions.

Please run `prisma -v` in your project and post the full output here. Also make sure you do not have a global installation that you are using instead. Please also make sure you are using the corresponding VSCode extension version.

**Comment by Karl-EdwardFPJeanMehu** [comment] 2021-05-31 00:50
@janpio I only entered it because it suggested so in VS Code. I have no extensions for Prisma installed and the versions are mentioned above, v2.23.0. I don't have any global versions installed either. I even created a completely new project to test it but got the same results.

**Comment by pantharshit00** [comment] 2021-05-31 07:42
Can you please share output of `prisma -v` please as @janpio. That lists the engine hashes and preview features which will help us here. 

You don't `nativeTypes` flag now so no need to add it. We will investigate what is going on here and why we are not throwing a warning here but you can get unblocked here. 

(Internal note: Probably a consequence of https://github.com/prisma/prisma/pull/6714)

**Comment by Karl-EdwardFPJeanMehu** [comment] 2021-05-31 10:51
Sure, here it is.
![image](https://user-images.githubusercontent.com/7329138/120182546-8992d780-c1dc-11eb-8fd5-7ba92b61bf86.png)

**Comment by janpio** [comment] 2021-05-31 17:00
> only entered it because it suggested so in VS Code. I have no extensions for Prisma installed and the versions are mentioned above, v2.23.0.

Hmm, that would be very weird that you get suggestions in VSCode without the Prisma extension being installed. Can you go back and take a screenshot of what you are seeing?

Your `prisma -v` output looks good indeed. This should not know at all about this preview feature any more.

**Comment by Karl-EdwardFPJeanMehu** [comment] 2021-06-02 19:24
Ok, So I reinstalled VS Code and it seems to be working fine now. I assume it was an outdated Prisma plugin installed via Settings Sync from an other computer.

**Comment by pantharshit00** [comment] 2021-06-03 08:55
Thanks for the info @Karl-EdwardFPJeanMehu 

I am going to close this. I can't reproduce this from the CLI.

**Closed by pantharshit00** 2021-06-03 08:55 UTC
Labels: bug/0-needs-info, kind/bug, team/client, topic: previewFeatures
