### ISSUE TITLE
Docker on RPi 4 fail to run generate command - query-engine-debian-openssl-1.1.x (32bit OS)

### ISSUE THREAD

**Issue by theboxer** [prisma/prisma#3713] opened 2020-09-19 22:35 UTC
## Bug description
I'm trying to deploy a project with prisma2, nexus and graphql to a docker container on my raspberry pi 4. The node server crashes with an error: `You most likely forgot to initialize the Prisma Client. Please run `prisma generate` and try to run it again. If that does not solve your problem, please open an issue.`

If I run `yarn prisma generate` I receive a following error:
```
Get config /app/node_modules/@prisma/cli/query-engine-debian-openssl-1.1.x: 1: /app/node_modules/@prisma/cli/query-engine-debian-openssl-1.1.x: Syntax error: "(" unexpected
```

Any input is appreciated, thank you.

## Dockerfile
```
FROM node:latest

RUN apt-get update && apt-get install --no-install-recommends --yes openssl

WORKDIR /app

COPY ./package.json .
COPY ./yarn.lock .

RUN yarn install

COPY . .

EXPOSE 4444

CMD yarn dev
```

## Project dependencies
```
"dependencies": {
    "@nexus/schema": "^0.15.0",
    "@types/express": "^4.17.8",
    "@types/node": "^12.12.56",
    "apollo-server-express": "^2.17.0",
    "cookie-parser": "^1.4.5",
    "cross-env": "^7.0.2",
    "express": "^4.17.1",
    "graphql": "^14.7.0",
    "graphql-middleware": "^4.0.2",
    "graphql-shield": "^7.3.6",
    "jsonwebtoken": "^8.5.1",
    "nexus": "^0.26.1",
    "nexus-plugin-prisma": "^0.19.0",
    "ts-node": "^9.0.0",
    "typescript": "^4.0.2"
  },
  "devDependencies": {
    "ts-node-dev": "^1.0.0-pre.62"
  }
```

**Comment by pantharshit00** [comment] 2020-09-22 05:03
Can you please share the schema that you are using? We haven't actually never received a report of that RPC failing failing but might be related to a syntax error. 


I don't have a raspberry pi 4 in hand so I can't test this. I will ask my coworkers after I have verified that the schema is fine.

**Comment by theboxer** [comment] 2020-09-22 06:10
@pantharshit00 here's the schema:

```
datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

generator client {
  provider = "prisma-client-js"
}

enum Role {
    USER
    ADMIN
}

model User {
    id              String      @id @default(uuid())
    username        String      @unique
    password        String
    role            Role        @default(USER)
}

model Movie {
    id              String      @id @default(uuid())
    scId            String      @unique
    name            String
    year            Int
    poster          String
    imdb            String
    csfd            Int
    kodiId          Int
}

model TvShow {
    id              String      @id @default(uuid())
}
```

btw. running `prisma generate` on my notebook (mac os) works fine.

**Comment by pantharshit00** [comment] 2020-09-22 13:39
The model looks fine, now I will need to test it on a RPi4 somehow.

**Comment by theboxer** [comment] 2020-09-22 13:45
@pantharshit00 ok, thank you. I can try and look how to make the rpi, I have, accessible from the internet. If I manage to do that, I can send you ssh credentials.

**Comment by pantharshit00** [comment] 2020-09-22 13:48
@theboxer No need for that, we will figure this out. Thanks for reporting!

**Comment by pantharshit00** [comment] 2020-09-22 14:33
But please note that this would be a bit of low priority for us right now with no timeline. We would love to fix this but we also need to prioritise other important things first.

**Comment by theboxer** [comment] 2020-09-22 14:46
That's a nice devotion
> I am ordering a Raspberry Pi 4

Thank you

**Comment by pantharshit00** [comment] 2020-09-22 15:26
Can you please also tell me which OS you are running on your Raspberry Pi? I will assume Raspberian but still please confirm.

**Comment by theboxer** [comment] 2020-09-22 15:31
Yup, raspbian, more specifically:
```
PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
NAME="Raspbian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=raspbian
ID_LIKE=debian
```

**Comment by pantharshit00** [comment] 2020-10-01 06:40
![2020-10-01_12-00](https://user-images.githubusercontent.com/22195362/94776228-f734fc80-03de-11eb-9cdd-5566fa579141.png)

I can reproduce this issue as well. I think this is being caused as raspbian is a 32bit operating system and we build the ubuntu binary for a 64bit ubuntu system. I am not sure if we want to support this.

**Comment by radicand** [comment] 2020-10-03 19:02
If this is running on an RPi, keep in mind that's ARM architecture which I don't believe binaries are supplied for yet. There are notes in #861 regarding building your own binaries in the interim.

**Comment by brielov** [comment] 2020-12-05 20:10
Excuse my ignorance, why is it so hard to provide pre-built binaries for ARM if the prisma engine is written in rust and rust compiles everywhere?

**Comment by mavilein** [comment] 2020-12-07 13:02
We are currently working on providing binaries for ARM. The reason this is not trivial is because the build process has to be integrated into our CI system. Our CI currently runs on x86 machines. In order to integrate we started to look into cross compiling. Support in Rust is good here but we also needed OpenSSL compiled for ARM to link against at build time. This was quite some work but we are nearing the finish line :-)

**Comment by brielov** [comment] 2020-12-07 14:16
@mavilein Thank you so much for clarifying!

**Comment by n1ru4l** [comment] 2020-12-10 11:17
You probably already know but it is easily possible to compile arm on any platform with socker buildx (qemu)

**Comment by kilrau** [comment] 2020-12-18 08:18
> We are currently working on providing binaries for ARM. The reason this is not trivial is because the build process has to be integrated into our CI system. Our CI currently runs on x86 machines. In order to integrate we started to look into cross compiling. Support in Rust is good here but we also needed OpenSSL compiled for ARM to link against at build time. This was quite some work but we are nearing the finish line :-)

Many thanks for taking this on. Any ~ETA when we can expect this to be available? Doesn't have to be stable, just "usable" :)

**Comment by pantharshit00** [comment] 2020-12-21 10:22
@kilrau ARM `aarch64` ( I think which is basically `arm64`, different names by different vendors) binaries are available in the dev channel right now if you are interested. 

Install the dev channel like so `npm install @prisma/cli@dev @prisma/client@dev`

**Comment by JanuaryLimes** [comment] 2021-04-27 13:34
@pantharshit00 what about ARMv7 (32bit) are those binaries also available?

**Comment by pantharshit00** [comment] 2021-05-19 10:17
Hello everyone here

At the current moment, we are not adding 32bit target in the official release pipeline. 

But for Pi and ARMv7, I have put together this repository which has precompiled 32 bit engines for these platforms and you can use prisma via this in the meantime: https://github.com/pantharshit00/prisma-rpi-builds

This will build the engine on every stable release.

**Comment by roeniss** [comment] 2021-07-22 12:42
@pantharshit00 you saved me. with your binaries I successfully build my docker image which do `prisma generate` during build. Thank you so much.

**Comment by janpio** [comment] 2024-01-30 19:10
I am closing this now, as there are no further plans to provide 32bit engine files, sorry.

**Closed by janpio** 2024-01-30 19:10 UTC
Labels: kind/feature, topic: prisma generate, team/client, topic: arm
