### ISSUE TITLE
Support .env.development

### ISSUE THREAD

**Issue by tsongas** [prisma/prisma#10219] opened 2021-11-11 19:36 UTC
## Problem

Because I have `.env.development` and `.env.test` files I have to create the following scripts for running `prisma` commands:

```
    "migrate:dev": "dotenv -e .env.development -- npx prisma migrate dev",
    "seed": "dotenv -e .env.development -- npx prisma db seed",
```

## Suggested solution

Could Prisma look for environment variables in `.env.development` if there is no `.env` file?

## Alternatives

I suppose I might be able to put my development environment variables in `.env` and test variables in `.env.test` but I want to avoid accidentally running tests against my development database.

**Comment by pantharshit00** [comment] 2021-11-12 14:15
Hi,

Thanks for reporting this! It has already been reported before, so I am going to close this as a duplicate of https://github.com/prisma/prisma/issues/3865

**Closed by pantharshit00** 2021-11-12 14:15 UTC
