### ISSUE TITLE
Feature request: JetBrains plugin (for WebStorm, PhpStorm, ...)

### ISSUE THREAD

**Issue by nickreynke** [prisma/prisma#2023] opened 2020-03-31 18:03 UTC
## Problem

Schema files (ending in `.prisma`) can be edited but neither the syntax is highlighted, nor there is any kind of code re-formatting on demand, code completion or error highlighting.

## Solution

A plugin that consists of the following:

* Syntax highlighting
* Code formatting
* Code completion for types, enums and so on
* Error highlighting

## Alternatives

Manual code formatting and checking if everything is alright.

## Additional context

None.

**Comment by pantharshit00** [comment] 2020-03-31 18:11
Hi,

Thanks for reporting this! It has already been reported before, so I am going to close this as a duplicate of https://github.com/prisma/prisma/issues/1788

**Closed by pantharshit00** 2020-03-31 18:11 UTC
