### ISSUE TITLE
an issue when running db pull 

### ISSUE THREAD

**Issue by vinstah** [prisma/prisma#21978] opened 2023-11-15 21:49 UTC
Hi Prisma Team! The following command just crashed.

## Command

`db pull`

## Versions
      
| Name        | Version            |
|-------------|--------------------|
| Platform    | darwin             | 
| Node        | v18.18.2           | 
| Prisma CLI  | 5.3.1              | 
| Engine      | 61e140623197a131c2a6189271ffee05a7aa9a59| 

## Error
```
RustPanic: Error in Schema engine.
Reason: [schema-engine/connectors/sql-schema-connector/src/introspection/introspection_pair/default.rs:71:22] called `Option::unwrap()` on a `None` value

```

**Comment by Weakky** [comment] 2023-11-17 16:06
Hey @vinstah,

Would you perhaps have some more information for us so that we can reproduce your issue? Your datamodel and database used would be useful for instance.

Thank you!

**Comment by Nanlung** [comment] 2023-12-11 00:07
Hi @vinstah I have the same issue. i used the example schema from the prisma official documentation.

**Comment by Jolg42** [comment] 2024-03-06 12:38
@vinstah @Nanlung did you manage to use `db pull` in the end?
Did you try with a newer version of Prisma maybe? (`5.10.2` is the latest as of today)

I'm also curious what's the database and its version you tried to introspect. Because at the moment we don't have enough information to try a reproduction, that will first be needed before we can fix this.

**Comment by SevInf** [comment] 2024-03-18 09:13
Hey @vinstah @Nanlung ,
 

With the lack of information and our inability to reproduce this issue, we're now closing it. Feel free to comment if you have any updates about it.
 
Thank you 🙏

**Closed by SevInf** 2024-03-18 09:13 UTC
Labels: bug/0-unknown, kind/bug, tech/engines/introspection engine, team/schema, topic: prisma db pull
