### ISSUE TITLE
PANIC in query-engine\core\src\query_graph_builder\read\utils.rs:52:85called `Result::unwrap()` on an `Err` value: FieldNotFound { name: "_count", model: "User" }

### ISSUE THREAD

**Issue by naveenrobo** [prisma/prisma#7345] opened 2021-05-29 10:26 UTC
Hi Prisma Team! My Prisma Client just crashed. This is the report:
## Versions

| Name            | Version            |
|-----------------|--------------------|
| Node            | v14.16.0           | 
| OS              | windows            |
| Prisma Client   | 2.22.1             |
| Query Engine    | query-engine 60cc71d884972ab4e897f0277c4b84383dddaf6c|
| Database        | Postgres|

## Query
```
query {
  findFirstLiveStream(where: {
    AND: [
      {
        OR: [
          {
            id: "X"
          },
          {
            path: "X"
          },
          {
            room_id: "X"
          }
        ]
      }
    ]
  }) {
    id
    name
    description
    created_user_id
    room_id
    started
    start_time
    end_time
    ended
    type
    preview
    need_record
    record_url
    path
    created_at
    updated_at
    created_by {
      first_name
      avatar
      _count {
        likes
      }
    }
  }
}
```

## Logs
```
:client clientVersion: 2.22.1  +2s
  prisma:tryLoadEnv Environment variables loaded from D:\Projects\BeamBox\beambox-backend\.env  
  prisma:client clientVersion: 2.22.1  
  prisma:engine Search for Query Engine in D:\Projects\BeamBox\beambox-backend\node_modules\.prisma\client  
  prisma:engine Search for Query Engine in D:\Projects\BeamBox\beambox-backend\node_modules\.prisma\client  
  prisma:engine Search for Query Engine in D:\Projects\BeamBox\beambox-backend\node_modules\.prisma\client  
  prisma:engine Search for Query Engine in D:\Projects\BeamBox\beambox-backend\node_modules\.prisma\client  
  prisma:engine Search for Query Engine in D:\Projects\BeamBox\beambox-backend\node_modules\.prisma\client  
  prisma:engine Search for Query Engine in D:\Projects\BeamBox\beambox-backend\node_modules\.prisma\client  
  prisma:engine Search for Query Engine in D:\Projects\BeamBox\beambox-backend\node_modules\.prisma\client  
  prisma:engine Search for Query Engine in D:\Projects\BeamBox\beambox-backend\node_modules\.prisma\client  
  prisma:engine Search for Query Engine in D:\Projects\BeamBox\beambox-backend\node_modules\.prisma\client  
  prisma:engine Search for Query Engine in D:\Projects\BeamBox\beambox-backend\node_modules\.prisma\client  
  prisma:engine Search for Query Engine in D:\Projects\BeamBox\beambox-backend\node_modules\.prisma\client  
  prisma:engine { cwd: 'D:\\Projects\\BeamBox\\beambox-backend\\prisma' }  +37s
  prisma:engine Search for Query Engine in D:\Projects\BeamBox\beambox-backend\node_modules\.prisma\client  
  prisma:engine { flags: [ '--enable-raw-queries', '--port', '50734' ] }  
  prisma:engine stdout  Starting a postgresql pool with 13 connections.  
  prisma:engine stdout  Started http server on http://127.0.0.1:50734  
  prisma:engine Search for Query Engine in D:\Projects\BeamBox\beambox-backend\node_modules\.prisma\client  
  prisma:engine stdout  PANIC in query-engine\core\src\query_graph_builder\read\utils.rs:52:85
called `Result::unwrap()` on an `Err` value: FieldNotFound { name: "_count", model: "User" }  
  prisma:engine {
  prisma:engine   error: Error: read ECONNRESET
  prisma:engine       at TCP.onStreamRead (internal/stream_base_commons.js:209:20) {
  prisma:engine     errno: -4077,
  prisma:engine     code: 'ECONNRESET',
  prisma:engine     syscall: 'read'
  prisma:engine   }
  prisma:engine }  
  prisma:engine {
  prisma:engine   error: Error: connect ECONNREFUSED 127.0.0.1:50734
  prisma:engine       at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1146:16) {
  prisma:engine     errno: -4078,
  prisma:engine     code: 'ECONNREFUSED',
  prisma:engine     syscall: 'connect',
  prisma:engine     address: '127.0.0.1',
  prisma:engine     port: 50734
  prisma:engine   }
  prisma:engine }  
  prisma:engine There is a child that still runs and we want to start again  
  prisma:engine { cwd: 'D:\\Projects\\BeamBox\\beambox-backend\\prisma' }  
  prisma:engine Search for Query Engine in D:\Projects\BeamBox\beambox-backend\node_modules\.prisma\client  
  prisma:engine Client Version: 2.22.1  
  prisma:engine Engine Version: query-engine 60cc71d884972ab4e897f0277c4b84383dddaf6c  
  prisma:engine Active provider: postgresql  
  prisma:engine { flags: [ '--enable-raw-queries', '--port', '50738' ] }  
  prisma:engine stdout  Starting a postgresql pool with 13 connections.  
  prisma:engine stdout  Started http server on http://127.0.0.1:50738  
  prisma:engine Search for Query Engine in D:\Projects\BeamBox\beambox-backend\node_modules\.prisma\client  
  prisma:engine stdout  PANIC in query-engine\core\src\query_graph_builder\read\utils.rs:52:85
called `Result::unwrap()` on an `Err` value: FieldNotFound { name: "_count", model: "User" }  
  prisma:engine {
  prisma:engine   error: Error: read ECONNRESET
  prisma:engine       at TCP.onStreamRead (internal/stream_base_commons.js:209:20) {
  prisma:engine     errno: -4077,
  prisma:engine     code: 'ECONNRESET',
  prisma:engine     syscall: 'read'
  prisma:engine   }
  prisma:engine }  
```

## Client Snippet
```ts
 let liveStream = await prisma.liveStream.findFirst({
      where: {
        AND: [
          {
            OR: [
              {
                id: id,
              },
              {
                path: id,
              },
              {
                room_id: id,
              },
            ],
          },
        ],
      },
      include: {
        created_by: {
          select: {
            first_name: true,
            avatar: true,
            _count: {
              select: {
                likes: true,
              },
            },
          },
        },
      },
    });```

**Comment by pantharshit00** [comment] 2021-05-29 12:31
Hi,

Thanks for reporting this! It has already been reported before, so I am going to close this as a duplicate of https://github.com/prisma/prisma/issues/6543

**Closed by pantharshit00** 2021-05-29 12:31 UTC
