### ISSUE TITLE
Add the ability to make a model or attributes read-only

### ISSUE THREAD

**Issue by conor** [prisma/prisma#9532] opened 2021-09-30 13:13 UTC
## Problem

I have specific models that I would like to expose read-only access to, but I don't think Prisma has a way of marking a model or even attributes as read-only.

[Slack discussion](https://prisma.slack.com/archives/CA491RJH0/p1633005891101600)

## Suggested solution

Something similar to how [ActiveRecords does it with the read_only? method](https://apidock.com/rails/ActiveRecord/Base/readonly%3F). With Prisma maybe you could possibly use something like a `@readOnly` annotation.

## Alternatives

I haven't tried to work around it yet.

**Comment by pantharshit00** [comment] 2021-09-30 13:15
Hi,

Thanks for reporting this! It has already been reported before, so I am going to close this as a duplicate of https://github.com/prisma/prisma/issues/3401

**Closed by pantharshit00** 2021-09-30 13:15 UTC

**Comment by conor** [comment] 2021-09-30 13:16
@pantharshit00 👍🏻
