### ISSUE TITLE
Respect `.env` from yarn workspace root

### ISSUE THREAD

**Issue by PhilippMolitor** [prisma/prisma#4798] opened 2020-12-27 12:27 UTC
## Problem

Imagine the following project structure:
```
+ my-project
  - package.json -- the yarn workspace project
  - .env -- this file has all my settings, but is not loaded by prisma
  + packages
    + backend
      - package.json
      - .env -- this env file is also respected by prisma
      + prisma
        - prisma.schema
        - .env -- the env file that is loaded
    - frontend
```

The `.env` inside my yarn workspace root is not loaded, even though it is inside *my* project root.

## Suggested solution

Make the `.env` loading more modular. Features I would really love to use:

- Be able to set a path for my `.env` (maybe even with glob support!) file inside the `prisma.schema`. This way I can adapt to any requirements.
  ```prisma
  datasource db {
    provider = "postgresql"
    env    = glob("../../../.env.*")
    url      = env("DATABASE_URL")
  }
  ```
- I use different variables for database host, user, password and database name for various reasons. Being able to concatenate variables when defining my database url inside the `prisma.schema` file would help a lot with flexibility:
  ```prisma
  datasource db {
    provider = "postgresql"
    url      = interpolateEnv("postgresql://${DATABASE_USER}:${DATABASE_PASSWORD}@${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}")
  }
  ```

**Comment by matthewmueller** [comment] 2021-01-12 08:23
Thanks for the issue. I can definitely see how in a multi-package setup like that you'd expect the .env to be at the root of all the packages. You could simulate this if you had one package.json at that level too. I'm guessing yarn workspaces doesn't like that though :-)

In your suggestion:

```prisma
datasource db {
  provider = "postgresql"
  env    = glob("../../../.env.*")
  url      = env("DATABASE_URL")
}
```

Typically people have one .env for development, one for production. How would you switch based on environment?

**Comment by leemason** [comment] 2021-01-28 21:13
"sort of" related but im just coming to prisma and first of all, this package is awesome, really liking where its going.

The biggest thing that bugs me though is is that prisma has an extremely complicated env requirement/setup. Im not really sure why a database package has taken on environment capturing as well. Especially as there are numerous tools to deal with env (cross-env, dotenv, dotenv-load, process.env, export ***=, and of course the numerous hosting setups).

All of these tools are either just there by design, or a quick npm install away. Wouldn't a well written guide on exposing env vars be much better than trying to cover all of the gotchas with the current setup?

My latest issue is that prisma isnt a first class dependency to the main project. The userland package requires an "app" package which is where the schema is defined and generated. On top of that this is all in a mono repo with workspaces, although i dont think this complicates the issue (it certainly does for other env reported issues).

Because prisma tries very hard to produce its own env loading, ive got a bit of weird setup where i load my own env (as an .env file is used for more than just prisma) and possibly have env related warnings because when not developing the "app" package there wont be an env file there.

It seems to me all of these issues go away should primsa just respect the current process env variables.

I think its safe to assume everyone generating prisma schemas understands the concept of env variables.

**Comment by jkomyno** [comment] 2024-12-13 09:45
Hi there,

As part of our effort to clean up our GitHub repo, we’re closing this issue to help focus on features and improvements that align with our focus areas and those of our community. 

If this is issue is still important to you, feel free to reopen the issue and get like-minded users to upvote as we will prioritize fixing issues based on community interest. If you do reopen the issue, please ensure that there’s a clear method for us to reproduce it. 

For more insight into our priorities and how we’re thinking about the future of the Prisma ORM, please see our recent blog post: https://www.prisma.io/blog/prisma-orm-manifesto.

Thank you for your understanding and support!

**Closed by jkomyno** 2024-12-13 09:45 UTC
Labels: kind/improvement, topic: env, topic: yarn workspaces, domain/client, topic: .env
