### ISSUE TITLE
Filter where value is NULL does not work

### ISSUE THREAD

**Issue by metadiego** [prisma/prisma#14175] opened 2022-07-06 17:53 UTC
### Bug description

When performing a nested read of a table, and filtering for all values that are null on the right hand side of the relation, the prisma output query seems wrong (or maybe I'm missing something).

Not only is the prisma query wrong, but the result is an empty array although I have verified that there are rows which match my filter criteria, so the output should not be an empty array.

### How to reproduce

**Models:**

```
  model AccountMetadata {
    publicKey            String    @id
    ...
    data AggregateOverviewByHolderAndCollection[]
  }
  
  model AggregateOverviewByHolderAndCollection {
    holder              String
    ....
    accountMetadata   AccountMetadata? @relation(fields: [holder], references: [publicKey])
    
    @@id([holder, collectionId])
  }
```

**Query:**

```
    const results =
      await prismaClient.aggregateOverviewByHolderAndCollection.findMany({
        select: {
          holder: true,
          accountMetadata: true,
        },
        where: {
          collectionId: { in: collectionIds },
          accountMetadata: { is: null },
        }
      });
```

### Expected behavior

Prisma query (from debug logs):
```
`prisma:query SELECT `crm`.`AggregateOverviewByHolderAndCollection`.`holder`, `crm`.`AggregateOverviewByHolderAndCollection`.`collectionId` FROM `crm`.`AggregateOverviewByHolderAndCollection` WHERE (`crm`.`AggregateOverviewByHolderAndCollection`.`collectionId` IN (?,?) AND `crm`.`AggregateOverviewByHolderAndCollection`.`holder` IS NULL)`
```

The issue I see is: `crm`.`AggregateOverviewByHolderAndCollection`.`holder` IS NULL.

But my filter is where accountMetadata IS NULL.

Even if this is intended, the output of the query is an empty array, even though I have verified that it should not be because there are instances where accountMetadata is NULL.

### Environment & setup

- OS: MacOS
- Database:  MySQL
- Node.js version: v16.13.0

### Prisma Version

```
3.14.0

```

**Comment by SevInf** [comment] 2022-09-05 10:55
@metadiego Thank you for the report.
`accountMetadata` is not a real field that exists in a database, this is a relation done through `holder` field, meaning that for each `AggregateOverviewByHolderAndCollection.holder` it will try to query corresponding `AcountMetadata` where `holder = accountMetadata.publicKey`. In that sense, generated query makes sense to me: `accountMetadata` is  null, when holder is null. 

>Even if this is intended, the output of the query is an empty array, even though I have verified that it should not be because there are instances where accountMetadata is NULL.

I could not verify this, since in provided schema `holder` is mandatory, can not be optional due to being a part of compound id and default referential actions settings prevent removing `accountMetadata` entries when there are `AggregateOverviewByHolderAndCollection`  referencing them. Could you share a code snippet, which shows how those entries are created?

**Comment by janpio** [comment] 2022-09-23 16:10
Ping @metadiego, can you help us out here please? We would love to be able to reproduce, but need additional information before attempting this again. Without that we will have to close this issue as unreproducible unforunately. Thanks!

**Comment by janpio** [comment] 2022-11-25 00:14
Closing then until someone provides more information. Please comment or open a new issue. Thanks!

**Closed by janpio** 2022-11-25 00:14 UTC
Labels: bug/0-unknown, kind/bug, topic: broken query, topic: filter, topic: mysql, team/client
