### ISSUE TITLE
Response time of prisma with mongodb hosted on GCP is very slow compared to mongoose

### ISSUE THREAD

**Issue by ArgekarStudios** [prisma/prisma#15148] opened 2022-09-02 02:31 UTC
### Bug description

Mongo with mongoose on GCP(nestjs) :- 200ms
Mongo with Prisma on GCP(nestjs):-1345ms

This is the main reason for not using prisma

### Expected behavior

It should be fast

### Prisma information

prisma with monogb
with atlas

### Environment & setup

- OS: 
- Database: 
- Node.js version: 

### Prisma Version

latest

**Comment by annibuliful** [comment] 2022-09-02 07:35
I think Prisma team need more time to research and build it to be more compatible with MongoDB

Refs:
https://engineering.hashnode.com/how-did-we-choose-our-next-tech-stack-at-hashnode#heading-prisma

**Comment by garrensmith** [comment] 2022-09-27 11:03
@ArgekarStudios could you supply your schema and the query you are doing. That would help us find out why this is so slow.

**Comment by kibertoad** [comment] 2022-09-30 10:16
@ArgekarStudios could you please provide a reproduction? it is not possible to fix "something is slow, please fix" problem

**Comment by janpio** [comment] 2023-09-07 12:55
Ping @ArgekarStudios - with no additional information we can only close this issue without getting the chance to improve anything.

**Comment by janpio** [comment] 2023-10-29 21:18
One last time @ArgekarStudios, can you help us with more information? Right now we don't know what to do here.

**Comment by millsp** [comment] 2023-11-07 16:57
Without your input, we could not reproduce this issue, I am therefore closing it. Please don't hesitate to ping us if you have more information to provide in the future and we will re-open this issue. Thanks.

**Closed by millsp** 2023-11-07 16:57 UTC
Labels: bug/0-unknown, kind/bug, topic: performance, team/client, topic: mongodb
