### ISSUE TITLE
Provider <-> connection string mismatch leads to strange error message

### ISSUE THREAD

**Issue by janpio** [prisma/prisma#2749] opened 2020-06-14 20:20 UTC
```prisma
generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "mysql"
  url      = env("DATABASE_URL")
}
```

```
DATABASE_URL="postgresql://foo:bar@host:sdfsdf/chinook"
```

When running `prisma introspect` I get this error message:

```
C:\Users\Jan\Documents\prisma-chinook-express>npx prisma introspect
Environment variables loaded from ./prisma/.env

Introspecting based on datasource defined in prisma\schema.prisma …
Error: Error in datamodel: ErrorCollection { errors: [SourceValidationError { message: "The URL for datasource `db` must start with the protocol `mysql://`.", source: "db", span: Span { start: 104, end: 123 } }] }
```

![image](https://user-images.githubusercontent.com/183673/84603250-41748b00-ae8d-11ea-9fdc-741efe249798.png)

**Comment by pantharshit00** [comment] 2020-06-17 11:55
<img width="1434" alt="image" src="https://user-images.githubusercontent.com/22195362/84895086-736d3380-b0bf-11ea-9b0d-0bf07d034785.png">

I can confirm this, migrate and introspect throws different error though.

**Comment by Jolg42** [comment] 2020-08-05 09:31
Closing as duplicate of https://github.com/prisma/migrate/issues/528

**Closed by Jolg42** 2020-08-05 09:31 UTC
Labels: bug/2-confirmed, kind/bug, topic: cli-introspect, topic: cli-migrate
