### ISSUE TITLE
Prisma crash in nested_read:97

### ISSUE THREAD

**Issue by dickfickling** [prisma/prisma#12435] opened 2022-03-19 20:39 UTC
Hi Prisma Team! My Prisma Client just crashed. This is the report:
## Versions

| Name            | Version            |
|-----------------|--------------------|
| Node            | v16.14.0           | 
| OS              | debian-openssl-1.1.x|
| Prisma Client   | 3.10.0             |
| Query Engine    | 0.1.0              |
| Database        | postgresql         |

## Logs
```
aryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine requestBatch
prisma:client:libraryEngine requestBatch
prisma:client:libraryEngine requestBatch
prisma:client:libraryEngine requestBatch
prisma:client:libraryEngine requestBatch
prisma:client:libraryEngine requestBatch
prisma:client:libraryEngine requestBatch
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:
```

the logs aren't exactly helpful, lol. Happy to send whatever else you need. This seems to be happening somewhat randomly in production. It's happened twice now. Not sure what's triggering it. We restart our API and things go on their way for a day or two, and then more crashes. I'm going to upgrade to prisma 3.11 now in case that fixes it

**Comment by janpio** [comment] 2022-03-21 19:49
Can you share the full error message?
Is it always the same query maybe?

**Comment by Weakky** [comment] 2022-06-21 13:00
Hey,

Since this issue has not seen any activity for the last 3 months, we'll close it now.

If you ever encounter this issue again or if you have any insights that could help us reproduce this issue, please let us know and re-open this issue.

Thanks for reporting 🙏

**Closed by Weakky** 2022-06-21 13:00 UTC
Labels: bug/0-unknown, kind/bug, team/client, topic: basic error report, priority/high, size/unknown
