### ISSUE TITLE
Using `env(VAR)` for custom generators results in `'(function)'` string being used.

### ISSUE THREAD

**Issue by arthurfiorette** [prisma/prisma#19065] opened 2023-05-04 00:54 UTC
### Bug description

When using a custom generator, we cannot use the function `env()` to any other property other than the `url` inside datasource. Any other usage of it results in the string `(function)` in its place.

_Context: https://github.com/arthurfiorette/prisma-json-types-generator/issues/60_

### How to reproduce

```prisma
// schema.prisma

generator test {
  name = "..."
  shouldComeFromEnv = env("VALUE")
}
```

```js
// generator.js

generatorHandler({
  onGenerate(options) {
    console.log(options.generator.config.shouldComeFromEnv) // prints '(function)'
  }
});
```

Will print the string `(function)` and not any useful information to enable the generator get the value from env.

### Expected behavior

To use any meaningful information about the function, like `{ fromEnvVar: null, value: '' }` on `provider` or `output`.

Prisma automatically reading the environment value would be a even better non-breaking change way.

### Prisma information

```prisma
// schema.prisma

generator test {
  name = "..."
  shouldComeFromEnv = env(VALUE)
}
```

### Environment & setup

"@prisma/client": "^4.10.1",
"prisma": "^4.10.1",
"node": ">=14.0"
"@prisma/generator-helper": "^4.10.1",

### Prisma Version

```
4.10.1
```

**Comment by janpio** [comment] 2023-05-06 01:12
Is this effectively a duplicate of https://github.com/prisma/prisma/issues/8990?

**Comment by arthurfiorette** [comment] 2023-05-06 02:51
Yes, sorry I couldn't found it :)

**Closed** 2023-05-06 02:51 UTC
Labels: kind/bug, topic: env, team/schema, team/client
