### ISSUE TITLE
Prisma Studio UI issue

### ISSUE THREAD

**Issue by clovellbsc** [prisma/prisma#25172] opened 2024-09-05 09:11 UTC
### Bug description

If there is an error when adding data to the db or deleting from the db when using prisma studio it opens a modal that doesn't have click outside to close functionality and does not have max height or overflow scroll therefore there is no way to close the modal or see the relevant information due the error message extending beyond the screen height. Currently having to refresh to the page to be able to actually use prisma studio again

![Screenshot 2024-09-05 at 09 55 08](https://github.com/user-attachments/assets/5489241a-9798-4749-9562-33705c2eec0a)

### Expected behavior

I'd expect to be able to close the modal and for the entirety of the modal error message to be readable.

### Prisma information

N/A as this was an issue with prisma studio frontend

### Environment & setup

- OS: macOS
- Database: MySQL
- Browser: Chrome

### Prisma Version

```
5.17.0
```

**Comment by jkomyno** [comment] 2024-12-30 15:40
Closing as a duplicate of https://github.com/prisma/prisma/issues/22492.

**Closed by jkomyno** 2024-12-30 15:40 UTC
Labels: bug/1-unconfirmed, kind/bug, topic: studio, domain/pdp
