### ISSUE TITLE
$transaction performance issue within Docker

### ISSUE THREAD

**Issue by veedchi** [prisma/prisma#9846] opened 2021-10-19 13:24 UTC
### Bug description

When running a service inside docker, the API call using `$transaction` kills the docker image by ramping up the CPU usage to 100%.

### How to reproduce

1. create a node server with an API using `prisma.$transaction`
2. run the server locally, and run the server within docker
3. test concurrent requests using script 
```
curl -X GET "http://localhost:{port}/api/v1/endpoint"
ab -k -c 20 -n 250 "http://localhost:{port}/api/v1/endpoint"
```

### Expected behavior

Server without docker runs fine where docker one crashes.

### Environment & setup

- OS: Mac OS
- Database: Postgres
- Node.js version: v14.17
- Docker version: v20.10
- Docker base image: node:14-alpine

### Prisma Version

```
3.2.1
```

**Comment by jgoux** [comment] 2021-10-29 20:34
It's maybe linked to https://github.com/prisma/prisma/issues/9584

**Comment by sjaakiejj** [comment] 2021-11-03 05:38
> It's maybe linked to #9584

Maybe - but the issue described here doesn't happen on Prisma 2.29 for us, it only started coming up after we upgraded to Prisma 3.x. Basically if we're using $transaction, it'll work a few times but after a few requests, CPU usage will shoot up to 100% and never goes back down. This doesn't happen when running on Mac, only when running it in a Docker / Linux environment. I'd expect it to be related to the Linux or Alpine drivers.

**Comment by janpio** [comment] 2021-11-08 18:41
Can you create a small reproduction project and put it on GH so we can reproduce this? Thanks.

**Comment by sjaakiejj** [comment] 2021-11-10 12:28
Hi @janpio ,

I've created a small reproduction project: https://github.com/sjaakiejj/prisma-transaction-bug
Whilst creating this project, I discovered the issue only appears when `interactiveTransactions` are included as a preview feature. Let me know if you have any issues setting this up or reproducing it yourself.

**Comment by richardwu** [comment] 2021-11-21 22:09
> Hi @janpio ,
> 
> I've created a small reproduction project: https://github.com/sjaakiejj/prisma-transaction-bug Whilst creating this project, I discovered the issue only appears when `interactiveTransactions` are included as a preview feature. Let me know if you have any issues setting this up or reproducing it yourself.

Just ran into this in prod: I can second that this does seem to be due to interactive transactions (switching to non-interactive transactions does not spike CPU usage to 100% after stress testing it).

**Comment by millsp** [comment] 2022-02-04 10:20
Hey, this issue has been fixed via https://github.com/prisma/prisma-engines/pull/2619. We've added a stress test (which reproduces the deadlock issue) to make sure we don't run into this again. Feel free to re-open or ping me if needed.

**Closed by millsp** 2022-02-04 10:20 UTC
Labels: bug/1-unconfirmed, kind/bug, team/client, topic: docker, topic: interactiveTransactions
