### ISSUE TITLE
QueryRaw - Not working for StoredProcedures in Linux

### ISSUE THREAD

**Issue by nicosampler** [prisma/prisma#2930] opened 2020-07-03 12:29 UTC
I'm facing a weird problem, it seems to be specific to Linux.

Calling `queryRaw` with a stored procedure takes a lot of time to respond and seems to be failing due to some timeout. (all the times).

In Windows it works perfectly. But in Linux does not, we have tested it locally and also deployed in a server running Linux.

Running `queryRaw` with a function, worked just as expected in Linux, so the problems seem to be only with Stored Procedure calls. 

- OS: Ubuntu 18.04.4 LTS
- Database: MySQL
- Prisma version: 2.1.3
- Node.js version: 12.6.2

**Comment by pantharshit00** [comment] 2020-07-03 13:33
Can you please share code of your stored procedure? Also, maybe your database schema as well

**Comment by nicosampler** [comment] 2020-07-03 13:39
@pantharshit00 

```
CREATE DEFINER=`some-user`@`%` PROCEDURE `testNico`()
BEGIN
	select "a value";
END
```
```
try{
  const rawQuery = `call testNico`;
  const response = await ctx.prisma.queryRaw(rawQuery);
  console.log("RESPONSE: ", response)
} catch (error) {
  console.log(error)
}
``` 

This does not work, even the `catch` is not executed.

**Comment by pantharshit00** [comment] 2020-07-07 21:55
I am unable to reproduce this:
![image](https://user-images.githubusercontent.com/22195362/86847780-85dcfa80-c0ca-11ea-8a41-edd6654c6509.png)


I used version `2.3.0-dev.2`, can you please also try with that version and see if this works for you?

**Comment by pantharshit00** [comment] 2020-07-07 21:55
Ok, wait I will also test this out on Linux. This test was done on Mac.

**Comment by nicosampler** [comment] 2020-07-15 16:19
@pantharshit00 have you had a chance to take a look at this one?

**Comment by pantharshit00** [comment] 2020-07-15 16:47
I am still unable to reproduce this. I used a vm in cloud with following config:
```

  System:
    OS: Linux 4.15 Ubuntu 18.04.4 LTS (Bionic Beaver)
    CPU: (1) x64 Intel(R) Xeon(R) CPU E5-2650 v4 @ 2.20GHz
    Memory: 240.33 MB / 985.52 MB
    Container: Yes
    Shell: 4.4.20 - /bin/bash
  Binaries:
    Node: 12.18.1 - ~/.nvm/versions/node/v12.18.1/bin/node
    Yarn: 1.22.4 - ~/.nvm/versions/node/v12.18.1/bin/yarn
    npm: 6.14.5 - ~/.nvm/versions/node/v12.18.1/bin/npm
  Managers:
    Apt: 1.6.12 - /usr/bin/apt
  Utilities:
    Git: 2.17.1 - /usr/bin/git
  IDEs:
    Nano: 2.9.3 - /bin/nano
    Vim: 8.0 - /usr/bin/vim
  Languages:
    Bash: 4.4.20 - /bin/bash
    Perl: 5.26.1 - /usr/bin/perl
    Python3: 3.6.9 - /usr/bin/python3
  Databases:
    MySQL: 5.7.30 - /usr/bin/mysql
```


![image](https://user-images.githubusercontent.com/22195362/87572310-f7c7cc00-c6e8-11ea-8d97-5e2434cc7af1.png)


Please try this out again with the latest version of prisma.

**Comment by janpio** [comment] 2020-09-02 02:27
Hey @nicosampler , could you have another look at this after @pantharshit00 could not reproduce this? With a newer Prisma version this should definitely not happen any more. If you can not reproduce this, we would like to close the issue (or you can do that for us).

**Comment by janpio** [comment] 2021-03-23 19:22
I am going to close this now. Happy to take a look again if we get more information.

**Closed by janpio** 2021-03-23 19:22 UTC
Labels: bug/0-needs-info, kind/bug, status/needs-action, topic: raw
