### ISSUE TITLE
Error in migration engine: entered unreachable code 

### ISSUE THREAD

**Issue by jkomyno** [prisma/prisma#15928] opened 2022-10-21 11:17 UTC
Command: `prisma db push`
Version: `4.4.0`
Binary Version: `f352a33b70356f46311da8b00d83386dd9f145d6`
Report: https://prisma-errors.netlify.app/report/14375 
OS: `x64 win32 10.0.22000`

Rust Stacktrace:
```
Starting migration engine RPC server
Aborting migration because at least one unexecutable step was detected.
Attempting best_effort_reset
[migration-engine\connectors\sql-migration-connector\src\sql_renderer\mysql_renderer.rs:522:97] internal error: entered unreachable code
```

## Context

We're hitting this line:

https://github.com/prisma/prisma-engines/blob/4.4.0/migration-engine/connectors/sql-migration-connector/src/sql_renderer/mysql_renderer.rs#L522

```rust
fn render_default<'a>(column: ColumnWalker<'a>, default: &'a DefaultValue) -> Cow<'a, str> {
    match default.kind() {
        // ...
        DefaultKind::DbGenerated(None) | DefaultKind::Sequence(_) | DefaultKind::UniqueRowid => unreachable!(),
    }
}
```

**Comment by tomhoule** [comment] 2022-10-24 05:16
Closing this as a duplicate of https://github.com/prisma/prisma/issues/15928

**Closed by tomhoule** 2022-10-24 05:16 UTC
Labels: kind/bug, process/candidate, tech/engines/datamodel, topic: error reporting, topic: mysql, team/schema, topic: prisma db push
