### ISSUE TITLE
internal error: entered unreachable code

### ISSUE THREAD

**Issue by bordeau** [prisma/prisma#23670] opened 2024-03-30 16:53 UTC
### Bug description

attempting to insert roles into roles table

To increase the chance of success, please post your schema and a snippet of
how you used Prisma Client in the issue. 

    at In.handleRequestError (/Users/bordeau/dev/crm1/node_modules/@prisma/client/runtime/library.js:122:7215)
    at In.handleAndLogRequestError (/Users/bordeau/dev/crm1/node_modules/@prisma/client/runtime/library.js:122:6188)
    at In.request (/Users/bordeau/dev/crm1/node_modules/@prisma/client/runtime/library.js:122:5896)
    at l (/Users/bordeau/dev/crm1/node_modules/@prisma/client/runtime/library.js:127:10871)
    at initRoles (file:///Users/bordeau/dev/crm1/app/controllers/roles.ts:19:23)

### How to reproduce

```typescript
//// how to reproduce.. execute initRoles on empty roles table
import { prisma } from "~/db/db.server.ts";

import { getAllRoles, initRoles } from "~/controllers/roles";

export async function initRoles() {
  const role = await getRoleByName("PendingUser");

  console.log("initRoles: " + JSON.stringify(role));

  if (role === null) {
    console.log("role was null");

    let data = { name: "Admin" };
    const adminRole = await prisma.roles.create({ data: data });
    data = { name: "User" };
    const userRole = await prisma.roles.create({ data: data });
    data = { name: "PendingUser" };
    const pendingUserRole = await prisma.roles.create({ data: data });

    console.log(
      "initRoles after insert: " +
        JSON.stringify(adminRole) +
        " " +
        JSON.stringify(pendingUserRole)
    );

    return pendingUserRole;
  }
  return role;
}

export async function getRoleByName(nm) {
  const role = await prisma.roles.findFirst({
    where: { name: nm },
  });
  console.log("getRolebyName: " + JSON.stringify(role));
  return role;
}
```

### Expected behavior

create the 3 roles specified above and return the  pendingUserRole role
or return the found PendingUser role data

### Prisma information

```prisma
generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "sqlite"
  url      = env( "DATABASE_URL" )
}

// user -authentication types

model roles {
  role_id   Int       @id @default(autoincrement())
  name      String?
  users     users[]
  createdAt DateTime  @default(now())
  updatedAt DateTime  @updatedAt
}

model users {
  user_id   Int       @id @default(autoincrement())
  clerk_id  String    @unique
  role_id   Int
  roles     roles?    @relation( fields: [role_id], references: [role_id], onDelete: NoAction, onUpdate: NoAction)
  isActive  Boolean   @default(false)
  persons persons[]
  createdAt DateTime  @default(now())
  updatedAt DateTime  @updatedAt
}

// crn types

model org_types {
  org_type_id   Int   @id @default(autoincrement())
  name      String
  orgs      orgs[]
  createdAt DateTime  @default(now())
  updatedAt DateTime  @updatedAt
}

model orgs {
  org_id    Int      @id @default(autoincrement())
  name      String
  org_type_id Int?
  address      String?      // the contents will be Json
  org_types   org_types?    @relation( fields: [org_type_id], references: [org_type_id], onDelete: NoAction, onUpdate: NoAction)
  persons persons_in_orgs[]
  createdAt DateTime @default(now())
  updatedAt DateTime @updatedAt
}

model persons {
  person_id Int @id @default(autoincrement())
  user_id Int?
  users   users?    @relation( fields: [user_id], references: [user_id])
  orgs persons_in_orgs[]
  first_name      String
  last_name      String
  email      String
  phone      String
  address      String?      // the contents will be Json
  createdAt DateTime @default(now())
  updatedAt DateTime @updatedAt
}

model persons_in_orgs {
  org orgs @relation(fields: [org_id], references: [org_id])
  org_id Int
  person persons @relation(fields: [person_id], references: [person_id])
  person_id Int
  title String
  sub_org String?
  email      String?
  phone      String?
  address      String?      // the contents will be Json
  createdAt DateTime @default(now())
  updatedAt DateTime @updatedAt
  @@id([org_id, person_id])
}
```

### Environment & setup

- OS: 
- Database:  SQLite, ]-->
- Node.js version: 

### Prisma Version

```
prisma                  : 5.11.0
@prisma/client          : 5.11.0
Computed binaryTarget   : darwin-arm64
Operating System        : darwin
Architecture            : arm64
Node.js                 : v21.6.2
Query Engine (Node-API) : libquery-engine efd2449663b3d73d637ea1fd226bafbcf45b3102 (at node_modules/@prisma/engines/libquery_engine-darwin-arm64.dylib.node)
Schema Engine           : schema-engine-cli efd2449663b3d73d637ea1fd226bafbcf45b3102 (at node_modules/@prisma/engines/schema-engine-darwin-arm64)
Schema Wasm             : @prisma/prisma-schema-wasm 5.11.0-15.efd2449663b3d73d637ea1fd226bafbcf45b3102
Default Engines Hash    : efd2449663b3d73d637ea1fd226bafbcf45b3102
Studio                  : 0.499.0
```

**Comment by jkomyno** [comment] 2024-04-03 09:55
Hi @bordeau, I'm unable to reproduce this problem with the snippet you provided.
I started from an empty SQLite database, and filled in the blanks where the method definitions were not provided:

```typescript
import { PrismaClient } from '.prisma/client'

async function main() {
  const prisma = new PrismaClient()

  const role = await prisma.roles.findFirst({
    where: {
      name: "PendingUser"
    }
  })

  console.log("initRoles: " + JSON.stringify(role))

  if (role === null) {
    console.log("role was null")

    let data = { name: "Admin" }
    const adminRole = await prisma.roles.create({ data: data })
    data = { name: "User" }
    const userRole = await prisma.roles.create({ data: data })
    data = { name: "PendingUser" }
    const pendingUserRole = await prisma.roles.create({ data: data })

    console.log(
      "initRoles after insert: " +
        JSON.stringify(adminRole) +
        " " +
        JSON.stringify(userRole) +
        " " +
        JSON.stringify(pendingUserRole)
    )

    return pendingUserRole
  }

  return role
}

void main().catch((e) => {
  console.log(e.message)
  process.exit(1)
})
```

This led to the following output:

```sh
initRoles: null
role was null
initRoles after insert: {"role_id":1,"name":"Admin","createdAt":"2024-04-03T09:48:59.241Z","updatedAt":"2024-04-03T09:48:59.241Z"} {"role_id":2,"name":"User","createdAt":"2024-04-03T09:48:59.242Z","updatedAt":"2024-04-03T09:48:59.242Z"} {"role_id":3,"name":"PendingUser","createdAt":"2024-04-03T09:48:59.243Z","updatedAt":"2024-04-03T09:48:59.243Z"}
```

**Comment by jkomyno** [comment] 2024-05-17 12:15
Hey @bordeau, can you please take a look at my previous comment and hopefully provide a reproduction for this problem?
Without it, I'm afraid we will have to close this issue. Thanks!

**Comment by Jolg42** [comment] 2024-05-27 13:56
With the lack of information and our inability to reproduce this issue, we're now closing it. Feel free to comment if you have any updates about it.

Thank you 🙏

**Closed by Jolg42** 2024-05-27 13:56 UTC
Labels: bug/0-unknown, kind/bug, topic: sqlite, team/client, topic: entered unreachable code
