### ISSUE TITLE
Query not generated when too many filters

### ISSUE THREAD

**Issue by agusgambina** [prisma/prisma#10576] opened 2021-12-04 17:31 UTC
### Bug description

I created an stackoverflow question for this [stackoverflow](https://stackoverflow.com/questions/70223111/how-to-query-with-prisma-multiple-inner-joins)

I am trying to query with multiple joins, but what happens is if I add conditions to the where I get the prisma version as response. 

### How to reproduce

The first query works, the second does not

    const products = await prisma.products.findMany({
      where: {
        is_enable: true,
        is_deleted: false,
      },
      include: {
        items: {
          where: {
            is_deleted: false
          },
          include: {
            parts: {
              include: {
                subvehicles: {
                  include: {
                    vehicles: {
                      include: {
                        manufacturers: true
                      }
                    }
                  }
                }
              }
            }
          }
        }
      },
      skip: replacements.offset,
      take: replacements.limit,
    });

---

    const products = await prisma.products.findMany({
          where: {
            is_enable: true,
            is_deleted: false,
          },
          include: {
            items: {
              where: {
                is_deleted: false
              },
              include: {
                parts: {
                  where: {
                    is_deleted: false,
                  },
                  include: {
                    subvehicles: {
                      include: {
                        vehicles: {
                          include: {
                            manufacturers: true
                          }
                        }
                      }
                    }
                  }
                }
              }
            }
          },
          skip: replacements.offset,
          take: replacements.limit,
        });

### Expected behavior

Queries should be generated

In the first case the generated query is

    prisma:client Prisma Client call: +1s
    prisma:client prisma.products.findMany({
    prisma:client   where: {
    prisma:client     is_enable: true,
    prisma:client     is_deleted: false
    prisma:client   },
    prisma:client   include: {
    prisma:client     items: {
    prisma:client       where: {
    prisma:client         is_deleted: false
    prisma:client       },
    prisma:client       include: {
    prisma:client         parts: {
    prisma:client           include: {
    prisma:client             subvehicles: {
    prisma:client               include: {
    prisma:client                 vehicles: {
    prisma:client                   include: {
    prisma:client                     manufacturers: true
    prisma:client                   }
    prisma:client                 }
    prisma:client               }
    prisma:client             }
    prisma:client           }
    prisma:client         }
    prisma:client       }
    prisma:client     }
    prisma:client   }
    prisma:client }) +1ms
    prisma:client Generated request: +1ms
    prisma:client query {
    prisma:client   findManyproducts(where: {
    prisma:client     is_enable: true
    prisma:client     is_deleted: false
    prisma:client   }) {
    prisma:client     id
    prisma:client     code
    prisma:client     description
    prisma:client     position
    prisma:client     is_enable
    prisma:client     category
    prisma:client     filename
    prisma:client     is_deleted
    prisma:client     creation_date
    prisma:client     last_modification_date
    prisma:client     items(where: {
    prisma:client       is_deleted: false
    prisma:client     }) {
    prisma:client       id
    prisma:client       part_id
    prisma:client       product_id
    prisma:client       quantity
    prisma:client       is_deleted
    prisma:client       creation_date
    prisma:client       last_modification_date
    prisma:client       parts {
    prisma:client         id
    prisma:client         subvehicle_id
    prisma:client         oem
    prisma:client         is_deleted
    prisma:client         creation_date
    prisma:client         last_modification_date
    prisma:client         subvehicles {
    prisma:client           id
    prisma:client           vehicle_id
    prisma:client           submodel
    prisma:client           is_deleted
    prisma:client           creation_date
    prisma:client           last_modification_date
    prisma:client           vehicles {
    prisma:client             id
    prisma:client             manufacturer_id
    prisma:client             model
    prisma:client             is_deleted
    prisma:client             creation_date
    prisma:client             last_modification_date
    prisma:client             manufacturers {
    prisma:client               id
    prisma:client               name
    prisma:client               position
    prisma:client               is_deleted
    prisma:client               creation_date
    prisma:client               last_modification_date
    prisma:client             }
    prisma:client           }
    prisma:client         }
    prisma:client       }
    prisma:client     }
    prisma:client   }
    prisma:client }
    prisma:client  +0ms

In the second case

    prisma:client clientVersion: 3.6.0 +0ms
    prisma:client clientEngineType: library +0ms

### Prisma information

```
generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

model images_products {
  id                     Int      @id @default(autoincrement())
  product_id             Int
  name                   String   @unique @db.VarChar(255)
  type                   String   @db.VarChar(255)
  title                  String   @db.VarChar(255)
  description            String   @db.VarChar(255)
  url                    String   @unique @db.VarChar(255)
  is_enable              Boolean? @default(true)
  position               Int?
  is_deleted             Boolean  @default(false)
  creation_date          DateTime @default(now()) @db.Timestamp(6)
  last_modification_date DateTime @default(now()) @db.Timestamp(6)
  products               products @relation(fields: [product_id], references: [id], onDelete: NoAction, onUpdate: NoAction)
}

model items {
  id                     Int      @id @default(autoincrement())
  part_id                Int
  product_id             Int
  quantity               Int?
  is_deleted             Boolean  @default(false)
  creation_date          DateTime @default(now()) @db.Timestamp(6)
  last_modification_date DateTime @default(now()) @db.Timestamp(6)
  parts                  parts    @relation(fields: [part_id], references: [id], onDelete: NoAction, onUpdate: NoAction)
  products               products @relation(fields: [product_id], references: [id], onDelete: NoAction, onUpdate: NoAction)
}

model manufacturers {
  id                     Int        @id @default(autoincrement())
  name                   String     @unique @db.VarChar(50)
  position               Int?
  is_deleted             Boolean    @default(false)
  creation_date          DateTime   @default(now()) @db.Timestamp(6)
  last_modification_date DateTime   @default(now()) @db.Timestamp(6)
  vehicles               vehicles[]
}

model parts {
  id                     Int      @id @default(autoincrement())
  subvehicle_id          Int
  oem                    String?  @db.VarChar(255)
  is_deleted             Boolean  @default(false)
  creation_date          DateTime @default(now()) @db.Timestamp(6)
  last_modification_date DateTime @default(now()) @db.Timestamp(6)
  subvehicles            subvehicles @relation(fields: [subvehicle_id], references: [id], onDelete: NoAction, onUpdate: NoAction)
  items                  items[]
}

model products {
  id                     Int                    @id @default(autoincrement())
  code                   String                 @unique @db.VarChar(100)
  description            String?                @db.VarChar(255)
  position               Int?
  is_enable              Boolean?               @default(true)
  category               product_category_type?
  filename               String?                @db.VarChar(255)
  is_deleted             Boolean?               @default(false)
  creation_date          DateTime               @default(now()) @db.Timestamp(6)
  last_modification_date DateTime               @default(now()) @db.Timestamp(6)
  images_products        images_products[]
  items                  items[]
}

model subvehicles {
  id                     Int      @id @default(autoincrement())
  vehicle_id             Int
  submodel               String   @unique @db.VarChar(50)
  is_deleted             Boolean? @default(false)
  creation_date          DateTime @default(now()) @db.Timestamp(6)
  last_modification_date DateTime @default(now()) @db.Timestamp(6)
  vehicles               vehicles @relation(fields: [vehicle_id], references: [id], onDelete: NoAction, onUpdate: NoAction)
  parts               parts[]
}

model vehicles {
  id                     Int           @id @default(autoincrement())
  manufacturer_id        Int
  model                  String        @unique @db.VarChar(50)
  is_deleted             Boolean?      @default(false)
  creation_date          DateTime      @default(now()) @db.Timestamp(6)
  last_modification_date DateTime      @default(now()) @db.Timestamp(6)
  manufacturers          manufacturers @relation(fields: [manufacturer_id], references: [id], onDelete: NoAction, onUpdate: NoAction)
  subvehicles            subvehicles[]
}

enum product_category_type {
  Buje
  Cazoleta
  Vario
}

```

### Environment & setup

- OS: Mac OS
- Database: PostgreSQL
- Node.js version: Node 12.22.6

### Prisma Version

```
prisma                  : 3.6.0
@prisma/client          : 3.6.0
Current platform        : darwin
Query Engine (Node-API) : libquery-engine dc520b92b1ebb2d28dc3161f9f82e875bd35d727 (at node_modules/@prisma/engines/libquery_engine-darwin.dylib.node)
Migration Engine        : migration-engine-cli dc520b92b1ebb2d28dc3161f9f82e875bd35d727 (at node_modules/@prisma/engines/migration-engine-darwin)
Introspection Engine    : introspection-core dc520b92b1ebb2d28dc3161f9f82e875bd35d727 (at node_modules/@prisma/engines/introspection-engine-darwin)
Format Binary           : prisma-fmt dc520b92b1ebb2d28dc3161f9f82e875bd35d727 (at node_modules/@prisma/engines/prisma-fmt-darwin)
Default Engines Hash    : dc520b92b1ebb2d28dc3161f9f82e875bd35d727
Studio                  : 0.440.0
```

**Comment by SevInf** [comment] 2022-09-02 13:29
I can not reproduce it with either current `main` or `3.6.0` reported in the ticket. 
Note that provided code has an error: `where` condition is not available on `parts` because in the provided schema, 1 item can have only one part. If I reverse the order of that 1:M relationship (meaning, 1 item, multiple parts) the query works correctly in both versions.
This error is also caught by both run- and compile- time checks in both versions. I assume this is a vanilla JS, so no compile time checks are done and runtime exception got lost somewhere in the application code. That would be consistent with provided prisma logs.

I am going to close this issue for now, but feel free to reopen if you manage to reproduce it without this error.

**Closed by SevInf** 2022-09-02 13:29 UTC
Labels: bug/1-unconfirmed, kind/bug, topic: broken query, team/client

**Comment by janpio** [comment] 2022-09-02 19:45
> and runtime exception got lost somewhere in the application code.

Is this fixced today or might this justify a follow up issue?

**Comment by SevInf** [comment] 2022-09-05 08:28
> 
> Is this fixed today or might this justify a follow up issue?

Both 3.6.0 and current version correctly throw a catchable error in this case. What I meant by exception gets lost: probably some other part of the application is responsible for catching that exception and not logging in. Node < 15 also does not exit on unhanlded promise rejection by default (but prints a warning to the console), that could be another reason why this exception got unnoticed.
