### ISSUE TITLE
Test and support array primary keys on PostgreSQL in the client/QE

### ISSUE THREAD

**Issue by pimeys** [prisma/prisma#14077] opened 2022-06-30 13:29 UTC
PostgreSQL allows using arrays as the primary key. We have a [pull request](https://github.com/prisma/prisma-engines/pull/2971) enabling them in the schema validation, migrations and introspection. Before we merge it, we should be sure the Query Engine works with them correctly by writing some tests. If something breaks, then fixing the issues.

E.g. this is valid:

```prisma
model test {
  id String[] @id
}
```

Please co-ordinate with @pimeys.

**Comment by matthewmueller** [comment] 2022-07-15 13:57
Duplicate of https://github.com/prisma/prisma/issues/13777?

**Closed** 2022-07-15 16:19 UTC
Labels: kind/improvement, tech/engines/query engine, topic: postgresql list, team/client
