### ISSUE TITLE
throw error when queryRaw with unsupported columns

### ISSUE THREAD

**Issue by liaojiwei666** [prisma/prisma#12864] opened 2022-04-18 17:07 UTC
### Bug description

I want to query data by queryRaw method, but I had few columns with unsupported type.
When I use the code like below to query data
```
await prisma.$queryRaw<Array<listing>>`
    SELECT *
    FROM listing
`
```
The prisma will throw error
```
PrismaClientKnownRequestError: 
Invalid `prisma.queryRaw()` invocation:


  Raw query failed. Code: `N/A`. Message: `error deserializing column 43: cannot convert between the Rust type `core::option::Option<alloc::string::String>` and the Postgres type `point``
    at cb (/Users/liaojiwei/Desktop/funwoo/backyard-api/node_modules/@prisma/client/runtime/index.js:38688:17) {
  code: 'P2010',
  clientVersion: '3.7.0',
  meta: {
    code: 'N/A',
    message: 'error deserializing column 43: cannot convert between the Rust type `core::option::Option<alloc::string::String>` and the Postgres type `point`'
  }
}
```

### How to reproduce

1. Create a Prisma Postgresql db with model containing one or more columns with unsupported type.
2. Use queryRaw method to select all columns from the table.
3. Prisma will throw the error I was mention above.

### Expected behavior

Get data with all columns without error

### Relevant model:
```
model listing {
  id                            String                    @id @default(dbgenerated("gen_random_uuid()")) @db.Uuid
  location_latlon               Unsupported("point")?
  location_geopoint             Unsupported
}
```

### Relevant queries:
```
const listings = await prisma.$queryRaw<Array<listing>>`
    SELECT *
    FROM listing
`
```

### Environment & setup

- OS: Mac OS 12.3.1
- Database: PostgreSQL
- Node.js version: 16.13.0

### Prisma Version

```
prisma                  : 3.7.0
@prisma/client          : 3.7.0
Current platform        : darwin
Query Engine (Node-API) : libquery-engine 8746e055198f517658c08a0c426c7eec87f5a85f (at node_modules/@prisma/engines/libquery_engine-darwin.dylib.node)
Migration Engine        : migration-engine-cli 8746e055198f517658c08a0c426c7eec87f5a85f (at node_modules/@prisma/engines/migration-engine-darwin)
Introspection Engine    : introspection-core 8746e055198f517658c08a0c426c7eec87f5a85f (at node_modules/@prisma/engines/introspection-engine-darwin)
Format Binary           : prisma-fmt 8746e055198f517658c08a0c426c7eec87f5a85f (at node_modules/@prisma/engines/prisma-fmt-darwin)
Default Engines Hash    : 8746e055198f517658c08a0c426c7eec87f5a85f
Studio                  : 0.445.0
Preview Features        : filterJson
```

**Comment by Weakky** [comment] 2022-05-05 17:44
Hey @liaojiwei666,

This is unfortunately not a bug. You're column `location_latlon` is marked as `Unsupported`. This means, among other things, that Prisma does not know how to serialize/deserialize your type.

There is a workaround though: you can cast your column to a type that's supported by Prisma, like `String`. On Postgres, that'd be `text` (`SELECT my_column::text FROM "Table"`).

If you do not actually _need_ to select the column of type `point`, removing it from the selection set is also an option.

Next release will include two things:
1. A more user-friendly error for your issue. 👇:
   ```
   Failed to deserialize column of type 'point'. If you're using $queryRaw and this column is explicitly marked as 'Unsupported' in your Prisma schema, try casting this column to any supported Prisma type such as 'String'.
   ```
2. Better documentation that explains the available workarounds

I'm now closing your issue in favor of https://github.com/prisma/prisma/issues/13203.

Thank you for reporting 🙏

**Closed by Weakky** 2022-05-05 17:44 UTC
Labels: bug/1-unconfirmed, kind/bug, topic: raw, tech/engines/query engine, team/client, topic: Unsupported
