### ISSUE TITLE
`updateMany` memory leak?

### ISSUE THREAD

**Issue by somersby10ml** [prisma/prisma#22346] opened 2023-12-12 11:32 UTC
### Bug description

# Description
I'm using MongoDB, and running a large number of updates when using Prisma will cause memory leakage.

# Total number of data
Number of data: 9 400 000
```ts
const client = new MongoClient(DATABASE_URL_DEVELOPMENT);
await client.connect();
const db = client.db();
const collection = db.collection('test');
const totalDocuments = await collection.countDocuments();
console.log(totalDocuments);
```

![스크린샷 2023-12-12 200502](https://github.com/prisma/prisma/assets/85594221/2cfc68b8-b9ab-4a7f-bc4a-abe2d56e7aad)

# Issues

It works slowly but normally in mongodb.
But when you update a lot on Prima, your RAM gets higher and higher.

image)
https://ibb.co/album/k5B0RF
sort A/Z

### Prisma information

```prisma
model Test {
  @@map("test")

  objectId String @id @default(auto()) @map("_id") @db.ObjectId
  id              String   @unique
  na              String
  sa              String
  
  ap              Float
  co              String
  eq              Float
  oi              String
  oq              Float
  ot              String
  pr              Float
  ro              Boolean
  si              String
  ps              String
  st              String
  sp              Float?
  cp              Boolean
  sy              String
  ti              Int
  tf              String
  ty              String
  ac              Float?
  pr2              Float?
  ut              Int
  wt              String
  pp              Boolean


  pi              String?

  ic              Boolean  @default(false)
  ca              DateTime? @default(now())
  ua              DateTime? @updatedAt
  da              DateTime?
}
```

```ts
 const result = await prisma.test.updateMany({
    data: {
      ic: false,
    },
  });
  console.log(result);
```
-> leak

### Environment & setup

- OS: WSL2 Ubuntu (host is windows)
- Database: MongoDB
- Node.js version: v18.17.1

## WSL
WSL version: 2.0.9.0
Kernel version: 5.15.133.1-1
WSLg version: 1.0.59
MSRDC version: 1.2.4677
Direct3D version: 1.611.1-81528511
DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows version: 10.0.22631.2792

## lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.3 LTS
Release:        22.04
Codename:       jammy

##  cat /etc/issue
Ubuntu 22.04.3 LTS

### Prisma Version

```
prisma                  : 5.7.0
@prisma/client          : 5.7.0
Computed binaryTarget   : debian-openssl-3.0.x
Operating System        : linux
Architecture            : x64
Node.js                 : v18.17.1
Query Engine (Node-API) : libquery-engine 79fb5193cf0a8fdbef536e4b4a159cad677ab1b9 (at ../../node_modules/.pnpm/@prisma+engines@5.7.0/node_modules/@prisma/engines/libquery_engine-debian-openssl-3.0.x.so.node)
Schema Engine           : schema-engine-cli 79fb5193cf0a8fdbef536e4b4a159cad677ab1b9 (at ../../node_modules/.pnpm/@prisma+engines@5.7.0/node_modules/@prisma/engines/schema-engine-debian-openssl-3.0.x)
Schema Wasm             : @prisma/prisma-schema-wasm 5.7.0-41.79fb5193cf0a8fdbef536e4b4a159cad677ab1b9
Default Engines Hash    : 79fb5193cf0a8fdbef536e4b4a159cad677ab1b9
Studio                  : 0.495.0
```

## MongoDB Server
OS: Windows10 22H2(19045.3693)
MongoDB Version: 6.0.5.0 (64bit)

**Comment by Druue** [comment] 2023-12-12 12:28
Hey @somersby10ml, thanks for opening an issue!
Could you please either provide a minimal reproduction of this (or the following information:) so that we can help confirm this :)

Which version of MongoDB are you using?
Can you confirm whether you're using `pnpm`, `npm`, `yarn`, or another, and which _version_.
Do you have a package.json & lockfile that you can share with us?

Do you have the same experience on other versions of Prisma? or only `5.6.0` (current latest is now `5.7.0`)

Have you confirmed that it _stays_ consistently high? or does memory usage return back to expected levels

It would help us a lot if the information you provided in that album link was directly in the issue instead

Cheers! ✨

**Comment by Jolg42** [comment] 2023-12-12 12:50
@somersby10ml additionally, I'm not sure if I understand what I see in your screenshots at the moment and could use your help.
![image](https://github.com/prisma/prisma/assets/1328733/9acaa2d6-ec5d-4fc0-b171-1842889f6752)

For example, here, I see 8 processes that were started using the same command, running the `prisma2.ts` script.
- Why are you running multiple processes of the same command at the same time?
- What's in that script exactly? Only one Prisma query?
- Is it running the exact same query as you mentioned before? `await prisma.test.updateMany({ data: { ic: false } });` 
- It looks like this query would be resource intensive without an index to me, did you try adding an index like `@@index([ic])` to this model?

**Comment by somersby10ml** [comment] 2023-12-12 13:08
@Druue
Which version of MongoDB are you using?
-> I updated the bottom of the question.

I'm using pnpm.

The same symptoms appear in the latest version of prisma (5.7.0).

Memory does not return to a certain level, continues to grow, and eventually the program ends. 

mongodb's `updateMany` works normally.
However, it seems that `Prisma updateMany` ends without completing it until the end.
https://ibb.co/dr4Zcys

**Comment by somersby10ml** [comment] 2023-12-12 13:19
@Jolg42 
### Why are you running multiple processes of the same command at the same time?
---
This is not what I meant. 
It seems to have been automatically divided by node.

package.json
```
 "script": "cross-env $(node env.js) ts-node -r tsconfig-paths/register --files",
```
When I did the test, I did the following.
```
pnpm dotenv -- pnpm script server -- ./test/migration/prisma2.ts
```

### What's in that script exactly? Only one Prisma query?
---
Yes
```ts
async function main() {
  const prisma = new PrismaClient({
    datasources: {
      db: {
        url: DATABASE_URL_DEVELOPMENT,
      },
    },
  });
  const result = await prisma.test.updateMany({
      data: {
        ic: false,
      },
    });
}
main();
```


### Is it running the exact same query...
---
Yes

### t looks like this query would be resource intensive...
I tried adding an index, but the same symptoms appear.

**Comment by Jolg42** [comment] 2023-12-14 15:40
@somersby10ml I'm back after getting lost through different rabbit holes here 😄 

About the index, it would indeed not help without also adapting the query like
```
  const result = await prisma.test.updateMany({
      data: {
        ic: false,
      },
	  where: {
        ic: true
      },
    });
```
Note that you would also need to run `npx prisma db push` to create the index.
The updateMany query will look like this 
```
db.test.aggregate([ { $match: { $expr: { $and: [ { $eq: [ "$ic", { $literal: true, }, ], }, { $ne: [ "$ic", "$$REMOVE", ], }, ], }, }, }, { $project: { _id: 1, }, }, ])
```
and is going to be a lot faster!

**Comment by Jolg42** [comment] 2023-12-14 15:45
Now back to the original issue description, where you suspected a memory leak

I made a reproduction repository here https://github.com/Jolg42/repro-22346

But I could not reproduce any memory leak so far.

The query is actually failing with the following error message for me:
```
Raw query failed. Code: `unknown`. Message: `Kind: Command failed: Error code 10334 (BSONObjectTooLarge): BSONObj size: 40889298 (0x26FEBD2) is invalid. Size must be between 0 and 16793600(16MB) First element: update: "test", labels: {}`
```

The full logs look like this, I had to truncate the number of ObjectIds, because it's a lot of them
```
....ObjectId("657b200569032efb20d2152c"), ObjectId("657b200569032efb20d2152d"), ObjectId("657b200569032efb20d2152e"), ObjectId("657b200569032efb20d2152f"), ObjectId("657b200569032efb20d21530"), ObjectId("657b200569032efb20d21531"), ObjectId("657b200569032efb20d21532"), ObjectId("657b200569032efb20d21533"), ObjectId("657b200569032efb20d21534"), ObjectId("657b200569032efb20d21535"), ObjectId("657b200569032efb20d21536"), ObjectId("657b200569032efb20d21537"),                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          ^
PrismaClientKnownRequestError: 
Invalid `prisma.test.updateMany()` invocation in
/Users/j42/Repros/22346/main.ts:73:23

  70 // Note: this logging approach works best when iterations are "fast"
  71 memoryLogger.maybeLog();
  72 
→ 73 await prisma.test.updateMany(
Raw query failed. Code: `unknown`. Message: `Kind: Command failed: Error code 10334 (BSONObjectTooLarge): BSONObj size: 40889298 (0x26FEBD2) is invalid. Size must be between 0 and 16793600(16MB) First element: update: "test", labels: {}`
    at si.handleRequestError (/Users/j42/Repros/22346/node_modules/@prisma/client/runtime/library.js:125:6817)
    at si.handleAndLogRequestError (/Users/j42/Repros/22346/node_modules/@prisma/client/runtime/library.js:125:6151)
    at si.request (/Users/j42/Repros/22346/node_modules/@prisma/client/runtime/library.js:125:5859)
    at async l (/Users/j42/Repros/22346/node_modules/@prisma/client/runtime/library.js:130:10025)
    at async main (/Users/j42/Repros/22346/main.ts:73:5) {
  code: 'P2010',
  clientVersion: '5.7.0',
  meta: {
    modelName: 'Test',
    code: 'unknown',
    message: 'Kind: Command failed: Error code 10334 (BSONObjectTooLarge): BSONObj size: 40889298 (0x26FEBD2) is invalid. Size must be between 0 and 16793600(16MB) First element: update: "test", labels: {}'
  }
}
```

-> It looks like this query ends up being one massive query which is bigger than 16MB

**Comment by Jolg42** [comment] 2023-12-14 15:49
If you want to us to have another look at the suspected memory leak, could you try to reproduce what you observed using my reproduction repository https://github.com/Jolg42/repro-22346? Let me know if you need any help.
If not, you/we could close this issue.

In general, I can recommend using a `where` filter when doing a `createMany`.
And if it's a query that needs to be fast, an index could help.

Let me know what you want to do next about this issue @somersby10ml

**Comment by somersby10ml** [comment] 2023-12-14 15:50
@Jolg42 I'll check. thank you

**Comment by somersby10ml** [comment] 2023-12-14 17:19
@Jolg42 We have put `83 00 000` data into the database.
I get the following error:
```
Raw query failed. Code: `unknown`. Message: `Kind: I/O error: 현재 연결은 사용자의 호스트 시스템의 소프트웨어의 의해 중단되었습니다. (os error 10053), labels: {"TransientTransactionError"}`    at si.handleRequestError (C:\Users\admin\Desktop\prisma_test\node_modules\@prisma\client\runtime\library.js:125:6817)
    at si.handleAndLogRequestError (C:\Users\admin\Desktop\prisma_test\node_modules\@prisma\client\runtime\library.js:125:6151)
    at si.request (C:\Users\admin\Desktop\prisma_test\node_modules\@prisma\client\runtime\library.js:125:5859)
    at async l (C:\Users\admin\Desktop\prisma_test\node_modules\@prisma\client\runtime\library.js:130:10025)
    at async main (C:\Users\admin\Desktop\prisma_test\main.ts:74:5) {
  code: 'P2010',
  clientVersion: '5.7.0',
  meta: {
    modelName: 'Test',
    code: 'unknown',
    message: 'Kind: I/O error: 현재 연결은 사용자의 호스트 시스템의 소프트웨어의 의해 중단되었습니다. (os error 10053), labels: {"TransientTransactionError"}'
  }
}
```
message = The current connection has been interrupted by software on your host system.

https://drive.google.com/file/d/15DX2vlSmQK97tkBs7OlXgglkw_ZncVi2/view?usp=sharing

Tested on the main host, Windows 11.

It's not the same error as https://ibb.co/dr4Zcys
`deleteMany` is still executed, but the program exits with no return value.

**Comment by Jolg42** [comment] 2023-12-14 17:48
In https://ibb.co/dr4Zcys it's indeed different, I can see: `Connection reset by peer (os error 104), labels: {"TransientTransactionError"}`

**Comment by somersby10ml** [comment] 2023-12-14 18:22
@Jolg42 
more test

Windows
The current connection has been interrupted by software on your host system.

WSL Ubuntu:
Connection reset by peer (os error 104)
or
ELIFECYCLE  Command failed with exit code 1.

MacOS(ram 16GB):
![제목 없음](https://github.com/prisma/prisma/assets/85594221/edfca9a6-7621-432d-adcb-3f614cceabc7)

The point is that when there is a lot of data, running `updateMany` increases RAM usage and terminates the program.

**Comment by Jolg42** [comment] 2023-12-14 18:27
So for the 2 errors:
- `Connection reset by peer (os error 104)`
	- it sounds to me that the MongoDB server restarted and the connection was reset
		- I think this should be visible in logs, did you see anything about this?
- `An established connection was aborted by the software in your host machine.(os error 10053)`
	- Here is some documentation from Microsoft https://learn.microsoft.com/en-us/windows/win32/winsock/windows-sockets-error-codes-2
	>WSAECONNABORTED 10053
	Software caused connection abort.
    An established connection was aborted by the software in your host computer, possibly due to a data transmission time-out or protocol error.

Other things you could check is to change the default settings: 
- for `maxTimeMS`, it looks like the default is 60 seconds.
	See https://www.mongodb.com/docs/compass/current/agg-pipeline-builder/maxtime-ms-pipeline/ it shows how to do it from the Compass App. I think you can also set this via the connection string.
- `wtimeoutMS` should be fine by default (no timeout), see [docs](https://www.mongodb.com/docs/drivers/rust/current/fundamentals/connections/connection-options/)
- `connectTimeoutMS` is set by default to 10 seconds. (see [code](https://github.com/mongodb/mongo-rust-driver/blob/2b448e99b3ca94f88e2b78c6b4b77b5b335be45f/src/client/options.rs#L1132))
	- I don't think it's relevant here, though you could put a high value to make sure it's not a problem.

For more details, check https://www.mongodb.com/docs/drivers/node/current/faq/#what-is-the-difference-between--connecttimeoutms----sockettimeoutms--and--maxtimems--

My theory at the moment is that your query is too big, which either ends up in a time-out or causes excessive memory usage and ends up with these errors as the MongoDB server is not able to process them. Probably because your OS kills the process and restarts it.
- How much RAM do you have on that machine? (and how much is free?)
- Try changing the settings, especially `maxTimeMS`

**Comment by Jolg42** [comment] 2023-12-14 18:34
@somersby10ml https://github.com/prisma/prisma/issues/22346#issuecomment-1856363870 is indeed a clear Out Of Memory error, from Node.js.

- It doesn't mean that there is a memory leak, though, it could be that this is only excessive memory usage. For example, if you write a program that needs too much RAM compared to the available RAM, it would OOM.
- It's likely that the memory usage of the Prisma engine could be improved in some cases, though that needs to be investigated, so I would first recommend optimizing your Prisma Client query.
	- If you log the query, you'll be able to see the query sent to the database, which could help you. 
- To work around the excessive memory usage, as you are writing queries against "big" collections, you could do multiple queries instead of one big query.
	- Did you try that already?

**Comment by Jolg42** [comment] 2023-12-14 18:41
In general, what works well to show a memory leak is to write some code that repeats the suspected operation many times.
And observe the memory usage.
In your video earlier, you could see the memory going up and down for example, which is normal behavior.

What would be abnormal is if an operation is repeated many times, and then you observe the memory usage going up steadily. That would mean that the memory is not released correctly, which would be a memory leak.

**Comment by Druue** [comment] 2024-01-02 11:51
Hey @somersby10ml,

Have you had the chance to read through what @Jolg42's response? An update with further tests would help us greatly 🙏 
Thanks!

**Comment by Jolg42** [comment] 2024-01-11 14:32
Following our `bug/0-unknown` process, I will now close this issue.

If you have a reproduction where a memory leak can be observed with a recent version of Prisma, please open a new issue with a reproduction, we will be happy to investigate and try to reproduce.

As a general note, let us know if what you see is excessive memory usage or something that looks like a memory leak.
- In case of a memory leak, the memory usage would steadily go up when repeating the same query many times.
- In case of excessive memory usage, the memory usage would not increase over time, but only spike when the query is running. In this case, it could be that too much data is returned from the database and using a limit like `take: 10` to specify how many objects should be returned.

I hope I can create a code template in the future with some guidelines to help with identifying potential memory leaks in the future (to be done).

**Closed by Jolg42** 2024-01-11 14:32 UTC
Labels: bug/0-unknown, kind/bug, topic: performance, team/client, topic: mongodb, topic: performance/memory, topic: updateMany(), topic: memory leak
