### ISSUE TITLE
Large decimals cause panick

### ISSUE THREAD

**Issue by haydenbriese** [prisma/prisma#12761] opened 2022-04-11 00:13 UTC
### Bug description

Prisma crashes when trying to create large decimals, even when the field is configured for a far greater precision

```
thread 'tokio-runtime-worker' panicked at 'called `Option::unwrap()` on a `None` value', /Users/runner/.cargo/git/checkouts/quaint-9f01e008b9a89c14/479e08a/src/connector/postgres/conversion/decimal.rs:81:39
```

### How to reproduce

1. Init db using schema
2. Execute example create

### Expected behavior

I can create a decimal with a precision of 128

### Schema
```
model Example {
  id     String  @id @default(uuid())
  number Decimal  @db.Decimal(128,0)
}
```

### Call
```
await this.prisma.test.create({
  data: {
    number: "1" + "0".repeat(60), // 1e60
   },
});
```

### Environment & setup

- OS: Mac OS 12
- Database: PostgreSQL
- Node.js version: 16.13.2
- @prisma/client version: 3.12.0

### Prisma Version

```
prisma                  : 3.12.0
@prisma/client          : 3.12.0
Current platform        : darwin-arm64
Query Engine (Node-API) : libquery-engine 22b822189f46ef0dc5c5b503368d1bee01213980 (at node_modules/@prisma/engines/libquery_engine-darwin-arm64.dylib.node)
Migration Engine        : migration-engine-cli 22b822189f46ef0dc5c5b503368d1bee01213980 (at node_modules/@prisma/engines/migration-engine-darwin-arm64)
Introspection Engine    : introspection-core 22b822189f46ef0dc5c5b503368d1bee01213980 (at node_modules/@prisma/engines/introspection-engine-darwin-arm64)
Format Binary           : prisma-fmt 22b822189f46ef0dc5c5b503368d1bee01213980 (at node_modules/@prisma/engines/prisma-fmt-darwin-arm64)
Default Engines Hash    : 22b822189f46ef0dc5c5b503368d1bee01213980
Studio                  : 0.459.0
```

**Comment by garrensmith** [comment] 2022-04-11 10:16
@haydenbriese thanks for the report. May I close this given it is a duplicate of #7061

**Comment by haydenbriese** [comment] 2022-04-11 12:53
> @haydenbriese thanks for the report. May I close this given it is a duplicate of #7061

Though the error messages are the same, the two bugs appear to occur under different circumstances
This bug occurs for very large Decimals.
The other occurs for relatively small Decimals when they're marked with `@id`.

**Comment by Weakky** [comment] 2022-06-17 14:15
Hey,

This was fixed by https://github.com/prisma/quaint/pull/379 and https://github.com/prisma/prisma-engines/pull/2988, and should be available in the next release.

Closing now, thanks for reporting 🙏

**Closed by Weakky** 2022-06-17 14:15 UTC
Labels: bug/1-unconfirmed, kind/bug, tech/engines/query engine, team/client, topic: rust panic, topic: Decimal, priority/low, size/s
