### ISSUE TITLE
Order by relation has only `_count` property. Can not order by relation fields.

### ISSUE THREAD

**Issue by ErlanBelekov** [prisma/prisma#7593] opened 2021-06-11 03:33 UTC
### Bug description

When I fetch a list of conversations, I want to order them by `sentAt` property of related conversation messages.

Currently, I can only sort the relations like this:
```
prisma.conversation.findMany({
    orderBy: {
        messages: {
           '_count': 'desc'
        }
     },
     ...
})
```

### Expected behavior

I expect that I can run this query to sort by relation field
```
prisma.conversation.findMany({
    orderBy: {
        messages: {
            sentAt: 'desc'
        }
    },
    ...
})
```

### Prisma information

```
model Conversation {
  id           Int                         @id @default(autoincrement())
  createdAt    DateTime                    @db.Timestamp(6)
  messages     ConversationMessage[]
}

model ConversationMessage {
  id             Int                     @id @default(autoincrement())
  text           String                  @db.VarChar(1000)
  sentAt         DateTime                @map("sent_at") @db.Timestamp(6)
  conversationId Int?                    @map("conversation_id")
  userId         Int?                    @map("user_id")
  conversation   Conversation?           @relation(fields: [conversationId], references: [id])
  sender         User?                   @relation(fields: [userId], references: [id])
}
```

### Environment & setup

- OS: Mac OS,
- Database: PostgreSQL
- Node.js version: v12.19.0

### Prisma Version

```
prisma               : 2.24.1
@prisma/client       : 2.24.1
Current platform     : darwin
Query Engine         : query-engine 18095475d5ee64536e2f93995e48ad800737a9e4 (at node_modules/@prisma/engines/query-engine-darwin)
Migration Engine     : migration-engine-cli 18095475d5ee64536e2f93995e48ad800737a9e4 (at node_modules/@prisma/engines/migration-engine-darwin)
Introspection Engine : introspection-core 18095475d5ee64536e2f93995e48ad800737a9e4 (at node_modules/@prisma/engines/introspection-engine-darwin)
Format Binary        : prisma-fmt 18095475d5ee64536e2f93995e48ad800737a9e4 (at node_modules/@prisma/engines/prisma-fmt-darwin)
Default Engines Hash : 18095475d5ee64536e2f93995e48ad800737a9e4
Studio               : 0.397.0
Preview Features     : orderByRelation
```

**Comment by ErlanBelekov** [comment] 2021-06-12 03:34
Hi @SuryaElavazhagan , thanks for your time trying to help.

I wonder why `ConversationOrderByInput` has no fields for ordering by the relation `messages` of `Conversation`. Is this a bug in Prisma?

My goal is to get a list of conversations, ordered by last message received, thus the last conversation where a message was sent or received is listed at the top and progresses down with the oldest conversation at the bottom.

I appreciate what you proposed, but that won't help much, because I want to get conversations, not the messages in them.

I would like to get any info pointing at how ordering works for 1:M relations. The Prisma docs have example of ordering with 1:1 relation. (https://www.prisma.io/docs/concepts/components/prisma-client/filtering-and-sorting#sort-by-relation-preview)

**Comment by matthewmueller** [comment] 2021-07-06 12:13
I think there's enough to repro this @pantharshit00

**Comment by pantharshit00** [comment] 2021-07-06 14:14
This is working as intended, you can only traverse to a to-one side, coming from a many or one side (m -> 1, 1 -> 1).

This use case seems more specific as you only intent to order by the last message of the multiple message in your one to many relation. 

I am going to close this as duplicate of https://github.com/prisma/prisma/issues/5837

**Closed by pantharshit00** 2021-07-06 14:14 UTC
Labels: bug/1-repro-available, kind/bug, team/client, topic: orderByRelations
