### ISSUE TITLE
Update behavior inconsistent between 1-n and 1-1 relation queries

### ISSUE THREAD

**Issue by peguerosdc** [prisma/prisma#24478] opened 2024-06-09 21:10 UTC
### Bug description

When having a 1-n relationship, I can use [relation queries](https://www.prisma.io/docs/orm/prisma-client/queries/relation-queries) to delete related records **IF ANY** with this code:

```typescript
async function thisWorks(id: string) {
  await prisma.profile.update({
    where: { id },
    data: {
      many: {
        deleteMany: {},
      }
    }
  });
  console.log(":) Deleting in 1-n worked!")
}
```

But if I try to do a very similar query for 1-1 relations, it doesn't work:

```typescript
async function thisDoesntWork(id: string) {
  await prisma.profile.update({
    where: { id },
    data: {
      one: {
        delete: true,
      }
    }
  });
  console.log(":( Deleting in 1-1 DOESN'T work!")
}
```

Yielding the following error:

```
PrismaClientKnownRequestError:
Invalid `prisma.profile.update()` invocation in
/Users/user/dev/prisma-sandbox/script.ts:25:24

  22 }
  23
  24 async function thisDoesntWork(id: string) {
→ 25   await prisma.profile.update(
An operation failed because it depends on one or more records that were required but not found. No 'ToOne' record was found for a nested delete on relation 'ProfileToToOne'.
    at In.handleRequestError (/Users/user/dev/prisma-sandbox/node_modules/@prisma/client/runtime/library.js:122:6877)
    at In.handleAndLogRequestError (/Users/user/dev/prisma-sandbox/node_modules/@prisma/client/runtime/library.js:122:6211)
    at In.request (/Users/user/dev/prisma-sandbox/node_modules/@prisma/client/runtime/library.js:122:5919)
    at async l (/Users/user/dev/prisma-sandbox/node_modules/@prisma/client/runtime/library.js:127:11167) {
  code: 'P2025',
  clientVersion: '5.14.0',
  meta: {
    modelName: 'Profile',
    cause: "No 'ToOne' record was found for a nested delete on relation 'ProfileToToOne'."
  }
}
```

Which is caused by the `one` record to be non-existing, which doesn't happen with `deleteMany` because it works independently of the relation to be populated or not.

Note: one workaround is to first fetch the record i want to update and check if the related record is set or not, but this requires one extra go to the db which is not optimal. My use-case (which I don't think is a corner-case) is receiving a form to update a `Profile` (that's why I used that name in my example) with the new self-containing data and the ID. I would like to set the new profile only based on the new data without having to go to the db to fetch the old data.

### How to reproduce

1. Clone and set up `https://github.com/peguerosdc/prisma-sandbox/tree/one-to-one-delete-issue`
2. Run the `script.ts` file with the `thisWorks` function to see the case for 1-n relations
3. Run the `script.ts` file with the `thisDoesntWork` function to see the case for 1-n relations
    - See the error
4. (optional) Run the `script.ts` file with the `thisIsTheWorkaround` function to see a workaround for 1-n relations, which would require one extra call to the db to fetch the corresponding record (assuming we are not creating the root record in the same function, which was only done for the purpose of this example and almost never happens in real life).

### Expected behavior

Considering the similarity both in the use case and in the API (note that `{deleteMany: {}}` is very similar to `{delete: true}`, as the analogous `{createMany: {}}` and `{create: {}}`), I would expect:

* prisma to behave the same for 1-1 and 1-n relation queries.
* prisma to let me delete records in 1-1 relations without having to worry if there is an existing record or not
* all similarities and differences to be documented

### Schema

```prisma
generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "sqlite"
  url      = "file:./dev.db"
}

model Profile {
  id        String     @id @default(cuid())
  one       ToOne?
  many      ToMany[]
}

model ToOne {
  id         String    @id @default(cuid())
  profile    Profile   @relation(fields: [profileId], references: [id], onDelete: Cascade)
  profileId  String    @unique
}

model ToMany {
  id         String    @id @default(cuid())
  profile    Profile   @relation(fields: [profileId], references: [id])
  profileId  String
}
```

### Queries

```typescript
async function thisWorks(id: string) {
  await prisma.profile.update({
    where: { id },
    data: {
      many: {
        deleteMany: {},
      }
    }
  });
  console.log(":) Deleting in 1-n worked!")
}

async function thisDoesntWork(id: string) {
  await prisma.profile.update({
    where: { id },
    data: {
      one: {
        delete: true,
      }
    }
  });
  console.log(":( Deleting in 1-1 DOESN'T work!")
}

async function thisIsTheWorkaround(id: string) {
  const root = await prisma.profile.findUniqueOrThrow({
    where: { id },
    include: { one: true }
  })
  await prisma.profile.update({
    where: { id },
    data: {
      one: root.one ? {
        delete: true
      } : undefined
    }
  });
  console.log(":) Deleting in 1-1 works, but I need one extra go to the db!")
}
```

### Environment & setup

- OS: macOS
- Database: I use PostgreSQL, but I have also reproduced it with SQLite
- Node.js version: v22.1.0

### Prisma Version

```
prisma                  : 5.14.0
@prisma/client          : 5.14.0
Computed binaryTarget   : darwin
Operating System        : darwin
Architecture            : x64
Node.js                 : v22.1.0
Query Engine (Node-API) : libquery-engine e9771e62de70f79a5e1c604a2d7c8e2a0a874b48 (at node_modules/@prisma/engines/libquery_engine-darwin.dylib.node)
Schema Engine           : schema-engine-cli e9771e62de70f79a5e1c604a2d7c8e2a0a874b48 (at node_modules/@prisma/engines/schema-engine-darwin)
Schema Wasm             : @prisma/prisma-schema-wasm 5.14.0-25.e9771e62de70f79a5e1c604a2d7c8e2a0a874b48
Default Engines Hash    : e9771e62de70f79a5e1c604a2d7c8e2a0a874b48
Studio                  : 0.500.0
```

**Comment by janpio** [comment] 2024-06-10 07:17
I think this is a side effect of the different semantics of `delete` and `deleteMany`, caused by only either being usable for 1-1 or 1-1 relations. `delete` is expected to throw if the entry to delete does not exist, while `deleteMany` is not it seems. 

Support for `deleteIfExists` would probably avoid your problem? https://github.com/prisma/prisma/issues/9460

**Comment by gustaveWPM** [comment] 2024-07-02 15:21
> I think this is a side effect of the different semantics of `delete` and `deleteMany`, caused by only either being usable for 1-1 or 1-1 relations. `delete` is expected to throw if the entry to delete does not exist, while `deleteMany` is not it seems.
> 
> Support for `deleteIfExists` would probably avoid your problem? #9460

Indeed, Prisma Docs AI told me to use `deleteMany` instead of `delete` to have a kind of "deleteIfExists" workaround... lol

**Comment by laplab** [comment] 2024-07-11 09:15
Closing this in favour of https://github.com/prisma/prisma/issues/9460 feature request.

**Closed by laplab** 2024-07-11 09:15 UTC
Labels: bug/1-unconfirmed, kind/bug, topic: relations, domain/client, topic: delete, topic: deleteMany
