### ISSUE TITLE
ME crash: foreign key references unknown table

### ISSUE THREAD

**Issue by NazarK0** [prisma/prisma#5785] opened 2021-02-22 14:19 UTC
Hi Prisma Team! Prisma Migrate just crashed. 

## Command

`db push --preview-feature`

## Versions
      
| Name        | Version            |
|-------------|--------------------|
| Platform    | debian-openssl-1.1.x| 
| Node        | v14.5.0            | 
| Prisma CLI  | 2.16.1             | 
| Binary      | 8b74ad57aaf2cc6c155f382a18a8e3ba95aceb03| 

## Error
```
Error: Error in migration engine.
Reason: [libs/sql-schema-describer/src/walkers.rs:364:18] foreign key references unknown table

Please create an issue with your `schema.prisma` at 
https://github.com/prisma/prisma/issues/new

```

**Comment by Jolg42** [comment] 2021-02-23 16:17
Hi!

Could you share your `schema.prisma` here?

**Comment by Jolg42** [comment] 2021-02-25 10:14
Note: Seems related/duplicate of

https://github.com/prisma/prisma/issues/4636
https://github.com/prisma/prisma/issues/4695
https://github.com/prisma/prisma/issues/4699

**Comment by NazarK0** [comment] 2021-03-01 15:31
`generator client {
  provider      = "prisma-client-js"
  output        = "./src/database/generated/client"
  binaryTargets = ["native"]
}

datasource db {
  provider = "sqlite"
  url      = "file:./tactic-map.db"
}

// models
model DefaultSignGroup {
  id          Int       @id @default(autoincrement())
  title       String
  description String
  signs       DsgSign[]
}

model DsgSign {
  id          Int              @id @default(autoincrement())
  sign        String
  title       String
  description String
  dsgFK       Int
  dsg         DefaultSignGroup @relation(fields: [dsgFK], references: [id])
}
`
This error dissapear, I don`t know why and how))

**Comment by Jolg42** [comment] 2021-03-01 15:35
What do you mean by `This error dissapear, I dont know why and how`?

Does it work for you know? With the same Prisma version?

**Closed** 2021-03-10 15:33 UTC
Labels: bug/0-needs-info, kind/bug, team/migrations, topic: db push
