### ISSUE TITLE
[5.9.0] Getting strange types after generating

### ISSUE THREAD

**Issue by sillvva** [prisma/prisma#22903] opened 2024-01-31 18:45 UTC
### Bug description

After running `prisma generate` and restarting the TypeScript server, I am not getting types which match my models

### How to reproduce

I'm honestly not sure how to reproduce.

I have tried:
- Removing `node_modules` and `pnpm-lock.yaml`, reinstalling, and running `pnpm dlx prisma generate`
- Restarting the typescript server

### Prisma information

```prisma
model Character {
    id                  String   @id @unique @default(cuid())
    name                String
    race                String?
    class               String?
    campaign            String?
    image_url           String?
    character_sheet_url String?
    user                User     @relation(fields: [userId], references: [id])
    userId              String
    logs                Log[]
    created_at          DateTime @default(now())

    @@index([userId])
}
```

```ts
const character = await prisma.character.findFirst({
	// ^ any
	// Should be Character | undefined
	include: {
		user: true
	},
	where: { id: characterId }
});

export async function getCharacters(userId: string) {
	//                ^ Promise<$Public.PrismaPromise<T>>
	//                Should be Character[]
	return await prisma.character.findMany({
		where: { userId: userId }
	});
}
```

### Environment & setup

- OS: macOS
- Database: PlanetScale
- Node.js version: 21.5.0

### Prisma Version

```
5.9.0
```

**Comment by sillvva** [comment] 2024-01-31 19:05
Reverting back to Prisma Version 4.15.0 seems to have fixed it.

**Comment by jessethomson** [comment] 2024-01-31 20:26
I also ran into this issue where the prisma types stopping working after upgrading.

I was able to confirm that everything works in 5.8.0, but breaks in 5.9.0

I also tried deleting node_modules, npm installing, npx prisma generate, restarting TS Server in VSCode, etc, and nothing fixed it.

**Comment by mnemosx** [comment] 2024-01-31 20:30
Spent like the whole day trying to figure this out as this is the first time I'm trying to use prisma. I' m also getting all my prisma data typed as $Public.PrismaPromise<T>~

Using these versions:
    "@next-auth/prisma-adapter": "^1.0.7",
    "@prisma/client": "^5.9.0",
    "prisma": "^5.8.1",

**Comment by millsp** [comment] 2024-01-31 20:48
Hey @sillvva @jessethomson @mnemosx, thanks for the report.

Yes, we have been working on a fix as soon as we have seen the regression. We have a good amount of reports that say our fix is working, but I'd like to ask you if you could take the time to try out pour integration version for the fix?

If you want, please try it out by updating both `prisma` and `@prisma/client` to this integration version: `5.10.0-integration-fix-client-exports-map.14` (once, installed don't forget to run `prisma generate`).

I'd appreaciate if you can let me know how it went, thanks!

We are aiming for a patch release with these fixes.

**Comment by Lebraz98** [comment] 2024-01-31 21:08
rollback to 4.8.1 worked correctly

**Comment by millsp** [comment] 2024-01-31 22:50
@Lebraz98 if you have the time, could you please give [this](https://github.com/prisma/prisma/issues/22903#issuecomment-1919930108) a try? Thanks

**Comment by SergioDiez** [comment] 2024-01-31 23:00
Hi @millsp, I was experiencing the same issue with 3.9.0 and with the `5.10.0-integration-fix-client-exports-map.14` works totally fine.

**Comment by Lebraz98** [comment] 2024-01-31 23:31
@millsp  im sorry tomorrow i will check it

**Comment by YuhangGe** [comment] 2024-02-01 03:14
`5.9.0` breaks，and `5.10.0-integration-fix-client-exports-map.14` works fine.

**Comment by sillvva** [comment] 2024-02-01 03:58
Comments look promising. I'll give it a try once it's in stable

**Comment by LA** [comment] 2024-02-01 06:18
Similar to @mnemosx, I am new to Prisma and was starting to believe that it wasn't worth the hype because all the properties of my models were implicit any with no auto-completion. However, `5.10.0-integration-fix-client-exports-map.14` does fix this bug. It might be worth it to display this somewhere more prominent and/or update [the docs](https://www.prisma.io/docs/orm/prisma-client/type-safety) to be clear that the model itself is available as a type with all of its properties (not just the Select/Include/Query Specific Types/`export declare type Model` that isn't actually what's generated), so that it would be more clear that this was a bug and not just how Prisma works.

**Comment by thomaslenaour** [comment] 2024-02-01 08:39
I have the same issue; ever since I switched to version 5.9.0, my types no longer work and are all `any`

**Comment by janpio** [comment] 2024-02-01 10:40
@thomaslenaour @kinseyky1 Can you follow [this](https://github.com/prisma/prisma/issues/22903#issuecomment-1919930108) and see if this resolves your problem? If so, this will be fixed with 5.9.1 that will come out soon.

**Comment by thomaslenaour** [comment] 2024-02-01 10:46
> @thomaslenaour @kinseyky1 Can you follow [this](https://github.com/prisma/prisma/issues/22903#issuecomment-1919930108) and see if this resolves your problem? If so, this will be fixed with 5.9.1 that will come out soon.

Hey @janpio @millsp, I just tried https://github.com/prisma/prisma/issues/22903#issuecomment-1919930108 and it seems to be working fine on my end.

**Comment by abel-officener** [comment] 2024-02-01 11:25
5.10.0-integration-fix-client-exports-map.14 works fine.
I also checked in two repositories.

**Closed** 2024-02-01 13:18 UTC
Labels: bug/1-unconfirmed, kind/regression, tech/typescript, team/client, topic: typescript, topic: exports map, 5.9.0

**Comment by Jolg42** [comment] 2024-02-01 16:04
https://github.com/prisma/prisma/releases/tag/5.9.1 is now available with the fix ✨ 

Please create [a new issue](https://github.com/prisma/prisma/issues/new/choose) if you find a bug.
