### ISSUE TITLE
Re-Introspection Error: model.rs:174:64 Could not find relation field User on model Team.

### ISSUE THREAD

**Issue by do4gr** [prisma/prisma#9905] opened 2021-10-22 08:39 UTC
Command: `prisma db pull`
Version: `3.2.1`
Binary Version: `b71d8cb16c4ddc7e3e9821f42fd09b0f82d7934c`
Report: https://prisma-errors.netlify.app/report/13550 
OS: `x64 darwin 20.6.0`

JS Stacktrace:
```
Error: [libs/datamodel/connectors/dml/src/model.rs:174:64] Could not find relation field User on model Team.
    at ChildProcess.<anonymous> (/usr/local/lib/node_modules/prisma/build/index.js:43135:28)
    at ChildProcess.emit (events.js:315:20)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
```

Rust Stacktrace:
```
   0: backtrace::backtrace::trace
   1: backtrace::capture::Backtrace::new
   2: user_facing_errors::Error::new_in_panic_hook
   3: user_facing_errors::panic_hook::set_panic_hook::{{closure}}
   4: std::panicking::rust_panic_with_hook
   5: std::panicking::begin_panic_handler::{{closure}}
   6: std::sys_common::backtrace::__rust_end_short_backtrace
   7: _rust_begin_unwind
   8: core::panicking::panic_fmt
   9: core::option::expect_failed
  10: dml::model::Model::find_relation_field_mut
  11: sql_introspection_connector::re_introspection::enrich
  12: sql_introspection_connector::calculate_datamodel::calculate_datamodel
  13: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  14: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  15: <futures_util::future::either::Either<A,B> as core::future::future::Future>::poll
  16: <futures_util::future::future::Then<Fut1,Fut2,F> as core::future::future::Future>::poll
  17: <futures_util::future::either::Either<A,B> as core::future::future::Future>::poll
  18: introspection_engine::main::{{closure}}
  19: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  20: introspection_engine::main
  21: std::sys_common::backtrace::__rust_begin_short_backtrace
  22: std::rt::lang_start::{{closure}}
  23: std::rt::lang_start_internal
  24: std::rt::lang_start

```

**Comment by janpio** [comment] 2022-01-07 22:42
Probably duplicate of: https://github.com/prisma/prisma/issues/10453

**Comment by jkomyno** [comment] 2024-12-13 10:12
Hi there,
As part of our effort to clean up our GitHub repo, we’re closing this issue to help focus on features and improvements that align with our focus areas and those of our community. 

This issue was originally created for internal tracking purposes, but if you feel this is important to you, feel free to reopen the issue and get like-minded users to upvote as we will prioritize fixing issues based on community interest.

For more insight into our priorities and how we’re thinking about the future of Prisma, please see our blog post: https://www.prisma.io/blog/prisma-orm-manifesto.

Thank you for your understanding and support!

**Closed by jkomyno** 2024-12-13 10:12 UTC
Labels: bug/1-unconfirmed, kind/bug, topic: re-introspection, tech/engines, topic: error reporting, domain/schema, topic: postgresql, topic: prisma db pull
