### ISSUE TITLE
OR operator results in a query with AND

### ISSUE THREAD

**Issue by uselessdev** [prisma/prisma#19992] opened 2023-06-28 01:12 UTC
### Bug description

I'm writting the following code:

```ts
await db.event.findMany({
  where: {
    store: orgId,
    OR: {
      user: userId as string,
    },
  },
  orderBy: {
    createdAt: "desc",
  },
});
```

I am expect the code above creates a query with an OR operator as below:

`...FROM "public"."events" WHERE ("public"."events"."store" = $1 OR "public"."events"."user" = $2)...`

But the code results in a query if an AND operator:
`...FROM "public"."events" WHERE ("public"."events"."store" = $1 OR "public"."events"."user" = $2)...`

### How to reproduce

1. Write a similar code
2. see the result query

### Prisma information

```prisma
model Event {
  id        String       @id @default(uuid())
  payload   Json
  user      String
  action    EventActions
  store     String?
  createdAt DateTime     @default(now()) @map("created_at")

  @@map("events")
}
```

```ts
const events = await db.event.findMany({
  where: {
    store: orgId,
    OR: {
      user: userId as string,
    },
  },
  orderBy: {
    createdAt: "desc",
  },
});
```

### Environment & setup

- MacOS
- PostgreSQL (neon)
- v18.15.0

### Prisma Version

```
prisma                  : 4.16.1
@prisma/client          : 4.16.1
```

**Comment by Jolg42** [comment] 2023-06-28 08:20
Could you try running this very similar query?
```
await db.event.findMany({
  where: {
    store: orgId,
    OR: [
		{
      		user: userId as string,
    	},
	]
  },
  orderBy: {
    createdAt: "desc",
  },
});
```

Note: I think you might have forgotten to edit the query below `But the code results in a query if an AND operator:` because it's the same query as the previous one and doesn't mention `AND`

**Comment by uselessdev** [comment] 2023-06-28 17:54
Hi again @Jolg42 I tested with `OR: [{ user: userID }]` but the results is the same:

`...WHERE ("public"."events"."store" = $1 AND "public"."events"."user" = $2)...`

**Comment by SevInf** [comment] 2023-06-30 07:51
Hi @uselessdev 

`OR` syntax does not quite work that way. Query you want is:

```ts
await db.event.findMany({
  where: {
    OR: [
      { store: orgId },
      { user: userId as string}
    ]
  },
  orderBy: {
    createdAt: "desc",
  },
});
```

Top level keys of `where` always joined with `AND`, elements of `OR` are joined with `OR`.
So, what happens is your example is:

1. Elements of `OR` are joined. You have only one element, so `OR: { user: userId as string }` is equivalent to `{ user: userId as string }`
2. Elements of `where` are joined with `AND`. You have `{ user: userId as string }` (result of step 1) and `{ store: orgId }`, so you get `userId=<id> AND store = <orgId>` as a result.

See [examples for `OR`](https://www.prisma.io/docs/reference/api-reference/prisma-client-reference#or) in our docs.

I am going to close this issue, since there is no bug and your query works as intended.

**Closed by SevInf** 2023-06-30 07:51 UTC
Labels: bug/1-unconfirmed, kind/bug, tech/engines/query engine, team/client
