### ISSUE TITLE
PANIC: called `Option::unwrap()` on a `None` value in query-engine/core/src/response_ir/internal.rs:334:86

### ISSUE THREAD

**Issue by yassinebridi** [prisma/prisma#9795] opened 2021-10-15 13:35 UTC
Hi Prisma Team! My Prisma Client just crashed. This is the report:
## Versions

| Name            | Version            |
|-----------------|--------------------|
| Node            | v16.3.0            | 
| OS              | linux-musl         |
| Prisma Client   | 3.0.1              |
| Query Engine    | 0.1.0              |
| Database        | postgresql         |

## Logs
```
 sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine graphQLToJSError
prisma:client:request_handler Error: called `Option::unwrap()` on a `None` value
    at LibraryEngine.prismaGraphQLToJSError (/node_modules/@prisma/client/runtime/index.js:25128:14)
    at LibraryEngine.request (/node_modules/@prisma/client/runtime/index.js:25143:24)
    at async RequestHandler.request (/node_modules/@prisma/client/runtime/index.js:37288:24)
    at async ChatService.getAllRooms (/dist/src/chat/chat.service.js:69:20)
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
```

## Client Snippet
```ts
    try {
      return await this.prismaService.room.findMany({
        where: { members: { some: { id: { equals: user.id } } } },
        orderBy: { createdAt: 'desc' },
        take: 3,
        include: {
          proposal: true,
          members: {
            select: {
              avatar: true,
              firstName: true,
              lastName: true,
            }
          },
          messages: {
            orderBy: { createdAt: 'desc' },
            take: 1,
            include: { user: { select: myUserSelect } },
          },
        },
      });
    } catch (error) {
      this.logger.error(error);
      throw new InternalServerErrorException(
        "Oups! quelque chose s'est mal pass√© essaie encore",
      );
    }

```

## Error from try catch
```bash
Invalid `prisma.room.findFirst()` invocation:


  PANIC: called `Option::unwrap()` on a `None` value in query-engine/core/src/response_ir/internal.rs:334:86

This is a non-recoverable error which probably happens when the Prisma Query Engine has a panic.
```
happens with room.findFirst() and room.findMany()

I can't post the whole schema, but here is a snippet of models that have direct contact with rooms,
This error happens only with the rooms models and doesn't always happen.
The bigger issue is when this happens the whole app crashes down, even though I'm try-catching the error.

## Schema
```prisma
generator client {
  provider        = "prisma-client-js"
  previewFeatures = ["interactiveTransactions"]
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

generator nestjsDto {
  provider = "prisma-generator-nestjs-dto"
  output   = "../src/generated"
}

model User {
  id                   String                 @id @default(cuid())
  rooms                Room[]
  roomId               String?
  /// @DtoReadOnly
  createdAt            DateTime               @default(now())
  /// @DtoReadOnly
  updatedAt            DateTime               @updatedAt
}


model Room {
  id        String    @id @default(cuid())
  /// @DtoRelationRequired
  /// @DtoRelationCanConnectOnCreate
  members   User[]
  /// @DtoRelationRequired
  /// @DtoRelationCanConnectOnCreate
  proposal  Proposal?
  /// @DtoRelationRequired
  /// @DtoRelationCanConnectOnCreate
  offer     Offer?
  messages  Message[]
  /// @DtoReadOnly
  createdAt DateTime  @default(now())
  /// @DtoReadOnly
  updatedAt DateTime  @updatedAt
}
model Message {
  id                    String   @id @default(cuid())
  /// @DtoRelationRequired
  content               String
  emailNotificationSent Boolean? @default(false)
  user                  User     @relation(fields: [userId], references: [id])
  userId                String
  /// @DtoRelationRequired
  /// @DtoRelationCanConnectOnCreate
  room                  Room?    @relation(fields: [roomId], references: [id])
  roomId                String?
  /// @DtoReadOnly
  createdAt             DateTime @default(now())
  /// @DtoReadOnly
  updatedAt             DateTime @updatedAt
}

model Offer {
  id           String         @id @default(cuid())
  room               Room?      @relation(fields: [roomId], references: [id])
  roomId             String?
  isDeleted              Boolean                 @default(false)
  /// @DtoReadOnly
  createdAt              DateTime                @default(now())
  /// @DtoReadOnly
  updatedAt              DateTime                @updatedAt
  teacherAssignedOffers  TeacherAssignedOffers[]
}
model Proposal {
  id             String         @id @default(cuid())
  room           Room?          @relation(fields: [roomId], references: [id])
  roomId         String?
  createdAt      DateTime       @default(now())
  /// @DtoReadOnly
  updatedAt      DateTime       @updatedAt

}
```
## Prisma Engine Query
```
{"X":{}}
```

**Comment by baba43** [comment] 2021-11-01 12:14
I get the same error. Did you find a cause or solution?

**Comment by yassinebridi** [comment] 2021-11-01 13:28
Nope, I just made a workaround to fetch rooms from the user entity 🙃

**Comment by elie222** [comment] 2021-11-02 10:48
Not sure it's related, but we get Rust panic after a few minutes of making a lot of upserts:
https://github.com/prisma/prisma/issues/10049

**Comment by yassinebridi** [comment] 2021-11-02 11:35
Not sure if a query is too complex or has a lot of nested inclusion does this. It happened today for me with this query:
```ts
  async getMyOffers(
    resUser: User,
    filterPaginationDto: OfferFilterPaginationDto,
  ) {
    try {
      const user = await this.prismaService.user.findUnique({
        where: { id: resUser.id },
      });
      if (!user) {
        throw new NotFoundException("Cet utilisateur n'existe pas");
      }

      const { page = 1, limit = 10 } = filterPaginationDto;

      const skip = (+page - 1) * +limit;
      const take = +limit;

      const totalCount = await this.prismaService.offer.count({
        where: {
          isDeleted: false,
          student:
            user.role === 'student' ? { user: { id: resUser.id } } : undefined,
        },
      });
      const offers = await this.prismaService.offer.findMany({
        where: {
          isDeleted: false,
          student:
            user.role === 'student' ? { user: { id: resUser.id } } : undefined,
        },
        take,
        skip,
        orderBy: {
          createdAt: 'desc',
        },
        include: {
          acceptedProposal: {
            include: {
              teacher: {
                include: {
                  user: {
                    select: {
                      id: true,
                      email: true,
                      avatar: true,
                      firstName: true,
                      lastName: true,
                      createdAt: true,
                    },
                  },
                },
              },
            },
          },
          potentialProposals: {
            include: {
              teacher: {
                include: {
                  user: {
                    select: {
                      id: true,
                      email: true,
                      avatar: true,
                      firstName: true,
                      lastName: true,
                      createdAt: true,
                    },
                  },
                },
              },
            },
          },
          student: {
            include: {
              user: {
                select: {
                  id: true,
                  email: true,
                  avatar: true,
                  firstName: true,
                  lastName: true,
                  createdAt: true,
                },
              },
            },
          },
          subject: true,
          level: true,
          files: true,
        },
      });

      return {
        page: +page,
        limit: +limit,
        totalCount,
        results: offers,
      };
    } catch (error) {
      this.logger.error(error);
      throw new InternalServerErrorException(
        "Oups! quelque chose s'est mal pass√© essaie encore",
      );
    }
  }
```

**Comment by kissmystic** [comment] 2021-11-04 21:11
I get same error!

**Comment by janpio** [comment] 2021-11-10 16:52
Please everyone posting share everything that could influence the occurrence of this crash.

What is your Prisma version (`prisma -v`)?
What OS? What Node version? What database and version?
What is similar in the Prisma Client queries you are running?

And most important: Does anyone have a (kinda) reliable reproduction of what is happening?

**Comment by NickFoden** [comment] 2022-02-21 19:27
I ran into this error this morning when using mongodb and trying to connect records and forgetting to add the relations and object.ids array etc. 

https://www.prisma.io/docs/concepts/components/prisma-schema/relations/many-to-many-relations#mongodb

Adding the explicit relations to the schema with the array of ObjectId's and working great now. 

```
model Category {
  id      String   @id @default(dbgenerated()) @map("_id") @db.ObjectId
  postIDs String[] @db.Array(ObjectId) // had forgotten to add this value with string[] of ObjectId 
  posts   Post[]   @relation(fields: [postIDs]) // and this "@relation" 
}

**Comment by janpio** [comment] 2022-02-21 19:46
Interesting @NickFoden - Can you maybe split that off into its own issue and describe all the things you did so we can reproduce this in context of Prisma MongoDB? That would be neat. Thanks

**Comment by janpio** [comment] 2022-09-19 23:17
Hey @baba43 @elie222 @yassinebridi @kissmystic Are you still experiencing this problem? If so, can you please provide some additional information that will help us reproduce this so we can actually fix it? Otherwise we will have to close this issue. Thanks.

**Comment by elie222** [comment] 2022-09-20 05:56
We ended up solving it by removing nested inserts/updates and doing it in multiple steps within a transaction. A little annoying. I don't know if it's still an issue.

It's difficult to reproduce. I tried with a simple repo at the time but wasn't able to although the problem would happen consistently.

**Comment by janpio** [comment] 2022-09-20 10:35
Can you maybe still come up with a before (when it was failing) and after (your simplified version) of the Prisma Client queries? That might give some pointers what is going on and might also help the others in this thread see if they are doing similar things.

**Comment by janpio** [comment] 2022-10-19 17:17
Ping @baba43 @elie222 @yassinebridi @kissmystic again - can you maybe help us out here? Otherwise, we will need to close this issue although it seems to be a real problem. Thanks.

**Comment by janpio** [comment] 2022-11-25 00:11
Closing then until someone provides more information. Please comment or open a new issue. Thanks!

**Closed by janpio** 2022-11-25 00:11 UTC
Labels: bug/0-unknown, kind/bug, team/client, topic: basic error report, topic: rust panic, topic: postgresql
