### ISSUE TITLE
Update 2.4.1 break _OrderByInput type

### ISSUE THREAD

**Issue by vh13294** [prisma/prisma#3224] opened 2020-08-06 12:55 UTC
## Bug description

After New Update

<img width="1030" alt="Screen Shot 2020-08-06 at 7 50 18 PM" src="https://user-images.githubusercontent.com/17086745/89533919-5ed72d00-d81e-11ea-95c7-4a053c70bd6f.png">

The OrderByInput type doesn't accept array format. (I run prisma generated after update)

<img width="384" alt="Screen Shot 2020-08-06 at 7 52 08 PM" src="https://user-images.githubusercontent.com/17086745/89533961-70b8d000-d81e-11ea-9751-f376c6a05bb7.png">

## Environment & setup

- OS: Catalina 10.15.6
- Database: MySQL 8.0
- Node.js version: 12.18.3
- Prisma version:
```
@prisma/cli          : 2.4.1
Current platform     : darwin
```

**Comment by pantharshit00** [comment] 2020-08-06 15:20
Order by is `Enumerable` in when it is used in the args type:
![image](https://user-images.githubusercontent.com/22195362/89549634-30f5e680-d826-11ea-8b0d-8b9f1968156e.png)


Enumerable make it so you can pass an Array or a single top level object:
![image](https://user-images.githubusercontent.com/22195362/89549687-479c3d80-d826-11ea-8632-6ff00681ac7b.png)


So I can't reproduce this. I also going to close this, feel free to comment if you find anything wrong about it after the explanation.

**Closed by pantharshit00** 2020-08-06 15:20 UTC

**Comment by vh13294** [comment] 2020-08-06 15:37
<img width="1036" alt="Screen Shot 2020-08-06 at 10 37 04 PM" src="https://user-images.githubusercontent.com/17086745/89551645-5e965c00-d835-11ea-8a56-fb6b17ee7ab4.png">

**Comment by vh13294** [comment] 2020-08-06 15:38
I get it now... just declare the type as array i guess?

<img width="617" alt="Screen Shot 2020-08-06 at 10 38 05 PM" src="https://user-images.githubusercontent.com/17086745/89551779-8ab1dd00-d835-11ea-91e1-ff7f0866433e.png">

**Comment by pantharshit00** [comment] 2020-08-06 15:50
Yes, since you are declaring an array, you would need to annotate it with `[]`
