### ISSUE TITLE
Improperly formatted query doesn't throw an error

### ISSUE THREAD

**Issue by dickfickling** [prisma/prisma#6093] opened 2021-03-13 01:51 UTC
## Bug description

We had an improperly written query that didn't throw an error but caused unexpected behavior, where our `OR` block nested inside an `AND` block was an object instead of an array. The resulting query was not what we expected and difficult to debug.

## How to reproduce

The improperly formatted query:
```
    prisma.bucket.findMany({
      where: {
        AND: [
          { discoverability: BucketDiscoverability.PUBLIC },
          {
            OR: {
              name: { contains: query },
              description: { contains: query },
            },
          },
        ],
      },
  });
```

The sql string it created:
```
prisma:query SELECT `chums_test`.`Bucket`.`id`, `chums_test`.`Bucket`.`name`, `chums_test`.`Bucket`.`description`, `chums_test`.`Bucket`.`image`, `chums_test`.`Bucket`.`creatorId`, `chums_test`.`Bucket`.`discoverability`, `chums_test`.`Bucket`.`createdAt`, `chums_test`.`Bucket`.`updatedAt` FROM `chums_test`.`Bucket` WHERE (`chums_test`.`Bucket`.`discoverability` = ? AND ( `chums_test`.`Bucket`.`name` LIKE ? AND `chums_test`.`Bucket`.`description` LIKE ?))
```

## Expected behavior

Using an object for the `OR` clause failed silently. We'd have expected it to cause a type error or throw an exception.

The query we intended to write:
```    return prisma.bucket.findMany({
      where: {
        AND: [
          { discoverability: BucketDiscoverability.PUBLIC },
          {
            OR: [
              { name: { contains: query } },
              { description: { contains: query } }
            ],
          },
        ],
      },
    });
```

the sql we expected:
```SELECT `chums_test`.`Bucket`.`id`, `chums_test`.`Bucket`.`name`, `chums_test`.`Bucket`.`description`, `chums_test`.`Bucket`.`image`, `chums_test`.`Bucket`.`creatorId`, `chums_test`.`Bucket`.`discoverability`, `chums_test`.`Bucket`.`createdAt`, `chums_test`.`Bucket`.`updatedAt` FROM `chums_test`.`Bucket` WHERE (`chums_test`.`Bucket`.`discoverability` = ? AND (`chums_test`.`Bucket`.`name` LIKE ? OR `chums_test`.`Bucket`.`description` LIKE ?))```

## Prisma information

2.18.0

## Environment & setup

- OS: mac os
- Database: mysql 
- Node.js version: 15.9
- Prisma version:

```
prisma               : 2.18.0
@prisma/client       : 2.18.0
Current platform     : darwin
Query Engine         : query-engine da6fafb57b24e0b61ca20960c64e2d41f9e8cff1 (at node_modules/@prisma/engines/query-engine-darwin)
Migration Engine     : migration-engine-cli da6fafb57b24e0b61ca20960c64e2d41f9e8cff1 (at node_modules/@prisma/engines/migration-engine-darwin)
Introspection Engine : introspection-core da6fafb57b24e0b61ca20960c64e2d41f9e8cff1 (at node_modules/@prisma/engines/introspection-engine-darwin)
Format Binary        : prisma-fmt da6fafb57b24e0b61ca20960c64e2d41f9e8cff1 (at node_modules/@prisma/engines/prisma-fmt-darwin)
Studio               : 0.356.0

```

**Comment by pantharshit00** [comment] 2021-03-13 17:26
This is expected behavior of the API here. filters inside a single blocker of OR are joined by `AND` condition. The one thing we might do here is removing enumerable(ie `T | T[]`) from OR in nested level as well so that you will always have to provide an array to it. Right now this is displaying the intended behavior so I won't consider this as an bug but an improvement which is subject to some discussion.

**Comment by janpio** [comment] 2024-03-02 09:43
We haven't had any additional reports of this in the last 3 years, so it is safe to say that this is not the most pressing need. As we have hundreds of issues where we do get constant feedback and upvotes, it is not realistic for us to prioritize this one any time soon, sorry. 

I am closing this issue for now. If someone has a dire need for this, please comment below or open a new feature request. Thank you.

**Closed by janpio** 2024-03-02 09:43 UTC
Labels: kind/improvement, team/client, topic: client api
