### ISSUE TITLE
Field "OR" is not defined by type for $where

### ISSUE THREAD

**Issue by sahildeliwala** [prisma/prisma#4060] opened 2019-02-15 08:20 UTC
I'm following this tutorial: https://www.howtographql.com/graphql-js/8-filtering-pagination-and-sorting/
I'm using latest prisma (1.26) install locally in docker container with connected to MongoDB

![2019-02-15_1327](https://user-images.githubusercontent.com/10909011/52842598-91223580-3125-11e9-8c61-93af4e3f3552.png)

This is similar issue that was closed [2874](https://github.com/prisma/prisma/issues/2874) without any proper solution

**Comment by pantharshit00** [comment] 2019-02-15 09:05
MongoDB doesn't support `OR` right now as it is in preview.

Closing as a duplicate of https://github.com/prisma/prisma/issues/3897

**Closed by pantharshit00** 2019-02-15 09:05 UTC

**Comment by sahildeliwala** [comment] 2019-02-15 09:28
@pantharshit00 Okay, thanks!
