### ISSUE TITLE
Failed to detect linux distro + `Error: Unknown binaryTarget debian-openssl-0.0.x and no custom engine files were provided` after upgrading  from 4.8.1 to 4.9.0

### ISSUE THREAD

**Issue by n05la3** [prisma/prisma#17499] opened 2023-01-24 07:33 UTC
### Bug description

Previously, `prisma generate` worked well with my manjaro linux distro until after an update from  4.8.1 to 4.9.0. Here's the error I get when I try to do anything with prisma:
```
prisma:warn Prisma failed to detect the Linux distro in use, and may not work as expected. Defaulting to "debian".
Error: Unknown binaryTarget debian-openssl-0.0.x and no custom engine files were provided
```

This error is definitely related to the update, I still have branches without the update that work well.

### How to reproduce

After setting up a new prisma 4.9 project and installing the dependencies, run `prisma generate` in Manjaro linux distro.

### Expected behavior

Running `prisma generate`, should generate the prisma client.

### Prisma information

```prisma
generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

model User {
  id     String  @id
  name   String
}
```

### Environment & setup

- OS: 
DISTRIB_ID=ManjaroLinux
DISTRIB_RELEASE=22.0.0
DISTRIB_CODENAME=Sikaris
DISTRIB_DESCRIPTION="Manjaro Linux"
- Database: PostgreSQL
- Node.js version: 16.18.1
- openssl: OpenSSL 3.0.7 1 Nov 2022 (Library: OpenSSL 3.0.7 1 Nov 2022)

`ls /lib | grep ssl` gives:
```
libevent_openssl-2.1.so
libevent_openssl-2.1.so.7
libevent_openssl-2.1.so.7.0.1
libevent_openssl.so
libgnutls-openssl.so
libgnutls-openssl.so.27
libgnutls-openssl.so.27.0.2
libssl3.so
libssl.so
libssl.so.0.9.8
libssl.so.1.1
libssl.so.3
libxmlsec1-openssl.so
libxmlsec1-openssl.so.1
libxmlsec1-openssl.so.1.2.37
openssl-0.9.8
openssl-1.1
ossl-modules
```

Here's the os-release note from `/etc/os-release`
```
NAME="Manjaro Linux"
PRETTY_NAME="Manjaro Linux"
ID=musl
ID_LIKE=arch
BUILD_ID=rolling
ANSI_COLOR="32;1;24;144;200"
HOME_URL="https://manjaro.org/"
DOCUMENTATION_URL="https://wiki.manjaro.org/"
SUPPORT_URL="https://forum.manjaro.org/"
BUG_REPORT_URL="https://docs.manjaro.org/reporting-bugs/"
PRIVACY_POLICY_URL="https://manjaro.org/privacy-policy/"
LOGO=manjarolinux
```

### Prisma Version

```
4.9.0
```

**Comment by yusufkandemir** [comment] 2023-01-24 08:23
Might be related https://github.com/prisma/prisma/pull/17241

**Comment by kylerm42** [comment] 2023-01-24 15:52
Can confirm the same is happening with Arch as well. Seems related to this issue, so posting my output to these commands https://github.com/prisma/prisma/issues/17063#issuecomment-1368540752


1. `ls -l /usr/lib/x64-linux-gnu/libssl.so.1.1*`
`ls: cannot access '/usr/lib/x64-linux-gnu/libssl.so.1.1*': No such file or directory`
3. `openssl version`
`OpenSSL 1.1.1n  15 Mar 2022`
5. `ldconfig -p | grep ssl`
```
	libxmlsec1-openssl.so.1 (libc6,x86-64) => /usr/lib/libxmlsec1-openssl.so.1
	libxmlsec1-openssl.so (libc6,x86-64) => /usr/lib/libxmlsec1-openssl.so
	libwolfssl.so.35 (libc6,x86-64) => /usr/lib/libwolfssl.so.35
	libwolfssl.so (libc6,x86-64) => /usr/lib/libwolfssl.so
	libssl3.so (libc6,x86-64) => /usr/lib/libssl3.so
	libssl3.so (libc6) => /usr/lib32/libssl3.so
	libssl.so.3 (libc6,x86-64) => /usr/lib/libssl.so.3
	libssl.so.3 (libc6) => /usr/lib32/libssl.so.3
	libssl.so.1.1 (libc6,x86-64) => /usr/lib/libssl.so.1.1
	libssl.so (libc6,x86-64) => /usr/lib/libssl.so
	libssl.so (libc6) => /usr/lib32/libssl.so
	libgnutls-openssl.so.27 (libc6,x86-64) => /usr/lib/libgnutls-openssl.so.27
	libgnutls-openssl.so (libc6,x86-64) => /usr/lib/libgnutls-openssl.so
	libevent_openssl-2.1.so.7 (libc6,x86-64) => /usr/lib/libevent_openssl-2.1.so.7
	libevent_openssl-2.1.so (libc6,x86-64) => /usr/lib/libevent_openssl-2.1.so
```
4. `ls -l /lib64 | grep ssl`
Nothing
8. `ls -l /usr/lib64 | grep ssl`
Nothing

**Comment by lcdss** [comment] 2023-01-24 18:16
This is also happening with me, after I upgraded to 4.9.x, on my desktop with Arch Linux as well.

*`ls -r /lib64 | grep libssl.so`*
```
libssl.so.3
libssl.so
```

**`ldconfig -p | grep ssl`**
```
libxmlsec1-openssl.so.1 (libc6,x86-64) => /usr/lib/libxmlsec1-openssl.so.1
libxmlsec1-openssl.so (libc6,x86-64) => /usr/lib/libxmlsec1-openssl.so
libssl3.so (libc6,x86-64) => /usr/lib/libssl3.so
llibssl.so.3 (libc6,x86-64) => /usr/lib/libssl.so.3
libssl.so (libc6,x86-64) => /usr/lib/libssl.so
libgnutls-openssl.so.27 (libc6,x86-64) => /usr/lib/libgnutls-openssl.so.27
libgnutls-openssl.so (libc6,x86-64) => /usr/lib/libgnutls-openssl.so
libevent_openssl-2.1.so.7 (libc6,x86-64) => /usr/lib/libevent_openssl-2.1.so.7
libevent_openssl-2.1.so (libc6,x86-64) => /usr/lib/libevent_openssl-2.1.so
```

**Comment by janpio** [comment] 2023-01-24 20:29
@lcdss @kylerm42 Do you also get `Error: Unknown binaryTarget debian-openssl-0.0.x and no custom engine files were provided` as an error message? Or only the initial warning?

**Comment by lcdss** [comment] 2023-01-25 13:17
> @lcdss @kylerm42 Do you also get `Error: Unknown binaryTarget debian-openssl-0.0.x and no custom engine files were provided` as an error message? Or only the initial warning?

I don't recall seeing this warning, only the `prisma:warn Prisma failed to detect the Linux distro in use, and may not work as expected. Defaulting to "debian".` twice every prisma command I run.

**Comment by kylerm42** [comment] 2023-01-25 14:16
Same as above, no error, just the warning twice.

**Comment by janpio** [comment] 2023-01-25 15:46
Then you do not actually have the same problem as @n05la3. Yours is a warning that just gives you additional information that you were not given before. I you want to get rid of that, or disagree with this being useful, open a new issue please (and include similar inforamtion to what you provided here). That would be helpful. Thanks.

**Comment by DownloadableFox** [comment] 2023-01-25 19:41
Having the exact same problem in Arch Linux. No other warnings appear.

**Comment by Grahf0085** [comment] 2023-01-25 19:41
Same problem on arch.......TOO

**Comment by kylerm42** [comment] 2023-01-25 19:41
I've created this issue to track the warnings on Arch: https://github.com/prisma/prisma/issues/17545

**Comment by janpio** [comment] 2023-01-25 21:50
@lcdss @DownloadableFox  @Grahf0085 @Please comment over on #17545 

I nthis issue we will only track the `debian-openssl-0.0.x` related problem moving forward. Thanks.

**Comment by fmujakitz** [comment] 2023-02-02 21:34
I've had the same issue with `Error: Unknown binaryTarget debian-openssl-0.0.x and no custom engine files were provided`, and tracked it down to [getPlatform](https://github.com/prisma/prisma/blob/8ad76c3e04bd3d037e2258b6219d062d863ee00c/packages/get-platform/src/getPlatform.ts).

The problem is that the parsed `libsslVersion=0.0.x` on [L346](https://github.com/prisma/prisma/blob/8ad76c3e04bd3d037e2258b6219d062d863ee00c/packages/get-platform/src/getPlatform.ts#L346) is valid, but binaries for that version apparently do not exist.

`libsslVersion` should be checked against `supportedLibSSLVersions` on [L17](https://github.com/prisma/prisma/blob/8ad76c3e04bd3d037e2258b6219d062d863ee00c/packages/get-platform/src/getPlatform.ts#L17) and returned accordingly, which covers the case of preferring older versions.

Otherwise, it should fall back to `openssl version -v`, and return the latest.

Temp fix at `node_modules/@prisma/engines/dist/index.js`
```js
  if (libsslFilename) {
    debug2(`Found libssl.so file using "ldconfig" or other generic paths: ${libsslFilenameFromSpecificPath}`);
    const libsslVersion = parseLibSSLVersion(libsslFilename);
    if (libsslVersion && ['1.0.x', '1.1.x', '3.0.x'].includes(libsslVersion)) {
      return libsslVersion;
    }
  }`

**Comment by jkomyno** [comment] 2023-02-03 15:55
Hi everyone, Alberto from Prisma here. This issue should be fixed with `prisma@4.10.0`, which will be available starting from February 7th (next Tuesday). We're now explicitly checking that the `libssl` versions we parse match our set of supported versions, and we avoid parsing `libssl.so.0*` files altogether to avoid picking up very old `libssl` files that `prisma-engines` does not support.

Hope that helps!

----

I will keep this issue open until you can confirm that the issue is actually solved on your end as well. We've added new tests, but user validation is always welcome. If you're eager to try our fix before Tuesday, you may try `prisma@4.10.0-integration-libssl-avoid-0-x.1` (this is a development-only/unstable Prisma version, please don't use it in production, only use it to confirm this issue is fixed)

**Closed** 2023-02-06 12:05 UTC
Labels: bug/2-confirmed, kind/bug, team/schema, topic: engine download

**Comment by jkomyno** [comment] 2023-02-06 13:29
Hi @n05la3, could you please confirm that [this solution](https://github.com/prisma/prisma/issues/17499#issuecomment-1416061100) works for you?

Moreover, could you please paste here the result of `npx prisma@4.8.1 version` on your Manjaro system?

And, to better understand how we can explicitly add a test for this issue into our [ecosystem-tests](https://github.com/prisma/ecosystem-tests/tree/dev/docker), do you recall whether you had manually installed a few `libssl` versions in your system?

**Comment by fmujakitz** [comment] 2023-02-06 18:25
@jkomyno yes, works, detected as `debian-openssl-3.0.x`

**Comment by n05la3** [comment] 2023-02-09 06:35
This is great. @jkomyno, I can confirm that this now works smoothly. I did try to install different versions of `libssl` in a bit to workaround this issue, none of which worked. At the point of writing this, all these changes have been reverted.

Here's the output from running  `npx prisma@4.8.1 version`:
```
Environment variables loaded from .env
prisma                  : 4.8.1
@prisma/client          : 4.8.1
Current platform        : debian-openssl-3.0.x
Query Engine (Node-API) : libquery-engine d6e67a83f971b175a593ccc12e15c4a757f93ffe (at ../../node_modules/.pnpm/@prisma+engines@4.8.1/node_modules/@prisma/engines/libquery_engine-debian-openssl-3.0.x.so.node)
Migration Engine        : migration-engine-cli d6e67a83f971b175a593ccc12e15c4a757f93ffe (at ../../node_modules/.pnpm/@prisma+engines@4.8.1/node_modules/@prisma/engines/migration-engine-debian-openssl-3.0.x)
Introspection Engine    : introspection-core d6e67a83f971b175a593ccc12e15c4a757f93ffe (at ../../node_modules/.pnpm/@prisma+engines@4.8.1/node_modules/@prisma/engines/introspection-engine-debian-openssl-3.0.x)
Format Binary           : prisma-fmt d6e67a83f971b175a593ccc12e15c4a757f93ffe (at ../../node_modules/.pnpm/@prisma+engines@4.8.1/node_modules/@prisma/engines/prisma-fmt-debian-openssl-3.0.x)
Format Wasm             : @prisma/prisma-fmt-wasm 4.8.0-61.d6e67a83f971b175a593ccc12e15c4a757f93ffe
Default Engines Hash    : d6e67a83f971b175a593ccc12e15c4a757f93ffe
Studio                  : 0.479.0
```

**Comment by omnaladkar** [comment] 2023-10-13 15:16
Prisma doesn't know which engines to download for the Linux distro "org.freedesktop.platform". Falling back to Prisma engines built "debian".
Please report your experience by creating an issue at https://github.com/prisma/prisma/issues so we can add your distro to the list of known supported distros i  am getting this problem vould you pls help me out

**Comment by janpio** [comment] 2023-10-13 21:20
@omnaladkar Open a new issue please as the error message suggest. Thanks.
