### ISSUE TITLE
Silence "Start using Prisma Client.."

### ISSUE THREAD

**Issue by tones31** [prisma/prisma#21857] opened 2023-11-09 00:18 UTC
## Problem

I run the generate command each time I start up my api as it's just easier. But I really don't need to see this every time

```
Start using Prisma Client in Node.js (See: https://pris.ly/d/client)
import { PrismaClient } from '@prisma/client'
const prisma = new PrismaClient()
or start using Prisma Client at the edge (See: https://pris.ly/d/accelerate)
import { PrismaClient } from '@prisma/client/edge'
const prisma = new PrismaClient()
See other ways of importing Prisma Client: http://pris.ly/d/importing-client
```

## Suggested solution

Please let me silence this output like `prisma generate --silent`

**Comment by janpio** [comment] 2023-11-09 09:28
Duplicate of https://github.com/prisma/prisma/issues/3390

**Closed by janpio** 2023-11-09 09:28 UTC
