### ISSUE TITLE
Suggested to modify the model

### ISSUE THREAD

**Issue by lglie** [prisma/prisma#2402] opened 2020-05-10 03:09 UTC
## Problem
The schema files of large applications are very large, and the relationships between models are complex. When modifying a field, the relevant relationships will change, which is particularly troublesome to modify

## Solution

1.Only write one side of relationship recommendation.
2.Object fields can also be used as unique constraints, not just scalar fields.
3.The foreign key is specified as the field name + ID suffix, not written in the model.
4.Optional field mark “?” Follow the field name.
5.Support schema file splitting into multiple.

```prisma
model User {
id Int @id
}

model Profile {
id     Int @id
user User.profile?
}

model Post {
id         Int @id
author User.posts[]
}

model Category {
id Int @id
posts Post[].categories[]
}
```
## Alternatives
```prisma
model User {
id          Int @id
profile? Profile.user
posts    Post[].author
}

model Profile {
id Int @id
}

model Post {
id Int @id
categories Category[].posts[]
}

model Category {
id Int @id
}
```

**Comment by pantharshit00** [comment] 2021-06-11 09:38
Duplicate of https://github.com/prisma/prisma/issues/2220

**Closed by pantharshit00** 2021-06-11 09:38 UTC
Labels: kind/discussion, team/client, topic: schema
