### ISSUE TITLE
npx prisma db push throws  Invalid version: "0.1.0.6"

### ISSUE THREAD

**Issue by agcty** [prisma/prisma#13243] opened 2022-05-08 14:51 UTC
### Bug description

I'm following this example https://docs.planetscale.com/tutorials/prisma-quickstart but everytime I try to run "npx prisma db push" it throws:

```
Environment variables loaded from .env
Error: Invalid version: "0.1.0.6"
```

Super weird error, doesn't tell me anything.

### How to reproduce

Run "npx prisma db push"

### Expected behavior

Pushes to the db

### Prisma information

```
datasource db {
  provider = "mysql"
  url      = env("DATABASE_URL")
  referentialIntegrity = "prisma"
}

generator client {
  provider = "prisma-client-js"
  previewFeatures = ["referentialIntegrity"]
}

model Star {
  id              Int       @default(autoincrement()) @id
  createdAt       DateTime  @default(now())
  updatedAt       DateTime  @updatedAt
  name            String    @db.VarChar(255)
  constellation   String    @db.VarChar(255)
}
```

### Environment & setup

- OS: 
- Database: 
- Node.js version: 

Macos 12.3.1
Planetscale
Node 16.1.0

### Prisma Version

npx prisma -v results in same error

**Comment by janpio** [comment] 2022-05-09 10:57
Did you set a version manually to `0.1.0.6` somewhere by chance?

**Comment by andyle83** [comment] 2022-05-20 10:14
Really annoying error. Same problem in here.

**Comment by andyle83** [comment] 2022-05-20 10:42
Found issue caused by version in package.json

**Comment by janpio** [comment] 2022-05-23 19:04
What exactly was the error @andyle83? Might help others to figure this out and fix it as well.

**Comment by pantharshit00** [comment] 2022-07-14 07:47
Ping @andyle83. Please provide the request information in order to move this forward.

**Comment by segheysens** [comment] 2022-08-17 03:56
I don't know why Prisma looks at this value, but that version is the `"version"` property you have in your project's top level `package.json`. 

For example, I received the error with `"version": "0.1"` and `"version": "1.0"`, but this is a personal project for right now, so I removed that property from my `package.json` and the CLI command worked fine. I'd like to reintroduce that value eventually, like when I hope to onboard another developer onto the project in the near future, but don't need it for now.

**Comment by segheysens** [comment] 2022-08-17 03:57
@janpio ^ any thoughts would be appreciated! I think there are duplicate Issues that might see the same resolution with this workaround.

**Comment by janpio** [comment] 2022-08-20 01:06
So the theory is that setting an "invalid" (non semver MAJOR.MINOR.PATCH) version in the project's `package.json` file leads to an error when running `npx prisma db push`?

**Comment by Bruce-Hopkins** [comment] 2022-08-27 07:21
I get the same error when I running `prisma generate`. If when I remove the version of the `package.json` it seems to work fine.

**Comment by marsidorowicz** [comment] 2022-08-31 10:46
same here

**Comment by Cimorexave** [comment] 2023-04-20 09:44
Currently on version 4.13.0 and having the same problem. All commands fail with the Error: Invalid version: "1.0". Deleting the prisma version from package.json file didn't help either.

**Comment by uzair9990** [comment] 2023-09-12 12:55
**FINALLY FIXED IT!**

For me the issue was with my package.json file. When doing "npm init", somehow the version was added as: "0.1." When I changed it to "0.1.0", then it started working fine.

The correct pkg.json is as follows:

![image](https://github.com/prisma/prisma/assets/51513047/349141d8-8556-4dfc-8bde-e142d1c7c21b)

**Comment by Poet9** [comment] 2023-11-06 09:36
I think it is referring to your application version because it should be "0.1.0"  instead of "0.1.0.6" or you can use "0.1.6" the most important is to respect the convention of only having three numbers to specify a version (Major revision. Minor revision. Bug fix). Like the previous comment specify.

**Comment by Noxillio** [comment] 2023-11-27 00:22
Still an issue after a year and a half, PLEASE stop checking app version. Not everyone uses nor wants to use semver. Totally breaks applications that have a different versioning scheme. Absolutely no reason to be checking it in the first place, incredibly frustrating and utterly ridiculous.

**Comment by peschee** [comment] 2024-01-03 08:04
I think this is a non-issue, since changing the version to a valid semver version (which `package.json` requires anyway to be valid) does not trigger the error.

**Comment by Jolg42** [comment] 2024-01-08 13:34
Closing as a duplicate of https://github.com/prisma/prisma/issues/7317 which is confirmed.

**Closed by Jolg42** 2024-01-08 13:34 UTC
Labels: bug/1-unconfirmed, kind/bug, topic: cli, topic: generator, topic: prisma generate, team/schema, team/client, topic: prisma db push, topic: database-provider/planetscale
