### ISSUE TITLE
Issue with running Prisma Client in a Nextjs Application

### ISSUE THREAD

**Issue by jvcmarcenes** [prisma/prisma#7022] opened 2021-05-11 06:31 UTC
### Bug description

I'm writing a Nextjs application which uses Prisma to generate and communicate to a database. I am running into the following error: 
```
PrismaClientInitializationError2 [PrismaClientInitializationError]:
Invalid `prisma.post.findMany()` invocation:


  Query engine exited with code 101

thread 'main' panicked at 'Could not open datamodel file "E:\\joao\\code-web\\next-firebase-auth\\.next\\server\\pages\\schema.prisma"', query-engine\query-engine\src\opt.rs:184:53
stack backtrace:
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
    at cb (E:\joao\code-web\next-firebase-auth\node_modules\@prisma\client\runtime\index.js:35104:17)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async getServerSideProps (E:\joao\code-web\next-firebase-auth\.next\server\pages\index.js:483:17)
    at async renderToHTML (E:\joao\code-web\next-firebase-auth\node_modules\next\dist\next-server\server\render.js:40:215)
    at async E:\joao\code-web\next-firebase-auth\node_modules\next\dist\next-server\server\next-server.js:111:97
    at async E:\joao\code-web\next-firebase-auth\node_modules\next\dist\next-server\server\next-server.js:104:142
    at async DevServer.renderToHTMLWithComponents (E:\joao\code-web\next-firebase-auth\node_modules\next\dist\next-server\server\next-server.js:136:387)
    at async DevServer.renderToHTML (E:\joao\code-web\next-firebase-auth\node_modules\next\dist\next-server\server\next-server.js:137:610)
    at async DevServer.renderToHTML (E:\joao\code-web\next-firebase-auth\node_modules\next\dist\server\next-dev-server.js:36:578) {
  clientVersion: '2.22.1',
  errorCode: undefined
}
```
whenever I try to run the app with `next dev`.
I have tried generating the Prisma client in a dedicated file, and importing where needed, generating the client in the api routes, and generating the client in the getServerSideProps method in a page route. they all returned the same error (with a different location for the datamodel file that could not be opened)

- I am aware prisma has some issues with yarn2, however I am using npm
- the database is being generated, as I am able to interact with it through Prisma Studio

### How to reproduce

1. create a next app `npx create-next-app .`
2. configure prisma and prisma client
3. try instantiating the prisma client and performing queries

### Expected behavior

Expected behaviour was for the app not to crash

### Prisma information

schema:
```
datasource db {
  provider = "sqlite"
  url      = env("DATABASE_URL")
}

generator client {
  provider = "prisma-client-js"
}

model User {
  uid      String   @id
  email    String?  @unique
  name     String?
  provider String?
  photoUrl String?
  posts    Post[]
  comments Comment[]
}

model Post {
  id        String    @id @default(cuid())
  author    User      @relation(fields: [authorId], references: [uid])
  authorId  String
  title     String
  content   String
  createdAt DateTime  @default(now())
  comments  Comment[]
}

model Comment {
  id       String @id @default(cuid())
  author   User   @relation(fields: [authorId], references: [uid])
  authorId String
  content  String
  post     Post   @relation(fields: [postId], references: [id])
  postId   String
}
```

### Environment & setup

- OS: Windows 8.1
- Database: SQLite
- Node.js version: 14.15.4
- Prisma version: 
```
prisma               : 2.22.1
@prisma/client       : 2.22.1
Current platform     : windows
Query Engine         : query-engine 60cc71d884972ab4e897f0277c4b84383dddaf6c (at node_modules\@prisma\engines\query-engine-windows.exe)
Migration Engine     : migration-engine-cli 60cc71d884972ab4e897f0277c4b84383dddaf6c (at node_modules\@prisma\engines\migration-engine-windows.exe)
Introspection Engine : introspection-core 60cc71d884972ab4e897f0277c4b84383dddaf6c (at node_modules\@prisma\engines\introspection-engine-windows.exe)
Format Binary        : prisma-fmt 60cc71d884972ab4e897f0277c4b84383dddaf6c (at node_modules\@prisma\engines\prisma-fmt-windows.exe)
Default Engines Hash : 60cc71d884972ab4e897f0277c4b84383dddaf6c
Studio               : 0.379.0
```

**Comment by janpio** [comment] 2021-05-11 21:35
> I also fail to understand why the schema file would need to be accessed during runtime, since by then the prisma client and the database model has already been generated, I'd like to understand the reason behind this behaviour too

The error message you are getting here is from the Query Engine, which does _not_ have the schema baked in (as it is a binary) but receives its path and then reads it to get the information from that. So that is quite normal.

What is not normal, is that this path is wrong and can not be read. 
The `.next` folder is where Nextjs puts it build artifacts, which might indeed be rewritten and modified heavily. But usually that still just work under the hood.

**Comment by Ovyerus** [comment] 2021-05-14 05:04
I believe this issue may be due to the use of Webpack 5 (which Next enables by default with an empty/missing config).

You can easily disable this by creating a `next.config.js` with any config you need - or if you don't have any config besides this, you can just do:
```js
module.exports = {
  future: {
    webpack5: false
  }
}
```

Tested on a new project I've been getting this issue on - disabled Webpack 5 in the config with the above and the API runs correctly, and setting `webpack5: true` instead brings back the `code 101` issue.

What's weird is that in another, older Next project, I upgraded Next and Prisma to latest version to test this, and even when forcing `webpack5: true` it doesn't error out there, which is interesting.

**Comment by jvcmarcenes** [comment] 2021-05-14 05:29
> I believe this issue may be due to the use of Webpack 5 (which recent versions of Next enables by default with an empty/missing config).
> 
> You can easily disable this by creating a `next.config.js` with any config you need - or if you don't have any config besides this, you can just do:
> 
> ```js
> module.exports = {
>   future: {
>     webpack5: false
>   }
> }
> ```

I did try this, but it resulted in another error and I just disregarded that solution at the time. However, now that I went to check what the error was, it turned out to be a date parsing error. The query engine didn't crash like before, after removing the date fields from the query it worked
The issue is in relation to webpack5 then

guess for now I'll just use webpack4

**Comment by janpio** [comment] 2021-05-18 18:38
Can someone maybe easily create a _simple_ minimal reproduction project using Webpack 5 that shows this crash? Would make our investigation and reproduction much faster.

**Comment by jvcmarcenes** [comment] 2021-05-18 23:42
> 
> 
> Can someone maybe easily create a _simple_ minimal reproduction project using Webpack 5 that shows this crash? Would make our investigation and reproduction much faster.

here it is: [jvcmarcenes/prisma-nextjs-webpack5](https://github.com/jvcmarcenes/prisma-nextjs-webpack5)

the index page, '/', will call getServerSideProps, to fetch data from the endpoint /api/comments
the endpoint handler will make a query to the PrismaClient, instantiate at prisma/index.ts
the application works if the api endpoint doesn't make a Prisma query

**Comment by pantharshit00** [comment] 2021-05-27 18:22
@jvcmarcenes You are importing the client from wrong location which messes up the webpack annotation we have. 

Please change the `prisma/index.ts` file to the following:
```ts
import { PrismaClient, Prisma } from "@prisma/client";

async function main() {
  const prisma = new PrismaClient({
    log: ["query"],
  });

  const ids = [1, "2);SELECT 1;SELECT (1", 3];
  const garages = await prisma.$queryRaw(
    `SELECT grg.id FROM public.garage as grg where grg.id in (${ids})`
  );
  console.log(garages);
  prisma.$disconnect();
}

main();
```

After this change, I was able to run the app:
![image](https://user-images.githubusercontent.com/22195362/119877406-9f876a80-bf46-11eb-80f0-3ae524c7e126.png)


I am going to close this.

**Closed** 2021-05-27 18:22 UTC
Labels: bug/0-needs-info, bug/1-repro-available, kind/bug, team/client, topic: nextjs, topic: windows
