### ISSUE TITLE
Investigate GCR Panic

### ISSUE THREAD

**Issue by pantharshit00** [prisma/prisma#2242] opened 2020-04-20 16:18 UTC
## Bug description
**Quoted from https://github.com/prisma/prisma/issues/1559#issuecomment-609405886 by @mufasa71** 

I have the same issues in cloud run
![image](https://user-images.githubusercontent.com/626420/78482694-74402b80-7746-11ea-802b-01c942c89ad2.png)

I can stable reproduce it. It works with simple query like getting 3-4 records from db. Throwing panic when i fetch over 300 records from db.

I use:
```
"@prisma/cli": "^2.0.0-beta.1",
"@prisma/client": "^2.0.0-beta.1"
```

## How to reproduce
(Yet to get a proper reproduction, needs more investigation)

## Expected behaviour

Query engine should not panic

**Comment by mufasa71** [comment] 2020-04-21 17:37
@pantharshit00 I can't reproduce it anymore, lets close it

**Closed** 2020-04-22 02:22 UTC
Labels: bug/1-repro-available, kind/bug, team/support
