### ISSUE TITLE
Index on type text

### ISSUE THREAD

**Issue by btodorce** [prisma/prisma#6063] opened 2021-03-11 15:37 UTC
## How to reproduce

1. Using mariadb, create an index on a field of type text
2. Run prisma introspect
3. Run prisma generate
4. Prisma generate would fail, since index can not exists on field of type text

## Expected behavior

The incorrectly setup index index should be commented out in the model and a console warning be displayed

## Environment & setup

OS: Windows
Database: mariadb
Node.js version: 14.5.4
Prisma version:2.17.0

**Comment by janpio** [comment] 2021-03-11 17:49
Can you show the code you are using to "create an index on a field of type text"?

**Comment by btodorce** [comment] 2021-03-11 18:37
When we tried integrating prisma to use for some of our surfaces the issue we faced was a dozen or  so errors, which most of them had no real impact but prevented us from using and running prospect which was essential to keep up with the db changes.

ALTER TABLE `x` ADD FULLTEXT KEY `z` (`y`);

**Comment by Jolg42** [comment] 2021-03-17 13:37
Seems like a duplicate of https://github.com/prisma/prisma/issues/5434

**Comment by pantharshit00** [comment] 2021-05-17 13:09
Closing as duplicate of https://github.com/prisma/prisma/issues/5434

**Closed by pantharshit00** 2021-05-17 13:09 UTC
Labels: status/needs-action, team/migrations, topic: introspection, topic: mariadb
