### ISSUE TITLE
intermittent mobc timeout / error creating database connection

### ISSUE THREAD

**Issue by shrugs** [prisma/prisma#2782] opened 2020-06-17 03:46 UTC
## Bug description

Occasionally (in spurts, it seems) my prisma-client-js will have some trouble establishing a database connection, resulting in an error report of:

```
Error in connector: Error creating a database connection. (Operation timed out (mobc timeout))
```

There's usually at least two of these errors reported to my error tracking service with nearly identical timestamps (sometimes up to 20), though the backtraces don't provide much context. Most of the time connections are established and everything functions fine - this is a <1% occurrence, it seems.

```
Error in connector: Error creating a database connection. (Operation timed out (mobc timeout))

    index.js 1 request(...)
    [NODE_MODULES]/@prisma/client/runtime/index.js:1:in `request'
    unknown ? runMicrotasks(...)
    unknown:?:in `runMicrotasks'
    task_queues.js 97 processTicksAndRejections(...)
    internal/process/task_queues.js:97:in `processTicksAndRejections'
```

<img width="1070" alt="image" src="https://user-images.githubusercontent.com/1535001/84849594-a95cda00-b023-11ea-8681-538c6f04d091.png">

Related issues i've read: #1559 #882 #283

## How to reproduce

In lieu of a reproduction (sorry! 🙏), here's what my setup looks like, and perhaps it will shed light on the potential issue. I'm running the latest prisma as part of a next.js project hosted on vercel (that is: running on AWS lambda). it talks to a relatively beefy `db.r5.large` RDS aurora (postgres compat) instance that should support something like 1600 concurrent db connections according to aws docs. my connection string includes the `?connection_limit=1` best practice for serverless environments, and the RDS monitoring reports a peak of 100 db connections and trivial cpu/memory usage (single percents).

The connection errors always occur when resolving a graphql field, (i'm using apollo-server-micro to provide a serverless graphql endpoint). The number of errors doesn't seem to correlate to how many fields are being resolved (i.e. i've received 4 errors for a single top-level field, all presumably from the same lambda execution.

One direction this could be going: given that graphql execution could create a cascading series of queries, i'm worried that this is being caused by a deeply nested query creating a bunch of `findOne' requests, which is overloading the connection pooler or something (forgive my lack of understanding about what's actually happening behind the scenes). I read that the dataloader pattern has been implemented as part of the engine (and confirmed that batch SELECTs were being issues to my database in development) so i'm not sure _why_ a nested graphql query would overload a connection, perhaps it's a start?

## Expected behavior

There shouldn't be connection timeouts when spinning up additional lambdas or waking sleeping lambdas, given the available resources in the database.

## Environment & setup

- OS: Vercel's Lambda Env
- Database: Aurora w/ Postgres
- Prisma version: `@prisma/client@2.0.0`
- Node.js version: Latest LTS `12.x`

**Comment by pantharshit00** [comment] 2020-06-17 07:56
Mobc is the connection pooling library that we use in the engines: https://github.com/importcjj/mobc


As a first step in debugging this can you please share how you are initializing you Prisma instance? Also check how many active connections that your database has.

**Comment by shrugs** [comment] 2020-06-18 02:25
My initialization looks something like

```ts
// at the top level of the module

const prisma = new PrismaClient();
// [...other singleton inits for context]


const context: ContextFunction<MicroContext, Context> = async (
  ctx: MicroContext,
): Promise<Context> => {
  return {
    ...ctx,
    prisma,
    //  ... other context values
  };
};

const apolloServer = new ApolloServer({
  schema,
  introspection: true,
  subscriptions: false,
  playground: true,
  context,
  // TODO: seems to be a type mismatch between apollo-server-core and apollo-server-plugin-base
  plugins: [new SimpleApolloLogger() as any],
  formatError,
});

export const config = {
  api: {
    bodyParser: false,
  },
};

export default apolloServer.createHandler({ path: '/api/graphql' });
```

afaik, this means there should be a single `new PrismaClient` per lambda, kept alive between re-used invocations

here's the RDS graph of maximum connections over the last 24 hours

<img width="1478" alt="image" src="https://user-images.githubusercontent.com/1535001/84970516-dcb56c80-b0e8-11ea-8d4e-aa37a6dedc1c.png">

thoughts?

**Comment by pimeys** [comment] 2020-06-23 10:25
I'd take a look into some things in your setup first:

- Try defining a different `connect_timeout` in your connection string. The default is 5 seconds (which should be enough to get a new connection, but...).
- Again, try to see what kind of queries you're spawning. If you send a crazy amount of `findOne` queries and we only have one connection in the pool, there is a good chance some of the countless queries will just time out due to the heavy traffic all fighting for the same connection.

You can try setting `LOG_QUERIES=true` to your environment and see from the logs what queries and how many were running in the database when these errors were happening.

**Comment by shrugs** [comment] 2020-06-25 02:37
I've gone ahead and updated my connection params to `?connection_limit=3&connect_timeout=10` in advance of some planned production traffic - will report back on frequency of errors, if any.

**Comment by Sytten** [comment] 2020-06-25 16:29
Looking at it, you top the 100 connections mark two times. Can you correlate that with the timeouts? Maybe you RDS database just doesn't have the capacity to have that many connections. I would reduce the connection limit to 1 too since you probably only have one concurrent request per lambda anyway. Maybe consider using an [RDS proxy](https://aws.amazon.com/rds/proxy/) too, that would help your database.

**Comment by shrugs** [comment] 2020-06-25 22:55
10 hours later after 500k `/api/graphql` hits, i haven't seed a `mobc` error in our logs while using that `?connection_limit=3&connect_timeout=10` config. That said, our logs haven't seen the error since 3 days ago, so I'm not _exactly_ sure what that tells us. 

Our RDS connects topped out at 800 concurrent connections, and cpu usage stayed nice.

**Connections**
![image](https://user-images.githubusercontent.com/1535001/85802524-1c94d900-b713-11ea-964a-ecd3f6db5aac.png)

**CPU**
![image](https://user-images.githubusercontent.com/1535001/85803453-2f101200-b715-11ea-897a-c2e06e280dcf.png)

**Comment by shrugs** [comment] 2020-06-25 23:01
Ok I think I figured it out. The last time we saw the error was monday at 10:40am ET. Checked the git logs for what I pushed that morning:

```
Author: Matt Condon (shrugs)
Date:   Mon Jun 22 11:09:41 2020 -0400

    fix: permissions loop on login?
```

I was causing a redirect loop on the login page by accessing a permissioned route, which triggered a redirect to the same login page...which probably quickly created `browser's-max-redirect-loop-threshold` `findOne` queries against the db, hitting that bottleneck you described, @pimeys.

If this sounds like the cause and solution to y'all, feel free to close the issue! Though perhaps there's a DX-related action item that could spawn from my terrible javascript that would help others in the future?

**Comment by pantharshit00** [comment] 2020-06-26 06:18
Yes, we are going to close this now as there is no isolated reproduction here. 

That being said, thanks for taking time to write this and reporting back your metrics. That can be super helpful for someone else 💚

**Closed by pantharshit00** 2020-06-26 06:18 UTC
Labels: bug/0-needs-info, kind/bug, topic: observability, topic: serverless

**Comment by pantharshit00** [comment] 2020-06-26 08:36
Opened https://github.com/prisma/prisma/issues/2864 for improving this error message

**Comment by Sytten** [comment] 2020-06-26 12:56
I am impressed by the 800 concurrent connections, either aurora is better than I anticipated or you got a very big machine.

**Comment by shrugs** [comment] 2020-06-27 18:20
@Sytten it's a pretty big db relatively (`db.r5.large`), but i'm burning AWS credits so i didn't really think too hard about it 😅 

you can see their advertised connection count here: https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/AuroraPostgreSQL.Managing.html

![image](https://user-images.githubusercontent.com/1535001/85929223-09a01700-b881-11ea-9dd1-4c1abebbdd7d.png)

it's beefy but at the same time the high connection limit is pretty necessary for a serverless backend if one doesn't want to manage connection pooling with pgbouncer.

**Comment by alfonmga** [comment] 2020-11-24 11:53
I'm experiencing the same issue `Error creating a database connection. (Operation timed out (mobc timeout))` and I have been tweaking the `connect_timeout` and `socket_timeout` parameters in my connection string but looks like it has no effect even when I change them to _absurd_ values (9999 seconds): instead I get the timeout error right away without waiting for the defined timeout value. May this be a bug?

Here's the connection string I'm using on prod:
```text
postgresql://fastmessage-io:<pw>@amgaventures-do-user-8339649-0.b.db.ondigitalocean.com:25061/fastmessage-io?sslmode=require&pgbouncer=true&connection_limit=1&connect_timeout=10&socket_timeout=10
```

This how Prisma is instanced (I'm using [Blitz.js](https://github.com/blitz-js/blitz)):
```ts
import { PrismaClient } from "@prisma/client"
export * from "@prisma/client"

let prisma: PrismaClient

if (process.env.NODE_ENV === "production") {
  prisma = new PrismaClient()
} else {
  // Ensure the prisma instance is re-used during hot-reloading
  // Otherwise, a new client will be created on every reload
  globalThis["prisma"] = globalThis["prisma"] || new PrismaClient()
  prisma = globalThis["prisma"]
}

export default prisma
```

Prisma client version: `2.11.0`

**Comment by pantharshit00** [comment] 2020-11-25 07:56
@alfonmga Please open a new issue about this 🙏

**Comment by adaddeo** [comment] 2021-01-07 01:19
We are running into this with an RDS Serverless instance in our staging environment that scales down to 0 and then takes about 30 seconds to warm up when a new connection is requested. The initial error makes sense but it doesn't look like a re-connection is ever attempted. We have to restart the process to get reconnected.
