### ISSUE TITLE
Expected type NullableStringFieldUpdateOperationsInput, found string

### ISSUE THREAD

**Issue by timi-codes** [prisma/prisma#3717] opened 2020-09-21 07:52 UTC
I would like to update a field in my database using the mutation below. It seems to work when I update the `username` 
with a null value.

```
mutation UpdateUser {
  updateProfile(where: { email: "tejumoladavid@gmail.com" }, 
data: {
    username: "timi"
  }){
    username
    email
  }
}

```

I'm using

- "@prisma/cli": "2.7.1"
- "@prisma/client": "^2.7.1"
- "nexus-plugin-prisma": "0.19.0"

**Comment by timi-codes** [comment] 2020-09-21 08:00
I saw a related issue at #3653 about upgrading to "@prisma/cli": "^2.7" but that doesn't work for me

**Comment by pantharshit00** [comment] 2020-09-22 04:47
Hi,

Thanks for reporting this! It has already been reported before, so I am going to close this as a duplicate of https://github.com/graphql-nexus/nexus-plugin-prisma/issues/830

**Closed by pantharshit00** 2020-09-22 04:47 UTC
