### ISSUE TITLE
Nested query does not return full payload

### ISSUE THREAD

**Issue by namnguyen2496** [prisma/prisma#19125] opened 2023-05-08 03:02 UTC
### Bug description
Prisma query with nested include clause returns output with missing field.

### How to reproduce
Run the code below.

### Expected behavior
I expected the code below to return a `TransactionRecord` object with nested `externalAddress` field, but it does not (the `externalAddress` field is missing).

### Prisma information

```prisma
model TransactionRecord {
  id        String   @id @default(cuid())
  createdAt DateTime @default(now())
  updatedAt DateTime @updatedAt
  
  subtransfer Subtransfer[]

  @@map("transaction_records")
}

model Subtransfer {
  id        String   @id @default(cuid())
  createdAt DateTime @default(now())
  updatedAt DateTime @updatedAt

  transactionId  String
  transactionRecord TransactionRecord @relation(fields: [transactionId], references: [id])
  
  ledgerAccountToId String
  ledgerAccountTo   LedgerAccount @relation("subtransferToLedgerAccount", fields: [ledgerAccountToId], references: [id])

  ledgerAccountFromId String
  ledgerAccountFrom   LedgerAccount @relation("subtransferFromLedgerAccount", fields: [ledgerAccountFromId], references: [id])

  @@map("subtransfers")
}

model LedgerAccount {
  id        String   @id @default(cuid())
  createdAt DateTime @default(now())
  updatedAt DateTime @updatedAt

  externalAddress ExternalAddress

  @@map("ledger_accounts")
}

model ExternalAddress {
  id        String   @id @default(cuid())
  createdAt DateTime @default(now())
  updatedAt DateTime @updatedAt

  address String

  ledgerAccountId String?        @unique
  ledgerAccount   LedgerAccount? @relation(fields: [ledgerAccountId], references: [id])

  @@map("external_addresses")
}
```
### Client code
```ts
const transaction = await prisma.transactionRecord.findUnique({
   where: {
      id
   },
   include: TRANSACTION_RECORD_INCLUDES
})

const LEDGER_ACCOUNT_INCLUDES = {
  include: {
    externalAddress: true,
  }
};

const TRANSACTION_RECORD_INCLUDES = {
 subtransfers: {
    include: {
      ledgerAccountTo: LEDGER_ACCOUNT_INCLUDES,
      ledgerAccountFrom: LEDGER_ACCOUNT_INCLUDES
    }
  }
};
```
However, the client code returns the output with `externalAddress` field if I set:
```ts
const TRANSACTION_RECORD_INCLUDES = {
 subtransfers: {
    include: {
      ledgerAccountTo: {
         include: {
           externalAddress: true
         }
      },
      ledgerAccountFrom: {
         include: {
           externalAddress: true
         }
      }
    }
  }
};
```
**Why do I get different query results if the include clauses in two cases essentially evaluate to the same string?**

### Environment & setup
- OS: macOS
- Database: PostgreSQL
- Node.js version: `16.15.1`

### Prisma Version
```
4.12.0
```

**Comment by IIapad0ks** [comment] 2024-02-08 10:35
any updates? 😅

**Comment by janpio** [comment] 2024-02-21 01:46
The described problem does not really make sense. The both `include` payloads should be identical when they reach Prisma. Are you saying @namnguyen2496 (and @IIapad0ks) that this is not the case, and that we should try to reproduce the code above and will get different query results?

**Comment by IIapad0ks** [comment] 2024-02-27 08:00
> The described problem does not really make sense. The both `include` payloads should be identical when they reach Prisma. Are you saying @namnguyen2496 (and @IIapad0ks) that this is not the case, and that we should try to reproduce the code above and will get different query results?

sorry, it works for me now, it was my fault
I had a different one problem, return type and return data was different, but it is ok now too 🤔

**Comment by Weakky** [comment] 2024-08-22 09:15
Hey @IIapad0ks,

We're closing this issue as you've found a workaround. Thanks for reporting nonetheless.

**Closed by Weakky** 2024-08-22 09:15 UTC
Labels: bug/1-unconfirmed, kind/bug, topic: prisma-client, topic: relations, domain/client, topic: postgresql, topic: findUnique(), topic: nested read
