### ISSUE TITLE
`createMany()` does not exist when a model has an `Unsupported()` field on PostgreSQL

### ISSUE THREAD

**Issue by rs-nikic** [prisma/prisma#21756] opened 2023-11-03 07:57 UTC
I'm using postgreSQL, still facing the same issue.

```prisma
datasource db {
  provider = "postgresql"
  url      = env("PG_CONNECTION_STRING")
}

model node_locations {
  NodeId String @unique(map: "node_locations_id_idx") @default(dbgenerated("gen_random_uuid()")) @db.Uuid
  ExternalId String @unique(map: "node_locations_ext_id_idx")
  Name String
  Description String
  Geometry Unsupported("geometry(Point, 4326)")
  Meta Json
  Provider String
  Species String[]
  Status String
  LastPing DateTime

  @@index([Geometry], name: "node_locations_geometry_idx", type: Gist)
}
```

Prisma version: 5.5.2

Note: `prisma db push` is used for code generation 

![image](https://github.com/prisma/prisma/assets/143053594/81a1b7d1-02e1-4591-82f7-2829b147883c)

_Originally posted by @rs-nikic in https://github.com/prisma/prisma/issues/11507#issuecomment-1791963064_

**Comment by Jolg42** [comment] 2023-11-03 09:07
Thanks! I could reproduce this, only when using the `Geometry Unsupported("geometry(Point, 4326)")` field, after removing it, `createMany` was available.

```prisma
generator client {
  provider        = "prisma-client-js"
  previewFeatures = ["postgresqlExtensions"]
}

datasource db {
  provider   = "postgresql"
  url        = "postgresql://postgres:password@localhost:5492/21756"
  extensions = [postgis]
}

model node_locations {
  NodeId      String                               @unique(map: "node_locations_id_idx") @default(dbgenerated("gen_random_uuid()")) @db.Uuid
  ExternalId  String                               @unique(map: "node_locations_ext_id_idx")
  Name        String
  Description String
  Geometry    Unsupported("geometry(Point, 4326)")
  Meta        Json
  Provider    String
  Species     String[]
  Status      String
  LastPing    DateTime

  @@index([Geometry], name: "node_locations_geometry_idx", type: Gist)
}
```

And I randomly found a Postgis docker file on my computer to try it with `docker compose up -d`
```
version: "3.6"
services:
  pgDB:
    image: postgis/postgis:13-3.1-alpine
    restart: always
    ports:
      - "5492:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: geoexample
volumes:
  db_data:
```

**Comment by rs-nikic** [comment] 2023-11-03 09:14
Thanks for the confirmation @Jolg42 Any other work around until it gets addressed?

**Comment by Jolg42** [comment] 2023-11-03 09:18
@rs-nikic So this is actually expected and somehow documented, though we will try to update the docs a bit in the future
https://www.prisma.io/docs/reference/api-reference/prisma-schema-reference#unsupported
https://www.prisma.io/docs/concepts/components/prisma-schema/data-model#unsupported-types

You can make your `Unsupported` field optional as a workaround like this
```prisma
Geometry    Unsupported("geometry(Point, 4326)")?
```
The `create*` and `update*` methods would work again.

About the `Unsupported` field you will have to use raw queries, see:
https://www.prisma.io/docs/concepts/components/prisma-client/raw-database-access#unsupported-types

**Comment by Jolg42** [comment] 2023-11-03 09:21
I will close this since it's expected.
Follow the PostGIS support issue for Prisma Client https://github.com/prisma/prisma/issues/2789

**Closed by Jolg42** 2023-11-03 09:21 UTC
Labels: bug/2-confirmed, kind/bug, team/client, topic: postgresql, topic: createMany(), topic: Unsupported
