### ISSUE TITLE
PANIC in query-engine/core/src/interpreter/query_interpreters/nested_read.rs:78:561

### ISSUE THREAD

**Issue by mhmdAljefri** [prisma/prisma#6187] opened 2021-03-19 16:59 UTC
Hi Prisma Team! My Prisma Client just crashed. This is the report:
## Versions

| Name            | Version            |
|-----------------|--------------------|
| Node            | v12.16.1           | 
| OS              | debian-openssl-1.1.x|
| Prisma Client   | 2.12.1             |
| Query Engine    | query-engine cf0680a1bfe8d5e743dc659cc7f08009f9587d58|
| Database        | undefined|

## Query
```
query {
  findManyOffer(
    where: {
      country: {
        suspend: false
      }
    }
    skip: 5
  ) {
    users {
      id
    }
  }
}
```

## Logs
```
engine       at Socket.onSocketClose (//node_modules/@prisma/client/runtime/index.js:27537:33)
  prisma:engine       at Socket.emit (events.js:311:20)
  prisma:engine       at TCP.<anonymous> (net.js:668:12) {
  prisma:engine     name: 'SocketError',
  prisma:engine     code: 'UND_ERR_SOCKET'
  prisma:engine   }
  prisma:engine }  
  prisma:engine {
  prisma:engine   error: Error: connect ECONNREFUSED 127.0.0.1:36593
  prisma:engine       at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1137:16) {
  prisma:engine     errno: 'ECONNREFUSED',
  prisma:engine     code: 'ECONNREFUSED',
  prisma:engine     syscall: 'connect',
  prisma:engine     address: '127.0.0.1',
  prisma:engine     port: 36593
  prisma:engine   }
  prisma:engine }  
  prisma:engine { cwd: '/db' }  
  prisma:engine Search for Query Engine in //node_modules/.prisma/client  
  plusX Execution permissions of /node_modules/.prisma/client/query-engine-debian-openssl-1.1.x are fine  
  prisma:engine { flags: [ '--enable-raw-queries', '--port', '38501' ] }  
  prisma:engine stdout  Starting a postgresql pool with 5 connections.  
  prisma:engine stdout  Started http server on http://127.0.0.1:38501  
  prisma:engine Search for Query Engine in //node_modules/.prisma/client  
  plusX Execution permissions of //node_modules/.prisma/client/query-engine-debian-openssl-1.1.x are fine  
  prisma:engine Client Version: 2.12.1  
  prisma:engine Engine Version: query-engine cf0680a1bfe8d5e743dc659cc7f08009f9587d58  
  prisma:engine Active provider: undefined  
  prisma:engine stdout  PANIC in query-engine/core/src/interpreter/query_interpreters/nested_read.rs:78:56
1  
  prisma:engine TypeError: this.currentRequestPromise.cancel is not a function
  prisma:engine     at NodeEngine.handlePanic (/node_modules/@prisma/client/runtime/index.js:29249:36)
  prisma:engine     at NodeEngine.setError (/node_modules/@prisma/client/runtime/index.js:29195:16)
  prisma:engine     at LineStream.<anonymous> (/node_modules/@prisma/client/runtime/index.js:29480:24)
  prisma:engine     at LineStream.emit (events.js:311:20)
  prisma:engine     at addChunk (_stream_readable.js:294:12)
  prisma:engine     at readableAddChunk (_stream_readable.js:275:11)
  prisma:engine     at LineStream.Readable.push (_stream_readable.js:209:10)
  prisma:engine     at LineStream.Transform.push (_stream_transform.js:152:32)
  prisma:engine     at LineStream._pushBuffer (/node_modules/@prisma/client/runtime/index.js:26388:19)
  prisma:engine     at LineStream._transform (/node_modules/@prisma/client/runtime/index.js:26382:10)
  prisma:engine     at LineStream.Transform._read (_stream_transform.js:191:10)
  prisma:engine     at LineStream.Transform._write (_stream_transform.js:179:12)
  prisma:engine     at doWrite (_stream_writable.js:441:12)
  prisma:engine     at writeOrBuffer (_stream_writable.js:425:5)
  prisma:engine     at LineStream.Writable.write (_stream_writable.js:316:11)
  prisma:engine     at Socket.ondata (_stream_readable.js:714:22)
  prisma:engine     at Socket.emit (events.js:311:20)
  prisma:engine     at addChunk (_stream_readable.js:294:12)
  prisma:engine     at readableAddChunk (_stream_readable.js:275:11)
  prisma:engine     at Socket.Readable.push (_stream_readable.js:209:10)
  prisma:engine     at Pipe.onStreamRead (internal/stream_base_commons.js:186:23)  {"timestamp":"Mar 19 19:55:22.587","level":"ERROR","fields":{"message":"PANIC","reason":"1","file":"query-engine/core/src/interpreter/query_interpreters/nested_read.rs","line":78,"column":56},"target":"query_engine"}  
  prisma:engine {
  prisma:engine   error: SocketError: closed
  prisma:engine       at Socket.onSocketClose (/node_modules/@prisma/client/runtime/index.js:27537:33)
  prisma:engine       at Socket.emit (events.js:311:20)
  prisma:engine       at TCP.<anonymous> (net.js:668:12) {
  prisma:engine     name: 'SocketError',
  prisma:engine     code: 'UND_ERR_SOCKET'
  prisma:engine   }
  prisma:engine }  
```

## Client Snippet
```ts
// PLEASE FILL YOUR CODE SNIPPET HERE
```

## Schema
```prisma
// PLEASE ADD YOUR SCHEMA HERE IF POSSIBLE
```

**Comment by pantharshit00** [comment] 2021-05-20 13:46
Hey @mhmdAljefri 

Sorry for late reply here. 

Can you please provide more information regarding how we can reproduce this crash if this is still reproducible in the latest version? The query code and schema file would be appreciated here.

**Comment by mhmdAljefri** [comment] 2021-05-26 22:25
Sorry @pantharshit00 I don't remember how to reproduce this issue.

**Comment by pantharshit00** [comment] 2021-05-27 06:14
Closing as duplicate of https://github.com/prisma/prisma/issues/7007

**Closed by pantharshit00** 2021-05-27 06:14 UTC
Labels: bug/0-needs-info, kind/bug, team/client, topic: basic error report
