### ISSUE TITLE
Schema folder preview feature can create multiple databases

### ISSUE THREAD

**Issue by dthyresson** [prisma/prisma#24912] opened 2024-07-30 14:07 UTC
### What's not working?

In RedwoodJS we notice odd behavior with the schema folder after supporting the feature in 15.5.

In short, multiple SQLite databases could be created depending on relative paths and working directories.

Thus the migration would run on one database and he client generate on the second -- this meant the app when when using the generated client didn't have any tables and queries failed.

We think it might happen when Prisma initiates a connection to the database, doesn't find and thus creates a new one.

We worked with @jharrell to reproduce and have a repo to showcase it.

See: https://github.com/redwoodjs/redwood/issues/11008 (content below):

This isn't strictly a bug in redwood but I am creating this issue to track what we want to do about the new behaviour (if we care to do anything at all).

In prisma v15.6.0 they made some breaking changes to the multi file schema preview feature:
>* When using relative paths in Prisma Schema files with the prismaSchemaFolder feature, a path is now relative to the file it is defined in rather than relative to the prisma/schema folder. This means that if you have a generator block in /project/prisma/schema/config/generator.prisma with an output of ./foo the output will be resolved to /project/prisma/schema/config/foo rather than /project/prisma/foo. The path to a SQLite file will be resolved in the same manner.
>* We realized that during migration many people would have prisma/schema as well as prisma/schema.prisma. Our initial implementation looked for a .prisma file first and would ignore the schema folder if it exists. This is now an error.

We added support for this in redwood recently. There was a slight difference in behaviour when I tested the multi file schema behaviour before and after the upgrade. The location that the database file resolves to is different. 

If you setup the test project you'll get a sqlite database file in the standard spot. If you now enable prisma multi file schema and then perform some action like `yarn rw prisma migrate reset` you'll observe a new database file generated in a different location. This is mentioned in prisma's first point above.

The result of following the reproduction steps below. Observe multiple database files:
<img width="371" alt="image" src="https://github.com/user-attachments/assets/7cd64aba-18a0-470e-becb-c6acec89be2d">

Maybe this is just something users should expect given prisma have changed their behaviour and we have nothing to do here? Perhaps we should add documentation to highlight this to our users? 

I'll leave it up to @dthyresson to how to go forward but happy if you want to just close this as expected behaviour. 

### How do we reproduce the bug?

* Create a new test project
* Follow the docs to setup multi file schema
* Run `yarn rw prisma migrate reset`
* Observe the new database file generated

### How to reproduce

ere's a non-redwood reproduction of the issue we were seeing: https://github.com/Josh-Walker-GM/prisma-multi-file-issue-repro.

Note we worked with @jharrell and confirmed reproduction case.

### Expected behavior

1. Database not duplicated
2. Client geenrated correctly

### Prisma information

See rep for schema

### Environment & setup

OSX, SQLite, RedwoodJs 7.7.3+, Prisma 15.6.x. See repo for setup.

### Prisma Version

```
 Prisma 15.6.x
```

**Comment by SevInf** [comment] 2024-07-31 08:20
Hi @dthyresson!
It looks like this is a duplicate of #24647.
It was fixed a couple of weeks ago, but not yet released. `5.18.0` will be the first version with this fix. You can also test `5.18.0-integration-fix-config-dir-client.5` version to verify that fix works for you.

**Comment by dthyresson** [comment] 2024-07-31 10:49
> Hi @dthyresson! It looks like this is a duplicate of #24647. It was fixed a couple of weeks ago, but not yet released. `5.18.0` will be the first version with this fix. You can also test `5.18.0-integration-fix-config-dir-client.5` version to verify that fix works for you.

Interesting. I don’t think we tried v18

@jharrell is this a different than issue or related to the findings you had with the test project  that we shared?

**Comment by Josh-Walker-GM** [comment] 2024-08-06 22:47
I just tested this with 5.18.0 and the issue appears to be fixed. Thanks!

**Comment by apolanc** [comment] 2024-08-07 09:51
I'll now close this issue as complete. Thanks!

**Closed by apolanc** 2024-08-07 09:51 UTC
Labels: bug/2-confirmed, kind/bug, domain/client, topic: prismaSchemaFolder
