### ISSUE TITLE
Extending one to one relations

### ISSUE THREAD

**Issue by kierangilliam** [prisma/prisma#3032] opened 2020-07-15 19:40 UTC
## Problem
It would be nice to be able to define a named relation that can belong to one of several other named relations. This is best explained in an example:

There are multiple stages that contain details like when the stage began. Each `Stage` should have exactly one `StageDetails` and each `StageDetails` should have exactly one `Stage`. Right now, this must be modeled by polluting the `StageDetails` model.  

```
model StageDetails {
  id    String   @id @default(cuid())
  child Stage    @relation("child")
  teen Stage    @relation("teen")
  adult Stage    @relation("adult")
  began DateTime
}

model Stage {
  id      String       @id @default(cuid())
  child   StageDetails @relation(name: "child", fields: [childID], references: [id])
  childID String
  teen    StageDetails @relation(name: "teen", fields: [teenID], references: [id])
  teenID  String
  adult   StageDetails @relation(name: "adult", fields: [adultID], references: [id])
  adultID String
}
```

This is unfavorable because we cannot guarantee that `StageDetails` points to exactly one `Stage`.

## Suggested solution
Using some sort of logical or to relate to one of many relations.

```
model StageDetails {
  id    String   @id @default(cuid())
  stage Stage    @relation("child | teen | adult")
  began DateTime
}

model Stage {
  ...
}
```

**Comment by pantharshit00** [comment] 2020-07-16 07:40
Hi,

Thanks for reporting this! It has already been reported before, so I am going to close this as a duplicate of https://github.com/prisma/prisma/issues/1644

**Closed by pantharshit00** 2020-07-16 07:40 UTC
