### ISSUE TITLE
Client seems to ignore Custom Binary Specification

### ISSUE THREAD

**Issue by do4gr** [prisma/prisma#3499] opened 2020-09-02 08:12 UTC
I tried testing the Client with a custom QE binary. I first specified it via the .env file. 
The **CLI** correctly picked up the custom binary as shown by the `prisma --version` command. 
But the **client** kept routing calls to the binary in the node_modules folder.

I confirmed this via deleting the node_modules binary. 
The CLI kept working, ts-code failed complaining about a missing binary in the node_modules folder. 

I then tried 
```
const prisma = new PrismaClient({
  __internal: { enginePath: 'custom_binary_path' }
} as any )
```

But this still failed while looking into the node_modules folder. 

My expected behavior would be that if I specify a binary in the .env file this is used by the CLI AND the Client.

**Comment by pantharshit00** [comment] 2020-09-02 11:38
I can confirm this.

**Comment by timsuchanek** [comment] 2020-09-30 14:12
I tried to reproduce and use
```
env PRISMA_QUERY_ENGINE_BINARY="$PWD/query-engine-debian-openssl-1.1.x" ts-node main.ts
```
in fish shell, it's 
```
PRISMA_QUERY_ENGINE_BINARY="$PWD/query-engine-debian-openssl-1.1.x" ts-node main.ts
```
in bash. That worked. I'll try the constructor now.

You can check, which engine path the client resolves with this script:

```ts
import { PrismaClient } from '@prisma/client'

async function main() {
  const prisma = new PrismaClient()


  const data = await prisma.user.findMany()
  console.log(data)
  const anyPrisma = prisma as any
  console.log(anyPrisma._engine.prismaPath)
  console.log(await anyPrisma._engine.getPrismaPath())
  prisma.$disconnect()
}

main()
```

**Comment by timsuchanek** [comment] 2020-09-30 14:14
For the constructor variant, it's not `  __internal: { enginePath: 'custom_binary_path' }`, but `    __internal: { engine: { binaryPath: path.join(__dirname, 'custom_binary_path') } }`.

This works for me:

```ts
import { PrismaClient } from '@prisma/client'
import path from 'path'

async function main() {
  const prisma = new PrismaClient({
    __internal: { engine: { binaryPath: path.join(__dirname, 'query-engine-debian-openssl-1.1.x') } }
  } as any)

  const data = await prisma.user.findMany()
  console.log(data)
  const anyPrisma = prisma as any
  console.log(anyPrisma._engine.prismaPath)
  console.log(await anyPrisma._engine.getPrismaPath())
  prisma.$disconnect()
}

main()

```

**Comment by timsuchanek** [comment] 2020-09-30 14:14
I'll close this for now, let me know if you can't make it work.

**Closed by timsuchanek** 2020-09-30 14:14 UTC
Labels: bug/2-confirmed, kind/bug, team/typescript, topic: binary, topic: prisma-client, topic: tests

**Comment by janpio** [comment] 2020-10-12 11:08
@pantharshit00 and @do4gr - can you please take another look with the information @timsuchanek posted above?
