### ISSUE TITLE
Foreign key migrations not idempotent on MySQL on windows

### ISSUE THREAD

**Issue by yazer79** [prisma/prisma#7767] opened 2021-06-19 12:14 UTC
### Bug description

The migrate dev is considering its own changes from last migration as drift 

When I run "prisma migrate dev":
Your database is now in sync with your schema.
And then running "prisma migrate dev" again right after:

? Drift detected: Your database schema is not in sync with your migration history.

```
[*] Changed the `main` table
  [+] Added foreign key on columns (id1)

[*] Changed the `main` table
  [+] Added foreign key on columns (id2)
```

migration sql:
```
-- AddForeignKey
ALTER TABLE `main` ADD FOREIGN KEY (`id1`) REFERENCES `ext_table1`(`id`) ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `main` ADD FOREIGN KEY (`id2`) REFERENCES `ext_table2`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;
```

### How to reproduce

1.  Run `prisma migrate dev`
2.  Run `prisma migrate dev`
3.  See error

### Expected behavior

Migration to run smoothly with no errors notifying that there are "no changes" in schema or db

### Environment & setup

- OS: Win10
- Database: MySQL
- Node.js version: 12

### Prisma Version

```
2.25.1
```

**Comment by pantharshit00** [comment] 2021-06-21 12:24
@yazer79 

Can you please share your schema and changes you made to it? Also, please tell us if you are running MySQL directly on windows or via docker.

**Comment by yazer79** [comment] 2021-06-23 11:06
@pantharshit00 
I am running MySQL directly
I have a production db that i am trying to use prisma with. I had some errors in the db before as it is a very old db. And I am getting prisma migrate errors popping up every while even if i fix things. It is very hard.
After I fixed migration issues, and ran prisma migrate. I got no error and it was fine. I immediately ran migrate again without any changes, and the last migrate seem to have added the foreign keys and it considered its own additions as drift.

**Comment by yazer79** [comment] 2021-06-23 11:10
should I use migrate deploy only in production databases even if I am developing locally?

**Comment by tomhoule** [comment] 2021-06-23 12:23
> should I use migrate deploy only in production databases even if I am developing locally?

Yes. You can use `deploy` in development if you want, although `migrate dev` also applies migrations, but you shouldn't use `migrate dev` in production.

**Comment by yazer79** [comment] 2021-06-23 21:26
So I shouldn't use migrate dev locally? that is the cause of the problem?

**Comment by tomhoule** [comment] 2021-06-24 05:21
MySQL on windows in general has serious problems (not only with Prisma) because it changes the table names to be lowercase under the hood. I would suggest using `migrate dev`, if possible on a MySQL in WSL or docker, since you are probably deploying to linux.

In general, developing on windows MySQL and deploying to a unix-like OS (Linux, ...) is buggy.

Note that this is also a prisma bug, the foreign key should not be recreated. But I think we have tests for that already, so any context and detail is helpful to reproduce the problem.

**Comment by tomhoule** [comment] 2021-07-01 09:30
This issue can't move forward without more info, I think. We should attempt a reproduction. @yazer79 would sharing your schema be possible?

**Comment by yazer79** [comment] 2021-07-11 19:20
I can't share the whole db or schema as it is a production private website. But I can share any general structure or table examples. Would that help?

**Comment by pantharshit00** [comment] 2021-07-11 20:37
Yeah, share any minimal reproduction for that bug.

**Comment by yazer79** [comment] 2021-07-13 09:51
Can I share my schema privately? and how?

**Comment by yazer79** [comment] 2021-07-17 12:11
Any response please? My work is halted because I can't change my database

**Comment by pantharshit00** [comment] 2021-07-18 19:16
The best thing you can do here if you can't change the database is change its configuration to not to lowercase table names: https://dev.mysql.com/doc/refman/8.0/en/identifier-case-sensitivity.html and https://stackoverflow.com/questions/8550789/where-to-change-the-value-of-lower-case-table-names-2-on-windows-xampp

Ideally I will recommend using docker.

**Comment by janpio** [comment] 2021-09-17 19:53
Hey @yazer79, did you figure this out? If not, send the schema to jan@prisma.io and I can make sure we try to reproduce the problem you are experiencing. Thanks.

**Comment by yazer79** [comment] 2021-09-18 18:55
@janpio 
I stopped using "prisma migrate dev" completely and was using prisma db push to add new tables, today I got this from prisma db push:
```
Error: Database error
Error querying the database: Server error: `ERROR HY000 (1215): Cannot add foreign key constraint'
   0: sql_migration_connector::sql_database_step_applier::apply_migration
             at migration-engine\connectors\sql-migration-connector\src\sql_database_step_applier.rs:11
   1: migration_core::api::SchemaPush
             at migration-engine\core\src\api.rs:161
```
And I don't even know where is the problem

**Comment by janpio** [comment] 2021-09-20 10:05
Please open a separate issue for the new problem, this does not sound related.

**Comment by Weakky** [comment] 2023-07-13 14:15
Hey @yazer79,

We'd really need a small reproduction repository for us to move this issue forward. Without your Prisma Schema and a migration history, it's fairly hard to reproduce your issue.

Thanks a lot 🙏

**Comment by jharrell** [comment] 2023-08-07 16:17
Hello again, 

Without further info we'll have to close this issue. Please feel free to leave a comment and/or open a new issue with the information requested above.

Thank you!

**Closed by jharrell** 2023-08-07 16:17 UTC
Labels: bug/0-unknown, kind/bug, topic: windows, tech/engines, status/needs-action, topic: mysql, team/schema, topic: foreign keys
