### ISSUE TITLE
prisma.dmmf missing @db.varChar(20) info

### ISSUE THREAD

**Issue by RobertCZ** [prisma/prisma#22157] opened 2023-11-29 08:04 UTC
We generate Zod validator out of Prisma scheme but unfortuntely best we can do with

```
name String @db.VarChar(20)
````

is validator

```
name: z.string()
```

because DMMF doesnt have info about native DB filed type. Generating automatically

```
name: z.string().max(20)
```

would be more ergonomic. 

Would it be possible to add info about `@db` field type to prisma.dmmf?

https://github.com/chrishoermann/zod-prisma-types/issues/214

**Comment by janpio** [comment] 2024-02-15 23:33
Thanks for opening an issue, this is a duplicate of https://github.com/prisma/prisma/issues/10252

**Closed by janpio** 2024-02-15 23:33 UTC
Labels: kind/improvement, topic: client types, topic: dmmf, team/client
