### ISSUE TITLE
Prisma Studio errors with a Prisma Client error `...It seems there is a problem with your OpenSSL installation!...`

### ISSUE THREAD

**Issue by Matheus-S-Costa** [prisma/prisma#15771] opened 2022-10-13 04:06 UTC
### Bug description

Can't use the localhost with prisma studio.

Error starting Prisma Client: {
```
  "message": "Unable to establish a connection to query-engine-node-api library. It seems there is a problem with your OpenSSL installation!\n\u001b[31m\u001b[1mDetails:\u001b[22m\u001b[39m Unable to require(`/home/matheus/www/nlw/esports/server/node_modules/@prisma/engines/libquery_engine-debian-openssl-1.1.x.so.node`)\n libssl.so.1.1: cannot open shared object file: No such file or directory\n[Context: getConfig]\n\nPrisma CLI Version : 4.3.1",
  "stack": "Unable to establish a connection to query-engine-node-api library. It seems there is a problem with your OpenSSL installation!\n\u001b[31m\u001b[1mDetails:\u001b[22m\u001b[39m Unable to require(`/home/matheus/www/nlw/esports/server/node_modules/@prisma/engines/libquery_engine-debian-openssl-1.1.x.so.node`)\n libssl.so.1.1: cannot open shared object file: No such file or directory\n[Context: getConfig]\n\nPrisma CLI Version : 4.3.1"
}
Error: Error starting Prisma Client: {
  "message": "Unable to establish a connection to query-engine-node-api library. It seems there is a problem with your OpenSSL installation!\n\u001b[31m\u001b[1mDetails:\u001b[22m\u001b[39m Unable to require(`/home/matheus/www/nlw/esports/server/node_modules/@prisma/engines/libquery_engine-debian-openssl-1.1.x.so.node`)\n libssl.so.1.1: cannot open shared object file: No such file or directory\n[Context: getConfig]\n\nPrisma CLI Version : 4.3.1",
  "stack": "Unable to establish a connection to query-engine-node-api library. It seems there is a problem with your OpenSSL installation!\n\u001b[31m\u001b[1mDetails:\u001b[22m\u001b[39m Unable to require(`/home/matheus/www/nlw/esports/server/node_modules/@prisma/engines/libquery_engine-debian-openssl-1.1.x.so.node`)\n libssl.so.1.1: cannot open shared object file: No such file or directory\n[Context: getConfig]\n\nPrisma CLI Version : 4.3.1"
}
    at qs.init (http://localhost:5555/assets/index.js:1:83069)
```

### How to reproduce

I just run the command: npx prisma studio

### Expected behavior

Enter in localhost and run my database.

### Environment & setup

- OS: 
- Browser: 
- Database:

**Comment by janpio** [comment] 2022-10-13 07:57
What operating system are you using @Matheus-S-Costa? Does Prisma Client work in a Node app?

**Comment by Matheus-S-Costa** [comment] 2022-10-13 14:17
I use linux distro ubuntu.

running whereis openssl:
openssl: /usr/bin/openssl /usr/include/openssl
/home/matheus/anaconda3/bin/openssl /usr/share/man/man1/openssl.1ssl.gz

Em qui., 13 de out. de 2022 às 04:59, Joël Galeran ***@***.***>
escreveu:

**Comment by janpio** [comment] 2022-10-13 14:20
"anaconda" rings a bell: https://github.com/prisma/prisma/issues/14073

**Comment by Matheus-S-Costa** [comment] 2022-10-13 14:21
if the problem is my OpenSSL setup, what steps I need to take?

Em qui., 13 de out. de 2022 às 11:17, Matheus Costa <
***@***.***> escreveu:

**Comment by Jolg42** [comment] 2022-10-13 14:23
Indeed.
It looks like something is related to `anaconda`
- mentions of `anaconda` interfering with `openssl` https://github.com/prisma/prisma/issues/14073#issuecomment-1195294394
- mention that removing `anaconda` worked https://github.com/prisma/prisma/issues/12570#issuecomment-1083320267

@Matheus-S-Costa You could try what people mentioned, though it doesn't sound like a great solution is you need to use `anaconda`.
So you could also give us more information, so we could reproduce this.

**Comment by Jolg42** [comment] 2022-11-03 08:00
@Matheus-S-Costa Did you solve your issue? What did you do? We're curious to know.

**Comment by Matheus-S-Costa** [comment] 2022-11-11 19:05
> @Matheus-S-Costa Did you solve your issue? What did you do? We're curious to know.

I uninstalled anaconda from my desktop and tried again. It wasn't the ideal solution for me, but was the easiest way. Thanks for help.

**Comment by Jolg42** [comment] 2022-11-11 19:15
We'll keep it open as we want to work on all openssl issues at some point.

**Comment by Matheus-S-Costa** [comment] 2022-11-11 20:25
Ok, no problem.

**Comment by hubsmoke** [comment] 2022-11-16 01:09
FYI I ran into this issue as well and I renamed the openssl binary under anaconda folder to prevent the issue.

```
mv /home/user/anaconda3/bin/openssl /home/user/anaconda3/bin/openssl-old
```

Not sure what the root cause of the conflict is here, but just documenting this in case it's useful

**Comment by aqrln** [comment] 2023-03-28 11:41
This issue is reproducible with Prisma up to 4.8.1. Starting with Prisma 4.9.0, OpenSSL installed via Anaconda, Homebrew etc doesn't interfere with system OpenSSL library detection. I'm going to go ahead and close this issue. Please feel free to open a new issue if you still run into any problems!

**Closed by aqrln** 2023-03-28 11:41 UTC
Labels: bug/1-unconfirmed, kind/bug, topic: prisma-client, team/client, topic: engine, topic: openssl
