### ISSUE TITLE
Get count when using - where with some

### ISSUE THREAD

**Issue by pavelvladimir** [prisma/prisma#4431] opened 2019-04-22 20:09 UTC
Hi, I have a problem get count when using this query.

```
query users {
  users(where: { posts_some: { id: "5cb63016a7b11b00075b58ec" } }) {
    id
    posts {
      id
    }
  }
  meta: usersConnection(
    where: { posts_some: { id: "5cb63016a7b11b00075b58ec" } }
  ) {
    pageInfo {
      startCursor
      endCursor
    }
    aggregate {
      count
    }
  }
}
```

I use this version of the example - https://github.com/prisma/prisma-examples/tree/cde963ad0005bae1d1ea8e5ee1e62b5509c1b3ed/typescript/docker-mongodb

and that’s the database datamodel

```
enum Role {
  ADMIN
  CUSTOMER
}

type Language @db(name: "languages") {
  id: ID! @id
  code: String! @unique
}

type User @db(name: "users") {
  id: ID! @id
  email: String @unique
  role: Role @default(value: CUSTOMER)
  name: String
  avatar: String
  auth0id: String! @unique
  identity: String
  posts: [Post!]! @relation(link: INLINE)
}

type Post @db(name: "posts") {
  id: ID! @id
  wasCreated: DateTime! @createdAt
  wasUpdated: DateTime! @updatedAt
  author: User!
  translation: [PostTranslation!]!
  comments: [Comment!]!
}

type PostTranslation @embedded {
  id: ID! @id
  languageId: Language @relation(link: INLINE)
  title: String!
  content: String
  published: Boolean! @default(value: false)
}

type Comment @embedded {
  text: String!
  writtenBy: User!
}
```

Result:
```
{
  "data": {
    "users": [
      {
        "id": "5cb62f7ea7b11b00075b58ea",
        "posts": [
          {
            "id": "5cb63016a7b11b00075b58ec"
          },
          {
            "id": "5cb63027a7b11b00075b58ee"
          }
        ]
      }
    ],
    "meta": {
      "pageInfo": {
        "startCursor": "5cb62f7ea7b11b00075b58ea",
        "endCursor": "5cb62f7ea7b11b00075b58ea"
      },
      "aggregate": {
        "count": 0
      }
    }
  }
}
```

**Comment by soqt** [comment] 2019-04-24 02:26
same issue. Not only with _some selector, but also all `nested where` selectors which query based on more than one data models requirements.

**Comment by pantharshit00** [comment] 2019-04-25 13:53
Closing as a duplicate of https://github.com/prisma/prisma/issues/4414

**Closed by pantharshit00** 2019-04-25 13:53 UTC
