### ISSUE TITLE
Can't connect to Google Cloud Mysql using SSL

### ISSUE THREAD

**Issue by ralvs** [prisma/prisma#3134] opened 2020-07-25 19:23 UTC
Hello guys!
I'm trying to connect my prisma2 project on my machine to Gcloud Mysql

Using this url it works normally: mysql://user:password@ip:3306/prisma2

But, when I add the SSL part it doesn't work: mysql://user:password@ip:3306/prisma2?sslmode=require&sslcert=server-ca.pem&sslidentity=client-identity.p12&sslpassword=sslPassword

By the way, from the command line I can also connect correctly with: mysql -uroot -p -h <ip> --ssl-ca=server-ca.pem --ssl-cert=client-cert.pem --ssl-key=client-key.pem

I have generated the .p12 file and the ssPassword as described at https://www.prisma.io/docs/reference/database-connectors/mysql
And the certificate files were downloaded from Google

Any ideias? :)
Thanks

## Environment & setup

- OS: Mac OS latest
- Database: MySQL 5.7
- Node.js version: v14.6.0
- Prisma version: 2.3.0

**Comment by divyenduz** [comment] 2020-07-27 14:45
Closing this as a duplicate of https://github.com/prisma/prisma/issues/1228

@ralvs Please comment here if you disagree 🙏

**Closed by divyenduz** 2020-07-27 14:45 UTC
