### ISSUE TITLE
A Node.js API is used (process.stdout at line: 68) which is not supported in the Edge Runtime.

### ISSUE THREAD

**Issue by vinkovsky** [prisma/prisma#25159] opened 2024-09-04 09:22 UTC
### Bug description

 ⚠ Compiled with warnings

./node_modules/.pnpm/@prisma+debug@5.20.0-dev.5/node_modules/@prisma/debug/dist/index.js
A Node.js API is used (process.stdout at line: 68) which is not supported in the Edge Runtime.
Learn more: https://nextjs.org/docs/api-reference/edge-runtime

Import trace for requested module:
./node_modules/.pnpm/@prisma+debug@5.20.0-dev.5/node_modules/@prisma/debug/dist/index.js
./node_modules/.pnpm/@prisma+driver-adapter-utils@5.20.0-dev.5/node_modules/@prisma/driver-adapter-utils/dist/index.mjs
./node_modules/.pnpm/@prisma+adapter-neon@5.20.0-dev.5_@neondatabase+serverless@0.9.5/node_modules/@prisma/adapter-neon/dist/index.mjs
./src/app/lib/prisma-client.ts

./node_modules/.pnpm/@prisma+debug@5.20.0-dev.5/node_modules/@prisma/debug/dist/index.js
A Node.js API is used (process.stdout at line: 68) which is not supported in the Edge Runtime.
Learn more: https://nextjs.org/docs/api-reference/edge-runtime

Import trace for requested module:
./node_modules/.pnpm/@prisma+debug@5.20.0-dev.5/node_modules/@prisma/debug/dist/index.js
./node_modules/.pnpm/@prisma+driver-adapter-utils@5.20.0-dev.5/node_modules/@prisma/driver-adapter-utils/dist/index.mjs
./node_modules/.pnpm/@prisma+adapter-neon@5.20.0-dev.5_@neondatabase+serverless@0.9.5/node_modules/@prisma/adapter-neon/dist/index.mjs
./src/app/lib/prisma-client.ts

### How to reproduce

1. Install with nextjs 
2. run next build

### Expected behavior

Solve this problem https://github.com/prisma/prisma/pull/24686

### Prisma information

```prisma
generator client {
  provider        = "prisma-client-js"
  previewFeatures = ["driverAdapters"]
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

model User {
  id       Int     @id @default(autoincrement())
  email    String  @unique
  username String?
  password String
}
```

```ts
import { PrismaClient } from "@prisma/client"
import { Pool } from '@neondatabase/serverless'
import { PrismaNeon } from '@prisma/adapter-neon'
import { DATABASE_URL } from "../constants/app"

const connectionString = DATABASE_URL
const prismaClientSingleton = () => {
  const pool = new Pool({ connectionString })
  // https://github.com/neondatabase/serverless/blob/main/DEPLOY.md
  const adapter = new PrismaNeon(pool)
  return new PrismaClient({ adapter })
}

declare const globalThis: {
  prismaGlobal: ReturnType<typeof prismaClientSingleton>
} & typeof global

const prisma = globalThis.prismaGlobal ?? prismaClientSingleton()

export default prisma

if (process.env.NODE_ENV !== "production") globalThis.prismaGlobal = prisma

```

### Environment & setup

- OS: macOS 
- Database: PostgreSQL 
- Node.js version: v18.19.0 - v20.11.1

### Prisma Version

```
Environment variables loaded from .env
prisma                  : 5.20.0-dev.5
@prisma/client          : 5.20.0-dev.5
Computed binaryTarget   : darwin-arm64
Operating System        : darwin
Architecture            : arm64
Node.js                 : v20.11.1
Query Engine (Node-API) : libquery-engine f2561ec470647d6a14db84d3c1dc6fc1c2414386 (at node_modules/.pnpm/@prisma+engines@5.20.0-dev.5/node_modules/@prisma/engines/libquery_engine-darwin-arm64.dylib.node)
Schema Engine           : schema-engine-cli f2561ec470647d6a14db84d3c1dc6fc1c2414386 (at node_modules/.pnpm/@prisma+engines@5.20.0-dev.5/node_modules/@prisma/engines/schema-engine-darwin-arm64)
Schema Wasm             : @prisma/prisma-schema-wasm 5.20.0-4.f2561ec470647d6a14db84d3c1dc6fc1c2414386
Default Engines Hash    : f2561ec470647d6a14db84d3c1dc6fc1c2414386
Studio                  : 0.502.0
Preview Features        : driverAdapters
```

Problem exists in 5.19.1 as well

**Comment by vinkovsky** [comment] 2024-09-04 09:38
`  "next": "14.2.7",`

**Comment by Mnigos** [comment] 2024-11-28 10:37
Same issue

**Comment by jkomyno** [comment] 2024-12-30 15:41
Closing as a duplicate of https://github.com/prisma/prisma/issues/24346.

[This comment](https://github.com/prisma/prisma/issues/24346#issuecomment-2538576991) still stands: this is a Next.js issue, not Prisma's.

**Closed by jkomyno** 2024-12-30 15:41 UTC
Labels: bug/1-unconfirmed, kind/bug, domain/client, topic: Vercel Edge Runtime, topic: driverAdapters
