### ISSUE TITLE
Support generator, datadase, models respectively for different databases.

### ISSUE THREAD

**Issue by calidion** [prisma/prisma#5759] opened 2021-02-20 04:47 UTC
## Problem

currently schema.prisma contains generator, database and model.

## Suggested solution

support generator, datadbase, models respectively for different databases.

for generators:
defined a file call `generator.prisma`
```
generator mysql {
  provider = "prisma-client-mysql-js"
}

generator sqlite {
  provider = "prisma-client-sqlite-js"
}

...

```

for database:

defined a file called `database.prisma`

```
mysql {
  provider = "mysql"
  url      = env("DATABASE_MYSQL_URL")
}

mysql_test {
  provider = "mysql"
  url      = env("DATABASE_MYSQL_TEST_URL")
}

sqlite {
  provider = "sqlite"
  url      = env("DATABASE_SQLITE_URL")
}
...

default = mysql_test
```
define a default database for bootstrap.

**Comment by calidion** [comment] 2021-02-23 08:22
generator.prisma, database.prisma, schema.prisma.
Try to keep schema universal, And override specific attributes :

```
model user {
username String?
}

override('mysql') user {
username String? @db.Varchar(255)
}
```

**Comment by calidion** [comment] 2021-02-28 06:08
Keep one copy schema for all databases is very vital.  To full utilize databases, you can create dialects for each database respectivly to further describe that type.

//universal schema.
// schema.prisma
model user {
username String?
}

//dialect schema
// mysql.prisma
mode user {
username String? @db.Varchar(255)
}
or
alias String to String @db.Varchar(255)
alias String? to String? @db.Varchar(255)

**Comment by janpio** [comment] 2024-02-01 18:30
I am closing this as a duplicate of https://github.com/prisma/prisma/issues/2443 which is a lot more popular. If you think some of the suggestions here are missing there, please leave a comment. Thanks!

**Closed by janpio** 2024-02-01 18:30 UTC
Labels: kind/feature, topic: schema, team/client
