### ISSUE TITLE
Using Primsa Without Docker

### ISSUE THREAD

**Issue by brillout** [prisma/prisma#3333] opened 2018-10-17 12:34 UTC
Docker is nice but tightly coupling prisma with docker has it downsides.

Creating this ticket for people interested in using prisma without docker.

**Comment by marktani** [comment] 2018-10-18 14:11
Closing as duplicate of #2992.

**Closed by marktani** 2018-10-18 14:11 UTC
Labels: kind/feature

**Comment by Zireael** [comment] 2019-05-25 18:20
I've had more luck using postgraphile

```
const express = require("express");
const { postgraphile } = require("postgraphile");

const app = express();

const postgresConn = "postgres://username:password@localhost:5432/postgres";

const options = {
	classicIds: true,
	graphqlRoute: "/graphql",
	graphiqlRoute: "/graphiql",
	graphiql: true, //!IS_PRODUCTION,
	enhanceGraphiql: true, //!IS_PRODUCTION
	exportJsonSchemaPath: "./schema.json",
	enableCors: true
	// jwtSecret: "123",
	// jwtPgTypeIdentifier: "discipuli.jwt_token",
	// pgDefaultRole: "anonymous"
};

app.use(postgraphile(process.env.DATABASE_URL || postgresConn, options));

app.listen(process.env.PORT || 3000);

console.log(
	`GraphQL listening on http://localhost:${process.env.PORT || 3000}`,
	"\n",
	`GUI: http://localhost:${process.env.PORT || 3000}${options.graphiqlRoute}`
);

```
