### ISSUE TITLE
Better soft delete management

### ISSUE THREAD

**Issue by euberdeveloper** [prisma/prisma#5771] opened 2021-02-21 15:24 UTC
## Problem

Reading this post https://www.prisma.io/docs/concepts/components/prisma-client/middleware/soft-delete-middleware I see a way to do the soft delete.

The problem comes when there are relations, what if I want a sort of **soft delete cascade**? I mean something like, if I soft delete a post, all its comments are soft deleted.

## Suggested solution

I think that it would be beautiful if there was an already built in soft delete.

in the model 
```prisma
model Person {
   // ...
   deleted Date? @softDelete(type: "cascade")
}
```

I actually do not know how it should be implemented and featured, but this is just a concept.

**Comment by pantharshit00** [comment] 2021-02-26 11:09
Hi,

Thanks for reporting this! It has already been reported before, so I am going to close this as a duplicate of https://github.com/prisma/prisma/issues/3398

**Closed by pantharshit00** 2021-02-26 11:09 UTC
Labels: kind/feature

**Comment by orendaeko** [comment] 2022-03-28 07:49
@pantharshit00 I think this issue for a better way than the current that is use middleware, hopefully, can use soft delete with Prisma without many step, thanks

**Comment by janpio** [comment] 2022-03-28 16:52
Exactly as is https://github.com/prisma/prisma/issues/3398 @orendaeko, which this one was closed as a duplicate.
