### ISSUE TITLE
Parallel request in mongo db cause WriteConflict error

### ISSUE THREAD

**Issue by NielsenMax** [prisma/prisma#14455] opened 2022-07-22 20:29 UTC
### Bug description

We are developing an API with NestJS, Prisma and MongoDB. When we try to make parallel request that can affect the same document we get the following error:

`Error occurred during query execution:
ConnectorError(ConnectorError { user_facing_error: None, kind: RawDatabaseError { code: "unknown", message: "Command failed (WriteConflict): WriteConflict error: this operation conflicted with another operation. Please retry your operation or multi-document transaction.)" } })
`

The example provided will fail with exactly the same error.

### How to reproduce

schema.prisma

```
datasource db {
  provider = "mongodb"
  url      = env("DATABASE_URL")
}

generator client {
  provider = "prisma-client-js"
}

model Chorizo {
  id String @id @default(auto()) @map("_id") @db.ObjectId

  name String
}
```

index.ts

```
import { PrismaClient, Prisma } from "@prisma/client";
import { faker } from "@faker-js/faker";

const prisma = new PrismaClient();

async function main() {
  // Connect the client
  try {
    await prisma.$connect();
    // ... you will write your Prisma Client queries here

    await Promise.all(
      Array.from({ length: 100 }).map(() => {
        return prisma.chorizo.upsert({
          where: {
            id: "62db038ec451256986370399",
          },
          update: {
            name: faker.internet.email(),
          },
          create: {
            name: faker.internet.email(),
          },
        });
      })
    );
    console.log("caravana fiest");
  } catch (error) {
    console.log(error);
  }
}

main()
  .catch((e) => {
    throw e;
  })
  .finally(async () => {
    await prisma.$disconnect();
  });

```

### Expected behavior

This means that if two client try to perform, for example, an update over the same resource one of them is going to get a WriteConflict error. The request should be performed anyways in the order they arrived to the MongoDB instance.

### Prisma information

```
datasource db {
  provider = "mongodb"
  url      = env("DATABASE_URL")
}

generator client {
  provider = "prisma-client-js"
}

model Chorizo {
  id String @id @default(auto()) @map("_id") @db.ObjectId

  name String
}
```

### Environment & setup

- OS: Ubuntu
- Database: MongoDB Atlas Free tier 
- Node.js version: v16.13.1

### Prisma Version

```
Environment variables loaded from .env
prisma                  : 4.1.0
@prisma/client          : 4.1.0
Current platform        : debian-openssl-1.1.x
Query Engine (Node-API) : libquery-engine 8d8414deb360336e4698a65aa45a1fbaf1ce13d8 (at node_modules/@prisma/engines/libquery_engine-debian-openssl-1.1.x.so.node)
Migration Engine        : migration-engine-cli 8d8414deb360336e4698a65aa45a1fbaf1ce13d8 (at node_modules/@prisma/engines/migration-engine-debian-openssl-1.1.x)
Introspection Engine    : introspection-core 8d8414deb360336e4698a65aa45a1fbaf1ce13d8 (at node_modules/@prisma/engines/introspection-engine-debian-openssl-1.1.x)
Format Binary           : prisma-fmt 8d8414deb360336e4698a65aa45a1fbaf1ce13d8 (at node_modules/@prisma/engines/prisma-fmt-debian-openssl-1.1.x)
Default Engines Hash    : 8d8414deb360336e4698a65aa45a1fbaf1ce13d8
Studio                  : 0.467.0
```

**Comment by pantharshit00** [comment] 2022-07-25 14:19
Hi,

Thanks for reporting this! It has already been reported before, so I am going to close this as a duplicate of https://github.com/prisma/prisma/issues/12814#issuecomment-1191703145

**Closed by pantharshit00** 2022-07-25 14:19 UTC
Labels: bug/1-unconfirmed, kind/bug, team/client, topic: mongodb

**Comment by Raduc4** [comment] 2023-11-20 20:56
Did you find the solution for this?
