### ISSUE TITLE
subscription with fragments does not fire properly

### ISSUE THREAD

**Issue by canercandan** [prisma/prisma#2026] opened 2018-03-06 12:25 UTC
Following the resolver example [here](https://github.com/graphcool/prisma/blob/master/examples/subscriptions/src/index.js#L35-L41), if you call a subscription with a fragment as follow:

```gql
subscription {
  publications {
    mutation
    node {
      ...Fields
    }
  }
}

fragment Fields on Post {
  id
  title
}
```

It will returns a response right away with a null data such as the one below and does not listen for changes.

```json
{
  "data": {
    "data": {
      "publications": null
    }
  }
}
```

Removing the fragment keeps the connection on and listening, and the mutations are triggered properly on changes.

Someone else can confirm?

```bash
$ prisma --version
prisma/1.3.3 (linux-x64) node-v8.7.0
```

Edit: One more thing, this issue does not occur when we use the prisma generated subscriptions with fragments (at the database level).

**Comment by Ranatchai** [comment] 2018-03-09 18:31
+1 I have the same issue.

**Comment by divyenduz** [comment] 2018-03-29 10:48
I am also able to replicate this issue.

**Comment by lowsky** [comment] 2018-04-06 21:16
I also ran into this, same issue: when replacing the fragment with regular fields, all works fine, but after introducing a fragment into the client-side query, it
* creates one spurious websocket response containing just 'null'
> returns a response right away with a null data
* does not fire up after a change should have triggered an event
* works, when regularly connecting the database prisma directly.
  In the logs I additionally find these lines:
  ```
    query: Promise {
        <rejected> TypeError: Cannot read property 'variableDefinitions' of undefined
    at Object.<anonymous> (//node_modules/graphql-tools/dist/stitching/delegateToSchema.js:64:155)
    at step (//node_modules/graphql-tools/dist/stitching/delegateToSchema.js:40:23)
    at Object.next (//node_modules/graphql-tools/dist/stitching/delegateToSchema.js:21:53)
    at //node_modules/graphql-tools/dist/stitching/delegateToSchema.js:15:71
    at new Promise (<anonymous>)
    at __awaiter (//node_modules/graphql-tools/dist/stitching/delegateToSchema.js:11:12)
    at Object.delegateToSchema (//node_modules/graphql-tools/dist/stitching/delegateToSchema.js:49:12)
    at Proxy.<anonymous> (//node_modules/prisma-binding/dist/src/Handler.js:54:36)
    at formatValue (util.js:430:38)
    at formatProperty (util.js:831:11) },
     mutation: Promise {
        <rejected> TypeError: Cannot read property 'variableDefinitions' of undefined
    at Object.<anonymous> (//node_modules/graphql-tools/dist/stitching/delegateToSchema.js:64:155)
    at step (//node_modules/graphql-tools/dist/stitching/delegateToSchema.js:40:23)
    at Object.next (//node_modules/graphql-tools/dist/stitching/delegateToSchema.js:21:53)
    at /node_modules/graphql-tools/dist/stitching/delegateToSchema.js:15:71
    at new Promise (<anonymous>)
    at __awaiter (//node_modules/graphql-tools/dist/stitching/delegateToSchema.js:11:12)
    at Object.delegateToSchema (//node_modules/graphql-tools/dist/stitching/delegateToSchema.js:49:12)
    at Proxy.<anonymous> (//node_modules/prisma-binding/dist/src/Handler.js:54:36)
    at formatValue (util.js:430:38)
    at formatProperty (util.js:831:11) },
```
and many or these: ```
(node:20312) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 24): TypeError: Cannot read property 'variableDefinitions' of undefined
(node:20312) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 26): TypeError: Cannot convert a Symbol value to a string
```

Hope this helps somehow?

**Comment by divyenduz** [comment] 2018-04-07 19:57
I am able to [replicate this](https://github.com/divyenduz/subscriptions-fragment-bug) with `apollo-link-*` and `graphql-tools`. Most likely a bug in `graphql-tools`, will work on isolating the issue further.

**Comment by bazaglia** [comment] 2018-04-16 22:47
I'm getting the same error in query object. `TypeError: Cannot read property 'variableDefinitions' of undefined`.

I can only see this error when I `console.log` the prisma instance. Despite the error, prisma-binding is seems to be working fine.

**Comment by frankdugan3** [comment] 2018-06-01 12:05
When using a query with `subscribeToMore`, this can really add a lot of duplication in the client code. Would be nice to see this get some attention.

**Comment by deiucanta** [comment] 2018-07-17 11:47
@marktani I have this issue as well. @divyenduz provided a reproduction repo

**Comment by samdenty99** [comment] 2018-07-22 14:54
Found the issue. The underlying subscriptions work correctly with fragments on the server, it's just an issue with GraphQL Playground.

It seems when a `fragment` is placed inside the query, instead of sending it over the WebSocket, it sends it in a POST request

**Comment by ntziolis** [comment] 2018-07-27 10:07
@marktani You closed #1810 stating that this issue provides a reproduction. Do you have everything you need to tacke this? Let me know if you still need a clean repro and I will set it up

The duplicate code issue is really getting out of hand in our codebase. It leads to a lot of the following situations:
- devs forgetting to update both fragment and subscription when adding / renaming fields => hours wasted until realizing their mistake
- devs forgetting or not knowing that the fragmenting subscription issue exists => hours wasted until they realize the framework is broken here

**Comment by ntziolis** [comment] 2018-08-18 21:11
@divyenduz While trying to setup a repro I think I figured out the root cause for this issue:

- In short when subscriptions have fragments but NO name prisma returns null and closes the subscription. I have created a separate issue for this here: https://github.com/prisma/prisma/issues/2942
- And when using the `prisma-bindings` we call the subscription without the initially given name hence we get a null response
- This also explains why:
  - this works in your repo as you are NOT using `prisma-bindings` to pass through the subscription
  - copying the subscriptions from app to database playground works just fine

Quick sanity check:
https://eu1.prisma.sh/public-silvermole-100/subscription-fragment/dev

The following breaks:
```
fragment PostFragment on Post{
  id
}
subscription {post{node{  ...PostFragment  }}}
```

While this works just fine:
```
fragment PostFragment on Post{
  id
}
subscription SomeName{post{node{  ...PostFragment  }}}
```

**Comment by ntziolis** [comment] 2018-08-19 09:01
So I found the cause for the newly seen type error:
- While `prisma-bindings@2.1.4` do solve the null return issue for subscriptions (with name) and fragments (2.1.3 still returns null for subscriptions with fragments)
- but at the same time 2.1.4 introduces the new type error (mentioned above) bug for ALL subscriptions. See issue https://github.com/prisma/prisma-binding/issues/229

Applying the fix mentioned in the issue thread for the type error (in my node modules folder) I can confirm that :
- **subscription with fragments and NAME now work as expected**
- still same issues for subscriptions with fragments and NO name #2942

Note:
The type error is actually part of the `graphl-bindings` not `prisma-bindings` itself

**Comment by marktani** [comment] 2018-10-04 12:34
Closed as duplicate of https://github.com/prisma/prisma/issues/2942 and https://github.com/prisma/graphql-playground/issues/846.

**Closed by marktani** 2018-10-04 12:34 UTC
Labels: area/subscriptions, kind/bug, reproduction-available
