### ISSUE TITLE
Prisma2 generate issue

### ISSUE THREAD

**Issue by yovanoc** [prisma/prisma#1397] opened 2020-01-21 18:54 UTC
Follow up on that one: https://github.com/prisma/prisma2/issues/1371

![pasted image](https://user-images.githubusercontent.com/7302317/72660302-5b886b00-39cc-11ea-8fab-a2af800cd825.png)

It seems that `yarn prisma2 generate` (when prisma2 installed on devDependencies) doesn't generate the new PrismaClient

**Comment by AlexanderProd** [comment] 2020-01-21 19:55
Did you try it with ˋnpx prisma2 generateˋ? Just a thought, might be worth a try.

**Comment by pantharshit00** [comment] 2020-01-22 16:36
I am unable to reproduce this. Can you please tell me the exact steps to reproduce this?

Also, please share your `package.json` file. Also, please note that the default schema doesn't have any models in it so it won't generate any typing for that. Can you please confirm that your schema has models in it.

**Comment by yovanoc** [comment] 2020-01-22 17:29
Yes I have already send to you my schema in previous issues, but I don't want to put it publicly because it's an enterprise project. 

Here's the dependencies:

![image](https://user-images.githubusercontent.com/7302317/72917812-cf1bd680-3d44-11ea-91cb-83a2b51d7ece.png)

its a yarn workspaces (monorepo) and when I do a `yarn prisma2 generate` (to use prisma2 installed by the project) it doesn't generate at all, the executable stop before 1 sec of running. But if I install prisma2 globally on my machine and run `prisma2 generate` all is doing great. Another thing, when I put a script like that: 

![image](https://user-images.githubusercontent.com/7302317/72917990-29b53280-3d45-11ea-9799-b1be9314c0ec.png)

and run `yarn gen` all is good too.

**Comment by pantharshit00** [comment] 2020-01-24 10:11
I am still unable to reproduce this. Can you please make a small git repository of this problem and share with me. No need to share your schema, I need just a minimal reproduction.

Right now I tried to reproduce this with the following yarn workspaces setup:

<img width="581" alt="image" src="https://user-images.githubusercontent.com/22195362/73060929-f26a9100-3ebe-11ea-86f2-2932a0afccea.png">

**Comment by steebchen** [comment] 2020-02-06 05:41
> it doesn't generate at all, the executable stop before 1 sec of running

@yovanoc Can you please send the exact error you're getting? This will help us debug this further. I'm running into a similar problem.

**Comment by yovanoc** [comment] 2020-02-06 06:41
I can't reproduce on the latest alpha now :/

**Comment by janpio** [comment] 2020-09-02 02:29
Closing this then. Please open a new issue if this ever pops up again.

**Closed by janpio** 2020-09-02 02:29 UTC
Labels: bug/0-needs-info, kind/bug, status/needs-action, topic: cli-generate
