### ISSUE TITLE
Error: Error in migration engine. Reason: [C:\Users\runneradmin\.cargo\git\checkouts\quaint-9f01e008b9a89c14\8196f13\src\connector\result_set\result_row.rs:59:64] index out of bounds: the len is 1 but the index is 10 

### ISSUE THREAD

**Issue by tomhoule** [prisma/prisma#6736] opened 2021-04-23 08:36 UTC
Command: `prisma db push --preview-feature`
Version: `2.21.2`
Binary Version: `e421996c87d5f3c8f7eeadd502d4ad402c89464d`
Report: https://prisma-errors.netlify.app/report/13234 
OS: `x64 win32 10.0.19042`

JS Stacktrace:
```
Error: Error in migration engine.
Reason: [C:\<...>\.cargo\git\checkouts\quaint-9f01e008b9a89c14\8196f13\src\connector\result_set\result_row.rs:59:64] index out of bounds: the len is 1 but the index is 10

Please create an issue with your `schema.prisma` at 
https://github.com/prisma/prisma/issues/new

    at ChildProcess.<anonymous> (C:\<...>\npm\node_modules\prisma\build\index.js:55668:23)
    at ChildProcess.emit (events.js:315:20)
    at ChildProcess.EventEmitter.emit (domain.js:486:12)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
```

Rust Stacktrace:
```
[C:\<...>\.cargo\git\checkouts\quaint-9f01e008b9a89c14\8196f13\src\connector\result_set\result_row.rs:59:64] index out of bounds: the len is 1 but the index is 10
```

**Comment by pimeys** [comment] 2021-05-10 13:56
There is no real backtrace here. We need to just let these errors to be before somebody gives a proper report and how to reproduce it. Here, we know that quaint panics due to accessing with an index out of bounds. We don't know which part of our code calls this to even start testing. Closing until we get a proper report from a user.

**Closed by pimeys** 2021-05-10 13:56 UTC
Labels: bug/1-repro-available, kind/bug, team/migrations, topic: db push, topic: error reporting
