### ISSUE TITLE
Error Formatting Not Working

### ISSUE THREAD

**Issue by webdevike** [prisma/prisma#3261] opened 2020-08-10 19:01 UTC
## How to reproduce

1. run a query or mutation that would cause an error like invalid args
2. Error output in Graphql playground not formatted

## Expected behavior

Expected `  const prisma = new PrismaClient({
    errorFormat: 'colorless'
  })
` to work as intended

Instead I am getting 

```
{
  "errors": [
    {
      "message": "\n\u001b[31mInvalid \u001b[1m`prisma.story.deleteMany()`\u001b[22m invocation in\u001b[39m\n\u001b[31m\u001b[4m/Users/isaacweber/code/sofam-api/src/modules/Story/story.resolvers.js:40:46\u001b[24m\u001b[39m\n\n\n\u001b[31mInvalid \u001b[1m`prisma.story.deleteMany()`\u001b[22m invocation:\u001b[39m\n\n{\n  where: {\n    url: {\n      \u001b[91mtesting\u001b[39m: \u001b[2m'weiorjweo'\u001b[22m\u001b[2m\u001b[22m\n      \u001b[91m~~~~~~~\u001b[39m\n\u001b[2m\u001b[22m    }\u001b[2m\u001b[22m\n\u001b[2m\u001b[22m  }\u001b[2m\u001b[22m\n\u001b[2m\u001b[22m}\n\nUnknown arg \u001b[91m`testing`\u001b[39m in \u001b[1mwhere.url.testing\u001b[22m for type \u001b[1mStringFilter\u001b[22m. Did you mean `\u001b[92min\u001b[39m`? \u001b[2mAvailable args:\u001b[22m\n\u001b[2mtype\u001b[22m \u001b[1m\u001b[2mStringFilter\u001b[22m\u001b[22m \u001b[2m{\u001b[22m\n  \u001b[2m\u001b[32mequals\u001b[39m?: \u001b[37mString\u001b[39m\u001b[22m\n  \u001b[2m\u001b[32mnot\u001b[39m?: \u001b[37mString | StringFilter\u001b[39m\u001b[22m\n  \u001b[2m\u001b[32min\u001b[39m?: \u001b[37mList<String>\u001b[39m\u001b[22m\n  \u001b[2m\u001b[32mnotIn\u001b[39m?: \u001b[37mList<String>\u001b[39m\u001b[22m\n  \u001b[2m\u001b[32mlt\u001b[39m?: \u001b[37mString\u001b[39m\u001b[22m\n  \u001b[2m\u001b[32mlte\u001b[39m?: \u001b[37mString\u001b[39m\u001b[22m\n  \u001b[2m\u001b[32mgt\u001b[39m?: \u001b[37mString\u001b[39m\u001b[22m\n  \u001b[2m\u001b[32mgte\u001b[39m?: \u001b[37mString\u001b[39m\u001b[22m\n  \u001b[2m\u001b[32mcontains\u001b[39m?: \u001b[37mString\u001b[39m\u001b[22m\n  \u001b[2m\u001b[32mstartsWith\u001b[39m?: \u001b[37mString\u001b[39m\u001b[22m\n  \u001b[2m\u001b[32mendsWith\u001b[39m?: \u001b[37mString\u001b[39m\u001b[22m\n\u001b[2m}\u001b[22m\n\n",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "deleteStory"
      ],
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR",
        "exception": {
          "stacktrace": [
            "Error: ",
            "\u001b[31mInvalid \u001b[1m`prisma.story.deleteMany()`\u001b[22m invocation in\u001b[39m",
            "\u001b[31m\u001b[4m/Users/isaacweber/code/sofam-api/src/modules/Story/story.resolvers.js:40:46\u001b[24m\u001b[39m",
            "",
            "",
            "\u001b[31mInvalid \u001b[1m`prisma.story.deleteMany()`\u001b[22m invocation:\u001b[39m",
            "",
            "{",
            "  where: {",
            "    url: {",
            "      \u001b[91mtesting\u001b[39m: \u001b[2m'weiorjweo'\u001b[22m\u001b[2m\u001b[22m",
            "      \u001b[91m~~~~~~~\u001b[39m",
            "\u001b[2m\u001b[22m    }\u001b[2m\u001b[22m",
            "\u001b[2m\u001b[22m  }\u001b[2m\u001b[22m",
            "\u001b[2m\u001b[22m}",
            "",
            "Unknown arg \u001b[91m`testing`\u001b[39m in \u001b[1mwhere.url.testing\u001b[22m for type \u001b[1mStringFilter\u001b[22m. Did you mean `\u001b[92min\u001b[39m`? \u001b[2mAvailable args:\u001b[22m",
            "\u001b[2mtype\u001b[22m \u001b[1m\u001b[2mStringFilter\u001b[22m\u001b[22m \u001b[2m{\u001b[22m",
            "  \u001b[2m\u001b[32mequals\u001b[39m?: \u001b[37mString\u001b[39m\u001b[22m",
            "  \u001b[2m\u001b[32mnot\u001b[39m?: \u001b[37mString | StringFilter\u001b[39m\u001b[22m",
            "  \u001b[2m\u001b[32min\u001b[39m?: \u001b[37mList<String>\u001b[39m\u001b[22m",
            "  \u001b[2m\u001b[32mnotIn\u001b[39m?: \u001b[37mList<String>\u001b[39m\u001b[22m",
            "  \u001b[2m\u001b[32mlt\u001b[39m?: \u001b[37mString\u001b[39m\u001b[22m",
            "  \u001b[2m\u001b[32mlte\u001b[39m?: \u001b[37mString\u001b[39m\u001b[22m",
            "  \u001b[2m\u001b[32mgt\u001b[39m?: \u001b[37mString\u001b[39m\u001b[22m",
            "  \u001b[2m\u001b[32mgte\u001b[39m?: \u001b[37mString\u001b[39m\u001b[22m",
            "  \u001b[2m\u001b[32mcontains\u001b[39m?: \u001b[37mString\u001b[39m\u001b[22m",
            "  \u001b[2m\u001b[32mstartsWith\u001b[39m?: \u001b[37mString\u001b[39m\u001b[22m",
            "  \u001b[2m\u001b[32mendsWith\u001b[39m?: \u001b[37mString\u001b[39m\u001b[22m",
            "\u001b[2m}\u001b[22m",
            "",
            "",
            "    at Object.model (/Users/isaacweber/code/sofam-api/node_modules/@prisma/client/src/runtime/getPrismaClient.ts:400:19)",
            "    at Object.deleteMany (/Users/isaacweber/code/sofam-api/node_modules/@prisma/client/src/runtime/getPrismaClient.ts:520:33)",
            "    at _callee5$ (/Users/isaacweber/code/sofam-api/src/modules/Story/story.resolvers.js:40:46)",
            "    at tryCatch (/Users/isaacweber/code/sofam-api/node_modules/regenerator-runtime/runtime.js:45:40)",
            "    at Generator.invoke [as _invoke] (/Users/isaacweber/code/sofam-api/node_modules/regenerator-runtime/runtime.js:274:22)",
            "    at Generator.prototype.<computed> [as next] (/Users/isaacweber/code/sofam-api/node_modules/regenerator-runtime/runtime.js:97:21)",
            "    at asyncGeneratorStep (/Users/isaacweber/code/sofam-api/node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)",
            "    at _next (/Users/isaacweber/code/sofam-api/node_modules/@babel/runtime/helpers/asyncToGenerator.js:25:9)",
            "    at /Users/isaacweber/code/sofam-api/node_modules/@babel/runtime/helpers/asyncToGenerator.js:32:7",
            "    at new Promise (<anonymous>)"
          ]
        }
      }
    }
  ],
  "data": {
    "deleteStory": null
  }
}
```

## Environment & setup

```
@prisma/cli          : 2.2.0
Current platform     : darwin
Query Engine         : query-engine 45c4da4dd3ccd6a322796b228bdf937c7ce884e8 (at /Users/isaacweber/code/sofam-api/node_modules/@prisma/cli/query-engine-darwin)
Migration Engine     : migration-engine-cli 45c4da4dd3ccd6a322796b228bdf937c7ce884e8 (at /Users/isaacweber/code/sofam-api/node_modules/@prisma/cli/migration-engine-darwin)
Introspection Engine : introspection-core 45c4da4dd3ccd6a322796b228bdf937c7ce884e8 (at /Users/isaacweber/code/sofam-api/node_modules/@prisma/cli/introspection-engine-darwin)
Format Binary        : prisma-fmt 45c4da4dd3ccd6a322796b228bdf937c7ce884e8 (at /Users/isaacweber/code/sofam-api/node_modules/@prisma/cli/prisma-fmt-darwin)
```
- OS: Mac
- Database: PostgresSQL
- Node.js v12.18.1
- Prisma version: 2.2.0

**Comment by pantharshit00** [comment] 2020-08-12 22:04
This is intended, colorless means none of your text will be colored but it will be spaced via ansi codes. If you want to get rid of the codes, you need `errorFormat: 'colorless'`

**Comment by janpio** [comment] 2020-08-13 14:45
Huh @pantharshit00? Isn't this exactly what @ikey2244 is doing - using `colorless` and expecting no color codes!?

**Comment by pantharshit00** [comment] 2020-08-13 14:49
Oh no, i meant to say `errorFormat: minimal`. Edited my comment

**Comment by ikey2244** [comment] 2020-08-13 15:59
Formatting is acting the same even when I set minimal. I have updated my issue to show what mutation I am running to get this error.

**Comment by pantharshit00** [comment] 2020-08-14 01:08
Hey @ikey2244 

Can you please share a minimal reproduction inside of a git repository? 

I tried it again with a graphql app and it is working correctly.

1. With `errorFormat: colorless`
![image](https://user-images.githubusercontent.com/22195362/90201509-b6fec800-ddf8-11ea-8d54-d3dcb75d2231.png)


2. With `errorFormat: minimal`
![image](https://user-images.githubusercontent.com/22195362/90201536-c7af3e00-ddf8-11ea-8f75-caf874824b81.png)



I used this nexus example for my reproduction: https://github.com/graphql-nexus/examples/tree/master/plugin-prisma

**Comment by janpio** [comment] 2021-03-23 19:24
I am going to close this now. Happy to take a look again if we get more information.

**Closed by janpio** 2021-03-23 19:24 UTC
Labels: bug/0-needs-info, kind/bug, status/needs-action, topic: error
