### ISSUE TITLE
Introspection: `Every RelationInfo should have a complementary RelationInfo on the opposite relation field.`

### ISSUE THREAD

**Issue by janpio** [prisma/prisma#3127] opened 2020-07-24 09:22 UTC
Command: `prisma introspect`
Version: `2.2.0`
Binary Version: `45c4da4dd3ccd6a322796b228bdf937c7ce884e8`
Report: https://prisma-errors.netlify.app/report/8849 
OS: `x64 darwin 18.7.0`

JS Stacktrace:
```
Error: [libs/datamodel/core/src/dml/datamodel.rs:175:9] Every RelationInfo should have a complementary RelationInfo on the opposite relation field.
    at IntrospectionEngine.<anonymous> (/Users/andrej/workspaces/prisma-day-2020/node_modules/@prisma/cli/build/index.js:2:1994783)
    at Generator.throw (<anonymous>)
    at rejected (/Users/andrej/workspaces/prisma-day-2020/node_modules/@prisma/cli/build/index.js:2:1991796)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

Rust Stacktrace:
```
   0: backtrace::backtrace::trace
   1: backtrace::capture::Backtrace::new
   2: user_facing_errors::Error::new_in_panic_hook
   3: user_facing_errors::panic_hook::set_panic_hook::{{closure}}
   4: std::panicking::rust_panic_with_hook
   5: _rust_begin_unwind
   6: core::panicking::panic_fmt
   7: core::option::expect_failed
   8: datamodel::dml::datamodel::Datamodel::find_related_field_for_info
   9: datamodel::dml::datamodel::Datamodel::find_related_info
  10: sql_introspection_connector::re_introspection::enrich
  11: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  12: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  13: <futures_util::compat::compat03as01::Compat<Fut> as futures::future::Future>::poll
  14: <futures::future::map::Map<A,F> as futures::future::Future>::poll
  15: <futures::future::either::Either<A,B> as futures::future::Future>::poll
  16: futures::future::chain::Chain<A,B,C>::poll
  17: <futures::future::then::Then<A,B,F> as futures::future::Future>::poll
  18: <futures::future::map::Map<A,F> as futures::future::Future>::poll
  19: <futures::future::either::Either<A,B> as futures::future::Future>::poll
  20: <futures::future::map::Map<A,F> as futures::future::Future>::poll
  21: futures::task_impl::std::set
  22: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  23: tokio::runtime::enter::Enter::block_on
  24: tokio::runtime::context::enter
  25: tokio::runtime::handle::Handle::enter
  26: introspection_engine::main
  27: std::rt::lang_start::{{closure}}
  28: std::rt::lang_start_internal
  29: _main

```

And another report of the same: https://prisma-errors.netlify.app/report/8825

**Comment by pantharshit00** [comment] 2020-08-05 22:12
@janpio as I mentioned in the other issue, these introspection issues are very hard for me to reproduce as we don't have a db schema 😓

**Comment by janpio** [comment] 2020-08-06 12:20
Ok. Still a valid bug and someone from the Engines team can look into the stacktrace and see if they get a hunch what is going on. 

If not, and this happens to often, we might want to find a way to actually get the database schema (optionally, via prompt) or similar.

**Comment by tomhoule** [comment] 2021-02-25 10:57
Closing this, since it's about a very old version. Thanks Jan!

**Closed by tomhoule** 2021-02-25 10:57 UTC
Labels: bug/1-repro-available, kind/bug, status/needs-action, team/migrations, tech/engines, topic: introspection
