### ISSUE TITLE
Import generated types in the frontend

### ISSUE THREAD

**Issue by darioielardi** [prisma/prisma#3766] opened 2020-09-25 21:39 UTC
## Problem

It would be extremely useful to have the chance to import the generated types in a frontend project.

I'm working with a yarn workspace setup, and the prisma client is generated in the root `node_modules`, which let me share it across multiple node microservices, and the only package where I need to manually write every model type is the frontend package.

I tried to do that with an example  create-react-app project and it works in dev mode but fails as soon as I try to build for production, I guess because of node specific dependencies.

It would be particularly handy to use the generated helpers types too, to achieve type safety for the api response objects.

I know I could achieve similar results with GraphQL and some dedicated generators, but unfortunately I'm working with a REST API.

## Suggested solution

We should have a way to import just the data model types and helper types from the generated client in a frontend project.

## Alternatives

An alternative might be a new generator specifically for those types, but it feels wrong since the same generation logic is already implemented in the client generator.

**Comment by darioielardi** [comment] 2020-09-26 10:19
I have experimented with this a little bit more.

I was wondering why the bundler was trying to include the prisma client in the production build since I only imported types definitions, which should be stripped out at compile time. I realized the only reason the bundler needs to include the generated code in the bundle are enums, which are compiled as objects by tsc. 

As soon as I remove my enums imports and use string literals everything works and the production build is correctly compiled. I may be happy with that, but it would be probably worth to figure out a way around this.

**Comment by pantharshit00** [comment] 2020-09-28 10:59
Hi,

Thanks for reporting this! It has already been reported before, so I am going to close this as a duplicate of https://github.com/prisma/prisma/issues/1272

**Closed by pantharshit00** 2020-09-28 10:59 UTC

**Comment by stuart-haas** [comment] 2024-08-19 01:45
For anyone who is still looking for a solid solution and having a hard time finding one, I wrote up an article on this, and it's been implemented in a production-grade application.

https://dev.to/stuarthaas/client-side-prisma-types-mj
