### ISSUE TITLE
Remove GraphQLSchema from generated prisma-client/index.ts

### ISSUE THREAD

**Issue by steida** [prisma/prisma#3717] opened 2018-12-16 23:38 UTC
`import { DocumentNode, GraphQLSchema } from 'graphql';`

It's not used therefore TypeScript in strict mode warns.

**Comment by steida** [comment] 2018-12-16 23:38
Related to https://github.com/prisma/prisma/issues/3369

**Comment by pantharshit00** [comment] 2018-12-17 06:41
Hi @steida,

As you have already identified this issue is on our radar and we will fix it very soon.

Closing this as duplicate of #3369

**Closed by pantharshit00** 2018-12-17 06:41 UTC
Labels: kind/duplicate
