### ISSUE TITLE
Prisma Accerlerate & Interactive Transactions just don't work!

### ISSUE THREAD

**Issue by karthikjn01** [prisma/prisma#21440] opened 2023-10-10 13:15 UTC
### Bug description

I had working code using an interactive session (in a server action), I made the jump to use prisma accelerate and all I changed was the prisma client to use `withAccelerate` and now the server action just isn't working. The error I'm getting back is:

### Expected behavior

The transaction should run as usual and should there be any conflicts, it should throw an error.

### Prisma information

```prisma
... // other models I can't share as it's IP
model Transaction {
  id           String            @id @default(uuid())
  createdAt    DateTime          @default(now()) @map(name: "created_at")
  updatedAt    DateTime          @default(now()) @updatedAt @map(name: "updated_at")
  restaurantId String
  restaurant   Restaurant        @relation(fields: [restaurantId], references: [id])
  userId       String?
  user         User?             @relation(fields: [userId], references: [id])
  amount       Float
  sessions     Session[]
  type         String?
  notes        String?
  status       TransactionStatus
  discounts    Discount[]
  intents      PaymentIntent[]
  allowSplit   Boolean?          @default(false)

  @@map(name: "transactions")
}
```

```ts

import prisma from "@/db"; //singleton with prisma accelerate enabled.
...
const createIntent = async (amount: number) => {
        "use server"


        const intent = await prisma.$transaction(async (tx) => {//breaks here!

            const transactionContent = await tx.transaction.findFirst({ //or here not entirely sure
                where: {
                    id: params.transactionId,
                },
                include: {
                    intents: true,
                    restaurant: {
                        include: {
                            settings: true,
                        }
                    }
                }
            });

            if (!transactionContent) {
                throw new Error('Transaction not found');
            }

            //calculate the total amount of all intents
            const total = transactionContent.intents.filter((e) => e.status === 'Pending' || e.status === 'Paid' || e.status === 'External_Paid').reduce((acc, curr) => {
                return acc + (curr.amount ?? 0);
            }, 0);

            //if the total amount of all intents + the new intent amount is greater than the transaction total, throw an error
            if (total + amount > transactionContent.amount) {
                throw new Error('Amount too large');
            }

            if (amount === 0) {
                throw new Error('Amount cannot be 0');
            }

            if (transactionContent.amount - total - amount < 200 && transactionContent.amount - total - amount > 0) {
                throw new Error('Amount too small');
            }


            const intent = await tx.paymentIntent.create({
                data: {
                    amount,
                    transactionId: params.transactionId,
                    status: 'External_Paid',
                }
            });

            await tx.transaction.update({
                where: {
                    id: params.transactionId,
                },
                data: {
                    updatedAt: new Date(),
                    status: total + amount === transactionContent.amount ? 'Paid' : undefined,
                }
            });

            return intent;
        }, {
            isolationLevel: Prisma.TransactionIsolationLevel.Serializable,
            timeout: 10000, //didn't originally have this, but this didn't fix it!
        }).catch((e) => {
            console.error(e);
            return e;
        });


        return {
            intent
        }
    }
```

### Environment & setup

- OS: MacOS
- Database: Postgres w Supabase
- Node.js version: v18.15.0

### Prisma Version

```
prisma                  : 5.4.1
@prisma/client          : 5.4.1
Current platform        : darwin-arm64
Query Engine (Node-API) : libquery-engine 2f302df92bd8945e20ad4595a73def5b96afa54f (at node_modules/@prisma/engines/libquery_engine-darwin-arm64.dylib.node)
Schema Engine           : schema-engine-cli 2f302df92bd8945e20ad4595a73def5b96afa54f (at node_modules/@prisma/engines/schema-engine-darwin-arm64)
Schema Wasm             : @prisma/prisma-schema-wasm 5.3.1-2.61e140623197a131c2a6189271ffee05a7aa9a59
Default Engines Hash    : 2f302df92bd8945e20ad4595a73def5b96afa54f
Studio                  : 0.494.0
```

**Comment by janpio** [comment] 2023-10-11 23:37
Seems something went wrong when you created the issue, the actual error you are getting is missing @karthikjn01. Can you please add that? Thanks.

**Comment by nurul3101** [comment] 2023-10-12 08:43
Hello @karthikjn01 👋 

Thank you for bringing this to our attention
I believe this issue is resolved as you migrated from server actions to API routes.

We have documented the feedback regarding the unexpected behaviour of interactive transactions with server actions. However, I'll be closing this GitHub Issue since this repository primarily addresses Prisma ORM issues rather than Prisma Accelerate concerns.

**Closed by nurul3101** 2023-10-12 08:43 UTC
Labels: kind/bug, topic: pdp/accelerate

**Comment by karthikjn01** [comment] 2023-10-12 08:48
Hey @nurul3101 ,

Cheers yep. And if anyone else happens to roll onto this issue, move the server function into an API route and that should fix it. It did for me atleast
