### ISSUE TITLE
Crash in command `generate`: "internal error: entered unreachable code"

### ISSUE THREAD

**Issue by JulioJuarezM** [prisma/prisma#23815] opened 2024-04-10 12:56 UTC
Hi Prisma Team! The following command just crashed.

## Command

`generate --schema [redacted]`

## Versions
      
| Name        | Version            |
|-------------|--------------------|
| Platform    | windows            | 
| Node        | v18.12.0           | 
| Prisma CLI  | 5.1.1              | 
| Engine      | 6a3747c37ff169c90047725a05a6ef02e32ac97e| 

## Error
```
RustPanic: RuntimeError: panicked at 'internal error: entered unreachable code: No unsupported field should reach that path', query-engine/schema/src/build/input_types/mod.rs:26:40
```

**Comment by Jolg42** [comment] 2024-05-28 09:08
@JulioJuarezM Is this still a problem for you?

Without more information, we are not able to reproduce this.
We would need your Prisma schema here.

**Comment by SevInf** [comment] 2024-06-20 08:51
Hey @JulioJuarezM  ,

Did you get a chance to have a look at my collegues comment? It'd be helpful for us to move your issue forward.

Without further information, we'll have to close this issue. Thank you 🙏

**Comment by jkomyno** [comment] 2024-07-10 12:30
We're closing this issue due to inactivity. Please leave a comment below, ideally with a reproduction repository, if you have more actionable feedback about this issue. Thanks!

**Closed by jkomyno** 2024-07-10 12:30 UTC
Labels: bug/0-unknown, kind/bug, topic: prisma generate, tech/engines, domain/schema, topic: rust panic, topic: entered unreachable code
