### ISSUE TITLE
PrismaClient complains about problems with the db url in schema.prisma even if you're not using that url

### ISSUE THREAD

**Issue by asktree** [prisma/prisma#3034] opened 2020-07-16 03:03 UTC
I'm having some major issues with the .env file loading the DATABASE_URL today -- it works during `prisma introspect` but not in the PrismaClient. I don't know what's wrong. However, it shouldn't even matter, because I don't use .env or schema.prisma to specify my database url outside of my local environment. 

## Expected behavior
There should be no errors related to the database specified in schema.prisma, because that isn't being used.

## Environment & setup

- OS: Linux
- Database: PG
- Prisma version: 2.2.0
- Node.js version: 10

**Comment by asktree** [comment] 2020-07-16 03:22
Oh, I think this is because setting the datasource in the options like so: 
```ts 
const prisma = new PrismaClient({
  datasources: { db: functions.config().postgres.url },
})
```
actually just does nothing

**Comment by pantharshit00** [comment] 2020-07-16 07:42
Closing as a duplicate of https://github.com/prisma/prisma-client-js/issues/779

**Closed by pantharshit00** 2020-07-16 07:42 UTC
