### ISSUE TITLE
Error: Get config: Unable to establish a connection to query-engine-node-api library

### ISSUE THREAD

**Issue by PiecePaperCode** [prisma/prisma#13717] opened 2022-06-08 21:24 UTC
```sh
$/prisma/starter$ npx prisma generate
Prisma schema loaded from prisma/schema.prisma
Error: Get config: Unable to establish a connection to query-engine-node-api library

Prisma CLI Version : 3.15.1-dev.1
```

**How to Reproduce**
OS: 22.04 Ubuntu
Node: 16.15.1
Follow these instructions. https://www.prisma.io/docs/getting-started/quickstart#1-download-the-starter-project
Switch to latest possible release: 3.15.1-dev.1 as per today.

**What have i tried so far**
Switching databases sqlite, postgres
Switching node from 16 to 17.
using 3.13 3.14 gives me this error
```
/snap/core20/current/lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /lib/x86_64-linux-gnu/libcrypto.so.3)
```
in ubuntu i could not figure out how to install GLIBC_2.33
tying with npm and yarn

**Comment by janpio** [comment] 2022-06-08 23:28
Error message is from our new error reporting code from @jkomyno: https://github.com/prisma/prisma/blob/a490f5a82baeccf985c2cc30476f45748ed0fcad/packages/sdk/src/engine-commands/queryEngineCommons.ts#L80

**Comment by janpio** [comment] 2022-06-08 23:30
To confirm:
Using 3.14.0 you are getting a different error message around GLIBC?

**Comment by irfanabdnst** [comment] 2022-06-09 05:24
I got this error when using 3.14.0 and 3.13.0
`libssl.so.1.1: cannot open shared object file: No such file or directory`

**Comment by PiecePaperCode** [comment] 2022-06-09 06:44
i confirm using version 3.13.x 3.14.x gives this error 

`/snap/core20/current/lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /lib/x86_64-linux-gnu/libcrypto.so.3)

`

when using 3.15 gives the Config Error described above.

in bouth cases making prisma work on ubuntu 22.04 is not possible.

**Comment by janpio** [comment] 2022-06-09 07:25
@irfanabdnst Please create a new issue providing all the info the bug issue template asks for. Thanks.

**Comment by pantharshit00** [comment] 2022-06-09 12:51
Looks like you are using snap to either install Node.js or openssl or maybe even glibC. Since snaps are sandboxes we can't dynamically link to required runtime libraries and so it will throw out that error. So please try installing these libs using `apt`:
```
sudo apt install openssl openssl-dev libc6 
```

**Comment by PiecePaperCode** [comment] 2022-06-09 18:49
[https://github.com/nodesource/distributions/blob/master/README.md](https://github.com/nodesource/distributions/blob/master/README.md)
```sh
# Using Ubuntu
curl -fsSL https://deb.nodesource.com/setup_16.x | sudo -E bash -
sudo apt-get install -y nodejs
```
Ok the snap version of node is not compatible with prisma.
Its going to trap ubuntu users who install almost everything with snap.

**Comment by janpio** [comment] 2022-06-09 18:58
We want to keep this open for the bug with the error reporting that you also reported. Thanks for your help in confirming that this was caused by the snap thingie.

**Comment by jkomyno** [comment] 2022-06-27 11:18
Hi @PiecePaperCode, to summarise, this issue was due an incompatibility between your system's snap, as highlighted [in this comment](https://github.com/prisma/prisma/issues/13717#issuecomment-1151080267).
A [related issue](https://github.com/prisma/prisma/issues/14006) is that the current error message can be somewhat obscure and misleading. We closed it with [this PR](https://github.com/prisma/prisma/pull/13736).

Tomorrow we will release a new major version that will contain improvements such as the following error message that tries to explain which connecting to the `query-engine-node-api` library failed:

```
Environment variables loaded from .env
Prisma schema loaded from prisma/schema.prisma
Error: Get Config: Unable to establish a connection to query-engine-node-api library. It seems there is a problem with your OpenSSL installation!
Details:Unable to require(`/home/prisma/.nvm/versions/node/v16.15.1/lib/node_modules/prisma/libquery_engine-debian-openssl-1.1.x.so.node`)
 libssl.so.1.1: cannot open shared object file: No such file or directory

Prisma CLI Version : 3.16.0-dev.102
```

Please let us know if we can close this issue then :)

**Comment by cmwhited** [comment] 2022-06-27 16:05
I am also getting this error when running `prisma generate` though docker using the `FROM node:16.15-alpine3.16` image and installing openssl through apk:
```
FROM node:16.15-alpine3.16
RUN apk add --no-cache git curl python3 make gcc libc-dev g++ libc6-compat openssl openssl-dev \
    && curl -sL https://unpkg.com/@pnpm/self-installer | node
RUN ln -sf python3 /usr/bin/python
```

Here is my [example repo](https://github.com/cmwhited/turbo-prisma-ex)

**Comment by janpio** [comment] 2022-06-27 19:32
What error exactly @cmwhited?
Can you try with a `prisma@dev` and `@prisma/client@dev` (or version 4.0.0 which will be release tomorrow) please and post the full output you are getting? That would help us to make sure you ar egetting the same error indeed.

**Comment by cmwhited** [comment] 2022-06-28 21:22
> What error exactly @cmwhited? Can you try with a `prisma@dev` and `@prisma/client@dev` (or version 4.0.0 which will be release tomorrow) please and post the full output you are getting? That would help us to make sure you ar egetting the same error indeed.

Updated to v4.0.0 and it still fails. I think it is actually an issue with `pnpm`. Testing now

**Comment by cmwhited** [comment] 2022-06-28 22:31
> Your error is different @cmwhited, which is now nicely visible with the new error message. Can you copy your last message into a new issue please? Thanks. Happy to investigate what is going on there.
> 
> Follow up question 1 (please reply in new issue): Does `/app/node_modules/prisma/libquery_engine-linux-arm64-openssl-1.1.x.so.node` exist?

https://github.com/prisma/prisma/issues/14043

**Closed** 2022-06-29 11:34 UTC
Labels: bug/1-unconfirmed, kind/bug, team/schema, team/client, topic: error handling

**Comment by mirandaa1** [comment] 2022-07-04 13:45
Error: Get config: Unable to establish a connection to query-engine-node-api library. -- I got this error when i try to connect to SQLite Database using Prisma

**Comment by shtse8** [comment] 2022-07-08 22:49
> Hi @PiecePaperCode, to summarise, this issue was due an incompatibility between your system's snap, as highlighted [in this comment](https://github.com/prisma/prisma/issues/13717#issuecomment-1151080267). A [related issue](https://github.com/prisma/prisma/issues/14006) is that the current error message can be somewhat obscure and misleading. We closed it with [this PR](https://github.com/prisma/prisma/pull/13736).
> 
> Tomorrow we will release a new major version that will contain improvements such as the following error message that tries to explain which connecting to the `query-engine-node-api` library failed:
> 
> ```
> Environment variables loaded from .env
> Prisma schema loaded from prisma/schema.prisma
> Error: Get Config: Unable to establish a connection to query-engine-node-api library. It seems there is a problem with your OpenSSL installation!
> Details: Unable to require(`/home/prisma/.nvm/versions/node/v16.15.1/lib/node_modules/prisma/libquery_engine-debian-openssl-1.1.x.so.node`)
>  libssl.so.1.1: cannot open shared object file: No such file or directory
> 
> Prisma CLI Version : 3.16.0-dev.102
> ```
> 
> Please let us know if we can close this issue then :)

I still have this issue, which new version can fix it?

**Comment by janpio** [comment] 2022-07-08 23:02
There is no new version that can fix, as this is a problem on your system. See the instructions on how to fix here: https://github.com/prisma/prisma/issues/13717#issuecomment-1151080267

**Comment by aniwn88480857** [comment] 2022-07-09 14:40
$ npm-run-all build-tracker build-geo build-db build-app
$ rollup -c rollup.tracker.config.js

tracker/index.js → public/umami.js...
created public/umami.js in 359ms
$ node scripts/build-geo.js
Saved geo database: E:\my\umami-master\umami-master\public\geo\GeoLite2-Country.
mmdb
$ npm-run-all copy-db-files build-db-client
$ node scripts/copy-db-files.js
internal/modules/cjs/loader.js:818
  throw err;
  ^

Error: Cannot find module 'fs-extra'
Require stack:
- E:\my\umami-master\umami-master\scripts\copy-db-files.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (E:\my\umami-master\umami-master\scripts\copy-db-files
.js:2:13)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js
:60:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ 'E:\\my\\umami-master\\umami-master\\scripts\\copy-db-files.js
' ]
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this comm
and.
ERROR: "copy-db-files" exited with 1.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this comm
and.
ERROR: "build-db" exited with 1.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this comm
and.

**Comment by aniwn88480857** [comment] 2022-07-09 14:42
Prisma schema loaded from prisma\schema.prisma
Error: Get config: Unable to establish a connection to query-engine-node-api lib
rary

Prisma CLI Version : 3.15.2
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this comm
and.
ERROR: "build-db-client" exited with 1.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this comm
and.
ERROR: "build-db" exited with 1.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this comm
and.

**Comment by shtse8** [comment] 2022-07-09 14:47
> There is no new version that can fix, as this is a problem on your system. See the instructions on how to fix here: [#13717 (comment)](https://github.com/prisma/prisma/issues/13717#issuecomment-1151080267)

It turns out that cannot generate scheme without root permission in linux. I finally can generate it with root. I don't know how to make it work without root permission.

**Comment by janpio** [comment] 2022-07-09 15:20
@aniwn88480857 Your first post looks completely unrelated to Prisma. Your second one is an old version that does not show the full error message, please upgrade to Prisma 4.0.0.

@shtse8 That is not a known limitation, and probably has to do with how you installed your node or application. If the error persists, please open a discussion here in Github and provide more information so Support can take a look. Thanks.

**Comment by kaykhan** [comment] 2022-07-18 11:58
> @kaykhan #9975 (comment) check out this solution, it may fix you issue too. install MSVCR on windows..

No~ im on ubuntu 22.04

**Comment by ivan-kleshnin** [comment] 2022-07-29 12:46
Same issue in Docker

```
FROM node:16.13-alpine
...
RUN apk add --update openssl openssl-dev libc6-compat
...
Get Config: Unable to establish a connection to query-engine-node-api library. It seems there is a problem with your OpenSSL installation!
```

If someone finds a solution for Alpine images – please share.

**Comment by janpio** [comment] 2022-07-29 23:55
@ivan-kleshnin There should be further output with the actual error message that provides the details what is going wrong in your case.

**Comment by ivan-kleshnin** [comment] 2022-07-30 06:39
@janpio here's the rest of the message, thank you for responding:

```
#0 347.2 Details: Unable to require(`/usr/src/app/node_modules/prisma/libquery_engine-linux-arm64-openssl-1.1.x.so.node`)
#0 347.2  Error relocating /usr/src/app/node_modules/prisma/libquery_engine-linux-arm64-openssl-1.1.x.so.node: 
__res_init: symbol not found
#0 347.2 Prisma CLI Version : 4.1.1
#0 347.2 error Command failed with exit code 1.
```

**Comment by janpio** [comment] 2022-07-30 22:24
Ugh, that one is new. Can you please open a new issue for this and fill the full template? We should try to reproduce this and understand what exactly is going on.

**Comment by gbgustavobraga** [comment] 2022-07-30 22:46
i was having this simple problem, >>> sudo su npx migrate dev....

**Comment by c43721** [comment] 2022-08-16 00:14
> Ugh, that one is new. Can you please open a new issue for this and fill the full template? We should try to reproduce this and understand what exactly is going on.

While I don't have a template for you unfortunately, I was encountering this error in my CI.

In my project, I build a docker image using `node:16-slim` as a base image, where I generate my prisma types.

For my runner layer, I was using `node:16-buster-slim`. I think there's something missing in the node:16-slim image. I have many checks from CI that are green with the same images, but have failed since I started including the prisma files on July 10th. 

I wasn't using prisma before then, so I assume that on June 8th this hasn't worked. For docker users, it seems like using node:16 or your favorite flavor of node should do the trick.

**Comment by janpio** [comment] 2022-08-20 01:01
Please open new issues with additional information if you still encounter this problem. Thanks.
