### ISSUE TITLE
Enum formatting spaces @map after a triple slash comment

### ISSUE THREAD

**Issue by casey-chow** [prisma/prisma#9192] opened 2021-09-10 00:36 UTC
### Bug description

`prisma format` seems to place the `@map` directive after the last column of a triple slash comment.

### How to reproduce

Insert the following into a Prisma schema and run `prisma format`.

```prisma
enum Test {
  /// A Pop quiz.
  PopQuiz @map("POP_QUIZ")
}

```

The outcome is like so:

```prisma
enum Test {
  /// A Pop quiz.
  PopQuiz          @map("POP_QUIZ")

  @@map("test")
}
```

### Expected behavior

No changes to the formatting.

### Prisma information

N/A

### Environment & setup

- OS:  macOS 11.4 Big Sur
- Database:  PostgreSQL 12
- Node.js version:  Node 14.13.1

### Prisma Version

I did a clean install to verify against the latest version (I'm on 2.27.0 on my project at the moment).

```
prisma                  : 3.0.2
@prisma/client          : Not found
Current platform        : darwin
Query Engine (Node-API) : libquery-engine 2452cc6313d52b8b9a96999ac0e974d0aedf88db (at node_modules/@prisma/engines/libquery_engine-darwin.dylib.node)
Migration Engine        : migration-engine-cli 2452cc6313d52b8b9a96999ac0e974d0aedf88db (at node_modules/@prisma/engines/migration-engine-darwin)
Introspection Engine    : introspection-core 2452cc6313d52b8b9a96999ac0e974d0aedf88db (at node_modules/@prisma/engines/introspection-engine-darwin)
Format Binary           : prisma-fmt 2452cc6313d52b8b9a96999ac0e974d0aedf88db (at node_modules/@prisma/engines/prisma-fmt-darwin)
Default Engines Hash    : 2452cc6313d52b8b9a96999ac0e974d0aedf88db
Studio                  : 0.423.0
```

**Comment by janpio** [comment] 2021-09-10 21:42
I can confirm the problem. On a quick test it only seems to apply to `@map` in `enum`, not in `model` or anywhere else.

**Comment by tomhoule** [comment] 2022-07-07 12:06
The schema reformats to this on Prisma 4.0:

```prisma
enum Test {
  /// A Pop quiz.
  PopQuiz @map("POP_QUIZ")

  @@map("test")
}
```

I think the problem is fixed, and we can close this issue. Thanks for reporting the problem!

**Closed by tomhoule** 2022-07-07 12:06 UTC
Labels: bug/2-confirmed, kind/bug, tech/engines, topic: prisma format, team/schema
