### ISSUE TITLE
Prisma CLI authentication against self-hosted server fails if logged in

### ISSUE THREAD

**Issue by philsch** [prisma/prisma#4343] opened 2019-04-10 09:17 UTC
**Describe the bug**
When `prisma login` was used before it seems like authentication against a self-hosted Prisma Server is not working. The authentication token is not send to the server even everything seems to be configured correctly.

**To Reproduce**
1. You need a self hosted Prisma Server with `managementApiSecret` enabled
2. Use `prisma login`
3. Set the needed environment variable `export PRISMA_MANAGEMENT_API_SECRET=xxx`
4. Validate your Prisma configuration is pointing to the self hosted server `prisma info`. My example:
```
Service Name: default

  default (cluster: `default`)

    HTTP:       https://example-dot-staticfilesserver.appspot.com
    Websocket:  wss://example-dot-staticfilesserver.appspot.com
``` 
5. Try to run `prisma deploy`.. An error is returned:
```
ERROR: GraphQL Error (Code: 400)

{
  "error": "<!DOCTYPE html>\n<html>\n  <head>\n    <meta charset=\"utf-8\">\n    <title>Bad Request – 400</title>\n    <style>\n      html, body {\n        margin: 0;\n        width: 100%;\n        height: 100%;\n        display: flex;\n        justify-content: center;\n        align-items: center;\n      }\n\n      body {\n        font-family: -apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, Helvetica, Arial, sans-serif, \"Apple Color Emoji\", \"Segoe UI Emoji\", \"Segoe UI Symbol\";\n        font-size: 15px;\n      }\n\n      .Error {\n        font-size: 1.35em;\n        \n          color: #6061BE;\n        \n      }\n\n      .Error .message {\n        font-weight: 200;\n        letter-spacing: 0.095em;\n      }\n\n      .Error .message a {\n        text-decoration: none;\n        color: inherit;\n        \n          border-bottom: 1px dotted #6061BE;\n        \n      }\n\n      .Error .status {\n        font-weight: 700;\n      }\n\n      .Error .code {\n        display: none;\n      }\n\n      .Error .dot {\n        font-weight: 100;\n      }\n\n      @media screen and (max-width: 800px) {\n        body {\n          font-size: 10px;\n        }\n\n        .Error {\n          display: flex;\n          flex-direction: column;\n        }\n\n        .Error .status {\n          font-size: 1.1em;\n        }\n\n        .Error .dot {\n          display: none\n        }\n      }\n    </style>\n  </head>\n  <body>\n    <div class=\"Error\">\n      <span class=\"status\">Bad Request</span>\n      <span class=\"code\">400</span>\n      <span class=\"dot\">•</span>\n      \n        <span class=\"message\">Please try your request again or contact support.</span>\n      \n    </div>\n  </body>\n</html>",
  "status": 400
}
```

The server log shows:

```
exception:  "com.prisma.deploy.schema.AuthFailure: No 'Authorization' header provided."    
```
6. Use `prisma logout`
7. Repeat `prisma deploy`. This time the command is successful.

**Expected behavior**
It is expected that the CLI works with a self-hosted secured server even if the Prisma CLI is "logged in". Fallback: the CLI recognises a wrong configuration and suggests to log out. 

**Versions (please complete the following information):**
 - Connector: `MongoDB`
 - Prisma Server: `1.30.0`
 - CLI: `prisma/1.30.0 (darwin-x64) node-v8.14.1`
 - OS: `OS X Mojave`

**Comment by divyenduz** [comment] 2019-04-10 09:52
This is fixed in the latest beta, please install it via `npm install -g prisma@beta`.

**Comment by pantharshit00** [comment] 2019-04-10 19:23
Closing as duplicate of https://github.com/prisma/prisma/issues/4312

**Closed by pantharshit00** 2019-04-10 19:23 UTC
