### ISSUE TITLE
Unsupported field in create and update

### ISSUE THREAD

**Issue by Jonatthu** [prisma/prisma#25116] opened 2024-08-29 13:42 UTC
## Problem
I want to be able to insert and update by Unsupported.

## Suggested solution

The use case I am looking for is postgis location field. If I am not able to query using prisma API but typedSQL that's okay but at least I want to be able to insert using prisma API, cases like:

create({ name: "hello", location: "POINT(1.23 23.767)" })

I really would not like to have to create an extension or sql file for every entity I have location enabled to

**Comment by jkomyno** [comment] 2024-08-30 13:39
Hi @Jonatthu, this is a known current limitation, and we hear you, but PostGIS support isn't yet in Prisma's priority list.

I will close this issue as a duplicate of https://github.com/prisma/prisma/issues/5984 and https://github.com/prisma/prisma/issues/2789. We welcome comments and proposals in there to help us shape PostGIS support! Thanks.

**Closed by jkomyno** 2024-08-30 13:39 UTC

**Comment by Jonatthu** [comment] 2024-08-30 14:30
@jkomyno i just wonder how come those issues with more than 120+ replies are not yet on the priority list specially for an issue for 4 years ago. I am grateful for the work prisma has done for open source just wondering what's the blocker or thought process from the prisma team on delaying this. Or at least give an official statement on how hard is this so the community can help on it. I tried to contribute with a PR but still lost on where to even start. 🥲
