### ISSUE TITLE
No way to cascade delete when the foreign key is non-nullable

### ISSUE THREAD

**Issue by ranjan-purbey** [prisma/prisma#2057] opened 2020-04-02 08:56 UTC
## Bug description

1. When the annotated relation field in schema.prisma is made mandatory (no `?` type suffix), running the migration automatically sets cascade deletion. When it is non-mandatory, it sets ON DELETE SET NULL. There should be a way to set the behavior in both cases.

2. Even when using introspection, when the "one" side of the relation is made non-nullable, deleting a record on this side causes prisma query engine to throw a relation violation error. Cascade delete works when the "one" side is nullable

## How to reproduce

1. Create a SQLite db and run following SQL statements
```
DROP TABLE IF EXISTS User;
DROP TABLE IF EXISTS Post;


CREATE TABLE "User" (
  "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
  "name" TEXT
);

CREATE TABLE "Post" (
  "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
  "authorId" INTEGER NOT NULL,
  FOREIGN KEY ("authorId") REFERENCES "User" ("id") ON DELETE CASCADE
);

INSERT INTO User("name") VALUES("Margot");
INSERT INTO Post ("authorId") VALUES(1);
```
2. Introspect the database and generate client JS
3. Run `new PrismaClient().user.delete({where: {id: 1}})`
4. See `RelationViolation` error
5. Make the "authorId" field nullable and re-introspect the db. Try deleting again
6. It works

## Expected behavior
1. The cascade delete should work even when the foeign key field is non nullable
2. @relation directive should have onDelete and onUpdate flags

## Environment & setup

- OS: Ubuntu 19.10
- Database: SQLite 3.30.1
- Prisma version: 2.0.0-beta.1
- Node.js version: v13.7.0

**Comment by pantharshit00** [comment] 2020-04-11 05:37
I can confirm this. I think this is one the assumptions that query engine makes right now but I am not certain.

**Comment by robmurtagh** [comment] 2020-04-16 10:54
Yes, I have exactly the same issue. I am running MySQL 5.7 and have:

```sql
CREATE TABLE `platform`.`entity_basket_item` (
  ...
  FOREIGN KEY (`entity_basket_id`) REFERENCES `platform`.`entity_basket` (`id`) ON DELETE CASCADE
)
```

If the Foreign Key is non-nullable in Prisma schema (which is true in the DB schema):

```
model EntityBasket {
  entityBasketId Int                @default(autoincrement()) @id @map("id")
  items          EntityBasketItem[]

  @@map("entity_basket")
}

model EntityBasketItem {
  entityBasketItemId Int          @default(autoincrement()) @id @map("id")
  basket             EntityBasket @relation(fields: [basketId], references: [entityBasketId])
  basketId           Int          @map("entity_basket_id")

  @@map("entity_basket_item")
}
```

Then I receive error:

```
Error occurred during query execution:
InterpretationError("Error for binding \'3\': RelationViolation(RelationViolation { relation_name: \"EntityBasketToEntityBasketItem\", model_a_name: \"EntityBasket\", model_b_name: \"EntityBasketItem\" })")
```

However making the Foreign Key nullable fixes the error:

```
model EntityBasket {
  entityBasketId Int                @default(autoincrement()) @id @map("id")
  items          EntityBasketItem[]

  @@map("entity_basket")
}

model EntityBasketItem {
  entityBasketItemId Int           @default(autoincrement()) @id @map("id")
  basket             EntityBasket? @relation(fields: [basketId], references: [entityBasketId])
  basketId           Int?          @map("entity_basket_id")

  @@map("entity_basket_item")
}
```

**Comment by ranjan-purbey** [comment] 2020-04-16 11:04
@robmurtagh By "fixes the error" do you mean cascade delete works?

**Comment by robmurtagh** [comment] 2020-04-16 11:05
Yes, exactly, cascade delete then works as expected.

**Comment by ranjan-purbey** [comment] 2020-04-16 11:23
Thanks @robmurtagh for the confirmation. Last time I tried doing that with beta-1, it didn't work for me. I'll try again. Do you mind sharing your prisma version and db provider version?

**Comment by robmurtagh** [comment] 2020-04-16 11:26
Yes, I'm on 2.0.0-beta.1, and mysql:5.7.14

**Comment by ranjan-purbey** [comment] 2020-04-18 17:38
Hey @robmurtagh I tried your solution and it works. But ideally it should also work when the foreign key is non-nullable.

**Comment by dodas** [comment] 2020-05-26 12:56
This one can be probably closed as well now.

**Comment by robmurtagh** [comment] 2020-05-26 13:07
Does that mean that the issue is fixed? Amazing news if so 😄

**Comment by ranjan-purbey** [comment] 2020-05-26 14:33
> This one can be probably closed now as well.
@dodas 
I haven't tested the latest release.  Can you please confirm whether cascade-delete works for non-nullable foreign-keys as well? We can close the issue if that is the case.

**Comment by kennytraction** [comment] 2020-05-26 14:42
> > This one can be probably closed now as well.
> 
> @dodas
> I haven't tested the latest release. Can you please confirm whether cascade-delete works for non-nullable foreign-keys as well? We can close the issue if that is the case.

I am running beta 6 and the issue doesn't seem to be fixed. I would guess that the closed linked issue was included in the release notes by accident.

**Comment by janpio** [comment] 2020-05-26 17:29
Release notes unfortunately can not differentiate between issues that were closed as a duplicate vs. really fixed.

**Comment by Sytten** [comment] 2020-05-26 17:32
You could add a tag for duplicate and exclude those issues.

**Comment by aakashkag** [comment] 2020-05-29 23:24
Hello Prisma Team. Thanks for great product. Is it possible to fix this issue in priority. it's very importent feature in any project. Still waiting from last 2 release. Please. ^^

**Comment by MikaStark** [comment] 2020-06-04 08:27
I don’t understand why cascade deletion is not supported... there are a bunch of workaround on the website for each Db kind and it seems to be just adding constraints ON DELETE but why this can’t be automatic ? (Just like prisma1 with decorators). This is a very important issue I think.

**Comment by aakashkag** [comment] 2020-06-09 18:57
Hope a day will come when this issue will solve by awesome Prisma team. :)

**Comment by jwld** [comment] 2020-06-17 10:53
Any chance we could get a timeline on this fix? Is it days, weeks or months away? It's a pretty painful bug that's holding up our migration to prisma 2.

**Comment by P4sca1** [comment] 2020-06-17 10:59
A timeline on when we can specify cascade deletes / updates in the prisma schema would also be great.

**Comment by janpio** [comment] 2020-06-20 18:36
This issue is _not_ about defining cascading deletes in the Prisma Schema, but about the inability to manually use cascade deletes (by defining them manually) when the relation field is not defined as optional (non-nullable).

Surprisingly we did not have a clear one for that, so I created one: https://github.com/prisma/prisma/issues/2810

**Comment by jhanschoo** [comment] 2020-07-08 16:56
Note that the workaround by defining one of the foreign keys to be optional becomes problematic in `2.2.0` of `@prisma/cli` and `@prisma/client` in an important use case of implicit many-to-many tables, that require the `@@id([A, B])` annotation, since `A` and `B` must be non-nullable for the annotation to pass `2.2.0`'s static checker.

**Comment by jwld** [comment] 2020-07-23 09:45
@jhanschoo How are you getting round this? Just using a raw SQL query instead?

**Comment by jhanschoo** [comment] 2020-07-24 11:51
@jwld I'm pinning to `2.1.3` since I don't need the `aggregateApi` of `2.2.x` just yet.

**Comment by pbelbin** [comment] 2020-10-06 15:01
Is this issue being worked on?  It's a huge pain, and seems like it's a bug that should be fixed by now.

**Comment by nikolasburk** [comment] 2020-10-28 16:42
This issue depends on the implementation of cascading deletes: https://github.com/prisma/prisma/issues/2810

Unfortuantelt, cascading deletes are not actively being worked on _right now_ but they're already on the roadmap and will likely be picked up by the eningeering team soon!

In the meantime, I want to mention that @AhmedElywa has built an awesome library that brings you cascading deletes to Prisma already today: https://paljs.com/plugins/delete You can use it as a workaround for the time where it's not yet natively supported by Prisma.

**Comment by Sytten** [comment] 2020-12-17 22:57
Ha funny that I didnt find it before, related issue: https://github.com/prisma/prisma/issues/4650

**Comment by sathyajitloganathan** [comment] 2021-02-18 07:42
As a workaround, one could execute a raw sql statement through prisma so that the cascaded delete constraint set on the database would work as expected.

```const result = await prisma.$executeRaw\`DELETE FROM User WHERE id=${userId};\````

**Comment by pbelbin** [comment] 2021-02-19 00:36
Yes, and, that's what we're **having to do**, but, really, this sort of thing should not have to be *worked around*!!!

**Comment by jrvidotti** [comment] 2021-03-01 16:50
I think it's a better workaround to recreate foreign key the right way after applying Prisma migration:

```
ALTER TABLE "Reading" DROP CONSTRAINT "Reading_createdById_fkey"; // <--- Old contrainst: ON DELETE SET NULL

ALTER TABLE "Reading" ADD FOREIGN KEY ("createdById") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
```

**Comment by StarpTech** [comment] 2021-04-27 22:24
What's the status? This is obviously an important bug. I'm trying prisma and run into that issue. ORM's 🤗

**Comment by MikaStark** [comment] 2021-04-27 22:32
According to the roadmap : https://www.notion.so/Prisma-Roadmap-50766227b779464ab98899accb98295f

Prisma team is working on it

**Comment by jasonlimantoro** [comment] 2021-05-06 08:58
Is this a priority for the Prisma team? seems like not 😢.

Prisma even has documented the following solutions for cascading deletes as if they were the **correct** solution all along (not a workaround).
(https://www.prisma.io/docs/concepts/components/prisma-client/crud#cascading-deletes-deleting-related-records):
- Make relations optional
- Change the ownership relationships temporarily
- Manually deleting the child records first and then, batch it with `prisma.$transaction` along with the parent record.

**Comment by MikaStark** [comment] 2021-05-06 15:18
Prisma team is working hard on a large bundle of tools like Prisma Studio or Prisma migrate. The latest was a mandatory step to achieve a stable and production-ready cascade delete.
Like any company in the world, human and technical resources are limited and cannot cover every issue instantly. And on top of that it’s free !

**Comment by bencun** [comment] 2021-05-13 10:54
I do like the current implementation with the deletion being forbidden on non-optional relations but that should be an optional kind of behaviour, the cascade deletes should work by default and we should then be able to optionally enforce strict no-cascade behaviour with a modifier on the relationship itself. That would be awesome.

**Comment by albertoperdomo** [comment] 2021-05-14 09:28
Hello everyone and thanks for your patience!

We've spent some time brainstorming about problem, discussing possible solutions, and finally have a proposal to share. The idea is to extend the Prisma Schema Language in order to be able to encode `ON DELET`E and `ON UPDATE` behavior of the foreign keys.

Please find the proposal with all the relevant details [in this GH issue](https://github.com/prisma/prisma/issues/6996). We are welcoming feedback at this stage and look forward to hearing from you!

**Comment by pimeys** [comment] 2021-06-22 16:48
Fixed in https://github.com/prisma/prisma-engines/pull/1947

**Closed by pimeys** 2021-06-22 16:48 UTC
Labels: kind/feature, team/client, tech/engines, topic: cascade, topic: referential actions

**Comment by janpio** [comment] 2021-06-29 10:19
This has now been released as a preview feature behind a preview feature flag. You can read about it in the release notes for 2.26.0: https://github.com/prisma/prisma/releases/tag/2.26.0 If you have any feedback, please use this issue: https://github.com/prisma/prisma/issues/7816
