### ISSUE TITLE
Unhelpful error message with mismatched relationship

### ISSUE THREAD

**Issue by mxstbr** [prisma/prisma#3468] opened 2018-11-12 12:47 UTC
**Describe the bug**
With an unmatched relationship in the datamodel the error reported is a syntactical one that doesn't point to the root of the problem.

**To Reproduce**

1. Create a mismatched relationship like so:

  ```GraphQL
  type Author {
    posts: [Post!]!
  } 

  type Post {
    # Note: This needs to have an "author" field like so, which is why it breaks:
    # author: Author!
    title: String!
  }
  ```
2. Run `prisma deploy` or `prisma generate` (I forget which one)
3. Get error message saying:
  ```
  "Expected name but found '}'"
  ```

**Expected behavior**
It should throw an error saying

```
"Mismatched relationship between Author and Post. Author has posts, but Post has no relationship to Author."
```

or something like that

**Versions (please complete the following information):**
 - OS: MacOS Mojave
 - `prisma` CLI: 1.20.0

**Comment by do4gr** [comment] 2019-01-31 17:11
Thanks for reporting this. Sorry for the late reply!

I tried reproducing it on 1.27 and there is no more error neither during `prisma generate` nor `prisma deploy`. 

I believe this error was related to the generation of empty types, since Author does not have scalar fields. Only having a relation field on one side of a relation is valid in our data model. We did some fixes with regards to empty types in the meantime, so I assume this was fixed while doing these. I'm therefore closing this. If you run into this again please let us know!

**Closed by do4gr** 2019-01-31 17:11 UTC
Labels: area/deploy, area/engine, area/migrations, area/prisma
