### ISSUE TITLE
undici dependency cannot install - " Couldn't find match for "e76f6a37836537f08c2d9b7d8805d6ff21d1e744" git://github.com/mcollina/undici.git" - @prisma/engine-core

### ISSUE THREAD

**Issue by cyrus-za** [prisma/prisma#3472] opened 2020-08-31 07:13 UTC
## Bug description

When installing `nexus-plugin-prisma` (which installs prisma 2.24) and depends on [@prisma/engine-core](https://www.npmjs.com/package/@prisma/engine-core), I run into an error. 

```sh
verbose 263.297637535 Error: Couldn't find match for "e76f6a37836537f08c2d9b7d8805d6ff21d1e744" in "refs/heads/1.2.0-proposal,refs/heads/1.3-proposal,refs/heads/1.4-proposal,refs/heads/allow-throwing-handler,refs/heads/async2,refs/heads/bench-echo,refs/heads/body-error-handler,refs/heads/buffer,refs/heads/busy-timeout,refs/heads/cork-tick,refs/heads/delvedor/add-353,refs/heads/delvedor/pool,refs/heads/delvedor/pool-share-tls-session,refs/heads/dispatch,refs/heads/doc-type,refs/heads/drain-stack,refs/heads/fast-pipeline-body,refs/heads/fast-socket,refs/heads/fast-socket2,refs/heads/fix-async-errors,refs/heads/fix-destroy-queued,refs/heads/fix-pipeline,refs/heads/fix-reset-pipeline,refs/heads/fix-test,refs/heads/get-head-body,refs/heads/idle-options,refs/heads/incoming-message-compat,refs/heads/info-trailers,refs/heads/invalid-server-response,refs/heads/llhttp,refs/heads/master,refs/heads/middleware,refs/heads/middleware2,refs/heads/move-core,refs/heads/no-async,refs/heads/onbody-callback,refs/heads/opaque,refs/heads/opt-parseHeaders,refs/heads/perf-test5,refs/heads/pipeline-destroy,refs/heads/pipeline-fast-dst,refs/heads/pool-aborted,refs/heads/pool-queue,refs/heads/proposal-1.1,refs/heads/refactor-request2,refs/heads/refactor11,refs/heads/refactor12,refs/heads/refactor2,refs/heads/request-timeout,refs/heads/request-timeout2,refs/heads/simplify,refs/heads/simplify-busy,refs/heads/test-parser,refs/heads/test-perf6,refs/heads/throw-expect,refs/tags/delete,refs/tags/elete,refs/tags/v1.0.0,refs/tags/v1.0.1,refs/tags/v1.0.2,refs/tags/v1.0.3,refs/tags/v1.1.0,refs/tags/v1.2.0,refs/tags/v1.2.1,refs/tags/v1.2.2,refs/tags/v1.2.4,refs/tags/v1.2.5,refs/tags/v1.2.6,refs/tags/v1.3.0,refs/tags/v1.3.1" for "git://github.com/mcollina/undici.git".
    at MessageError.ExtendableBuiltin (/usr/local/Cellar/yarn/1.22.4/libexec/lib/cli.js:721:66)
    at new MessageError (/usr/local/Cellar/yarn/1.22.4/libexec/lib/cli.js:750:123)
    at Git.<anonymous> (/usr/local/Cellar/yarn/1.22.4/libexec/lib/cli.js:51440:15)
    at Generator.next (<anonymous>)
    at step (/usr/local/Cellar/yarn/1.22.4/libexec/lib/cli.js:310:30)
    at /usr/local/Cellar/yarn/1.22.4/libexec/lib/cli.js:321:13
    at processTicksAndRejections (internal/process/task_queues.js:82:5)
error Couldn't find match for "e76f6a37836537f08c2d9b7d8805d6ff21d1e744" in "refs/heads/1.2.0-proposal,refs/heads/1.3-proposal,refs/heads/1.4-proposal,refs/heads/allow-throwing-handler,refs/heads/async2,refs/heads/bench-echo,refs/heads/body-error-handler,refs/heads/buffer,refs/heads/busy-timeout,refs/heads/cork-tick,refs/heads/delvedor/add-353,refs/heads/delvedor/pool,refs/heads/delvedor/pool-share-tls-session,refs/heads/dispatch,refs/heads/doc-type,refs/heads/drain-stack,refs/heads/fast-pipeline-body,refs/heads/fast-socket,refs/heads/fast-socket2,refs/heads/fix-async-errors,refs/heads/fix-destroy-queued,refs/heads/fix-pipeline,refs/heads/fix-reset-pipeline,refs/heads/fix-test,refs/heads/get-head-body,refs/heads/idle-options,refs/heads/incoming-message-compat,refs/heads/info-trailers,refs/heads/invalid-server-response,refs/heads/llhttp,refs/heads/master,refs/heads/middleware,refs/heads/middleware2,refs/heads/move-core,refs/heads/no-async,refs/heads/onbody-callback,refs/heads/opaque,refs/heads/opt-parseHeaders,refs/heads/perf-test5,refs/heads/pipeline-destroy,refs/heads/pipeline-fast-dst,refs/heads/pool-aborted,refs/heads/pool-queue,refs/heads/proposal-1.1,refs/heads/refactor-request2,refs/heads/refactor11,refs/heads/refactor12,refs/heads/refactor2,refs/heads/request-timeout,refs/heads/request-timeout2,refs/heads/simplify,refs/heads/simplify-busy,refs/heads/test-parser,refs/heads/test-perf6,refs/heads/throw-expect,refs/tags/delete,refs/tags/elete,refs/tags/v1.0.0,refs/tags/v1.0.1,refs/tags/v1.0.2,refs/tags/v1.0.3,refs/tags/v1.1.0,refs/tags/v1.2.0,refs/tags/v1.2.1,refs/tags/v1.2.2,refs/tags/v1.2.4,refs/tags/v1.2.5,refs/tags/v1.2.6,refs/tags/v1.3.0,refs/tags/v1.3.1" for "git://github.com/mcollina/undici.git".
```

## How to reproduce

```
mkdir bug
cd bug
yarn init -y
yarn add nexus-plugin-prisma --verbose
```

## Expected behavior

The plugin should install without errors

## Prisma information

Not relevant

## Environment & setup

- OS: Mac OS
- Database: N/A
- Node.js version: 12.5.0
- Prisma version: 2.4.0

## Suggested Solution

The issue appears to be due to a recent repo change from github.com/mcollina/undici to github.com/nodejs/undici seeing as the package.json entry goes to a specific commit url as opposed to a npm version. Updating [@prisma/engine-core](https://www.npmjs.com/package/@prisma/engine-core) to point to latest version of undici on npm `should` solve the problem.

**Comment by cyrus-za** [comment] 2020-08-31 07:41
I can confirm that using `yarn resolutions` as a workaround fixes the immediate issue.

```json
// package.json

  "resolutions": {
    "undici": "1.3.1"
  }
```

**Comment by Jolg42** [comment] 2020-08-31 12:49
Hi @cyrus-za !

Thanks for the issue and reproduction steps 😄 

It looks like the Git url broke when the `undici` repository moved.

A temporary fix like you pointed out is to add this into your package.json
```json
"resolutions": {
   "undici": "git://github.com/nodejs/undici.git#e76f6a37836537f08c2d9b7d8805d6ff21d1e744"
},
```

Why this particular commit? because the latest version of undici has a bug that is fixed in this commit. We will switch to a standard undici npm latest release when it's available.

Explanation:
This problem affects because it's requiring `@prisma/migrate` which requires `@prisma/studio-server` which requires `@prisma/sdk` which requires `@prisma/engine-core` and there is the broken Git URL.

So the affected users are those who have in their package.json `nexus-plugin-prisma` or `@prisma/migrate` or `@prisma/studio-server` or `@prisma/sdk` or `@prisma/engine-core`

Users requiring `@prisma/cli` or `@prisma/client` are not affected.

**Comment by Jolg42** [comment] 2020-08-31 12:50
Note: the Git URL was fixed in `2.6.0-dev.53`

**Comment by cyrus-za** [comment] 2020-08-31 13:12
Using the commit ID like you suggested also works. Once 2.6.0 releases I guess this issue can be closed

**Comment by luhagel** [comment] 2020-08-31 13:58
Another workaround seems to be running `yarn cache clean` and downloading everything with the correct repository hooked up

**Comment by Jolg42** [comment] 2020-09-01 09:01
Closing as fixed in for prisma-client-js and will be part of the 2.6.0 release.

It will be fixed in next nexus-plugin-prisma release, tracking issue is https://github.com/graphql-nexus/nexus-plugin-prisma/issues/809

**Closed by Jolg42** 2020-09-01 09:01 UTC
Labels: bug/2-confirmed, kind/regression
