### ISSUE TITLE
NextJS try to open "schema.prisma" at wrong path.

### ISSUE THREAD

**Issue by GrassHopper42** [prisma/prisma#12823] opened 2022-04-14 13:33 UTC
### Bug description

I'm using Lerna and Yarn workspace for monorepo.

```
root
└ packages
  └ prisma      (@my-app/primsa)
    └ schema.prisma    //generated
  └ server
  └ web       (@my-app/web)
└ prisma
  └ schema.prisma
```

I instantiating new client in web package just for next-auth. There is another instantiated client in server package.

```typescript
...
import { PrismaClient } from "@my-app/prisma";

const prisma = new PrimsaClient();

export default NextAuth({
  adapter: PrismaAdapter(prisma),
...
```

If I run dev and try to signin, server throw this error
```bash
warn  - ../prisma/runtime/index.js
Module not found: Can't resolve 'encoding' in 'root/packages/prisma/runtime'
error - Error: ENOENT: no such file or directory, open 'root/packages/web/.next/server/pages/api/auth/schema.prisma'
```

I found similar issue, but it fixed in `@3.12.0`.
And I try again after delete yarn cache, but nothing to change.

### Prisma information

```prisma
generator client {
  provider = "prisma-client-js"
  output   = "../packages/prisma"
}

datasource db {
  provider = "mongodb"
  url      = env("DATABASE_URL")
}

model Account {
  id                String   @id @default(auto()) @map("_id") @db.ObjectId
  createdAt         DateTime @default(now())
  updatedAt         DateTime @updatedAt
  user              User     @relation(fields: [userId], references: [id])
  userId            String   @db.ObjectId
  type              String
  provider          String
  providerAccountId String
  refresh_token     String?  @db.String
  access_token      String
  expires_at        Int?
  token_type        String?
  scope             String?
  id_token          String?  @db.String
  session_state     String?

  @@unique([provider, providerAccountId])
}

model Session {
  id           String   @id @default(auto()) @map("_id") @db.ObjectId
  sessionToken String   @unique
  user         User     @relation(fields: [userId], references: [id])
  userId       String   @db.ObjectId
  expires      DateTime
}

model VerificationToken {
  id         String   @id @default(auto()) @map("_id") @db.ObjectId
  identifier String
  token      String   @unique
  expires    DateTime

  @@unique([identifier, token])
}

model User {
  id            String    @id @default(auto()) @map("_id") @db.ObjectId
  createdAt     DateTime  @default(now())
  updatedAt     DateTime  @updatedAt
  email         String    @unique
  emailVerified DateTime?
  userName      String
  image         String?
  name          String?
  role          Role      @default(USER)
  userRank      UserRank  @default(IRON)
  artworks      Artwork[]
  posts         Post[]
  projectsid    String[]
  comments      Comment[]
  Account       Account[]
  Session       Session[]
}

...
```

### Environment & setup

- OS: WSL2 Ubuntu
- Database: MongoDB
- Node.js version: v17.9.0

### Prisma Version

```
prisma                  : 3.12.0
@prisma/client          : 3.12.0
Current platform        : debian-openssl-1.1.x
Query Engine (Node-API) : libquery-engine 22b822189f46ef0dc5c5b503368d1bee01213980 (at .yarn/unplugged/@prisma-engines-npm-3.12.0-37.22b822189f46ef0dc5c5b503368d1bee01213980-e0ed682c55/node_modules/@prisma/engines/libquery_engine-debian-openssl-1.1.x.so.node)
Migration Engine        : migration-engine-cli 22b822189f46ef0dc5c5b503368d1bee01213980 (at .yarn/unplugged/@prisma-engines-npm-3.12.0-37.22b822189f46ef0dc5c5b503368d1bee01213980-e0ed682c55/node_modules/@prisma/engines/migration-engine-debian-openssl-1.1.x)
Introspection Engine    : introspection-core 22b822189f46ef0dc5c5b503368d1bee01213980 (at .yarn/unplugged/@prisma-engines-npm-3.12.0-37.22b822189f46ef0dc5c5b503368d1bee01213980-e0ed682c55/node_modules/@prisma/engines/introspection-engine-debian-openssl-1.1.x)
Format Binary           : prisma-fmt 22b822189f46ef0dc5c5b503368d1bee01213980 (at .yarn/unplugged/@prisma-engines-npm-3.12.0-37.22b822189f46ef0dc5c5b503368d1bee01213980-e0ed682c55/node_modules/@prisma/engines/prisma-fmt-debian-openssl-1.1.x)
Default Engines Hash    : 22b822189f46ef0dc5c5b503368d1bee01213980
Studio                  : 0.459.0
```

**Comment by GrassHopper42** [comment] 2022-04-15 14:35
I fix `Module not found: Can't resolve 'encoding' in 'root/packages/prisma/runtime'`error. I add this code in `next.config.js`.

```typescript
module.exports = {
  webpack: (conf, options) => {
    if (options.isServer) {
      conf.externals.push("encoding");
    }
  return conf;
}
```

But the other one is same.

**Comment by janpio** [comment] 2023-01-27 01:05
Hey @GrassHopper42, can you maybe create a reproduction of the problem and put it on GitHub? That would help us a lot to understand and fix it. We are currently working on a workaround for similar problems, so being able to confirm that via a previously failing reproduction would be amazing. Thanks!

**Comment by millsp** [comment] 2023-02-03 03:52
Hey, thanks for the feedback. We have been working on a simpler way to make things work for you, as the workaround we proposed had clear limitations for TS projects. We worked on an experimental webpack plugin that ensures your Prisma files are copied correctly. I'd love if you could give it a try (https://www.npmjs.com/package/experimental-prisma-webpack-plugin). We have tested it in many different scenarios, so we hope this works for you.

```ts
const { PrismaPlugin } = require('experimental-prisma-webpack-plugin')

module.exports = {
  output: 'standalone',
  webpack: (config, { isServer }) => {
    if (isServer) {
      config.plugins = [...config.plugins, new PrismaPlugin()]
    }

    return config
  },
}
```

**Comment by GrassHopper42** [comment] 2023-02-04 15:01
> Hey @GrassHopper42, can you maybe create a reproduction of the problem and put it on GitHub? That would help us a lot to understand and fix it. We are currently working on a workaround for similar problems, so being able to confirm that via a previously failing reproduction would be amazing. Thanks!

I'm sorry but it was too long ago to reproduce. I've forgotten this issue..

**Comment by Karabur** [comment] 2023-02-20 22:17
> Hey, thanks for the feedback.
> 
> We have been working on a simpler way to make things work for you, as the workaround we proposed had clear limitations for TS projects. We worked on an experimental webpack plugin that ensures your Prisma files are copied correctly. I'd love if you could give it a try (https://www.npmjs.com/package/experimental-prisma-webpack-plugin). We have tested it in many different scenarios, so we hope this works for you.
> 
> ```ts
> const { PrismaPlugin } = require('experimental-prisma-webpack-plugin')
> 
> module.exports = {
>   output: 'standalone',
>   webpack: (config, { isServer }) => {
>     if (isServer) {
>       config.plugins = [...config.plugins, new PrismaPlugin()]
>     }
> 
>     return config
>   },
> }
> ```

I've tried your plugin, and while it do copies schema file, it also renames it by default to `schema.prisma1`. 
While it also renames it in source code, that does not work for my setup. 

To the context: I am deploying NextJS project to vercel including prisma in Api Route. 
having `api/my-route.ts` as 
```
import { PrismaClient } from '.prisma/client';

const prisma = new PrismaClient();
```

I can confirm it does copy file and update import in source code locally, but then deploying on vercel I'm getting error indicating `@prisma/client` package still refers to `schema.prisma` file, sorry, no screenshot here. 
My guess it is related to having that lines in `next.config.js`
```
experimental: {
    serverComponentsExternalPackages: ['@prisma/client'],
  },
```
which is default in new versions of NextJs and probably resulting in copying it as-is to the output build, so it's source code keeps unaffected and still referencing `schema.prisma`


So, I've updated your plugin and removed rename block all together and it works fine now.

**Comment by millsp** [comment] 2023-02-21 01:43
Hey @Karabur, thanks for the report. I think that because you're importing from `.prisma/client` and not `@prisma/client`, the code is not marked as external. It will be external as soon as you change to `@prisma/client`. But maybe you have a custom output? Regardless, I think the plugin should work for your use-case too. Could you please provide us with a simple reproduction? Then I could soon look into how to make it work for you.

**Comment by Karabur** [comment] 2023-02-21 20:11
@millsp I can confirm what when I change `.prisma/client` to `@prisma/client` that works. 
Thanks for a hint

**Closed** 2023-02-24 17:34 UTC
Labels: bug/1-unconfirmed, kind/bug, tech/typescript, topic: yarn workspaces, topic: Next.js, team/client, topic: monorepo, topic: ENOENT schema.prisma

**Comment by millsp** [comment] 2023-02-24 17:40
For those using multiple Prisma Clients, we are going to schedule follow-up work via https://github.com/prisma/prisma/issues/18069. Please upvote it if you need multi-client support, and don't hesitate to share more information there.

**Comment by nklisch** [comment] 2023-03-26 22:32
I found another issue with the plugin - if you use tsconfig.json paths: to remap your import paths, this plug-in can't handled that:
Found in create t3 app base setup:
```
{
  "compilerOptions": {
    "target": "es2017",
    "lib": ["dom", "dom.iterable", "esnext"],
    "allowJs": true,
    "checkJs": true,
    "skipLibCheck": true,
    "strict": true,
    "forceConsistentCasingInFileNames": true,
    "noEmit": true,
    "esModuleInterop": true,
    "module": "esnext",
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "jsx": "preserve",
    "incremental": true,
    "noUncheckedIndexedAccess": true,
    "baseUrl": ".",
    "paths": {
      "~/*": ["./src/*"]
    }
  },
  "include": [
    ".eslintrc.cjs",
    "next-env.d.ts",
    "**/*.ts",
    "**/*.tsx",
    "**/*.cjs",
    "**/*.mjs"
  ],
  "exclude": ["node_modules"]
}
```
you have to do the full relative path other wise the mapping doesn't work.

**Comment by millsp** [comment] 2023-03-27 14:40
Hey @nklisch, thanks for the report. Could you please open a separate issue with some steps for us to reproduce this?
