### ISSUE TITLE
PANIC in libs/prisma-models/src/record.rs:161:30Invalid coercion encountered: ConversionFailure("Bytes([125, 14, 147, 14, 185, 241, 17, 235, 164, 76, 2, 66, 172, 24, 0, 2])", "Bytes")

### ISSUE THREAD

**Issue by HyperCharlie** [prisma/prisma#7214] opened 2021-05-21 23:16 UTC
Hi Prisma Team! I have been using prisma 2.21.2, and every time I upgrade it past that, I get core panics, with no other changes. I have re-generated the client code after the upgrade, but it makes no difference.

Also, in the off chance someone takes a look at this, I am attempting to use Binary UUIDs for my DB keys, and they don't work with:

```
where: {
  id: { in: binaryIds},
},
```
I'm not aware of a SQL limitation with IN and binary columns but I'm not a SQL guru so that's pretty meaningless. Is support for binary lists anywhere on the roadmap? The way I write repositories makes this a pretty big limitation; I've been trying to use raw queries to work around it but that makes everything else more difficult.

## Versions

| Name            | Version            |
|-----------------|--------------------|
| Node            | v14.17.0           |
| OS              | debian-openssl-1.1.x
| Prisma Client   | 2.23.0          |   
| Query Engine    | query-engine adf5e8cba3daf12d456d911d72b6e9418681b28b |
| Database        | Mysql|

## Query
```
query {
  findManyProductEntity(where: {
    client_id: {
      in: ["X"]
    }
  }) {
    id
    client_id
    client_secret
    created_at
    updated_at
    business_name
    description
  }
}
```

## Logs
```
prisma:tryLoadEnv Environment variables not found at null
prisma:tryLoadEnv Environment variables loaded from /home/node/app/packages/microservice/.env
prisma:tryLoadEnv Environment variables not found at null
prisma:tryLoadEnv Environment variables loaded from /home/node/app/packages/microservice/.env
prisma:client clientVersion: 2.23.0
prisma:engine {
  cwd: '/home/node/app/packages/microservice/src/implementations/data/prisma'
}
prisma:engine Search for Query Engine in /home/node/app/node_modules/.prisma/client
prisma:engine Search for Query Engine in /home/node/app/node_modules/.prisma/client
plusX Execution permissions of /home/node/app/node_modules/.prisma/client/query-engine-debian-openssl-1.1.x are fine
plusX Execution permissions of /home/node/app/node_modules/.prisma/client/query-engine-debian-openssl-1.1.x are fine
prisma:engine { flags: [ '--enable-raw-queries', '--port', '37209' ] }
prisma:engine stdout  Starting a mysql pool with 9 connections.
prisma:engine stdout  Started http server on http://127.0.0.1:37209
prisma:engine Search for Query Engine in /home/node/app/node_modules/.prisma/client
plusX Execution permissions of /home/node/app/node_modules/.prisma/client/query-engine-debian-openssl-1.1.x are fine
prisma:engine Client Version: 2.23.0
prisma:engine Engine Version: query-engine adf5e8cba3daf12d456d911d72b6e9418681b28b
prisma:engine Active provider: mysql
prisma:engine stdout  PANIC in libs/prisma-models/src/record.rs:161:30
Invalid coercion encountered: ConversionFailure("Bytes([125, 14, 147, 14, 185, 241, 17, 235, 164, 76, 2, 66, 172, 24, 0, 2])", "Bytes")
prisma:engine {
  error: SocketError: other side closed
      at Socket.onSocketEnd (/home/node/app/node_modules/@prisma/client/runtime/index.js:25530:24)
      at Socket.emit (events.js:388:22)
      at Socket.emit (domain.js:470:12)
      at endReadableNT (internal/streams/readable.js:1336:12)
      at processTicksAndRejections (internal/process/task_queues.js:82:21) {
    code: 'UND_ERR_SOCKET'
  }
}
prisma:engine {
  error: Error: connect ECONNREFUSED 127.0.0.1:37209
      at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1146:16) {
    errno: -111,
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '127.0.0.1',
    port: 37209
  }
}
prisma:engine {
  cwd: '/home/node/app/packages/microservice/src/implementations/data/prisma'
}
prisma:engine Search for Query Engine in /home/node/app/node_modules/.prisma/client
plusX Execution permissions of /home/node/app/node_modules/.prisma/client/query-engine-debian-openssl-1.1.x are fine
prisma:engine { flags: [ '--enable-raw-queries', '--port', '42427' ] }
prisma:engine stdout  Starting a mysql pool with 9 connections.
prisma:engine stdout  Started http server on http://127.0.0.1:42427
prisma:engine Search for Query Engine in /home/node/app/node_modules/.prisma/client
plusX Execution permissions of /home/node/app/node_modules/.prisma/client/query-engine-debian-openssl-1.1.x are fine
prisma:engine stdout  PANIC in libs/prisma-models/src/record.rs:161:30
Invalid coercion encountered: ConversionFailure("Bytes([125, 14, 147, 14, 185, 241, 17, 235, 164, 76, 2, 66, 172, 24, 0, 2])", "Bytes")
prisma:engine {
  error: SocketError: other side closed
      at Socket.onSocketEnd (/home/node/app/node_modules/@prisma/client/runtime/index.js:25530:24)
      at Socket.emit (events.js:388:22)
      at Socket.emit (domain.js:470:12)
      at endReadableNT (internal/streams/readable.js:1336:12)
      at processTicksAndRejections (internal/process/task_queues.js:82:21) {
    code: 'UND_ERR_SOCKET'
  }
}
```

## Client Snippet
```ts
public getByClientId(
    clientIds: string[]
  ): ResultAsync<Map<string, Product>, DatabaseError> {
    console.log("getByClientId");
    return this.prismaProvider
      .getPrismaClient()
      .andThen((prisma) => {
        return ResultAsync.fromPromise(
          prisma.productEntity.findMany({
            where: {
              client_id: { in: clientIds },
            },
          }),
          (e) => {
            return e as DatabaseError;
          }
        );
      })
      .map((entities) => {
        const map = new Map();

        for (const entity of entities) {
          const obj = this.entityToObject(entity);
          map.set(obj.clientId, obj);
        }

        return map;
      });
  }
```

## Schema
```prisma
generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "mysql"
  url      = env("DATABASE_URL")
}

model CustomerEntity {
  id               Bytes                   @id @db.Binary(16)
  external_id      String                  @unique @db.VarChar(36)
  createdAt        DateTime                @db.DateTime(0)
  updatedAt        DateTime                @db.DateTime(0)
  username         String                  @db.VarChar(64)
  email            String?                 @db.VarChar(64)
  given_name       String?                 @db.VarChar(64)
  family_name      String?                 @db.VarChar(64)
  nickname         String?                 @db.VarChar(64)
  picture          String?                 @db.VarChar(256)
  locale           String?                 @db.VarChar(5)
  email_verified   Boolean?
  birthday         DateTime?               @db.DateTime(0)
  customer_product CustomerProductEntity[] @relation("customer_product_tTocustomer_t")
  payments         PaymentEntity[]

  @@map("customer_t")
}

model PaymentDetailsEntity {
  id                                                         Bytes           @id @db.Binary(16)
  sender_public_identifier                                   String          @db.VarChar(60)
  receiver_public_identifier                                 String          @db.VarChar(60)
  payment_id                                                 String?         @db.VarChar(66)
  amount                                                     String          @db.VarChar(30)
  payment_type                                               Int
  status                                                     Int
  payment_amount                                             String          @db.VarChar(30)
  insurance_amount                                           String          @db.VarChar(30)
  payment_token_address                                      String          @db.VarChar(42)
  expiration_date                                            DateTime        @db.DateTime(0)
  createdAt                                                  DateTime        @db.DateTime(0)
  updatedAt                                                  DateTime        @db.DateTime(0)
  payment_t_payment_details_tTopayment_t_receiver_details_id PaymentEntity[] @relation("payment_details_tTopayment_t_receiver_details_id")
  payment_t_payment_details_tTopayment_t_sender_details_id   PaymentEntity[] @relation("payment_details_tTopayment_t_sender_details_id")

  @@map("payment_details_t")
}

model PaymentEntity {
  id                         Bytes                 @id @db.Binary(16)
  createdAt                  DateTime              @db.DateTime(0)
  updatedAt                  DateTime              @db.DateTime(0)
  customer_id                Bytes                 @db.Binary(16)
  payment_type               Int
  amount                     Decimal               @db.Decimal(64, 0)
  payment_token              String                @db.VarChar(42)
  required_insurance         Decimal               @db.Decimal(64, 0)
  expiration_date            DateTime              @db.DateTime(0)
  sender_user_id             Bytes                 @db.Binary(16)
  receiver_user_id           Bytes?                @db.Binary(16)
  receiver_public_identifier String                @db.VarChar(60)
  payment_id                 String?               @db.VarChar(66)
  sender_details_id          Bytes?                @db.Binary(16)
  receiver_details_id        Bytes?                @db.Binary(16)
  received_amount            Decimal?              @db.Decimal(27, 18)
  insurance_amount           Decimal?              @db.Decimal(27, 18)
  customer                   CustomerEntity        @relation(fields: [customer_id], references: [id])
  receiverDetails            PaymentDetailsEntity? @relation("payment_details_tTopayment_t_receiver_details_id", fields: [receiver_details_id], references: [id])
  receiverUser               UserEntity?           @relation("payment_t_receiver_user_idTouser_t", fields: [receiver_user_id], references: [id])
  senderDetails              PaymentDetailsEntity? @relation("payment_details_tTopayment_t_sender_details_id", fields: [sender_details_id], references: [id])
  senderUser                 UserEntity            @relation("payment_t_sender_user_idTouser_t", fields: [sender_user_id], references: [id])

  @@index([customer_id], name: "fk_payment_customer")
  @@index([receiver_details_id], name: "fk_receiver_payment_payment_details")
  @@index([receiver_user_id], name: "fk_receiver_payment_user")
  @@index([sender_details_id], name: "fk_sender_payment_payment_details")
  @@index([sender_user_id], name: "fk_sender_payment_user")
  @@map("payment_t")
}

model UserEntity {
  id                Bytes               @id @db.Binary(16)
  public_identifier String              @db.VarChar(60)
  nonce             String              @db.VarChar(64)
  createdAt         DateTime            @db.DateTime(0)
  updatedAt         DateTime            @db.DateTime(0)
  receivedPayments  PaymentEntity[]     @relation("payment_t_receiver_user_idTouser_t")
  sentPayments      PaymentEntity[]     @relation("payment_t_sender_user_idTouser_t")
  product_user      ProductUserEntity[] @relation("product_user_tTouser_t")

  @@map("user_t")
}

model CustomerProductEntity {
  id          Bytes          @id @db.Binary(16)
  customer_id Bytes          @db.Binary(16)
  product_id  Bytes          @db.Binary(16)
  role        Int            @default(0)
  created_at  DateTime       @db.DateTime(0)
  updated_at  DateTime       @db.DateTime(0)
  customer    CustomerEntity @relation("customer_product_tTocustomer_t", fields: [customer_id], references: [id])
  product     ProductEntity  @relation(fields: [product_id], references: [id])

  @@index([customer_id], name: "fk_customer_integration_customer_idx")
  @@index([product_id], name: "fk_customer_integration_integration_idx")
  @@map("customer_product_t")
}

model ProductEntity {
  id               Bytes                   @id @db.Binary(16)
  client_id        String                  @db.VarChar(45)
  client_secret    String                  @db.VarChar(64)
  created_at       DateTime                @db.DateTime(0)
  updated_at       DateTime                @db.DateTime(0)
  business_name    String                  @db.VarChar(100)
  description      String                  @db.Text
  customer_product CustomerProductEntity[]
  product_user     ProductUserEntity[]

  @@map("product_t")
}

model ProductUserEntity {
  id         Bytes         @id @db.Binary(16)
  product_id Bytes         @db.Binary(16)
  user_id    Bytes         @db.Binary(16)
  nonce      String        @db.VarChar(64)
  signature  String?       @db.VarChar(132)
  createdAt  DateTime      @db.DateTime(0)
  updatedAt  DateTime      @db.DateTime(0)
  product    ProductEntity @relation(fields: [product_id], references: [id])
  user       UserEntity    @relation("product_user_tTouser_t", fields: [user_id], references: [id])

  @@index([user_id], name: "fk_customer_user_user")
  @@index([product_id], name: "fk_integration_user_integration_idx")
  @@map("product_user_t")
}

```

**Comment by janpio** [comment] 2021-05-21 23:20
Optimally create an additional issue or discussion for your questions or challenges there, so we can focus on debugging this crash here. Thanks.

Can you maybe quickly create a minimal reproduction example of the problem, with a minimal schema and application that works in 2.21.2 but does not work in later versions? That would be amazing in helping us reproduce and optimally fix this problem.

What MySQL version are you using?

**Comment by janpio** [comment] 2021-05-21 23:28
This could indeed be a duplicate to https://github.com/prisma/prisma/issues/7097, so we do not need additional information if everything there fits your case as well @HyperCharlie

**Comment by HyperCharlie** [comment] 2021-05-21 23:54
@janpio I'm using MySQL 8, FYI.

I believe I have the same issue as #7097 the more I read it. I also have multiple binary columns in my schema. So let's just focus on that one, and if the fix for that works I can confirm and close this one.

Thanks for the quick response!

**Comment by pantharshit00** [comment] 2021-05-27 18:07
I can confirm this is duplicate of #7097 so please subscribe to that issue.

**Closed by pantharshit00** 2021-05-27 18:07 UTC
Labels: bug/1-repro-available, kind/bug, team/client, topic: native database types, topic: rust panic
