### ISSUE TITLE
Error regarding DATABASE_URL protocol

### ISSUE THREAD

**Issue by mattpengelly** [prisma/prisma#3277] opened 2020-08-13 00:32 UTC
## Bug description

When attempting to run a query or mutation, Prisma is throwing an error that the db protocol is wrong, even though it appears correct:

```
Error:
Invalid `.findMany()` invocation in
C:\Users\mattp\OneDrive\Documents\Development\nerd-prisma-nexus-2.5\nerd-prisma-nexus-2.5\src\query.js:198:7

  194   console.log("newArgs: ", newArgs);
  195   args = newArgs;
  196 }
  197 return ctx.prisma.assessmentAnswer
→ 198   .findMany(
  error: Error validating datasource `db`: The URL for datasource `db` must start with the protocol `mysql://`.
  -->  schema.prisma:7
   |
 6 |   provider = "mysql"
 7 |   url      = env("DATABASE_URL")
   |

Validation Error Count: 1
    at PrismaClientFetcher.request (C:\Users\mattp\OneDrive\Documents\Development\nerd-prisma-nexus-2.5\nerd-prisma-nexus-2.5\node_modules\@prisma\client\runtime\index.js:1:211356)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

## How to reproduce

Use the repo at https://github.com/mattpengelly/prisma-nexus-nerd/blob/master/prisma/schema.prisma to create a db, generate prisma and run the playground.

## Expected behavior

Queries and mutations work as expected.

## Prisma information

I included my db info in the .env file since that's where the error appears to be coming from.

## Environment & setup

- OS:  Windows
- Database:  MariaDB
- Node.js version: 12.6.1
- Prisma version:  2.4.1

**Comment by pantharshit00** [comment] 2020-08-13 23:12
I wasn't even able to migrate the schema:
![image](https://user-images.githubusercontent.com/22195362/90195767-f1139e00-dde7-11ea-97f3-284d12d781ba.png)


This schema looks introspected, did you make any specific changes? Also, can you please tell me the exact version of mariadb that you are using?

**Comment by janpio** [comment] 2020-08-14 11:29
Can you possibly just upload a SQL schema export from that database @mattpengelly? Then @pantharshit00 does not need to use our migrate but can work on the exact same database as you.

**Comment by mattpengelly** [comment] 2020-08-17 17:47
Here is the schema for the db.  Please let me know if you have any issues with it.


[r5ahc4qa0enfvbop.zip](https://github.com/prisma/prisma/files/5085947/r5ahc4qa0enfvbop.zip)

**Comment by pantharshit00** [comment] 2020-08-24 11:17
I am unable to reproduce this after using the schema that you have posted. 

Try upgrading prisma client to latest version and clearing your `node_modules` once. 

![image](https://user-images.githubusercontent.com/22195362/91039041-75a4be80-e629-11ea-825e-817a94083e4c.png)

**Comment by pantharshit00** [comment] 2020-08-24 13:54
Also, please make sure that your actual connection string that you are passing is in this format: https://www.prisma.io/docs/reference/database-connectors/connection-urls#examples

**Comment by bre7** [comment] 2020-09-16 03:17
The error can be something else though. In my case I deleted the last `"` (there should be an `.env` linter)

**Comment by divyenduz** [comment] 2020-09-16 09:24
This happens when you are using an env var and the env var does not exist/doesn't have the correct provider value (@pantharshit00 can you please validate that?)

If we are able to reproduce it like so, I agree that the error should be more helpful.

**Comment by pantharshit00** [comment] 2020-09-16 13:15
@divyenduz 

I am unable to reproduce this with `2.7`
1. Non existant env var
![image](https://user-images.githubusercontent.com/22195362/93342218-b4a2ea00-f84c-11ea-995d-8647d7691004.png)

2. Wrong protocol
![image](https://user-images.githubusercontent.com/22195362/93342318-d4d2a900-f84c-11ea-8372-de1b3f9bdf6b.png)

**Comment by tomhoule** [comment] 2021-02-25 10:56
This issue is about very old versions of prisma, we'll just close it. If you experience something similar on a recent version, please open a new issue. Thanks!

**Closed by tomhoule** 2021-02-25 10:56 UTC
Labels: bug/0-needs-info, kind/bug, status/needs-action
