### ISSUE TITLE
prisma init: add .env to root instead of ./prisma 

### ISSUE THREAD

**Issue by timsuchanek** [prisma/prisma#4293] opened 2020-11-18 08:15 UTC
The `prisma init` command should add the `.env` file to the root of the project instead of the `prisma` dir. This needs conflict resolution logic in case there already is a `.env` file:

- If there is no conflict with the existing env vars, append
- If the env var about to be added already is defined, throw an error

**Comment by matthewmueller** [comment] 2020-11-18 11:23
Duplicate of https://github.com/prisma/prisma/issues/3721

**Closed by matthewmueller** 2020-11-18 11:23 UTC
Labels: kind/improvement, process/candidate, team/client, tech/typescript
