### ISSUE TITLE
Error creating an object with a connect input

### ISSUE THREAD

**Issue by marticrespi** [prisma/prisma#4128] opened 2019-03-05 11:45 UTC
**Describe the bug**
Trying to create a new object with a connection type fails.

**To Reproduce**
My datamodel is here:
[datamodel.prisma.txt](https://github.com/prisma/prisma/files/2930726/datamodel.prisma.txt)

My summarized database model here:
[DDBB_script.txt](https://github.com/prisma/prisma/files/2930734/DDBB_script.txt)

I have customertype entities from 1 to 4, (4 inserts included in the above script). When I try to send a mutation to create a new customer, it fails.

`Mutation`
````
mutation CreateCustomer($customer: CustomerCreateInput!) {
  createCustomer(data: $customer) {
    code
  }
}
````
`Variables`
````
{
  "customer" : {
    "code": "TEST",
    "name": "Test Test",
    "type": {
      "connect": {
        "id": 3,
        "code": "PBUY"
      }
    },
    "sapCode":"TESTSAP"
  }
}
````

I recieve this error from docker.. It's trying to insert null in type field..

````
org.postgresql.util.PSQLException: ERROR: null value in column "type" violates not-null constraint
  Detail: Failing row contains (4, TEST, TESTSAP, Test TEst, null, 2019-03-05 11:32:15.134+00, 2019-03-05 11:32:15.134+00).
at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2433)
at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2178)
at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:306)
at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:441)
at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:365)
at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:155)
at org.postgresql.jdbc.PgPreparedStatement.execute(PgPreparedStatement.java:144)
at com.zaxxer.hikari.pool.ProxyPreparedStatement.execute(ProxyPreparedStatement.java:44)
at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.execute(HikariProxyPreparedStatement.java)
at com.prisma.connector.shared.jdbc.SharedSlickExtensions.$anonfun$insertReturningGeneratedKeysToDBIO$1(SharedSlickExtensions.scala:28)
at com.prisma.connector.shared.jdbc.SharedSlickExtensions.$anonfun$jooqToDBIO$1(SharedSlickExtensions.scala:62)
at slick.jdbc.SimpleJdbcAction.run(StreamingInvokerAction.scala:70)
at slick.jdbc.SimpleJdbcAction.run(StreamingInvokerAction.scala:69)
at slick.basic.BasicBackend$DatabaseDef$$anon$2.liftedTree1$1(BasicBackend.scala:275)
at slick.basic.BasicBackend$DatabaseDef$$anon$2.run(BasicBackend.scala:275)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
````

**Expected behavior**
Create a customer succesfully linking its type to an existing type.

**Versions (please complete the following information):**
 - Connector: `Postgres`
 - Prisma Server: `1.27.4`
 - `prisma` CLI: `prisma/1.29.0-alpha.7 (windows-x64) node-v8.9.4`
 - OS: `Windows 10`
 - Prisma client: `1.27.4`

**Comment by epitaphmike** [comment] 2019-03-05 18:38
Same issues here https://github.com/prisma/prisma/issues/3319

**Comment by epitaphmike** [comment] 2019-03-05 18:39
I came ended up using the same "fix" as mentioned here https://github.com/prisma/prisma/issues/3319#issuecomment-443395291

While not ideal, it may help you in the interim.

**Comment by marticrespi** [comment] 2019-03-06 06:52
But if I have to remove the non null contrainst I will get inconsistent data, for sure! Is it a bug from october 2018 and is not fixed yet? 🤔 

Thanks!

**Comment by pantharshit00** [comment] 2019-03-06 16:13
Hi @marticrespi 

I believe this is something that the new datamodel 1.1 will fix so I think that is why it is not being updated. The new datamodel is under a prototype flag in the current release. Can you try that with that? https://github.com/prisma/prisma/issues/3233#issuecomment-465513624

For now I am going to close this issue as a duplicate of #3319

**Closed by pantharshit00** 2019-03-06 16:13 UTC

**Comment by marticrespi** [comment] 2019-03-07 06:54
@pantharshit00 I have already rawAccess = true. Only works if you remove the FK from database.

**Comment by james-ff** [comment] 2019-04-03 00:22
Having the same problem
