### ISSUE TITLE
MongoDB findRaw doesn't seem to work

### ISSUE THREAD

**Issue by stringbeans** [prisma/prisma#12124] opened 2022-03-02 23:30 UTC
### Bug description

I can't seem to use the MongoDB `findRaw` command successfully. I can verify that `findFirst` works though on the same client. For example...

```
// doesnt work
console.log(await client.user.findRaw({
  filter: {
    id: {$eq: '6M4D3ncvpAWy2Fo8T'}
  }
}))

// does work
console.log(await client.user.findFirst({
  where: {
    id: '6M4D3ncvpAWy2Fo8T'
  }
}))
```
Note: I don't think its related to how the IDs are defined. if i include another basic string field and try to query on that it still doesnt work. Nor a basic Int field.

### How to reproduce

1. Generate a client with the above schema. (Note that our IDs do not use ObjectIds but instead are just unique strings)
2. Try the console.log statements above

### Expected behavior

I expect at least one record to be found.

### Prisma information

my schema is very basic:

```
generator client {
  provider = "prisma-client-js"
  output   = "./generated/mongo-db"
  previewFeatures = ["mongoDb"]
}

datasource db {
  provider = "mongodb"
  url      = env("MONGO_DATABASE_URL")
}

model User {
  id    String  @unique @id  @map("_id") 

  @@map("users")
}
```

### Environment & setup

- OS: PopOS
- Database: MongoDB
- Node.js version: 16.13.2

### Prisma Version

```
prisma                  : 3.10.0
@prisma/client          : 3.10.0
Current platform        : debian-openssl-1.1.x
Query Engine (Node-API) : libquery-engine 73e60b76d394f8d37d8ebd1f8918c79029f0db86 (at node_modules/@prisma/engines/libquery_engine-debian-openssl-1.1.x.so.node)
Migration Engine        : migration-engine-cli 73e60b76d394f8d37d8ebd1f8918c79029f0db86 (at node_modules/@prisma/engines/migration-engine-debian-openssl-1.1.x)
Introspection Engine    : introspection-core 73e60b76d394f8d37d8ebd1f8918c79029f0db86 (at node_modules/@prisma/engines/introspection-engine-debian-openssl-1.1.x)
Format Binary           : prisma-fmt 73e60b76d394f8d37d8ebd1f8918c79029f0db86 (at node_modules/@prisma/engines/prisma-fmt-debian-openssl-1.1.x)
Default Engines Hash    : 73e60b76d394f8d37d8ebd1f8918c79029f0db86
Studio                  : 0.458.0
```

**Comment by millsp** [comment] 2022-03-03 12:02
Hey @stringbeans, since ids are represented with `ObjectId`s or `$oid` on the db level, you need to build your query like the following:

```ts
    const users = await prisma.user.findRaw({
        filter: {
            _id: { $eq: { $oid: "6202ec178be26d2b28adc075" } },
        },
    })
```

**Comment by matthewmueller** [comment] 2022-03-03 17:21
Thanks @millsp. This seems like a duplicate of: https://github.com/prisma/prisma/issues/11830.

I've made a note to get this documented.

**Comment by stringbeans** [comment] 2022-03-03 19:30
@millsp @matthewmueller can we reopen this issue? the suggestion does not fix my issue...

if you take a look at the schema, you will see that the `id` field is simply a string. its not an ObjectID. by running the suggestion i get the following error:

```
console.log(await client.user.findRaw({
      filter: {
        id: {
          $eq: {
            $oid: '6M4D3ncvpAWy2Fo8T'
          }
        }
      }
    }))

====

Invalid `prisma.user.findRaw()` invocation:


  Inconsistent column data: Malformed ObjectID: provided hex string representation must be exactly 12 bytes, instead got: "6M4D3ncvpAWy2Fo8T", length 17.

```

i also mentioned the following note in my original post:

> Note: I don't think its related to how the IDs are defined. if i include another basic string field and try to query on that it still doesnt work. Nor a basic Int field.

**Comment by millsp** [comment] 2022-03-03 20:26
Right, sorry for overlooking this and thanks for reporting. Summary:

This works:
```prisma
model User {
  id      String  @unique @id @map("_id") 
  country String?
}
```
```ts
const users = await prisma.user.findRaw({
  filter: { _id: '6M4D3ncvpAWy2Fo8T' }
})
```

This does not:
```prisma
model User {
  id      String  @unique @id @map("_id") 
  country String?
  
  @@map("users") // <==
}
```

`prisma db push` fails with both:
```ts
Error: MongoDB error
Command failed (InvalidIndexSpecificationOption): The field 'unique' is not valid for an _id index specification. Specification: { key: { _id: 1 }, name: "users__id_key", unique: true, v: 2 })
   0: migration_core::state::SchemaPush
             at migration-engine/core/src/state.rs:342
```

**Comment by matthewmueller** [comment] 2022-03-04 15:18
Sorry for prematurely closing this @stringbeans. Do you mind sharing why you decided to use ids that aren't ObjectIDs in MongoDB?

**Comment by janpio** [comment] 2022-03-04 16:14
@stringbeans Did I understand your sentence correctly that this is not only about `@id` fields but in general, all fields and then searching for/by them via `findRaw`?

**Comment by stringbeans** [comment] 2022-03-04 18:34
@janpio yes thats correct! even if i try searching by other fields (ie. not the `id` field) i still cannot get results back..

@matthewmueller yes! we are working with the collections created by the MeteorJS framework. we're relatively inexperienced with that framework, but from what i understand, MeteorJS does not use ObjectIDs for their id fields but instead uses an internal package `meteor/random` to generate the ids. its something to do with how they manage optimistic UI changes.. this forum post touches on it: https://forums.meteor.com/t/using-mongos-random-ids-instead-of-meteors/17184/10

**Closed** 2022-03-18 10:09 UTC
Labels: bug/2-confirmed, kind/bug, topic: raw, engines/query engine, team/client, topic: mongodb
