### ISSUE TITLE
Prisma cloud creation with existing mySQL database throws error

### ISSUE THREAD

**Issue by thomasjensen1194** [prisma/prisma#4646] opened 2019-06-08 15:02 UTC
**Describe the bug**
It is not possible to create a server through the prisma cloud, using an existing mySQL database. Regardless of specifying the schema or not, the following error is thrown: 
`2019-06-08T14:59:22.171854+00:00 app[web.1]: Exception in thread "main" java.lang.RuntimeException: Unable to load Prisma config: com.prisma.config.InvalidConfiguration: Only Postgres connectors are allowed to configure schema and database. For others please use database.`

Full log can be found here: https://pastebin.com/Km8t8Zz7

**To Reproduce**
Go to https://www.prisma.io/cloud and create a new server.

**Comment by pantharshit00** [comment] 2019-06-11 14:34
Closing as a duplicate of https://github.com/prisma/prisma/issues/4434

**Closed by pantharshit00** 2019-06-11 14:34 UTC
