### ISSUE TITLE
Deploy issues with 1.25

### ISSUE THREAD

**Issue by yukulelix** [prisma/prisma#3909] opened 2019-01-23 10:08 UTC
**Description of the bug**
Since 1.25 update, I can't deploy anymore. The error I get is `Cannot read property 'steps' of null`. From what I can tell, it comes from deploy.js within prisma-cli-core package. Any chance you could help on this ?

**To Reproduce**
1. Update to 1.25
2. Perform a `prisma deploy`

**Comment by divyenduz** [comment] 2019-01-23 11:33
@yukulelix : Can you please share your Prisma CLI version via `prisma --version`

**Comment by divyenduz** [comment] 2019-01-23 11:35
I suspect that you are on the latest server version but an older CLI version. Ideally, they should be on the same version. Would it be possible for you to update the CLI to latest version if that is the case indeed. 

You can do so via `npm install -g prisma` or `brew install prisma`

**Comment by divyenduz** [comment] 2019-01-23 12:31
@nunsie : Can you please share your Prisma server version as well? Thanks!

**Comment by nunsie** [comment] 2019-01-23 12:33
Sure thing @divyenduz 
`prismagraphql/prisma:1.24`

**Comment by divyenduz** [comment] 2019-01-23 12:34
Got it, so, older Prisma server (1.24) version and newer CLI (1.25) fails to work. Trying a reproduction now.

**Comment by divyenduz** [comment] 2019-01-23 12:48
I am unable to reproduce this with Prisma server version `1.24` and CLI version `1.25`. Can you please provide more information (maybe the datamodel) or a reproduction repository?

**Comment by pantharshit00** [comment] 2019-01-23 14:43
I am able to confirm this @divyenduz. This only happens when there is no change in the datamodel and it throws this error instead of notifying us that the service is already up to date.

Quick repro
1. Clone: https://github.com/baby1990/test-graphql-shield
2. Change version to 1.24 in the compose file
3. Launch the cluster
4. run prisma deploy twice

**Comment by divyenduz** [comment] 2019-01-23 15:05
This is resolved in the latest beta of CLI (`prisma@1.25.0-beta.33`) `npm install -g prisma@beta`

Please give it a go and let me know if the issue still exists. Thanks.

**Comment by jiaxi0713** [comment] 2019-01-24 03:09
@divyenduz : I've updated prisma to 1.25.1 and this issue still occurs while I exec prisma deploy with no change in my datamodel.

**Comment by divyenduz** [comment] 2019-01-24 03:32
@jiaxi0713: this fix is not yet available in stable, can you please try it with the latest beta and let me know?

**Closed** 2019-01-24 12:50 UTC
Labels: area/cli, bug/2-confirmed

**Comment by divyenduz** [comment] 2019-01-24 13:31
This is now available on all release channels, including the latest stable at `1.25.3`, please give it a go via `npm install -g prisma` and let me know if there are any hiccups via comment. Thanks.
