### ISSUE TITLE
[PSL] Request: reuse `struct` definitions within  models

### ISSUE THREAD

**Issue by brandfactoryitalia** [prisma/prisma#22348] opened 2023-12-12 15:38 UTC
It would be very useful in my opinion, the possibility of extending models in a way similar to this:

```prisma
struct BaseConnection {
    apiKey        String
    apiSecret   String
} 


model TelegramConnection {
    ...BaseConnection
    username    String
}

model WhatsappConnection {
    ...BaseConnection
    phone    String
}
```

In this way you can create models that have common fields without having to repeat them every time

**Comment by janpio** [comment] 2024-01-30 19:02
This sounds like a duplicate of https://github.com/prisma/prisma/issues/2371, so I am closing this for now. If you feel your syntax suggestion adds something to the discussion there, please leave a comment. Thanks!

**Closed by janpio** 2024-01-30 19:02 UTC
Labels: kind/feature, tech/engines, team/psl-wg
