### ISSUE TITLE
Select almost all fields but except some fields

### ISSUE THREAD

**Issue by l2D** [prisma/prisma#7954] opened 2021-06-30 12:08 UTC
## Problem
Sometimes I want almost all fields but I don't need some fields. Ex. created_at or updated_at

## Suggested solution
```javascript
const result = await prisma.user.findUnique({
  where: { id: 1 },
  select: {
    except: [field_name_1, .... , field_name_N]
  },
})
```

```javascript
const result = await prisma.user.findUnique({
  where: { id: 1 },
  except: {
      field_name_1: true,
      field_name_n: true,
  },
})
```

**Comment by ryands17** [comment] 2021-06-30 12:44
Duplicate of https://github.com/prisma/prisma/issues/5042

It would be great if you could add a 👍 to that request.

**Closed by ryands17** 2021-06-30 12:44 UTC
