### ISSUE TITLE
`select` for `updateMany`

### ISSUE THREAD

**Issue by heymartinadams** [prisma/prisma#5098] opened 2020-12-23 01:49 UTC
## Problem
There are often instances when we need to update many records and would like certain fields returned at the same time. However, `updateMany` [doesn’t have a `select` property](https://www.prisma.io/docs/concepts/components/prisma-client/crud#updatemany).

## Suggested solution

So instead of this:
```js
// For example: find meditation events and update their names to a generic “Meditation event”
await prisma.event.updateMany({
  where: {
    EventCategory: { name: 'meditation' }
  },
  data: {
    name: 'Meditation event'
  }
})

// ...then get their dates
await prisma.event.findMany({
  where: {
    EventCategory: { name: 'meditation' }
  },
  select: {
    dates: true
  }
})
```

this:
```js
// Find meditation events, update their names to a generic “Meditation event”, and get all of their dates
await prisma.event.updateMany({
  where: {
    EventCategory: { name: 'meditation' }
  },
  data: {
    name: 'Meditation event'
  },
  select: {
    dates: true
  }
})
```

**Comment by helariL** [comment] 2023-03-09 11:32
Any updates on this? 🙏

**Comment by rares2002** [comment] 2023-03-30 14:32
any updates?

**Comment by abrozzesi** [comment] 2023-08-19 13:09
bump

**Comment by janpio** [comment] 2024-04-25 16:53
This seems to be a duplicate of https://github.com/prisma/prisma/issues/5019 - if `updateMany()` can return data, we would most probably also implement `select` to configure what exactly is returned.

**Closed** 2024-04-26 03:59 UTC
Labels: kind/feature, team/client, topic: updateMany(), topic: select

**Comment by gregoryorton-ws** [comment] 2024-05-09 11:24
Why would you close this as 'not planned'? basic ORM feature, no @janpio ?

**Comment by janpio** [comment] 2024-05-10 14:29
As I wrote, this is a duplicate of #5019 which asks for the exact same thing.
