### ISSUE TITLE
Sharing Schema / Models

### ISSUE THREAD

**Issue by mothershipper** [prisma/prisma#21186] opened 2023-09-21 22:59 UTC
## Problem

We have a few patterns we'd like to share across projects that use prisma, for example, a message outbox pattern, where the tables would ideally be consistent across projects and we'd like to distribute the table definitions with the source code.

## Suggested solution

Allow some form of import / additional models file(s) for client generation in the schema syntax:

```
datasource db {
  provider = "postgresql"
  url      = env("MIGRATION_POSTGRES_URI")
}

// ----- Models -----
model Customer {
  ...
}

include OutboxLib {
  models = "../node_modules/@our-org/outboxlib/schema.prisma"
}
```

Or perhaps a syntax as follows could allow for eventual overrides / customization:

```
// Allows end-user to customize / stamp out tables
model CustomerTopicOutboxMessages {
  // file path reference, name of the model we're pulling out
  @@import('../node_modules/@our-org/outboxlib/schema.prisma', OutboxMessages)
}

model InvoiceTopicOutboxMessages {
  @@import('../node_modules/@our-org/outboxlib/schema.prisma', OutboxMessages)
}
```

## Alternatives

We looked a little bit at the client extensions, but it didn't seem like that would integrate with the migration product.

We could just ask devs to copy/paste, but this feels like a quick way to ensure these "standard" tables become anything but.

**Comment by Jolg42** [comment] 2023-10-24 12:24
Closing as duplicate of https://github.com/prisma/prisma/issues/2377

I can't say much about this beside that we want to do something "in the future", hopefully "soon".

**Closed by Jolg42** 2023-10-24 12:24 UTC
Labels: kind/feature, topic: schema, team/schema, topic: schema file
