### ISSUE TITLE
Cannot read properties of undefined error while working inside of an interactive transaction and trying to connect relations

### ISSUE THREAD

**Issue by BlackoutGG** [prisma/prisma#17486] opened 2023-01-23 17:11 UTC
Prisma: 4.8.x
Postgres: 13.x

Here's my use case:

I have a collection of users, each user can have multiple roles, and roles can belong to multiple users. In my scenario I can apply and remove roles from users (connect/disconnect).

First my schema:

```
model User {
    id            String         @id @default(cuid())
    discordId     String?        @map(name: "discord_id") @db.VarChar(255)
    username      String?        @unique() @db.Char(50)
    email         String         @unique() @db.VarChar(255)
    emailVerified DateTime?      @map(name: "email_verified")
    avatar        String?        @db.VarChar(255)
    securityLevel SecurityLevel  @default(GUEST) @map(name: "security_level")
    isDeletable   Boolean?       @default(true) @map(name: "is_deletable")
    isSuperAdmin  Boolean?       @default(false) @map(name: "is_super_admin")
    isAdmin       Boolean?       @default(false) @map(name: "is_admin")
    createdAt     DateTime?      @default(now()) @map(name: "created_at") @db.Timestamptz(6)
    updatedAt     DateTime?      @default(now()) @map(name: "updated_at") @db.Timestamptz(6)
    profile       UserProfile?
    roles         UserRoles[]
    policies      UserPolicies[]
    accounts      Account[]

    @@map("users")
}

model UserRoles {
    user       User        @relation(fields: [userId], references: [id], onUpdate: Cascade, onDelete: Cascade)
    userId     String      @map(name: "user_id")
    role       Role        @relation(fields: [roleId], references: [id], onUpdate: Cascade, onDelete: Cascade)
    roleId     String      @map(name: "role_id")
    assignedBy AssignedBy? @default(SITE)
    assignedAt DateTime    @default(now())

    @@id([userId, roleId])
    @@map("user_roles")
}

model Role {
    id            String         @id @default(cuid())
    name          String         @unique() @db.VarChar(255)
    securityLevel SecurityLevel  @default(ADMIN) @map(name: "security_level")
    isDeletable   Boolean?       @default(true) @map(name: "is_deletable")
    createdAt     DateTime       @default(now()) @map(name: "created_at") @db.Timestamptz
    updatedAt     DateTime       @default(now()) @map(name: "updated_at") @db.Timestamptz
    users         UserRoles[]
    policies      RolePolicies[]

    @@map("roles")
}

```

I join the role to the user through an explicit relation(join) table. My endpoint calls this function:

```
async updateUser(
      id: string,
      user: Partial<Omit<User, "id" | "discordId">>,
      roles: Relation | undefined,
      policies: Relation | undefined
    ): Promise<UserResult> {
      let result = await prisma?.$transaction(
        async (trx): Promise<UserUpgradeQueryResult> => {
          const data: Prisma.UserUncheckedUpdateInput = {};

          const queryData: Prisma.UserUpdateArgs = {
            where: { id },
            data,
            select: {
              id: true,
              username: true,
              updatedAt: true,
              // roles: {
              //   include: {
              //     role: true,
              //   },
              // },
              // policies: {
              //   include: {
              //     policy: true,
              //   },
              // },
            },
          };

          if (roles != undefined) {
            queryData.select! = {
              ...queryData.select,
              roles: {
                include: {
                  role: true,
                },
              },
            };
          }

          if (policies != undefined) {
            queryData.select! = {
              ...queryData.select,
              policies: {
                include: {
                  policy: true,
                },
              },
            };
          }

          if (roles?.connect?.length) {
           await relate(
              id,
              roles.connect,
              "userId_roleId",
              trx.userRoles as unknown as Prisma.TransactionClient
            );

    
          }

          if (roles?.disconnect?.length) {
            await unrelate(
              id,
              roles.disconnect,
              "userId_roleId",
              trx.userRoles as unknown as Prisma.TransactionClient
            );
          }

          let result: any;

          if (user) {
            Object.assign(data, user);
            result = trx.user.update(queryData);
          } else {
            result = trx.user.findUnique({
              where: queryData.where,
              select: queryData.select,
            });
          }

          

          return (await result) as UserData;
        }

```
Without going too into detail and off track, the transaction returns a user record, with or without roles depending on if roles is something that requires to be updated on the user (connected/disconnected). Because the relation is a list, when it comes to disconnecting a relation, I cannot use disconnect in queryData, I have to do it manually using trx.userRoles. This works fine.

However when it comes to connecting a role within the transaction, using the transaction client (trx), I get the following error:
```
TypeError: Cannot read properties of undefined (reading 'roleId')                                                                                                                                                                                            11:46:40
    at file:///home/blackout/Projects/workplaces/site-nuxt3/nuxt-app/.nuxt/dev/index.mjs:1219:47
    at async PrismaClient._request (/home/blackout/Projects/workplaces/site-nuxt3/nuxt-app/node_modules/@prisma/client/runtime/index.js:36082:16)
    at async file:///home/blackout/Projects/workplaces/site-nuxt3/nuxt-app/.nuxt/dev/index.mjs:957:13
    at async Proxy._transactionWithCallback (/home/blackout/Projects/workplaces/site-nuxt3/nuxt-app/node_modules/@prisma/client/runtime/index.js:36014:18)
    at async Proxy.updateUser (file:///home/blackout/Projects/workplaces/site-nuxt3/nuxt-app/.nuxt/dev/index.mjs:920:20)
    at async file:///home/blackout/Projects/workplaces/site-nuxt3/nuxt-app/.nuxt/dev/index.mjs:1489:20
    at async Object.handler (file:///home/blackout/Projects/workplaces/site-nuxt3/nuxt-app/node_modules/h3/dist/index.mjs:723:19)
    at async Server.toNodeHandle (file:///home/blackout/Projects/workplaces/site-nuxt3/nuxt-app/node_modules/h3/dist/index.mjs:798:7) {
  clientVersion: '4.8.0'
}
```

If I pass the prisma (where p is the prisma client) client directly to the relate function, everything works fine. 
```
await relate(
              id,
              roles.connect,
              "userId_roleId",
              p.userRoles
            ); <-- works
            
 await relate(id, roles.connect, "userId_roleId, trx.userRoles) <-- doesn't work
```

```
the relate function:
const relate = async (
  id: string,
  relation: RelationItem[],
  key: string,
  trx: Prisma.TransactionClient
) => {
  if (Array.isArray(relation)) {
    if (relation.length > 1) {
      const data = relation.map((r) => getIndex(key, id, r.id));

      console.log(data);

      return (trx as any).createMany({ data });
    }
    const data = getIndex(key, id, relation[0].id);

    console.log(data);
    return (trx as any).create({ data });
  } else {
    throw new Error("[relate]: Relation must be an array.");
  }
};
```

This is problematic because if there's a failure anywhere inside the transaction flow I want to roll back all the queries.

Why is this happening?

**Comment by Jolg42** [comment] 2023-07-13 13:11
@BlackoutGG can you reproduce this with a recent version of Prisma?

Note: The error stack looks like there might be a problem in your code 🤔

**Comment by SevInf** [comment] 2023-07-24 09:42
Hi @BlackoutGG , did you have a chance to look at @Jolg42  comment?

It'd be helpful for us to move your issue forward.

Without further information, we'll have to close this issue. Thank you 🙏

**Comment by SevInf** [comment] 2023-07-31 13:47
Hey @BlackoutGG ,
 

With the lack of information and our inability to reproduce this issue, we're now closing it. Feel free to comment if you have any updates about it.
 
Thank you 🙏

**Closed by SevInf** 2023-07-31 13:47 UTC
Labels: bug/0-unknown, kind/bug, topic: prisma-client, tech/typescript, team/client, topic: interactiveTransactions
