### ISSUE TITLE
prisma query '= null' not 'is null' in sql where clause

### ISSUE THREAD

**Issue by roseline124** [prisma/prisma#3727] opened 2020-09-22 07:09 UTC
## Bug description

There are  posts the 'postDraft.metadata' column is null.
But the query cannot find any posts. 

And I found `where metadata::jsonb = null` the sql query
I think it should be `is null`
(params are $1="tech", $2=null, $3=0)

I'm prisma beginner so if I missed something please let me know :)

```
select
	"public"."Post"."url",
	"public"."Post"."categoryId",
	"public"."Post"."id",
	"public"."Post"."createdAt"
from
	"public"."Post"
where
	("public"."Post"."categoryId" = $1
	and ("public"."Post"."url", "public"."Post"."categoryId") in (
	select
		"t0"."url", "t0"."categoryId"
	from
		"public"."Post" as "t0"
	inner join "public"."PostDraft" as "j0" on
		("j0"."url") = ("t0"."url")
	where
		"j0"."metadata"::jsonb = $2 )) offset $3;
```

## Expected behavior

I think it should be `is null` not `= null` when filtering with null

```
"j0"."metadata"::jsonb is null )) offset 0;
```

## Prisma information

`Post` model is related to `PostDraft` like below.

```
model Post {
  id           String    @unique
  url          String
  draft        PostDraft @relation(fields: [url], references: [url])
  categoryId String
  createdAt    DateTime  @default(now())

  @@id([url, categoryId])
}

model PostDraft {
  url        String          @id
  metadata   Json?
  createdAt  DateTime        @default(now())

  Post Post[]
}
```

this is my prisma query.

```javascript
const posts = await prisma.post.findMany({
    where: {
      categoryId,
      draft: {
        metadata: null,
      },
    },
  })
```

## Environment & setup

- OS: Mac OS
- Database: PostgreSQL
- Node.js version: 12.18.3
- Prisma version: 2.5.1

**Comment by pantharshit00** [comment] 2020-09-23 15:03
Hi,

Thanks for reporting this! It has already been reported before, so I am going to close this as a duplicate of https://github.com/prisma/prisma/issues/3579

Indeed the query generated here is wrong as there is a protocol issue between client and engine where client is sending `"NULL"` as a string to the prisma engine.

**Closed by pantharshit00** 2020-09-23 15:03 UTC
