### ISSUE TITLE
"message": "Cannot query field 'id' on type 'AirMoistureSensor'. 

### ISSUE THREAD

**Issue by artem-korolev** [prisma/prisma#4314] opened 2019-04-04 23:44 UTC
I have datamodel like this:
`
type Metric {
	id: ID! @unique @id
	airMoistureSensors: [AirMoistureSensor!]!
}

type AirMoistureSensor @embedded {
	pin: Int!
	value: Int!
}
`

prisma deploys this successfuly. But when I go to prisma Admin (new beta feature). I create Metric.. cannot insert AirMoistureSensor values. After refreshing Admin interface I get this error:
""message": "Cannot query field 'id' on type 'AirMoistureSensor'. "

And admin interface do not work anymore. It stucks with this error forever, becomes totally unusable

 - Connector:  `MongoDB`
 - Prisma Server: 1.30
 - `prisma` CLI: [e.g. `prisma/1.30.0 (darwin-x64) node-v11`]
 - OS: [e.g. `Linux`]

**Comment by pantharshit00** [comment] 2019-04-05 12:45
@artem-korolev 

Currently, Prisma Admin doesn't support embedded types properly.

Closing as a duplicate of https://github.com/prisma/prisma-admin-feedback/issues/108

Also, see: https://github.com/prisma/prisma-admin-feedback/issues/114

**Closed by pantharshit00** 2019-04-05 12:45 UTC
