### ISSUE TITLE
store .primsa in a directory and make models extensible and variable for different databases

### ISSUE THREAD

**Issue by calidion** [prisma/prisma#10249] opened 2021-11-14 06:33 UTC
## Problem

currently schema.prisma merges `generator`, `datasource`, `model` together within a file, which makes it hard for debugging and extending.

## Suggested solution

I propose that schema.prisma can be both a file and a directory, where we can extend a lot of things inside the directory.
It can be like this:

```
.
├── datasource
│   ├── mongodb.ds
│   ├── mysql.ds
│   └── oracle.ds
├── generator
│   ├── mongodb.gen
│   ├── mysql.gen
│   └── oracle.gen
└── model
    ├── base.model
    └── ext
        ├── mongodb.model
        ├── mysql.model
        ├── oracle.model
        ├── postgre.model
        ├── sqlite.model
        └── sqlserver.model
```

**Comment by pantharshit00** [comment] 2021-11-15 14:44
Hi,

Thanks for reporting this! It has already been reported before, so I am going to close this as a duplicate of https://github.com/prisma/prisma/issues/2377

**Closed by pantharshit00** 2021-11-15 14:44 UTC
