### ISSUE TITLE
N+1 issues when selecting `_count` of relation on a `findMany` query

### ISSUE THREAD

**Issue by JClackett** [prisma/prisma#16829] opened 2022-12-15 10:38 UTC
Hey when running the below query and inspecting the prisma logs, it seems it runs a query for every team to get user count, looks like an n+1 thing, is this known?

```ts
const teams = await prisma.team.findMany({
      select: {
        id: true,
        _count: {
          select: { users: true },
        },
      },
})
```

A short snippet of the logs
```
prisma:query SELECT "public"."Team"."id" FROM "public"."Team" WHERE ("public"."Team"."id" = $1 AND 1=1) LIMIT $2 OFFSET $3
prisma:query SELECT "public"."Team"."id" FROM "public"."Team" WHERE ("public"."Team"."id" = $1 AND 1=1) LIMIT $2 OFFSET $3
prisma:query SELECT "public"."User"."id", "public"."User"."teamId" FROM "public"."User" WHERE (("public"."User"."archivedAt" IS NULL AND "public"."User"."deletedAt" IS NULL) AND "public"."User"."teamId" IN ($1)) OFFSET $2
prisma:query SELECT "public"."Team"."id" FROM "public"."Team" WHERE ("public"."Team"."id" = $1 AND 1=1) LIMIT $2 OFFSET $3
prisma:query SELECT "public"."User"."id", "public"."User"."teamId" FROM "public"."User" WHERE (("public"."User"."archivedAt" IS NULL AND "public"."User"."deletedAt" IS NULL) AND "public"."User"."teamId" IN ($1)) OFFSET $2
prisma:query SELECT "public"."User"."id", "public"."User"."teamId" FROM "public"."User" WHERE (("public"."User"."archivedAt" IS NULL AND "public"."User"."deletedAt" IS NULL) AND "public"."User"."teamId" IN ($1)) OFFSET $2
prisma:query SELECT "public"."Team"."id" FROM "public"."Team" WHERE ("public"."Team"."id" = $1 AND 1=1) LIMIT $2 OFFSET $3
prisma:query SELECT "public"."Team"."id" FROM "public"."Team" WHERE ("public"."Team"."id" = $1 AND 1=1) LIMIT $2 OFFSET $3
prisma:query SELECT "public"."Team"."id" FROM "public"."Team" WHERE ("public"."Team"."id" = $1 AND 1=1) LIMIT $2 OFFSET $3
prisma:query SELECT "public"."Team"."id" FROM "public"."Team" WHERE ("public"."Team"."id" = $1 AND 1=1) LIMIT $2 OFFSET $3
prisma:query SELECT "public"."User"."id", "public"."User"."teamId" FROM "public"."User" WHERE (("public"."User"."archivedAt" IS NULL AND "public"."User"."deletedAt" IS NULL) AND "public"."User"."teamId" IN ($1)) OFFSET $2
prisma:query SELECT "public"."User"."id", "public"."User"."teamId" FROM "public"."User" WHERE (("public"."User"."archivedAt" IS NULL AND "public"."User"."deletedAt" IS NULL) AND "public"."User"."teamId" IN ($1)) OFFSET $2
prisma:query SELECT "public"."User"."id", "public"."User"."teamId" FROM "public"."User" WHERE (("public"."User"."archivedAt" IS NULL AND "public"."User"."deletedAt" IS NULL) AND "public"."User"."teamId" IN ($1)) OFFSET $2
prisma:query SELECT "public"."User"."id", "public"."User"."teamId" FROM "public"."User" WHERE (("public"."User"."archivedAt" IS NULL AND "public"."User"."deletedAt" IS NULL) AND "public"."User"."teamId" IN ($1)) OFFSET $2
prisma:query SELECT "public"."Team"."id" FROM "public"."Team" WHERE ("public"."Team"."id" = $1 AND 1=1) LIMIT $2 OFFSET $3
prisma:query SELECT "public"."Team"."id" FROM "public"."Team" WHERE ("public"."Team"."id" = $1 AND 1=1) LIMIT $2 OFFSET $3
prisma:query SELECT "public"."Team"."id" FROM "public"."Team" WHERE ("public"."Team"."id" = $1 AND 1=1) LIMIT $2 OFFSET $3
prisma:query SELECT "public"."Team"."id" FROM "public"."Team" WHERE ("public"."Team"."id" = $1 AND 1=1) LIMIT $2 OFFSET $3
prisma:query SELECT "public"."Team"."id" FROM "public"."Team" WHERE ("public"."Team"."id" = $1 AND 1=1) LIMIT $2 OFFSET $3
prisma:query SELECT "public"."User"."id", "public"."User"."teamId" FROM "public"."User" WHERE (("public"."User"."archivedAt" IS NULL AND "public"."User"."deletedAt" IS NULL) AND "public"."User"."teamId" IN ($1)) OFFSET $2
prisma:query SELECT "public"."User"."id", "public"."User"."teamId" FROM "public"."User" WHERE (("public"."User"."archivedAt" IS NULL AND "public"."User"."deletedAt" IS NULL) AND "public"."User"."teamId" IN ($1)) OFFSET $2
prisma:query SELECT "public"."User"."id", "public"."User"."teamId" FROM "public"."User" WHERE (("public"."User"."archivedAt" IS NULL AND "public"."User"."deletedAt" IS NULL) AND "public"."User"."teamId" IN ($1)) OFFSET $2
prisma:query SELECT "public"."User"."id", "public"."User"."teamId" FROM "public"."User" WHERE (("public"."User"."archivedAt" IS NULL AND "public"."User"."deletedAt" IS NULL) AND "public"."User"."teamId" IN ($1)) OFFSET $2
prisma:query SELECT "public"."User"."id", "public"."User"."teamId" FROM "public"."User" WHERE (("public"."User"."archivedAt" IS NULL AND "public"."User"."deletedAt" IS NULL) AND "public"."User"."teamId" IN ($1)) OFFSET $2
prisma:query SELECT "public"."Team"."id" FROM "public"."Team" WHERE ("public"."Team"."id" = $1 AND 1=1) LIMIT $2 OFFSET $3
prisma:query SELECT "public"."Team"."id" FROM "public"."Team" WHERE ("public"."Team"."id" = $1 AND 1=1) LIMIT $2 OFFSET $3
prisma:query SELECT "public"."Team"."id" FROM "public"."Team" WHERE ("public"."Team"."id" = $1 AND 1=1) LIMIT $2 OFFSET $3
prisma:query SELECT "public"."Team"."id" FROM "public"."Team" WHERE ("public"."Team"."id" = $1 AND 1=1) LIMIT $2 OFFSET $3
prisma:query SELECT "public"."Team"."id" FROM "public"."Team" WHERE ("public"."Team"."id" = $1 AND 1=1) LIMIT $2 OFFSET $3
prisma:query SELECT "public"."User"."id", "public"."User"."teamId" FROM "public"."User" WHERE (("public"."User"."archivedAt" IS NULL AND "public"."User"."deletedAt" IS NULL) AND "public"."User"."teamId" IN ($1)) OFFSET $2
prisma:query SELECT "public"."User"."id", "public"."User"."teamId" FROM "public"."User" WHERE (("public"."User"."archivedAt" IS NULL AND "public"."User"."deletedAt" IS NULL) AND "public"."User"."teamId" IN ($1)) OFFSET $2
prisma:query SELECT "public"."User"."id", "public"."User"."teamId" FROM "public"."User" WHERE (("public"."User"."archivedAt" IS NULL AND "public"."User"."deletedAt" IS NULL) AND "public"."User"."teamId" IN ($1)) OFFSET $2
prisma:query SELECT "public"."User"."id", "public"."User"."teamId" FROM "public"."User" WHERE (("public"."User"."archivedAt" IS NULL AND "public"."User"."deletedAt" IS NULL) AND "public"."User"."teamId" IN ($1)) OFFSET $2
prisma:query SELECT "public"."User"."id", "public"."User"."teamId" FROM "public"."User" WHERE (("public"."User"."archivedAt" IS NULL AND "public"."User"."deletedAt" IS NULL) AND "public"."User"."teamId" IN ($1)) OFFSET $2
prisma:query SELECT "public"."Team"."id" FROM "public"."Team" WHERE ("public"."Team"."id" = $1 AND 1=1) LIMIT $2 OFFSET $3
prisma:query SELECT "public"."User"."id", "public"."User"."teamId" FROM "public"."User" WHERE (("public"."User"."archivedAt" IS NULL AND "public"."User"."deletedAt" IS NULL) AND "public"."User"."teamId" IN ($1)) OFFSET $2
prisma:query SELECT "public"."Team"."id" FROM "public"."Team" WHERE ("public"."Team"."id" = $1 AND 1=1) LIMIT $2 OFFSET $3
prisma:query SELECT "public"."Team"."id" FROM "public"."Team" WHERE ("public"."Team"."id" = $1 AND 1=1) LIMIT $2 OFFSET $3
prisma:query SELECT "public"."User"."id", "public"."User"."teamId" FROM "public"."User" WHERE (("public"."User"."archivedAt" IS NULL AND "public"."User"."deletedAt" IS NULL) AND "public"."User"."teamId" IN ($1)) OFFSET $2
```

_Originally posted by @JClackett in https://github.com/prisma/prisma/issues/5079#issuecomment-1348670008_

**Comment by janpio** [comment] 2023-01-11 10:57
Hey @JClackett, that looks bad. Can you maybe provide the schema you were using so we have an easier time to reproduce? Thanks.

**Comment by JClackett** [comment] 2023-01-11 12:44
Hey @janpio yeah super strange, its also literally just a one-to-many relation:

```prisma
model User {
  ... stuff
  team                    Team?              @relation(fields: [teamId], references: [id])
  teamId                  String?            @db.Uuid
}

model Team {
  ... stuff
  users                   User[]
}

```

There is a lot of other fields in each model, relating to other columns and other relations, not sure if that would be relevant, I assume not? let me know if you need them (there's quite a lot)

Also realised that I have some prisma.$use calls that are essentially adding some default fields to a where clause, wonder if thats affecting things?

```ts
import type { Prisma } from "@prisma/client"

export function useSoftDelete(params: Prisma.MiddlewareParams) {
  if (params.action === "delete") {
    // Delete queries
    // Change action to an update
    params.action = "update"
    params.args["data"] = { deletedAt: new Date() }
  }
  if (params.action === "deleteMany") {
    // Delete many queries
    params.action = "updateMany"
    if (params.args.data !== undefined) {
      params.args.data["deletedAt"] = new Date()
    } else {
      params.args["data"] = { deletedAt: new Date() }
    }
  }
  if (params.action === "updateMany") {
    if (params.args.where !== undefined) {
      params.args.where["deletedAt"] = { equals: null }
    } else {
      params.args["where"] = { deletedAt: { equals: null } }
    }
  }
  // THIS BREAK N + 1 currently
  // if (params.action === "findUnique" || params.action === "findFirst") {
  //   // Change to findFirst - you cannot filter
  //   // by anything except ID / unique with findUnique

  //   params.action = "findFirst"
  //   // Add 'deletedAt' filter
  //   // ID filter maintained
  //   params.args.where["deletedAt"] = { equals: null }
  // }
  if (params.action === "findMany") {
    // Find many queries
    if (params.args.where !== undefined) {
      if (params.args.where.deletedAt === undefined) {
        // Exclude deletedAt records if they have not been explicitly requested
        params.args.where["deletedAt"] = { equals: null }
      }
    } else {
      params.args["where"] = { deletedAt: { equals: null } }
    }
  }
  return params
}

```

**Comment by aqrln** [comment] 2023-08-21 20:21
I couldn't reproduce this with with the given query and middleware, neither with latest Prisma nor with a bunch of older versions. Do you remember by chance which version of Prisma were you using back then? Was this issue resolved or can you still reproduce it?

**Comment by janpio** [comment] 2023-10-29 21:14
Hey @JClackett, did you see Alexey's response? We would love to reproduce this, but are missing information on how. Thanks.

**Comment by SevInf** [comment] 2024-02-02 10:30
Hey @JClackett ,
 

With the lack of information and our inability to reproduce this issue, we're now closing it. Feel free to comment if you have any updates about it.
 
Thank you 🙏

**Closed by SevInf** 2024-02-02 10:30 UTC
Labels: bug/1-unconfirmed, kind/bug, topic: relations, team/client, topic: _count, topic: performance/queries, topic: findMany()
