### ISSUE TITLE
Prisma Migrate just crashed. 

### ISSUE THREAD

**Issue by seiji0411** [prisma/prisma#13415] opened 2022-05-19 06:54 UTC
Hi Prisma Team! Prisma Migrate just crashed. 

## Command

`db push`

## Versions
      
| Name        | Version            |
|-------------|--------------------|
| Platform    | darwin             | 
| Node        | v16.14.2           | 
| Prisma CLI  | 3.14.0             | 
| Engine      | 2b0c12756921c891fec4f68d9444e18c7d5d4a6a| 

## Error
```
Error: Error in migration engine.
Reason: [libs/sql-schema-describer/src/postgres.rs:1039:28] no entry found for key

Please create an issue with your `schema.prisma` at
https://github.com/prisma/prisma/issues/new

```

**Comment by meotimdihia** [comment] 2022-05-25 17:00
duplicated with the issue:
https://github.com/prisma/prisma/issues/13352
it looks like a lot of people got this bug.

**Comment by pantharshit00** [comment] 2022-05-27 10:32
I would close this as a duplicate of #13352 like @meotimdihia mentioned

**Closed by pantharshit00** 2022-05-27 10:32 UTC
Labels: bug/0-unknown, kind/bug, team/schema, topic: prisma db push, topic: basic error report
