### ISSUE TITLE
Prisma Generate issue in Ubundu windows sub system

### ISSUE THREAD

**Issue by ranjith-sterna** [prisma/prisma#21680] opened 2023-10-30 10:57 UTC
Hi Prisma Team! The following command just crashed.

## Command

`generate`

## Versions
      
| Name        | Version            |
|-------------|--------------------|
| Platform    | debian-openssl-1.1.x| 
| Node        | v18.15.0           | 
| Prisma CLI  | 5.4.1              | 
| Engine      | 2f302df92bd8945e20ad4595a73def5b96afa54f| 

## Error
```
RustPanic: RuntimeError: panicked at 'index out of bounds: the len is 0 but the index is 0', psl/parser-database/src/walkers/relation_field.rs:30:56
```

**Comment by miguelff** [comment] 2023-10-30 11:45
Could you please provide us with some reproduction? to the least, the `prisma.schema` file that you are using?

**Comment by millsp** [comment] 2023-11-07 02:16
@ranjith-sterna did you see the message from @miguelff? Without additional information to be able to reproduce, we would later close this issue as part of our issue process.

**Comment by ranjith-sterna** [comment] 2023-11-10 04:31
Hi,

I am using below prisma file module.

generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "sqlserver"
  url      = env("DATABASE_URL")
}

model AssetType {
  id        Int       @id @default(autoincrement())
  name      String    @unique
  isLock    Boolean   @default(true)
  createdAt DateTime  @default(now())
  updatedAt DateTime  @updatedAt
  deletedAt DateTime?
  assets    Asset[]
}

model Asset {
  id                  Int                  @id @default(autoincrement())
  name                String?
  marking             String?
  uuid                String               @unique
  secondaryMarking    String?
  assetTypeId         Int
  createdAt           DateTime             @default(now())
  updatedAt           DateTime             @updatedAt
  deletedAt           DateTime?
}

Application developed in Bunster JS
The application is developed in the Ubuntu Windows subsystem.

Please let know if any details required to fix this issue

**Comment by jkomyno** [comment] 2024-03-04 08:21
Hey @ranjith-sterna, `prisma generate` didn't succeed in your case because the provided schema is invalid, as you can check with `prisma validate`:

```
❯ pnpm prisma validate
Environment variables loaded from .env
Prisma schema loaded from prisma/schema.prisma

Error: Prisma schema validation - (validate wasm)
Error code: P1012
error: Error validating field `assets` in model `AssetType`: The relation field `assets` on model `AssetType` is missing an opposite relation field on the model `Asset`. Either run `prisma format` or add it manually.
  -->  schema.prisma:17
   | 
16 |   deletedAt DateTime?
17 |   assets    Asset[]
18 | }
   | 

Validation Error Count: 1
[Context: validate]

Prisma CLI Version : 5.4.1
```

If you're using our [Prisma extension for VSCode](https://marketplace.visualstudio.com/items?itemName=Prisma.prisma), you may have noticed this message while the `schema.prisma` file is open:

![Image](https://github.com/prisma/prisma/assets/12381818/72e82fbc-59b6-49b5-9bd5-b2ff1dc8dfdb)

Running `prisma format` indeed fixes the schema, and enables `prisma generate` to create the Prisma Client without issues.
I'll be closing the issue as solved now, but please leave a comment in case you disagree / have further issues related to this one. Thanks!

**Closed by jkomyno** 2024-03-04 08:21 UTC
Labels: bug/1-unconfirmed, kind/bug, topic: prisma generate, team/client, topic: rust panic, topic: bun
