### ISSUE TITLE
Timed out fetching a new connection from the pool

### ISSUE THREAD

**Issue by Giarry156** [prisma/prisma#20019] opened 2023-06-30 12:30 UTC
### Bug description

I'm creating a multitenant system managed by this function:

```
import { PrismaClient as TenantPrismaClient } from "C:/Users/GianroccoNicassio/Documents/dev/atoms-api/prisma/tenant/generated/atoms_tenant/index.js";

/**
 * This class defines methods for tenant database connection creation.
 *
 * @class TenantDatabase
 */
class TenantDatabase {
  // Declaring properties.
  public prisma: TenantPrismaClient<any> | undefined;

  // Declaring methods.
  constructor(tenant: any) {
    this._setTenant(tenant);
  }

  /**
   * This method creates a new database connection on database requested.
   *
   * @method _setTenant
   * @param tenant any
   */
  private async _setTenant(tenant: any) {
    // Create a new connection and set it like connection instance.
    this._setPrismaClient(
      new TenantPrismaClient({
        datasources: {
          db: {
            url: process.env.CUSTOM_DATABASE_URL + tenant.db_name + ";",
          },
        },
      })
    );
  }

  /**
   * This method is a setter for prisma client property of the instance.
   *
   * @method _setPrismaClient
   * @param prismaClient object - TenantPrismaClient
   */
  private _setPrismaClient(prismaClient: TenantPrismaClient) {
    this.prisma = prismaClient;
  }
}

// Interface to standardize a connection.
interface PrismaConnectionDictonary {
  [key: string]: TenantDatabase;
}

/**
 * This class defines tenants' database connections gesture methods.
 * This is an artifice to define a "smart" connection pool that doesn't permit to instantiate more than one db connection for tenant.
 * @class TenantConnection
 */
class TenantConnection {
  // Declaring properties.
  private _connection_pool: PrismaConnectionDictonary;

  // Declaring constructor.
  constructor() {
    this._connection_pool = {};
  }

  /**
   * This method is used to retrieve requested tenant prisma client.
   *
   * @method getPrismaClient
   * @param tenant any
   */
  public getPrismaClient(tenant: any) {
    try {
      // Connection pool already has a connection for the tenant requested?
      if (this._connection_pool[tenant.code]) {
        // Returning the existing connection.
        return this._connection_pool[tenant.code].prisma;
      } else {
        // Creating a new connection and updates the pool.
        let connection = new TenantDatabase(tenant);

        this._updateConnectionPool({ [tenant.code]: connection });

        return connection.prisma;
      }
    } catch (error) {
      throw error;
    }
  }

  /**
   * This method updates connection pool with existing instance of connection established.
   *
   * @method _updateConnectionPool
   * @param connection object - PrismaConnection
   */
  private _updateConnectionPool(connection: { [key: string]: TenantDatabase }) {
    try {
      Object.assign(this._connection_pool, connection);
    } catch (error) {
      throw error;
    }
  }
}

// Declaring db connections gesture instance as loader.
let database = new TenantConnection();

// Exporting loader.
export default database;
```

I have a .prisma schema with the structure of all tenants and the url value of the datasource db has the shadow tenant database url. Every time that an HTTP request is sent to the server, it has an X-Tenant header inside the headers to search the tenant requested and use it to create a PrismaClient and insert it inside the dictionary connection_pool, or recycle it if it was already created and inserted in the dictionary.

The problem is random and 1/2 times every 3 days this error income:

![image](https://github.com/prisma/prisma/assets/96413547/9fa2f46e-a790-4e38-9202-f899d372f6fc)

Ignore connection limit: 1, the same error incomed with 5 and 100 connections.

What can I do for this?

Note:
@garrensmith https://github.com/prisma/prisma/issues/7249
I saw that you closed this issue that it's pretty similar to my issue. Did you find the solution for this?

### How to reproduce

Actually there is no way to reproduce it, there is this function and 1/2 times every 3 day this bug happens.

### Expected behavior

It must work as always. It must take the tenant object, extract the db_name and use it with the URL combo and connect to that. It works always, except in these cases.

### Prisma information

There are no schema problems.

The bug incomes everytime in the first query done to the tenant database selected. As you can see from the image, the query is on contact.findUnique(), nothing special.

### Environment & setup

- OS: Windows
- Database: SQL Server
- Node.js version: v19.7.0

### Prisma Version

```
Environment variables loaded from .env
prisma                  : 4.11.0
@prisma/client          : 4.16.1
Current platform        : windows
Query Engine (Node-API) : libquery-engine 8fde8fef4033376662cad983758335009d522acb (at ..\..\..\..\AppData\Roaming\npm\node_modules\prisma\node_modules\@prisma\engines\query_engine-windows.dll.node)
Migration Engine        : migration-engine-cli 8fde8fef4033376662cad983758335009d522acb (at ..\..\..\..\AppData\Roaming\npm\node_modules\prisma\node_modules\@prisma\engines\migration-engine-windows.exe)
Format Wasm             : @prisma/prisma-fmt-wasm 4.11.0-57.8fde8fef4033376662cad983758335009d522acb
Default Engines Hash    : 8fde8fef4033376662cad983758335009d522acb
Studio                  : 0.483.0
```

**Comment by Jolg42** [comment] 2023-06-30 15:23
Which database are you using here?

Unrelated note: I noticed that your Prisma CLI version is not in sync (`4.11.0`) with the Prisma Client, we recommend keeping these in sync.

**Comment by Giarry156** [comment] 2023-06-30 15:37
> Which database are you using here?
> 
> Unrelated note: I noticed that your Prisma CLI version is not in sync (`4.11.0`) with the Prisma Client, we recommend keeping these in sync.

Sorry, I forgot that note block. Anyway, I updated the info.

**Comment by andreasvh-conceto** [comment] 2023-07-01 07:55
Hello @Giarry156 
we have a similar approach and use multiple prisma clients in our company in similar dictionary. 

Let's think about it:
- this error needs some time to happen
- you are able to add tenants at runtime
-  you have a default connection limit if not explicitly set, which depends on your cpu cores, see: [documentation](https://www.prisma.io/docs/guides/performance-and-optimization/connection-management#recommended-connection-pool-size) 
- your database has a fixed size of connections it allows ( especially in cloud environments)

A connection pool timeout happens if the prisma client is not able to receive a connection from the connection pool in time (connection timeout). According to this what  are possible issues, or what would i check:

- check how many tenants and prisma instances you want to create. I create them initially once on startup 
- the connection limit: set it manually like recomemded in the doc link. Assuming you have 4 cores, where your prisma app is running, each prisma Client will per default use connection limit of (2 threads × 4 cores +1) = 9.  Assuming you have 2 tenants, you are already requesting for each prisma Client 2×9=18 connections  in worst case if you do not set the connection limit manually. Prisma would recommend to give one tenant1 prisma dbclient a connection_limit of 5 and for tenant2  a limit of 4 if i understand it correcrly.  So that you do not exceed the 9. You share them between the clients. If you don't set it manually, maybe the other threads are already maintaing other connections in their pool. So other prisma connections pools can not be filled with enough connections to handle your queries
- Your database server must be able to fit this max number of additional 9 client connections (also  user connections or other applications can access your database and needs connections - so dont forget them)
- according to this knowledge i would not allow to add tenants at runtime. Or you reinstantiate prisma clients with an adjusted limit if one dbclient is added. You as the developer should be in control which tenants are created with which connection limits. Assume via frontend admin users are adding prisma clients and they create 10 tenants and you are not in control. That is why I set them up on startup (via environment variable holding a json array of several database connection urls including the connection limit) and then they are not touched again.
- Verify if there are long lasting queries running in the background. Querys block the connection and let them free into the pool if they finish. If you have multiple long lasting queries running at the same time, this can cause issues, then you are forced to improve your query performance
- If you are in the production environment I also recommend pgboucer for managing and removing dead connections, but don't forget the `pgbouncer=true` in the url

Here also some useful link related to the pool size: 
https://www.prisma.io/docs/guides/performance-and-optimization/connection-management#recommended-connection-pool-size

I hope this helps to figure out the issue. If you got the issue, i would be interested in the solution :)

Best regards 
Andreas

**Comment by Durisvk** [comment] 2023-07-04 08:49
We're not using multitenancy but we're running on Google Cloud Run which can scale up. We're also using pgBouncer with `pgbouncer=true` option enabled in `DATABASE_URL`. I'm still figuring out why is this happening and we've recently set up a monitoring of prisma connection pool which proves the point that there's something rotten.

Here's our Prisma code setup:

```ts
import { Prisma as P, PrismaClient } from '@prisma/client';
import { Service } from 'typedi';

class PrismaInternal extends PrismaClient {
  constructor() {
    let config: P.PrismaClientOptions = {};

    super(config);

    this.$connect().catch(e => {
      throw e;
    });
  }

  async $connect() {
    try {
      return await super.$connect();
    } catch (error) {
      console.error(
        `Failed to establish a connection with the database at ${process.env.DATABASE_URL}. Terminating a process...`
      );
      console.error(error);
      process.exit(1);
    }
  }
}

const prismaGlobal = new PrismaInternal();

// to make double sure we only use a single instance of Prisma
// to avoid connection pool issues: https://www.prisma.io/docs/guides/performance-and-optimization/connection-management#prevent-hot-reloading-from-creating-new-instances-of-prismaclient
@Service({ global: true, factory: () => prismaGlobal })
export class Prisma extends PrismaInternal {}
```

And here's how we monitor the prisma every 5 minutes:

```ts
  async sendMetrics(serviceName: string) {
    const project_id = await this.getGcpProjectId();
    const metrics = await this.prisma.$metrics.json();

    const metricsToReport = METRICS_TO_REPORT.flatMap(metricName => {
      return metrics.gauges.find(({ key }) => key === metricName);
    });

    const data = metricsToReport.filter(Boolean).map(
      metric =>
        ({
          metricKind: 'GAUGE',
          unit: 'connections',
          metric: {
            type: METRIC_TYPE,
            labels: {
              metric: metric?.key,
            },
          },
          resource: {
            type: 'generic_node',
            labels: {
              project_id,
              location: 'us-central1',
              namespace: serviceName,
              node_id: `${process.env.K_REVISION || 'local'}:${
                process.env.K_INSTANCE || 'local'
              }`,
            },
          },
          valueType: 'INT64',
          points: [
            {
              interval: {
                endTime: {
                  seconds: Date.now() / 1000,
                },
              },
              value: {
                int64Value: metric?.value,
              },
            },
          ],
        } as google.monitoring.v3.ITimeSeries)
    );
```

And this is the graph we see of Prisma open connections over time:
<img width="1226" alt="image" src="https://github.com/prisma/prisma/assets/8467003/b93f30a5-ebe7-4507-8426-f005e6157334">


We didn't set a connection limit in our DATABASE_URL and it appears from the chart that Prisma goes wild on allocating new connections.

**Comment by imwexpex** [comment] 2023-07-04 15:23
@Durisvk Facing the same issue with metrics.

![image](https://github.com/prisma/prisma/assets/25363536/2c2ef84a-8f17-47a6-8e16-a1983109be9d)

**Comment by janpio** [comment] 2023-07-05 22:00
@Durisvk @imwexpex Please create new issues for your problems. Although they are also about connections, they do not seem to be caused by the same root problem as what @Giarry156 reported - and hence we can not debug them in the same issue. Make sure to fill the full issue template, so we have all the information we usually need. Thank you.

**Comment by janpio** [comment] 2024-05-23 20:17
I think @andreasvh-conceto gave a great response here, that I hoped helped @Giarry156 to figure this out. Closing for now.

**Closed by janpio** 2024-05-23 20:17 UTC
Labels: bug/1-unconfirmed, kind/bug, topic: prisma-client, topic: sql server, team/client, topic: connection pool, topic: multi-tenant
