### ISSUE TITLE
`take` key doesn't work correctly for nested query that returns one item with its nested children

### ISSUE THREAD

**Issue by getayush96** [prisma/prisma#15623] opened 2022-09-30 13:31 UTC
### Bug description

If we have a nested query, and we have `take` key present in the query. It doesn't generate the correct raw query. The `limit` key isn't there when the query is converted into the raw query by prisma. This results in huge latencies for querying data. 

### How to reproduce

sync db with the given schema and run the given query. 

We will have two tables created. one for `Person` and another for `Cars`. a `Person` can have many `Cars` by definition.  When the given query ( to get a person and include the cars ) , prisma generates the following queries :

q1 )`SELECT "public"."Person"."id", "public"."Person"."name" FROM "public"."Person" WHERE "public"."Person"."id" = $1 LIMIT $2 OFFSET $3 [1,1,0]`

q2) `SELECT "public"."Cars"."id", "public"."Cars"."ownerId" FROM "public"."Cars" WHERE "public"."Cars"."ownerId" IN ($1) ORDER BY "public"."Cars"."id" ASC OFFSET $2 [1,0]`

If we look at the second query we can see the `limit` keyword is not applied over here. Whereas this is specified in the prima query written in the code. Whats happening is that `prisma is fetching all the cars for this person and handling the limit in the code` . This creates huge latencies if we want to fetch only one car ( by specifying limit as 1 ) and the person has lots of cars, as prisma will fetch all the cars from the DB and return us one car for the person.

### Expected behavior

Ideally, prisma should add the `limit` key to the query such that we retrieve only the desired results.

### Prisma information

```prisma

model Person {
  id              Int                 @id @default(autoincrement())
  name          String
  Cars Cars[]
}

model Cars {
  id      Int             @id @default(autoincrement())
  owner     Person @relation(references: [id], fields: [ownerId], onDelete: Cascade)
  ownerId   Int

}

```

```ts
await this.prisma.person.findFirst({
                where:{
                    id:1
                },
                include:{
                    Cars:{
                        take:1
                    }
                }
            })
```

### Environment & setup

- OS:  Macos
- Database: Postgres
- Node.js version: 14.18.0

### Prisma Version

```
3.12 and 4.4
```

**Comment by getayush96** [comment] 2023-03-13 09:58
@millsp Is there any update on this ?

**Comment by millsp** [comment] 2023-03-20 17:29
This does not currently fit our planned projects for this quarter, but seems important enough for us to try to squeeze it into our planning, but that would also depend on how much engineering effort this would take. I will try to help this happen, and will keep you updated.

**Comment by livthomas** [comment] 2023-04-19 08:42
We were wondering for a while why our application has become so slow when we have all indexes in place until we found that some queries miss `LIMIT` and then we found this issue.

We're syncing the data in the background and storing `Sync` records in the DB. Each time the data is synced, all new records are linked to a new `Sync` record. When we show the data in our web UI, we get it from DB by the latest successful sync and so we often use a nested query with `take: 1`. But instead of loading a single record from database, this Prisma bug causes it to load all sync records (around 15000 at the moment) every time any data is retrieved from the database.

**Comment by venables** [comment] 2023-05-19 11:30
Hitting the same issue as well. Might I suggest including a note in the documentation to mention this unexpected behavior, if it can't be fixed in the current cycle?

**Comment by clathrop** [comment] 2023-06-28 22:19
Hey there, any update on this? We are running into the same problem.

**Comment by tom2o17** [comment] 2023-06-28 22:19
bump ^

**Comment by livthomas** [comment] 2023-06-29 07:06
> Hey there, any update on this? We are running into the same problem. @livthomas did you ever find a workable solution?

We simply had to rewrite all our queries that were affected by this. We usually split them into two queries. The first one uses `findFirst` method and then we use the results of this query in the `where` clause of the second one.

We even introduced an ESLint rule in our project that detects `take: 1` in our codebase so we won't add inefficient queries in the future.

**Comment by millsp** [comment] 2023-07-05 00:58
No update yet, sorry. We are looking into query performance though, but other things in that spectrum are having a higher priority at the moment. We will post you updates when we made progress on this.

**Comment by kirillrogovoy** [comment] 2023-07-26 15:01
Just wanted to chime in and say that I killed three full days of work hunting what I thought to be a memory leak.

In reality, I had an `orderBy` + `take: 1` on a nested query on a table with 100k+ records. Because the raw query didn't have `LIMIT`, it would download all those records into RAM and eventually crash the process before the GC gets to free that memory.

No shame on Prisma, because I love it and it's free and open-source. Huge respect to the team and thanks for working on it!

Just wanted to give an example of an impact this bug has. It degraded the end-customer experience of a real business for more than a week.

The worst thing is that it mostly populated RSS, not the Heap. So analyzing heap dumps was mostly useless.

**Comment by janpio** [comment] 2023-07-26 17:21
@kirillrogovoy @livthomas @tom2o17 @clathrop @venables 
Are you all using `findFirst` or another method that by default returns only one result (which then includes the `take` results from the relation)?

**Comment by livthomas** [comment] 2023-07-27 06:54
@janpio This issue is about nested queries with `take: 1` where `LIMIT` is not being added to the actual SQL query.

An example of one of our queries affected by this bug:
```ts
    await prisma.zone.findMany({
      select: {
        syncs: {
          select: {
            id: true,
          },
          orderBy: {id: 'desc'},
          take: 1,
          where: {
            status: SyncStatus.FINISHED,
          },
        },
      }
    });
```
We use nested selects with `take: 1` with other methods (`findUnique`, `findFirst`, or `groupBy`) but I'm not sure if all of them cause this issue. We decided to rewrite all the queries immediately when we discovered this bug.

**Comment by kirillrogovoy** [comment] 2023-07-27 07:13
I can confirm that it doesn't matter if you use findUnique, findFirst, findMany, etc. as long as you have `take` in a nested query just like @livthomas pointed out.

The top-level `take` always works as expected (adds `LIMIT`) but nested `take` never adds `LIMIT`

**Comment by janpio** [comment] 2023-07-28 08:19
Ok, thanks.

The problem indeed applies to all Prisma Client queries - but the original issue description here was specifically about `findFirst`. Now that we looked into this, we identified that the solution for queries that only return 1 result with its nested data is much simpler to implement than for all the other ones (the SQL query is much easier, just adding a `LIMIT` does not actually work for multiple items).

Hence I suggest we treat this issue here now for the one representing the problem with `findFirst`, `findUnique` and `findUniqueOrThrow` and use https://github.com/prisma/prisma/issues/16168 for `findMany` and other queries that return multiple items. We'll resolve and close this one here first, and then move on to the other one separately.

Does that make sense?

**Comment by kirillrogovoy** [comment] 2023-07-28 12:36
Sounds good to me, but I'll avoid any use of nested `take` until both are fixed. 

Thanks!

**Comment by clathrop** [comment] 2023-07-28 21:13
@janpio Sorry we can't be of much help here, we actually moved this specific query to a different api which uses sqlalchemy and had no issues there. Unfortunate that prisma couldn't handle this use case right now but didn't end up being a major blocker for us.

If we didn't have the option we would have either gone with the same approach @livthomas mentioned or just had done it raw.

**Closed** 2023-08-08 12:16 UTC
Labels: bug/2-confirmed, kind/bug, tech/engines, topic: findFirst, team/client, topic: performance/queries, topic: take, topic: nested read

**Comment by kolserdav** [comment] 2024-09-19 04:45
This slows down the child table fetch a lot, instead of fetching just one record, if we pass `take: 1` it fetches all 100500, this query takes 1.5 seconds and then Prisma filters them and returns the result in 3-4 seconds. Wouldn't it be better if when passing `take` Prisma added `LIMIT` to its query so that it not only works as expected but also works well in terms of speed.
