### ISSUE TITLE
Could not connect to websocket endpoint

### ISSUE THREAD

**Issue by Alosies** [prisma/prisma#3787] opened 2018-12-31 12:48 UTC
**Describe the bug**
When I try a subscription in the playground, i get the following

`{
  "error": "Could not connect to websocket endpoint wss://my-heroku-instance.herokuapp.com/server-prisma-heroku/dev. Please check if the endpoint url is correct."
}`

My queries and mutations are working fine at the same endpoint.
What could be the issue for subscriptions?

**Versions (please complete the following information):**
 - OS:  `OS X High Sierra`
 - `prisma` CLI:  `prisma@1.23.2  node-v10.12.0`

**Additional context**
My instance is deployed in heroku using the installer options from prisma website.

**Comment by morpherious** [comment] 2019-02-19 12:42
Any update on this issue?

**Comment by pantharshit00** [comment] 2019-02-20 07:35
@morpherious Currently heroku doesnt seem to allow websockets on . container deploy. You will require to host your prisma server somewhere else.

**Comment by pantharshit00** [comment] 2019-04-04 15:01
Closing this as it is not related to prisma. It is related to Heroku and we really can't do a fix there ;)

**Closed by pantharshit00** 2019-04-04 15:01 UTC
Labels: area/deploy, bug/2-confirmed

**Comment by AWebOfBrown** [comment] 2019-04-17 00:58
So I'd like to take a stab at clarifying the issue, because I imagine there are a lot of people who've been guided by Prisma Cloud to deploy on Heroku and then hit this dead end buried in GitHub issues. Some messaging about this limitation is really important.  

As far as I understand, the issue is that Heroku's container runtime only [allows traffic over HTTP ](https://devcenter.heroku.com/articles/container-registry-and-runtime#dockerfile-commands-and-runtime) and thus not the web-socket protocol. When you deploy to Heroku, you specify a ${PORT} number that (I assume*) is mapped on the container side to port 80 for incoming HTTP traffic .  
*My knowledge of docker / containers isn't amazing. 

This means that the only way this limitation will be unblocked is:
1. Heroku exposes more than HTTP traffic to containers (unlikely anytime soon).
2. Prisma stops using Docker for deployment, which I assume is highly unlikely unless it's part of the (effort to turn Prisma into a "library") [https://github.com/prisma/prisma/issues/2992]. It would be nice to get a quick affirmation from a Prisma member as to whether that actually is the case, as it does impact on deployment decisions.  

Please feel free to correct me if/where I'm wrong :).

**Comment by nugoo1** [comment] 2019-06-16 16:18
Hey I'm having the same issue here... Where Can I deploy?? Stresseddddddd

**Comment by AWebOfBrown** [comment] 2019-06-17 23:03
> Hey I'm having the same issue here... Where Can I deploy?? Stresseddddddd

@nugoo1 You can get around this if you're okay with publishing messages for your message queues from your node API server instead of relying on Prisma server's subscriptions, as they have done here [Subscription example](https://github.com/prisma/prisma-examples/tree/master/typescript/graphql-subscriptions). This relies on your mutations publishing an event each time they succeed, but it doesn't allow you to dynamically query the data, resulting from the mutation, in the subscription operation.

**Comment by nugoo1** [comment] 2019-06-18 03:21
Helloioo, Heroku doez support wss now and working beautifully! Thanks for the reply AWebofBrown, I had used ws instead of wss which was the problem,, my bad.. Need wss if u have https
