### ISSUE TITLE
`migrate dev --create-only` doesn't work in the first time on an existing database

### ISSUE THREAD

**Issue by xiangnanscu** [prisma/prisma#12272] opened 2022-03-11 16:47 UTC
### Bug description

I want to try prisma as a migrate tool in an existing non-prisma project. so I've run `prisma db pull` on an existing database and got the `schema.prisma` file, then I want to make the first migrations without applying changes:
```
npx prisma migrate dev --create-only
```
the docs says 
```
The --create-only command allows you to create a migration without applying it
```
 but when I do so, it says 
```
Drift detected: Your database schema is not in sync with your migration history.
```
and 
```
✔ We need to reset the PostgreSQL database "xxx" at "localhost:5432".
Do you want to continue? All data will be lost. … no
```

### How to reproduce

just as description

### Expected behavior

prisma should just make a `migrations` folder and make the first migrate `.sql` file containing all the `create table` stuff, and should not force me to reset my database

### Environment & setup

- OS: 
- Database: 
- Node.js version: 

### Prisma Version

```
prisma                  : 3.10.0
@prisma/client          : 3.10.0
Current platform        : debian-openssl-1.1.x
Query Engine (Node-API) : libquery-engine 73e60b76d394f8d37d8ebd1f8918c79029f0db86 (at node_modules/prisma/node_modules/@prisma/engines/libquery_engine-debian-openssl-1.1.x.so.node)
Migration Engine        : migration-engine-cli 73e60b76d394f8d37d8ebd1f8918c79029f0db86 (at node_modules/prisma/node_modules/@prisma/engines/migration-engine-debian-openssl-1.1.x)
Introspection Engine    : introspection-core 73e60b76d394f8d37d8ebd1f8918c79029f0db86 (at node_modules/prisma/node_modules/@prisma/engines/introspection-engine-debian-openssl-1.1.x)
Format Binary           : prisma-fmt 73e60b76d394f8d37d8ebd1f8918c79029f0db86 (at node_modules/prisma/node_modules/@prisma/engines/prisma-fmt-debian-openssl-1.1.x)
Default Engines Hash    : 73e60b76d394f8d37d8ebd1f8918c79029f0db86
Studio                  : 0.458.0
```

**Comment by xiangnanscu** [comment] 2022-03-11 16:52
Note, I don't make any database changes during `prisma db pull` and `npx prisma migrate dev --create-only`, so prisma should just make migration sql file, so let the migration file sync with database, not let database sync with migrations!

**Comment by kb-ig** [comment] 2022-05-12 21:17
Can confirm this happens for me, also. If you accept `yes`, a message tells you the migration was created but not applied.
>Prisma Migrate created the following migration without applying it 20220512210023_initial_migration

And this is correct, it hasnt been applied, but all existing tables have been dropped - clean slate. The only table in my DB now is `_prisma_migrations`, which has no data in it.

I have a feeling this may be the expected behaviour, although I really hope not. It's mentioned in the [docs](https://www.prisma.io/docs/guides/database/developing-with-prisma-migrate/baselining) that:
> We assume it is acceptable to reset and seed development databases

So perhaps running the `migrate dev`, even with `--create-only`, will always reset the database. 

If so, **I really hope this is changed in the future**!

**Comment by pencilcheck** [comment] 2022-10-25 07:53
I also encountered this issue, I am not going to say yes to reset database. This is very confusing, a lot of docs are saying things that are not what the command line is doing.

**Comment by sacru2red** [comment] 2023-05-09 05:59
Same case,

So, I think first migaration must just let it be
[link](https://www.prisma.io/docs/guides/migrate/developing-with-prisma-migrate/add-prisma-migrate-to-a-project#apply-the-initial-migrations)

**Comment by miguelff** [comment] 2023-08-04 04:52
As https://github.com/prisma/prisma/issues/12272#issuecomment-1125431192 points above, this is the current expected behavior:

From [the docs on migrate `--create-only`](https://www.prisma.io/docs/reference/api-reference/command-reference#options-6)

<img width="702" alt="Screenshot 2023-08-04 at 12 46 21" src="https://github.com/prisma/prisma/assets/210307/a8554848-8d84-4b84-ba93-971c36cb53ef">

And

<img width="678" alt="Screenshot 2023-08-04 at 12 46 40" src="https://github.com/prisma/prisma/assets/210307/e2a6533b-3f11-4eb9-8fb5-4c92530ea33f">

What might be confusing and subject to an enhacement of the future, is why a schema drift is happening? 

According to the [docs](https://www.prisma.io/docs/concepts/components/prisma-migrate/shadow-database#detecting-schema-drift):


> To detect drift in development, Prisma Migrate:
> 
> * Creates a fresh copy of the shadow database (or performs a soft reset if the shadow database is cloud-hosted)
> * Reruns the current migration history in the shadow database.
> * Introspects the shadow database to generate the 'current state' of your Prisma schema.
> * Compares the end state of the current migration history to the development database.
> * Reports schema drift if the end state of the current migration history does not match the development database (for example, due to a manual change)
> 

Currently the migration history is empty, and hence after trying to apply it, the result is not that of the development database, leading to the drift.

The behavior expected by @xiangnanscu might sound sensible, but in any case, it should be subject of an enhacement and not a bug. 

> prisma should just make a migrations folder and make the first migrate .sql file containing all the create table stuff, and should not force me to reset my database

I'm opening an enhacement issue for that.

**Comment by miguelff** [comment] 2023-08-04 04:58
Closing in favor of #20551

**Closed by miguelff** 2023-08-04 04:59 UTC
Labels: bug/1-unconfirmed, kind/bug, tech/engines, team/schema, topic: drift, topic: prisma migrate dev --create-only

**Comment by yfeleke** [comment] 2023-11-13 03:28
I want to add a note that when a migration fails, there is still an entry in the `_prisma_migrations` which means that even after you resolve the error (in my case duplicate rows when trying to add an index) you will run into the request to reset the schema and drop all data. 

My way around this was to manually delete the row representing the failed migration which removes the supposed drift that requires a drastic response (drop all tables in public)
