### ISSUE TITLE
Can't Delete field from Enum

### ISSUE THREAD

**Issue by simontoya** [prisma/prisma#4698] opened 2020-10-30 13:56 UTC
## Bug description

I tried to eliminate a value from an enum, and the migration cannot be done. 

## How to reproduce

1. Create a enum in the prisma schema with some field
2. Save the migration
3. Delete one field from the enum and save the migration
4. run npx prisma migrate up --experimental

## Expected behavior

I was expecting that the field on the enum gets deleted

## Environment & setup

- OS: Mac Os
- Database: PostgreSQL 12
- Node.js version: 12.18.3
- Prisma version: 2.10.1
```
To give more information, since the migration where the field in enum was deleted did not work y took the commands the migration generated and I executed them directly in the database and an error was thrown
```
![Screen Shot 2020-10-30 at 10 47 45](https://user-images.githubusercontent.com/26397078/97712786-b1328d80-1a9d-11eb-9308-6abbb683a5a8.png)
```
After that I looked up for another solution, and this appeared in my search

DELETE FROM pg_enum
WHERE enumlabel = 'DECLINED'
AND enumtypid = (
  SELECT oid FROM pg_type WHERE typname = 'CandidateStatus'
);

```
So I executed this query in order to view the fields in the enum and executed the previous command
```
select * from pg_enum where enumtypid in (SELECT oid FROM pg_type WHERE typname = 'enum_name');
```
Afterwards the field actually got deleted, but I think it might be a problem if the a column in a table has that value

**Comment by pantharshit00** [comment] 2020-12-21 10:02
I am unable to reproduce this with the new migrate. 

<img width="1432" alt="image" src="https://user-images.githubusercontent.com/22195362/102764451-2b4a0900-43a1-11eb-96e8-8e7b23cb93b2.png">


We properly warn the user now that if they are using the old variants, the migration will fail.

Here is the generated migrations:
```sql
BEGIN;
CREATE TYPE "Dog_new" AS ENUM ('Arrow', 'Simba', 'Bruno');
ALTER TABLE "public"."Test" ALTER COLUMN "dog" TYPE "Dog_new" USING ("dog"::text::"Dog_new");
ALTER TYPE "Dog" RENAME TO "Dog_old";
ALTER TYPE "Dog_new" RENAME TO "Dog";
DROP TYPE "Dog_old";
COMMIT;
```

Also, with new migrate, you can specify the exact sql that you want to execute and change the generated statements if they doesn't cover your use case so I think this is addressed. 


cc @tomhoule I think we can close this one.

**Closed** 2021-02-02 17:46 UTC
Labels: bug/0-needs-info, kind/bug, team/migrations
