### ISSUE TITLE
Custom environments

### ISSUE THREAD

**Issue by HurricaneDancer** [prisma/prisma#2640] opened 2020-06-02 11:10 UTC
## Problem

Forcing the .env file is frustrating for those that run their application in different environments (beta, production etc) you will have different settings for your database. 

## Suggested solution

Allow users to set their own DATABASE_URL variable, so long as it's called that. Prisma should read the environment for that variable and throw an error if it doesnt find it. 

## Alternatives

Give users an option when initializing prisma to use custom envs 
npx prisma init -env (to enable the .env) 
## Additional context

When I deploy applications to my server I always have to change the password on the DATABASE_URL variable for the .env so being able to customise this with my own env would be nice.

**Comment by pantharshit00** [comment] 2020-06-03 14:43
Hi,

Thanks for reporting this! It has already been reported before, so I am going to close this as a duplicate of https://github.com/prisma/prisma/issues/1255


You can use the workaround specified here in the meanwhile: https://github.com/prisma/prisma/issues/1255#issuecomment-598743005

**Closed by pantharshit00** 2020-06-03 14:43 UTC
