### ISSUE TITLE
Prisma introspect is deleting models I created for database views

### ISSUE THREAD

**Issue by jacky-lam** [prisma/prisma#5501] opened 2021-02-05 19:50 UTC
## Bug description

Action:
I have create a simple database view in Postgres and then manually add the model for the view as instructed here:
- https://www.prisma.io/docs/guides/general-guides/database-workflows/sql-views-postgres

Bug:
- If I run `prisma generate` it works perfectly fine.
- However, if run `prisma introspect`, it deletes all my models that I had setup for the database views.

## How to reproduce
1. Create a simple database table.
2. Create a simple database view (for that table).
3. In the `schema.prisma` manually add the model for that database view.
4. Run `yarn prisma introspect`.
5. Check `schema.prisma` file, the model for that database view is gone.

## Expected behavior
After running `yarn prisma introspect`, it would not delete the model for the database view.

## Environment & setup
- OS: Mac OS
- Database: Postgres
- Node.js version: 12.20.*
- Prisma: 2.15

**Comment by janpio** [comment] 2021-02-05 23:16
This will solve your problem: https://www.prisma.io/docs/concepts/components/preview-features/native-types/native-types-mappings#ignore-and-ignore Note this is currently just a preview feature that needs to be explicitly enabled.

**Comment by jacky-lam** [comment] 2021-02-08 12:27
thank you @janpio. i will try to use this.

**Comment by jacky-lam** [comment] 2021-02-08 20:25
hi @janpio ,

I just updated my prisma version to `2.16.1` and put the `@ignore` tag at the bottom of the model definition as shown in the link you sent.

When i ran `yarn prisma introspect` it still deleted my model definition. Was that an expected behaviour?

**Comment by pantharshit00** [comment] 2021-02-09 11:42
That is unexpected. I will try to reproduce this.

**Comment by pantharshit00** [comment] 2021-02-09 12:04
Hey @jacky-lam 

Looks like this hasn't been implemented in reintrospection yet: https://github.com/prisma/prisma/issues/5331

Please wait on that here.

**Comment by pantharshit00** [comment] 2021-02-09 12:08
I suggest you also not use `@@ignore` in first place as models marked with that gets removed from the client API. The real solution here is having views supported in the schema: #678

**Comment by janpio** [comment] 2021-02-09 18:46
> I suggest you also not use `@@ignore` in first place as models marked with that gets removed from the client API.

That is actually true. So although you would keep the models, you would still not be able to use them. My bad, sorry.

**Comment by janpio** [comment] 2021-09-23 13:47
Closing this issue as https://github.com/prisma/prisma/issues/678 is the only way to make this nicer.

**Closed by janpio** 2021-09-23 13:47 UTC
Labels: kind/improvement, topic: introspection, team/migrations
