### ISSUE TITLE
Explore ideas for a Python client 🐍

### ISSUE THREAD

**Issue by Sytten** [prisma/prisma#2285] opened 2020-04-23 14:40 UTC
## Problem
Typing in Python 🐍 is now a real thing and can be quite powerful. I have yet to see an ORM/Query builder fill that space and I believe prisma could improve the status quo. Ideally this would be a direct binding instead of spawning a separate process since Rust can be called easily from Python with a C ABI. 

## Prior art
- [Stackoverflow dicussion on type hinting SqlAlchemy](https://stackoverflow.com/questions/55361186/type-hinting-sqlalchemy-query-result)
- [FluentQL](https://github.com/RaduG/fluentql): a library attempting to verify query validation at runtime using type hinting

## Challenges
- Typing that adapts to `select`, `include`, etc. This is not as "easy" as in Typescript because you cannot compose types on the fly in Python. 
- It is common for python servers to spawn multiple processes behind an WSGI (or ASGI) server. Ideally we would want to use the same query engine process (if we are still using a separate process at that time).
- Having an `async` interface (Python 3.6+) is I think the way to go, but we will need to support a `sync` API too for adoption.
- Making sure the typing works with most of the type checkers used in production: [pyright](https://github.com/microsoft/pyright), [mypy](http://mypy-lang.org/), [pyre-check](https://github.com/facebook/pyre-check), [pytype](https://github.com/google/pytype), [pycharm type checker](https://github.com/JetBrains/intellij-community/tree/master/python)

## Documentation
- [Protocols](https://www.python.org/dev/peps/pep-0544/) (structural typing) has been merge (3.8+) and will be quite important for us. This means that the typing will accept the input if the members/methods match the given type instead of explicitly requirement that it be the same type.

**Comment by w121211** [comment] 2020-06-11 11:21
Very happy to see Prisma has a python client. 
In my project, I use both typescript (for web-app) and python (for data mining). In such case, both typescript and python need to access the same database, and I think Prisma is the key to solve such problem.

**Comment by DrBenton** [comment] 2020-12-14 14:59
Hi! :slightly_smiling_face: 

Is there any way people can contribute to a Python client? Modern Python is almost as powerful as TypeScript in terms of typing annotations (and it seems that the few lacking aspect of Python vs TypeScript have already been identified here :arrow_up: ).
And the 2 languages are pretty comparable on many aspects - similar modules system, similar optional async/await syntax, first-class functions in both languages, etc. - , which would  probably help making such a port.

Moreover, Python has never been as popular as it is these days, and I reckon that a Python client would likely be an important vector of popularisation for Prisma.

As a Web developer mostly using Python, Postgresql and TypeScript in my day-to-day work, I would love to be able to contribute to a Python version of the Prisma client, wrapping the Rust engines.
I'm convinced that Prisma could become "_the next big thing"_ as a cross-technology approach to work with databases, with potential strong ecosystems around it, that could generate so much useful tools from the "declarative database schema" aspect of Prisma  - automatically build CMS, API, etc.

**Comment by adriangb** [comment] 2021-08-28 06:49
Posting this here for visibility: https://github.com/RobertCraigie/prisma-client-py/

I think a big +1 on this project is the use of Pydantic models as the data container / description. This will make it great for interoperability w/ FastAPI, in addition to being able to seamlessly add app level data parsing, etc

**Comment by RobertCraigie** [comment] 2021-09-07 20:50
Thanks @adriangb!

I actually hadn't seen this issue until now.

In regards to the challenges mentioned and how they relate to my client:

## Interfaces

Both `async` and `sync` interfaces are [supported](https://prisma-client-py.readthedocs.io/en/latest/setup/) although only one interface can be used at once.

## Typing select and include

This is a difficult one. Due to the limitations mentioned initially, all scalar model fields are selected by default and relational fields must be explicitly included.

However including a relational field doesn't change the returned type unless the [mypy plugin](https://prisma-client-py.readthedocs.io/en/latest/mypy/#removes-optional-from-relational-fields) is used. This only works as relational fields are typed as `Optional` and there is a fairly big downside to this which is that type checkers will not error when accessing the relational field without explicitly including it, for example:

```py
user = await client.user.find_unique(
    where={
        'id': 'abc',
    },
)
if user.posts is not None:  # this should error
    print(user.posts[0].title)
```

Currently selecting fields is not supported although I do have a [proposed solution](https://github.com/RobertCraigie/prisma-client-py/issues/19).

## Type checkers

Only [pyright](https://github.com/microsoft/pyright) and [mypy](http://mypy-lang.org/) are officially supported.

[pytype](https://github.com/google/pytype) will not be supported due to [missing features](https://github.com/google/pytype/issues/680).

[pyre-check](https://github.com/facebook/pyre-check) and the [pycharm type checker](https://github.com/JetBrains/intellij-community/tree/master/python) are untested.

## WSGI and ASGI integration

Although this has not been researched, I do have a working [example](https://github.com/RobertCraigie/prisma-client-py/tree/main/examples/fastapi-basic) with [FastAPI](https://fastapi.tiangolo.com/) and [uvicorn](https://www.uvicorn.org/).

**Comment by hyochan** [comment] 2022-06-19 14:28
@RobertCraigie Thank you so much for writing [Prisma Python Client](https://prisma-client-py.readthedocs.io/en/stable). This is very useful for writing server-side applications with [Fast API](https://fastapi.tiangolo.com).

I also wrote a [small article trying this in medium](https://medium.com/dooboolab/prisma-with-python-and-fastapi-33bf25bb20c0).

By the way, I think some features are missing like selecting specific columns while querying.

Thank you for the great work again @RobertCraigie 🙌

**Comment by RobertCraigie** [comment] 2022-06-20 09:49
Wow thank you so much @hyochan  for writing up a tutorial on Prisma Client Python, I really appreciate it 💜 

> By the way, I think some features are missing like selecting specific columns while querying.

Yeah, selecting specific columns is a pain point with the client right now as it would be impossible to implement it in the same fashion as the Prisma TS Client does because it cannot be typed correctly in Python :/

There is an open issue detailing my proposed solution, https://github.com/RobertCraigie/prisma-client-py/issues/19, do you have any thoughts on the API?

**Comment by jkomyno** [comment] 2024-12-06 13:36
Hi there,

As part of our effort to clean up our GitHub repo, we’re closing this issue to help focus on features and improvements that align with our focus areas and those of our community. 

If this is issue is still important to you, feel free to reopen the issue and get like-minded users to upvote as we will prioritize fixing issues based on community interest. If you do reopen the issue, please ensure that there’s a clear method for us to reproduce it. 

For more insight into our priorities and how we’re thinking about the future of the Prisma ORM, please see our recent blog post: https://www.prisma.io/blog/prisma-orm-manifesto.

Thank you for your understanding and support!

**Closed by jkomyno** 2024-12-06 13:36 UTC
Labels: kind/feature, topic: language, domain/client, status/has-custom-client
