### ISSUE TITLE
Prisma generate script throws error

### ISSUE THREAD

**Issue by yantakus** [prisma/prisma#2049] opened 2020-03-31 06:36 UTC
When I'm trying to run this example: https://github.com/prisma/prisma-examples/tree/master/typescript/graphql-auth

I'm getting the following problem. When running `npm i` I get this error:

```
> @prisma/client@2.0.0-preview025 postinstall /Users/yan/Projects/prisma-examples/typescript/graphql-auth/node_modules/@prisma/client
> node scripts/postinstall.js

Error: ENOENT: no such file or directory, mkdir

... Skip lines. Everything is ok here ...

> prisma2 generate

Error: ENOENT: no such file or directory, mkdir
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! graphql-auth@ generate:prisma: `prisma2 generate`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the graphql-auth@ generate:prisma script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/yan/.npm/_logs/2020-03-31T06_04_32_492Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! graphql-auth@ generate: `npm run generate:prisma && npm run generate:nexus`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the graphql-auth@ generate script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/yan/.npm/_logs/2020-03-31T06_04_32_519Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! graphql-auth@ postinstall: `npm run generate`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the graphql-auth@ postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/yan/.npm/_logs/2020-03-31T06_04_32_556Z-debug.log
```

and here is the above mentioned log file contents:

```
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'run',
1 verbose cli   'generate:prisma'
1 verbose cli ]
2 info using npm@6.14.4
3 info using node@v13.7.0
4 verbose run-script [ 'pregenerate:prisma', 'generate:prisma', 'postgenerate:prisma' ]
5 info lifecycle graphql-auth@~pregenerate:prisma: graphql-auth@
6 info lifecycle graphql-auth@~generate:prisma: graphql-auth@
7 verbose lifecycle graphql-auth@~generate:prisma: unsafe-perm in lifecycle true
8 verbose lifecycle graphql-auth@~generate:prisma: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/yan/Projects/prisma-examples/typescript/graphql-auth/node_modules/.bin:/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/yan/Projects/prisma-examples/typescript/graphql-auth/node_modules/.bin:/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/yan/Projects/prisma-examples/typescript/graphql-auth/node_modules/.bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
9 verbose lifecycle graphql-auth@~generate:prisma: CWD: /Users/yan/Projects/prisma-examples/typescript/graphql-auth
10 silly lifecycle graphql-auth@~generate:prisma: Args: [ '-c', 'prisma2 generate' ]
11 silly lifecycle graphql-auth@~generate:prisma: Returned: code: 1  signal: null
12 info lifecycle graphql-auth@~generate:prisma: Failed to exec generate:prisma script
13 verbose stack Error: graphql-auth@ generate:prisma: `prisma2 generate`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:321:20)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:321:20)
13 verbose stack     at maybeClose (internal/child_process.js:1026:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
14 verbose pkgid graphql-auth@
15 verbose cwd /Users/yan/Projects/prisma-examples/typescript/graphql-auth
16 verbose Darwin 19.0.0
17 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "generate:prisma"
18 verbose node v13.7.0
19 verbose npm  v6.14.4
20 error code ELIFECYCLE
21 error errno 1
22 error graphql-auth@ generate:prisma: `prisma2 generate`
22 error Exit status 1
23 error Failed at the graphql-auth@ generate:prisma script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

I tried to remove node_modules and install again with no luck.

Any ideas?

**Comment by timsuchanek** [comment] 2020-04-02 13:26
Thanks for reporting. We now catch, if the cache behavior fails, as it's optional and not needed for the generate command to succeed.

**Comment by RussMax783** [comment] 2020-04-10 06:02
@timsuchanek I'm running into this same issue on the the `2.0.0-beta.2` version, but not locally. I went to deploy the upgrade on AWS Elastic Beanstalk and started getting this error. The version I had previously deployed was `preview021` and it worked just fine. I've been trying to track down if there are permissions issues or something but am having no luck.  I totally get that there are a million use cases and build environments to consider so I'm not expecting anyone to know and fix my problem. Just wanted to update that there are probably a lot of other use cases where this will cause problems. 

![image](https://user-images.githubusercontent.com/5333786/78966904-3b91b080-7abe-11ea-88e8-4a8f1431604e.png)


Whats interesting to me is that i see those logs, and then the failure. I'm not sure how to provide more information on this bad boy. But I'm happy to answer questions and help dig into it.

**Comment by janpio** [comment] 2020-04-10 18:55
You can try setting `DEBUG=*` as an env var to get more output hopefully.

**Comment by RussMax783** [comment] 2020-04-11 22:37
[nodejs.log](https://github.com/prisma/prisma/files/4465568/nodejs.log)

Here is the log from elastic beanstalk after setting `DEBUG=*` Starts at the bottom of the file.

**Comment by timsuchanek** [comment] 2020-04-15 07:14
Thanks for reporting @RussMax783!

It looks like you're trying to run prisma generate, while maybe the filesystem can't be accessed within your AWS Elastic Beanstalk.

If that is the case, we should for sure catch the error nicer.

The action item from our side: Improve the error message.
If you e.g. do a simple `fs.writeFileSync('test', 'test')` in your application, you can validate, if you can write to the filesystem or not.

**Comment by RussMax783** [comment] 2020-04-15 13:40
I created a node script and ran it right before running prisma generate. The script looks like this:

```js
const fs = require('fs')

console.log('RUNNING TEST')

console.log('Current path: ', __dirname)

fs.writeFileSync('test', 'test')

fs.readdir('./', function(err, items) {
  console.log(items)

  for (var i = 0; i < items.length; i++) {
    console.log(items[i])
  }
})

console.log('FINISHED RUNNING TEST')
```

and the log looks like this. 

```
RUNNING TEST
Current path:  /var/app/current/src
FINISHED RUNNING TEST
[
  'dist',
  'node_modules',
  'npm-shrinkwrap.json',
  'package.json',
  'prisma',
  'src',
  'test'
]
dist
node_modules
npm-shrinkwrap.json
package.json
prisma
src
test
```

**Comment by RussMax783** [comment] 2020-04-21 16:06
@timsuchanek Because I still see the message that the generate command succeeded (the `you can now start using prisma client...`) I had the idea to wrap calling `prisma generate` in a script and allow the environment to keep moving on and start. It seems to have worked! My Elastic beanstalk is now up and running and seems to be working just fine. So I wonder if there is some async command being run to create some directory and its being thrown after the fact. Happy to dig in more.

**Comment by matthewmueller** [comment] 2020-08-24 10:19
@RussMax783 are you still seeing this after you generate inside Elastic Beanstalk?

Does it still log

```
Error: Error: ENOENT: no such file or directory, mkdir
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! maxway-server@0.0.1 prestart: `DEBUG=* prisma generate`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the maxway-server@0.0.1 prestart script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

When you **don't** have `DEBUG=*`?

**Comment by kimchhickey** [comment] 2020-09-04 05:25
I am trying to run prisma generate in AWS Elastic Beanstalk. I got the error, either. How is it going?

**Comment by pantharshit00** [comment] 2020-09-09 10:05
@kimchhickey Can you please lay out the reproductions steps that I can use to reproduce this in elastic beanstalk. That will help a lot!


Also, please paste the actual error message that you are getting here

**Comment by johhansantana** [comment] 2020-09-24 20:19
I just recently have this issue:

```
[Error: EACCES: permission denied, mkdir '/var/app/staging/node_modules/.prisma'] {
  errno: -13,
  code: 'EACCES',
  syscall: 'mkdir',
  path: '/var/app/staging/node_modules/.prisma'
}
Error: Can't write to /var/app/staging/node_modules/@prisma/cli please make sure you install "@prisma/cli" with the right permissions.
Error: Can't write to /var/app/staging/node_modules/@prisma/sdk please make sure you install "@prisma/cli" with the right permissions.
```

I am basically creating a simple instance in AWS EBS UI
Then I .zip all my prisma files and upload that.
Then it gives me the above error.

**Comment by johhansantana** [comment] 2020-09-24 20:27
I was able to fix this by adding a file in the root folder called `.npmrc` then adding inside this `unsafe-perm=true`

**Comment by janpio** [comment] 2020-09-25 10:59
Can you please open a new issue with just the text you posted here @johhansantana please? We should and want to look into this, but that is much easier with a separate issue just for your case. Thanks.

**Comment by croossin** [comment] 2021-01-24 23:03
@johhansantana Thanks for the tip... I got past the invalid access issue.. but then ran into the following issue. Did you see this too?

```bash
Environment variables loaded from .env
Prisma schema loaded from prisma/schema.prisma
info The postinstall script automatically ran `prisma generate`, which failed.
The postinstall script still succeeds but won't generate the Prisma Client.
```

**Comment by janpio** [comment] 2021-03-23 19:21
That is just an information and should not block anything @croossin.

I am going to close this now. Happy to take a look again if we get more information.

**Closed by janpio** 2021-03-23 19:21 UTC
Labels: bug/0-needs-info, kind/bug

**Comment by lc443** [comment] 2022-02-01 21:49
on my Mac I did sudo prism generate then it worked

**Comment by aarjan** [comment] 2022-03-24 13:40
Mine was fixed by changing the ownership of the node_modules/.prisma folder from **root** to the default one.

**Comment by KinjalWS** [comment] 2022-05-23 13:21
> 



> I had this issue in my docker container. Mine was fixed by changing the ownership of the node_modules/.prisma folder from **root** to the default one.

Can you please elaborate on this @aarjan ?

**Comment by aarjan** [comment] 2022-05-23 14:55
> > 
> 
> 
> 
> > I had this issue in my docker container. Mine was fixed by changing the ownership of the node_modules/.prisma folder from **root** to the default one.
> 
> Can you please elaborate on this @aarjan ?

I changed it from root to node
chown -R node_modules/.prisma node:node

**Comment by sostenesapollo** [comment] 2023-06-08 20:47
```
bash-3.2$ chown -R node_modules/.prisma node:node
chown: node_modules/.prisma: illegal user name
```
