### ISSUE TITLE
Hi Prisma Team! My Prisma Client just crashed

### ISSUE THREAD

**Issue by DenisVASI9** [prisma/prisma#7289] opened 2021-05-26 16:36 UTC
Hi Prisma Team! My Prisma Client just crashed. This is the report:
## Versions

| Name            | Version            |
|-----------------|--------------------|
| Node            | v14.15.4           | 
| OS              | debian-openssl-1.1.x|
| Prisma Client   | 2.22.1             |
| Query Engine    | query-engine 60cc71d884972ab4e897f0277c4b84383dddaf6c|
| Database        | undefined|

## Query
```
query {
  findManygroup {
    id
    name
    devices {
      id
      mac
      ipv4
      ipv6
      _count {
        groups
      }
    }
  }
}
```

## Logs
```
onment variables loaded  
  prisma:client clientVersion: 2.22.1  
  prisma:engine { cwd: '/home/devbook/club/src/database/prisma' }  
  prisma:engine Search for Query Engine in /home/devbook/club/node_modules/.prisma/client  
  prisma:engine Search for Query Engine in /home/devbook/club/node_modules/.prisma/client  
  plusX Execution permissions of /home/devbook/club/node_modules/.prisma/client/query-engine-debian-openssl-1.1.x are fine  
  plusX Execution permissions of /home/devbook/club/node_modules/.prisma/client/query-engine-debian-openssl-1.1.x are fine  
  prisma:engine { flags: [ '--enable-raw-queries', '--port', '37033' ] }  
  prisma:engine stdout  Starting a postgresql pool with 9 connections.  
  prisma:engine stdout  Fetched a connection from the pool  
  prisma:engine stdout  Started http server on http://127.0.0.1:37033  
  prisma:engine Search for Query Engine in /home/devbook/club/node_modules/.prisma/client  
  plusX Execution permissions of /home/devbook/club/node_modules/.prisma/client/query-engine-debian-openssl-1.1.x are fine  
  prisma:engine Client Version: 2.22.1  
  prisma:engine Engine Version: query-engine 60cc71d884972ab4e897f0277c4b84383dddaf6c  
  prisma:engine Active provider: postgresql  
  prisma:engine stdout  Fetched a connection from the pool  +2s
  prisma:engine stdout  PANIC in query-engine/core/src/query_graph_builder/read/utils.rs:52:85
called `Result::unwrap()` on an `Err` value: FieldNotFound { name: "_count", model: "device" }  
  prisma:engine {
  prisma:engine   error: SocketError: other side closed
  prisma:engine       at Socket.onSocketEnd (/home/devbook/club/node_modules/@prisma/client/runtime/index.js:25530:24)
  prisma:engine       at Socket.emit (events.js:327:22)
  prisma:engine       at Socket.EventEmitter.emit (domain.js:467:12)
  prisma:engine       at endReadableNT (internal/streams/readable.js:1327:12)
  prisma:engine       at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  prisma:engine     code: 'UND_ERR_SOCKET'
  prisma:engine   }
  prisma:engine }  
  prisma:engine {
  prisma:engine   error: Error: connect ECONNREFUSED 127.0.0.1:37033
  prisma:engine       at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1146:16) {
  prisma:engine     errno: -111,
  prisma:engine     code: 'ECONNREFUSED',
  prisma:engine     syscall: 'connect',
  prisma:engine     address: '127.0.0.1',
  prisma:engine     port: 37033
  prisma:engine   }
  prisma:engine }  
  prisma:engine { cwd: '/home/devbook/club/src/database/prisma' }  
  prisma:engine Search for Query Engine in /home/devbook/club/node_modules/.prisma/client  
  plusX Execution permissions of /home/devbook/club/node_modules/.prisma/client/query-engine-debian-openssl-1.1.x are fine  +2s
  prisma:engine { flags: [ '--enable-raw-queries', '--port', '46019' ] }  
  prisma:engine stdout  Starting a postgresql pool with 9 connections.  
  prisma:engine stdout  Fetched a connection from the pool  
  prisma:engine stdout  Started http server on http://127.0.0.1:46019  
  prisma:en

**Comment by janpio** [comment] 2021-05-26 17:14
Can you add some more information, that https://github.com/prisma/prisma/issues/new?assignees=&labels=kind%2Fbug&template=bug_report.yml would be asking for? That would be very useful. Thanks.

**Comment by DenisVASI9** [comment] 2021-05-27 09:55
@janpio https://github.com/prisma/prisma/issues/7304, Yes, I would be happy to help

**Comment by pantharshit00** [comment] 2021-05-27 13:30
Closing as duplicate of #7304

**Closed by pantharshit00** 2021-05-27 13:30 UTC
Labels: topic: basic error report
