### ISSUE TITLE
Elastic Beanstalk: Error: @prisma/client did not initialize yet

### ISSUE THREAD

**Issue by dakshshah96** [prisma/prisma#6216] opened 2021-03-23 18:23 UTC
## Bug description

I'm trying to deploy to Elastic Beanstalk by following this tutorial: https://www.prisma.io/docs/guides/deployment/deployment#aws-elastic-beanstalk.

Created a `.npmrc` file in the root of my project and added `unsafe-perm=true` configuration.

I still get an error saying that `@prisma/client` has not been initialized when I try to do `npm start` and run my server.

```
web: > api-server@1.23.3 start /var/app/current
web: > node src/index.js
web: Error: @prisma/client did not initialize yet. Please run "prisma generate" and try to import it again.
web: In case this error is unexpected for you, please report it in https://github.com/prisma/prisma/issues
web: at new PrismaClient (/var/app/current/node_modules/.prisma/client/index.js:3:11)
web: at Object.<anonymous> (/var/app/current/src/apollo-server.js:14:16)
web: at Module._compile (internal/modules/cjs/loader.js:1063:30)
web: at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
web: at Module.load (internal/modules/cjs/loader.js:928:32)
web: at Function.Module._load (internal/modules/cjs/loader.js:769:14)
web: at Module.require (internal/modules/cjs/loader.js:952:19)
web: at require (internal/modules/cjs/helpers.js:88:18)
web: at Object.<anonymous> (/var/app/current/src/index.js:31:22)
web: at Module._compile (internal/modules/cjs/loader.js:1063:30)
web: at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
web: at Module.load (internal/modules/cjs/loader.js:928:32)
web: at Function.Module._load (internal/modules/cjs/loader.js:769:14)
web: at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
web: at internal/main/run_main_module.js:17:47
web: npm ERR! code ELIFECYCLE
web: npm ERR! errno 1
web: npm ERR! api-server@1.23.3 start: `node src/index.js`
web: npm ERR! Exit status 1
web: npm ERR!
web: npm ERR! Failed at the api-server@1.23.3 start script.
web: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
web: npm ERR! A complete log of this run can be found in:
web: npm ERR! /home/webapp/.npm/_logs/2021-03-23T18_06_34_230Z-debug.log
```

## How to reproduce

Try deploying a Prisma app to AWS Elastic Beanstalk by following the instructions in the tutorial.

## Expected behavior

Expected `@prisma/client` to be initialized correctly since I've already set up a `.npmrc` file in the root of my project with the correct configuration.

## Prisma information

```
"devDependencies": {
  ...
  "prisma": "^2.17.0"
},
"dependencies": {
  ...
  "@prisma/client": "^2.17.0"
}
```

## Environment & setup

- OS: 64bit Amazon Linux 2/5.3.0
- Database: PostgreSQL
- Node.js version: Node.js 14
- Prisma version:

```
"devDependencies": {
  ...
  "prisma": "^2.17.0"
},
"dependencies": {
  ...
  "@prisma/client": "^2.17.0"
}
```

**Comment by armendh** [comment] 2021-03-28 21:59
@timsuchanek 
I'm having the same issue.

**Comment by janpio** [comment] 2021-03-29 18:57
Can you share the full output you are getting while installing the project on that environment?

**Comment by altaudio** [comment] 2021-04-13 13:19
After a lot of digging, I think I have found the issue and a fix 🎉
### 😓 Issue
The key to the issue is that by default an Elastic Beanstalk installs dependencies with `npm install --production`, which does not install `devDependencies`.

The `@prisma/client` `postinstall.js` script (which generates the client) requires the Prisma CLI to be installed either locally or globally. However (in my case) the Prism CLI `prisma` was in `devDependencies` [(as recommended in the docs)](https://www.prisma.io/docs/concepts/components/prisma-cli/installation#npm), so when my code was installed on an EB container this dependency was skipped, and the `postinstall.js` script fell over with the error:
```
warning In order to use "@prisma/client", please install Prisma CLI. You can install it with "npm add -D prisma".
```
### ✅ Fix
There are two options, both of which are different ways of including the Prisma CLI in EB dependency installs:
1. Add `prisma` to your dependencies (best solution)
2. From the [EB docs](https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/nodejs-platform-dependencies.html): `If you want to install development dependencies on your environment instances, set the NPM_USE_PRODUCTION environment property to false.`

**Comment by mcoevert** [comment] 2021-05-14 13:02
@altaudio Great suggestion! I've faced the same problem with FIrebase functions, and this fixed it. Remember to run npm install locally first so package-lock.json is updated.

**Comment by pantharshit00** [comment] 2021-05-16 13:56
I guess this is resolved now. Closing!

**Closed by pantharshit00** 2021-05-16 13:56 UTC
Labels: bug/0-needs-info, kind/bug, team/client, topic: deployment-platform

**Comment by dakshshah96** [comment] 2021-05-16 16:27
@pantharshit00 The [Prisma docs for Elastic Beanstalk](https://www.prisma.io/docs/guides/deployment/deployment-guides/caveats-when-deploying-to-aws-platforms#aws-elastic-beanstalk) don't seem to cover this. Would it be a good idea to add one of @altaudio's fixes to the docs?

![CleanShot 2021-05-16 at 21 46 36](https://user-images.githubusercontent.com/7896438/118404719-ad5d0600-b691-11eb-9c2a-085e12bd30bc.png)

**Comment by pantharshit00** [comment] 2021-05-17 13:11
@dakshshah96 
https://github.com/prisma/docs/issues/1709

**Comment by rajapattanayak** [comment] 2021-05-24 15:30
> 1. Add `prisma` to your dependencies rather than `devDependencies`
I faced the same issue while deploying to firebase. Your above suggestion helped me. Could deploy now. Thank you so much

**Comment by Harsh4999** [comment] 2023-05-13 07:29
> > 1. Add `prisma` to your dependencies rather than `devDependencies`
> 
> I faced the same issue while deploying to firebase. @altaudio Your above suggestion helped me. Can deploy now. Thank you so much

Hey @rajapattanayak I am also trying to deploy a next js project with Prisma to firebase functions but getting Prisma could not be initialised error this is my package.json I don't know why when I run `npm i` the Prisma moves from dependency to dev dependency so I manually put it under dependency and than run firebase deploy but then same error


{
  "name": "deployment2",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "build": "next build && npx prisma generate",
    "dev": "npx prisma generate && next dev",
    "postinstall": "npx prisma generate",
    "lint": "npx prisma generate && next lint",
    "start": "npx prisma generate && next start",
    "preinstall": "npm install prisma && npx prisma generate"
  },
  "dependencies": {
    "@prisma/client": "^4.11.0",
    "@t3-oss/env-nextjs": "^0.2.1",
    "@tanstack/react-query": "^4.28.0",
    "@trpc/client": "^10.18.0",
    "@trpc/next": "^10.18.0",
    "@trpc/react-query": "^10.18.0",
    "@trpc/server": "^10.18.0",
    "next": "^13.4.1",
    "prisma": "^4.14.0",
    "react": "18.2.0",
    "react-dom": "18.2.0",
    "superjson": "1.12.2",
    "zod": "^3.21.4"
  },
  "devDependencies": {
    "@types/eslint": "^8.21.3",
    "@types/node": "^18.15.5",
    "@types/prettier": "^2.7.2",
    "@types/react": "^18.0.28",
    "@types/react-dom": "^18.0.11",
    "@typescript-eslint/eslint-plugin": "^5.56.0",
    "@typescript-eslint/parser": "^5.56.0",
    "autoprefixer": "^10.4.14",
    "eslint": "^8.36.0",
    "eslint-config-next": "^13.4.1",
    "postcss": "^8.4.21",
    "prettier": "^2.8.6",
    "prettier-plugin-tailwindcss": "^0.2.6",
    "tailwindcss": "^3.3.0",
    "typescript": "^5.0.2"
  },
  "ct3aMetadata": {
    "initVersion": "7.13.0"
  }
}

Please guide me what might be wrong here

**Comment by Daim-Nickel-Penny** [comment] 2023-05-13 13:31
Issue:
Encountering an error stating that` @prisma/client did not initialize yet. Please run "prisma generate" and try to import it again` when deploying a NestJS application with Prisma ORM on AWS Elastic Beanstalk.

What I've Tried:

Followed the instructions in the "Caveats when deploying to AWS platforms" section of the Prisma documentation.
Added the Prisma CLI package to project dependencies and updated the package-lock.json by running npm install.
Set the AWS Elastic Beanstalk NPM_USE_PRODUCTION environment property to false to install devDependencies on instances.

NO LUCK! I finally created a new issue.
[Issue](https://github.com/prisma/docs/issues/4769)

**Comment by Harsh4999** [comment] 2023-05-13 15:59
I just resolved my issue on firebase deployment so in my case it was this

I found the root cause and solution:

So basically in my project structure I had a prisma folder and inside that schema.prisma file and when I ran firebase deploy the schema.prisma file was not getting uploaded to firebase function and hence my post install script of prisma generate was failing so the work around here is to include this in firebase.json

````json

   "predeploy":[      "cp prisma/schema.prisma .firebase/${YOUR PROJECT NAME}/functions/schema.prisma"    ]
   
 ````

This copies schema file and puts it into functions folder note to replace your project name before using this. After this you can use this script in package.json add this under script section:


````json
 "postinstall": "npx prisma generate --schema=schema.prisma",

````


This will run npx prisma generate after deployment and we are also mentioning where our prisma file location is

I hope this saves hours of searching

So @Daim-Nickel-Penny I would recommend you to first confirm and check what all things are getting eventually uploaded high chance that schema.prisma is not being deployed and then your post install script would fail also if you are sure schema.prisma is uploaded make sure to add postinstall in package.json
