### ISSUE TITLE
Prisma doesn't work on Linux aarch64 (through Docker on Mac M1)

### ISSUE THREAD

**Issue by joaom182** [prisma/prisma#9572] opened 2021-10-03 14:29 UTC
### Bug description

I'm trying to run a Prisma application in the Linux Alpine aarch64 through the Docker on my Mac M1

```
Linux 69b51cb4aba2 5.10.47-linuxkit #1 SMP PREEMPT Sat Jul 3 21:50:16 UTC 2021 aarch64 Linux
```

I've already tried to add the `binaryTargets` on `schema.prisma`

```
generator client {
  provider      = "prisma-client-js"
  binaryTargets = ["native", "linux-musl", "linux-arm-openssl-1.1.x"]
}
```

And when I try to run `prisma generate` on the Docker container it throws the following error:

```
Error: Unable to require(`/usr/app/node_modules/prisma/libquery_engine-linux-arm-openssl-1.1.x.so.node`)
 Error loading shared library ld-linux-aarch64.so.1: No such file or directory (needed by /usr/app/node_modules/prisma/libquery_engine-linux-arm-openssl-1.1.x.so.node)
```

### How to reproduce

The error will only happen on Mac M1, on Mac with Intel processors, everything works fine.

1. Clone https://github.com/joaom182/learn-graphql-prisma
2. Run `yarn docker:build`
4. It will throw the following error

```
#12 1.245 Error: Unable to require(`/usr/app/node_modules/prisma/libquery_engine-linux-arm-openssl-1.1.x.so.node`)
#12 1.245  Error loading shared library ld-linux-aarch64.so.1: No such file or directory (needed by /usr/app/node_modules/prisma/libquery_engine-linux-arm-openssl-1.1.x.so.node)
```

### Expected behavior

Should `prisma generate` work without binary issues on Linux aarch64

### Prisma information

```prisma
datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

generator client {
  provider      = "prisma-client-js"
  binaryTargets = ["native", "linux-musl", "linux-arm-openssl-1.1.x"]
}

generator typegraphql {
  provider           = "typegraphql-prisma"
  output             = "./generated/type-graphql"
  emitTranspiledCode = true
}

model User {
  id       Int      @id @default(autoincrement())
  email    String   @unique
  name     String?
}
```

### Environment & setup

- OS: Mac OS (M1)
- Database: PostgresSQL
- Node.js version: v14.18.0

### Prisma Version

```
prisma                  : 3.0.1
@prisma/client          : 3.0.1
Current platform        : darwin
Query Engine (Node-API) : libquery-engine 2452cc6313d52b8b9a96999ac0e974d0aedf88db (at node_modules/@prisma/engines/libquery_engine-darwin.dylib.node)
Migration Engine        : migration-engine-cli 2452cc6313d52b8b9a96999ac0e974d0aedf88db (at node_modules/@prisma/engines/migration-engine-darwin)
Introspection Engine    : introspection-core 2452cc6313d52b8b9a96999ac0e974d0aedf88db (at node_modules/@prisma/engines/introspection-engine-darwin)
Format Binary           : prisma-fmt 2452cc6313d52b8b9a96999ac0e974d0aedf88db (at node_modules/@prisma/engines/prisma-fmt-darwin)
Default Engines Hash    : 2452cc6313d52b8b9a96999ac0e974d0aedf88db
Studio                  : 0.423.0
```

**Comment by pantharshit00** [comment] 2021-10-03 17:33
Hi,

Thanks for reporting this! It has already been reported before, so I am going to close this as a duplicate of https://github.com/prisma/prisma/issues/8478

**Closed by pantharshit00** 2021-10-03 17:33 UTC
Labels: kind/bug

**Comment by joaom182** [comment] 2021-10-03 19:02
@pantharshit00 I believe that both are correlated, but not duplicated. If you take a look at the issue description, the libs are different.

Correct me if I'm wrong, but the issue here is with the lib `ld-linux-aarch64.so.1` that I think is wrongly referenced on `libquery_engine-linux-arm-openssl-1.1.x.so.node`

**Comment by joaom182** [comment] 2021-10-03 20:29
The workaround that I found to make it work, is changing the base image on Dockerfile, from `node:alpine` to `node:lts`

**Comment by pantharshit00** [comment] 2021-10-04 09:42
@joaom182 They are the same. Old one was opened at a time when Node API wasn't the default so it didn't referenced a the shared `.so.node` library file. When we will compile for `aarch64-unknown-linux-musl`, we will also compile the Node API shared library file while client uses and it will not throw the error referenced above.

**Comment by spvn87** [comment] 2022-03-04 21:57
I posted an interim solution to this for alpine in the duped issue: https://github.com/prisma/prisma/issues/8478#issuecomment-1059559520

Crossposting here because Google brought me here originally and not to the first issue :)

**Comment by pimmesz** [comment] 2023-01-12 08:55
Is there a workaround which doesn't use Docker? Just trying to run my project on Raspbian 64 bit (aarch64).
