### ISSUE TITLE
Prisma Introspect generates invalid relation names

### ISSUE THREAD

**Issue by serranoarevalo** [prisma/prisma#4081] opened 2019-02-21 10:56 UTC
**Describe the bug**
 I have introspected a Django PostgreSQL database with Prisma and the datamodel.prisma file that has been generated cannot be deployed because all the @relation names have been generated with underscores _ which makes them invalid.

Shouldn't the introspect command generate valid @relation names?

Any workaround for this?

![code](https://user-images.githubusercontent.com/3612017/53163979-d81a9a00-3601-11e9-8cd3-0c94509c978a.png)

<img width="1343" alt="screen shot 2019-02-21 at 5 58 55 pm" src="https://user-images.githubusercontent.com/3612017/53164320-832b5380-3602-11e9-8b84-b6e66cbfac9b.png">

**Comment by pantharshit00** [comment] 2019-02-21 16:46
@serranoarevalo 

Which version of cli are you using?

We recently fixed many of the introspection issues in #4031 so please upgrade to version `1.27` and try again.

If this still an issue please provide a dump of the database which you are using.

**Comment by serranoarevalo** [comment] 2019-02-21 17:13
Hi! I updated and now there are even more and different errors.

You want to see some sample data from the DB or the datamodel.prisma generated by the command?

**Comment by pantharshit00** [comment] 2019-02-21 17:14
@serranoarevalo Please, share

Also cc @ejoebstl

**Comment by serranoarevalo** [comment] 2019-02-21 17:15
@pantharshit00 which one?

**Comment by pantharshit00** [comment] 2019-02-21 17:17
Both sql dump and the new generated datamodel.

**Comment by pantharshit00** [comment] 2019-02-21 17:31
@serranoarevalo 

Just noticed that introspection improvements were merged into beta for now.

Can you please try `npm i -g prism@beta` and try again?

**Comment by serranoarevalo** [comment] 2019-02-21 17:53
I updated to @beta and I still have errors, you can find the requested files below:

Datamodel: https://gist.github.com/serranoarevalo/cbb63a2ea0726e7f46c47431ff429da4
Errors on deploy: https://gist.github.com/serranoarevalo/9c8a1b2cc65999b9367f8c927691faa1
Dump: https://gist.github.com/serranoarevalo/40c24f32920ef9ce01470aaffe85d98d

**Comment by pantharshit00** [comment] 2019-02-22 17:30
@serranoarevalo 

Looks like the generate name is exceeding the character limit.

This will require a fix.

**Comment by ejoebstl** [comment] 2019-02-22 19:37
Hello, 

thanks for the files @serranoarevalo, very helpful. I was able to reproduce the issue. 

It seems like the CLI is printing an unnormalized datamodel. The duplicate fields and relations names which cause issues here should not even be part of the result.

**Comment by ejoebstl** [comment] 2019-02-22 20:35
Does this [introspection result](https://gist.github.com/ejoebstl/dc19368ae5695bedf2e6111fc2e2d108) look better?

I've pushed a fix [here](https://github.com/prisma/prisma/pull/4090).

That eliminates most problems with the current stable server (1.27). The remaining issue right now is that integer IDs are not support.

**Comment by serranoarevalo** [comment] 2019-02-24 13:57
Thanks a lot for looking into this!

Any ETA for this?

**Comment by mattdamon108** [comment] 2019-02-25 09:43
#3746
I had raised the same issue before, I hope this fixed soon.

**Comment by pantharshit00** [comment] 2019-04-04 16:33
The fix has landed in the stable version.


Please open a new issue if you are still facing this

**Closed by pantharshit00** 2019-04-04 16:33 UTC
Labels: area/introspection, bug/2-confirmed
