### ISSUE TITLE
Allow prisma-client to take null as input values

### ISSUE THREAD

**Issue by Weakky** [prisma/prisma#3622] opened 2018-11-29 13:31 UTC
**Is your feature request related to a problem? Please describe.**

This is related to graphqlgen, and specifically to https://github.com/prisma/graphqlgen/issues/278 (Everything is already clearly explained here)

GraphQL accepts nullable input fields either as `undefined` or `null`. As a result, graphqlgen needs to type all input fields as `field: type | undefined | null`, or `field?: type | null`

However, `prisma-client` **does not** accept `null` as input values of queries/mutations, probably because it doesn't make sense in the context of the client.

Unfortunately, this prevents users from passing typed arguments with graphqlgen to `prisma-client`, because `undefined | null` !== `undefined`.

**Comment by nikolasburk** [comment] 2018-11-29 13:34
Closing as a duplicate of https://github.com/prisma/prisma/issues/3621

**Closed by nikolasburk** 2018-11-29 13:34 UTC
