### ISSUE TITLE
Error: [libs/datamodel/connectors/dml/src/model.rs:160:14] We assume an internally valid datamodel before mutating.

### ISSUE THREAD

**Issue by kimchhung** [prisma/prisma#6181] opened 2021-03-19 05:15 UTC
Hi Prisma Team! Prisma Migrate just crashed. 

## Command

`introspect`

## Versions
      
| Name        | Version            |
|-------------|--------------------|
| Platform    | debian-openssl-1.1.x| 
| Node        | v12.18.2           | 
| Prisma CLI  | 2.18.0             | 
| Binary      | da6fafb57b24e0b61ca20960c64e2d41f9e8cff1| 

## Error
```
Error: [libs/datamodel/connectors/dml/src/model.rs:160:14] We assume an internally valid datamodel before mutating.
```

**Comment by pantharshit00** [comment] 2021-03-22 10:36
Hello! Can you please provide a minimal reproduction for the above crash? Unfortunately the automatically collected information in the issue does not give us much to go with here - we will need a bit more information. What were you doing? Can you share the code and schema that was active?

**Comment by Jolg42** [comment] 2021-03-25 11:03
Thanks for reporting this.

Unfortunately, we were not collecting the information in our error reporting in a format that allows us to replay the bug. That has changed with 2.19.0. Can you please try again with this version? This should allow us to exactly pinpoint the issue.

I'm closing this one now because we cannot act on it.
Please just open a new issue once you retried with 2.19.0 and still get an error.

**Closed by Jolg42** 2021-03-25 11:03 UTC
Labels: bug/0-needs-info, kind/bug, team/migrations, topic: basic error report
