### ISSUE TITLE
Error node_modules\@prisma\engines\query_engine-windows.dll.node is not a valid Win32 application

### ISSUE THREAD

**Issue by RobertCZ** [prisma/prisma#24964] opened 2024-08-06 13:55 UTC
### Bug description

Prisma on Windows 11/ARM64/LTS NodeJS doesnt start anymore (pull/generate still working correctly)

### Prisma information

```prisma
// Add your schema.prisma
```

```ts
// Add your code using Prisma Client
```

### Environment & setup

- OS: 
- Database: 
- Node.js version: 

### Prisma Version

```
Environment variables loaded from prisma\.env
Error: Unable to require(`C:\Users\.....\node_modules\@prisma\engines\query_engine-windows.dll.node`).
The Prisma engines do not seem to be compatible with your system. Please refer to the documentation about Prisma's system requirements: https://pris.ly/d/system-requirements

Details: \\?\C:\Users\...r\node_modules\@prisma\engines\query_engine-windows.dll.node is not a valid Win32 application.
\\?\C:\Users\....\node_modules\@prisma\engines\query_engine-windows.dll.node
    at Vee (C:\Users....node_modules\prisma\build\index.js:292:116)
    at Lqe (C:\Users\....node_modules\prisma\build\index.js:292:269)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
prisma                  : 5.12.1
@prisma/client          : 5.12.1
Computed binaryTarget   : windows
Operating System        : win32
Architecture            : arm64
Node.js                 : v20.16.0
Query Engine (Node-API) : E_CANNOT_RESOLVE_VERSION (at node_modules\@prisma\engines\query_engine-windows.dll.node)
Schema Engine           : schema-engine-cli 473ed3124229e22d881cb7addf559799debae1ab (at node_modules\@prisma\engines\schema-engine-windows.exe)
Schema Wasm             : @prisma/prisma-schema-wasm 5.12.0-21.473ed3124229e22d881cb7addf559799debae1ab
Default Engines Hash    : 473ed3124229e22d881cb7addf559799debae1ab
Studio                  : 0.499.0
Preview Features        : multiSchema
```

**Comment by RobertCZ** [comment] 2024-08-06 13:57
Tried also NodeJS 22.5.1 and Prisma 5.17 (and various other combinations), still same error. It used to work just fine for some slightly older versions of NodeJS 20

**Comment by Weakky** [comment] 2024-08-07 16:06
Hey @RobertCZ, would you mind providing us with a reproduction repository or at least detailed steps to reproduce the error you're seeing? That'd help us a lot. Thanks

**Comment by RobertCZ** [comment] 2024-08-08 08:54
I'll have to setup a fake Windows database but I'll see what I can do. For now (and for others hit by similar issue) Im now running NodeJS X64 build (with Rosetta) which somewhat surprisingly seems to work just fine (as opposed to ARM64 build reported above - both builds are MSI from official download site).

**Comment by RobertCZ** [comment] 2024-08-08 09:30
```
npx try-prisma@latest --template javascript/rest-fastify
cd .\javascript_rest-fastify
npm install
npx prisma migrate dev --name init
npm run dev

> rest-fastify@1.0.0 dev
> node src/index.js

{"level":30,"time":1723108615531,"pid":12228,"hostname":"GERMIC44B3","msg":"Server listening at http://[::1]:3000"}
{"level":30,"time":1723108615533,"pid":12228,"hostname":"GERMIC44B3","msg":"Server listening at http://127.0.0.1:3000"}

🚀 Server ready at: http://localhost:3000

```

```
npx prisma -v
prisma                  : 5.17.0
@prisma/client          : 5.17.0
Computed binaryTarget   : windows
Operating System        : win32
Architecture            : x64
Node.js                 : v20.16.0
Query Engine (Node-API) : libquery-engine 393aa359c9ad4a4bb28630fb5613f9c281cde053 (at node_modules\@prisma\engines\query_engine-windows.dll.node)
Schema Engine           : schema-engine-cli 393aa359c9ad4a4bb28630fb5613f9c281cde053 (at node_modules\@prisma\engines\schema-engine-windows.exe)
Schema Wasm             : @prisma/prisma-schema-wasm 5.17.0-31.393aa359c9ad4a4bb28630fb5613f9c281cde053
Default Engines Hash    : 393aa359c9ad4a4bb28630fb5613f9c281cde053
Studio                  : 0.502.0
```



Now I run again `node-v20.16.0-x64.msi` to uninstall it and run `node-v20.16.0-arm64.msi` to install arm version. I create completely new folder and start running commands above again.

```
npx try-prisma@latest --template javascript/rest-fastify
cd .\javascript_rest-fastify
npm install
npx prisma migrate dev --name init

Prisma schema loaded from prisma\schema.prisma
Datasource "db": SQLite database "dev.db" at "file:./dev.db"

SQLite database dev.db created at file:./dev.db

Applying migration `20240808092450_init`

The following migration(s) have been created and applied from new schema changes:

migrations/
  └─ 20240808092450_init/
    └─ migration.sql

Your database is now in sync with your schema.

✔ Generated Prisma Client (v5.17.0) to .\node_modules\@prisma\client in 31ms


Running seed command `node prisma/seed.js` ...
Start seeding ...
PrismaClientInitializationError:
Invalid `prisma.user.create()` invocation in
C:\Users\xxx\Workspace\javascript_rest-fastify\prisma\seed.js:56:36

  53 async function main() {
  54   console.log(`Start seeding ...`)
  55   for (const u of userData) {
→ 56     const user = await prisma.user.create(
Unable to require(`C:\Users\xxx\Workspace\javascript_rest-fastify\node_modules\.prisma\client\query_engine-windows.dll.node`).
The Prisma engines do not seem to be compatible with your system. Please refer to the documentation about Prisma's system requirements: https://pris.ly/d/system-requirements

Details: \\?\C:\Users\xxx\Workspace\javascript_rest-fastify\node_modules\.prisma\client\query_engine-windows.dll.node is not a valid Win32 application.
\\?\C:\Users\xxx\Workspace\javascript_rest-fastify\node_modules\.prisma\client\query_engine-windows.dll.node
    at _n.handleRequestError (C:\Users\xxx\Workspace\javascript_rest-fastify\node_modules\@prisma\client\runtime\library.js:121:8049)
    at _n.handleAndLogRequestError (C:\Users\xxx\Workspace\javascript_rest-fastify\node_modules\@prisma\client\runtime\library.js:121:7057)
    at _n.request (C:\Users\xxx\Workspace\javascript_rest-fastify\node_modules\@prisma\client\runtime\library.js:121:6741)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async l (C:\Users\xxx\Workspace\javascript_rest-fastify\node_modules\@prisma\client\runtime\library.js:130:9355)
    at async main (C:\Users\xxx\Workspace\javascript_rest-fastify\prisma\seed.js:56:18) {
  clientVersion: '5.17.0',
  errorCode: undefined
}

An error occurred while running the seed command:
Error: Command failed with exit code 1: node prisma/seed.js

```

```
npx prisma -v
Error: Unable to require(`C:\Users\germic\Workspace\javascript_rest-fastify\node_modules\@prisma\engines\query_engine-windows.dll.node`).
The Prisma engines do not seem to be compatible with your system. Please refer to the documentation about Prisma's system requirements: https://pris.ly/d/system-requirements

Details: \\?\C:\Users\germic\Workspace\javascript_rest-fastify\node_modules\@prisma\engines\query_engine-windows.dll.node is not a valid Win32 application.
\\?\C:\Users\germic\Workspace\javascript_rest-fastify\node_modules\@prisma\engines\query_engine-windows.dll.node
    at Jte (C:\Users\germic\Workspace\javascript_rest-fastify\node_modules\prisma\build\index.js:284:116)
    at i7e (C:\Users\germic\Workspace\javascript_rest-fastify\node_modules\prisma\build\index.js:284:269)
prisma                  : 5.17.0
@prisma/client          : 5.17.0
Computed binaryTarget   : windows
Operating System        : win32
Architecture            : arm64
Node.js                 : v20.16.0
Query Engine (Node-API) : E_CANNOT_RESOLVE_VERSION (at node_modules\@prisma\engines\query_engine-windows.dll.node)
Schema Engine           : schema-engine-cli 393aa359c9ad4a4bb28630fb5613f9c281cde053 (at node_modules\@prisma\engines\schema-engine-windows.exe)
Schema Wasm             : @prisma/prisma-schema-wasm 5.17.0-31.393aa359c9ad4a4bb28630fb5613f9c281cde053
Default Engines Hash    : 393aa359c9ad4a4bb28630fb5613f9c281cde053
Studio                  : 0.502.0
```

**Comment by RobertCZ** [comment] 2024-08-08 09:36
Above is MacBook Pro MS running free preview of Parallels (latest) running their supplied image of Windows 11 (with latest updates installed), I installed also some `VC_redist.x64.exe` for ARM64. Same result for Mac Studio (M1 Max) with similar Parallels/Windows 11 setup.

**Comment by jkomyno** [comment] 2024-12-30 15:52
>The problems happen only in MacOS/Arm64/Parallels/Windows11 

Hi, closing this as a duplicate of https://github.com/prisma/prisma/issues/15306

**Closed by jkomyno** 2024-12-30 15:52 UTC
Labels: bug/0-unknown, kind/bug, topic: windows, domain/client, topic: arm
