### ISSUE TITLE
Optional field's return type

### ISSUE THREAD

**Issue by bacpv1269** [prisma/prisma#20736] opened 2023-08-18 03:54 UTC
## Problem
I have a field in model: `field  String?`
In the find query such as `findFirst`, although `where` argument has `field: { not: null }` condition, the return type still includes null in this field.
## Suggested solution

In this case, the `field`'s return type only should be `string`

## Alternatives

Should we change the `CheckSelect` type :) ?
## Additional context

Prisma with MySQL  and Typescript

**Comment by SevInf** [comment] 2023-08-18 10:43
Hi @bacpv1269.
This issue seem to be duplicate of #20348. Since the other issue has more activity on it, I am going to close this one. If you have any further input, please, leave a comment on #20348. 

Thank you!

**Closed by SevInf** 2023-08-18 10:43 UTC
