### ISSUE TITLE
`pnpm dlx` or `pnpx` downloads prisma for every `pnpx generate`

### ISSUE THREAD

**Issue by wvhulle** [prisma/prisma#16169] opened 2022-11-07 17:56 UTC
### Bug description

Pnpm dlx or pnpx downloads prisma for every `pnpx generate`. It should only happen the first time, the prisma client is generated, but it happens every time.

### How to reproduce

To reproduce the bug,

1. install pnpm,
2. use the `alias pnpx='pnpm dlx'` or `pnpm dlx`
3. run `pnpx prisma generate` with internet connection
4. run `pnpx prisma generate` without internet connection

The process will hang. Doesn't hang with `npx`.

Reproduction: https://github.com/wvhulle/prisma-pnpm-bug

### Expected behavior

Generate without internet connection.

### Prisma information

```prisma
generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

model User {
 id String @id
}
```

### Environment & setup

- OS: Linux Mint 21 or Ubuntu 22.04
- Database: SQLite
- Node.js version:  16.17.1
- Pnpm: 7.14.2

### Prisma Version

```
prisma                  : 4.5.0
@prisma/client          : 4.5.0
Current platform        : debian-openssl-3.0.x
Query Engine (Node-API) : libquery-engine 0362da9eebca54d94c8ef5edd3b2e90af99ba452 (at ../.local/share/pnpm/store/v3/tmp/dlx-677829/node_modules/.pnpm/@prisma+engines@4.5.0/node_modules/@prisma/engines/libquery_engine-debian-openssl-3.0.x.so.node)
Migration Engine        : migration-engine-cli 0362da9eebca54d94c8ef5edd3b2e90af99ba452 (at ../.local/share/pnpm/store/v3/tmp/dlx-677829/node_modules/.pnpm/@prisma+engines@4.5.0/node_modules/@prisma/engines/migration-engine-debian-openssl-3.0.x)
Introspection Engine    : introspection-core 0362da9eebca54d94c8ef5edd3b2e90af99ba452 (at ../.local/share/pnpm/store/v3/tmp/dlx-677829/node_modules/.pnpm/@prisma+engines@4.5.0/node_modules/@prisma/engines/introspection-engine-debian-openssl-3.0.x)
Format Binary           : prisma-fmt 0362da9eebca54d94c8ef5edd3b2e90af99ba452 (at ../.local/share/pnpm/store/v3/tmp/dlx-677829/node_modules/.pnpm/@prisma+engines@4.5.0/node_modules/@prisma/engines/prisma-fmt-debian-openssl-3.0.x)
Format Wasm             : @prisma/prisma-fmt-wasm 4.5.0-43.0362da9eebca54d94c8ef5edd3b2e90af99ba452
Default Engines Hash    : 0362da9eebca54d94c8ef5edd3b2e90af99ba452
Studio                  : 0.476.0
```

**Comment by SevInf** [comment] 2022-11-08 09:52
Hi @wvhulle!
This is not an issue with `prisma`: `pnpm dlx` does not behave the same way `pnpmx` used to and always fetches a package, even if it is installed locally. If you want to run locally installed dependency, you should use `pnpm exec prisma generate` or just `pnpm prisma generate`. 
I am going to close this since this is the expected behaviour for `pnpm 7` and even if it was not, that would be `pnpm` issue, not `prisma`.

**Closed by SevInf** 2022-11-08 09:52 UTC
Labels: kind/bug

**Comment by wvhulle** [comment] 2022-11-08 10:06
Oh okay, thanks for giving the right command.

**Comment by janpio** [comment] 2022-11-08 19:06
That is so much cleaner and defined behavior than `npx` and Co... totally makes sense. :til:
