### ISSUE TITLE
Introspection fail with an empty DEFAULT in the schema

### ISSUE THREAD

**Issue by sircon** [prisma/prisma#3095] opened 2020-07-21 09:35 UTC
## Bug description

I'm maintaining an old product that uses a MariaDB 10.1.36 and was trying to use Prisma with it. Unfortunately, while running `npx prisma introspect` it returns a vague weird error.

After many trial and error attempts, I figure out the issue was with setting a column with a `DEFAULT ''`. By deleting all these references from the schema, it worked.

This is an old product with old database schema that I'm maintaining, and can't change the schema for it, so I had to make it work with what I have for now.

## How to reproduce

1. Create a MySQL database with this table:
```
CREATE TABLE `norm_brands` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(255) NOT NULL DEFAULT '',
  PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;
```
2. Run `npx prisma introspect`

## Expected behavior
It should create a prisma schema which would look something like this:
```
model norm_brands {
  id       Int    @default(autoincrement()) @id
  name     String @default("")
}
```

## Prisma information
```
Introspecting based on datasource defined in prisma/schema.prisma …
  IntrospectionEngine:rpc starting introspection engine with binary: /Users/**/**/node_modules/@prisma/cli/introspection-engine-darwin +0ms
  IntrospectionEngine:rpc SENDING RPC CALL {"id":1,"jsonrpc":"2.0","method":"introspect","params":[{"schema":"// This is your Prisma schema file,\n// learn more about it in the docs: https://pris.ly/d/prisma-schema\n\ndatasource db {\n  provider = \"mysql\"\n  url      = env(\"DATABASE_URL\")\n}\n\ngenerator client {\n  provider = \"prisma-client-js\"\n}\n"}]} +7ms
  IntrospectionEngine:stderr {"is_panic":true,"message":"[/rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7/src/libcore/str/mod.rs:1920:47] byte index 1 is out of bounds of ``","backtrace":"   0: backtrace::backtrace::trace\n   1: backtrace::capture::Backtrace::new\n   2: user_facing_errors::Error::new_in_panic_hook\n   3: user_facing_errors::panic_hook::set_panic_hook::{{closure}}\n   4: std::panicking::rust_panic_with_hook\n   5: _rust_begin_unwind\n   6: core::panicking::panic_fmt\n   7: core::str::slice_error_fail\n   8: core::str::traits::<impl core::slice::SliceIndex<str> for core::ops::range::Range<usize>>::index::{{closure}}\n   9: sql_schema_describer::mysql::unescape_and_unquote_default_string\n  10: <sql_schema_describer::mysql::SqlSchemaDescriber as sql_schema_describer::SqlSchemaDescriberBackend>::describe::__describe::{{closure}}\n  11: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll\n  12: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll\n  13: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll\n  14: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll\n  15: <futures_util::compat::compat03as01::Compat<Fut> as futures::future::Future>::poll\n  16: <futures::future::map::Map<A,F> as futures::future::Future>::poll\n  17: <futures::future::either::Either<A,B> as futures::future::Future>::poll\n  18: futures::future::chain::Chain<A,B,C>::poll\n  19: <futures::future::then::Then<A,B,F> as futures::future::Future>::poll\n  20: <futures::future::map::Map<A,F> as futures::future::Future>::poll\n  21: <futures::future::either::Either<A,B> as futures::future::Future>::poll\n  22: <futures::future::map::Map<A,F> as futures::future::Future>::poll\n  23: futures::task_impl::std::set\n  24: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll\n  25: tokio::runtime::enter::Enter::block_on\n  26: tokio::runtime::context::enter\n  27: tokio::runtime::handle::Handle::enter\n  28: introspection_engine::main\n  29: std::rt::lang_start::{{closure}}\n  30: std::rt::lang_start_internal\n  31: _main\n"} +0ms
 ERROR  Oops, an unexpected error occured!
[/rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7/src/libcore/str/mod.rs:1920:47] byte index 1 is out of bounds of 
```

## Environment & setup

- OS: `MacOs 10.15.5`
- Database: `10.1.36-MariaDB`
- Prisma version: `2.2.0`
- Node.js version: `v12.17.0`
- Introspection Engine : `introspection-core 45c4da4dd3ccd6a322796b228bdf937c7ce884e8 (at /Users/**/**/node_modules/@prisma/cli/introspection-engine-darwin)`

Thanks for the help,
Miguel

**Comment by divyenduz** [comment] 2020-07-29 10:32
I am unable to reproduce this with MariaDB `10.4.12`. Trying it out now with the version in the original report.

**Comment by divyenduz** [comment] 2020-07-29 11:00
I am able to reproduce this with MariaDB `10.1.36`, internal error report https://prisma-errors.netlify.app/report/9528

```
divyendusingh [prisma-3095]$ yarn prisma introspect
yarn run v1.22.4
$ /Users/divyendusingh/Documents/prisma/triage/prisma-3095/node_modules/.bin/prisma introspect

Introspecting based on datasource defined in schema.prisma …
[/rustc/5c1f21c3b82297671ad3ae1e8c942d2ca92e84f2/src/libcore/str/mod.rs:1920:47] byte index 1 is out of bounds of ``
We successfully received the error report
To help us even more, please create an issue at https://github.com/prisma/prisma/issues/new
mentioning the report id 9528.

Thanks a lot for your help! 🙏
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

We have seen an issue with the same error message before in https://github.com/prisma/prisma/issues/3126

**Comment by divyenduz** [comment] 2020-11-10 13:45
Unable to reproduce this with `2.11.0-dev.59`

Able to reproduce with older CLIs (tried `2.7.0` among others)

@sircon Can you please try it with the latest dev?

**Comment by do4gr** [comment] 2020-11-10 16:20
We recently implemented a fix for default value parsing on MySQL variants. Since then we cannot reproduce this anymore. I am closing this therefore.

**Closed by do4gr** 2020-11-10 16:20 UTC
Labels: bug/2-confirmed, kind/bug, status/needs-action, team/engines, topic: introspection, topic: mariadb
