### ISSUE TITLE
Break Generated d.ts file into multiple files.

### ISSUE THREAD

**Issue by ericwooley** [prisma/prisma#8559] opened 2021-08-03 18:21 UTC
## Problem

We have a large and complex database. Our `node_modules/.prisma/client/index.d.ts` is over 65,000 lines. Which makes our editor experience really hard.

## Suggested solution

According to [this issue](https://github.com/microsoft/TypeScript/issues/8521), the best move is to split the file into smaller d.ts files.

## Alternatives

I can't think of any better alternatives.

## Additional context

We generate our prisma.schema file using the prisma cli instead of writing the schema file manually. Not sure if that would affect anything here though.

**Comment by ericwooley** [comment] 2021-08-03 20:31
I'd be happy to contribute a PR to fix this, but I'm struggling to find the actual code that generates the d.ts files. Looks like it's a process fork to something based on an environment variable in  https://github.com/prisma/prisma/blob/8ca013393ff6778d8996afe65202a524278d347d/packages/generator-helper/src/GeneratorProcess.ts#L49

If anyone can't point me in the right direction to where the generation code is really happening, this issue probably wouldn't be that hard.

**Comment by pantharshit00** [comment] 2021-08-08 12:50
Hi,

Thanks for reporting this! It has already been reported before, so I am going to close this as a duplicate of https://github.com/prisma/prisma/issues/4807


Regarding contributing a fix, it is not that straight forward since Prisma client uses our generator architecture which is not very well documented. You will still read about it here though: https://github.com/prisma/specs/tree/master/generators

The Prisma Client is just another generator which gets invoked: https://github.com/prisma/prisma/blob/main/packages/client/src/generation/generator.ts

Most of the code fixtures are here: https://github.com/prisma/prisma/tree/512ddab74d9a67d234e1d20450738af88d67ec69/packages/client/src/generation/TSClient

**Closed by pantharshit00** 2021-08-08 12:50 UTC
