### ISSUE TITLE
`npx prisma generate` hangs after upgrading `@prisma/client` from 3.0.2

### ISSUE THREAD

**Issue by Download** [prisma/prisma#10291] opened 2021-11-16 13:09 UTC
### Bug description

Running `npx prisma generate` from `postinstall` hangs on 3.4.2. Used to work fine with 3.0.2:

```sh
> npx prisma generate

Environment variables loaded from .env
Prisma schema loaded from prisma/schema.prisma
^C
``` 

I had to CTRL+C out of it.

I upgraded `@prisma/client` from 3.0.2 to latest (3.4.2) and after that upgrade, the generate command just hangs.

Using:

```json
{
  "dependencies": {
    "@prisma/client": "^3.4.2",
    "graphql": "^15.5.3",
    "nexus": "^1.1.0",
    "nexus-prisma": "^0.34.0"
  }
}
```
(stripped dependencies I didn't think were relevant)

### How to reproduce

* Upgrade prisma from 3.0.2 to 3.4.2
* Run `npx prisma generate`
* Observe: it just hangs

### Expected behavior

Expect it to complete successfully like it used to do before

In the changeset I made for my project are only 2 files:
* package.json
* package-lock.json

The diff for package.json shows only the @prisma/client version number as changed.

### Prisma information

generator client {
  provider = "prisma-client-js"
}

generator nexusPrisma {
  provider = "nexus-prisma"
}

datasource db {
  provider = "mysql"
  url      = env("DATABASE_URL")
}

### Environment & setup

- OS: MacOS
- Database: MySQL
- Node.js version: v16.13.0

### Prisma Version

```
prisma                  : 3.0.2
@prisma/client          : 3.4.2
Current platform        : darwin-arm64
Query Engine (Node-API) : libquery-engine 2452cc6313d52b8b9a96999ac0e974d0aedf88db (at node_modules/@prisma/engines/libquery_engine-darwin-arm64.dylib.node)
Migration Engine        : migration-engine-cli 2452cc6313d52b8b9a96999ac0e974d0aedf88db (at node_modules/@prisma/engines/migration-engine-darwin-arm64)
Introspection Engine    : introspection-core 2452cc6313d52b8b9a96999ac0e974d0aedf88db (at node_modules/@prisma/engines/introspection-engine-darwin-arm64)
Format Binary           : prisma-fmt 2452cc6313d52b8b9a96999ac0e974d0aedf88db (at node_modules/@prisma/engines/prisma-fmt-darwin-arm64)
Default Engines Hash    : 2452cc6313d52b8b9a96999ac0e974d0aedf88db
Studio                  : 0.423.0
```

**Comment by Download** [comment] 2021-11-16 13:46
Downgraded to 3.3.0: same issue.
Downgraded to 3.2.0: same issue.
Downgraded to 3.1.0: same issue.
Downgraded to 3.0.2: FIXED

Upgraded Prisma and Prisma Client to latest with

```
npm uninstall --save @prisma/client && npm uninstall --save-dev prisma && npm install --save @prisma/client && npm install --save-dev prisma
```

LOL, you guys released prisma client 3.5.0 while I was testing this!
Unfortunately, same issue with latest of both prisma and prisma client:

```
prisma                  : 3.5.0
@prisma/client          : 3.5.0
Current platform        : darwin-arm64
Query Engine (Node-API) : libquery-engine 78a5df6def6943431f4c022e1428dbc3e833cf8e (at node_modules/@prisma/engines/libquery_engine-darwin-arm64.dylib.node)
Migration Engine        : migration-engine-cli 78a5df6def6943431f4c022e1428dbc3e833cf8e (at node_modules/@prisma/engines/migration-engine-darwin-arm64)
Introspection Engine    : introspection-core 78a5df6def6943431f4c022e1428dbc3e833cf8e (at node_modules/@prisma/engines/introspection-engine-darwin-arm64)
Format Binary           : prisma-fmt 78a5df6def6943431f4c022e1428dbc3e833cf8e (at node_modules/@prisma/engines/prisma-fmt-darwin-arm64)
Default Engines Hash    : 78a5df6def6943431f4c022e1428dbc3e833cf8e
Studio                  : 0.439.0
```

**Comment by Download** [comment] 2021-11-16 13:48
Also tried upgrading both prisma and prisma-client to 3.4.0 i.s.o 3.5.0 but still same issue.

`npx prisma generate` just hangs.

**Comment by Download** [comment] 2021-11-18 08:25
@aqrln 
Thanks for picking this up 👍 
Can you tell me what info is needed?

**Comment by aqrln** [comment] 2021-11-18 10:06
Hi @Download and thanks for your report! I don't think I can reproduce it with latest Prisma, but maybe I'm missing something in my setup. Could you please prepare a minimal reproduction as a separate repo?

```
❯ npx prisma generate
Environment variables loaded from .env
Prisma schema loaded from prisma/schema.prisma
You can now start using Nexus Prisma in your code. Reference: https://pris.ly/d/nexus-prisma

✔ Generated Prisma Client (3.5.0) to ./node_modules/@prisma/client in 224ms

✔ Generated Nexus Prisma to ./node_modules/nexus-prisma/dist-cjs/runtime in 6ms
You can now start using Prisma Client in your code. Reference: https://pris.ly/d/client
```

```
❯ npx prisma --version
Environment variables loaded from .env
prisma                  : 3.5.0
@prisma/client          : 3.5.0
Current platform        : darwin-arm64
Query Engine (Node-API) : libquery-engine 78a5df6def6943431f4c022e1428dbc3e833cf8e (at node_modules/@prisma/engines/libquery_engine-darwin-arm64.dylib.node)
Migration Engine        : migration-engine-cli 78a5df6def6943431f4c022e1428dbc3e833cf8e (at node_modules/@prisma/engines/migration-engine-darwin-arm64)
Introspection Engine    : introspection-core 78a5df6def6943431f4c022e1428dbc3e833cf8e (at node_modules/@prisma/engines/introspection-engine-darwin-arm64)
Format Binary           : prisma-fmt 78a5df6def6943431f4c022e1428dbc3e833cf8e (at node_modules/@prisma/engines/prisma-fmt-darwin-arm64)
Default Engines Hash    : 78a5df6def6943431f4c022e1428dbc3e833cf8e
Studio                  : 0.439.0
```

**Comment by Download** [comment] 2021-11-18 10:27
@aqrln 
It's a lot of work to strip everything from our project to make it minimal but I understand why you need this if you cannot reproduce.

We used introspection of an existing database to generate our schema, then made some changes by hand. So maybe we are using some construct in our schema that triggers this issue. 

Can you tell me what project you are using to repro? Is it a public project that you can share? Then maybe I can compare your schema with ours and see if I can introduce the problem in your project?

**Comment by aqrln** [comment] 2021-11-18 10:43
@Download it's basically just an empty project template with your deps and a generator block for Nexus in the schema: https://github.com/aqrln/tmp-prisma-10291. Not much I can reconstruct without additional context.

**Comment by Download** [comment] 2021-11-18 12:12
Yeah I understand. I will see if I can add some model defs to the schema that trigger the bug. Thanks for your quick responses, much appreciated!

**Comment by janpio** [comment] 2021-11-19 17:52
I think we have a related issue about a similar problem, that is also solved by downgrading to 3.0.2: https://github.com/prisma/prisma/issues/9553

**Comment by aldeed** [comment] 2021-12-03 18:44
For me it was hanging in the same way, and it turned out to be because `env("POSTGRES_URL")` was in the `.prisma` file but that env was not set. Don't know why there isn't an error message. Maybe in 3.1+ error handling changed and these are errors that get lost?

**Comment by janpio** [comment] 2021-12-03 19:06
Missing an actual var should usually be output as an error in most commands, but `generate` does not care about that. So if this happened for another command @aldeed, this might indeed be a problem. For `prisma generate`, not. (You could be generating on a different system than where you run the generated Client in the end where the env var would be set)

**Comment by aldeed** [comment] 2021-12-03 21:41
@janpio Interesting. Adding the missing `.env` file is clearly what solved it for me because I did nothing else, but now that it has worked once, it still works even if I remove that `.env` file. This is on M1 mac, which it looks like the original issue was too, so my first thought was something related to that. (It causes a lot of subtle bugs.) Could be something deeper like that and altering the filesystem just happened to resolve it. 🤷🏻‍♂️

**Comment by bkrausz** [comment] 2022-04-12 01:14
I had a similar issue where `prisma generate` was hanging, but only on our Render machines despite attempting identical setups locally. I added a `DEBUG=*` and got this:

```
Apr 11 05:30:13 PM  2022-04-12T00:30:13.212Z prisma:GeneratorProcess /opt/render/project/src/node_modules/.pnpm/floggy@0.3.2/node_modules/floggy/dist-cjs/chalk.js:11
Apr 11 05:30:13 PM  2022-04-12T00:30:13.212Z prisma:GeneratorProcess exports.chalk = new chalk_1.default.Instance();
Apr 11 05:30:13 PM  2022-04-12T00:30:13.212Z prisma:GeneratorProcess                 ^
Apr 11 05:30:13 PM  2022-04-12T00:30:13.212Z prisma:GeneratorProcess TypeError: chalk_1.default.Instance is not a constructor
Apr 11 05:30:13 PM  2022-04-12T00:30:13.212Z prisma:GeneratorProcess     at Object.<anonymous> (/opt/render/project/src/node_modules/.pnpm/floggy@0.3.2/node_modules/floggy/dist-cjs/chalk.js:11:17)
Apr 11 05:30:13 PM  2022-04-12T00:30:13.212Z prisma:GeneratorProcess     at Module._compile (node:internal/modules/cjs/loader:1103:14)
Apr 11 05:30:13 PM  2022-04-12T00:30:13.212Z prisma:GeneratorProcess     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1157:10)
Apr 11 05:30:13 PM  2022-04-12T00:30:13.213Z prisma:GeneratorProcess     at Module.load (node:internal/modules/cjs/loader:981:32)
Apr 11 05:30:13 PM  2022-04-12T00:30:13.213Z prisma:GeneratorProcess     at Function.Module._load (node:internal/modules/cjs/loader:822:12)
Apr 11 05:30:13 PM  2022-04-12T00:30:13.213Z prisma:GeneratorProcess     at Module.require (node:internal/modules/cjs/loader:1005:19)
Apr 11 05:30:13 PM  2022-04-12T00:30:13.213Z prisma:GeneratorProcess     at require (node:internal/modules/cjs/helpers:102:18)
Apr 11 05:30:13 PM  2022-04-12T00:30:13.213Z prisma:GeneratorProcess     at Object.<anonymous> (/opt/render/project/src/node_modules/.pnpm/floggy@0.3.2/node_modules/floggy/dist-cjs/filter.js:6:17)
Apr 11 05:30:13 PM  2022-04-12T00:30:13.213Z prisma:GeneratorProcess     at Module._compile (node:internal/modules/cjs/loader:1103:14)
Apr 11 05:30:13 PM  2022-04-12T00:30:13.213Z prisma:GeneratorProcess     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1157:10)
Apr 11 05:30:13 PM  2022-04-12T00:30:13.240Z prisma:GeneratorProcess 2022-04-12T00:30:13.239Z prisma:client:generator requiredEngine: libqueryEngine
```

It turns out `nexus-prisma` includes `floppy`, which doesn't declare `chalk` despite importing it.

May not be the same issue as seen here, but the interesting part is that a pretty straightforward `TypeError` caused `generate` to hang. If fixed I bet it'd at least turn the hangs into actionable errors.

**Comment by bkrausz** [comment] 2022-04-12 01:16
For anyone using `pnpm` and looking for a workaround, you can fix the missing dep via `.pnpmfile.cjs':

```js
module.exports = {
  hooks: {
    readPackage: (pkg) => {
      if (pkg.name === 'floggy') {
        pkg.dependencies['chalk'] = '^4.1.2';
      }
      return pkg;
    }
  }
};
```

**Comment by janpio** [comment] 2022-04-13 17:28
(I forwarded your comment to the people that work on `nexus-prisma` - maybe it can be fixed on their side and avoid more people potentially running into this. Optimally also open an issue at https://github.com/prisma/nexus-prisma/ (including the nice workaround))

**Comment by CrabBucket** [comment] 2022-09-09 18:55
This might be adjacent but I ran into the same issue but it was because I hadn't installed @prisma/client and only installed the prisma CLI.

Followed this https://www.prisma.io/docs/getting-started/quickstart after I decided to refactor out of GraphQL on my Next website (to be honest I don't understand it well enough to know how to properly use middleware to secure the GrapQL endpoints).

**Closed** 2023-05-26 14:50 UTC
Labels: bug/0-unknown, kind/regression, topic: prisma generate, tech/typescript, team/client
