### ISSUE TITLE
Using full-text search feature returns syntax error, when the search term having more than 1 word.

### ISSUE THREAD

**Issue by analoguezone** [prisma/prisma#10319] opened 2021-11-17 11:51 UTC
### Bug description

Full-text search feature returns syntax error when the search term having more than 1 word!

<img width="1396" alt="Screenshot 2021-11-17 at 11 36 13" src="https://user-images.githubusercontent.com/17030643/142194780-ea527094-809f-4661-9e9c-01e6fcc30d1f.png">

### How to reproduce

Using the search argument at where or orderBy _relevance with search terms having more than 1 words. 

### Prisma information

<img width="508" alt="Screenshot 2021-11-17 at 11 44 05" src="https://user-images.githubusercontent.com/17030643/142194725-e89a880f-c1d4-4af4-9272-b4599b339a37.png">
<img width="744" alt="Screenshot 2021-11-17 at 11 44 56" src="https://user-images.githubusercontent.com/17030643/142194755-d9336116-1e2c-4e4e-bef8-f1809e77f911.png">

Same error occurs when the search is at the where

<img width="510" alt="Screenshot 2021-11-17 at 12 00 00" src="https://user-images.githubusercontent.com/17030643/142194899-d20de8f8-f3f7-450e-b963-fda5bd510fd7.png">

### Environment & setup

- OS: Mac OS
- Database: PostgreSQL
- Node.js version: v14.15.4

### Prisma Version

prisma                  : 3.5.0
@prisma/client          : 3.5.0
Current platform        : darwin
Query Engine (Node-API) : libquery-engine 78a5df6def6943431f4c022e1428dbc3e833cf8e (at node_modules/@prisma/engines/libquery_engine-darwin.dylib.node)
Migration Engine        : migration-engine-cli 78a5df6def6943431f4c022e1428dbc3e833cf8e (at node_modules/@prisma/engines/migration-engine-darwin)
Introspection Engine    : introspection-core 78a5df6def6943431f4c022e1428dbc3e833cf8e (at node_modules/@prisma/engines/introspection-engine-darwin)
Format Binary           : prisma-fmt 78a5df6def6943431f4c022e1428dbc3e833cf8e (at node_modules/@prisma/engines/prisma-fmt-darwin)
Default Engines Hash    : 78a5df6def6943431f4c022e1428dbc3e833cf8e
Studio                  : 0.439.0
Preview Features        : extendedIndexes, fullTextSearch

**Comment by Crymzix** [comment] 2021-12-13 20:33
I, too, am getting this error. This makes using `search` almost unusable for most use cases.

**Comment by pantharshit00** [comment] 2021-12-14 12:22
Hi,

Thanks for reporting this! It has already been reported before, so I am going to close this as a duplicate of https://github.com/prisma/prisma/issues/8939#issuecomment-909388537


Please have a look at the workaround there.

**Closed by pantharshit00** 2021-12-14 12:22 UTC
Labels: bug/0-needs-info, kind/bug, team/client, topic: client api, topic: full-text search
