### ISSUE TITLE
Postinstall hook fails with custom location for schema.prisma

### ISSUE THREAD

**Issue by flybayer** [prisma/prisma#2944] opened 2020-07-07 10:42 UTC
## Bug description

When you have `schema.prisma` at a non-default location, like `db/schema.prisma`, then running `npm install` results in a scary error message that confuses users.

```
> @prisma/client@2.1.3 postinstall /private/tmp/a1/node_modules/@prisma/client
> node scripts/postinstall.js

Error: Either provide --schema or make sure that you are in a folder with a schema.prisma file.
```

## How to reproduce

1. Move `schema.prisma` to non-default location
2. Delete `node_modules`
3. Run `npm i`

## Expected behavior

I'm not sure the best solution here, but at the very least this error message should be downgraded to info or warning and remove the terminal colors (currently bright red).

In Blitz we automatically generate prisma client as part of `blitz build` or `blitz start`, so usually Blitz users never have to think about this.

## Environment & setup

```
@prisma/cli          : 2.1.3
Current platform     : darwin
Node: 12.6.3
```

**Comment by Jolg42** [comment] 2020-07-07 13:04
Hi @flybayer!

So what happens is that the `postinstall` hooks gets triggered after `npm install` and calls `prisma generate` and displays the output from it.

I agree that for someone new this can look like a "real error"
So what could be done is maybe something like this:

```
> @prisma/client postinstall /private/tmp/a1/node_modules/@prisma/client
> node scripts/postinstall.js

Error: Either provide --schema or make sure that you are in a folder with a schema.prisma file.

We couldn't find your schema.prisma, you will need to run `prisma generate --schema=./path/to/your/schema.prisma` to generate your Prisma Client(s).
```

**Comment by flybayer** [comment] 2020-07-07 14:57
@Jolg42 yes, that extra line is definitely helpful, but the main problem of confusion remains because of that error message.

The core problem, which I should have clarified originally, is that people see this error and think the entire `npm install` failed.

**Comment by janpio** [comment] 2020-07-07 17:53
Can we catch the error here @Jolg42 and output an alternative text in case of _any_ error? The user can not act on the error reason anyway, so maybe something like `Info: Prisma Client could not be generated during installation because of an error. Run 'npx prisma generate' again to see the output.` could solve the problem for all cases.

**Comment by pantharshit00** [comment] 2020-07-07 22:15
I am marking this as an improvement for now as behavior is confirmed but it is not breaking.

**Comment by flybayer** [comment] 2020-07-08 01:56
I think the prisma postinstall hook fails (not sure), but `npm install` succeeds regardless.

I think it would be good to include something about the custom schema location in that message.

**Comment by Jolg42** [comment] 2020-07-16 13:36
Ok so maybe a more explicit version would help:

```
> @prisma/client postinstall /private/tmp/a1/node_modules/@prisma/client
> node scripts/postinstall.js

Error: Either provide --schema or make sure that you are in a folder with a schema.prisma file.

Warning: The postinstall script automatically ran `prisma generate` and did not find your `prisma/schema.prisma`.
If you do not have Prisma Schema file yet you can ignore this message.
If you have a Prisma Schema file in a custom path you will need to run `prisma generate --schema=./path/to/your/schema.prisma` to generate your Prisma Client(s).
```

**Comment by flybayer** [comment] 2020-07-16 14:19
Yes, that helps a bit, but the confusion remains because people will see that red error message and think the entire npm install failed. 

Most folks won't read on to actually see what the warning message says.

If you remove that error line, then I think it's perfect:

```
> @prisma/client postinstall /private/tmp/a1/node_modules/@prisma/client
> node scripts/postinstall.js

Warning: The postinstall script automatically ran `prisma generate` and did not find your `prisma/schema.prisma`.
If you have a Prisma Schema file in a custom path you will need to run `prisma generate --schema=./path/to/your/schema.prisma` to generate your Prisma Client(s).
If you do not have a Prisma Schema file yet, you can ignore this message.
```

**Comment by Jolg42** [comment] 2020-07-16 14:41
So I don't think we should do that because the error could be a real error happening because of a broken `prisma.schema` file.

What you could do is to set the environment variable `SKIP_GENERATE=1` and `prisma generate` will be skipped during postinstall.

**Comment by flybayer** [comment] 2020-07-17 02:39
If the problem is a broken schema file, shouldn't the error say that the schema file is broken instead of "_can't find the schema file_"?

**Closed** 2020-07-20 15:49 UTC
Labels: kind/improvement, team/typescript, topic: cli, topic: dx

**Comment by timsuchanek** [comment] 2020-07-20 15:52
Thanks for reporting @flybayer!
It for sure makes sense to not error in the postinstall script, but only when executing `prisma generate` directly.

For all the cases that a schema could not be found, we now have this warning:
![image](https://user-images.githubusercontent.com/1094804/87958235-91102d00-cab1-11ea-954d-dcf8a97534b0.png)

If the schema was invalid or any other error caused the generation to fail, we have this info:
![image](https://user-images.githubusercontent.com/1094804/87958301-a6855700-cab1-11ea-902d-cdd9a7f4d229.png)
