### ISSUE TITLE
Postgres 11 date type not supported by introspection

### ISSUE THREAD

**Issue by redaikidoka** [prisma/prisma#4435] opened 2019-04-23 14:56 UTC
**Describe the bug**
I have a psql 11 database; used introspection to generate the prisma datamodel.
When I deploy the model, Date types in the model cause an error in the prisma server

**To Reproduce**
1. Create a psql table with a Date datatype (not DateTime!):
```
create table adm_framework
(
	id_adm_framework serial not null
			primary key,
	framework_version integer,
	effective_date date,
	end_date date,
	tags text,
	framework_name varchar(30),
	id_adm_app integer,
	s_create timestamp(6) default now(),
	s_create_user integer,
	s_update_user integer,
	s_update timestamp(6) default now(),
	is_active boolean
);
```

2. create a new prisma introspection with ```prisma init```
3. ```prisma deploy``` and the server error will appear
```java.lang.RuntimeException: Encountered unknown SQL type date with column effective\_date. IntrospectedColumn(effective\_date,date,null,true)```

**Expected behavior**
psql Date types should be supported by the DateTime declaration in prisma.

**Versions (please complete the following information):**
 - Connector: Postgres
 - Prisma server version: 1.31.0
 - `prisma` CLI:  prisma/1.31.1 (darwin-x64) node-v10.15.3
 - OS: OS X High Sierra

**Additional context**
Be awesome if this got fixed! :) Or if I'm somehow doing something dumb.

**Comment by redaikidoka** [comment] 2019-04-23 16:59
In addition, if any tables in the database prisma is connecting to are of these types, the server crashers:

- date
- time
- double precision
- float
- float4
- float8

Is this prisma not supporting psql 11 well? Is it a driver issue?
Should I downgrade to psql 9.6?

**Comment by pantharshit00** [comment] 2019-04-25 17:32
It is happened due to the active-passive unification we did(same connector for introspected dbs). The current workaround is to downgrade to a version smaller than 1.28.3.

Closing as a duplicate of https://github.com/prisma/prisma/issues/4190. 

It will be awesome if you can comment your list of types in that issue.

**Closed** 2019-04-25 17:32 UTC
