### ISSUE TITLE
`driverAdapters` early access + Cloudflare Hyperdrive: "Release called on client which has already been released to the pool" 

### ISSUE THREAD

**Issue by vladinator1000** [prisma/prisma#23367] opened 2024-03-05 18:11 UTC
### Bug description

Hi y'all, I'm running the driverAdapters early access.
I have a Cloudflare Worker that does multiple database calls per request, connected to a Postgres database [behind Cloudflare Hyperdrive](https://developers.cloudflare.com/hyperdrive/).

It seems like after the first request finishes, the connection is closed and the other database requests fail with an exception. Here are my logs:

```
"exceptions": [
    {
      "name": "Error",
      "message": "Release called on client which has already been released to the pool.",
      "timestamp": 1709660812613
    },
    {
      "name": "Error",
      "message": "The script will never generate a response.",
      "timestamp": 1709660812613
    }
  ],
```

### How to reproduce

1. Follow the Hyperdrive getting started tutorial https://developers.cloudflare.com/hyperdrive/get-started/
2. Follow the Prisma + Cloudflare driverAdapters early access pg instructions
```ts
// e.g. src/index.js
import { PrismaClient } from '@prisma/client'
import { PrismaPg } from '@prisma/adapter-pg'
import { Pool } from 'pg'

export default {
  async fetch(request, env, ctx) {
    const pool = new Pool({ connectionString:  env.HYPERDRIVE.connectionString })
    const adapter = new PrismaPg(pool)
    const prisma = new PrismaClient({ adapter })

    const promises = [prisma.user.findMany(), prisma.user.findFirst(), prisma.user.findMany()] // multiple requests here
    const results = await Promise.all(promises)
    const result = JSON.stringify(users)
    return new Response(result);
  }
}
```

3. Make multiple database requests in one worker call
4. Deploy your worker in production
5. Go to your worker settings and start streaming logs
6. Open the worker url and observe errors in log stream

### Expected behavior

I can run multiple driverAdapter database requests using Cloudflare workers Hyperdrive in 1 go.

### Environment & setup

- OS: WSL
- Database: Postgres
- Node.js v21

### Versions

```
Prisma: v5.11.0-dev.5
Wrangler: v3.30.1
```

**Comment by Jolg42** [comment] 2024-03-06 13:40
Internal note: we have a test for Hyperdrive since last week here https://github.com/prisma/ecosystem-tests/pull/4610

**Comment by vladinator1000** [comment] 2024-03-06 13:55
@Jolg42 let me know if you want me to test something on my setup.I found this bug on my production site. It's using Hyperdrive going to a DigitalOcean database.

It fires off multiple parallel database queries that finish at different times, but the bug only happened after I deployed it to Cloudflare, locally everything worked fine.

**Comment by Jolg42** [comment] 2024-03-06 16:51
@vladinator1000 I could not reproduce, though here are some thoughts.

`The script will never generate a response.` error is from Cloudflare Worker, because of the previous error from `pg`.

@SevInf found the error message `Release called on client which has already been released to the pool.` in `pg` code in `pg-pool` https://github.com/brianc/node-postgres/blob/b4bfd63f6337018b312bf5a9a70887660954cbfa/packages/pg-pool/index.js#L27
Which would be triggered by a release, but given your queries `const promises = [prisma.user.findMany(), prisma.user.findFirst(), prisma.user.findMany()]`, no implicit transaction (created by Prisma) is expected so `release()` must be called from `pg` internals. (For context we call `release()` in the adapter after a commit or rollback https://github.com/prisma/prisma/blob/4aee1423da37c3974515740950c45effed8f8b2b/packages/adapter-pg/src/pg.ts#L113-L126)

`Pool` is what we require for the `pg` adapter (`Client` is not an option here because of how transactions needs to be handled.)


So now, could you try changing one line in your code? and add `max: 1` (the default is 10)
```diff
-  const pool = new Pool({ connectionString:  env.HYPERDRIVE.connectionString })
+ const client = new Pool({ connectionString: env.HYPERDRIVE.connectionString, max: 1 }) 
```

Because with Hyperdrive, there is no need of a connection pool, it's already managed by Hyperdrive.

----

There are other options, that could be interesting to try later, if this doesn't improve things, like `allowExitOnIdle: true`.

See https://node-postgres.com/apis/pool
```ts
type Config = {
  // all valid client config options are also valid here
  // in addition here are the pool specific configuration parameters:
 
  // number of milliseconds to wait before timing out when connecting a new client
  // by default this is 0 which means no timeout
  connectionTimeoutMillis?: number
 
  // number of milliseconds a client must sit idle in the pool and not be checked out
  // before it is disconnected from the backend and discarded
  // default is 10000 (10 seconds) - set to 0 to disable auto-disconnection of idle clients
  idleTimeoutMillis?: number
 
  // maximum number of clients the pool should contain
  // by default this is set to 10.
  max?: number
 
  // Default behavior is the pool will keep clients open & connected to the backend
  // until idleTimeoutMillis expire for each client and node will maintain a ref
  // to the socket on the client, keeping the event loop alive until all clients are closed
  // after being idle or the pool is manually shutdown with `pool.end()`.
  //
  // Setting `allowExitOnIdle: true` in the config will allow the node event loop to exit
  // as soon as all clients in the pool are idle, even if their socket is still open
  // to the postgres server.  This can be handy in scripts & tests
  // where you don't want to wait for your clients to go idle before your process exits.
  allowExitOnIdle?: boolean
}
```

**Comment by Jolg42** [comment] 2024-03-12 09:24
@vladinator1000 Did you have a chance to try this since? Because I could not reproduce on my side, I'm curious to know if it helped you or not 👀

**Comment by vladinator1000** [comment] 2024-03-12 14:03
@Jolg42 just tried it, adding `max: 1` to the pool options worked! 🥳

**Comment by janpio** [comment] 2024-03-12 14:09
Let's keep the issue open as we want to fully understand _why_ this happens.

**Comment by Jolg42** [comment] 2024-05-14 12:11
I really could not reproduce, I tried with Hyperdrive caching default and also disabled by sending a lot of queries with autocannon.
<img width="1346" alt="Screenshot 2024-05-14 at 11 47 37" src="https://github.com/prisma/prisma/assets/1328733/ffae86d0-6502-4140-838f-ca61b63bbfdf">
<img width="705" alt="Screenshot 2024-05-14 at 11 47 10" src="https://github.com/prisma/prisma/assets/1328733/9645227c-fb10-4bec-9af3-203ded6efc3e">
<img width="719" alt="Screenshot 2024-05-14 at 11 47 05" src="https://github.com/prisma/prisma/assets/1328733/5824e971-e66e-4126-b879-fd07c0613010">
But all requests were successful.

If this happens again to you, please let us know what's your Hyperdrive settings, and the best would be to have a minimal reproduction repository.

If this happens to someone else: please open a new issue 🙏🏼 

Here is my attempt to reproduce as a repo: https://github.com/Jolg42/prisma-repro-23367

**Comment by Jolg42** [comment] 2024-05-21 08:47
@vladinator1000 You previously mentioned that adding `max: 1` to the pool options worked but then got stuck on https://github.com/prisma/prisma/issues/23457 which got resolved with `5.11.0`.

My question now is: is everything working for you?

We want to know if you can still reproduce this issue with the latest version of Prisma (without `max: 1`)?
If so, what are your settings on Hyperdrive, and if you can find out how to get to a minimal reproduction (see my previous message for a minimal reproduction repo, where I could not reproduce).

Let us know if that's something you could try on your side or if we should close this issue instead.

**Closed** 2024-05-21 13:48 UTC
Labels: bug/0-unknown, kind/bug, team/client, topic: Cloudflare Workers, topic: driverAdapters, topic: Cloudflare Hyperdrive, topic: @prisma/adapter-pg, topic: edge functions

**Comment by flobamediaacc** [comment] 2024-10-22 15:21
Hey, we had the same problem. Unfortunately, Max connections didn't help us. I noticed that the Cloudflare docs say that you should use the pooled connection with Neon. Neon itself doesn't say anything about this. Maybe it could have something to do with that? Perhaps the problem occurs with pooled connections strings in Hyperdrive?

Another possibility is the CPU limits for Cloudflare Workers. If you set them low, could that also lead to the errors?

**Comment by hyusetiawan** [comment] 2025-01-05 23:30
@Jolg42 I am trying to replicate the this prisma schema: https://github.com/prisma/ecosystem-tests/blob/dev/driver-adapters-wasm/pg-cf-hyperdrive/prisma/schema.prisma

but I am not sure what to put for the environment variables values.

first,

`error: Error validating datasource `db`: You must provide a nonempty URL. The environment variable `INVALID_ENV_VAR` resolved to an empty string.
  -->  prisma/schema.prisma:14
   |
13 |   // fake url to ensure the driver adapter is used
14 |   url       = env("INVALID_ENV_VAR")
   |`
   
 second, what to put for the DATABASE_URL? It cannot be empty, but then we should be using the HYPERDRIVE connection string no? Or should we just put the localhost connection here?
