### ISSUE TITLE
Error parsing MySQL URLs

### ISSUE THREAD

**Issue by jrwaine** [prisma/prisma#3921] opened 2020-10-14 15:52 UTC
## Bug description

The program does not parse correctly MySQL URL's when reserved characters are used (in password, for example).

When using a URL such as `mysql://root:password_with_#@localhost:3306/mydb` it outputs.

```bash
Introspecting based on datasource defined in prisma/schema.prisma …
Error: Error parsing connection string: invalid port number in `mysql://root:password_with_#@localhost:3306/mydb`)
```

## How to reproduce

1. Create a user with a password with [MySQL reserved characters](https://dev.mysql.com/doc/connector-j/8.0/en/connector-j-reference-jdbc-url-format.html) (I only tested with #).
2. Run `npx prisma introspect` with a database URL for this user.

It should output something as

```bash
Introspecting based on datasource defined in prisma/schema.prisma …
Error: Error parsing connection string: invalid port number in `mysql://root:password-with-#@localhost:3306/mydb`)
```

I tried escaping the character with %, as specified by MySQL, and using quotation marks, but the error continued.

## Expected behavior

The URL should be parsed correctly and the command run with success.

## Prisma information

File `schema.prisma`

```prisma
generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "mysql"
  url      = env("DATABASE_URL")
}
```

## Environment & setup

- OS: Fedora 32 
- Database: MySQL 
- Node.js version: v12.18.3 
- Prisma version: 2.8.1

**Comment by tomhoule** [comment] 2020-10-15 07:06
The database URLs on postgres and MySQL are standard URLs, which means [some characters need to be percent-encoded](https://dev.mysql.com/doc/connector-j/8.0/en/connector-j-reference-jdbc-url-format.html) in the password, host and other places.

Prisma could do a better job of reporting the error and pointing to a solution, I'll create an issue and link it here. Thanks for reporting!

**Comment by tomhoule** [comment] 2020-10-15 13:28
Hi! Thanks for reporting this. I cannot reproduce the error with a percent-encoded password. See https://github.com/prisma/quaint/pull/204/files#diff-5a761617dcb1c0032d5678fe31bbb1bdd126596bcfac1938800ee43a58b425aaR312 for an example that works.

The error message could be much better, however, here's an issue I just created to work on improving this: https://github.com/prisma/prisma-engines/issues/1241

**Comment by pantharshit00** [comment] 2021-05-04 16:30
Since https://github.com/prisma/prisma-engines/issues/1241 is addressed I am going to close this

**Closed by pantharshit00** 2021-05-04 16:30 UTC
Labels: bug/0-needs-info, kind/bug, status/needs-action, team/migrations, topic: connection-string
