### ISSUE TITLE
error

### ISSUE THREAD

**Issue by coffeemountaincaparao** [prisma/prisma#19613] opened 2023-06-05 14:50 UTC
Hi Prisma Team! My Prisma Client just crashed. This is the report:
## Versions

| Name            | Version            |
|-----------------|--------------------|
| Node            | v16.20.0           | 
| OS              | debian-openssl-3.0.x|
| Prisma Client   | 4.11.0             |
| Query Engine    | 8fde8fef4033376662cad983758335009d522acb|
| Database        | mysql              |

## Logs
```
de_modules/.prisma/client/libquery_engine-debian-openssl-3.0.x.so.node
prisma:get-platform Command "ls -v "libssl.so.0*" /usr/lib/x86_64-linux-gnu | grep libssl.so | grep -v "libssl.so.0"" successfully returned "libssl.so.3
"
prisma:get-platform Found libssl.so file using platform-specific paths: libssl.so.3

prisma:get-platform The parsed libssl version is: 3.0.x
prisma:client:libraryEngine:loader Searching for Query Engine Library in /home/rodrigo/projetos/coffee-market-nest/node_modules/.prisma/client
prisma:client:libraryEngine:loader loadEngine using /home/rodrigo/projetos/coffee-market-nest/node_modules/.prisma/client/libquery_engine-debian-openssl-3.0.x.so.node
prisma:get-platform Command "ls -v "libssl.so.0*" /usr/lib/x86_64-linux-gnu | grep libssl.so | grep -v "libssl.so.0"" successfully returned "libssl.so.3
"
prisma:get-platform Found libssl.so file using platform-specific paths: libssl.so.3

prisma:get-platform The parsed libssl version is: 3.0.x
prisma:client:libraryEngine:loader Searching for Query Engine Library in /home/rodrigo/projetos/coffee-market-nest/node_modules/.prisma/client
prisma:client:libraryEngine:loader loadEngine using /home/rodrigo/projetos/coffee-market-nest/node_modules/.prisma/client/libquery_engine-debian-openssl-3.0.x.so.node
prisma:get-platform Command "uname -m" successfully returned "x86_64
"
pr

**Comment by Weakky** [comment] 2023-07-13 12:57
Hey @coffeemountaincaparao,

We unfortunately can't reproduce your issue without further information. Could you please have a look at @petradonka's comment so that we can try fixing your issue?

Thank you 🙏

**Comment by petradonka** [comment] 2023-07-23 14:44
Hello @coffeemountaincaparao,

We'll close this issue for now, as we don't have enough details to reproduce and address the problem. Don't hesitate to provide more details in a new comment, and we'll be happy to reopen the issue again.

Thank you!

**Closed by petradonka** 2023-07-23 14:44 UTC
Labels: bug/0-unknown, kind/bug, topic: mysql, team/client, topic: basic error report
