### ISSUE TITLE
`null` values stripped from `Json` fields when using Prisma Neon Adapter

### ISSUE THREAD

**Issue by defrex** [prisma/prisma#22879] opened 2024-01-30 19:49 UTC
### Bug description

When using the Prisma Neon Adapter, `null` values inside `Json` fields are stripped out.

### How to reproduce

Here is a repository with an isolated reproduction of the issue.

https://github.com/defrex/prisma-neon-json-null

```
npm run repro 
```

Essentially, using two Prisma clients, one with the Neon adapter, and one with the default adapter, I've inserted the same JSON document which contains an object with a `null`-valued field.

```js
// input
{ isString: 'foo', isNull: null }

// default adapter output
{ isNull: null, isString: 'foo' }

// Neon adapter output
{ isString: 'foo' }
```

### Expected behavior

Using the Neon adapter shouldn't effect how Json fields operate.

### Prisma information

```prisma
generator client {
  provider        = "prisma-client-js"
  previewFeatures = ["driverAdapters"]
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

model Example {
  id        Int      @id @default(autoincrement())
  createdAt DateTime @default(now())
  data      Json
}

```

```ts
import { Pool, neon, neonConfig } from "@neondatabase/serverless";
import { PrismaNeon } from "@prisma/adapter-neon";
import { PrismaClient } from "@prisma/client";
import dotenv from "dotenv";
import { inspect } from "util";
import ws from "ws";

dotenv.config();

neonConfig.webSocketConstructor = ws;
const connectionString = `${process.env.DATABASE_URL}`;

const pool = new Pool({ connectionString });
const adapter = new PrismaNeon(pool);
const neonPrisma = new PrismaClient({ adapter });

const defaultPrisma = new PrismaClient();

async function main() {
  const input = {
    isString: "foo",
    isNull: null,
  };

  const defaultExample = await defaultPrisma.example.create({
    data: { data: input },
  });

  const neonExample = await neonPrisma.example.create({
    data: { data: input },
  });

  console.log(
    inspect(
      {
        defaultPrisma: { input: input, output: defaultExample.data },
        neonPrisma: { input: input, output: neonExample.data },
      },
      { depth: null }
    )
  );
}

main()
  .then(async () => {
    await defaultPrisma.$disconnect();
    process.exit(0);
  })
  .catch(async (e) => {
    console.error(e);
    await defaultPrisma.$disconnect();
    process.exit(1);
  });
```

### Environment & setup

- `@neondatabase/serverless`: 0.7.2
- Database: Postgres 16 (hosted by Neon)
- Node.js version: 21

### Prisma Version

```
prisma                  : 5.9.0
@prisma/client          : 5.9.0
Computed binaryTarget   : darwin-arm64
Operating System        : darwin
Architecture            : arm64
Node.js                 : v21.5.0
Query Engine (Node-API) : libquery-engine 23fdc5965b1e05fc54e5f26ed3de66776b93de64 (at node_modules/@prisma/engines/libquery_engine-darwin-arm64.dylib.node)
Schema Engine           : schema-engine-cli 23fdc5965b1e05fc54e5f26ed3de66776b93de64 (at node_modules/@prisma/engines/schema-engine-darwin-arm64)
Schema Wasm             : @prisma/prisma-schema-wasm 5.9.0-32.23fdc5965b1e05fc54e5f26ed3de66776b93de64
Default Engines Hash    : 23fdc5965b1e05fc54e5f26ed3de66776b93de64
Studio                  : 0.497.0
Preview Features        : driverAdapters
```

**Comment by defrex** [comment] 2024-01-30 19:49
This may be related to https://github.com/prisma/prisma/issues/22294

**Comment by jkomyno** [comment] 2024-01-31 05:17
Hi @defrex, thanks for the reproduction! I confirm that this is a duplicate of #22294.

We've identified that the behavior observed in this issue is caused by a Rust library we rely on ([napi.rs](https://github.com/napi-rs/napi-rs/blob/napi%402.12.4/crates/napi/src/bindgen_runtime/js_values/object.rs#L24-L44)).
We will open a PR upstream and hope for a fast fix.

Closing in favor of #22294.

**Closed by jkomyno** 2024-01-31 05:17 UTC
Labels: kind/bug
