### ISSUE TITLE
update will break atomicity

### ISSUE THREAD

**Issue by wvq** [prisma/prisma#9798] opened 2021-10-15 16:07 UTC
### Bug description

The updateMany() method is separate in 2 step,  
1. select record witch is match condication
2. update data by record ID,  not the passing condication.

so , in a concurrent, just few thread, it's not reliable.

|  goods_id  | available  |
|  ----  | ----  |
| 1 | 10 |
| 2  | 15 |

```sql 
-- it's atomicity.
update goods set available = available - 1 where goods_id = 1 and available > 0
```

```javascript
// prisma.update() is not support condination 'available: {gt: 0}' 

// With prisma.updateMany()
// Because at step 2, it's replace the update sql condication from  'available > 0' to 'goods_id in (1)'. 
// the execute sql will be:
// update goods set avaiable = available - 1 where goods_id in (1)
//
// it's not check available > 0.
// So, Concurrent execution is unreliable, the 'available' field may be a negative value.
await prisma.goods.updateMany({
        data: {
          available: { decrement: 1 }
        },
        where: {
          goods_id: 1,
          available: { gt: 0 }
        }
      })
```

### Environment & setup

- OS: 
- Database: 
- Node.js version: 

### Prisma Version

```

```

**Comment by pantharshit00** [comment] 2022-06-02 13:48
Hey, sorry for the really late response here but can you please share your schema here?

**Comment by wvq** [comment] 2022-06-24 02:59
Sorry for late response too. But it has nothing to do with schema.
It's a multithreading problem, prisma transform `update with where conditions` to `select id with where conditions` then `update by id`, after transform, the actual execute update sql loose `where conditions`, so the result is unexpected if `where conditions` contains some expression.

---
execute sql
```sql
update goods set available = available - 1 where goods_id = 1 and available > 0
``` 
column `available` will always >=0

---

 execute prisma transformed sql
```sql
select id from goods where goods_id = 1 and available > 0;
update goods set available = available -1 where id = 1;
```
column `available` may <0 in multithreading.

**Comment by janpio** [comment] 2022-08-23 16:35
Your schema would have helped of letting us actually execute the Prisma Client code you shared in the hope of being able to reproduce the issue. But yes, we can of course recreate a `goods` model ourselves with fields `good_id` and `available` and see if that is enough to somehow trigger a reproduction of this problem.

**Comment by garrensmith** [comment] 2022-09-02 13:02
@wvq thanks for this report. I can reproduce it and will be looking into it soon.

**Comment by garrensmith** [comment] 2022-09-07 07:48
I'm going to close this since it is a duplicate of https://github.com/prisma/prisma/issues/8612
Please follow along on the other ticket for updates.

**Closed by garrensmith** 2022-09-07 07:48 UTC
Labels: bug/1-unconfirmed, kind/bug, topic: prisma-client, tech/engines, team/client, topic: updateMany, topic: query race condition
