### ISSUE TITLE
Indices on Single Column Expressions

### ISSUE THREAD

**Issue by drewcorlin1** [prisma/prisma#13414] opened 2022-05-19 02:47 UTC
## Problem

Commonly we define indices (and unique indices) that make use of expressions, most commonly `LOWER(col)` and `UPPER(col)`, though we are unable to express that in our `schema.prisma`. Furthermore prisma actually tries to remove our indices containing expressions in every subsequent migration, causing us to manually update each migration (looks like this is already captured in https://github.com/prisma/prisma/issues/12914).

Edit: As of prisma 4.1, `prisma migrate dev` no longer attempts to remove the existing index on those columns, but still tries to add the new index. This causes the newly added migration to fail.

An isolated reproducible example of this [can be found here](https://github.com/drewcorlin1/prisma-index-expression-example).

## Suggested solution

```prisma
model User {
  id        String @id
  firstName String @map("first_name")

  @@index([@lower(firstName)])
  @@map("users")
}
```
to generate
```sql
CREATE INDEX "user_first_name_idx" ON "user"(LOWER("first_name"));
```

Ideally the solution would be able to be applied to multi column indices the same as single column indices
```prisma
@@index([@lower(firstName), @lower(lastName)])
```
as well as unique indices.
```prisma
@@unique([@lower(firstName), @lower(lastName)])
```
## Alternatives

Adding a standard index `@@index([firstName])` and then manually updating the generated migration to use an expression on the desired columns.

**Comment by drewcorlin1** [comment] 2022-07-21 14:36
When attempting to update to prisma 4.1 I followed the upgrade guide and ran `prisma db pull`. It attempted to delete my functional index from my prisma schema. If I add that index back it now doesn't attempt to delete the functional index, but does attempt to add a new one which fails. This is preventing me from upgrading to prisma 4.x

**Comment by janpio** [comment] 2022-07-30 21:36
The problem here is how to deal with all the other possible expressions @drewcorlin1 - `LOWER` and `UPPER` are the simple cases, but there are many more and we do not fully know yet how to express these. One thought is currently to just let the user describe the full expression manually, so somehow to include `LOWER("first_name")`. But with multi column indexes that is also pretty meh.

Sorry that Prisma 4 makes things more complicated here. Please make sure both your original issue description and your comment include _all_ the inforamtion we need to reproduce this fully. We will need to really see this to wrap our head around waht is going on here.

**Comment by drewcorlin1** [comment] 2022-08-01 13:36
@janpio Definitely agreed that all the other types of expressions can really complicate things. I'm also wondering if a CITEXT column would be a better fit for the behavior we're going for here.

I've updated the initial description to include a summary of the behavior we're seeing with prisma 4.1 as well as a reproducible example repo. Please let me know if I can provide any more information!

**Comment by janpio** [comment] 2022-11-16 21:20
Is this issue here overlapping/duplicate of https://github.com/prisma/prisma/issues/2504 (or the other way around)?

**Comment by drewcorlin1** [comment] 2022-11-16 21:27
Yes I think it is largely a duplicate. I think the difference between the 2 tickets is the incompatibility of `prisma migrate dev` with manually added expressions, but that could just be folded into the same ticket.

**Comment by janpio** [comment] 2022-11-16 21:47
Let's close this then, and you make sure that the missing bits are mentioend over there via a comment please.

duplicate of https://github.com/prisma/prisma/issues/2504

**Closed by janpio** 2022-11-16 21:47 UTC
Labels: kind/feature, topic: indexes, team/schema, topic: expression
