### ISSUE TITLE
PANIC: timer has gone away

### ISSUE THREAD

**Issue by mrizkyrn** [prisma/prisma#25526] opened 2024-10-28 16:29 UTC
Hi Prisma Team! My Prisma Client just crashed. This is the report:

I encountered a persistent error using Prisma Client on a production environment hosted on a cPanel shared hosting. This issue occurs when attempting to connect the Prisma Client to a MySQL database.

Since prisma could not run in the restricted cPanel environment, I generated the client files locally and copied node_modules/.prisma directory to the server.

## Versions

| Name            | Version            |
|-----------------|--------------------|
| Node            | v20.17.0           | 
| OS              | debian-openssl-1.1.x|
| Prisma Client   | 5.21.1             |
| Query Engine    | bf0e5e8a04cada8225617067eaa03d041e2bba36|
| Database        | mysql              |

## Logs
```
prisma:tryLoadEnv Environment variables not found at null
prisma:tryLoadEnv Environment variables loaded from /home/user/nodevenv/node-app/20/lib/.env
prisma:client checkPlatformCaching:postinstall false
prisma:client checkPlatformCaching:ciName 
prisma:tryLoadEnv Environment variables not found at null
prisma:tryLoadEnv Environment variables loaded from /home/user/nodevenv/node-api/20/lib/.env
prisma:client dirname /home/user/nodevenv/node-app/20/lib/node_modules/.prisma/client
prisma:client relativePath ../../../prisma
prisma:client cwd /home/user/nodevenv/node-app/20/lib/node_modules/.prisma/client
prisma:client clientVersion 5.21.1
prisma:client:libraryEngine internalSetup
prisma:get-platform Don't know any platform-specific paths for "undefined" on x64 (x86_64)
prisma:get-platform Falling back to "ldconfig" and other generic paths
prisma:get-platform Command "ldconfig -p | sed "s/.*=>s*//" | sed "s|.*/||" | grep libssl | sort | grep -v "libssl.so.0"" successfully returned "libssl.so
libssl.so.1.1
libssl.so.3
libssl3.so
"
prisma:get-platform Found libssl.so file using "ldconfig" or other generic paths: libssl.so
libssl.so.1.1
libssl.so.3
libssl3.so

prisma:get-platform The parsed libssl version is: 1.1.x
prisma:get-platform Distro is "undefined". Falling back to Prisma engines built for "debian".
prisma:client:engines:resolveEnginePath enginePath /home/user/nodevenv/node-app/20/lib/node_modules/.prisma/client/libquery_engine-debian-openssl-1.1.x.so.node
prisma:client Prisma Client call:
prisma:client prisma.user.findUnique({
  where: {
    email: "admin@example.com"
  }
})
prisma:client Generated request:
prisma:client {
  "modelName": "User",
  "action": "findUnique",
  "query": {
    "arguments": {
      "where": {
        "email": "admin@example.com"
      }
    },
    "selection": {
      "$composites": true,
      "$scalars": true
    }
  }
}

prisma:client:libraryEngine sending request, this.libraryStarted: false
prisma:client:libraryEngine library starting
```

**Comment by jkomyno** [comment] 2024-10-29 10:50
Hi @mrizkyrn, can you please share your `schema.prisma`'s `generator` block, and the OS info of both your local machine and cPanel's shared machine?

Is it possible that your CPU architecture or OS differs from cPanel's? If so, you may want to look into [`binaryTargets`](https://www.prisma.io/docs/orm/prisma-schema/overview/generators#binary-targets).

**Comment by jkomyno** [comment] 2024-10-29 10:51
Also, please note that https://github.com/prisma/prisma/issues/23909 mentions the same kind of panic, with the user reporting that it was **NOT** due to Prisma.

**Comment by jkomyno** [comment] 2024-10-29 11:57
> Is it possible that this issue is due to the server's process limit being reached? 

It's possible, but that looks like a cPanel issue rather than a Prisma one, wouldn't you agree?

**Comment by mrizkyrn** [comment] 2024-10-29 13:06
> It's possible, but that looks like a cPanel issue rather than a Prisma one, wouldn't you agree?

I see your point, but the issue seems to occur specifically during the initialization of the PrismaClient. Given that the process count hits 60/60 at that moment, Do you think 60 processes are not enough to initialize PrismaClient, or could there be something wrong with my configuration that's causing this issue?

**Comment by jkomyno** [comment] 2024-12-30 15:21
Closing this as a duplicate of https://github.com/prisma/prisma/issues/24100

**Closed by jkomyno** 2024-12-30 15:21 UTC
Labels: bug/0-unknown, kind/bug, domain/client, topic: rust panic
