### ISSUE TITLE
[Introspection] Error: [libs/datamodel/core/src/dml/model.rs:166:14] We assume an internally valid datamodel before mutating. 

### ISSUE THREAD

**Issue by janpio** [prisma/prisma#3611] opened 2020-09-11 20:23 UTC
Command: `prisma introspect`
Version: `2.6.2`
Binary Version: `6a8054bb549e4cc23f157b0010cb2e95cb2637fb`
Report: https://prisma-errors.netlify.app/report/11131 
OS: `x64 darwin 18.7.0`

JS Stacktrace:
```
Error: [libs/datamodel/core/src/dml/model.rs:166:14] We assume an internally valid datamodel before mutating.
    at IntrospectionEngine.<anonymous> (/Users/../Documents/.../c.../node_modules/@prisma/cli/build/index.js:2:1828886)
    at Generator.throw (<anonymous>)
    at rejected (/Users/.../Documents/.../.../node_modules/@prisma/cli/build/index.js:2:1825889)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

Rust Stacktrace:
```
   0: backtrace::backtrace::trace
   1: backtrace::capture::Backtrace::new
   2: user_facing_errors::Error::new_in_panic_hook
   3: user_facing_errors::panic_hook::set_panic_hook::{{closure}}
   4: std::panicking::rust_panic_with_hook
   5: _rust_begin_unwind
   6: core::panicking::panic_fmt
   7: core::option::expect_failed
   8: datamodel::dml::datamodel::Datamodel::find_relation_field_mut
   9: sql_introspection_connector::re_introspection::enrich
  10: sql_introspection_connector::calculate_datamodel::calculate_datamodel
  11: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  12: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  13: <futures_util::compat::compat03as01::Compat<Fut> as futures::future::Future>::poll
  14: <futures::future::map::Map<A,F> as futures::future::Future>::poll
  15: <futures::future::either::Either<A,B> as futures::future::Future>::poll
  16: <futures::future::lazy::Lazy<F,R> as futures::future::Future>::poll
  17: futures::future::chain::Chain<A,B,C>::poll
  18: <futures::future::then::Then<A,B,F> as futures::future::Future>::poll
  19: <futures::future::map::Map<A,F> as futures::future::Future>::poll
  20: <futures::future::either::Either<A,B> as futures::future::Future>::poll
  21: <futures::future::map::Map<A,F> as futures::future::Future>::poll
  22: futures::task_impl::std::set
  23: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  24: tokio::runtime::enter::Enter::block_on
  25: tokio::runtime::context::enter
  26: tokio::runtime::handle::Handle::enter
  27: introspection_engine::main
  28: std::rt::lang_start::{{closure}}
  29: std::rt::lang_start_internal
  30: _main

```

**Comment by pantharshit00** [comment] 2020-09-15 21:31
I am unable to reproduce these introspection errors which came from error reporting as we don't have a database schema.

I am going to tag this with `topic: introspection error reporting` so that someone working on the this part of rust source can check the source code lines which the error is referencing.

**Comment by janpio** [comment] 2021-03-04 16:32
There are still recent reports for this: https://prisma-errors.netlify.app/search?q=We%20assume%20an%20internally%20valid%20datamodel%20before%20mutating.

**Comment by tomhoule** [comment] 2021-03-05 09:49
https://prisma-errors.netlify.app/report/13057 is another instance

**Comment by tomhoule** [comment] 2021-03-05 09:51
https://prisma-errors.netlify.app/report/13045

**Comment by tomhoule** [comment] 2021-03-05 09:51
https://prisma-errors.netlify.app/report/13036

**Comment by tomhoule** [comment] 2021-03-05 09:52
https://prisma-errors.netlify.app/report/13030

**Comment by tomhoule** [comment] 2021-03-05 09:52
https://prisma-errors.netlify.app/report/13029

**Comment by do4gr** [comment] 2021-03-12 09:59
Unfortunately we were not collecting the information in our error reporting in a format that allows us to replay the bug. That has changed with 2.19 which should be out next Tuesday.This should allow us to exactly pinpoint the issue. 

I'm closing this one now because we cannot act on it.

**Closed by do4gr** 2021-03-12 09:59 UTC
Labels: bug/1-repro-available, kind/bug, team/migrations, topic: introspection, topic: introspection error reporting
