### ISSUE TITLE
Upsert not creating all entries

### ISSUE THREAD

**Issue by BelphegorPrime** [prisma/prisma#5255] opened 2021-01-24 08:46 UTC
## Bug description
It is a little hard to describe, but I´m out of ideas.
I in my application to mock some data and write them into the DB.
So for some off my entities I created an array with data to insert and when I try to insert all of them with array map and Promise all the response is rather weird and not correctly written into the DB!

## How to reproduce
Important is that before executing the following, there are no entries in the corresponding datatable
```
const createScenarioCharacterClasses = async (dataSources: DataSources) => {
  const scenarioCharacterClasses = [{
    id: 1,
    name: 'Rooter',
    scenarioId: 1
  }, {
    id: 2,
    name: 'Warrior',
    scenarioId: 1
  }, {
    id: 3,
    name: 'Wizard',
    scenarioId: 1
  }, {
    id: 4,
    name: 'Rooter',
    scenarioId: 2
  }, {
    id: 5,
    name: 'Warrior',
    scenarioId: 2
  }, {
    id: 6,
    name: 'Wizard',
    scenarioId: 2
  }, {
    id: 7,
    name: 'Rooter',
    scenarioId: 3
  }, {
    id: 8,
    name: 'Warrior',
    scenarioId: 3
  }, {
    id: 9,
    name: 'Wizard',
    scenarioId: 3
  }]

  const a = await Promise.all(
    scenarioCharacterClasses.map(({ id, ...create }) => dataSources.scenarioCharacterClass.delegate.upsert({
      where: { id },
      update: {},
      create
    }))
  )
  console.log(a)

  return a
}
```
before calling this function I of course awaited another function that creates my scenarios.
The function for scenarios does it in exactly the same way as this function for scenarioCharacterClasses.

I only can reproduce this wrongdoing when trying to insert more than 3 or 4 entries.

the console.log(a)

produces the following data

```
[
  {
    id: 4,
    createdAt: 2021-01-24T08:31:11.107Z,
    updatedAt: 2021-01-24T08:31:11.107Z,
    name: 'Rooter',
    scenarioId: 1
  },
  {
    id: 2,
    createdAt: 2021-01-24T08:31:11.107Z,
    updatedAt: 2021-01-24T08:31:11.107Z,
    name: 'Rooter',
    scenarioId: 3
  },
  {
    id: 1,
    createdAt: 2021-01-24T08:31:11.107Z,
    updatedAt: 2021-01-24T08:31:11.107Z,
    name: 'Wizard',
    scenarioId: 1
  },
  {
    id: 4,
    createdAt: 2021-01-24T08:31:11.107Z,
    updatedAt: 2021-01-24T08:31:11.107Z,
    name: 'Rooter',
    scenarioId: 1
  },
  {
    id: 3,
    createdAt: 2021-01-24T08:31:11.107Z,
    updatedAt: 2021-01-24T08:31:11.107Z,
    name: 'Warrior',
    scenarioId: 2
  },
  {
    id: 7,
    createdAt: 2021-01-24T08:31:11.140Z,
    updatedAt: 2021-01-24T08:31:11.140Z,
    name: 'Wizard',
    scenarioId: 2
  },
  {
    id: 2,
    createdAt: 2021-01-24T08:31:11.107Z,
    updatedAt: 2021-01-24T08:31:11.107Z,
    name: 'Rooter',
    scenarioId: 3
  },
  {
    id: 6,
    createdAt: 2021-01-24T08:31:11.140Z,
    updatedAt: 2021-01-24T08:31:11.140Z,
    name: 'Warrior',
    scenarioId: 3
  },
  {
    id: 5,
    createdAt: 2021-01-24T08:31:11.124Z,
    updatedAt: 2021-01-24T08:31:11.124Z,
    name: 'Wizard',
    scenarioId: 3
  }
]
```
You can clearly see how the entity with id 4 and 2 are two times into the output but only ones in the input.
and this data is also what is written into the DB

## Environment & setup

```
- OS: Debian docker
- Database: PostgreSQL
- Node.js version: v12.18.2
- Prisma version:
@prisma/cli          : 2.15.0
@prisma/client       : 2.15.0
Current platform     : debian-openssl-1.1.x
Query Engine         : query-engine e51dc3b5a9ee790a07104bec1c9477d51740fe54 (at node_modules/@prisma/engines/query-engine-debian-openssl-1.1.x)
Migration Engine     : migration-engine-cli e51dc3b5a9ee790a07104bec1c9477d51740fe54 (at node_modules/@prisma/engines/migration-engine-debian-openssl-1.1.x)
Introspection Engine : introspection-core e51dc3b5a9ee790a07104bec1c9477d51740fe54 (at node_modules/@prisma/engines/introspection-engine-debian-openssl-1.1.x)
Format Binary        : prisma-fmt e51dc3b5a9ee790a07104bec1c9477d51740fe54 (at node_modules/@prisma/engines/prisma-fmt-debian-openssl-1.1.x)
Studio               : 0.340.0
Preview Features     : uncheckedScalarInputs, groupBy
```
AND I also tried with 2.14.0, but that resulted into the same behaviour

```
@prisma/cli          : 2.14.0
@prisma/client       : 2.14.0
Current platform     : debian-openssl-1.1.x
Query Engine         : query-engine 5d491261d382a2a5ffdc71de17072b0e409f1cc1 (at node_modules/@prisma/engines/query-engine-debian-openssl-1.1.x)
Migration Engine     : migration-engine-cli 5d491261d382a2a5ffdc71de17072b0e409f1cc1 (at node_modules/@prisma/engines/migration-engine-debian-openssl-1.1.x)
Introspection Engine : introspection-core 5d491261d382a2a5ffdc71de17072b0e409f1cc1 (at node_modules/@prisma/engines/introspection-engine-debian-openssl-1.1.x)
Format Binary        : prisma-fmt 5d491261d382a2a5ffdc71de17072b0e409f1cc1 (at node_modules/@prisma/engines/prisma-fmt-debian-openssl-1.1.x)
Studio               : 0.332.0
Preview Features     : uncheckedScalarInputs, groupBy

```

**Comment by BelphegorPrime** [comment] 2021-01-24 09:18
https://github.com/prisma/prisma/issues/5066#issue-785398386 helps but I think this is still unwanted behaviour.

**Comment by pantharshit00** [comment] 2021-01-27 19:32
This is quite strange. Can you please share the model involved in the query so that I can try this locally. I wasn't able to reproduce with a simple example with tried.

**Comment by BelphegorPrime** [comment] 2021-01-28 12:38
Yeah no Problem, here are the model and sub-models.
Oh and as I mentioned already changing `Promise.all` to `prisma.$transaction` in the fucntionI provided solved it. But `Promise.all` should actually work in the same way.

```
model ScenarioCharacterClass {
  id                    Int                 @default(autoincrement()) @id
  createdAt             DateTime            @default(now())
  updatedAt             DateTime            @updatedAt @default(now())
  name                  String

  scenario              Scenario            @relation(fields: [scenarioId], references: [id])
  scenarioId            Int
}

enum ScenarioSetting {
  HIGHFANTASY
  MEDIVAL
  SCIFI
}

model Scenario {
  id                    Int                 @default(autoincrement()) @id
  createdAt             DateTime            @default(now())
  updatedAt             DateTime            @updatedAt @default(now())
  name                  String

  setting               ScenarioSetting

  levelUpStrategie      LevelUpStrategie    @relation(fields: [levelUpStrategieId], references: [id])
  levelUpStrategieId    Int
}

model LevelUpStrategie {
  id                    Int                 @default(autoincrement()) @id
  createdAt             DateTime            @default(now())
  updatedAt             DateTime            @updatedAt @default(now())

  steps                 LevelUpStep[]
}

model LevelUpStep {
  id                    Int                 @default(autoincrement()) @id
  createdAt             DateTime            @default(now())
  updatedAt             DateTime            @updatedAt @default(now())

  from                  Int
  to                    Int
  level                 Int
}

```

**Comment by Weakky** [comment] 2021-02-02 14:44
I'm able to reproduce that issue.

*Datamodel*

```prisma
datasource db {
  provider = "postgres"
  url      = "postgresql://postgres:prisma@localhost"
}

generator client {
  provider = "prisma-client-js"
}

model Item {
  id        Int      @default(autoincrement()) @id
  createdAt DateTime @default(now())
  updatedAt DateTime @updatedAt @default(now())
  name      String
}
```

*Seed*

```js
const { PrismaClient } = require("@prisma/client");

async function main() {
  const prisma = new PrismaClient();

  const data = [
    "1",
    "2",
    "3",
    "4",
    "5",
    "6",
    "7",
    "8",
    "9",
    "10",
    "11",
    "12",
    "13",
    "14",
  ];

  const res = await Promise.all(
    data.map((name, i) => {
      return prisma.item.upsert({
        where: { id: i },
        update: {},
        create: {
          name,
        },
      });
    })
  );

  console.log(res);
  prisma.$disconnect();
}

main();
```

*Result*
- `id` 4 and 6 are duplicated in the result
- These are not duplicated at the db level. So this is either happening at the client level or at the QE level before returning the response back
- 
```
[
  {
    id: 2,
    createdAt: 2021-02-02T14:39:19.807Z,
    updatedAt: 2021-02-02T14:39:19.807Z,
    name: '1'
  },
  {
    id: 1,
    createdAt: 2021-02-02T14:39:19.797Z,
    updatedAt: 2021-02-02T14:39:19.797Z,
    name: '2'
  },
  {
    id: 3,
    createdAt: 2021-02-02T14:39:19.816Z,
    updatedAt: 2021-02-02T14:39:19.816Z,
    name: '3'
  },
  {
    id: 4,
    createdAt: 2021-02-02T14:39:19.816Z,
    updatedAt: 2021-02-02T14:39:19.816Z,
    name: '4'
  },
  {
    id: 4,
    createdAt: 2021-02-02T14:39:19.816Z,
    updatedAt: 2021-02-02T14:39:19.816Z,
    name: '4'
  },
  {
    id: 6,
    createdAt: 2021-02-02T14:39:19.827Z,
    updatedAt: 2021-02-02T14:39:19.827Z,
    name: '6'
  },
  {
    id: 6,
    createdAt: 2021-02-02T14:39:19.827Z,
    updatedAt: 2021-02-02T14:39:19.827Z,
    name: '6'
  },
  {
    id: 5,
    createdAt: 2021-02-02T14:39:19.827Z,
    updatedAt: 2021-02-02T14:39:19.827Z,
    name: '8'
  },
  {
    id: 7,
    createdAt: 2021-02-02T14:39:19.840Z,
    updatedAt: 2021-02-02T14:39:19.840Z,
    name: '9'
  },
  {
    id: 9,
    createdAt: 2021-02-02T14:39:19.840Z,
    updatedAt: 2021-02-02T14:39:19.840Z,
    name: '10'
  },
  {
    id: 8,
    createdAt: 2021-02-02T14:39:19.840Z,
    updatedAt: 2021-02-02T14:39:19.840Z,
    name: '11'
  },
  {
    id: 12,
    createdAt: 2021-02-02T14:39:19.854Z,
    updatedAt: 2021-02-02T14:39:19.854Z,
    name: '12'
  },
  {
    id: 10,
    createdAt: 2021-02-02T14:39:19.854Z,
    updatedAt: 2021-02-02T14:39:19.854Z,
    name: '13'
  },
  {
    id: 11,
    createdAt: 2021-02-02T14:39:19.854Z,
    updatedAt: 2021-02-02T14:39:19.854Z,
    name: '14'
  }
]
```

**Comment by pantharshit00** [comment] 2021-02-04 18:53
I can reproduce with your example as well :)

Marking it as confirmed.

**Comment by Weakky** [comment] 2021-02-19 13:03
Hey @BelphegorPrime,

After investigating this issue further, we've concluded that this is actually _not_ a bug. The problem you're experiencing here is due to two facts:

- Requests are processed concurrently
- The auto-increment ids

Let me explain further 👇

Let's consider this simple datamodel:

```prisma
model Item {
  id        Int      @default(autoincrement()) @id
  name      String
}
```

And this simple script:

```js
import { PrismaClient } from '@prisma/client'

async function main() {
  const prisma = new PrismaClient()
  const names = ["bob", "sarah", "dom"]
  
  const upserts = names.map((name, id) => {
    return prisma.item.upsert({
      where: { id: id + 1 },
      update: {},
      create: { name }
    })
  })
  
  const res = await Prisma.all(upserts)
  
  console.log(res)
}

main()
```

Now let's try to dissect what would happen at the query engine level.

1. **Three HTTP requests are sent/received**

   Remember though, **these requests are processed concurrently**. That means the order in which they're executed 
   is _unpredictable_ by nature.

   In practice, there's actually a very high chance that these requests won't be executed in the order in which 
   they were sent.

2. **Requests are processed**

   Upsert operations are using transactions. This makes the variety of potential scenarios even larger as one 
   upsert is not executed at the db level in a single operation. 

   To simplify the explanation, we'll assume one upsert is executed in a single operation at the db level. Even 
   with that guarantee, we'd still face the issue.

   Moving on, let's assume we process the upsert ops in the following order:

   ```
   1. upsert({ where: { id: 1 }, update: {}, create: { name: "bob" } })
   2. upsert({ where: { id: 3 }, update: {}, create: { name: "dom" } })
   3. upsert({ where: { id: 2 }, update: {}, create: { name: "sarah" } })
   ```

   - First request, there's no record with `id: 1`, so we create `{ name: "bob" }` and we return `{ name: "bob" }`
   - Second request, there's no record with `id: 2`, so we create `{ name: "dom" }`, and we return `{ name: "dom" }`
   - Third request, there _is_ a record with `id: 2`, so we don't create anything and we return `{ name: "dom" }`

3. **Results are duplicated**

   Suddenly, it _seems_ we have duplicated results as we get back:

   ```js
   [{ "name": "bob" }, { "name": "dom" }, { "name": "dom" }]
   ```

   You might think that you'd solve this problem by _ensuring_ that your requests are sent in the right order, 
   but that won't solve it, because, once again:
     - These requests are processed concurrently anyway at the Query Engine
     - Upserts are done using transactions

4. **Solution(s) ?**
  
   1. Do not use auto-incremental ids. This will prevent this kind of problems to happen in the future. If you 
   were using uuids, you wouldn't have wrote this piece of code in the first place because you wouldn't have been able to "guess" the ids
   2. I'm not sure exactly why you're using upsert here, but maybe consider using `create` instead, [potentially within a single transaction](https://www.prisma.io/docs/concepts/components/prisma-client/transactions/#the-transaction-api) using `prisma.$transaction`
   3. You could use the [`createMany` feature (still in preview)](https://www.prisma.io/docs/reference/api-reference/prisma-client-reference#createmany-preview) but you wouldn't be able to select the ids back as for the response.


Hopefully this explanation was clear enough. I'm closing the issue now but feel free to keep commenting if you have any further questions.

Thanks for posting that issue regardless! 🙌

**Closed** 2021-02-19 13:06 UTC
Labels: bug/2-confirmed, kind/bug, team/client

**Comment by BelphegorPrime** [comment] 2021-02-19 13:45
Hey @Weakky ,

I think you have here a little typo `const res = await Prisma.all(upserts)` and it should be Promise.all.

I understand that there are conflicts with async execution and order.
The drop-in-replacement `Promise.all` with `prisma.$transaction` does as i already mentioned exactly what i have initally expected.

The Question was more why is it working with `prisma.$transaction` and not with `Promise.all`? I would expect the `Promise.all` work the same way as the `prisma.$transaction` from a users viewpoint.

Ok it would be hard to know if a upsert is part of a `Promise.all`-execution.


P.S. what i wanted t archieve was to init my database with like a root user and other stuff. (that was before you released the seeding stuff) When something is added to it it will create automaticly the new db entries for values if they not existing. Thats the reason for the upsert. I didn´t want to make a `if it exists than create` thing where i have to make two db requests because upsert should do it in one call because it is postgreSQL and it knows nativly how a upsert works.

**Comment by matthewmueller** [comment] 2021-03-01 09:55
Thanks @BelphegorPrime, I think for your specific case, seeding stuff would be solved by the [createMany](https://www.prisma.io/docs/reference/api-reference/prisma-client-reference#createmany-preview) API with `skipDuplicates`.

This issue is eerily similar to #3242, which I've re-opened and I'd like to test further. If you look at the SQL in [this comment],(https://github.com/prisma/prisma/issues/3242#issuecomment-787808111) it seems like even with transactions, it's not entirely atomic.

**Comment by SwapnilSoni1999** [comment] 2025-01-21 21:59
I'm facing same issue 
I'm getting the return value as well for upserted data but when I check from beekeeper it doesn't update the data
