### ISSUE TITLE
MongoDB schema to support relative path for TLS certificate location

### ISSUE THREAD

**Issue by leafyshark** [prisma/prisma#11749] opened 2022-02-10 21:35 UTC
I'm trying to connect to a DigitalOcean MongoDB instance, **which requires providing a certificate file** in the form of a tlsCAFile option added to the connection string. Example:

`
mongodb+srv://<un>:<pw>@example.mongo.ondigitalocean.com/admin?authSource=admin&tls=true&tlsCAFile=<path-to-CA-cert>
`

I read that the [MySQL database connection string SSL certificate paths are resolved relative to the ./prisma folder](https://www.prisma.io/docs/concepts/database-connectors/mysql#arguments), however I have tried changing the path to the certificate in the above string relative to my prisma folder (my folder's name is actually `db` not `prisma`, maybe this is what is causing the issue?) i.e. `tlsCAFile=/cert/ca-certificate.pem`.

However, this doesn't work. My folder structure is as follows:

```
db/schema.prisma
db/certs/ca-certificate.pem
```

What seems to me to be a solution is to include a tlsCAFile property in the `datasource` object in `schema.prisma` file.

**Comment by janpio** [comment] 2022-02-11 09:37
We have an e2e test for DigitalOcean MongoDB. The connection string looks like this: `mongodb+srv://doadmin:...@db-mongodb-....mongo.ondigitalocean.com/e2e-tests?authSource=admin&replicaSet=db-mongodb-...&tls=true&tlsCAFile=../ca-certificate.crt` and we create the `ca-certificate.crt` in build with this code: https://github.com/prisma/e2e-tests/blob/07fdae39be1f28385fbd1be2051ff5eb5c75a344/databases/mongodb-digitalocean/run.sh#L5-L7 So it looks to me as if the path also is relative to the `prisma` folder where our `schema.prisma` lives.

In your example I would expect the valid path value to be `tlsCAFile=cert/ca-certificate.pem`. (The leading `/` you have right now makes it look at the absolute path in the root)

**Comment by janpio** [comment] 2022-02-14 18:55
I now found an issue, ironically by me, that also shows that this does not seem to be working properly: https://github.com/prisma/prisma/issues/9072

**Comment by matthewmueller** [comment] 2022-02-16 20:57
Thanks for bringing this up @leafyshark. Once this issue is fixed, we should re-test #9072

**Comment by janpio** [comment] 2022-03-11 18:00
I can confirm this is now fixed, the path of `tlsCAFile` is also relative to the Prisma schema file location as it should be. Our tests now explicitly do that and it works as expected starting with `3.11.0-dev.50`, which we will release as 3.11.0 next week.

Please let us know if this also works for you now @leafyshark. Thanks!

**Closed by janpio** 2022-03-11 18:00 UTC
Labels: team/client, topic: mongodb, kind/support

**Comment by mbhafaiedh** [comment] 2023-07-22 20:25
Currently, `tlsCAFile` is being accessed from the "prisma" directory, whereas `tlsCertificateKeyFile` is accessed from the absolute root directory. To ensure consistency, both `tlsCAFile` and `tlsCertificateKeyFile` should be referenced the same way. 🦜
