### ISSUE TITLE
Attempted to serialize scalar 'null' with incompatible type 'String'

### ISSUE THREAD

**Issue by aputinski** [prisma/prisma#2267] opened 2020-04-22 03:07 UTC
## Bug description

I'm getting`Attempted to serialize scalar 'null' with incompatible type 'String'` when trying to create new records that use nested writes (both `create` and `connect`)

I followed the [upgrade guide](https://github.com/prisma/prisma/releases/tag/2.0.0-beta.1) and all my read queries are working as expected.

## Prisma information
```javascript
let vendor = await client.vendor.create({
  data: {
    name: "New Vendor",
    description: "",
    minimumOrder: "",
    minimumReorder: "",
    config: {
      create: {
        exclusions: "",
        expandAnnotation: "",
        transformSku: "",
      },
    },
  },
});
```

```
model Vendor {
  id             String       @default(cuid()) @id
  createdAt      DateTime     @default(now())
  updatedAt      DateTime     @updatedAt
  name           String
  minimumOrder   String
  minimumReorder String
  description    String
  active         Boolean      @default(false)
  skusUpdatedAt  DateTime?
  catalogs       Catalog[]
  config         VendorConfig @relation(fields: [configId], references: [id])
  configId       String       @map("config")
}

model VendorConfig {
  id               String   @default(cuid()) @id
  createdAt        DateTime @default(now())
  updatedAt        DateTime @updatedAt
  exclusions       String?
  transformSku     String?
  expandAnnotation String?
}

model Catalog {
  id        String         @default(cuid()) @id
  createdAt DateTime       @default(now())
  updatedAt DateTime       @updatedAt
  name      String
  active    Boolean        @default(false)
  vendor    Vendor         @relation(fields: [vendorId], references: [id])
  vendorId  String         @map("vendor")
  pages     CatalogPage[]
  upload    CatalogUpload?
}

model CatalogUpload {
  id          String    @default(cuid()) @id
  createdAt   DateTime  @default(now())
  updatedAt   DateTime  @updatedAt
  completedAt DateTime?
  catalog     Catalog   @relation(fields: [catalogId], references: [id])
  catalogId   String    @map("catalog")
}

model CatalogPage {
  id        String   @default(cuid()) @id
  createdAt DateTime @default(now())
  updatedAt DateTime @updatedAt
  number    Int
  value     String
  catalog   Catalog  @relation(fields: [catalogId], references: [id])
  catalogId String   @map("catalog")
}

model Order {
  id        String   @default(cuid()) @id
  createdAt DateTime @default(now())
  updatedAt DateTime @updatedAt
  value     String
}
```

## Environment & setup

- OS: [Mac OS]
- Database: [PostgreSQL]
- Prisma version: [2.0.0-beta.3]
- Node.js version: [10.18.0]

**Comment by pantharshit00** [comment] 2020-04-23 11:26
I can confirm this issue. Looks like a bug to me.

**Comment by Jolg42** [comment] 2020-04-23 12:35
I can confirm as well with another schema in 2.0.0-alpha.1127

**Comment by Jolg42** [comment] 2020-04-24 11:36
Ok so it looks like I messed up with too many things yesterday because I think the origin of my specific issue is from the sqlite db I was using that had the column id as integer.

I think I changed `id    Int     @id @default(autoincrement())`  without noticing to `id    String  @default(cuid()) @id` without updating / migrating the database.

**Comment by pantharshit00** [comment] 2020-04-24 11:46
Fixed in `2.0.0-alpha.1136` via https://github.com/prisma/prisma-engines/commit/30c72503f68f53bb848c6f0b9a20bb95620be3de

Please test it out using `npm install @prisma/cli@alpha && npx prisma generate`

**Closed** 2020-05-12 08:10 UTC
Labels: bug/2-confirmed, kind/bug, team/engines

**Comment by terion-name** [comment] 2021-07-01 10:00
I have this on queries for empty parent relation. E.g. tree-like structure with parent-child:
 ```prisma
# irrelevant fields stripped off
 model Unit {
  id String @id @default(cuid())     
  manager Unit?      @relation(name: "DepartmentManager", fields: [managerId], references: [id])
  managerOf Unit[]      @relation(name: "DepartmentManager")
  managerId String?   
}
 ```
Table:
```sql
# irrelevant fields stripped off
CREATE TABLE `Unit` (
  `id` varchar(25) NOT NULL,
  `managerId` varchar(25) DEFAULT NULL COMMENT 'DepartmentManager.B',
  `documentsDocumentId` varchar(25) DEFAULT NULL COMMENT 'UnitToDocumentsDocument.A',
  PRIMARY KEY (`id`),
  KEY `unit_managerid_foreign` (`managerId`),
  CONSTRAINT `unit_managerid_foreign` FOREIGN KEY (`managerId`) REFERENCES `Unit` (`id`),
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
```
Query:
 ```graphql
 {
  units {
      id
      # who is this unit's manager - e.g. parent
      manager {
        id
      }
      # who does this unit manages - e.g. children
      managerOf {
        id
      }
}
```
Or in orm syntax:
```js
{select: {
  id: true,
  manager: { select: { id: true } },
  managerOf: { select: { id: true } },
  manages: { select: { id: true } }
}}
```
If `managerId` is null, children do query correctly and return empty array, but parent fails: 
```
Invalid `prisma.unit.findMany()` invocation:  Attempted to serialize scalar 'null' with incompatible type 'String' for field managerId
```

**Comment by vibhanshu909** [comment] 2022-03-06 17:13
I'm getting `Attempted to serialize scalar 'null' with incompatible type 'BigInt' for field <fieldName>`.
I'm using:
Mongodb atlas
Prisma: ^3.10.0

**Comment by janpio** [comment] 2022-03-10 21:01
Please open a new issue @vibhanshu909 and provide all the information the issue template asks for. Thanks.
