### ISSUE TITLE
Bug: [D1] Error in performIO: Error: D1_ERROR: too many SQL variables

### ISSUE THREAD

**Issue by hrueger** [prisma/prisma#23743] opened 2024-04-05 19:01 UTC
### Bug description

When running queries with relations with a D1 database as the backend, I run into the following error quite often:
`Error in performIO: Error: D1_ERROR: too many SQL variables at offset [some offset].`

This is probably the same as #302 (but is closed) and #21648. `relationJoins` does not change anything since that is not available for sqlite/d1.

### How to reproduce

Checkout https://github.com/hrueger/prisma-d1-variables-bug and follow the instructions (also in the readme):
```sh
npm install
npx wrangler d1 create prisma-demo-db
```
update the `wrangler.toml` file with the database id
```sh
npx wrangler d1 migrations apply prisma-demo-db --local
npm run dev
```

### Expected behavior

it should work ;-)

I believe the split limit (I read about this in some other issue) has to be reduced. Seems like this is 100, see (https://developers.cloudflare.com/d1/platform/limits/)

### Prisma information

```prisma
// This is your Prisma schema file,
// learn more about it in the docs: https://pris.ly/d/prisma-schema

generator client {
  provider        = "prisma-client-js"
  previewFeatures = ["driverAdapters"]
}

datasource db {
  provider = "sqlite"
  url      = env("DATABASE_URL")
}

model User {
  id    Int     @id @default(autoincrement())
  email String  @unique
  name  String?
  posts  Post[]
}

model Post {
  id        Int     @id @default(autoincrement())
  title     String
  content   String?
  published Boolean @default(false)
  author    User    @relation(fields: [authorId], references: [id])
  authorId  Int
}

```

```ts
import { PrismaClient } from '@prisma/client'
import { PrismaD1 } from '@prisma/adapter-d1'

export interface Env {
	DB: D1Database
}

export default {
	async fetch(request: Request, env: Env, ctx: ExecutionContext): Promise<Response> {
		const adapter = new PrismaD1(env.DB)
		const prisma = new PrismaClient({ adapter })

		let users = await loadUsers(prisma)
		if (!users.length) {
			await createUsers(prisma);
			users = await loadUsers(prisma);
		}
		const result = JSON.stringify(users)
		return new Response(result);
	},
};

async function loadUsers(prisma: PrismaClient) {
	return await prisma.user.findMany({
		include: {
			posts: true,
		},
	});
}

async function createUsers(prisma: PrismaClient) {
	for (let i = 0; i < 250; i++) {
		await prisma.user.create({
			data: {
				email: `user${i}@example.com`,
				name: `User ${i}`,
				posts: {
					createMany: {
						data: [
							{
								title: `Post ${i}`,
								content: `This is the content of post ${i} by User ${i}`,
							},
							{
								title: `Post ${i}b`,
								content: `This is the content of the second post ${i}b by User ${i}`,
							},
						],
					},
				},
			},
		});
	}
}
```

### Environment & setup

- OS: macOS
- Database: Cloudflare D1
- Node.js version: v21.6.1

### Prisma Version

```
prisma                  : 5.12.1
@prisma/client          : 5.12.1
Computed binaryTarget   : darwin-arm64
Operating System        : darwin
Architecture            : arm64
Node.js                 : v21.6.1
Query Engine (Node-API) : libquery-engine 473ed3124229e22d881cb7addf559799debae1ab (at node_modules/@prisma/engines/libquery_engine-darwin-arm64.dylib.node)
Schema Engine           : schema-engine-cli 473ed3124229e22d881cb7addf559799debae1ab (at node_modules/@prisma/engines/schema-engine-darwin-arm64)
Schema Wasm             : @prisma/prisma-schema-wasm 5.12.0-21.473ed3124229e22d881cb7addf559799debae1ab
Default Engines Hash    : 473ed3124229e22d881cb7addf559799debae1ab
Studio                  : 0.499.0
Preview Features        : driverAdapters
```

**Comment by zett-8** [comment] 2024-04-07 16:27
@hrueger 
I wanted to ask you a question since I have a similar setup: Remix + D1 + Prisma.

When you deploy this project on Cloudflare Pages (or Workers), does it work?
In my case, the deployment itself fails due to `new PrimaClient({ adapter })`, and I'm not sure how exactly the error occurs because Cloudflare doesn't provide any logs regarding the deployment failures.

**Comment by hrueger** [comment] 2024-04-07 16:31
@zett-8 yes, apart from this issue it works just fine for me 👍 I have multiple projects running on Cloudflare Workers as well as on Cloudflare Pages.

**Comment by janpio** [comment] 2024-04-26 11:32
To connect the dots, here is a related discussion thread: https://github.com/prisma/prisma/discussions/23646#discussioncomment-9083299

**Comment by janpio** [comment] 2024-04-26 23:12
![image](https://github.com/prisma/prisma/assets/183673/b90c558c-513b-4b35-ab6e-38fa3fc00617)
```
✘ [ERROR] Error in performIO: Error: D1_ERROR: too many SQL variables at offset 381

      at D1Database._sendOrThrow (cloudflare-internal:d1-api:66:19)
      at async D1PreparedStatement.raw (cloudflare-internal:d1-api:184:32)
      ... 2 lines matching cause stack trace ...
      at null.<anonymous> (async
  file:///workspace/prisma-d1-variables-bug/.wrangler/tmp/dev-G7ujFb/index.js:1703:18) {
    [cause]: Error: too many SQL variables at offset 381
        at D1Database._sendOrThrow (cloudflare-internal:d1-api:67:24)
        at async D1PreparedStatement.raw (cloudflare-internal:d1-api:184:32)
        at async PrismaD1.performIO
  (file:///workspace/prisma-d1-variables-bug/node_modules/@prisma/adapter-d1/dist/index.mjs:235:40)
        at async PrismaD1.queryRaw
  (file:///workspace/prisma-d1-variables-bug/node_modules/@prisma/adapter-d1/dist/index.mjs:189:22)
        at null.<anonymous> (async
  file:///workspace/prisma-d1-variables-bug/.wrangler/tmp/dev-G7ujFb/index.js:1703:18)
  }


[wrangler:err] PrismaClientUnknownRequestError: 
Invalid `prisma.user.findMany()` invocation:


Error occurred during query execution:
ConnectorError(ConnectorError { user_facing_error: None, kind: QueryError(SqliteError { extended_code: 1, message: Some("D1_ERROR: too many SQL variables at offset 381") }), transient: false })
    at [object Object]
    at or.handleRequestError (file:///workspace/prisma-d1-variables-bug/node_modules/@prisma/client/runtime/wasm.js:22:7318)
    at or.handleAndLogRequestError (file:///workspace/prisma-d1-variables-bug/node_modules/@prisma/client/runtime/wasm.js:22:6462)
    at or.request (file:///workspace/prisma-d1-variables-bug/node_modules/@prisma/client/runtime/wasm.js:22:6176)
    at async f (file:///workspace/prisma-d1-variables-bug/node_modules/@prisma/client/runtime/wasm.js:27:11094)
    at async loadUsers (file:///workspace/prisma-d1-variables-bug/src/index.ts:24:9)
    at async Object.fetch (file:///workspace/prisma-d1-variables-bug/src/index.ts:16:12)
    at async jsonError (file:///workspace/prisma-d1-variables-bug/node_modules/wrangler/templates/middleware/middleware-miniflare3-json-error.ts:22:10)
    at async drainBody (file:///workspace/prisma-d1-variables-bug/node_modules/wrangler/templates/middleware/middleware-ensure-req-body-drained.ts:5:10)
[wrangler:inf] GET / 500 Internal Server Error (1466ms)
```

**Comment by TimKieu** [comment] 2024-05-21 05:26
This Bug seems to come from limit of D1 SQL statement size (by  parameters, batch or number of inserted records)...
I think that CloudFlare should note on [D1 Limits](https://developers.cloudflare.com/d1/platform/limits/).

**Comment by TimKieu** [comment] 2024-05-22 01:33
I tested with D1 plain SQL and Drizzle ORM, this is NOT Prisma error.
This is D1 ERROR due to its limited SQL statement chain, not sure how SQlite3-based D1 gives us a explixit measurement for this, may be the SQL statement string buffer (which built from raw SQL scritp and parameters).
What you should do is reduce complexity of Prism and its SQL statement.
For example, for simple insert SQL with 5 parameters I can use upto batch of 20 insert value array, but when I use 22 upsert parameters, I can only use an array of 2 values.
Thus, you should use pagination technique or SQL statement buffer measurement to reduce to the best trade-off and runnable SQL command, no matter what they are generated by Prisma/Drizzle or plain D1 Sqlite.

**Comment by janpio** [comment] 2024-05-22 10:23
We have a mechanism called "chunking" that we usually use to split problematic queries to stay inside the limits imposed by the databases. We are currently implementing this for D1, and expect this to fix the problem.

Do you have a concrete example that is currently failing with Prisma ORM, so we can confirm it now works after our fix @TimKieu?

**Comment by jkomyno** [comment] 2024-06-04 13:17
Hi @hrueger! This issue is fixed, and will be part of the upcoming release (in a few hours): Prisma 5.15.0. Thanks!

**Closed** 2024-06-04 13:23 UTC
Labels: bug/2-confirmed, kind/bug, team/client, topic: chunking, topic: driverAdapters, topic: @prisma/adapter-d1, topic: d1

**Comment by joefitter** [comment] 2024-06-04 15:38
Just dropping in to say this works brilliantly 🎉

**Comment by whiskerside** [comment] 2024-06-05 15:28
> Hi @hrueger! This issue is fixed, and will be part of the upcoming release (in a few hours): Prisma 5.15.0. Thanks!

I just encountered this error 20 mins ago, then find this great news, upgrade to 5.15.0 and the error is gone.
Thank you guys.

**Comment by andrewcashmore** [comment] 2024-06-08 17:23
I think I still get this issue when running a query with a join that has over 100 records. I can see since 5.15.0 the query is being successfully chunked and hopefully this is user error on my part.

When I run the below select as part of a prisma 'findMany'.
```
const select = {
  friendlyId: true,
  memberships: {
    select: {
      name: true
    }
  },
  user: {
    select: {
      id: true,
      firstName: true,
      lastName: true,
      email: true,
      phone: true
    }
  }
}
```

And where the original table, in this case 'members' returns over 100 results, I end up with the following queries:

```
prisma:query SELECT `main`.`Member`.`id`, `main`.`Member`.`friendlyId`, `main`.`Member`.`userId` FROM `main`.`Member` WHERE `main`.`Member`.`clubId` = ? LIMIT ? OFFSET ?
```

```
prisma:query SELECT `main`.`Membership`.`id`, `main`.`Membership`.`name`, `main`.`Membership`.`memberId` FROM `main`.`Membership` WHERE (1=1 AND `main`.`Membership`.`memberId` IN (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)) LIMIT ? OFFSET ?
```

```
prisma:query SELECT `main`.`User`.`id`, `main`.`User`.`firstName`, `main`.`User`.`lastName`, `main`.`User`.`email`, `main`.`User`.`phone` FROM `main`.`User` WHERE `main`.`User`.`id` IN (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?) LIMIT ? OFFSET ?
```

Essentially the inclusion of over 100 `?` in the query seems to get treated as breaching the '100' D1 variables limit.

**Comment by janpio** [comment] 2024-06-08 17:34
So you see queries currently being limited to 100 `?` and still get the error message? Can you share the exact query that is triggering the error? It is possible that D1 counts differently than ... usual, and that is causing trouble. Maybe also share your Prisma Schema and Prisma Client query so we can fully reproduce this. How many `Membership`s or `User`s _does_ the query return?

**Comment by andrewcashmore** [comment] 2024-06-08 19:33
Hey @janpio, I appreciate the quick response here. Yep, I have to pop a 'limit 50' on to save the query crashing at the minute, I haven't tried to up the limit to figure out the exact breaking point.

There's currently 125 rows in the members table with the same number of memberships and users for the sake of this test data. This query in theory would return 125 members who happen to have 1 membership each and a member is associated to 1 user.

Using the select above with:

```
const members = await prisma.member.findMany({
  take: 50,
  where: {
    clubId: input.clubId
  },
  select
})
```

I've tried to simplify these a little for the sake of making life a bit easier, sorry for the formatting!

```
model Member {
  id               String       @id @default(uuid())
  friendlyId  String
  userId       String
  user          User         @relation(fields: [userId], references: [id])
  memberships Membership[]
}

model User {
  id        String     @id @default(uuid())
  name  String
}

model Membership {
  id                String     @id @default(uuid())
  status         String
  memberId  String
  member     Member @relation(fields: [memberId], references: [id])
}
```

**Comment by janpio** [comment] 2024-06-08 20:52
Quick attempt seems to show the chunking is working as expected for me:
```
"SELECT `main`.`Member`.`id`, `main`.`Member`.`friendlyId`, `main`.`Member`.`userId` FROM `main`.`Member` WHERE 1=1 ORDER BY `main`.`Member`.`id` ASC LIMIT ? OFFSET ?"
"SELECT `main`.`Membership`.`id`, `main`.`Membership`.`status`, `main`.`Membership`.`memberId` FROM `main`.`Membership` WHERE `main`.`Membership`.`memberId` IN (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?) LIMIT ? OFFSET ?"
"SELECT `main`.`Membership`.`id`, `main`.`Membership`.`status`, `main`.`Membership`.`memberId` FROM `main`.`Membership` WHERE `main`.`Membership`.`memberId` IN (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?) LIMIT ? OFFSET ?"
"SELECT `main`.`User`.`id`, `main`.`User`.`name` FROM `main`.`User` WHERE `main`.`User`.`id` IN (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?) LIMIT ? OFFSET ?"
"SELECT `main`.`User`.`id`, `main`.`User`.`name` FROM `main`.`User` WHERE `main`.`User`.`id` IN (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?) LIMIT ? OFFSET ?"
```

This is with 150 entries and then also reading 150 back.

Are you sure you are on 5.15.0?

**Comment by andrewcashmore** [comment] 2024-06-12 14:03
Hey @janpio, I double checked and I'm definitely on 5.15.0, I'll try to put together an example to reproduce it. Thanks for your help so far.

**Comment by andrewcashmore** [comment] 2024-06-13 13:04
Hey @janpio I've been doing some more digging, it looks like the inclusion of a subquery is what pushes it over the edge. Example like below, I'll hopefully have a working example on how to reproduce shortly.

```
const select = {
  user: {
    ...
  },
  medicals: {
    where: {
      OR: [
        { expiryDate: { gte: new Date() } }
      ],
    }
  }
}
```

**Comment by janpio** [comment] 2024-06-13 13:07
That would be amazing. Just open a new issue with that information when you get it. The problem definitely seems to happen less often after the previous fix, but it seems we didn't get all the instances yet. Let's make that happen.
