### ISSUE TITLE
Importing with `createdAt` system field not working

### ISSUE THREAD

**Issue by andruxnet** [prisma/prisma#3856] opened 2019-01-13 20:49 UTC
I'm trying to import some data where the `createdAt` field is needed for several of my app's features.

I found [this section](https://www.prisma.io/docs/reference/service-configuration/data-modelling-(sdl)-eiroozae8u#system-fields) in the docs where it says modifying that field should be possible when importing data, however, when I run `prisma seed` it tells me that `Field 'createdAt' is not defined in the input type 'UserCreateInput'.`.

Here's the section mentioned above:
> The values of these fields are currently read-only in the GraphQL API (except when importing data) but will be made configurable in the future.

This is my current setup:

```
# prisma.yml
endpoint: ${env:PRISMA_ENDPOINT}
datamodel: datamodel.graphql
secret: ${env:PRISMA_SECRET}
seed:
  import: ./src/seed.graphql
hooks:
  post-deploy:
  - graphql get-schema -p prisma
```

```
# seed.graphql
mutation {
  createUser(
    data: {
      email: "me@email.com"
      createdAt: "2018-11-21T07:00:00.000Z"
      ...
    }
  )
  {
    id
    email
  }
}
```

Am I missing something here?

**Comment by andruxnet** [comment] 2019-01-14 18:42
I have an update for this.. I added a few users to my db, then exported them using `prisma export`, and then, I modified the `createdAt` field in the exported json file, then ran `prisma import --data` -- to use the NDF format instead -- and it did work correctly. So, I guess "import mode" means using the NDF format exclusively...

I already have a migration script to build the graphql query, I guess I need to make it generate the json files as NDF instead... but I have a question: are we going to  be able to to this using the graphql file in the near future? if so, is there an estimated timeframe where this would be possible?

**Comment by do4gr** [comment] 2019-01-22 16:07
Hey @andruxnet, 

your observation is correct, when using normal mutations (like `seed` uses) `createdAt` and `updatedAt` are defined as system fields and not user writable. They won't be in the generated schema and query providing them will be rejected as invalid. 

The import/export workflow using NDF does allow you to provide these values as well as ids. 

We'll have a look whether we can be more explicit about this in the documentation. Sorry for the confusion and late response!

**Comment by nikolasburk** [comment] 2019-01-24 07:48
Hey @andruxnet, I've improved the docs for that topic and hopefully clarified that this only works when importing data in [this](https://github.com/prisma/prisma/pull/3918) PR.

@pantharshit00, I believe this issue can be closed as we already have a pending feature request for that feature [here](https://github.com/prisma/prisma/issues/1278).

**Comment by pantharshit00** [comment] 2019-01-24 08:31
Alrighty, closing as duplicate of #1278

**Closed by pantharshit00** 2019-01-24 08:31 UTC
Labels: area/api, kind/feature
