### ISSUE TITLE
Make migrations flat

### ISSUE THREAD

**Issue by rouzbehsbz** [prisma/prisma#11548] opened 2022-02-01 12:45 UTC
Hi,
After a while, the number of magrites becomes very large and takes up space. Isn't it better to add a new feature that can make magrites that have no problems and have been checked,  flat (in one file) ?

**Comment by eduhenke** [comment] 2022-02-01 13:23
Related to https://github.com/prisma/prisma/issues/5714 and https://github.com/prisma/prisma/issues/5226

**Comment by pantharshit00** [comment] 2022-02-01 18:13
As pointed by @eduhenke, I am going to close this as a duplicate of https://github.com/prisma/prisma/issues/5714.

**Closed by pantharshit00** 2022-02-01 18:13 UTC
