### ISSUE TITLE
Mocking using mockDeep produces a circular dependency error

### ISSUE THREAD

**Issue by richardweaver** [prisma/prisma#7065] opened 2021-05-12 20:10 UTC
### Bug description

I am trying to mock Prisma in a Nest.js project. Following the instructions in the docs I implemented a `context.ts` file and am getting a compiler error relating to the use of `mockDeep`.

<img width="1369" alt="Screenshot 2021-05-12 at 20 59 26" src="https://user-images.githubusercontent.com/56024126/118036978-23493080-b365-11eb-86ec-38ebaaa4b11a.png">

### How to reproduce

1. Generate @prisma/client
2. Create a context.ts file as per the docs
<img width="554" alt="Screenshot 2021-05-12 at 21 05 59" src="https://user-images.githubusercontent.com/56024126/118037591-f77a7a80-b365-11eb-97fa-096aa6318d1e.png">

### Prisma information

```
generator client {
  provider = "prisma-client-js"
  binaryTargets = ["native"]
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

model Channel {
  id                  Int                   @id @default(autoincrement())
  name                String                @unique @db.VarChar(50)
  itemWebChannelId    String?               @db.VarChar(16) @map("item_web_channel_id")
  orderChannelId      String?               @db.VarChar(16) @map("order_channel_id")
  createdAt           DateTime              @default(now()) @map("created_at")
  updatedAt           DateTime              @default(now()) @updatedAt @map("updated_at")
  productDefinitions  ProductDefinition[]
  @@map("channels")
  @@index([itemWebChannelId], name: "channels_item_web_channel_id_index")
  @@index([orderChannelId], name: "channels_order_channel_id_index")
}

model ProductDefinition {
  id                           Int       @id @default(autoincrement())
  sku                          String    @unique @db.VarChar(8)
  channelId                    Int?      @map("channel_id")
  internalName                 String    @db.VarChar(50) @map("internal_name")
  consumerName                 String?   @db.VarChar(128) @map("consumer_name")
	@@map("product_definitions")
  @@unique([sku, channelId], name: "product_definitions_sku_channel_id_unique")
  @@index([sku], name: "product_definitions_sku_index")
}

model User {
  id            Int      @id @default(autoincrement())
  email         String   @unique @db.VarChar(128)
  passwordHash  String?  @db.VarChar(256) @map("password_hash")
  createdAt     DateTime @default(now()) @map("created_at")
  updatedAt     DateTime @default(now()) @updatedAt @map("updated_at")
	@@map("users")
}

```

### Environment & setup

- OS: Mac OS
- Database: PostgreSQL
- Node.js version: 14.5
- Prisma version: 2.22.1
- jest-mock-extended: 1.0.14

```
prisma               : 2.22.1
@prisma/client       : 2.22.1
Current platform     : darwin
Query Engine         : query-engine 60cc71d884972ab4e897f0277c4b84383dddaf6c (at node_modules/@prisma/engines/query-engine-darwin)
Migration Engine     : migration-engine-cli 60cc71d884972ab4e897f0277c4b84383dddaf6c (at node_modules/@prisma/engines/migration-engine-darwin)
Introspection Engine : introspection-core 60cc71d884972ab4e897f0277c4b84383dddaf6c (at node_modules/@prisma/engines/introspection-engine-darwin)
Format Binary        : prisma-fmt 60cc71d884972ab4e897f0277c4b84383dddaf6c (at node_modules/@prisma/engines/prisma-fmt-darwin)
Default Engines Hash : 60cc71d884972ab4e897f0277c4b84383dddaf6c
Studio               : 0.379.0
```

**Comment by pantharshit00** [comment] 2021-05-16 20:24
I am unable to reproduce this with a simple example: 
![image](https://user-images.githubusercontent.com/22195362/118411543-bb6f4e80-b6b2-11eb-928b-4bb98ce2b2ad.png)


Can you please share a reproduction inside of a git repository?

**Comment by pantharshit00** [comment] 2021-05-16 20:24
cc/ @molebox re testing docs related.

**Comment by molebox** [comment] 2021-05-17 06:39
Thanks @pantharshit00. Hey @richardweaver if you could provide a sample repo that would be awesome. In the meantime i can try and spin up a nest.js project and check if i can replicate the error.

**Comment by molebox** [comment] 2021-05-17 07:47
Hey @richardweaver , i was able to reproduce your error in a nestjs project setup to mock the Prisma Client. I dont have a concrete solution for you just yet but in the meantime you can `ts-ignore` the return statement from the `createMockContext` function. This will allow you to use the context without any errors. Ill ask around with the team and come back to you if we can get to the bottom of the actual error.

```
export const createMockContext = (): MockContext => {
  // @ts-ignore
  return {
    prisma: mockDeep<PrismaClient>(),
  }
}
```

**Comment by richardweaver** [comment] 2021-05-17 08:42
@molebox Thanks for the tip, helpful.

**Comment by molebox** [comment] 2021-05-17 14:17
Hey @richardweaver, good news, ive figured out what the issue was 😀 You'll need to explicitly add `"strictNullChecks": true` to your tsconfig. This is to do with how under the hood we have `undefined | null` logic. Im going to make a note to document this.

**Comment by molebox** [comment] 2021-05-24 06:17
Im going to close this now as the issue has been solved. ✌️

**Closed by molebox** 2021-05-24 06:17 UTC
Labels: kind/docs
