### ISSUE TITLE
Choose database by env

### ISSUE THREAD

**Issue by yovanoc** [prisma/prisma#221] opened 2019-07-23 14:10 UTC
When we follow this part of the website:

![image](https://user-images.githubusercontent.com/7302317/61719009-638c8880-ad64-11e9-8f23-299ef8caeac2.png)

we have that error because apparently we have to define both env variables

https://gist.github.com/yovanoc/a89db13c7e655e38866b815bc170ceb2

**Comment by sorenbs** [comment] 2020-05-19 08:13
I am closing this as a duplicate of https://github.com/prisma/prisma/issues/1487

Please let me know if you feel these issues address different use cases. Thanks 🙏

**Closed by sorenbs** 2020-05-19 08:13 UTC
Labels: kind/feature, topic: env, topic: schema
