### ISSUE TITLE
called `Option::unwrap()` on a `None` value

### ISSUE THREAD

**Issue by LiJoah** [prisma/prisma#22681] opened 2024-01-17 02:07 UTC
### Bug description
```
thread 'tokio-runtime-worker' panicked at query-engine/core/src/interpreter/query_interpreters/nested_read.rs:232:50:
called `Option::unwrap()` on a `None` value
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
prisma:error 
Invalid `prisma.solutionUserRequirements.count()` invocation:


called `Option::unwrap()` on a `None` value

This is a non-recoverable error which probably happens when the Prisma Query Engine has a panic.
```

### Prisma information

```prisma
model SolutionUserRequirements {
  id Int @id @default(autoincrement()) @db.UnsignedInt

  userId Int @map("user_id")

  userName String @map("user_name")

  solutionId Int @map("solution_id")

  projectId Int? @map("project_id")

  reviewId Int? @map("review_id")

  projectName String? @map("project_name")

  departmentId Int? @map("department_id")

  department String? @map("department")

  // 进度: 0, 已申请， 1 受理中， 2： 进行中， 3 已完成， 4： 异常关闭
  state Int @map("state")

  pmUserName String? @map("pm_user_name")

  pmUserId Int? @map("pm_user_id") @db.UnsignedInt

  createdAt DateTime? @default(now()) @map("created_at") @db.DateTime(0)

  updatedAt DateTime? @updatedAt @map("updated_at") @db.DateTime(0)

  solution Solutions @relation(fields: [solutionId], references: [id])

  userInfo Users @relation("user", fields: [userId], references: [userId])

  pmUserInfo Users? @relation("pm", fields: [pmUserId], references: [userId])

  @@index([userId, solutionId])
  @@map("grp_compass_solution_user_requirements")
}

```

```ts
const {
    pageSize = '20',
    page = '1',
    department = '',
    projectName = '',
    userName = '',
  } = query;

  const ps = parseInt(pageSize, 10);
  const p = parseInt(page, 10);
  const skip = (p - 1) * ps;
  const take = ps;

  console.log(skip, take);

  const where: Prisma.SolutionUserRequirementsFindManyArgs['where'] = {};

  if (projectName) {
    where.projectName = { contains: projectName };
  }
  if (department) {
    where.department = { contains: department };
  }
  if (userName) {
    where.userName = { contains: userName };
  }

  console.log(where);

  try {
    const [total, requirements] = await prisma.$transaction([
      prisma.solutionUserRequirements.count(),
      prisma.solutionUserRequirements.findMany({
        include: { userInfo: true, solution: true, pmUserInfo: true },
      }),
    ]);
    return { total, requirements };
  } catch (error) {
    console.error(error);
    return { total: 0, requirements: [] };
  }
```

### Environment & setup

FROM node:18-alpine

### Prisma Version

```

```

**Comment by LiJoah** [comment] 2024-01-17 02:08
prisma: 5.8.1

**Comment by LiJoah** [comment] 2024-01-17 02:16
mysql;

**Comment by Jolg42** [comment] 2024-01-17 08:58
Note: The error is similar to https://github.com/prisma/prisma/issues/21974

**Comment by SevInf** [comment] 2024-01-18 15:58
Hi @LiJoah.
Can you share the whole schema? In particular, your query uses `Solutions` and `Users` models that you have not provided.  Do you know what data is in the DB when it happens? Or schema and code snippet you've sent and it reproduces reliable regardless of the actual contents of the DB?

**Comment by jkomyno** [comment] 2024-01-19 11:14
Background note: this is a duplicate of https://github.com/prisma/prisma/issues/19968.

**Closed** 2024-01-19 11:17 UTC
Labels: bug/0-unknown, kind/bug, team/client, topic: rust panic, topic: nested read
