### ISSUE TITLE
Client Extensions Destroy Typescript Compilation Performance (and Intellisense)

### ISSUE THREAD

**Issue by iamnafets** [prisma/prisma#23369] opened 2024-03-05 18:43 UTC
### Bug description

Adding simple client extensions blows up `check time` reported in `tsc --extendedDiagnostics` on a basic project from 0.12s to 1.79s, destroying intellisense performance.

Here's the client with extensions:
```typescript
  const p = new RawPrismaClient({
    datasources: {
      db: {
        url: env.DATABASE_URL ?? "", // This will be undefined during builds
      },
    },
    log:
      (env.NODE_ENV === "development" ? ["error", "warn"] : ["error"]) as Array<Prisma.LogLevel>,
  }).$extends({
    name: "Extensions",
    result: {
      user: {
        realName_DANGEROUS_DO_NOT_USE: { // the users real name, should never be used unless you're an admin and know what you're doing
          needs: { name: true},
          compute(user) {
            return user.name
          }
        },
        name: { // the name that should be used throughout. It will correctly be the real name or the anonymous name based on the user's settings
          needs: { name: true, email: true, anonymous: true, id: true },
          compute(user) {
            const anonymousName = makeAnonymousName(user.id);
            return user.anonymous
              ? anonymousName
              : user.name ?? user.email?.split("@")[0] ?? anonymousName;
          }
        },
        anonymousName: { // should only be used if you really want an anonymous name even if they are not anonymous. Like with comments on the blog
          needs: { id: true },
          compute(user) {
            return makeAnonymousName(user.id);
          }
        }
      }
    }
  });
```

`@typescript/analyze-trace` then shows a hotspot (doesn't exist when client extensions aren't present)
```
Hot Spots
└─ Check file ********** /apps/worker/worker.ts (1334ms)
   └─ Check variable declaration from (line 28, char 7) to (line 40, char 2) (1313ms)
      └─ Compare types 22909 and 109 (1301ms)
         └─ Compare types 22527 and 415 (1301ms)
            └─ Compare types 22527 and 359 (1130ms)
               └─ Compare types 22520 and 359 (1130ms)
                  ├─ {"id":22520,"kind":"AnonymousType","location":{"path":"*********** client/runtime/library.d.ts","line":876,"char":5}}
                  └─ {"id":359,"kind":"AnonymousType","location":{"path":"*********** client/runtime/library.d.ts","line":876,"char":5}}
```

Happy to share schemas and/or sponsor a fix.

### How to reproduce

Add client extensions to a project with a few dozen models.

### Prisma information

Happy to share privately.

### Environment & setup

Mac
tsc version 5.1.3
prisma 5.10.2

### Prisma Version

```
prisma                  : 5.10.2
@prisma/client          : 5.10.2
Computed binaryTarget   : darwin-arm64
Operating System        : darwin
Architecture            : arm64
Node.js                 : v20.9.0
Query Engine (Node-API) : libquery-engine 5a9203d0590c951969e85a7d07215503f4672eb9 (at node_modules/@prisma/engines/libquery_engine-darwin-arm64.dylib.node)
Schema Engine           : schema-engine-cli 5a9203d0590c951969e85a7d07215503f4672eb9 (at node_modules/@prisma/engines/schema-engine-darwin-arm64)
Schema Wasm             : @prisma/prisma-schema-wasm 5.10.0-34.5a9203d0590c951969e85a7d07215503f4672eb9
Default Engines Hash    : 5a9203d0590c951969e85a7d07215503f4672eb9
Studio                  : 0.499.0
```

**Comment by Jolg42** [comment] 2024-03-06 10:23
@iamnafets Thanks for the issue. I'm curious to know more about your setup here, since I saw you mentioned that you were "Happy to share privately.", please email `schemas at prisma.io`.

Because before trying to fix this, we would first need to reproduce it, so anything that would help to reproduce it easily is very welcome, like a minimal reproduction repo for example, because it's likely related to your specific project, and could be hard to reproduce without it.

**Comment by Jolg42** [comment] 2024-03-06 10:23
Just curious, did you try other TypeScript versions and observed the same results?

**Comment by SevInf** [comment] 2024-03-21 09:21
Hey @iamnafets  ,

Did you get a chance to have a look at my colleagues previous comment or send the schema to the email address they mention? It'd be helpful for us to move your issue forward.

Without further information, we'll have to close this issue. Thank you 🙏

**Comment by jkomyno** [comment] 2024-04-08 09:18
Hi @iamnafets, we're closing this issue as we didn't receive the reproduction we needed to investigate this.
Please leave a comment whenever you manage to provide such reproduction, so we can re-open this issue. Thanks!

**Closed by jkomyno** 2024-04-08 09:18 UTC
Labels: bug/0-unknown, kind/bug, topic: prisma-client, topic: client types, tech/typescript, team/client, topic: type performance, topic: clientExtensions, topic: typescript
