### ISSUE TITLE
engine support for 'deepin' os

### ISSUE THREAD

**Issue by Diaa-Hassan** [prisma/prisma#22024] opened 2023-11-18 12:36 UTC
### Bug description

prisma:warn Prisma doesn't know which engines to download for the Linux distro "deepin". Falling back to Prisma engines built "debian".

### How to reproduce

no steps needed

### Prisma information

```
generator client {
  provider      = "prisma-client-js"
  binaryTargets = ["native", "debian-openssl-1.1.x"]
}
```

### Environment & setup

```
$ cat /etc/os-release

PRETTY_NAME="Deepin 20.9"
NAME="Deepin"
VERSION="20.9"
VERSION_CODENAME="apricot"
ID=Deepin
HOME_URL="https://www.deepin.org/"
```

### Prisma Version

```
❯ prisma -v

prisma:warn Prisma doesn't know which engines to download for the Linux distro "deepin". Falling back to Prisma engines built "debian".
Please report your experience by creating an issue at https://github.com/prisma/prisma/issues so we can add your distro to the list of known supported distros.
Environment variables loaded from .env
prisma:warn Prisma doesn't know which engines to download for the Linux distro "deepin". Falling back to Prisma engines built "debian".
Please report your experience by creating an issue at https://github.com/prisma/prisma/issues so we can add your distro to the list of known supported distros.
prisma                  : 5.6.0
@prisma/client          : 5.6.0
Computed binaryTarget   : debian-openssl-1.1.x
Operating System        : linux
Architecture            : x64
Node.js                 : v18.18.2
Query Engine (Node-API) : libquery-engine e95e739751f42d8ca026f6b910f5a2dc5adeaeee (at ../../../../../../home/linuxbrew/.linuxbrew/lib/node_modules/prisma/node_modules/@prisma/engines/libquery_engine-debian-openssl-1.1.x.so.node)
Schema Engine           : schema-engine-cli e95e739751f42d8ca026f6b910f5a2dc5adeaeee (at ../../../../../../home/linuxbrew/.linuxbrew/lib/node_modules/prisma/node_modules/@prisma/engines/schema-engine-debian-openssl-1.1.x)
Schema Wasm             : @prisma/prisma-schema-wasm 5.6.0-32.e95e739751f42d8ca026f6b910f5a2dc5adeaeee
Default Engines Hash    : e95e739751f42d8ca026f6b910f5a2dc5adeaeee
Studio                  : 0.495.0
```

```[tasklist]
### Tasks
- [ ] support for `deepin` os
```

**Comment by SevInf** [comment] 2023-11-20 14:02
Duplicate of #19157.
Let's continue discussion there.

**Closed by SevInf** 2023-11-20 14:02 UTC
Labels: kind/bug
