### ISSUE TITLE
Cursor based pagination with soft delete

### ISSUE THREAD

**Issue by kadeer** [prisma/prisma#10455] opened 2021-11-26 13:22 UTC
## Bug description

I have a model defined below I'm trying to paginate using a cursor. When a row in the application is deleted, the deletion is implemented using a soft delete marking the `delete_date` as `NOW()`. In the query generated to build the `order_cmp` subquery used to implement the pagination, is there a way to pass other where conditions to be passed into the subquery? The subquery returns rows including deleted rows because the subquery generated doesn't add a `delete_date IS NOT NULL` condition. Is there a way to achieve this?

```
model investigator_note {
  id                BigInt              @id @default(autoincrement()) @db.UnsignedBigInt
  body              String?             @db.Text
  is_jeli_suggested Int                 @default(0) @db.UnsignedTinyInt
  customer_id       Int                 @db.UnsignedInt
  investigation_id  Int                 @db.UnsignedInt
  ts                DateTime?           @default(now()) @db.Timestamp(0)
  thread_id         String?             @db.VarChar(255)
  create_date       DateTime            @default(now()) @db.Timestamp(0)
  update_date       DateTime            @default(now()) @db.Timestamp(0)
  delete_date       DateTime?           @db.Timestamp(0)
  created_by        Int                 @db.UnsignedInt
  updated_by        Int?                @db.UnsignedInt
  deleted_by        Int?                @db.UnsignedInt
  jeli_user         jeli_user           @relation(fields: [created_by], references: [id], onUpdate: Restrict, map: "investigator_note_ibfk_3")
  customer          customer            @relation(fields: [customer_id], references: [id], onUpdate: Restrict, map: "investigator_note_ibfk_1")
  investigation     InvestigationModel2 @relation(fields: [investigation_id, customer_id], references: [id, customer_id], onUpdate: Restrict, map: "investigator_note_ibfk_2")
  note_object       note_object[]

  @@unique([customer_id, investigation_id, ts])
  @@index([created_by], map: "created_by")
  @@index([customer_id], map: "customer_id")
  @@index([investigation_id, customer_id], map: "investigation_id")
}
```

Here's the query generated by PrismaClient:
```
SELECT `jeli`.`investigator_note`.`id`,
       `jeli`.`investigator_note`.`body`,
       `jeli`.`investigator_note`.`is_jeli_suggested`,
       `jeli`.`investigator_note`.`customer_id`,
       `jeli`.`investigator_note`.`investigation_id`,
       `jeli`.`investigator_note`.`ts`,
       `jeli`.`investigator_note`.`thread_id`,
       `jeli`.`investigator_note`.`create_date`,
       `jeli`.`investigator_note`.`update_date`,
       `jeli`.`investigator_note`.`delete_date`,
       `jeli`.`investigator_note`.`created_by`,
       `jeli`.`investigator_note`.`updated_by`,
       `jeli`.`investigator_note`.`deleted_by`
FROM `jeli`.`investigator_note`,
     (SELECT `jeli`.`investigator_note`.`ts` AS `investigator_note_ts_0`
      FROM `jeli`.`investigator_note`
      WHERE (`jeli`.`investigator_note`.`customer_id`, `jeli`.`investigator_note`.`investigation_id`,
             `jeli`.`investigator_note`.`ts`) = (1, 368, '2021-04-05 13:16:40 UTC')) AS `order_cmp`
WHERE (`jeli`.`investigator_note`.`ts` IS NOT NULL AND `jeli`.`investigator_note`.`customer_id` = 1 AND
       `jeli`.`investigator_note`.`investigation_id` = 368 AND `jeli`.`investigator_note`.`delete_date` IS NULL AND
       (`jeli`.`investigator_note`.`ts` >= `order_cmp`.`investigator_note_ts_0` OR
        `jeli`.`investigator_note`.`ts` IS NULL OR `order_cmp`.`investigator_note_ts_0` IS NULL))
ORDER BY `jeli`.`investigator_note`.`ts` ASC;
```

## Expected behavior

What I want to generate:
```diff
SELECT `jeli`.`investigator_note`.`id`,
       `jeli`.`investigator_note`.`body`,
       `jeli`.`investigator_note`.`is_jeli_suggested`,
       `jeli`.`investigator_note`.`customer_id`,
       `jeli`.`investigator_note`.`investigation_id`,
       `jeli`.`investigator_note`.`ts`,
       `jeli`.`investigator_note`.`thread_id`,
       `jeli`.`investigator_note`.`create_date`,
       `jeli`.`investigator_note`.`update_date`,
       `jeli`.`investigator_note`.`delete_date`,
       `jeli`.`investigator_note`.`created_by`,
       `jeli`.`investigator_note`.`updated_by`,
       `jeli`.`investigator_note`.`deleted_by`
FROM `jeli`.`investigator_note`,
     (SELECT `jeli`.`investigator_note`.`ts` AS `investigator_note_ts_0`
      FROM `jeli`.`investigator_note`
      WHERE (`jeli`.`investigator_note`.`customer_id`, `jeli`.`investigator_note`.`investigation_id`,
-            `jeli`.`investigator_note`.`ts`) = (1, 368, '2021-04-05 13:16:40 UTC')) AS `order_cmp`
+            `jeli`.`investigator_note`.`ts`) = (1, 368, '2021-04-05 13:16:40 UTC') AND `jeli`.`investigator_note`.`delete_date` IS NULL) AS `order_cmp`
WHERE (`jeli`.`investigator_note`.`ts` IS NOT NULL AND `jeli`.`investigator_note`.`customer_id` = 1 AND
       `jeli`.`investigator_note`.`investigation_id` = 368 AND `jeli`.`investigator_note`.`delete_date` IS NULL AND
       (`jeli`.`investigator_note`.`ts` >= `order_cmp`.`investigator_note_ts_0` OR
        `jeli`.`investigator_note`.`ts` IS NULL OR `order_cmp`.`investigator_note_ts_0` IS NULL))
ORDER BY `jeli`.`investigator_note`.`ts` ASC;
```

## Environment & setup

- OS: macOS
- Database: PostgreSQL
- Node.js version: v12.18.1
- Prisma version:

```
prisma                  : 3.5.0
@prisma/client          : 3.5.0
Current platform        : darwin
Query Engine (Node-API) : libquery-engine 78a5df6def6943431f4c022e1428dbc3e833cf8e (at node_modules/@prisma/engines/libquery_engine-darwin.dylib.node)
Migration Engine        : migration-engine-cli 78a5df6def6943431f4c022e1428dbc3e833cf8e (at node_modules/@prisma/engines/migration-engine-darwin)
Introspection Engine    : introspection-core 78a5df6def6943431f4c022e1428dbc3e833cf8e (at node_modules/@prisma/engines/introspection-engine-darwin)
Format Binary           : prisma-fmt 78a5df6def6943431f4c022e1428dbc3e833cf8e (at node_modules/@prisma/engines/prisma-fmt-darwin)
Default Engines Hash    : 78a5df6def6943431f4c022e1428dbc3e833cf8e
Studio                  : 0.439.0
```

Update: the unique definition was slightly updated to reflect the code from the project.

**Comment by pantharshit00** [comment] 2021-11-26 17:53
Can you please share the actual client call which leads to that query? That would help in debugging.

**Comment by kadeer** [comment] 2021-11-26 18:07
Thank you for your attention. Here's a simplified version from my project:

```
prisma.investigator_note.findMany({
  where: {
    customer_id: customerId,
    investigation_id: investigationId,
    delete_date: null,
  },

  orderBy: { ts: 'asc' },
  skip: 1,
  take: 10,
  cursor:
    // after & before are cursor strings 
    after || before
      ? {
          customer_id_investigation_id_ts: {
            customer_id: customerId,
            investigation_id: investigationId,
            ts: new Date(cursor.ts!),
          },
        }
      : undefined
})
```

Thank you.

**Comment by Jolg42** [comment] 2022-09-07 11:02
> The subquery returns rows including deleted rows because the subquery generated doesn't add a delete_date IS NOT NULL condition.

I can't reproduce this with the version mentioned (`3.5.0`)

The query is like mentioned in the description
```
 SELECT `10455`.`investigator_note`.`id`,
       `10455`.`investigator_note`.`body`,
       `10455`.`investigator_note`.`is_jeli_suggested`,
       `10455`.`investigator_note`.`customer_id`,
       `10455`.`investigator_note`.`investigation_id`,
       `10455`.`investigator_note`.`ts`,
       `10455`.`investigator_note`.`thread_id`,
       `10455`.`investigator_note`.`create_date`,
       `10455`.`investigator_note`.`update_date`,
       `10455`.`investigator_note`.`delete_date`,
       `10455`.`investigator_note`.`created_by`,
       `10455`.`investigator_note`.`updated_by`,
       `10455`.`investigator_note`.`deleted_by`
FROM   `10455`.`investigator_note`,
       (SELECT `10455`.`investigator_note`.`ts` AS `investigator_note_ts_0`
        FROM   `10455`.`investigator_note`
        WHERE
(
`10455`.`investigator_note`.`customer_id`, `10455`.`investigator_note`.`investigation_id`, `10455`.`investigator_note`.`ts` ) = ( ?, ?, ? )) AS `order_cmp`
WHERE  ( `10455`.`investigator_note`.`customer_id` = ?
         AND `10455`.`investigator_note`.`investigation_id` = ?
         AND `10455`.`investigator_note`.`delete_date` IS NULL
         AND ( `10455`.`investigator_note`.`ts` >=
               `order_cmp`.`investigator_note_ts_0`
                OR `10455`.`investigator_note`.`ts` IS NULL
                OR `order_cmp`.`investigator_note_ts_0` IS NULL ) )
ORDER  BY `10455`.`investigator_note`.`ts` ASC  
```

But this Prisma Client Query filters out the deleted items successfully:
```
import { PrismaClient } from "@prisma/client";

async function main() {
  const prisma = new PrismaClient({
    log: [
      {
        emit: "event",
        level: "query",
      },
    ],
  });

  prisma.$on("query", (query) => {
    console.log(query);
  });

  const createNote = await prisma.investigator_note.create({
    data: {
      customer_id: 1,
      created_by: 1,
      investigation_id: 1,
      delete_date: new Date("2021-01-01"),
      deleted_by: 1,
    },
  });
  console.log({ createNote });

  const data = await prisma.investigator_note.findMany({
    where: {
      customer_id: 1,
      investigation_id: 1,
      // if I comment this line, then deleted items are returned
      delete_date: null,
    },
    orderBy: { ts: "asc" },
    skip: 1,
    take: 10,
    cursor: {
      customer_id_investigation_id_ts: {
        customer_id: 1,
        investigation_id: 1,
        ts: new Date("2022-09-07T10:47:50.000Z"),
      },
    },
  });
  console.log({ data });

  prisma.$disconnect();
}

main();
```

@kadeer If this is still an issue could you help us and provide a reproduction?
If this is not an issue anymore, let's close this.

**Comment by millsp** [comment] 2023-07-20 00:07
Hey @kadeer,

We unfortunately can't reproduce your issue without further information. Could you please have a look at @Jolg42's comment so that we can try fixing your issue?

Thank you 🙏

**Comment by millsp** [comment] 2023-07-27 13:36
We haven't heard back about this issue, so we'll close it for now as we need a few more details to be able to dig into this problem. Don't hesitate to add more details in a new comment, and we'll be happy to reopen the issue. Thank you! :pray:

**Closed by millsp** 2023-07-27 13:36 UTC
Labels: bug/0-unknown, kind/bug, topic: broken query, team/client
