### ISSUE TITLE
Docker latest/alpine version

### ISSUE THREAD

**Issue by guigaoliveira** [prisma/prisma#4478] opened 2019-05-01 21:27 UTC
**Is your feature request related to a problem? Please describe.**
I think it's a bit bad to have to upgrade the prism to a specific version whenever you're developing.

**Describe the solution you'd like**
In docker hub I think there could be at least the "latest" version for so whenever I download a docker image it will be the most current version. The alpine version would be a bonus.

**Comment by pantharshit00** [comment] 2019-05-02 06:43
Closing as a duplicate of https://github.com/prisma/prisma/issues/3244

**Closed by pantharshit00** 2019-05-02 06:43 UTC

**Comment by SergeiMeza** [comment] 2019-05-11 05:45
Prisma is at an active development stage right now. They are releasing a new version every two weeks, so to not break your code, it is best practice to set up the tag manually.
