### ISSUE TITLE
rawQuery ERROR:  insufficient data left in message; when casting to interval

### ISSUE THREAD

**Issue by rmzg** [prisma/prisma#15199] opened 2022-09-06 05:59 UTC
### Bug description

The following query:
```
await db.$queryRaw`
INSERT INTO "QuickbooksTokens"
("accessToken", "refreshToken", "accessExpiration", "refreshExpiration")
VALUES (
${access},
${refresh},
NOW() + ${accessExpiration}::INTERVAL,
    NOW() + INTERVAL '24 hours'
  )
  `

```

Produces the postgresql error:
```
ERROR:  insufficient data left in message
CONTEXT:  unnamed portal parameter $3
```

Where "accessToken" and "refreshToken" are "String" and "accessExpiration" and "refreshExpiration" are "DateTime".
If you change it to the following:

```
  await db.$queryRaw`
  INSERT INTO "Tokens"
    ("accessToken", "refreshToken", "accessExpiration", "refreshExpiration")
  VALUES (
    ${access},
${refresh},
NOW() + ${accessExpiration}::TEXT::INTERVAL,
    NOW() + INTERVAL '24 hours'
)
  `
```

Then it works fine. 

### How to reproduce

Create table with datetime field, try to run a `$queryRaw` using an integer interval.

### Prisma information

```prisma
model Tokens {
  id Int @id @default(autoincrement())
  accessToken String
  refreshToken String
  accessExpiration DateTime
  refreshExpiration DateTime
}
```

```ts
// Add your code using Prisma Client
```

### Environment & setup

- OS: Debian
- Database: Postgresql14
- Node.js version: v18.7.0

### Prisma Version

```
❯ node_modules/.bin/prisma -v
Environment variables loaded from .env
prisma                  : 3.15.2
@prisma/client          : 3.15.2
Current platform        : debian-openssl-3.0.x
Query Engine (Node-API) : libquery-engine 461d6a05159055555eb7dfb337c9fb271cbd4d7e (at node_modules/@prisma/engines/libquery_engine-debian-openssl-3.0.x.so.node)
Migration Engine        : migration-engine-cli 461d6a05159055555eb7dfb337c9fb271cbd4d7e (at node_modules/@prisma/engines/migration-engine-debian-openssl-3.0.x)
Introspection Engine    : introspection-core 461d6a05159055555eb7dfb337c9fb271cbd4d7e (at node_modules/@prisma/engines/introspection-engine-debian-openssl-3.0.x)
Format Binary           : prisma-fmt 461d6a05159055555eb7dfb337c9fb271cbd4d7e (at node_modules/@prisma/engines/prisma-fmt-debian-openssl-3.0.x)
Default Engines Hash    : 461d6a05159055555eb7dfb337c9fb271cbd4d7e
Studio                  : 0.462.0
```

**Comment by jkomyno** [comment] 2022-09-06 09:43
Hi @rmzg, we're currently not able to reproduce this locally. May you please provider the values of `access`, `refresh`, `accessExpiration` you're passing to the raw query? Is the `QuickbooksTokens` model different than `Tokens`? If so, can you please add that part of the schema to this issue as well?

Most likely, you have some null character strings in your input, which triggers [this problem](https://www.postgresql.org/message-id/alpine.BSO.2.00.0906031639270.2432%40leary.csoft.net) in Postgres. This is also mentioned on [StackOverflow](https://stackoverflow.com/questions/28308418/postgres-org-postgresql-util-psqlexception-error-insufficient-data-left-in-me).

**Comment by janpio** [comment] 2022-09-23 16:58
Ping @rmzg - can you help us out here please? We want to reproduce this, but are currently not able to without additional information from you. Thanks!

**Comment by rmzg** [comment] 2022-09-23 17:27
I don't have easy access to test this in prisma 4.x at the moment so I'm
going to assume it's fixed later on.

**Comment by janpio** [comment] 2022-09-23 19:05
Ok, closing this for now. If anyone hits the same problem, jsut comment here again and we can reopen and take another look.

**Closed** 2022-09-23 19:05 UTC
Labels: bug/0-unknown, kind/bug, team/client, topic: postgresql
