### ISSUE TITLE
GraphQL many-to-many relationship works for MySQL but not PostgreSQL

### ISSUE THREAD

**Issue by harrison-carter** [prisma/prisma#6803] opened 2021-04-26 16:56 UTC
## Bug description

I created a Discussion topic to cover why I couldn't use `connect` to link an existing record when using `create` for insert a new Model record.

I decided to switch my datasource to MySQL to recreate the same structure with a different database provider. Following the steps I attempted in the [Discussion](https://github.com/prisma/prisma/discussions/6796), I successfully linked the many-to-many relationship I had attempted to create in PostgreSQL.

## How to reproduce

A MySQL and PostgreSQL database is required to recreate this issue.

https://github.com/prisma/prisma/discussions/6796
https://github.com/harrison-carter/prisma_m-to-n_issue

1. Clone the above repo, change the schema connection string to match your database and use `yarn prisma generate`.
2. Create a category record using the mutation

```
"createCategoryData": {
    "name": "NSFW"
  }

mutation NameMutation($createCategoryData: CategoryCreateInput!) {
  createCategory(data: $createCategoryData) {
    name
  }
}
```

3. Create a post record linking the newly created category record via `connect`

```
"createPostData": {
    "name": "Testing",
    "categories": [
      {
        "id": 1
      }
    ]
  }

mutation Mutation($createPostData: PostCreateInput!) {
  createPost(data: $createPostData) {
    id
  }
}
```

4. Run the below query to confirm the two records have been linked

```
query Query {
  posts {
    id
    name
    categories {
      id
      name
    }
  }
}
```

## Expected behavior

In both MySQL and PostgreSQL instances, the data should relate with the same codebase.
With MySQL, the output received confirms that the existing category has been linked.

```
{
  "data": {
    "posts": [
      {
        "id": 1,
        "name": "Testing",
        "categories": [
          {
            "id": 1,
            "name": "NSFW"
          }
        ]
```

Using PostgreSQL, the following error is returned

```
"errors": [
    {
      "message": "\nInvalid `prisma.post.create()` invocation:\n\n\n  Error occurred during query execution:\nConnectorError(ConnectorError { user_facing_error: None, kind: QueryError(Error { kind: Db, cause: Some(DbError { severity: \"ERROR\", parsed_severity: None, code: SqlState(\"42601\"), message: \"syntax error at or near \\\"ON\\\"\", detail: None, hint: None, position: Some(Original(65)), where_: None, schema: None, table: None, column: None, datatype: None, constraint: None, file: Some(\"scan.l\"), line: Some(1053), routine: Some(\"scanner_yyerror\") }) }) })",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "createPost"
      ],
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR",
        "exception": {
          "clientVersion": "2.21.2",
          "stacktrace": [
            "Error: ",
            "Invalid `prisma.post.create()` invocation:",
            "",
            "",
            "  Error occurred during query execution:",
            "ConnectorError(ConnectorError { user_facing_error: None, kind: QueryError(Error { kind: Db, cause: Some(DbError { severity: \"ERROR\", parsed_severity: None, code: SqlState(\"42601\"), message: \"syntax error at or near \\\"ON\\\"\", detail: None, hint: None, position: Some(Original(65)), where_: None, schema: None, table: None, column: None, datatype: None, constraint: None, file: Some(\"scan.l\"), line: Some(1053), routine: Some(\"scanner_yyerror\") }) }) })",
            "    at cb (/Users/harrison.carter/Development/graphql-playground/node_modules/@prisma/client/runtime/index.js:34784:17)",
            "    at processTicksAndRejections (internal/process/task_queues.js:93:5)"
          ]
        }
      }
    }
  ],
  "data": {
    "createPost": null
  }
}
```

## Prisma information

Provided in repo 
https://github.com/harrison-carter/prisma_m-to-n_issue

## Environment & setup

- OS: MacOS
- Database: 
PostgreSQL 9.3.17 on x86_64-unknown-linux-gnu, compiled by gcc (Ubuntu/Linaro 4.6.3-1ubuntu5) 4.6.3, 64-bit
mysql  Ver 15.1 Distrib 10.5.8-MariaDB, for osx10.15 (x86_64) using readline 5.1
- Node.js version: Node v14.15.4
- Prisma version:

```
prisma               : 2.21.2
@prisma/client       : 2.21.2
Current platform     : darwin
Query Engine         : query-engine e421996c87d5f3c8f7eeadd502d4ad402c89464d (at node_modules/@prisma/engines/query-engine-darwin)
Migration Engine     : migration-engine-cli e421996c87d5f3c8f7eeadd502d4ad402c89464d (at node_modules/@prisma/engines/migration-engine-darwin)
Introspection Engine : introspection-core e421996c87d5f3c8f7eeadd502d4ad402c89464d (at node_modules/@prisma/engines/introspection-engine-darwin)
Format Binary        : prisma-fmt e421996c87d5f3c8f7eeadd502d4ad402c89464d (at node_modules/@prisma/engines/prisma-fmt-darwin)
Default Engines Hash : e421996c87d5f3c8f7eeadd502d4ad402c89464d
Studio               : 0.371.0
```

**Comment by pantharshit00** [comment] 2021-05-28 15:23
Hmm, @harrison-carter 

I am unable to reproduce this locally. Can you please try again with the latest version of Prisma?

Sorry for the late reply here.

**Comment by shayan-shojaei** [comment] 2021-07-30 11:17
I'm having the same issue as explained [here](https://stackoverflow.com/questions/68583833/prisma-create-with-nested-connect-throws-error).
I'll try to provide as much information as possible for the reproduction of the issue.


### My schema: ###

```
  model Movie {
  id               String     @id @default(uuid())
  createdAt        DateTime   @default(now()) @map("created_at")
  updatedAt        DateTime   @default(now()) @updatedAt @map("updated_at")
  tmdbId           Int        @unique @map("tmdb_id")
  title            String
  director         String?
  length           Int        @default(0)
  genres           Genre[]    @relation("movies_in_genre", references: [id])
  releaseDate      String?    @default("-") @map("release_date")
  description      String?
  shortDescription String?    @map("short_description")
  posterUrl        String?    @map("poster_url")
  imdbUrl          String?    @map("imdb_url")

  @@map("movies")
}

model Genre {
  id     Int     @id @default(autoincrement())
  name   String  @unique
  movies Movie[] @relation("movies_in_genre", references: [id])

  @@map("genres")
}
```

I'm using prisma as my data provider for a apollo-server graphql API.
and `TMDB` is a module that uses an external rest API.

### The code responsible for the transaction: ###

```javascript
module.exports = {
	Query: {
		search: async (_, { input }, { prisma }) => {
			const results = await TMDB.search(input);
			await validateGenres(prisma);
			return results.map((item) => getMovieItem(item.id, prisma));
		},
		trending: async (_, { page }, { prisma }) => {
			const results = await TMDB.getTrending(page);
			await validateGenres(prisma);
			return results.map((item) => getMovieItem(item.id, prisma));
		},
	},
}
```

---

```javascript
const getMovieItem = async (movieId, prisma) => {
	// see if is already in database
	const movie = await prisma.movie.findUnique({
		where: { tmdbId: movieId },
	});
	if (movie) {
		return movie;
	} else {
		// create and return if doesn't exist
		const details = await TMDB.details(movieId);
		const genresData = details.genres.map((genre) => ({ name: genre.name }));
		return prisma.movie.create({
			data: {
				title: details.title,
				description: details.overview,
				shortDescription: details.tag_line,
				posterUrl: TMDB.getPosterUrl(details.poster_path),
				releaseDate: details.release_date,
				tmdbId: details.id,
				imdbUrl: details.imdb_id,
				length: details.runtime,
				genres: {
					connect: genresData,
				},
			},
			select: {
				tmdbId: true,
				id: true,
				title: true,
				releaseDate: true,
				shortDescription: true,
				description: true,
				length: true,
				imdbUrl: true,
				posterUrl: true,
			},
		});
	}
};

const validateGenres = async (prisma) => {
	// check if genres have already been gathered
	// if not, request them from the api and create in database
	const genresCount = await prisma.genre.count();
	if (genresCount === 0) {
		const genres = await TMDB.getGenres();
		await prisma.genre.createMany({
			data: genres.map((genre) => ({ name: genre.name })),
		});
	}
};
```
everything seems to be working fine on my local machine but not my server environment.

### Local Environment & Setup ###

OS: Windows 10 Build 19042
Node.js version: v16.4.2
Database: psql (PostgreSQL) 13.3
Prisma:

```
prisma                          : 2.28.0
@prisma/client            : 2.28.0
Current platform         : windows
Query Engine              : query-engine 89facabd0366f63911d089156a7a70125bfbcd27 (at node_modules\@prisma\engines\query-engine-windows.exe)
Migration Engine        : migration-engine-cli 89facabd0366f63911d089156a7a70125bfbcd27 (at node_modules\@prisma\engines\migration-engine-windows.exe)  
Introspection Engine  : introspection-core 89facabd0366f63911d089156a7a70125bfbcd27 (at node_modules\@prisma\engines\introspection-engine-windows.exe)
Format Binary             : prisma-fmt 89facabd0366f63911d089156a7a70125bfbcd27 (at node_modules\@prisma\engines\prisma-fmt-windows.exe)
Default Engines Hash : 89facabd0366f63911d089156a7a70125bfbcd27
Studio                         : 0.417.0
```

### Server Environment & Setup ###

OS: centos-release-7-8.2003.0.el7.centos.x86_64
       centos-release-7-9.2009.1.el7.centos.x86_64
Node.js version: v16.5.0
Database: psql (PostgreSQL) 9.2.24
Prisma:

```
prisma                          : 2.28.0
@prisma/client             : 2.28.0
Current platform          : rhel-openssl-1.0.x
Query Engine               : query-engine 89facabd0366f63911d089156a7a70125bfbcd27 (at node_modules/@prisma/engines/query-engine-rhel-openssl-1.0.x)
Migration Engine         : migration-engine-cli 89facabd0366f63911d089156a7a70125bfbcd27 (at node_modules/@prisma/engines/migration-engine-rhel-openssl-1.0.x)
Introspection Engine   : introspection-core 89facabd0366f63911d089156a7a70125bfbcd27 (at node_modules/@prisma/engines/introspection-engine-rhel-openssl-1.0.x)
Format Binary             : prisma-fmt 89facabd0366f63911d089156a7a70125bfbcd27 (at node_modules/@prisma/engines/prisma-fmt-rhel-openssl-1.0.x)
Default Engines Hash : 89facabd0366f63911d089156a7a70125bfbcd27
Studio                         : 0.417.0
```

Note: I just found out about the difference between my local and server versions of Postgres. I'll be upgrading the server's Postgres and provide an update here afterward.

**Comment by pantharshit00** [comment] 2022-06-02 11:59
Thanks, I am going to close this.

**Closed by pantharshit00** 2022-06-02 11:59 UTC
Labels: bug/0-unknown, kind/bug, status/needs-action, team/client, topic: postgresql
