### ISSUE TITLE
Row update with DB Row Lock (SELECT FOR UPDATE)

### ISSUE THREAD

**Issue by flybayer** [prisma/prisma#1918] opened 2020-03-24 12:51 UTC
## Problem

There's an entire class of DB mutations that can be affected by race conditions. An example is incrementing a value by one.

So when updating a row, we need a way to acquire a DB row lock to prevent these types of race conditions. 

## Solution

I think this could be a good solution. If `data` is a function, then `SELECT FOR UPDATE` is used.
```js
await prisma.counter.update({where: {id: 1}, data: counter => ({value: counter.value + 1})})
```

## Alternatives

Or accept the above arguments with a new API like `prisma.count.updateWithLock()`

**Comment by schickling** [comment] 2020-03-24 20:57
We've already drafted a Client API improved for this use case [in this issue](https://github.com/prisma/specs/issues/356):

```ts
await prisma.users.findMany().update({ version: u => u.version.inc(5) })
await prisma.users.findMany().update({ version: u => u.version.dec(5) })
await prisma.users.findMany().update({ version: u => u.version.mul(5) })
await prisma.users.findMany().update({ version: u => u.version.div(5) })
await prisma.users.findMany().update({ version: u => u.version.mod(5) })
await prisma.users.findMany().update({ version: u => u.version.pow(5, 10) })
await prisma.users.findMany().update({ version: u => u.version.min(5, 10) })
await prisma.users.findMany().update({ version: u => u.version.max(5, 10) })
```

**Comment by pantharshit00** [comment] 2020-03-25 08:41
Related: https://github.com/prisma/prisma2/issues/1844

I think we would cover this we have an API for atomic transactions but that will take quite some time properly specing that and implementing it so that is a bit far in the future.

This might be closed as a duplicate of https://github.com/prisma/prisma2/issues/1844

**Comment by yovanoc** [comment] 2020-03-29 08:27
Ohhh look very nice! Any timeline for a v1 of this draft?

**Comment by steebchen** [comment] 2020-04-23 17:04
related for number-like types: https://github.com/prisma/prisma-client-js/issues/655

**Comment by albertoperdomo** [comment] 2020-07-08 12:11
Thanks for the feature request @flybayer!

As mentioned earlier in the issue, we are planning to tackle atomic operations natively in https://github.com/prisma/prisma-client-js/issues/655.

If you still feel the need for acquiring DB row locks for other operations, please feel free to open a new feature request.

**Closed by albertoperdomo** 2020-07-08 12:11 UTC
Labels: kind/feature

**Comment by Sytten** [comment] 2020-07-08 13:01
I kind of disagree with this closing this, row locking is important and one step in providing more control to dev since long running transactions are out of the question for now. That could allow chaining of a findOne and update  where the update takes some data from the findOne.

**Comment by janpio** [comment] 2020-07-08 13:18
@Sytten Then we need an issue about this set of problems. As this one was explicitly about what https://github.com/prisma/prisma-client-js/issues/655 covers, it would be invalid to keep this around. We are happy to look into other problems that require this, and might even require this general solution.

**Comment by JoniBR** [comment] 2022-12-07 13:09
Why was this closed? I don't see another solution providing this :(

**Comment by janpio** [comment] 2022-12-07 19:04
See https://github.com/prisma/prisma/issues/1918#issuecomment-655480141

**Comment by leppaott** [comment] 2024-04-30 05:23
There should be more generic solution to using `SELECT .. FOR UPDATE` to lock rows before an update. Atomic number operations don't quite cut it.
