### ISSUE TITLE
$executeRaw throws PostgreSQL ERROR: invalid scale in external "numeric" value or inserts 0.0

### ISSUE THREAD

**Issue by kennytraction** [prisma/prisma#4828] opened 2020-12-30 21:36 UTC
## Bug description

We are using $executeRaw to insert data into a table. If a decimal value is passed in the record will get inserted. If a whole number (1234, 1234.0) is passed in, the record will be inserted but the decimal value will be 0.0. If a larger whole number (12345, 12345.0) is passed in, Postgres will throw an error: ERROR: invalid scale in external "numeric" value

## How to reproduce

```
CREATE TABLE IF NOT EXISTS "someTable" (
  "accountId" uuid PRIMARY KEY,
  "originalAmount" decimal(12,2),
  "notes" varchar(500)
);
```
```
model someTable {
  accountId      String  @id
  originalAmount Float?
  notes          String?
}
```
```
async runRawQuery(value: number, accountId: string, notes: string) {
    await this.client.$executeRaw`
    INSERT INTO "someTable" ("originalAmount","accountId","notes")
    VALUES (${value}, ${accountId}, ${notes});
    `
  }
```
Using `runRawQuery(1234.5, '032c9baa-0616-4361-8a40-7a808e5180f3', 'some notes')` will create the record with the correct values.

Using `runRawQuery(1234.0, '032c9baa-0616-4361-8a40-7a808e5180f3', 'some notes')` will create the record but originalAmount will be 0.00

Using `runRawQuery(12345.0, '032c9baa-0616-4361-8a40-7a808e5180f3', 'some notes')` will cause Postgres to throw an error: ERROR: invalid scale in external "numeric" value

## Expected behavior

I expect the record to get created with the correct values.

## Environment & setup

- OS: Windows 10
- Database: PostgreSQL 12.2
- Node.js version: 12.16.1
- Prisma version: found using 2.10.2, also duplicated on 2.13.1

```
Prisma CLI version: prisma/1.34.10 (windows-x64) node-v12.16.1
```

**Comment by aliscott** [comment] 2021-01-02 17:28
I'm seeing the same issue. Are there any workarounds for this just now?

**Comment by pimeys** [comment] 2021-01-04 12:50
Could you try a workaround by using a floating point value instead of number? Can't replicate this yet on the Rust side, but I guess what js does here is it sends the value as a string, and by strict typing in Postgres we do something stupid here which is hard to prevent.

**Comment by kennytraction** [comment] 2021-01-04 16:04
So far the only workaround we have it to run $executeRaw using 0 for the numeric value followed immediately by a `client.someTable.update()`.

**Comment by pantharshit00** [comment] 2021-01-13 16:00
I can reproduce the loss of value but I can't reproduce `invalid scale in "numeric" value` error. I used 2.14 for reproduction. 

Marking this as a confirmed bug though and we need to fix the JS value coercion here.

**Closed** 2021-02-10 11:19 UTC
Labels: bug/2-confirmed, kind/bug, team/client, topic: floating point types, topic: raw
