### ISSUE TITLE
Find many returns empty array or null

### ISSUE THREAD

**Issue by dagistan-tuncbilek** [prisma/prisma#14019] opened 2022-06-27 11:43 UTC
### Bug description

FindMany query returns null or empty, if it uses where in query with 1000+ items. This bug can be seen in many-to-many and one to many nested models. Tested in Mysql-8 and MariaDB. (EDIT: It works with PostgreSQL)

### How to reproduce

Seed and then, these queries returns empty array;

```
this.prisma.user.findMany({ include: { posts: true }})
this.prisma.post.findMany({ include: { users: true }})
this.prisma.user.findMany({ where: { id: { lt: 51}}, include: { posts: true }});
```
But interestingly this works. (I think the problem is the count of where in ids, 50 * 20 = 1000)

`this.prisma.user.findMany({ where: { id: { lt: 50}}, include: { posts: true }});`

### Expected behavior

```
[   {
        "id": 1,
        "email": "tf2v9@mail.com",
        "name": "9ev6v",
        "posts": []
    },
    {
        "id": 2,
        "email": "5usm7@mail.com",
        "name": "y3nbu",
        "posts": []
    },
    {
        "id": 3,
        "email": "8qwpt@mail.com",
        "name": "oqjec",
        "posts": []
    }]

[   {
        "id": 1,
        "title": "p70a3",
        "content": "h5g7q@mail.com",
        "published": false,
        "users": []
    },
    {
        "id": 2,
        "title": "x3mg3",
        "content": "gxc7z@mail.com",
        "published": false,
        "users": []
    }]
```

### Prisma information

```
generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "mysql"
  url      = env("DATABASE_URL")
}


model User {
  id    Int     @default(autoincrement()) @id
  email String  @unique
  name  String?
  posts Post[]
}

model Post {
  id        Int      @default(autoincrement()) @id
  title     String
  content   String?
  published Boolean? @default(false)
  users    User[]
}
```

### Environment & setup

- OS: Ubuntu 22.04
- Database: MariaDB
- Node.js version: 16.15

### Prisma Version
4.0.0

**Comment by dagistan-tuncbilek** [comment] 2022-06-27 11:49
[dump-test-202206271345.zip](https://github.com/prisma/prisma/files/8991663/dump-test-202206271345.zip)

**Comment by the-gorg** [comment] 2022-07-14 10:31
I seem to have the same issue with MariaDB

**Comment by kkomelin** [comment] 2022-09-01 12:23
The same here. Upgrading MariaDB from 10.7.3 to 10.7.5 has fixed the issue.

**Comment by dagistan-tuncbilek** [comment] 2022-09-01 12:56
> The same here. Upgrading MariaDB from 10.7.3 to 10.7.5 has fixed the issue. More details about the MariaDB bug here [#12338 (comment)](https://github.com/prisma/prisma/issues/12338#issuecomment-1195954336)

Yes, exactly. I tested it, and it works. I close this issue.

**Comment by kkomelin** [comment] 2022-09-01 12:59
You're welcome @dagistan-tuncbilek

**Comment by aqrln** [comment] 2022-09-01 14:31
Next steps for us: check if it's reproducible with latest MySQL 8.

**Comment by kkomelin** [comment] 2022-09-01 14:34
@aqrln if you need a playground for that, please use my https://github.com/kkomelin/prisma-in-issue-reproduction and just change the docker image to the one you need to test with.

**Comment by dagistan-tuncbilek** [comment] 2022-09-02 06:55
> Next steps for us: check if it's reproducible with latest MySQL 8.

@aqrln  I tested it with mysql:8.0.30 image. It also works as expected.

**Comment by aqrln** [comment] 2022-09-02 08:36
@dagistan-tuncbilek perfect, thank you!

I see that @jkomyno self-assigned, so I'm not going to close this issue just yet and let him do that, but good to know that it's not an issue anymore.

**Comment by jkomyno** [comment] 2022-09-02 09:54
Closing this issue as it's independent of Prisma: it's instead related to a bug in some MariaDB versions.
[This reproduction](https://github.com/jkomyno/reprod-14539) runs test cases inspired by issue #14539 (which comprises #12338 and #14019 as well) on a "bugged" MariaDB instance (`mariadb:10.7.3`), on a "stable" MariaDB instance (`mariadb:10.8.4`), and on a recent MySQL instance (`mysql:8.0.30`).

Thanks to @kkomelin and @HendrikJan for their independent reproductions, and to @d-Rickyy-b for spotting https://jira.mariadb.org/browse/MDEV-27937.

**Closed by jkomyno** 2022-09-02 09:54 UTC
Labels: bug/1-unconfirmed, kind/bug, topic: mariadb, topic: mysql, team/client, topic: mysql 8

**Comment by janpio** [comment] 2022-09-06 20:40
Just for bookkeeping: We consider this a duplicate of https://github.com/prisma/prisma/issues/14019
