### ISSUE TITLE
Database collation affects result of orderBy (case sensitive)

### ISSUE THREAD

**Issue by mhwelander** [prisma/prisma#2369] opened 2020-05-05 07:56 UTC
## Problem

When I order by a `title` field, I get different results if I use PostgreSQL or SQLite because they have different default collation.

Default PostgreSQL:

Another one
another one
Bites the
bites the 
Dust
dust

Default SQLite:

Another one
Bites the
Dust
another one
bites the
dust

## Suggestion

An option to use case-insensitive sorting per instance of client or the ability to specify that I want to sort by title.toLower().

## Notes

Have not done any testing on decimals/numbers.

**Comment by pantharshit00** [comment] 2020-05-05 10:17
Hi,

Thanks for reporting this! It has already been reported before, so I am going to close this as a duplicate of

**Comment by janpio** [comment] 2020-05-06 11:31
The linked issue does not mention "collation" once, and does not actually describe the problem or the solution in the issue itself @pantharshit00. Are you sure this is an appropriate replacement? If so, it definitely needs an update in description.

**Comment by pantharshit00** [comment] 2020-05-06 11:36
"collation" is irrelevant as client will return the data returned by the database. You will need to change it on db level of you want to have a different behaviour.

**Comment by janpio** [comment] 2020-05-06 12:27
Exactly. https://github.com/prisma/prisma-client-js/issues/343 might offer a workaround when it is implemented, but the underlying problem of @mhwelander is a different one.

**Comment by pantharshit00** [comment] 2020-05-06 12:37
> Exactly. prisma/prisma-client-js#343 might offer a workaround when it is implemented, but the underlying problem of @mhwelander is a different one.

Is it really a problem though? Does client should care about of collation which underlying database uses? We can keep this open but I don't this is something which is under the scope of Prisma Client

**Comment by janpio** [comment] 2020-05-11 13:08
As it leads to confusing situations to users like @mhwelander I would say the behavior of Prisma here is relevant.

**Comment by mhwelander** [comment] 2020-05-11 13:34
Changing #343 to 'Add case sensitive/insensitive querying **and sorting**' as per Jan's suggestion works, just to make sure it is considered in the design (maybe I want filtering to be case-sensitive but ordering to be case-insensitive for the same query, for example).

I should have phrased my request differently - the request is that I would like the option to specify case-insensitive ordering just as I can do in regular SQLite (e.g. `SELECT * FROM ... WHERE name = 'someone' COLLATE NOCASE`) - no matter what the db collation is. I brought up collation only to emphasize that I know Prisma respecting SQLite's default sort order is not a bug.

Sorry about my title! :)

**Comment by pantharshit00** [comment] 2020-05-14 11:12
This issue now tracks feature request for an option to specific `COLLATE NOCASE` in the queries

**Comment by thebiglabasky** [comment] 2020-07-17 11:24
We did investigate the topic of case sensitivity extensively recently.
Coping with all possible underlying database settings is too big of a promise to make so we are looking into supporting case insensitive filtering first, monitored on this issue: https://github.com/prisma/prisma-client-js/issues/690
Providing ways to allow users to perform a case insensitive sort needs to be assessed separately, but should also be monitored through https://github.com/prisma/prisma-client-js/issues/690

I will close this issue as it is asking for a specific solution to the problem described in the issue mentioned above.
Thanks!

**Closed by thebiglabasky** 2020-07-17 11:24 UTC
Labels: kind/feature, topic: collation
