### ISSUE TITLE
Error in PostgreSQL connection: Error { kind: Closed, cause: None }

### ISSUE THREAD

**Issue by bkrausz** [prisma/prisma#5947] opened 2021-03-02 21:33 UTC
Hi Prisma Team! My Prisma Client just crashed. This is the report:

We get batches of these (and have been for many months, maybe once a week), where something will die and then we'll lose all DB connections for about 25s. At first we thought it was a max number of connections or CPU issue, but we don't see much evidence of that being the case.

I recognize it's possible this is a Postgres or Render (our host) issue, but am hoping for some advice on eliminating Prisma's engine as a cause/general debugging help, since Render has not seen this issue before with their setup.

We've tried playing with max connections (currently `connection_limit=5` on each of our 2 machines), which hasn't changed anything.

## Versions

| Name            | Version            |
|-----------------|--------------------|
| Node            | v14.11.0           | 
| OS              | debian-openssl-1.1.x|
| Prisma Client   | 2.17.0             |
| Query Engine    | query-engine 3c463ebd78b1d21d8fdacdd27899e280cf686223|
| Database        | undefined|

## Logs
```
PrismaClientUnknownRequestError2 [PrismaClientUnknownRequestError]: Error occurred during query execution:
  ConnectorError(ConnectorError { user_facing_error: None, kind: QueryError(Error { kind: Closed, cause: None }) })
      at NodeEngine.graphQLToJSError (/opt/render/project/src/node_modules/@prisma/client/runtime/index.js:27156:14)
      at NodeEngine.request (/opt/render/project/src/node_modules/@prisma/client/runtime/index.js:27052:24)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (internal/process/task_queues.js:93:5)
      at async cb (/opt/render/project/src/node_modules/@prisma/client/runtime/index.js:78659:26) {
    clientVersion: '2.17.0'
  }
}
prisma:engine {
  error: PrismaClientUnknownRequestError2 [PrismaClientUnknownRequestError]: Error in connector: Error querying the database: connection closed
      at NodeEngine.graphQLToJSError (/opt/render/project/src/node_modules/@prisma/client/runtime/index.js:27156:14)
      at NodeEngine.request (/opt/render/project/src/node_modules/@prisma/client/runtime/index.js:27052:24)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (internal/process/task_queues.js:93:5)
      at async cb (/opt/render/project/src/node_modules/@prisma/client/runtime/index.js:78659:26) {
    clientVersion: '2.17.0'
  }
}
prisma:engine {
  error: PrismaClientUnknownRequestError2 [PrismaClientUnknownRequestError]: Error occurred during query execution:
  ConnectorError(ConnectorError { user_facing_error: None, kind: QueryError(Error { kind: Closed, cause: None }) })
      at NodeEngine.graphQLToJSError (/opt/render/project/src/node_modules/@prisma/client/runtime/index.js:27156:14)
      at NodeEngine.request (/opt/render/project/src/node_modules/@prisma/client/runtime/index.js:27052:24)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (internal/process/task_queues.js:93:5)
      at async cb (/opt/render/project/src/node_modules/@prisma/client/runtime/index.js:78659:26) {
    clientVersion: '2.17.0'
  }
}
prisma:engine {
  error: PrismaClientUnknownRequestError2 [PrismaClientUnknownRequestError]: Error occurred during query execution:
  ConnectorError(ConnectorError { user_facing_error: None, kind: QueryError(Error { kind: Closed, cause: None }) })
      at NodeEngine.graphQLToJSError (/opt/render/project/src/node_modules/@prisma/client/runtime/index.js:27156:14)
      at NodeEngine.request (/opt/render/project/src/node_modules/@prisma/client/runtime/index.js:27052:24)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (internal/process/task_queues.js:93:5)
      at async cb (/opt/render/project/src/node_modules/@prisma/client/runtime/index.js:78659:26) {
    clientVersion: '2.17.0'
  }
}
prisma:engine {
  error: Error: Error occurred during query execution:
  ConnectorError(ConnectorError { user_facing_error: None, kind: QueryError(Error { kind: Closed, cause: None }) })
      at /opt/render/project/src/node_modules/@prisma/client/runtime/index.js:27103:19
      at /opt/render/project/src/node_modules/honeycomb-beeline/lib/async_tracker.js:47:19
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (internal/process/task_queues.js:93:5)
}
prisma:engine {
  error: PrismaClientUnknownRequestError2 [PrismaClientUnknownRequestError]: Error occurred during query execution:
  ConnectorError(ConnectorError { user_facing_error: None, kind: QueryError(Error { kind: Closed, cause: None }) })
      at NodeEngine.graphQLToJSError (/opt/render/project/src/node_modules/@prisma/client/runtime/index.js:27156:14)
      at NodeEngine.request (/opt/render/project/src/node_modules/@prisma/client/runtime/index.js:27052:24)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (internal/process/task_queues.js:93:5) {
    clientVersion: '2.17.0'
  }
}
prisma:engine {
  error: Error: Error occurred during query execution:
  ConnectorError(ConnectorError { user_facing_error: None, kind: QueryError(Error { kind: Closed, cause: None }) })
      at /opt/render/project/src/node_modules/@prisma/client/runtime/index.js:27103:19
      at /opt/render/project/src/node_modules/honeycomb-beeline/lib/async_tracker.js:47:19
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (internal/process/task_queues.js:93:5)
}
prisma:engine {
  error: PrismaClientUnknownRequestError2 [PrismaClientUnknownRequestError]: Error occurred during query execution:
  ConnectorError(ConnectorError { user_facing_error: None, kind: QueryError(Error { kind: Closed, cause: None }) })
      at NodeEngine.graphQLToJSError (/opt/render/project/src/node_modules/@prisma/client/runtime/index.js:27156:14)
      at NodeEngine.request (/opt/render/project/src/node_modules/@prisma/client/runtime/index.js:27052:24)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (internal/process/task_queues.js:93:5) {
    clientVersion: '2.17.0'
  }
}
```

**Comment by janpio** [comment] 2021-03-03 19:38
After 25 seconds all queries just start working again? 
Can you share the logfile of this happening maybe?

**Comment by bkrausz** [comment] 2021-03-03 23:25
Yup, details from the last two bursts:

## 13:14:45 - 13:15:03
- 30 500s
- 21 200s

## 13:45:33 - 13:45:50
- 68 500s
- 26 200s

These are inconsistently spread across our two servers, though it is hitting both at the same time.

Were you looking for prisma logs? I can run with DEBUG=* and report back next time it happens if that's what you're looking for.

**Comment by janpio** [comment] 2021-03-04 14:25
Yep, that could possibly be interesting what is output when this recovers.

**Comment by pantharshit00** [comment] 2021-03-04 16:04
While you are at it, please upgrade to 2.18 to make sure this hasn't been addressed by a recent code change.

**Comment by bkrausz** [comment] 2021-03-05 03:10
I'm usually a little behind latest release because we have to wait for nexus-plugin-prisma to update. Will upgrade when I can.

We have had issues in the past (6+mo ago) with Prisma being the first thing to fail with unintuitive errors when our machine got resource constrained, and we did just discover that `graphql-shield` has been causing a ton of memory allocation and slowness (we ship down fairly large GQL objects), so it is possible that fixing that will cause these issues to improve.

Happy to reopen if/when this happens down the line, or leave this for tracking: whatever you'd prefer.

**Comment by Sytten** [comment] 2021-03-19 00:14
Related to https://github.com/prisma/prisma/issues/5976

**Closed** 2021-04-07 16:22 UTC
Labels: bug/0-needs-info, kind/bug, team/client, topic: "kind: Closed", topic: prisma-client

**Comment by janpio** [comment] 2021-04-07 16:30
Information about the PR that closed this:
https://github.com/prisma/prisma/issues/6329#issuecomment-815012006

Feel free to reply here again if the problem is not solved/better for you and we can reopen the issue of course.
