### ISSUE TITLE
Simple clear database functionality

### ISSUE THREAD

**Issue by michielswaanen** [prisma/prisma#5143] opened 2021-01-18 08:02 UTC
## Problem
When I'm running my unit tests, I use a virtual temporary database in order to test my routes. Prisma doesn't provide (to my knowledge) no "clean" way to delete everything inside the database. After each unit test the database tables should be emptied.

## Suggested solution
I would really like to see a simple function in order to **delete all data from the tables**, without giving a **constraint error**!
```ts
const prisma = new PrismaClient();
prisma.clear();
```

## Alternatives
The only way I found to mimic this behavior is by creating a file that contains all the tables, looping through every table and delete all the records one by one. The tables must be looped in order to not get a constraint error. This is just not the way you want to go... but there's just no other way (I think?).

## Additional context
It would look something like this using Jest:

```ts
afterEach(async () => {
  prisma.clear();
});

afterAll(async () => {
  prisma.$disconnect();
})
```

Please let me know about any alternatives! I'm dying to know! 😄

**Comment by Glazy** [comment] 2021-09-08 20:50
Related to: #5230 and #5231

**Comment by pantharshit00** [comment] 2021-09-09 13:12
Yeah, closing as duplicate of above noted issues.

**Closed by pantharshit00** 2021-09-09 13:12 UTC
Labels: kind/feature, team/client, topic: client api
