### ISSUE TITLE
allow renaming enums

### ISSUE THREAD

**Issue by jasonkuhrt** [prisma/prisma#8378] opened 2021-07-21 15:04 UTC
## Problem

Example migration after enum rename:

```
/*
  Warnings:

  - You are about to drop the column `provider` on the `DatabaseLink` table. All the data in the column will be lost.
  - Added the required column `databaseType` to the `DatabaseLink` table without a default value. This is not possible if the table is not empty.

*/
-- CreateEnum
CREATE TYPE "DatabaseType" AS ENUM ('postgresql', 'mysql', 'sqlserver');

-- AlterTable
ALTER TABLE "DatabaseLink" DROP COLUMN "provider",
ADD COLUMN     "databaseType" "DatabaseType" NOT NULL;

-- DropEnum
DROP TYPE "DatabaseProvider";
```

Failure to migrate:

![image](https://user-images.githubusercontent.com/284476/126511844-6785a9a5-b772-4475-9742-029f8b931d65.png)

## Suggested solution

What we needed generated was this:

```
ALTER TYPE "DatabaseProvider" RENAME TO "DatabaseType";
```

**Comment by pantharshit00** [comment] 2021-07-21 22:23
I will need some kind of temporary directive to mark the field which was renamed otherwise it can be hard to keep track of them.

**Comment by matthewmueller** [comment] 2022-09-09 16:35
Duplicate of https://github.com/prisma/prisma/issues/8407

**Closed by matthewmueller** 2022-09-09 16:35 UTC
Labels: kind/feature, team/schema, topic: rename, topic: enums
