### ISSUE TITLE
Trying to understand why prisma overflowed on slow network

### ISSUE THREAD

**Issue by Sytten** [prisma/prisma#6884] opened 2021-05-01 14:41 UTC
This is an investigation ticket. Some facts first:
- We started experiencing higher latency in our service two days ago (queries that would take several minutes to complete where they usually complete in milliseconds)
- We are not sure what is the cause of it (still investigating with GCP support)
- We started seeing pool timeout a lot
- We started fanning out the service and reducing the concurrency per instance, this helped on the pool timeout issues but the queries were still very slow
- Strangely when we removed our logger (logdna) who was experiencing an outage, it seemed to have solved the issue? Might just be a coincidence since we were also seeing high latency on GCP buckets (which lead us to the conclusion it was a GCP network issue) 
- The database query didn't seem particularly slow
- We did see some errors where prisma could not connect to the DB, so I am not ruling out the possibility that the problem was on the google network

Worth investigating:
- Prisma should have a way to cancel queries from JS when not using the NAPI binding
- Prisma should release connections even if the JS event loop is blocked
- Prisma should respect the socket_timeout of 5s, it seems to not respect it currently?
- Prisma should respect the connection_limit, from what I saw in the connection tab of cloud sql it didnt seem to use them all
- We should have metrics to monitor prisma, currently very hard to know what is happening
- We reported a issue with a middleware not respecting the transactions the other day because it seems to keep the queries around even after the promise has resolved, that tells me it might have kept connections in use during an event loop block causing a cascading effect?

**Comment by janpio** [comment] 2021-05-03 18:53
I can confirm that `socket_timeout` is definitely not `5` as documented (https://www.prisma.io/docs/concepts/database-connectors/postgresql, https://www.prisma.io/docs/concepts/database-connectors/mysql) but also not `30` or `60`.

**Comment by SevInf** [comment] 2023-07-13 13:29
@Sytten is this still a problem for you or can we close this issue? Quite a bunch of things have been changed/fixed since this issue was created.

Thank you!

**Comment by Sytten** [comment] 2023-07-13 13:34
Sure, but I dont think you guys fixed all the problems in the rust connection pool. I worked on it a couple years ago but have not touched it since.

**Closed** 2023-07-13 13:34 UTC
Labels: bug/0-unknown, kind/bug, status/needs-action, team/client
