### ISSUE TITLE
Engine freezes all requests/responses in 2.0.0-beta.2

### ISSUE THREAD

**Issue by asciant** [prisma/prisma#2143] opened 2020-04-09 06:17 UTC
## Bug description

Beta.2 freezes all requests to the application. The queries never resolve, and the requests never return any data.

I tested in NextJS, although even loading prisma with beta.2 outside the NextJS app (using just node) it still hangs.

Removing the query/request code from NextJS sees it start resolving requests as normal.

## How to reproduce

Reproduction: 

https://github.com/asciant/prisma-next-db-slots/tree/testing-beta-2
Note: this is a separate branch of a 2.0.0-beta.1 issue #1438 (https://github.com/prisma/prisma/issues/1438#issuecomment-610196306)

1. Clone the repository (https://github.com/asciant/prisma-next-db-slots);
2. Switch to the `testing-beta-2` branch
3. Have your own local Postgres server running, and setup the `DATABASE_URL` connection string environment variable;
4. Install the dependencies (`npm install`), generate the prisma client (`npx prisma generate`) and run the migration (`npx prisma migrate up --experimental`);
5. Start the server (`npm run dev`) and visit the page in the browser (`http://localhost:3000`).

## Expected behavior

The prisma engine to respond with the results of the query.

## Prisma information

Included in the reproduction.

## Environment & setup

- OS: MacOS
- Database: PostgreSQL 12.2
- Prisma version: 

```
Environment variables loaded from ./prisma/.env
@prisma/cli          : 2.0.0-beta.2
Current platform     : darwin
Query Engine         : query-engine 76857c35ba1e1764dd5473656ecbbb2f739e1822 (at /usr/local/lib/node_modules/@prisma/cli/query-engine-darwin)
Migration Engine     : migration-engine-cli 76857c35ba1e1764dd5473656ecbbb2f739e1822 (at /usr/local/lib/node_modules/@prisma/cli/migration-engine-darwin)
Introspection Engine : introspection-core 76857c35ba1e1764dd5473656ecbbb2f739e1822 (at /usr/local/lib/node_modules/@prisma/cli/introspection-engine-darwin)
```

- Node.js version: v13.12.0

**Comment by janpio** [comment] 2020-04-09 08:37
Can you please set `DEBUG=*` env var and post the full output you are getting?

**Comment by asciant** [comment] 2020-04-09 09:00
There is no prisma output, in the terminal window or in the console.

Probably because the request never resolves, it just endlessly loads with no response received.

The NextJS output:

```
➜  prisma2-next-db-slots git:(testing-beta-2) npm run dev

> prisma2-next-db-slots@1.0.0 dev /Users/asciant/Projects/prisma2-next-db-slots
> next

[ wait ]  starting the development server ...
[ info ]  waiting on http://localhost:3000 ...
[ ready ] compiled successfully - ready on http://localhost:3000
[ wait ]  compiling ...
[ ready ] compiled successfully - ready on http://localhost:3000
[ wait ]  compiling ...
[ ready ] compiled successfully - ready on http://localhost:3000
[ event ] build page: /
[ wait ]  compiling ...
[ ready ] compiled successfully - ready on http://localhost:3000
[ event ] build page: /api/graph
[ wait ]  compiling ...
[ ready ] compiled successfully - ready on http://localhost:3000
```

If you leave a web browser window long enough (Chrome in my case) it eventually returns, `ERR_CONNECTION_REFUSED.`

I [created a file ](https://github.com/asciant/prisma-next-db-slots/blob/testing-beta-2/prisma/console.js) that uses prisma directly, and it simply sits with no response ever output to the terminal window:

```
➜  prisma2-next-db-slots git:(testing-beta-2) ✗ node ./prisma/console.js
 
```

In a working app, I use a file like this to seed the DB. Even with no statements it would normally release the node process and return to the normal terminal (where you could type more commands). In this case, you have to use `control + c` to break out of the script. 

Is it possible that this is related to a DB connection issue (as the only thing that file does is connect and then disconnect from the prisma engine/DB?

**Comment by MattGson** [comment] 2020-04-09 09:03
Same problem here

Debug output on startup:
```
 prisma-client { engineConfig:
  prisma-client    { cwd:
  prisma-client       '/Users/REDACTED/prisma',
  prisma-client      debug: false,
  prisma-client      datamodelPath:
  prisma-client       '/Users/REDACTED/@prisma/client/schema.prisma',
  prisma-client      prismaPath: undefined,
  prisma-client      datasources: [],
  prisma-client      generator:
  prisma-client       { name: 'client',
  prisma-client         provider: 'prisma-client-js',
  prisma-client         output:
  prisma-client          'REDACTED/@prisma/client',
  prisma-client         binaryTargets: [],
  prisma-client         config: {} },
  prisma-client      showColors: false,
  prisma-client      logLevel: undefined,
  prisma-client      logQueries: true,
  prisma-client      env: { DATABASE_URL: 'mysql://REDACTED' },
  prisma-client      flags: [] } } +0ms

```

And for the query:

```
  prisma-client Prisma Client call: +1m
  prisma-client prisma.users.findMany({
  prisma-client   where: {
REDACTED
  prisma-client   },
  prisma-client   select: {
REDACTED
  prisma-client   }
  prisma-client }) +3ms
  prisma-client Generated request: +0ms
  prisma-client query {
  prisma-client   findManyusers(where: {
REDACTED
  prisma-client     }
  prisma-client   }) {
  prisma-client     language_id
REDACTED
  prisma-client   }
  prisma-client }
  prisma-client  +0ms
  engine { PRISMA_DML_PATH:
  engine    '/Users/REDACTED/node_modules/@prisma/client/schema.prisma',
  engine   PORT: '53759',
  engine   RUST_BACKTRACE: '1',
  engine   RUST_LOG: 'info',
  engine   LOG_QUERIES: 'true',
  engine   OVERWRITE_DATASOURCES: '[]' } +0ms
  engine { cwd:
  engine    '/Users/REDACTED/prisma' } +1ms
  plusX Execution permissions of /Users/REDACTED/@prisma/client/runtime/query-engine-darwin are fine +0ms
  engine { flags: [ '--enable-raw-queries' ] } +2ms
 ...
  engine stderr Printing to stderr for debugging +59ms
  engine stderr Listening on 127.0.0.1:53759 +1ms
  engine stdout { timestamp: 'Apr 09 08:56:05.300',
  level: 'INFO',
  target: 'quaint::pooled',
  fields: { message: 'Starting a mysql pool with 9 connections.' } } +25ms
  engine stdout { timestamp: 'Apr 09 08:56:05.346',
  level: 'INFO',
  target: 'prisma::server',
  fields:
   { message: 'Started http server on 127.0.0.1:53759',
     'log.target': 'prisma::server',
     'log.module_path': 'prisma::server',
     'log.file': 'query-engine/prisma/src/server.rs',
     'log.line': 109 } } +45ms
  morgan log request +524ms

 

  engine stderr Printing to stderr for debugging +59ms
  engine stderr Listening on 127.0.0.1:53759 +1ms
  engine stdout { timestamp: 'Apr 09 08:56:05.300',
  level: 'INFO',
  target: 'quaint::pooled',
  fields: { message: 'Starting a mysql pool with 9 connections.' } } +25ms
  engine stdout { timestamp: 'Apr 09 08:56:05.346',
  level: 'INFO',
  target: 'prisma::server',
  fields:
   { message: 'Started http server on 127.0.0.1:53759',
     'log.target': 'prisma::server',
     'log.module_path': 'prisma::server',
     'log.file': 'query-engine/prisma/src/server.rs',
     'log.line': 109 } } +45ms

```

**Comment by pantharshit00** [comment] 2020-04-09 11:37
I can confirm this via the reproduction. Still it is not very clear to me why this is happening as there are no logs. This need more investigation.

Also, @asciant, a small note, please don't create a new Prisma instance per request in the context like so:
```js
const apolloServer = new ApolloServer({
  schema,
  context: ({ req, res }) => {
    return {
      req,
      res,
      prisma: new PrismaClient(),
    };
  },
});
```

This is absolutely not recommended as it will spawn a new binary instance per request.

Instead do it like so:
```js
const prisma = new PrismaClient()
const apolloServer = new ApolloServer({
  schema,
  context: ({ req, res }) => {
    return {
      req,
      res,
      prisma: prisma,
    };
  },
});
```

**Comment by jozefhruska** [comment] 2020-04-11 06:53
I experienced exactly the same issue after updating to  2.0.0-beta.2. With `DEBUG` env query freezes with this output:
```
  getos { platform: 'darwin', libssl: undefined } +0ms
  engine {
  engine   PRISMA_DML_PATH: '/Users/jozefhruska/Development/School/BP/slackify/node_modules/@prisma/client/schema.prisma',
  engine   PORT: '52635',
  engine   RUST_BACKTRACE: '1',
  engine   RUST_LOG: 'info',
  engine   OVERWRITE_DATASOURCES: '[]',
  engine   CLICOLOR_FORCE: '1'
  engine } +0ms
  engine {
  engine   cwd: '/Users/jozefhruska/Development/School/BP/slackify/packages/prisma'
  engine } +0ms
  plusX Execution permissions of /Users/jozefhruska/Development/School/BP/slackify/node_modules/@prisma/client/runtime/query-engine-darwin are fine +0ms
  engine { flags: [ '--enable-raw-queries' ] } +1ms
  engine stderr Printing to stderr for debugging +95ms
  engine stderr Listening on 127.0.0.1:52635 +0ms
  engine stdout {
  timestamp: 'Apr 11 08:49:27.334',
  level: 'INFO',
  target: 'quaint::pooled',
  fields: { message: 'Starting a postgresql pool with 13 connections.' }
} +2ms
  engine stdout {
  timestamp: 'Apr 11 08:49:27.342',
  level: 'INFO',
  target: 'query_engine::server',
  fields: {
    message: 'Started http server on 127.0.0.1:52635',
    'log.target': 'query_engine::server',
    'log.module_path': 'query_engine::server',
    'log.file': 'query-engine/query-engine/src/server.rs',
    'log.line': 109
  }
} +7ms
```

After some investigation I found this inside my `package-lock.json`:
```
		"@prisma/cli": {
			"version": "2.0.0-beta.2",
			"resolved": "https://registry.npmjs.org/@prisma/cli/-/cli-2.0.0-beta.2.tgz",
			"integrity": "sha512-lD0cv/YC4g4SKByxH3hvzX1oS9cjRdCDU1Sh2inATaKcTHWPlxxgXQW4yYU2FF/HSWR9KK6YMAdO3ShkOl1PEQ=="
		},
		"@prisma/client": {
			"version": "2.0.0-previewnull-1",
			"resolved": "https://registry.npmjs.org/@prisma/client/-/client-2.0.0-previewnull-1.tgz",
			"integrity": "sha512-glIyw5+4fyXABnvhPErG6X7IrepBj88N+0QsEXksB/NERHo8R97vHNpQvq0sAxAaK61mjiuaypZ3CyjxcC1XhA=="
		},
```

I'm using lerna with all packages on version `2.0.0-beta.2`.

**Comment by asciant** [comment] 2020-04-11 07:00
Within the lock file of the reproduction app, the package-lock.json looks like this:

```
    "@prisma/cli": {
      "version": "2.0.0-beta.1",
      "resolved": "https://registry.npmjs.org/@prisma/cli/-/cli-2.0.0-beta.1.tgz",
      "integrity": "sha512-uMCthsNkLCmQiPs6veMdqT/Y4RWRbn8Y0GAfqvg+qStene6Pqid7DTrdN7hC+VYlY7Ok5Fxcb6oBis1jsOO7pQ==",
      "dev": true
    },
    "@prisma/client": {
      "version": "2.0.0-beta.2",
      "resolved": "https://registry.npmjs.org/@prisma/client/-/client-2.0.0-beta.2.tgz",
      "integrity": "sha512-VhNYeeGTrFfLjB/JL7XPoWpxSTCb+YV+F3ggR1X0CGa4b/u6Kxy65aElLozs+yFdMQPVNkyg2PwUO8xQ7G9fpg=="
    },
```

**Comment by janpio** [comment] 2020-04-11 09:51
@asciant Please try to set both to `beta.2`.
@jozefhruska Ugh, that `2.0.0-previewnull-1` should not be. Can you manually change it to `beta.2`? (We had a bug in our publish script which lead to this version being published...)

**Comment by thoughtpoet** [comment] 2020-04-11 15:35
I have the same problem with a non-responsive client that waits forever. package-lock.json appears correct:
    "@prisma/client": {
      "resolved": "https://registry.npmjs.org/@prisma/client/-/client-2.0.0-beta.2.tgz",

I added connect-timeout to force an early error, but it is ignored, though connection-limit is accepted. My debug info looks like this, with some values changed for security purposes, looks like this:

  prisma-client {
  prisma-client   engineConfig: {
  prisma-client     cwd: '/Users/me/projects/src/meproj/prisma',
  prisma-client     debug: false,
  prisma-client     datamodelPath: '/Users/me/projects/src/meproj/node_modules/@prisma/client/schema.prisma',
  prisma-client     prismaPath: undefined,
  prisma-client     datasources: [],
  prisma-client     generator: {
  prisma-client       name: 'client',
  prisma-client       provider: 'prisma-client-js',
  prisma-client       output: '/Users/me/projects/src/meproj/node_modules/@prisma/client',
  prisma-client       binaryTargets: [],
  prisma-client       config: {}
  prisma-client     },
  prisma-client     showColors: false,
  prisma-client     logLevel: undefined,
  prisma-client     logQueries: true,
  prisma-client     env: {
  prisma-client       DATABASE_URL: 'postgresql://meadim:mepass@localhost:5432/simple?schema=public&connection_limit=5&connect_timeout=5'
  prisma-client     },
  prisma-client     flags: []
  prisma-client   }
  prisma-client } +0ms
in main()...
  getos { platform: 'darwin', libssl: undefined } +0ms
  engine {
  engine   PRISMA_DML_PATH: '/Users/me/projects/src/meproj/node_modules/@prisma/client/schema.prisma',
  engine   PORT: '52688',
  engine   RUST_BACKTRACE: '1',
  engine   RUST_LOG: 'info',
  engine   LOG_QUERIES: 'true',
  engine   OVERWRITE_DATASOURCES: '[]'
  engine } +0ms
  engine { cwd: '/Users/me/projects/src/meproj/prisma' } +1ms
  plusX Execution permissions of /Users/me/projects/src/meproj/node_modules/@prisma/client/runtime/query-engine-darwin are fine +0ms
  engine { flags: [ '--enable-raw-queries' ] } +1ms
  engine stderr Printing to stderr for debugging +19ms
  engine stderr Listening on 127.0.0.1:52688 +0ms
  engine stdout {
  timestamp: 'Apr 11 08:25:43.598',
  level: 'INFO',
  target: 'quaint::pooled',
  fields: { message: 'Starting a postgresql pool with 5 connections.' }
} +0ms
  engine stdout {
  timestamp: 'Apr 11 08:25:43.605',
  level: 'INFO',
  target: 'prisma::server',
  fields: {
    message: 'Started http server on 127.0.0.1:52688',
    'log.target': 'prisma::server',
    'log.module_path': 'prisma::server',
    'log.file': 'query-engine/prisma/src/server.rs',
    'log.line': 109
  }
} +6ms

**Comment by atjeff** [comment] 2020-04-11 18:06
Changing both to beta.2 in package-lock, wiping node_modules, and reinstalling seemed to work for me. I think an artifact of me accidentally having one on beta1 and the other on beta2 before may have caused this issue.

**Comment by thoughtpoet** [comment] 2020-04-11 18:30
@atjeff and for me as well, thank you much.

**Comment by janpio** [comment] 2020-04-11 19:00
Thanks for reporting back @atjeff and @the-bionic - I am happy this solved it for you but of course am even more confused now because this should not happen and/or cause these problems.

We will definitely look into this.

**Comment by atjeff** [comment] 2020-04-11 19:13
Thanks for being responsive on the weekend @janpio. Stay safe

**Comment by asciant** [comment] 2020-04-11 21:10
I can confirm this fixes the issue in the reproduction as well.

If I recall correctly, this did cross my mind at the time that I encountered the issue, but my recollection was that `@prisma/client` was the only package available as `2.0.0-beta.2` and `@prisma/cli` hadn't received a `2.0.0-beta.2` release. Is it possible that there was a window between the `beta.2` release of `client` and `cli` that resulted in the available versions not matching?

**Comment by pantharshit00** [comment] 2020-04-14 09:57
@asciant Yes, that might be possible.

Closing this now. Please comment here if someone is still experiencing this!

**Closed by pantharshit00** 2020-04-14 09:57 UTC
Labels: 2.0.0-beta.2, bug/2-confirmed, kind/bug, team/engines

**Comment by adrianoresende** [comment] 2020-04-26 02:33
I had the same problem when upgrading from beta1 to beta3, thanks to this issue I managed to solve it after an hour.
I deleted `package-lock.json` and execute `npm i` that solved.
