### ISSUE TITLE
Raw sql Is not working as expected 

### ISSUE THREAD

**Issue by losefor** [prisma/prisma#9333] opened 2021-09-20 11:24 UTC
### Bug description

the new feature(**bug**). **Prisma.sql``** is not working as expected it's only handles strings properly but does not work as expected with **number** .

### in the porstgreSQL databse
 
| minPrice | maxPrice |
|----------|----------|
|   1000     |    5000    |

```ts

const price = 2000 ; 

 ${
          price
          ? Prisma.sql`WHERE  2000 BETWEEN "minPrice" AND "maxPrice" `
          : Prisma.empty
}
```

the above example works fine and retrieve the reuried data

```ts
const price = 2000 ; 

${
          price
          ? Prisma.sql`WHERE  ${price} BETWEEN "minPrice" AND "maxPrice" `
          : Prisma.empty
}
```

the above example is not working at all and not retrieving any data

### Expected behavior

expected to retrieve data from the db 

### Prisma information

  minPrice Float?
  maxPrice Float?

### Environment & setup

Mac Os
PostgreSQL
- Node.js version: v16.8.0

### Prisma Version

```

3.0.2

```

**Comment by Weakky** [comment] 2022-03-31 16:34
Hey @losefor, I'm unable to reproduce your issue with the following script:

```ts
import { PrismaClient, Prisma } from "@prisma/client";

async function main() {
  const prisma = new PrismaClient({
    log: ["info", "query", "warn", "error"],
  });

  const price = 2000;
  const sql = Prisma.sql`SELECT (${price} BETWEEN 1000 AND 2001) as is_between`;
  const res = await prisma.$queryRaw(sql);

  console.log(res); // { is_between: true }
}

main();
```

What version of Prisma are you using? Would you mind providing a reproducible example?

Thank you 🙏

**Comment by Weakky** [comment] 2022-04-25 13:19
I have managed to reproduce your issue after all. This should be fixed next release.

**Comment by Weakky** [comment] 2022-05-05 17:12
Hey,

This issue was fixed by https://github.com/prisma/prisma-engines/pull/2847. It will be available in the next release under the `improvedQueryRaw` feature flag.

Beware that enabling `improvedQueryRaw` is a breaking change. Release notes will contain information as to how to upgrade (so will the documentation).

Thanks for reporting 🙏

**Closed by Weakky** 2022-05-05 17:12 UTC
Labels: bug/0-unknown, kind/bug, topic: raw, team/client
