### ISSUE TITLE
[FER] Nested / cascading deletion via DeleteArgs.select or DeleteArgs.include ?

### ISSUE THREAD

**Issue by yw662** [prisma/prisma#8207] opened 2021-07-10 18:38 UTC
## Problem

`PrismaClient.<model>.delete` allow passing `select` or `include` field via `<Model>DeleteArgs`, but it won't actually do the cascading deletion, and will raise `change you are trying to make would violate the required relation` if the relation is required.

## Suggested solution

Since it allows the parameter, maybe it is good to make use of it.

If sth. like
```js
prisma.user.delete({where: {id}, include: {posts}})
```
The suggestion is that it should delete the included `posts` as well, and, if the relation is required by `posts`, it should be allowed since it is not violating the requirement.

## Alternatives

Currently it can be done by sth. like `transaction([deleteMany(...), delete(...)])`, or `on delete cascade` with an optional-but-actually-required relation.

**Comment by pantharshit00** [comment] 2021-07-11 21:13
Cascade deletes are now in preview and they are embedded in the schema: https://www.prisma.io/docs/concepts/components/prisma-schema/relations/referential-actions


Closing as duplicate of #4711

**Closed by pantharshit00** 2021-07-11 21:13 UTC

**Comment by yw662** [comment] 2021-07-11 21:32
@pantharshit00  It is actually more like an option for cascade deletion without `on delete cascade`. This will offer an option to cascade when the underlying schema is on delete set null.

**Comment by pantharshit00** [comment] 2021-07-11 21:41
This is covered by https://github.com/prisma/prisma/issues/8197

Add you +1 there
