### ISSUE TITLE
Get `JavaScript heap out of memory` error when pushing a bulk date with `createMany`.

### ISSUE THREAD

**Issue by DevYuns** [prisma/prisma#8500] opened 2021-07-30 05:59 UTC
### Bug description

I'm working on migrating data form `mariaDB` to `postgreSQL`.

When I try to push a bulk data with `createMany`, I got error message like below. 
The ballpark data size I'v tried is about `252mb`.

```
<--- Last few GCs --->

[94783:0x120008000]   645373 ms: Scavenge 4031.5 (4114.0) -> 4029.3 (4117.5) MB, 6.5 / 0.0 ms  (average mu = 0.874, current mu = 0.271) allocation failure
[94783:0x120008000]   645387 ms: Scavenge 4034.7 (4117.5) -> 4032.1 (4135.5) MB, 7.2 / 0.0 ms  (average mu = 0.874, current mu = 0.271) allocation failure
[94783:0x120008000]   646371 ms: Mark-sweep 4044.7 (4135.5) -> 4038.1 (4145.2) MB, 967.5 / 0.0 ms  (average mu = 0.814, current mu = 0.109) allocation failure scavenge might not succeed


<--- JS stacktrace --->

FATAL ERROR: MarkCompactCollector: young object promotion failed Allocation failed - JavaScript heap out of memory
 1: 0x10476c668 node::Abort() [/Users/dean/.nvm/versions/node/v15.9.0/bin/node]
 2: 0x10476c7e8 node::errors::TryCatchScope::~TryCatchScope() [/Users/dean/.nvm/versions/node/v15.9.0/bin/node]
 3: 0x1048b77e8 v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [/Users/dean/.nvm/versions/node/v15.9.0/bin/node]
 4: 0x1048b777c v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [/Users/dean/.nvm/versions/node/v15.9.0/bin/node]
 5: 0x104a4a214 v8::internal::Heap::CollectionBarrier::ShutdownRequested() [/Users/dean/.nvm/versions/node/v15.9.0/bin/node]
 6: 0x104a9bc6c v8::internal::EvacuateNewSpaceVisitor::Visit(v8::internal::HeapObject, int) [/Users/dean/.nvm/versions/node/v15.9.0/bin/node]
 7: 0x104a85214 void v8::internal::LiveObjectVisitor::VisitBlackObjectsNoFail<v8::internal::EvacuateNewSpaceVisitor, v8::internal::MajorNonAtomicMarkingState>(v8::internal::MemoryChunk*, v8::internal::MajorNonAtomicMarkingState*, v8::internal::EvacuateNewSpaceVisitor*, v8::internal::LiveObjectVisitor::IterationMode) [/Users/dean/.nvm/versions/node/v15.9.0/bin/node]
 8: 0x104a84e6c v8::internal::FullEvacuator::RawEvacuatePage(v8::internal::MemoryChunk*, long*) [/Users/dean/.nvm/versions/node/v15.9.0/bin/node]
 9: 0x104a84b70 v8::internal::Evacuator::EvacuatePage(v8::internal::MemoryChunk*) [/Users/dean/.nvm/versions/node/v15.9.0/bin/node]
10: 0x104a9fcf0 v8::internal::PageEvacuationTask::RunInParallel(v8::internal::ItemParallelJob::Task::Runner) [/Users/dean/.nvm/versions/node/v15.9.0/bin/node]
11: 0x104a5ffbc v8::internal::ItemParallelJob::Task::RunInternal() [/Users/dean/.nvm/versions/node/v15.9.0/bin/node]
12: 0x104a6038c v8::internal::ItemParallelJob::Run() [/Users/dean/.nvm/versions/node/v15.9.0/bin/node]
13: 0x104a8693c void v8::internal::MarkCompactCollectorBase::CreateAndExecuteEvacuationTasks<v8::internal::FullEvacuator, v8::internal::MarkCompactCollector>(v8::internal::MarkCompactCollector*, v8::internal::ItemParallelJob*, v8::internal::MigrationObserver*, long) [/Users/dean/.nvm/versions/node/v15.9.0/bin/node]
14: 0x104a864e4 v8::internal::MarkCompactCollector::EvacuatePagesInParallel() [/Users/dean/.nvm/versions/node/v15.9.0/bin/node]
15: 0x104a736b4 v8::internal::MarkCompactCollector::Evacuate() [/Users/dean/.nvm/versions/node/v15.9.0/bin/node]
16: 0x104a71478 v8::internal::MarkCompactCollector::CollectGarbage() [/Users/dean/.nvm/versions/node/v15.9.0/bin/node]
17: 0x104a4a878 v8::internal::Heap::MarkCompact() [/Users/dean/.nvm/versions/node/v15.9.0/bin/node]
18: 0x104a48154 v8::internal::Heap::PerformGarbageCollection(v8::internal::GarbageCollector, v8::GCCallbackFlags) [/Users/dean/.nvm/versions/node/v15.9.0/bin/node]
19: 0x104a461f0 v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [/Users/dean/.nvm/versions/node/v15.9.0/bin/node]
20: 0x104a524b8 v8::internal::Heap::AllocateRawWithLightRetrySlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [/Users/dean/.nvm/versions/node/v15.9.0/bin/node]
21: 0x104a52548 v8::internal::Heap::AllocateRawWithRetryOrFailSlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [/Users/dean/.nvm/versions/node/v15.9.0/bin/node]
22: 0x104a2588c v8::internal::Factory::NewFillerObject(int, bool, v8::internal::AllocationType, v8::internal::AllocationOrigin) [/Users/dean/.nvm/versions/node/v15.9.0/bin/node]
23: 0x104d42038 v8::internal::Runtime_AllocateInYoungGeneration(int, unsigned long*, v8::internal::Isolate*) [/Users/dean/.nvm/versions/node/v15.9.0/bin/node]
24: 0x1050321cc Builtins_CEntry_Return1_DontSaveFPRegs_ArgvOnStack_NoBuiltinExit [/Users/dean/.nvm/versions/node/v15.9.0/bin/node]
25: 0x1050331fc Builtins_StringAdd_CheckNone [/Users/dean/.nvm/versions/node/v15.9.0/bin/node]
26: 0x10508d000 Builtins_RegExpReplace [/Users/dean/.nvm/versions/node/v15.9.0/bin/node]
27: 0x1050232b0 Builtins_StringPrototypeReplace [/Users/dean/.nvm/versions/node/v15.9.0/bin/node]
28: 0x203a5e9f1fc
29: 0x10504ea24 Builtins_ArrayMap [/Users/dean/.nvm/versions/node/v15.9.0/bin/node]
30: 0x104fcaed4 Builtins_InterpreterEntryTrampoline [/Users/dean/.nvm/versions/node/v15.9.0/bin/node]
31: 0x104fcaed4 Builtins_InterpreterEntryTrampoline [/Users/dean/.nvm/versions/node/v15.9.0/bin/node]
32: 0x104fcaed4 Builtins_InterpreterEntryTrampoline [/Users/dean/.nvm/versions/node/v15.9.0/bin/node]
33: 0x104fc2504 Builtins_ArgumentsAdaptorTrampoline [/Users/dean/.nvm/versions/node/v15.9.0/bin/node]
34: 0x10504ea24 Builtins_ArrayMap [/Users/dean/.nvm/versions/node/v15.9.0/bin/node]
35: 0x104fcaed4 Builtins_InterpreterEntryTrampoline [/Users/dean/.nvm/versions/node/v15.9.0/bin/node]
36: 0x104fcaed4 Builtins_InterpreterEntryTrampoline [/Users/dean/.nvm/versions/node/v15.9.0/bin/node]
37: 0x1050650a0 Builtins_OrdinaryToPrimitive_String [/Users/dean/.nvm/versions/node/v15.9.0/bin/node]
38: 0x105064df0 Builtins_NonPrimitiveToPrimitive_String [/Users/dean/.nvm/versions/node/v15.9.0/bin/node]
39: 0x10505e4b4 Builtins_ToString [/Users/dean/.nvm/versions/node/v15.9.0/bin/node]
40: 0x105060a0c Builtins_StringConstructor [/Users/dean/.nvm/versions/node/v15.9.0/bin/node]
41: 0x10504ea24 Builtins_ArrayMap [/Users/dean/.nvm/versions/node/v15.9.0/bin/node]
42: 0x104fcaed4 Builtins_InterpreterEntryTrampoline [/Users/dean/.nvm/versions/node/v15.9.0/bin/node]
43: 0x1050650a0 Builtins_OrdinaryToPrimitive_String [/Users/dean/.nvm/versions/node/v15.9.0/bin/node]
44: 0x105064df0 Builtins_NonPrimitiveToPrimitive_String [/Users/dean/.nvm/versions/node/v15.9.0/bin/node]
45: 0x10505e4b4 Builtins_ToString [/Users/dean/.nvm/versions/node/v15.9.0/bin/node]
46: 0x105060a0c Builtins_StringConstructor [/Users/dean/.nvm/versions/node/v15.9.0/bin/node]
47: 0x104fcaed4 Builtins_InterpreterEntryTrampoline [/Users/dean/.nvm/versions/node/v15.9.0/bin/node]
48: 0x104fcaed4 Builtins_InterpreterEntryTrampoline [/Users/dean/.nvm/versions/node/v15.9.0/bin/node]
49: 0x104fcaed4 Builtins_InterpreterEntryTrampoline [/Users/dean/.nvm/versions/node/v15.9.0/bin/node]
50: 0x104fcaed4 Builtins_InterpreterEntryTrampoline [/Users/dean/.nvm/versions/node/v15.9.0/bin/node]
51: 0x104fcaed4 Builtins_InterpreterEntryTrampoline [/Users/dean/.nvm/versions/node/v15.9.0/bin/node]
52: 0x104fcaed4 Builtins_InterpreterEntryTrampoline [/Users/dean/.nvm/versions/node/v15.9.0/bin/node]
53: 0x104fcaed4 Builtins_InterpreterEntryTrampoline [/Users/dean/.nvm/versions/node/v15.9.0/bin/node]
54: 0x104fcaed4 Builtins_InterpreterEntryTrampoline [/Users/dean/.nvm/versions/node/v15.9.0/bin/node]
55: 0x104fc2504 Builtins_ArgumentsAdaptorTrampoline [/Users/dean/.nvm/versions/node/v15.9.0/bin/node]
56: 0x104fcaed4 Builtins_InterpreterEntryTrampoline [/Users/dean/.nvm/versions/node/v15.9.0/bin/node]
57: 0x104fcaed4 Builtins_InterpreterEntryTrampoline [/Users/dean/.nvm/versions/node/v15.9.0/bin/node]
58: 0x10507fc4c Builtins_PromiseResolveThenableJob [/Users/dean/.nvm/versions/node/v15.9.0/bin/node]
59: 0x104fea274 Builtins_RunMicrotasks [/Users/dean/.nvm/versions/node/v15.9.0/bin/node]
60: 0x104fc8668 Builtins_JSRunMicrotasksEntry [/Users/dean/.nvm/versions/node/v15.9.0/bin/node]
61: 0x120008000
error Command failed with signal "SIGABRT".
```

### Expected behavior

pushing data without error.

### Prisma information

Try to push data to below model.

```
generator client {
  provider = "prisma-client-js"
  output   = "../src/generated/client-new"
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

model Artwork {
  id                             String    @id @default(cuid()) @db.VarChar(50)
  productionFromYear             String?   @db.VarChar(4)
  productionToYear               String?   @db.VarChar(4)
  korName                        String?   @db.VarChar(700)
  engName                        String?   @db.VarChar(700)
  meterial                       String?   @db.Text
  dimension                      String?   @db.Text
  heightType                     String?   @db.VarChar(50)
  heightCm                       Decimal?  @db.Decimal(7, 3)
  widthCm                        Decimal?  @db.Decimal(7, 3)
  depthCm                        Decimal?  @db.Decimal(7, 3)
  diameterCm                     Decimal?  @db.Decimal(7, 3)
  heightInch                     Decimal?  @db.Decimal(7, 3)
  widthInch                      Decimal?  @db.Decimal(7, 3)
  depthInch                      Decimal?  @db.Decimal(7, 3)
  diameterInch                   Decimal?  @db.Decimal(7, 3)
  desc                           String?
  modifierId                     String?   @db.VarChar(50)
  registId                       String?   @db.VarChar(50)
  locationLat                    Decimal?  @db.Decimal(15, 12)
  locationLon                    Decimal?  @db.Decimal(15, 12)
  estimatedPriceCurrency         String?   @db.VarChar(50)
  highEstimatedPrice             Decimal?  @db.Decimal(20, 5)
  lowEstimatedPrice              Decimal?  @db.Decimal(20, 5)
  estimatedPriceUSD              Decimal?  @db.Decimal(20, 5)
  estimatedPriceRegistDate       DateTime?
  signiture                      String?   @db.VarChar(1000)
  location                       String?   @db.VarChar(200)
  publicSalesRecordState         String?   @default("100") @db.VarChar(50)
  publicSalesRecordPriceCurrency String?   @default("100") @db.VarChar(50)
  publicSalesRecordPrice         Decimal?  @db.Decimal(20, 5)
  publicSalesRecordDate          DateTime?
  hashtag                        String?   @db.VarChar(1000)
  repColor1                      String?   @db.VarChar(50)
  repColor2                      String?   @db.VarChar(50)
  repColor3                      String?   @db.VarChar(50)
  introUrl                       String?   @db.VarChar(255)
  sizeType                       String?   @db.VarChar(50)

  createdAt DateTime? @default(now())
  updatedAt DateTime? @default(now()) @updatedAt
  deletedAt DateTime?

  artistId String? @db.VarChar(50)
  artist   Artist? @relation(fields: [artistId], references: [id])

  essays   Essay[]
  comments Comment[]
  likes    Like[]
}
```

### Environment & setup

- OS: Mac OS silicon(M1) Bigsur
- Database: PostgreSQL
- Node.js version: 15.9

### Prisma Version

```
2.27
```

**Comment by pantharshit00** [comment] 2021-07-30 06:04
Hello @DevYuns 

Can you please try the Node API preview here? https://www.prisma.io/docs/concepts/components/prisma-engines/query-engine#enable-the-node-api-n-api-preview

It is a more efficient communication method between the client and the engines.

I will have another look here after you report back.

**Comment by pantharshit00** [comment] 2021-07-30 06:06
You might also need to increase the node js heap size itself using `NODE_OPTIONS=--max-old-space-size=1536` (sets heap size to about 1.5G)

**Comment by DevYuns** [comment] 2021-08-02 04:17
Hi! @pantharshit00 

Thank you for kindly answer. but unfortunately I got same errors. To make it works, I use `create` method every single `for loop`. and It takes an hour. 😢

**Comment by janpio** [comment] 2022-02-11 18:16
@DevYuns Can you please share a data sample with us? We would love to be able to reproduce this.

**Comment by DevYuns** [comment] 2022-02-13 04:09
@janpio I finished off that job last year. So I don't have a data anymore. I’m sorry that I can’t help you.

**Comment by mehdi-sp** [comment] 2022-02-15 13:39
Recently we had the same problem while inserting ~1M rows using `createMany`. in my observations it uses at least 3 times more memory than the size of its input. 
![image](https://user-images.githubusercontent.com/62498424/154072266-e4d82fb7-a09a-4341-adb1-e28888dab620.png)
the violet bar on the right of the picture is the input array(~400MB) and the green one on the left is the memory used by prisma client (~1400MB) before the crash. (prisma v3.7.0)

**Comment by kaykhancheckpoint** [comment] 2022-03-24 09:32
I also jsut experienced this issue where im inserting batches of data into my database, the batch size is of around 300k with a total of 2m . With each pass of the loop, the amount of memory in use by the node.js application increases e.g from 1gb -> 3gb. 

It seems like createMany has some memory leak as it holds onto the memory with each pass. 

Switching to plain sql (instead of prisma for this function) resolved the issue for me

**Comment by SevInf** [comment] 2022-09-01 13:46
I was able to reproduce excessive memory usage on batch inserts [here](https://github.com/prisma/reproductions/tree/main/gh-8500). This is more or less verbatim example from @mehdi-sp, thanks a lot for providing that.

What I could not reproduce is memory leak during `createdMany` (see #15136). Which would mean that even though memory usage is excessive, this memory would be later reclaimed by GC. @kaykhancheckpoint  could you provide a reproduction for memory leak you experiencing?

**Comment by jcbfonseca** [comment] 2022-09-02 18:32
@SevInf @janpio : Is there a forecast for this issue  PullRequest integration ?

**Comment by janpio** [comment] 2022-09-02 19:56
No. The "higher than expected" memory usage is not super high priority for us right now (as we are busy with more pressing things). And the "memory leak" (which would probably be more pressing) we could not reproduce. So we will definitely get to improve the memory usage of Prisma one day, but not right now.

Do you have a concrete problem @jcbfonseca that is triggered by this? Additional information can always change the priority.

**Comment by jcbfonseca** [comment] 2022-09-12 12:47
Hi @janpio : please, let me known your analysis about our tests. Is the same issue reported before? Is it possible to increase issue priority ?

**Comment by janpio** [comment] 2022-09-12 20:19
Thanks for the additional information - that is all we need right now. Someone will take a look when we have the time to do so.

**Comment by CleberL** [comment] 2023-07-12 13:32
Hi @janpio, has there been any improvement over this issue in Prisma 5?

**Comment by SevInf** [comment] 2023-07-13 10:42
There are some improvements to memory consumption on the large queries. Re-running @mehdi-sp  example, on 4.16.2 heap grows by 1977 MB after insert, where on 5.0.0 it grows by 555 MB. In both cases, excess memory is succesfully reclaimed by GC.

**Comment by Druue** [comment] 2024-01-02 11:00
Hey @DevYuns, 

Per the updates in Prisma 5 and the lack of further information, we're now closing it.
If folks still have issues on Prisma 5, please open up a new issue

Thank you 🙏

**Closed by Druue** 2024-01-02 11:00 UTC
Labels: bug/1-unconfirmed, kind/bug, topic: prisma-client, team/client, topic: createMany(), topic: performance/memory, topic: js heap out of memory, topic: memory leak, topic: maturity
