### ISSUE TITLE
"Object annotation" like Django

### ISSUE THREAD

**Issue by tasops** [prisma/prisma#4554] opened 2020-12-08 13:14 UTC
## Problem

Howdy! There is no way to annotate custom data/aggregations to objects when querying them from the database. I'm coming from the Django framework that has a [solid implementation](https://docs.djangoproject.com/en/3.1/ref/models/querysets/#annotate) of that and i really miss it. It would be a major improvement to this great framework.

For example, each product has one-to-many relation with reviews and by annotation you could append a custom field to each object when querying them. Simple example below:
```typescript
model Product {
  id      Int     @id @default(autoincrement())
  name    String
  reviews Review[]
}

model Review {
  id         Int     @id @default(autoincrement())
  content    String
  rating     Int
  product    Product @relation(fields: [productId], references: [id])
  productId  Int
}

[
  {
    id: 1,
    name: someName,
    reviews: [...],
    aggregateRating: 3.9, // Annotated field
    reviewCount: 283 // Annotated field
  },
  {
    id: 2,
    name: otherName,
    reviews: [...],
    aggregateRating: 1.4, // Annotated field
    reviewCount: 93 // Annotated field
  }.
]
```

## Suggested solution

Maybe something like chaining relations, but for annotation, so for example:
```typescript
prisma.model
  .findMany() // Or findUnique() etc.
  .annotate({
    fieldName: { // Field that will be annotated to each object
      someAggregateFunction(...) // Value for this particular field as aggregation from relation etc.
    }
  })

// Or:

prisma.model
  .findMany({
    aggregate: {
      // ...some aggregate function...
    }
  })
```
Don't know if that would be feasible, but maybe the best way would be to put existing aggregation api inside each annotation field? With count() included.

## Additional context

Here is a link to Django website and their implementation of this idea.
https://docs.djangoproject.com/en/3.1/ref/models/querysets/#annotate

**Comment by janpio** [comment] 2023-06-17 17:26
Hey @Telluu, it has been quite some while - I apologize for that. Do I understand correctly that you basically want to have some clean models that represent the data in your database, but then define "annotations" in your code that add additional "computed fields" to the result, that are then part of the returned data?

If so, I think we actually built exactly what you are asking for, just slightly different: via Client Extensions, `result` component type to be exact: https://www.prisma.io/docs/concepts/components/prisma-client/client-extensions/result You can define the model you want to extend, which field name the data should have, and a function `compute()` that can do whatever you want based on the other data of the model.

(Also pinging the people that upvotes this issue: @olragon @marxlow @AbundantSalmon @AdemHodzic @joaoflaviosantosmoniari @cabjr @RodrigoJacznik)

**Comment by Telluu** [comment] 2023-06-23 12:59
Thanks for response @janpio.

That's a pretty nice solution, i tested it myself and it solves my problem. But... i was thinking about something more intuitive and easy to use.

I have to define an extended client instead of just doing that "annotation" at the same place and time when making a query. In my opinion that's a little bit weird and adds an unnecessary additional step. Maybe that's the best solution when you take into account the project code structure that I'm not familiar with, so i don't know.

Would it be feasible to modify the feature, so that its possible to do it at the same time when making a query?

Short example of what i mean (or something similar):
```typescript
prisma.model
  .findMany()
  .annotate({ // Or .result()
    fieldName: compute(model) { ... } // Name a field & compute value at the same place
  })
// Dependencies (or needs) should be inferred automatically
```

**Comment by Telluu** [comment] 2023-07-07 11:52
On closer examination i realized that computed fields can only be based on scalar fields, and because of that, it doesn't solve the problem i described in the first post. But i see that there is an issue already that mentions this here #20091.

**Comment by jeroenmaas** [comment] 2024-08-25 10:47
Long time Django developer here which is missing the same feature. Computed fields are nice, but since they are only calculated after the database is done with it can't be used for sorting or filtering. It would be nice if this functionality could be added to Prisma, though I fully understand this would be a place where type safety will become really difficult to enforce.

I did some more digging in the prisma issues and found https://github.com/prisma/prisma/issues/6336 where a workaround was described for virtual columns in mysql see also https://github.com/nikolasburk/generated-columns. I'd prefer to do it code wise not in mysql. Gives me a bit of old skool mysql views vibes. And (at least in mysql) virtual columns are limited to only the data of that table so it wouldn't work for relational data. Though i've seen Prisma has some basic support for that but not played around with it yet.

**Comment by jkomyno** [comment] 2024-12-06 13:42
Hi there,

As part of our effort to clean up our GitHub repo, we’re closing this issue to help focus on features and improvements that align with our focus areas and those of our community. 

If this is issue is still important to you, feel free to reopen the issue and get like-minded users to upvote as we will prioritize fixing issues based on community interest. If you do reopen the issue, please ensure that there’s a clear method for us to reproduce it. 

For more insight into our priorities and how we’re thinking about the future of the Prisma ORM, please see our recent blog post: https://www.prisma.io/blog/prisma-orm-manifesto.

Thank you for your understanding and support!

**Closed by jkomyno** 2024-12-06 13:42 UTC
Labels: kind/feature, domain/client, topic: client api, topic: extend-client
