### ISSUE TITLE
FullTextSearch breaks on doing Alpha Numeric Search

### ISSUE THREAD

**Issue by nurul3101** [prisma/prisma#12714] opened 2022-04-07 10:55 UTC
### Bug description

When doing an alphanumeric search with the fullTextSearch preview feature enabled, we get a connector error.

### How to reproduce

Executing the `main.ts` file with the below mentioned `schema` file should reproduce the error. 

### Expected behavior

Search operation should succeed and not throw any error.

### Prisma information

Schema file
```prisma
// This is your Prisma schema file,
// learn more about it in the docs: https://pris.ly/d/prisma-schema

generator client {
  provider        = "prisma-client-js"
  previewFeatures = ["fullTextSearch"]
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

model Post {
  id        Int     @id @default(autoincrement())
  title     String
  content   String?
  published Boolean @default(false)
}

```

main.ts file with bug
```typescript
import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

async function main() {
  await prisma.post.create({
    data: {
      title: 'Hello World',
      content:
        'Select the SOAP header that does not exist in API 29.0 and earlier versions up to 14.0 and might not be seen in WSDL',
    },
  });

  // All drafts that contain the words
  const result = await prisma.post.findMany({
    where: {
      content: {
        search: 'API 29.0',
      },
    },
  });

  console.log(result);
}

main()
  .catch((e) => {
    throw e;
  })
  .finally(async () => {
    await prisma.$disconnect();
  });

```
Executing the main function would throw this error.

```text
Error occurred during query execution:
ConnectorError(ConnectorError { user_facing_error: None, kind: QueryError(Error { kind: Db, cause: Some(DbError { severity: "ERROR", parsed_severity: Some(Error), code: SqlState("42601"), message: "syntax error in tsquery: \"API 29.0\"", detail: None, hint: None, position: None, where_: None, schema: None, table: None, column: None, datatype: None, constraint: None, file: Some("tsquery.c"), line: Some(726), routine: Some("makepol") }) }) })
```

However, using the `&` operator while searching would give the expected result and not throw any error.

```javascript
  const result = await prisma.post.findMany({
    where: {
      content: {
        search: 'API & 29.0',
      },
    },
  }); 
```

### Environment & setup

- OS: Mac OS
- Database: PostgreSQL
- Node.js version: v14.19.1

### Prisma Version

```
prisma                  : 3.10.0
@prisma/client          : 3.10.0
Current platform        : darwin
Query Engine (Node-API) : libquery-engine 73e60b76d394f8d37d8ebd1f8918c79029f0db86 (at node_modules/@prisma/engines/libquery_engine-darwin.dylib.node)
Migration Engine        : migration-engine-cli 73e60b76d394f8d37d8ebd1f8918c79029f0db86 (at node_modules/@prisma/engines/migration-engine-darwin)
Introspection Engine    : introspection-core 73e60b76d394f8d37d8ebd1f8918c79029f0db86 (at node_modules/@prisma/engines/introspection-engine-darwin)
Format Binary           : prisma-fmt 73e60b76d394f8d37d8ebd1f8918c79029f0db86 (at node_modules/@prisma/engines/prisma-fmt-darwin)
Default Engines Hash    : 73e60b76d394f8d37d8ebd1f8918c79029f0db86
Studio                  : 0.458.0
Preview Features        : fullTextSearch
```

**Comment by janpio** [comment] 2022-04-07 19:14
Searching for `not exist` works as expected @nurul3101?

**Comment by nurul3101** [comment] 2022-04-08 05:28
@janpio Searching for `not exist` also throws the same error. 🤔 
While searching for just `not` provide an incorrect result, an empty array is returned instead of the actual post.

**Comment by matthewmueller** [comment] 2022-04-08 13:57
Hey @nurul3101, this is a duplicate of https://github.com/prisma/prisma/issues/8939

It would apply to query with spaces.

**Closed by matthewmueller** 2022-04-08 13:57 UTC
Labels: bug/1-unconfirmed, kind/bug, team/client, topic: full-text search

**Comment by Crymzix** [comment] 2022-05-30 03:29
@matthewmueller I'm not sure if that issue applies to this. Even if you apply the preprocessing for the query with spaces, this query would still fail because of the numbers contained in it.
