### ISSUE TITLE
Typescript return type is suddenly `any` when having too many fields selected

### ISSUE THREAD

**Issue by coder246** [prisma/prisma#20134] opened 2023-07-09 13:08 UTC
### Bug description

When selecting 14 fields everything is fine, but if I add one more the type returned will be `any`

### How to reproduce

1. Create a schema containing a model with more than 14 fields
2. Create a function

```javascript

async function test() {

 return await prisma.test.findMany({
 select {
      a: true,
      b: true,
      c: true,
      d: true,
      e: true,
      f: true,
     g: true,
     h: true,
     i: true,
     j: true,
     k: true,
     l: true,
     m: true,
     n: true,

     //o: true,

  }

 })

}
```
4. Remove comment before o
5. See return type will be Promise<any>

### Expected behavior

Return correct Promise containing all the types

### Prisma information

```prisma

model test {
 a number
 b number
 c number
 d number
 e number
 f number
 g number
 h number
 i number
 j number
 k number
 l number
 m number
 n number
 o number


}

```

### Environment & setup

- OS: macOS
- Database: CockroachDB
- Node.js version: v20.3.1
- TS Version: 5.1.6

### Prisma Version

```
prisma                  : 4.16.2
@prisma/client          : 4.16.2
Current platform        : darwin-arm64
Query Engine (Node-API) : libquery-engine 4bc8b6e1b66cb932731fb1bdbbc550d1e010de81 (at node_modules/@prisma/engines/libquery_engine-darwin-arm64.dylib.node)
Migration Engine        : migration-engine-cli 4bc8b6e1b66cb932731fb1bdbbc550d1e010de81 (at node_modules/@prisma/engines/migration-engine-darwin-arm64)
Format Wasm             : @prisma/prisma-fmt-wasm 4.16.1-1.4bc8b6e1b66cb932731fb1bdbbc550d1e010de81
Default Engines Hash    : 4bc8b6e1b66cb932731fb1bdbbc550d1e010de81
Studio                  : 0.484.0
Preview Features        : extendedWhereUnique

```

**Comment by millsp** [comment] 2023-07-12 19:57
Hey @Coder246 @jorgerodrigues Sorry, I was not able reproduce, but thanks for the report. Here's what I have tried:

```prisma
generator client {
  provider = "prisma-client-js"
  previewFeatures = []
  output = "client"
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}


model Test {
  id        Int      @id @default(autoincrement())
  a Int
  b Int
  c Int
  d Int
  e Int
  f Int
  g Int
  h Int
  i Int
  j Int
  k Int
  l Int
  m Int
  n Int
  o Int
  p Int
  q Int
  r Int
  s Int
  t Int
  u Int
  v Int
  w Int
  x Int
  y Int
  z Int
}
```
```ts
import { PrismaClient, Prisma } from "./prisma/client"

async function main() {
  const prisma = new PrismaClient();

  const data =  await prisma.test.findMany({
    select: {
        a: true,
        b: true,
        c: true,
        d: true,
        e: true,
        f: true,
        g: true,
        h: true,
        i: true,
        j: true,
        k: true,
        l: true,
        m: true,
        n: true,
        o: true,
        p: true,
        q: true,
        r: true,
        s: true,
        t: true,
        u: true,
        v: true,
        w: true,
        x: true,
        y: true,
        z: true,
    }
})
}

void main()
```

![Screenshot from 2023-07-12 09-44-30](https://github.com/prisma/prisma/assets/18401805/1e550882-b380-4455-8cbc-ee641e7b9ad3)

I have tried it on Prisma `4.16.2` and `5.0.0`, TS `5.1.6` and `5.1.3`, both on Cockroach and Postgres, and with and without `extendedWhereUnique`. Maybe it has to do with the tsconfig, or something else. Could you please submit us a reproduction?

**Comment by Coder246** [comment] 2023-07-13 09:51
Thanks for taking the time to reproduce. I think you used vs code. Maybe it's about the used ide. I encountered the issue with phpstorm.

I will try to create a minimal example project with this issue.

**Comment by jorgerodrigues** [comment] 2023-07-13 12:42
> Thanks for taking the time to reproduce. I think you used vs code. Maybe it's about the used ide. I encountered the issue with phpstorm.
> 
> I will try to create a minimal example project with this issue.
> 
> @jorgerodrigues which ide did you use?

In my case it was in NVim. But in Vscode the result was the same. The way I discovered it at first was by simply:
1. Upgrading prisma
2. Running `prisma generate`
3. Running eslint on the whole codebase -> then it failed with the issue described here

**Comment by millsp** [comment] 2023-07-13 15:56
Hey @jorgerodrigues could you also please give us a reproduction for us to take a look?

**Comment by jorgerodrigues** [comment] 2023-07-13 18:11
I will update it here tomorrow with a reproduction that can be used.
Just another piece of info:
- I only experienced this issue when querying nested relationships through `include` or `select`.
- I didn't see any relation to the number of fields but to the depth of the query.

Again, will try an example tomorrow and post here

**Comment by jorgerodrigues** [comment] 2023-07-15 05:42
> Hey @jorgerodrigues could you also please give us a reproduction for us to take a look?

Okay, I've been trying to recreate this in a new empty project to post here, however I didn't manage yet. 

I do have the issue happening on the main repo at work when trying to upgrade it, but unfortunately I cannot directly post that one here. 

I will continue trying and will update it here if I manage to recreate. 

A question tough: @millsp are you aware of any circumstance where the new type generation brakes or fail to timely show/generate the types? 
I am just wondering if we are hitting some known corner cases in our app at work.

**Comment by Coder246** [comment] 2023-07-16 15:43
I was able to reproduce it. But only when using `select`.

![Bildschirmfoto 2023-07-16 um 17 35 15](https://github.com/prisma/prisma/assets/46609883/2b2a3bcc-04a6-4898-96d1-ddbc2c025e1e)

I uploaded the repo: https://github.com/Coder246/PrismaIssue20134

**Comment by jorgerodrigues** [comment] 2023-07-19 07:35
Do any of you have an idea already on what triggers the issue?

**Comment by millsp** [comment] 2023-07-19 15:08
Not yet, but I will take a look in the coming days.

**Comment by millsp** [comment] 2023-07-21 21:50
Hey @Coder246, I could not reproduce with your repository. `global.prisma` is not defined and hence defaults to `any`. After adding the following to your `index.ts` the result is also properly typed and I don't see any errors. This is what I added to your `index.ts`:

```ts
declare global {
    var prisma: PrismaClient;
}
```

**Comment by millsp** [comment] 2023-07-21 21:51
@jorgerodrigues, if you want, you can give me private access to your repo and I can take alook?

**Comment by Coder246** [comment] 2023-07-22 06:38
@millsp I think I already did this here https://github.com/Coder246/PrismaIssue20134/blob/master/custom.d.ts

**Comment by Coder246** [comment] 2023-07-22 19:37
I just realized it may be a Bug in the IDE. Did I something wrong?

![image](https://github.com/prisma/prisma/assets/46609883/4ffe5d66-cbeb-403b-990d-1ef2e4994d19)

**Comment by millsp** [comment] 2023-07-24 14:03
@Coder246 Interesting, for me `custom.d.ts` is not picked up by VS Code and caused types to resolve to any, maybe could be related to your bug? I am not sure at this stage.

**Comment by Jolg42** [comment] 2023-07-24 14:14
Same thing as @millsp when I tried it.

**Comment by Coder246** [comment] 2023-07-24 15:27
I also tried to put it in Index.ts but with no difference.

**Comment by Coder246** [comment] 2023-07-25 15:43
From the prisma side I would say yes

**Comment by millsp** [comment] 2023-07-25 15:56
We then need your input @jorgerodrigues to be able to drive this forward. Could you help us with a reproduction?

**Comment by janpio** [comment] 2023-08-06 12:31
@jorgerodrigues, did you see Pierre's message? We need your help as we could not figure out how to reproduce this on our own. Thanks!

**Comment by SevInf** [comment] 2023-08-18 12:53
Hey @jorgerodrigues ,
 

With the lack of information and our inability to reproduce this issue, we're now closing it. Feel free to comment if you have any updates about it.
 
Thank you 🙏

**Closed by SevInf** 2023-08-18 12:53 UTC
Labels: bug/0-unknown, kind/bug, topic: prisma-client, topic: client types, tech/typescript, team/client, topic: select
