### ISSUE TITLE
Can't fix "Timed out fetching a new connection from the connection pool"

### ISSUE THREAD

**Issue by maticzav** [prisma/prisma#12545] opened 2022-03-27 10:06 UTC
### Bug description

We are using a small database (2GB of RAM, 48GB of storage, 92 max active connections) and very lightweight queries and Prisma times out frequently. 90% of the queries are `findUnique`-queries and we have set the connection limit to 86 connections. The remaining 10% are `findMany` queries that are not executed as often but have a rather restrictive filter that is indexed.

Frequently (i.e. in ~20% of all cases) `findUnique` queries take more than three seconds to complete or time-out waiting for a connection.

### How to reproduce

Create a DB with 4 tables of 500.000 rows.

### Expected behavior

Unique queries execute instantaneously in all cases, the DB doesn't timeout waiting for a connection in the pool.

Furthermore,

- is it expected that trivial `findMany` queries in tables with <500.000 rows take more than a second?
- what's the expected spec of the DB for Prisma?
- is there any info about the overhead that using Prisma / prisma.raw creates?

### Prisma information

```
generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

model User {
  id String @id @default(cuid())

  createdAt  DateTime @default(now())
  lastActive DateTime @default(now())

  nickname String?
  country  Country?

  expoPushToken String?

  ChallengeAttempts ChallengeAttempt[]
  Leaderboards      Leaderboard[]
  Scores            WeeklyScore[]

  Streaks UserStreak[] @relation("UserStreak")

  // Each user may create challenges that make up _his_ leaderboard.
  // Other players may play those challenges and climb the leaderboard.
  // We track scores of those players in LeaderboardScores relation.
  Challenges        Challenge[]
  LeaderboardScores LeaderboardScore[] @relation("LeaderboardAuthor")

  // This player's scores on other players leaderboards.
  PlayedLeaderboards LeaderboardScore[] @relation("LeaderboardPlayer")

  @@unique([nickname, country])
}

model UserStreak {
  id String @id @default(cuid())

  user   User   @relation("UserStreak", fields: [userId], references: [id])
  userId String @unique

  country Country

  // We track streaks as a day difference between the first solved
  // challenge and the last one.
  //
  // To extend the streak, we check if last solved challenge was less
  // than 48 hours ago and update the lastChallengeSolvedAt date.
  // If the player solved last challenge more than 48 hours ago, we
  // reset the streak start date to the current date.
  streakStartedAt       DateTime
  lastChallengeSolvedAt DateTime?

  @@unique([userId, country])
}

// A table that we use to track weekly scores of the players in the global leaderboard.
model WeeklyScore {
  id String @id @default(cuid())

  createdAt DateTime @default(now())

  weekSinceEpoch Int
  user           User   @relation(fields: [userId], references: [id])
  userId         String

  value Int

  @@unique([weekSinceEpoch, userId])
  @@index([weekSinceEpoch])
}

// A table that we use to track users progress for challenges made by their friends.
model LeaderboardScore {
  id String @id @default(cuid())

  createdAt DateTime @default(now())

  player   User   @relation("LeaderboardPlayer", fields: [playerId], references: [id])
  playerId String

  author   User   @relation("LeaderboardAuthor", fields: [authorId], references: [id])
  authorId String

  score               Int
  completedChallenges Int

  @@unique([playerId, authorId])
}

model Challenge {
  id        String   @id @default(cuid())
  createdAt DateTime @default(now())
  updatedAt DateTime @default(now()) @updatedAt

  date   DateTime
  number Int
  word   String
  ranked Boolean  @default(true)

  country Country

  author   User?   @relation(fields: [authorId], references: [id])
  authorId String?

  starts      Int @default(0)
  completions Int @default(0)
  successes   Int @default(0)

  ChallengeAttempts ChallengeAttempt[]

  @@index([country, date, ranked])
}

enum Country {
  SI // Slovenia
  DE // Deutchland 
  DK // Denmark
  AT // Austria
  CH // Switzerland
  FR // France
  BE // Belgium
  HU // Hungary
  IT // Italy
  NO // Norway
  GB // United Kingdom
}

model ChallengeAttempt {
  id String @id @default(cuid())

  challenge   Challenge @relation(fields: [challengeId], references: [id])
  challengeId String

  user   User   @relation(fields: [userId], references: [id])
  userId String

  Guesses Guess[]

  @@unique([challengeId, userId])
}

model Guess {
  id String @id @default(cuid())

  attempt   ChallengeAttempt @relation(fields: [attemptId], references: [id])
  attemptId String

  guess String
  order Int
}

model Leaderboard {
  id String @id @default(cuid())

  createdAt DateTime @default(now())
  updatedAt DateTime @default(now()) @updatedAt

  name    String
  country Country

  code    String @unique
  Members User[]

  @@unique([name, country])
  @@index([code])
}
```

### Environment & setup

- OS: MacOS
- Database: Postgres
- Node.js version: 16.13.0

### Prisma Version

```
prisma                  : 3.8.0
@prisma/client          : 3.8.0
Current platform        : darwin-arm64
Query Engine (Node-API) : libquery-engine 34df67547cf5598f5a6cd3eb45f14ee70c3fb86f (at ../node_modules/@prisma/engines/libquery_engine-darwin-arm64.dylib.node)
Migration Engine        : migration-engine-cli 34df67547cf5598f5a6cd3eb45f14ee70c3fb86f (at ../node_modules/@prisma/engines/migration-engine-darwin-arm64)
Introspection Engine    : introspection-core 34df67547cf5598f5a6cd3eb45f14ee70c3fb86f (at ../node_modules/@prisma/engines/introspection-engine-darwin-arm64)
Format Binary           : prisma-fmt 34df67547cf5598f5a6cd3eb45f14ee70c3fb86f (at ../node_modules/@prisma/engines/prisma-fmt-darwin-arm64)
Default Engines Hash    : 34df67547cf5598f5a6cd3eb45f14ee70c3fb86f
Studio                  : 0.452.0
```

**Comment by janpio** [comment] 2022-03-27 12:13
The error message in the title and the description that some queries are sometimes slower, indicate you are hitting the _capacity_ limits of your current configuration.

Fundamentally Prisma opens up to the pool size / `connection_limit` (86 in your case) connections in the pool, and then uses them to execute queries against the database. When a new query comes in, it gets one of these connections from the connection pool and executes it. 

If all connection are busy with queries, it has to wait until a connection becomes available and then executes the query. This is what can lead to _some_ queries being slower than the actual SQL under the hood. A good way to figure that out is to log the SQL query duration and compare it to how long the Prisma Client query took. The difference is overhead - and wait time for a connection.

When that wait time it longer than [pool timeout](https://www.prisma.io/docs/concepts/components/prisma-client/working-with-prismaclient/connection-pool#setting-the-connection-pool-timeout), by default 10 seconds, you get an error message instead of waiting longer for the query to succeed so you can handle that manually (either retry or react in some other way like throwing an error). 

So you description with sometimes slower queries and sometimes connection pool timeout errors matches pretty well with your system scrating at the capacity limit it can handle.

So how to go about it? That is a difficult and complex questions. There are multiple approaches:

1. Update Prisma Client to a newer version. We frequently fix bugs and improve things. Especially 3.12.0 in ~10 days should improve the connection pool behavior, but already 3.11.0 should be better than 3.8.0.
1. Make sure you do not have additional apps or instances running that connect to this database. Your description above is about 1 app instance running Prisma Client that has a pool size of 86. If there are "other players", this could influence thigns a lot.
2. Get an overview what queries you are sending and how long they take. Does it make sense hat 86 of them are running at the same time sometimes? Does your database metrics confirm that? Does the math work out for the # of requests you handle? (Caution: Each request probably executes multiple Prisma queries which might run multiple SQL queries under the hood)
3. Send less queries. Less queries means less load. Can you avoid some? Cache some?
4. Send faster queries. Are you potentially missing some indexes that could improve the query performance overall?
5. Measure if you have query queing/waiting time or something else (database side, e.g. overload) that makes your queries slower. Knowing that will inform further decisions.
6. Look more at your database: Does it have CPU spikes? Other error messages in the log files?
7. Increase the pool timeout to a higher value and see how that changes the behavior.
8. Scale up your database so it can reply to queries faster.
9. Scale up your database so it can can handle more connections.
10. Put PgBouncer in front of your database so the connection limit can be increased that way.

That way you can usually figure out what is going on and how to fix it.

To your additional concrete questions:

> is it expected that trivial findMany queries in tables with <500.000 rows take more than a second?

That depends on the SQL that is executed underneath. Prisma "only" runs SQL and then transforms the data. If one of the two is very resource intensive, that will take time. Start by looking at the SQL.

> what's the expected spec of the DB for Prisma?

Prisma does not have special requirement for the database. What kind of database you need depends on your queries and the request patterns you have. At some point the "bandwidth" (# connections, length of queries leads to all connections being busy all the time) of all the connection is just reached, and then you will get error message or timeouts. See the strategies above how to handle that.

> is there any info about the overhead that using Prisma / prisma.raw creates?

Overhead of course is there (need to figure out what the query means, what the SQL for that looks like, execute it, get the data, transform the data inot something JS will like, and then return the data to the app.) but usually does not matter that much in most usage scenarios. Raw SQL executed via the native database client will always be faster though (unless you write less optimal queries or more than what Prisma would generate. Which happens more often that we would have expected.)

**Comment by Weakky** [comment] 2023-07-13 14:20
Hey @maticzav,

Have you perhaps managed to solve your issue? If so, do you have any updates for us that could help us make the experience better for users? (eg: better docs)

Thanks! 🙏

**Comment by maticzav** [comment] 2023-07-13 15:13
@Weakky I don't think we did. I think we started using something else entirely, because we continualy kept hitting the limit with Prisma.

**Comment by jharrell** [comment] 2023-07-26 14:28
@maticzav Thank you for your reply and your patience! For now, we're going to be closing this issue but if you run into something similar, please open a new issue.

**Closed by jharrell** 2023-07-26 14:28 UTC
Labels: bug/0-unknown, kind/bug, team/client, topic: connection pool, topic: pool_timeout

**Comment by raulsanchez1024** [comment] 2023-08-06 15:31
I have a Postgres DB with a limit of 97 connections. However, Prisma frequently times out when it reaches ~10 connections. 

@maticzav what solution did you move over to?

**Comment by maticzav** [comment] 2023-08-06 16:15
Funnily enough I am trying Drizzle. Impressive experience so far, especially the simplicity.

**Comment by janpio** [comment] 2023-08-06 18:53
> I have a Postgres DB with a limit of 97 connections. However, Prisma frequently times out when it reaches ~10 connections.

Can you open a new discussion or issue about this @raulsanchez1024? A closed issue is not the right place to start a conversation, which we totally want to do. (For example: What is the size of the connection pool you have configured for Prisma?)

**Comment by maticzav** [comment] 2023-08-07 09:58
@janpio could you back reference this issue when you create a new one? I am also interested in hearing the wider context of @raulsanchez1024's problems and possible solutions.

> My 2cents; I don't wholly agree with the sentiment of the "closed issue is not the right place to start a conversation" especially when you close the issue with "we won't be looking into it". 
> This is also like the third issue that I spotted with the same pattern of "create a new issue → opens a new issue → we won't be looking into it → create a new issue" and it undermines my trust in Prisma which sucks because I love Prisma.

**Comment by janpio** [comment] 2023-08-07 13:20
Of course, maybe @raulsanchez1024 can also just @ mention you when he opens a new issue.

> My 2cents; I don't wholly agree with the sentiment of the "closed issue is not the right place to start a conversation" especially when you close the issue with "we won't be looking into it".
> This is also like the third issue that I spotted with the same pattern of "create a new issue → opens a new issue → we won't be looking into it → create a new issue" and it undermines my trust in Prisma which sucks because I love Prisma.

Existing issues are bad places to start an investigation because we do not have the information the issue template asks for. I have no idea what Prisma version Raúl is using, that database he is talking to, and so on. 

If we later figure out he has an actual problem, it in no way has to mean that it was caused by the same problem you had. "Timed out fetching a new connection from the connection pool" is a generic "There is too much stuff going on" error message that can have a million reasons unfortunately.

And finally, you know we never just close issues with "we won't be looking into it". We closed this one as we did not have enough information to understand what was happening, and you indicated that you could not provide more information anymore. That is fine, but it means we have to close the issue as there is nothing actionable for us.
