### ISSUE TITLE
Prisma in Lambda Layer with AWS Amplify - "@prisma/client did not initialize yet"

### ISSUE THREAD

**Issue by Etep15** [prisma/prisma#13883] opened 2022-06-17 17:29 UTC
### Bug description

We have an AWS Amplify project and with that we have prisma in our lambda layer for use in all the lambda functions. Works great. 

We are trying to setup proper CI/CD so that when we merge from our dev branch over to test amplify will automatically deploy the code. This part is working. However when we hit any endpoint of any lambda function we get the dreaded "@prisma/client did not initialize yet" error. 

If we do a `prisma generate` and then an `amplify push` everything works and we do not see that error.

However if we do `prisma generate` and then `git push origin test` to kick off the amplify auto deployment we get the error after the deployment completes. 

My understanding is that when amplify kicks off the autodeployment our client is being removed and it reinstalls everything. I saw a blog post about adding `"postinstall":"prisma generate"` to the scripts in the package.json (and adding the prisma cli). But this then complains that it cannot find the `prisma/prisma.schema`. I tried specifying the directory with `prisma generate --schema=opt/prisma/prisma.schema` (and a whole bunch of other paths) but it still kept complaining it couldn't find the prisma.schema. 

Welcome any thoughts on getting this to work? I assume it's just a path issue? What would be the path then? I don't know if we are running from lib/nodejs or from the root of my function or from some deeper path? Is this even the right course of action?

### How to reproduce

1. Create AWS amplify project
2. link amplify environment to git branch using Amplify console.
3. Setup prisma with lambda layer (may be the case for a regular lambda function too)
4. git push origin main #if that's your branch you used to setup above link with Amplify
5. Wait for deployment to complete
6. Hit endpoint on lambda function that uses lambda layer
7. Check error in cloudformation logs. Will see @prisma/client did not initialize yet

### Expected behavior

prisma is initialized and ready to go.

### Prisma information

version 3.14.0

### Environment & setup

node version 14.17.1
Create AWS amplify project
Link amplify project to git branch
Turn on CI/CD for that amplify environment

### Prisma Version

```
prisma                  : 3.14.0
@prisma/client          : 3.14.0
Current platform        : darwin
Query Engine (Node-API) : libquery-engine 2b0c12756921c891fec4f68d9444e18c7d5d4a6a (at node_modules/@prisma/engines/libquery_engine-darwin.dylib.node)
Migration Engine        : migration-engine-cli 2b0c12756921c891fec4f68d9444e18c7d5d4a6a (at node_modules/@prisma/engines/migration-engine-darwin)
Introspection Engine    : introspection-core 2b0c12756921c891fec4f68d9444e18c7d5d4a6a (at node_modules/@prisma/engines/introspection-engine-darwin)
Format Binary           : prisma-fmt 2b0c12756921c891fec4f68d9444e18c7d5d4a6a (at node_modules/@prisma/engines/prisma-fmt-darwin)
Default Engines Hash    : 2b0c12756921c891fec4f68d9444e18c7d5d4a6a
Studio                  : 0.460.0
```

**Comment by matthewmueller** [comment] 2022-06-21 23:25
Hey @Etep15

> However if we do prisma generate and then git push origin test to kick off the amplify auto deployment we get the error after the deployment completes.

What's the error that you encouter?

**Comment by Markkos89** [comment] 2022-07-10 20:21
Hi @Etep15 ! How are you triggerin the deployment? You are leaving this to amplify right?
There is no way to add a "step" where you can run the prisma generate command? before the build and after the installation of the dependencies?
I was facing something similiar but with github actions and could resolve it.

Regards!

**Comment by Darkmift** [comment] 2023-01-31 16:15
So I cant say I understand much...once I removed the custom output path and the client was re generated in the default location instead, the issue did not persist

Figured I'd share with ya'll in hopes this helps.

**Comment by jkomyno** [comment] 2024-12-30 15:31
Closing this in favour of https://github.com/prisma/prisma/issues/25332.
This is also a duplicate of the already closed issue https://github.com/prisma/prisma/issues/22828.

**Closed by jkomyno** 2024-12-30 15:31 UTC
Labels: bug/1-unconfirmed, kind/bug, topic: prisma-client, domain/client, topic: deployment/aws-lambda, topic: @prisma/client did not initialize yet, topic: aws
