### ISSUE TITLE
Add connector for arangodb

### ISSUE THREAD

**Issue by apoveda25** [prisma/prisma#8499] opened 2021-07-30 03:23 UTC
## Problem

There is currently a client for arangodb that supports js / ts, but it would be great if Prisma ORM supports this database.

## Suggested solution

Prism ORM should use ArangoDB's graph-oriented model, making one-to-one, one-to-many, many-to-one, and many-to-many relationships modeled using a pivot or join collection for each of these. To represent a common table in the sql world, ArangoDB's node collections can be used. Migrations could create the collections in ArangoDB and their respective schemas.

An additional feature would be the cross-sectional queries, which traverse the graph at a depth N, for this, nested relationships could be used, as follows:
...
const publishedPosts = await prism.post.findMany ({
    where: {published: true},
    include: {
        author: {
            books: true
        }
    },
  })
...

This should return the published pots, with their respective author and each author's books.

**Comment by pantharshit00** [comment] 2021-07-30 04:05
Hello,

This connector has been already requested before so I am going to close this as duplicate of https://github.com/prisma/prisma/issues/2535

**Closed by pantharshit00** 2021-07-30 04:05 UTC
