### ISSUE TITLE
Type of property 'AND' circularly references itself in mapped type when using jest-mock-extended

### ISSUE THREAD

**Issue by revmischa** [prisma/prisma#10203] opened 2021-11-11 07:29 UTC
### Bug description

```
  validateUpsert(args: PrismaTypes.CandidateUpsertArgs) {
    return Prisma.validator<PrismaTypes.CandidateUpsertArgs>()(args)
  }
```

```
packages/repo/src/repository/candidate.ts:22:12 - error TS2615: Type of property 'AND' circularly references itself in mapped type '{ [K in keyof CandidateCommentScalarWhereInput]: K extends keyof CandidateCommentScalarWhereInput ? Exact<CandidateCommentScalarWhereInput[K], CandidateCommentScalarWhereInput[K]> : CandidateCommentScalarWhereInput[K]; }'.
```

### Environment & setup

- OS: 
- Database: 
- Node.js version: 

### Prisma Version

```

```

**Comment by janpio** [comment] 2021-11-12 14:35
Can you please give us some more information besides the code snipper and error message so we know what lead to this code? How can we reproduce?

**Comment by revmischa** [comment] 2021-11-12 14:46
<img width="1101" alt="Screen Shot 2021-11-12 at 16 43 26" src="https://user-images.githubusercontent.com/245131/141485024-6bcaea5d-9e77-4a91-b017-4345eb8336ab.png">

<img width="1442" alt="Screen Shot 2021-11-12 at 16 45 25" src="https://user-images.githubusercontent.com/245131/141485280-6a7b4896-6d82-402c-a813-4dfc83b18383.png">

```
Type of property 'AND' circularly references itself in mapped type '{ [K in keyof CandidateCommentWhereInput]: K extends keyof CandidateCommentWhereInput ? Exact<CandidateCommentWhereInput[K], CandidateCommentWhereInput[K]> : CandidateCommentWhereInput[K]; }'.
```

I'm not sure how to reproduce it sorry but maybe others are having this problem and can share. It's a table with about 10 relations

**Comment by janpio** [comment] 2021-11-12 16:33
Can you share the relevant part of the schema maybe?

**Comment by jacobdr** [comment] 2021-12-25 22:40
Not that its all that helpful but I hit this as well following the [instructions on unit testing](https://www.prisma.io/docs/guides/testing/unit-testing). The generated types for our project our private but maybe I can come up with a small repro. 

As a workaround I did something like this:

```typescript
import { mock, mockReset, MockProxy } from 'jest-mock-extended';
import { PrismaService, PrismaClient, createPrismaError } from 'src/modules/prisma';
import { UsersServicePrisma } from './users.service.prisma';

describe('UsersServicePrisma:Unit', () => {
    let usersService: UsersServicePrisma;

    const userPrismaMock: MockProxy<Pick<PrismaClient['user'], 'findUnique' | 'update'>> = mock();
    const mockPrismaClient = {
        user: userPrismaMock,
    };

    beforeEach(async () => {
        mockReset(userPrismaMock);
        // Kind of annoying cast here, leaving it as a form of documentation
        usersService = new UsersServicePrisma(mockPrismaClient as unknown as PrismaService);
    });

    it('Tests something...', () => {
        const result = { foo: 'bar' };
        userPrismaMock.findUnique.mockResolvedValueOnce(result as any);
        // expectations....
    })
})
```

**Comment by marbemac** [comment] 2021-12-31 19:07
We're running into something similar - in our case, narrowed it down to something in the `groupBy` typings. If we do the below, the type error goes away:

```ts
export const dbMock = db as unknown as DeepMockProxy<{
  stores: Omit<PrismaClient['stores'], 'groupBy'>;
}>;
```

**Comment by marbemac** [comment] 2021-12-31 19:20
Ah, actually `strictNullChecks` fixes it for us (https://github.com/prisma/prisma/discussions/2083#discussioncomment-748336).

**Comment by revmischa** [comment] 2022-01-01 08:08
I have `"strictNullChecks": true` and the error persists for me

**Comment by AnthonyLzq** [comment] 2022-01-24 00:59
Same problem here, this is my code:

```ts
import { PrismaClient, User } from '@prisma/client'
import { mockDeep, DeepMockProxy } from 'jest-mock-extended'

import { getOneAvocado } from '../src/graphql/models/avocado'

type ResolverContext = {
  orm: PrismaClient
  user?: User
}

type MockResolverContext = {
  orm: DeepMockProxy<PrismaClient>
  user: User | undefined
}

const createMockContext = (): MockResolverContext => {
  return {
    orm: mockDeep<PrismaClient>(),
    user: undefined
  }
}
```

My prisma model:

```prisma
generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "sqlite"
  url      = "file:./dev.db"
}

model User {
  id        Int      @id @default(autoincrement())
  username  String   @unique
  password  String
  createdAt DateTime @default(now())
}
```

The output:

![image](https://user-images.githubusercontent.com/43073718/150706214-15f96fab-088a-49f3-a2b8-4df25d8d5394.png)

**Comment by AntoineGGG** [comment] 2022-01-26 07:05
Same issue here:

`import { createUser, updateUsername } from "./function";
import { prismaMock } from "../singleton";
import { UtilisateursService } from "../src/main/utilisateurs/utilisateurs.service";
import { UtilisateursController } from "../src/main/utilisateurs/utilisateurs.controller";

describe("It should test utilisateur manipulation", () => {
  let utilisateursController: UtilisateursController;
  let utilisateursService: UtilisateursService;

  test("should create new user ", async () => {
    const user = {
      id: 1,
      email: "hello@prisma.io",
      password: "1234567",
      dateCreation: new Date(),
      dateModification: new Date(),
    };

    prismaMock.utilisateur.create.mockResolvedValue(user),
      await expect(utilisateursService.create(user)).resolves.toEqual({
        id: 1,
        email: "hello@prisma.io",
        password: "1234567",
        dateCreation: new Date(),
        dateModification: new Date(),
      });
  });
});`
`    __tests__/user.spec.ts:19:5 - error TS2615: Type of property 'AND' circularly references itself in mapped type '{ [K in keyof { AND?: Enumerable<UtilisateurScalarWhereWithAggregatesInput>; OR?: Enumerable<UtilisateurScalarWhereWithAggregatesInput>; ... 5 more ...; dateModification?: string | ... 1 more ... | DateTimeWithAggregatesFilter; }]: Or<...> extends 1 ? { ...; }[K] extends infer TK ? GetHavingFields<...> : never : {} ...'.

    19     prismaMock.utilisateur.create.mockResolvedValue(user),
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    __tests__/user.spec.ts:19:5 - error TS2615: Type of property 'NOT' circularly references itself in mapped type '{ [K in keyof { AND?: Enumerable<UtilisateurScalarWhereWithAggregatesInput>; OR?: Enumerable<UtilisateurScalarWhereWithAggregatesInput>; ... 5 more ...; dateModification?: string | ... 1 more ... | DateTimeWithAggregatesFilter; }]: Or<...> extends 1 ? { ...; }[K] extends infer TK ? GetHavingFields<...> : never : {} ...'.

    19     prismaMock.utilisateur.create.mockResolvedValue(user),
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    __tests__/user.spec.ts:19:5 - error TS2615: Type of property 'OR' circularly references itself in mapped type '{ [K in keyof { AND?: Enumerable<UtilisateurScalarWhereWithAggregatesInput>; OR?: Enumerable<UtilisateurScalarWhereWithAggregatesInput>; ... 5 more ...; dateModification?: string | ... 1 more ... | DateTimeWithAggregatesFilter; }]: Or<...> extends 1 ? { ...; }[K] extends infer TK ? GetHavingFields<...> : never : {} ...'.

    19     prismaMock.utilisateur.create.mockResolvedValue(user),`

**Comment by stepanic** [comment] 2022-01-30 06:36
I also have a similar issue.

<img width="854" alt="Screenshot 2022-01-30 at 07 32 41" src="https://user-images.githubusercontent.com/315282/151689423-c66a4ba1-06af-47b6-bb48-869779ee0b1b.png">

Dirty workaround (temp fix) with `any`
<img width="537" alt="Screenshot 2022-01-30 at 07 35 48" src="https://user-images.githubusercontent.com/315282/151689458-ab640242-3c92-4599-bdb2-3ce77ece6073.png">

**Comment by AnthonyLzq** [comment] 2022-03-26 02:48
Any suggestion guys?

**Comment by msreekm** [comment] 2022-03-29 19:30
same issue here as well, this makes prisma unusable if you are serious about unit testing!

**Comment by sumit-tw** [comment] 2022-04-04 11:36
We have used this documentation https://www.prisma.io/docs/guides/testing/unit-testing for mocking prisma client in our unit test and this error is blocking us.  (As we are using TypeScript we can't compile)

**Comment by lensbart** [comment] 2022-04-08 17:46
> same issue here as well, this makes prisma unusable if you are serious about unit testing!

It doesn’t. You can disable the warning by adding `// @ts-expect-error -- awaiting fix: https://github.com/prisma/prisma/issues/10203` to the offending line.

**Comment by AnthonyLzq** [comment] 2022-04-10 05:51
> > same issue here as well, this makes prisma unusable if you are serious about unit testing!
> 
> Have you tried disabling the warning by adding `// @ts-expect-error -- awaiting fix: https://github.com/prisma/prisma/issues/10203` before the offending line?

I have, this is what I got:

```
test/api.test.ts:17:3 - error TS2578: Unused '@ts-expect-error' directive.
```

**Comment by lensbart** [comment] 2022-04-10 06:33
Yeah, that’s because the error can occur alternatively at different places in your codebase, wherever the TypeScript compiler encounters the first instance of your mocked Prisma client. And because `tsc` can evaluate files incrementally, the error can jump from one place to another, leading to unused nused `@ts-expect-error` directives.

Try `@ts-ignore` instead.

**Comment by Vellanci** [comment] 2022-05-01 06:23
> I've spent some time trying to reproduce this with no success (`prisma@dev`, `jest-mock-extended@2.0.5`).
> 
> It would be super helpful if someone could provide a reproduction, or at least some more clues.

(`'@prisma/client': ^3.13.0` (3.13.0), `jest-mock-extended: ^2.0.5` (jest-mock-extended: 2.0.5_jest@27.5.1+typescript@4.6.3), prisma: ^3.13.0 (3.13.0))

```prisma

generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "mongodb"
  url      = env("DATABASE_URL")
}

model User {
  id    String @id @default(cuid()) @map("_id")
  email String @unique
}
```
```typescript
import { PrismaClient, User } from '@prisma/client';
import { DeepMockProxy, mockDeep } from 'jest-mock-extended';
import { randomUUID } from 'crypto';

describe('#10203', () => {
  it('cannot compile', async () => {
    const user: User = { id: randomUUID(), email: 'ex@mp.le' };
    const mock = mockDeep<PrismaClient>();
    const prisma: DeepMockProxy<PrismaClient> =
      mock as unknown as DeepMockProxy<PrismaClient>;
    prisma.user.create.mockResolvedValue(user);
  });
});
```

**Comment by aqrln** [comment] 2022-05-02 11:03
@Vellanci no compile errors for me here. What is your TypeScript version?

**Comment by aqrln** [comment] 2022-05-02 12:15
@Vellanci here's your reproduction as a clonable repo: https://github.com/aqrln/prisma-jest-mock-repro. Is there anything I'm doing wrong or am I missing something?

**Comment by Vellanci** [comment] 2022-05-03 06:55
@aqrln I tried your repo and it worked ok. Then I tried merging my repo bit by bit and came to conclusion that the difference is in our tsconfig.json. You can either:

- comment `strict: true` (or set to false) in your tsconfig.json
- leave `strict: true` but add `strictNullChecks:false` there

Then you can see TS2615 error either by compiling with `tsc` or just in Webstorm

**Comment by aqrln** [comment] 2022-05-03 08:59
@Vellanci using `strictNullChecks: true` is required here, [as per the docs](https://www.prisma.io/docs/guides/testing/unit-testing#dependency-injection).
<img width="711" alt="image" src="https://user-images.githubusercontent.com/4923335/166427399-8780a1bc-ce6f-4fa0-bc9f-815475064288.png">

I've added the `bug/0-unknown` label back, since there's a [comment](https://github.com/prisma/prisma/issues/10203#issuecomment-1003523280) from @revmischa about the error persisting for them even with `strictNullChecks`.

**Comment by Vellanci** [comment] 2022-05-03 14:20
> @Vellanci using `strictNullChecks: true` is required here, [as per the docs](https://www.prisma.io/docs/guides/testing/unit-testing#dependency-injection). <img alt="image" width="711" src="https://user-images.githubusercontent.com/4923335/166427399-8780a1bc-ce6f-4fa0-bc9f-815475064288.png">
> 
> I've added the `bug/0-unknown` label back, since there's a [comment](https://github.com/prisma/prisma/issues/10203#issuecomment-1003523280) from @revmischa about the error persisting for them even with `strictNullChecks`.

Got it. Thanks for explaining

**Comment by pantharshit00** [comment] 2022-06-02 13:33
Hello, Can other people in thread can also confirm above solution addresses their use case?

**Comment by lensbart** [comment] 2022-06-02 13:36
> Hello, Can other people in thread can also confirm above solution addresses their use case?

In my case, the issue was resolved by making my codebase pass with `"strict": true` (i.e. `"strictNullChecks": true`) in `tsconfig.json`.

**Closed** 2022-06-02 15:17 UTC
Labels: bug/0-unknown, kind/bug, topic: client types, team/client

**Comment by dicrescenzoa** [comment] 2023-03-02 13:52
in case someone is still struggling with this problem and cannot set `strictNullChecks: true` I've solved the problem in this way:
```ts
export const prismaMock = mockDeep<PrismaClient>() as unknown as DeepMockProxy<{
  // this is needed to resolve the issue with circular types definition
  // https://github.com/prisma/prisma/issues/10203
  [K in keyof PrismaClient]: Omit<PrismaClient[K], "groupBy">;
}>;
```
