### ISSUE TITLE
Where filter not working with JSON.not with another condition

### ISSUE THREAD

**Issue by AnandChowdhary** [prisma/prisma#6755] opened 2021-04-23 14:40 UTC
## Bug description

Please see this repository for reproduction: https://github.com/AnandChowdhary/prisma-6755-reproduction

If you have a `findMany` with a JSON filter (using `not`) and another condition, the second condition is entirely ignored:

```ts
console.log(
  await prisma.user.findMany({ where: { AND: [{ data: { not: "example-string" } }, { id: 2 }] } })
);
```

In the above, I would expect that Prisma returns all users that don't have this JSON value in `data` and their ID is 2. Instead, Prisma just returns all users without this JSON value, completely ignoring the second condition.

## Schema and code

```prisma
datasource mysql {
  provider = "mysql"
  url      = env("DATABASE_URL")
}

generator client {
  provider = "prisma-client-js"
}

model User {
  id    Int     @id @default(autoincrement())
  email String  @unique
  name  String?
  data  Json?
}
```

```ts
// Create a user without JSON
await prisma.user.create({
  data: { id: 1, email: "hello-1@example.com", name: "First" },
});
// Create a user with JSON data
await prisma.user.create({
  data: {
    id: 2,
    email: "hello-2@example.com",
    name: "Second",
    data: { hello: "second" },
  },
});
// Create another user with JSON data
await prisma.user.create({
  data: {
    id: 3,
    email: "hello-3@example.com",
    name: "Third",
    data: { hello: "third" },
  },
});

console.log(
  "All users with JSON data and their ID is 2",
  await prisma.user.findMany({ where: { data: { not: "example-string" }, id: 2 } })
);
// SHOULD DO THIS: Logs an array of a single user with ID 2
// ACTUALLY DOES THIS: Logs an array of both users with ID 2 and 3
```

## Environment & setup

- OS: macOS
- Database: MySQL
- Node.js version: v14.16.0
- Prisma version: 2.21.2

```
prisma               : 2.21.2
@prisma/client       : 2.21.2
Current platform     : darwin
Query Engine         : query-engine e421996c87d5f3c8f7eeadd502d4ad402c89464d (at node_modules/@prisma/engines/query-engine-darwin)
Migration Engine     : migration-engine-cli e421996c87d5f3c8f7eeadd502d4ad402c89464d (at node_modules/@prisma/engines/migration-engine-darwin)
Introspection Engine : introspection-core e421996c87d5f3c8f7eeadd502d4ad402c89464d (at node_modules/@prisma/engines/introspection-engine-darwin)
Format Binary        : prisma-fmt e421996c87d5f3c8f7eeadd502d4ad402c89464d (at node_modules/@prisma/engines/prisma-fmt-darwin)
Default Engines Hash : e421996c87d5f3c8f7eeadd502d4ad402c89464d
Studio               : 0.371.0
```

**Comment by pantharshit00** [comment] 2021-04-30 13:20
I can reproduce this. Thanks for detailed reproduction repository.

**Comment by Weakky** [comment] 2021-05-17 13:55
Hey @AnandChowdhary and @pantharshit00, I cannot reproduce this issue anymore on `2.22.1`.

I'm closing now, please let me know if I missed something.

**Closed by Weakky** 2021-05-17 13:55 UTC
Labels: bug/2-confirmed, kind/bug, team/client, topic: json
