### ISSUE TITLE
Prisma Caching Middleware

### ISSUE THREAD

**Issue by ninecodes** [prisma/prisma#11777] opened 2022-02-12 10:01 UTC
Hello there, it would be great if we could have either:

- Out of the box caching support for queries which would greatly improve performance and definitely get a lot of people hooked up to Prisma as it is an amazing tool

Or:

- Add some form of middleware that would easily let us turn it on and control for what we want caching and configure it to our liking, so we would ofc need to enable it first by going to the generator:

```ts
generator client {
  provider        = "prisma-client-js"
  previewFeatures = ["middlewares"]
}
```

And maybe a similar approach to this one: [prisma-lrucache-middleware](https://github.com/abhiaiyer91/prisma-lrucache-middleware )

It would definitely be a great win win for Prisma to offer this feature to it's Users as caching is a big topic and if that got handled, I am sure people would go crazy and with all the recent features coming out I think it would add to the value of Prisma immensely.

Prisma can benefit a lot by adding this feature and it would probably skyrocket it to even more fame 🚀🚀🚀

Hope to hear back from you guys :)

**Comment by Asjas** [comment] 2022-02-20 13:00
Similar issue has been created here https://github.com/prisma/prisma/issues/3165 🙂

**Comment by TasinIshmam** [comment] 2022-11-07 16:26
Closing as duplicate of #3165

**Closed by TasinIshmam** 2022-11-07 16:26 UTC
Labels: kind/feature, topic: middleware, team/client
