### ISSUE TITLE
next js prisma - undefined when in vercel deployment

### ISSUE THREAD

**Issue by sunrunner4kr-simon** [prisma/prisma#6730] opened 2021-04-22 18:58 UTC
Hi all

Have been asked to raise a bug report. Details below.

So...I have an api in Next js that uses Prisma Client. Prisma is imported from the global object defined in prisma.js

Locally everything builds and runs fine. I get no errors and the prisma variable is defined. However, when it's deployed in Vercel, prisma is undefined...I can't work out why.

It was also working fine before when I was calling a prisma instance in each page - I changed it to declare prisma globally (so I wouldn't get multiple instances)

If anyone has any suggestions, I'd much appreciate it.

Prisma GH discussion here: - https://github.com/prisma/prisma/discussions/6651

Here's the error: -

```
2021-04-20T18:12:55.922Z 74782da2-8f0f-448c-bd44-ee81ead879ed ERROR TypeError: Cannot read property 'upsert' of undefined
at exports.modules.5712.webpack_exports.default (/var/task/nextjs-store/.next/server/pages/api/success.js:57:115)
at apiResolver (/var/task/nextjs-store/node_modules/next/dist/next-server/server/api-utils.js:8:7)
at processTicksAndRejections (internal/process/task_queues.js:93:5)
at async Server.handleApiRequest (/var/task/nextjs-store/node_modules/next/dist/next-server/server/next-server.js:67:462)
at async Object.fn (/var/task/nextjs-store/node_modules/next/dist/next-server/server/next-server.js:59:492)
at async Router.execute (/var/task/nextjs-store/node_modules/next/dist/next-server/server/router.js:25:67)
at async Server.run (/var/task/nextjs-store/node_modules/next/dist/next-server/server/next-server.js:69:1042)
at async Server.handleRequest (/var/task/nextjs-store/node_modules/next/dist/next-server/server/next-server.js:34:504)
at async Server. (/var/task/nextjs-store/___next_launcher.js:26:9)
```

And here's the code: -

```node js
import eBayApi from "@hendt/ebay-api";
import prisma from "../../lib/prisma";

const eBay = new eBayApi({
  appId: "SimonEdg-StoreApp-XXXXXXXXXXXXXXXX",
  certId: "SBX-XXXXXXXXXXXXXXXX",
  sandbox: true,

  scope: [
    "https://api.ebay.com/oauth/api_scope",
    "https://api.ebay.com/oauth/api_scope/sell.fulfillment.readonly",
    "https://api.ebay.com/oauth/api_scope/sell.fulfillment",
  ],

  // optional parameters, should be omitted if not used
  siteId: eBayApi.SiteId.EBAY_UK, // required for traditional APIs, see https://developer.ebay.com/DevZone/merchandising/docs/Concepts/SiteIDToGlobalID.html
   ruName: "Simon_Edge-XXXXXXXXXXXXXXXX", // required for authorization code grant
  //authToken: "", // can be set to use traditional API without code grant
});

export default async (req, res) => {
  // Access the provided 'page' and 'limt' query parameters
  const code = req.query.code; // this is provided from eBay
  console.log(code);

  try {
    //const token = await eBay.OAuth2.getToken(code);
    const token = "bob";

    console.log("Prisma handler instance", prisma);

    const env_variable = await prisma.variable.upsert({
      where: {
        variable: "EBAY_TOKEN",
      },
      update: { value: token },
      create: {
        variable: "EBAY_TOKEN",
        value: token,
      },
    });

    if (env_variable) {
      console.log("New Token Stored in DB");
    } else console.log("Failed to store new Token");

    res.status(200);
    res.writeHead(302, {
      Location: "/orders",
      //add other headers here...
    });
    res.end();
  } catch (e) {
    console.error(e);
    res.status(400).end();
  }

  res.writeHead(302, {
    Location: "/orders",
    //add other headers here...
  });
  res.end();
};
```

## How to reproduce

Repo here: -
https://github.com/sunrunner4kr-simon/StoreApp

Vercel deployment here: -
https://store-app-9d9d1weic-sunrunner4kr-simon.vercel.app/

## Environment & setup

- OS: 
- Database: 
- Node.js version: 
- Prisma version:

```

```

**Comment by sunrunner4kr-simon** [comment] 2021-04-27 06:59
So, I had a play around, and think I found the problem. My prisma table field was a VARCHAR (String), however I was inadvertently trying to store upsert with a JSON object.
Now that I've changed to a JSON field it's working.

So I guess the only problem is that maybe the error wasn't helpul?
Although it was all my stupid fault.

**Comment by sunrunner4kr-simon** [comment] 2021-04-27 07:31
It's now progressed to even stranger behaviour after fixing the above problem...again only happening in Vercel

Something went wrong error
2021-04-27T07:27:34.279Z	08c49fe8-ed92-4ad5-b70a-6ccf58949044	ERROR	PrismaClientKnownRequestError2 [PrismaClientKnownRequestError]: The table `Variable` does not exist in the current database.
    at cb (/var/task/nextjs-store/node_modules/@prisma/client/runtime/index.js:34780:17)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async getServerSideProps (/var/task/nextjs-store/.next/server/pages/settings.js:3377:22)
    at async renderToHTML (/var/task/nextjs-store/node_modules/next/dist/next-server/server/render.js:40:215)
    at async /var/task/nextjs-store/node_modules/next/dist/next-server/server/next-server.js:112:97
    at async /var/task/nextjs-store/node_modules/next/dist/next-server/server/next-server.js:105:142
    at async Server.renderToHTMLWithComponents (/var/task/nextjs-store/node_modules/next/dist/next-server/server/next-server.js:137:387)
    at async Server.renderToHTML (/var/task/nextjs-store/node_modules/next/dist/next-server/server/next-server.js:138:522)
    at async Server.render (/var/task/nextjs-store/node_modules/next/dist/next-server/server/next-server.js:75:236)
    at async Object.fn (/var/task/nextjs-store/node_modules/next/dist/next-server/server/next-server.js:59:580) {
  code: 'P2021',
  clientVersion: '2.21.2',
  meta: { table: 'Variable' }
}
RequestId: 08c49fe8-ed92-4ad5-b70a-6ccf58949044 Error: Runtime exited with error: exit status 1
Runtime.ExitError

```prisma
model Variable {
  variable String  @unique
  value    String? @db.Text
  token    Json?
}
```

![image](https://user-images.githubusercontent.com/58920692/116202760-d9d8ce80-a732-11eb-82da-e9bb582d9763.png)

**Comment by pantharshit00** [comment] 2021-05-28 14:07
Looks like reproduction is no longer available. Any chance you can post it again? If not, feel free to close this.

**Closed** 2022-06-02 12:00 UTC
Labels: bug/0-unknown, kind/bug, topic: deployment-platform, status/needs-action, topic: nextjs, team/client, topic: deployment/vercel
