### ISSUE TITLE
Client extensions break generated Fluent API Typescript types 

### ISSUE THREAD

**Issue by jonoc330** [prisma/prisma#22030] opened 2023-11-20 03:48 UTC
### Bug description

Hi Prisma team. Using a Prisma Accelerate client in Typescript appears to break types for the Fluent API i.e https://www.prisma.io/docs/concepts/components/prisma-client/relation-queries#fluent-api when using it to chain to fetch relationships.

I noticed this while using RedwoodJS `6.4.0` which uses Prisma version `5.6.0` under the hood.

For example:

```
export const User: UserRelationResolvers = {
  builder: (_obj, { root }) => {
    return db.user.findUnique({ where: { id: root?.id } }).builder()
  },
}
```

Fails one line 40 at `builder()`: `Property 'builder' does not exist on type 'AcceleratePromise<{ id: number; email: string; name: string; builderId: number; }>'`

Given a simple relationship between a `user` and a `builder`.

### How to reproduce

- Run `yarn create redwood-app my-redwood-project --typescript`
- Run `cd api` then `yarn add @prisma/extension-accelerate`
- Change `.env` to:

```
DATABASE_URL=file:./dev.db
```

- Change `schema.prisma` (see Prisma Information)
- Change `db.ts` (see Prisma Information)
- Run `yarn rw prisma migrate dev`
- Run `yarn rw g sdl user`
- Run `yarn rw prisma generate`
- See type error in `api/src/services/users/users.ts` on line 40. It cannot reference the builder, however the code runs fine in dev environment.

### Expected behavior

Extending a Prisma Client `withAccelerate()` should maintain the underlying Fluent API types.

### Prisma information

```prisma
datasource db {
  provider  = "sqlite"
  url       = env("DATABASE_URL")
}

generator client {
  provider      = "prisma-client-js"
  binaryTargets = "native"
}

model User {
  id    Int     @id @default(autoincrement())
  email String  @unique
  name  String?

  builder   Builder? @relation(fields: [builderId], references: [id])
  builderId Int?
}

model Builder {
  id   Int    @id @default(autoincrement())
  name String
  user User[]
}
```

```ts
// See https://www.prisma.io/docs/reference/tools-and-interfaces/prisma-client/constructor
// for options.

import { PrismaClient } from '.prisma/client'
import { withAccelerate } from '@prisma/extension-accelerate'

import { emitLogLevels, handlePrismaLogging } from '@redwoodjs/api/logger'

import { logger } from './logger'

const prisma = new PrismaClient({
  log: emitLogLevels(['info', 'warn', 'error']),
})

handlePrismaLogging({
  db: prisma,
  logger,
  logLevels: ['info', 'warn', 'error'],
})

export const db = prisma.$extends(withAccelerate())
```

### Environment & setup

- OS: macOS
- Database: PostgreSQL, SQLite
- Node.js version: 18.15.0

### Prisma Version

```
prisma                  : 5.6.0
@prisma/client          : 5.6.0
Computed binaryTarget   : darwin-arm64
Operating System        : darwin
Architecture            : arm64
Node.js                 : v18.15.0
Query Engine (Node-API) : libquery-engine e95e739751f42d8ca026f6b910f5a2dc5adeaeee (at node_modules/@prisma/engines/libquery_engine-darwin-arm64.dylib.node)
Schema Engine           : schema-engine-cli e95e739751f42d8ca026f6b910f5a2dc5adeaeee (at node_modules/@prisma/engines/schema-engine-darwin-arm64)
Schema Wasm             : @prisma/prisma-schema-wasm 5.6.0-32.e95e739751f42d8ca026f6b910f5a2dc5adeaeee
Default Engines Hash    : e95e739751f42d8ca026f6b910f5a2dc5adeaeee
Studio                  : 0.495.0
```

**Comment by jonoc330** [comment] 2023-11-20 04:08
Noticed this is a known limitation

**Comment by janpio** [comment] 2023-11-20 19:42
Duplicate of, https://github.com/prisma/prisma/issues/21988 that was opened a few days earlier.

Thanks for opening an issue!

**Closed by janpio** 2023-11-20 19:42 UTC
Labels: bug/1-unconfirmed, kind/bug, team/client, topic: fluent api, topic: clientExtensions
