### ISSUE TITLE
Migrate from sqlite to postresql 

### ISSUE THREAD

**Issue by davecthomas** [prisma/prisma#13545] opened 2022-05-28 19:11 UTC
Hi Prisma Team! Prisma Migrate just crashed. 

## Command

`migrate dev`

## Versions
      
| Name        | Version            |
|-------------|--------------------|
| Platform    | darwin             | 
| Node        | v16.15.0           | 
| Prisma CLI  | 3.14.0             | 
| Engine      | 2b0c12756921c891fec4f68d9444e18c7d5d4a6a| 

## Error
```
Error: Error in migration engine.
Reason: [libs/sql-schema-describer/src/postgres.rs:1039:28] no entry found for key

Please create an issue with your `schema.prisma` at
https://github.com/prisma/prisma/issues/new

```

**Comment by davecthomas** [comment] 2022-05-29 15:37
I worked around this by creating a new, empty database. It fails if there are any tables in the database referred to by the connection string. Creating a new database and granting access then re-run `npm run setup` will fix this. 
If you hit this error after you have already tried once, you need to remove your migrations folder then try again. 

I suggest the Prisma team take a look at why this is happening if there are other tables in the DB that are unrelated to the schema involved in the migration.

**Comment by pantharshit00** [comment] 2022-05-30 12:18
I believe this crash is a duplicate of https://github.com/prisma/prisma/issues/13352. We working on that and you can follow that issue for any updates.

**Closed by pantharshit00** 2022-05-30 12:18 UTC
