### ISSUE TITLE
Secure/private fields

### ISSUE THREAD

**Issue by thecodeah** [prisma/prisma#2498] opened 2020-05-17 15:15 UTC
## Problem
When I indirectly access a user from the database, I want some sensitive data to be hidden.

Let's say I have a Student model and a Lesson model (Many to many related). I want to display information about all students that attend Lesson X. I do the following:
```js
const lesson = await prisma.lesson.findOne({
     include: {
         students: true
     }
});
```

Great! I have all the information about the lesson as well as the students that attend it. However, I also have the students sensitive data now. I could accidentally pass this information to the client while forgetting to strip that data from the result.

My gut is telling me a similar feature already exists but I can't seem to find any reference to it so I guess this issue is worth a shot :sweat_smile: 

## Suggested solution
1. Add a `@secure` or `@private` tag that you can add to fields in a Prisma model. These fields will only be accessable if you directly query for that model. 

2. Add a `@secure` or `@private` tag that you can add to fields in a Prisma model. If you want to retrieve these fields you have to specify it in the `include` section.

**Comment by pantharshit00** [comment] 2020-05-18 14:38
Hi,

Thanks for reporting this! It has already been reported before, so I am going to close this as a duplicate of https://github.com/prisma/prisma-client-js/issues/649. Also related to https://github.com/prisma/prisma-client-js/issues/649

**Closed by pantharshit00** 2020-05-18 14:38 UTC

**Comment by pantharshit00** [comment] 2020-05-19 10:07
Hello, sorry I think I linked to same issue twice above. The issue this is a duplicate of is https://github.com/prisma/specs/issues/461


https://github.com/prisma/prisma-client-js/issues/649 is just a related request
