### ISSUE TITLE
Calls to certain table suddenly not working in production

### ISSUE THREAD

**Issue by NathanVG** [prisma/prisma#21368] opened 2023-10-05 10:12 UTC
### Bug description

I have a next.js app using the T3 stack with TRPC and Prisma, my db is hosted on planetscale. 

Since yesterday calls to a specific table are suddenly not resolving. Locally everything works perfectly and every call goes through. However for my production deploy on Vercel these calls are simply not doing anything, they keep loading. I'm not getting any errors. 

Everything works fine locally, my data seems to be in order through prisma studio as well. I updated all packages yesterday and just now again as I saw a new release for the Prisma client was available. 

I'm at wits end... 

### Prisma information

```prisma
// Add your schema.prisma
```

```ts
// Add your code using Prisma Client
```

### Environment & setup

- OS: MacOs
- Database: Planetscale
- Node.js version: v19.9.0

### Prisma Version

```
prisma                  : 4.3.1
@prisma/client          : 5.4.1
Current platform        : darwin-arm64
Query Engine (Node-API) : libquery-engine c875e43600dfe042452e0b868f7a48b817b9640b (at ../../../../../../opt/homebrew/lib/node_modules/prisma/node_modules/@prisma/engines/libquery_engine-darwin-arm64.dylib.node)
Migration Engine        : migration-engine-cli c875e43600dfe042452e0b868f7a48b817b9640b (at ../../../../../../opt/homebrew/lib/node_modules/prisma/node_modules/@prisma/engines/migration-engine-darwin-arm64)
Introspection Engine    : introspection-core c875e43600dfe042452e0b868f7a48b817b9640b (at ../../../../../../opt/homebrew/lib/node_modules/prisma/node_modules/@prisma/engines/introspection-engine-darwin-arm64)
Format Binary           : prisma-fmt c875e43600dfe042452e0b868f7a48b817b9640b (at ../../../../../../opt/homebrew/lib/node_modules/prisma/node_modules/@prisma/engines/prisma-fmt-darwin-arm64)
Format Wasm             : @prisma/prisma-fmt-wasm 4.3.0-32.c875e43600dfe042452e0b868f7a48b817b9640b
Default Engines Hash    : c875e43600dfe042452e0b868f7a48b817b9640b
Studio                  : 0.473.0

```

**Comment by aqrln** [comment] 2023-10-05 11:57
Is there any way we could reproduce this? I don't think there's anything we can do right now with the information provided but here are some follow-up questions that might help figure out what's happening:
1. What do you mean by "calls to a specific table", does that mean you only have problems with queries that involve one specific table but not the others?
2. Some specific query as well, or just any query that involves that table?
3. Anything interesting about that table (e.g. millions of rows or something)?
4. Are you using the same PlanetScale database with the same data locally where you cannot reproduce the issue?
5. Have you also confirmed this is a Prisma issue at all and not a problem with something else in your stack? If the answer to the previous question is "yes" then the answer here is likely "no" but let's figure this out anyway.

**Comment by aqrln** [comment] 2023-10-05 12:00
Also, unrelated to your problem, but I noticed that the Prisma CLI and Prisma Client versions in your `prisma -v` output are diverging, and the CLI is very old. They must always be the same version and updated together.

**Comment by NathanVG** [comment] 2023-10-05 12:19
1. What do you mean by "calls to a specific table", does that mean you only have problems with queries that involve one specific table but not the others?

>  Yes exactly, it is specifically the "employees" table that has the issue, 'contracts' and 'customers' are working. I have various endpoints on the employees table (getAll, getById, getByRole, ...) none of them work. Endpoints for all other tables work just fine. 

3. Anything interesting about that table (e.g. millions of rows or something)?

>  nope, the table is about 50 rows in total, the largest table I have (contracts) works. 

4. Are you using the same PlanetScale database with the same data locally where you cannot reproduce the issue?

> yes I am, same database url, same credentials

5. Have you also confirmed this is a Prisma issue at all and not a problem with something else in your stack? 
> I am not entirely sure, but I don't know what else it could be, I created an issue with TRPC as well. What's the most confusing to me is that it's concerning one specific table.

**Comment by NathanVG** [comment] 2023-10-05 12:20
Also, the trpc file for the table in question hasn't been touched in two months, so no reason it should stop working suddenly.

**Comment by NathanVG** [comment] 2023-10-05 12:28
I have updated prisma multiple times now, both `--save-dev` and globally

<img width="502" alt="Screenshot 2023-10-05 at 14 27 22" src="https://github.com/prisma/prisma/assets/3620183/db223ae8-58d8-44d8-bdd1-ce6aec8499ed">

prisma -v keeps saying I am out of date.

**Comment by janpio** [comment] 2023-10-05 12:30
You are running the CLI globally with just `prisma` - so seems that was not updated somehow. I would suggest to uninstall it globally so that just running `prisma` fails, and then use the local command (equivalent of `npx` for pnpm) to run the CLI - then this distracting problem should go away.

**Comment by NathanVG** [comment] 2023-10-05 12:32
> You are running the CLI globally with just `prisma` - so seems that was not updated somehow. I would suggest to uninstall it globally so that just running `prisma` fails, and then use the local command (equivalent of `npx` for pnpm) to run the CLI - then this distracting problem should go away.

good catch 

<img width="608" alt="image" src="https://github.com/prisma/prisma/assets/3620183/95e1276b-1740-4aa7-9d4c-6d098301b0a5">

**Comment by janpio** [comment] 2023-10-05 12:45
Problem persists after generating the Client with that CLI?

**Comment by NathanVG** [comment] 2023-10-05 12:58
Well everything was already working fine locally, it's when I deploy to vercel that things start failing. I have prisma generate as postinstall script so this should run automatically when deploying to vercel, no? 

I updated all packages again and redeployed, the problem persists

**Comment by NathanVG** [comment] 2023-10-05 13:29
So what's interesting is that if I surf to the url generated for the endpoint ie `https://xxx.vercel.app/api/trpc/companyemployees.getByRole?batch=1&input=%7B%220%22%3A%7B%22json%22%3A2%7D%7D` I do see the data in a raw format

**Comment by aqrln** [comment] 2023-10-05 13:30
> Yes exactly, it is specifically the "employees" table that has the issue, 'contracts' and 'customers' are working. I have various endpoints on the employees table (getAll, getById, getByRole, ...) none of them work. Endpoints for all other tables work just fine.

So, to clarify: have you checked that the handlers for these endpoints hang when trying to communicate with the database or calling Prisma, or is that an assumption? Could you add logs or traces to see where exactly the problem happens in them?

**Comment by aqrln** [comment] 2023-10-05 13:31
> So what's interesting is that if I surf to the url generated for the endpoint ie https://xxx.vercel.app/api/trpc/companyemployees.getByRole?batch=1&input=%7B%220%22%3A%7B%22json%22%3A2%7D%7D I do see the data in a raw format

Where does the problem happen then, when calling them from the frontend?

**Comment by aqrln** [comment] 2023-10-05 13:32
> Could you add logs or traces to see where exactly the problem happens in them?

given the last message, is it possible those API calls don't even get to the server?

**Comment by NathanVG** [comment] 2023-10-05 16:04
Okay so update, 

I accessed deploys from before the issues started, and I have the same issues there, only the same call not working. So I think that means I can assume it's not a bug I introduced or a package that's out of date, it has to be either a Vercel issue or a Planetscale issue.

**Comment by aqrln** [comment] 2023-10-05 18:50
I will close this issue for now since it looks like it's not a Prisma issue indeed. Please do let us know right away if you have any new findings that point at any potential problems in Prisma so that we reopen this issue and investigate. Also let us know if there's anything else we can help with!

**Closed by aqrln** 2023-10-05 18:50 UTC
Labels: bug/0-unknown, kind/bug, team/client, topic: deployment/vercel, topic: database-provider/planetscale

**Comment by NathanVG** [comment] 2023-10-05 19:02
I have support cases running with Planetscale and Vercel. If this gets solved I will report back here. 

For posterity, this is an issue in the vercel repo from someone with the same issue: 
https://github.com/orgs/vercel/discussions/4368#discussioncomment-7196111

**Comment by NathanVG** [comment] 2023-10-05 21:10
Good news and bad news, the issue resolved itself. I however still do not know what caused it.
