### ISSUE TITLE
PANIC: called `Option::unwrap()` on a `None` value

### ISSUE THREAD

**Issue by bamada** [prisma/prisma#12079] opened 2022-02-28 22:15 UTC
Hi Prisma Team! My Prisma Client just crashed. This is the report:
## Versions

| Name            | Version            |
|-----------------|--------------------|
| Node            | v12.22.5           | 
| OS              | darwin             |
| Prisma Client   | 3.8.1              |
| Query Engine    | 0.1.0              |
| Database        | mysql              |

## Logs
```
  prisma:tryLoadEnv Environment variables loaded from /Users/Documents/kronos-tasks/.env  
  prisma:tryLoadEnv Environment variables loaded from /Users/Documents/kronos-tasks/.env  
  prisma:client clientVersion: 3.8.1  
  prisma:client clientEngineType: library  
  prisma:client:libraryEngine internalSetup  
  prisma:client:libraryEngine Searching for Query Engine Library in /Users/Documents/kronos-tasks/prisma/.prisma/client  
  prisma:client:libraryEngine Searching for Query Engine Library in /Users/Documents/kronos-tasks/prisma/generated/client  
  prisma:client:libraryEngine loadEngine using /Users/Documents/kronos-tasks/prisma/generated/client/libquery_engine-darwin.dylib.node  
  prisma:tryLoadEnv Environment variables loaded from /Users/Documents/kronos-tasks/.env  
  prisma:client clientVersion: 3.8.1  
  prisma:client clientEngineType: library  
  prisma:client:libraryEngine internalSetup  
  prisma:client:libraryEngine Searching for Query Engine Library in /Users/Documents/kronos-tasks/prisma/.prisma/client  
  prisma:client:libraryEngine Searching for Query Engine Library in /Users/Documents/kronos-tasks/prisma/generated/client  
  prisma:client:libraryEngine loadEngine using /Users/Documents/kronos-tasks/prisma/generated/client/libquery_engine-darwin.dylib.node  
  prisma:client:libraryEngine library starting  
  prisma:client:libraryEngine library started  
  prisma:client:libraryEngine library starting  
  prisma:client:libraryEngine library started  
  prisma:client:libraryEngine sending request, this.libraryStarted: true  +12s
  prisma:client:fetcher   Error: called `Option::unwrap()` on a `None` value
  prisma:client:fetcher   
  prisma:client:fetcher   - index.js:3596
```

## Snippet
```
  this.prisma.timeSheetRowsDetail.findMany({
        include: {
          Task: {
            include: {
              TaskChargingCode: {
                include: { chargingCode: true },
              },
            },
          },
        },
        where: {
          day: {
            gte: new Date('2021-10-01'),
            lte: new Date('2021-10-31'),
          },
        },
        take: 1,
      }),
```

**Comment by janpio** [comment] 2022-03-01 08:43
Can you share the schema of `timeSheetRowsDetail` and `Task` and `TaskChargingCode` so it is easier for us to reproduce this? Thanks.

**Comment by millsp** [comment] 2022-09-05 18:39
Hey @bamada, I was not able to reproduce this. Therefore I am closing this issue. Please do let us know if we mistakenly closed this and please provide us with a reproduction. I have tested the following on all our providers:

```prisma

    generator client {
      provider = "prisma-client-js"
      previewFeatures = []
    }
    
    datasource db {
      provider = "postgresql"
      url      = env("DATABASE_URI_postgresql")
    }

    model User {
      id    String @id @default(cuid())
      tasks Task[] @relation("userTask")
    }
    
    model Task {
      id          String @id @default(cuid())
      user        User @relation("userTask", fields: [userId], references: [id])
      userId      String
      taskSheet   TaskSheet @relation("taskSheet", fields: [taskSheetId], references: [id])
      taskSheetId String
    }

    model TaskSheet {
      id    String @id @default(cuid())
      tasks Task[] @relation("taskSheet")
      date  DateTime
    }
  ```
  
  ```ts
  testMatrix.setupTestSuite((suiteConfig, suiteMeta) => {
  beforeAll(async () => {
    const user = await prisma.user.create({ data: {} })
    const taskSheet = await prisma.taskSheet.create({ data: { date: new Date() } })
    const taskSheetTask = await prisma.task.create({
      data: { user: { connect: { id: user.id } }, taskSheet: { connect: { id: taskSheet.id } } },
    })
  })

  test('findMany', async () => {
    const [taskSheet] = await prisma.taskSheet.findMany({
      include: {
        tasks: {
          include: {
            user: true,
          },
        },
      },
      where: {
        date: {
          lte: new Date(),
        },
      },
      take: 1,
    })

    expect(taskSheet).not.toBeUndefined()
  })
})
  ```

**Closed** 2022-09-05 18:41 UTC
Labels: bug/0-unknown, kind/bug, tech/engines, topic: mysql, team/client, topic: basic error report, priority/high, size/unknown
