### ISSUE TITLE
`prisma_pool_connections_open` metric can sometimes be`0` instead of `1`?

### ISSUE THREAD

**Issue by Jolg42** [prisma/prisma#21231] opened 2023-09-26 14:09 UTC
### Bug description

[To be reproduced]

Example, it happened in our Windows CI for `sqlite`, though it could be a Windows only or SQLite only behavior or something else.
https://github.com/prisma/prisma/pull/21230/files/b40f59bb5e0d4db07288deb238556e3c643def2a..d9c2750042dbbc37c517849d8f06013de301123d#diff-cde9ef4629a82ade38c57c88826a126e532c7d37263a55f6178bd1c8b864cf6b

### How to reproduce

The expectation is here
https://github.com/prisma/prisma/blob/deps/engines-5.4.0-26.4bf3cce422a49f49c661da32d4016a5be81d28b4/packages/client/tests/functional/metrics/enabled/tests.ts#L277

**Comment by miguelff** [comment] 2024-03-01 16:07
I couldn't reproduce this in several attempts, and the effort to dig deeper is massive. I'm closing for the moment, lets reopen it in case we see this manifesting again.

**Closed by miguelff** 2024-03-01 16:07 UTC
Labels: bug/1-unconfirmed, kind/bug, topic: sqlite, topic: windows, topic: previewFeatures, team/client, topic: metrics
