### ISSUE TITLE
Geolocation data types

### ISSUE THREAD

**Issue by steebchen** [prisma/prisma#2788] opened 2020-06-17 14:46 UTC
Prisma should have an abstraction for basic geo data types. The underlying data type depends on what the user uses, e.g. `geometry` for PostGIS. It would also be great to support different typesafe methods to query for these fields.

Please upvote this issue if you're interested in this feature. For specific implementations (such as [this issue for PostGIS](https://github.com/prisma/prisma/issues/2789)), feel free to create a new issue and I'll try to collect them here.

non-prisma related resources which might be helpful:
- [Hibernate geo queries database comparison table](https://docs.jboss.org/hibernate/orm/5.2/userguide/html_single/Hibernate_User_Guide.html#spatial-configuration-dialect)
- [knex-postgis extension](https://github.com/jfgodoy/knex-postgis)
- [TypeORM feature request](https://github.com/typeorm/typeorm/issues/3296)
- [GeoAlchemy 2](https://geoalchemy-2.readthedocs.io/en/latest/)

**Comment by pantharshit00** [comment] 2020-06-18 14:32
Related or might be closed as a duplicate of https://github.com/prisma/prisma/issues/1798

**Comment by steebchen** [comment] 2020-06-25 02:56
@pantharshit00 I agree this is a duplicate, but I do think it may be worth either keeping this or renaming the other one to include words like geo/location; I’m sure a lot of people will search for this instead of “spatial types”, even though that’s probably more accurate.

**Comment by pantharshit00** [comment] 2020-06-25 14:13
I have renamed the other issue. Closing this as a duplicate of #1798

**Closed by pantharshit00** 2020-06-25 14:13 UTC
Labels: kind/feature, topic: native database types
