### ISSUE TITLE
Relation filter operator 'every' does not work correctly

### ISSUE THREAD

**Issue by younes-alouani** [prisma/prisma#14847] opened 2022-08-17 03:47 UTC
### Bug description

Relation filter operator ‘every’ does not work correctly. ‘Every’ will return records in case there’s no related record (relation field of that record is an empty array) regardless of filter conditions

### How to reproduce

How can I get posts that have selected tags (filter by tag id) ? 

Here are the models I'm using :

```
model Post {
  id    Int        @id @default(autoincrement())
  title String
  tags  PostTags[]
}

model PostTags {
  id     Int   @id @default(autoincrement())
  post   Post? @relation(fields: [postId], references: [id])
  tag    Tag?  @relation(fields: [tagId], references: [id])
  postId Int?
  tagId  Int?
}

model Tag {
  id    Int        @id @default(autoincrement())
  name  String     @unique
  posts PostTags[]
}
```

### Expected behavior

Relation filter operator ‘every’ does not work correctly. ‘Every’ will return records in case there’s no related record. 

It should return posts that have all the selected tags. 

### Prisma information

I tried to filter posts using this query but I'm getting also posts that have zero tags :

```
const posts = await prisma.post.findMany({ 
  where: { tags: { every: { id: { in: tags_arrays_ids } } } } 
})
```

### Environment & setup

- OS: Windows
- Database: PostgreSQL
- Node.js version: v16.16.0

### Prisma Version

```
prisma                  : 4.2.1
@prisma/client          : 4.2.1
```

**Comment by younes-alouani** [comment] 2022-08-19 21:26
Please note this bug was confirmed and reproduced according to #discussioncomment-3434535.

**Comment by aqrln** [comment] 2022-09-01 15:04
Related: https://github.com/prisma/prisma/issues/11819

**Comment by SevInf** [comment] 2022-09-06 09:03
This is not a bug, this is expected behavior. In JS, for example `[].every(anything)` will also return `true` and so will do sql `ALL` statement.

 The way to exclude empty relationships:
 
 ```js
 await prisma.post.findMany({ 
  where: {
    tags: {
      every: { id: {in: tags_arrays_ids } },
      some: {},
     }
  } 
})
 ```
 
 I am going to close this as duplicate of #11819, let's continue discussion there.

**Closed by SevInf** 2022-09-06 09:03 UTC
Labels: bug/1-unconfirmed, kind/bug, team/client
