### ISSUE TITLE
Allow @unique fields of related model in `where` clause of `upsert()`

### ISSUE THREAD

**Issue by jonasmerlin** [prisma/prisma#2988] opened 2020-07-10 16:11 UTC
## Problem
When I have 2 models that are related 1:1 and where the @id of model 2 is its scalar representation of the foreign key of model 1, then I'd like to be able to call `upsert()` on model 2 and use @unique fields of model 1 in the `where` clause.

Here's an example:

Suppose I have the following model:

```
model ModelOne {
  id               Int               @default(autoincrement()) @id
  name         String          @unique
  modelTwo ModelTwo?
}

model ModelTwo {
    modelOne ModelOne @relation(fields: [id], references: [id])
    id               Int             @id
    title            String
}
```

Then I'd like to be able to do the following:

```javascript
prismaClient.modelTwo.upsert({
  where: {
    account {
      email: "mail"
    },
    update: {
      title: "new title"
    },
    create: {
      modelOne {
        create: {
           name: "original name"
         }
      },
      title: "original title"
    },
  }
})
```

**Comment by jonasmerlin** [comment] 2020-07-10 16:16
Actually, I just realized that this extends to `findOne()` etc. and I'm pretty sure that I already saw an open issue about that particular case on here somewhere. 😅

**Comment by pantharshit00** [comment] 2020-07-15 18:00
Yes, I am going to close this as duplicate of https://github.com/prisma/prisma/issues/1924

**Closed by pantharshit00** 2020-07-15 18:00 UTC
