### ISSUE TITLE
querying an integer from a mysql tinyint(1) column fails

### ISSUE THREAD

**Issue by freund17** [prisma/prisma#4981] opened 2021-01-12 22:36 UTC
What happens:

```js
const { my_column } = prisma.MyTable.create({ data: { my_column: -1 } })

expect(my_column).toBe(-1) // fails, my_column is `0`
```

The value is correctly being added to the database.

My setup:

MySQL 8.0.22
@prisma/client 2.14.0
@prisma/cli 2.14.0

A table with the following column:

```sql
# schema.sql
`my_column` tinyint(1) NOT NULL DEFAULT -1
```

```prisma
// schema.prisma
my_column Int @default(-1)
```

What I tried:

I debugged my way through the JavaScript side of things. The problem likely lies in the Rust part.

What fixed it:

- switching the column type in MySQL to `tinyint(2)`
- switching the column type in MySQL to `int(1)`
- storing `0` or `1`

What did not fix it:

- changing the column default in MySQL (tried `0`, `9`, `-4`)
- changing the column default in Prisma schema (tried `0`, `9`, `-4`)
- storing `3`, `5`, `-4` (same problem)
- using the "nativeTypes" preview feature
  - as intended
  - setting prisma and db type to BigInt => value is not stored, an exception is thrown "Attempted to serialize scalar 'false' with incompatible type 'BigInt'"
- reverting to a slighty older version of prisma (I think I checked 2.10, 2.12, 2.13 - not sure though...)

If you need more information, let me know.

PS: Huge fan of the library. 🙂

**Comment by pantharshit00** [comment] 2021-01-19 10:15
Thanks for reporting this. I can reproduce this. 

I think this is happening because we use `tinyint(1)` to represent booleans on a database level which is common practice is mysql. 

Marking this as a confirmed bug.

**Closed** 2021-01-26 15:51 UTC
Labels: bug/2-confirmed, kind/bug, team/client, topic: mysql, topic: native database types
