### ISSUE TITLE
Permit falseable fields when using `select` or querying

### ISSUE THREAD

**Issue by andreluiz901** [prisma/prisma#22584] opened 2024-01-07 23:43 UTC
## Problem

I was trying to retrieve data from users when creating at database like this: 

```
// some code

return this.database.users.create({
      select: {
        password: false,    // this topic is about this line in this select query
      },
      data: {
        email,
        fullName,
        username,
        profile_photo,
        password: this.securityService.encrypt(password),
      },
    });
```
So, this dont worked and give me a error to insert at least one true field:

```
Invalid `this.database.users.create()` 
... some path information error ...

PrismaClientValidationError: 
Invalid `this.database.users.create()` invocation in /home/andre.....

The `select` statement for type users needs at least one truthy value.

``` 

I understand that we should inform at least one true value.  However i think that in cases when we want to retrieve data excepting some security values like password etc. we could do something like a select(*) excepting the false value. 

The only thing i could to my application at this point is a more verbose code like this:

```
return this.database.users.create({
      select: {
        email: true,
        fullName: true,
        username: true,
        profile_photo: true,
        ...all other fileds
        ...not informing password to retrieve
      },
      data: {
        email,
        fullName,
        username,
        profile_photo,
        password: this.securityService.encrypt(password),
      },
    });
```

## Suggested solution

I think that we could implement falseable fields and intelligent query to accpets a false field, and not only true fileds like now. 

The flow could be something like:
   -   If a false field is informed we look to see if theres any other field with true. If only false fields are informed, we do a select(*) retrieving all data EXCEPTING the false values informed.
   - If only true values are informed, could perform like today.
   - If a true and false values are informed, we could do something similar like today and just ignore the false fields and select the true values at query.

## Alternatives

I could not figure out any alternative. Its just a suggestion. I think I'll work on this feature myself with some free time soon.

## Additional context

No context is necessary.

**Comment by Weakky** [comment] 2024-01-08 10:34
Hey @andreluiz901,

I believe your issue is a duplicate of https://github.com/prisma/prisma/issues/5042.

I'll keep this around because I think we could enhance typings by expecting at least one `true` field in the selection set.

**Comment by andreluiz901** [comment] 2024-01-08 13:17
Okay, @Weakky , thanks for note that, i made  search about this and really cannot find nothing about, sorry for not notice that before, i will read how this feature development is running in this issue that you mentioned. I made some tests here and i will see if i can contribute with this feature. 

Best regards.

**Comment by janpio** [comment] 2024-02-19 11:23
Closing this as a duplicate of https://github.com/prisma/prisma/issues/5042

**Closed by janpio** 2024-02-19 11:23 UTC
Labels: kind/feature, topic: client types, tech/typescript, team/client
