### ISSUE TITLE
crashed

### ISSUE THREAD

**Issue by Santo-Philip** [prisma/prisma#20525] opened 2023-08-03 09:09 UTC
Hi Prisma Team! The following command just crashed.

## Command

`db pull --force`

## Versions
      
| Name        | Version            |
|-------------|--------------------|
| Platform    | windows            | 
| Node        | v18.16.1           | 
| Prisma CLI  | 5.1.0              | 
| Engine      | a9b7003df90aa623086e4d6f4e43c72468e6339b| 

## Error
```
RustPanic: Error in Schema engine.
Reason: [schema-engine\connectors\schema-connector\src\introspection_context.rs:51:76] called `Result::unwrap()` on an `Err` value: "error: The generator \"client\" cannot be defined because a generator with that name already exists.\n  -->  schema.prisma:8\n   | \n 7 | }\n 8 | generator client {\n   | \n"

```

**Comment by janpio** [comment] 2023-08-03 11:32
> The generator \"client\" cannot be defined because a generator with that name already exists.

Can you please share the Prisma schema file that you got this error with? Does it maybe include two `generator client` blocks?

**Comment by SevInf** [comment] 2023-08-16 08:20
Hey @Santo-Philip  ,

Did you get a chance to have a look at @janpio's comment? It'd be helpful for us to move your issue forward.

Without further information, we'll have to close this issue. Thank you 🙏

**Comment by jkomyno** [comment] 2023-08-25 09:53
Hey @Santo-Philip, could you please reply to the comments above? Thank you.

**Comment by aqrln** [comment] 2023-09-05 11:04
Hi @Santo-Philip, as we couldn't reproduce the issue without further information and couldn't reach out to you to get the missing details, we have to close this issue for now. In case you didn't see the previous comments yet, feel free to post a response here at any point in the future, and we'll reopen the issue and investigate. Thank you!

**Closed by aqrln** 2023-09-05 11:04 UTC
Labels: bug/0-unknown, kind/bug, team/schema, topic: prisma db pull
