### ISSUE TITLE
`count({distinct: "foo"})` not working

### ISSUE THREAD

**Issue by terion-name** [prisma/prisma#9590] opened 2021-10-04 16:14 UTC
### Bug description

request `await ctx.prisma.response.count({distinct: "text"})` (with any distinct field) fails with error: 
```
Invalid `prisma.response.aggregate()` invocation:

{
  distinct: 'text',
  ~~~~~~~~
  _count: {
    _all: true
  }
}

Unknown arg `distinct` in distinct for type AggregateResponse. Did you mean `select`? Available args:
type aggregateResponse {
  where?: ResponseWhereInput
  orderBy?: List<ResponseOrderByWithRelationInput> | ResponseOrderByWithRelationInput
  cursor?: ResponseWhereUniqueInput
  take?: Int
  skip?: Int
}
```

Adding a select statement doesn't help.

### How to reproduce

1. Save a model and migrate
2. Run query

### Expected behavior

Query returns number of unique texts, as described in documentation (https://www.prisma.io/docs/reference/api-reference/prisma-client-reference#count)

### Prisma information

Used Model:
```
model Response {
  id String @id @default(cuid())
  createdAt DateTime   @default(now())
  updatedAt DateTime    @updatedAt
  user UsersUser?      @relation(name: "ResponseToUsersUser", fields: [userId], references: [id])
  user_temp String?
  survey Survey?      @relation(name: "SurveyResponse", fields: [surveyId], references: [id])
  question Question?      @relation(name: "QuestionResponse", fields: [questionId], references: [id])
  variant Variant?      @relation(name: "VariantResponse", fields: [variantId], references: [id])
  text String?
  questionId String?
  surveyId String?
  variantId String?
  userId String?
}
```

### Environment & setup

- OS: Mac OS
- Database: MySQL
- Node.js version: v14.13.1

### Prisma Version

```
Prisma 3.1.1
```

**Comment by NathanPB** [comment] 2022-07-25 17:28
Also occurring in Prisma 4.0.0

**Comment by garrensmith** [comment] 2022-08-23 08:04
@NathanPB and @terion-name could you provide us with a reproduction or a schema file so we can investigate further.

**Comment by medihack** [comment] 2022-09-14 13:47
Isn't this a duplicate of #4228? (And yes, I really miss this, too).

**Comment by janpio** [comment] 2022-09-14 16:37
One views it from the perspective of it not existing (feature request, #4228) and this one from it should already work but does not. Those are clearly conflicting, so thank for making the connection here. I think this is also why @garrensmith earlier this month asked for more information, so we can decide if this is indeed _broken_ in some way or really just _missing_ (which would mean closing this with a pointer to #4228).

**Comment by medihack** [comment] 2022-09-14 17:03
> One views it from the perspective of it not existing (feature request, #4228) and this one from it should already work but does not. Those are clearly conflicting, so thank for making the connection here. I think this is also why @garrensmith earlier this month asked for more information, so we can decide if this is indeed _broken_ in some way or really just _missing_ (which would mean closing this with a pointer to #4228).

At least the type definition of `count` is broken then, as it allows using `distinct`. But `DISTINCT` is such a well-supported and common SQL clause that I was a bit surprised to find out that it is implemented programmatically in Prisma (yes, I read the reasons why). So thanks for looking into this.

**Comment by janpio** [comment] 2022-09-14 17:18
A note: It not being implemented is just a capacity and/or awareness problem, if we keep to not do something feature requests are closed instead.

**Comment by miguelff** [comment] 2023-07-13 14:31
Closing as a duplicate of https://github.com/prisma/prisma/issues/9590

**Closed by miguelff** 2023-07-13 14:31 UTC
Labels: bug/0-unknown, kind/bug, team/client, topic: client api, topic: distinct, topic: count()
