### ISSUE TITLE
Count relationships

### ISSUE THREAD

**Issue by teovillanueva** [prisma/prisma#2519] opened 2020-05-19 13:35 UTC
## Problem

Hi everyone! Yesterday i opened a discussion asking if it was possible to count relationships with my prisma client and still fetching data in the same query. @ryands17 answered me that prisma currently doesnt support it. So im opening a feauture request.

This is my `User` model, it is really similar to one provided in the docs.

```
model User {
  id         Int       @default(autoincrement()) @id
  username   String    @unique
  followedBy User[]    @relation("UserFollows", references: [id])
  following  User[]    @relation("UserFollows", references: [id])
}
```

i currently fetch users with this query:

```
const user = await prisma.user.findOne({ where: { id: 1 }, include: { following: true } });
```

That include works perfectly, but i need to bring the user with the count of `following`. I found a way of doing it with another query, but it would be nice to be able to do it in the same query.

```
const following = await prisma.user.count({ where: { followedBy: { some: { id: 1 } } }});
```

## Suggested solution

I thought of maybe counting relationships like this

```
const user = await prisma.user.findOne({ where: { id: 1 }, include: { following: { count: true } } });
```

## Alternatives

Other ways of counting these relations could be like this
```
const user = await prisma.user.findOne({ where: { id: 1 }, count: { following: true }});
```
or
```
const user = await prisma.user.findOne({ where: { id: 1 }, include: { following: { select: { count: true } } } });
```

those are some ideas i came with.

## Additional context
I personally think the first or third solution would be the best since it really matches the intellisense provided

![image](https://user-images.githubusercontent.com/41754896/82332636-07ae8280-99bc-11ea-82ca-b66eb5d1974d.png)

This is my first time contributing in this projet so if there is a typo or there is something wrong please let me know! Thanks!

**Comment by teovillanueva** [comment] 2020-05-19 17:13
This is the link to the discussion: https://github.com/prisma/prisma/discussions/2512

**Comment by Akxe** [comment] 2020-05-20 09:21
If this would be implemented, I would suggest using some kind of special key. A symbol (`Symbol('countRelations')`) would be best, but if this query needs to be stringified, then constant like `__Prisma_countRelations__` will do the same just fine.
```
const user = await prisma.user.findOne({ where: { id: 1 }, include: { following: { [Prisma.countRelations]: true } } })
```

**Comment by laugharn** [comment] 2020-05-20 18:10
https://github.com/prisma/prisma-client-js/issues/692 this was my request that got moved over to prisma/prisma-client-js

Using Eloquent's withCount as a reference, my hope is a query like this:

```js
const user = await prisma.user.findOne({ where: { id: 1 }, include: { following: { count: true } } })
```

Would return an object like this:

```js
{
  id: 1,
  following: [...],
  followingCount: 2,
  // other fields
}
```

**Comment by pantharshit00** [comment] 2020-05-24 23:07
Thanks for linking that @laugharn 

We can close this one as a duplicate of prisma/prisma-client-js#692

**Closed by pantharshit00** 2020-05-24 23:07 UTC
Labels: kind/feature

**Comment by camsloanftc** [comment] 2021-02-04 22:47
Is this being discussed anywhere now? 

It looks like that previously linked issue is on an archived repo. Could we open this back up?

**Comment by laugharn** [comment] 2021-02-04 22:49
@camsloanftc https://github.com/prisma/prisma/issues/5079

**Comment by ne07hekin6** [comment] 2022-04-07 05:15
I would love to be able to query using the count of relations. 

Example:
 owner : {   lastLogin : { gt : twoWeeksAgo } , betsMade : { gt : 10 } },

Being betsMade an array of the model Bet
