### ISSUE TITLE
Prisma not properly set isolation level in MySQL and MariaDB

### ISSUE THREAD

**Issue by jonathanblade** [prisma/prisma#22890] opened 2024-01-31 07:37 UTC
### Bug description

When I start transaction with `Prisma.TransactionIsolationLevel.ReadUncommitted`:

Prisma runs `SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED` after `START TRANSACTION`, so it doesn't affect the current ongoing transaction as is stated in mysql manual https://dev.mysql.com/doc/refman/8.0/en/set-transaction.html#set-transaction-isolation-level

Similar sequelize [issue](https://github.com/sequelize/sequelize/issues/10975) and [PR](https://github.com/sequelize/sequelize/pull/11476).

### How to reproduce

1. Create Prisma instance with mysql dialect.
2. Run sample code.
3. See output and logs.

### Expected behavior

A transaction isolation level is set correctly.

### Prisma information

```ts
import { PrismaClient, Prisma } from '@prisma/client';

const prisma = new PrismaClient({
  log: [{ level: 'query', emit: 'event' }],
});

prisma.$on('query', (event) => {
  console.log(event.query);
});

await prisma.$transaction(async (tx) => {
    const isolationLevel = await tx.$queryRaw`SELECT @@transaction_isolation`;
    console.log(isolationLevel); /** REPEATABLE-READ (expected: READ-UNCOMMITTED) */
  },
  {
    isolationLevel: Prisma.TransactionIsolationLevel.ReadUncommitted,
  }
);
```

### Environment & setup

- OS: Debian
- Database: MySQL, MariaDB
- Node.js version: 16.15.1

### Prisma Version

```
prisma   : 5.8.0
platform : debian-openssl-3.0.x
engine   : 0a83d8541752d7582de2ebc1ece46519ce72a848
```

**Comment by aqrln** [comment] 2024-01-31 09:02
Thanks for the report @jonathanblade.

This sounds unexpected, it should be running it before `START TRANSACTION`: https://github.com/prisma/prisma-engines/blob/main/quaint/src/connector/mysql/native/mod.rs#L294-L296. I would also expect this to be caught by our tests.

We should reproduce it ASAP and see what the problem is.

**Comment by jonathanblade** [comment] 2024-01-31 09:09
> Thanks for the report @jonathanblade.
> 
> This sounds unexpected, it should be running it before `START TRANSACTION`: https://github.com/prisma/prisma-engines/blob/main/quaint/src/connector/mysql/native/mod.rs#L294-L296. I would also expect this to be caught by our tests.
> 
> We should reproduce it ASAP and see what the problem is.

I found it [here](https://github.com/RobertCraigie/prisma-client-py/actions/runs/7717088743/job/21035386010#step:7:803) (if it's help you) when creating isolation level [tests](https://github.com/jonathanblade/prisma-client-py/blob/main/databases/tests/test_transactions.py#L257) for prisma-client-py.

**Comment by jonathanblade** [comment] 2024-01-31 10:03
UPD: The engine seems to really [check it](https://github.com/prisma/prisma-engines/blob/main/quaint/src/connector/transaction.rs#L49).

**Comment by jkomyno** [comment] 2024-02-01 16:34
@aqrln possibly related to this issue: setting the `SERIALIZABLE` transaction level on PlanetScale (via the `driverAdapters` preview feature) results in the following error:
> Transaction characteristics can't be changed while a transaction is in progress (errno 1568) (sqlstate 25001) during query: SET TRANSACTION ISOLATION LEVEL SERIALIZABLE

(In fact, PlanetScale is excluded by [this test](https://github.com/prisma/prisma-engines/blob/dcb8cb9817af92fefaf0f95117dfb5dc19545a2c/query-engine/connector-test-kit-rs/query-engine-tests/tests/new/interactive_tx.rs#L576-L579)).

**Comment by Weakky** [comment] 2024-02-02 11:22
I believe this is not a bug.

There are 3 scopes for isolation levels:
- Global
- Session
- Next transaction

Prisma uses the following syntax:

```sql
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;
BEGIN;
--- transaction content
COMMIT;
```

Which sets the transaction level for the very next transaction of the session.

Unfortunately though, there is currently no way of querying _this_ specific level. Regardless of where `SELECT @@transaction_isolation` is executed, it always returns the **SESSION** transaction level. It is equivalent to `SELECT @@SESSION.transaction_isolation`.

Sources:
1. https://bugs.mysql.com/bug.php?id=53341
2. [MySQL docs (all the way at the bottom)](https://dev.mysql.com/doc/refman/8.0/en/set-transaction.html)
	<img width="683" alt="image" src="https://github.com/prisma/prisma/assets/25233379/35a1d024-e852-46eb-8b46-36aac63dd75a">
3. https://stackoverflow.com/a/50941611

To confirm what I'm saying is correct, you should be able to create a situation that proves the correct isolation level is used. In light of the MySQL bug reported above, I didn't take the time to craft such example.

I will now close this issue. Thanks for reporting 🙏

**Closed by Weakky** 2024-02-02 11:22 UTC
Labels: bug/1-unconfirmed, kind/bug, tech/engines, topic: $transaction, topic: transaction, topic: mysql, team/client, topic: interactiveTransactions
