### ISSUE TITLE
Relation fields are removed after npx prisma db pull

### ISSUE THREAD

**Issue by NicolaGenesinJetty** [prisma/prisma#16100] opened 2022-11-02 10:48 UTC
### Bug description

Virtual fields are removed after npx prisma db pull

### How to reproduce

If you do `npx prisma db pull` the `answers` and `candidate` fields will be removed

### Expected behavior

`npx prisma db pull` won't remove virtual fields

### Prisma information

```
generator client {
  provider        = "prisma-client-js"
  previewFeatures = ["referentialIntegrity"]
}

datasource db {
  provider     = "mysql"
  url          = env("DATABASE_URL")
  relationMode = "prisma"
}

model Answer {
  id          Int        @id @default(autoincrement())
  candidateId Int?       @map("candidate_id")
  candidate   Candidate? @relation(fields: [candidateId], references: [id])
  shortCode   String?    @map("short_code") @db.VarChar(10)

  @@map("answer")
}

model Candidate {
  id                Int       @id @default(autoincrement())
  shortCode         String?   @map("short_code") @db.VarChar(10)
  answers           Answer[]

  @@map("candidate")
}
```

### Environment & setup

- OS: macOS 12.4
- Database: PlanetScale
- Node.js version: v16.14.2

### Prisma Version

```
prisma                  : 4.5.0
@prisma/client          : ^4.5.0
Current platform        : darwin-arm64
Query Engine (Node-API) : libquery-engine 0362da9eebca54d94c8ef5edd3b2e90af99ba452 (at ../../../.npm/_npx/2778af9cee32ff87/node_modules/@prisma/engines/libquery_engine-darwin-arm64.dylib.node)
Migration Engine        : migration-engine-cli 0362da9eebca54d94c8ef5edd3b2e90af99ba452 (at ../../../.npm/_npx/2778af9cee32ff87/node_modules/@prisma/engines/migration-engine-darwin-arm64)
Introspection Engine    : introspection-core 0362da9eebca54d94c8ef5edd3b2e90af99ba452 (at ../../../.npm/_npx/2778af9cee32ff87/node_modules/@prisma/engines/introspection-engine-darwin-arm64)
Format Binary           : prisma-fmt 0362da9eebca54d94c8ef5edd3b2e90af99ba452 (at ../../../.npm/_npx/2778af9cee32ff87/node_modules/@prisma/engines/prisma-fmt-darwin-arm64)
Format Wasm             : @prisma/prisma-fmt-wasm 4.5.0-43.0362da9eebca54d94c8ef5edd3b2e90af99ba452
Default Engines Hash    : 0362da9eebca54d94c8ef5edd3b2e90af99ba452
Studio                  : 0.476.0
Preview Features        : referentialIntegrity
```

**Comment by SevInf** [comment] 2022-11-02 11:27
@NicolaGenesinJetty could you also share the SQL schema of your database? That will help with reproducing the issue.

**Comment by NicolaGenesinJetty** [comment] 2022-11-02 11:45
Sure!

```
CREATE TABLE `answer` (
	`id` int NOT NULL AUTO_INCREMENT,
	`candidate_id` int,
	`short_code` varchar(10),
	PRIMARY KEY (`id`)
) ENGINE InnoDB,
  CHARSET utf8mb4,
  COLLATE utf8mb4_0900_ai_ci;

CREATE TABLE `candidate` (
	`id` int NOT NULL AUTO_INCREMENT,
	`short_code` varchar(10),
	PRIMARY KEY (`id`),
	UNIQUE KEY `email` (`email`)
) ENGINE InnoDB,
  CHARSET utf8mb4,
  COLLATE utf8mb4_0900_ai_ci;
```

**Comment by Jolg42** [comment] 2022-11-02 13:50
If I use the provided SQL, I can reproduce.
Though, it's because the SQL is invalid and fails creating the `candidate` table, which means that no relation could exist (table doesn't exist)
```
Query 1 ERROR: target: helloo.-.primary: vttablet: rpc error: code = AlreadyExists desc = Table 'candidate' already exists (errno 1050) (sqlstate 42S01) (CallerID: planetscale-admin): Sql: "create table candidate (\n\tid int not null auto_increment,\n\tshort_code varchar(10),\n\tPRIMARY KEY (id),\n\tUNIQUE KEY email (email)\n) ENGINE InnoDB,\n  CHARSET utf8mb4,\n  COLLATE utf8mb4_0900_ai_ci", BindVars: {REDACTED}
```

After adding 
```
`email` varchar(10),
```
to the candidate table it works as expected.

Do you observe something similar @NicolaGenesinJetty ?

**Comment by Jolg42** [comment] 2022-11-02 16:33
Ok I can can reproduce in `4.5.0`, it is already fixed in our internal dev version.

Related issue is https://github.com/prisma/prisma/issues/11022

So I can recommend to wait until, next release, `4.6.0`, planned on Tuesday.

**Closed by Jolg42** 2022-11-02 16:33 UTC
Labels: bug/2-confirmed, kind/bug, topic: re-introspection, team/schema, topic: referentialIntegrity/relationMode

**Comment by NicolaGenesinJetty** [comment] 2022-11-03 07:41
Thank you so much! I love Prisma!
