### ISSUE TITLE
Pagination: cursor is ignored when using negative take argument

### ISSUE THREAD

**Issue by Gomah** [prisma/prisma#2696] opened 2020-06-09 06:45 UTC
## Bug description

It looks like the "cursor" is being ignored when using a negative take argument.

## How to reproduce

Here's a repo reproduction: https://github.com/Gomah/prisma-negative-cursor-repro , with some query examples: https://github.com/Gomah/prisma-negative-cursor-repro#6-queries-to-test

## Expected behaviour

In the repo reproduction, It should return 10 posts from `ID` 30 to 39.

## Environment & setup

- OS:  Mac OS 10.15.5
- Database: PostresSQL / SQLite
- Prisma version: 2.0.0-beta.9
- Node.js version: 12.18.0

```
@prisma/cli          : 2.0.0-beta.9
Current platform     : darwin
Query Engine         : query-engine de2bc1cbdb5561ad73d2f08463fa2eec48993f56 (at /Users/gomah/Playground/pagination-prisma/node_modules/@prisma/cli/query-engine-darwin)
Migration Engine     : migration-engine-cli de2bc1cbdb5561ad73d2f08463fa2eec48993f56 (at /Users/gomah/Playground/pagination-prisma/node_modules/@prisma/cli/migration-engine-darwin)
Introspection Engine : introspection-core de2bc1cbdb5561ad73d2f08463fa2eec48993f56 (at /Users/gomah/Playground/pagination-prisma/node_modules/@prisma/cli/introspection-engine-darwin)
Format Binary        : prisma-fmt de2bc1cbdb5561ad73d2f08463fa2eec48993f56 (at /Users/gomah/Playground/pagination-prisma/node_modules/@prisma/cli/prisma-fmt-darwin
```

**Comment by Gomah** [comment] 2020-06-10 05:09
Looks like it's happening only nested fields:

```ts
const User = objectType({
  name: 'User',
  definition(t) {
    t.model.id()
    t.model.name()
    t.model.email()
    t.model.posts({
      ordering: true,
      pagination: true,
      filtering: true,
    })
  },
})
```

Negative `take` argument won't work on `posts` with the code above.

However, using a custom resolver temporarily fixes the problem:
```ts
const User = objectType({
  name: 'User',
  definition(t) {
    t.model.id()
    t.model.name()
    t.model.email()
    t.model.posts({
      ordering: true,
      pagination: true,
      filtering: true,

      resolve({ id }, args, context, info) {
        return context.prisma.post.findMany({
          ...args,
          where: {
            author: {
              id
            }
          }
        })
      }
    })
  },
})
```

**Comment by pantharshit00** [comment] 2020-06-18 13:36
I can confirm this issue. Thank you for reporting this.

I made a more minimal reproduction for this which doesn't use nexus: https://github.com/harshit-test-org/prisma-issue-2636

**Comment by dpetrick** [comment] 2020-06-25 11:20
Internal note: Can't reproduce on the engines level, with the following GQL query (adjusted with `skip: 1` to get the exact result that is desired) against the engine directly I get the expected result:
```graphql
{
  findOneUser(where:{
    id:3
  }) {
    id
    posts(orderBy: id_ASC, skip: 1, take: -10, cursor:{
      id: 40
    }) {
      id
    }
  }
}
```

```json
{
  "data": {
    "findOneUser": {
      "id": 3,
      "email": "jack@prisma.io",
      "name": "Jack",
      "posts": [
        {
          "id": 30,
          "title": "nobis"
        },
        {
          "id": 31,
          "title": "qui"
        },
        {
          "id": 32,
          "title": "rem"
        },
        {
          "id": 33,
          "title": "consequatur"
        },
        {
          "id": 34,
          "title": "qui"
        },
        {
          "id": 35,
          "title": "officia"
        },
        {
          "id": 36,
          "title": "ut"
        },
        {
          "id": 37,
          "title": "dolore"
        },
        {
          "id": 38,
          "title": "aspernatur"
        },
        {
          "id": 39,
          "title": "incidunt"
        }
      ]
    }
  }
}
```

**Comment by dpetrick** [comment] 2020-06-25 11:21
Your version is too old to work with nested cursors. This is fixed in the newest releases.

**Closed by dpetrick** 2020-06-25 11:21 UTC
Labels: bug/2-confirmed, kind/bug, process/candidate, team/engines, topic: pagination
