### ISSUE TITLE
Misleading error message when using `datasources.db.url`

### ISSUE THREAD

**Issue by janpio** [prisma/prisma#6915] opened 2021-05-03 19:34 UTC
## Bug description

When you have a valid connection string in the schema, but then overwrite it with an invalid connection string in your code when instantiating `PrismaClient`, you get a misleading error message that points to your schema:

```
$ node index.js
PrismaClientInitializationError2 [PrismaClientInitializationError]: 
Invalid `prisma.executeRaw()` invocation:


  error: Error validating datasource `db`: The URL for datasource `db` must start with the protocol `postgresql://`.
  -->  schema.prisma:7
   | 
 6 |     provider = "postgresql"
 7 |     url      = "postgresql://prisma:prisma@localhost:5432/prisma"
   | 

Validation Error Count: 1
    at cb (/workspaces/e2e-tests/core-features/socket_timeout_postgresql/node_modules/@prisma/client/runtime/index.js:35104:17)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async main (/workspaces/e2e-tests/core-features/socket_timeout_postgresql/index.js:17:5) {
  clientVersion: '2.22.0-dev.53',
  errorCode: undefined
}
```

## How to reproduce

```prisma
generator client {
    provider = "prisma-client-js"
}

datasource db {
    provider = "postgresql"
    url      = "postgresql://prisma:prisma@localhost:5432/prisma"
}

model User {
    id    String  @default(cuid()) @id
    email String  @unique
    name  String?
}
```

```
const prisma = new PrismaClient({
  datasources: {
    db: {
      url: 'this-is-invalid'
    }
  }
})
await prisma.$executeRaw('select 1;')
```

## Expected behavior

The error message should point to the `datasources` object in the code, not to the schema file.

## Environment & setup

```
prisma               : 2.22.0-dev.53
@prisma/client       : 2.22.0-dev.53
Current platform     : debian-openssl-1.1.x
Query Engine         : query-engine 60cc71d884972ab4e897f0277c4b84383dddaf6c (at node_modules/@prisma/engines/query-engine-debian-openssl-1.1.x)
Migration Engine     : migration-engine-cli 60cc71d884972ab4e897f0277c4b84383dddaf6c (at node_modules/@prisma/engines/migration-engine-debian-openssl-1.1.x)
Introspection Engine : introspection-core 60cc71d884972ab4e897f0277c4b84383dddaf6c (at node_modules/@prisma/engines/introspection-engine-debian-openssl-1.1.x)
Format Binary        : prisma-fmt 60cc71d884972ab4e897f0277c4b84383dddaf6c (at node_modules/@prisma/engines/prisma-fmt-debian-openssl-1.1.x)
Default Engines Hash : 60cc71d884972ab4e897f0277c4b84383dddaf6c
Studio               : 0.379.0
```

**Comment by pantharshit00** [comment] 2021-05-05 14:39
Duplicate of https://github.com/prisma/prisma/issues/3318

**Closed by pantharshit00** 2021-05-05 14:39 UTC
Labels: bug/1-repro-available, kind/bug, team/client, tech/typescript, topic: prisma-client
