### ISSUE TITLE
`Command failed (IllegalOperation): This MongoDB deployment does not support retryable writes`

### ISSUE THREAD

**Issue by kaname-png** [prisma/prisma#8727] opened 2021-08-13 00:55 UTC
### Bug description

I am simply trying to create a document in my mongodb collection.

```ts
2021-08-12 18:42:57 - ❌ - Encountered error on event listener "CoreMessageParser" for event "preMessageParsed" at path "C:\Users\Kaname\Documents\Proyectos\Kaede\kaede-rewrite\node_modules\@sapphire\framework\dist\lis
teners\command-handler\CoreMessageParser.js" PrismaClientUnknownRequestError3 [PrismaClientUnknownRequestError]: 
2021-08-12 18:42:57 - ❌ - Invalid `prisma.settings.create()` invocation:
2021-08-12 18:42:57 - ❌ - 
2021-08-12 18:42:57 - ❌ - 
2021-08-12 18:42:57 - ❌ -   Error occurred during query execution:
2021-08-12 18:42:57 - ❌ - ConnectorError(ConnectorError { user_facing_error: None, kind: RawError { code: "unknown", message: "Command failed (IllegalOperation): This MongoDB deployment does not support retryable writ
es. Please add retryWrites=false to your connection string.)" } })
2021-08-12 18:42:57 - ❌ -     at cb (C:\Users\Kaname\Documents\Proyectos\Kaede\kaede-rewrite\node_modules\@prisma\client\runtime\index.js:35947:17)
2021-08-12 18:42:57 - ❌ -     at processTicksAndRejections (node:internal/process/task_queues:96:5)
2021-08-12 18:42:57 - ❌ -     at async KaedeClient.fetchPrefix (C:\Users\Kaname\Documents\Proyectos\Kaede\kaede-rewrite\dist\lib\kaede.js:46:22)
2021-08-12 18:42:57 - ❌ -     at async CoreListener.run (C:\Users\Kaname\Documents\Proyectos\Kaede\kaede-rewrite\node_modules\@sapphire\framework\dist\listeners\command-handler\CoreMessageParser.js:32:30)
2021-08-12 18:42:57 - ❌ -     at async CoreListener._run (C:\Users\Kaname\Documents\Proyectos\Kaede\kaede-rewrite\node_modules\@sapphire\framework\dist\lib\structures\Listener.js:92:13) {
2021-08-12 18:42:57 - ❌ -   clientVersion: '2.29.0'
2021-08-12 18:42:57 - ❌ - }
```

### How to reproduce

Create an document.

### Expected behavior

Create the document in my mongodb collection correctly.

### Prisma information

```prisma
// This is your Prisma schema file,
// learn more about it in the docs: https://pris.ly/d/prisma-schema

datasource db {
  provider = "mongodb"
  url      = env("DATABASE_URL")
}

generator client {
  provider        = "prisma-client-js"
  previewFeatures = ["mongoDb"]
}

model Settings {
  id         String    @id @default(dbgenerated()) @map("_id") @db.ObjectId
  guild_id   String    @unique
  lang       Languages @default(es_419)
  prefix     String    @default("k!")
  created_at DateTime  @default(now())
}

enum Languages {
  es_419
  en_us
}
```

```ts
<prisma>.<collection>.create({ data: { field: "any value" } })
```

### Environment & setup

- OS: 
- Database: 
- Node.js version: 

### Prisma Version

```ts
Environment variables loaded from .env
prisma               : 2.29.0
@prisma/client       : 2.29.0
Current platform     : windows
Query Engine         : query-engine 1be4cd60b89afa04b192acb1ef47758a39810f3a (at ..\..\..\..\AppData\Local\Yarn\Data\global\node_modules\@prisma\engines\query-engine-windows.exe)
Migration Engine     : migration-engine-cli 1be4cd60b89afa04b192acb1ef47758a39810f3a (at ..\..\..\..\AppData\Local\Yarn\Data\global\node_modules\@prisma\engines\migration-engine-windows.exe)  
Introspection Engine : introspection-core 1be4cd60b89afa04b192acb1ef47758a39810f3a (at ..\..\..\..\AppData\Local\Yarn\Data\global\node_modules\@prisma\engines\introspection-engine-windows.exe)
Format Binary        : prisma-fmt 1be4cd60b89afa04b192acb1ef47758a39810f3a (at ..\..\..\..\AppData\Local\Yarn\Data\global\node_modules\@prisma\engines\prisma-fmt-windows.exe)
Default Engines Hash : 1be4cd60b89afa04b192acb1ef47758a39810f3a
Studio               : 0.419.0
Preview Features     : mongoDb
```

### mongodb version:
`MongoDB 4.4.6 Community`

**Comment by pantharshit00** [comment] 2021-08-18 10:12
Hi,

Thanks for reporting this! It has already been reported before, so I am going to close this as a duplicate of https://github.com/prisma/prisma/issues/8713

**Closed by pantharshit00** 2021-08-18 10:12 UTC
Labels: bug/0-needs-info, kind/bug, team/client, topic: mongodb
