### ISSUE TITLE
Prisma does not respect environment variables in database seeds

### ISSUE THREAD

**Issue by felinto-dev** [prisma/prisma#6158] opened 2021-03-18 05:58 UTC
## Bug description

I am using prisma db seed feature but unfortunately sounds that prisma does not respect NODE_ENV environment variable. Always set itself for "production".

## How to reproduce

package.json
```
    "db:seed": "NODE_ENV=development prisma db seed --preview-feature",
```

in prisma/seed.ts
```
  console.log(process.env.NODE_ENV);
```
I always get "production". I am using node 14-alpine based NodeJS image.

## Environment & setup

- OS: Linux Node 14-alpine based NodeJS image
- Database: PostgreSQL
- Node.js version 14.15.1
- Prisma version:
```
prisma               : 2.19.0
@prisma/client       : 2.19.0
Current platform     : linux-musl
Query Engine         : query-engine c1455d0b443d66b0d9db9bcb1bb9ee0d5bbc511d (at ../node_modules/@prisma/engines/query-engine-linux-musl)
Migration Engine     : migration-engine-cli c1455d0b443d66b0d9db9bcb1bb9ee0d5bbc511d (at ../node_modules/@prisma/engines/migration-engine-linux-musl)
Introspection Engine : introspection-core c1455d0b443d66b0d9db9bcb1bb9ee0d5bbc511d (at ../node_modules/@prisma/engines/introspection-engine-linux-musl)
Format Binary        : prisma-fmt c1455d0b443d66b0d9db9bcb1bb9ee0d5bbc511d (at ../node_modules/@prisma/engines/prisma-fmt-linux-musl)
Studio               : 0.358.0
Preview Features     : createMany
```

**Comment by Jolg42** [comment] 2021-03-18 10:12
> NODE_ENV environment variable. Always set itself for "production".

Thanks for the nice report!

Looks like a duplicate of https://github.com/prisma/prisma/issues/5990

You can subscribe there, it should be fixed in next version 😃

**Closed by Jolg42** 2021-03-18 10:12 UTC
Labels: bug/1-repro-available, kind/bug, team/client, team/migrations, topic: cli
