### ISSUE TITLE
Error connecting to Planetscale 

### ISSUE THREAD

**Issue by code-with-onye** [prisma/prisma#20333] opened 2023-07-21 13:50 UTC
### Bug description

Error: P1001: Can't reach database server at `aws.connect.psdb.cloud`:`3306`

Please make sure your database server is running at `aws.connect.psdb.cloud`:`3306`.

### Prisma information

```prisma
// This is your Prisma schema file,
// learn more about it in the docs: https://pris.ly/d/prisma-schema

generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider     = "mysql"
  url          = env("DATABASE_URL")
  relationMode = "prisma"
}

model Store {
  id     String @id @default(uuid())
  name   String
  userId String
  menus  Menu[] @relation("storeMenu")
  // menuCategory menuCategory[] @relation("storeMenuCategory")
  // product      Product[]      @relation("storeProduct")

  createdAt DateTime @default(now())
  updatedAt DateTime @updatedAt
}

model Menu {
  id        String   @id @default(uuid())
  name      String
  userId    String
  storeId   String
  createdAt DateTime @default(now())
  updatedAt DateTime @updatedAt

  store Store @relation("storeMenu", fields: [storeId], references: [id])
  // categories menuCategory[]

  @@index([storeId])
}

```

```ts
 const store = await prismadb.store.findFirst({
    where: {
      userId,
    },
  });

  // checking if store exsist
  if (store) {
    redirect(`/${store.id}`);
  }
```

### Environment & setup

- OS:   macOS
- Database:  Planetscale
- Node.js version: v16.19.1

### Prisma Version

```
^5.0.0
```

**Comment by millsp** [comment] 2023-07-21 16:46
Hey @code-with-onye could you please check if the port is not blocked by your ISP, router, firewall, or something else? Prisma is pretty standard and try to open a socket connection to the given URL and port. I see you are on a mac, so maybe something you could do is to find which terminal command to use in order to check if the port is working?

**Comment by SteakFisher** [comment] 2023-07-21 19:47
Heyo, try adding ?sslaccept=strict&connect_timeout=300 to the end of ur connection string situated within ur env file, also make sure that ur connection string format is accurate

**Comment by code-with-onye** [comment] 2023-07-21 20:41
> Hey @code-with-onye could you please check if the port is not blocked by your ISP, router, firewall, or something else? Prisma is pretty standard and try to open a socket connection to the given URL and port. I see you are on a mac, so maybe something you could do is to find which terminal command to use in order to check if the port is working?

can you help on how i can find which terminal command to use in order to check if the port is working?

**Comment by code-with-onye** [comment] 2023-07-21 20:44
> Heyo, try adding ?sslaccept=strict&connect_timeout=300 to the end of ur connection string situated within ur env file, also make sure that ur connection string format is accurate

Have tried adding connect_timeout=300  to the database url, same issue  occurred

**Comment by millsp** [comment] 2023-07-21 21:24
I am a linux user, but I'm pretty sure this would work on a mac (though I have not tested)

`nc -zv aws.connect.psdb.cloud 3306`

For me it shows:

```sh
~ nc -zv aws.connect.psdb.cloud 3306

Connection to aws.connect.psdb.cloud (44.238.124.216) 3306 port [tcp/mysql] succeeded!
```

**Comment by code-with-onye** [comment] 2023-07-21 23:42
> I am a linux user, but I'm pretty sure this would work on a mac (though I have not tested)
> 
> `nc -zv aws.connect.psdb.cloud 3306`
> 
> For me it shows:
> 
> ```shell
> ~ nc -zv aws.connect.psdb.cloud 3306
> 
> Connection to aws.connect.psdb.cloud (44.238.124.216) 3306 port [tcp/mysql] succeeded!
> ```

This is the error am having when i run  `nc -zv aws.connect.psdb.cloud 3306`,`nc: connectx to aws.connect.psdb.cloud port 3306 (tcp) failed: Operation timed out`

**Comment by millsp** [comment] 2023-07-22 02:24
In that case you should check the following [things](https://github.com/prisma/prisma/issues/20333#issuecomment-1645978989) I suggested earlier. Closing this issue, as it is not something we can fix, but more something on your end. Good luck!

**Closed by millsp** 2023-07-22 02:24 UTC
Labels: bug/0-unknown, kind/bug, tech/engines, topic: connections, team/client

**Comment by KalpChaudhary** [comment] 2023-11-04 00:05
@code-with-onye if the issue is still not solved then try connecting to a different internet connection. It worked for me. I tried everything that I found related to this error and wasn't able to solve it. Thank you @millsp for suggesting possible solutions.

**Comment by Emmanuel-Nkongolo** [comment] 2023-11-22 19:15
I was trying using the WSL i think it is the terminal,.. a normal gitbash would do
