### ISSUE TITLE
Fail on delete [code: 1105, message: "symbol ts.Address.addressId not found", state: "HY000" ]

### ISSUE THREAD

**Issue by ManolisPap** [prisma/prisma#12538] opened 2022-03-26 07:01 UTC
### Bug description

When i try to delete an address i get the following error message: 

Error occurred during query execution:
ConnectorError(ConnectorError { user_facing_error: None, kind: QueryError(Server(ServerError { code: 1105, message: "symbol ts.Address.addressId not found", state: "HY000" })) })

T.S. I inpect the index.d.ts and Address looks like:
/**
Model Address
 */
export type Address = {
  addressId: number
  address: string
  zipCode: string
  city: string
  floor: number | null
  doorNumber: string | null
}

### Expected behavior

Delete the addresses.

### Prisma information

prisma.schema
model Address {
  addressId  Int         @id @default(autoincrement())
  address    String      @db.VarChar(50)
  zipCode    String      @db.VarChar(50)
  city       String      @db.VarChar(50)
  floor      Int?
  doorNumber String?     @db.VarChar(50)
  orderFrom  Order[]     @relation("addressFrom")
  orderTo    Order[]     @relation("addressTo")
  telephones Telephone[]
  company    Company?
  recipient  Recipient?
}

// delete and deleteMany get the same error
  await prisma.address.deleteMany({
    where: {
      OR: [
        {
          addressId: 9,
        },
        {
          addressId: 10,
        },
      ],
    },
  });

  await prisma.address.delete({
    where: {
      addressId: 9,
    },
  });

### Environment & setup

- OS: Windows
- Database: PlanetScale
- Node.js version: v16.13.0

### Prisma Version

"prisma": "^3.10.0"

**Comment by janpio** [comment] 2022-03-28 13:07
Is this potentially a duplicate of https://github.com/prisma/prisma/issues/10758? If so, just close this issue. Thanks.

**Comment by janpio** [comment] 2022-03-31 21:56
Closing as duplicate of #10758

**Closed by janpio** 2022-03-31 21:56 UTC
Labels: kind/bug
