### ISSUE TITLE
Throw a better error message when a Postgres column exceeds its size limit

### ISSUE THREAD

**Issue by louisrli** [prisma/prisma#2730] opened 2020-06-12 15:01 UTC
## Bug description

Postgres column says `<unknown>` for column type in `update()`

StudyGuide is a pretty deeply nested entity that I'm creating at once (this is in a bulk create script that parses a CSV of base data), so it goes like StudyGuide -> Topic -> Section -> Concept -> Card -> Content, and each of these has fields that are quite long.

Using `DEBUG='*'` lets me see the exact mutation that caused the issue (it's 4000 lines long) so still it's a bit of a hassle to re-parse the mutation and figure out exactly which ones are candidates for exceeding some length.

So this bug is not about the underlying cause, which I'm assuming is that I'm trying to insert text that's too long into a char/varchar. The bug is that the error message is unclear for me to figure out which column it is:

```
Invalid `prisma.studyGuide.update()` invocation:


  The provided value for the column is too long for the column's type. Column: <unknown>
    at PrismaClientFetcher.request (/Users/louis/branches/srs/server/node_modules/@prisma/client/src/runtime/getPrismaClient.ts:762:15)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at main (/Users/louis/branches/srs/server/prisma.bak/spreadsheetseed.ts:104:5) {
  code: 'P2000',
  meta: { column_name: '<unknown>' }
}
```

## Expected behavior

It tells me the problematic column, or at least any other useful metainformation

## Prisma information

2.0 
## Environment & setup
Mac
Prisma 2
Node 14.4

**Comment by louisrli** [comment] 2020-06-12 15:07
Actually upon further inspection of the underlying postgres schema the strings seem to be `text` except for the ID. is this actually a problem with having a mutation that's too long?

**Comment by pantharshit00** [comment] 2020-06-18 12:54
Try changing the underlying column type to longtext or mediumtext. 


But I agree we need to throw a better message here. 

Simple reproduction for this error message.

Setup database with following sql and introspect it:
```sql
CREATE TABLE "public"."Test" (
    "content" varchar(255) NOT NULL,
    "id" text NOT NULL,
    PRIMARY KEY ("id")
);
```

Introspection should give you the following schema:
```prisma
model Test {
  id String @id @default(cuid())
  content String
}
```


Now run this script to reproduce:
```ts
import { PrismaClient } from "@prisma/client";

async function main() {
  const client = new PrismaClient();

  let myString = Array.from({ length: 256 })
    .map(() => " ")
    .join();

  await client.test.create({
    data: {
      content: myString,
    },
  });

  client.disconnect();
}

main();
```

**Comment by louisrli** [comment] 2020-07-02 08:26
After some diagnosing, I believe I've found the cause of this issue.

I used the prisma upgrade tool to introspect my prisma1 database, and it created id fields of `VARCHAR(25)` for postgres (perhaps it was `VARCHAR(25)` in prisma1 -- this I don't know).

However, after reading about cuid a bit, it seems that it's supposed to start at 25 characters but it's not guaranteed: https://github.com/ericelliott/cuid/issues/164#issuecomment-516637547

> In general, you should not try to depend on the length of a cuid string in any way (that's an anti-pattern).

So I suppose there's two issues at hand here:

1. The debug error message says `<unknown>`, which makes it very, very difficult for a user to usefully debug this issue.
2. The prisma-upgrade tool defaults to using `VARCHAR(25)` (or it takes it from prisma1) and then uses assigns it to use cuid, which causes this problem (I want to emphasize that I did nothing manually in this process in terms of altering the tables yet, besides running prisma-upgrade)

**Comment by janpio** [comment] 2020-07-02 09:08
> * The debug error message says `<unknown>`, which makes it very, very difficult for a user to usefully debug this issue.

That is a bug that should have an issue and then should just be fixed (cc @pantharshit00)

> 2\. The prisma-upgrade tool defaults to using `VARCHAR(25)` (or it takes it from prisma1) and then uses assigns it to use cuid, which causes this problem (I want to emphasize that I did nothing manually in this process in terms of altering the tables yet, besides running prisma-upgrade)

Varchar(25) is indeed the value in the Prisma 1 type database. I will point this out to the people working on the upgrade tool, so they can investigate.

**Comment by pantharshit00** [comment] 2020-07-02 12:57
> That is a bug that should have an issue and then should just be fixed (cc @pantharshit00)

This issue servers for that. I have a reproduction posted here for that as well. Julius should pick this up next sprint.


Other part should be handled via the upgrade tool

**Comment by tomhoule** [comment] 2020-07-09 15:07
I implemented that error message, and If I recall correctly, postgres doesn't return which column this happened to. We could check again (could be an omission), but if it's still the case, the only solution is to wait until we can express the maximum length of strings in the prisma schema. Then we can have a good error from the query engine.

**Comment by bardak-dev** [comment] 2020-07-10 04:02
cuid generate 26 length but @id field in schema.prisma makes pg column be varchar 25

**Comment by janpio** [comment] 2020-07-10 07:56
That should not be the case for new Prisma projects, only if you upgrade from Prisma 1 possibly. You can follow https://github.com/prisma/upgrade/issues/43 for our approach of fixing this @bardak-dev - it should be available soon in our P1-P2 upgrade tool.

**Comment by bardak-dev** [comment] 2020-07-10 09:27
> That should not be the case for new Prisma projects, only if you upgrade from Prisma 1 possibly. You can follow [prisma/upgrade#43](https://github.com/prisma/upgrade/issues/43) for our approach of fixing this @bardak-dev - it should be available soon in our P1-P2 upgrade tool.

That was the case, thank you 👍

**Comment by tomhoule** [comment] 2020-07-20 06:54
I just spent some time confirming that we cannot do better here, in terms of error message quality. This is the log output of all the error data we get from the database (the first part is the database error, the second part is what we extract from the database error):

```
[src/connector/postgres/error.rs:7] &e = Error {           
    kind: Db,                                              
    cause: Some(                                           
        DbError {                                          
            severity: "ERROR",                             
            parsed_severity: Some(                         
                Error,                                     
            ),                                             
            code: SqlState(                                
                "22001",                                   
            ),                                             
            message: "value too long for type character varying(5)",
            detail: None,                                  
            hint: None,                                    
            position: None,                                                                                            
            where_: None,                                  
            schema: None,                                  
            table: None,                                                                                                                                                                                                                       
            column: None,                                                                                              
            datatype: None,                                
            constraint: None,                              
            file: Some(                                    
                "varchar.c",                               
            ),                                                                                                         
            line: Some(                                                                                                
                624,                                       
            ),                                                                                                         
            routine: Some(                                 
                "varchar",                                 
            ),                                             
        },                                                 
    ),                                                     
}                                                          
[src/connector/postgres.rs:992] &err = Error {
    kind: LengthMismatch {                                 
        column: None,                                      
    },                                                     
    original_code: Some(                                   
        "22001",                                           
    ),                                                     
    original_message: Some(                                
        "ERROR: value too long for type character varying(5)",
    ),                                                     
}
```

So I think that sadly, we currently cannot say which column exceeds the size limit on postgres. @pimeys do you think sqlx could change that?

**Comment by pimeys** [comment] 2020-07-20 06:56
This error comes directly from the database. We probably cannot do better.

**Comment by tomhoule** [comment] 2020-07-20 07:40
Conclusion: there is nothing we can do now. Once we can express more precise types in the prisma schema, which is very much planned, the query engine can potentially validate this and return a better error.

**Comment by janpio** [comment] 2020-07-20 11:53
Is the situation the same for MySQL and SQLite?

Native Types would probably already allow us to validate the data on the Client or QE level, to avoid sending the query in the first place. With out of data schema definition, we could still hit this error message though so fully understanding it might be beneficial.

**Comment by tomhoule** [comment] 2020-07-20 13:17
MySQL returns the column with the error, so we display it there.

SQLite does not have the notion of a limited length string columns if I remember correctly, so this error can't occur.

**Comment by pantharshit00** [comment] 2021-05-04 13:39
Closing since native type work addresses most of cuid concerns and we mark the column as `(not available)` in postgres now.

**Closed by pantharshit00** 2021-05-04 13:39 UTC
Labels: bug/2-confirmed, kind/bug, status/needs-action, team/client, tech/engines, topic: error, topic: prisma-client

**Comment by baileymckay** [comment] 2022-01-29 20:18
@louisrli Did you ever figure out the cause of your specific issue? I seem to be running into the same thing. I get:

Error: Invalid `prisma.XXX.create()` invocation: The provided value for the column is too long for the column's type. Column: (not available)

Like you, I introspected from Prisma1. I'm using Postgres. All my text columns are "Text" except my ids, which are VARCHAR(30). I migrated with the updated tool that has you ALTER COLUMN of cuids to "character varying(30)".

However, I still get this error, and it's hard to diagnose why. Whatever caused this initial error still seems to be there. Does anyone have any ideas? I'm not ever sure what to try.

**Comment by baileymckay** [comment] 2022-01-29 22:18
Ok, I figured mine out. It was indeed being caused by old Prisma1 cuid fields in varchar(25) rather than varchar(30), but they were in a many-to-many join table. Apparently, prisma-upgrade does not generate the SQL statements to take care of such fields. I altered the table manually, and everything seems to be working.
