### ISSUE TITLE
Aggregation using "where" clause on a relation is not working

### ISSUE THREAD

**Issue by AhmadElsagheer** [prisma/prisma#4422] opened 2019-04-20 16:34 UTC
**Describe the bug**
I have the following two models:
```
type Blog {
  id: ID! @id
  title: String!
  labels: [Label!]! @relation(name: "BlogLabels", link: INLINE)
}

type Label {
  id: ID! @id
  text: String! @unique
}
```
I want to count the number of blogs that have a specific label. However, the count returned by the aggregation is always zero.

**To Reproduce**
1. Create the two models above.
2. Create a label
```
mutation {
  createLabel(data: {
    text: "l"
  }) {
    text
  }
}
```
3. Create a blog with the label
```
mutation {
  createBlog(data: {
    title: "blog_1"
    labels: {
      connect: {
        text: "l"
      }
    }
  }) {
    title
  }
}
```
4. Create a blog without the label
```
mutation {
  createBlog(data: {
    title: "blog_2"
  }) {
    title
  }
}
```
5. Query for the blogs and the aggregated count
```
query {
  blogs(where: {
    labels_some: {
      text: "l"
    }
  }) {
    title
  }
  blogsConnection(where: {
    labels_some: {
      text: "l"
    }
  }) {
    aggregate {
      count
    }
  }
}
```
The output will be
```
{
  "data": {
    "blogs": [
      {
        "title": "blog_1"
      }
    ],
    "blogsConnection": {
      "aggregate": {
        "count": 0
      }
    }
  }
}
```

**Expected behavior**
```
{
  "data": {
    "blogs": [
      {
        "title": "blog_1"
      }
    ],
    "blogsConnection": {
      "aggregate": {
        "count": 1
      }
    }
  }
}
```

**Versions (please complete the following information):**
 - Connector: [`MongoDB`]
 - Prisma Server: [`1.31.0`]
 - `prisma` CLI: [`prisma/1.31.0 (linux-x64) node-v10.15.3`]
 - OS: [`Ubuntu 18.04`]

**Comment by pantharshit00** [comment] 2019-04-21 17:44
Closing as a duplicate of https://github.com/prisma/prisma/issues/4414

**Closed by pantharshit00** 2019-04-21 17:44 UTC
