### ISSUE TITLE
Unnecessary select statement generated for one-to-one relation in create/update operation when primary key is provided in connect clause or where clause

### ISSUE THREAD

**Issue by aflatoon2874** [prisma/prisma#3518] opened 2020-09-04 02:40 UTC
## Problem
Unnecessary select statement is generated when primary key is provided in connect clause for a create and/or update operation. 
For example:
```
await prisma.post.create({
   title: 'Post 1',
   author: {
     connect: {
        id: 1
     }
   }
})

await global.prisma.user.update({
  where: { id: user.id },
  data: { lastLoginAt: new Date() }
})
```
Here, `id` is primary key, therefore the provided value should be used as-is. There is no need to fetch it again from db.

## Suggested solution
If `connect` clause provides the primary key then the select statement should not be generated. The provided value should be used as-is in the resulting insert statement. 

## Alternatives
None

## Additional context
None

**Comment by pantharshit00** [comment] 2020-09-09 11:07
I can confirm this behaviour. This can be improved in the future.

**Comment by aflatoon2874** [comment] 2020-12-03 07:00
@pantharshit00 - Any ETA please. This is a much needed performance improvement. Please do not defer any further. Thanks

**Comment by laplab** [comment] 2024-01-30 13:03
Thanks to the work done in [Prisma 5.1.0 release](https://github.com/prisma/prisma/releases/tag/5.1.0), this issue no longer reproduces. This is because we use `RETURNING` statement, which enables us to skip the initial `SELECT` query.

Users might experience similar issues with nested updates as well as on MySQL and MSSQL. However, this is out of scope for this issue and will be addressed separately in https://github.com/prisma/prisma/issues/2157.

**Closed by laplab** 2024-01-30 13:03 UTC
Labels: kind/improvement, topic: performance, tech/engines, team/client, topic: performance/queries
