### ISSUE TITLE
PANIC: supplied instant is later than self in library/std/src/time.rs:313:48

### ISSUE THREAD

**Issue by paulvidal** [prisma/prisma#11905] opened 2022-02-18 09:49 UTC
Hi Prisma Team! My Prisma Client just crashed. This is the report:
## Versions

| Name            | Version            |
|-----------------|--------------------|
| Node            | v16.13.0           | 
| OS              | debian-openssl-1.1.x|
| Prisma Client   | 3.9.2              |
| Query Engine    | 0.1.0              |
| Database        | postgresql         |

## Logs
```
prisma:tryLoadEnv Environment variables not found at null
prisma:tryLoadEnv Environment variables not found at undefined
prisma:tryLoadEnv No Environment variables loaded
prisma:tryLoadEnv Environment variables not found at null
prisma:tryLoadEnv Environment variables not found at undefined
prisma:tryLoadEnv No Environment variables loaded
prisma:client clientVersion: 3.9.2
prisma:client clientEngineType: library
prisma:client:libraryEngine internalSetup
prisma:client:libraryEngine Searching for Query Engine Library in /src/app/node_modules/.prisma/client
prisma:client:libraryEngine loadEngine using /src/app/node_modules/.prisma/client/libquery_engine-debian-openssl-1.1.x.so.node
prisma:client:libraryEngine library starting
prisma:client:libraryEngine library started
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine requestBatch
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine requestBatch
prisma:client:libraryEngine requestBatch
prisma:client:libraryEngine requestBatch
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
```

## Client Snippet
```ts
await this.prisma.user.findUnique({
      where: {
        id: id,
        email: email,
      },
      include: {
        members: {
          include: { collective: true },
        },
        userCompany: true,
      },
    });
```

## Schema
```prisma

model User {
  id                             String          @id @default(cuid())
  email                       String          @unique @db.VarChar(255)
  token                       String?        @db.VarChar(1000)
  tokenExp                 DateTime?  @db.Timestamptz(3)
  createdAt                DateTime    @default(now()) @db.Timestamptz(3)

  members                Member[]
  userCompany        UserCompany?
}

model UserCompany {
  id                                            String                 @id @default(cuid())
  userId                                     String                 @unique
  name                                      String?
  companyRegistrationId        String?

  user User @relation(fields: [userId], references: [id], onDelete: Cascade)
}

model Member {
  id                      String       @id @default(cuid())
  userId              String
  collectiveId     String
  createdAt        DateTime  @default(now()) @db.Timestamptz(3)
  title                  String?      @db.VarChar(255)
  bio                   String?
  references      String?

  user                              User                              @relation(fields: [userId], references: [id], onDelete: Cascade)
  collective                     Collective                      @relation(fields: [collectiveId], references: [id])

  @@unique([userId, collectiveId])
}

model Collective {
  id                   String            @id @default(cuid())
  name             String            @db.VarChar(255)
  createdAt      DateTime      @default(now()) @db.Timestamptz(3)

  members              Member[]
}
```

## Prisma Engine Query
```

```

## Error

```
Error:
Invalid `this.prisma.user.findUnique()` invocation in
/src/app/dist/apps/backend/main.js:12832:49
12829 }
12830 getByUniqueId({ id, email, }) {
12831 return (0, tslib_1.__awaiter)(this, void 0, void 0, function* () {
→ 12832 const user = yield this.prisma.user.findUnique(
PANIC: supplied instant is later than self in library/std/src/time.rs:313:48
```

## Additional notes

I got in my logs the following error

```
thread 'tokio-runtime-worker' panicked at 'supplied instant is later than self', library/std/src/time.rs:313:48
```

**Comment by paulvidal** [comment] 2022-02-22 22:59
@janpio I added all the info :) sorry for the terrible formatting, not sure why this is happening github readme is a bit weird here :) hope you manage to get this one, seems pretty bad :'(

**Comment by janpio** [comment] 2022-02-23 13:46
Formatting is fine, thanks for the edit! Someone can now look into this.

**Comment by pantharshit00** [comment] 2022-02-25 12:42
I am unable to reproduce. Can you try this again with 3.10 once?

**Comment by Jolg42** [comment] 2022-08-31 15:27
Note: could be that the system clock is not set correctly and our dependency errors.

**Comment by Jolg42** [comment] 2022-08-31 15:30
@paulvidal Was it a one time thing or did it happen multiple times? Are you still experiencing this issue?

**Comment by Jolg42** [comment] 2022-08-31 15:40
Closing: we think this is fixed. Let us know if it's not fixed.

**Closed by Jolg42** 2022-08-31 15:40 UTC
Labels: bug/1-unconfirmed, kind/bug, tech/engines, team/client, topic: basic error report, priority/high, size/unknown
