### ISSUE TITLE
Support default `select` value on migration

### ISSUE THREAD

**Issue by Ridwansameer** [prisma/prisma#3726] opened 2020-09-21 15:53 UTC
## Problem
Currently there is no ability to set a column to be `false` by default on `findOne` or `findMany`

Assume I have a large table, with 10 columns. I know that 9 out of 10 times I only want three of these columns. I would have to write 
```
await prisma.user.findOne({
  where: { id: 1 },
  select: {
    fieldIwant: true,
    otherFieldIwant: true,
    thirdFieldIwant: true,
  },
})
```
## Suggested solution
Make Prisma Migrate support something along the following
```
model User {
  id  @autoincrement  Int
  fieldIwant  String
  otherFieldIwant String
  thirdFieldIwant String
  fieldIDontWant  String  @select(false)
  secondFieldIDontWant  String  @select(false)
  thirdFieldIDontWant  String  @select(false)
}
```

## Alternatives
The syntax can change depending on preference. Maybe just a decorator that says `@noDefaultSelect`

## Additional context
N/A

**Comment by pantharshit00** [comment] 2020-09-21 17:29
Hi,

Thanks for reporting this! It has already been reported before, so I am going to close this as a duplicate of https://github.com/prisma/prisma/issues/3636

**Closed by pantharshit00** 2020-09-21 17:29 UTC
