### ISSUE TITLE
prisma db seed doesn't correctly support `"type": "module"`

### ISSUE THREAD

**Issue by ghoullier** [prisma/prisma#7053] opened 2021-05-12 12:32 UTC
## Problem

When you enable module resolution with `"type": "module"` on your projet the `prisma db seed` command fail due to ts-node resolution.

```sh
➜ yarn prisma db seed --preview-feature
yarn run v1.22.10
$ /path-to-my-project/node_modules/.bin/prisma db seed --preview-feature
Environment variables loaded from prisma/.env
Prisma schema loaded from prisma/schema.prisma
Running ts-node "prisma/seed.ts" ...
TypeError [ERR_UNKNOWN_FILE_EXTENSION]: Unknown file extension ".ts" for /path-to-my-project/play-prisma-sqlite/prisma/seed.ts
    at new NodeError (node:internal/errors:329:5)
    at Loader.defaultGetFormat [as _getFormat] (node:internal/modules/esm/get_format:71:15)
    at Loader.getFormat (node:internal/modules/esm/loader:104:42)
    at Loader.getModuleJob (node:internal/modules/esm/loader:242:31)
    at Loader.import (node:internal/modules/esm/loader:176:17)
    at Object.loadESM (node:internal/process/esm_loader:68:5)
Error: Command failed with exit code 1: ts-node "prisma/seed.ts"
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

## Suggested solution

When `"type": "module"` is detected:  instead of running `ts-node "prisma/seed.ts"` you can use the node loader `node --loader ts-node/esm "prisma/seed.ts"`

## Alternatives

N/A

## Additional context

Project example https://github.com/ghoullier/esm-prisma-seed

**Comment by ymzuiku** [comment] 2021-05-31 16:33
This is temp case:

1 - Install esbuild in your project

```bash
npm i esbuild --save-dev
```
2  - add `seed` in  your `package.json` scripts:

```json
"scripts": {
  "seed":"esbuild prisma/seed.ts --outfile=node_modules/tmp-seed.cjs --bundle --format=cjs --external:prisma --external:@prisma/client && node node_modules/tmp-seed.cjs --preview-feature"
}
```

3 - run seed script

```bash
npm run seed
```

**Comment by Jolg42** [comment] 2021-06-23 09:53
I reproduced your issue and could make it work using `prisma` & `@prisma/client` `~2.24.0` and using this file with modified syntax as the seed script in `./prisma/seed.ts`
```
const Prisma = require("@prisma/client");
const prisma = new Prisma.PrismaClient();

async function main() {
  await prisma.task.create({
    data: {
      name: `Todo`,
    },
  });

  const tasks = await prisma.task.findMany();

  console.table(tasks);

  await prisma.$disconnect();
}

module.exports = main;
```

Note `2.25.0` errors with 
```
Running seed from prisma/seed.ts ...
/Users/j42/Dev/repro/esm-prisma-seed/[eval].ts:36
export {};
^^^^^^

SyntaxError: Unexpected token 'export'
    at new Script (node:vm:100:7)
    at exec (/Users/j42/Dev/repro/esm-prisma-seed/node_modules/ts-node/src/repl.ts:194:18)
    at /Users/j42/Dev/repro/esm-prisma-seed/node_modules/ts-node/src/repl.ts:186:27
    at Array.reduce (<anonymous>)
    at _eval (/Users/j42/Dev/repro/esm-prisma-seed/node_modules/ts-node/src/repl.ts:185:18)
    at Object.evalCode (/Users/j42/Dev/repro/esm-prisma-seed/node_modules/ts-node/src/repl.ts:77:12)
    at evalAndExit (/Users/j42/Dev/repro/esm-prisma-seed/node_modules/ts-node/src/bin.ts:267:26)
    at main (/Users/j42/Dev/repro/esm-prisma-seed/node_modules/ts-node/src/bin.ts:195:5)
    at Object.<anonymous> (/Users/j42/Dev/repro/esm-prisma-seed/node_modules/ts-node/src/bin.ts:288:3)
    at Module._compile (node:internal/modules/cjs/loader:1109:14)
```
I will look at this separately.

**Comment by Jolg42** [comment] 2021-08-13 15:47
🗒️ We heard the feedback and we are planning a redesign of `db seed` (currently planned to be released early September)

How it will work is that a `prisma.seed` property in the package.json of your project will be required if you want to use `prisma db seed`.

This property is where you will be able to put any command you want to execute your seed script.

More info/details & how to try it out now in:
https://github.com/prisma/prisma/issues/8732

**Comment by janpio** [comment] 2021-09-09 12:22
The redesign of `db seed` was released with Prisma 3. Please try it, this problem should be gone.

**Closed by janpio** 2021-09-09 12:22 UTC
Labels: bug/2-confirmed, kind/bug, tech/typescript, team/migrations, topic: esm, topic: db seed

**Comment by smamun19** [comment] 2022-11-21 19:52
I am facing this issue in Prisma 3.11.1 

`Running seed command `ts-node prisma/seed.ts` ...
TypeError [ERR_UNKNOWN_FILE_EXTENSION]: Unknown file extension ".ts" for /home/mamun/Dev/foodie-backend/prisma/seed.ts
    at new NodeError (node:internal/errors:372:5)
    at Object.getFileProtocolModuleFormat [as file:] (node:internal/modules/esm/get_format:76:11)
    at defaultGetFormat (node:internal/modules/esm/get_format:118:38)
    at defaultLoad (node:internal/modules/esm/load:21:20)
    at ESMLoader.load (node:internal/modules/esm/loader:407:26)
    at ESMLoader.moduleProvider (node:internal/modules/esm/loader:326:22)
    at new ModuleJob (node:internal/modules/esm/module_job:66:26)
    at ESMLoader.#createModuleJob (node:internal/modules/esm/loader:345:17)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:304:34)
    at async Promise.all (index 0) {
  code: 'ERR_UNKNOWN_FILE_EXTENSION'
}

An error occured while running the seed command:
Error: Command failed with exit code 1: ts-node prisma/seed.ts`

**Comment by smamun19** [comment] 2022-11-21 20:12
I am facing the same issue with Prisma 3.11.1 but removing `"type": "module"` solves the issue.

````
Running seed command `ts-node prisma/seed.ts` ...
TypeError [ERR_UNKNOWN_FILE_EXTENSION]: Unknown file extension ".ts" for /home/mamun/Dev/foodie-backend/prisma/seed.ts
    at new NodeError (node:internal/errors:372:5)
    at Object.getFileProtocolModuleFormat [as file:] (node:internal/modules/esm/get_format:76:11)
    at defaultGetFormat (node:internal/modules/esm/get_format:118:38)
    at defaultLoad (node:internal/modules/esm/load:21:20)
    at ESMLoader.load (node:internal/modules/esm/loader:407:26)
    at ESMLoader.moduleProvider (node:internal/modules/esm/loader:326:22)
    at new ModuleJob (node:internal/modules/esm/module_job:66:26)
    at ESMLoader.#createModuleJob (node:internal/modules/esm/loader:345:17)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:304:34)
    at async Promise.all (index 0) {
  code: 'ERR_UNKNOWN_FILE_EXTENSION'
}

An error occured while running the seed command:
Error: Command failed with exit code 1: ts-node prisma/seed.ts
````

**Comment by Erij-Maherzia-BEN-BRAHIM** [comment] 2022-12-27 20:42
I've uninstalled the anitvirus then it worked for me ✅

**Comment by thegartrell** [comment] 2023-04-02 20:13
You can just tell ts-node to use CJS module resolution when transpiling `seed.ts` by passing `--compilier-options {"module":"CommonJS"}` in your seed command in your `package.json`. 

```
"prisma": { 
    "seed": "ts-node --compiler-options {\"module\":\"CommonJS\"} prisma/seed.ts" 
},
```

**Comment by nrthbound** [comment] 2023-04-05 04:27
Still running into this issue with the latest version of Prisma while using Sveltekit. I've installed all the prerequisites.

```
Environment variables loaded from .env
Running seed command `ts-node prisma/seed.ts` ...
TypeError [ERR_UNKNOWN_FILE_EXTENSION]: Unknown file extension ".ts" for /Users/username/development/northbound/apps/geekd-samples/prisma/seed.ts
    at new NodeError (node:internal/errors:393:5)
    at Object.getFileProtocolModuleFormat [as file:] (node:internal/modules/esm/get_format:75:9)
    at defaultGetFormat (node:internal/modules/esm/get_format:114:38)
    at defaultLoad (node:internal/modules/esm/load:81:20)
    at nextLoad (node:internal/modules/esm/loader:161:28)
    at ESMLoader.load (node:internal/modules/esm/loader:594:26)
    at ESMLoader.moduleProvider (node:internal/modules/esm/loader:446:22)
    at new ModuleJob (node:internal/modules/esm/module_job:64:26)
    at ESMLoader.#createModuleJob (node:internal/modules/esm/loader:469:17)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:423:34) {
  code: 'ERR_UNKNOWN_FILE_EXTENSION'
}

An error occurred while running the seed command:
Error: Command failed with exit code 1: ts-node prisma/seed.ts
```
I've tried it multiple ways 
```
"prisma": {
    "seed": "ts-node prisma/seed.ts"
  },
  ```
and 
```
"prisma": {
    "seed": "ts-node --compiler-options {\"module\":\"CommonJS\"} prisma/seed.ts"
  },
```

Not sure what else to try here.

**Comment by janpio** [comment] 2023-04-06 20:27
Anyone who still has this problem, open a new issue please and fill the issue template. We can not react to closed issues. Thanks.

**Comment by Nakroma** [comment] 2023-04-11 12:03
Had the same problem, but `ts-node --esm prisma/seed.ts` is working for me

**Comment by ARMATAV** [comment] 2023-05-19 03:58
> Had the same problem, but the ts-node esm flag fixed it for me: `ts-node --esm prisma/seed.ts`

This is perfect, `CommonJS` is not working

**Comment by fadbad** [comment] 2023-05-21 02:28
[TSX](https://github.com/esbuild-kit/tsx) worked for me in sveltekit
---
yarn add -D tsx
---
"prisma": {
    "seed": "tsx prisma/seed.ts"
 }

**Comment by vicentematus** [comment] 2023-05-26 05:20
> ## [TSX](https://github.com/esbuild-kit/tsx) worked for me in sveltekit
> ## yarn add -D tsx
> "prisma": { "seed": "tsx prisma/seed.ts" }

After trying for a few hours, this also worked for me with typescript. I'm also using SvelteKit.

**Comment by dox-exon** [comment] 2023-06-07 12:55
###TSX also worked for me

**Comment by stephanalas** [comment] 2023-06-16 14:14
TSX FTW!

**Comment by cesarvarela** [comment] 2023-07-04 03:20
`tsx` worked for me too, while all the other suggestions did not, but I would like to understand why.

**Comment by gustavospriebe** [comment] 2023-07-29 03:09
> You can just tell ts-node to use CJS module resolution when transpiling `seed.ts` by passing `--compilier-options {"module":"CommonJS"}` in your seed command in your `package.json`.
> 
> ```
> "prisma": { 
>     "seed": "ts-node --compiler-options {\"module\":\"CommonJS\"} prisma/seed.ts" 
> },
> ```

Only solution that works for me on Next 13.4.12

**Comment by mikenator5** [comment] 2023-08-16 02:41
> Still running into this issue with the latest version of Prisma while using Sveltekit. I've installed all the prerequisites.

I was running into the same issues but had success with `tsx`.
```
npm install -D tsx
npx prisma db seed
``` 

Svelte version: `"svelte": "^4.0.5",`

**Comment by tlbignerd** [comment] 2023-09-20 18:26
I'm using Vue3 and Vite (not Svelte) and the `tsx` solution worked for me.

**Comment by fbt0wizard** [comment] 2023-11-16 16:15
I fixed this buy doing the following 

Note i have  `"next": "13.5.6",`

1. i add `"type": "module",` to package.json not sure this is necessary
2.  ```
"prisma": {
    "seed": "ts-node prisma/seed.mjs" 
  },
``` in package.json

3. i renamed my seet.ts file to seed.mjs
4. then i run `npx prisma db seed`


I hope this is helpful

**Comment by karis** [comment] 2024-07-16 10:39
works for me too

> > ## [TSX](https://github.com/esbuild-kit/tsx) worked for me in sveltekit
> > ## yarn add -D tsx
> > "prisma": { "seed": "tsx prisma/seed.ts" }
> 
> using tsx worked for me

**Comment by Lockwu6749** [comment] 2024-10-25 15:20
Removing "type": "module" from the package.json and using:
"prisma": {
    "seed": "ts-node --compiler-options {\"module\":\"CommonJS\"} prisma/seed.ts"
  },
  worked for me
