### ISSUE TITLE
Incorrect syntax near 'OFFSET'.

### ISSUE THREAD

**Issue by kawin-pk** [prisma/prisma#8816] opened 2021-08-19 09:15 UTC
Hi Prisma Team! My Prisma Client just crashed. This is the report:
## Versions

| Name            | Version            |
|-----------------|--------------------|
| Node            | v12.16.1           | 
| OS              | windows            |
| Prisma Client   | 2.29.1             |
| Query Engine    | undefined|
| Database        | SQL Server 1074147850  |

## Query
```
mutation {
  createOnetb_ComplaintJob(data: {
    Title: "X"
    Contact_FirstName: "X"
    Contact_LastName: "X"
    Contact_HomeNo: "X"
  }) {
    ID
    ComplaintJobID
    Title
    Contact_FirstName
    Contact_LastName
    Contact_HomeNo
    Contact_Moo
    Contact_Soi
    Contact_Road
    Contact_Subdistrict
    Contact_District
    Contact_Province
    Contact_Zipcode
    Contact_Phone
    Contact_Email
    ComplaintType
    IsValid
    InvalidRemark
    IsConfidential
    ResponsibleBy
    CreateBy
    CreateDate
    UpdateBy
    UpdateDate
    ComplaintState
    RNo
    RTo
    RReason
    RObjective
    RSum
    RDate
    RAttachment
    Contact_Country
    PrintDate
    ContactSubdistrictId
    ContactDistrictId
    ContactProvinceId
    InvalidRemarkId
    IsCancel
  }
}
```

## Logs
```
TLS handshake successful  
  prisma:engine stdout  Turning TLS off after a login. All traffic from here on is not encrypted.  
  prisma:engine stdout  Database change from 'NHRCT_DBS' to 'master'  
  prisma:engine stdout  Changed database context to 'NHRCT_DBS'.  
  prisma:engine stdout  SQL collation change from None to None  
  prisma:engine stdout  Microsoft SQL Server version 1074147850  
  prisma:engine stdout  Packet size change from '4096' to '4096'  
  prisma:engine stdout  Started http server on http://127.0.0.1:60954  
  prisma:engine Search for Query Engine in C:\Work\me-rights-complain\node_modules\.prisma\client  
  prisma:engine stdout  Begin transaction  
  prisma:engine stdout  Incorrect syntax near 'OFFSET'.  
  prisma:engine stdout  Rollback transaction  
  prisma:engine {
  prisma:engine   error: PrismaClientUnknownRequestError3 [PrismaClientUnknownRequestError]: Error occurred during query execution:
  prisma:engine   ConnectorError(ConnectorError { user_facing_error: None, kind: QueryError(TokenError { code: 102, state: 1, class: 15, message: "Incorrect syntax near 'OFFSET'.", server: "DATAAPPLICATION", procedure: "", line: 1 }) })
  prisma:engine       at BinaryEngine.graphQLToJSError (C:\Work\me-rights-complain\node_modules\@prisma\client\runtime\index.js:29974:14)
  prisma:engine       at BinaryEngine.request (C:\Work\me-rights-complain\node_modules\@prisma\client\runtime\index.js:29857:24)
  prisma:engine       at processTicksAndRejections (internal/process/task_queues.js:97:5)
  prisma:engine       at cb (C:\Work\me-rights-complain\node_modules\@prisma\client\runtime\index.js:36344:26) {
  prisma:engine     clientVersion: '2.29.1'
  prisma:engine   }
  prisma:engine }  
  prisma:engine stdout  Begin transaction  
  prisma:engine stdout  Incorrect syntax near 'OFFSET'.  
  prisma:engine stdout  Rollback transaction  
  prisma:engine {
  prisma:engine   error: PrismaClientUnknownRequestError3 [PrismaClientUnknownRequestError]: Error occurred during query execution:
  prisma:engine   ConnectorError(ConnectorError { user_facing_error: None, kind: QueryError(TokenError { code: 102, state: 1, class: 15, message: "Incorrect syntax near 'OFFSET'.", server: "DATAAPPLICATION", procedure: "", line: 1 }) })
  prisma:engine       at BinaryEngine.graphQLToJSError (C:\Work\me-rights-complain\node_modules\@prisma\client\runtime\index.js:29974:14)
  prisma:engine       at BinaryEngine.request (C:\Work\me-rights-complain\node_modules\@prisma\client\runtime\index.js:29857:24)
  prisma:engine       at processTicksAndRejections (internal/process/task_queues.js:97:5)
  prisma:engine       at cb (C:\Work\me-rights-complain\node_modules\@prisma\client\runtime\index.js:36344:26) {
  prisma:engine     clientVersion: '2.29.1'
  prisma:engine   }
  prisma:engine }  
  prisma:engine stdout  Begin transaction  
  prisma:engine stdout  Incorrect syntax near 'OFFSET'.  
  prisma:engine stdout  Rollback transaction  
  prisma:engine {
  prisma:engine   error: PrismaClientUnknownRequestError3 [PrismaClientUnknownRequestError]: Error occurred during query execution:
  prisma:engine   ConnectorError(ConnectorError { user_facing_error: None, kind: QueryError(TokenError { code: 102, state: 1, class: 15, message: "Incorrect syntax near 'OFFSET'.", server: "DATAAPPLICATION", procedure: "", line: 1 }) })
  prisma:engine       at BinaryEngine.graphQLToJSError (C:\Work\me-rights-complain\node_modules\@prisma\client\runtime\index.js:29974:14)
  prisma:engine       at BinaryEngine.request (C:\Work\me-rights-complain\node_modules\@prisma\client\runtime\index.js:29857:24)
  prisma:engine       at processTicksAndRejections (internal/process/task_queues.js:97:5)
  prisma:engine       at cb (C:\Work\me-rights-complain\node_modules\@prisma\client\runtime\index.js:36344:26) {
  prisma:engine     clientVersion: '2.29.1'
  prisma:engine   }
  prisma:engine }  
```
Mutation Create, and Query where with take, skip got this error

**Comment by janpio** [comment] 2021-08-19 11:31
Can you please share your Prisma Client query that creates this request?

**Comment by kawin-pk** [comment] 2021-08-19 14:28
Hi Prisma Team! My Prisma Client just crashed. This is the report:
## Versions

| Name            | Version            |
|-----------------|--------------------|
| Node            | v12.16.1           | 
| OS              | windows            |
| Prisma Client   | 2.29.1             |
| Query Engine    | undefined|
| Database        | undefined|



## Query
```
mutation {
  createOnetb_ComplaintJob(data: {
    ComplaintJobID: "X"
  }) {
    ID
    ComplaintJobID
    Title
    Contact_FirstName
    Contact_LastName
    Contact_HomeNo
    Contact_Moo
    Contact_Soi
    Contact_Road
    Contact_Subdistrict
    Contact_District
    Contact_Province
    Contact_Zipcode
    Contact_Phone
    Contact_Email
    ComplaintType
    IsValid
    InvalidRemark
    IsConfidential
    ResponsibleBy
    CreateBy
    CreateDate
    UpdateBy
    UpdateDate
    ComplaintState
    RNo
    RTo
    RReason
    RObjective
    RSum
    RDate
    RAttachment
    Contact_Country
    PrintDate
    ContactSubdistrictId
    ContactDistrictId
    ContactProvinceId
    InvalidRemarkId
    IsCancel
  }
}
```

## Logs
```
om None to None  
  prisma:engine stdout  Microsoft SQL Server version 1074147850  
  prisma:engine stdout  Packet size change from '4096' to '4096'  
  prisma:engine stdout  Started http server on http://127.0.0.1:50918  
  prisma:engine Search for Query Engine in C:\Work\me-rights-complain\node_modules\.prisma\client  
  prisma:engine stdout  Begin transaction  
  prisma:engine stdout  Incorrect syntax near 'OFFSET'.  
  prisma:engine stdout  Rollback transaction  
  prisma:engine {
  prisma:engine   error: PrismaClientUnknownRequestError3 [PrismaClientUnknownRequestError]: Error occurred during query execution:
  prisma:engine   ConnectorError(ConnectorError { user_facing_error: None, kind: QueryError(TokenError { code: 102, state: 1, class: 15, message: "Incorrect syntax near 'OFFSET'.", server: "DATAAPPLICATION", procedure: "", line: 1 }) })
  prisma:engine       at BinaryEngine.graphQLToJSError (C:\Work\me-rights-complain\node_modules\@prisma\client\runtime\index.js:29974:14)
  prisma:engine       at BinaryEngine.request (C:\Work\me-rights-complain\node_modules\@prisma\client\runtime\index.js:29857:24)
  prisma:engine       at processTicksAndRejections (internal/process/task_queues.js:97:5)
  prisma:engine       at cb (C:\Work\me-rights-complain\node_modules\@prisma\client\runtime\index.js:36344:26)
  prisma:engine       at createNews (C:\Work\me-rights-complain\mom.ts:8:5)
  prisma:engine       at seed (C:\Work\me-rights-complain\mom.ts:5:5) {
  prisma:engine     clientVersion: '2.29.1'
  prisma:engine   }
  prisma:engine }  
  prisma:engine stdout  Begin transaction  
  prisma:engine stdout  Incorrect syntax near 'OFFSET'.  
  prisma:engine stdout  Rollback transaction  
  prisma:engine {
  prisma:engine   error: PrismaClientUnknownRequestError3 [PrismaClientUnknownRequestError]: Error occurred during query execution:
  prisma:engine   ConnectorError(ConnectorError { user_facing_error: None, kind: QueryError(TokenError { code: 102, state: 1, class: 15, message: "Incorrect syntax near 'OFFSET'.", server: "DATAAPPLICATION", procedure: "", line: 1 }) })
  prisma:engine       at BinaryEngine.graphQLToJSError (C:\Work\me-rights-complain\node_modules\@prisma\client\runtime\index.js:29974:14)
  prisma:engine       at BinaryEngine.request (C:\Work\me-rights-complain\node_modules\@prisma\client\runtime\index.js:29857:24)
  prisma:engine       at processTicksAndRejections (internal/process/task_queues.js:97:5)
  prisma:engine       at cb (C:\Work\me-rights-complain\node_modules\@prisma\client\runtime\index.js:36344:26)
  prisma:engine       at createNews (C:\Work\me-rights-complain\mom.ts:8:5)
  prisma:engine       at seed (C:\Work\me-rights-complain\mom.ts:5:5) {
  prisma:engine     clientVersion: '2.29.1'
  prisma:engine   }
  prisma:engine }  
  prisma:engine stdout  Begin transaction  
  prisma:engine stdout  Incorrect syntax near 'OFFSET'.  
  prisma:engine stdout  Rollback transaction  
  prisma:engine {
  prisma:engine   error: PrismaClientUnknownRequestError3 [PrismaClientUnknownRequestError]: Error occurred during query execution:
  prisma:engine   ConnectorError(ConnectorError { user_facing_error: None, kind: QueryError(TokenError { code: 102, state: 1, class: 15, message: "Incorrect syntax near 'OFFSET'.", server: "DATAAPPLICATION", procedure: "", line: 1 }) })
  prisma:engine       at BinaryEngine.graphQLToJSError (C:\Work\me-rights-complain\node_modules\@prisma\client\runtime\index.js:29974:14)
  prisma:engine       at BinaryEngine.request (C:\Work\me-rights-complain\node_modules\@prisma\client\runtime\index.js:29857:24)
  prisma:engine       at processTicksAndRejections (internal/process/task_queues.js:97:5)
  prisma:engine       at cb (C:\Work\me-rights-complain\node_modules\@prisma\client\runtime\index.js:36344:26)
  prisma:engine       at createNews (C:\Work\me-rights-complain\mom.ts:8:5)
  prisma:engine       at seed (C:\Work\me-rights-complain\mom.ts:5:5) {
  prisma:engine     clientVersion: '2.29.1'
  prisma:engine   }
  prisma:engine }  
```

## Client Snippet
```ts
await prisma.tb_ComplaintJob.create({
        data: {
            ComplaintJobID: 'Test',
        },
    });
```

## Schema
```prisma

model tb_ComplaintJob {
  ID                   BigInt    @id @default(autoincrement())
  ComplaintJobID       String?   @db.VarChar(10)
  Title                String?   @db.VarChar(500)
  Contact_FirstName    String?   @db.VarChar(200)
  Contact_LastName     String?   @db.VarChar(200)
  Contact_HomeNo       String?   @db.VarChar(50)
  Contact_Moo          String?   @db.VarChar(50)
  Contact_Soi          String?   @db.VarChar(50)
  Contact_Road         String?   @db.VarChar(100)
  Contact_Subdistrict  String?   @db.VarChar(100)
  Contact_District     String?   @db.VarChar(100)
  Contact_Province     String?   @db.VarChar(100)
  Contact_Zipcode      String?   @db.VarChar(10)
  Contact_Phone        String?   @db.VarChar(20)
  Contact_Email        String?   @db.VarChar(50)
  ComplaintType        String?   @db.VarChar(156)
  IsValid              Boolean?
  InvalidRemark        String?   @db.VarChar(100)
  IsConfidential       Boolean?
  ResponsibleBy        String?   @db.VarChar(50)
  CreateBy             String?   @db.VarChar(50)
  CreateDate           DateTime? @db.DateTime
  UpdateBy             String?   @db.VarChar(50)
  UpdateDate           DateTime? @db.DateTime
  ComplaintState       String?   @db.VarChar(50)
  RNo                  String?   @db.VarChar(100)
  RTo                  String?   @db.VarChar(200)
  RReason              String?   @db.Text
  RObjective           String?   @db.Text
  RSum                 String?   @db.Text
  RDate                DateTime? @db.DateTime
  RAttachment          String?   @db.Text
  Contact_Country      String?   @db.VarChar(255)
  PrintDate            DateTime? @db.DateTime
  ContactSubdistrictId Int?
  ContactDistrictId    Int?
  ContactProvinceId    Int?
  InvalidRemarkId      Int?
  IsCancel             Boolean?
}
```

**Comment by kawin-pk** [comment] 2021-08-19 14:31
Prisma Find without  skip, take work fine, when using skip, take will always face the same error( Incorrect syntax near 'OFFSET' )

**Comment by pantharshit00** [comment] 2021-08-24 14:07
Hey can you please tell us what you passing in skip? I wasn't able to reproduce this. 

If you can give us the exact query which is failing, that would be awesome.

**Comment by brnyza** [comment] 2022-01-27 16:25
'OFFSET' only works with SQL Server 2012 or above.

**Comment by pantharshit00** [comment] 2022-06-02 12:43
Looks like you need to upgrade your SQL Server instance here OP. I will close this now.

**Closed by pantharshit00** 2022-06-02 12:43 UTC
Labels: bug/0-unknown, kind/bug, topic: sql server, team/client, topic: basic error report
