### ISSUE TITLE
Loss of precision on Float fields

### ISSUE THREAD

**Issue by esistgut** [prisma/prisma#2903] opened 2020-07-01 12:01 UTC
## Bug description

I have a `price Float @default(0)` field and while the value stored in the database row (postgres) is `0.69` the value returned by the prisma client is `0.6900000000000001` (this is a `console.log` on the output of `.findMany`)

## Environment & setup

- OS: ArchLinux
- Database: PostgreSQL
- Prisma version: 2.1.3
- Node.js version: 12.17

**Comment by pantharshit00** [comment] 2020-07-02 18:03
I can reproduce this we do lose precision. 

![image](https://user-images.githubusercontent.com/22195362/86394420-2fcc1980-bcbc-11ea-87ed-b733076e6759.png)


Reproduction:
1. Bootstrap the following schema using migrate(`npx prisma migrate save --experimental && npx prisma migrate up --experiemental`)
```prisma
generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

model Testing {
  id String @id @default(cuid())
  name String
  price Float @default(0)
}
```

2. Run the following query:
```ts
import { PrismaClient } from "@prisma/client";

async function main() {
  const client = new PrismaClient();

  const data = await client.testing.findMany();
  console.log(data);
  client.disconnect();
}

main();
```

**Comment by pimeys** [comment] 2020-07-21 15:56
Confirming this happens on master, and is fixed on the experimental sqlx branch. Maybe should fix it on master now due to sqlx merge taking probably to August/September (after my vacations).

**Comment by esistgut** [comment] 2020-07-21 16:55
Please update this report when you come up with a plan. Our team uses databases to store numbers (prices) and as far as I can tell if this is going to take months we are forced to either rewrite our reading layer using raw queries or remove Prisma altogether.

**Comment by pimeys** [comment] 2020-07-21 17:29
Fix is done. Merging when reviewed and tests are green. You can read what was the issue from the PR.

**Closed** 2020-07-22 07:56 UTC
Labels: bug/2-confirmed, kind/bug, team/engines, topic: floating point types

**Comment by janpio** [comment] 2020-07-22 08:54
This was released in `dev` as `2.4.0-dev.1` @esistgut - can you install that version and test it out if this fixes your problem? 

If so, this will be included in `2.4.0` on Tuesday in two weeks. But you can also keep using this version in production, as it is identical to the `2.3.0 we released yesterday with only this additional change, so no other side effects are possible technically.

**Comment by esistgut** [comment] 2020-07-22 11:47
I deployed it to our staging environment. Everything seems to be ok. Should I find anything wrong I'll keep you posted.

**Comment by shanmukhm** [comment] 2020-11-12 14:02
This bug is appearing again in version 2.11.0

**Comment by pantharshit00** [comment] 2020-11-12 14:44
@shanmukhm Please open a new issue with a minimal reproduction. Thanks!
