### ISSUE TITLE
Non-model types for e.g. JSON columns for added type safety

### ISSUE THREAD

**Issue by saevarb** [prisma/prisma#6583] opened 2021-04-14 19:15 UTC
## Problem

Currently, in our schema, we can define models which are translated to database tables. In some cases, using JSON in our models can be a useful compromise to avoid an explosion in table count(and other issues) while implementing something like union types.

However, when using this approach in Prisma, it is unfortunately not possible to impose any type-level restrictions on the structure of the JSON object inside such a column, and we are forced to maintain such types in the API layer(in my case, using GraphQL, using nexus).

## Suggested solution

Being able to define types in our schema which we can then use for JSON columns, which are then *only* used for additional type-safety in typescript would be super useful. That is, I don't think there needs to be any kind of actual validation performed by prisma. The idea is just that we are able to propagate type information all the way from the schema, and that way we will be able to maintain integrity without having to perform actual structural validation, as well as keeping all the flexibility afforded to us by storing JSON.

**Comment by pantharshit00** [comment] 2021-04-16 15:43
Hi,

Thanks for reporting this! It has already been reported before, so I am going to close this as a duplicate of https://github.com/prisma/prisma/issues/5449

**Closed by pantharshit00** 2021-04-16 15:43 UTC
