### ISSUE TITLE
called `Option::unwrap()` on a `None` value

### ISSUE THREAD

**Issue by tjbarrett42** [prisma/prisma#24760] opened 2024-07-11 00:21 UTC
Hi Prisma Team! My Prisma Client just crashed. This is the report:
## Versions

| Name            | Version            |
|-----------------|--------------------|
| Node            | v18.20.4           | 
| OS              | darwin-arm64       |
| Prisma Client   | in-memory          |
| Query Engine    | 2804dc98259d2ea960602aca6b8e7fdc03c1758f|
| Database        | mongodb            |

## Logs
```
prisma:client:libraryEngine sending request, this.libraryStarted: false
prisma:client:libraryEngine library starting
prisma:client:libraryEngine sending request, this.libraryStarted: false
prisma:client:libraryEngine library already starting, this.libraryStarted: false
prisma:client:libraryEngine library started
```

## Client Snippet
```ts
// PLEASE FILL YOUR CODE SNIPPET HERE
```

## Schema
```prisma
// PLEASE ADD YOUR SCHEMA HERE IF POSSIBLE
```

## Prisma Engine Query
```
{"X":true}}}
```

**Comment by jkomyno** [comment] 2024-07-12 09:14
Hi @tjbarrett42 and @Elliott-Chong, we'd like to help investigate this issue, but we need to know at least the `@prisma/client` snippet that caused this, the Prisma Client version, and the Prisma schema.
Ideally, you can provide a self-contained reproduction repo to speed things up on our side.

Without that information, we won't be able to proceed. Thanks

**Comment by josiahwiebe** [comment] 2024-07-12 20:44
Same issue here. Here's a couple of snippets:

**Prisma Schema:**
```prisma
model Lesson {
  id          String      @id @default(auto()) @map("_id") @db.ObjectId
  v           Int         @default(0) @map("__v") @ignore
  active      Boolean
  courseSlug  String      @map("course")
  course      Course      @relation(fields: [courseSlug], references: [slug])
  createdAt   DateTime    @db.Date
  duration    Int?        @db.Int
  meta        LessonsMeta
  publishedAt DateTime    @db.Date
  slug        String      @unique
  stream      String
  title       String
  value       Int         @db.Int
  results     Result[]

  @@index([stream], map: "stream")
  @@map("lessons")
}
```

**Client snippet:**
```js
import { PrismaClient } from '@prisma/client'

let prisma
if (typeof window === 'undefined') {
  if (process.env.NODE_ENV === 'production') {
    prisma = new PrismaClient()
  } else {
    if (!global.prisma) {
      global.prisma = new PrismaClient()
    }
    prisma = global.prisma
  }
}

export default prisma
```

**Query:**
```js
const lesson = await prisma.lesson.findUnique({ where: { slug: slug }, include: { course: true } })
```

This is using `prisma@5.16.2` and `@prisma/client@5.16.2`. These issues were not present in `5.5.2`.

**Comment by jkomyno** [comment] 2024-07-15 09:58
Hi @josiahwiebe, unfortunately the snippet you posted isn't enough to reproduce this issue. Please:
- Post a self-contained reproduction
- Post a valid schema (`prisma validate` needs to show a message like `The schema at prisma/schema.prisma is valid 🚀`)
- In your Client Snippet, please include the minimal amount of queries necessary to populate the database and trigger the crash

Thanks!

---

This is what I have attempted so far with Prisma `5.16.2`, resulting in no crash:
- `prisma/schema.prisma`:
  ```prisma
  generator client {
    provider = "prisma-client-js"
  }
  
  datasource db {
    provider = "mongodb"
    url      = env("TEST_MONGO_URI")
  }
  
  model Lesson {
    id          String      @id @default(auto()) @map("_id") @db.ObjectId
    active      Boolean
    courseSlug  String      @map("course")
    course      Course      @relation(fields: [courseSlug], references: [slug])
    createdAt   DateTime    @db.Date
    duration    Int?        @db.Int
    publishedAt DateTime    @db.Date
    slug        String      @unique
    stream      String
    title       String
    value       Int         @db.Int
  
    @@index([stream], map: "stream")
    @@map("lessons")
  }
  
  model Course {
    id          String      @id @default(auto()) @map("_id") @db.ObjectId
    active      Boolean
    createdAt   DateTime    @db.Date
    description String
    duration    Int?        @db.Int
    lessons     Lesson[]
    publishedAt DateTime    @db.Date
    slug        String      @unique
    title       String
    value       Int         @db.Int
  
    @@map("courses")
  }
  ```

- `src/index.ts`
  ```typescript
  import { PrismaClient } from '@prisma/client'
  
  async function main() {
    const prisma = new PrismaClient()
  
    const slug = ''
    const lesson = await prisma.lesson.findUnique({
      where: {
        slug,
      },
      include: {
        course: true,
      },
    })
  
    console.log(lesson)
    // ^^ `null`
  }
  
  void main().catch((e) => {
    console.log(e.message)
    process.exit(1)
  })
  ```

**Comment by jkomyno** [comment] 2024-08-08 09:42
Hi @josiahwiebe, any news on https://github.com/prisma/prisma/issues/24760#issuecomment-2228123711? Without further input anytime soon, I'm afraid we'll have to close this issue (you may still leave comments once the issue is closed, to potentially prompt us to re-open it). Thanks!

**Comment by SevInf** [comment] 2024-10-15 15:13
Hey @josiahwiebe ,
 

With the lack of information and our inability to reproduce this issue, we're now closing it. Feel free to comment if you have any updates about it.
 
Thank you 🙏

**Closed by SevInf** 2024-10-15 15:13 UTC
Labels: bug/0-unknown, kind/bug, domain/client, topic: rust panic, topic: query-crash
