### ISSUE TITLE
Update queries broken for with optional String columns

### ISSUE THREAD

**Issue by langal** [prisma/prisma#3653] opened 2020-09-14 21:54 UTC
## Bug description

"XXXOperationsInput" seems to have replaced primitive string types when going from 2.5.1 to 2.6.2.   For example,

 type StringFieldUpdateOperationsInput = {
  set?: string
}

is now the defined type instead of just "string".   This forces the clients to make many refactoring changes to get previously working queries to function.

## How to reproduce

1. Create a schema that includes an optional String field:

```
model User {
  id Int @default(autoincrement()) @id
  phone String? @unique

  @@map("users")
}
```

2. run the following query:

```
const PrismaClient = require('@prisma/client').PrismaClient

const prisma = new PrismaClient();
prisma.user.update({
	where: {
		id: 1,
	},
	data: {
		phone: '1231231231',
	},
}).then(() => {}, (err) => { console.log(err) });
```

3. note error:

```

Argument phone: Got invalid value '1231231231' on prisma.updateOneUser. Provided String, expected NullableStringFieldUpdateOperationsInput:
type NullableStringFieldUpdateOperationsInput {
  set?: String
}
```

## Expected behavior

The update query should work fine with just a string parameter as the new phone number.

## Environment & setup

- OS: Debian
- Database: PostgresQL
- Node.js version: 14.3
- Prisma version:
```
@prisma/cli          : 2.6.2
Current platform     : debian-openssl-1.1.x
Query Engine         : query-engine 6a8054bb549e4cc23f157b0010cb2e95cb2637fb (at node_modules/@prisma/cli/query-engine-debian-openssl-1.1.x)
Migration Engine     : migration-engine-cli 6a8054bb549e4cc23f157b0010cb2e95cb2637fb (at node_modules/@prisma/cli/migration-engine-debian-openssl-1.1.x)
Introspection Engine : introspection-core 6a8054bb549e4cc23f157b0010cb2e95cb2637fb (at node_modules/@prisma/cli/introspection-engine-debian-openssl-1.1.x)
Format Binary        : prisma-fmt 6a8054bb549e4cc23f157b0010cb2e95cb2637fb (at node_modules/@prisma/cli/prisma-fmt-debian-openssl-1.1.x)
Studio               : 0.272.0
Preview Features     : connectOrCreate, transactionApi
```

**Comment by pantharshit00** [comment] 2020-09-15 08:54
I am unable to reproduce this with `2.6.2`

Can you please make sure that you ran `npx prisma generate` after you upgrade? Try deleting the node_modules once and retrying it.

**Comment by HumbertoAriza** [comment] 2020-09-17 01:56
I'm almost ready to send an app to production but all the updates are f***ed up without update any version of prisma or anything because this new version. Expected type NullableStringFieldUpdateOperationsInput to be an object.
Do you know how versions work? if i dont upgrade should still work but well it does not.
There is also the change from first to take without advertisement, also a lot of time lost changing stuff.

**Comment by janpio** [comment] 2020-09-17 07:47
I unfortunately do not follow what you are telling us @HumbertoAriza. 
Do you also have the same problem that @langal describes in this issue? If so, can you help us reproduce it? @pantharshit00 could not with 2.6.2 of Prisma.
If you have other, additional problems, please open an additional issue so we can look into it. An existing issue unfortunately makes this very hard to keep the different things apart. Thanks.

**Comment by HumbertoAriza** [comment] 2020-09-17 15:18
I just clone my repo 
"@prisma/client": "^2.0.0"
 "@prisma/cli": "^2.5.1"
and install and all the fields in update mutations needs a set to be change.

type User{ 
id Int@id
name String
}
`
prisma.user.update({
	where: {
		id: 1,
	},
	data: {
		name: {set: "kajdaksjd"},
	},
}).then(() => {}, (err) => { console.log(err) });
`

**Comment by langal** [comment] 2020-09-17 15:20
Upgraded to 2.7 and an having no troubles.  Normal strings work now as arguments . thanks!

**Comment by HumbertoAriza** [comment] 2020-09-17 15:24
if nothing was updated why is broken, if i get to production this could be a problem

**Comment by HumbertoAriza** [comment] 2020-09-17 15:28
Just updated the package to 
  @prisma/client: ^2.7.1
 @prisma/cli:"^2.7.1
and all my update inputs still looking like this
```
input UserUpdateInput {
  active: BoolFieldUpdateOperationsInput
  activeAccount: BoolFieldUpdateOperationsInput
  activeCode: NullableStringFieldUpdateOperationsInput
  address: AddressUpdateOneWithoutUserInput
  age: NullableIntFieldUpdateOperationsInput
}
```

**Comment by janpio** [comment] 2020-09-17 17:21
Thanks @langal - seems your problem is solved then.

@HumbertoAriza: Please open a new bug issue with all information it asks for and we are happy to help you debug.

**Comment by pantharshit00** [comment] 2020-09-18 11:27
Ok, I am going to close this issue as original author's problem is solved.

@HumbertoAriza Please open a new issue with a minimal reproduction.

**Closed by pantharshit00** 2020-09-18 11:27 UTC
Labels: 2.6, bug/0-needs-info, kind/bug
