### ISSUE TITLE
Difficult to read error report

### ISSUE THREAD

**Issue by adrianoresende** [prisma/prisma#2153] opened 2020-04-10 02:44 UTC
## Bug description

I'm with difficult to read an error report from GraphQL Playground with **Prisma v2** + **Apollo Server**

With `debug="*"` on `.env` or `log: ['query', 'info', 'warn']` in `PrismaClient` don't display the same the error on terminal, only shown on GraphQL Playgroud (localhost:4000).

![image](https://user-images.githubusercontent.com/798755/78956917-36cafd80-7aba-11ea-862a-719c393e319e.png)

OBS: With generated updated

## How to reproduce

1. Use type (side Apollo Server) with attribute that don't exist on model (Prisma).
2. Run mutation

Example:
schema.graphql (Apollo Server)
```gql
type User {
  id: ID!
  name: String!
  email: String
  pwd: String!
  updatedAt: String!
  createdAt: String!
}
```
schema.prisma (Prisma)
```gql
model User {
  id        String @id @default(uuid())
  email     String @unique
  name      String
  password  String
  createdAt DateTime @default(now())
  updatedAt DateTime @updatedAt
}
```

## Expected behavior

Show error decoded and readable

## Prisma information

`npm installed`
```json
"devDependencies": {
    "@babel/cli": "^7.8.4",
    "@babel/core": "^7.9.0",
    "@babel/node": "^7.8.7",
    "@babel/polyfill": "^7.8.7",
    "@babel/preset-env": "^7.9.0",
    "@babel/register": "^7.9.0",
    "@prisma/cli": "^2.0.0-beta.1",
    "babel-plugin-transform-object-rest-spread": "^6.26.0",
    "nodemon": "^2.0.2"
  },
  "dependencies": {
    "@prisma/client": "^2.0.0-beta.1",
    "apollo-server": "^2.11.0",
    "bcryptjs": "^2.4.3",
    "env-cmd": "^10.1.0",
    "graphql": "^15.0.0",
    "graphql-binding": "^2.5.2",
    "graphql-import": "^1.0.1",
    "jsonwebtoken": "^8.5.1"
  }
```

`server.js`
```js
import { ApolloServer } from 'apollo-server'
import { PrismaClient } from '@prisma/client'
import { resolvers } from './resolvers/index'
import { importSchema } from 'graphql-import'

const typeDefs = importSchema('./src/schema.graphql')

const prisma = new PrismaClient()

const server = new ApolloServer({
  typeDefs,
  resolvers,
  context({ req }) {
    return {
      prisma,
      request: req,
    }
  },
  playground: process.env.NODE_ENV === 'development',
  debug: process.env.NODE_ENV === 'development',
})

export { server as default, prisma }
```

## Environment & setup

- OS: 10.15.4 macOS
- Database: PostgreSQL
- Prisma version: 2.0.0-beta.1
- Node.js version: v13.3.0

**Comment by adrianoresende** [comment] 2020-04-11 00:34
In Studio has the same behavior:
if you write:

```js
prisma.user.findMany({
  where: {
    body: true
  }
})
```

In terminal show unicoded:
![image](https://user-images.githubusercontent.com/798755/79031073-d2b84000-7b72-11ea-885f-b15b6fc183da.png)

**Comment by pantharshit00** [comment] 2020-04-15 11:51
Looks like `errorFormat: "minimal"` (https://www.prisma.io/docs/reference/tools-and-interfaces/prisma-client/error-formatting) which is the default now is getting ignored by the client and it is throwing a full-blown ANSI formatted error which is pretty to display on a terminal but it is ugly to look at when converted into a plain string. 

![image](https://user-images.githubusercontent.com/22195362/79334099-4eccd200-7f3d-11ea-9144-1a5c5c6c6d71.png)

Script to reproduce: 
```prisma
const { PrismaClient } = require("@prisma/client");

const prisma = new PrismaClient({
  errorFormat: "minimal",
});

async function main() {
  const something = await prisma.user.create({
    data: {},
  });
  console.log(something);
}

main();
```

Datamodel:
```prisma
datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

generator client {
  provider = "prisma-client-js"
}

model User {
  id String @id @default(cuid())
  name String
}
```

**Comment by adrianoresende** [comment] 2020-04-15 19:39
Thanks! 
Fixed with `errorFormat: "minimal"`

**Comment by pantharshit00** [comment] 2020-04-16 13:47
Awesome, but this really should be the default behaviour now so I am going to keep this issue open :)

**Comment by adrianoresende** [comment] 2020-04-21 03:53
Really has bug, I code wrong `findOne({ id: args.id })` and get log thus:
![image](https://user-images.githubusercontent.com/798755/79823575-82a75d80-836a-11ea-8be1-ee06bf5c3f8b.png)

**Comment by timsuchanek** [comment] 2020-04-29 17:22
Thanks a lot for reporting 🙏
This issue is fixed in the latest alpha version of `@prisma/cli`.
You can try it out with `npm i -g @prisma/cli@alpha`.

In case it’s not fixed for you - please let us know and we’ll reopen this issue!

**Closed by timsuchanek** 2020-04-29 17:22 UTC
Labels: bug/2-confirmed, kind/bug, team/typescript, topic: errors
