### ISSUE TITLE
Prisma migrate: formatting failure

### ISSUE THREAD

**Issue by EliseuCS** [prisma/prisma#15351] opened 2022-09-15 21:07 UTC
Hi Prisma Team! Prisma Migrate just crashed. 

## Command

`format`

## Versions
      
| Name        | Version            |
|-------------|--------------------|
| Platform    | windows            | 
| Node        | v18.8.0            | 
| Prisma CLI  | 3.15.2             | 
| Engine      | 461d6a05159055555eb7dfb337c9fb271cbd4d7e| 

## Error
```
Error: Command failed with exit code 101: C:\Users\lilli\OneDrive\Documentos\GitHub\Mecprog\BackEnd\node_modules\@prisma\engines\prisma-fmt-windows.exe format -i C:\Users\lilli\OneDrive\Documentos\GitHub\Mecprog\BackEnd\prisma\schema.prisma
```

**Comment by jkomyno** [comment] 2022-09-16 07:58
Hi @EliseuCS, we are aware of a few `prisma format` issues in `prisma@3.15.2`, which we have already solved in more recent versions.

Would you please post your schema file here, and try running `prisma format` using `prisma@4.3.1` instead?

**Comment by janpio** [comment] 2024-05-16 09:34
@EliseuCS Did you see Alberto's comment? Without the schema to be able to reproduce the problem, we will not be able to do anything here.

**Comment by jkomyno** [comment] 2024-05-16 13:34
Also, as of `prisma@5.14.0`, there is no known way in which `prisma format` or `prisma validate` - or their internal validation commands used by `prisma migrate` - can crash. I think we can close this issue @janpio.

**Comment by jkomyno** [comment] 2024-05-17 12:12
Hi @EliseuCS, since we got no reply with information that could help us reproducing this issue, and we believe this problem has been solved many Prisma versions ago, we're closing this issue.
Should you or another user bump into the same problem and provide a reproduction, we will consider reopening this issue. Thanks!

**Closed by jkomyno** 2024-05-17 12:12 UTC
Labels: bug/0-unknown, kind/bug, topic: prisma format, team/schema
