### ISSUE TITLE
Foreign key constraint failed when using createMany

### ISSUE THREAD

**Issue by ssantoshp** [prisma/prisma#20659] opened 2023-08-11 14:34 UTC
### Bug description

I have a single CSV file with a primary key column, and the remaining columns divided into distinct tables. All the tables except my Product table use this shared key column as the foreign constraint. I am using batch since I have a lot of data and it does achieve to push around 8 batches (1 batch = 100 records) but then stops working. 

My script iterates over my CSV at the same time for all 3 tables. Once my batches are ready (size of 100), I make sure to push my Product batch first and then the other table (price and quantity) that have a foreign constraints.

So I am not really sure why it manages to pass so much records but then fail at one particularly. I tried a smaller batch to narrow down the data and see which record could be the source of the problem but the key column does exist for each of those records and should have no issue being passed. 

I am suspecting that the script silently fail to actually push some record to the Product table of my database. Last time I ran the script (database was empty), it worked well but after retrieving a dump and comparing it with my inital file I noticed that around 130 rows (among 400k) have not been pushed. Let me know if that makes sense or if something is wrong with my code/schema.

The error is a classical Prisma foreign key error:
```
PrismaClientKnownRequestError:
Invalid `prisma.quantity.createMany()` invocation in
C:\Users\santosh.passoubady\Desktop\work\code\ProjectPipelineV2\push_to_db\push_main.ts:29:51

  26   skipDuplicates: true,
  27 });
  28
→ 29 const upsertPartQty = await prisma.quantity.createMany(
Foreign key constraint failed on the field: `(not available)`
    at Rn.handleRequestError (C:\Users\santosh.passoubady\Desktop\work\code\ProjectPipelineV2\push_to_db\node_modules\@prisma\client\runtime\library.js:174:7325)
    at Rn.handleAndLogRequestError (C:\Users\santosh.passoubady\Desktop\work\code\ProjectPipelineV2\push_to_db\node_modules\@prisma\client\runtime\library.js:174:6754)
    at Rn.request (C:\Users\santosh.passoubady\Desktop\work\code\ProjectPipelineV2\push_to_db\node_modules\@prisma\client\runtime\library.js:174:6344) {
  code: 'P2003',
  clientVersion: '4.16.2',
  meta: { field_name: '(not available)' }
}
```

### How to reproduce

My schema and script are below. 

### Expected behavior

Ideally, there would be no problem pushing data to all 3 tables into the same script if they were done sequentially: first the product table and then the tables that depend on the product table for their foreign constraint. 

### Prisma information

```prisma
generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "cockroachdb"
  url      = env("DATABASE_URL")
}

model Product {
  id        BigInt      @id @default(autoincrement())
  key       String     @unique // foreign key
  dummycol  String?      @unique
  Price    Price[]
  Quantity Quantity[]
}

model Price {
  id        BigInt   @id @default(autoincrement())
  keyPrice  String
  quantity  Int
  price     Int
  timestamp DateTime
  product   Product  @relation(fields: [keyPrice], references: [key], onDelete: Cascade, onUpdate: Cascade)

  @@unique([keyPrice, timestamp, price, quantity])
}

model Quantity {
  id        BigInt   @id @default(autoincrement())
  keyQty    String
  quantity  Int     
  timestamp DateTime
  product   Product  @relation(fields: [keyQty], references: [key], onDelete: Cascade, onUpdate: Cascade)

  @@unique([keyQty, timestamp])
}

```

My script:
```ts
import { PrismaClient, Prisma } from "@prisma/client";
import {
    ProductColumnMapping,
    qtyColumnMapping,
    priceColumnMapping,
  } from "./mapping"; // those maps columns of the CSV to the fields of the Prisma models
const prisma = new PrismaClient();

const csv = require("csv-parser");
const fs = require("fs");
const path = require("path")

const results: any[] = [];

async function pushBatches(
  batchProduct: Record<string, any>[],
  batchQty: Record<string, any>[],
  batchPrice: Record<string, any>[]
) {

  try {
      const upsertPartProduct = await prisma.partNumber.createMany({
        data: batchProduct as Prisma.Enumerable<Prisma.PartNumberCreateManyInput>,
        skipDuplicates: true,
      });

      const upsertPartQty = await prisma.quantity.createMany({
        data: batchQty as Prisma.Enumerable<Prisma.QuantityCreateManyInput>,
        skipDuplicates: true,
      });

      const upsertPartPrice = await prisma.price.createMany({
        data: batchPrice as Prisma.Enumerable<Prisma.PriceCreateManyInput>,
        skipDuplicates: true,
      });

  } catch (error: any) {
      console.log(error);
      process.exit(1);
  }
}

const parentDir = path.join(__dirname, '..'); // Go one level up to the parent directory

async function Product() {
  const csvFilePath = path.join(parentDir, 'orm_ready', 'Product_data.csv'); // CSV from which I am getting all the data
  fs.createReadStream(csvFilePath)
    .pipe(csv())
    .on("data", (data: any) => results.push(data))
    .on("end", async () => {
            
      let batchCount = 0;
      let batchProduct = [];
      let batchQty = [];
      let batchPrice = [];
     
      for (const result of results) {        // iterate over the records of the CSV
        const recordProduct: Record<string, any> = {};
        const recordQty: Record<string, any> = {};
        const recordPrice: Record<string, any> = {};

        for (const column in result) {        // iterate over the columns of the record
          if (result[column] === "-") continue;

          if (column in ProductColumnMapping) {        // check if the column is one of the fields for the Product table
            const field = ProductColumnMapping[column];
            if (field[1] === "Int") {
              recordProduct[field[0]] = parseInt(result[column]);  // explicitly convert to int
            } else {
              recordProduct[field[0]] = result[column];        // string by default
            }
          }

          if (column in qtyColumnMapping) {  // check if the column is one of the fields for the quantity table
            const field = qtyColumnMapping[column];
            if (field[1] === "Int") {
              recordQty[field[0]] = parseInt(result[column]);  // explicitly convert to int
            } else if (field[1] === "DateTime") { 
              recordQty[field[0]] = new Date(result[column]);  // explicitly convert to date
            } else {
              recordQty[field[0]] = result[column];         // string by default
            }
          }

          if (column in priceColumnMapping) {  // check if the column is one of the fields for the price table
            const field = priceColumnMapping[column];
            if (field[1] === "Int") {
              recordPrice[field[0]] = parseInt(result[column]);
            } else if (field[1] === "DateTime") {
              recordPrice[field[0]] = new Date(result[column]);
            } else {
              recordPrice[field[0]] = result[column];    // string by default
            }
          }
        }
        
        if (batchProduct.length < 100) {       // push the record to the batch array if size is less than 100
          batchProduct.push(recordProduct);
          batchQty.push(recordQty);
          batchPrice.push(recordPrice);

        } else {        // push the batch to the database if size is >= 100
          console.log(recordProduct);
          await pushBatches(batchProduct, batchQty, batchPrice);
          batchCount = batchCount + 1;
          batchProduct = []; // Reset the batchProduct array
          batchQty = []; // Reset the batchQty array
          batchPrice = []; // Reset the batchPrice array
        }
      }
      await pushBatches(batchProduct, batchQty, batchPrice);
     }
    );
}

Product()
  .then(async () => {
    await prisma.$disconnect();
  })
  .catch(async (e) => {
    console.error(e);
    await prisma.$disconnect();
    process.exit(1);
  });
```

and here is what my `mapping.ts` looks like:

```ts
  export const  productColumnMapping: Record<string, [string, string]> = {
    'Product #': ['key', 'String'],
    'Mfr #': ['dummycol', 'String'],
  };

  export const priceColumnMapping: Record<string, [string, string]> = {
    'Product #': ['keyPrice', 'String'],
    'Quantity': ['quantity', 'Int'],
    'Price (USD)': ['price', 'Int'],
    'Last Updated': ['timestamp', 'DateTime'],
  };

  export const qtyColumnMapping: Record<string, [string, string]> = {
    'Product #': ['keyQty', 'String'],
    'Stock': ['quantity', 'Int'],
    'Last Updated': ['timestamp', 'DateTime'],
  };
```

and finally here is what a MAIN_data.csv (CSV I am passing through Prisma can look like):
```csv
Product #,Mfr #,Quantity,Stock,Price (USD),Last Updated
P1,MFR1,10,50,20.99,2023-08-11
P2,MFR2,25,100,5.49,2023-08-11
P3,MFR3,15,75,12.75,2023-08-11
P4,MFR1,8,40,32.00,2023-08-11
P5,MFR4,30,120,8.95,2023-08-11
```

### Environment & setup

- OS: Windows
- Database: CockroachDB
- Node.js version: v18.16.0

### Prisma Version

```
v4.16.2
```

**Comment by Jolg42** [comment] 2023-08-14 07:39
(I'm not sure if that's the issue here)
The arrays are passed by reference and mutated, passing a clone of these would be safer like.
```
...
        } else {        // push the batch to the database if size is >= 100
          console.log(recordProduct);
          await pushBatches(structuredClone(batchProduct), structuredClone(batchQty), structuredClone(batchPrice));
          batchCount = batchCount + 1;
          batchProduct = []; // Reset the batchProduct array
          batchQty = []; // Reset the batchQty array
          batchPrice = []; // Reset the batchPrice array
        }
      }
      await pushBatches(structuredClone(batchProduct), structuredClone(batchQty), structuredClone(batchPrice));
```
See https://developer.mozilla.org/en-US/docs/Web/API/structuredClone

**Comment by Jolg42** [comment] 2023-08-14 07:41
We would need a minimal reproduction to be able to allocate time on this.
Could you try creating one where you can also provide a "small" `csv` so we can run the code and reproduce this?

**Comment by ssantoshp** [comment] 2023-08-14 10:22
Hey thanks I will try this and send a minimal reproduction by the end of the day!

**Comment by ssantoshp** [comment] 2023-08-14 13:43
Just added you as a collaborator in a private repo where you can see a minimal reproduction. Let me know if I need to add other people. Is that okay to work this way since my csv contains some sensitive data?

**Comment by Jolg42** [comment] 2023-08-14 14:32
Thanks! I got it, I'll try to allocate some time to attempt a reproduction based on this in the next couple of days.

**Comment by ssantoshp** [comment] 2023-08-14 15:06
Awesome, thank you so much :))

**Comment by ssantoshp** [comment] 2023-08-17 14:45
Hey, any updates? I am trying to make an alternative version on my side in which I push the main table first, get a dump of the main table and filter out my original Price and Quantity CSV files based on what has been pushed to the database. 
Once again I found a discrepancy of ~240 products (in the original CSV file that was pushed to main but not in the dump) that have not been pushed properly to the database (for 400k rows pushed).

**Comment by Jolg42** [comment] 2023-08-23 14:45
I tried the reproduction https://github.com/ssantoshp/prisma-bug

But I had to stop because I encountered quite a few problems along the way
```
npx prisma migrate dev
```
Failed with
```
Applying migration `20230704140745_init`
Applying migration `20230704194435_init`
Applying migration `20230704194917_init`
Applying migration `20230714150203_1689346911`
Error: P3018

A migration failed to apply. New migrations cannot be applied before the error is recovered from. Read more about how to resolve migration issues in a production database: https://pris.ly/d/migrate-resolve

Migration name: 20230714150203_1689346911

Database error code: XXUUU

Database error:
ERROR: there is no transaction in progress

DbError { severity: "ERROR", parsed_severity: Some(Error), code: SqlState(Other("XXUUU")), message: "there is no transaction in progress", detail: None, hint: None, position: None, where_: None, schema: None, table: None, column: None, datatype: None, constraint: None, file: Some("exec_util.go"), line: Some(741), routine: Some("init") }
```
I had to remove the `COMMIT;` from the failing migration.

Then `npx ts-node push_main.ts` failed with
```
PrismaClientKnownRequestError: 
Invalid `prisma.partNumber.createMany()` invocation in
/Users/j42/Repros/20659/push_to_db/push_main.ts:24:54

  21 ) {
  22 
  23   try {
→ 24       const upsertPartMain = await prisma.partNumber.createMany(
The column `isMarketplace` does not exist in the current database.
    at Rn.handleRequestError (/Users/j42/Repros/20659/push_to_db/node_modules/@prisma/client/runtime/library.js:174:7325)
    at Rn.handleAndLogRequestError (/Users/j42/Repros/20659/push_to_db/node_modules/@prisma/client/runtime/library.js:174:6754)
    at Rn.request (/Users/j42/Repros/20659/push_to_db/node_modules/@prisma/client/runtime/library.js:174:6344) {
  code: 'P2022',
  clientVersion: '4.16.2',
  meta: { column: 'isMarketplace' }
}
```

So I used `npx prisma db push` instead but that failed too, this time with
```
Argument `totalPrice`: Invalid value provided. Expected Float, provided Enum.
    at vn (/Users/j42/Repros/20659/push_to_db/node_modules/@prisma/client/runtime/library.js:167:1288)
    at Rn.handleRequestError (/Users/j42/Repros/20659/push_to_db/node_modules/@prisma/client/runtime/library.js:174:7065)
    at Rn.handleAndLogRequestError (/Users/j42/Repros/20659/push_to_db/node_modules/@prisma/client/runtime/library.js:174:6754)
    at Rn.request (/Users/j42/Repros/20659/push_to_db/node_modules/@prisma/client/runtime/library.js:174:6344)
```

**Comment by Jolg42** [comment] 2023-08-23 14:46
A more minimalistic reproduction would help.

**Comment by janpio** [comment] 2023-10-29 21:12
@ssantoshp Did you see Joel's feedback on your reproduction? We would love to be able to continue here - but need your help. Thanks.

**Comment by millsp** [comment] 2023-11-07 01:03
Hey @ssantoshp, without your input we cannot move this issue forward, so I am closing it. Please provide us with the missing information so we understand how to treat this, and we will happily re-open it.

**Closed by millsp** 2023-11-07 01:03 UTC
Labels: bug/0-unknown, kind/bug, topic: relations, team/client, topic: createMany(), topic: cockroachdb, topic: foreign keys
