### ISSUE TITLE
`Error in migration engine: Starting migration engine RPC server`

### ISSUE THREAD

**Issue by janpio** [prisma/prisma#8218] opened 2021-07-11 12:29 UTC
This is some new error string that is being output when the Migration engine is encountering errors. It recently started to pop up and now also shows up in issues reported by users: https://github.com/prisma/prisma/issues?q=%22Error+in+migration+engine%3A+Starting+migration+engine+RPC+server%22+

**Comment by pantharshit00** [comment] 2021-07-11 20:16
Any reproduction? The search results mostly shows closed issues.

**Comment by janpio** [comment] 2021-07-11 23:52
https://github.com/prisma/prisma/issues/8212#issuecomment-877773918 was the one that triggered this, but I also saw it a few times during reproductions. When I hit it again, will update here.

**Comment by tomhoule** [comment] 2021-07-12 05:48
I noticed that. It's almost certainly caused by https://github.com/prisma/prisma/pull/7620 and should be fixed by https://github.com/prisma/prisma/pull/8075

**Comment by Jolg42** [comment] 2021-07-29 10:00
Closing, will reopen if can be reproduced

**Closed by Jolg42** 2021-07-29 10:00 UTC
Labels: bug/0-needs-info, kind/bug, team/migrations, topic: migrate
