### ISSUE TITLE
I get "Can't resolve '_http_common'" when I use NestJS with monorepo (webpack)

### ISSUE THREAD

**Issue by kvandake** [prisma/prisma#6899] opened 2021-05-03 09:35 UTC
## Bug description

When I try to composite Prisma with [NestJS monorepo](https://docs.nestjs.com/cli/monorepo#monorepo-mode) project I get the error. I can`t use default prisma client output path because my projects use prisma client and each project overrides before generated client files. I try to use custom output path but I get the error. I found some information about the error -> https://github.com/restify/node-restify/issues/794.

## How to reproduce

1. Create new app as [monorepo project](https://docs.nestjs.com/cli/monorepo#monorepo-mode)
2. Generate client in custom output path. For example "output = ../src/prisma/client"
3. Execute command "build"
4. See error "Can't resolve '_http_common'"

## Expected behavior

Build happy project

## Environment & setup

- OS: Mac OS
- Database: PostgreSQL
- Node.js version: 12.22.1
- Prisma version: 2.21.2

```
datasource db {
  provider	=	"postgresql"
  url	=	env("MAIN_DATABASE_URL")
}

generator client {
  provider = "prisma-client-js"
  output = "../src/prisma/client"
}
```

**Comment by pantharshit00** [comment] 2021-05-03 09:39
@kvandake Can you update your node js version once?

**Comment by kvandake** [comment] 2021-05-03 10:43
@pantharshit00  I try to use node **14.16.1** but I get same error. 
I create a project with the bug.
https://github.com/kvandake/prisma-http-common-bug. 
**yarn build:my-app** makes an error "Can't resolve '_http_common'".

**Comment by kvandake** [comment] 2021-05-03 10:55
Node 16 does same error.

**Comment by kvandake** [comment] 2021-05-03 11:03
I excluded _http_common from webpack. The build completed but when I start my project I get an error "_http_common is not defined". I created [new branch **master-webpack**](https://github.com/kvandake/prisma-http-common-bug/tree/master-webpack) for reproduce this case.

**webpack.config.js**
```
module.exports = function(options) {
  return {
    ...options,
    target: 'node',
    externals: [...options.externals, '_http_common']
  };
};
```

**Comment by pantharshit00** [comment] 2021-05-03 11:20
Ok, this looks like known issue https://github.com/prisma/prisma/issues/6564. I will recommend you downgrade while we work on a fix. 

We are waiting for release of v4 of https://github.com/nodejs/undici which will remove the usage of `_http_common` private nodejs module altogether.

**Comment by kvandake** [comment] 2021-05-03 12:45
@pantharshit00  I get same error when I use version 2.18.0.

**Comment by LayneHaber** [comment] 2021-05-17 17:01
> I will recommend you downgrade while we work on a fix

Also seeing this -- are you suggesting a webpack or prisma downgrade?

**Comment by pantharshit00** [comment] 2021-05-18 03:42
@LayneHaber I was suggesting to downgrade node js here to 14 LTS

**Comment by trivigy** [comment] 2021-05-23 07:35
@LayneHaber @kvandake did you happen to find a workaround in the meantime? I tried running with node 14 LTS (per @pantharshit00 recommendation) but getting the same issue.

**Comment by j0hnm4r5** [comment] 2021-05-26 14:29
@trivigy I'm in the same boat as you here — if you manage to find a workaround, please share. And I'll do the same!

**Comment by trivigy** [comment] 2021-05-26 17:10
@j0hnm4r5 Unfortunately I do not know of a workaround and my current solution was to downgrade to prisma `v2.20.0`.

**Comment by millsp** [comment] 2021-05-26 21:19
Here's a temporary workaround. Sorry for the inconvenience, we will upgrade `undici` asap. You might need to exclude `encoding` too, so I'll let you uncomment that if needed.

```ts
module.exports = {
    webpack: (config, {isServer}) => {
        if (isServer) {
            config.externals.push('_http_common');
			// config.externals.push('encoding');
        }
        return config;
    },
    target: 'serverless',
};
```

**Comment by j0hnm4r5** [comment] 2021-05-27 21:10
@millsp that got me closer, but still no cigar. I'm not sure if it's a Prisma, Next-Auth, or my issue at this point though: https://github.com/prisma/prisma/issues/7311

I can import the client okay, and even console.log it perfectly fine before setting the adapter, but once it is in the adapter, those errors start to throw. Any ideas?

**Comment by j0hnm4r5** [comment] 2021-05-28 17:36
@millsp here's a reproduction repo that clearly shows what's going on (with instructions): https://github.com/j0hnm4r5/example-prisma-next-auth-monorepo

I really appreciate all your help!

**Comment by j0hnm4r5** [comment] 2021-06-03 17:42
@millsp any luck, by chance?

**Comment by LayneHaber** [comment] 2021-06-08 03:40
Also sad to report that I didn't find a workaround other than not upgrading prisma or webpack 😢 

But it does look like [v4 of unidici](https://github.com/nodejs/undici/releases) is in release candidate stages

**Comment by belgattitude** [comment] 2021-08-28 21:45
Seems NextJs 11.1.0 / prisma 2.30.0 works out of the box. 

Thanks @gavrichards for testing, see https://github.com/prisma/prisma/issues/6925#issuecomment-907679255

**Comment by ahmadalfy** [comment] 2022-02-25 23:50
Any update on this? I am facing this with version `3.1` as well

**Comment by millsp** [comment] 2022-02-28 12:57
Hey @ahmadalfy, sorry about this. We have a fix ready but that is unfortunately blocked due to [memory leak issues](https://github.com/prisma/prisma/issues/8989). That will need to be prioritized first (and investigated) before we can merge the fix.

**Comment by ahmadalfy** [comment] 2022-03-03 07:09
@millsp thanks for the update, I found a work around because I use Nx so all references to Prisma moved to the library of components instead of the nest application.

**Comment by homoky** [comment] 2022-03-03 07:21
For me is working to get client generated as below:

```
generator client {
  provider        = "prisma-client-js"
  output          = "../../../node_modules/@~internal/prisma"
}
```

Then you can import it from anywhere like:

`import {PrismaClient} from '@~internal/prisma'`

Hope it helps.

**Comment by juanzgc** [comment] 2022-03-13 15:14
I'm using Turborepo and I'm also facing the same issues.

Prisma Version: `3.10.0`
Next Version: `12.0.8`

It seems when I import 'prisma` from a package in my turborepo I get the following error:
```
Module not found: Can't resolve '_http_common'
```

**Comment by VincentThomas06** [comment] 2022-03-17 15:08
I still have this issue error ```
ERROR in ./apps/thunderbolt/prisma/client/runtime/index.js 27999:21-44
Module not found: Error: Can't resolve '_http_common' in 'C:\Users\vincent\coding\Codebase\apps\thunderbolt\prisma\client\runtime'

```

**Comment by juanzgc** [comment] 2022-03-18 00:19
@janpio Hi Jan, by any chance do you have a timeline for the following issue: https://github.com/prisma/prisma/pull/8842

It would be great to have this sorted so we can begin using Prisma in our monorepo (Turborepo)!  😇

**Comment by VincentThomas06** [comment] 2022-03-25 16:48
> Hey everyone, this has been fixed in `@prisma/client@dev` if you want to give it a try. Please let us know if you find anything unexpected. Thanks.
> 
> (cc @VincentThomas06 @j0hnm4r5 @juanzgc)

Thanks for notifying me!

**Comment by VincentThomas06** [comment] 2022-03-25 21:23
> In my case, I am not getting the `Can't resolve '_http_common'` error anymore but now I am getting a `Can't resolve 'util/types'` error.
> 
> To reproduce it, I started from this [prisma blog post](https://www.prisma.io/blog/full-stack-typesafety-with-angular-nest-nx-and-prisma-CcMK7fbQfTWc) project as a base + @prisma/client upgrade to 3.11.0 and dev + set a custom output path.

Thats funny, i got the same error:
```
ERROR in ./prisma/client/runtime/index.js 33781:27-48
Module not found: Error: Can't resolve 'util/types' in 'C:\Users\vincent\coding\Codebase\apps\thunderbolt\prisma\client\runtime'
resolve 'util/types' in 'C:\Users\vincent\coding\Codebase\apps\thunderbolt\prisma\client\runtime'
  Parsed request is a module
  using description file: C:\Users\vincent\coding\Codebase\apps\thunderbolt\package.json (relative path: ./prisma/client/runtime)
```

webpack config:
```jsonc
module.exports = (options, webpack) => {
  const lazyImports = [
    '@nestjs/microservices/microservices-module',
    '@nestjs/websockets/socket-module',
// Tried fixing the issue with this below
    /util/
  ];

  return {
    ...options,
    externals: ['util'],

    resolve: {
      extensions: ['.ts', '.js', '.json'],
      fallback: {
        util: require.resolve('util/')
      }
    },
    module: {
      rules: [
        {
          test: /\.ts$/,
          use: 'ts-loader'
        },
        {
          test: /\.js$/,
          exclude: /(node_modules|prisma)/,
          use: {
            loader: 'swc-loader'
          }
        }
      ]
    },
    plugins: [
      ...options.plugins,
      new webpack.IgnorePlugin({
        checkResource: resource => {
          if (lazyImports.includes(resource)) {
            try {
              require.resolve(resource);
            } catch (err) {
              return true;
            }
          }
          return false;
        }
      })
    ]
  };
};

```

**Comment by millsp** [comment] 2022-04-01 12:18
Hey @Frankitch @VincentThomas06 👋 I think I understood the issue. When you generate to the default location, the client gets generated with a `package.json` in which there is a browser field. This field is used by webpack to bundle for the web (default). But because it's generated outside of node_modules, we don't create such `package.json`. Maybe for good reasons? Maybe not?

The next steps will simple. I'll need to setup a repro, you're very welcome to help me there if you already have one. And that is just to make sure we are fixing the right problem. Then, I will let us output a `package.json` in custom locations to and see if webpack/nestjs can pick that up automatically. If that fails, I will provide you with a workaround.

Thus, I'm closing this issue about `_http_common`, but don't worry we will be tracking the work to come via [#12607](https://github.com/prisma/prisma/issues/12607)

Thanks!

**Closed by millsp** 2022-04-01 12:18 UTC
Labels: bug/0-unknown, kind/bug, status/needs-fix-confirmation, topic: node version, topic: undici, team/client, topic: _http_common

**Comment by joshribakoff-sm** [comment] 2022-07-25 17:33
@millsp I think you got it wrong. In my project I am generating a client in the node_modules, it works 50% of the time and the  other 50% I get the error described in this issue. When it does work, I inspect the built artifacts and there is no package.json. This doesn't seem related to a package.json or generating clients outside of node_modules

I verified the problematic line is in fact there during the times it works::

```
grep -r 'http_common' node_modules/@internal/prisma
node_modules/@internal/prisma/client/runtime/index.js:    var common = require("_http_common");
```

this is also a file that doesn't exist in my project (both when Prisma fails to be generated, and in the cases where Prisma generation is scuffed):

```
find . | grep http_common
# no output
```

**Comment by millsp** [comment] 2022-07-25 18:10
`http_common` imports should all be gone in the latest versions of prisma, as that was coming from our `undici` dependency. Which version are you testing this on?

**Comment by joshribakoff-sm** [comment] 2022-07-25 18:15
You're right, I had to update `@prisma/client` to 3.15.2 (and not just `prisma` as I had done previously), and it is working now 👍
