### ISSUE TITLE
Prisma support for Deno

### ISSUE THREAD

**Issue by LaurenceM10** [prisma/prisma#2541] opened 2020-05-24 21:31 UTC
Feature requests

Deno was released a few days ago, is there any plan to support it?
https://deno.land/v1

**Comment by Sytten** [comment] 2020-05-24 21:53
Duplicates of https://github.com/prisma/prisma/issues/2452

**Comment by pantharshit00** [comment] 2020-05-24 22:29
Hi,

Thanks for reporting this! It has already been reported before, so I am going to close this as a duplicate of #2452 

Thanks @Sytten 🎉

**Closed by pantharshit00** 2020-05-24 22:29 UTC
