### ISSUE TITLE
[Feature request] Support database-functions such as the ones from pgcrypto

### ISSUE THREAD

**Issue by GeeWee** [prisma/prisma#9466] opened 2021-09-27 11:02 UTC
## Problem
(From discussion [here](https://github.com/prisma/prisma/discussions/7798))

I would like to be able to work with [pgcrypto](https://www.postgresql.org/docs/8.3/pgcrypto.html) to encrypt some columns in my database. A usage example of this in raw SQL would look something like this:

```sql
INSERT INTO 'table' VALUES pgp_sym_encrypt('someEmail', 'myClientSidePassword')
SELECT pgp_sym_decrypt(email, 'myClientSidePassword') from 'table'
```

I would like to not have to dig into `queryRaw` for this if possible.

## Suggested solution

I would like some way to specify that a value should be passed to `pgp_sym_encrypt` or `pgp_sym_decrypt` in the query, like above. Perhaps this should be part of the actual query, or perhaps the Prisma Schema. 

For `pgcrypto` it could easily be part of the schema as you'll always want to encrypt/decrypt, but for other cases of database functions it might be on a per-query basis.

I'm not sure what the best solution here is. I think the problem of running some value through a database function before inserting or acting on it is a "broader" problem than just for pgcrypto, and I imagine there might be some more generalizable solution

**Comment by pantharshit00** [comment] 2021-09-27 13:51
Hi,

Thanks for reporting this! It has already been reported before, so I am going to close this as a duplicate of https://github.com/prisma/prisma/issues/7815

**Closed by pantharshit00** 2021-09-27 13:51 UTC

**Comment by GeeWee** [comment] 2021-09-27 14:22
That seems very reasonable to me.
