### ISSUE TITLE
Error when serialize array value to scalar domain on postgres

### ISSUE THREAD

**Issue by brunomarchioro** [prisma/prisma#18301] opened 2023-03-13 18:42 UTC
### Bug description

I have a table that contains a field that uses a custom array type (DOMAIN). When trying to create a new record in this table, I receive the error: `ConversionError("Couldn't serialize value Some([Text(Some(\"ES\"))]) into a language_sample. Value is a list but language_sample is not.")`.

### How to reproduce

Create de domain and table:

```sql
CREATE DOMAIN language_sample AS VARCHAR(3)[]
  CONSTRAINT no_empty_element CHECK (NOT VALUE @> '{""}')
  CONSTRAINT is_uppercase CHECK (array_to_string(VALUE, ',') =
                                 upper(array_to_string(VALUE, ',')));

CREATE TABLE IF NOT EXISTS site_sample
(
  site_id         UUID NOT NULL PRIMARY KEY DEFAULT uuid_generate_v1(),
  translates_from language_sample
);
```

Create a Prisma schema:

```prisma
generator client {
  provider = "prisma-client-js"
  previewFeatures = ["clientExtensions"]
}

datasource db {
  provider = "postgresql"
  url = env("DATABASE_URL")
}

model Site {
  siteId String @id @default(dbgenerated("uuid_generate_v1()")) @map("site_id") @db.Uuid
  translatesFrom String[] @map("translates_from") @db.VarChar(3)

  @@map("site")
}
```

Try to create a new site:

```ts
const newSite = await prisma.site.create({
  data: {
    translatesFrom: ["ES"],
  },
})
```

I create a repository with a reproduction:
[https://github.com/brunomarchioro/prisma_issue](https://github.com/brunomarchioro/prisma_issue)

### Expected behavior

Successfully create a new record with an array field.

### Prisma information

```prisma
generator client {
  provider = "prisma-client-js"
  previewFeatures = ["clientExtensions"]
}

datasource db {
  provider = "postgresql"
  url = env("DATABASE_URL")
}

model Site {
  siteId String @id @default(dbgenerated("uuid_generate_v1()")) @map("site_id") @db.Uuid
  translatesFrom String[] @map("translates_from") @db.VarChar(3)

  @@map("site")
}
```

```ts
const { PrismaClient } = require("@prisma/client");

const prisma = new PrismaClient();

(async () => {
  const newSite = await prisma.siteSample.create({
    data: {
      translatesFrom: ["ES"],
    },
  });

  console.log(newSite);
})();
```

### Environment & setup

- OS: Ubuntu v22.04
- Database: PostgreSQL v10
- Node.js version: v16.19.1

### Prisma Version

```
prisma                  : 4.11.0
@prisma/client          : 4.11.0
Current platform        : debian-openssl-3.0.x
Query Engine (Node-API) : libquery-engine 8fde8fef4033376662cad983758335009d522acb (at node_modules/@prisma/engines/libquery_engine-debian-openssl-3.0.x.so.node)
Migration Engine        : migration-engine-cli 8fde8fef4033376662cad983758335009d522acb (at node_modules/@prisma/engines/migration-engine-debian-openssl-3.0.x)
Format Wasm             : @prisma/prisma-fmt-wasm 4.11.0-57.8fde8fef4033376662cad983758335009d522acb
Default Engines Hash    : 8fde8fef4033376662cad983758335009d522acb
Studio                  : 0.483.0
Preview Features        : clientExtensions
```

**Comment by janpio** [comment] 2023-03-14 17:33
You are telling Prisma that `translatesFrom` is an array of `String`s, but it really `VARCHAR(3)[]` with a bunch of constraints. That is probably what leads to somewhere in there something not matching up.

Does `language_array4` mean anything to you? Surprisingly there are 0 result for it on Google.

What does Prisma produce when you `db pull` this database as a schema?

**Comment by brunomarchioro** [comment] 2023-03-21 17:47
Hi @janpio, I made a mistake when write the description. `language_array4` is the name of custom domain on my local database. On the description the correct name should be `language_sample` (I already fix it in the description), both names is the name of a custom field created by the `CREATE DOMAIN` command (this is why you had no results on Google).

The `db pull` command return the same schema only without the length parameter. I belive that is not the problem on schema because `String[]` is a array os strings and `VARCHAR(3)[]` is also.

Thanks,

**Comment by brunomarchioro** [comment] 2023-04-13 00:14
Hi @janpio, any news about this problem?

**Comment by janpio** [comment] 2023-04-13 00:55
No, next step is that someone from the team needs to reproduce the problem and be able to understand what is going on. As it does not seem very common, it is unfortunately not high on our priority list. Sorry.

**Comment by jkomyno** [comment] 2024-08-22 09:23
Hey @brunomarchioro, apologies for the delay, but we just looked at this issue.
As it turns out, querying Postgres values using `DOMAIN` types isn't a problem with Prisma.

However, it looked like Prisma migrations weren't applied correctly, but rather, you were relying on `./schema.sql` being loaded into Docker's `postgres` service (which may be handy locally, but would break expectations in a production setting).

Given https://github.com/brunomarchioro/prisma_issue, here are the steps I took to successfully run your `prisma.siteSample.create(..)` query:
- Install dependencies with `pnpm i`
- Run the database via `docker compose -f docker-compose.yml up postgres`
- Reset the database schema via `pnpm prisma migrate --force --skip-generate`
- Create a new empty migration via `pnpm prisma migrate dev --name create_table_with_domain --create-only`, which creates a new `./prisma/migrations/<timestamp>_create_table_with_domain/migration.sql` file.
- Paste `schema.sql`'s content into the `migration.sql` file just created
- Apply the migration via `pnpm prisma migrate deploy`
- Clear out the `model` in `./prisma/schema.prisma` (it was referencing functions that do not exist normally in Postgres, like `uuid_generate_v1()` from the `uuid-osp` Postgres extension)
- Introspect the database schema via `pnpm prisma db pull`
- Add the missing `@map(...)` / `@@map(...)` attributes, as well as `@db.VarChar(3)`, so that the model looks like
  ```prisma
  model SiteSample {
    site_id         Int      @id @default(autoincrement())
    translatesFrom  String[] @map("translates_from") @db.VarChar(3)
  
    @@map("site_sample")
  }
  ```
- Run `prisma generate`
- Run `node main.js`

Output I got:

```javascript
❯ node main.js
{ site_id: 1, translatesFrom: [ 'ES' ] }
```

I hope this helps! I'm closing this thread as resolved, but feel free to leave a comment with feedback once you have a chance of trying again with the setup I've listed above. Thanks!

**Closed by jkomyno** 2024-08-22 09:23 UTC
Labels: domain/client, topic: postgresql, topic: domain
