### ISSUE TITLE
findUnique function fires two seperate query instead of using join

### ISSUE THREAD

**Issue by swapnil-gawali** [prisma/prisma#5251] opened 2021-01-23 11:53 UTC
Following is my schema:

```
generator client {
  provider = "prisma-client-js"
}


datasource db {
  provider = "mysql"
  url      = env("DATABASE_URL")
}

model profile {
  id    Int     @id @default(autoincrement())
  email String  @unique
  bio   String?
  user  user[]
}

model user {
  id         Int      @id @default(autoincrement())
  mobile     String   @unique
  name       String?
  profile_id Int?
  profile    profile? @relation(fields: [profile_id], references: [id])

  @@index([profile_id], name: "idx_fk_user_profile")
}
```

Code to find user based on id:
```
await this.prisma.user.findUnique({
      where: {
        id: 5
      },
      include: {
        profile: true,
      }
    })
```

when using **findUnique** its fires two queries instead of using joins:

```
prisma:query SELECT `newdb`.`user`.`id`, `newdb`.`user`.`mobile`, `newdb`.`user`.`name`, `newdb`.`user`.`profile_id` FROM `newdb`.`user` WHERE `newdb`.`user`.`id` = ? LIMIT ? OFFSE
T ?

prisma:query SELECT `newdb`.`profile`.`id`, `newdb`.`profile`.`email`, `newdb`.`profile`.`bio` FROM `newdb`.`profile` WHERE `newdb`.`profile`.`id` IN (?)
```

Am i doing something wrong?

**Comment by pantharshit00** [comment] 2021-01-29 17:10
Hey @swapnil-gawali 

We use dataloader pattern for fetching data right now. 

We will tackle this once we will start working on query optimization. 

I am going to close this as a duplicate of https://github.com/prisma/prisma/issues/5184

**Closed** 2021-01-29 17:11 UTC
