### ISSUE TITLE
intermittent: write EPIPE + Cannot read property 'onError' of undefined

### ISSUE THREAD

**Issue by royra** [prisma/prisma#4557] opened 2020-12-08 13:47 UTC
## Bug description

These two exceptions happen in the same flow:

```
ERROR	Invoke Error 	{"errorType":"Error","errorMessage":"write EPIPE","code":"EPIPE","clientVersion":"2.12.1","stack":["Error: write EPIPE","    at PrismaClientFetcher.request (/var/task/dist/webpack:/mnt/ramdisk/project/node_modules/@prisma/client/runtime/index.js:79355:15)","    at processTicksAndRejections (internal/process/task_queues.js:97:5)"]}
```

2 milliseconds later:

```
ERROR	Uncaught Exception 	{"errorType":"TypeError","errorMessage":"Cannot read property 'onError' of undefined","stack":["TypeError: Cannot read property 'onError' of undefined","    at Socket.ce (/var/task/dist/webpack:/mnt/ramdisk/project/node_modules/@prisma/client/runtime/index.js:25673:45)","    at Socket.emit (events.js:314:20)","    at Socket.EventEmitter.emit (domain.js:483:12)","    at Pipe.<anonymous> (net.js:676:12)"]}
```

This was previously masked by #4117, which was fixed by [this commit](https://github.com/prisma/prisma/commit/582ee80cd0f52c95280b3cf7babc5a1fbfe20a44); now the real error is visible.

Possibly related to #4400

## How to reproduce

This is an intermittent error on AWS Lambda, could not reproduce it on a dev machine.

## Expected behavior

- No exception (duh)
- It would be nice to have source mapping to link the stack trace into a specific spot in the code (instead of `@prisma/client/runtime/index.js:25673:45`).
- It would be nice to have more logs from the Rust process; IIUC there's no way to set `RUST_LOG` to something other than `info`

## Environment & setup

- OS: AWS Lambda (linux-musl), node 12.x
- Database: PostgreSQL 12 on RDS
- Node.js version: 12.18
- Prisma version: 2.12.1

**Comment by BearGuy** [comment] 2020-12-10 23:13
Any focus on this? This is giving me a reasonable headache in my own application.

@royra If you've developed any work arounds for this, please let me know. It would be greatly appreciated.

**Comment by andresggarcia** [comment] 2020-12-11 17:16
Having the same issue today just after upgrading from @prisma/client v2.4.1 => v2.12.1

`2020-12-11 @ 14:13:12.159 - error: Failed handling shipment status - request failed - [message:write EPIPE] [stack:Error: write EPIPE     at PrismaClientFetcher.request (/app/node_modules/@prisma/client/runtime/index.js:79353:15)     at process._tickCallback (internal/process/next_tick.js:68:7)] [level:ERROR]`

**Comment by pantharshit00** [comment] 2020-12-16 17:29
@royra AWS lambda uses `rhel-openssl-1.0.x` binary while you are mentioning `linux-musl`. I am not sure AWS has musl lib c installed in the environment. Please use `rhel-openssl-1.0.x` binary and try again. I think this is just binary compatibility issue here.


Here is what I use for an internal app deployed to lambda:
```prisma
generator client {
  provider        = "prisma-client-js"
  binaryTargets   = ["rhel-openssl-1.0.x", "native"]
}

```

**Comment by royra** [comment] 2020-12-17 08:02
> @royra AWS lambda uses `rhel-openssl-1.0.x` binary while you are mentioning `linux-musl`. I am not sure AWS has musl lib c installed in the environment. Please use `rhel-openssl-1.0.x` binary and try again. I think this is just binary compatibility issue here.
> 

@pantharshit00 sorry, my initial report was wrong. Lambda does use `rhel-openssl-1.0.x` as you said, we have both binary targets in the generator config (`linux-musl` is used elsewhere), and we copy the correct binary to the lambda runtime fs. Note that the issue is intermittent - everything works, most of the time. With the wrong binary it probably wouldn't have worked at all...

**Comment by aniruddha-adhikary** [comment] 2020-12-18 01:27
This issue is affecting me as well in AWS Lambda. I am using

```
generator client {
  provider = "prisma-client-js"
  binaryTargets = ["native", "rhel-openssl-1.0.x"]
}
```

I have been deploying with Serverless. And the issue is intermittent. The service continues to work well for some time, and with some random request, I get this error. I am not sure about the pattern of this error occurring. A retry with the same request works!

It does seem like a runtime fetching issue. What is it attempting to write to the Lambda Filesystem? It does suggest `write EPIPE`.

**Comment by pantharshit00** [comment] 2020-12-21 10:19
I have a theory that lambda is cleaning up the `/tmp` directory and cleaning up our unix domain socket which we use now in the latest version(we were using a TCP port before for Rust <-> communication).

Can you all try installing the dev channel and turning off UDS and see if this shows up again:
```
const prisma = new PrismaClient({
  __internal:{
    useUds: false
  }
} as any) // remove as any if you using js
```


Similar bug report about ads: https://github.com/prisma/prisma/issues/4744

**Comment by aniruddha-adhikary** [comment] 2020-12-21 14:20
> I have a theory that lambda is cleaning up the `/tmp` directory and cleaning up our unix domain socket which we use now in the latest version(we were using a TCP port before for Rust <-> communication).
> 
> Can you all try installing the dev channel and turning off UDS and see if this shows up again:
> 
> ```
> const prisma = new PrismaClient({
>   __internal:{
>     useUds: false
>   }
> } as any) // remove as any if you using js
> ```
> 
> Similar bug report about uds: #4744

@pantharshit00 That appears to have solved the issue! I am no longer getting the crashes. 💣 🚀 👍🏼

**Comment by zhorifiandi** [comment] 2020-12-22 07:24
> I have a theory that lambda is cleaning up the `/tmp` directory and cleaning up our unix domain socket which we use now in the latest version(we were using a TCP port before for Rust <-> communication).
> 
> Can you all try installing the dev channel and turning off UDS and see if this shows up again:
> 
> ```
> const prisma = new PrismaClient({
>   __internal:{
>     useUds: false
>   }
> } as any) // remove as any if you using js
> ```
> 
> Similar bug report about uds: #4744

Wow, I've been looking for days to solve this issue. This works for me. Thank you, sir!

**Comment by royra** [comment] 2020-12-23 13:43
> I have a theory that lambda is cleaning up the `/tmp` directory and cleaning up our unix domain socket which we use now in the latest version(we were using a TCP port before for Rust <-> communication).

Looks like prisma itself is [deleting its socket file](https://github.com/prisma/prisma/blob/b7dd2548559ce9221e57fe07dd2b467930884e8e/src/packages/engine-core/src/NodeEngine.ts#L1248) on the `beforeExit` event of the node process. According to [this blog post](https://medium.com/lifeomic/a-two-week-search-for-the-missing-body-of-a-lambda-function-response-c9ee79bd8093): 

> The Lambda runtime uses the beforeExit event to complete the last request and start processing the next request.

If this is true, it explains the intermittent error:
1. The event loop for the lambda container is emptied and `beforeHook` is called
2. Prisma deletes its own socket file
3. More requests are queued to the event loop, causing the same prisma instance to attempt more work
4. EPIPE

Reverting to tcp socket is a workaround, but the real fix could be unhooking from the `beforeExit` event.

**Comment by doomsower** [comment] 2020-12-29 10:33
For me the temporary solution was downgrading to version 2.11.

**Comment by d2kx** [comment] 2020-12-30 02:22
Ran into the same problem, PostgreSQL 12 @ AWS Lambda (Node.js 12.x) and upgrading to Prisma-dev and setting useUds: false fixed the issue for me aswell.

**Comment by RussMax783** [comment] 2021-01-05 03:13
upgrading too `"@prisma/cli": "^2.14.0-dev.68", "@prisma/client": "^2.14.0-dev.68",` seems to have fixed this issue for me as well. I've been using Node 12 with Postgres RDS and an RDS proxy.

**Comment by timsuchanek** [comment] 2021-01-18 14:17
Thanks for the comments, everyone! We switched back to TCP for now until we understand the problems with UDS better. Therefore this issue should be fixed now. Please let us know, if that is not the case for you, then we'll reopen this.

**Closed by timsuchanek** 2021-01-18 14:17 UTC
Labels: bug/2-confirmed, kind/bug, process/candidate, team/client, topic: aws lambda, topic: binary
