### ISSUE TITLE
`libquery_engine-debian-openssl-1.1.x.so.node` segmentation fault on Node v18.8.0

### ISSUE THREAD

**Issue by wvhulle** [prisma/prisma#15052] opened 2022-08-28 15:51 UTC
### Bug description

Installed a repository from scratch with prisma. Then wrote a seed function to seed the database. Running the seed function results in a segmentation fault related to `.prisma.client/libquery_engine-debian-openssl-1.1.x.so.node`.

The repository to reproduce is in https://github.com/wvhulle/hello-prisma

### How to reproduce

1. Follow the project from scratch tutorial (with https://www.prisma.io/docs/getting-started/setup-prisma/start-from-scratch/relational-databases-typescript-postgres)
2. Push schema and add seed script that uses `csv-parse`
3. Install the segmentation fault tracer ( with https://httptoolkit.tech/blog/how-to-debug-node-segfaults/)
4. Run the seed script.

### Expected behavior

A successful upsert of one database record.

### Prisma information

schema.prisma
```
generator client {
  provider        = "prisma-client-js"
  previewFeatures = ["fullTextSearch"]
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

model Project {
  label       String       @id
  productions Production[] @relation("productionsToProject")
}

model Product {
  name        String       @id
  description String?
  productions Production[] @relation("productionsToProduct")
}

model Production {
  projectLabel String
  project      Project @relation("productionsToProject", fields: [projectLabel], references: [label], onDelete: Cascade)
  productName  String
  product      Product @relation("productionsToProduct", fields: [productName], references: [name], onDelete: Cascade)

  @@id([projectLabel, productName])
}
```

The upsert: `const product = await prisma.product.upsert({ where: { name }, create: { name }, update: { name } })`

### Environment & setup

- OS: Linux Mint 20.3
- Database: PostgreSQL 14
- Node.js version: v18.8.0

### Prisma Version

```
prisma                  : 4.2.1
@prisma/client          : 4.2.1
Current platform        : debian-openssl-1.1.x
Query Engine (Node-API) : libquery-engine 2920a97877e12e055c1333079b8d19cee7f33826 (at node_modules/@prisma/engines/libquery_engine-debian-openssl-1.1.x.so.node)
Migration Engine        : migration-engine-cli 2920a97877e12e055c1333079b8d19cee7f33826 (at node_modules/@prisma/engines/migration-engine-debian-openssl-1.1.x)
Introspection Engine    : introspection-core 2920a97877e12e055c1333079b8d19cee7f33826 (at node_modules/@prisma/engines/introspection-engine-debian-openssl-1.1.x)
Format Binary           : prisma-fmt 2920a97877e12e055c1333079b8d19cee7f33826 (at node_modules/@prisma/engines/prisma-fmt-debian-openssl-1.1.x)
Default Engines Hash    : 2920a97877e12e055c1333079b8d19cee7f33826
Studio                  : 0.469.0
Preview Features        : fullTextSearch
```

**Comment by wvhulle** [comment] 2022-08-28 16:01
```
sudo npm install -g n 
sudo n stable
npm rebuild
```

fixes the bug, but i had to downgrade from Node v18.8.0 to v16.17.0.

**Comment by garrensmith** [comment] 2022-08-31 08:32
@wvhulle thanks for the report. I'm going to close this one since it is a duplicate of https://github.com/prisma/prisma/issues/13641

**Closed by garrensmith** 2022-08-31 08:32 UTC
Labels: bug/1-unconfirmed, kind/bug, topic: node version, team/client, topic: segmentation fault

**Comment by garth** [comment] 2022-09-07 19:58
I just upgraded my PostgreSQL server from v12 to v14. Prisma 4.3 was running via node 18.8.0 with no issues before the upgrade. After the upgrade I got segmentation faults. But interestingly, migrations succeed, only regular queries caused the segmentation fault. Reverting back back to node 16.17.0 fixed issue.

**Comment by aqrln** [comment] 2022-09-19 13:21
https://github.com/prisma/prisma/issues/10649#issuecomment-1249209025
