### ISSUE TITLE
Unable to migration autoincrementing BigInt to autoincrementing Int

### ISSUE THREAD

**Issue by dompatmore** [prisma/prisma#8746] opened 2021-08-14 16:15 UTC
### Bug description

I tried to create a prisma model with connects to a Postgres database. For the ids for the table, I want to use the BigInt datatype, as it says it's supported. However,  when I try to push the new model I get `Error querying the database: db error: ERROR: type "bigserial" does not exist` and I'm unable to push the model

### How to reproduce

1. Create a new prisma instance as per documentation, connecting to a postgres database
2. Create the model as described below
3. Push the model using `prisma db push`
4. Very the error returned is 
`Error: Database error
Error querying the database: db error: ERROR: type "bigserial" does not exist
   0: sql_migration_connector::sql_database_step_applier::apply_migration
             at migration-engine/connectors/sql-migration-connector/src/sql_database_step_applier.rs:11
   1: migration_core::api::SchemaPush
             at migration-engine/core/src/api.rs:161`

### Expected behavior

`push` command should happen as expected as BigInt is supported

### Prisma information
```prisma
enum EntityType {
  club
  individual
}

enum Status {
  active
  dormant
}

generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

model club_entity {
  id     BigInt @db.BigInt @id @default(autoincrement())
  name   String @unique
  email  String
  type   EntityType @default(club)
  status Status
  points Int    @default(0)
}

model club_transactions {
  id          BigInt @db.BigInt @id @default(autoincrement())
  description String
  pointChange Int
  clubId      Int
}
```

### Environment & setup

- Client OS is MacOS
- Database: PostsgreSQL
- Node: 14.15.4

### Prisma Version

```
prisma               : 2.29.1
@prisma/client       : 2.29.1
Current platform     : darwin
Query Engine         : query-engine 1be4cd60b89afa04b192acb1ef47758a39810f3a (at node_modules/@prisma/engines/query-engine-darwin)
Migration Engine     : migration-engine-cli 1be4cd60b89afa04b192acb1ef47758a39810f3a (at node_modules/@prisma/engines/migration-engine-darwin)
Introspection Engine : introspection-core 1be4cd60b89afa04b192acb1ef47758a39810f3a (at node_modules/@prisma/engines/introspection-engine-darwin)
Format Binary        : prisma-fmt 1be4cd60b89afa04b192acb1ef47758a39810f3a (at node_modules/@prisma/engines/prisma-fmt-darwin)
Default Engines Hash : 1be4cd60b89afa04b192acb1ef47758a39810f3a
Studio               : 0.419.0
```

**Comment by janpio** [comment] 2021-08-16 14:22
Can you please use `prisma migrate dev` instead of `prisma db push` and post the content of the SQL migration file that was generated?

What version of PostgreSQL are you using? Where are you hosting it?

**Comment by dompatmore** [comment] 2021-08-16 17:04
I'm using the Postres hosted here: https://supabase.io/docs/guides/database
As for the sql:
/*
  Warnings:

  - The primary key for the `club_entity` table will be changed. If it partially fails, the table could be left without primary key constraint.
  - The `type` column on the `club_entity` table would be dropped and recreated. This will lead to data loss if there is data in the column.
  - The primary key for the `club_transactions` table will be changed. If it partially fails, the table could be left without primary key constraint.
  - Added the required column `status` to the `club_entity` table without a default value. This is not possible if the table is not empty.

*/
-- CreateEnum
CREATE TYPE "EntityType" AS ENUM ('club', 'individual');

-- CreateEnum
CREATE TYPE "Status" AS ENUM ('active', 'dormant');

-- AlterTable
ALTER TABLE "club_entity" DROP CONSTRAINT "club_entity_pkey",
ADD COLUMN     "status" "Status" NOT NULL,
ALTER COLUMN "id" SET DATA TYPE BIGSERIAL,
DROP COLUMN "type",
ADD COLUMN     "type" "EntityType" NOT NULL DEFAULT E'club',
ADD PRIMARY KEY ("id");

-- AlterTable
ALTER TABLE "club_transactions" DROP CONSTRAINT "club_transactions_pkey",
ALTER COLUMN "id" SET DATA TYPE BIGSERIAL,
ADD PRIMARY KEY ("id");

**Comment by janpio** [comment] 2021-08-16 18:07
Interesting. Did you by chance run this on a database that already has some data or was that on a clean one?

**Comment by pantharshit00** [comment] 2021-08-18 15:29
I am unable to reproduce this. I tried it on both supabase and locally:
![image](https://user-images.githubusercontent.com/22195362/129926551-8d227205-0102-45cb-a95f-fb5a000f2d24.png)
![image](https://user-images.githubusercontent.com/22195362/129926663-5b1ffec6-f09c-4f45-bfc6-79e59dd2d518.png)


Maybe try cloning your supabase project if the service allows that and try on new database connection?

**Comment by dompatmore** [comment] 2021-08-19 16:59
Thank you-to clarify:
On an empty table, I'm able to create a schema using BigInt:

-- CreateEnum
CREATE TYPE "EntityType" AS ENUM ('club', 'individual');

-- CreateEnum
CREATE TYPE "Status" AS ENUM ('active', 'dormant');

-- CreateTable
CREATE TABLE "club_entity" (
    "id" BIGSERIAL NOT NULL,
    "name" TEXT NOT NULL,
    "email" TEXT NOT NULL,
    "type" "EntityType" NOT NULL DEFAULT E'club',
    "status" "Status" NOT NULL,
    "points" INTEGER NOT NULL DEFAULT 0,

    PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "club_transactions" (
    "id" BIGSERIAL NOT NULL,
    "description" TEXT NOT NULL,
    "pointChange" INTEGER NOT NULL,
    "clubId" INTEGER NOT NULL,

    PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "club_entity.name_unique" ON "club_entity"("name");

*However*; should I try to change the primary back to Int using this migration:

/*
  Warnings:

  - The primary key for the `club_entity` table will be changed. If it partially fails, the table could be left without primary key constraint.
  - You are about to alter the column `id` on the `club_entity` table. The data in that column could be lost. The data in that column will be cast from `BigInt` to `Integer`.
  - The primary key for the `club_transactions` table will be changed. If it partially fails, the table could be left without primary key constraint.
  - You are about to alter the column `id` on the `club_transactions` table. The data in that column could be lost. The data in that column will be cast from `BigInt` to `Integer`.

*/
-- AlterTable
ALTER TABLE "club_entity" DROP CONSTRAINT "club_entity_pkey",
ALTER COLUMN "id" SET DATA TYPE SERIAL,
ADD PRIMARY KEY ("id");

-- AlterTable
ALTER TABLE "club_transactions" DROP CONSTRAINT "club_transactions_pkey",
ALTER COLUMN "id" SET DATA TYPE SERIAL,
ADD PRIMARY KEY ("id");


I get the error previously raised. Is this expected?

**Comment by janpio** [comment] 2021-08-19 17:41
Can you paste the error you are getting when you run this last migration please? It does not include `BIGSERIAL`. so you getting an error message containing that would be super unexpected and weird.

**Comment by dompatmore** [comment] 2021-08-19 19:16
![Screenshot 2021-08-19 at 20 15 51](https://user-images.githubusercontent.com/36126777/130130531-ed8e16bb-2a43-48b9-8f95-b18480f45053.png)

**Comment by janpio** [comment] 2021-08-19 19:22
Ok, the error there is that `Serial` does not exist. That is different but also interesting. For some reason the database does not seem to know these aliases. Maybe @pantharshit00 can reproduce _that_.

**Comment by pantharshit00** [comment] 2021-08-24 11:05
Thanks for the info @dompatmore 

I can reproduce this even locally now when you change `BigInt` to `Int` on **autoincrementing** fields. 

`SERIAL` is not a datatype but a shortcut and it does not work on alter statements. So what we generate is `ALTER COLUMN "id" SET DATA TYPE SERIAL,` doesn't work. 

Workaround here would be to remove `autoincrement()` as well when changing from `BigInt` to `Int` and adding it again on separate migration.

**Comment by pantharshit00** [comment] 2021-08-24 11:14
This has been actually reported before so closing as duplicate of https://github.com/prisma/prisma/issues/5206

**Closed by pantharshit00** 2021-08-24 11:14 UTC
Labels: bug/2-confirmed, kind/bug, process/candidate, team/migrations, topic: db push

**Comment by intellectualDarknet** [comment] 2024-08-30 08:26
have the same problem. Dropped the table in the database and it migrated successfully
