### ISSUE TITLE
Prisma Migrate: User was denied access on the database

### ISSUE THREAD

**Issue by net-caster** [prisma/prisma#4579] opened 2020-12-10 08:57 UTC
## Bug description

Hi everyone. First time submitting a bug(?) report. Yesterday I upgraded to Prisma 2.13.0 and everything seemed to go well but when i tried to run `npx prisma migrate dev --preview-feature` I got a P1010 error (*User was denied access on the database*).
The permissions all seem to be fine and I can connect to the database from either a client or the terminal. The already existing code also works just fine (I can read and write to the database) through the API with Prisma in the middle.

Also running `npx prisma introspect` gives me this: *[libs/datamodel/connectors/dml/src/datamodel.rs:175:14] Every RelationInfo should have a complementary RelationInfo on the opposite relation field.*

## How to reproduce

Not sure. It's in a docker network and all was working fine until 2.13.0

## Expected behavior

Prisma Migrate would create all the tables based on the schema file

## Environment & setup

- OS: Linux (Kubuntu)
- Database: MySQL
- Node.js version: Latest node 12 version from Docker
- Prisma version: 2.13.0

```

```

**Comment by pantharshit00** [comment] 2020-12-10 09:48
Hi,

Thanks for reporting this! It has already been reported before, so I am going to close this as a duplicate of https://github.com/prisma/prisma/issues/4571

**Closed by pantharshit00** 2020-12-10 09:48 UTC
