### ISSUE TITLE
Prisma Accelerate—Critical dependency: the request of a dependency is an expression

### ISSUE THREAD

**Issue by jessaleks** [prisma/prisma#22197] opened 2023-12-01 17:13 UTC
### Bug description

Similary to the issue #20743, I am experiencing a problem with prisma accelerate. In the build process, I get 

```
Critical dependency: the request of a dependency is an expression

Import trace for requested module:
./node_modules/@prisma/extension-accelerate/node_modules/@prisma/client/scripts/default-index.js
./node_modules/@prisma/extension-accelerate/dist/esm/extension.js
./node_modules/@prisma/extension-accelerate/dist/esm/entry.node.js
```

During the build process, I got an error, while when in dev mode, I got a different error `Error: Cannot find module '@prisma/engines-version'`.

It's a next.js app,

```
"next": "14.0.3",
"@prisma/client": "^5.6.0",
"@prisma/extension-accelerate": "^0.6.2",
"@prisma/instrumentation": "^4.16.2".
```

### How to reproduce

It's just a standard data fetching function in a Next server component.

### Prisma information

```ts
client.blogPost.findMany({
			where: {
				status: "PUBLISHED",
			},
			take: 10,
			select: {
				slug: true,
				title: true,
				description: true,
				Image: {
					select: {
						url: true,
						title: true,
						placeholderString: true,
					},
				},
				Category: {
					select: {
						title: true,
						slug: true,
						description: true,
					},
				},
			},
			orderBy: {
				publishedAt: "desc",
			},
		})
```

### Environment & setup

- OS: macOS 14.0
- Database: PostgresQL
- Node.js version: 20.10.0

### Prisma Version

```
prisma                  : 5.6.0
@prisma/client          : 5.6.0
Computed binaryTarget   : darwin-arm64
Operating System        : darwin
Architecture            : arm64
Node.js                 : v20.10.0
Query Engine (Node-API) : libquery-engine e95e739751f42d8ca026f6b910f5a2dc5adeaeee (at node_modules/@prisma/engines/libquery_engine-darwin-arm64.dylib.node)
Schema Engine           : schema-engine-cli e95e739751f42d8ca026f6b910f5a2dc5adeaeee (at node_modules/@prisma/engines/schema-engine-darwin-arm64)
Schema Wasm             : @prisma/prisma-schema-wasm 5.6.0-32.e95e739751f42d8ca026f6b910f5a2dc5adeaeee
Default Engines Hash    : e95e739751f42d8ca026f6b910f5a2dc5adeaeee
Studio                  : 0.495.0
Preview Features        : multiSchema, postgresqlExtensions, tracing

```

**Comment by janpio** [comment] 2023-12-01 19:20
Are you by chance using a custom `output` in your Prisma schema and importing from that path directly?

**Comment by jessaleks** [comment] 2023-12-02 08:37
> Are you by chance using a custom `output` in your Prisma schema and importing from that path directly?

Nah.

**Comment by jessaleks** [comment] 2023-12-02 08:41
> Hey @jessaleks, could you please try our latest `dev` version? Install `@prisma/client@dev` and `prisma@dev`, and re-generate your client. Thanks :)

Right, done. Unfortunately, that didn't do the trick. 

```
./node_modules/@prisma/extension-accelerate/node_modules/@prisma/client/scripts/default-index.js
Critical dependency: the request of a dependency is an expression

Import trace for requested module:
./node_modules/@prisma/extension-accelerate/node_modules/@prisma/client/scripts/default-index.js
./node_modules/@prisma/extension-accelerate/dist/esm/extension.js
./node_modules/@prisma/extension-accelerate/dist/esm/entry.node.js
./prisma/Client.ts
```

I'm not doing anything fancy as well.

```
import "server-only";

import { PrismaClient } from "@prisma/client/edge";
import { withAccelerate } from "@prisma/extension-accelerate";

let prisma: PrismaClient;

if (process.env.NODE_ENV === "production") {
	prisma = new PrismaClient().$extends(withAccelerate());
} else {
	if (!global.prisma) {
		global.prisma = new PrismaClient().$extends(withAccelerate());
	}

	prisma = global.prisma;
}

export default prisma;
```

**Comment by jessaleks** [comment] 2023-12-02 21:18
Ok so I gave it a shot on Windows. It builds without any issues.

**Comment by nurul3101** [comment] 2023-12-03 18:32
@jessaleks To confirm, are you observing this issue only on Mac OS and not on Windows?

**Comment by jessaleks** [comment] 2023-12-03 18:36
> @jessaleks To confirm, are you observing this issue only on Mac OS and not on Windows?

Correct.

**Comment by jessaleks** [comment] 2023-12-07 19:48
> @jessaleks, I wanted to check in to see if you're still experiencing the issue you mentioned. A similar problem was resolved by updating to the latest versions of `@prisma/client` and `@prisma/extension-accelerate`.
>  
> - https://github.com/prisma/prisma/issues/22181 
> 
> Also, could you clarify whether your build fails when this warning appears, or does it still pass successfully?

Hi, 

I updated all packages to the latest versions, and I am not experiencing the issues anymore.

Funnily enough, before the upgrades, I did have the errors on macOS 14, BUT not on Windows 11. Now, none.

Yes, the build failed.

**Comment by nurul3101** [comment] 2023-12-08 06:50
Thank you for confirming that the issue is resolved. 🙏 

I'll close this issue.

**Closed by nurul3101** 2023-12-08 06:50 UTC
Labels: bug/1-unconfirmed, kind/bug, team/pdp, topic: pdp/accelerate
