### ISSUE TITLE
Snowflake provider support

### ISSUE THREAD

**Issue by thebiglabasky** [prisma/prisma#11881] opened 2022-02-17 15:49 UTC
## Problem

This issue is there to track interest and use cases for supporting Snowflake with Prisma.

**Comment by szawadski** [comment] 2022-06-07 15:35
Hello, due to its configuration simplicity, its cost model and its power with large dataset, we currently use Snowflake for the prototyping of web apps (mainly data-based apps). When we migrate them into production ready apps, we have to migrate the data and the app to PostgreSQL (internal company requirement).
With Snowflake compatible with Prisma, this would allow us to perform those migrations seamlessly. Especially that Snowflake will announce soon a new table type, optimised for transactions (while the current table type is more optimised for analytics).

**Comment by dbnar2** [comment] 2023-01-09 22:32
Any updates on this? Would love to have some workaround solution to use Prisma with Snowflake DB

**Comment by thebiglabasky** [comment] 2023-01-10 08:32
Our stance hasn't changed, so I wouldn't count on any official Snowflake connector anytime soon. I am not aware of workarounds at the moment.

**Comment by samplefrequency** [comment] 2023-07-04 13:33
Is there any update on this?

**Comment by janpio** [comment] 2023-07-04 19:36
No.

**Comment by arghhjayy** [comment] 2024-02-20 07:18
I think it's high time Prisma provides support for Snowflake. It is picking up pace and is a great db warehouse

**Comment by jonataslaw** [comment] 2024-03-22 04:59
Yeah, it is... necessary.
uuid and auto increment is awful

**Comment by nedmayo** [comment] 2024-04-03 19:09
We would love to have snowflake support!

**Comment by andyinsf** [comment] 2024-05-17 19:04
Snowflake now has a feature called Hybrid Tables, which is analogous to a PostgreSQL plopped down inside of Snowflake, giving OLTP characteristics.  I know Snowflake is looking to create more connectivity into the application space, so a partnership between Prisma and Snowflake might be mutually beneficial.  cc @sfc-gh-jgarcia-0 @ jocagarcia

**Comment by andyinsf** [comment] 2024-05-17 19:04
Snowflake now has a feature called Hybrid Tables, which is analogous to a PostgreSQL plopped down inside of Snowflake, giving OLTP characteristics. I know Snowflake is looking to create more connectivity into the application space, so a partnership between Prisma and Snowflake might be mutually beneficial. cc @sfc-gh-jgarcia-0 @jocagarcia

**Comment by oieduardorabelo** [comment] 2024-07-10 23:19
adding to the thread:

i work with multiple companies across new zealand / australia, and lots of them are using snowflake as they direct database, having a single source between data warehousing and application data

any instructions, guidance or native integration between prisma and snowflake would be fantastic, prisma dx is the best on the better

**Comment by supermacro** [comment] 2024-09-19 18:20
prisma support for hybrid tables would be great

**Comment by jkomyno** [comment] 2024-12-06 13:34
Hi there,

As part of our effort to clean up our GitHub repo, we’re closing this issue to help focus on features and improvements that align with our focus areas and those of our community. 

If this is issue is still important to you, feel free to reopen the issue and get like-minded users to upvote as we will prioritize fixing issues based on community interest. If you do reopen the issue, please ensure that there’s a clear method for us to reproduce it. 

For more insight into our priorities and how we’re thinking about the future of the Prisma ORM, please see our recent blog post: https://www.prisma.io/blog/prisma-orm-manifesto.

Thank you for your understanding and support!

**Closed by jkomyno** 2024-12-06 13:34 UTC
Labels: kind/feature, topic: connector, domain/schema, domain/client

**Comment by omerchn** [comment] 2024-12-27 18:49
Hey, can we re-open this? Prisma support for Snowflake would be really helpful for us.
