### ISSUE TITLE
Prisma.JsonValue type is incompatible with Typescript JSON.parse typing

### ISSUE THREAD

**Issue by Faithfinder** [prisma/prisma#6416] opened 2021-04-05 14:50 UTC
## How to reproduce

```ts
import { Prisma } from "@prisma/client";

function parsePrisma(json: Prisma.JsonValue) {
  JSON.parse(json); 
  // Argument of type 'JsonValue' is not assignable to parameter of type 'string'.
  // Type 'null' is not assignable to type 'string'.
}

```

## Expected behavior

It's arguable that Prisma's typing is better than Typescript's - JS JSON.parse indeed accepts nulls, numbers etc. I would still expect the typings to match, so that I don't have to typecast every time I parse the database response.

## Prisma information

2.20.1

**Comment by matthewmueller** [comment] 2021-04-14 12:48
Yep that makes sense. What's the current workaround you do with type casting?

**Comment by Faithfinder** [comment] 2021-04-14 14:57
`json as any` or `json as string`, doesn't matter. Typescript `JSON.parse` definition isn't too helpful, it's not even generic.

```ts
parse(text: string, reviver?: (this: any, key: string, value: any) => any): any;
```
```ts
function parsePrisma(json: Prisma.JsonValue) {
  return JSON.parse(json as string) as WhatIExpectTheJsonToBe;
}
```

This issue is just about not having to type `as string` each time.

**Comment by millsp** [comment] 2021-04-15 13:06
Hey @Faithfinder, pass a `string` instead of `Prisma.JsonValue`. Could you provide some more context for your use-case please?

**Comment by Faithfinder** [comment] 2021-04-15 13:47
This is just an example that's easiest to reproduce. `Prisma.JsonValue` is the return type of a Json column.

Given schema
```prisma
model KPI {
  id       Int       @id @default(autoincrement())
  name     String
  formula  Json
}
```
Where "Formula" is arbitrary thing that describes a complicated calculation that would be overcomplicated to normalize

You can get a formula like this.
```ts
const formula = await prisma.KPI.findFirst({rejectOnNotFound: true}).formula;
// formula is Prisma.JsonValue
```
Next you feed it into JSON.parse and do whatever. I imagine that parsing the JSON from the database to get an object would be the most common operation on Json columns. Indeed, the [docs](https://www.prisma.io/docs/concepts/components/prisma-client/working-with-advanced-types#working-with-json) describe the typings as something to help working with `JSON.parse`
![image](https://user-images.githubusercontent.com/25051063/114879519-4668da80-9dcf-11eb-8fc2-a51305786287.png)

**Comment by aqrln** [comment] 2022-04-15 17:10
@Faithfinder but why do you even need to pass the contents of the field to `JSON.parse` in the first place?

**Comment by Faithfinder** [comment] 2022-04-15 19:30
Hmm... Just checked, and at least in PostgreSQL the return is indeed an already parsed object. We migrated from MySQL to Postgre since then, so maybe it wasn't the case with MySQL driver, or maybe our database was weirder then?

I'd love a way to easily get stronger type on a Json field, but that's a different topic altogether. Sorry about the confusion, I guess?

**Comment by aqrln** [comment] 2022-04-16 11:53
> Just checked, and at least in PostgreSQL the return is indeed an already parsed object. We migrated from MySQL to Postgre since then, so maybe it wasn't the case with MySQL driver, or maybe our database was weirder then?

Oh, I see. That would sound like a bug if it returned a JSON string to you instead of an actual value. I can't reproduce it with the latest Prisma with MySQL, but I wonder if something might have gone wrong back then.

> I'd love a way to easily get stronger type on a Json field, but that's a different topic altogether.

Yes, it's a popular feature request (https://github.com/prisma/prisma/issues/3219), and we'd love to have this too, but I can't share any specific timeline. Now that we support composite types for embedded documents in MongoDB we're one step closer to typed JSON fields in relational databases as well though.

> Sorry about the confusion, I guess?

No worries! Should I go ahead and close this issue?

**Closed** 2022-04-16 14:39 UTC
Labels: kind/discussion, tech/typescript, topic: json, team/client
