### ISSUE TITLE
Enums in QueryRaw do not work anymore

### ISSUE THREAD

**Issue by basitanwer** [prisma/prisma#14999] opened 2022-08-25 10:26 UTC
### Bug description

I upgraded my project from prisma 3 to 4.2.1 and now enums defined in schema do not work anymore.

```typescript
  asdf = await p.$queryRaw`
  SELECT * FROM "ShopInfo" WHERE "ShopInfo"."processorStatus"=${ProcessStatus.DONE}`;
```

This query used to work before, the only way to make it work is to remove it from the parameter

### How to reproduce

1. Code in question
```typescript
import { prisma, PrismaClient, ProcessStatus } from "@prisma/client";

(async () => {
  let p = new PrismaClient({
    log: [
      {
        emit: "event",
        level: "query",
      },
      {
        emit: "stdout",
        level: "error",
      },
      {
        emit: "stdout",
        level: "info",
      },
      {
        emit: "stdout",
        level: "warn",
      },
    ],
  });
  p.$connect();

  p.$on("query", (e) => {
    console.log(
      `Duration: ${e.duration}ms | Params: + ${e.params} | Query:  + ${e.query}`,
      "context.ts"
    );
  });

  let asdf = await p.shopInfo.findMany({
    where: {
      processorStatus: ProcessStatus.DONE,
    },
  });
  console.log(asdf); //This works

  // Throws error
  asdf = await p.$queryRaw`
  SELECT * FROM "ShopInfo" WHERE "ShopInfo"."processorStatus"=${ProcessStatus.DONE}`;

})();

```

2. See error
```bash
Duration: 27ms | Params: + ["DONE",0] | Query:  + SELECT "public"."ShopInfo"."qwer", "public"."ShopInfo"."asdf", "public"."ShopInfo"."processorStatus" FROM "public"."ShopInfo" WHERE "public"."ShopInfo"."processorStatus" = $1 OFFSET $2 context.ts
[]
Duration: 12ms | Params: + ["DONE"] | Query:  + 
  SELECT * FROM "ShopInfo" WHERE "ShopInfo"."processorStatus"=$1 context.ts
<PATH>/test-server/node_modules/@prisma/client/runtime/index.js:28838
      throw new PrismaClientKnownRequestError(message, error2.code, this.client._clientVersion, error2.meta);
            ^
PrismaClientKnownRequestError: 
Invalid `prisma.$queryRaw()` invocation:


  Raw query failed. Code: `42883`. Message: `db error: ERROR: operator does not exist: "ProcessStatus" = text
HINT: No operator matches the given name and argument types. You might need to add explicit type casts.`
    at RequestHandler.handleRequestError (<PATH>test-server/node_modules/@prisma/client/runtime/index.js:28838:13)
    at RequestHandler.request (<PATH>/test-server/node_modules/@prisma/client/runtime/index.js:28820:12)
    at async Proxy._request (<PATH>/test-server/node_modules/@prisma/client/runtime/index.js:29753:16)
    at async <PATH>/test-server/src/test.ts:56:10 {
  code: 'P2010',
  clientVersion: '4.2.1',
  meta: {
    code: '42883',
    message: 'db error: ERROR: operator does not exist: "ProcessStatus" = text\n' +
      'HINT: No operator matches the given name and argument types. You might need to add explicit type casts.'
  }
}
```

### Expected behavior

This should work fine and return values

### Prisma information

```prisma
generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

model ShopInfo {
  asdf            String
  qwer            Int
  processorStatus ProcessStatus @default(AWAITING)

  @@id([qwer, asdf])
}

enum ProcessStatus {
  AWAITING
  IN_PROGRESS
  DONE
}
```

### Environment & setup

- OS: Mac OS
- Database:PostgreSQL
- Node.js version: v16.9.0

### Prisma Version

```
prisma                  : 4.2.1
@prisma/client          : 4.2.1
Current platform        : darwin-arm64
Query Engine (Node-API) : libquery-engine 2920a97877e12e055c1333079b8d19cee7f33826 (at node_modules/@prisma/engines/libquery_engine-darwin-arm64.dylib.node)
Migration Engine        : migration-engine-cli 2920a97877e12e055c1333079b8d19cee7f33826 (at node_modules/@prisma/engines/migration-engine-darwin-arm64)
Introspection Engine    : introspection-core 2920a97877e12e055c1333079b8d19cee7f33826 (at node_modules/@prisma/engines/introspection-engine-darwin-arm64)
Format Binary           : prisma-fmt 2920a97877e12e055c1333079b8d19cee7f33826 (at node_modules/@prisma/engines/prisma-fmt-darwin-arm64)
Default Engines Hash    : 2920a97877e12e055c1333079b8d19cee7f33826
Studio                  : 0.469.0
```

**Comment by Jolg42** [comment] 2022-09-07 13:06
Can reproduce, code works with `3.15.2` 
```
ts-node main.ts   
prisma:info Starting a postgresql pool with 21 connections.
Duration: 8ms | Params: + ["DONE",0] | Query:  + SELECT "public"."ShopInfo"."qwer", "public"."ShopInfo"."asdf", "public"."ShopInfo"."processorStatus" FROM "public"."ShopInfo" WHERE "public"."ShopInfo"."processorStatus" = $1 OFFSET $2 context.ts
[]
Duration: 1ms | Params: + ["DONE"] | Query:  + 
  SELECT * FROM "ShopInfo" WHERE "ShopInfo"."processorStatus"=$1 context.ts
```

And fails on our internal dev version `4.4.0-dev.30`
```
ts-node main.ts
prisma:info Starting a postgresql pool with 21 connections.
Duration: 8ms | Params: + ["DONE",0] | Query:  + SELECT "public"."ShopInfo"."qwer", "public"."ShopInfo"."asdf", "public"."ShopInfo"."processorStatus" FROM "public"."ShopInfo" WHERE "public"."ShopInfo"."processorStatus" = $1 OFFSET $2 /* traceparent=00-00-00-00 */ context.ts
[]
Duration: 1ms | Params: + ["DONE"] | Query:  + 
  SELECT * FROM "ShopInfo" WHERE "ShopInfo"."processorStatus"=$1 context.ts
/Users/j42/Repros/14999/node_modules/@prisma/client/runtime/index.js:30850
      throw new PrismaClientKnownRequestError(message, error2.code, this.client._clientVersion, error2.meta);
            ^
PrismaClientKnownRequestError: 
Invalid `prisma.$queryRaw()` invocation:


Raw query failed. Code: `42883`. Message: `db error: ERROR: operator does not exist: "ProcessStatus" = text
HINT: No operator matches the given name and argument type(s). You might need to add explicit type casts.`
    at RequestHandler.handleRequestError (/Users/j42/Repros/14999/node_modules/@prisma/client/runtime/index.js:30850:13)
    at RequestHandler.request (/Users/j42/Repros/14999/node_modules/@prisma/client/runtime/index.js:30833:12)
    at async Proxy._request (/Users/j42/Repros/14999/node_modules/@prisma/client/runtime/index.js:31805:16)
    at async /Users/j42/Repros/14999/main.ts:41:10 {
  code: 'P2010',
  clientVersion: '4.4.0-dev.30',
  meta: {
    code: '42883',
    message: 'db error: ERROR: operator does not exist: "ProcessStatus" = text\n' +
      'HINT: No operator matches the given name and argument type(s). You might need to add explicit type casts.'
  }
}
```

**Comment by Jolg42** [comment] 2022-09-07 13:16
Closing since this is expected.
You will now need a type cast like
```
  await p.$queryRaw`
  SELECT * FROM "ShopInfo" WHERE "ShopInfo"."processorStatus" = ${ProcessStatus.DONE}::"ProcessStatus"`;
```

**Closed by Jolg42** 2022-09-07 13:16 UTC
Labels: bug/2-confirmed, kind/bug, kind/regression, topic: prisma-client, topic: raw, team/client, topic: enums, topic: postgresql
