### ISSUE TITLE
`prisma db pull` doesn't read `.env` file and errors with Environment variable not found: DATABASE_URL

### ISSUE THREAD

**Issue by smoothdvd** [prisma/prisma#11570] opened 2022-02-02 13:32 UTC
### Bug description

yarn prisma db pull report Environment variable not found: DATABASE_URL.
```
Prisma schema loaded from prisma/schema.prisma
Error: Get config: Schema Parsing P1012

error: Environment variable not found: DATABASE_URL.
  -->  schema.prisma:10
   | 
 9 |   provider = "postgresql"
10 |   url      = env("DATABASE_URL")
   | 

Validation Error Count: 1
```

.env:
DATABASE_URL="postgresql://user:pass@localhost:49154/db?schema=public"

### Expected behavior

read DATABASE_URL from .env correctly

### Prisma information

Environment variables loaded from .env
prisma                  : 3.9.0
@prisma/client          : 3.9.0
Current platform        : darwin-arm64
Query Engine (Node-API) : libquery-engine bcc2ff906db47790ee902e7bbc76d7ffb1893009 (at node_modules/@prisma/engines/libquery_engine-darwin-arm64.dylib.node)
Migration Engine        : migration-engine-cli bcc2ff906db47790ee902e7bbc76d7ffb1893009 (at node_modules/@prisma/engines/migration-engine-darwin-arm64)
Introspection Engine    : introspection-core bcc2ff906db47790ee902e7bbc76d7ffb1893009 (at node_modules/@prisma/engines/introspection-engine-darwin-arm64)
Format Binary           : prisma-fmt bcc2ff906db47790ee902e7bbc76d7ffb1893009 (at node_modules/@prisma/engines/prisma-fmt-darwin-arm64)
Default Engines Hash    : bcc2ff906db47790ee902e7bbc76d7ffb1893009
Studio                  : 0.457.0

### Environment & setup

- OS: macOS 12.2
- Database: PostgreSQL 13
- Node.js version: v14.18.1

### Prisma Version

```

```

**Comment by Jolg42** [comment] 2022-02-02 14:00
Hi @smoothdvd 

Thanks for the report!

I can confirm this is a regression, we are working on a fix and are planning a patch release later today 🚢

**Comment by millsp** [comment] 2022-02-02 17:19
Hey, this issue has been fixed in [3.9.1](https://github.com/prisma/prisma/releases/tag/3.9.1) which was just published. Thanks for reporting this!

**Closed by millsp** 2022-02-02 17:19 UTC
Labels: bug/2-confirmed, kind/bug, kind/regression, team/migrations, topic: db pull

**Comment by cweekly** [comment] 2022-02-14 23:24
Phew! Thought I was losing my mind. Confirmed I saw this in 3.9.0, and thankfully not in 3.9.2.

**Comment by stivencardonam** [comment] 2022-08-10 20:37
I have this problem with `mysql` and my @prisma/client version is `4.2.1`

**Comment by janpio** [comment] 2022-08-10 21:04
Cna you describe your problem fully @stivencardonam? If there was another full regression, I think we would have already seen more reports of it. So please spend some time to describe the full situation and we can try to figure out what is going on.

**Comment by stivencardonam** [comment] 2022-08-10 21:29
Sure,

**Bug Description**

yarn prisma db pull report Environment variable not found: DATABASE_URL.

**Environment & setup**
OS: macOS 12.2
Database: PostgreSQL 13
Node.js version: v14.18.1

```
Error: Get Config: Schema parsing - Error while interacting with query-engine-node-api library
Error code: P1012
error: Error validating datasource `db`: the URL must start with the protocol `mysql://`.
  -->  schema.prisma:7
   |
6 |   provider = "mysql"
7 |   url      = env("DATABASE_URL")
   | 

Validation Error Count: 1

Prisma CLI Version : 4.2.1
error Command failed with exit code 1.
```

`.env:` 
```env
DATABASE_URL=mysql://docker:docker@localhost:3306/test
```
OS: macOS 12.3.1
Database: MySQL 8.0.27 
Node.js version: v14.17.3

**DESCRIPTION**

I am start using prisma with nestsjs, I have a folder name `prisma` with `schema.prisma` file, when I execute `yarn prisma db pull` I have the error but when I replace the 7 line with the value of the env variable works fine:

`prisma/schema.primsma`
```
generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "mysql"
  url      = env("DATABASE_URL") // line that I replace with the env value directly and work fine
}
```

**Comment by stivencardonam** [comment] 2022-08-10 22:21
Sorry dude, I see my error now, I was overwriting the `DATABASE_URL` variable hahahahahaha 🙃

**Comment by janpio** [comment] 2022-08-11 18:52
That explains it 😆 Great you figured it out.

**Comment by rael346** [comment] 2022-08-12 14:05
@stivencardonam I'm having the same issue as you have stated above. How did you solve it?

**Comment by ZiadJ** [comment] 2022-08-28 08:38
> Sorry dude, I see my error now, I was overwriting the `DATABASE_URL` variable hahahahahaha 🙃

I'm getting the same error and I'm not sure what you mean by overwriting the variable.

**Comment by fwJayy** [comment] 2022-12-22 05:37
Hey, I am using mongodb and with prisma, When i try logging into my account it shows up some big error....
![Screenshot 2022-12-22 10 17 38 AM](https://user-images.githubusercontent.com/114661530/209064387-0a7c4e24-c70c-474a-aa17-a8811fdfd1c5.png) -- schema.prisma file

The ERROR IN THE TERMINAL...

[next-auth][warn][NO_SECRET] 
https://next-auth.js.org/warnings#no_secret
[next-auth][error][adapter_error_getUserByAccount] 
https://next-auth.js.org/errors#adapter_error_getuserbyaccount 
Invalid `p.account.findUnique()` invocation in
/workspaces/chat-app/frontend/node_modules/@next-auth/prisma-adapter/dist/index.js:11:45

   8 getUserByEmail: (email) => p.user.findUnique({ where: { email } }),
   9 async getUserByAccount(provider_providerAccountId) {
  10     var _a;
→ 11     const account = await p.account.findUnique(
Error parsing connection string: Database must be defined in the connection string {
  message: '\n' +
    'Invalid `p.account.findUnique()` invocation in\n' +
    '/workspaces/chat-app/frontend/node_modules/@next-auth/prisma-adapter/dist/index.js:11:45\n' +
    '\n' +
    '   8 getUserByEmail: (email) => p.user.findUnique({ where: { email } }),\n' +
    '   9 async getUserByAccount(provider_providerAccountId) {\n' +
    '  10     var _a;\n' +
    '→ 11     const account = await p.account.findUnique(\n' +
    'Error parsing connection string: Database must be defined in the connection string',
  stack: 'Error: \n' +
    'Invalid `p.account.findUnique()` invocation in\n' +
    '/workspaces/chat-app/frontend/node_modules/@next-auth/prisma-adapter/dist/index.js:11:45\n' +
    '\n' +
    '   8 getUserByEmail: (email) => p.user.findUnique({ where: { email } }),\n' +
    '   9 async getUserByAccount(provider_providerAccountId) {\n' +
    '  10     var _a;\n' +
    '→ 11     const account = await p.account.findUnique(\n' +
    'Error parsing connection string: Database must be defined in the connection string\n' +
    '    at RequestHandler.handleRequestError (/workspaces/chat-app/frontend/node_modules/@prisma/client/runtime/index.js:35038:13)\n' +
    '    at RequestHandler.handleAndLogRequestError (/workspaces/chat-app/frontend/node_modules/@prisma/client/runtime/index.js:34996:12)\n' +
    '    at /workspaces/chat-app/frontend/node_modules/@prisma/client/runtime/index.js:35542:25\n' +
    '    at async PrismaClient._executeRequest (/workspaces/chat-app/frontend/node_modules/@prisma/client/runtime/index.js:36111:22)\n' +
    '    at async PrismaClient._request (/workspaces/chat-app/frontend/node_modules/@prisma/client/runtime/index.js:36082:16)\n' +
    '    at async getUserByAccount (/workspaces/chat-app/frontend/node_modules/@next-auth/prisma-adapter/dist/index.js:11:29)',
  name: 'Error'
}
[next-auth][error][OAUTH_CALLBACK_HANDLER_ERROR] 
https://next-auth.js.org/errors#oauth_callback_handler_error 
Invalid `p.account.findUnique()` invocation in
/workspaces/chat-app/frontend/node_modules/@next-auth/prisma-adapter/dist/index.js:11:45

   8 getUserByEmail: (email) => p.user.findUnique({ where: { email } }),
   9 async getUserByAccount(provider_providerAccountId) {
  10     var _a;
→ 11     const account = await p.account.findUnique(
Error parsing connection string: Database must be defined in the connection string Error: 
Invalid `p.account.findUnique()` invocation in
/workspaces/chat-app/frontend/node_modules/@next-auth/prisma-adapter/dist/index.js:11:45

   8 getUserByEmail: (email) => p.user.findUnique({ where: { email } }),
   9 async getUserByAccount(provider_providerAccountId) {
  10     var _a;
→ 11     const account = await p.account.findUnique(
Error parsing connection string: Database must be defined in the connection string
    at RequestHandler.handleRequestError (/workspaces/chat-app/frontend/node_modules/@prisma/client/runtime/index.js:35038:13)
    at RequestHandler.handleAndLogRequestError (/workspaces/chat-app/frontend/node_modules/@prisma/client/runtime/index.js:34996:12)
    at /workspaces/chat-app/frontend/node_modules/@prisma/client/runtime/index.js:35542:25
    at async PrismaClient._executeRequest (/workspaces/chat-app/frontend/node_modules/@prisma/client/runtime/index.js:36111:22)
    at async PrismaClient._request (/workspaces/chat-app/frontend/node_modules/@prisma/client/runtime/index.js:36082:16)
    at async getUserByAccount (/workspaces/chat-app/frontend/node_modules/@next-auth/prisma-adapter/dist/index.js:11:29) {
  name: 'GetUserByAccountError',
  code: undefined
}
[next-auth][error][adapter_error_getUserByAccount] 
https://next-auth.js.org/errors#adapter_error_getuserbyaccount 
Invalid `p.account.findUnique()` invocation in
/workspaces/chat-app/frontend/node_modules/@next-auth/prisma-adapter/dist/index.js:11:45

   8 getUserByEmail: (email) => p.user.findUnique({ where: { email } }),
   9 async getUserByAccount(provider_providerAccountId) {
  10     var _a;
→ 11     const account = await p.account.findUnique(
Error parsing connection string: Database must be defined in the connection string {
  message: '\n' +
    'Invalid `p.account.findUnique()` invocation in\n' +
    '/workspaces/chat-app/frontend/node_modules/@next-auth/prisma-adapter/dist/index.js:11:45\n' +
    '\n' +
    '   8 getUserByEmail: (email) => p.user.findUnique({ where: { email } }),\n' +
    '   9 async getUserByAccount(provider_providerAccountId) {\n' +
    '  10     var _a;\n' +
    '→ 11     const account = await p.account.findUnique(\n' +
    'Error parsing connection string: Database must be defined in the connection string',
  stack: 'Error: \n' +
    'Invalid `p.account.findUnique()` invocation in\n' +
    '/workspaces/chat-app/frontend/node_modules/@next-auth/prisma-adapter/dist/index.js:11:45\n' +
    '\n' +
    '   8 getUserByEmail: (email) => p.user.findUnique({ where: { email } }),\n' +
    '   9 async getUserByAccount(provider_providerAccountId) {\n' +
    '  10     var _a;\n' +
    '→ 11     const account = await p.account.findUnique(\n' +
    'Error parsing connection string: Database must be defined in the connection string\n' +
    '    at RequestHandler.handleRequestError (/workspaces/chat-app/frontend/node_modules/@prisma/client/runtime/index.js:35038:13)\n' +
    '    at RequestHandler.handleAndLogRequestError (/workspaces/chat-app/frontend/node_modules/@prisma/client/runtime/index.js:34996:12)\n' +
    '    at /workspaces/chat-app/frontend/node_modules/@prisma/client/runtime/index.js:35542:25\n' +
    '    at async PrismaClient._executeRequest (/workspaces/chat-app/frontend/node_modules/@prisma/client/runtime/index.js:36111:22)\n' +
    '    at async PrismaClient._request (/workspaces/chat-app/frontend/node_modules/@prisma/client/runtime/index.js:36082:16)\n' +
    '    at async getUserByAccount (/workspaces/chat-app/frontend/node_modules/@next-auth/prisma-adapter/dist/index.js:11:29)',
  name: 'Error'
}
[next-auth][error][OAUTH_CALLBACK_HANDLER_ERROR] 
https://next-auth.js.org/errors#oauth_callback_handler_error 
Invalid `p.account.findUnique()` invocation in
/workspaces/chat-app/frontend/node_modules/@next-auth/prisma-adapter/dist/index.js:11:45

   8 getUserByEmail: (email) => p.user.findUnique({ where: { email } }),
   9 async getUserByAccount(provider_providerAccountId) {
  10     var _a;
→ 11     const account = await p.account.findUnique(
Error parsing connection string: Database must be defined in the connection string Error: 
Invalid `p.account.findUnique()` invocation in
/workspaces/chat-app/frontend/node_modules/@next-auth/prisma-adapter/dist/index.js:11:45

   8 getUserByEmail: (email) => p.user.findUnique({ where: { email } }),
   9 async getUserByAccount(provider_providerAccountId) {
  10     var _a;
→ 11     const account = await p.account.findUnique(
Error parsing connection string: Database must be defined in the connection string
    at RequestHandler.handleRequestError (/workspaces/chat-app/frontend/node_modules/@prisma/client/runtime/index.js:35038:13)
    at RequestHandler.handleAndLogRequestError (/workspaces/chat-app/frontend/node_modules/@prisma/client/runtime/index.js:34996:12)
    at /workspaces/chat-app/frontend/node_modules/@prisma/client/runtime/index.js:35542:25
    at async PrismaClient._executeRequest (/workspaces/chat-app/frontend/node_modules/@prisma/client/runtime/index.js:36111:22)
    at async PrismaClient._request (/workspaces/chat-app/frontend/node_modules/@prisma/client/runtime/index.js:36082:16)
    at async getUserByAccount (/workspaces/chat-app/frontend/node_modules/@next-auth/prisma-adapter/dist/index.js:11:29) {
  name: 'GetUserByAccountError',
  code: undefined

**Comment by Jolg42** [comment] 2022-12-22 09:47
@fwJayy This looks unrelated to this issue and a duplicate of https://github.com/prisma/prisma/issues/13647
Could you try adding a database name to your connection url like
```
mongodb+srv://user:password@cluster0.xnrtx.mongodb.net/DATABASENAME?retryWrites=true&w=majority
```
If that does not work, please create a new issue, so we can help you with that.

**Comment by jedstroke** [comment] 2023-03-27 14:58
> 

Remove the quote from your `.env` file

**Comment by franva** [comment] 2024-02-08 02:35
@jedstroke @janpio @Jolg42 Hi this issue comes back again in 5.9.1. 

With or without the quote from my `.env` file. And I have double checked that there is only one `.env` file in my project.
I also removed the `.env.local` file, so there is no any other versions of the `.env` file. So no overwrite.

Here is the link for the details: https://github.com/prisma/prisma/discussions/23000

**Comment by abdoo9** [comment] 2024-06-07 21:23
the problem is that $`npx prisma init` is automatically adding a line in the .env file you need to delete that line and it will work.

**Comment by Tobby-pro** [comment] 2024-08-30 02:56
> the problem is that $`npx prisma init` is automatically adding a line in the .env file you need to delete that line and it will work.

so you cant be specfic about how you did this. why talk in the first place ..when you can't explain to us how you fixed a problem.mtchew!

**Comment by LavGlides** [comment] 2024-09-08 20:43
> the problem is that $`npx prisma init` is automatically adding a line in the .env file you need to delete that line and it will work.

can you show the addition, my has no addition of line
