### ISSUE TITLE
MongoDB Prisma Client not creating indexes correctly

### ISSUE THREAD

**Issue by rmolinamir** [prisma/prisma#6756] opened 2021-04-23 14:41 UTC
![1](https://user-images.githubusercontent.com/40744756/115888193-a5a69a80-a420-11eb-8fa3-e3e32577dd7c.png)
![2](https://user-images.githubusercontent.com/40744756/115888195-a63f3100-a420-11eb-99fb-ac02e2626272.png)
![3](https://user-images.githubusercontent.com/40744756/115888197-a63f3100-a420-11eb-8fa2-f25a06e2e124.png)
![4](https://user-images.githubusercontent.com/40744756/115888199-a63f3100-a420-11eb-8db3-f9d4dea0956b.png)
![5](https://user-images.githubusercontent.com/40744756/115888201-a6d7c780-a420-11eb-80bc-74c70fa0a687.png)

## Bug description

Using the [Getting Started](https://www.notion.so/Getting-Started-with-MongoDB-and-Prisma-58b41c67eb554787944c600d2239801f) guide as a reference, I noticed that indexes are not being created, e.g. as intended in the schema for the Post `slug` property (attached some pics regarding this):

Afterward, I tried to create the unique index manually and as expected it won't let me because I had duplicate posts.

I dropped the duplicates and ran the script again a couple of times, this time the error is thrown after the index was manually created (as expected), but it seems like it's not handled by the client as other errors are.

## How to reproduce

1. Run `index.ts` twice (no error is thrown even though the `slug` should be unique)
2. Drop the collection
3. Run `index.ts` once
3. Manually create the index in the collection
4. Run `index.ts` again, an error should be thrown this time, but it does not seem like it's an expected error, unlike the others.
5. See attached picture for the thrown error.

## Expected behavior

I would expect the collection to be created with the correct indexes and the error to be handled similarly to others such as the type errors.

## Prisma information

```prisma
// We want to connect to the MongoDB datasource
datasource db {
  provider = "mongodb"
  url      = env("DATABASE_URL")
}

// We want to generate a typescript client
// Since mongodb is a preview feature, we'll enable that.
generator client {
  provider        = "prisma-client-js"
  previewFeatures = ["mongodb"]
}

// Create our post schema. All posts have a title, slug and body.
// The id attributes tell Prisma it's a primary key and to generate
// object ids by default when we insert posts.
model Post {
  id       String    @id @default(dbgenerated()) @map("_id") @db.ObjectId
  slug     String    @unique
  title    String
  body     String
  comments Comment[]
}

// Comments contain a comment string and connect back to the post.
// postId must have @db.ObjectId to match up with Post's id type
model Comment {
  id      String @id @default(dbgenerated()) @map("_id") @db.ObjectId
  post    Post   @relation(fields: [postId], references: [id])
  postId  String @db.ObjectId
  comment String
}
```

## Environment & setup

- OS: Windows 10 Pro
- Database: MongoDB
- Node.js version: v12.14.0
- Prisma version: v2.21.2

```

```

Edit: Of course, I forget the attachments.

**Comment by matthewmueller** [comment] 2021-04-23 14:46
Likely related to: https://github.com/prisma/prisma/issues/6727

**Comment by pantharshit00** [comment] 2021-04-30 10:50
It does indeed looks like duplicate of #6727, I am going to close this.

**Closed by pantharshit00** 2021-04-30 10:50 UTC
Labels: bug/1-repro-available, kind/bug, process/candidate, team/client, topic: mongodb
