### ISSUE TITLE
Libsql adapter broken with Next.js

### ISSUE THREAD

**Issue by moljac024** [prisma/prisma#22231] opened 2023-12-04 02:02 UTC
Trying to build a simple next.js project with prisma and the new libsql adapter to support turso. This is the error I am running into:

```
 ✓ Linting and checking validity of types    
   ▲ Next.js 14.0.2
   - Environments: .env

Failed to compile.

./node_modules/@prisma/adapter-libsql/dist/index.mjs
Module not found: Can't resolve 'util/types'

```

**Comment by janpio** [comment] 2023-12-12 10:41
Can you help us by putting such a simple Next.js on GitHub so we can use it to reproduce the problem? Thanks.

**Comment by Jolg42** [comment] 2024-01-19 11:02
Since I reproduced a similar case using https://github.com/mmachatschek/repro_nextjs_neon_driveradapter_issue I adapted it and could not reproduce the issue mentioned here.
Repo: https://github.com/Jolg42/repro_nextjs_neon_driveradapter_issue/tree/repro-22231

Logs
```
/workspaces/repro_nextjs_neon_driveradapter_issue/nextjs (main) $ npm run dev

> dev
> next

   ▲ Next.js 14.0.2
   - Local:        http://localhost:3000

 ✓ Ready in 1841ms
 ○ Compiling /api/prisma ...
 ✓ Compiled /api/prisma in 578ms (64 modules)
[ { id: 1, title: 'Test title', createdAt: 2024-01-19T10:50:44.583Z } ]
```

I tried using `5.8.0-dev.38` and the most recent `@erly-access` version (`5.9.0-dev.11`).

@moljac024 Could you help us reproduce this? Without more information, we would later close this issue.

**Comment by moljac024** [comment] 2024-01-19 12:46
I have since moved on from both libsql and prisma. Closing the issue.

**Closed** 2024-01-19 12:46 UTC
Labels: bug/0-unknown, kind/bug, topic: Next.js, team/client, topic: esm, topic: serverless database driver, topic: driverAdapters, topic: turso, topic: @prisma/adapter-libsql
