### ISSUE TITLE
Result types are incorrectly inferred from `select` when Models have optional relationships.

### ISSUE THREAD

**Issue by shadoath** [prisma/prisma#20405] opened 2023-07-26 14:34 UTC
### Bug description

I'm getting a result type that tells me all the values will be defined when the underlying data is missing relationships and or the selected value is NULL.  Example below

### How to reproduce

1. Create schema as outlined below
2. Run schema generate
3. Create the Prisma query and check the result types
4. Discover the bug.

### Expected behavior

I would expect the type without the where clause to have been:
```ts
type resultType: {
    id: string;
    demographic: {
        birthDate: Date | null;
    } | null;
}[]
```

### Prisma information

```prisma
generator client {
  provider      = "prisma-client-js"
  binaryTargets = ["native", "debian-openssl-3.0.x"]
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}


// Minimized student schema
model Student {
  id                                  String                         @id @default(dbgenerated("uuid_generate_v4()")) @db.Uuid
  firstName                           String                         @map("first_name")
  middleName                          String?                        @map("middle_name")
  lastName                            String                         @map("last_name")
  demographicId                       String?                        @map("demographic_id") @db.Uuid
  demographic                         Demographic?                   @relation(fields: [demographicId], references: [id], onDelete: NoAction, onUpdate: NoAction)
  createdBy                           Unsupported("name")?
  @@map("students")
}

// Partial demographics model
model Demographic {
  id                                          String                         @id @default(dbgenerated("uuid_generate_v4()")) @db.Uuid
  birthDate                                   DateTime?                      @map("birth_date") @db.Date
  students                                    Student[]
  createdBy                                   Unsupported("name")?
  @@map("demographics")
}

// I included the `createdBy` field as it is Unsupported incase that is part of this issue.

```

```ts
// My initial select:
    const studentBirthDates = await prisma.student.findMany({
      where: {
        id: {
          in: ids,
        },
      },
      select: {
        id: true,
        demographic: {
          select: {
            birthDate: true,
          },
        },
      },
    })


// Updated Select with expanded where for demographic values
    const studentBirthDates = await prisma.student.findMany({
      where: {
        id: {
          in: ids,
        },
        demographic: {
          birthDate: {
            not: null,
          },
        },
      },
      select: {
        id: true,
        demographic: {
          select: {
            birthDate: true,
          },
        },
      },
    })
 ```
 
 In both cases the type is:
 ```ts
type resultType: {
    id: string;
    demographic: {
        birthDate: Date;
    };
}[]
```

### Environment & setup

- OS: macOS => 13.4.1 (c) (22F770820d)
- Database: PostgreSQL
- node -v  => v14.19.3
- 

### Prisma Version

```
Environment variables loaded from .env
prisma                  : 4.16.1
@prisma/client          : 4.16.1
Current platform        : darwin-arm64
Query Engine (Node-API) : libquery-engine b20ead4d3ab9e78ac112966e242ded703f4a052c (at node_modules/@prisma/engines/libquery_engine-darwin-arm64.dylib.node)
Migration Engine        : migration-engine-cli b20ead4d3ab9e78ac112966e242ded703f4a052c (at node_modules/@prisma/engines/migration-engine-darwin-arm64)
Format Wasm             : @prisma/prisma-fmt-wasm 4.16.0-66.b20ead4d3ab9e78ac112966e242ded703f4a052c
Default Engines Hash    : b20ead4d3ab9e78ac112966e242ded703f4a052c
Studio                  : 0.484.0
```

**Comment by janpio** [comment] 2023-08-07 09:46
Thanks for the issue @shadoath. Does the problem still exist with Prisma 5, specifically 5.1.1?

(Internal note for reproduction: Reproduce with 4.16.2 first, then if confirmed see if problem persists in 5.1)

**Comment by SevInf** [comment] 2023-08-21 15:56
Hi @shadoath!
Unfortunately, I could not reproduce the issue with the information you provided, neither on 5.1.1 nor on 4.16.1 version that you reported. Type for `demographics` and `birthDate` include `null` for me in both cases. Could you maybe share the repository where we could see it happen?

Thank you!

**Comment by janpio** [comment] 2023-10-29 21:12
DId you see Serhii's request @shadoath? We need more information to be able to reproduce. Thanks!

**Comment by SevInf** [comment] 2024-02-02 10:28
Hey @shadoath ,
 

With the lack of information and our inability to reproduce this issue, we're now closing it. Feel free to comment if you have any updates about it.
 
Thank you 🙏

**Closed by SevInf** 2024-02-02 10:28 UTC
Labels: bug/1-unconfirmed, kind/bug, topic: client types, team/client, topic: optional relation
