### ISSUE TITLE
GroupByOutputType make 'count'. I also have 'count'. -> type error

### ISSUE THREAD

**Issue by SeonghuiChoe** [prisma/prisma#6706] opened 2021-04-22 02:10 UTC
Hi Prisma Team! 

## Bug description

I'm trying to upgrade prisma 2.19.0 to 2.21.2.
Every GroupByOutputType has `count`.  My model also has `count`.
When I try 'tsc', I got a type error about duplicate names.
![Screen Shot 2021-04-22 at 10 38 07 AM](https://user-images.githubusercontent.com/18391559/115644232-2f8b3080-a359-11eb-9321-70ec983832c0.png)
![Screen Shot 2021-04-22 at 10 38 27 AM](https://user-images.githubusercontent.com/18391559/115644236-30bc5d80-a359-11eb-8654-bcd7b8908889.png)

## How to reproduce

```bash
❯ rm -rf node_modules/ && npm i && tsc
```

## Expected behavior

Should I change the name of count to solve this type error?

## Prisma information

```graphql
generator client {
  provider      = "prisma-client-js"
  binaryTargets = ["native", "debian-openssl-1.1.x"]
}

model MarketProductGroup {
  id                 String          @id @default(cuid())
  count              Int?            @default(0)
  orderCount         Int?            @default(0)
  marketProductCount Int?            @default(0)
  deletedAt          DateTime?
  createdAt          DateTime        @default(now())
  updatedAt          DateTime        @updatedAt
}
```

## Environment & setup

- OS: Mac OS
- Database: MySQL
- Node.js version: v14.5.0
- Prisma version: 2.21.2

@prisma/client: 2.21.2
nexus-plugin-prisma: 0.34.1
prisma: 2.21.2

**Comment by 2color** [comment] 2021-04-22 10:53
I can confirm this.

With the following model:

```prisma
model User {
  id    Int    @id @default(autoincrement())
  name  String @unique
  count Int
}
```

The generated code has a type error:

```
export type UserGroupByOutputType = {
    id: number
    name: string
    count: number
    count: UserCountAggregateOutputType | null
    avg: UserAvgAggregateOutputType | null
    sum: UserSumAggregateOutputType | null
    min: UserMinAggregateOutputType | null
    max: UserMaxAggregateOutputType | null
  }
```


```
Duplicate identifier 'count'.ts(2300)
Subsequent property declarations must have the same type.  Property 'count' must be of type 'number', but here has type 'UserCountAggregateOutputType | null'.ts(2717)
```

--- 
Prisma version

```
prisma               : 2.21.2
@prisma/client       : 2.21.2
Current platform     : darwin
Query Engine         : query-engine e421996c87d5f3c8f7eeadd502d4ad402c89464d (at node_modules/@prisma/engines/query-engine-darwin)
Migration Engine     : migration-engine-cli e421996c87d5f3c8f7eeadd502d4ad402c89464d (at node_modules/@prisma/engines/migration-engine-darwin)
Introspection Engine : introspection-core e421996c87d5f3c8f7eeadd502d4ad402c89464d (at node_modules/@prisma/engines/introspection-engine-darwin)
Format Binary        : prisma-fmt e421996c87d5f3c8f7eeadd502d4ad402c89464d (at node_modules/@prisma/engines/prisma-fmt-darwin)
Default Engines Hash : e421996c87d5f3c8f7eeadd502d4ad402c89464d
Studio               : 0.371.0
```

**Comment by janpio** [comment] 2021-04-22 18:36
Similar bug: https://github.com/prisma/prisma/issues/6344
This one is in the current sprint to be looked at.

**Comment by SeonghuiChoe** [comment] 2021-04-22 22:06
@janpio Thank you and sorry for making similar issue 🥺
Yes this issue is same situation.  #6344
I'll check issues more carefully befor making issues.
Always thank you a lot. Should I close this issue?

**Comment by pantharshit00** [comment] 2021-04-23 12:50
I am going to close this as duplicate of #6344 


Thanks for reporting anyways.

**Closed by pantharshit00** 2021-04-23 12:50 UTC
Labels: bug/2-confirmed, kind/bug, team/client, tech/typescript, topic: types

**Comment by janpio** [comment] 2021-04-23 14:06
No worries, we totally prefer a 1000 duplicate issues to not having issues at all 👍 @SeonghuiChoe
