### ISSUE TITLE
Prisma Client: Error thown on passing `null` to connect

### ISSUE THREAD

**Issue by ryands17** [prisma/prisma#2271] opened 2020-04-22 10:35 UTC
#  Bug description

`prisma-client` throws an error when `null` is passed to `connect`.

## How to reproduce

1. Create a simple model with relations

2. Run this snippet

```ts
 await prisma.user.create({
    data: {
      name: 'User',
      posts: {
        connect: null,
      },
    },
  })
```

TypeScript doesn't complain as in the types file this is present

```ts
export type PostCreateManyWithoutAuthorInput = {
  create?: Enumerable<PostCreateWithoutAuthorInput> | null
  connect?: Enumerable<PostWhereUniqueInput> | null
}
```

But on running this, the following error is generated

```
Invalid `prisma.user.create()` invocation:

{
  data: {
    name: 'User',
    posts: {
      connect: {
?       id?: Int
      }
    }
  }
}

Argument data.posts.connect of type PostWhereUniqueInput needs at least one argument. Available args are listed in green.
```

And the following issue is faced while directly assigning `null` to the relation

```ts
await prisma.user.create({
    data: {
      name: 'User',
      posts: null,
    },
  })
```

```
Failed to validate the query `Error occurred during query validation & transformation:
Assertion error: Attempted conversion of non-map ParsedInputValue (Single(Null)) into map failed..` at ``
```

## Expected behavior

The type-checking system should provide the specific error instead of obtaining it at runtime.

## Prisma information

```prisma
datasource db {
  provider = "sqlite"
  url      = "file:./dev.db"
}

generator photon {
  provider = "prisma-client-js"
}

model User {
  id        Int      @default(autoincrement()) @id
  name      String
  createdAt DateTime @default(now())
  updatedAt DateTime @updatedAt
  posts     Post[]
}

model Post {
  id        Int     @default(autoincrement()) @id
  title     String
  content   String?
  author    User?   @relation(fields: [author_id], references: [id])
  author_id Int?
}
```

## Environment & setup

- OS: Debian
- Database: SQLite
- Prisma version: 2.0.0-beta.2
- Node.js version: 10.20.0

**Comment by dpetrick** [comment] 2020-04-22 11:20
Duplicate of https://github.com/prisma/prisma-client-js/issues/614

**Closed by dpetrick** 2020-04-22 11:20 UTC

**Comment by ifightcrime** [comment] 2023-02-02 23:16
Can this be reopened? I'm running into this on prisma 4.9.0 when passing undefined to an optional relation. Typescript tells me I can, but it fails on runtime. 😱 

![Screen Shot 2023-02-02 at 5 15 25 PM](https://user-images.githubusercontent.com/616525/216472463-f01dc0ef-d9cd-4663-906b-5273f41fe065.png)

**Comment by janpio** [comment] 2023-02-03 00:16
No, please open a new issue and fill the full bug issue template and provide all the information it asks for. Optimally also a reproduction project. Thanks.

**Comment by inferusvv** [comment] 2023-05-29 18:22
Do we have a new issue for that? The same for me. I have "PATCH" method in REST API. If `id` is undefined I want to do nothing. For disconnect there are different way, so probably it is an issue
