### ISSUE TITLE
Update fails when querying nullable field with "not" operator when field is NULL using extendedWhereUnique

### ISSUE THREAD

**Issue by herzog0** [prisma/prisma#16880] opened 2022-12-17 17:41 UTC
## Bug description
Having this data model: 
```prisma
model User {
  id   Int     @id @default(autoincrement())
  name String?
  key  String  @default("something")
}
```

with this row in the database: 
```sql
INSERT INTO "User" VALUES (1, default, default);
```

and this operation: 
```ts
await prisma.user.update({
    where: {
        id: 1,
        name: {
            not: "Bob"
        }
    },
    data: {
        name: "Alice"
    }
})
``` 
We have the error: 
`An operation failed because it depends on one or more records that were required but not found. Record to update not found.`   

## Expected behavior
The query should update the row where the unique id is 1, because the field `name` is not "Bob" in the database. It is NULL.   

## Reproducible example

Run the code above or just [clone this repo](https://github.com/herzog0/prisma-bug-test)

## Environment & Setup
- OS: Linux Mint 21
- Database: PostgreSQL
- Node.js version: 16.15.0

## Prisma Version
```
yarn run v1.22.19
$ /home/lupin/Projects/mentora/repos/mentora-copa/node_modules/.bin/prisma version
Environment variables loaded from .env
prisma                  : 4.7.1
@prisma/client          : 4.7.1
Current platform        : debian-openssl-3.0.x
Query Engine (Node-API) : libquery-engine 272861e07ab64f234d3ffc4094e32bd61775599c (at node_modules/@prisma/engines/libquery_engine-debian-openssl-3.0.x.so.node)
Migration Engine        : migration-engine-cli 272861e07ab64f234d3ffc4094e32bd61775599c (at node_modules/@prisma/engines/migration-engine-debian-openssl-3.0.x)
Introspection Engine    : introspection-core 272861e07ab64f234d3ffc4094e32bd61775599c (at node_modules/@prisma/engines/introspection-engine-debian-openssl-3.0.x)
Format Binary           : prisma-fmt 272861e07ab64f234d3ffc4094e32bd61775599c (at node_modules/@prisma/engines/prisma-fmt-debian-openssl-3.0.x)
Format Wasm             : @prisma/prisma-fmt-wasm 4.7.1-1.272861e07ab64f234d3ffc4094e32bd61775599c
Default Engines Hash    : 272861e07ab64f234d3ffc4094e32bd61775599c
Studio                  : 0.477.0
Preview Features        : postgresqlExtensions, extendedWhereUnique
Done in 0.94s.

```

**Comment by herzog0** [comment] 2022-12-17 17:44
Currently, I'm using an alternative form of executing this statement:  
```ts
await prisma.user.update({
        where: {
            id: 1,
            OR: [
                {
                    name: {
                        not: "Bob"
                    }
                },
                {
                    name: null
                }
            ]
        },
        data: {
            name: "Alice"
        }
    })
```

**Comment by aqrln** [comment] 2023-05-25 18:36
Reproducible with latest `main`.

**Comment by Weakky** [comment] 2023-05-31 15:30
Hey @herzog0,

While I understand the confusion, this is _not_ a bug. Null is always a special value that can't be compared to other values. It's the reason why there is an `IS` operator. If you want to include null values, you should explicitly include them.

```ts
await prisma.user.update({
    where: {
       id: 1,
       OR: [
        { name: { not: "Bob" } },
        { name: null },
       ]
    },
    data: {
        name: "Alice"
    }
})
```

Which will roughly translate to:

```sql
WHERE id = 1 AND (name <> "Bob" OR name IS NULL)
```

Hope that makes sense to you, closing now 🙏🏻

**Closed by Weakky** 2023-05-31 15:30 UTC
Labels: bug/2-confirmed, kind/bug, topic: previewFeatures, topic: null, team/client, topic: postgresql, topic: extendedWhereUnique
