### ISSUE TITLE
`contains` string filter not working with mongoDB

### ISSUE THREAD

**Issue by michaelspeed** [prisma/prisma#10267] opened 2021-11-15 14:04 UTC
### Bug description

```
this.prismaService.products.findMany({
      where: {
        name: {
          contains: search,
        },
      },
    });
```

in this query the result returned is 0
but contains should match documents with filed names containing the search term

### How to reproduce

1. Created model called products
Model described below
```
model Products {
    id          String          @id @default(dbgenerated()) @map("_id") @db.ObjectId
    createdAt   DateTime        @default(now())
    updatedAt   DateTime        @updatedAt
    name        String
}
```
3. run js query as described above

### Expected behavior

but contains should match documents with filed names containing the search term

### Prisma information

`"@prisma/client": "^3.4.1",`
`"prisma": "^3.4.1",`

### Environment & setup

- OS: Mac OS
- Database: MongoDb
- Node.js version: v14.16.0

### Prisma Version

```
`"@prisma/client": "^3.4.1",`
`"prisma": "^3.4.1",`
```

**Comment by matthewmueller** [comment] 2022-03-02 21:54
@michaelspeed I wasn't able to reproduce this:


```prisma
// This is your Prisma schema file,
// learn more about it in the docs: https://pris.ly/d/prisma-schema

generator client {
  provider        = "prisma-client-js"
  previewFeatures = ["mongoDb"]
}

datasource db {
  provider = "mongodb"
  url      = env("DATABASE_URL")
}

model Product {
  id        String   @id @default(auto()) @map("_id") @db.ObjectId
  createdAt DateTime @default(now())
  updatedAt DateTime @updatedAt
  name      String
}
```

script.ts

```ts
import { PrismaClient, Prisma } from "@prisma/client"
const prisma = new PrismaClient()

async function main() {
  await prisma.$connect()
  await prisma.product.deleteMany()
  await prisma.product.create({
    data: {
      name: "Shoes",
    },
  })
  const results = await prisma.product.findMany({
    where: {
      name: {
        contains: "oe",
      },
    },
  })
  console.log(results)
}

main()
  .catch(console.error)
  .finally(() => prisma.$disconnect())
```

```
Environment variables loaded from .env
prisma                  : 3.11.0-dev.30
@prisma/client          : 3.11.0-dev.30
Current platform        : darwin
Query Engine (Node-API) : libquery-engine 4cac12afbeef2fa3eedf1cb87c79bc15e2648836 (at node_modules/@prisma/engines/libquery_engine-darwin.dylib.node)
Migration Engine        : migration-engine-cli 4cac12afbeef2fa3eedf1cb87c79bc15e2648836 (at node_modules/@prisma/engines/migration-engine-darwin)
Introspection Engine    : introspection-core 4cac12afbeef2fa3eedf1cb87c79bc15e2648836 (at node_modules/@prisma/engines/introspection-engine-darwin)
Format Binary           : prisma-fmt 4cac12afbeef2fa3eedf1cb87c79bc15e2648836 (at node_modules/@prisma/engines/prisma-fmt-darwin)
Default Engines Hash    : 4cac12afbeef2fa3eedf1cb87c79bc15e2648836
Studio                  : 0.458.0
Preview Features        : mongoDb
```

Do you mind trying again? Could it be your collation settings?

**Comment by janpio** [comment] 2022-03-11 19:59
Ping @michaelspeed

**Comment by matthewmueller** [comment] 2022-03-14 22:37
Closing, but happy to re-open if this pops back up.

**Closed by matthewmueller** 2022-03-14 22:37 UTC
Labels: bug/0-unknown, kind/bug, team/client, topic: mongodb

**Comment by JuanDa237** [comment] 2023-01-30 21:24
> @michaelspeed I wasn't able to reproduce this:
> 
> ```prisma
> // This is your Prisma schema file,
> // learn more about it in the docs: https://pris.ly/d/prisma-schema
> 
> generator client {
>   provider        = "prisma-client-js"
>   previewFeatures = ["mongoDb"]
> }
> 
> datasource db {
>   provider = "mongodb"
>   url      = env("DATABASE_URL")
> }
> 
> model Product {
>   id        String   @id @default(auto()) @map("_id") @db.ObjectId
>   createdAt DateTime @default(now())
>   updatedAt DateTime @updatedAt
>   name      String
> }
> ```
> 
> **main.ts**
> 
> ```ts
> import { PrismaClient, Prisma } from "@prisma/client"
> const prisma = new PrismaClient()
> 
> async function main() {
>   await prisma.$connect()
>   await prisma.product.deleteMany()
>   await prisma.product.create({
>     data: {
>       name: "Shoes",
>     },
>   })
>   const results = await prisma.product.findMany({
>     where: {
>       name: {
>         contains: "oe",
>       },
>     },
>   })
>   console.log(results)
> }
> 
> main()
>   .catch(console.error)
>   .finally(() => prisma.$disconnect())
> ```
> 
> ```shell
> $ ts-node index.ts
> [
>   {
>     id: '621fe774ef9be0fcb6a5c406',
>     createdAt: 2022-03-02T21:53:56.253Z,
>     updatedAt: 2022-03-02T21:53:56.253Z,
>     name: 'Shoes'
>   }
> ]
> ```
> 
> Version:
> 
> ```
> Environment variables loaded from .env
> prisma                  : 3.11.0-dev.30
> @prisma/client          : 3.11.0-dev.30
> Current platform        : darwin
> Query Engine (Node-API) : libquery-engine 4cac12afbeef2fa3eedf1cb87c79bc15e2648836 (at node_modules/@prisma/engines/libquery_engine-darwin.dylib.node)
> Migration Engine        : migration-engine-cli 4cac12afbeef2fa3eedf1cb87c79bc15e2648836 (at node_modules/@prisma/engines/migration-engine-darwin)
> Introspection Engine    : introspection-core 4cac12afbeef2fa3eedf1cb87c79bc15e2648836 (at node_modules/@prisma/engines/introspection-engine-darwin)
> Format Binary           : prisma-fmt 4cac12afbeef2fa3eedf1cb87c79bc15e2648836 (at node_modules/@prisma/engines/prisma-fmt-darwin)
> Default Engines Hash    : 4cac12afbeef2fa3eedf1cb87c79bc15e2648836
> Studio                  : 0.458.0
> Preview Features        : mongoDb
> ```
> 
> Do you mind trying again? Could it be your collation settings?

Your example works because it will return all the data, if you instert one more row that doesnt contains "oe" with will return it as well.

**Comment by codeinearts** [comment] 2024-02-12 03:38
Hey @matthewmueller 

I got this issue when `[]` character gets searched within the string. 

Given the following schema 

```prisma
datasource db {
  provider = "mongodb"
  url      = env("MONGO_URL")
}

generator client {
  provider      = "prisma-client-js"
  binaryTargets = ["native", "linux-musl"]
}

model User {
  id            String         @id @default(auto()) @map("_id") @db.ObjectId
  firstName     String
  lastName      String
}
```

This snippet causes the issue to appear

```typescript
import { PrismaClient } from "@prisma/client";

async function prismaSketch() {
  const prisma = new PrismaClient();

  const deleted = await prisma.user.deleteMany();
  console.log(deleted);

  const created = await prisma.user.createMany({
    data: [
      { firstName: "CARLOS", lastName: "SUAZO [DOCTOR]" },
      { firstName: "ATILA", lastName: "GENESIS [NURSE]" },
      { firstName: "BOB", lastName: "DYLAN [NURSE]" },
      { firstName: "MARK", lastName: "RENTON [DOCTOR]" },
    ],
  });
  console.log(created);

  const correctResults = await prisma.user.findMany({
    where: {
      lastName: { contains: "NURSE" },
    },
  });

  console.log(correctResults);
  /*
[
  {
    id: '65c98f233edab806443a6061',
    firstName: 'ATILA',
    lastName: 'GENESIS [NURSE]'
  },
  {
    id: '65c98f233edab806443a6062',
    firstName: 'BOB',
    lastName: 'DYLAN [NURSE]'
  }
]
  */

  const randomResults = await prisma.user.findMany({
    where: {
      lastName: { contains: "[NURSE]" },
    },
  });

  console.log(randomResults);
  /* 
[
  {
    id: '65c98f233edab806443a6060',
    firstName: 'CARLOS',
    lastName: 'SUAZO [DOCTOR]'
  },
  {
    id: '65c98f233edab806443a6061',
    firstName: 'ATILA',
    lastName: 'GENESIS [NURSE]'
  },
  {
    id: '65c98f233edab806443a6062',
    firstName: 'BOB',
    lastName: 'DYLAN [NURSE]'
  },
  {
    id: '65c98f233edab806443a6063',
    firstName: 'MARK',
    lastName: 'RENTON [DOCTOR]'
  }
]
  NANI!?
  */

  await prisma.$disconnect();
}

prismaSketch();
```

Didn't know if this is a known issue or if I should open a new one for it, but since this is the most similar issue i've found associated with my problem I'm posting it here.

I've left a small reproduction repo at https://github.com/codeinearts/prisma-bug-contains

**Comment by janpio** [comment] 2024-02-12 11:19
Please open a new issue @codeinearts, that will make it easier to triage this. (Link to this one for context of course). Thanks!

**Comment by tanvirgeek** [comment] 2025-02-01 23:14
Faced same issue. Can't find if string contains parenthesis, using prisma contains.
