### ISSUE TITLE
Since v2.4 prisma generate no longer works in yarn workspaces

### ISSUE THREAD

**Issue by djgrant** [prisma/prisma#3208] opened 2020-08-04 23:30 UTC
## Bug description

Running `prisma generate` within yarn workspaces fails with the error:

```sh
Running this command will add the dependency to the workspace root rather than the workspace itself,
which might not be what you want - if you really meant it, make it explicit by running this command 
again with the -W flag (or --ignore-workspace-root-check).
```

## How to reproduce

1. Set up yarn workspaces in your repo
2. Set up prisma 2.4 (with prisma folder at root)
3. npx prisma generate

## Expected behavior

The prisma types should be generated successfully.

## Environment & setup

- OS: Mac OS
- Database: PostgreSQL
- Node.js version: 14.4
- Prisma version: 2.4

**Comment by pantharshit00** [comment] 2020-08-05 21:01
I am unable to reproduce this with 2.4.1:
<img width="1213" alt="image" src="https://user-images.githubusercontent.com/22195362/89463030-efb0f880-d78b-11ea-940f-53d7bde7996a.png">


Here is reproduction that I used: https://github.com/harshit-test-org/prisma-issue-3208

**Comment by marvinroger** [comment] 2020-09-25 22:17
This happens when you don't have a `@prisma/client` in your `dependencies`. Adding the dependency fixes the issue!

**Comment by pantharshit00** [comment] 2020-09-28 11:05
@marvinroger This is kind of expected as yarn won't let us install the client automatically on a monorepo root with the `-W` flag. I am also not sure that should be the case as you typically want to install it in the backend package.

**Comment by marvinroger** [comment] 2020-09-28 13:24
@pantharshit00 Yes, I am not saying it's a bug, it's just confusing in this edge case: initially, my project wasn't in a monorepo setup, and everything was fine, because I had `@prisma/cli` installed in the only package I had. I forgot to install `@prisma/client`, but it was not problematic, because, as you said, the CLI installs the client automatically.

However, when I splitted my code as multiple packages, I installed `@prisma/cli` in the workspace root, and running `prisma generate` failed with the same error as OP. I think the CLI should warn us if `@prisma/client` is not installed, instead of trying to install automatically when ran in a monorepo root - which will fail.

**Comment by timsuchanek** [comment] 2020-10-05 13:50
It sounds like everything is working fine, if the dependency is installed.
But we should still make sure, that the situation you just described @marvinroger works and we handle it with a proper error at least.

**Comment by marvinroger** [comment] 2020-10-05 14:01
@timsuchanek exactly, therefore, this is not a critical issue, just a nice-to-have. In the meantime, people having this error will stumble upon this GitHub issue.

**Comment by janpio** [comment] 2024-03-02 10:06
Closing this as we have a more popular issue about this here: https://github.com/prisma/prisma/issues/8765

**Closed by janpio** 2024-03-02 10:06 UTC
Labels: kind/improvement, topic: yarn workspaces, team/client
