### ISSUE TITLE
$transaction api with Array.map resolves to never[].

### ISSUE THREAD

**Issue by gleant** [prisma/prisma#5781] opened 2021-02-22 13:10 UTC
## Bug description

$transaction api with Array.map resolves to never[].

## How to reproduce

Using the following code will produce never[] as a result.

```typescript
const result = await prisma.$transaction(
      users.map(({name}) =>
          prisma.user.create({
               select: {
                    id: true,
                },
                data: {
                    name,
                }
          }),
      ),
  )
```

## Expected behavior

Result array items should be typed as prisma.user.create return type.

This has worked as expected on version 2.16.x.

## Environment & setup

- OS: Mac OS
- Database: Postgresql
- Node.js version: 12.16.3
- Prisma version: 2.17.0

**Comment by pantharshit00** [comment] 2021-02-26 16:12
Fixed in `dev` channel. Closing as duplicate of https://github.com/prisma/prisma/issues/5688. I will the part of 2.18

**Closed by pantharshit00** 2021-02-26 16:12 UTC
