### ISSUE TITLE
$queryRaw with improvedQueryRaw returning string for Decimal MySQL type

### ISSUE THREAD

**Issue by jdmoliner** [prisma/prisma#13708] opened 2022-06-08 16:19 UTC
### Bug description

Hi,

Using new `improvedQueryRaw` I can solve the old problem with precision but I get `string` instead of `number` for Decimal MySQL type

MySQL Table "test"

 ```
Column   |  Type        
------------------------
id | int(11)
test_decimal   | decimal (5,3) 
test_float | float
test_double | double
```

```
INSERT INTO `test` (`id`, `decimal_test`, `float_test`, `double_test`) VALUES (NULL, 3.147, 3.147, 3.147);
```
```
const test = await prisma.$queryRaw`SELECT decimal_test, float_test, double_test FROM test WHERE id = 1`;
console.log(test); 

test: [
  {
    decimal_test: "3.147", // I get string instead of number
    float_test: 3.1470000743865967, // precision bug
    double_test: 3.147 // correct
  }
]

```

### Environment & setup

- OS: Mac OS
- Database: MySQL
- Node.js version: v16.14.2

### Prisma Version

```
prisma                  : 3.15.0
@prisma/client          : 3.15.0
Current platform        : darwin
Query Engine (Node-API) : libquery-engine b9297dc3a59307060c1c39d7e4f5765066f38372 (at node_modules/@prisma/engines/libquery_engine-darwin.dylib.node)
Migration Engine        : migration-engine-cli b9297dc3a59307060c1c39d7e4f5765066f38372 (at node_modules/@prisma/engines/migration-engine-darwin)
Introspection Engine    : introspection-core b9297dc3a59307060c1c39d7e4f5765066f38372 (at node_modules/@prisma/engines/introspection-engine-darwin)
Format Binary           : prisma-fmt b9297dc3a59307060c1c39d7e4f5765066f38372 (at node_modules/@prisma/engines/prisma-fmt-darwin)
Default Engines Hash    : b9297dc3a59307060c1c39d7e4f5765066f38372
Studio                  : 0.462.0
Preview Features        : filterJson, improvedQueryRaw

```

**Comment by garrensmith** [comment] 2022-06-30 12:47
@jdmoliner would you mind testing this with Prisma version 4.0.

**Comment by matthewmueller** [comment] 2022-07-15 13:23
Ping @jdmoliner. Please re-test.

**Comment by jdmoliner** [comment] 2022-07-18 11:16
@garrensmith @matthewmueller updated to prisma 4.0.0 and same bug:

```
const test = await prisma.$queryRaw`SELECT decimal_test, float_test, double_test FROM test WHERE id = 1`;
console.log(test); 

test: [
  {
    decimal_test: "3.147", // I get string instead of number
    float_test: 3.1470000743865967, // precision bug
    double_test: 3.147 // correct
  }
]
```

**Comment by Weakky** [comment] 2022-08-22 14:54
Hey @jdmoliner,

I can't reproduce your issue with Decimal. I migrated a col of type `decimal(5,3)` and ran the same query as you did.

<img width="957" alt="image" src="https://user-images.githubusercontent.com/25233379/185951775-d8e67c81-61ba-4d5d-a083-02fa693f0803.png">

Now, I initially thought you simply got confused because `Decimal` objects are printed as regular numbers. But you are seeing a decimal of type string, and I'm not.

Would you mind sharing your MySQL version? This is the only difference I can think of right now.

**Comment by janpio** [comment] 2022-09-23 13:55
Ping @jdmoliner. Can you help us out here? Otherweise we will have to close this issue as we can not reproduce the problem - which makes it impossible for us to fix it of course. Thanks.

**Comment by janpio** [comment] 2022-10-19 16:33
Once more @jdmoliner, without your help we can not proceed here. Thanks!

**Comment by janpio** [comment] 2022-11-25 00:09
Closing then until someone provides more information. Please comment or open a new issue. Thanks!

**Closed by janpio** 2022-11-25 00:09 UTC
Labels: bug/0-unknown, kind/bug, team/client, topic: improvedQueryRaw
