### ISSUE TITLE
Can't do nested orderBy

### ISSUE THREAD

**Issue by pasekit** [prisma/prisma#3891] opened 2020-10-10 14:33 UTC
## Bug description

Type '{ orderBy: { driveLetter: string; }; select: { driveLetter: true; }; }' is not assignable to type 'boolean | FolderArgs'.
  Object literal may only specify known properties, and 'orderBy' does not exist in type 'FolderArgs'.ts(2322)
index.d.ts(53640, 3): The expected type comes from property 'Folder' which is declared here on type 'FolderAccessInclude'

## How to reproduce

    model folderAccess {
      id          Int       @id @default(autoincrement())
      folderId    Int
      access      Boolean
      Folder   Folder @relation(fields: [folderId], references: [id])
    }
    model SupFolder {
      id              Int               @id @default(autoincrement())
      folder          String
      driveLetter     String
      FolderAccess FolderAccess[]
    }

		return this.prisma.folderAccess.findMany({
			include: {
				Folder: {
					orderBy: {
						driveLetter: 'asc'
					},
					select: {
						driveLetter: true
					}
					
				},
			},
		});

## Expected behavior

Output Orderd By DriveLetter

## Environment & setup

- OS: Windows
- Database: MariaDB
- Nest.js version: 7.4
- Prisma version: 2.8.0

**Comment by pantharshit00** [comment] 2020-10-12 09:32
Hi,

Thanks for reporting this! It has already been reported before, so I am going to close this as a duplicate of https://github.com/prisma/prisma-client-js/issues/249

**Closed by pantharshit00** 2020-10-12 09:32 UTC
