### ISSUE TITLE
Allow relation disconnect without knowing current state of relation

### ISSUE THREAD

**Issue by mcsdevv** [prisma/prisma#4194] opened 2020-11-09 12:05 UTC
## Problem

The use of `disconnect` will throw an error if no relation is present. However, there are many cases where the user may not know whether or not a relation exists while wanting to ensure it that, whatever the current state, a relation does not exist after the database call is made.

Because of this, more code needs to be written to figure out whether a relation exists before making the database call.

## Suggested solution

The suggested solution is to simply not error when `disconnect` is called and no relation is present.

**Comment by pantharshit00** [comment] 2020-11-10 13:28
Hi,

Thanks for reporting this! It has already been reported before, so I am going to close this as a duplicate of https://github.com/prisma/prisma/issues/3069

**Closed by pantharshit00** 2020-11-10 13:28 UTC

**Comment by pantharshit00** [comment] 2020-11-10 13:31
Related epic: https://github.com/prisma/prisma-client-js/issues/896
