### ISSUE TITLE
Problem with trying import own data

### ISSUE THREAD

**Issue by strelov1** [prisma/prisma#2648] opened 2018-06-18 18:15 UTC
Problem with trying import own data

1. I create NDF json data from import :
`
{
    "valueType": "nodes",
    "values": [{
        "_typeName": "Phrase",
        "id": "cjikk1hkj00009b7a4inrd3yi",
        "startTime": "400",
        "stopTime": "2325",
        "originalText": "For everything there is a season,",
    }, {
        "_typeName": "Phrase",
        "id": "cjikk1hkj00019b7al5s4buok",
        "startTime": "2325",
        "stopTime": "5000",
        "originalText": "and a time for every purpose under heaven:",
    }]
}
`
* for id I use package cuid()
2.  Compress to export.zip as I got after **prisma export**
3. I trying **prisma import --data export.zip**
4. I got [https://imgur.com/6X5rszi](https://imgur.com/6X5rszi) :
`
Unzipping 12ms
Validating data 9ms

Uploading nodes...
 ▸    {
 ▸    "errors": [
 ▸    {
 ▸    "message": "JsError.get",
 ▸    "requestId": "local:api:cjikktdkj000x0820wl0vjx54"
 ▸    }
 ▸    ]
 ▸    }
`
- OS: `Ubuntu 18.10`
 - `prisma` CLI: prisma/1.9.0 (linux-x64) node-v10.4.1

Sory for my English

**Comment by marktani** [comment] 2018-06-18 18:22
Thanks for your report. Can you provide the additional information in your original post:

**To Reproduce**
* What is your exact datamodel that is deployed to the Prisma service you're importing the data to?
* can you share the exact `export.zip` file that you are importing?

Thanks!

**Comment by marktani** [comment] 2018-06-19 08:28
Thanks @strelov1! I can confirm this bug.

**Comment by agonbina** [comment] 2018-08-01 10:16
@marktani is there any update about this? I just ran into the exact same issue which does not seem to have a workaround yet?
Having a fix or a workaround is critical for us as we are migrating from DynamoDB to Prisma and we have to move all the existing data that we have there to Prisma.

**Comment by agonbina** [comment] 2018-08-01 10:31
In my case it seems like the issue seems to be with importing fields marked as JSON type in the datamodel. Sadly due to the fact that there is no interfaces, we have to use this type for more complex object like fields(ex. address). 

Could you please prioritize this issue or provide a workaround?

**Comment by do4gr** [comment] 2018-10-26 10:05
Hey @strelov1, 

sorry for the late response. I could reproduce the error. The problem is that you have startTime defined as Int in your data model but provide it as a String. This causes the error. I have improved the error handling for this case so that you will get a response that helps you identify the problem. 

Thanks for reporting this!

**Closed** 2018-10-26 11:53 UTC
Labels: component/server, kind/bug
