### ISSUE TITLE
Huge app start times when deploying Prisma to a lambda with NestJS

### ISSUE THREAD

**Issue by samrith-s** [prisma/prisma#4972] opened 2021-01-12 20:20 UTC
## Bug description

With a simple NestJS application which uses Prisma as described in [the recipe](https://docs.nestjs.com/recipes/prisma), app start times on Lambda are as very high as compared to NestJS applications which do not use Prisma.

## Background

I have 3 standalone NestJS applications, each deployed as a lambda function behind an API Gateway. Two of the (`profile` and `auth`) use Prisma and one (`hello`) does not.

- The size of `profile` and `auth` is **1.5MB** each as all lambdas are bundled using Webpack and they bundle the Prisma Client and all other required node-modules into a self-containing bundle
- The size of `hello` is around **1MB**
- Size seems to be a non-issue
- `@prisma/cli` is not bundled. Only `@prisma/client` is
- The `rhel-openssl-1.0.x` query engine is generated locally and made available to all the lambdas via layers
- The `PRISMA_QUERY_ENGINE_BINARY` path is set to `/opt/rhel-openssl-1.0.x` as the lambda layer is extracted into `/opt` directory
- All lambdas have **1024MB** of memory allotted to them and a **30 seconds** timeout (standard for API Gateway)
- The `hello` function takes **~100ms** to start while reading some content from `/opt` folder

This was initially discussed [on the Slack thread](https://prisma.slack.com/archives/CKQTGR6T0/p1610451492040300) this issue is to document it.

## Issues
- The `profile` and `auth` functions take over **15000 - 20000ms** to start as they contain Prisma
- If the lambda memory is reduced to **128MB** then:
	- The `hello` function still starts in the same amount of time
	- The `profile` and `auth` functions timeout atleast the first two times and the API throws an error
	- On the third call the entire thing bootstraps again and then we receive a response by around the **16000ms** mark

Here are the CloudWatch logs indicating the two drastically different startup times:
1. With Prisma
![image](https://user-images.githubusercontent.com/9032162/104367975-cdca5780-551b-11eb-8bce-7c5d67191f9f.png)
2. Without Prisma
![image](https://user-images.githubusercontent.com/9032162/104368024-da4eb000-551b-11eb-929c-92eaf5267f69.png)

## Expected behavior

Prisma should not be a bottleneck while bootstrapping a lambda function as other file-read operations perform 10x faster.

## Prisma information

There are no queries being made to the database so far and the Prisma schema is just the one found in the [quickstart guide](https://www.prisma.io/docs/getting-started/quickstart-typescript/#write-your-first-query-with-prisma-client) with an additional `binaryTargets` and `output` specified in the `generator client` block.

## Environment & setup

- OS: AMI
- Database: Postgres
- Node.js version: 12.x
- Prisma version:

```
@prisma/cli          : 2.13.1
@prisma/client       : 2.13.1
Current platform     : darwin
Query Engine         : query-engine fcbc4bb2d306c86c28014f596b1e8c7980af8bd4 (at node_modules/@prisma/engines/query-engine-darwin)
Migration Engine     : migration-engine-cli fcbc4bb2d306c86c28014f596b1e8c7980af8bd4 (at node_modules/@prisma/engines/migration-engine-darwin)
Introspection Engine : introspection-core fcbc4bb2d306c86c28014f596b1e8c7980af8bd4 (at node_modules/@prisma/engines/introspection-engine-darwin)
Format Binary        : prisma-fmt fcbc4bb2d306c86c28014f596b1e8c7980af8bd4 (at node_modules/@prisma/engines/prisma-fmt-darwin)
Studio               : 0.329.0
```

**Comment by travisbloom** [comment] 2021-01-14 18:28
I don't know if this will help, but we had similar issues where the bundled functions were larger than 50mb and Vercel was throwing errors. In the end, the solution was to make sure you don't ship `@prisma/cli` along with @prisma/client.

We had @prisma/cli installed as a local dependency (in the package.json) instead of a global dependency, and this added 42mb to the bundled payload. By installing the cli globally in our CI flow, we prevented it from being shipped.

Hope that helps!

**Comment by samrith-s** [comment] 2021-01-15 14:42
Hey @travisbloom ,

Thank you so much for that, but I am not packaging the CLI with my code. In fact. My Lambda is only **1.5MB** roughly.

**Comment by Jolg42** [comment] 2021-01-15 16:46
@samrith-s It's unlikely the whole lambda is only 1.5MB because you're using Lambda Layers and they probably add some MB too.

**Comment by samrith-s** [comment] 2021-01-15 16:47
Including the layers and my actual code, it's 12MB.

**Comment by samrith-s** [comment] 2021-01-17 23:21
Hello guys, is there any update on this?

**Comment by Jolg42** [comment] 2021-01-18 09:27
@pantharshit00 will check soon, he has been quite busy these days 😃

**Comment by pantharshit00** [comment] 2021-01-20 13:37
Hey @samrith-s 

Sorry for late reply here. I am back now. 

20,000 ms cold start is unexpected. I personally run some prisma services on lambda and max cold start time that I have noticed is 4 secs. 

I have some questions for you: 
1. Where is your database hosted? Please make sure that they are on the same geographic location. 
2. Are you using a connection pooler like pgbouncer? 


After I have this information I can try a reproduction with the starter.

**Comment by samrith-s** [comment] 2021-01-20 13:41
@pantharshit00 No problem at all!

1. Yes database is hosted in the same geographic location and also within the same VPC as the lambdas
2. No, I am not using that yet (and have no idea where to start with that)

I have also added you to our project. :)

**Comment by pantharshit00** [comment] 2021-01-21 14:06
@samrith-s Unfortunately the invitation expired, can you please send that again.

**Comment by samrith-s** [comment] 2021-01-21 14:13
@pantharshit00 Sent!

**Comment by f0rr0** [comment] 2021-01-27 09:40
I recently did something similar (Prisma, vanilla nodejs handler). I can see cold starts of 3 - 4 seconds. The zipped asset is around 12MB (I am not using any layers). The lambda is in a VPC. 1GB memory

I am interested in potentially optimizing the cold start further and was wondering if there are any open discussions or resources on this (specifically pertaining to prisma since that seems to be the bottleneck here) @pantharshit00

**Comment by samrith-s** [comment] 2021-02-01 02:31
Hey @Jolg42 @pantharshit00 do you guys have any update around this, or can I help in resolving this in any way?

**Comment by Jolg42** [comment] 2021-02-01 09:57
@f0rr0 I think the AWS `Provisioned Concurrency` could help a lot https://aws.amazon.com/blogs/compute/new-for-aws-lambda-predictable-start-up-times-with-provisioned-concurrency/

Also this article https://mikhail.io/serverless/coldstarts/aws/ has an interesting comparison between JavaScript functions and Node.js Docker container, it seems that the Docker images get the same cold start time when their size get bigger while the simple function cold start grows fast. Maybe something to try.

@samrith-s I guess that ⬆️ could help too but your case seems slower than expected and @pantharshit00 will check.

**Comment by samrith-s** [comment] 2021-03-09 10:01
Hey guys, any idea when you guys will have time to check this out? My project is kinda stuck because of this

**Comment by sreuter** [comment] 2021-03-18 13:56
Suffering from the same issue, 3-4 seconds cold start times on Lambda with Prisma. How can we help tracking this down and get fixed?

**Comment by Jolg42** [comment] 2021-03-18 14:18
@sreuter 3-4 seconds actually seems normal to me. Cold starts are relative to the size of the labda function.

So I'm curious to know what's the size of your function zipped and unzipped? And the list of files you have in there (including dependencies).

https://mikhail.io/serverless/coldstarts/aws/ shows a 3-5s cold start for a 35MB function

A good workaround is to have a provisioned concurrency setting:
https://aws.amazon.com/blogs/compute/new-for-aws-lambda-predictable-start-up-times-with-provisioned-concurrency/

For a more detailed investigation, it seems interesting to enable AWS X-Ray
![image](https://user-images.githubusercontent.com/1328733/111640911-ecd7b500-87fc-11eb-9b3a-91467d32af87.png)
https://docs.aws.amazon.com/lambda/latest/dg/services-xray.html

I randomly found this https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:374852340823:applications~measure-cold-start (didn't try it, could be interesting to try)

**Comment by pantharshit00** [comment] 2021-03-26 13:35
Hey @samrith-s 

Can you please share the XRay information of the deployment with us? 


Also, your codebase is fairly sized so it is not trivial for me to deploy without collecting a lot of secrets and other resources. If XRay doesn't show us more details, I will ask you to onboard me on this.

**Comment by janpio** [comment] 2021-03-26 16:07
Hey @samrith-s, I also took a look at your issue here as I am investigating some things in relation to serverless right now, which include cold start times. 

Usually what is referred to as "cold start" in context of Lambda functions is the time it takes for your app to even start "booting", so the time it takes for the Lambda function to be fully set up and being able to execute our custom code. This is a value that is influenced by the lambda environment and the function and its dependencies.

The Cloudwatch logs you posted above indicate that the >15s duration you refer to is actually your app starting/booting and doing _something_. That could very well be Prisma of course, but we would not describe this as the "lambda cold-start time" in this case.

This kinda changes what we need to investigate here - if we look into cold start times, this is not actually what you are experiencing and will not help you. I updated your issue title and message to reflect that difference as well - I hope that is okay for you.

So the question now is: Why does you app take so long to start up on Lambda when using Prisma? We can (and will) certainly look into that.

**Comment by samrith-s** [comment] 2021-03-29 21:40
Hey @janpio 

Thanks, I will post the XRay information (which I have to enable) soon. What you're saying makes sense. So basically in NestJS we have a bootstrapping phase where it inits Prisma. We have consistently observed longer start times when we use the module which uses Prisma than the ones without.

Thanks for this, I will try and get the info for @pantharshit00 soon.

**Comment by samrith-s** [comment] 2021-03-29 21:54
@pantharshit00 Here you go
![image](https://user-images.githubusercontent.com/9032162/112904545-61f29680-90e9-11eb-9261-960a0b557c88.png)

Another thing to note, that after using provisioned concurrency, the start times have reduced drastically.

Here is our catalog service which doesn't use provisioned concurrency.
![image](https://user-images.githubusercontent.com/9032162/112904965-01b02480-90ea-11eb-8384-0136bbdc6caf.png)
Also, got this error internally (which never appears when not using Prisma)
```
2021-03-29T23:52:08.433+02:00

Copy
2021-03-29T21:52:08.091Z	647c9d98-a60c-450d-988b-3828efa0e0fc	ERROR	Error: spawn ENOMEM
    at ChildProcess.spawn (internal/child_process.js:408:11)
    at Object.spawn (child_process.js:553:9)
    at /var/task/src/apps/catalog/src/lambda.js:163635:40
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {
  errno: 'ENOMEM',
  code: 'ENOMEM',
  syscall: 'spawn'
}
```

**Comment by f0rr0** [comment] 2021-03-30 03:12
@Jolg42 i think using provisioned concurrency might be a temporary solution to get around the problem for now but it cannot be a long term solution. A major reason for using lambda at scale is to have automatic scale down to zero at least for infrequently accessed services.

In my experiments I noticed a couple of things which might be helpful to further investigate this:

- Prisma is the biggest dependency of my project. I'm using webpack to optimise the final asset I upload to lambda but a trivial CRUD handler results in ~ 3 mb file.

- The query engine binary for me is at ~ 25 MB. However I think this should not impact the handler perf.

- Releasing a database connection from the handler at the end of each handler is painfully slow. Initially I was doing this since I was not using a proxy but later I moved to RDS proxy. However RDS pins the connections Prisma makes but that's a separate issue. The point is at scale I still might have to release the connections from handler since the proxy is useless because of pinning.

**Comment by Jolg42** [comment] 2021-03-30 07:58
@f0rr0 Yes, though because of how lambda works today there will always be some kind of cold start. Even for an infrequently accessed service, I think that setting a provision of 1 instance would be doable / won't cost that much. 

- You can expect to see the query engine get bigger in future releases but this should not affect the cold start significantly. It seems that the most significant "setup" time is establishing a database connection to the database, which can be slow if the database is not in the same datacenter / geographic region.
- About RDS Proxy, we documented it and have an issue you can follow here:
>Prepared statements (of any size) or query statements greater than 16 KB cause RDS Proxy to pin the session. Because Prisma uses prepared statements for all queries, you won't see any benefit when using RDS Proxy with Prisma.
https://www.prisma.io/docs/guides/deployment/deployment#aws-rds-proxy
https://github.com/prisma/prisma/issues/5866

**Comment by janpio** [comment] 2021-03-30 22:41
@samrith-s Connecting to the database would be the obvious candidate how "adding Prisma to a project" could easily increase the boot/start time of your app. So if you call `$connect()` or execute any query, that would happen. You could use custom segments for X-Ray (https://docs.aws.amazon.com/xray/latest/devguide/xray-sdk-nodejs-subsegments.html) or some simple time measurement in your code to figure out what is actually taking that time.

> Another thing to note, that after using provisioned concurrency, the start times have reduced drastically.

This could also match the database connection theory.

> Also, got this error internally (which never appears when not using Prisma)
> 
> ```
> 2021-03-29T23:52:08.433+02:00
> 
> Copy
> 2021-03-29T21:52:08.091Z	647c9d98-a60c-450d-988b-3828efa0e0fc	ERROR	Error: spawn ENOMEM
>     at ChildProcess.spawn (internal/child_process.js:408:11)
>     at Object.spawn (child_process.js:553:9)
>     at /var/task/src/apps/catalog/src/lambda.js:163635:40
>     at processTicksAndRejections (internal/process/task_queues.js:97:5) {
>   errno: 'ENOMEM',
>   code: 'ENOMEM',
>   syscall: 'spawn'
> }
> ```

Prisma uses memory, of course. If the combination of your app and Prisma uses to much, this could follow from that. But we would also need to look deeper into the details here. Can you reproduce the same error with a lambda with more memory?

**Comment by samrith-s** [comment] 2021-03-30 22:42
I'll try the stuff you've mentioned and post the logs here tomorrow!

**Comment by pantharshit00** [comment] 2021-05-16 13:12
Hey @samrith-s Do you have any updates here for us?

**Comment by samrith-s** [comment] 2021-05-22 06:21
Hey @pantharshit00 I currently have set `reservedConcurrency` for all of my functions to `1`. This is costing me a bit right now, but overall it has solved this issue.

**Comment by meotimdihia** [comment] 2021-07-26 02:54
Fastify and Prisma start slow too. It takes 4s to restart the server when I use nodemon.

**Comment by janpio** [comment] 2021-07-28 10:21
The please open a separate issue about this and supply more information about what you are doing. If creating a connection to your database takes 3 seconds, this is not very surprising outcome.

**Comment by rehanvdm** [comment] 2021-09-16 13:27
128MB Lambda Memorry
```
Call | Time
1    | 30s (Timeout)
2    | 30s (Timeout)
3    | 22s 
```
256MB 
```
Call | Time
1    | ~ 4,100ms
2    | ~ 2,200ms
3    | ~ 2,500ms
```
512MB 
```
Call | Time
1    | ~ 2,300ms
2    | ~   900ms
3    | ~ 1,200ms
```
1024MB
```
Call | Time
1    | ~ 1,100ms
2    | ~   365ms 
3    | ~   327ms 
```
2048MB
```
Call | Time
1    | ~   570ms
2    | ~   330ms 
3    | ~   300ms 
```

The strange thing is that it takes longer on a basic insert, not the initialization of the Prisma client. I can only assume it is doing some lazy loading in there.

Still not sure why inserting a basic record takes ~300ms (on 1024MB), even if it is a warm lambda? 

The creation of the Prisma client and the insert time went down as the function memory increased. That binary does not seem very efficient? I was working on Golang project at work where we got ~80ms per lambda call on average, for personal projects I prefer JS and decided to use Prisma this time around with TS and I am shocked to learn this now. I spent so much time setting everything up 😅, this is a bit disappointing, I don't really want to go pack to `node-postgres` after learning about how cool Prisma is..

**Comment by ryands17** [comment] 2021-09-16 13:41
@rehanvdm 👋 
It shouldn't take this much time on the latest version with [N-API](https://www.prisma.io/docs/concepts/components/prisma-engines/query-engine#defining-the-query-engine-type-for-prisma-client) enabled by default. I recently gave a talk regarding this in which I load tested with artillery on a 512 MB Lambda and the average was around 256ms.

**Comment by rehanvdm** [comment] 2021-09-16 14:01
Hey @ryands17 I actually leaned a lot on your article you posted, specifically for the CDK https://dev.to/prisma/bundling-prisma-with-the-cdk-using-aws-lambda-nodejs-2lkd 

The N-API is enabled by default if I use Prisma v3.0,2 right? My numbers aren't load-tested, I am sure the more traffic the Lambda recieveis the faster the request will be, but still much slower than expected...

**Comment by ryands17** [comment] 2021-09-16 14:09
Yes it is enabled by default in 3.0.2. As far as I tested it, the first request would be slower but subsequent ones should be around the median value I got.

**Comment by rehanvdm** [comment] 2021-09-20 21:32
I did a test to see how Prisma compares with node-pg and the results were as expected, disappointing. 

Both Lambdas are at 256MB because Prisma times out at 128MB. Both lambdas do the exact same thing, I made a new branch from the Prisma one, removed Prisma and then used node-pg instead. Both are in TS and bundled with the CDK and ESBuild. 

API Latency is pretty bad to us-east-1 from South Africa, so the artillery load tests are not accurate, I mainly used artillery to force sequential API requests(so that the first one is always a cold start) with the phases below.
```YAML
  phases:
    - duration: 30
      arrivalRate: 1
      maxVusers: 1
```

The following is a summary of the Lambda logs at the end.

**Cold Start**
```
           | Prisma | node-pg
DB init    | 138ms  | 0.489ms
Insert     | 3.211s | 120.644ms 
Memory     | 212MB  | 124MB
Init Dur.  | 822ms  | 464.84ms
Total Dur. | 4360ms | 1068ms
```
**First sampled log**
```
           | Prisma | node-pg
DB init    | 90ms   | 0.06ms
Insert     | 1.414s | 29.919ms 
Memory     | 243MB  | 124MB 
Total Dur. | 1513ms | 34ms
```
**Second sampled log**
```
           | Prisma | node-pg
DB init    | 99ms   | 0.077ms
Insert     | 1.119s | 9.608ms
Memory     | 250MB  | 124MB 
Total Dur. | 1222ms | 13ms
```

Lambda Cold start seems to be **~4 times slower.**
Lambda Warm starts seems to be between **~40 to ~90 times slower**
Prisma Warm inserts seems to be between **~50 to ~120 times slower**
Memory used seems to be **~2 more**
The Lambda Zip size for Prisma is 18.7MB while node-pg came in at 1.4MB. Prisma produces **~13 times bigger package**

-----
**RAW LOGS**

**[node-pg @ 256MB]**
```
All virtual users finished
Summary report @ 22:43:28(+0200) 2021-09-20
  Scenarios launched:  13
  Scenarios completed: 13
  Requests completed:  13
  Mean response/sec: 0.44
  Response time (msec):
    min: 307
    max: 2101
    median: 342
    p95: 1982.5
    p99: 2101
  Scenario counts:
    0: 13 (100%)
  Codes:
    200: 13
```
```
2021-09-20T22:43:03.535+02:00	2021-09-20T20:43:03.535Z 824a7117-4134-4ef4-a83d-261202d8ea58 INFO Db Create: 0.489ms 
2021-09-20T22:43:04.336+02:00	2021-09-20T20:43:04.336Z 824a7117-4134-4ef4-a83d-261202d8ea58 INFO node-pg Insert: 120.644ms 
2021-09-20T22:43:04.338+02:00	REPORT RequestId: 824a7117-4134-4ef4-a83d-261202d8ea58 Duration: 1067.75 ms Billed Duration: 1068 ms Memory Size: 256 MB Max Memory Used: 124 MB Init Duration: 464.84 ms 

2021-09-20T22:43:06.504+02:00	2021-09-20T20:43:06.504Z ff272450-456b-4ad4-a820-056b45b0cb99 INFO Db Create: 0.06ms 
2021-09-20T22:43:06.535+02:00	2021-09-20T20:43:06.535Z ff272450-456b-4ad4-a820-056b45b0cb99 INFO node-pg Insert: 29.919ms 
2021-09-20T22:43:06.536+02:00	REPORT RequestId: ff272450-456b-4ad4-a820-056b45b0cb99 Duration: 33.98 ms Billed Duration: 34 ms Memory Size: 256 MB Max Memory Used: 124 MB 

2021-09-20T22:43:08.627+02:00	2021-09-20T20:43:08.627Z c836286d-9819-4ba7-b06d-dd1234437505 INFO Db Create: 0.077ms 
2021-09-20T22:43:08.637+02:00	2021-09-20T20:43:08.637Z c836286d-9819-4ba7-b06d-dd1234437505 INFO node-pg Insert: 9.608ms 
2021-09-20T22:43:08.638+02:00	REPORT RequestId: c836286d-9819-4ba7-b06d-dd1234437505 Duration: 12.59 ms Billed Duration: 13 ms Memory Size: 256 MB Max Memory Used: 124 MB 
```

**[prisma @ 256MB]**
```
All virtual users finished
Summary report @ 22:35:41(+0200) 2021-09-20
  Scenarios launched:  9
  Scenarios completed: 9
  Requests completed:  9
  Mean response/sec: 0.28
  Response time (msec):
    min: 1531
    max: 5933
    median: 1637
    p95: 5933
    p99: 5933
  Scenario counts:
    0: 9 (100%)
  Codes:
    200: 9
```
```
2021-09-20T22:35:14.489+02:00	2021-09-20T20:35:14.471Z 6f397321-ef14-4520-aa76-c76d22baac47 INFO Prisma Create: 138.127ms 
2021-09-20T22:35:18.400+02:00	2021-09-20T20:35:18.399Z 6f397321-ef14-4520-aa76-c76d22baac47 INFO Prisma Insert: 3.211s 
2021-09-20T22:35:18.410+02:00	REPORT RequestId: 6f397321-ef14-4520-aa76-c76d22baac47 Duration: 4359.03 ms Billed Duration: 4360 ms Memory Size: 256 MB Max Memory Used: 212 MB Init Duration: 822.67 ms

2021-09-20T22:35:20.873+02:00	2021-09-20T20:35:20.870Z 4396b162-bc04-43b7-ac74-303955064440 INFO Prisma Create: 90.276ms 
2021-09-20T22:35:22.285+02:00	2021-09-20T20:35:22.285Z 4396b162-bc04-43b7-ac74-303955064440 INFO Prisma Insert: 1.414s 
2021-09-20T22:35:22.289+02:00	REPORT RequestId: 4396b162-bc04-43b7-ac74-303955064440 Duration: 1512.02 ms Billed Duration: 1513 ms Memory Size: 256 MB Max Memory Used: 243 MB 

2021-09-20T22:35:35.610+02:00	2021-09-20T20:35:35.610Z 9cd8fb7a-3c1d-437e-9904-7def05b9765d INFO Prisma Create: 99.743ms 
2021-09-20T22:35:36.729+02:00	2021-09-20T20:35:36.729Z 9cd8fb7a-3c1d-437e-9904-7def05b9765d INFO Prisma Insert: 1.119s 
2021-09-20T22:35:36.731+02:00	REPORT RequestId: 9cd8fb7a-3c1d-437e-9904-7def05b9765d Duration: 1221.96 ms Billed Duration: 1222 ms Memory Size: 256 MB Max Memory Used: 250 MB 
```

----

I really loved Prisma up until these last few tests, it is just too slow (for me) at least to be used in a Lambda function. I think those fat binary engines have a lot to do with the problem. I am hoping to revisit this thread in a year or less and hope to see better results, I really want to use Prisma, but guess it is back to node-pg and flywheel for now.

**Comment by Zn4rK** [comment] 2021-09-20 21:47
@rehanvdm Interesting results. I'm curious if a container image lambda performs better or worse for warm invocations. Puppeteer is a very large binary that people often try to run in AWS Lambda. There's a similar thread to this one [here](https://github.com/puppeteer/puppeteer/issues/3120). It might be possible to garner some insight as to why Prisma is so slow on AWS Lambda (and potentially all cloud providers) from there.

**Comment by ryands17** [comment] 2021-09-21 06:43
@rehanvdm I am getting better values using **Prisma @ 512MB** on an Edge API so latency won't be an issue here:

```
All virtual users finished
Summary report @ 12:11:44(+0530) 2021-09-21
  Scenarios launched:  50
  Scenarios completed: 50
  Requests completed:  25000
  Mean response/sec: 184.8
  Response time (msec):
    min: 215
    max: 1306
    median: 228
    p95: 273
    p99: 1017
  Scenario counts:
    0: 50 (100%)
  Codes:
    200: 25000
```

Using the command: `artillery quick -c 50 -n 500 $URL`

Also this would be vastly improved using the [Prisma Data Proxy](https://prisma103696.typeform.com/to/LWC6905E) that we will be introducing an early access version of.

**Comment by rehanvdm** [comment] 2021-09-21 07:41
@Zn4rK 
> @rehanvdm Interesting results. I'm curious if a container image lambda performs better or worse for warm invocations. Puppeteer is a very large binary that people often try to run in AWS Lambda. There's a similar thread to this one [here](https://github.com/puppeteer/puppeteer/issues/3120). It might be possible to garner some insight as to why Prisma is so slow on AWS Lambda (and potentially all cloud providers) from there.

I doubt(haven't used them before) a lambda container image will perform better. Native JS code is always better than having the overhead of the JS code communicate to a binary.  I am not sure what design decisions led to having that big ruby binary (which is actually not that performant), but I am 100% sure it can be done without it - proof being node-pg.

Node-pg is also build to do one thing, client interface to PG. Whereas Prisma has so many bells and whistles (migrations, extra type safety, etc) to cater for so many scenarios and different database engines. Unfortunately, all the unnecessary code can not be tree shaken by bundlers because it is a single binary. 

I know of and am currently using Puppeteer. I don't expect it and Chromium to be fast though, those are CPU and memory intensive. Interfacing with a DB should not be, it is much more IO intensive but not in the case of Prisma, the binary is doing some serious work in there that is slow.

**Comment by rehanvdm** [comment] 2021-09-21 07:46
@ryands17 
>Also this would be vastly improved using the Prisma Data Proxy that we will be introducing an early access version of. 

I don't see how that solves the problem? Not RDS Proxy nor PG Bouncer will help, so I can only assume that the Prisma Data Proxy bundles the query engine binaries and then the client calls them somehow? So all that CPU an IO intensive work has to then be done on that server that I then own? This means it has to be highly available, so at the minimum 2 servers distributed across 2 AZs with a NLB in front of it.

I understand the reasoning but I still feel that this is a problem that can be much better utilized by removing the binary and writing native code.

**Comment by ryands17** [comment] 2021-09-21 11:05
@rehanvdm 
Not exactly. This would be similar to Aurora's Data API, so in that case, you don't need to manage any servers as the queries would be resolved on Prisma's end.

**Comment by janpio** [comment] 2022-12-20 18:51
([In our release 4.8.0](https://github.com/prisma/prisma/releases/tag/4.8.0) we have made significant improvements, average decrease of 50%, on the size of our engine files. That should ease the pain, but we will continue looking into other solutions of course. Expect more updates from us in this direction soon.)

**Comment by sorenbs** [comment] 2023-04-10 20:26
I know this issue is pretty old, but we have made some significant improvements through the first months of 2023. @samrith-s, if you are still interested in this, can I request that you try out this preview feature and let us know if you see any improvements: https://github.com/prisma/prisma/issues/18095

We have completed many small improvements, which together reduce startup time significantly. All these improvements are included in the latest stable release. Additionally, we have made one very large structural change which is currently gated behind that feature flag described above. All together, these improvements more than triple the startup speed on reasonably complex schemas.

**Comment by SevInf** [comment] 2023-07-13 13:59
Thank you everyone for the feedback 🙌🏼

We’re thrilled to announce that the jsonProtocol Preview feature is now Generally Available. You can now remove the Preview feature flag from your schema after upgrading. We made the JSON-based wire protocol the default protocol used for communication between Prisma Client and the query engine.

We introduced this feature in version [4.11.0](https://github.com/prisma/prisma/releases/tag/4.11.0) to improve Prisma’s performance. Previously, Prisma used a GraphQL-like protocol to communicate between Prisma Client and the query engine. Applications with larger schemas had higher CPU and memory consumption compared to smaller schemas which created a performance bottleneck.

The JSON-based wire protocol improves efficiency when Prisma Client is communicating with the query engine.

If you want to learn more about the performance improvements that are bundled with Prisma 5, including the JSON-based protocol, we recommend giving [Prisma 5: Faster by Default](https://www.prisma.io/blog/prisma-5-f66prwkjx72s) a read.

See [Prisma 5.0.0 release notes.](https://github.com/prisma/prisma/releases/tag/5.0.0)

**Closed** 2023-08-04 10:30 UTC
Labels: bug/1-unconfirmed, kind/bug, topic: performance, topic: serverless, status/needs-action, team/client, topic: NestJS, topic: deployment/aws-lambda
