### ISSUE TITLE
Prisma transactions are not working

### ISSUE THREAD

**Issue by ali3nnn** [prisma/prisma#22496] opened 2023-12-22 13:43 UTC
### Bug description

I am running this code:

```
await prisma.$transaction([
    prisma.$queryRaw`SELECT * FROM tankstelle`,
    prisma.$queryRaw`SELECT * FROM tankstelle`,
])
```

and the script is running continously without a response.

The logs are looking like this:

```
2023-12-22T13:36:39.424Z prisma:client  prisma.$queryRaw(SELECT * FROM tankstelle, [])
[1] 2023-12-22T13:36:39.425Z prisma:client  Prisma Client call:
[1] 2023-12-22T13:36:39.426Z prisma:client  prisma.$queryRaw({
[1]   query: "SELECT * FROM tankstelle",
[1]   parameters: {
[1]     values: "[]",
[1]     __prismaRawParameters__: true
[1]   }
[1] })
[1] 2023-12-22T13:36:39.426Z prisma:client  Generated request:
[1] 2023-12-22T13:36:39.426Z prisma:client  {
[1]   "action": "queryRaw",
[1]   "query": {
[1]     "arguments": {
[1]       "query": "SELECT * FROM tankstelle",
[1]       "parameters": "[]"
[1]     },
[1]     "selection": {}
[1]   }
[1] }
[1] 
[1] 2023-12-22T13:36:39.426Z prisma:client  prisma.$queryRaw(SELECT * FROM tankstelle, [])
[1] 2023-12-22T13:36:39.426Z prisma:client  Prisma Client call:
[1] 2023-12-22T13:36:39.426Z prisma:client  prisma.$queryRaw({
[1]   query: "SELECT * FROM tankstelle",
[1]   parameters: {
[1]     values: "[]",
[1]     __prismaRawParameters__: true
[1]   }
[1] })
[1] 2023-12-22T13:36:39.426Z prisma:client  Generated request:
[1] 2023-12-22T13:36:39.426Z prisma:client  {
[1]   "action": "queryRaw",
[1]   "query": {
[1]     "arguments": {
[1]       "query": "SELECT * FROM tankstelle",
[1]       "parameters": "[]"
[1]     },
[1]     "selection": {}
[1]   }
[1] }
[1] 
[1] 2023-12-22T13:36:39.427Z prisma:client:libraryEngine  requestBatch
[1] 2023-12-22T13:36:39.427Z prisma:client:libraryEngine  library already starting, this.libraryStarted: false
[1] 2023-12-22T13:36:39.877Z prisma:client:libraryEngine  library started
[1] 2023-12-22T13:36:40.067Z prisma:client:libraryEngine  library stopping
[1] 2023-12-22T13:36:40.067Z prisma:client:libraryEngine  library stopped
```

### How to reproduce

- install prisma@5.6.0 in NodeJS
- set the env variable: DEBUG="prisma:*"
- run the forementioned code prisma transaction

### Expected behavior

To get back the response of the queries

### Prisma information

```prisma
generator client {
  provider = "prisma-client-js"
  engineType = "binary"
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

model tankstelle {
...
}
```

```ts
await prisma.$transaction([
    prisma.$queryRaw`SELECT * FROM tankstelle`,
    prisma.$queryRaw`SELECT * FROM tankstelle`,
])
```

### Environment & setup

- OS: macOS
- Database: PostgreSQL (neon.tech)
- Node.js version: 21.2.0

### Prisma Version

```
^5.6.0
```

**Comment by jkomyno** [comment] 2024-01-02 15:17
Hi @ali3nnn, how many entries are there in the `tankstelle` table? I'm not able to reproduce this issue.

Consider the following Prisma schema:

```prisma
generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "postgres"
  url      = env("DATABASE_URL")
}

model test {
  id   Int    @id
  name String
}
```

and the following TypeScript snippet:

```typescript
import { PrismaClient } from '@prisma/client'

async function main() {
  const prisma = new PrismaClient()

  await prisma.test.deleteMany()

  await prisma.test.createMany({
    data: [
      { id: 1, name: 'A' },
      { id: 2, name: 'B' },
    ],  
  })

  const result = await prisma.$transaction([
    prisma.$queryRaw`SELECT * FROM test`,
    prisma.$queryRaw`SELECT * FROM test`,
  ])

  console.log(result)
}

main()
```

The output is:

```js
[
  [ { id: 1, name: 'A' }, { id: 2, name: 'B' } ],
  [ { id: 1, name: 'A' }, { id: 2, name: 'B' } ]
]
```

as one would expect, and it only takes a few milliseconds to resolve.

If the table you're querying in raw mode has several thousands entries, however, I'd expect it to take longer, giving the impression that the query is halted.

An even simpler test that you can try to verify the connection to Neon + see Prisma transactions running is:

```typescript
  const result = await prisma.$transaction([
    prisma.$queryRaw`SELECT version()`,
    prisma.$queryRaw`SELECT version()`,
  ])

  console.log(result)
```

which should print something like

```js
[
  [
    {
      version: 'PostgreSQL 15.5 on x86_64-pc-linux-gnu, compiled by gcc (Debian 10.2.1-6) 10.2.1 20210110, 64-bit'
    }
  ],
  [
    {
      version: 'PostgreSQL 15.5 on x86_64-pc-linux-gnu, compiled by gcc (Debian 10.2.1-6) 10.2.1 20210110, 64-bit'
    }
  ]
]
```

---

I'll be closing this issue for now, but please leave a comment in case anything else is unclear. Thanks!

**Closed by jkomyno** 2024-01-02 15:17 UTC
Labels: kind/bug

**Comment by janpio** [comment] 2024-01-16 22:17
Did you figure out what was wrong with your app @ali3nnn?
