### ISSUE TITLE
Is there any way to use Prisma in-browser?

### ISSUE THREAD

**Issue by midwesterntechnology** [prisma/prisma#10853] opened 2021-12-23 18:18 UTC
## Problem

We are building an offline first app using sql.js (with absurd-sql). Given that prisma already supports sqlite, is there any way to use it in the browser by writing an adapter to connect using sql.js instead of a file?

## Suggested solution

Allow prisma to be used in browser if a custom driver is provided that requires no node.js only libraries to function.

## Alternatives

The only real alternative that exists at this point is TypeORM. But this doesn't have any of the graphql functionality we're looking for.

**Comment by pantharshit00** [comment] 2021-12-24 10:16
Prisma uses Node JS APIs currently which are unavailable in the browser so it is currently not possible to run Prisma in browser. Since core of Prisma is written in Rust which can be compiled to WASM, it might be able to work in browser in future but no timeline for that yet. 

I will close this as a duplicate of this issue: https://github.com/prisma/prisma/issues/4992

**Closed by pantharshit00** 2021-12-24 10:16 UTC
