### ISSUE TITLE
Nullable lists

### ISSUE THREAD

**Issue by tvvignesh** [prisma/prisma#847] opened 2019-10-27 05:34 UTC
Hi. I am trying to declare a list explicitly as optional/null as mentioned in the documentation here: https://github.com/prisma/prisma2/blob/master/docs/data-modeling.md#types

While I understand that I need not explicitly specify it since empty lists are allowed, doing so is throwing error as mentioned in the 2nd screenshot below.

![Screenshot from 2019-10-27 11-03-37](https://user-images.githubusercontent.com/1165845/67630178-72c22b80-f8a9-11e9-88fb-2be9f1a90526.png)

![Screenshot from 2019-10-27 10-58-19](https://user-images.githubusercontent.com/1165845/67630162-09dab380-f8a9-11e9-84c9-25a3f734a6b3.png)

**PS:** It works if I don't explicitly define it as optional. Also, the same issue occurs even for String Lists (when trying to declare them as optional with null as default value). This problem occurs only for list fields and not for others.

Not sure if I am doing something wrong here. Thanks in advance.

**Comment by pantharshit00** [comment] 2019-10-28 11:00
Right now we don't support nullable lists by design because ideally, you want to return `[]` instead of `null` if there are no items in the lists. I think this ended up in the docs by mistake.

But I do know we would bring nullability back to the arrays due to compatibility reasons but ideally, you should not make them nullable.

**Comment by tvvignesh** [comment] 2019-10-28 11:46
@pantharshit00 Thanks for the clarification. And what about optional (?) character for lists. Even that was throwing errors (without null). So, does this mean that lists are always treated as optional? And if yes, what is the modifier to make them mandatory?

**Comment by pantharshit00** [comment] 2019-10-28 13:35
I do mean optional for lists. `Blog[]?` is not allowed by design because of the reasons I mentioned above.

I think the docs were badly written for that line and you thought syntax was `Blog?:null` which is not the case. I apologies for that and we have removed the misleading docs.

I am going to reopen the issue so that we can use this issue to track whether we are going to implement `Blog[]?` or not.

**Comment by tvvignesh** [comment] 2019-10-28 13:38
@pantharshit00 Sure. Btw, no need to apologise for all this - you guys are doing a great job at Prisma. Really respect all the work happening behind the scenes.

**Comment by Sytten** [comment] 2020-07-09 01:42
Did I miss something or array are nullable by default? I realized that the typing for it changed at some point and now the `set` accepts null. But now we have the opposite problem that it is not possible to make it mandatory :S
Can you confirm @pantharshit00 thanks

**Comment by pantharshit00** [comment] 2020-07-15 17:42
@Sytten You are talking in context of scalar lists, right? The issue here talks about m:n relations. Anyways, looks like null is allowed for them but it crashes the client. I have opened https://github.com/prisma/prisma-client-js/issues/780 in order to track that. Thanks for reporting as always.

I don't think we will allow nullable scalar lists as well. Also, right now migrate makes them nullable in the database which is also against the schema so I also opened: https://github.com/prisma/migrate/issues/519

**Comment by thebiglabasky** [comment] 2020-08-31 09:17
We fixed our [documentation](https://www.prisma.io/docs/reference/tools-and-interfaces/prisma-schema/prisma-schema-reference#model-field-type-modifiers)

Lists are so far not allowed to be optional (hence `null`). We are unlikely to change this at this point, so I will close this issue.
Feel free to comment if you have a specific use case which makes this compelling to reopen.
Thanks!

**Closed by thebiglabasky** 2020-08-31 09:17 UTC
Labels: kind/feature, topic: schema

**Comment by arda-** [comment] 2021-02-02 08:38
I have an edge-y use case that Prisma Developer Success' Ryan encouraged me to share here:
- I still want Prisma's current behavior (default to [])
- I'd prefer the generated typedef to be `myOptArray: T[] | null` so that I can do partial references to the object when reading & writing it. 

... I understand that reconciling those two things would be rather weird.

Use case: 
- CRUD REST API to allow partial object updates, and my client web client to use the same partial definitions and _write_ those partial objects.
- Pain point: I don't want to define partial typedefs for my client / server, seperate from Prisma's return type (Prisma's single source of truth is bliss), or constantly detect and add empty arrays to satisfy the mandatory field.

----

### example:

ideal world:

```prisma
// schema.prisma
model BlogPost {
  id             Int       @id @default(autoincrement())
  tags           String[]?
  slug           String?
}
```

would generate

```ts
// index.d.ts
export type Blogpost = {
  id: number
  tags: string[] | null
  slug: string | null
}
```

Which would be lovely, since I could write some code on the client along the lines of: 

```ts
// client code
function putBlogpostRequest(post: Blogpost) {
  axios.put("api/blogpost", { data: Blogpost }); 
  //... 
}

// server code
handle putBlogpostRequest(post: Blogpost) {
  prisma.user.update({
    where: { id: post.id },
    data: post,
  })
}

```

instead of how it works currently, which generates:

```ts
// index.d.ts
export type Blogpost = {
  id: number
  tags: string[] 
  slug: string | null
}
```

and causes somewhat messier code everywhere else:

```ts
// derived type which actually tracks optional fields
// client & server must be a monorepo with a single shared typedef, otherwise
// this needs to be exported as a module & imported everywhere else
type ActualBlogpost =  Partial<Blogpost> & Pick<Blogpost, "id">;

// Case A: client wants to compensate for missing mandatory fields, and transmits a Prisma-compliant Blogpost
// client
function updateBlogpost(post: ActualBlogpost) {
  axios.put("api/blogpost", { data: { ...post, tags: post.tags || []; } }
}

// server Case A is same as "ideal world"
function handlePutBlogpost(post: Blogpost) {
  prisma.user.update({
    where: { id: post.id },
    data: post ,
  })
}

// Case B: client sends a n ActualBlogpost over the wire, and server corrects it
// server Case B compensates for missing fields
function updateBlogpost(post: ActualBlogpost) {
  axios.put("api/blogpost", { data: { ...post, tags: post.tags || []; } }
}

// server Case B
function handlePutBlogpost(post: ActualBlogpost) {
  prisma.user.update({
    where: { id: post.id },
    data: {
      ...post,
      tags: ActualBlogpost.tags || []
   },
  })
}
```

In this false dichotomy I laid out, using partial objects around in a Typescript environment is laborious; to keep my function signatures correct with partial usage, both Case A and Case B above have to use some derived `Partial<` to make BlogPost's required empty array (`tags`) optional, I'd have to pass along a [] for those fields _every time_.

I feel like I'm misusing some of Prisma's generated types; should I be using a more clever/obscure Prisma type (akin to Prisma's internally generated `BlogpostUpdateType` etc) in the CRUD-related methods on the outside, to ease this situation?

**Comment by robere2** [comment] 2022-07-12 20:54
I am running into an issue with this while working on my IAM system with [CASL.js](https://casl.js.org/v5/en/). Field access is stored in array, e.g.:

```json
{
  "action": "read",
  "subject": "BlogPost",
  "fields": ["authorName", "contents", "title"]
}
```

To signify access to ALL fields, the `fields` value is omitted:

```json
{
  "action": "read",
  "subject": "BlogPost"
}
```
Prisma will automatically convert null values in my database to `[]`, which is specifically an error in CASL. I would have to undo this manually, which adds unnecessary computation. If I wanted the array to be non-nullable, I would specify it as such, with a default value of `[]`.

My current solution is to just perform a raw query.

**Comment by janpio** [comment] 2022-07-13 14:43
Please make sure to persist this in a not closed issue, here it will most probably be ignored. Thanks.

**Comment by renatocron** [comment] 2022-10-19 10:47
Another issue, will any day be possible to use prisma with `(T | null)[]`  ? for example:

```
create table t (an_array boolean[] not null);
CREATE TABLE

insert into t values ('{null, false, true}'::boolean[]);
INSERT 0 1

select * from t;
  an_array  
------------
 {NULL,f,t}

```
The field itself cannot be null, but I want to have null values on some indices (for exemple: marking the data as not initialized yet on those indices) 


for now I think I gonna convert those fields into JSON

**Comment by bhaugeea** [comment] 2024-10-07 22:42
I'm very happy with Prisma so far, thanks for all the hard work everyone. The `dp pull` option is way better than horrendous weird JS-based DDL for most other ORMs. I do want to chime in on this feature though @pantharshit00:

> Right now we don't support nullable lists by design because ideally, you want to return [] instead of null if there are no items in the lists. I think this ended up in the docs by mistake.
>
> But I do know we would bring nullability back to the arrays due to compatibility reasons but ideally, you should not make them nullable.

I can imagine thinking that an empty array is _usually_ better than `null`, but that is not a compelling case for omitting a very basic database feature. If I want it to be non-nullable and default to an empty array, I'll use the normal database features to accomplish that. I don't understand why we would arbitrarily leave out basic SQL capabilities that everyone expects to be able to use.
