### ISSUE TITLE
A simple many to many relationship causes PANIC: 1

### ISSUE THREAD

**Issue by kran6a** [prisma/prisma#4855] opened 2021-01-02 20:19 UTC
## Bug description

Trying to implement a simple many to many relationship results in findMany causing panic

## How to reproduce

I used the following schema to create a database:
```prisma
datasource db {
  provider = "postgresql"
  url      = "postgresql://[snipped]"
}

generator client {
  provider = "prisma-client-js"
}

model Image {
  hash          String          @id
  tags          Tag[]           @relation(name: "tags")
}

model Tag {
  name          String          @id
  images        Image[]         @relation(name: "tags")
}
```

Then lanched prisma studio and created two Image instances then saved them and created a single tag, then I associated both images with that tag. After that any prisma.image.findMany query that includes or selects images fails with a panic message (including those of prisma studio).

## Expected behavior

The query should not fail since it is almost a copy of a documentation example.

```prisma
//Copied from https://www.prisma.io/docs/support/help-articles/working-with-many-to-many-relations
model Post {
  id    Int    @id @default(autoincrement())
  title String
  tags  Tag[]
}
model Tag {
  id    Int    @id @default(autoincrement())
  name  String @unique
  posts Post[]
}
```

## Prisma information
Included above

## Environment & setup

- OS: Linux (Manjaro)
- Database: PostgreSQL
- Node.js version: 15.5.0
- Prisma version: 

```
@prisma/cli          : 2.13.1
@prisma/client       : 2.13.1
Current platform     : debian-openssl-1.1.x
Query Engine         : query-engine fcbc4bb2d306c86c28014f596b1e8c7980af8bd4 (at ../../../../../home/kranga/.nvm/versions/node/v15.5.0/lib/node_modules/@prisma/cli/node_modules/@prisma/engines/query-engine-debian-openssl-1.1.x)
Migration Engine     : migration-engine-cli fcbc4bb2d306c86c28014f596b1e8c7980af8bd4 (at ../../../../../home/kranga/.nvm/versions/node/v15.5.0/lib/node_modules/@prisma/cli/node_modules/@prisma/engines/migration-engine-debian-openssl-1.1.x)
Introspection Engine : introspection-core fcbc4bb2d306c86c28014f596b1e8c7980af8bd4 (at ../../../../../home/kranga/.nvm/versions/node/v15.5.0/lib/node_modules/@prisma/cli/node_modules/@prisma/engines/introspection-engine-debian-openssl-1.1.x)
Format Binary        : prisma-fmt fcbc4bb2d306c86c28014f596b1e8c7980af8bd4 (at ../../../../../home/kranga/.nvm/versions/node/v15.5.0/lib/node_modules/@prisma/cli/node_modules/@prisma/engines/prisma-fmt-debian-openssl-1.1.x)
Studio               : 0.329.0
```

**Comment by pantharshit00** [comment] 2021-01-12 13:26
I can reproduce this. Looks like we are having a naming conflict in the query graph. 

I have posted a script for reproduction of this issue here: https://github.com/harshit-test-org/prisma-issue-4855

The person who works that part of the engine will look into this now. Thanks for reporting.

**Comment by pantharshit00** [comment] 2021-01-12 13:38
Panic message:
```
Invalid `prisma.image.findMany()` invocation:
  PANIC in query-engine\core\src\interpreter\query_interpreters\nested_read.rs:78:56
1
```

**Comment by pantharshit00** [comment] 2021-01-12 13:48
Looks like this one is duplicate of https://github.com/prisma/prisma-client-js/issues/933 which already has a fix ready so please follow that issue. 

I am closing this one as a duplicate.

**Comment by dpetrick** [comment] 2021-01-12 13:48
Duplicate of https://github.com/prisma/prisma-client-js/issues/933, a fix is already prepared.

**Closed by dpetrick** 2021-01-12 13:48 UTC
Labels: bug/2-confirmed, kind/bug, process/candidate, team/client, topic: broken query
