### ISSUE TITLE
Difference in behavior for deploy and generate for endpoint

### ISSUE THREAD

**Issue by nealoke** [prisma/prisma#4751] opened 2019-07-20 14:10 UTC
**Describe the bug**
After a few hours of frustrating debugging I found the issue I was stumbling on. There is namely a difference in the `prisma deploy` and the generated prisma client (`prisma generate`) which both use the `enpoint` from the `prisma.yml` file. 

I am running a local prisma server (via docker) and when I tried to run `prisma deploy` it would always pull up the login page in my browser in stead of connecting to the local running prisma server. I found that when the `endpoint` is set to an IP adres (from docker) it doesn't work but when setting it to `http://localhost:1234` (1234 being the port of your prisma server) it works correctly.

Then the other side of the coin is when you set the `endpoint` like mentioned above using localhost the client that gets generated also has (at the bottom of the file) the `endpoint: http://localhost:1234`. When you try to run anything in the playground you will see that you get the `request to http://localhost:1234/ failed` error. In order to solve it you basically you need to change the `localhost` to the ip address that was causing the error in the `prisma deploy` command. (eg. `endpoint: http:/172.18.0.1:1234`)

> **How confusing is that?!**

**Expected behavior**
Should be able to use the `endpoint` for both the generated client and the `prisma deploy` command.

**Versions (please complete the following information):**
 - Connector: `Postgres`
 - Prisma Server: `1.34`
 - `prisma` CLI: `prisma/1.34.1 (windows-x64) node-v10.16.0`
 - OS: `Windows 10`

**Comment by pantharshit00** [comment] 2019-07-30 19:05
This is related to the resolution of MANAGEMENT_API_SECRET, so that's why prisma cli is trying to open a login window. 

I think this is a duplicate of https://github.com/prisma/prisma/issues/4483#issuecomment-506482785

**Closed by pantharshit00** 2019-07-30 19:05 UTC
Labels: bug/2-confirmed, kind/bug

**Comment by nealoke** [comment] 2019-08-05 06:43
I don't think it is something with the `MANAGEMENT_API_SECRET` because it is currently not set in my case, unless that is what is causing it. The issue #4483 is similar so I will follow that one, thanks!
