### ISSUE TITLE
Relative db path doesnt work on NixOs

### ISSUE THREAD

**Issue by LamprosPitsillos** [prisma/prisma#21036] opened 2023-09-11 13:36 UTC
### Bug description

#9649 might be related  
Relative path doesn't work properly, while absolute works.

## Logs 
```
2023-09-11T13:30:39.795Z prisma:engines  binaries to download libquery-engine, schema-engine
2023-09-11T13:30:39.795Z prisma:engines  binaries to download libquery-engine, schema-engine
2023-09-11T13:30:39.799Z prisma:get-platform  Found distro info:
{
  "targetDistro": "nixos",
  "originalDistro": "nixos",
  "familyDistro": "nixos"
}
2023-09-11T13:30:39.799Z prisma:get-platform  Found distro info:
{
  "targetDistro": "nixos",
  "originalDistro": "nixos",
  "familyDistro": "nixos"
}
2023-09-11T13:30:39.799Z prisma:get-platform  Don't know any platform-specific paths for "nixos" on x64 (x86_64)
2023-09-11T13:30:39.799Z prisma:get-platform  Don't know any platform-specific paths for "nixos" on x64 (x86_64)
2023-09-11T13:30:39.799Z prisma:get-platform  Falling back to "ldconfig" and other generic paths
2023-09-11T13:30:39.799Z prisma:get-platform  Falling back to "ldconfig" and other generic paths
2023-09-11T13:30:39.826Z prisma:get-platform  Command "openssl version -v" successfully returned "OpenSSL 3.0.10 1 Aug 2023 (Library: OpenSSL 3.0.10 1 Aug 2023)
"
2023-09-11T13:30:39.826Z prisma:get-platform  Command "openssl version -v" successfully returned "OpenSSL 3.0.10 1 Aug 2023 (Library: OpenSSL 3.0.10 1 Aug 2023)
"
2023-09-11T13:30:39.826Z prisma:get-platform  Found openssl binary with version: OpenSSL 3.0.10 1 Aug 2023 (Library: OpenSSL 3.0.10 1 Aug 2023)

2023-09-11T13:30:39.826Z prisma:get-platform  Found openssl binary with version: OpenSSL 3.0.10 1 Aug 2023 (Library: OpenSSL 3.0.10 1 Aug 2023)

2023-09-11T13:30:39.826Z prisma:get-platform  The parsed openssl version is: 3.0.x
2023-09-11T13:30:39.826Z prisma:get-platform  The parsed openssl version is: 3.0.x
2023-09-11T13:30:39.827Z prisma:get-platform  Found distro info:
{
  "targetDistro": "nixos",
  "originalDistro": "nixos",
  "familyDistro": "nixos"
}
2023-09-11T13:30:39.827Z prisma:get-platform  Found distro info:
{
  "targetDistro": "nixos",
  "originalDistro": "nixos",
  "familyDistro": "nixos"
}
2023-09-11T13:30:39.828Z prisma:get-platform  Don't know any platform-specific paths for "nixos" on x64 (x86_64)
2023-09-11T13:30:39.828Z prisma:get-platform  Don't know any platform-specific paths for "nixos" on x64 (x86_64)
2023-09-11T13:30:39.828Z prisma:get-platform  Falling back to "ldconfig" and other generic paths
2023-09-11T13:30:39.828Z prisma:get-platform  Falling back to "ldconfig" and other generic paths
2023-09-11T13:30:39.852Z prisma:get-platform  Command "openssl version -v" successfully returned "OpenSSL 3.0.10 1 Aug 2023 (Library: OpenSSL 3.0.10 1 Aug 2023)
"
2023-09-11T13:30:39.852Z prisma:get-platform  Found openssl binary with version: OpenSSL 3.0.10 1 Aug 2023 (Library: OpenSSL 3.0.10 1 Aug 2023)

2023-09-11T13:30:39.852Z prisma:get-platform  Command "openssl version -v" successfully returned "OpenSSL 3.0.10 1 Aug 2023 (Library: OpenSSL 3.0.10 1 Aug 2023)
"
2023-09-11T13:30:39.852Z prisma:get-platform  Found openssl binary with version: OpenSSL 3.0.10 1 Aug 2023 (Library: OpenSSL 3.0.10 1 Aug 2023)

2023-09-11T13:30:39.853Z prisma:get-platform  The parsed openssl version is: 3.0.x
2023-09-11T13:30:39.853Z prisma:get-platform  The parsed openssl version is: 3.0.x
2023-09-11T13:30:39.853Z prisma:fetch-engine:env  Using env var [1mPRISMA_QUERY_ENGINE_LIBRARY[22m for binary [1mlibquery-engine[22m, which points to [4m/nix/store/hmxi33qpcc3w2lk3z8n5v69pb3bcqd3i-prisma-engines-4.13.0/lib/libquery_engine.node[24m
2023-09-11T13:30:39.853Z prisma:fetch-engine:env  Using env var [1mPRISMA_QUERY_ENGINE_LIBRARY[22m for binary [1mlibquery-engine[22m, which points to [4m/nix/store/hmxi33qpcc3w2lk3z8n5v69pb3bcqd3i-prisma-engines-4.13.0/lib/libquery_engine.node[24m
2023-09-11T13:30:39.853Z prisma:fetch-engine:env  Using env var [1mPRISMA_SCHEMA_ENGINE_BINARY[22m for binary [1mschema-engine[22m, which points to [4m/nix/store/hmxi33qpcc3w2lk3z8n5v69pb3bcqd3i-prisma-engines-4.13.0/bin/migration-engine[24m
2023-09-11T13:30:39.853Z prisma:fetch-engine:env  Using env var [1mPRISMA_SCHEMA_ENGINE_BINARY[22m for binary [1mschema-engine[22m, which points to [4m/nix/store/hmxi33qpcc3w2lk3z8n5v69pb3bcqd3i-prisma-engines-4.13.0/bin/migration-engine[24m
2023-09-11T13:30:39.853Z prisma:fetch-engine:env  Using env var [1mPRISMA_QUERY_ENGINE_LIBRARY[22m for binary [1mlibquery-engine[22m, which points to [4m/nix/store/hmxi33qpcc3w2lk3z8n5v69pb3bcqd3i-prisma-engines-4.13.0/lib/libquery_engine.node[24m
2023-09-11T13:30:39.853Z prisma:fetch-engine:env  Using env var [1mPRISMA_QUERY_ENGINE_LIBRARY[22m for binary [1mlibquery-engine[22m, which points to [4m/nix/store/hmxi33qpcc3w2lk3z8n5v69pb3bcqd3i-prisma-engines-4.13.0/lib/libquery_engine.node[24m
2023-09-11T13:30:39.853Z prisma:fetch-engine:env  Using env var [1mPRISMA_SCHEMA_ENGINE_BINARY[22m for binary [1mschema-engine[22m, which points to [4m/nix/store/hmxi33qpcc3w2lk3z8n5v69pb3bcqd3i-prisma-engines-4.13.0/bin/migration-engine[24m
2023-09-11T13:30:39.853Z prisma:fetch-engine:env  Using env var [1mPRISMA_SCHEMA_ENGINE_BINARY[22m for binary [1mschema-engine[22m, which points to [4m/nix/store/hmxi33qpcc3w2lk3z8n5v69pb3bcqd3i-prisma-engines-4.13.0/bin/migration-engine[24m
2023-09-11T13:30:39.866Z prisma:loadEnv  project root found at /home/inferno/UoC/Ptixiaki/json2db/package.json
2023-09-11T13:30:39.866Z prisma:loadEnv  project root found at /home/inferno/UoC/Ptixiaki/json2db/package.json
2023-09-11T13:30:39.867Z prisma:tryLoadEnv  Environment variables loaded from /home/inferno/UoC/Ptixiaki/json2db/.env
2023-09-11T13:30:39.867Z prisma:tryLoadEnv  Environment variables loaded from /home/inferno/UoC/Ptixiaki/json2db/.env
2023-09-11T13:30:39.869Z prisma:getConfig  Using getConfig Wasm
2023-09-11T13:30:39.869Z prisma:getConfig  Using getConfig Wasm
2023-09-11T13:30:39.873Z prisma:getConfig  config data retrieved without errors in getConfig Wasm
2023-09-11T13:30:39.873Z prisma:getConfig  config data retrieved without errors in getConfig Wasm
2023-09-11T13:30:39.875Z prisma:get-platform  Found distro info:
{
  "targetDistro": "nixos",
  "originalDistro": "nixos",
  "familyDistro": "nixos"
}
2023-09-11T13:30:39.875Z prisma:get-platform  Found distro info:
{
  "targetDistro": "nixos",
  "originalDistro": "nixos",
  "familyDistro": "nixos"
}
2023-09-11T13:30:39.875Z prisma:get-platform  Don't know any platform-specific paths for "nixos" on x64 (x86_64)
2023-09-11T13:30:39.875Z prisma:get-platform  Don't know any platform-specific paths for "nixos" on x64 (x86_64)
2023-09-11T13:30:39.875Z prisma:get-platform  Falling back to "ldconfig" and other generic paths
2023-09-11T13:30:39.875Z prisma:get-platform  Falling back to "ldconfig" and other generic paths
2023-09-11T13:30:39.900Z prisma:get-platform  Command "openssl version -v" successfully returned "OpenSSL 3.0.10 1 Aug 2023 (Library: OpenSSL 3.0.10 1 Aug 2023)
"
2023-09-11T13:30:39.900Z prisma:get-platform  Found openssl binary with version: OpenSSL 3.0.10 1 Aug 2023 (Library: OpenSSL 3.0.10 1 Aug 2023)

2023-09-11T13:30:39.900Z prisma:get-platform  Command "openssl version -v" successfully returned "OpenSSL 3.0.10 1 Aug 2023 (Library: OpenSSL 3.0.10 1 Aug 2023)
"
2023-09-11T13:30:39.900Z prisma:get-platform  Found openssl binary with version: OpenSSL 3.0.10 1 Aug 2023 (Library: OpenSSL 3.0.10 1 Aug 2023)

2023-09-11T13:30:39.901Z prisma:get-platform  The parsed openssl version is: 3.0.x
2023-09-11T13:30:39.901Z prisma:get-platform  The parsed openssl version is: 3.0.x
2023-09-11T13:30:39.901Z prisma:loadEnv  project root found at /home/inferno/UoC/Ptixiaki/json2db/package.json
2023-09-11T13:30:39.901Z prisma:loadEnv  project root found at /home/inferno/UoC/Ptixiaki/json2db/package.json
2023-09-11T13:30:39.902Z prisma:tryLoadEnv  Environment variables loaded from /home/inferno/UoC/Ptixiaki/json2db/.env
2023-09-11T13:30:39.902Z prisma:tryLoadEnv  Environment variables loaded from /home/inferno/UoC/Ptixiaki/json2db/.env
2023-09-11T13:30:39.904Z prisma:getConfig  Using getConfig Wasm
2023-09-11T13:30:39.904Z prisma:getConfig  Using getConfig Wasm
2023-09-11T13:30:39.907Z prisma:getConfig  config data retrieved without errors in getConfig Wasm
2023-09-11T13:30:39.907Z prisma:getConfig  config data retrieved without errors in getConfig Wasm
2023-09-11T13:30:39.912Z prisma:validate  Using validate Wasm
2023-09-11T13:30:39.912Z prisma:validate  Using validate Wasm
2023-09-11T13:30:39.917Z prisma:getConfig  Using getConfig Wasm
2023-09-11T13:30:39.917Z prisma:getConfig  Using getConfig Wasm
2023-09-11T13:30:39.918Z prisma:getConfig  config data retrieved without errors in getConfig Wasm
2023-09-11T13:30:39.918Z prisma:getConfig  config data retrieved without errors in getConfig Wasm
2023-09-11T13:30:39.919Z prisma:getConfig  Using getConfig Wasm
2023-09-11T13:30:39.919Z prisma:getConfig  Using getConfig Wasm
2023-09-11T13:30:39.920Z prisma:getConfig  config data retrieved without errors in getConfig Wasm
2023-09-11T13:30:39.920Z prisma:getConfig  config data retrieved without errors in getConfig Wasm
2023-09-11T13:30:39.920Z prisma:fetch-engine:env  Using env var [1mPRISMA_SCHEMA_ENGINE_BINARY[22m for binary [1mschema-engine[22m, which points to [4m/nix/store/hmxi33qpcc3w2lk3z8n5v69pb3bcqd3i-prisma-engines-4.13.0/bin/migration-engine[24m
2023-09-11T13:30:39.920Z prisma:fetch-engine:env  Using env var [1mPRISMA_SCHEMA_ENGINE_BINARY[22m for binary [1mschema-engine[22m, which points to [4m/nix/store/hmxi33qpcc3w2lk3z8n5v69pb3bcqd3i-prisma-engines-4.13.0/bin/migration-engine[24m
[1m[31mError: [39m[22mError: Schema engine error:
Database dev.db does not exist at ./db/dev.db
    at canConnectToDatabase2 (/home/inferno/UoC/Ptixiaki/json2db/node_modules/prisma/build/index.js:114053:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async ensureDatabaseExists (/home/inferno/UoC/Ptixiaki/json2db/node_modules/prisma/build/index.js:114879:22)
    at async _MigrateDev.parse (/home/inferno/UoC/Ptixiaki/json2db/node_modules/prisma/build/index.js:117123:26)
    at async main2 (/home/inferno/UoC/Ptixiaki/json2db/node_modules/prisma/build/index.js:120301:18)
[1m[31mError: [39m[22mError: Schema engine error:
Database dev.db does not exist at ./db/dev.db
    at canConnectToDatabase2 (/home/inferno/UoC/Ptixiaki/json2db/node_modules/prisma/build/index.js:114053:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async ensureDatabaseExists (/home/inferno/UoC/Ptixiaki/json2db/node_modules/prisma/build/index.js:114879:22)
    at async _MigrateDev.parse (/home/inferno/UoC/Ptixiaki/json2db/node_modules/prisma/build/index.js:117123:26)
    at async main2 (/home/inferno/UoC/Ptixiaki/json2db/node_modules/prisma/build/index.js:120301:18)

```

### How to reproduce

```nix
{
  inputs = {
    # nixpkgs.url = "github:NixOS/nixpkgs/nixos-23.05";
    nixpkgs.url = "github:NixOS/nixpkgs/nixos-23.05";
    systems.url = "github:nix-systems/default";
    devenv.url = "github:cachix/devenv";
  };

  nixConfig = {
    extra-trusted-public-keys = "devenv.cachix.org-1:w1cLUi8dv3hnoSPGAuibQv+f9TZLr6cv/Hm9XgU50cw=";
    extra-substituters = "https://devenv.cachix.org";
  };

  outputs = { self, nixpkgs, devenv, systems, ... } @ inputs:
    let
      forEachSystem = nixpkgs.lib.genAttrs (import systems);
    in
    {
      devShells = forEachSystem
        (system:
          let
            pkgs = nixpkgs.legacyPackages.${system};
          in
          {
            default = devenv.lib.mkShell {
              inherit inputs pkgs;
              modules = [
                {
                  # https://devenv.sh/reference/options/
                  packages = with pkgs;[
                  prisma-engines
                  openssl
                  sqlite
                  ];
                  dotenv.disableHint = true;
                  languages.javascript.enable = true;
                  languages.typescript.enable = true;
                  # enterShell = ''
                  #   hello
                  # '';

                  env.PRISMA_SCHEMA_ENGINE_BINARY = "${pkgs.prisma-engines}/bin/migration-engine";
                  # env.PRISMA_MIGRATION_ENGINE_BINARY="${pkgs.prisma-engines}/bin/migration-engine";
                  env.PRISMA_QUERY_ENGINE_BINARY = "${pkgs.prisma-engines}/bin/query-engine";
                  env.PRISMA_QUERY_ENGINE_LIBRARY = "${pkgs.prisma-engines}/lib/libquery_engine.node";
                  env.PRISMA_FMT_BINARY = "${pkgs.prisma-engines}/bin/prisma-fmt";
                }
              ];
            };
          });
    };
}

```
```
.
├── db
│  ├── dev.db
│  └── dev.db-journal
├── flake.lock
├── flake.nix
├── node_modules
│  ├── @cspotcode
│  ├── @jridgewell
│  ├── @prisma
│  ├── @tsconfig
│  ├── @types
│  ├── acorn
│  ├── acorn-walk
│  ├── arg
│  ├── create-require
│  ├── diff
│  ├── make-error
│  ├── prisma
│  ├── ts-node
│  ├── typescript
│  ├── v8-compile-cache-lib
│  └── yn
├── package-lock.json
├── package.json
├── prisma
│  ├── migrations
│  └── schema.prisma
└── tsconfig.json


```

`npx prisma migrate dev --name init`

### Expected behavior

Find file and migrate db

### Prisma information

```prisma

// This is your Prisma schema file,
// learn more about it in the docs: https://pris.ly/d/prisma-schema

generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "sqlite"
  url      = env("DATABASE_URL")
}

model User {
  id    Int     @id @default(autoincrement())
  email String  @unique
  name  String?
  posts Post[]
}

model Post {
  id        Int     @id @default(autoincrement())
  title     String
  content   String?
  published Boolean @default(false)
  author    User    @relation(fields: [authorId], references: [id])
  authorId  Int
}

```
Doesnt work:
DATABASE_URL="file:./db/dev.db" 
Works :
DATABASE_URL="file:/home/inferno/UoC/Ptixiaki/json2db/db/dev.db"

### Environment & setup

- OS: OS: NixOS 23.11.20230906.0bffda1 (Tapir) x86_64
- Database: SQLite
- Node.js version: v18.17.1

Reproducible flake given above

### Prisma Version

```
Environment variables loaded from ../.env
prisma                  : 5.2.0
@prisma/client          : 5.2.0
Current platform        : linux-nixos
Query Engine (Node-API) : libquery-engine  (at ../../../../../../nix/store/hmxi33qpcc3w2lk3z8n5v69pb3bcqd3i-prisma-engines-4.13.0/lib/libquery_engine.node, resolved by PRISMA_QUERY_ENGINE_LIBRARY)
Schema Engine           : schema-engine-cli  (at ../../../../../../nix/store/hmxi33qpcc3w2lk3z8n5v69pb3bcqd3i-prisma-engines-4.13.0/bin/migration-engine, resolved by PRISMA_SCHEMA_ENGINE_BINARY)
Schema Wasm             : @prisma/prisma-schema-wasm 5.2.0-25.2804dc98259d2ea960602aca6b8e7fdc03c1758f
Default Engines Hash    : 2804dc98259d2ea960602aca6b8e7fdc03c1758f
Studio                  : 0.494.0
```

**Comment by janpio** [comment] 2023-09-11 17:27
What command are you trying to run?
Is it possible that the usage of `PRISMA_SCHEMA_ENGINE_BINARY` breaks relative paths for the SQLite database?

**Comment by LamprosPitsillos** [comment] 2023-09-11 17:38
>What command are you trying to run?

`npx prisma migrate dev --name init`

**Comment by janpio** [comment] 2023-09-18 15:59
Next step: Reproduce this by using `PRISMA_SCHEMA_ENGINE_BINARY` with SQLite and see if this changes the resolution logic of the path. (No need to use NixOS I think)

**Comment by aqrln** [comment] 2024-01-19 13:46
@janpio I don't think any reproduction on our side is necessary here. There should be no difference in behaviour regardless of whether `PRISMA_SCHEMA_ENGINE_BINARY` or NixOS is used, it should be reproducible regardless of the operating system with the default engines because it's not a bug.

`DATABASE_URL="file:./db/dev.db"` in the first post is incorrect, the path must be relative to the schema file, as @LamprosPitsillos already figured out in https://github.com/prisma/prisma/issues/21036#issuecomment-1717041450. This behaviour is expected, and sort of documented in https://www.prisma.io/docs/orm/overview/databases/sqlite albeit in a very confusing and vague way. We should definitely improve the docs to be more explicit.

We might want to revisit this in future major releases, especially now because of driver adapters (the current behaviour already causes troubles for libSQL adapter because it makes it necessary to use different `DATABASE_URL` for Migrate and Client because of it there, or use an absolute path like we do in tests), but that needs to be discussed and planned separately. 

I'll go ahead and close the issue. Thanks for raising this @LamprosPitsillos!

**Closed by aqrln** 2024-01-19 13:46 UTC
Labels: bug/1-unconfirmed, kind/bug, topic: sqlite, team/schema, topic: prisma migrate dev, topic: nix
