### ISSUE TITLE
`db seed` tests need to run on multiple platforms, not just Ubuntu

### ISSUE THREAD

**Issue by janpio** [prisma/prisma#8033] opened 2021-07-02 23:59 UTC
As we know `db seed` has specific problems on specific platforms, hence it needs to be tested on all platforms. This should not be to big of a deal, as it does not actually talk to databases and so can be extracted from the current test suite in GH Actions and be run on all platforms.

**Comment by Jolg42** [comment] 2021-08-13 11:11
WIP in https://github.com/prisma/prisma/pull/8037

**Comment by Jolg42** [comment] 2021-09-06 14:36
Since multi-os testing was added to e2e https://github.com/prisma/e2e-tests/issues/1806

This is not as relevant as before especially if only testing db seed it would not bring more confidence at the tradeoff of more test jobs running 

So basically closing as duplicate of https://github.com/prisma/prisma/issues/7725 for now

**Closed by Jolg42** 2021-09-06 14:36 UTC
Labels: kind/feature, team/migrations, topic: db seed
