### ISSUE TITLE
Github Actions tests failing

### ISSUE THREAD

**Issue by ncphillips** [prisma/prisma#3963] opened 2020-10-19 13:11 UTC
## Bug description

Github Action fails when running tests for gmkit/gmkit#12

```bash
2020-10-19T13:06:12.834Z engine { cwd: '/home/runner/work/gmkit/gmkit/prisma' }
2020-10-19T13:06:13.028Z engine {
  dotPrismaPath: '/home/runner/work/gmkit/gmkit/node_modules/.prisma/client/query-engine-debian-openssl-1.1.x'
}
2020-10-19T13:06:13.032Z engine { flags: [ '--enable-raw-queries' ] }
2020-10-19T13:06:13.035Z engine port: 42715
2020-10-19T13:06:13.065Z engine stdout {
  timestamp: 'Oct 19 13:06:13.065',
  level: 'INFO',
  target: 'quaint::pooled',
  fields: { message: 'Starting a sqlite pool with 5 connections.' }
}
2020-10-19T13:06:13.071Z engine stdout {
  timestamp: 'Oct 19 13:06:13.071',
  level: 'INFO',
  target: 'query_engine::server',
  fields: { message: 'Started http server' }
}
node[2995]: ../src/node_http_parser_impl.h:529:static void node::{anonymous}::Parser::Initialize(const v8::FunctionCallbackInfo<v8::Value>&): Assertion `args[3]->IsInt32()' failed.
  console.error
    2020-10-19T13:06:12.680Z prisma-client {
      engineConfig: {
        cwd: '/home/runner/work/gmkit/gmkit/prisma',
        enableDebugLogs: false,
        enableEngineDebugMode: undefined,
        datamodelPath: '/home/runner/work/gmkit/gmkit/node_modules/.prisma/client/schema.prisma',
        prismaPath: undefined,
        engineEndpoint: undefined,
        generator: {
          name: 'client',
          provider: 'prisma-client-js',
          output: '/home/runner/work/gmkit/gmkit/node_modules/@prisma/client',
          binaryTargets: [],
          previewFeatures: [],
          config: {}
        },
        showColors: false,
        logLevel: undefined,
        logQueries: undefined,
        flags: [],
        clientVersion: '2.5.0',
        enableExperimental: [],
        useUds: undefined
      }
    }

       5 | 
       6 | beforeAll(() => {
    >  7 |   prisma = new PrismaClient()
         |            ^
       8 |   prisma.$connect()
       9 | })
      10 | 

      at Function.createDebug [as log] (node_modules/@prisma/debug/dist/index.js:68:1)
      at enabled (node_modules/@prisma/client/app/src/node_modules/.pnpm/debug@4.1.1/node_modules/debug/src/common.js:119:1)
      at PrismaClientFetcher (node_modules/@prisma/debug/dist/index.js:49:1)
      at new NewPrismaClient (node_modules/@prisma/client/src/runtime/getPrismaClient.ts:351:27)
      at Object.<anonymous> (tests/prisma/campaigns.test.ts:7:12)

  console.error
    2020-10-19T13:06:13.010Z prisma-client Prisma Client call:

      at Function.createDebug [as log] (node_modules/@prisma/debug/dist/index.js:68:1)
      at enabled (node_modules/@prisma/client/app/src/node_modules/.pnpm/debug@4.1.1/node_modules/debug/src/common.js:119:1)
      at valuePaths (node_modules/@prisma/debug/dist/index.js:49:1)
      at NewPrismaClient.params [as _executeRequest] (node_modules/@prisma/client/src/runtime/getPrismaClient.ts:848:13)
      at node_modules/@prisma/client/src/runtime/getPrismaClient.ts:756:27
      at NewPrismaClient._request (node_modules/@prisma/client/src/runtime/getPrismaClient.ts:754:26)

  console.error
    2020-10-19T13:06:13.015Z prisma-client prisma.user.create({
      data: {
        name: 'Bob'
      }
    })

      at Function.createDebug [as log] (node_modules/@prisma/debug/dist/index.js:68:1)
      at enabled (node_modules/@prisma/client/app/src/node_modules/.pnpm/debug@4.1.1/node_modules/debug/src/common.js:119:1)
      at n (node_modules/@prisma/debug/dist/index.js:49:1)
      at NewPrismaClient.params [as _executeRequest] (node_modules/@prisma/client/src/runtime/getPrismaClient.ts:849:27)
      at node_modules/@prisma/client/src/runtime/getPrismaClient.ts:756:27
      at NewPrismaClient._request (node_modules/@prisma/client/src/runtime/getPrismaClient.ts:754:26)

  console.error
    2020-10-19T13:06:13.017Z prisma-client Generated request:

      at Function.createDebug [as log] (node_modules/@prisma/debug/dist/index.js:68:1)
      at enabled (node_modules/@prisma/client/app/src/node_modules/.pnpm/debug@4.1.1/node_modules/debug/src/common.js:119:1)
      at clientMethod (node_modules/@prisma/debug/dist/index.js:49:1)
      at NewPrismaClient.params [as _executeRequest] (node_modules/@prisma/client/src/runtime/getPrismaClient.ts:858:9)
      at node_modules/@prisma/client/src/runtime/getPrismaClient.ts:756:27
      at NewPrismaClient._request (node_modules/@prisma/client/src/runtime/getPrismaClient.ts:754:26)

  console.error
    2020-10-19T13:06:13.019Z prisma-client mutation {
      createOneUser(data: {
        name: "Bob"
      }) {
        id
        name
        email
        emailVerified
        image
        createdAt
        updatedAt
      }
    }

      at Function.createDebug [as log] (node_modules/@prisma/debug/dist/index.js:68:1)
      at enabled (node_modules/@prisma/client/app/src/node_modules/.pnpm/debug@4.1.1/node_modules/debug/src/common.js:119:1)
      at isList (node_modules/@prisma/debug/dist/index.js:49:1)
      at NewPrismaClient.params [as _executeRequest] (node_modules/@prisma/client/src/runtime/getPrismaClient.ts:861:9)
      at node_modules/@prisma/client/src/runtime/getPrismaClient.ts:756:27
      at NewPrismaClient._request (node_modules/@prisma/client/src/runtime/getPrismaClient.ts:754:26)


 1: 0xa17c40 node::Abort() [node]
 2: 0xa17cbe  [node]
 3: 0xa3214a  [node]
 4: 0xc019e9  [node]
 5: 0xc037d7 v8::internal::Builtin_HandleApiCall(int, unsigned long*, v8::internal::Isolate*) [node]
 6: 0x1409319  [node]
/home/runner/work/_temp/7dd18700-8cd9-4d31-bae5-abd5b0d39c1a.sh: line 1:  2995 Aborted                 (core dumped) npx jest --testPathPattern "tests/prisma"
Error: Process completed with exit code 134.
```

## How to reproduce

- Push Code to Github 

## Expected behavior

Tests pass

## Prisma information

- [Action](https://github.com/gmkit/gmkit/blob/encounters/.github/workflows/test.yml)
- [Schema](https://github.com/gmkit/gmkit/blob/encounters/prisma/schema.prisma)
- [Tests](https://github.com/gmkit/gmkit/blob/encounters/tests/prisma/campaigns.test.ts)
- [Failing Action](https://github.com/gmkit/gmkit/pull/12/checks?check_run_id=1275252056)

## Environment & setup

Github Actions

- OS: Ubuntu
- Database: SQLite
- Node.js version: 
- Prisma version: 2.5.0

```

```

**Comment by janpio** [comment] 2020-10-19 13:36
This is related to the node version. Either upgrade to a recent Prisma version, or pin your node version to something earlier than 12.19.0: https://github.com/prisma/prisma-client-js/issues/907

**Comment by pantharshit00** [comment] 2020-10-19 13:44
Indeed, closing as duplicate of https://github.com/prisma/prisma-client-js/issues/907

I will recommend using node 14

**Closed by pantharshit00** 2020-10-19 13:44 UTC

**Comment by ncphillips** [comment] 2020-10-19 14:07
Amazing! Thank you very much. The tests are passing now :)
