### ISSUE TITLE
Migrate Reset

### ISSUE THREAD

**Issue by DevDuque** [prisma/prisma#15337] opened 2022-09-15 13:07 UTC
Hi Prisma Team! The following command just crashed.

## Command

`migrate reset`

## Versions
      
| Name        | Version            |
|-------------|--------------------|
| Platform    | windows            | 
| Node        | v16.17.0           | 
| Prisma CLI  | 4.3.1              | 
| Engine      | c875e43600dfe042452e0b868f7a48b817b9640b| 

## Error
```
Error: Error in migration engine.
Reason: [migration-engine\connectors\sql-migration-connector\src\flavour\sqlite.rs:256:46] failed to truncate sqlite file: Os { code: 5, kind: PermissionDenied, message: "Access Denied" }

Please create an issue with your `schema.prisma` at
https://github.com/prisma/prisma/issues/new

```

**Comment by jkomyno** [comment] 2022-09-15 15:38
Thank you, closing this as a duplicate of https://github.com/prisma/prisma/issues/13991.

**Closed by jkomyno** 2022-09-15 15:38 UTC
