### ISSUE TITLE
1.17-beta: graphql_1.isListType is not a function

### ISSUE THREAD

**Issue by gregwebs** [prisma/prisma#3121] opened 2018-09-17 23:59 UTC
I am unable to generate typescript client code for the latest prisma client. I can generate the go client and the graphql schema just fine.

``` shell
$ node node_modules/.bin/prisma --version
prisma/1.17.0-beta.16 (linux-x64) node-v10.10.0

$  node node_modules/.bin/prisma generate
Generating schema 74ms
 ▸    graphql_1.isListType is not a function

Get in touch if you need help: https://www.prisma.io/forum/
To get more detailed output, run $ export DEBUG="*"
```

**Comment by marktani** [comment] 2018-09-18 06:27
Thanks for the report, can you share a reproduction?

**Comment by gregwebs** [comment] 2018-09-18 14:00
This happens for me with any schema, including the example graphql model given from the [blog](https://www.prisma.io/blog/prisma-client-beta-ahph4o1umail/).

**Comment by gregwebs** [comment] 2018-09-18 22:18
This may be unrelated, but I also have the issue of `prisma list` showing no services (after a successful `prisma deploy`) and `prisma introspect` not connecting:

```
$ ./node_modules/.bin/prisma deploy
Deploying service `default` to stage `default` to server `local` 636ms
Service is already up to date.

$ ./node_modules/.bin/prisma introspect
 ▸    Could not connect to database. Project not found:
 ▸    'prisma-temporary-introspection-service@prisma-temporary-test-stage':
 ▸    {"response":{"errors":[{"message":"Project not found:
 ▸    'prisma-temporary-introspection-service@prisma-temporary-test-stage'","code":3016,"requestId":"local:api:cjm89qozv00060a945n4dqsp2"}],"status":200},"request":{"query":"{\n
 ▸    __type(name: \"PrismaDatabase\") {\n        kind\n        enumValues {\n          name\n        }\n
 ▸    }\n    }"}}

Get in touch if you need help: https://www.prisma.io/forum/
To get more detailed output, run $ export DEBUG="*"

mysql> select * from Project;
+--------------------------------------------------------------------+---------+------------+----------------------------------+-------+--------------+----------------+-----------+
| id                                                                 | ownerId | webhookUrl | secrets                          | seats | allowQueries | allowMutations | functions |
+--------------------------------------------------------------------+---------+------------+----------------------------------+-------+--------------+----------------+-----------+
| default@default                                                    | NULL    |            | []                               | NULL  |            1 |              1 | []        |
| prisma-temporary-introspection-service@prisma-temporary-test-stage | NULL    |            | ["prisma-instrospection-secret"] | NULL  |            1 |              1 | []        |
+--------------------------------------------------------------------+---------+------------+----------------------------------+-------+--------------+----------------+-----------+
2 rows in set (0.00 sec)

```

Note that I was able to seed data, see it in the database, and to use the go language bindings (or just the playground) to make queries

**Comment by gregwebs** [comment] 2018-09-18 23:57
The second issue does seem very much unrelated since the first workflow doesn't involve the database. For the second issue I see this in the logs:

```
prisma_1  | Caused by: java.sql.SQLException: Identifier name 'prisma-temporary-introspection-service@prisma-temporary-test-stage' is too long
prisma_1  | Query is: CREATE SCHEMA `prisma-temporary-introspection-service@prisma-temporary-test-stage` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci; 
```

**Comment by gregwebs** [comment] 2018-09-19 00:04
oh. I see that `introspect` is only available for postgres. It would be nice if the command gave me that as an error before running! I still dont' know why `list` does not work.

**Comment by gregwebs** [comment] 2018-09-19 05:14
amazingly I did some re-installs and wrote out a large schema and now `prisma generate` is working for TypeScript. Not sure how to reproduce this for you.

**Comment by marktani** [comment] 2018-09-28 15:53
Closing this as it seems to be a version mismatch of some sort.

**Closed** 2018-10-08 10:37 UTC
