### ISSUE TITLE
Investigate origin of `AWS Lambda timed out` (#1754)

### ISSUE THREAD

**Issue by Jolg42** [prisma/prisma#1921] opened 2020-03-24 15:59 UTC
I found a solution to #1754 [reproduction is here](https://github.com/UWellFail/prisma2--1754) 
https://github.com/prisma/prisma2/issues/1754#issuecomment-601271228
```
// Set to false to send the response right away when the callback executes, instead of waiting for the Node.js event loop to be empty.
context.callbackWaitsForEmptyEventLoop = false;
```

But this means that the Node.js event loop is not empty and it should be empty.

### Without `context.callbackWaitsForEmptyEventLoop = false`
A POST request works perfectly. Only the GET requests in this example have a non empty event loop.

We could start investigating with: 
- Try out pure Prisma Client in lambda without the apollo server overhead, get the GET and POST event running
- Instead of the callback based approach, try using a promise and play with async: true as described here https://github.com/serverless/serverless/issues/3171#issuecomment-540101244
- Try to get serverless offline running with a simple prisma client example https://serverless.com/plugins/serverless-offline/

**Comment by pantharshit00** [comment] 2020-03-25 19:16
Marking it as a confirmed bug I can reproduce the timeouts.

**Comment by Jolg42** [comment] 2020-03-26 09:21
@pantharshit00 You mean confirmed with reproduction https://github.com/UWellFail/prisma2--1754 I guess?

**Comment by pantharshit00** [comment] 2020-03-26 10:19
Yes, that one.

**Comment by timsuchanek** [comment] 2020-04-07 09:32
> But this means that the Node.js event loop is not empty and it should be empty.
As we have an open handle to the database with an active connection, the event loop can't be empty, therefore this is not a bug.

**Closed by timsuchanek** 2020-04-07 09:32 UTC
Labels: bug/2-confirmed, kind/bug, process/candidate, topic: deployment-platforms
