### ISSUE TITLE
PrismaClientInitializationError:  Invalid `prisma.post.findMany()` (related to Studio?)

### ISSUE THREAD

**Issue by nikolasburk** [prisma/prisma#2761] opened 2020-06-15 08:21 UTC
I'm running into a strange bug.

I start with this SQL schema:

```sql
CREATE TABLE "public"."User" (
  id SERIAL PRIMARY KEY NOT NULL,
  name VARCHAR(255),
  email VARCHAR(255) UNIQUE NOT NULL
);

CREATE TABLE "public"."Post" (
  id SERIAL PRIMARY KEY NOT NULL,
  title VARCHAR(255) NOT NULL,
  "createdAt" TIMESTAMP NOT NULL DEFAULT now(),
  content TEXT,
  published BOOLEAN NOT NULL DEFAULT false,
  "authorId" INTEGER NOT NULL,
  FOREIGN KEY ("authorId") REFERENCES "public"."User"(id)
);

CREATE TABLE "public"."Profile" (
  id SERIAL PRIMARY KEY NOT NULL,
  bio TEXT,
  "userId" INTEGER UNIQUE NOT NULL,
  FOREIGN KEY ("userId") REFERENCES "public"."User"(id)
);
```

Then I `init` and `introspect` the DB in a new TS project and make some adjustments to the generated Prisma schema:

```prisma
generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

model Post {
  authorId  Int
  content   String?
  createdAt DateTime @default(now())
  id        Int      @default(autoincrement()) @id
  published Boolean  @default(false)
  title     String
  author    User     @relation(fields: [authorId], references: [id])
}

model Profile {
  bio    String?
  id     Int     @default(autoincrement()) @id
  userId Int     @unique
  user   User    @relation(fields: [userId], references: [id])
}

model User {
  email   String   @unique
  id      Int      @default(autoincrement()) @id
  name    String?
  posts   Post[]
  profile Profile?
}
```

Then I `npm install @prisma/client`, this is what my `package.json` looks like:

```json
{
  "name": "starter",
  "version": "1.0.0",
  "main": "index.ts",
  "license": "MIT",
  "dependencies": {
    "@prisma/client": "^2.0.0",
    "@types/node": "^14.0.4"
  },
  "devDependencies": {
    "@prisma/cli": "^2.0.0",
    "ts-node": "^8.10.1",
    "typescript": "^3.9.3"
  },
  "scripts": {
    "dev": "ts-node src/index.ts"
  }
}
```

Then I run this script:

```
import { PrismaClient } from '@prisma/client'

const prisma = new PrismaClient()

async function main() {
  const posts = await prisma.post.findMany()
  console.dir(posts, { depth: null })
}

main()
  .catch((e) => console.error(e))
  .finally(async () => await prisma.disconnect())
```

Everything works.

Then I start Prisma Studio:

```
yarn prisma studio --experimental
```

I open Studio and it works fine. But when I go back to the script and run it again, I get this error:

```
$ yarn dev
yarn run v1.22.0
$ ts-node src/index.ts
PrismaClientInitializationError: 
Invalid `prisma.post.findMany()` invocation in
/Users/nikolasburk/prisma/talks/2020/prisma-day/dry-runs/dr2/src/index.ts:6:35

  2 
  3 const prisma = new PrismaClient()
  4 
  5 async function main() {
→ 6   const posts = await prisma.post.findMany(
  error: Environment variable not found: DATABASE_URL.
  -->  schema.prisma:7
   | 
 6 |   provider = "postgresql"
 7 |   url      = env("DATABASE_URL")
   | 

Validation Error Count: 1
    at PrismaClientFetcher.request (/Users/nikolasburk/prisma/talks/2020/prisma-day/dry-runs/dr2/node_modules/.prisma/client/src/runtime/getPrismaClient.ts:768:15)
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
(node:6295) UnhandledPromiseRejectionWarning: Error: error: Environment variable not found: DATABASE_URL.
  -->  schema.prisma:7
   | 
 6 |   provider = "postgresql"
 7 |   url      = env("DATABASE_URL")
   | 

Validation Error Count: 1
    at LineStream.<anonymous> (/Users/nikolasburk/prisma/talks/2020/prisma-day/dry-runs/dr2/node_modules/.prisma/engine-core/dist/NodeEngine.js:419:1)
    at LineStream.emit (events.js:196:13)
    at LineStream.EventEmitter.emit (domain.js:471:20)
    at addChunk (_stream_readable.js:290:12)
    at readableAddChunk (_stream_readable.js:271:11)
    at LineStream.Readable.push (_stream_readable.js:226:10)
    at LineStream.push (_stream_transform.js:150:32)
    at LineStream._pushBuffer (/Users/nikolasburk/prisma/talks/2020/prisma-day/dry-runs/dr2/node_modules/.prisma/engine-core/dist/byline.js:106:1)
    at LineStream._transform (/Users/nikolasburk/prisma/talks/2020/prisma-day/dry-runs/dr2/node_modules/.prisma/engine-core/dist/byline.js:98:1)
    at LineStream.Transform._read (_stream_transform.js:189:10)
(node:6295) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:6295) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
✨  Done in 1.15s.
```

**Comment by janpio** [comment] 2020-06-15 18:02
Hey, that's the one that messed with you during your meetup talk!

**Comment by pantharshit00** [comment] 2020-06-18 14:29
I am unable to reproduce this with `2.1.0-dev.39`
![image](https://user-images.githubusercontent.com/22195362/85033124-36c43980-b19e-11ea-8349-bba364a326dd.png)

Maybe you should try to reproduce this with dev once.

**Comment by janpio** [comment] 2021-03-23 19:26
I am going to close this now. Happy to take a look again if we get more information.

**Closed by janpio** 2021-03-23 19:26 UTC
Labels: bug/1-repro-available, kind/bug, status/needs-action, topic: env, topic: studio
