### ISSUE TITLE
SQL Server Introspection Error

### ISSUE THREAD

**Issue by ruheni** [prisma/prisma#4762] opened 2020-12-21 20:37 UTC
## Bug description
I seem to be running an error when I run `npx prisma introspect` a SQL server db on Azure. 
Here's the error I run into:
```
Environment variables loaded from .env
Prisma schema loaded from prisma\schema.prisma
Introspecting based on datasource defined in prisma\schema.prisma …
Error: P4002
The schema of the introspected database was inconsistent: Table RhionsUsers not found.
```
The DB structure is as follows:
![image_2020_12_20T10_55_31_908Z](https://user-images.githubusercontent.com/33921841/102819329-51dd6380-43e4-11eb-967b-88b65811a678.png)

## Expected behavior

Generate models and add them to `schema.prisma` file

## Environment & setup

- OS: Windows
- Database: mssql
- Node.js version: 14.15.1
- Prisma version: 
```
Environment variables loaded from .env
@prisma/cli          : 2.13.1
@prisma/client       : Not found
Current platform     : windows
Query Engine         : query-engine fcbc4bb2d306c86c28014f596b1e8c7980af8bd4 (at node_modules\@prisma\engines\query-engine-windows.exe)
Migration Engine     : migration-engine-cli fcbc4bb2d306c86c28014f596b1e8c7980af8bd4 (at node_modules\@prisma\engines\migration-engine-windows.exe)
Introspection Engine : introspection-core fcbc4bb2d306c86c28014f596b1e8c7980af8bd4 (at node_modules\@prisma\engines\introspection-engine-windows.exe)
Format Binary        : prisma-fmt fcbc4bb2d306c86c28014f596b1e8c7980af8bd4 (at node_modules\@prisma\engines\prisma-fmt-windows.exe)
Studio               : 0.329.0
Preview Features     : microsoftSqlServer
```

**Comment by pantharshit00** [comment] 2020-12-23 11:32
Hey @ruheni 


Can you please share a schema dump of this database? I just wanted to check if there are no cross schema references which I think we don't support in Prisma yet.

**Comment by ruheni** [comment] 2020-12-23 20:33
Does this help?
```sql
/****** Object:  Table [dbo].[__EFMigrationsHistory]    Script Date: 23/12/2020 23:32:44 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[__EFMigrationsHistory](
	[MigrationId] [nvarchar](150) NOT NULL,
	[ProductVersion] [nvarchar](32) NOT NULL,
 CONSTRAINT [PK___EFMigrationsHistory] PRIMARY KEY CLUSTERED 
(
	[MigrationId] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Devices]    Script Date: 23/12/2020 23:32:44 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Devices](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[DeviceVersionId] [int] NOT NULL,
	[DeviceNetId] [nvarchar](max) NOT NULL,
	[BatteryLevel] [float] NOT NULL,
	[IsAllocated] [bit] NOT NULL,
	[DateAllocated] [datetime2](7) NULL,
	[RhionsDeviceKind] [int] NOT NULL,
 CONSTRAINT [PK_Devices] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[DeviceVersions]    Script Date: 23/12/2020 23:32:44 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[DeviceVersions](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[FirmwareVersionNumber] [nvarchar](max) NOT NULL,
	[HardwareVersionNumber] [nvarchar](max) NOT NULL,
	[FirmwareReleaseNotes] [nvarchar](max) NULL,
	[HardwareDescription] [nvarchar](max) NOT NULL,
 CONSTRAINT [PK_DeviceVersions] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[InternalAccessLogs]    Script Date: 23/12/2020 23:32:44 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[InternalAccessLogs](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[DateAccessed] [datetime2](7) NOT NULL,
	[Claims] [nvarchar](max) NULL,
	[Name] [nvarchar](max) NULL,
	[Activity] [nvarchar](max) NOT NULL,
 CONSTRAINT [PK_InternalAccessLogs] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Organizations]    Script Date: 23/12/2020 23:32:44 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Organizations](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[OrganizationName] [nvarchar](max) NOT NULL,
	[Country] [nvarchar](max) NOT NULL,
	[County] [nvarchar](max) NULL,
 CONSTRAINT [PK_Organizations] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[ProtectedAreas]    Script Date: 23/12/2020 23:32:44 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ProtectedAreas](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Name] [nvarchar](max) NOT NULL,
	[OrganizationId] [int] NOT NULL,
 CONSTRAINT [PK_ProtectedAreas] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[RhionsAccounts]    Script Date: 23/12/2020 23:32:44 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[RhionsAccounts](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[ProtectedAreaId] [int] NOT NULL,
	[RhionsUserId] [int] NOT NULL,
	[ProfilePicUrl] [nvarchar](max) NULL,
	[FirstName] [nvarchar](max) NOT NULL,
	[LastName] [nvarchar](max) NOT NULL,
	[IsActive] [bit] NOT NULL,
	[IsEnabled] [bit] NOT NULL,
 CONSTRAINT [PK_RhionsAccounts] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[RhionsTrails]    Script Date: 23/12/2020 23:32:44 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[RhionsTrails](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[RhionsDeviceId] [int] NOT NULL,
	[ShapeFileId] [int] NULL,
	[ProtectedAreaId] [int] NOT NULL,
	[DateCollared] [datetime2](7) NOT NULL,
	[RhionsTrailName] [nvarchar](max) NOT NULL,
	[AnimalKind] [nvarchar](max) NOT NULL,
 CONSTRAINT [PK_RhionsTrails] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[ShapeFiles]    Script Date: 23/12/2020 23:32:44 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ShapeFiles](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[BlobContainerName] [nvarchar](max) NOT NULL,
	[BlobItemName] [nvarchar](max) NOT NULL,
	[UploadDate] [datetime2](7) NOT NULL,
	[ProtectedAreaId] [int] NOT NULL,
 CONSTRAINT [PK_ShapeFiles] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TrailMessages]    Script Date: 23/12/2020 23:32:44 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TrailMessages](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[RhionsTrailId] [int] NOT NULL,
	[Time] [datetime2](7) NOT NULL,
	[Longitude] [float] NOT NULL,
	[Latitude] [float] NOT NULL,
	[BatteryLevel] [float] NULL,
 CONSTRAINT [PK_TrailMessages] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [Security].[RhionsRoles]    Script Date: 23/12/2020 23:32:44 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [Security].[RhionsRoles](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Name] [nvarchar](256) NULL,
	[NormalizedName] [nvarchar](256) NULL,
	[ConcurrencyStamp] [nvarchar](max) NULL,
 CONSTRAINT [PK_RhionsRoles] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [Security].[RhionsUsers]    Script Date: 23/12/2020 23:32:44 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [Security].[RhionsUsers](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[UserName] [nvarchar](256) NULL,
	[NormalizedUserName] [nvarchar](256) NULL,
	[Email] [nvarchar](256) NULL,
	[NormalizedEmail] [nvarchar](256) NULL,
	[EmailConfirmed] [bit] NOT NULL,
	[PasswordHash] [nvarchar](max) NULL,
	[SecurityStamp] [nvarchar](max) NULL,
	[ConcurrencyStamp] [nvarchar](max) NULL,
	[PhoneNumber] [nvarchar](max) NULL,
	[PhoneNumberConfirmed] [bit] NOT NULL,
	[TwoFactorEnabled] [bit] NOT NULL,
	[LockoutEnd] [datetimeoffset](7) NULL,
	[LockoutEnabled] [bit] NOT NULL,
	[AccessFailedCount] [int] NOT NULL,
 CONSTRAINT [PK_RhionsUsers] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [Security].[RoleClaims]    Script Date: 23/12/2020 23:32:44 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [Security].[RoleClaims](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[RoleId] [int] NOT NULL,
	[ClaimType] [nvarchar](max) NULL,
	[ClaimValue] [nvarchar](max) NULL,
 CONSTRAINT [PK_RoleClaims] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [Security].[UserClaims]    Script Date: 23/12/2020 23:32:44 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [Security].[UserClaims](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[UserId] [int] NOT NULL,
	[ClaimType] [nvarchar](max) NULL,
	[ClaimValue] [nvarchar](max) NULL,
 CONSTRAINT [PK_UserClaims] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [Security].[UserLogins]    Script Date: 23/12/2020 23:32:44 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [Security].[UserLogins](
	[LoginProvider] [nvarchar](450) NOT NULL,
	[ProviderKey] [nvarchar](450) NOT NULL,
	[ProviderDisplayName] [nvarchar](max) NULL,
	[UserId] [int] NOT NULL,
 CONSTRAINT [PK_UserLogins] PRIMARY KEY CLUSTERED 
(
	[LoginProvider] ASC,
	[ProviderKey] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [Security].[UserRoles]    Script Date: 23/12/2020 23:32:44 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [Security].[UserRoles](
	[UserId] [int] NOT NULL,
	[RoleId] [int] NOT NULL,
 CONSTRAINT [PK_UserRoles] PRIMARY KEY CLUSTERED 
(
	[UserId] ASC,
	[RoleId] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [Security].[UserTokens]    Script Date: 23/12/2020 23:32:44 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [Security].[UserTokens](
	[UserId] [int] NOT NULL,
	[LoginProvider] [nvarchar](450) NOT NULL,
	[Name] [nvarchar](450) NOT NULL,
	[Value] [nvarchar](max) NULL,
 CONSTRAINT [PK_UserTokens] PRIMARY KEY CLUSTERED 
(
	[UserId] ASC,
	[LoginProvider] ASC,
	[Name] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE [dbo].[Devices]  WITH CHECK ADD  CONSTRAINT [FK_Devices_DeviceVersions_DeviceVersionId] FOREIGN KEY([DeviceVersionId])
REFERENCES [dbo].[DeviceVersions] ([Id])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[Devices] CHECK CONSTRAINT [FK_Devices_DeviceVersions_DeviceVersionId]
GO
ALTER TABLE [dbo].[ProtectedAreas]  WITH CHECK ADD  CONSTRAINT [FK_ProtectedAreas_Organizations_OrganizationId] FOREIGN KEY([OrganizationId])
REFERENCES [dbo].[Organizations] ([Id])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[ProtectedAreas] CHECK CONSTRAINT [FK_ProtectedAreas_Organizations_OrganizationId]
GO
ALTER TABLE [dbo].[RhionsAccounts]  WITH CHECK ADD  CONSTRAINT [FK_RhionsAccounts_ProtectedAreas_ProtectedAreaId] FOREIGN KEY([ProtectedAreaId])
REFERENCES [dbo].[ProtectedAreas] ([Id])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[RhionsAccounts] CHECK CONSTRAINT [FK_RhionsAccounts_ProtectedAreas_ProtectedAreaId]
GO
ALTER TABLE [dbo].[RhionsAccounts]  WITH CHECK ADD  CONSTRAINT [FK_RhionsAccounts_RhionsUsers_RhionsUserId] FOREIGN KEY([RhionsUserId])
REFERENCES [Security].[RhionsUsers] ([Id])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[RhionsAccounts] CHECK CONSTRAINT [FK_RhionsAccounts_RhionsUsers_RhionsUserId]
GO
ALTER TABLE [dbo].[RhionsTrails]  WITH CHECK ADD  CONSTRAINT [FK_RhionsTrails_Devices_RhionsDeviceId] FOREIGN KEY([RhionsDeviceId])
REFERENCES [dbo].[Devices] ([Id])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[RhionsTrails] CHECK CONSTRAINT [FK_RhionsTrails_Devices_RhionsDeviceId]
GO
ALTER TABLE [dbo].[RhionsTrails]  WITH CHECK ADD  CONSTRAINT [FK_RhionsTrails_ProtectedAreas_ProtectedAreaId] FOREIGN KEY([ProtectedAreaId])
REFERENCES [dbo].[ProtectedAreas] ([Id])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[RhionsTrails] CHECK CONSTRAINT [FK_RhionsTrails_ProtectedAreas_ProtectedAreaId]
GO
ALTER TABLE [dbo].[RhionsTrails]  WITH CHECK ADD  CONSTRAINT [FK_RhionsTrails_ShapeFiles_ShapeFileId] FOREIGN KEY([ShapeFileId])
REFERENCES [dbo].[ShapeFiles] ([Id])
GO
ALTER TABLE [dbo].[RhionsTrails] CHECK CONSTRAINT [FK_RhionsTrails_ShapeFiles_ShapeFileId]
GO
ALTER TABLE [dbo].[ShapeFiles]  WITH CHECK ADD  CONSTRAINT [FK_ShapeFiles_ProtectedAreas_ProtectedAreaId] FOREIGN KEY([ProtectedAreaId])
REFERENCES [dbo].[ProtectedAreas] ([Id])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[ShapeFiles] CHECK CONSTRAINT [FK_ShapeFiles_ProtectedAreas_ProtectedAreaId]
GO
ALTER TABLE [dbo].[TrailMessages]  WITH CHECK ADD  CONSTRAINT [FK_TrailMessages_RhionsTrails_RhionsTrailId] FOREIGN KEY([RhionsTrailId])
REFERENCES [dbo].[RhionsTrails] ([Id])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[TrailMessages] CHECK CONSTRAINT [FK_TrailMessages_RhionsTrails_RhionsTrailId]
GO
ALTER TABLE [Security].[RoleClaims]  WITH CHECK ADD  CONSTRAINT [FK_RoleClaims_RhionsRoles_RoleId] FOREIGN KEY([RoleId])
REFERENCES [Security].[RhionsRoles] ([Id])
ON DELETE CASCADE
GO
ALTER TABLE [Security].[RoleClaims] CHECK CONSTRAINT [FK_RoleClaims_RhionsRoles_RoleId]
GO
ALTER TABLE [Security].[UserClaims]  WITH CHECK ADD  CONSTRAINT [FK_UserClaims_RhionsUsers_UserId] FOREIGN KEY([UserId])
REFERENCES [Security].[RhionsUsers] ([Id])
ON DELETE CASCADE
GO
ALTER TABLE [Security].[UserClaims] CHECK CONSTRAINT [FK_UserClaims_RhionsUsers_UserId]
GO
ALTER TABLE [Security].[UserLogins]  WITH CHECK ADD  CONSTRAINT [FK_UserLogins_RhionsUsers_UserId] FOREIGN KEY([UserId])
REFERENCES [Security].[RhionsUsers] ([Id])
ON DELETE CASCADE
GO
ALTER TABLE [Security].[UserLogins] CHECK CONSTRAINT [FK_UserLogins_RhionsUsers_UserId]
GO
ALTER TABLE [Security].[UserRoles]  WITH CHECK ADD  CONSTRAINT [FK_UserRoles_RhionsRoles_RoleId] FOREIGN KEY([RoleId])
REFERENCES [Security].[RhionsRoles] ([Id])
ON DELETE CASCADE
GO
ALTER TABLE [Security].[UserRoles] CHECK CONSTRAINT [FK_UserRoles_RhionsRoles_RoleId]
GO
ALTER TABLE [Security].[UserRoles]  WITH CHECK ADD  CONSTRAINT [FK_UserRoles_RhionsUsers_UserId] FOREIGN KEY([UserId])
REFERENCES [Security].[RhionsUsers] ([Id])
ON DELETE CASCADE
GO
ALTER TABLE [Security].[UserRoles] CHECK CONSTRAINT [FK_UserRoles_RhionsUsers_UserId]
GO
ALTER TABLE [Security].[UserTokens]  WITH CHECK ADD  CONSTRAINT [FK_UserTokens_RhionsUsers_UserId] FOREIGN KEY([UserId])
REFERENCES [Security].[RhionsUsers] ([Id])
ON DELETE CASCADE
GO
ALTER TABLE [Security].[UserTokens] CHECK CONSTRAINT [FK_UserTokens_RhionsUsers_UserId]
GO
```

**Comment by pantharshit00** [comment] 2020-12-25 18:04
Indeed you have a different schemas `Security` and `dbo`. Prisma doesn't support multiple schemas in one app yet. Marking this as a feature request.

**Comment by pimeys** [comment] 2021-01-05 15:20
Yeah. What should happen here is that we should introspect either `dbo` or `Security`, depending of the connection parameters. By default we choose `dbo` and try to introspect that.

The problem is that one of the tables, `RhionsAccounts` in the `dbo` schema that has a foreign key linking to `RhionsUsers` in the `Security` schema. The introspection diligently stays in the schema it's been told to be, and cannot find this table.

This is definitely a feature request, not a bug.

**Comment by janpio** [comment] 2021-01-05 15:47
Thanks for reporting this, we already have an issue for foreign keys that span schemas: https://github.com/prisma/prisma/issues/1175

I am closing this issue.

**Closed by janpio** 2021-01-05 15:47 UTC
Labels: kind/feature, team/support-engineering, topic: data-introspection, topic: sql server
