### ISSUE TITLE
CLI generate: Add option to continue watching in case of error

### ISSUE THREAD

**Issue by tobiasdiez** [prisma/prisma#8847] opened 2021-08-20 21:17 UTC
## Problem
If you run `prisma generate --watch`, edit the schema and a validation error occurs, then the generate command exits with code 1. Eg:
```
[prisma:generate:watch] Schema parsing
[prisma:generate:watch] error: Error validating field `journalIssue` in model `UserDocument`: The relati
[prisma:generate:watch] on field `journalIssue` on Model `UserDocument` is missing an opposite relation 
[prisma:generate:watch] field on the model `JournalIssue`. Either run `prisma format` or add it manually
[prisma:generate:watch]     at Socket.Writable.write (node:internal/streams/writable:334:10)
[prisma:generate:watch]     at GeneratorProcess2.sendMessage (D:\Programming\JabRefOnline\node_modules\prisma\build\index.js:32830:24)
[prisma:generate:watch]     at D:\Programming\JabRefOnline\node_modules\prisma\build\index.js:32874:14
[prisma:generate:watch]     at new Promise (<anonymous>)
error Command failed with exit code 1.
[prisma:generate:watch] yarn run prisma:generate:watch exited with code 1
```

This may be inconvenient since after fixing the error you have to restart the generation watch.

## Suggested solution

Add a cli option which disables exit in case of errors, i.e. something like `prisma generate --watch --continueOnError`

**Comment by Janpot** [comment] 2022-02-21 10:38
> Add a cli option which disables exit in case of errors

I'd argue that this should be the default behavior and instead, if there's demand for it, add an option to `--exitOnError`.

**Comment by Jolg42** [comment] 2022-02-21 11:03
My point of view is, it would be better to not exit by default with `--watch` when iterating on my schema like suggested here.
For example, I do a typo and correct it, then the flow would be interrupted by relaunching the command after an error.

Though I could not reproduce the flow here as it seems that `prisma generate --watch` doesn't exit on error anymore.

@Janpot could you try and see what's the behavior for you now?

**Comment by Janpot** [comment] 2022-02-21 11:30
Can't reproduce anymore neither. Found the GitHub issue after I `prisma generate --watch` did not recover after fixing an error and immediately assumed I was hitting this problem. Trying to reproduce now it seems like it recovers correctly for me as well.
Going through my log output again, looks like the process didn't exit, but rather the file watcher missed an update or something.

**Comment by Jolg42** [comment] 2022-02-21 11:34
Ok then I think the best here will be that I close this issue since it's already the current behavior.

If you see a bug or a possible improvement, it will be greatly appreciated if you could create a new issue 🙇🏼‍♂️

**Closed by Jolg42** 2022-02-21 11:34 UTC
Labels: kind/improvement, topic: prisma generate, tech/typescript, team/client
