### ISSUE TITLE
Error: [introspection-engine\connectors\sql-introspection-connector\src\re_introspection.rs:378:14] Could not find relation field Transaction on model Account. 

### ISSUE THREAD

**Issue by tomhoule** [prisma/prisma#10124] opened 2021-11-05 09:42 UTC
This could be related to the recent relation lifting refactoring.

Command: `prisma db pull`
Version: `3.4.0`
Binary Version: `1c9fdaa9e2319b814822d6dbfd0a69e1fcc13a85`
Report: https://prisma-errors.netlify.app/report/13562 
OS: `x64 win32 10.0.22000`

JS Stacktrace:
```
Error: [introspection-engine\connectors\sql-introspection-connector\src\re_introspection.rs:378:14] Could not find relation field Transaction on model Account.
    at ChildProcess.<anonymous> (D:\work\open_source\financeNext\node_modules\prisma\build\index.js:45755:30)
    at ChildProcess.emit (events.js:376:20)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
```

Rust Stacktrace:
```
   0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: <unknown>
   7: <unknown>
   8: <unknown>
   9: <unknown>
  10: <unknown>
  11: <unknown>
  12: <unknown>
  13: <unknown>
  14: <unknown>
  15: <unknown>
  16: <unknown>
  17: <unknown>
  18: <unknown>
  19: <unknown>
  20: <unknown>
  21: <unknown>
  22: <unknown>
  23: <unknown>
  24: <unknown>
  25: <unknown>
  26: BaseThreadInitThunk
  27: RtlUserThreadStart

```

**Comment by jkomyno** [comment] 2023-02-17 12:48
Closing as a duplicate of https://github.com/prisma/prisma/issues/10453

**Closed by jkomyno** 2023-02-17 12:48 UTC
Labels: bug/1-unconfirmed, kind/bug, topic: introspection, topic: sqlite, topic: re-introspection, tech/engines, topic: error reporting, team/schema, topic: prisma db pull
