### ISSUE TITLE
Error: [libs/datamodel/core/src/diagnostics/helper.rs:8:27] byte index 1806 is not a char boundary; it is inside '中' (bytes 1805..1808) of `generator client { 

### ISSUE THREAD

**Issue by divyenduz** [prisma/prisma#5343] opened 2021-01-29 09:39 UTC
Command: `prisma introspect`
Version: `2.15.0`
Binary Version: `e51dc3b5a9ee790a07104bec1c9477d51740fe54`
Report: https://prisma-errors.netlify.app/report/12786 
OS: `x64 darwin 20.2.0`

JS Stacktrace:
```
Error: [libs/datamodel/core/src/diagnostics/helper.rs:8:27] byte index 1806 is not a char boundary; it is inside '中' (bytes 1805..1808) of `generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "mysql"
  url      = env("DATABASE_URL")
}

/// 証明書情報
model Certificate {
  ///
  /// 証明書番号
  serialNumber String           @id @map("serial_number")
  /`[...]
    at ChildProcess.<anonymous> (/Users/sachoboo/g/work/harmo/harmophr/backend-fs/facility/node_modules/@prisma/cli/build/index.js:4780:28)
    at ChildProcess.emit (node:events:379:20)
    at ChildProcess.EventEmitter.emit (node:domain:470:12)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:285:12)
```

Rust Stacktrace:
```
   0: backtrace::backtrace::trace
   1: backtrace::capture::Backtrace::new
   2: user_facing_errors::Error::new_in_panic_hook
   3: user_facing_errors::panic_hook::set_panic_hook::{{closure}}
   4: std::panicking::rust_panic_with_hook
   5: std::panicking::begin_panic_handler::{{closure}}
   6: std::sys_common::backtrace::__rust_end_short_backtrace
   7: _rust_begin_unwind
   8: core::panicking::panic_fmt
   9: core::str::slice_error_fail
  10: datamodel::diagnostics::helper::pretty_print
  11: datamodel::diagnostics::error::DatamodelError::pretty_print
  12: datamodel::diagnostics::collection::Diagnostics::to_pretty_string
  13: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  14: <futures_util::compat::compat03as01::Compat<Fut> as futures::future::Future>::poll
  15: <futures::future::either::Either<A,B> as futures::future::Future>::poll
  16: <futures::future::then::Then<A,B,F> as futures::future::Future>::poll
  17: <futures::future::either::Either<A,B> as futures::future::Future>::poll
  18: futures::task_impl::Spawn<T>::enter::{{closure}}
  19: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  20: introspection_engine::main
  21: std::sys_common::backtrace::__rust_begin_short_backtrace
  22: std::rt::lang_start::{{closure}}
  23: std::rt::lang_start_internal
  24: std::rt::lang_start

```

**Comment by pantharshit00** [comment] 2021-05-04 15:56
Closing as duplicate of https://github.com/prisma/prisma/issues/5614

**Closed by pantharshit00** 2021-05-04 15:56 UTC
Labels: bug/1-repro-available, kind/bug, status/needs-action, team/migrations, topic: introspection
