### ISSUE TITLE
Random PrismaClientUnknownRequestError Occurring After Driver Update with Cloudflare Workers + MongoDB Atlas

### ISSUE THREAD

**Issue by xhulz** [prisma/prisma#25705] opened 2024-11-22 14:56 UTC
### Bug description

Starting November 12th, we began experiencing a random and recurring issue where 10-15% of our database queries fail with the following error:

```
PrismaClientUnknownRequestError: 
Invalid prisma.level.findFirst() invocation:

Operation 'findFirst' for model 'level' does not match any query.
```

Or:

```
PrismaClientUnknownRequestError: 
Invalid prisma.rewards.findMany() invocation:

Operation 'findMany' for model 'rewards' does not match any query.
```

And so on...

This issue happens intermittently and impacts various models across our collections. No changes were made to the system or database schemas, except for a driver update to the latest Prisma version shortly before the issue started.

We are using Cloudflare Workers with MongoDB Atlas, and the problem has persisted since the driver update.

### How to reproduce

Unfortunately, the issue is random and not easily reproducible. However, it consistently impacts approximately 10-15% of the calls made to our database.

### Expected behavior

All database queries should execute without throwing random PrismaClientUnknownRequestError exceptions.

### Prisma information

```prisma
generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "mongodb"
  url      = env("DATABASE_URL")
}

enum QuestStatusEnum {
  DRAFT
  ARCHIVED
  COMING_SOON
  LIVE
}

enum ProgressionTypeEnum {
  quest
  task
}

enum UserCreditTypeEnum {
  quest
  task
  referral
}

enum UserLootDropEntriesType {
  level
  category
}

type QuestsEarn {
  credits Int?
  xp      Int
}

type QuestsTasks {
  id     String
  name   String
  earn   QuestsTasksEarn
  status QuestStatusEnum
}

type QuestsTasksEarn {
  credits Int?
  xp      Int
}

type UsersCredits {
  total    Float?
  referral Float?
}

model campaigns {
  id          String   @id @default(auto()) @map("_id") @db.ObjectId
  key         String
  isActive    Boolean
  categoryIds String[]
}

model categories {
  id                  String                @id @default(auto()) @map("_id") @db.ObjectId
  key                 String
  name                String
  isActive            Boolean
  userLootDropEntries userLootDropEntries[]
}

model quests {
  id          String          @id @default(auto()) @map("_id") @db.ObjectId
  name        String
  categoryId  String
  earn        QuestsEarn
  status      QuestStatusEnum
  tasks       QuestsTasks[]
  progression progression[]
  level       level?          @relation(fields: [levelId], references: [id])
  levelId     String?         @db.ObjectId

  @@index([categoryId], map: "categoryId_1")
}

type rewardsIntegrationConstraints {
  maxUnitDistributionLimit Int?
}

model transactionHistory {
  id          String  @id @default(auto()) @map("_id") @db.ObjectId
  type        String
  userId      String
  taskId      String?
  questId     String?
  categoryId  String?
  campaignId  String?
  rewardId    String?
  lootDropId  String?
  value       Int
  description String
  createdAt   String

  @@index([userId], map: "userId_1")
}

model users {
  id                  String                @id @default(auto()) @map("_id") @db.ObjectId
  legacyUserId        String
  xp                  Int
  credits             UsersCredits?
  progression         progression[]
  userLootDropEntries userLootDropEntries[]

  @@index([xp], map: "xp_1")
}

model progression {
  id        String              @id @default(auto()) @map("_id") @db.ObjectId
  xp        Int
  userId    String              @db.ObjectId
  users     users               @relation(fields: [userId], references: [id])
  questId   String              @db.ObjectId
  quests    quests              @relation(fields: [questId], references: [id])
  taskId    String?
  type      ProgressionTypeEnum
  active    Boolean
  createdAt DateTime            @db.Date

  @@index([xp], map: "xp_1")
  @@index([userId], map: "userId_1")
  @@index([taskId], map: "taskId_1")
  @@index([questId], map: "questId_1")
  @@index([type], map: "type_1")
}

model userCredit {
  id             String             @id @default(auto()) @map("_id") @db.ObjectId
  userId         String
  referredUserId String?
  questId        String?
  taskId         String?
  amount         Float
  type           UserCreditTypeEnum
  active         Boolean
  createdAt      String

  @@index([userId], map: "userId_1")
  @@index([referredUserId], map: "referredUserId_1")
  @@index([type], map: "type_1")
}

model userReferral {
  id             String  @id @default(auto()) @map("_id") @db.ObjectId
  userId         String
  referrerUserId String
  active         Boolean
  createdAt      String
  acceptedAt     String

  @@index([userId], map: "userId_1")
  @@index([referrerUserId], map: "referrerUserId_1")
}

model level {
  id                  String                @id @default(auto()) @map("_id") @db.ObjectId
  name                String
  level               Int
  minimumXp           Int
  createdAt           DateTime              @db.Date
  updatedAt           DateTime              @db.Date
  quests              quests[]
  userLootDropEntries userLootDropEntries[]
}

model rewards {
  id                  String  @id @default(auto()) @map("_id") @db.ObjectId
  title               String
  campaignId          String?
  categoryId          String?
  questId             String?
  taskId              String?
  lootDropId          String?
  level               Int?
  rewardIntegrationId String
  units               Int
  active              Boolean
}

model rewardsIntegration {
  id               String                         @id @default(auto()) @map("_id") @db.ObjectId
  constraints      rewardsIntegrationConstraints?
  distributedCount Int
  active           Boolean
}

model rewardsRedeemed {
  id                  String   @id @default(auto()) @map("_id") @db.ObjectId
  rewardId            String
  rewardIntegrationId String
  userId              String
  campaignId          String?
  categoryId          String?
  questId             String?
  taskId              String?
  lootDropId          String?
  level               Int?
  units               Int
  redeemed            Boolean
  acquiredAt          String
  active              Boolean?
}

model lootDrops {
  id                    String                @id @default(auto()) @map("_id") @db.ObjectId
  name                  String
  startTime             String
  endTime               String
  categoriesIds         String[]
  multiplierPerLevel    Int
  multiplierPerCategory Int
  userLootDropEntries   userLootDropEntries[]
}

model userLootDrop {
  id          String @id @default(auto()) @map("_id") @db.ObjectId
  userId      String
  lootDropId  String
  consentedAt String
  multiplier  Int
}

model userLootDropEntries {
  id         String                  @id @default(auto()) @map("_id") @db.ObjectId
  users      users                   @relation(fields: [userId], references: [id])
  userId     String                  @db.ObjectId
  lootDrops  lootDrops               @relation(fields: [lootDropId], references: [id])
  lootDropId String                  @db.ObjectId
  level      level?                  @relation(fields: [levelId], references: [id])
  levelId    String?                 @db.ObjectId
  categories categories?             @relation(fields: [categoryId], references: [id])
  categoryId String?                 @db.ObjectId
  multiplier Int
  type       UserLootDropEntriesType
  active     Boolean
  acquiredAt DateTime                @db.Date
}
```

```ts
      /**
       * Set the Prisma client
       * @param params.connectionString The connection string / url string.
       * @returns The Prisma client.
       */
      const set = (params: { connectionString: string }) => {
        const { connectionString } = params;
      
        // Create the Prisma client
        return new PrismaClient({
          datasources: {
            db: {
              url: connectionString,
            },
          },
        }).$extends(withAccelerate());
      };

    // Check if there are rewards attached to the category
    const rewards = await repo.rewards.findMany({
      where: {
        campaignId: campaign.id,
        active: true,
      },
    });
    if (!rewards.length) return;
    
    // Get the user level based on the XP.
    const level = await repo.level.findFirst({
      select: {
        id: true,
        level: true,
      },
      where: {
        minimumXp: {
          lte: user.xp,
        },
      },
      orderBy: {
        level: 'desc',
      },
    });
    if (!level) throw new Error('User does not have a level');    
```

### Environment & setup

Prisma Version: 5.22.0
Node.js Version: >= v20.0.0
Deployment Environment: Cloudflare Workers
Database: MongoDB Atlas

### Prisma Version

```
10.8.2
```

**Comment by aqrln** [comment] 2024-11-26 15:21
Hey @xhulz, thanks for the report. I tried doing stress testing with your schema and queries, including in a resource-constrained environment with 0.1 vCPU to try to catch any race conditions, but I couldn't reproduce this issue.

Some follow-up questions:
* Did you run `prisma generate` after updating the Prisma ORM version?
* What was the previous Prisma version before you updated it?
* Does the 10–15% failure rate apply to all queries or these two queries specifically? Do these two queries ever succeed?
* Anything else we should know for the reproduction?

**Comment by xhulz** [comment] 2024-11-26 15:56
Hi @aqrln 

Thank you for looking into this issue and for running tests in resource-constrained environments. I appreciate your effort in trying to reproduce the problem. Let me provide more context and answers to your questions:

**Running prisma generate:** Yes, we run the prisma generate command both during the build process and in the postinstall step to ensure everything is set up correctly. Here's a snippet of our current package.json:

```
"scripts": {
  "start": "npm run prisma:generate && wrangler dev --env local",
  "prisma:generate": "npx prisma generate --no-engine",
  "postinstall": "npm run prisma:generate"
}
```

This setup ensures Prisma is generated correctly across all environments.

`Previous Prisma version: `Our previous Prisma version was 5.19.1. We downgraded to this version yesterday after encountering issues with the latest release. While this has reduced the error rate, we are still seeing the same generic error for 7–10% of requests.

`10–15% failure rate:` The 10–15% failure rate applies to all queries in this service, as well as two other services:

 - The service providing data for our site: https://app.game7.io/.
 - A service used for integrations with external games.

It’s worth noting that the majority of requests succeed, but some fail with the same generic error. This inconsistency makes it difficult to diagnose the root cause, especially as the error doesn’t provide specific details. We are unsure whether this is due to:
 - Timeout issues,
 - Cloudflare Workers,
 - Or MongoDB Atlas itself.

`Additional information:` If it helps, I can add you to the repository for our source code so you can verify that Prisma is being used correctly. It’s very puzzling since the same schema and queries work for most requests, yet we still face intermittent failures.

Thank you again for your support, and let me know if you’d like access to the repo or any other details to help with troubleshooting!

**Comment by aqrln** [comment] 2024-11-27 14:38
Thanks so much for the response @xhulz. We have been investigating this issue further and found the likely cause. We'll let you know ASAP once the fix is merged today.

**Comment by xhulz** [comment] 2024-11-28 10:24
Hi @aqrln!

Thank you for the update!

Last night, we monitored the entire system and didn’t encounter any more errors like the one we were experiencing.

We truly appreciate the fix and all the effort from you and the entire Prisma team. 🙂

**Closed** 2024-11-28 11:37 UTC
Labels: bug/1-unconfirmed, kind/bug, tech/engines, topic: mongodb, topic: pdp/accelerate
