### ISSUE TITLE
CPU Crashing even at 4 GB RAM, 2 vCPUs on mutation

### ISSUE THREAD

**Issue by Alosies** [prisma/prisma#4707] opened 2019-06-29 12:36 UTC
**Describe the bug**
I am doing a nested mutation, and after doing around 10 of them in a span 15 mins. The CPU consumption is shooting up and the Server is crashing. 

It happened when I had 2GB RAM, so I thought if I increase the RAM to 4GB, at least by brute force it should not crash. But it does. 

**To Reproduce**
Unfortunately, it is a private repo and hence I cannot share the complete code for reproduction. 

This happens when I do a nested update mutation.  

**Screenshots**
The error I get when I run `docker logs` is 
```
Uncaught error from thread [single-server-akka.actor.default-dispatcher-22]: GC overhead limit exceeded, shutting down JVM since 'akka.jvm-exit-on-fatal-error' is enabled for ActorSystem[single-server]
java.lang.OutOfMemoryError: GC overhead limit exceeded
	at scala.collection.generic.ImmutableSetFactory.newBuilder(ImmutableSetFactory.scala:20)
	at scala.collection.generic.GenericTraversableTemplate.genericBuilder(GenericTraversableTemplate.scala:70)
	at scala.collection.generic.GenericTraversableTemplate.genericBuilder$(GenericTraversableTemplate.scala:70)
	at scala.collection.AbstractTraversable.genericBuilder(Traversable.scala:104)
	at scala.collection.generic.GenSetFactory$$anon$1.apply(GenSetFactory.scala:44)
	at scala.collection.generic.GenSetFactory$$anon$1.apply(GenSetFactory.scala:41)
	at scala.collection.TraversableLike.collect(TraversableLike.scala:269)
	at scala.collection.TraversableLike.collect$(TraversableLike.scala:268)
	at scala.collection.AbstractTraversable.collect(Traversable.scala:104)
	at com.prisma.api.connector.SelectedFields.<init>(DataResolverTypes.scala:87)
	at com.prisma.api.schema.SangriaExtensions$ContextExtensions$.$anonfun$recurse$1(SangriaExtensions.scala:25)
	at com.prisma.api.schema.SangriaExtensions$ContextExtensions$$$Lambda$2015/757892978.apply(Unknown Source)
	at scala.collection.TraversableLike.$anonfun$flatMap$1(TraversableLike.scala:240)
	at scala.collection.TraversableLike$$Lambda$47/2045766957.apply(Unknown Source)
	at scala.collection.Iterator.foreach(Iterator.scala:937)
	at scala.collection.Iterator.foreach$(Iterator.scala:937)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1425)
	at scala.collection.IterableLike.foreach(IterableLike.scala:70)
	at scala.collection.IterableLike.foreach$(IterableLike.scala:69)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
	at scala.collection.TraversableLike.flatMap(TraversableLike.scala:240)
	at scala.collection.TraversableLike.flatMap$(TraversableLike.scala:237)
	at scala.collection.AbstractTraversable.flatMap(Traversable.scala:104)
	at com.prisma.api.schema.SangriaExtensions$ContextExtensions$.recurse$extension(SangriaExtensions.scala:21)
	at com.prisma.api.schema.SangriaExtensions$ContextExtensions$.getSelectedFields$extension(SangriaExtensions.scala:17)
	at com.prisma.api.schema.ObjectTypeBuilder.mapToOutputResolve(ObjectTypeBuilder.scala:261)
	at com.prisma.api.schema.ObjectTypeBuilder.$anonfun$mapClientField$1(ObjectTypeBuilder.scala:109)
	at com.prisma.api.schema.ObjectTypeBuilder$$Lambda$1540/151871512.apply(Unknown Source)
	at sangria.execution.Resolver.resolveField(Resolver.scala:1024)
	at sangria.execution.Resolver.$anonfun$collectActionsPar$1(Resolver.scala:445)
	at sangria.execution.Resolver$$Lambda$1980/1624504471.apply(Unknown Source)
	at scala.collection.TraversableOnce.$anonfun$foldLeft$1(TraversableOnce.scala:
```
Metrics on AWS Lightsail

<img width="620" alt="Screenshot 2019-06-29 at 6 03 37 PM" src="https://user-images.githubusercontent.com/24241029/60384178-4c75b600-9a98-11e9-938a-187220fd4ebd.png">

CPU at 199%

<img width="1361" alt="Screenshot 2019-06-29 at 6 05 34 PM" src="https://user-images.githubusercontent.com/24241029/60384191-8941ad00-9a98-11e9-89f9-26ed7dc99209.png">

**Versions (please complete the following information):**
 - Connector: `Postgres`
 - Prisma Server: `1.30.0`
 - `prisma` CLI: `prisma/1.30.4 (linux-x64) node-v10.16.0`
 - OS: `Ubuntu 16.04`

**Additional context**

**Comment by pantharshit00** [comment] 2019-07-01 12:42
Currently, JVM is a big overhead and the Garbage collector is not that efficient. That is why you are setting this big of a spike.

We have released Prisma 2 which is rewritten in Rust to avoid performance issues. But for this issue, I will suggest you increase the queue size. Or you can also batch your nested operations.

Closing this as a duplicate of #3504 as it basically the same issue.

Also, can you please tell me roughly how many nested levels you are trying to query.

**Closed by pantharshit00** 2019-07-01 12:42 UTC

**Comment by Alosies** [comment] 2019-07-01 13:20
It is a nested mutation that I am performing. It modifies things at around 3 levels. I want to know, does it help in managing the GC if I made multiple shallow mutations instead of one mutation that is deep?

**Comment by pantharshit00** [comment] 2019-07-01 15:56
Yes, it will surely help if you narrow down the mutation
