### ISSUE TITLE
Cannot run `generate` script if prisma was installed with yarn v3 Plug'n'Play

### ISSUE THREAD

**Issue by LOLBRUHNICE** [prisma/prisma#17084] opened 2023-01-01 09:34 UTC
### Bug description

If prisma was installed with yarn v3 Plug'n'Play and I run `yarn prisma generate`, it will return
```
Error: Could not resolve prisma and @prisma/client in the current project. Please install them with yarn add -D prisma and yarn add @prisma/client, and rerun yarn prisma generate 🙏.
```
But after I added `nodeLinker: node-modules` to the .yarnrc.yml and run again, it runs successfully

### How to reproduce

1. Initialize a yarn v3 project
2. Install prisma and configure your prisma
3. Run `yarn prisma generate`

### Expected behavior

Run successfully

### Prisma information

```prisma
// Add your schema.prisma

// Not related
```

```ts
// Add your code using Prisma Client

// Not related
```

### Environment & setup

- OS: Windows 11
- Database: Not related
- Node.js version: 18.12.1

### Prisma Version

```
prisma                  : 4.8.0
@prisma/client          : 4.8.0
Current platform        : windows
Query Engine (Node-API) : libquery-engine d6e67a83f971b175a593ccc12e15c4a757f93ffe (at node_modules\@prisma\engines\query_engine-windows.dll.node)
Migration Engine        : migration-engine-cli d6e67a83f971b175a593ccc12e15c4a757f93ffe (at node_modules\@prisma\engines\migration-engine-windows.exe)
Introspection Engine    : introspection-core d6e67a83f971b175a593ccc12e15c4a757f93ffe (at node_modules\@prisma\engines\introspection-engine-windows.exe)
Format Binary           : prisma-fmt d6e67a83f971b175a593ccc12e15c4a757f93ffe (at node_modules\@prisma\engines\prisma-fmt-windows.exe)
Format Wasm             : @prisma/prisma-fmt-wasm 4.8.0-61.d6e67a83f971b175a593ccc12e15c4a757f93ffe
Default Engines Hash    : d6e67a83f971b175a593ccc12e15c4a757f93ffe
Studio                  : 0.479.0
```

**Comment by Jolg42** [comment] 2023-01-02 15:20
This looks like a duplicate of https://github.com/prisma/prisma/issues/1439

You could try this https://github.com/prisma/prisma/issues/1439#issuecomment-1023884266 maybe

**Comment by vleandersson** [comment] 2023-07-09 21:45
I think we can close this one as a duplicate

**Closed** 2023-07-10 08:21 UTC
Labels: bug/1-unconfirmed, kind/bug, tech/typescript, team/client, topic: yarn berry(v2)
