### ISSUE TITLE
WebSocket server error: Port is already in use

### ISSUE THREAD

**Issue by dionsaur84** [prisma/prisma#17082] opened 2023-01-01 00:17 UTC
### Bug description

When running my server, and simultaneously trying to seed it in another terminal tab, I am getting this error:

> WebSocket server error: Port is already in use

Here is my `db` file:

```js
import { PrismaClient } from '@prisma/client'

const db = new PrismaClient()

export default db
```

The server uses this, as does my seed file:

```js
import { faker } from '@faker-js/faker'
import { db } from 'anarchy'

await db.user.deleteMany()

for (let i = 1; i <= 10; i++) {
    await db.user.create({
        data: {
            name: faker.name.fullName(),
            email: faker.helpers.unique(faker.internet.email),
        }
    })
}
```

I read there was a workaround for this, but has since been removed:

```js
const prisma = new PrismaClient({
  __internal: {
    useUds: true
  }
});
```

However this doesn't work in the latest version of Prisma.

### Prisma information

```prisma
// Add your schema.prisma
```

```ts
// Add your code using Prisma Client
```

### Environment & setup

- OS: 
- Database: 
- Node.js version: 

### Prisma Version

```

```

**Comment by annibuliful** [comment] 2023-01-01 11:30
I think this is not related to Prisma I think because opened ports your node server I guess. Could you create a reproducible repo?

**Comment by jkomyno** [comment] 2023-01-01 21:09
Hi @dionsaur84, happy new year. I agree with @annibuliful, this issue is not relevant to Prisma.
Besides, we're missing any relevant info that may help allow us to help you figuring out the issue: your OS, what port your server is running on, what your database is and which port that's using. I'm closing this issue for now.

**Closed by jkomyno** 2023-01-01 21:09 UTC
Labels: kind/bug
