### ISSUE TITLE
internal error: entered unreachable code

### ISSUE THREAD

**Issue by gmiserani** [prisma/prisma#24666] opened 2024-06-28 18:56 UTC
### Bug description

it just stopped working after a feel tries

### Prisma information

```prisma
// Add your schema.prisma
```

```ts
// Add your code using Prisma Client
```

### Environment & setup

- OS: 
- Database: 
- Node.js version: 

### Prisma Version

```

```

**Comment by SevInf** [comment] 2024-07-19 14:39
Hi @gmiserani.
It looks like you ignored our issue template. Without the information we request in there, there is no way for us to reproduce and diagnose your issue so we have to close it. Please, open a new one and fill out issue teamplete.

**Closed by SevInf** 2024-07-19 14:39 UTC
Labels: bug/0-unknown, kind/bug, tech/engines, domain/client
