### ISSUE TITLE
Error when pulling from database

### ISSUE THREAD

**Issue by renanlido** [prisma/prisma#19971] opened 2023-06-26 20:07 UTC
Hi Prisma Team! The following command just crashed.

## Command

`db pull --schema [redacted]`

## Versions
      
| Name        | Version            |
|-------------|--------------------|
| Platform    | debian-openssl-3.0.x| 
| Node        | v18.12.1           | 
| Prisma CLI  | 4.16.1             | 
| Engine      | b20ead4d3ab9e78ac112966e242ded703f4a052c| 

## Error
```
RustPanic: Error in migration engine.
Reason: [schema-engine/sql-schema-describer/src/mssql.rs:348:30] called `Result::unwrap()` on an `Err` value: "Couldn't parse default value: `create default def_zero as 0\r\n`"

```

**Comment by janpio** [comment] 2024-05-23 17:36
We still do not know how to make Introspection crash because of the existence of such an index. 
We need a SQL dump of a database that reproduces this behavior to replicate this behavior. Can you help @renanlido?

(For us the default is just ignored and not represented in the Prisma schema: https://github.com/prisma/prisma/issues/12150)

**Comment by janpio** [comment] 2024-05-23 19:17
I actually figured out one way to reproduce this: https://github.com/prisma/prisma/issues/24275
In my case a comment make the default string multi-line, but yours also shows `\r\n`, so I think this is the same root cause @renanlido.

**Comment by janpio** [comment] 2024-05-31 23:23
Closed by https://github.com/prisma/prisma-engines/pull/4884

**Closed by janpio** 2024-05-31 23:23 UTC
Labels: bug/2-confirmed, kind/bug, topic: introspection, topic: sql server, team/schema, topic: prisma db pull, topic: default, topic: unwrap error, topic: CREATE DEFAULT ... AS ...
