### ISSUE TITLE
Typescript errors with Prisma Atomic operations on update

### ISSUE THREAD

**Issue by jose-donato** [prisma/prisma#3655] opened 2020-09-15 02:20 UTC
## Bug description

Current prisma version throws typescript errors with Prisma Atomic operations on update (increment, decrement, etc. - more info in [prisma docs](https://www.prisma.io/docs/reference/tools-and-interfaces/prisma-client/crud#atomic-operations-on-update)). 

## How to reproduce

![image](https://user-images.githubusercontent.com/43375532/93030106-758c5300-f618-11ea-8fc6-718661c51d21.png)

**Temporary fix:**
adding `//@ts-ignore` in the previous line ignores the typescript error and everything works as expected (upvotes field is incremented by one)

![image](https://user-images.githubusercontent.com/43375532/93030120-905ec780-f618-11ea-9e0b-fde2cab40d81.png)

## Expected behavior

Auto completion for atomic operations and no typescript errors

## Prisma information

```
datasource db {
  provider = ["sqlite", "postgres"]
  url      = env("DATABASE_URL")
}

generator client {
  provider = "prisma-client-js"
  previewFeatures = ["atomicNumberOperations"]
}

model Comment {
  id                 Int       @default(autoincrement()) @id
  createdAt DateTime @default(now())
  updatedAt DateTime @updatedAt
  url                String?
  content            String
  upvotes            Int      @default(0)
  parentId           Int?
}
```

## Environment & setup

- OS: `Linux version 5.7.0-kali3-amd64 (devel@kali.org) (gcc version 9.3.0 (Debian 9.3.0-15), GNU ld (GNU Binutils for Debian) 2.35) #1 SMP Debian 5.7.17-1kali1 (2020-08-26)`
- Database: SQLite
- Node.js version: 12.17.0
- Prisma version:
```
@prisma/cli          : 2.6.2
Current platform     : debian-openssl-1.1.x
Query Engine         : query-engine 6a8054bb549e4cc23f157b0010cb2e95cb2637fb (at node_modules/@prisma/cli/query-engine-debian-openssl-1.1.x)
Migration Engine     : migration-engine-cli 6a8054bb549e4cc23f157b0010cb2e95cb2637fb (at node_modules/@prisma/cli/migration-engine-debian-openssl-1.1.x)
Introspection Engine : introspection-core 6a8054bb549e4cc23f157b0010cb2e95cb2637fb (at node_modules/@prisma/cli/introspection-engine-debian-openssl-1.1.x)
Format Binary        : prisma-fmt 6a8054bb549e4cc23f157b0010cb2e95cb2637fb (at node_modules/@prisma/cli/prisma-fmt-debian-openssl-1.1.x)
Studio               : 0.272.0
```

**Comment by pantharshit00** [comment] 2020-09-15 12:38
I am unable to reproduce this:
![image](https://user-images.githubusercontent.com/22195362/93211077-590a2b00-f77e-11ea-96a6-f5ce3520300b.png)


Please share the code of the function updateComment. I think you wrapping a Prisma method inside of that.

**Comment by jose-donato** [comment] 2020-09-15 15:02
i'm using blitz.js.

![image](https://user-images.githubusercontent.com/43375532/93227912-d0cf5a00-f76c-11ea-9b19-a1cbbbab6c34.png)

this is odd. when i launched the project right now i did not get any typescript error. i guess it is solved somehow ahah

**Comment by pantharshit00** [comment] 2020-09-15 21:24
Looks like you didn't ran Prisma generate somehow or your editor didn't load the typings.

Trying installing the Prisma vscode extension as it will refresh the typing if you generate the typings.

Anyways, I am going to close this. Please comment here if you are still facing this.

**Closed by pantharshit00** 2020-09-15 21:24 UTC
Labels: bug/0-needs-info, kind/bug, topic: atomicOperations, topic: previewFeatures

**Comment by jose-donato** [comment] 2020-09-15 21:42
Oh, maybe it was exactly that! I think i installed the extension in the mean time! thanks for the help @pantharshit00
