### ISSUE TITLE
Rust crate

### ISSUE THREAD

**Issue by Milo123459** [prisma/prisma#11341] opened 2022-01-23 19:02 UTC
## Problem

Currently, in Rust, there isn't a good tool like Prisma that does everything for you (db wise).

## Suggested solution

It would be nice if Prisma was supported for Rust and had some sort of crate that could be used to interact with prisma.

## Alternatives

Using SQLx, it's a crate that allows you to make SQL queries but is very low-level.

**Comment by pantharshit00** [comment] 2022-01-24 13:40
Hi,

Thanks for reporting this! It has already been reported before, so I am going to close this as a duplicate of https://github.com/prisma/prisma/issues/5790

You can checkout Quaint(our SQL abstraction for Rust) in meantime: https://github.com/prisma/quaint

**Closed by pantharshit00** 2022-01-24 13:40 UTC
