### ISSUE TITLE
Null relationship issue in many to many 

### ISSUE THREAD

**Issue by aakashkag** [prisma/prisma#2552] opened 2020-05-25 17:08 UTC
OS: Ubuntu 19.10
Database: Postgres,
Prisma version: @prisma/cli: 2.0.0-beta.5
Node.js version: v12.14.0

Hi
I am trying to create relationhip between 4 tables.
In short trying to assign role to user in (Organization or Sub_Organization)
1) Organization
2) Sub_Organization
3) User
4) Role
5) Assigned_Role (to mainain relationship)

```
model Organization {
  organization_id          Int                @default(autoincrement()) @id
  organization_name        String             @unique
  Assigned_Role            Assigned_Role[]
}
```

```
model SUb_Organization {
 sub_ organization_id          Int                @default(autoincrement()) @id
 sub_organization_name        String             @unique
  Assigned_Role            Assigned_Role[]
}
```
```
model User {
  user_id                            Int              @default(autoincrement()) @id
  user_name        String             @unique
  Assigned_Role            Assigned_Role[]
}
```

```
model Role {
  role_id                            Int              @default(autoincrement()) @id
  role_name        String             @unique
  Assigned_Role            Assigned_Role[]
}
```
```
model Assigned_Role {
  assigned_role_id    Int               @default(autoincrement()) @id
  organization_id     Int               @default(autoincrement())
  sub_organization_id Int               @default(autoincrement())
  role_id             Int               @default(autoincrement())
  user_id             Int               @default(autoincrement())
  Organization        Organization?     @relation(fields: [organization_id], references: 
[organization_id])
  Sub_Organization    Sub_Organization? @relation(fields: [sub_organization_id], references: 
  Role                Role              @relation(fields: [role_id], references: [role_id])
[sub_organization_id])
  User                User              @relation(fields: [user_id], references: [user_id])
}
```

Now I am trying to assign new role to user only in Organization using :
        ```
```
return ctx.prisma.assigned_Role.create({
            data: {
                Organization: {
                    connect: {
                        organization_id: args.organization_id,
                    },
                },
                Sub_Organization: {
                    connect: {
                        sub_organization_id: null,
                    },
                },
                User: {
                    connect: {
                        user_id: args.user_id,
                    },
                },
                Role: {
                    connect: {
                        role_id: args.role_id,
                    },
                },
            },
        });
```
``
In Assigned_Role table I droped Not Null constraints on field organization_id, sub_organization_id
but still I am  getting below issue.
When trying to generate client using  " npx prisma generate" i am getting issue
![https://user-images.githubusercontent.com/10579939/82832352-b833ef00-9eb2-11ea-90c7-d6a59f6145cf.png](https://user-images.githubusercontent.com/10579939/82832352-b833ef00-9eb2-11ea-90c7-d6a59f6145cf.png)

Here is repo I created to debug: 
https://github.com/aakashkag/prisma2_examples

**Comment by aakashkag** [comment] 2020-05-25 17:10
Here is repo I created to debug: 
https://github.com/aakashkag/prisma2_examples

**Comment by ryands17** [comment] 2020-05-26 07:52
Hey @aakashkag :wave: 
The error you have shown contains a model named *Group*. Could you share that model as well so I can reproduce it from my end?

**Comment by aakashkag** [comment] 2020-05-26 08:22
> Hey @aakashkag 
> The error you have shown contains a model named _Group_. Could you share that model as well so I can reproduce it from my end?

```
model Group {
  group_id          Int                @default(autoincrement()) @id
  group_name        String             @unique
  Assigned_Role            Assigned_Role[]
}
model Sub_Group {
 sub_group_id          Int                @default(autoincrement()) @id
 sub_group_name        String             @unique
  Assigned_Role            Assigned_Role[]
}
```

**Comment by ryands17** [comment] 2020-05-26 09:53
Here is the schema that is working with `prisma generate`

```prisma
model Assigned_Role {
  assigned_role_id      Int              @default(autoincrement()) @id
  organization_id       Int              @default(autoincrement())
  role_id               Int              @default(autoincrement())
  sub_organization_id   Int              @default(autoincrement())
  user_id               Int
  Organization          Organization     @relation(fields: [organization_id], references: [organization_id])
  Role                  Role             @relation(fields: [role_id], references: [role_id])
  Sub_Organization      Sub_Organization @relation(fields: [sub_organization_id], references: [sub_organization_id])
  User                  User             @relation(fields: [user_id], references: [user_id])
  Group                 Group?           @relation(fields: [groupGroup_id], references: [group_id])
  groupGroup_id         Int?
  Sub_Group             Sub_Group?       @relation(fields: [sub_GroupSub_group_id], references: [sub_group_id])
  sub_GroupSub_group_id Int?
}

model Organization {
  organization_created_at  DateTime           @default(now())
  organization_description String
  organization_id          Int                @default(autoincrement()) @id
  organization_logo        String
  organization_name        String             @unique
  organization_size        Int?
  organization_type        String             @default("private")
  organization_updated_at  DateTime           @updatedAt
  organization_website     String
  Assigned_Role            Assigned_Role[]
  Sub_Organization         Sub_Organization[]
}

model Role {
  role_id       Int             @default(autoincrement()) @id
  role_name     String
  Assigned_Role Assigned_Role[]
}

model Sub_Organization {
  organization_id              Int             @default(autoincrement())
  sub_organization_created_at  DateTime        @default(now())
  sub_organization_description String
  sub_organization_id          Int             @default(autoincrement()) @id
  sub_organization_logo        String
  sub_organization_name        String
  sub_organization_size        Int?
  sub_organization_type        String
  sub_organization_updated_at  DateTime        @updatedAt
  sub_organization_website     String
  Organization                 Organization    @relation(fields: [organization_id], references: [organization_id])
  Assigned_Role                Assigned_Role[]
}

model User {
  user_active_status   Boolean         @default(false)
  user_avatar          String?
  user_biography       String?
  user_birthday        DateTime
  user_email           String
  user_email_verified  Boolean         @default(false)
  user_first_name      String
  user_gender          String?
  user_id              Int             @default(autoincrement()) @id
  user_last_name       String
  user_mobile          Int
  user_mobile_verified Boolean         @default(false)
  user_name            String
  user_password        String          @default("false")
  user_time_zone       DateTime?
  Assigned_Role        Assigned_Role[]
}

model Group {
  group_id      Int             @default(autoincrement()) @id
  group_name    String          @unique
  Assigned_Role Assigned_Role[]
}

model Sub_Group {
  sub_group_id   Int             @default(autoincrement()) @id
  sub_group_name String          @unique
  Assigned_Role  Assigned_Role[]
}
```

Also your query is incorrect, as `Sub_Organization` connect cannot have null as a paremeter. It requires a valid `id` to be passed to it. If you do not want to pass anything, you can skip the entire block like this:

```ts
return ctx.prisma.assigned_Role.create({
            data: {
                Organization: {
                    connect: {
                        organization_id: args.organization_id,
                    },
                },
                User: {
                    connect: {
                        user_id: args.user_id,
                    },
                },
                Role: {
                    connect: {
                        role_id: args.role_id,
                    },
                },
            },
        });
```

**Comment by aakashkag** [comment] 2020-05-26 10:09
Thank you :)  I am checking. 
Btw I defined "Assigned_Role" explicitly in database then I am trying to introspect and generate client.

**Comment by aakashkag** [comment] 2020-05-27 16:11
@pantharshit00 
Looks like it's bug:
becuase (organization_id, sub_organization_id, group, sub_group) is null in postgress table but
![image](https://user-images.githubusercontent.com/10579939/83045000-e3e2e080-a03c-11ea-969e-5b1ae33dcaa6.png)
but schema.prisma shows 

```
 model Assigned_Role {
  assigned_role_id    Int               @default(autoincrement()) @id
  group_id            Int               @default(autoincrement())
  organization_id     Int               @default(autoincrement())
  role_id             Int               @default(autoincrement())
  sub_group_id        Int               @default(autoincrement())
  sub_organization_id Int               @default(autoincrement())
  user_id             Int               @default(autoincrement())
  Group               Group?            @relation(fields: [group_id], references: [group_id])
  Organization        Organization?     @relation(fields: [organization_id], references: [organization_id])
  Role                Role              @relation(fields: [role_id], references: [role_id])
  Sub_Group           Sub_Group?        @relation(fields: [sub_group_id], references: [sub_group_id])
  Sub_Organization    Sub_Organization? @relation(fields: [sub_organization_id], references: [sub_organization_id])
  User                User              @relation(fields: [user_id], references: [user_id])
}
```
only relation showing optional("?") not fields.

**Comment by pantharshit00** [comment] 2020-05-27 21:06
@aakashkag Can you please share sql dump of that table or possible the whole database so that I can try this out locally? Thanks!

**Comment by aakashkag** [comment] 2020-05-27 21:30
@pantharshit00 
Here is my database. Currently it's empty, [https://github.com/aakashkag/prisma2_examples/blob/master/prisma/prismaexample_db.sql](https://github.com/aakashkag/prisma2_examples/blob/master/prisma/prismaexample_db.sql)
I can reproduce issue using same code repostory and with empthy database.[https://github.com/aakashkag/prisma2_examples](https://github.com/aakashkag/prisma2_examples)

**Comment by aakashkag** [comment] 2020-05-27 21:43
Here is screen recording: [https://www.loom.com/share/c894cc4bb05543b580348092c61c389a](https://www.loom.com/share/c894cc4bb05543b580348092c61c389a)

**Comment by pantharshit00** [comment] 2020-05-29 08:42
Thanks for the dump. Now I can identify the issue. This is actually a duplicate of https://github.com/prisma/prisma/issues/1368. Please subscribe to that issue. Thanks!

**Closed by pantharshit00** 2020-05-29 08:42 UTC
Labels: bug/0-needs-info, kind/bug
