### ISSUE TITLE
Filtering on both a composite key and an individual element of that key generates incorrect SQL when queries are batched

### ISSUE THREAD

**Issue by VictoriaHunsaker** [prisma/prisma#22202] opened 2023-12-01 20:16 UTC
### Bug description

My organization is using Prisma with PostgreSQL alongside Graphql and Pothos. Some of our tables are tenant-scoped partitioned tables, and some are non-partitioned. Many of our tables use a composite key like `@@id([tenantId, id])`. In order to ensure tenant A's data is not shown to tenant B, we wrote a custom middleware that adds `tenantId: 'xyz'` to most of our queries.

Prisma is generating SQL as expected for these composite keys, but in the event we execute a set of `findUnique` queries at the same time, Prisma is batching these queries and generating incorrect SQL like below:

**Prisma client requests**
```ts
 await Promise.all([
    prisma.example.findUnique({
      where: {
        tenantId_id: {
          id: exampleIds[0],
          tenantId,
        },
        tenantId,
      }
    }),
    prisma.example.findUnique({
      where: {
        tenantId_id: {
          id: exampleIds[1],
          tenantId,
        },
        tenantId,
      }
    }),
    prisma.example.findUnique({
      where: {
        tenantId_id: {
          id: exampleIds[2],
          tenantId,
        },
        tenantId,
      }
    }),
  ]);
```

**Resulting generated query**
```sql
SELECT
	"public"."Example"."tenantId",
	"public"."Example"."id",
	"public"."Example"."exampleRelationId",
	"public"."Example"."field",
	"public"."Example"."otherField"
FROM
	"public"."Example"
WHERE (("public"."Example"."id" = $1 AND "public"."Example"."tenantId" = $2)
	OR ("public"."Example"."tenantId" = $3 AND "public"."Example"."id" = $4)
	OR "public"."Example"."tenantId" = $5 -- INCORRECT
	OR ("public"."Example"."tenantId" = $6 AND "public"."Example"."id" = $7)
	OR "public"."Example"."tenantId" = $8 -- INCORRECT
	OR "public"."Example"."tenantId" = $9 -- INCORRECT
) OFFSET $10
```

I cannot overemphasize how problematic this is for us because our real-life table is large, and if an `OR tenantId = X` is attached to the WHERE clause above, it is pulling all of the tenant's data for that table into memory and crashing the service due to an OutOfMemory exception. To mitigate this in the short-term, we are modifying our middleware to avoid adding the `tenantId` if already present in a composite key filter, but we are **extremely** alarmed by how this bug may manifest in the future.

### How to reproduce

I have put together a minimal reproduction at [this repository](https://github.com/VictoriaHunsaker/composite-key-bug) that you can clone and run via `docker-compose` to observe the behavior described above.

However, the exact steps to reproduce appear to be straightforward:
1. Have model with a composite key
2. Execute multiple simultaneous `findUnique`s against that model with filters on **both** the composite key and an individual element of the key (e.g. filters on both `tenantId_id and id` or `tenantId_id and tenantId`)

### Expected behavior

The generated SQL should not include `OR`s chained to the root of the `WHERE`, eg 

```sql
SELECT
	"public"."Example"."tenantId",
	"public"."Example"."id",
	"public"."Example"."exampleRelationId",
	"public"."Example"."field",
	"public"."Example"."otherField"
FROM
	"public"."Example"
WHERE (("public"."Example"."id" = $1 AND "public"."Example"."tenantId" = $2)
	OR ("public"."Example"."id" = $4 AND "public"."Example"."tenantId" = $5)
	) OFFSET $7
```

### Prisma information

```prisma
generator client {
  provider      = "prisma-client-js"
  binaryTargets = ["linux-musl-arm64-openssl-3.0.x"]
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

model ExampleRelation {
  id        String    @id @default(dbgenerated("gen_random_uuid()")) @db.Uuid
  tenantId  String    @db.Uuid
  isExample Boolean   @default(false)
  example   Example[]
}

model Example {
  id                String          @default(dbgenerated("gen_random_uuid()")) @db.Uuid
  tenantId          String          @db.Uuid
  exampleRelationId String          @db.Uuid
  exampleRelation   ExampleRelation @relation(fields: [exampleRelationId], references: [id])
  field             String?
  otherField        String?

  @@unique([tenantId, id])
}

```

```ts
  const prisma = new PrismaClient({ log: ['query'] });
  
  // Running these as a batch adds an extraneous "OR tenantId = ..." to the query
  console.log("-----------------------------------");
  console.log("Invalid query construction");
  console.log("-----------------------------------");
  await Promise.all([
    prisma.example.findUnique({
      where: {
        tenantId_id: {
          id: exampleIds[0],
          tenantId,
        },
        tenantId,
      }
    }),
    prisma.example.findUnique({
      where: {
        tenantId_id: {
          id: exampleIds[1],
          tenantId,
        },
        tenantId,
      }
    }),
    prisma.example.findUnique({
      where: {
        tenantId_id: {
          id: exampleIds[2],
          tenantId,
        },
        tenantId,
      }
    }),
  ]);
    
  console.log("-----------------------------------");
  console.log("Valid query construction");
  console.log("-----------------------------------");
  await Promise.all([
    prisma.example.findUnique({
      where: {
        tenantId_id: {
          id: exampleIds[2],
          tenantId,
        },
        exampleRelationId: exampleRelationIds[0],
      }
    }),
    prisma.example.findUnique({
      where: {
        tenantId_id: {
          id: exampleIds[3],
          tenantId,
        },
        exampleRelationId: exampleRelationIds[1],
      }
    }),
  ]);
```

### Environment & setup

- OS: MacOS w/o Docker, or Docker with `node:20.10-alpine3.17` image
- Database: PostgreSQL
- Node.js version: 20.10.1 or 20.9.0

### Prisma Version

```
 prisma                  : 5.6.0
 @prisma/client          : 5.6.0
 Computed binaryTarget   : linux-musl-arm64-openssl-3.0.x
 Operating System        : linux
 Architecture            : arm64
 Node.js                 : v20.10.0
 Query Engine (Node-API) : libquery-engine e95e739751f42d8ca026f6b910f5a2dc5adeaeee (at node_modules/@prisma/engines/libquery_engine-linux-musl-arm64-openssl-3.0.x.so.node)
 Schema Engine           : schema-engine-cli e95e739751f42d8ca026f6b910f5a2dc5adeaeee (at node_modules/@prisma/engines/schema-engine-linux-musl-arm64-openssl-3.0.x)
 Schema Wasm             : @prisma/prisma-schema-wasm 5.6.0-32.e95e739751f42d8ca026f6b910f5a2dc5adeaeee
 Default Engines Hash    : e95e739751f42d8ca026f6b910f5a2dc5adeaeee
 Studio                  : 0.495.0
```

**Comment by benweissmann** [comment] 2024-01-22 13:47
@aqrln Any updates here? Curious if there's a timeline for a fix, or anything else we can do to help move this along -- this bug is still marked as unconfirmed even though @VictoriaHunsaker has provided a full reproduction example.

To reiterate the impact -- we were using a totally-valid query; that query returned correct results *in development* when the tables weren't that big, and then this ended up causing a production outage because under the hood, that query was actually loading almost the *entire table* into memory, immediately crashing the application server.

**Comment by aqrln** [comment] 2024-01-31 13:24
Really sorry for the delay and for this issue falling through the cracks @VictoriaHunsaker and @benweissmann, we will reproduce and look into it ASAP, please expect an update by the end of this week. This sounds like a problematic bug indeed to me. And thanks @VictoriaHunsaker for the detailed reproduction!

**Comment by aqrln** [comment] 2024-02-02 14:08
I can reproduce it, both on 5.6.0 and with latest 5.9.1 (thanks again for the stellar reproduction!)

The `findUnique` queries which have an additional filter which is not a part of the composite key are not batched and are issued as separate queries to the database but the filters are correct in the generated SQL.

The `findUnique` queries which have a filter that is also a part of the composite key are batched, and the generated SQL query is incorrect.

The `WHERE` clause looks like this:

```
 WHERE
   (
     (
       "public"."Example"."id" = $1
       AND "public"."Example"."tenantId" = $2
     )
     OR (
       "public"."Example"."tenantId" = $3
       AND "public"."Example"."id" = $4
     )
     OR "public"."Example"."tenantId" = $5
     OR (
       "public"."Example"."tenantId" = $6
       AND "public"."Example"."id" = $7
     )
     OR "public"."Example"."tenantId" = $8
     OR "public"."Example"."tenantId" = $9
   )
```

but it must be this instead:

```
 WHERE
   (
     (
       "public"."Example"."id" = $1
       AND "public"."Example"."tenantId" = $2
       AND "public"."Example"."tenantId" = $3
     )
     OR (
       "public"."Example"."id" = $4
       AND "public"."Example"."tenantId" = $5
       AND "public"."Example"."tenantId" = $6
     )
     OR (
       "public"."Example"."id" = $7
       AND "public"."Example"."tenantId" = $8
       AND "public"."Example"."tenantId" = $9
     )
   )
```

As far as I can see, it still returns correct results to the client, even if I pass different `tenantId` values as a separate filter and as a part of the composite key filter (i.e., that query correctly evaluates to `null`), so Prisma evaluates the filters correctly when dealing with the result of the batched query, but the SQL query itself indeed overfetches a potentially large amount of data from the database.

**Comment by benweissmann** [comment] 2024-02-13 13:45
@aqrln Any updates on this? I agree with everything in your write-up, that's the behavior we're seeing as well. I'm a little worried about this being classified as a "performance" bug -- again, for any non-trivially-sized table, this immediately crashes the Rust process and causes an outage.

**Comment by Druue** [comment] 2024-03-27 23:07
Hey @VictoriaHunsaker @benweissmann,
There is a fix in the works for another issue https://github.com/prisma/prisma/issues/23343 that to me seems to be the same as the problem being highlighted here.

You can track progress [here](https://github.com/prisma/prisma-engines/pull/4789) :)

**Comment by apolanc** [comment] 2024-04-02 19:44
Hi @VictoriaHunsaker, @benweissmann 👋🏼

As mentioned by @Druue, the fix has been implemented [here](https://github.com/prisma/prisma-engines/pull/4789). Could you please confirm if this issue is solved for you? 🙏🏼

I'll keep this issue open for another week and close it if we get no confirmation, thank you!

**Comment by Druue** [comment] 2024-04-09 14:09
Hey, I took a look at this. This is what is now generated, using your repro, so I can confirm that this has been fixed :)
```sql
SELECT
    "public"."Example"."tenantId",
    "public"."Example"."id",
    "public"."Example"."exampleRelationId",
    "public"."Example"."field",
    "public"."Example"."otherField"
FROM
    "public"."Example"
WHERE
    (
        (
            "public"."Example"."id" = $ 1
            AND "public"."Example"."tenantId" = $ 2
            AND "public"."Example"."tenantId" = $ 3
        )
        OR (
            "public"."Example"."id" = $ 4
            AND "public"."Example"."tenantId" = $ 5
            AND "public"."Example"."tenantId" = $ 6
        )
        OR (
            "public"."Example"."id" = $ 7
            AND "public"."Example"."tenantId" = $ 8
            AND "public"."Example"."tenantId" = $ 9
        )
    ) OFFSET $ 10
```

**Closed by Druue** 2024-04-09 14:09 UTC
Labels: bug/2-confirmed, kind/bug, topic: performance, topic: broken query, team/client, topic: postgresql, topic: performance/memory, topic: composite ids, topic: findUnique(), topic: batching
