### ISSUE TITLE
Add SQL views support

### ISSUE THREAD

**Issue by 3NdR1m** [prisma/prisma#2631] opened 2020-06-01 23:15 UTC
Our MySQL database have several views we'd like to access with Prisma.

Since SQL views can be described as "read-only" tables, why not adding read-only models (i.e. Without update/insert/delete methods)?

For now, we only need tables and views, but since I'm at it I'd also suggest to implement the ability to interact with other Database object like stored procedures, events, etc :)

**Comment by Sytten** [comment] 2020-06-01 23:26
Duplicates of https://github.com/prisma/prisma/issues/678

**Comment by pantharshit00** [comment] 2020-06-02 08:09
Hi,

Thanks for reporting this! It has already been reported before, so I am going to close this as a duplicate of #678 


Thanks @Sytten for pointing out!

**Closed by pantharshit00** 2020-06-02 08:09 UTC
