### ISSUE TITLE
Wrong orderBy enum behaviour in combination with cursor

### ISSUE THREAD

**Issue by cimchd** [prisma/prisma#3072] opened 2020-07-18 09:38 UTC
## Bug description

I detected a strange behaviour in Prisma when I try to sort the results by an enum field and use a cursor to get a limited amount of the results. Normally the cursor element is the first element of the result, but here it was always the last element. 

When i use orderBy on a normal scalar field (int or string), it works fine.

## How to reproduce

Use a schema like this:

```prisma
enum DocumentType {
  order
  offer
}

model Document {
  id      String          @default(cuid()) @id
  type    DocumentType?
```

To reproduce the error use data where each entry has the same enum value from DocumentType.

Run Prisma findMany:
```js 
prisma.document.findMany({
  orderBy: {type: 'desc'}, 
  cursor: {id: '[...someID]'}, 
  take: 4 
});
```

## Expected behavior

The result with the id of the cursor should be the first element in the result. This is important for cursor based pagination to not always reload the same datasets.

## Prisma information

Prisma version 2.1.3, used together with nexus

## Environment & setup

- OS: Debian
- Database: PostgreSQL
- Prisma version: 2.1.3
- Node.js version: 14.4.0

**Comment by divyenduz** [comment] 2020-07-27 14:11
@cimchd Thanks for raising this, I am unable to reproduce this with `2.3.0`. Closing this issue. If the problem persists for you, please comment here.

**Closed by divyenduz** 2020-07-27 14:11 UTC
Labels: kind/improvement, team/product

**Comment by cimchd** [comment] 2020-08-01 06:38
> @cimchd Thanks for raising this, I am unable to reproduce this with `2.3.0`. Closing this issue. If the problem persists for you, please comment here.

Just checked it in 2.3.0 and the error seems to be gone. Thx 👍
