### ISSUE TITLE
prisma2 generate : "Schema parsing ,thread main overflow its stack"

### ISSUE THREAD

**Issue by Yawaiaung001** [prisma/prisma#3048] opened 2020-07-17 04:17 UTC
I have an existing big size postgresql database.When i introspected and generate, I faced this problem,
When introspect,

---

*** WARNING ***
These fields were commented out because we currently do not support their types.
- Model "base_import_import", field: "file", original data type: "binary"
- Model "base_language_export", field: "data", original data type: "binary"
- Model "base_language_import", field: "data", original data type: "binary"
- Model "ir_act_client", field: "params_store", original data type: "binary"
- Model "ir_attachment", field: "db_datas", original data type: "binary"
- Model "ir_property", field: "value_binary", original data type: "binary"
- Model "res_company", field: "logo_web", original data type: "binary"
- Model "web_editor_converter_test", field: "binary", original data type: "binary"

---

I replaced binary type as String.
After generate,

---
Environment variables are loaded from prisma\.env
Schema parsing
thread 'main' has overflowed its stack
---
-> check my schema.prisma
[schema.zip](https://github.com/prisma/prisma/files/4929401/schema.zip)

**Comment by pantharshit00** [comment] 2020-07-23 11:59
Hi,

Thanks for reporting this! It has already been reported before, so I am going to close this as a duplicate of https://github.com/prisma/prisma/issues/3051

**Closed by pantharshit00** 2020-07-23 11:59 UTC

**Comment by GBSH-dev** [comment] 2020-07-24 05:48
Hello @pantharshit00 
please check details , This is not same.

**Comment by janpio** [comment] 2020-07-24 08:56
@GBSH-dev the issue @pantharshit00 linked was created based on a discussion that has exactly the same text, error message and schema. What is not the same so this issue here should stay open?
