### ISSUE TITLE
`npx prisma` broken in v2.14

### ISSUE THREAD

**Issue by WesCossick** [prisma/prisma#4891] opened 2021-01-05 16:52 UTC
## Bug description

Running `npx prisma` on Prisma v2.14 does not work. All it does is print: `missing ) after argument list`.

## How to reproduce

1. Make sure you're using v2.14 (`yarn add @prisma/cli@2.14.x @prisma/client@2.14.x`)
2. Run something like `npx prisma generate` or `npx prisma -v`
3. See error

You can also confirm it's working on v2.13 by doing:
1. Downgrade to v2.13 (`yarn add @prisma/cli@2.13.x @prisma/client@2.13.x`)
2. Run something like `npx prisma generate` or `npx prisma -v`
3. See that it runs successfully

## Expected behavior

`npx prisma` to actually run.

## Environment & setup

- OS: macOS
- Database: MySQL
- Node.js version: v14.15.4
- Prisma version: v2.14.0 (cannot use `npx prisma -v` because it also produces the error)

**Comment by Jolg42** [comment] 2021-01-06 11:32
Could not reproduce on macOS, Node 14.15.0

Could you send more details about `missing ) after argument list.` is there more logs about that?
Maybe doing a screenshot or copy pasting the full logs could help here.

```
j42@Pluto ~/D/r/repro-4891> yarn init
yarn init v1.22.5
question name (repro-4891): 
question version (1.0.0): 
question description: 
question entry point (index.js): 
question repository url: 
question author: 
question license (MIT): 
question private: 
success Saved package.json
✨  Done in 4.45s.
j42@Pluto ~/D/r/repro-4891> 
j42@Pluto ~/D/r/repro-4891> yarn add @prisma/cli@2.14.x @prisma/client@2.14.x
yarn add v1.22.5
info No lockfile found.
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 🔨  Building fresh packages...
success Saved lockfile.
success Saved 5 new dependencies.
info Direct dependencies
├─ @prisma/cli@2.14.0
└─ @prisma/client@2.14.0
info All dependencies
├─ @prisma/bar@0.0.1
├─ @prisma/cli@2.14.0
├─ @prisma/client@2.14.0
├─ @prisma/engines-version@2.14.0-28.5d491261d382a2a5ffdc71de17072b0e409f1cc1
└─ @prisma/engines@2.14.0-28.5d491261d382a2a5ffdc71de17072b0e409f1cc1
✨  Done in 11.38s.
j42@Pluto ~/D/r/repro-4891> npx prisma -v
@prisma/cli          : 2.14.0
@prisma/client       : 2.14.0
Current platform     : darwin
Query Engine         : query-engine 5d491261d382a2a5ffdc71de17072b0e409f1cc1 (at node_modules/@prisma/engines/query-engine-darwin)
Migration Engine     : migration-engine-cli 5d491261d382a2a5ffdc71de17072b0e409f1cc1 (at node_modules/@prisma/engines/migration-engine-darwin)
Introspection Engine : introspection-core 5d491261d382a2a5ffdc71de17072b0e409f1cc1 (at node_modules/@prisma/engines/introspection-engine-darwin)
Format Binary        : prisma-fmt 5d491261d382a2a5ffdc71de17072b0e409f1cc1 (at node_modules/@prisma/engines/prisma-fmt-darwin)
Studio               : 0.332.0
j42@Pluto ~/D/r/repro-4891> node -v
v14.15.0
```

**Comment by WesCossick** [comment] 2021-01-06 14:34
`missing ) after argument list` is the entirety of the output. See video:

https://user-images.githubusercontent.com/3850064/103779897-ec02f580-4ff9-11eb-992f-14763c0518fd.mp4

**Comment by WesCossick** [comment] 2021-01-06 14:41
Here's a similar sequence of commands to what you used ([recording](http://images.sparksuite.com/v/3xglLI1AokZ0PDh69bGM)):
 
```
wescossick@Wess-MacBook-Pro Downloads % mkdir test-bug
wescossick@Wess-MacBook-Pro Downloads % cd test-bug 
wescossick@Wess-MacBook-Pro test-bug % yarn init
yarn init v1.22.10
question name (test-bug): 
question version (1.0.0): 
question description: 
question entry point (index.js): 
question repository url: 
question author: 
question license (MIT): 
question private: 
success Saved package.json
✨  Done in 2.41s.
wescossick@Wess-MacBook-Pro test-bug % yarn add @prisma/cli@2.14.x @prisma/client@2.14.x
yarn add v1.22.10
info No lockfile found.
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 🔨  Building fresh packages...
success Saved lockfile.
success Saved 5 new dependencies.
info Direct dependencies
├─ @prisma/cli@2.14.0
└─ @prisma/client@2.14.0
info All dependencies
├─ @prisma/bar@0.0.1
├─ @prisma/cli@2.14.0
├─ @prisma/client@2.14.0
├─ @prisma/engines-version@2.14.0-28.5d491261d382a2a5ffdc71de17072b0e409f1cc1
└─ @prisma/engines@2.14.0-28.5d491261d382a2a5ffdc71de17072b0e409f1cc1
✨  Done in 3.22s.
wescossick@Wess-MacBook-Pro test-bug % npx prisma -v
missing ) after argument list
wescossick@Wess-MacBook-Pro test-bug % node -v
v14.15.4
wescossick@Wess-MacBook-Pro test-bug % yarn add @prisma/cli@2.13.x @prisma/client@2.13.x
yarn add v1.22.10
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 🔨  Building fresh packages...
success Saved lockfile.
success Saved 4 new dependencies.
info Direct dependencies
├─ @prisma/cli@2.13.1
└─ @prisma/client@2.13.1
info All dependencies
├─ @prisma/cli@2.13.1
├─ @prisma/client@2.13.1
├─ @prisma/engines-version@2.13.1-2.fcbc4bb2d306c86c28014f596b1e8c7980af8bd4
└─ @prisma/engines@2.13.1-2.fcbc4bb2d306c86c28014f596b1e8c7980af8bd4
✨  Done in 4.21s.
wescossick@Wess-MacBook-Pro test-bug % npx prisma -v
@prisma/cli          : 2.13.1
@prisma/client       : 2.13.1
Current platform     : darwin
Query Engine         : query-engine fcbc4bb2d306c86c28014f596b1e8c7980af8bd4 (at node_modules/@prisma/engines/query-engine-darwin)
Migration Engine     : migration-engine-cli fcbc4bb2d306c86c28014f596b1e8c7980af8bd4 (at node_modules/@prisma/engines/migration-engine-darwin)
Introspection Engine : introspection-core fcbc4bb2d306c86c28014f596b1e8c7980af8bd4 (at node_modules/@prisma/engines/introspection-engine-darwin)
Format Binary        : prisma-fmt fcbc4bb2d306c86c28014f596b1e8c7980af8bd4 (at node_modules/@prisma/engines/prisma-fmt-darwin)
Studio               : 0.329.0
wescossick@Wess-MacBook-Pro test-bug % yarn add @prisma/cli@2.14.x @prisma/client@2.14.x
yarn add v1.22.10
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 🔨  Building fresh packages...
success Saved lockfile.
success Saved 4 new dependencies.
info Direct dependencies
├─ @prisma/cli@2.14.0
└─ @prisma/client@2.14.0
info All dependencies
├─ @prisma/cli@2.14.0
├─ @prisma/client@2.14.0
├─ @prisma/engines-version@2.14.0-28.5d491261d382a2a5ffdc71de17072b0e409f1cc1
└─ @prisma/engines@2.14.0-28.5d491261d382a2a5ffdc71de17072b0e409f1cc1
✨  Done in 2.45s.
wescossick@Wess-MacBook-Pro test-bug % npx prisma -v
missing ) after argument list
```

**Comment by Jolg42** [comment] 2021-01-06 15:25
I suspect that you have a Prisma 1 dependency somehow here, maybe globally.

Could you execute these 2 commands to verify?

`npm list -g` will list all global dependencies, is there some `prisma` there?
`npm list` will list all project dependencies, is there some `prisma` there?

Also this should work `npx @prisma/cli -v`

**Comment by WesCossick** [comment] 2021-01-06 15:29
There is no Prisma installed globally:

```
wescossick@Wess-MacBook-Pro test-bug % npm list -g | grep prisma
wescossick@Wess-MacBook-Pro test-bug % 
```

Only the v2.14.0 packages are listed when using `npm list`:

```
wescossick@Wess-MacBook-Pro test-bug % npm list | grep prisma                           
├─┬ @prisma/cli@2.14.0
│ ├── @prisma/bar@0.0.1
│ └── @prisma/engines@2.14.0-28.5d491261d382a2a5ffdc71de17072b0e409f1cc1
└─┬ @prisma/client@2.14.0
  └── @prisma/engines-version@2.14.0-28.5d491261d382a2a5ffdc71de17072b0e409f1cc1
```

Running `npx @prisma/cli -v` does seem to work, though:

```
wescossick@Wess-MacBook-Pro test-bug % npx @prisma/cli -v
@prisma/cli          : 2.14.0
@prisma/client       : 2.14.0
Current platform     : darwin
Query Engine         : query-engine 5d491261d382a2a5ffdc71de17072b0e409f1cc1 (at ../../.npm/_npx/15138/lib/node_modules/@prisma/cli/node_modules/@prisma/engines/query-engine-darwin)
Migration Engine     : migration-engine-cli 5d491261d382a2a5ffdc71de17072b0e409f1cc1 (at ../../.npm/_npx/15138/lib/node_modules/@prisma/cli/node_modules/@prisma/engines/migration-engine-darwin)
Introspection Engine : introspection-core 5d491261d382a2a5ffdc71de17072b0e409f1cc1 (at ../../.npm/_npx/15138/lib/node_modules/@prisma/cli/node_modules/@prisma/engines/introspection-engine-darwin)
Format Binary        : prisma-fmt 5d491261d382a2a5ffdc71de17072b0e409f1cc1 (at ../../.npm/_npx/15138/lib/node_modules/@prisma/cli/node_modules/@prisma/engines/prisma-fmt-darwin)
Studio               : 0.332.0
```

**Comment by Jolg42** [comment] 2021-01-06 15:37
Maybe @pantharshit00 has an idea here 🤔

**Comment by pantharshit00** [comment] 2021-01-15 12:09
I also can't reproduce this. Try cleaning the npm cache once. ` npm cache clean --force`

**Comment by WesCossick** [comment] 2021-01-15 14:13
Running `npm cache clean --force` followed by `npx prisma -v` produced the same result.

**Comment by pantharshit00** [comment] 2021-01-18 13:42
That's unfortunate and I am still unable to reproduce this :(. I suggest we wait till `2.15` which is going to be released tomorrow then you can try this again.

**Comment by WesCossick** [comment] 2021-01-20 20:07
It looks like `2.15` also does not have the issue, like every other version of Prisma aside from `2.14`. Here's the output of the same command sequence used above, but using `2.15` this time:

```
wescossick@Wess-MacBook-Pro Downloads % mkdir test-bug
wescossick@Wess-MacBook-Pro Downloads % cd test-bug 
wescossick@Wess-MacBook-Pro test-bug % yarn init

yarn init v1.22.10
question name (test-bug): 
question version (1.0.0): 
question description: 
question entry point (index.js): 
question repository url: 
question author: 
question license (MIT): 
question private: 
success Saved package.json
✨  Done in 1.27s.
wescossick@Wess-MacBook-Pro test-bug % yarn add @prisma/cli@2.15.x @prisma/client@2.15.x
yarn add v1.22.10
info No lockfile found.
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 🔨  Building fresh packages...
success Saved lockfile.
success Saved 4 new dependencies.
info Direct dependencies
├─ @prisma/cli@2.15.0
└─ @prisma/client@2.15.0
info All dependencies
├─ @prisma/cli@2.15.0
├─ @prisma/client@2.15.0
├─ @prisma/engines-version@2.15.0-25.e51dc3b5a9ee790a07104bec1c9477d51740fe54
└─ @prisma/engines@2.15.0-25.e51dc3b5a9ee790a07104bec1c9477d51740fe54
✨  Done in 8.68s.
wescossick@Wess-MacBook-Pro test-bug % npx prisma -v
@prisma/cli          : 2.15.0
@prisma/client       : 2.15.0
Current platform     : darwin
Query Engine         : query-engine e51dc3b5a9ee790a07104bec1c9477d51740fe54 (at node_modules/@prisma/engines/query-engine-darwin)
Migration Engine     : migration-engine-cli e51dc3b5a9ee790a07104bec1c9477d51740fe54 (at node_modules/@prisma/engines/migration-engine-darwin)
Introspection Engine : introspection-core e51dc3b5a9ee790a07104bec1c9477d51740fe54 (at node_modules/@prisma/engines/introspection-engine-darwin)
Format Binary        : prisma-fmt e51dc3b5a9ee790a07104bec1c9477d51740fe54 (at node_modules/@prisma/engines/prisma-fmt-darwin)
Studio               : 0.340.0
```

If I run `yarn add @prisma/cli@2.14.x @prisma/client@2.14.x` and then `npx prisma -v`, it's still broken. So there's something wrong with that release in particular. Something that doesn't affect any other version.

**Comment by pantharshit00** [comment] 2021-01-21 13:12
Thanks for the info. I will close this as latest release doesn't have this and no one else was able to reproduce this.

**Closed by pantharshit00** 2021-01-21 13:12 UTC
Labels: bug/0-needs-info, kind/bug, team/client, topic: prisma-client
