### ISSUE TITLE
`mysql://...` connection string with `postgresql` provider does not fail

### ISSUE THREAD

**Issue by janpio** [prisma/prisma#1736] opened 2020-03-01 22:15 UTC
I accidentally only replaced the connection string that was created by `prisma2 init` with `mysql://root:root@localhost:3306/test_chinook_simplified` and did not touch the `provider` in the other file.

`prisma2 introspect` and `prisma2 generate` did not care at all. But when trying to query the database

```
const { PrismaClient } = require('@prisma/client')

const prisma = new PrismaClient()
prisma.album.findMany().then(result => {
    console.log(result)
})
```

I got this error:

```
λ node index.js
(node:9000) UnhandledPromiseRejectionWarning: Error:
Invalid `prisma.albums.findMany()` invocation in
C:\Users\Jan\Documents\throwaway\prismaTestUtils\index.js:4:14

  1 const { PrismaClient } = require('@prisma/client')
  2
  3 const prisma = new PrismaClient()
→ 4 prisma.album.findMany().then(result =>

Error occurred during query execution:
ConnectorError(ConnectorError { user_facing_error: None, kind: QueryError(Server(ServerError { code: 1146, message: "Table \'public.album\' doesn\'t exist", state: "42S02" })) })
    at PrismaClientFetcher.request (C:\Users\Jan\Documents\throwaway\prismaTestUtils\node_modules\@prisma\client\index.js:90:17)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:9000) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:9000) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Only on third look I saw and wondered about `public.album` - there should be no schema in MySQL query!

After changing the provider to `mysql` and running `prisma2 generate` again everything works:

```
λ node index.js
[
  { AlbumId: 1, Title: 'irapa' },
  { AlbumId: 2, Title: 'ejagu' },
  { AlbumId: 3, Title: 'lerpo' }
]
```

---
λ prisma2 -v
prisma2@2.0.0-alpha.843, binary version: e167d27e7f147151af1411efe20c1aa525059cb8
(global install)

**Comment by pantharshit00** [comment] 2020-03-04 13:54
I can confirm this with `prisma2@2.0.0-preview023, binary version: d3b0ceed5d87544b9d2decb70e08664f9047bb73`

**Comment by tomhoule** [comment] 2020-03-27 10:44
Same behaviour observed with reverse (mysql url, postgres db) on introspection.

**Comment by tomhoule** [comment] 2020-04-01 15:46
I think this should be validated in the datasource validation if possible. Since the sql connectors only care about the URL, if the scheme is wrong, they'll just try to start a connection to a postgres server with the mysql protocol or vice versa. In my experiments it just hangs, so it's hard to detect if it's that or a bad connection.

**Comment by mavilein** [comment] 2020-04-06 14:55
Internal Note: This will probably clash with our hack for ignoring env vars, which insert `dummy://url` when an env var is missing.

**Comment by mavilein** [comment] 2020-04-16 21:28
Fixed in https://github.com/prisma/prisma-engines/pull/679

**Closed by mavilein** 2020-04-16 21:28 UTC
Labels: bug/2-confirmed, kind/bug, team/engines, topic: cli-generate, topic: cli-introspect, topic: prisma-client
