### ISSUE TITLE
Postgres: Cannot Update a JSON Field

### ISSUE THREAD

**Issue by SamTheFam** [prisma/prisma#7121] opened 2021-05-17 18:29 UTC
I have a JSON in my database model like this:

```prisma
email Json? @db.JsonB
```

But when I try and `update` my database like this, I get a Typescript error:

```ts
await prisma.user.update({
    data: {
        emailConfirmed: true,
    },
    where: {
        email: emailHash,
    },
});
```

Here is the error:

```
Type '{ email: EmailHash; }' is not assignable to type 'UserWhereUniqueInput'.
  Object literal may only specify known properties, and 'email' does not exist in type 'UserWhereUniqueInput'.ts(2322)
```

It doesn't look like it's possible to update JSON fields with prisma, making the JSON type almost useless.

**Comment by pantharshit00** [comment] 2021-05-18 05:16
@SamTheFam Are you using the preview of the mongo connector? If yes, then this issue is a duplicate of https://github.com/prisma/prisma/issues/6750

**Comment by SamTheFam** [comment] 2021-05-18 06:12
> @SamTheFam Are you using the preview of the mongo connector? If yes, then this issue is a duplicate of https://github.com/prisma/prisma/issues/6750

I am using the Postgres connector.

**Comment by pantharshit00** [comment] 2021-05-18 14:13
I am unable to reproduce this.
![image](https://user-images.githubusercontent.com/22195362/118667106-55e5a400-b811-11eb-8e3d-1e9598678efa.png)


Please make sure you can `prisma generate` after updating your schema.

**Comment by SamTheFam** [comment] 2021-05-18 16:49
Ah, I think I explained it incorrectly. The issue is using `where` on a JSON field.

Here's the repo: https://github.com/SamTheFam/prisma-7121/

**Comment by pantharshit00** [comment] 2021-05-28 22:39
@SamTheFam You will need to use `updateMany` here email is not unique. `update` only take unique fields in where.
```ts
  await prisma.user.updateMany({
    where: {
      email: {
        equals: email,
      },
    },
    data: {
      str: "some string",
    },
  });
```

**Closed by pantharshit00** 2021-05-28 22:39 UTC
Labels: bug/0-needs-info, kind/bug, team/client, tech/typescript
