### ISSUE TITLE
prisma migrate not working with basic example `Reason: [libs/sql-schema-describer/src/getters.rs:42:14] called `Result::unwrap()` on an `Err` value: "Getting non_unique from Resultrow ResultRow { columns: [\"index_name\", \"non_unique\", \"column_name\", \"seq_in_index\", \"table_name\"], values: [Text(Some(\"PRIMARY\")), Text(Some(\"0\")), Text(Some(\"id\")), Integer(Some(1)), Text(Some(\"_prisma_migrations\"))] } as bool failed"`

### ISSUE THREAD

**Issue by kang-heewon** [prisma/prisma#5235] opened 2021-01-22 04:17 UTC
Hi Prisma Team! Prisma Migrate just crashed. 

## Versions
      
| Name        | Version            |
|-------------|--------------------|
| Platform    | darwin             | 
| Node        | v14.15.0           | 
| Prisma CLI  | 2.15.0             | 
| Binary      | e51dc3b5a9ee790a07104bec1c9477d51740fe54| 

## Error
```
Error: Error in migration engine.
Reason: [libs/sql-schema-describer/src/getters.rs:42:14] called `Result::unwrap()` on an `Err` value: "Getting non_unique from Resultrow ResultRow { columns: [\"index_name\", \"non_unique\", \"column_name\", \"seq_in_index\", \"table_name\"], values: [Text(Some(\"PRIMARY\")), Text(Some(\"0\")), Text(Some(\"id\")), Integer(Some(1)), Text(Some(\"_prisma_migrations\"))] } as bool failed"

Please create an issue in the migrate repo with
your `schema.prisma` and the prisma command you tried to use 🙏:
https://github.com/prisma/prisma/issues/new

```

**Comment by kang-heewon** [comment] 2021-01-22 04:18
```
generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "mysql"
  url      = env("DATABASE_URL")
}

model User {
  id    Int    @id @default(autoincrement())
  name  String
  posts Post[]
}

model Post {
  id        Int     @id @default(autoincrement())
  title     String
  published Boolean @default(true)
  authorId  Int
  author    User    @relation(fields: [authorId], references: [id])
}
```
This is my schema.

**Comment by kang-heewon** [comment] 2021-01-22 04:24
```
@prisma/cli          : 2.15.0
@prisma/client       : 2.15.0
Current platform     : darwin
Query Engine         : query-engine e51dc3b5a9ee790a07104bec1c9477d51740fe54 (at node_modules/@prisma/engines/query-engine-darwin)
Migration Engine     : migration-engine-cli e51dc3b5a9ee790a07104bec1c9477d51740fe54 (at node_modules/@prisma/engines/migration-engine-darwin)
Introspection Engine : introspection-core e51dc3b5a9ee790a07104bec1c9477d51740fe54 (at node_modules/@prisma/engines/introspection-engine-darwin)
Format Binary        : prisma-fmt e51dc3b5a9ee790a07104bec1c9477d51740fe54 (at node_modules/@prisma/engines/prisma-fmt-darwin)
Studio               : 0.340.0
```
this is my prisma version

**Comment by tomhoule** [comment] 2021-01-22 10:34
Hi @kang-heewon , thanks for the error report, we'll look into it. Can you tell us what database version you are using?

**Comment by tomhoule** [comment] 2021-01-22 10:34
and which OS

**Comment by kang-heewon** [comment] 2021-01-23 03:56
I am using macOS and mysql. 
mysql is on remote ubuntu 18.04 server and using v8.

**Comment by pantharshit00** [comment] 2021-01-27 19:30
I wasn't able to reproduce this. Migrate correctly generated the following migrate for me:
```sql
-- CreateTable
CREATE TABLE `User` (
    `id` INT NOT NULL AUTO_INCREMENT,
    `name` VARCHAR(191) NOT NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `Post` (
    `id` INT NOT NULL AUTO_INCREMENT,
    `title` VARCHAR(191) NOT NULL,
    `published` BOOLEAN NOT NULL DEFAULT true,
    `authorId` INT NOT NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `Post` ADD FOREIGN KEY (`authorId`) REFERENCES `User`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;
```


Are you starting from a fresh database or there is some existing data in your database?

**Comment by kang-heewon** [comment] 2021-01-28 05:53
i'm starting from fresh database.
and my mysql user is root. also i set previlege.

**Comment by kang-heewon** [comment] 2021-01-28 05:55
"Migrate" correctly genrate migration.sql & migration_lock.toml.
but my database has only _prisma_migration table.

**Comment by kang-heewon** [comment] 2021-01-28 06:43
I am running a database through docker.
So I created a new database and tried it.
but... 😢 
```
~/starter » yarn prisma migrate dev --preview-feature --name init                                                                                                                                                         1 ↵ owen@ganghuiwon-ui-MacBook-Pro
yarn run v1.22.10
$ /Users/owen/starter/node_modules/.bin/prisma migrate dev --preview-feature --name init
Environment variables loaded from prisma/.env
Prisma schema loaded from prisma/schema.prisma
Datasource "db": MySQL database "test" at "nas.heewon.dev:32771"

MySQL database test created at nas.heewon.dev:32771

Oops, an unexpected error occured!
Error in migration engine.
Reason: [libs/sql-schema-describer/src/getters.rs:42:14] called `Result::unwrap()` on an `Err` value: "Getting non_unique from Resultrow ResultRow { columns: [\"index_name\", \"non_unique\", \"column_name\", \"seq_in_index\", \"table_name\"], values: [Text(Some(\"PRIMARY\")), Text(Some(\"0\")), Text(Some(\"id\")), Integer(Some(1)), Text(Some(\"_prisma_migrations\"))] } as bool failed"

Please create an issue in the migrate repo with
your `schema.prisma` and the prisma command you tried to use 🙏:
https://github.com/prisma/prisma/issues/new


Please help us improve Prisma by submitting an error report.
Error reports never contain personal or other sensitive information.
Learn more: https://pris.ly/d/telemetry

? Submit error report › - Use arrow-keys. Return to submit.
❯   Yes - Send error report once
    No
```

**Comment by kang-heewon** [comment] 2021-01-28 06:51
I make same environment on this repo.
https://github.com/kang-heewon/prisma-starter-with-bug
can you try with my database?
This is the same database configured for this issue.

**Comment by pantharshit00** [comment] 2021-01-29 11:22
@kang-heewon It worked for me. Checkout your database, it should have a `test_prisma` database with the migration.

**Comment by kang-heewon** [comment] 2021-01-30 05:04
hmm.. it must be my problem.

**Comment by kang-heewon** [comment] 2021-02-18 04:22
I can't fix my problem.

**Comment by kang-heewon** [comment] 2021-02-18 04:23
```
 MigrateEngine:rpc starting migration engine with binary: /Users/owen/Project/prisma-starter-with-bug/node_modules/@prisma/engines/migration-engine-darwin +0ms
  MigrateEngine:rpc SENDING RPC CALL {"id":1,"jsonrpc":"2.0","method":"devDiagnostic","params":{"migrationsDirectoryPath":"/Users/owen/Project/prisma-starter-with-bug/prisma/migrations"}} +5ms
  MigrateEngine:stderr Feb 18 13:19:18.448  INFO migration_engine: Starting migration engine RPC server git_hash="e51dc3b5a9ee790a07104bec1c9477d51740fe54" +0ms
  MigrateEngine:stderr Feb 18 13:19:18.510  INFO quaint::single: Starting a mysql connection. +61ms
  MigrateEngine:stderr Feb 18 13:19:18.617  INFO DevDiagnostic:calculate_drift:sql_schema_from_migration_history: quaint::single: Starting a mysql connection. +107ms
  MigrateEngine:stderr Feb 18 13:19:18.820  INFO DevDiagnostic:validate_migrations:sql_schema_from_migration_history: quaint::single: Starting a mysql connection. +203ms
  migrate:dev {
  migrate:dev   devDiagnostic: '{\n  "action": {\n    "tag": "createMigration"\n  }\n}'
  migrate:dev } +0ms
  MigrateEngine:rpc SENDING RPC CALL {"id":2,"jsonrpc":"2.0","method":"applyMigrations","params":{"migrationsDirectoryPath":"/Users/owen/Project/prisma-starter-with-bug/prisma/migrations"}} +460ms
  MigrateEngine:rpc SENDING RPC CALL {"id":3,"jsonrpc":"2.0","method":"evaluateDataLoss","params":{"migrationsDirectoryPath":"/Users/owen/Project/prisma-starter-with-bug/prisma/migrations","prismaSchema":"// This is your Prisma schema file,\n// learn more about it in the docs: https://pris.ly/d/prisma-schema\n\ndatasource db {\n  provider = \"mysql\"\n  url      = env(\"DATABASE_URL\")\n}\n\ngenerator client {\n  provider = \"prisma-client-js\"\n}\n\nmodel Student {\n  id       String @id @default(cuid())\n  name     String\n  career   Career @relation(fields: [careerId], references: [id])\n  careerId String\n}\n\nmodel Career {\n  id       String    @id @default(cuid())\n  name     String\n  students Student[]\n}\n"}} +102ms
  MigrateEngine:stderr Feb 18 13:19:19.052  INFO EvaluateDataLoss:infer_next_migration:sql_schema_from_migration_history: quaint::single: Starting a mysql connection. +232ms
  migrate:dev {
  migrate:dev   evaluateDataLossResult: {
  migrate:dev     migrationSteps: [
  migrate:dev       'CREATE TABLE `Student` (\n' +
  migrate:dev         '    `id` VARCHAR(191) NOT NULL,\n' +
  migrate:dev         '    `name` VARCHAR(191) NOT NULL,\n' +
  migrate:dev         '    `careerId` VARCHAR(191) NOT NULL,\n' +
  migrate:dev         '\n' +
  migrate:dev         '    PRIMARY KEY (`id`)\n' +
  migrate:dev         ') DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci',
  migrate:dev       'CREATE TABLE `Career` (\n' +
  migrate:dev         '    `id` VARCHAR(191) NOT NULL,\n' +
  migrate:dev         '    `name` VARCHAR(191) NOT NULL,\n' +
  migrate:dev         '\n' +
  migrate:dev         '    PRIMARY KEY (`id`)\n' +
  migrate:dev         ') DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci',
  migrate:dev       'ALTER TABLE `Student` ADD FOREIGN KEY (`careerId`) REFERENCES `Career`(`id`) ON DELETE CASCADE ON UPDATE CASCADE'
  migrate:dev     ],
  migrate:dev     warnings: [],
  migrate:dev     unexecutableSteps: []
  migrate:dev   }
  migrate:dev } +285ms
  MigrateEngine:rpc SENDING RPC CALL {"id":4,"jsonrpc":"2.0","method":"createMigration","params":{"migrationsDirectoryPath":"/Users/owen/Project/prisma-starter-with-bug/prisma/migrations","migrationName":"init","draft":false,"prismaSchema":"// This is your Prisma schema file,\n// learn more about it in the docs: https://pris.ly/d/prisma-schema\n\ndatasource db {\n  provider = \"mysql\"\n  url      = env(\"DATABASE_URL\")\n}\n\ngenerator client {\n  provider = \"prisma-client-js\"\n}\n\nmodel Student {\n  id       String @id @default(cuid())\n  name     String\n  career   Career @relation(fields: [careerId], references: [id])\n  careerId String\n}\n\nmodel Career {\n  id       String    @id @default(cuid())\n  name     String\n  students Student[]\n}\n"}} +185ms
  MigrateEngine:stderr Feb 18 13:19:19.243  INFO CreateMigration{migration_name="init" draft=false}:infer_next_migration:sql_schema_from_migration_history: quaint::single: Starting a mysql connection. +191ms
  migrate:dev {
  migrate:dev   createMigrationResult: { generatedMigrationName: '20210218041919_init' }
  migrate:dev } +138ms
  MigrateEngine:rpc SENDING RPC CALL {"id":5,"jsonrpc":"2.0","method":"applyMigrations","params":{"migrationsDirectoryPath":"/Users/owen/Project/prisma-starter-with-bug/prisma/migrations"}} +134ms
  MigrateEngine:stderr {"is_panic":true,"message":"[libs/sql-schema-describer/src/getters.rs:42:14] called `Result::unwrap()` on an `Err` value: \"Getting non_unique from Resultrow ResultRow { columns: [\\\"index_name\\\", \\\"non_unique\\\", \\\"column_name\\\", \\\"seq_in_index\\\", \\\"table_name\\\"], values: [Text(Some(\\\"PRIMARY\\\")), Text(Some(\\\"0\\\")), Text(Some(\\\"id\\\")), Integer(Some(1)), Text(Some(\\\"_prisma_migrations\\\"))] } as bool failed\"","backtrace":"   0: backtrace::backtrace::trace\n   1: backtrace::capture::Backtrace::new\n   2: user_facing_errors::Error::new_in_panic_hook\n   3: user_facing_errors::panic_hook::set_panic_hook::{{closure}}\n   4: std::panicking::rust_panic_with_hook\n   5: std::panicking::begin_panic_handler::{{closure}}\n   6: std::sys_common::backtrace::__rust_end_short_backtrace\n   7: _rust_begin_unwind\n   8: core::panicking::panic_fmt\n   9: core::option::expect_none_failed\n  10: <quaint::connector::result_set::result_row::ResultRow as sql_schema_describer::getters::Getter>::get_expect_bool\n  11: <sql_schema_describer::mysql::SqlSchemaDescriber as sql_schema_describer::SqlSchemaDescriberBackend>::describe::__describe::{{closure}}::{{closure}}\n  12: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll\n  13: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll\n  14: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll\n  15: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll\n  16: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll\n  17: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll\n  18: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll\n  19: migration_core::api::rpc::RpcApi::create_handler::{{closure}}\n  20: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll\n  21: <futures_util::compat::compat03as01::Compat<Fut> as futures::future::Future>::poll\n  22: <futures::future::lazy::Lazy<F,R> as futures::future::Future>::poll\n  23: futures::future::chain::Chain<A,B,C>::poll\n  24: <futures::future::then::Then<A,B,F> as futures::future::Future>::poll\n  25: <futures::future::map::Map<A,F> as futures::future::Future>::poll\n  26: <futures::future::either::Either<A,B> as futures::future::Future>::poll\n  27: futures::task_impl::std::set\n  28: migration_engine::main::{{closure}}\n  29: tokio::runtime::thread_pool::ThreadPool::block_on\n  30: tokio::runtime::context::enter\n  31: tokio::runtime::handle::Handle::enter\n  32: migration_engine::main\n  33: std::sys_common::backtrace::__rust_begin_short_backtrace\n  34: std::rt::lang_start::{{closure}}\n  35: std::rt::lang_start_internal\n  36: _main\n"} +112ms
```

**Comment by kang-heewon** [comment] 2021-02-18 04:24
I created a new database and reinstalled prisma several times but it doesn't work.

**Comment by kang-heewon** [comment] 2021-02-18 04:47
when i use 2.13.1 is worked for me

**Comment by pantharshit00** [comment] 2021-02-18 07:49
@kang-heewon Is it the same repository?

**Comment by kang-heewon** [comment] 2021-02-18 08:06
@pantharshit00 yes!

**Comment by tomhoule** [comment] 2021-03-01 10:17
I think I found what's going on @kang-heewon — weirdly, your mysql doesn't return the same from its information schema as other installations, so I couldn't reproduce it in test, but https://github.com/prisma/prisma-engines/pull/1694 should fix the problem. It will be in tomorrow's release.

**Closed** 2021-03-02 08:04 UTC
Labels: bug/0-needs-info, kind/bug, process/candidate, team/migrations
