### ISSUE TITLE
Error in migration engine. Reason: Starting migration engine RPC server 

### ISSUE THREAD

**Issue by jkomyno** [prisma/prisma#16132] opened 2022-11-04 12:03 UTC
Command: `prisma migrate dev`
Version: `4.5.0`
Binary Version: `0362da9eebca54d94c8ef5edd3b2e90af99ba452`
Report: https://prisma-errors.netlify.app/report/14416 
OS: `x64 win32 10.0.19044`

JS Stacktrace:
```
Error: Error in migration engine.
Reason: Starting migration engine RPC server

Please create an issue with your `schema.prisma` at
https://github.com/prisma/prisma/issues/new

    at handlePanic (E:\CODING\Next-Projects\supaVacation\node_modules\prisma\build\index.js:93411:15)
    at ChildProcess.<anonymous> (E:\CODING\Next-Projects\supaVacation\node_modules\prisma\build\index.js:93430:15)
    at ChildProcess.emit (node:events:390:28)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)
```

Rust Stacktrace:
```
Starting migration engine RPC server
```

**Comment by jkomyno** [comment] 2022-11-04 12:03
We're probably not doing everything we can to capture useful errors when `prisma migrate dev` panics.

**Comment by FrancoMuniz** [comment] 2022-11-09 17:00
Is there a fix for this? I keep getting this error when running prisma migrate dev

**Comment by jkomyno** [comment] 2022-11-09 17:44
Hi @FrancoMuniz, would please be able to share a quick reproduction of this error with us? That would help us spotting the bug source and hopefully provide a solution

**Comment by FrancoMuniz** [comment] 2022-11-09 18:56
Hey @jkomyno, the issue is the same as the on you mentioned, also on Windows.

```
Error: Error in migration engine.
Reason: Starting migration engine RPC server

Please create an issue with your `schema.prisma` at
https://github.com/prisma/prisma/issues/new
```

That's all the console outputs. Is there anything else I can check to understand the issue better?

A few hours ago, using the same schema.prisma file, the migration worked properly.

**Comment by jkomyno** [comment] 2022-11-10 09:41
Hey @FrancoMuniz, thanks for your reply, but what I really meant was: can you please share a minimally reproducible repository where we can run a sequence of `prisma` commands that triggers the same error you're facing right now?

You may take [this reproduction repository](https://github.com/jkomyno/reprod-14539) as a template. Thanks!

**Comment by miguelff** [comment] 2023-07-13 14:41
Gentle ping @FrancoMuniz, have you tried reproducing these with newer versions of prisma? Otherwise could we count with a minimal reproduction repository?

**Comment by millsp** [comment] 2023-07-27 13:35
We haven't heard back about this issue, so we'll close it for now as we need a few more details to be able to dig into this problem. Don't hesitate to add more details in a new comment, and we'll be happy to reopen the issue. Thank you! :pray:

**Closed by millsp** 2023-07-27 13:35 UTC
Labels: bug/0-unknown, kind/bug, topic: error reporting, team/schema, topic: prisma migrate dev
