### ISSUE TITLE
Prisma 3.15.2 does not work on latest node:16-alpine3.17 (node:16-alpine3.16 works)

### ISSUE THREAD

**Issue by proutek** [prisma/prisma#16834] opened 2022-12-15 12:32 UTC
### Bug description

Suddenly our CI on github started to fail when running build inside docker image with node:16-alpine
After few tryouts I have find out that node:16-alpine3.16 works but latest version node:16-alpine3.17 does not.

Prisma shows this error

```
Prisma schema loaded from prisma/schema.prisma
Error: Get config: Unable to establish a connection to query-engine-node-api library
```

**Comment by craig-feldman** [comment] 2022-12-15 12:55
We are using `node 18` and `prisma 4.6.1` and are also experiencing issues with the latest alpine:

`Unable to load Node-API Library from /app/node_modules/.pnpm/@prisma+client@4.6.1_prisma@4.6.1/node_modules/.prisma/client/libquery_engine-linux-musl.so.node, Library may be corrupt`

**Comment by ncarn2** [comment] 2022-12-15 18:31
Same issue here, Github CI node `v16.16.0` and `@prisma/client: 4.7.1` 

```
Error: Unable to establish a connection to query-engine-node-api library. It seems there is a problem with your OpenSSL installation!
Details: Unable to require(`/app/node_modules/prisma/libquery_engine-linux-musl.so.node`)
 Error loading shared library libssl.so.1.1: No such file or directory (needed by /app/node_modules/prisma/libquery_engine-linux-musl.so.node)
 ```

**Comment by tonton-k37** [comment] 2022-12-16 02:38
Hi, I'm using fly.io for the hosting service. facing the same issue here. This is my set up files.

```terminal
#12 3.338 npm WARN exec The following package was not found and will be installed: prisma@4.7.1
#12 26.04 Prisma schema loaded from prisma/schema.prisma
#12 27.07 Error: Unable to establish a connection to query-engine-node-api library. It seems there is a problem with your OpenSSL installation!
#12 27.07 Details: Unable to require(`/root/.npm/_npx/2778af9cee32ff87/node_modules/prisma/libquery_engine-linux-musl.so.node`)
#12 27.07  Error loading shared library libssl.so.1.1: No such file or directory (needed by /root/.npm/_npx/2778af9cee32ff87/node_modules/prisma/libquery_engine-linux-musl.so.node)
```

```Dockerfile
# Install dependencies only when needed
FROM node:16-alpine AS builder
RUN apk add --no-cache libc6-compat
WORKDIR /app
COPY . .

ENV NEXT_TELEMETRY_DISABLED 1

RUN npx prisma generate
RUN yarn build:nexus

# Production image, copy all the files and run next
FROM node:16-alpine AS runner
WORKDIR /app

ENV NODE_ENV production
ENV NEXT_TELEMETRY_DISABLED 1

RUN addgroup --system --gid 1001 nodejs
RUN adduser --system --uid 1001 nextjs

COPY --from=builder --chown=node:node /app ./

# USER nextjs
USER node

CMD ["yarn", "start"]
```

```json

  "dependencies": {
    "@apollo/client": "^3.7.0",
    "@chakra-ui/react": "^2.3.6",
    "@emotion/react": "^11.10.4",
    "@emotion/styled": "^11.10.4",
    "@hookform/resolvers": "^2.9.10",
    "@next-auth/prisma-adapter": "^1.0.5",
    "@prisma/client": "^4.5.0",
    ...
}

**Comment by tonton-k37** [comment] 2022-12-16 03:13
> Hi, I'm using fly.io for the hosting service. facing the same issue here. This is my set up files.
> 
> ```
> #12 3.338 npm WARN exec The following package was not found and will be installed: prisma@4.7.1
> #12 26.04 Prisma schema loaded from prisma/schema.prisma
> #12 27.07 Error: Unable to establish a connection to query-engine-node-api library. It seems there is a problem with your OpenSSL installation!
> #12 27.07 Details: Unable to require(`/root/.npm/_npx/2778af9cee32ff87/node_modules/prisma/libquery_engine-linux-musl.so.node`)
> #12 27.07  Error loading shared library libssl.so.1.1: No such file or directory (needed by /root/.npm/_npx/2778af9cee32ff87/node_modules/prisma/libquery_engine-linux-musl.so.node)
> ```
> 
> ```dockerfile
> # Install dependencies only when needed
> FROM node:16-alpine AS builder
> RUN apk add --no-cache libc6-compat
> WORKDIR /app
> COPY . .
> 
> ENV NEXT_TELEMETRY_DISABLED 1
> 
> RUN npx prisma generate
> RUN yarn build:nexus
> 
> # Production image, copy all the files and run next
> FROM node:16-alpine AS runner
> WORKDIR /app
> 
> ENV NODE_ENV production
> ENV NEXT_TELEMETRY_DISABLED 1
> 
> RUN addgroup --system --gid 1001 nodejs
> RUN adduser --system --uid 1001 nextjs
> 
> COPY --from=builder --chown=node:node /app ./
> 
> # USER nextjs
> USER node
> 
> CMD ["yarn", "start"]
> ```
> 
> ```json
>   "dependencies": {
>     "@apollo/client": "^3.7.0",
>     "@chakra-ui/react": "^2.3.6",
>     "@emotion/react": "^11.10.4",
>     "@emotion/styled": "^11.10.4",
>     "@hookform/resolvers": "^2.9.10",
>     "@next-auth/prisma-adapter": "^1.0.5",
>     "@prisma/client": "^4.5.0",
>     ...
> }
> ```

the problem fixed by adding `RUN apk add --update --no-cache openssl1.1-compat` from the answer of https://github.com/prisma/prisma/issues/14073#issuecomment-1348534199

**Comment by DenzoNL** [comment] 2022-12-16 10:30
Perhaps it is related due to Alpine 3.17 upgrading to OpenSSL 3.0 from 1.1.1?

**Comment by Ketcap** [comment] 2022-12-16 12:51
Using similiar setups with docker.
Getting error of :
```
"Context creation failed: Unable to load Node-API Library from /app/node_modules/.prisma/client/libquery_engine-linux-musl.so.node, Library may be corrupt"
```
package.json
```
...
 "prisma": "^3.15.1",
"@prisma/client": "^3.15.1"
...


In docker
```
FROM node:16-alpine3.16 AS installer
```

Builds fine but error thrown on run time.

**Comment by jkomyno** [comment] 2022-12-16 16:40
Hey everyone, closing as a duplicate of https://github.com/prisma/prisma/issues/16553.
Please follow the steps described in https://github.com/prisma/prisma/issues/16553#issuecomment-1353302617 for a working solution.

TL/DR, you have two choices:

- Use a Node.js Docker image based on Alpine 3.16, like `node:alpine3.16`, `node:lts-alpine3.16`, `node:18.12.1-alpine3.16` (encouraged)

- Install OpenSSL 1.1.x via the `openssl1.1-compat` package, e.g., by adding
  ```Dockerfile
  RUN apk add --update --no-cache openssl1.1-compat
  ```
  to your Dockerfile before installing Prisma 

**Notes**:
- we recommend you to **always** pin Docker images to a specific version, to ensure reproducible builds
- we've noticed some comments in similar issues suggesting to install `libc` / `libc6-compat` on Linux Alpine to fix the problem. Please **DON'T** do this, as it could cause other unexpected errors.

**Closed by jkomyno** 2022-12-16 16:40 UTC
Labels: bug/0-unknown, kind/bug, tech/engines/query engine, topic: node version, team/client, topic: alpine
