### ISSUE TITLE
Support SureealDB

### ISSUE THREAD

**Issue by jonasschultheiss** [prisma/prisma#15350] opened 2022-09-15 19:45 UTC
I just took a look at SurrealDB and it looks really cool.
Lately I've been using nestjs coupled with prisma and I really like it.
Could you take a look at this new DB, maybe give an estimate on how much work this would be and if this can be considered in the future?

https://youtu.be/C7WFwgDRStM

**Comment by janpio** [comment] 2022-09-15 19:50
Duplicate of https://github.com/prisma/prisma/issues/15346

**Closed by janpio** 2022-09-15 19:50 UTC
