### ISSUE TITLE
Prisma crashes with `This is a non-recoverable error which probably happens when the Prisma Query Engine has a panic.`

### ISSUE THREAD

**Issue by thesunny** [prisma/prisma#2754] opened 2020-06-14 21:42 UTC
## Bug description

Prisma panics on a valid query.

I make this Prisma call:

```ts
  await prisma.book_share_email_invitations.findOne({
    select: {
      id: true,
      book_id: true,
      book: {
        select: {
          id: true,
          name: true,
          shelf: { select: { id: true, name: true } },
        },
      },
      email: true,
      permission: true,
      // vvv This is the problematic part
      last_sent_user: {
        select: {
          id: true,
          name: true,
          first_name: true,
          last_name: true,
        },
      },
    },
    where: { auth_token },
  })
```

In the query, I request `last_sent_user` which is a relation based on the field `last_sent_by` (full schema shown later).

Additional details:

- This isn't the default name for the relation which would be `users`; however, `last_sent_user` is more representative of what the relation is.
- The `last_sent_user` related record does exist. I checked it manually and the related `users.id` exists in the database.
- If I remove `last_sent_user` from the query, it executes without error.
- The book relation works fine.

The error is:

```
Error at path "api/pages/share/book/[auth_token].ts" on method "entry":
Invalid `prisma.book_share_email_invitations.findOne()` invocation in
/Users/sunnyhirai/Projects/airshelf/api/pages/share/book/[auth_token].ts:8:52

   4 async function getInvitation(
   5   [object Object], auth_token ,[object Object],[object Object], ,[object Object], auth_token,[object Object], string ,[object Object],[object Object],
   6   ,[object Object], prisma ,[object Object],[object Object], ,[object Object],[object Object],Context
   7 ) {
→  8   return await prisma.book_share_email_invitations.findOne(
  PANIC: Application logic invariant error: received null value for field last_sent_user which may not be null

This is a non-recoverable error which probably happens when the Prisma Query Engine has a panic.
```

As can be seen in the error, Prisma is expected to receive a value for `last_sent_user`:

```sql
SELECT "public"."book_share_email_invitations"."id", "public"."book_share_email_invitations"."book_id", "public"."book_share_email_invitations"."email", "public"."book_share_email_invitations"."permission", "public"."book_share_email_invitations"."book_id", "public"."book_share_email_invitations"."last_sent_by" FROM "public"."book_share_email_invitations" WHERE "public"."book_share_email_invitations"."auth_token" = $1 LIMIT $2 OFFSET $3
```

## How to reproduce

I've provided details below but a minimal reproduction may be hard to create because my other relations work fine. I don't know what is special about this one that makes it crash other than the naming is a little different (however, other relations are renamed to use a singular form in many cases).

## Expected behavior

Should not panic.

## Prisma information

These are the immediate models related to this query.

```
model book_share_email_invitations {
  auth_token   String @unique
  book_id      Int
  email        String
  id           Int    @default(autoincrement()) @id
  last_sent_by Int
  permission   Int
  // normalized (singularized)
  book        books  @relation(fields: [book_id], references: [id])
  // normalized (singularized)
  last_sent_user        users  @relation(fields: [last_sent_by], references: [id])

  @@index([book_id], name: "book_share_email_invitations_book_id_index")
  @@unique([book_id, email], name: "book_share_email_invitations_book_id_email_unique")
}

model users {
  created_at                   Int
  email                        String                         @unique
  first_name                   String
  id                           Int                            @id
  last_name                    String
  name                         String                         @unique
  password_hash                String?
  // normalized (singularized)
  shelf                      shelves                        @relation(fields: [id], references: [id])
  // normalized (no change)
  book_marks                   book_marks[]
  // normalized (no change)
  book_share_email_invitations book_share_email_invitations[]
  // normalized (no change)
  book_shares                  book_shares[]
  // normalized (no change)
  notifications                notifications[]
  // normalized (no change)
  page_edit_sessions           page_edit_sessions[]
  // normalized (no change)
  page_marks                   page_marks[]
  // normalized (no change)
  pages                        pages[]
  // normalized (no change)
  sessions                     sessions[]
  // normalized (no change)
  user_starred_books           user_starred_books[]
}

model books {
  counter                      Int                            @default(0)
  created_at                   Int
  id                           Int                            @default(autoincrement()) @id
  name                         String
  privacy                      Int
  shelf_id                     Int
  title                        String
  toc                          Json
  updated_at                   Int
  // normalized (singularized)
  shelf                      shelves                        @relation(fields: [shelf_id], references: [id])
  // normalized (no change)
  book_marks                   book_marks[]
  // normalized (no change)
  book_share_email_invitations book_share_email_invitations[]
  // normalized (no change)
  book_shares                  book_shares[]
  // normalized (no change)
  pages                        pages[]
  // normalized (no change)
  shelf_pinned_books           shelf_pinned_books[]
  // normalized (no change)
  user_starred_books           user_starred_books[]

  @@unique([shelf_id, name], name: "books_shelf_id_name_unique")
}
```

## Environment & setup

- OS: Mac OS
- Database: PostgreSQL
- Prisma version: 2.0.0
- Node.js version: v12.16.2

**Comment by thesunny** [comment] 2020-06-14 23:36
The was solved by removing @prisma/client and adding it again.

As the solution was unclear, I added issue https://github.com/prisma/prisma/issues/2753 to improve the error message.

**Comment by thesunny** [comment] 2020-06-15 17:28
The panic occurs again in the same place `last_sent_user` in production. Since it is in the same place, it feels like this is something more than just a one time corruption.

We are going live in two weeks.

Would appreciate somebody taking a look or offering some suggestions on how to prevent this when our app is live.

**Comment by janpio** [comment] 2020-06-15 17:37
Does this always crash or just sometimes?
Can you maybe a dump of your SQL with the data that is causing this? Then it would be simple for us to reproduce.

**Comment by thesunny** [comment] 2020-06-15 19:35
@janpio,

When I run it, it always crashes.

These are the unedited SQL logs from Heroku.

Some of the queries are executed in the same `Promise.all` in parallel on the client. The API accepts a graph, and executes each branch of the graph in its own Promise which it then combines together at the end using `Promise.all`. I mention this in case parallelism in Prisma is part of the issue.

```
2020-06-15T19:30:48.000000+00:00 app[postgres.10197]: [PINK] [16-1]  sql_error_code = 00000 LOG:  statement:
2020-06-15T19:30:48.000000+00:00 app[postgres.10197]: [PINK] [16-2] 	            SET search_path = "public";
2020-06-15T19:30:48.000000+00:00 app[postgres.10197]: [PINK] [16-3] 	            SET NAMES 'UTF8';
2020-06-15T19:30:48.000000+00:00 app[postgres.10197]: [PINK] [16-4]
2020-06-15T19:30:48.000000+00:00 app[postgres.10197]: [PINK] [17-1]  sql_error_code = 00000 LOG:  duration: 0.151 ms
2020-06-15T19:30:48.000000+00:00 app[postgres.10197]: [PINK] [18-1]  sql_error_code = 00000 LOG:  duration: 0.781 ms  parse s0: SELECT "public"."sessions"."id", "public"."sessions"."user_id" FROM "public"."sessions" WHERE "public"."sessions"."token" = $1 LIMIT $2 OFFSET $3
2020-06-15T19:30:48.000000+00:00 app[postgres.10197]: [PINK] [19-1]  sql_error_code = 00000 LOG:  duration: 0.383 ms  bind s0: SELECT "public"."sessions"."id", "public"."sessions"."user_id" FROM "public"."sessions" WHERE "public"."sessions"."token" = $1 LIMIT $2 OFFSET $3
2020-06-15T19:30:48.000000+00:00 app[postgres.10197]: [PINK] [19-2]  sql_error_code = 00000 DETAIL:  parameters: $1 = 'nRj7xaYa2szeC0lQKXrVs', $2 = '1', $3 = '0'
2020-06-15T19:30:48.000000+00:00 app[postgres.10197]: [PINK] [20-1]  sql_error_code = 00000 LOG:  execute s0: SELECT "public"."sessions"."id", "public"."sessions"."user_id" FROM "public"."sessions" WHERE "public"."sessions"."token" = $1 LIMIT $2 OFFSET $3
2020-06-15T19:30:48.000000+00:00 app[postgres.10197]: [PINK] [20-2]  sql_error_code = 00000 DETAIL:  parameters: $1 = 'nRj7xaYa2szeC0lQKXrVs', $2 = '1', $3 = '0'
2020-06-15T19:30:48.000000+00:00 app[postgres.10197]: [PINK] [21-1]  sql_error_code = 00000 LOG:  duration: 0.046 ms
2020-06-15T19:30:48.000000+00:00 app[postgres.10197]: [PINK] [22-1]  sql_error_code = 00000 LOG:  duration: 0.213 ms  parse s1: SELECT "public"."book_share_email_invitations"."id", "public"."book_share_email_invitations"."book_id", "public"."book_share_email_invitations"."email", "public"."book_share_email_invitations"."permission", "public"."book_share_email_invitations"."book_id", "public"."book_share_email_invitations"."last_sent_by" FROM "public"."book_share_email_invitations" WHERE "public"."book_share_email_invitations"."auth_token" = $1 LIMIT $2 OFFSET $3
2020-06-15T19:30:48.000000+00:00 app[postgres.10197]: [PINK] [23-1]  sql_error_code = 00000 LOG:  duration: 0.262 ms  bind s1: SELECT "public"."book_share_email_invitations"."id", "public"."book_share_email_invitations"."book_id", "public"."book_share_email_invitations"."email", "public"."book_share_email_invitations"."permission", "public"."book_share_email_invitations"."book_id", "public"."book_share_email_invitations"."last_sent_by" FROM "public"."book_share_email_invitations" WHERE "public"."book_share_email_invitations"."auth_token" = $1 LIMIT $2 OFFSET $3
2020-06-15T19:30:48.000000+00:00 app[postgres.10197]: [PINK] [23-2]  sql_error_code = 00000 DETAIL:  parameters: $1 = 'ZxgbGRDBJDRIhcpLrMFWh', $2 = '1', $3 = '0'
2020-06-15T19:30:48.000000+00:00 app[postgres.10197]: [PINK] [24-1]  sql_error_code = 00000 LOG:  execute s1: SELECT "public"."book_share_email_invitations"."id", "public"."book_share_email_invitations"."book_id", "public"."book_share_email_invitations"."email", "public"."book_share_email_invitations"."permission", "public"."book_share_email_invitations"."book_id", "public"."book_share_email_invitations"."last_sent_by" FROM "public"."book_share_email_invitations" WHERE "public"."book_share_email_invitations"."auth_token" = $1 LIMIT $2 OFFSET $3
2020-06-15T19:30:48.000000+00:00 app[postgres.10197]: [PINK] [24-2]  sql_error_code = 00000 DETAIL:  parameters: $1 = 'ZxgbGRDBJDRIhcpLrMFWh', $2 = '1', $3 = '0'
2020-06-15T19:30:48.000000+00:00 app[postgres.10197]: [PINK] [25-1]  sql_error_code = 00000 LOG:  duration: 0.044 ms
2020-06-15T19:30:48.000000+00:00 app[postgres.10197]: [PINK] [26-1]  sql_error_code = 00000 LOG:  duration: 0.163 ms  parse s2: SELECT "public"."books"."id", "public"."books"."name", "public"."books"."shelf_id" FROM "public"."books" WHERE "public"."books"."id" IN ($1) OFFSET $2
2020-06-15T19:30:48.000000+00:00 app[postgres.10197]: [PINK] [27-1]  sql_error_code = 00000 LOG:  duration: 0.263 ms  bind s2: SELECT "public"."books"."id", "public"."books"."name", "public"."books"."shelf_id" FROM "public"."books" WHERE "public"."books"."id" IN ($1) OFFSET $2
2020-06-15T19:30:48.000000+00:00 app[postgres.10197]: [PINK] [27-2]  sql_error_code = 00000 DETAIL:  parameters: $1 = '61', $2 = '0'
2020-06-15T19:30:48.000000+00:00 app[postgres.10197]: [PINK] [28-1]  sql_error_code = 00000 LOG:  execute s2: SELECT "public"."books"."id", "public"."books"."name", "public"."books"."shelf_id" FROM "public"."books" WHERE "public"."books"."id" IN ($1) OFFSET $2
2020-06-15T19:30:48.000000+00:00 app[postgres.10197]: [PINK] [28-2]  sql_error_code = 00000 DETAIL:  parameters: $1 = '61', $2 = '0'
2020-06-15T19:30:48.000000+00:00 app[postgres.10197]: [PINK] [29-1]  sql_error_code = 00000 LOG:  duration: 0.045 ms
2020-06-15T19:30:48.000000+00:00 app[postgres.10197]: [PINK] [30-1]  sql_error_code = 00000 LOG:  duration: 0.110 ms  parse s3: SELECT "public"."shelves"."id", "public"."shelves"."name" FROM "public"."shelves" WHERE "public"."shelves"."id" IN ($1) OFFSET $2
2020-06-15T19:30:48.000000+00:00 app[postgres.10197]: [PINK] [31-1]  sql_error_code = 00000 LOG:  duration: 0.154 ms  bind s3: SELECT "public"."shelves"."id", "public"."shelves"."name" FROM "public"."shelves" WHERE "public"."shelves"."id" IN ($1) OFFSET $2
2020-06-15T19:30:48.000000+00:00 app[postgres.10197]: [PINK] [31-2]  sql_error_code = 00000 DETAIL:  parameters: $1 = '13', $2 = '0'
2020-06-15T19:30:48.000000+00:00 app[postgres.10197]: [PINK] [32-1]  sql_error_code = 00000 LOG:  execute s3: SELECT "public"."shelves"."id", "public"."shelves"."name" FROM "public"."shelves" WHERE "public"."shelves"."id" IN ($1) OFFSET $2
2020-06-15T19:30:48.000000+00:00 app[postgres.10197]: [PINK] [32-2]  sql_error_code = 00000 DETAIL:  parameters: $1 = '13', $2 = '0'
2020-06-15T19:30:48.000000+00:00 app[postgres.10197]: [PINK] [33-1]  sql_error_code = 00000 LOG:  duration: 0.033 ms
2020-06-15T19:30:48.000000+00:00 app[postgres.10197]: [PINK] [34-1]  sql_error_code = 00000 LOG:  duration: 0.132 ms  parse s4: SELECT "public"."users"."id", "public"."users"."name", "public"."users"."first_name", "public"."users"."last_name" FROM "public"."users" WHERE "public"."users"."id" IN ($1) OFFSET $2
2020-06-15T19:30:48.000000+00:00 app[postgres.10197]: [PINK] [35-1]  sql_error_code = 00000 LOG:  duration: 0.205 ms  bind s4: SELECT "public"."users"."id", "public"."users"."name", "public"."users"."first_name", "public"."users"."last_name" FROM "public"."users" WHERE "public"."users"."id" IN ($1) OFFSET $2
2020-06-15T19:30:48.000000+00:00 app[postgres.10197]: [PINK] [35-2]  sql_error_code = 00000 DETAIL:  parameters: $1 = '61', $2 = '0'
2020-06-15T19:30:48.000000+00:00 app[postgres.10197]: [PINK] [36-1]  sql_error_code = 00000 LOG:  execute s4: SELECT "public"."users"."id", "public"."users"."name", "public"."users"."first_name", "public"."users"."last_name" FROM "public"."users" WHERE "public"."users"."id" IN ($1) OFFSET $2
2020-06-15T19:30:48.000000+00:00 app[postgres.10197]: [PINK] [36-2]  sql_error_code = 00000 DETAIL:  parameters: $1 = '61', $2 = '0'
2020-06-15T19:30:48.000000+00:00 app[postgres.10197]: [PINK] [37-1]  sql_error_code = 00000 LOG:  duration: 0.025 ms
```

**Comment by thesunny** [comment] 2020-06-15 19:44
@janpio 

Based on the log, Prisma is looking for a `users.id` in `61` which I can confirm does not exist in the database. This explains the error `PANIC: Application logic invariant error: received null value for field last_sent_user which may not be null`

Prisma appears to be reusing the id from `books.id` which is `61` and which I can confirm is the correct id and that it exists.

I can also confirm that inside the database, the `last_sent_by` value is `13` and not `61`.

**Comment by janpio** [comment] 2020-06-15 21:07
> Can you maybe a dump of your SQL with the data that is causing this? Then it would be simple for us to reproduce.

**Comment by thesunny** [comment] 2020-06-15 23:43
@janpio 

The logs I in the previous post includes the SQL and the input data. Scroll to the right to see them.

It does not show the result data because I don't know how to make that work on Heroku but you can see from the SQL query and input data where the error comes from.

To break it down, this query is run:

```ts
  await prisma.book_share_email_invitations.findOne({
    select: {
      id: true,
      book_id: true,
      book: {
        select: {
          id: true,
          name: true,
          shelf: { select: { id: true, name: true } },
        },
      },
      email: true,
      permission: true,
      // vvv This is the problematic part
      last_sent_user: {
        select: {
          id: true,
          name: true,
          first_name: true,
          last_name: true,
        },
      },
    },
    where: { auth_token },
  })
```

From there, this query is run:

```sql
SELECT "public"."book_share_email_invitations"."id", 
       "public"."book_share_email_invitations"."book_id", 
       "public"."book_share_email_invitations"."email", 
       "public"."book_share_email_invitations"."permission", 
       "public"."book_share_email_invitations"."book_id", 
       "public"."book_share_email_invitations"."last_sent_by" 
FROM   "public"."book_share_email_invitations" 
WHERE  "public"."book_share_email_invitations"."auth_token" = $1 
LIMIT  $2 offset $3 
DETAIL:  parameters: $1 = 'ZxgbGRDBJDRIhcpLrMFWh', $2 = '1', $3 = '0'
```

We can see that some time after that, the `books` which is specified as a nested select in the query is selected:

```sql
SELECT "public"."books"."id", 
       "public"."books"."name", 
       "public"."books"."shelf_id" 
FROM   "public"."books" 
WHERE  "public"."books"."id" IN ($1) offset $2
DETAIL:PARAMETERS: $1 = '61', 
       $2 = '0'
```

In this query, it can be seen that the `id` parameters is `61`. This is the correct return value as can be seen in the database screenshot here:

![image](https://user-images.githubusercontent.com/469587/84699348-3447b280-af06-11ea-80d6-9de20ee83800.png)

Then later still, we see this query being executed against the `users` table which is the join to `last_sent_user`:

```sql
S4:SELECT "public"."users"."id", 
       "public"."users"."name", 
       "public"."users"."first_name", 
       "public"."users"."last_name" 
FROM   "public"."users" 
WHERE  "public"."users"."id" IN ($1) offset $2
DETAIL:PARAMETERS: $1 = '61', 
       $2 = '0'
```

The issue with this query, however, is that it is using the value `61` in its where clause but that is the value for `book`.

Again, looking at the data in the database:

[image](https://user-images.githubusercontent.com/469587/84699348-3447b280-af06-11ea-80d6-9de20ee83800.png)

We can see that the `last_sent_by` column has the value `13`. So somewhere during this query, the value from `book_id` was being used instead of the value from `last_sent_by`.

For additional clarity, the relation `last_sent_user` connects to the `users` table through the column `last_sent_by` as can be seen in the Prisma schema:

```graphql
model book_share_email_invitations {
  auth_token   String @unique
  book_id      Int
  email        String
  id           Int    @default(autoincrement()) @id
  last_sent_by Int
  permission   Int
  // normalized (singularized)
  book        books  @relation(fields: [book_id], references: [id])
  // normalized (singularized)
  last_sent_user        users  @relation(fields: [last_sent_by], references: [id])

  @@index([book_id], name: "book_share_email_invitations_book_id_index")
  @@unique([book_id, email], name: "book_share_email_invitations_book_id_email_unique")
}
```

**Comment by janpio** [comment] 2020-06-16 14:59
Can you please export the SQL database schema and the data in it into a .sql file so we can recreate your database ourselves and run the code you provided on that?

**Comment by thesunny** [comment] 2020-06-16 15:25
I will try to recreate this in a way that is transportable. For clarity, the code works on my Mac at the moment. My last deploy to Heroku did not but I changed the app to not make that query.

Reproducibility is important to bug fixes. It’s just inconsistent in how it gets to the broken state and I’m unclear how it got into that state. Any insight on things I can try?

It **might** be related to upgrading. I feel like it worked before and then started failing after an upgrade. On the Mac, I fixed the issue by removing then adding @prisma/client. On Heroku, it rebuilds each time I deploy and it continued to fail after a redeploy. however, I wonder if it’s a caching issue in their build process.

I remember reading that prisma uses a . file of some sort in newer versions in node_modules and I wonder if that is playing a part.

**Comment by janpio** [comment] 2020-06-16 16:09
If you can give us a SQL file with the schema and some data we can totally try to reproduce this ourselves - maybe it already works on the first try with the code snippets you provided above.

**Comment by thesunny** [comment] 2020-06-19 23:18
@janpio How should I send the file to you? I have it ready.

**Comment by pantharshit00** [comment] 2020-06-20 04:52
@thesunny You can email it to "schemas@prisma.io". If you want us to sign an NDA, we can also do that.

**Comment by thesunny** [comment] 2020-06-20 23:25
Done. Let me know if there are any issues with it.

**Comment by pantharshit00** [comment] 2020-06-24 10:44
@thesunny I restored the pg_dump that you have sent but it looks like it is missing some data. The query posted here is for `book_share_email_invitations` but the restore doesn't have that model. 

![image](https://user-images.githubusercontent.com/22195362/85541057-48da2800-b635-11ea-9bb1-e86bbe7a68ac.png)

Can you please send me a complete data? Also, I would prefer it to be a a simple `pg_dump` with `-Fc` flags as that export it in a custom format which is not very convenient to modify if I want to change the roles.

https://www.postgresql.org/docs/9.1/backup-dump.html


Also, as always, try with the latest dev version once to make sure if this was not already addressed in some other form.

**Comment by thesunny** [comment] 2020-06-24 17:01
Oh, my apologies. I used the dump feature in Heroku which I don't have much experience with.

I will try again.

**Comment by pantharshit00** [comment] 2020-06-26 06:40
No problems at all. Take your time :)

**Comment by thesunny** [comment] 2020-07-01 01:06
@pantharshit00 @janpio 

I resent the file using `pg_dump` as requested. Note that I mistakenly read that you wanted it WITH the `-Fc` flag so the first version I sent you is wrong. I then sent the correct version in a follow up email.

**Comment by pantharshit00** [comment] 2020-07-02 17:49
@thesunny I was unable to reproduce the error:
![image](https://user-images.githubusercontent.com/22195362/86393103-2c379300-bcba-11ea-93f3-bc5a9de53789.png)


I used the following code:
```ts
  const data = await prisma.book_share_email_invitations.findOne({
    select: {
      id: true,
      book_id: true,
      book: {
        select: {
          id: true,
          name: true,
          shelf: { select: { id: true, name: true } },
        },
      },
      email: true,
      permission: true,
      // vvv this is the problematic part
      last_sent_user: {
        select: {
          id: true,
          name: true,
          first_name: true,
          last_name: true,
        },
      },
    },
    where: { auth_token: "nqdHjAAAlYdB-gIBFZon5" },
  });
```


I used version:
```
@prisma/cli          : 2.1.3
Current platform     : darwin
Query Engine         : query-engine 363f5a521d6b06543e53d134652a0037a3096d41 (at /Users/harshit/code/reproductions/issue-2754/node_modules/@prisma/cli/query-engine-darwin)
Migration Engine     : migration-engine-cli 363f5a521d6b06543e53d134652a0037a3096d41 (at /Users/harshit/code/reproductions/issue-2754/node_modules/@prisma/cli/migration-engine-darwin)
Introspection Engine : introspection-core 363f5a521d6b06543e53d134652a0037a3096d41 (at /Users/harshit/code/reproductions/issue-2754/node_modules/@prisma/cli/introspection-engine-darwin)
Format Binary        : prisma-fmt 363f5a521d6b06543e53d134652a0037a3096d41 (at /Users/harshit/code/reproductions/issue-2754/node_modules/@prisma/cli/prisma-fmt-darwin)
```

Can you please try again with the latest version? :pray:

**Comment by thesunny** [comment] 2020-07-03 20:49
I'm afraid the bug still exists. Here is the relevant code. You can see my workaround which I commented out in there as well.

```ts
async function getInvitation(
  { auth_token }: { auth_token: string },
  { prisma }: API.Context
) {
  const book_share_email_invitation = await prisma.book_share_email_invitations.findOne(
    {
      select: {
        id: true,
        book_id: true,
        book: {
          select: {
            id: true,
            name: true,
            shelf: { select: { id: true, name: true } },
          },
        },
        email: true,
        permission: true,
        // last_sent_by: true,
        last_sent_user: {
          select: {
            id: true,
            name: true,
            first_name: true,
            last_name: true,
          },
        },
      },
      where: { auth_token },
    }
  )
  console.log(book_share_email_invitation)
  if (book_share_email_invitation == null) return null
  // const last_sent_user = await prisma.users.findOne({
  //   select: {
  //     id: true,
  //     name: true,
  //     first_name: true,
  //     last_name: true,
  //   },
  //   where: { id: book_share_email_invitation.last_sent_by },
  // })
  // if (last_sent_user == null)
  //   throw new Error(`User not found for last_sent_by should not happen`)
  return Object.assign(book_share_email_invitation, {
    last_sent_user: book_share_email_invitation.last_sent_user,
  })
}
```

And here is the error message:

```
Error at path "api/pages/share/book/[auth_token].ts" on method "entry":
Invalid `prisma.book_share_email_invitations.findOne()` invocation in
/Users/sunnyhirai/Projects/airshelf/api/pages/share/book/[auth_token].ts:11:81

   7 async function getInvitation(
   8   { auth_token }: { auth_token: string },
   9   { prisma }: API.Context
  10 ) {
→ 11   const book_share_email_invitation = await prisma.book_share_email_invitations.findOne
  PANIC: Application logic invariant error: received null value for field last_sent_user which may not be null

This is a non-recoverable error which probably happens when the Prisma Query Engine has a panic.
```

**Comment by thesunny** [comment] 2020-07-03 20:56
A few extra notes:

- This error message came from my Mac where the error, previously, had gone away when I removed then added @prisma/client
- The error also appears on Heroku so it appears not to be a platform issue
- I removed then added @prisma/client on the mac and this time, it did not resolve the issue

This feels like an important bug as it speaks to reliability. I may be willing to have you virtually come into my system while I watch in order for you to get a better understanding of the issue.

**Comment by pantharshit00** [comment] 2020-07-07 22:07
Hm, can you tell me which auth_token from the data you sent me triggering this? I can try again.

**Comment by janpio** [comment] 2020-09-02 02:23
Ping @thesunny: Please see Harshit's last follow up.

**Comment by janpio** [comment] 2021-03-23 19:14
Happy to open this again if we get more information.

**Closed by janpio** 2021-03-23 19:14 UTC
Labels: bug/0-needs-info, kind/bug, status/needs-action

**Comment by lumgashi** [comment] 2023-07-31 09:23
I just encountered this error, I wanted to query a table with 'currentStatus' using groupBy, but in my db it was saved as null instead of a string, so as soon as I changed the value in my db, the error was gone and query was made.
