### ISSUE TITLE
Production Schema Is Unknown

### ISSUE THREAD

**Issue by Ryanmwb** [prisma/prisma#3247] opened 2020-08-09 01:22 UTC
## Problem
I am about 200 hours into my project and haven't had any issues until just this morning.  After adding new schema, Prisma on the production side doesn't recognize the new schema. 
<img width="544" alt="Screen Shot 2020-08-08 at 9 06 29 PM" src="https://user-images.githubusercontent.com/29359977/89722852-c7f4a700-d9bc-11ea-9bb3-b5e62b52d112.png">
![Screen Shot 2020-08-08 at 9 06 40 PM](https://user-images.githubusercontent.com/29359977/89722859-e5c20c00-d9bc-11ea-8376-27f3ce13af0f.png)

 I figured something was missing in the production schema.prisma file, but after comparing it to what I have locally they match.  
![Screen Shot 2020-08-08 at 9 07 31 PM](https://user-images.githubusercontent.com/29359977/89722864-eb1f5680-d9bc-11ea-8919-1de63d578d35.png)

After trying to move the data onto the user object, this is the error I got from production (heroku)
<img width="773" alt="Screen Shot 2020-08-08 at 10 06 16 PM" src="https://user-images.githubusercontent.com/29359977/89723411-c8447080-d9c3-11ea-8e12-18c8d924b15b.png">

## Things I've tried

1. Diff checking production and local schema
2. Rolling back migrations
3. Creating a different table 
4. Querying the data multiple ways
5. Delete and reinstall node_modules
6. Screaming into a pillow

## Versions
@prisma/cli 2.4.1
@prisma/client 2.0.0

**Comment by janpio** [comment] 2020-08-09 12:46
Checking the obvious things:
- Database tables are present?
- You did run `npx prisma generate` to regenerate your Prisma Client for that schema?

I would also suggest to update your `@prisma/client` to the newest version 2.4.1 to match your CLI.

**Comment by Ryanmwb** [comment] 2020-08-09 20:45
Yep, DB was present.  I ended up deleting the production project and rebuilding it which fixed the problem.  But I still don't know what was causing the issue since `/prisma/schema.prisma` and `/node_modules/.prisma/client/schema.prisma` both had those "unknown" fields listed.

**Comment by pantharshit00** [comment] 2020-08-10 14:33
I am glad you were able to fix the problem. Since we don't know the cause here it is very hard for me to reproduce this. 

If this is fixed for now, I suggest we close the issue.

**Closed** 2020-08-10 21:01 UTC
