### ISSUE TITLE
executeRaw error: PrismaClientKnownRequestError: Raw query failed. Code: `N/A`. Message: `N/A` when executing successful create queries

### ISSUE THREAD

**Issue by AssisrMatheus** [prisma/prisma#2867] opened 2020-06-26 15:27 UTC
## Bug description
If a query that does not return results is ran with `db.executeRaw`, it throws the following error:
```
PrismaClientKnownRequestError: Raw query failed. Code: `N/A`. Message: `N/A`
    at PrismaClientFetcher.request (D:\dev\perimetre\export-connect-backend\node_modules\@prisma\client\src\runtime\getPrismaClient.ts:902:15)
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {
  code: 'P2010',
  meta: { code: 'N/A', message: 'N/A' }
}
```

But even thought I get an exception, the query still runs successfully and the database is modified correctly.

An example of the query that It's being ran:
```sql
CREATE TABLE IF NOT EXISTS `MyTable` (
  `id` int NOT NULL AUTO_INCREMENT,
  `name` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `slug` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `MyTable.slug` (`slug`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
```

This also happenned when running a select query with `queryRaw` and the table did not have any data. I got the error instead of getting an undefined result or an empty array.

## How to reproduce
1. Make a simple create query like the one in the example above
2. Execute it with `db.executeRaw`

## Expected behavior

The expected behaviour should be that no exception is thrown since the operation worked successfully

## Environment & setup

- OS: Windows 10
- Database: Mysql 8
- Prisma version: 2.1.3
- Node.js version: v12.18.0

**Comment by pantharshit00** [comment] 2020-06-30 08:55
I am unable to reproduce this: 
![image](https://user-images.githubusercontent.com/22195362/86105835-757ebb80-badd-11ea-938a-b056704b3cc1.png)

Version used: 
```
@prisma/cli          : 2.2.0-dev.19
Current platform     : darwin
Query Engine         : query-engine cb47e060d4a557e1e7870f50fc7b3c014f278114 (at /Users/harshit/code/reproductions/issue-2867/node_modules/@prisma/cli/query-engine-darwin)
Migration Engine     : migration-engine-cli cb47e060d4a557e1e7870f50fc7b3c014f278114 (at /Users/harshit/code/reproductions/issue-2867/node_modules/@prisma/cli/migration-engine-darwin)
Introspection Engine : introspection-core cb47e060d4a557e1e7870f50fc7b3c014f278114 (at /Users/harshit/code/reproductions/issue-2867/node_modules/@prisma/cli/introspection-engine-darwin)
Format Binary        : prisma-fmt cb47e060d4a557e1e7870f50fc7b3c014f278114 (at /Users/harshit/code/reproductions/issue-2867/node_modules/@prisma/cli/prisma-fmt-darwin)
```

Code used for reproduction:
```ts
import { PrismaClient } from "@prisma/client";

async function main() {
  const client = new PrismaClient({
    log: ["query"],
  });

  const data = await client.executeRaw(
    "CREATE TABLE IF NOT EXISTS `MyTable` ( `id` int NOT NULL AUTO_INCREMENT, `name` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL, `slug` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,PRIMARY KEY (`id`), UNIQUE KEY `MyTable.slug` (`slug`) ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;"
  );

  console.log(data);
  client.disconnect();
}

main();
```


Can you please share the exact code that you used for reproduction here?

**Comment by pantharshit00** [comment] 2020-06-30 09:27
Also, enable the query logging by setting the following option in the Prisma client constructor: 

```js
const prisma = new PrismaClient({
  log: ["query"]
})
```

**Comment by janpio** [comment] 2020-09-02 02:05
Hey @AssisrMatheus, could you have another look at this after @pantharshit00 could not reproduce this? With a newer Prisma version this should definitely not happen any more. If you can not reproduce this, we would like to close the issue (or you can do that for us).

**Comment by cclaflin89** [comment] 2020-10-12 09:12
The issue still occurs in prisma cli 2.8.1

**Comment by janpio** [comment] 2020-10-12 12:36
Nice @cclaflin89 - can you maybe give us all information required to reproduce this? Would love to have a reproduction we can hand over to our engineers to fix.

**Comment by guotie** [comment] 2020-12-30 09:44
any solution?

I have encounter this problem too.

**Comment by pantharshit00** [comment] 2021-01-01 12:50
@guotie Can you please share the query which you are running?

**Comment by guotie** [comment] 2021-01-01 13:25
maybe it is my db's problem, thank you.

**Comment by janpio** [comment] 2021-03-23 19:23
I am going to close this now. Happy to take a look again if we get more information.

**Closed by janpio** 2021-03-23 19:23 UTC
Labels: bug/0-needs-info, kind/bug, topic: raw

**Comment by janpio** [comment] 2022-03-11 08:26
Please open a new discussion or bug report @mjpaquet. Thanks.

**Comment by eldoncosta1** [comment] 2022-05-20 12:55
remove quotes inside SQL command, leave just

`
AND YEAR(date_facture) = ${annee}
AND MONTH(date_facture) = ${mois}
AND MONTH(date_facture) = ${mois}
`
