### ISSUE TITLE
Error: PrismaClient is unable to be run in the browser.

### ISSUE THREAD

**Issue by PublicTrades** [prisma/prisma#19944] opened 2023-06-24 06:21 UTC
Hello all,
I am having the same issue, and not running PrismaClient on the frontend. I have a file in the `/api/file`, and when I tried making a POST request I got this error:
```Server Error
Error: PrismaClient is unable to be run in the browser.
In case this error is unexpected for you, please report it in https://github.com/prisma/prisma/issues
```
I also got this message in the console: 
```
error - node_modules/.prisma/client/index-browser.js (169:0) @ <unknown>
error - PrismaClient is unable to be run in the browser.
In case this error is unexpected for you, please report it in https://github.com/prisma/prisma/issues
null
```
Is there a solution to this issue?

<img width="519" alt="Screen Shot 2023-06-24 at 2 11 38 AM" src="https://github.com/prisma/prisma/assets/8324290/a1888e24-eebe-48ab-ad5f-f0e4708232c8" />

_Originally posted by @PublicTrades in https://github.com/prisma/prisma/issues/19500#issuecomment-1605283701_

**Comment by janpio** [comment] 2023-06-24 08:37
Duplicate of https://github.com/prisma/prisma/issues/19500#issuecomment-1605283701

**Closed by janpio** 2023-06-24 08:37 UTC

**Comment by PublicTrades** [comment] 2023-06-24 09:24
@janpio - Don't close my issue unless you have an answer for me. First off, my issue is not a duplicate of [#19500](https://github.com/prisma/prisma/issues/19500) - Issue with that was PrismaClient was NOT setup on the server side - a simple google would provide them an answer to resolve that issue. I have it set up on the server side, and was still throwing error. I couldn't find any way to resolve it so, I'd appreciate you leave this ticket the way it is so I can get folks who can help point me in the right direction, it is NOT  duplicate of that other one. Thank you.
P.S. If you gonna do shit like that at least provide your two cents, Just don't hop on the machine closing ticket left and right.

**Comment by janpio** [comment] 2023-06-24 10:28
Then don't post the exact same message multiple times, especially not by creating an issue by just putting the comment into it. Doing so means that different people will see your message in multiple places, and potentially do double the work.

If you think your problem is not related to #19500, then please delete your comment there and open a new issue and fill in the full bug issue template and provide all the information it asks for. Otherwise we will not be able to help you.

Also: Please watch your tone. Your message here is inappropriate and we will not accept that around here. If you want help, be nice and follow the rules. Thank you.

**Comment by PublicTrades** [comment] 2023-06-24 18:41
Little @janpio got a little sensitive huh ‘Mr. Prisma’, couldn’t take punch - So what I thought the other thread’s was  directly related to my issue.
Have at it if it makes you feel better, close the issue, better yet, shut down GitHub.
