### ISSUE TITLE
`createMany` is a very worth considering for testing in sqlite development mode

### ISSUE THREAD

**Issue by LaicZhang** [prisma/prisma#21206] opened 2023-09-24 09:20 UTC
## Problem
such as #11507 ，I browsed some past issues, but I still don’t know why I didn’t complete the function for testing.

## Suggested solution

add a `createMany` function for sqlite developer.

**Comment by janpio** [comment] 2023-09-24 17:02
Duplicate of https://github.com/prisma/prisma/issues/10710?

**Comment by LaicZhang** [comment] 2023-09-25 02:30
> Duplicate of #10710?

I mean, just need a method for testing, not not provide it at all. There are no performance requirements for this method.

just like
```
function create(prisma, data){
prisma.post.create({ data })
}

function createMany(prisma, datas){
for (const data of datas) {
  inserts.push(prisma.post.create({ data }))
}
await prisma.$transaction(inserts)
}
```

**Comment by Jolg42** [comment] 2023-09-25 13:47
Thanks @LaicZhang, I'll close this as a duplicate of https://github.com/prisma/prisma/issues/10710 as this suggestion looks like a workaround or alternative suggestion for it.

If you want to have a custom `createMany` function you could check [Query Client Extensions](https://www.prisma.io/docs/concepts/components/prisma-client/client-extensions/query)

**Closed by Jolg42** 2023-09-25 13:47 UTC
