### ISSUE TITLE
called `Option::unwrap()` on a `None` value

### ISSUE THREAD

**Issue by enjidev** [prisma/prisma#17283] opened 2023-01-13 03:35 UTC
Hi Prisma Team! My Prisma Client just crashed. This is the report:
## Versions

| Name            | Version            |
|-----------------|--------------------|
| Node            | v18.12.1           | 
| OS              | windows            |
| Prisma Client   | 4.8.1              |
| Query Engine    | d6e67a83f971b175a593ccc12e15c4a757f93ffe|
| Database        | mongodb            |

## Logs
```
yStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
```

## Client Snippet
```ts
await prisma.reaction.groupBy({
  by: ['section', 'type'],
  _sum: {
    count: true,
  },
  where: {
    content: {
      slug,
    },
  },
});
```

## Schema
```prisma
model ContentMeta {
  id String @id @default(auto()) @map("_id") @db.ObjectId

  slug      String     @unique
  reactions Reaction[]
  createdAt DateTime   @default(now())
}

model Reaction {
  id String @id @default(auto()) @map("_id") @db.ObjectId

  count     Int?          @default(1)
  type      ReactionType? @default(CLAPPING)
  section   String?
  createdAt DateTime      @default(now())

  contentId String      @db.ObjectId
  content   ContentMeta @relation(fields: [contentId], references: [id], onDelete: Cascade)
}

enum ReactionType {
  CLAPPING
  THINKING
  AMAZED
}
```

## Prisma Engine Query
```
{"X":{}}
```

**Comment by enjidev** [comment] 2023-01-13 03:59
Adding this to the WHERE clause has fixed the issue and now everything is working fine.

```ts
section: {
  not: null,
},
```

**Comment by laplab** [comment] 2024-03-19 12:25
Thank you for reporting the issue @enjidev! Unfortunately, I was not able to reproduce it on the most recent version of Prisma - 5.11.0. I used the following script:

```typescript
import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient({ log: ["query", "info", "error", "warn"] });

async function main() {
    await prisma.reaction.create({
        data: {
            section: "testSection",
            content: {
                create: {
                    slug: "testSlug"
                }
            }
        }
    });

    await prisma.reaction.groupBy({
        by: ['section', 'type'],
        _sum: {
          count: true,
        },
        where: {
          content: {
            slug: "testSlug",
          },
        },
      });
}

main()
  .catch((e) => {
    throw e;
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
```

Can you please confirm if the issue still reproduces for you on Prisma 5.11.0? If so, can you please provide:
1. `npx prisma version`
2. Version of MongoDB you are using
3. Full query you are issuing (without any variables in it)
4. Minimal dataset that the issue is reproducible on

**Comment by laplab** [comment] 2024-04-02 09:13
Hey @enjidev, we are going to close this issue for now, as we do not have enough information to reproduce it. If you continue experiencing the same problem, please feel free to open a new issue with the details requested above.

**Closed by laplab** 2024-04-02 09:13 UTC
Labels: bug/1-unconfirmed, kind/bug, topic: prisma-client, team/client, topic: groupBy(), topic: rust panic, topic: mongodb, topic: unwrap error
