### ISSUE TITLE
Error with npm resolution for dev package

### ISSUE THREAD

**Issue by albertoperdomo** [prisma/prisma#5346] opened 2021-01-29 12:28 UTC
Having trouble with npm resolution and dev packages.

package.json
```
{
  "name": "script",
  "license": "MIT",
  "devDependencies": {
    "prisma": "^2.16.0-dev.37",
    "ts-node": "9.1.1",
    "typescript": "4.1.3"
  },
  "scripts": {
    "dev": "ts-node ./script.ts"
  },
  "dependencies": {
    "@prisma/client": "^2.16.0-dev.37"
  },
  "engines": {
    "node": ">=10.0.0"
  }
}
```
Expected package-lock.json (with 37 being the latest dev release available):
```
{
  "name": "script",
  "requires": true,
  "lockfileVersion": 1,
  "dependencies": {
    "@prisma/client": {
      "version": "2.16.0-dev.37",
      "resolved": "https://registry.npmjs.org/@prisma/client/-/client-2.16.0-dev.37.tgz",
      "integrity": "sha512-kU+SBDH5/XVnHboj32g2AgMS47dAuvjHwOxFsAjx0TKB3Xwd61aO8TIxxXdfeSd0cz6zfa8MTyUyFE3gyVwwrA==",
      "requires": {
        "@prisma/engines-version": "2.16.0-27.16fd0a533346115ecd4e03b25f1cca9dac5f5cff"
      }
    },
    "@prisma/engines": {
      "version": "2.16.0-27.16fd0a533346115ecd4e03b25f1cca9dac5f5cff",
      "resolved": "https://registry.npmjs.org/@prisma/engines/-/engines-2.16.0-27.16fd0a533346115ecd4e03b25f1cca9dac5f5cff.tgz",
      "integrity": "sha512-2YYk9HJqKpaPdyTVRZGYmGZwSwYQucW+tfeCHcHA9hQhK8OquP0JAHkAkIS1NI3zbU9nHMPYWgMIzpfNk/NGBg==",
      "dev": true
    },
    "@prisma/engines-version": {
      "version": "2.16.0-27.16fd0a533346115ecd4e03b25f1cca9dac5f5cff",
      "resolved": "https://registry.npmjs.org/@prisma/engines-version/-/engines-version-2.16.0-27.16fd0a533346115ecd4e03b25f1cca9dac5f5cff.tgz",
      "integrity": "sha512-MgeVfVOx6bD7z408VpWKvt1qBguwq7l5nJ05UUUoK827dxZ3yxv7z6aKAGXOrskBxrQGYioHX2eaVJ/E6VyPWw=="
    },
    "arg": {
      "version": "4.1.3",
      "resolved": "https://registry.npmjs.org/arg/-/arg-4.1.3.tgz",
      "integrity": "sha512-58S9QDqG0Xx27YwPSt9fJxivjYl432YCwfDMfZ+71RAqUrZef7LrKQZ3LHLOwCS4FLNBplP533Zx895SeOCHvA==",
      "dev": true
    },
    "buffer-from": {
      "version": "1.1.1",
      "resolved": "https://registry.npmjs.org/buffer-from/-/buffer-from-1.1.1.tgz",
      "integrity": "sha512-MQcXEUbCKtEo7bhqEs6560Hyd4XaovZlO/k9V3hjVUF/zwW7KBVdSK4gIt/bzwS9MbR5qob+F5jusZsb0YQK2A==",
      "dev": true
    },
    "create-require": {
      "version": "1.1.1",
      "resolved": "https://registry.npmjs.org/create-require/-/create-require-1.1.1.tgz",
      "integrity": "sha512-dcKFX3jn0MpIaXjisoRvexIJVEKzaq7z2rZKxf+MSr9TkdmHmsU4m2lcLojrj/FHl8mk5VxMmYA+ftRkP/3oKQ==",
      "dev": true
    },
    "diff": {
      "version": "4.0.2",
      "resolved": "https://registry.npmjs.org/diff/-/diff-4.0.2.tgz",
      "integrity": "sha512-58lmxKSA4BNyLz+HHMUzlOEpg09FV+ev6ZMe3vJihgdxzgcwZ8VoEEPmALCZG9LmqfVoNMMKpttIYTVG6uDY7A==",
      "dev": true
    },
    "make-error": {
      "version": "1.3.6",
      "resolved": "https://registry.npmjs.org/make-error/-/make-error-1.3.6.tgz",
      "integrity": "sha512-s8UhlNe7vPKomQhC1qFelMokr/Sc3AgNbso3n74mVPA5LTZwkB9NlXf4XPamLxJE8h0gh73rM94xvwRT2CVInw==",
      "dev": true
    },
    "prisma": {
      "version": "2.16.0-dev.37",
      "resolved": "https://registry.npmjs.org/prisma/-/prisma-2.16.0-dev.37.tgz",
      "integrity": "sha512-mifd4PRbvbqorFrbGWGKX8NQKjyvvuNW3BZseh/1yXIbns1wrXdPTZuclYUtBFLkisttt7xCHHHypB3TlHrjmA==",
      "dev": true,
      "requires": {
        "@prisma/engines": "2.16.0-27.16fd0a533346115ecd4e03b25f1cca9dac5f5cff"
      }
    },
    "source-map": {
      "version": "0.6.1",
      "resolved": "https://registry.npmjs.org/source-map/-/source-map-0.6.1.tgz",
      "integrity": "sha512-UjgapumWlbMhkBgzT7Ykc5YXUT46F0iKu8SGXq0bcwP5dz/h0Plj6enJqjz1Zbq2l5WaqYnrVbwWOWMyF3F47g==",
      "dev": true
    },
    "source-map-support": {
      "version": "0.5.19",
      "resolved": "https://registry.npmjs.org/source-map-support/-/source-map-support-0.5.19.tgz",
      "integrity": "sha512-Wonm7zOCIJzBGQdB+thsPar0kYuCIzYvxZwlBa87yi/Mdjv7Tip2cyVbLj5o0cFPN4EVkuTwb3GDDyUx2DGnGw==",
      "dev": true,
      "requires": {
        "buffer-from": "^1.0.0",
        "source-map": "^0.6.0"
      }
    },
    "ts-node": {
      "version": "9.1.1",
      "resolved": "https://registry.npmjs.org/ts-node/-/ts-node-9.1.1.tgz",
      "integrity": "sha512-hPlt7ZACERQGf03M253ytLY3dHbGNGrAq9qIHWUY9XHYl1z7wYngSr3OQ5xmui8o2AaxsONxIzjafLUiWBo1Fg==",
      "dev": true,
      "requires": {
        "arg": "^4.1.0",
        "create-require": "^1.1.0",
        "diff": "^4.0.1",
        "make-error": "^1.1.1",
        "source-map-support": "^0.5.17",
        "yn": "3.1.1"
      }
    },
    "typescript": {
      "version": "4.1.3",
      "resolved": "https://registry.npmjs.org/typescript/-/typescript-4.1.3.tgz",
      "integrity": "sha512-B3ZIOf1IKeH2ixgHhj6la6xdwR9QrLC5d1VKeCSY4tvkqhF2eqd9O7txNlS0PO3GrBAFIdr3L1ndNwteUbZLYg==",
      "dev": true
    },
    "yn": {
      "version": "3.1.1",
      "resolved": "https://registry.npmjs.org/yn/-/yn-3.1.1.tgz",
      "integrity": "sha512-Ux4ygGWsu2c7isFWe8Yu1YluJmqVhxqK2cLXNQA5AcC3QfbGNpM7fu0Y8b/z16pXLnFxZYvWhd3fhBY9DLmC6Q==",
      "dev": true
    }
  }
}

```

Actual package-lock.json
```
{
  "name": "script",
  "requires": true,
  "lockfileVersion": 1,
  "dependencies": {
    "@prisma/client": {
      "version": "2.16.0-integration-prisma-renaming.1",
      "resolved": "https://registry.npmjs.org/@prisma/client/-/client-2.16.0-integration-prisma-renaming.1.tgz",
      "integrity": "sha512-KG4KzyaXCCrt7+paNG9NX0HJj+4PUA8QoBLJCvOEpYdLKAFnvjYZDbIO9dNBXKfOlBpqlLeAE9BMWTTqrVABrA==",
      "requires": {
        "@prisma/engines-version": "2.15.0-26.6c8b3ff8b9a910842e10127753e5ab9b411f9e03"
      }
    },
    "@prisma/engines": {
      "version": "2.16.0-27.16fd0a533346115ecd4e03b25f1cca9dac5f5cff",
      "resolved": "https://registry.npmjs.org/@prisma/engines/-/engines-2.16.0-27.16fd0a533346115ecd4e03b25f1cca9dac5f5cff.tgz",
      "integrity": "sha512-2YYk9HJqKpaPdyTVRZGYmGZwSwYQucW+tfeCHcHA9hQhK8OquP0JAHkAkIS1NI3zbU9nHMPYWgMIzpfNk/NGBg==",
      "dev": true
    },
    "@prisma/engines-version": {
      "version": "2.15.0-26.6c8b3ff8b9a910842e10127753e5ab9b411f9e03",
      "resolved": "https://registry.npmjs.org/@prisma/engines-version/-/engines-version-2.15.0-26.6c8b3ff8b9a910842e10127753e5ab9b411f9e03.tgz",
      "integrity": "sha512-JjJ5bIA/yLpvxdviaR0nygMDD/wCXG/ai7YRbDXNHY37QFqYDXHgG4Xun7Rv6LHaS6cKvzn0jMhe40m/EZEijw=="
    },
    "arg": {
      "version": "4.1.3",
      "resolved": "https://registry.npmjs.org/arg/-/arg-4.1.3.tgz",
      "integrity": "sha512-58S9QDqG0Xx27YwPSt9fJxivjYl432YCwfDMfZ+71RAqUrZef7LrKQZ3LHLOwCS4FLNBplP533Zx895SeOCHvA==",
      "dev": true
    },
    "buffer-from": {
      "version": "1.1.1",
      "resolved": "https://registry.npmjs.org/buffer-from/-/buffer-from-1.1.1.tgz",
      "integrity": "sha512-MQcXEUbCKtEo7bhqEs6560Hyd4XaovZlO/k9V3hjVUF/zwW7KBVdSK4gIt/bzwS9MbR5qob+F5jusZsb0YQK2A==",
      "dev": true
    },
    "create-require": {
      "version": "1.1.1",
      "resolved": "https://registry.npmjs.org/create-require/-/create-require-1.1.1.tgz",
      "integrity": "sha512-dcKFX3jn0MpIaXjisoRvexIJVEKzaq7z2rZKxf+MSr9TkdmHmsU4m2lcLojrj/FHl8mk5VxMmYA+ftRkP/3oKQ==",
      "dev": true
    },
    "diff": {
      "version": "4.0.2",
      "resolved": "https://registry.npmjs.org/diff/-/diff-4.0.2.tgz",
      "integrity": "sha512-58lmxKSA4BNyLz+HHMUzlOEpg09FV+ev6ZMe3vJihgdxzgcwZ8VoEEPmALCZG9LmqfVoNMMKpttIYTVG6uDY7A==",
      "dev": true
    },
    "make-error": {
      "version": "1.3.6",
      "resolved": "https://registry.npmjs.org/make-error/-/make-error-1.3.6.tgz",
      "integrity": "sha512-s8UhlNe7vPKomQhC1qFelMokr/Sc3AgNbso3n74mVPA5LTZwkB9NlXf4XPamLxJE8h0gh73rM94xvwRT2CVInw==",
      "dev": true
    },
    "prisma": {
      "version": "2.16.0-dev.37",
      "resolved": "https://registry.npmjs.org/prisma/-/prisma-2.16.0-dev.37.tgz",
      "integrity": "sha512-mifd4PRbvbqorFrbGWGKX8NQKjyvvuNW3BZseh/1yXIbns1wrXdPTZuclYUtBFLkisttt7xCHHHypB3TlHrjmA==",
      "dev": true,
      "requires": {
        "@prisma/engines": "2.16.0-27.16fd0a533346115ecd4e03b25f1cca9dac5f5cff"
      }
    },
    "source-map": {
      "version": "0.6.1",
      "resolved": "https://registry.npmjs.org/source-map/-/source-map-0.6.1.tgz",
      "integrity": "sha512-UjgapumWlbMhkBgzT7Ykc5YXUT46F0iKu8SGXq0bcwP5dz/h0Plj6enJqjz1Zbq2l5WaqYnrVbwWOWMyF3F47g==",
      "dev": true
    },
    "source-map-support": {
      "version": "0.5.19",
      "resolved": "https://registry.npmjs.org/source-map-support/-/source-map-support-0.5.19.tgz",
      "integrity": "sha512-Wonm7zOCIJzBGQdB+thsPar0kYuCIzYvxZwlBa87yi/Mdjv7Tip2cyVbLj5o0cFPN4EVkuTwb3GDDyUx2DGnGw==",
      "dev": true,
      "requires": {
        "buffer-from": "^1.0.0",
        "source-map": "^0.6.0"
      }
    },
    "ts-node": {
      "version": "9.1.1",
      "resolved": "https://registry.npmjs.org/ts-node/-/ts-node-9.1.1.tgz",
      "integrity": "sha512-hPlt7ZACERQGf03M253ytLY3dHbGNGrAq9qIHWUY9XHYl1z7wYngSr3OQ5xmui8o2AaxsONxIzjafLUiWBo1Fg==",
      "dev": true,
      "requires": {
        "arg": "^4.1.0",
        "create-require": "^1.1.0",
        "diff": "^4.0.1",
        "make-error": "^1.1.1",
        "source-map-support": "^0.5.17",
        "yn": "3.1.1"
      }
    },
    "typescript": {
      "version": "4.1.3",
      "resolved": "https://registry.npmjs.org/typescript/-/typescript-4.1.3.tgz",
      "integrity": "sha512-B3ZIOf1IKeH2ixgHhj6la6xdwR9QrLC5d1VKeCSY4tvkqhF2eqd9O7txNlS0PO3GrBAFIdr3L1ndNwteUbZLYg==",
      "dev": true
    },
    "yn": {
      "version": "3.1.1",
      "resolved": "https://registry.npmjs.org/yn/-/yn-3.1.1.tgz",
      "integrity": "sha512-Ux4ygGWsu2c7isFWe8Yu1YluJmqVhxqK2cLXNQA5AcC3QfbGNpM7fu0Y8b/z16pXLnFxZYvWhd3fhBY9DLmC6Q==",
      "dev": true
    }
  }
}
```

Current workaround available:

Pin the version in package.json

```
{
  "name": "script",
  "license": "MIT",
  "devDependencies": {
    "prisma": "2.16.0-dev.37",
    "ts-node": "9.1.1",
    "typescript": "4.1.3"
  },
  "scripts": {
    "dev": "ts-node ./script.ts"
  },
  "dependencies": {
    "@prisma/client": "2.16.0-dev.37"
  },
  "engines": {
    "node": ">=10.0.0"
  }
}

```

How to diagnose: Run `npx prisma -v`

The prisma version should be pinned to dev versions, not integration branches.

Before
```
Environment variables loaded from prisma/.env
prisma               : 2.16.0-dev.37
@prisma/client       : 2.16.0-integration-prisma-renaming.1
Current platform     : darwin
Query Engine         : query-engine 16fd0a533346115ecd4e03b25f1cca9dac5f5cff (at node_modules/@prisma/engines/query-engine-darwin)
Migration Engine     : migration-engine-cli 16fd0a533346115ecd4e03b25f1cca9dac5f5cff (at node_modules/@prisma/engines/migration-engine-darwin)
Introspection Engine : introspection-core 16fd0a533346115ecd4e03b25f1cca9dac5f5cff (at node_modules/@prisma/engines/introspection-engine-darwin)
Format Binary        : prisma-fmt 16fd0a533346115ecd4e03b25f1cca9dac5f5cff (at node_modules/@prisma/engines/prisma-fmt-darwin)
Studio               : 0.345.0
```

After
```
Environment variables loaded from prisma/.env
prisma               : 2.16.0-dev.37
@prisma/client       : 2.16.0-dev.37
Current platform     : darwin
Query Engine         : query-engine 16fd0a533346115ecd4e03b25f1cca9dac5f5cff (at node_modules/@prisma/engines/query-engine-darwin)
Migration Engine     : migration-engine-cli 16fd0a533346115ecd4e03b25f1cca9dac5f5cff (at node_modules/@prisma/engines/migration-engine-darwin)
Introspection Engine : introspection-core 16fd0a533346115ecd4e03b25f1cca9dac5f5cff (at node_modules/@prisma/engines/introspection-engine-darwin)
Format Binary        : prisma-fmt 16fd0a533346115ecd4e03b25f1cca9dac5f5cff (at node_modules/@prisma/engines/prisma-fmt-darwin)
Studio               : 0.345.0
```

**Comment by Jolg42** [comment] 2021-01-29 12:38
Note: dev versions are only for internal use.

**Comment by Jolg42** [comment] 2021-01-29 12:45
I guess it’s expected to work like that but we could potentially rename the integration version to avoid that behavior.

**Comment by janpio** [comment] 2021-01-29 13:16
Internal discussion about expected behavior: https://prisma-company.slack.com/archives/C9HRC5YTY/p1611924202053500?thread_ts=1611923573.051600&cid=C9HRC5YTY

**Comment by matthewmueller** [comment] 2021-02-22 15:43
To clarify this issue:

Running `npm install` on `^2.16.0-dev10` upgrades to `2.16.0-integration-prisma-renaming.1` because semver.

This is probably not what you want. We should consider renaming the integration version differently.

**Comment by matthewmueller** [comment] 2021-03-17 15:42
Next Steps:

- Ensure that dev doesn't get upgrade to integration tag (reformat the naming convention so semver doesn't auto-upgrade)

**Comment by janpio** [comment] 2023-05-16 16:35
Closing, as this is just how Npm works. We almost never run into it internally, so we should be fine.

**Closed by janpio** 2023-05-16 16:35 UTC
Labels: bug/2-confirmed, kind/bug, tech/typescript, status/needs-action, team/client
