### ISSUE TITLE
Error using onDelete: CASCADE for nested fields

### ISSUE THREAD

**Issue by Gazuntype** [prisma/prisma#4175] opened 2019-03-12 16:47 UTC
**Describe the bug**
When attempting to delete a node that is related to another node using onDelete: CASCADE, if the other node is related to yet another node, an error is thrown.
For example; there's are three nodes; A, B and C. A has a field of B and is related to be with onDelete:CASCADE. B has a field of C and is related with onDelete: CASCADE also.

When trying to delete A, since it is related to an instance of B with onDelete: CASCADE, it attempts to delete B. But it fails. Because B cannot be deleted due to its relation with C.

![](https://www.prisma.io/forum/uploads/default/original/2X/2/2a98c18fc250e2eac5285fd707ada076e2ed7ca8.png)
This is another example. (picture above)
Hence, when I try to delete a Hunt, since onDelete is set to Cascade, it should the associated Phase. But here’s when the problem arises. When it tries to delete the associated Phase, the relation between the Phase and its Interaction doesn’t allow the Phase to be deleted arising to the error:
“The change you are trying to make would violate the required relation ‘PhaseInteraction’ between Interaction and Phase”.
This is probably because the onDelete for the Phase isn’t triggered due to the fact that it was deleted by the onDelete for the Hunt, and not from a normal prisma delete.

**To Reproduce**
1. Create a datamodel with three nodes.
2. The first node should have a field of the type of the second node and should be related with onDelete: CASCADE
3. the second node should have a field of the type of the third node and should be related with onDelete: CASCADE
4. Try to delete the first node using maybe the Prisma Client.

**Expected behavior**
An error would be thrown saying that the second node could not be deleted because of its relation with the third one.

**Screenshots**

**Versions (please complete the following information):**
 - Connector: MySQL
 - Prisma Server: 1.24.0
 - `prisma` CLI: prisma/1.24.0
 - OS: Windows 10
 - other dependencies: `prisma-client`

**Comment by do4gr** [comment] 2019-03-14 13:21
I tried reproducing the issue with the following datamodel: 

```graphql
type UserA {
  id: ID! @unique
  name: String!
  userBs: [UserB!]! @relation(name: "AtoB", onDelete: CASCADE)
}

type UserB {
  id: ID! @unique
  name: String!
  userA: UserA! @relation(name: "AtoB", onDelete: SET_NULL)
  userC: UserC! @relation(name: "BtoC", onDelete: CASCADE)
}

type UserC {
  id: ID! @unique
  name: String!
  userB: UserB! @relation(name: "BtoC", onDelete: SET_NULL)
  userD: UserD! @relation(name: "CtoD", onDelete: CASCADE)
}

type UserD {
  id: ID! @unique
  name: String!
  userC: UserC! @relation(name: "CtoD", onDelete: SET_NULL)
 }
```

I created data with this mutation: 

```graphql
mutation a {
  createUserA(
    data: {
      name: "A"
      userBs: {
        create: [
          {
            name: "B1"
            userC: {
              create: 
                {
                  name: "C11"
                  userD: { create:  { name: "D112" } }
                }
            }
          }
          {
            name: "B2"
            userC: {
              create: 
                {
                  name: "C22"
                  userD: { create: { name: "D222" } }
                }
              
            }
          }
        ]
      }
    }
  ) {
    id
  }
}
```

Deleting it with this mutation.

```graphql
mutation b {
  deleteUserA(where: { id: "id" }) {
    id
  }
}
```

This worked for me. Can you please provide an example repo that triggers the error (datamodel, seed data and mutations)? Otherwise I can't reproduce and fix the issue.

**Comment by Gazuntype** [comment] 2019-03-14 13:26
Hi,
I was going to comment on this issue. I tried it again and it worked without errors. Didn't change any part of my datamodel or any code and it worked. I'm not sure what exactly was the problem or why it didn't work before but I guess the issue has been solved. Thanks!

**Comment by divyenduz** [comment] 2019-03-14 13:43
Thanks for letting us know. I am closing this issue for now. Please feel free to open a new issue if the problem reoccurs.

**Closed by divyenduz** 2019-03-14 13:43 UTC
