### ISSUE TITLE
When executing queries in parallel, each next connection to the database gets progressively slower

### ISSUE THREAD

**Issue by EliKor** [prisma/prisma#13134] opened 2022-05-03 21:15 UTC
### Bug description

In investigating some latency issues we have been experiencing, we have found that attempting multiple concurrent async queries at once exhibits behavior closer to serial queries even when increasing our connection pool limit, i.e. queries are remaining queued waiting for a connection for much longer than we expect regardless of connection pool limit.

### How to reproduce

1. Run the following script:
```
import { PrismaClient, WriteSmall } from "@prisma/client";
import { v4 as uuid } from "uuid";

type RandData = Omit<WriteSmall, "rowId" | "id">;

const getData = (n: number): [string, RandData][] => {
  const data = [];
  const rowIds = [];
  for (let i = 0; i < n; i++) {
    rowIds.push(uuid());
  }
  for (let i = 0; i < n; i++) {
    const randVal = Math.floor(Math.random() * 100);
    data.push([
      rowIds[i],
      { name: `name_${randVal}`, status: randVal % 2 === 0, count: randVal },
    ]);
  }
  return data;
};

const prismaCreate = (rowId: string, randData: RandData) => {
  return client.writeSmall.create({ data: { rowId, ...randData } });
};

const createConcurrently = async () => {
  const NUM_WRITES = 100;
  const promises = [];
  const durations = [];
  const startTimes = Array(NUM_WRITES);
  const data = getData(NUM_WRITES);
  for (let i = 0; i < NUM_WRITES; i++) {
    const [rowId, randData] = data[i];
    startTimes[i] = Date.now();
    promises.push(
      prismaCreate(rowId, randData)
        .then(() => {
          const now = Date.now();
          const duration = now - startTimes[i];
          durations.push(duration);
          console.log(
            `Finished create ${i} at ${now} in ${duration} with start time ${startTimes[i]}`
          );
        })
        .catch((e) => console.log(e))
    );
  }
  let allSettled = await Promise.allSettled(promises);
  const avgTime = durations.reduce((acc, curr) => curr + acc, 0) / durations.length;;
  const failures = allSettled.filter(
    (val) => val.status !== "fulfilled"
  ).length;
  console.log(
    `Finished with an average time of ${avgTime} ms with ${failures} failures`
  );
};

main()
  .then(() => console.log("Done"))
  .catch((e) => console.log(e));
````
2. Watch output as later writes experience significant lag waiting for previous writes to complete.
3. Adjust `connection_limit` to a higher value.
4. Watch output and see that later writes are still experiencing significant lag.

<details>
  <summary>Click to see example logs</summary>
<p>
Finished create 0 at 1651608806235 in 3101 with start time 1651608803134 <br>
Finished create 1 at 1651608807848 in 4707 with start time 1651608803141 <br>
Finished create 2 at 1651608808988 in 5847 with start time 1651608803141 <br>
Finished create 4 at 1651608809418 in 6276 with start time 1651608803142 <br>
Finished create 7 at 1651608810617 in 7474 with start time 1651608803143 <br>
Finished create 5 at 1651608810632 in 7490 with start time 1651608803142 <br>
Finished create 3 at 1651608811126 in 7984 with start time 1651608803142 <br>
Finished create 8 at 1651608812267 in 9124 with start time 1651608803143 <br>
Finished create 9 at 1651608812284 in 9141 with start time 1651608803143 <br>
Finished create 10 at 1651608812298 in 9155 with start time 1651608803143 <br>
Finished create 6 at 1651608812767 in 9625 with start time 1651608803142 <br>
Finished create 12 at 1651608813861 in 10717 with start time 1651608803144 <br>
Finished create 14 at 1651608813874 in 10730 with start time 1651608803144 <br>
Finished create 13 at 1651608813893 in 10749 with start time 1651608803144 <br>
Finished create 15 at 1651608813894 in 10750 with start time 1651608803144 <br>
Finished create 11 at 1651608814315 in 11172 with start time 1651608803143 <br>
Finished create 17 at 1651608815506 in 12359 with start time 1651608803147 <br>
Finished create 21 at 1651608815506 in 12358 with start time 1651608803148 <br>
Finished create 16 at 1651608815511 in 12367 with start time 1651608803144 <br>
Finished create 19 at 1651608815527 in 12380 with start time 1651608803147 <br>
Finished create 20 at 1651608815531 in 12384 with start time 1651608803147 <br>
Finished create 18 at 1651608815980 in 12833 with start time 1651608803147 <br>
Finished create 23 at 1651608817145 in 13997 with start time 1651608803148 <br>
Finished create 24 at 1651608817145 in 13997 with start time 1651608803148 <br>
Finished create 25 at 1651608817155 in 14007 with start time 1651608803148 <br>
Finished create 28 at 1651608817164 in 14015 with start time 1651608803149 <br>
Finished create 26 at 1651608817173 in 14025 with start time 1651608803148 <br>
Finished create 27 at 1651608817173 in 14025 with start time 1651608803148 <br>
Finished create 22 at 1651608817640 in 14492 with start time 1651608803148 <br>
Finished create 30 at 1651608818791 in 15642 with start time 1651608803149 <br>
Finished create 31 at 1651608818795 in 15646 with start time 1651608803149 <br>
Finished create 32 at 1651608818801 in 15652 with start time 1651608803149 <br>
Finished create 33 at 1651608818811 in 15662 with start time 1651608803149 <br>
Finished create 36 at 1651608818817 in 15667 with start time 1651608803150 <br>
Finished create 35 at 1651608818818 in 15668 with start time 1651608803150 <br>
...
</p>
</details>

### Expected behavior

Up to a point (depending on the database's connection load), the actions are able to run increasingly concurrently as connection pool limit is increased.

### Prisma information

Schema:
```prisma
datasource db {
    provider = "postgresql"
    url = "postgress://user:password@host:port/db?connection_limit=10"
}

model WriteSmall {
  id Int @id @default(autoincrement())
  rowId String @db.VarChar(255) @unique
  name String @db.VarChar(255)
  count Int
  status Boolean

  createdAt DateTime @default(now())
  updatedAt DateTime @updatedAt
}

generator client {
    provider = "prisma-client-js"
}
```
We are running the following query:
```
client.writeSmall.create({ data: { rowId, ...randData } })
```

### Environment & setup

- OS: Ubuntu 
- Database: PostgreSQL 
- Node.js version: v14.17.6 

### Prisma Version

```
prisma                  : 3.13.0
@prisma/client          : 3.13.0
Current platform        : debian-openssl-1.1.x
Query Engine (Node-API) : libquery-engine efdf9b1183dddfd4258cd181a72125755215ab7b (at ../.npm/_npx/2778af9cee32ff87/node_modules/@prisma/engines/libquery_engine-debian-openssl-1.1.x.so.node)
Migration Engine        : migration-engine-cli efdf9b1183dddfd4258cd181a72125755215ab7b (at ../.npm/_npx/2778af9cee32ff87/node_modules/@prisma/engines/migration-engine-debian-openssl-1.1.x)
Introspection Engine    : introspection-core efdf9b1183dddfd4258cd181a72125755215ab7b (at ../.npm/_npx/2778af9cee32ff87/node_modules/@prisma/engines/introspection-engine-debian-openssl-1.1.x)
Format Binary           : prisma-fmt efdf9b1183dddfd4258cd181a72125755215ab7b (at ../.npm/_npx/2778af9cee32ff87/node_modules/@prisma/engines/prisma-fmt-debian-openssl-1.1.x)
Default Engines Hash    : efdf9b1183dddfd4258cd181a72125755215ab7b
Studio                  : 0.459.0
```

**Comment by EliKor** [comment] 2022-05-04 17:01
I did some more testing with `pg` and got the following results attempting 10 "concurrent" inserts:
```
Finished create 1 at 1651683286608 in 61 with start time 1651683286547
Finished create 9 at 1651683286612 in 61 with start time 1651683286551
Finished create 0 at 1651683286616 in 76 with start time 1651683286540
Finished create 2 at 1651683286617 in 69 with start time 1651683286548
Finished create 4 at 1651683286617 in 68 with start time 1651683286549
Finished create 3 at 1651683286618 in 70 with start time 1651683286548
Finished create 7 at 1651683286620 in 70 with start time 1651683286550
Finished create 6 at 1651683286621 in 71 with start time 1651683286550
Finished create 5 at 1651683286622 in 73 with start time 1651683286549
Finished create 8 at 1651683286622 in 71 with start time 1651683286551
```
Doing the same with Prisma and a `pool_limit` of 20, I am getting the following:
```
Finished create 0 at 1651683015904 in 159 with start time 1651683015745
Finished create 3 at 1651683015959 in 205 with start time 1651683015754
Finished create 2 at 1651683016010 in 256 with start time 1651683015754
Finished create 1 at 1651683016032 in 279 with start time 1651683015753
Finished create 5 at 1651683016077 in 322 with start time 1651683015755
Finished create 6 at 1651683016077 in 322 with start time 1651683015755
Finished create 4 at 1651683016092 in 338 with start time 1651683015754
Finished create 8 at 1651683016144 in 389 with start time 1651683015755
Finished create 9 at 1651683016144 in 389 with start time 1651683015755
Finished create 7 at 1651683016161 in 406 with start time 1651683015755
```

**Comment by EliKor** [comment] 2022-05-24 21:06
You can also use the following code in the above script to use pg instead:
```
import { Client as PgClient } from "pg";

const pgCreate = (rowId: string, randData: RandData) => {
  const client = new PgClient({ connectionString: process.env.DB_URL });
  return client.connect().then(() => {
    return client
      .query(
        'INSERT INTO "WriteSmall" ("rowId", "name", "count", "status", "updatedAt", "createdAt") VALUES ($1, $2, $3, $4, NOW(), NOW())',
        [
          rowId,
          randData["name"],
          randData["count"],
          randData["status"],
        ]
      )
      .then(() => client.end())
      .catch((e) => console.log(e));
  });
};
```
Just make sure to replace prismaCreate with pgCreate.

**Comment by andrewicarlson** [comment] 2022-05-27 15:30
Measuring the difference between individual queries in an aggregate group of concurrent requests between `pg` and Prisma is going to be tricky because they don't necessarily manage queues in the same way.

I also think it's useful to measure the actual query time using the query event duration, and then the total time it takes all requests to execute for a slightly more meaningful measurement. See below for an updated script using the query events and `console.time`. 

```prisma
import { PrismaClient, WriteSmall } from "@prisma/client";
import { v4 as uuid } from "uuid";

type RandData = Omit<WriteSmall, "rowId" | "id">;

const prisma = new PrismaClient({
    log: [
        {
            emit: 'event',
            level: 'query',
        }
    ],
});
const queries = [];
const NUM_WRITES = 5;

prisma.$on('query', (e) => {
    queries.push(e)
})

const getData = (n: number): [string, RandData][] => {
    const data = [];
    const rowIds = [];
    for (let i = 0; i < n; i++) {
        rowIds.push(uuid());
    }
    for (let i = 0; i < n; i++) {
        const randVal = Math.floor(Math.random() * 100);
        data.push([
            rowIds[i],
            { name: `name_${randVal}`, status: randVal % 2 === 0, count: randVal },
        ]);
    }
    return data;
};

const prismaCreate = async (rowId: string, randData: RandData) => {
    return prisma.writeSmall.create({ data: { rowId, ...randData } });
};

const createConcurrently = async () => {
    console.time('CREATE_CONCURRENTLY')
    const data = getData(NUM_WRITES);
    const promises = [];

    for (let i = 0; i < NUM_WRITES; i++) {
        const [rowId, randData] = data[i];
        console.time(`PRISMA_CREATE_${rowId}`)
        promises.push(prismaCreate(rowId, randData)
            .then(() => console.timeEnd(`PRISMA_CREATE_${rowId}`))
            .catch((e) => console.log(e)))
    }

    await Promise.all(promises);
};

createConcurrently()
    .then(() => {
        console.timeEnd('CREATE_CONCURRENTLY');
        console.log(`Average duration for ${queries.length} queries (concurrently): ${queries.reduce((acc, curr) => { return acc + curr.duration }, 0) / queries.length}ms`)
    })
    .catch((e) => console.log(e));
```
In this example you'll see that the `console.time` reporting for a row (Identified using `PRISMA_CREATE_${rowId}` doesn't line up with the actual duraction that the query took. We can't line it up perfectly because there isn't a transaction ID in the query event, but by averaging it out you'll notice that the durations don't seem to line up. 

I included `console.time` here for the individual queries to illustrate that it's not a meaningful unit of measurement because the "start" is at the time it's pushed into the queue and the "end" is when the request has been processed and the write is complete. I don't think it's wise to consider that a measure of the latency. 

The gradually incrementing query time that you see logged is due to the fact that the timer starts when the query is sent to the prisma engine, not to the time that the query actually starts.

**Comment by SevInf** [comment] 2022-09-13 13:44
Reproduced this on current `main` (4.4.0-dev) with tracing enabled. Code:

https://github.com/prisma/reproductions/tree/main/gh-13134

[Zipped traces](https://github.com/prisma/prisma/files/9557605/traces.zip), can be viewed in Jaeger.

Interesting one is `trace-parallel.json`. Note that engine is running with connection limit of 100, which should be enough for all writes.

For the first, request `prisma:engine:connection` span takes 42ms:
![image](https://user-images.githubusercontent.com/603056/189916172-2af3d4ce-857c-4759-89c9-02787f6471db.png)

Then, for each request, connection to the database takes more and more time and for the last write, we are at 456ms:

![image](https://user-images.githubusercontent.com/603056/189916925-63129764-b4ab-4e58-b363-71721ee1eebc.png)


This behaviour persists regardless of connection limit with more or less same timings.

**Comment by garrensmith** [comment] 2022-09-13 15:13
Just some ideas around this. The pg comparison to Prisma is not accurate. Prisma will start a transaction, update, possible run a read of the rows updated and then commit. So that is a lot more queries than the single raw pg query. That is why the difference is there. 

I'm not 100% sure why each request to the connection pool takes longer. But it could be because each create is running a transaction with a few queries it takes longer and longer to get a connection from the pool because there are a lot of operations. I'm not sure how you created 100 connections for the database. But another thing could be that your database could not handle 100 open connections at a time. 

So req1 gets a connection immediately, but req 50..100 which are started at the same time are sitting and waiting for a recycled connection or for the database to create a connection. So that is why it looks like the connection pool is the problem here. And it could very likely be the problem. But it could be somewhere else. We will have to dig a bit deeper on this one.

**Comment by SevInf** [comment] 2022-09-13 15:26
I tried replacing `create` call with `queryRaw(SELECT 1)` and connection still got slower over time: from 62ms for the first to 237ms for the last. Trace is attached.
[trace-select.json.zip](https://github.com/prisma/prisma/files/9558542/trace-select.json.zip)

**Comment by SevInf** [comment] 2022-09-13 17:03
And another trace with individual identifiable spans for each request.
[anotatated-trace.json.zip](https://github.com/prisma/prisma/files/9559238/anotatated-trace.json.zip)

**Comment by AndrewSouthpaw** [comment] 2022-09-21 03:40
> But another thing could be that your database could not handle 100 open connections at a time.

@garrensmith FWIW we addressed that in our test case. We saw this behavior for Aurora, which could handle up to 1200 connections, and we were not near the limit. The DB instance was also not under load, so there was no cross-talk effects from other prod traffic.

**Comment by garrensmith** [comment] 2022-09-26 12:25
An update on this. I think I've found the issue and have a fix for it. We will still need to do a fair amount of testing to confirm. But so far it is looking good. PR is https://github.com/prisma/mobc/pull/9

**Comment by cgat** [comment] 2023-01-27 23:28
Hey folks, is there any update on this. Seems like a potential fix was implemented in the `mobc` repo, but it's unclear if this has made it into the latest version of prisma? I found [this](https://github.com/prisma/prisma/pull/12220), which suggests it didn't make it in for some reason.

Curious if any of the other people on this thread figured out a workaround? We are building out a NestJS GraphQL application and appears we are running into some similar performance limitations related to this with very limited users. I feel like most GraphQL will hit this limitation fairly quickly due to the nature of resolvers running in parallel.

**Comment by janpio** [comment] 2023-07-21 20:34
@lleifermann Can you (or did you already) open a separate, standalone issue for this and fill the full bug issue template? From your comment I am not fully sure what I am looking at, and debugging this here in this (potentially unrelated) issue feels wrong. I think we need to start asking questions and try to understand what exactly your screenshots are saying. Thank you!

**Comment by lleifermann** [comment] 2023-07-21 20:50
> @lleifermann Can you (or did you already) open a separate, standalone issue for this and fill the full bug issue template? From your comment I am not fully sure what I am looking at, and debugging this here in this (potentially unrelated) issue feels wrong. I think we need to start asking questions and try to understand what exactly your screenshots are saying. Thank you!

I initially commented this when I started investigating our performance issues with Prisma. This is just one part of the puzzle and I fear separating things into their own issues will make things only less transparent to track. 

From this I investigated deeper and found other issues which are seemingly connected to this. I am open to do a joint session or meeting if folks at Prisma are interested. 
You all need to get aware that performance is a real issue for anyone running anything else than a hobby app. I am not talking about performance in the sense of "the last 5%". More like being able to build an app with Prisma that can handle more than 30 req/s. I fear this is impossible as of right now.

**Comment by cgat** [comment] 2023-07-22 01:37
The above comment is pretty concerning to us. The application we are working has a high likelihood of reaching a mass audience. @janpio My assumption would that that the prisma team has done the proper load testing to counter the argument above and suggest that maybe this is a configuration issue.

**Comment by janpio** [comment] 2023-07-22 21:51
@cgat Prisma is used by thousands of high-load applications out there, so generally this can not be a fundamental problem. We would have a _lot_ more of these issues if that was the case. At the same time I can not make broad statements about _individual_ applications.

@lleifermann Happy to do that, but we would still need more information than what was provided here until now. Especially because it generally looks unrelated or at least different to the original problem that was described in this issue, I am not super eager to continue the discussion here. 
If you are not comfortable sharing the information in an issue in our repository, you could create a new repository and invite me and write it in an issue there, for example. Email also always works with firstname@prisma.io - but there having a technical discussion is much harder usually than in a GitHub issue.

**Comment by janpio** [comment] 2023-08-08 23:35
There is no update to give beyond that I updated the label to record that Serhii did reproduce the problem in the past. Someone will need to look into this, and that has not happened yet.

**Comment by SevInf** [comment] 2023-08-09 13:07
So, we've actually not only reproduced it, but fixed it and the PR that was posted in https://github.com/prisma/prisma/issues/13134#issuecomment-1257956062 made it into Prisma 4.5.0 ([PR](https://github.com/prisma/prisma-engines/pull/3242)). 

I've just re-run my reproduction from last year on latest prisma version (5.1.1) and can no longer observe this behaviour. Connection time varies from request to request, but I observe similar request time distiribution when running same queries with `pg` rather than `prisma`.

@EliKor could you confirm that fix worked on your side?
Thank you.

**Comment by cgat** [comment] 2023-08-14 21:01
@SevInf Thanks for clarifying that the change made it in to prisma!

**Comment by janpio** [comment] 2023-09-04 21:30
Ping @EliKor, can you please confirm if the problem is fixed so we can close this issue? Thanks.
(With no response we will close the issue without confirmation in a few weeks.)

**Comment by laplab** [comment] 2024-01-25 14:08
Closing this as fixed.

**Closed by laplab** 2024-01-25 14:08 UTC
Labels: bug/2-confirmed, kind/bug, topic: performance, topic: connections, team/client, topic: connection pool, topic: performance/queries
