### ISSUE TITLE
return nothing using full text search with mariadb 10 and next.js 13

### ISSUE THREAD

**Issue by danx2y** [prisma/prisma#22359] opened 2023-12-13 02:38 UTC
### Bug description

Simply speaking, search field is not working without any error messages.
There is no search results in the codes below...

### How to reproduce

1. enabled the necessary preview features in my Prisma schema.
2. database schema includes the appropriate full-text indexes.
3. Prisma Client has been regenerated after making schema changes.

### Prisma information

```prisma
generator client {
  provider = "prisma-client-js"
  previewFeatures = ["fullTextSearch", "fullTextIndex"]
}

datasource db {
  provider     = "mysql"
  url          = env("DATABASE_URL")
  relationMode = "prisma"
}

model apartment {
  id          Int                @id @default(autoincrement())
  name        String             @db.VarChar(50)
  address     String             @db.VarChar(100)
  gu          String             @db.VarChar(20)
  dong        String             @db.VarChar(20)
  use_date    Int
  household   Int
  contract    Int
  meter_date  Int
  latitude    Float
  longitude   Float
  consumption apt_elec_consump[]
  
  @@fulltext([name])
}
```

```ts
const apartment = await prisma.apartment.findMany({
    where: {
      name: {
        search: "word",
      },
    },
  });
```

### Environment & setup

- OS: Ubuntu 20.04
- Database: Mariadb 10
- Node.js version: 18.17.1

### Prisma Version

```
prisma                  : 5.3.1
@prisma/client          : 5.3.1
Current platform        : debian-openssl-1.1.x
Query Engine (Node-API) : libquery-engine 61e140623197a131c2a6189271ffee05a7aa9a59 (at node_modules/@prisma/engines/libquery_engine-debian-openssl-1.1.x.so.node)
Schema Engine           : schema-engine-cli 61e140623197a131c2a6189271ffee05a7aa9a59 (at node_modules/@prisma/engines/schema-engine-debian-openssl-1.1.x)
Schema Wasm             : @prisma/prisma-schema-wasm 5.3.1-2.61e140623197a131c2a6189271ffee05a7aa9a59
Default Engines Hash    : 61e140623197a131c2a6189271ffee05a7aa9a59
Studio                  : 0.494.0
Preview Features        : fullTextIndex, fullTextSearch
```

**Comment by jkomyno** [comment] 2023-12-14 11:29
Hi @daeb2a, is it ok for you to share your database dump (or Prisma `seed.ts` file) with us, for reproduction purposes? Have you by any chance tried the same code against a MySQL 8 database instance?

**Comment by daeb2a** [comment] 2023-12-15 02:29
Hi @jkomyno, I haven't tried in MySQL 8. Here's a part of database dumps!
[apartment.zip](https://github.com/prisma/prisma/files/13680234/apartment.zip)

**Comment by alexpirine** [comment] 2023-12-16 15:05
What SQL query does "search" vs "contains" generate?

**Comment by daeb2a** [comment] 2023-12-18 00:28
@alexpirine I couldn't get it what you mean. Please give me a chance to understand what you said.

**Comment by alexpirine** [comment] 2023-12-18 10:30
> @alexpirine I couldn't get it what you mean. Please give me a chance to understand what you said.

I thought

```javascript
const apartment = await prisma.apartment.findMany({
    where: {
      name: {
        contains: "word",
      },
    },
  });
```

works, while

```javascript
const apartment = await prisma.apartment.findMany({
    where: {
      name: {
        search: "word",
      },
    },
  });
```

doesn't.

**Comment by daeb2a** [comment] 2024-01-18 10:18
@romaob Thank you for answering! but your suggestion is not working to mine. since it was not working with `search`, I solved this issue using `contains` with js methods like below.

```javascript
  let combinedKeyword = [];
  const letterArray = keyword?.split("");
  if (letterArray) {
    for (let i = 0; i <= letterArray.length; i++) {
      for (let j = 2; j <= letterArray.length; j++) {
        combinedKeyword.push(letterArray.slice(i, j).join(""));
      }
    }
  }
  const filteredKeyword = combinedKeyword.filter((word) => word.length >= 2);
  const ultimateKeyword = filteredKeyword.map((word) => ({
    name: {
      contains: word,
    },
  }));

  const apartment = await prisma.apartment.findMany({
    where: {
      OR: ultimateKeyword.length === 0 ? undefined : ultimateKeyword,
    }
  });
```

**Comment by danx2y** [comment] 2024-02-20 11:46
@janpio I definately typed codes like below which are totally same as the documentations.
I just tried the way below because I wanted to check first if the codes in the simplest structure are working. but that couldn't get any results.

```
// All posts that contain the words 'cat' or 'dog'.
const result = await prisma.posts.findMany({
  where: {
    body: {
      search: 'cat dog',
    },
  },
})
```

**Comment by janpio** [comment] 2024-02-21 23:02
Can you [enable Prisma Client query logging](https://www.prisma.io/docs/orm/prisma-client/observability-and-logging/logging) and share the query that this executes? Can you also shared a screenshot of the data in that table that you would expect to be returned?

**Comment by SevInf** [comment] 2024-03-18 09:32
Hey @danx2y ,

Did you get a chance to have a look at my colleagues previous comment? It'd be helpful for us to move your issue forward.

Thank you 🙏

**Comment by jkomyno** [comment] 2024-04-08 09:19
Hi @danx2y, can you please take a look at [this comment](https://github.com/prisma/prisma/issues/22359#issuecomment-1958253279), and provide an answer below?
Without that, I'm afraid we won't be able to reproduce this issue, and we'll be forced to close it. Thanks!

**Comment by danx2y** [comment] 2024-04-09 00:18
@jkomyno @SevInf @janpio Sorry for late replying, I will try it tonight!

**Comment by danx2y** [comment] 2024-04-09 13:42
@jkomyno @SevInf @janpio I just checked db server shut down now so I couldn't check more.... Since I can't handle the server now this issue should be closed....Sorry for saying that

**Comment by SevInf** [comment] 2024-05-03 09:20
Thank you @danx2y, I'll close issue as non-reproducible for now. Feel free to comment if you'll encounter it again and will be able to provide requested info.

**Closed by SevInf** 2024-05-03 09:20 UTC
Labels: bug/0-unknown, kind/bug, topic: mariadb, team/client, topic: fullTextSearch
