### ISSUE TITLE
interactiveTransactions: 2 concurrent writes to the same row will cause it to hang until expiring

### ISSUE THREAD

**Issue by matthewmueller** [prisma/prisma#8707] opened 2021-08-12 04:50 UTC
### Bug description

I'm trying to use interactive transactions to build a bank transfer. I'd like to try to achieve the following:

- Alice and Bob have $100
- Concurrently, Alice sends Bob $100 twice
  - One of those requests goes through
  - The other one is rejected saying there's not enough money  
- Alice has $0, Bob has $100

### How to reproduce

**Reproduction Repo:** https://github.com/matthewmueller/interactive-transactions 

Given the following Prisma Schema

```prisma
// This is your Prisma schema file,
// learn more about it in the docs: https://pris.ly/d/prisma-schema

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

generator client {
  provider        = "prisma-client-js"
  previewFeatures = ["interactiveTransactions"]
}

model Account {
  id      Int    @id @default(autoincrement())
  email   String @unique
  balance Int
}
```

And the following script:

```ts
import { PrismaClient } from "@prisma/client"
const prisma = new PrismaClient()

async function unseed() {
  await prisma.account.deleteMany({
    where: {
      OR: [{ email: "alice@prisma.io" }, { email: "bob@prisma.io" }],
    },
  })
}

async function seed() {
  await prisma.account.create({
    data: {
      email: "alice@prisma.io",
      balance: 100,
    },
  })
  await prisma.account.create({
    data: {
      email: "bob@prisma.io",
      balance: 100,
    },
  })
}

async function transfer(nth: number, from: string, to: string, amount: number) {
  return await prisma.$transaction(
    async (prisma) => {
      console.time("send " + nth)
      const sender = await prisma.account.update({
        data: {
          balance: {
            decrement: amount,
          },
        },
        where: {
          email: from,
        },
      })
      console.timeEnd("send " + nth)
      console.time("throw " + nth)
      if (sender.balance < 0) {
        throw new Error(`${from} doesn't have enough to send ${amount}`)
      }
      console.timeEnd("throw " + nth)
      console.time("recieve " + nth)
      const recipient = prisma.account.update({
        data: {
          balance: {
            increment: amount,
          },
        },
        where: {
          email: to,
        },
      })
      console.timeEnd("recieve " + nth)
      return recipient
    },
    {
      timeout: 20000,
    }
  )
}

async function main() {
  await prisma.$connect()
  await unseed()
  await seed()
  console.time("transfer")
  await Promise.all([
    transfer(1, "alice@prisma.io", "bob@prisma.io", 100),
    transfer(2, "alice@prisma.io", "bob@prisma.io", 100),
  ])
  console.timeEnd("transfer")
}

main()
  .catch(console.error)
  .finally(() => prisma.$disconnect())
```

If you setup a database and then run `ts-node index.ts`, you'll get:

```
send 1: 7.005ms
throw 1: 0.005ms
recieve 1: 0.279ms
send 2: 20.005s
throw 2: 0.367ms
recieve 2: 0.644ms
PrismaClientKnownRequestError3 [PrismaClientKnownRequestError]: 
Invalid `prisma.account.deleteMany()` invocation in
/Users/m/dev/src/github.com/prisma/interactive-transactions/index.ts:5:58

  2 const prisma = new PrismaClient()
  3 
  4 async function unseed() {
→ 5   await prisma.account.deleteMany(
  Transaction API error: Transaction already closed: Transaction is no longer valid. Last state: 'Expired'.
    at RequestHandler.request (/Users/m/dev/src/github.com/prisma/interactive-transactions/node_modules/@prisma/client/runtime/index.js:36361:15)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at PrismaClient._transactionWithCallback (/Users/m/dev/src/github.com/prisma/interactive-transactions/node_modules/@prisma/client/runtime/index.js:36932:18) {
  code: 'P2028',
  clientVersion: '2.30.0-dev.8',
  meta: {
    error: "Transaction already closed: Transaction is no longer valid. Last state: 'Expired'."
  }
}
```

Two notes:
- The 2nd send takes the full 20s
- An FYI that the stack trace is off. It was pointing to that line even when it was commented out.

I think this could be a bug because if I change the code to transfer serially, it works as expected:

```typescript
async function main() {
  await prisma.$connect()
  await unseed()
  await seed()
  await transfer("alice@prisma.io", "bob@prisma.io", 100)
  await transfer("alice@prisma.io", "bob@prisma.io", 100) // Error: alice@prisma.io doesn't have enough to send 100
}
```

### Expected behavior

I'd expect this to work as expected, you should be able to initialize multiple transactions concurrently and let the database sort it out.

### Environment & setup

- OS:  OSX
- Database:  Postgres
- Node.js version:  v14.16.0

### Prisma Version

```
Environment variables loaded from .env
prisma                : 2.30.0-dev.8
@prisma/client        : 2.30.0-dev.8
Current platform      : darwin
Query Engine (Binary) : query-engine 71d96e8bbd21982078694f00add0f51da2056a8b (at node_modules/@prisma/engines/query-engine-darwin)
Migration Engine      : migration-engine-cli 71d96e8bbd21982078694f00add0f51da2056a8b (at node_modules/@prisma/engines/migration-engine-darwin)
Introspection Engine  : introspection-core 71d96e8bbd21982078694f00add0f51da2056a8b (at node_modules/@prisma/engines/introspection-engine-darwin)
Format Binary         : prisma-fmt 71d96e8bbd21982078694f00add0f51da2056a8b (at node_modules/@prisma/engines/prisma-fmt-darwin)
Default Engines Hash  : 71d96e8bbd21982078694f00add0f51da2056a8b
Studio                : 0.419.0
Preview Features      : interactiveTransactions
```

**Comment by matthewmueller** [comment] 2021-08-12 13:47
I just tested it with Postgres via `pg`. First I used a single connection:

```ts
import { Client } from "pg"
import dotenv from "dotenv"
dotenv.config()

const client = new Client({
  connectionString: process.env.DATABASE_URL,
})

async function unseed() {
  await client.query(`delete from "Account" where email in($1, $2)`, [
    "alice@prisma.io",
    "bob@prisma.io",
  ])
}

async function seed() {
  await client.query(`insert into "Account" (email, balance) values ($1, $2)`, [
    "alice@prisma.io",
    100,
  ])
  await client.query(`insert into "Account" (email, balance) values ($1, $2)`, [
    "bob@prisma.io",
    100,
  ])
}

async function transfer(nth: number, from: string, to: string, amount: number) {
  await client.query("begin")
  console.time("send " + nth)
  const sender = await client.query(
    `update "Account" set balance = balance - $1 where email = $2 returning *`,
    [amount, from]
  )
  console.timeEnd("send " + nth)
  console.time("throw " + nth)
  if (sender.rows[0].balance < 0) {
    await client.query("rollback")
    console.timeEnd("throw " + nth)
    return
  }
  console.timeEnd("throw " + nth)
  console.time("recieve " + nth)
  const recipient = await client.query(
    `update "Account" set balance = balance + $1 where email = $2 returning *`,
    [amount, to]
  )
  console.timeEnd("recieve " + nth)
  await client.query("commit")
  return recipient.rows[0]
}

async function main() {
  await client.connect()
  await unseed()
  await seed()
  console.time("transfer")
  await Promise.all([
    transfer(1, "alice@prisma.io", "bob@prisma.io", 100),
    transfer(2, "alice@prisma.io", "bob@prisma.io", 100),
  ])
  console.timeEnd("transfer")
}

main()
  .catch(console.error)
  .finally(() => client.end())
```

Running `ts-node postgres.ts`, 

```
send 1: 1.634ms
throw 1: 0.009ms
send 2: 2.25ms
recieve 1: 0.763ms
throw 2: 0.552ms
transfer: 4.121ms
```

The result:

id | email | balance
-- | -- | --
43 | alice@prisma.io | 100
44 | bob@prisma.io | 100

This sort of makes sense because with 1 connection, 2 concurrent requests, it's not clear in what order the queries happen.

Next I setup the pool and used a separate connection per transfer.

```ts
import { Pool, PoolClient } from "pg"
import dotenv from "dotenv"
dotenv.config()

const pool = new Pool({
  connectionString: process.env.DATABASE_URL,
})

async function unseed(client: PoolClient) {
  await client.query(`delete from "Account" where email in($1, $2)`, [
    "alice@prisma.io",
    "bob@prisma.io",
  ])
}

async function seed(client: PoolClient) {
  await client.query(`insert into "Account" (email, balance) values ($1, $2)`, [
    "alice@prisma.io",
    100,
  ])
  await client.query(`insert into "Account" (email, balance) values ($1, $2)`, [
    "bob@prisma.io",
    100,
  ])
}

async function transfer(
  pool: Pool,
  nth: number,
  from: string,
  to: string,
  amount: number
) {
  const client = await pool.connect()
  await client.query("begin")
  console.time("send " + nth)
  const sender = await client.query(
    `update "Account" set balance = balance - $1 where email = $2 returning *`,
    [amount, from]
  )
  console.timeEnd("send " + nth)
  console.time("throw " + nth)
  if (sender.rows[0].balance < 0) {
    await client.query("rollback")
    client.release()
    console.timeEnd("throw " + nth)
    return
  }
  console.timeEnd("throw " + nth)
  console.time("recieve " + nth)
  const recipient = await client.query(
    `update "Account" set balance = balance + $1 where email = $2 returning *`,
    [amount, to]
  )
  console.timeEnd("recieve " + nth)
  await client.query("commit")
  client.release()
  return recipient.rows[0]
}

async function main() {
  const client = await pool.connect()
  await unseed(client)
  await seed(client)
  client.release()
  console.time("transfer")
  await Promise.all([
    transfer(pool, 1, "alice@prisma.io", "bob@prisma.io", 100),
    transfer(pool, 2, "alice@prisma.io", "bob@prisma.io", 100),
  ])
  console.timeEnd("transfer")
}

main()
  .catch(console.error)
  .finally(() => pool.end())

```

This works as expected:

id | email | balance
-- | -- | --
45 | alice@prisma.io | 0
46 | bob@prisma.io | 200

**Comment by matthewmueller** [comment] 2021-08-24 04:08
More investigation here: https://github.com/matthewmueller/interactive-transactions

**Comment by juanantoniodamianv** [comment] 2021-09-06 22:40
Hey, did you solve this?
I have the same issue, this is my scenario:

```
const invoice = await prisma.$transaction(async (prisma) => {
					
	const invoice = await prisma.invoice.create({ data });
	if (!invoice) throw new Error('Invoice not created');

	const updatedServices = await prisma.service.updateMany({ where: { serviceNumber: { in: serviceNumbers } }, data: { eosStatus: SERVICE_STATUS.APROVED, invoiceId: invoice.id } });
	if (!updatedServices) throw 'Services cannot be updated';

	const invoiceAtacchmentData = [];
	for (const file of files.files) {
		const fileName = `invoice-attachments/${Date.now()}-${file.originalFilename}`;
		const stream = fs.createReadStream(file.path);
		const { Location } = await uploadToS3(stream, fileName);
		if (!Location) throw `File ${file.originalFilename} cannot be uploaded`;
		invoiceAtacchmentData.push({
			invoiceId: invoice.id, fileName: file.originalFilename, filePath: Location
		});
	}
	if (invoiceAtacchmentData.length > 0) {
		const invoiceAttachments = await prisma.invoiceAttachment.createMany({ data: invoiceAtacchmentData, skipDuplicates: true });
		if (!invoiceAttachments) throw 'Invoice Attachment record cannot be created';
	}

	return invoice;
});
```

**Comment by Stefandasbach** [comment] 2021-09-25 16:44
Hey @millsp, is this still slated for milestone 3.1.0? Actively blocking me at the moment.

**Comment by MichalLytek** [comment] 2021-11-09 09:46
@matthewmueller Any chance it will be fixed in v3.5.0?
For now because of that, the interactive transactions are unusable in any http/graphql scenario when the requests can come at the same time 😕

**Comment by matthewmueller** [comment] 2021-11-09 16:28
We're working on it!

**Comment by tmcw** [comment] 2021-12-04 14:29
Unfortunately, I've updated to 3.6.0 in prod and am seeing the same failure case. Concurrent transactions stall, consume 100% of CPU, and eventually time-out.

**Comment by pascalporedda** [comment] 2022-01-10 09:12
We're currently experiencing the same issues with 3.7.0

**Comment by janpio** [comment] 2022-01-10 09:28
Do you have a reproduction we can try?

**Comment by pascalporedda** [comment] 2022-01-10 10:40
@janpio I'll see if I can get some time from my client to set up a reproduction repo.

**Comment by millsp** [comment] 2022-01-11 19:48
I think I might have a repro - which differs from the OP since that issue has been fixed. Instead, I just performed a load test and triggering many transactions at once. That sometimes works and other times it leads to the screenshot below. `binary` engine seems more susceptible to this, even though it happens on `library` too (without proof of where is stalls on that one though).
![Screenshot from 2022-01-11 20-07-35](https://user-images.githubusercontent.com/18401805/149008137-d6201598-b3fd-4575-94d9-54862c1d499a.png)

**Comment by s-montigny-desautels** [comment] 2022-01-11 21:57
> I think I might have a repro - which differs from the OP since that issue has been fixed. Instead, I just performed a load test and triggering many transactions at once. That sometimes works and other times it leads to the screenshot below. `binary` engine seems more susceptible to this, even though it happens on `library` too (without proof of where is stalls on that one though).

I did experience this too. What I also found is that when using the `interactiveTransactions` preview feature, regular transaction will also suffer from the same probleme, i.e a transaction using an array of Prisma Promise. When disabling the feature, regular transaction work as expected.

**Comment by linde12** [comment] 2022-01-12 16:42
Encountering the same issue when having multiple shortlived concurrent transactions.

`{"code":"P2028","clientVersion":"3.4.2","meta":{"error":"Transaction already closed: Transaction is no longer valid. Last state: 'Expired'."}}`

Can't provide code unfortunately :(

**Comment by ebaer-payix** [comment] 2022-01-21 14:00
> I did experience this too. What I also found is that when using the `interactiveTransactions` preview feature, regular transaction will also suffer from the same probleme, i.e a transaction using an array of Prisma Promise. When disabling the feature, regular transaction work as expected.

I have seen the same thing in my application.  I created a "Poor Man's" SEQUENCE for MySQL, and it uses the transaction array listed in s-montigny-desautels comment above.  The application is running in AWS with a Health Check that hits it about every 10 seconds.  I put many changes in, including upgrading all the packages, and Prisma to 3.7.  Suddenly my application was crashing randomly (varying from <30 minutes to 4+ hours), and forcing an AWS restart.  This was too difficult to narrow down for debugging purposes, as when the CPU went to 100%, it was only 1 - 2 minutes before AWS restarted the application, and it wasn't happening locally.

I was at a complete loss to determine what was going on, due to the number of changes, but it finally occurred to me it was the Prisma change, as two applications were crashing, neither of which were doing anything at the time, except the Health Checks.  After investigating the Health Check, I realized it was using a prisma.$transaction([]), and had a lead, since I had also turned on the previewFeatures = ["interactiveTransactions"], and even though it was not being used anywhere, it was a likely cause.

I commented out the interactiveTransaction in the schema.prisma, and redeployed.  The attached graph shows the Random crashes before the ~ 9:30am deployment, and none since.

I could provide the code that caused it, but I don't think it is needed, as it is pretty obvious that the Health Check Transaction was somehow getting called again, before completing the previous call.  The only reason this would likely happen, is that the prisma.$transaction wasn't finishing and/or cleaning up anything it was doing before returning from the Promise, so the next call to it is not starting with a "clean slate".

NOTE: This is some how tied to the previewFeature interactiveTransactions.

![CPU_Utilization_Problem](https://user-images.githubusercontent.com/75736969/150539334-649f1c82-da0f-4eaa-b055-6250441bc3fc.JPG)

Update:

After looking at the graphs highly expanded (image attached), another thought occurred to me.  These Memory Usages were from 2 separate Tasks running in separate Containers.  I am now thinking that whatever Prisma is using to create (identify) the Transaction is stored in the Database (possibly a timestamp ?), because the Database requests are coming from 2 different systems at the same time, and both systems CPU usage went to 100%, and then both got restarted.  I am guessing that the 2nd transaction in is somehow corrupting the first one because it ends up with the same identifier and then whatever they use to check completion goes into an infinite loop, causing both to go to 100% CPU utilization.

![CPU_Utilization_Expanded](https://user-images.githubusercontent.com/75736969/150539241-a08153ec-4a0c-401d-b23c-100f41344634.JPG)

**Comment by garrensmith** [comment] 2022-01-21 14:18
Thanks for reporting this. We are actively working to resolve these issues.

**Comment by ebaer-payix** [comment] 2022-01-21 15:03
Sorry, I had a dyslectic moment with the Prisma Version numbers in the first Graph above.
I have corrected it now...

**Comment by millsp** [comment] 2022-01-31 19:43
Engine deadlocks have been fixed via
https://github.com/prisma/prisma-engines/pull/2619
and https://github.com/prisma/prisma/pull/10797

**Closed by millsp** 2022-01-31 19:43 UTC
Labels: bug/2-confirmed, kind/bug, tech/typescript, topic: previewFeatures, team/client, topic: interactiveTransactions
