### ISSUE TITLE
PANIC: called `Option::unwrap()` on a `None` value in query-engine/connectors/mongodb-query-connector/src/root_queries/read.rs:112:74

### ISSUE THREAD

**Issue by joaquimrobs** [prisma/prisma#11717] opened 2022-02-09 12:18 UTC
Hi Prisma Team! My Prisma Client just crashed. This is the report:
## Versions

| Name            | Version            |
|-----------------|--------------------|
| Node            | v14.16.0           | 
| OS              | darwin             |
| Prisma Client   | in-memory          |
| Query Engine    | 0.1.0              |
| Database        | mongodb            |

## Logs
```
 post your schema and a snippet of
how you used Prisma Client in the issue. 

    at Object.logger (/private/var/folders/cj/2n9f0rqd3dlb55jhxd5gx0180000gn/T/AppTranslocation/0DAE9B4A-9F47-42F4-A3F1-3A69BBCD4A4D/d/Prisma Studio.app/Contents/Resources/app.asar/node_modules/@prisma/client/runtime/index.js:36229:30)
    at /private/var/folders/cj/2n9f0rqd3dlb55jhxd5gx0180000gn/T/AppTranslocation/0DAE9B4A-9F47-42F4-A3F1-3A69BBCD4A4D/d/Prisma Studio.app/Contents/Resources/app.asar/node_modules/@prisma/client/runtime/index.js:36198:34
prisma:client:libraryEngine library is already stopping
prisma:client:libraryEngine library stopping
prisma:client:libraryEngine library stopped
prisma:client:libraryEngine sending request, this.libraryStarted: false
prisma:client:libraryEngine library starting
prisma:client:libraryEngine sending request, this.libraryStarted: false
prisma:client:libraryEngine library already starting, this.libraryStarted: false
prisma:client:libraryEngine library started
prisma:client:fetcher Error: PANIC: called `Option::unwrap()` on a `None` value in query-engine/connectors/mongodb-query-connector/src/root_queries/read.rs:112:74

This is a non-recoverable error which probably happens when the Prisma Query Engine has a panic.

https://github.com/prisma/prisma/issues/new?body=Hi+Prisma+Team%21+My+Prisma+Client+just+crashed.+This+is+the+report%3A%0A%23%23+Versions%0A%0A%7C+Name++++++++++++%7C+Version++++++++++++%7C%0A%7C-----------------%7C--------------------%7C%0A%7C+Node++++++++++++%7C+v14.16.0+++++++++++%7C+%0A%7C+OS++++++++++++++%7C+darwin+++++++++++++%7C%0A%7C+Prisma+Client+++%7C+in-memory++++++++++%7C%0A%7C+Query+Engine++++%7C+0.1.0++++++++++++++%7C%0A%7C+Database++++++++%7C+mongodb++++++++++++%7C%0A%0A%0A%0A%23%23+Logs%0A%60%60%60%0A%0A%60%60%60%0A%0A%23%23+Client+Snippet%0A%60%60%60ts%0A%2F%2F+PLEASE+FILL+YOUR+CODE+SNIPPET+HERE%0A%60%60%60%0A%0A%23%23+Schema%0A%60%60%60prisma%0A%2F%2F+PLEASE+ADD+YOUR+SCHEMA+HERE+IF+POSSIBLE%0A%60%60%60%0A%0A%23%23+Prisma+Engine+Query%0A%60%60%60%0A%7B%22X%22%3A%7B%7D%7D%0A%60%60%60%0A&title=PANIC%3A+called+%60Option%3A%3Aunwrap%28%29%60+on+a+%60None%60+value+in+query-engine%2Fconnectors%2Fmongodb-query-connector%2Fsrc%2Froot_queries%2Fread.rs%3A112%3A74&template=bug_report.md

If you want the Prisma team to look into it, please open the link above 🙏
To increase the chance of success, please post your schema and a snippet of
how you used Prisma Client in the issue. 

    at Object.logger (/private/var/folders/cj/2n9f0rqd3dlb55jhxd5gx0180000gn/T/AppTranslocation/0DAE9B4A-9F47-42F4-A3F1-3A69BBCD4A4D/d/Prisma Studio.app/Contents/Resources/app.asar/node_modules/@prisma/client/runtime/index.js:36229:30)
    at /private/var/folders/cj/2n9f0rqd3dlb55jhxd5gx0180000gn/T/AppTranslocation/0DAE9B4A-9F47-42F4-A3F1-3A69BBCD4A4D/d/Prisma Studio.app/Contents/Resources/app.asar/node_modules/@prisma/client/runtime/index.js:36198:34
prisma:client:fetcher Error: called `Option::unwrap()` on a `None` value
    at prismaGraphQLToJSError (/private/var/folders/cj/2n9f0rqd3dlb55jhxd5gx0180000gn/T/AppTranslocation/0DAE9B4A-9F47-42F4-A3F1-3A69BBCD4A4D/d/Prisma Studio.app/Contents/Resources/app.asar/node_modules/@prisma/client/runtime/index.js:35994:10)
    at Object.request (/private/var/folders/cj/2n9f0rqd3dlb55jhxd5gx0180000gn/T/AppTranslocation/0DAE9B4A-9F47-42F4-A3F1-3A69BBCD4A4D/d/Prisma Studio.app/Contents/Resources/app.asar/node_modules/@prisma/client/runtime/index.js:36358:17)
    at async cb (/private/var/folders/cj/2n9f0rqd3dlb55jhxd5gx0180000gn/T/AppTranslocation/0DAE9B4A-9F47-42F4-A3F1-3A69BBCD4A4D/d/Prisma Studio.app/Contents/Resources/app.asar/node_modules/@prisma/client/runtime/index.js:38673:26)
    at async PrismaClient._request (/private/var/folders/cj/2n9f0rqd3dlb55jhxd5gx0180000gn/T/AppTranslocation/0DAE9B4A-9F47-42F4-A3F1-3A69BBCD4A4D/d/Prisma Studio.app/Contents/Resources/app.asar/node_modules/@prisma/client/runtime/index.js:40853:18)
    at async $3615da8794764d66$var$PCW.request (/private/var/folders/cj/2n9f0rqd3dlb55jhxd5gx0180000gn/T/AppTranslocation/0DAE9B4A-9F47-42F4-A3F1-3A69BBCD4A4D/d/Prisma Studio.app/Contents/Resources/app.asar/node_modules/@prisma/studio-pcw/dist/index.js:395:45)
    at async IpcMainImpl.$5291d6b59ade0cdb$var$prisma (/private/var/folders/cj/2n9f0rqd3dlb55jhxd5gx0180000gn/T/AppTranslocation/0DAE9B4A-9F47-42F4-A3F1-3A69BBCD4A4D/d/Prisma Studio.app/Contents/Resources/app.asar/dist/main/index.js:195:31)
prisma:client:libraryEngine library is already stopping
prisma:client:libraryEngine library stopping
prisma:client:libraryEngine library stopped
prisma:client:libraryEngine requestBatch
prisma:client:libraryEngine library starting
prisma:client:libraryEngine library started
prisma:client:fetcher Error: called `Option::unwrap()` on a `None` value
    at prismaGraphQLToJSError (/private/var/folders/cj/2n9f0rqd3dlb55jhxd5gx0180000gn/T/AppTranslocation/0DAE9B4A-9F47-42F4-A3F1-3A69BBCD4A4D/d/Prisma Studio.app/Contents/Resources/app.asar/node_modules/@prisma/client/runtime/index.js:35994:10)
    at Object.requestBatch (/private/var/folders/cj/2n9f0rqd3dlb55jhxd5gx0180000gn/T/AppTranslocation/0DAE9B4A-9F47-42F4-A3F1-3A69BBCD4A4D/d/Prisma Studio.app/Contents/Resources/app.asar/node_modules/@prisma/client/runtime/index.js:36391:15)
prisma:client:fetcher Error: called `Option::unwrap()` on a `None` value
    at prismaGraphQLToJSError (/private/var/folders/cj/2n9f0rqd3dlb55jhxd5gx0180000gn/T/AppTranslocation/0DAE9B4A-9F47-42F4-A3F1-3A69BBCD4A4D/d/Prisma Studio.app/Contents/Resources/app.asar/node_modules/@prisma/client/runtime/index.js:35994:10)
    at Object.requestBatch (/private/var/folders/cj/2n9f0rqd3dlb55jhxd5gx0180000gn/T/AppTranslocation/0DAE9B4A-9F47-42F4-A3F1-3A69BBCD4A4D/d/Prisma Studio.app/Contents/Resources/app.asar/node_modules/@prisma/client/runtime/index.js:36391:15)
prisma:client:libraryEngine library stopping
prisma:client:libraryEngine library stopped
prisma:client:libraryEngine sending request, this.libraryStarted: false
prisma:client:libraryEngine library starting
prisma:client:libraryEngine library started
```

## Client Snippet
```ts
// create record - Insert
```

## Schema
```prisma

model DRecurso {
  id                String     @id @default(dbgenerated()) @map("_id") @db.ObjectId
  codigo            String?
  nome              String?
  situacao          String?
  tolerMais         Int?
  tolerMenos        Int?
  prVenda           Decimal?
  prCompra          Decimal?
  prCusto           Decimal?
  ncm               String?
  qdPorVol          Int?
  pesoLiquido       Decimal?
  pesoBruto         Decimal?
  qdeMinCompra      Int?
  localizacao       String?
  diasRessuprimento Int?
  observacao        String?
  pontoCritico      Boolean    @default(false)
  numeroSerie       String?
  ean               String?
  refFabrica        String?
  foto              String?
  modelo            String?
  diasEntrega       Int?
  diasLogistica     Int?
  marca             String?
  material          String?
  estoqueMinimo     Int?
  foraDeLinha       DateTime?
  confirmacao       DateTime?
  altura            Decimal?
  largura           Decimal?
  comprimento       Decimal?
  colecao           String?
  capacidade        String?
  funcionalidade    String?
  cest              String?
  cestDescricao     String?
  inativo           Boolean    @default(false)
  excluido          Boolean    @default(false)
  criadoEm          DateTime   @default(now())
  atualizadoEm      DateTime   @updatedAt
  idProcedencia     String?    @db.ObjectId
  Procedencia       DTabela?   @relation("Procedencia", fields: [idProcedencia], references: [id], onDelete: NoAction, onUpdate: NoAction)
  idCorRecurso      String?    @db.ObjectId
  CorRecurso        DTabela?   @relation("CorRecurso", fields: [idCorRecurso], references: [id], onDelete: NoAction, onUpdate: NoAction)
  idTamanho         String?    @db.ObjectId
  Tamanho           DTabela?   @relation("Tamanho", fields: [idTamanho], references: [id], onDelete: NoAction, onUpdate: NoAction)
  idUnidadeMedida   String?    @db.ObjectId
  UnidadeMedida     DTabela?   @relation("Unidade de Medida", fields: [idUnidadeMedida], references: [id], onDelete: NoAction, onUpdate: NoAction)
  idCadastrador     String?    @db.ObjectId
  Cadastrador       DEntidade? @relation("Cadastrador", fields: [idCadastrador], references: [id], onDelete: NoAction, onUpdate: NoAction)
  idForaDeLinhaInfo String?    @db.ObjectId
  ForaDeLinhaInfo   DEntidade? @relation("ForaDeLinhaInfo", fields: [idForaDeLinhaInfo], references: [id], onDelete: NoAction, onUpdate: NoAction)
  idInativador      String?    @db.ObjectId
  Inativador        DEntidade? @relation("Inativador", fields: [idInativador], references: [id], onDelete: NoAction, onUpdate: NoAction)
  idConfirmador     String?    @db.ObjectId
  Confirmador       DEntidade? @relation("Confirmador", fields: [idConfirmador], references: [id], onDelete: NoAction, onUpdate: NoAction)
  idFabricante      String?    @db.ObjectId
  Fabricante        DEntidade? @relation("Fabricante", fields: [idFabricante], references: [id], onDelete: NoAction, onUpdate: NoAction)
  idClasse          String?    @db.ObjectId
  Classe            DClasse?   @relation(fields: [idClasse], references: [id], onDelete: NoAction, onUpdate: NoAction)
  RecursoPedido     DPedido[]  @relation("RecursoPedido")

  Ncm DTabela[] @relation("Ncm")

  Recurso DTabela[] @relation("Recurso")

  DTabela          DTabela[]   @relation("NCM")
  DFator           DFator[]    @relation("DFatorRecurso")
  DMovDeposRecurso DMovDepos[] @relation("DMovDeposRecurso")

}
```

## Prisma Engine Query
```
Query:
{
  "modelName": "DRecurso",
  "operation": "findMany",
  "args": {
    "take": 100,
    "skip": 0,
    "select": {
      "id": true,
      "codigo": true,
      "nome": true,
      "situacao": true,
      "tolerMais": true,
      "tolerMenos": true,
      "prVenda": true,
      "prCompra": true,
      "prCusto": true,
      "ncm": true,
      "qdPorVol": true,
      "pesoLiquido": true,
      "pesoBruto": true,
      "qdeMinCompra": true,
      "localizacao": true,
      "diasRessuprimento": true,
      "observacao": true,
      "pontoCritico": true,
      "numeroSerie": true,
      "ean": true,
      "refFabrica": true,
      "foto": true,
      "modelo": true,
      "diasEntrega": true,
      "diasLogistica": true,
      "marca": true,
      "material": true,
      "estoqueMinimo": true,
      "foraDeLinha": true,
      "confirmacao": true,
      "altura": true,
      "largura": true,
      "comprimento": true,
      "colecao": true,
      "capacidade": true,
      "funcionalidade": true,
      "cest": true,
      "cestDescricao": true,
      "inativo": true,
      "excluido": true,
      "criadoEm": true,
      "atualizadoEm": true,
      "idProcedencia": true,
      "Procedencia": true,
      "idCorRecurso": true,
      "CorRecurso": true,
      "idTamanho": true,
      "Tamanho": true,
      "idUnidadeMedida": true,
      "UnidadeMedida": true,
      "idCadastrador": true,
      "Cadastrador": true,
      "idForaDeLinhaInfo": true,
      "ForaDeLinhaInfo": true,
      "idInativador": true,
      "Inativador": true,
      "idConfirmador": true,
      "Confirmador": true,
      "idFabricante": true,
      "Fabricante": true,
      "idClasse": true,
      "Classe": true,
      "RecursoPedido": true,
      "Ncm": true,
      "Recurso": true,
      "DTabela": true,
      "DFator": true,
      "DMovDeposRecurso": true
    }
  }
}
  
```

**Comment by Jolg42** [comment] 2022-09-05 09:26
Since your report, MongoDB support was released in GA
https://www.prisma.io/blog/mongodb-general-availability-pixnun6mffmu
https://github.com/prisma/prisma/releases/tag/3.12.0
If this is still reproducible with a newer version, we can reopen this.

**Closed by Jolg42** 2022-09-05 09:26 UTC
Labels: bug/0-unknown, kind/bug, tech/engines, team/client, topic: basic error report, topic: mongodb, priority/high, size/s
