### ISSUE TITLE
Slow start: `require("@prisma/client")` takes 5-8 seconds on Google Cloud Run

### ISSUE THREAD

**Issue by renchap** [prisma/prisma#12132] opened 2022-03-03 10:16 UTC
### Bug description

We are looking to migrate some of our apps to Google Cloud Run (Container as a Service). In doing so, we noticed that Cloud Run sometimes marks the deployment as failed because the container takes too much time to start.

I started instrumenting our app startup times with [Honeycomb](https://www.honeycomb.io) and noticed that our database initialisation function takes a big part of the startup time.

After instrumenting it further, we noticed that `require("@prisma/client")` takes between 5 and 8 seconds.

On our local dev machines (macbook pro M1) it is much quicker, but our Cloud Run containers only have 1 core and I suspect that they dont have as much CPU power available.

### How to reproduce

I am using `async import` to first import and configure Prisma, then import and launch the remaining of our app (express/GraphQL NodeJS app).

I can not share the real code, but it is similar to this:

```ts
async function initDB() {
    const span = startSpan("app.startup.initDB", { service })

    const prismaRequireSpan = startSpan("app.get_dbs.prisma_require")
    const { PrismaClient } = require("@prisma/client")
    finishSpan(prismaRequireSpan)

    const newPrismaSpan = startSpan("app.get_dbs.new_prisma_client")
    const prismaClient = new PrismaClient({ datasources: { db: { url } } })
    finishSpan(newPrismaSpan)

    finishSpan(span)
}

function start() {
    const startupTrace = startTrace("app.startup")

    // First, we initialize Prisma and the DB connections
    // This allows us to require and initialize Prisma and the DB pools before
    // application code is loaded, so we can instrument this part
    initDB()
        .then(() => import("./app"))
        .then(({ startServer }) => startServer())
        .then(() => {
           finishTrace(startupTrace)
        })
}

start()
```

Here is a sample resulting trace:
<img width="1207" alt="image" src="https://user-images.githubusercontent.com/42070/156543718-f044f0d0-592a-4c38-aa6a-702cdeeb83a9.png">

I am not sure where those `execFile` calls come from (something called when instantiating a new Prisma client), , but they execute these 2 commands:
- `openssl version -v`
- ` ls -l /lib64 | grep ssl;  ls -l /usr/lib64 | grep ssl;`

I am also unsure why they take this long, but I suspect our Node event loop is saturated during the app startup, I do not know (yet) if this is caused by Prisma starting up or by some other application code.

### Expected behavior

Importing Prisma should not take this long to be imported

### Prisma information

We are running an old Prisma version but @janpio told me to post this report anyway. We plan to upgrade to Prisma 3 soon.

Our prisma schema is:
- 1674 lines long
- 74 models
- 10 enums

Our `.prisma/client/index.js` file is 9.5MB, and the DMMF string is a bit less than 10M characters long:
```
grep "const dmmfString" node_modules/.prisma/client/index.js | wc -c
 9 864 027
```

### Environment & setup

- OS: Google Cloud Run containers
- Database: PostgreSQL
- Node.js version: 16.13

### Prisma Version

```
prisma               : 2.28.0
@prisma/client       : 2.28.0
Current platform     : darwin
Query Engine         : query-engine 89facabd0366f63911d089156a7a70125bfbcd27 (at node_modules/@prisma/engines/query-engine-darwin)
Migration Engine     : migration-engine-cli 89facabd0366f63911d089156a7a70125bfbcd27 (at node_modules/@prisma/engines/migration-engine-darwin)
Introspection Engine : introspection-core 89facabd0366f63911d089156a7a70125bfbcd27 (at node_modules/@prisma/engines/introspection-engine-darwin)
Format Binary        : prisma-fmt 89facabd0366f63911d089156a7a70125bfbcd27 (at node_modules/@prisma/engines/prisma-fmt-darwin)
Default Engines Hash : 89facabd0366f63911d089156a7a70125bfbcd27
Studio               : 0.417.0
```

**Comment by janpio** [comment] 2022-03-04 15:55
Internal note: The affected schema has been provided in private. It can be found in the usual location.

**Comment by tgensol** [comment] 2022-06-24 09:46
any update on this one ?

**Comment by janpio** [comment] 2023-03-29 22:49
Our `jsonProtocol` preview feature should have _significant_ impact here @renchap: https://github.com/prisma/prisma/issues/18095 Can you maybe test this out and compare it to what you are/were seeing? That would be amazing.

**Comment by janpio** [comment] 2023-04-25 13:08
Although I could never fully reproduce the actualy 5-8 seconds on Google Cloud Run, there is no question older versions of Prisma had a significant problem with bigger schemas. As we wrote in the [blog post](https://www.prisma.io/blog/prisma-and-serverless-73hbgKnZ6t) we made real progress here, and I thought it would be worth to revisit this reproduction.

I used the schema file you provided us @renchap (1674 lines, 74 models).
I created a small script that runs the typical code you have using Prisma Client (require, constructor, opening the connection, and running a query) and measures the time it takes for each of those steps to be executed.
```
async function main() {

    const time_1 = performance.now()
    const { PrismaClient } = require('@prisma/client')
    const time_2 = performance.now()
    const prisma = new PrismaClient()
    const time_3 = performance.now()
    await prisma.$connect()
    const time_4 = performance.now()
    // prisma.ads.findMany() wrapped in try-catch block
    try {
        const data = await prisma.ads.findMany()
    } catch (e) {
        console.log(e)
    }
    const time_5 = performance.now()

    // console.log(time_1, time_2, time_3, time_4, time_5)
    const timings = {
        require: time_2 - time_1,
        constructor: time_3 - time_2,
        connect: time_4 - time_3,
        query: time_5 - time_4
    }
    console.log(timings)
}

main()
  .then(async () => {
  })
  .catch(async (e) => {
    console.error(e)
    process.exit(1)
  })
```
Then I ran this script for your original version 2.28.0, added 3.0.1 (as because of some local IPv6 problem the oldest version could not even run the query any more), then the current 4.13.0, 4.13.0 with the `jsonProtocol` preview feature and our current `dev` version (`4.14.0-dev.16`, will be released with 4.14.0 in a few weeks). The results are pretty nice:
<img width="659" alt="image" src="https://user-images.githubusercontent.com/183673/234280802-8c7b23fb-3d70-4d4a-8bdb-c85e1a123a35.png">
This issue is about the blue bars - and we already got rid 4/5 of it. We will continue optimizing that further.

(Note these are not averages, but randomly selected individual runs from my local machine - so concrete difference <50ms can also just be noise. The result still stays the same fortunately. Also, yellow and green are super wide because I was testing with a database in the US while I am in EU myself. With a real local database, the connection and query are of course much faster.)

**Comment by renchap** [comment] 2023-04-25 21:33
Hi @janpio and thanks a lot for your work on this, as for your detailed answer!

We tried enabling `jsonProtocol` on our containers, but did not see a real effect, which is consistent with your tests.

I did not profile our app startup for some time, but the cold boot are much faster now than before. I will see if I can gather some data on what the startup times are for Prisma in our app (compared to the full startup time), but I suspect they are much better than in 2.28.0 when I initially reported it.

**Comment by janpio** [comment] 2023-05-26 00:12
I am closing this issue for now. 

We further improved the cold start time after our blog post and my comment here, and are now generally happy with the cold start time even with massive schemas. `jsonProtocol` will soon be promoted to GA, and with that the default experience of using Prisma should have no negative impacts on cold starts in serverless environments any more compared to other database Clients.

If someone thinks their app still has slow cold start times, please open a new issue and we will be happy to take a look and figure out what is happening. Thanks!

**Closed by janpio** 2023-05-26 00:12 UTC
Labels: bug/1-unconfirmed, kind/bug, topic: performance, topic: dmmf, tech/typescript, team/client, topic: google cloud, topic: Google Cloud Run
