### ISSUE TITLE
spacing during a postgresql text search

### ISSUE THREAD

**Issue by wowowooooo** [prisma/prisma#10481] opened 2021-11-29 08:57 UTC
### Bug description

I got an error when sending a full text search query that contains spaces

### How to reproduce

ConnectorError(ConnectorError { user_facing_error: None, kind: QueryError(Error { kind: Db, cause: Some(DbError { severity: "ERROR", parsed_severity: Some(Error), code: SqlState("42601"), message: ": \"Discord Nitro\"", detail: None, hint: None, position: None, where_: None, schema: None, table: None, column: None, datatype: None, constraint: None, file: Some("tsquery.c"), line: Some(723), routine: Some("makepol") }) }) })

### Environment & setup

- OS: 
- Database: 
- Node.js version: 

### Prisma Version

```
Environment variables loaded from .env
prisma                  : 3.5.0
@prisma/client          : 3.5.0
Current platform        : windows
Query Engine (Node-API) : libquery-engine 78a5df6def6943431f4c022e1428dbc3e833cf8e (at node_modules\@prisma\engines\query_engine-windows.dll.node)
Migration Engine        : migration-engine-cli 78a5df6def6943431f4c022e1428dbc3e833cf8e (at node_modules\@prisma\engines\migration-engine-windows.exe)
Introspection Engine    : introspection-core 78a5df6def6943431f4c022e1428dbc3e833cf8e (at node_modules\@prisma\engines\introspection-engine-windows.exe)
Format Binary           : prisma-fmt 78a5df6def6943431f4c022e1428dbc3e833cf8e (at node_modules\@prisma\engines\prisma-fmt-windows.exe)
Default Engines Hash    : 78a5df6def6943431f4c022e1428dbc3e833cf8e
Studio                  : 0.439.0
Preview Features        : fullTextSearch, interactiveTransactions
```

**Comment by pantharshit00** [comment] 2021-11-29 11:49
Hello @wowowooooo 

The full text search API uses the postgres filters under the hood to allow for flexibility. You will need to sanitize the input manually if you want to search with input having space. Here is an example on how you can do that: 

```ts
const results = await prisma.post.findMany({
  where: {
    body: {
      search: "second post".split(" ").join(" & "),
    },
  },
});
```

Here is an proposal on making this API more user friendly: https://github.com/prisma/prisma/issues/8939

I will close this ticket as a duplicate of the above issue.

**Closed by pantharshit00** 2021-11-29 11:49 UTC
Labels: kind/bug

**Comment by RockLloque** [comment] 2022-11-22 11:09
If you want to search only for words in the **exact** order I recommend the postgres `proximity operator`. 
```js
const results = await prisma.post.findMany({
  where: {
    body: {
      search: "second post".split(" ").join(" <-> "),
    },
  },
});
```
