### ISSUE TITLE
Updater function to the update method that would receive the old value as a parameter

### ISSUE THREAD

**Issue by jvzaniolo** [prisma/prisma#14068] opened 2022-06-30 00:28 UTC
## Problem

I would like to not do so many requests just to increment the item `quantity` if it already exists

```js
const cart = await prisma.cart.findFirst({
  where: { userId: user.id },
  select: { id: true },
})

if (!cart) throw new Error('Cart not found')

/* I couldn't get this to work */

// await prisma.$executeRaw`
//   INSERT INTO CartItem(userId, cartId, productId, quantity)
//   VALUES (${user.id}, ${cart.id}, ${input.productId}, ${input.quantity})
//   ON DUPLICATE KEY UPDATE quantity = quantity + ${input.quantity};
// `
//
// return await prisma.cart.findFirst({
//   where: { userId: user.id },
//   include: { cartItems: { product: true } },
// )}

const hasCartItem = await prisma.cartItem.findFirst({
  where: { productId: input.productId, cartId: cart.id },
  select: { quantity: true },
})

if (hasCartItem) {
  return await prisma.cart.update({
    where: { userId: user.id },
    data: {
      items: {
        update: {
          where: { productId: input.productId },
          data: { quantity: hasCartItem.quantity + input.quantity },
        },
      },
    },
    include: { items: { include: { product: true } } },
  })
}

return await prisma.cart.update({
  where: { userId: user.id },
  data: {
    items: {
      create: {
        userId: user.id,
        productId: input.productId,
        quantity: input.quantity,
      },
    },
  },
  include: { items: { include: { product: true } } },
})
```

## Suggested solution

It would be nice if we could also send an updater function to the `update` method that receives the old value as a parameter and return a new one

```js
// Insert an item to the cart if it doesn't exist, or else increment its quantity

return await prisma.cart.update({
  where: { userId: user.id },
  data: {
    cartItems: {
      upsert: {
        where: { productId: input.productId },
        update: { quantity: old => old + input.quantity },
        create: { productId: input.productId, quantity: input.quantity },
      },
    },
  },
  include: { items: { include: { product: true } } },
})
```

## Or more explicit

```js
// Insert an item to the cart, on duplicate key increment its quantity

return await prisma.cart.update({
  where: { userId: user.id },
  data: {
    cartItems: {
      create: {
        userId: user.id,
        productId: input.productId,
        quantity: input.quantity,
      },
      onDuplicateKey: { // or just `onDuplicate: ` or `duplicate: `
        update: {
          quantity: old => old + input.quantity,
        },
      },
    },
  },
  include: { items: { include: { product: true } } },
})
```

**Comment by janpio** [comment] 2024-02-08 21:22
The code examples here are super hard to understand, but I think this is effectively a duplicate of https://github.com/prisma/prisma/issues/9941 - so I am closing the issue. Thanks for opening it back in the day!

**Closed by janpio** 2024-02-08 21:22 UTC
Labels: kind/feature, team/client
