### ISSUE TITLE
Panic when trying to use Uuid native type with insensitive filters

### ISSUE THREAD

**Issue by pantharshit00** [prisma/prisma#5311] opened 2021-01-27 19:14 UTC
## Bug description

When the following query where `id` is `@postgres.Uuid` type is executed prisma is throwing the following panic:

```ts
 const data = await prisma.user.findMany({
    where: {
      id: {
        mode: "insensitive",
        contains: "something",
      },
    },
  });
```
```
(node:9993) UnhandledPromiseRejectionWarning: Error:
Invalid `prisma.user.findMany()` invocation:


  Error occurred during query execution:
ConnectorError(ConnectorError { user_facing_error: None, kind: QueryError(Error { kind: Db, cause: Some(DbError { severity: "ERROR", parsed_severity: Some(Error), code: SqlState("42883"), message: "function lower(uuid) does not exist", detail: None, hint: Some("No function matches the given name and argument types. You might need to add explicit type casts."), position: Some(Original(105)), where_: None, schema: None, table: None, column: None, datatype: None, constraint: None, file: Some("parse_func.c"), line: Some(627), routine: Some("ParseFuncOrColumn") }) }) })
    at PrismaClientFetcher.request (/home/harshit/code/reproductions/issue-3447-studio/node_modules/@prisma/client/runtime/index.js:78461:15)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at main (/home/harshit/code/reproductions/issue-3447-studio/main.ts:6:16)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:9993) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:9993) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

## How to reproduce

See: https://github.com/harshit-test-org/issue-prisma-5311

## Expected behavior

Prisma should not ever generate this invalid sql. 

## Prisma information

See the reproduction posted above

## Environment & setup

- OS: Ubuntu 20.04 via WSL
- Database: Postgres 12 (docker)
- Node.js version: 14.15.2
- Prisma version:

```
@prisma/cli          : 2.16.0-dev.23
@prisma/client       : 2.16.0-dev.25
Current platform     : debian-openssl-1.1.x
Query Engine         : query-engine 874f616fce40a665d24867f42e602ce8b5ed2cd7 (at node_modules/@prisma/engines/query-engine-debian-openssl-1.1.x)
Migration Engine     : migration-engine-cli 874f616fce40a665d24867f42e602ce8b5ed2cd7 (at node_modules/@prisma/engines/migration-engine-debian-openssl-1.1.x)
Introspection Engine : introspection-core 874f616fce40a665d24867f42e602ce8b5ed2cd7 (at node_modules/@prisma/engines/introspection-engine-debian-openssl-1.1.x)
Format Binary        : prisma-fmt 874f616fce40a665d24867f42e602ce8b5ed2cd7 (at node_modules/@prisma/engines/prisma-fmt-debian-openssl-1.1.x)
Studio               : 0.343.0
Preview Features     : nativeTypes
```

**Comment by lifedup** [comment] 2021-01-28 23:11
I also get the same error when filtering a uuid column in Prisma Studio.

**Comment by Weakky** [comment] 2021-02-08 13:42
We're not yet in a position to fix that issue. We'll get back to it once the Query Engine can deal with native types more granularly.

**Comment by matthewmueller** [comment] 2021-02-08 13:46
To elaborate on @Weakky's comment. We use the underlying database as much as possible. For Postgres, the query would look like this:

```sql
select * from users where id = lower($1::uuid)
```

Unfortunately `lower` does not accept a `uuid` as an input. In the future, we may disable this API, but we're not there yet.

**Comment by pantharshit00** [comment] 2021-05-04 15:38
This is still reproducible in 2.22.

**Comment by Jolg42** [comment] 2022-09-07 12:41
Can reproduce in our internal dev version `4.4.0-dev.30`

Note: The message is now different
```
ts-node main.ts    
/Users/j42/Repros/5311/node_modules/@prisma/client/runtime/index.js:30854
      throw new PrismaClientUnknownRequestError(message, this.client._clientVersion);
            ^
PrismaClientUnknownRequestError: 
Invalid `prisma.user.findMany()` invocation in
/Users/j42/Repros/5311/main.ts:6:34

  3 async function main() {
  4   const prisma = new PrismaClient();
  5 
→ 6   const data = await prisma.user.findMany(
Error occurred during query execution:
ConnectorError(ConnectorError { user_facing_error: None, kind: QueryError(Error { kind: Db, cause: Some(DbError { severity: "ERROR", parsed_severity: Some(Error), code: SqlState(E42883), message: "operator does not exist: uuid ~~* unknown", detail: None, hint: Some("No operator matches the given name and argument type(s). You might need to add explicit type casts."), position: Some(Original(126)), where_: None, schema: None, table: None, column: None, datatype: None, constraint: None, file: Some("parse_oper.c"), line: Some(728), routine: Some("op_error") }) }) })
    at RequestHandler.handleRequestError (/Users/j42/Repros/5311/node_modules/@prisma/client/runtime/index.js:30854:13)
    at RequestHandler.request (/Users/j42/Repros/5311/node_modules/@prisma/client/runtime/index.js:30833:12)
    at async PrismaClient._request (/Users/j42/Repros/5311/node_modules/@prisma/client/runtime/index.js:31805:16)
    at async main (/Users/j42/Repros/5311/main.ts:6:16) {
  clientVersion: '4.4.0-dev.30'
}
```

**Comment by Jolg42** [comment] 2022-10-21 09:27
This issue was a duplicate of https://github.com/prisma/prisma/issues/9007

**Closed by Jolg42** 2022-10-21 09:27 UTC
Labels: bug/2-confirmed, kind/bug, topic: native database types, team/client, topic: postgresql, topic: uuid
