### ISSUE TITLE
SyntaxError: ';' expected on Typescript Client when missing ID

### ISSUE THREAD

**Issue by louisrli** [prisma/prisma#4837] opened 2019-08-21 15:06 UTC
**Describe the bug**
Typescript client generation fails for GraphQL types that are missing an @ID field. It's unclear whether this is a documentation error or an actual bug. As far as I can tell after perusing the Prisma docs, an ID field is a system field but it's not supposed to be required.

Also see:
https://github.com/prisma/prisma/issues/4578

**To Reproduce**
0. Define a type without an ID
1. Notice that the generated typescript type has `export type MyTypeOrderByInput =`, notably with no text afterwards.
2. In the example below, ClozePiece and ContentPiece are missing IDs, while Flashcard has an ID type. One can see the difference between the generated code that results in a syntax error.
```
[louis@varnothing gql] (master↑2|✚3…)$ prisma generate                                         (0) ~/branches/srs/gql
Generating schema... 52ms                                                                                             SyntaxError: ';' expected. (158:8)
  156 | export type ClozePieceOrderByInput =                                                                            157 |
> 158 | export type ContentPieceOrderByInput =
      |        ^                                                                                                        159 |
  160 | export type FlashcardOrderByInput =   'id_ASC' |                                                                161 |   'id_DESC'
```

**Expected behavior**
I expected it to generate without having to require an ID or for the documentation to explicitly say that an ID field is required in order for the generated code to work. For example, this doc says nothing about the ID field being required.

https://www.prisma.io/docs/1.34/datamodel-and-migrations/datamodel-POSTGRES-knum/#id
**Screenshots**

**Versions (please complete the following information):**
 - Connector: Postrges
- Prisma CLI version: prisma/1.34.6 (darwin-x64) node-v12.8.0
 - OS: mac

**Comment by louisrli** [comment] 2019-08-21 15:11
Same thing happens if you generate for the JS client too.

**Comment by pantharshit00** [comment] 2019-08-23 19:04
Duplicate of #4578 

Please comment on that issue, don't open a new issue for the same problem.

**Closed by pantharshit00** 2019-08-23 19:04 UTC
