### ISSUE TITLE
Filters max size is exceeded

### ISSUE THREAD

**Issue by oceandrama** [prisma/prisma#13457] opened 2022-05-23 16:58 UTC
### Bug description

The code below works well:
```ts
const ids = new Array(32768 - 2).fill(0).map((_, i) => i); // 2^15-2

const count = await prisma.user.count({
  where: { id: { in: ids } }
});
```
But if you increase array size to `2^15 - 1` it throws the error:
```
Can't reach database server at `localhost`:`5432`
```
Is it known Prisma limitation?

### How to reproduce

1. Create any database using prisma even without data
2. Execute the code above

### Environment & setup

- OS: Linux
- Database: PostgreSQL
- Node.js version: 16.14.2

### Prisma Version

```
3.14.0
```

**Comment by pantharshit00** [comment] 2022-05-27 15:17
Can you share you schema? I think you might not be using `BigInt` type for IDs which is the type which you wanna use if you want to deal with large integers.

**Comment by oceandrama** [comment] 2022-05-27 15:35
@pantharshit00 It's true, I'm using `Int` for `id` field
```
model User {
  id Int @id @default(autoincrement())
```
But the problem persists even I fill array with ones:
```
const ids = new Array(32768 - 2).fill(1);
```
`Int` should handle so small values, right?

**Comment by oceandrama** [comment] 2022-06-12 15:27
@pantharshit00 Hi! Do you have any updates on this?

**Comment by garrensmith** [comment] 2022-07-01 13:41
@oceandrama we will look into this. It does seem like a bug. We typically try batch queries with a lot of parameters.

**Comment by aqrln** [comment] 2022-09-02 10:26
Related: https://github.com/prisma/prisma/issues/11950, https://github.com/prisma/prisma/issues/13704

**Comment by Jolg42** [comment] 2022-09-07 12:13
Can reproduce on our internal dev version `4.4.0-dev.30` with 
```
  const ids = new Array(32768 - 1).fill(0).map((_, i) => i);
  const count = await prisma.user.count({
    where: { id: { in: ids } },
  });
  console.log({ count });
```

**Comment by jkomyno** [comment] 2022-09-23 15:34
Thank you for this issue. This is a duplicate of #8832. In the example query above, we're hitting the maximum allowed number of bind variables in a prepared statement supported by the Postgres driver we're using (the driver's limit is `32767`).

**Closed by jkomyno** 2022-09-23 15:34 UTC
Labels: bug/2-confirmed, kind/bug, tech/engines, team/client, topic: (Misleading) Can't reach database server at
