### ISSUE TITLE
Prisma Migrate not working with local postgres database but with docker postgres

### ISSUE THREAD

**Issue by sdoering01** [prisma/prisma#5303] opened 2021-01-27 14:18 UTC
Hi Prisma Team! Prisma Migrate just crashed. 

## Versions
      
| Name        | Version            |
|-------------|--------------------|
| Platform    | debian-openssl-1.1.x| 
| Node        | v14.15.4           | 
| Prisma CLI  | 2.15.0             | 
| Binary      | e51dc3b5a9ee790a07104bec1c9477d51740fe54| 

## Error
```
Error: Error in migration engine.
Reason: [/root/.cargo/git/checkouts/quaint-9f01e008b9a89c14/2d8c9c7/src/connector/postgres/error.rs:138:29] index out of bounds: the len is 1 but the index is 1

Please create an issue in the migrate repo with
your `schema.prisma` and the prisma command you tried to use 🙏:
https://github.com/prisma/prisma/issues/new

```

I followed the getting started guide (https://www.prisma.io/docs/getting-started/setup-prisma/start-from-scratch-typescript-postgres) and got the error above when running the mentioned command `npx prisma migrate dev --name init --preview-feature`.

This occured when using a fresh postgres database on my local computer. I tried the same using a postgres docker container (created with `docker run --name prisma-test -e POSTGRES_PASSWORD=postgres -p 5433:5432 -d postgres:11`), which worked. For the tests I only exchanged the connection url in the .env file. I used version 11 of postgresql for both the local and the docker test.

**Comment by tomhoule** [comment] 2021-01-28 10:05
Hi @sdoering01 , thanks for reporting this! I am pretty sure this is a duplicate of https://github.com/prisma/prisma/issues/4606, it's a known problem we are working on, let's track progress on a fix there.

**Closed by tomhoule** 2021-01-28 10:05 UTC

**Comment by sdoering01** [comment] 2021-01-28 10:41
Ok, I searched the internet before too, but thought that it would be nice to know that it works with a postgres docker container. Will mention it in the other issue. Thanks
