### ISSUE TITLE
PANIC in query-engine/core/src/interpreter/query_interpreters/nested_read.rs:78:561

### ISSUE THREAD

**Issue by scriptcoded** [prisma/prisma#5368] opened 2021-01-31 13:41 UTC
**Note:** I've attached our complete schema file, in case there's anything interfering that I don't understand. The TypeScript is the minimum query I could use to reproduce the error. If you need more info, just shout!

Hi Prisma Team! My Prisma Client just crashed. This is the report:
## Versions

| Name            | Version            |
|-----------------|--------------------|
| Node            | v14.15.2           | 
| OS              | debian-openssl-1.1.x|
| Prisma Client   | 2.15.0             |
| Query Engine    | query-engine e51dc3b5a9ee790a07104bec1c9477d51740fe54|
| Database        | undefined|

## Query
```
query {
  findManyShippingZone {
    id
    createdAt
    updatedAt
    name
    countries {
      id
    }
  }
}
```

## Logs
```
.js:26465:16)
  engine     at LineStream.<anonymous> (/home/scriptcoded/hdd/projects/puntobasta/adora/packages/backend/node_modules/@prisma/client/runtime/index.js:26760:24)
  engine     at LineStream.emit (events.js:315:20)
  engine     at LineStream.EventEmitter.emit (domain.js:467:12)
  engine     at addChunk (internal/streams/readable.js:309:12)
  engine     at readableAddChunk (internal/streams/readable.js:284:9)
  engine     at LineStream.Readable.push (internal/streams/readable.js:223:10)
  engine     at LineStream.Transform.push (internal/streams/transform.js:166:32)
  engine     at LineStream._pushBuffer (/home/scriptcoded/hdd/projects/puntobasta/adora/packages/backend/node_modules/@prisma/client/runtime/index.js:23721:19)  {"timestamp":"Jan 31 14:38:35.629","level":"ERROR","fields":{"message":"PANIC","reason":"1","file":"query-engine/core/src/interpreter/query_interpreters/nested_read.rs","line":78,"column":56},"target":"query_engine"}  
  engine {
  engine   error: SocketError: other side closed
  engine       at Socket.onSocketEnd (/home/scriptcoded/hdd/projects/puntobasta/adora/packages/backend/node_modules/@prisma/client/runtime/index.js:24857:25)
  engine       at Socket.emit (events.js:327:22)
  engine       at Socket.EventEmitter.emit (domain.js:467:12)
  engine       at endReadableNT (internal/streams/readable.js:1327:12)
  engine       at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  engine     code: 'UND_ERR_SOCKET'
  engine   }
  engine }  
  engine {
  engine   cwd: '/home/scriptcoded/hdd/projects/puntobasta/adora/packages/backend/prisma'
  engine }  
  engine Search for Query Engine in /home/scriptcoded/hdd/projects/puntobasta/adora/packages/backend/node_modules/.prisma/client  
  plusX Execution permissions of /home/scriptcoded/hdd/projects/puntobasta/adora/packages/backend/node_modules/.prisma/client/query-engine-debian-openssl-1.1.x are fine  
  engine { flags: [ '--enable-raw-queries' ] }  
  engine port: 34107  
  engine Client Version: 2.15.0  
  engine Engine Version: query-engine e51dc3b5a9ee790a07104bec1c9477d51740fe54  
  engine Active provider: postgresql  
  engine stdout  Starting a postgresql pool with 13 connections.  
  engine stdout  Started http server on http://127.0.0.1:34107  
  engine Search for Query Engine in /home/scriptcoded/hdd/projects/puntobasta/adora/packages/backend/node_modules/.prisma/client  
  plusX Execution permissions of /home/scriptcoded/hdd/projects/puntobasta/adora/packages/backend/node_modules/.prisma/client/query-engine-debian-openssl-1.1.x are fine  
  engine stdout  PANIC in query-engine/core/src/interpreter/query_interpreters/nested_read.rs:78:56
1  
  engine TypeError: this.currentRequestPromise.cancel is not a function
  engine     at NodeEngine.handlePanic (/home/scriptcoded/hdd/projects/puntobasta/adora/packages/backend/node_modules/@prisma/client/runtime/index.js:26519:36)
  engine     at NodeEngine.setError (/home/scriptcoded/hdd/projects/puntobasta/adora/packages/backend/node_modules/@prisma/client/runtime/index.js:26465:16)
  engine     at LineStream.<anonymous> (/home/scriptcoded/hdd/projects/puntobasta/adora/packages/backend/node_modules/@prisma/client/runtime/index.js:26760:24)
  engine     at LineStream.emit (events.js:315:20)
  engine     at LineStream.EventEmitter.emit (domain.js:467:12)
  engine     at addChunk (internal/streams/readable.js:309:12)
  engine     at readableAddChunk (internal/streams/readable.js:284:9)
  engine     at LineStream.Readable.push (internal/streams/readable.js:223:10)
  engine     at LineStream.Transform.push (internal/streams/transform.js:166:32)
  engine     at LineStream._pushBuffer (/home/scriptcoded/hdd/projects/puntobasta/adora/packages/backend/node_modules/@prisma/client/runtime/index.js:23721:19)  {"timestamp":"Jan 31 14:38:35.721","level":"ERROR","fields":{"message":"PANIC","reason":"1","file":"query-engine/core/src/interpreter/query_interpreters/nested_read.rs","line":78,"column":56},"target":"query_engine"}  
  engine {
  engine   error: SocketError: other side closed
  engine       at Socket.onSocketEnd (/home/scriptcoded/hdd/projects/puntobasta/adora/packages/backend/node_modules/@prisma/client/runtime/index.js:24857:25)
  engine       at Socket.emit (events.js:327:22)
  engine       at Socket.EventEmitter.emit (domain.js:467:12)
  engine       at endReadableNT (internal/streams/readable.js:1327:12)
  engine       at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  engine     code: 'UND_ERR_SOCKET'
  engine   }
  engine }  
```

## Client Snippet
```ts
const shippingZones = await ctx.db.shippingZone.findMany({
  include: {
    countries: {
      select: {
        id: true
      }
    }
  }
})
```

## Schema
```prisma
datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

generator client {
  provider = "prisma-client-js"
  previewFeatures = ["nativeTypes"]
}

enum WeightUnit {
  GRAM
  KILOGRAM
}

enum Role {
  ADMIN
  CUSTOMER
}

enum CustomerType {
  RETAIL
  WHOLESALE
}

enum ShippingConditionField {
  WEIGHT
  SUBTOTAL
  CUSTOMER_TYPE
}

enum ConditionComparison {
  EQUAL
  NOT_EQUAL
  GREATER_THAN
  GREATER_THAN_OR_EQUAL
  LESS_THAN
  LESS_THAN_OR_EQUAL
}

model User {
  id            String       @id @default(cuid())
  createdAt     DateTime     @default(now())
  updatedAt     DateTime     @updatedAt()

  email         String       @unique
  givenName     String
  familyName    String
  password      String
  role          Role         @default(CUSTOMER)
  customerType  CustomerType @default(RETAIL)

  cartItems     CartItem[]
}

model CartItem {
  createdAt   DateTime    @default(now())
  updatedAt   DateTime    @updatedAt()

  product     Product @relation(fields: [productId], references: [id])
  productId   String
  quantity    Int

  user        User     @relation(fields: [userId], references: [id])
  userId      String

  @@id([userId, productId])
}


model Collection {
  id            String      @id @default(cuid())
  publicId      Int         @unique @default(autoincrement())
  createdAt     DateTime    @default(now())
  updatedAt     DateTime    @updatedAt()

  translations  CollectionTranslation[]

  parent        Collection?   @relation("CollectionHierarchy", fields: [parentId], references: [id])
  parentId      String?
  children      Collection[]  @relation("CollectionHierarchy")
  products      Product[]
}
model CollectionTranslation {
  createdAt    DateTime    @default(now())
  updatedAt    DateTime    @updatedAt()

  collection   Collection  @relation(fields: [modelId], references: [id])
  modelId      String
  language     String

  name         String
  slug         String
  description  String?

  @@id([modelId, language])
}

model Product {
  id           String      @id @default(cuid())
  publicId     Int         @unique @default(autoincrement())
  createdAt    DateTime    @default(now())
  updatedAt    DateTime    @updatedAt()

  translations     ProductTranslation[]

  price            Decimal      @db.Decimal(12, 2)
  comparePrice     Decimal?     @db.Decimal(12, 2)
  vat              Int?
  isWholesale      Boolean      @default(false)
  wholesaleMinQty  Int          @default(1)
  weight           Int?
  weightUnit       WeightUnit   @default(GRAM)
  discountable     Boolean      @default(true)
  type             ProductType?
  tags             ProductTag[]
  vendor           Vendor?
  collections      Collection[]
  keepStock        Boolean      @default(false)
  allowOverdraft   Boolean      @default(false)
  stockQty         Int          @default(0)
  buyCount         Int          @default(0)

  sku              String?
  published        Boolean      @default(false)

  images           ProductImage[]

  users            CartItem[]
}
model ProductTranslation {
  createdAt    DateTime    @default(now())
  updatedAt    DateTime    @updatedAt()

  product      Product     @relation(fields: [modelId], references: [id])
  modelId      String
  language     String

  name         String
  slug         String
  description  String @default("")

  @@id([modelId, language])
}

model ProductImage {
  id            String      @id @default(cuid())
  createdAt     DateTime    @default(now())
  updatedAt     DateTime    @updatedAt()
  
  filename      String      @unique
  sizes         String[]
  orderNo       Int         @default(-1)

  product       Product?    @relation(fields: [productId], references: [id])
  productId     String?
}

model ProductType {
  id            String      @id @default(cuid())
  createdAt     DateTime    @default(now())
  updatedAt     DateTime    @updatedAt()

  translations  ProductTypeTranslation[]
}
model ProductTypeTranslation {
  createdAt    DateTime    @default(now())
  updatedAt    DateTime    @updatedAt()

  productType  ProductType @relation(fields: [modelId], references: [id])
  modelId      String
  language     String

  name         String

  @@id([modelId, language])
}

model ProductTag {
  id            String    @id @default(cuid())
  createdAt     DateTime  @default(now())
  updatedAt     DateTime  @updatedAt()

  translations  ProductTagTranslation[]
}
model ProductTagTranslation {
  createdAt    DateTime   @default(now())
  updatedAt    DateTime   @updatedAt()

  productTag   ProductTag @relation(fields: [modelId], references: [id])
  modelId      String
  language     String

  name         String

  @@id([modelId, language])
}

model Vendor {
  id          String      @id @default(cuid())
  createdAt   DateTime    @default(now())
  updatedAt   DateTime    @updatedAt()

  name       String      @unique()
}

model Page {
  id           String     @id @default(cuid())
  createdAt    DateTime   @default(now())
  updatedAt    DateTime   @updatedAt()

  translations PageTranslation[]
}
model PageTranslation {
  createdAt    DateTime   @default(now())
  updatedAt    DateTime   @updatedAt()

  page         Page       @relation(fields: [modelId], references: [id])
  modelId      String
  language     String

  title        String
  slug         String
  content      String

  @@id([modelId, language])
}

model DiscountCodes {
  id                 String      @id @default(cuid())
  createdAt          DateTime    @default(now())
  updatedAt          DateTime    @updatedAt()
  code               String      @unique
  modifier           String
  applicableProducts Product[]
  stock              Int
  uses               Int
  startDate          DateTime
  endDate            DateTime
}

model ShippingZone {
  id            String      @id @default(cuid())
  createdAt     DateTime    @default(now())
  updatedAt     DateTime    @updatedAt()

  name          String
  countries     ShippingCountry[]
  methods       ShippingMethod[]
}

model ShippingCountry {
  id            String      @id @default(cuid())
  createdAt     DateTime    @default(now())
  updatedAt     DateTime    @updatedAt()

  translations  ShippingCountryTranslation[]

  zones         ShippingZone[]
}
model ShippingCountryTranslation {
  createdAt         DateTime        @default(now())
  updatedAt         DateTime        @updatedAt()

  shippingCountry   ShippingCountry @relation(fields: [modelId], references: [id])
  modelId           String
  language          String

  name              String

  @@id([modelId, language])
}

model ShippingMethod {
  id            String      @id @default(cuid())
  createdAt     DateTime    @default(now())
  updatedAt     DateTime    @updatedAt()

  name          String
  conditions    ShippingCondition[]
  matchAll      Boolean     @default(true)
  price         Decimal     @db.Decimal(12, 2)
}

model ShippingCondition {
  id            String    @id @default(cuid())
  createdAt     DateTime  @default(now())
  updatedAt     DateTime  @updatedAt()

  field         ShippingConditionField
  comparison    ConditionComparison
  value         String
}

model Order {
  id                  String          @id @default(cuid())
  serial              Int             @unique @default(autoincrement())
  createdAt           DateTime        @default(now())
  updatedAt           DateTime        @updatedAt()

  items               OrderItem[]
  
  email               String
  phone               String
  message             String

  shippingMethod      ShippingMethod? @relation(fields: [shippingMethodId], references: [id])
  shippingMethodId    String?
  shippingMethodName  String
  shippingMethodPrice Decimal         @db.Decimal(12, 2)

  shippingAddress     String
  shippingCO          String?
  shippingPostal      String
  shippingCity        String
  shippingCountry     String

  billingAddress      String
  billingCO           String?
  billingPostal       String
  billingCity         String
  billingCountry      String

  companyName         String
  companyRegNumber    String
  companyAddress      String
  companyPostal       String
  companyCity         String
  companyCountry      String
}

model OrderItem {
  id            String      @id @default(cuid())
  createdAt     DateTime    @default(now())
  updatedAt     DateTime    @updatedAt()

  name          String
  price         Decimal     @db.Decimal(12, 2)
  vat           Int
  quantity      Int

  product       Product     @relation(fields: [productId], references: [id])
  productId     String
}

```

**Comment by pantharshit00** [comment] 2021-02-01 11:54
Fixed via https://github.com/prisma/prisma-engines/pull/1495

It will included in 2.16 which is planned for tomorrow. 


Closing as duplicate of https://github.com/prisma/prisma/issues/5092

**Closed by pantharshit00** 2021-02-01 11:54 UTC

**Comment by pantharshit00** [comment] 2021-02-02 17:56
Hey @scriptcoded 

2.16 was released. Please let me know if this is fixed :)

**Comment by scriptcoded** [comment] 2021-02-03 08:50
@pantharshit00 Wonderful :tada: I'll get back to you as soon as I can.

**Comment by scriptcoded** [comment] 2021-02-06 12:34
@pantharshit00 I can confirm that it's solved :) Thanks for the quick response! (and everything else you do in this repo ^_^)
