### ISSUE TITLE
Upgrading Prisma from 2.2.2 to 2.4.1 breaks the aggregate feature.

### ISSUE THREAD

**Issue by jamesonev** [prisma/prisma#3262] opened 2020-08-10 21:09 UTC
## Bug description

Upgrading Prisma from `2.2.2` to `2.4.1` breaks the aggregate feature.

## How to reproduce

1. Include 
```
generator client {
  provider             = "prisma-client-js"
  experimentalFeatures = ["aggregateApi", "transactionApi"]
}
``` 
in your  schema.prisma (version 2.2.2 )and have some prisma query that relies on aggregate:
```
const data = await prisma.withdrawal.aggregate({
    where: { status: WithdrawalStatus.COMPLETE },
    sum: { amount: true },
  });
```
1. Run `yarn build`, and check you have no errors
1. Run `yarn upgrade @prisma/cli`, and yarn bumps the version to `2.4.1`
1. Run `yarn build` again

## Expected behavior

I expected the update to be backward-compatible. I tried updating my prisma schema to use the `previewFeatures` flag instead of `experimentalFeatures`, but the error persists.

![Screenshot of error](https://user-images.githubusercontent.com/20564654/89831474-8599aa00-db23-11ea-8c43-248148179eba.png)

## Environment & setup

- OS: MacOS Catalina (10.15.6)
- Database: PostgreSQL
- Node.js version: v14.5.0
- Prisma version:
```
2.4.1
```

**Comment by Sytten** [comment] 2020-08-10 22:05
The feature is not backward compatible, though the README should have been clearer that this is a breaking change. The versioning is not semver AFAIK so this is a none issue.

**Comment by pantharshit00** [comment] 2020-08-17 14:35
@jamesonev I am unable to reproduce this, can you please make sure you ran `npx prisma generate` after you added the flag to your schema?

**Comment by janpio** [comment] 2021-03-23 19:24
I am going to close this now. Happy to take a look again if we get more information.

**Closed by janpio** 2021-03-23 19:24 UTC
Labels: bug/0-needs-info, kind/bug, status/needs-action, topic: aggregateApi
