### ISSUE TITLE
Distro solus os

### ISSUE THREAD

**Issue by tovoniry** [prisma/prisma#22494] opened 2023-12-22 08:28 UTC
### Bug description

 Prisma doesn't know which engines to download for the Linux distro "solus". Falling back to Prisma engines built "debian".

### Prisma information

```prisma
// Add your schema.prisma
```

```ts
// Add your code using Prisma Client
```

### Environment & setup

- OS: 
- Database: 
- Node.js version: 

### Prisma Version

```

```

**Comment by jkomyno** [comment] 2024-01-02 15:04
Hi @tovoniry, thanks for the report.
Does Prisma still run in your case? If so, then you can safely ignore this warning.

---

In the future, we might explicitly check for Solus Linux as well.
Can you please share the output of:

- `cat /etc/os-release`

**Comment by jkomyno** [comment] 2024-01-03 13:17
I'm closing this issue as a duplicate of https://github.com/prisma/prisma/issues/21493. Please leave a comment in there with the output of `cat /etc/os-release`. Thanks!

**Closed by jkomyno** 2024-01-03 13:17 UTC
Labels: kind/improvement, team/schema
