### ISSUE TITLE
Relationships: Polymorphic Types 

### ISSUE THREAD

**Issue by medz** [prisma/prisma#4173] opened 2020-11-06 08:27 UTC
```prisma
model report {
    id String @id
    message String
   reportable @morphRelation(models: [User, Post])
}

model User {
  id String @id
  name String
}

model Post {
  id String @id
  content String
}
```

When adding a "morph map" to your existing application, every morphable *_type column value in your database that still contains a fully-qualified class will need to be converted to its "map" name.

reference👉https://laravel.com/docs/8.x/eloquent-relationships#custom-polymorphic-types

**Comment by pantharshit00** [comment] 2020-11-09 12:50
This is related and possibly a duplicate of https://github.com/prisma/prisma/issues/2506

**Comment by laugharn** [comment] 2020-11-09 14:56
I think a common use case for this would be something like an activity feed. Imagine a platform-like site where people can post, comment, like, etc. It would be nice to have a model like:

```prisma
model Activity {
  id String @id
  model @morphRelation(models: [Comment, Like, Post])
}
```

And in the client, we would be able to make a request like `prisma.activity.findMany({ include: { model: true }})` and get the Comment, Like, or Post back with each Activity, without having to specify all of the possible relations everywhere an Activity will be called.

**Comment by medz** [comment] 2020-11-10 03:55
> This is related and possibly a duplicate of #2506
NO!!!
This is a polymorphism of data relations, not interfaces. This polymorphism is very suitable for notification, activity, report, even public category or tags. The existence of this relationship is a kind of aggregation relationship.

**Comment by pantharshit00** [comment] 2020-11-10 07:59
Yes, I am aware of that. That is why I didn't immediately closed this. That issue is surely related though.

We had a RFC for Prisma 1 a long time ago which didn't got implemented but partly describes what you are asking for: https://github.com/prisma/prisma1/issues/3407

I will keep this open and the product team and decide and design this feature properly. I also feel this  is quite important for Prisma schema.

**Comment by pantharshit00** [comment] 2020-11-10 08:02
Ok, actually found the duplicate issue for this: https://github.com/prisma/prisma/issues/2505

I knew it existed. Sorry for linking the interface one at first.

**Closed by pantharshit00** 2020-11-10 08:02 UTC
Labels: kind/feature, team/product, topic: relations
