### ISSUE TITLE
onDelete: CASCADE completely ignored

### ISSUE THREAD

**Issue by remorses** [prisma/prisma#4254] opened 2019-03-23 19:25 UTC
**Describe the bug**
Objects referenced in a @relation(onDelete: CASCADE) don't get deleted when I delete the referenced object. I know this is a known issue with deleteMany but I encounter the same issue with simple delete.

**To Reproduce**
- prisma init with docker MongoDB database and prisma:1.29 with the following data model 
```graphql
type User {
  id: ID! @id
  name: String @unique
  blog: Blog @relation(link: INLINE, onDelete: CASCADE)
}
type Blog {
    id: ID! @id
    title: String @unique
    user: User 
}
``` 
- from playground create a new user and blog
```graphql
mutation create_user {
    createUser(data: {name: "a", blog: { create: { title: "1" } } }) {
        name
    }
}
```
- delete the user
```graphql
mutation delete_user {
    deleteUser(where: { name: "a" }) { name }
}
```
- query the blogs and notice that blog hasn't been deleted
```graphql
query blogs {
    blogs {
        title
    }
}
```
The returned data will be
```
{
  "data": {
    "blogs": [
      {
        "title": "1"
      }
    ]
  }
}
```
The blog hasn't been deleted as it should

**Expected behavior**
The blog should be deleted together with the user, but instead querying the blogs returns
```
{
  "data": {
    "blogs": [
      {
        "title": "1"
      }
    ]
  }
}
```
instead of
```
{
  "data": {
    "blogs": [ ]
  }
}
```

**Versions (please complete the following information):**
 - Connector:  `MongoDB`
 - Prisma Server:  `1.29.0`
 - `prisma/1.29.1 (darwin-x64) node-v10.15.0`
 - OS: MacOs Mojave and Ubuntu 16

**Comment by remorses** [comment] 2019-03-24 16:40
Is #4212 related?

**Comment by pantharshit00** [comment] 2019-03-25 11:42
@remorses 

Yes, it is related to that PR.

Also it a duplicate of #3796 so I am going to close this.

**Closed by pantharshit00** 2019-03-25 11:42 UTC
