### ISSUE TITLE
@prisma/client is not being installed when you run `npx prisma generate`

### ISSUE THREAD

**Issue by matthewmueller** [prisma/prisma#7650] opened 2021-06-14 15:38 UTC
### Bug description

There seems to have been a regression between 2.23.0 and 2.24.0 where `npx prisma generate` does not install the `@prisma/client` package by default.

This makes our onboarding workflow quite a bit more error prone.

### How to reproduce

**1. Setup your project**

```
mkdir fresh-package && cd fresh-package
npm init -y
npm install prisma
npx prisma init
```

**2. Add a model to your `prisma/schema.prisma`**

```prisma
// This is your Prisma schema file,
// learn more about it in the docs: https://pris.ly/d/prisma-schema

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

generator client {
  provider = "prisma-client-js"
}

model User {
  id    Int     @id @default(autoincrement())
  email String  @unique
  name  String?
}
```

**3. Run `npx prisma generarate`**

4. Create a index.js script

```ts
import { PrismaClient } from "@prisma/client"
console.log(PrismaClient)
```

You'll see a red squiggly line with the following error:

```
Cannot find module '@prisma/client' or its corresponding type declarations.
```

This is because the `@prisma/client` package was never installed. It's not in node_modules or in the package.json

### Expected behavior

We should install the `@prisma/client` package when you run `npx prisma generate`.

If you run through the steps with `npm install prisma@2.23.0` you'll see the Prisma Client is installed. It should also appear in the package.json.

### Environment & setup

- OS: OSX 
- Database: Any 
- Node.js version: v14.16.0 

### Prisma Version

```
npx prisma version       
Environment variables loaded from .env
prisma               : 2.24.0
@prisma/client       : Not found
Current platform     : darwin
Query Engine         : query-engine f3e341280d96d0abc068f97e959ddf01f321a858 (at node_modules/@prisma/engines/query-engine-darwin)
Migration Engine     : migration-engine-cli f3e341280d96d0abc068f97e959ddf01f321a858 (at node_modules/@prisma/engines/migration-engine-darwin)
Introspection Engine : introspection-core f3e341280d96d0abc068f97e959ddf01f321a858 (at node_modules/@prisma/engines/introspection-engine-darwin)
Format Binary        : prisma-fmt f3e341280d96d0abc068f97e959ddf01f321a858 (at node_modules/@prisma/engines/prisma-fmt-darwin)
Default Engines Hash : f3e341280d96d0abc068f97e959ddf01f321a858
Studio               : 0.397.0
```

Also appears in @dev and 2.24.1.

**Comment by janpio** [comment] 2021-06-14 15:42
Duplicate of https://github.com/prisma/prisma/issues/7579

**Closed by janpio** 2021-06-14 15:42 UTC
Labels: bug/1-repro-available, kind/regression, team/client
