### ISSUE TITLE
When using FindUniqueArgs or FindFirstArgs there are no types for includes.

### ISSUE THREAD

**Issue by ykulinych** [prisma/prisma#22932] opened 2024-02-02 15:42 UTC
### Bug description

```
ERROR in ./apps/backend/src/modules/course-pass/course-pass.service.ts:443:57
TS2339: Property 'courses' does not exist on type '{ id: number; result: number; isFinal: boolean; wasCompleted: boolean; wasSuccessfullyPassed: boolean; endsAt: Date; createdAt: Date; updatedAt: Date; groupId: number; studentId: number; }'.
    441 |                 studentId: coursePass.studentId,
    442 |                 groupId: coursePass.groupId,
  > 443 |                 courses: { some: { courseId: coursePass.courses[0].courseId } },
        |                                                         ^^^^^^^
    444 |               },
    445 |             }),
    446 |           ]);
```

### Expected behavior

When using **Prisma.CoursePassFindUniqueArgs** or **Prisma.CoursePassFindFirstArgs** (for **findUnique** and **findFirst** respectively) I get an error:
```
    const findArgs: Prisma.CoursePassFindUniqueArgs = {
      where: { id },
      include: includeArgs,
    };
```
If remove type for findArgs, the error disappears:
```
    const findArgs = {
      where: { id },
      include: includeArgs,
    };
```
So basically query works but types are wrong.

### schema.prisma
```prisma
model Course {
  id                         Int                       @id @default(autoincrement())
  name                       String                    @default("")
  ...
  createdAt                  DateTime                  @default(now()) @map("created_at") @db.Timestamptz()
  updatedAt                  DateTime                  @default(now()) @updatedAt @map("updated_at") @db.Timestamptz()
  // relations
  ...
  coursePasses               CourseOnCoursePass[]
}

model CoursePass {
  id                    Int                  @id @default(autoincrement())
  result                Float
  ...
  createdAt             DateTime             @default(now()) @db.Timestamptz()
  updatedAt             DateTime             @default(now()) @updatedAt @db.Timestamptz()
  // relations
  group                 Group                @relation(fields: [groupId], references: [id], onDelete: Cascade)
  groupId               Int
  student               Student              @relation(fields: [studentId], references: [id], onDelete: Cascade)
  studentId             Int
  ...
  courses               CourseOnCoursePass[]
}

model CourseOnCoursePass {
  course       Course     @relation(fields: [courseId], references: [id], onDelete: Cascade)
  courseId     Int
  coursePass   CoursePass @relation(fields: [coursePassId], references: [id], onDelete: Cascade)
  coursePassId Int

  @@unique([courseId, coursePassId])
  @@index([courseId, coursePassId])
}
```
### ./apps/backend/src/modules/course-pass/course-pass.service.ts
```ts
    const includeArgs: Prisma.CoursePassInclude = {
      courses: {
        include: {
          course: true,
        },
      },
      ...(student && {
        tasks: {
          include: {
            answer: true,
            question: {
              include: {
                answers: true,
              },
            },
          },
        },
      }),
    };

    const findArgs: Prisma.CoursePassFindUniqueArgs = {
      where: { id },
      include: includeArgs,
    };
    
    ...
    ...
    ...

          const [courseOnStudent, countSingleCoursePasses] = await Promise.all([
            await tx.coursesOnStudents.findFirst({
              where: { groupId: coursePass.groupId, studentId: coursePass.studentId },
            }),
            await tx.coursePass.count({
              where: {
                isFinal: false,
                studentId: coursePass.studentId,
                groupId: coursePass.groupId,
                courses: { some: { courseId: coursePass.courses[0].courseId } },
              },
            }),
          ]);

```

### Environment & setup

- OS: Windows 10
- Database: PostgreSQL
- Node.js version: v20.11.0

### Prisma Version

```
@prisma/client@5.8.1
```

**Comment by ursarik** [comment] 2024-02-02 15:46
are you sure? have you tried to open your eyes?

**Comment by aqrln** [comment] 2024-02-02 18:18
Hi @ykulinych! The problem is that you are opting out of type inference by annotating the type of `includeArgs` as `CoursePassInclude` and the type of `findArgs` as `CoursePassFindUniqueArgs` instead of a narrower type. This way the `courses` field will be marked as potentially undefined even though you actually provided it, but there's no way to know that for `findUnique` types downstream. The right way to express what you intended in TypeScript is to use the `satisfies` operator:

```ts
    const includeArgs = {
      courses: {
        include: {
          course: true,
        },
      },
      ...(student && {
        tasks: {
          include: {
            answer: true,
            question: {
              include: {
                answers: true,
              },
            },
          },
        },
      }),
    } satisfies Prisma.CoursePassInclude;

    const findArgs = {
      where: { id },
      include: includeArgs,
    } satisfies Prisma.CoursePassFindUniqueArgs;
```

I'll go ahead and close this issue since it's rather a usage question than a Prisma issue. Please let us know if you're still facing any problems!

**Closed by aqrln** 2024-02-02 18:18 UTC
Labels: bug/1-unconfirmed, kind/bug, topic: client types, tech/typescript, team/client
