### ISSUE TITLE
edge-esm.js.map Missing this file

### ISSUE THREAD

**Issue by q351941406** [prisma/prisma#22443] opened 2023-12-17 21:31 UTC
### Bug description

<img width="1069" alt="截屏2023-12-18 05 28 55" src="https://github.com/prisma/prisma/assets/12267572/3439ab59-e74d-46ae-b536-d86289d44305">
<img width="1829" alt="截屏2023-12-18 05 30 05" src="https://github.com/prisma/prisma/assets/12267572/7fb0b316-7e64-4bc0-ba69-e961bc03b1e8">

https://www.prisma.io/docs/orm/prisma-client/deployment/edge/deploy-to-deno-deploy
I have been following this tutorial but got the error

### Prisma information

```prisma
// Add your schema.prisma
```

```ts
// Add your code using Prisma Client
```

### Environment & setup

- OS: 
- Database: 
- Node.js version: 

### Prisma Version

```

```

**Comment by janpio** [comment] 2024-01-05 08:56
@q351941406 Is anything actually failing because of this message or is this "just" a warning from Deno?

**Comment by q351941406** [comment] 2024-01-05 09:01
@janpio failing because of this message,It's not a warning, it's an error

**Comment by janpio** [comment] 2024-01-05 10:00
Do you know who is failing with an error because of this missing? It is not Prisma. Is it Deno CLI? The Deno Server?
DId you open an issue with Deno if it is coming from them? I don't see why they should _fail_ with a missing Sourcemap file.

What version of Deno CLI are you using?
I see from the output you are using Prisma 5.6.0 - correcT?

**Comment by q351941406** [comment] 2024-01-05 20:51
@janpio I don't know, I'm just following this tutorial

**Comment by Jolg42** [comment] 2024-03-06 13:08
@q351941406 Did you try with a new version of Prisma? We did changes recently and added an exports map, maybe that changes your problem.

I can recommend trying the latest version `5.10.2` as of today.

**Comment by SevInf** [comment] 2024-03-21 09:19
@q351941406 from your screenshot, it does not look it is actually failing: it prints error in red, but then still says that server is listening. What happens if you actually open http://localhost:3000?

**Comment by jkomyno** [comment] 2024-04-08 09:22
Hey @q351941406, unfortunately we didn't receive any answer, so we'll close this issue for now.
Please leave a comment below once you have a reproduction at hand or an answer to my colleagues comments ([1](https://github.com/prisma/prisma/issues/22443#issuecomment-1980841147), [2](https://github.com/prisma/prisma/issues/22443#issuecomment-2011717556)), so we can attempt to investigate this issue. Thanks!

**Closed by jkomyno** 2024-04-08 09:22 UTC
Labels: bug/0-unknown, kind/bug, tech/typescript, team/client, topic: deno, topic: sourcemap

**Comment by yorch** [comment] 2024-11-12 00:07
@Jolg42 I'm facing a similar issue with latest Prisma version (not with Deno, but when bundling my app with `tsup`). The Prisma generated code does mention a sourcemap file, but the file is nowhere to be found. You mentioned you guys added something related to exports map, does it mean that is possible to tell Prisma to generate the sourcemaps?
