### ISSUE TITLE
Error: P1011: Error opening a TLS connection: Internal error

### ISSUE THREAD

**Issue by BjoernRave** [prisma/prisma#4282] opened 2020-11-17 13:22 UTC
As a result of: https://prisma.slack.com/archives/CKQTGR6T0/p1605611171317000

I tried migrating my database hosted on Google Cloud SQL and got the following error:

I am not using SSL.

This is the format of the connection string I am using: `postgresql://username:password@IP:Port/database`

Connecting to the database with `psql` with the same connection string works fine.

<img width="950" alt="Screenshot 2020-11-17 at 14 19 58" src="https://user-images.githubusercontent.com/36173920/99395035-c568ee00-28d7-11eb-8995-63e636820819.png">

Prisma version: 2.11.0 (But the error also occurred with 2.10.0)
OS: MacOS BigSur

**Comment by narciero** [comment] 2020-11-17 17:51
+1 I am seeing this as well after upgrading to Big Sur. Happened on Prisma versions 2.5.1, 2.10.0, and 2.11.0.

**Comment by joshuacrowley** [comment] 2020-11-18 03:40
Same for me, post upgrade to Big Sur.

Prisma Version 2.1.3
OS: MacOS BigSur

**Comment by divyenduz** [comment] 2020-11-20 14:49
@BjoernRave Thanks for raising this, are these any specific settings that you are doing? I tried to reproduce this with Big Sur and Postgres on Google Cloud but I coulnd't reproduce it.

**Comment by BjoernRave** [comment] 2020-11-20 15:47
where should i be doing these settings?

**Comment by divyenduz** [comment] 2020-11-20 17:21
In Google Cloud SQL maybe? Or is it possible for you to share a small reproduction project? I tried this out today and it worked for me. I can use some more information like Postgres version or some code that can be used to reproduce this.

**Comment by joshuacrowley** [comment] 2020-11-23 00:48
I'm using Big Sur 11.0.1. I'm using Postgres 12.3 on GCP, Cloud SQL. I allow unsecured connections, and use the Public IP access (with whitelisting). Using Node v14.15.1 on my Macbook Pro  (also not working on Node v12.14.1). Use case here is I'm trying to run prisma commands locally and connect to my production database. Can use Table Plus no worries.

My API services also hosted on GCP use the Gcloud localhost connection host parameter, .e.g -> postgres://postgres:password@localhost/prisma?host=/cloudsql/project:region:service and that works fine.

Tricky to organise a reproduction given the 3rd party service. Happy to review your reproduction though @divyenduz

**Comment by pantharshit00** [comment] 2020-11-23 15:16
I am unable to reproduce this on macOS Big Sur 11.0.1 and NodeJS v14.15.1 on an Intel based 2018 Macbook Pro.
![image](https://user-images.githubusercontent.com/22195362/99978602-273fc100-2dcc-11eb-9d46-6b51bcae1ea1.png)


I tried both `dev` and `latest` tag `2.11` and `2.12.0-dev.52`. 



These are the connection properties that I am using:
![image](https://user-images.githubusercontent.com/22195362/99979152-d381a780-2dcc-11eb-9b17-4c6f233af629.png)
![image](https://user-images.githubusercontent.com/22195362/99979282-ee541c00-2dcc-11eb-9121-4c75fb3f5fba.png)

**Comment by joshuacrowley** [comment] 2020-11-23 23:36
Thanks for looking into it further @pantharshit00. Appreciate how the Prisma team has been responsive on this issue.

So I think I have a resolution for those still affected. If you simply [create a clone](https://cloud.google.com/sql/docs/postgres/clone-instance) of your Cloud SQL service, and use the new IP details you'll find that you can create a prisma connection just fine. 

So I guess GCP made a change to our existing services that caused problems, and creating new services fixes it. Or this could be some kind of ongoing Big Sur issue that might come up again? Doesn't feel like a Prisma specific issue though.

**Comment by magne4000** [comment] 2021-01-07 10:36
I also bypassed the issue by issuing a new certificate (Create new certificate) and rotating it (Rotate certificate):
![image](https://user-images.githubusercontent.com/1098371/103882738-89365a80-50dc-11eb-80c0-6adab20bd8d4.png)

**Comment by danhollick** [comment] 2021-01-10 13:38
I just hit this issue myself. it seems to be something on the GCP side:
https://cloud.google.com/sql/docs/troubleshooting

![Screenshot 2021-01-10 at 14 37 35](https://user-images.githubusercontent.com/13898607/104124503-83957a80-5351-11eb-8930-32f9c26be2e8.png)

**Comment by Jolg42** [comment] 2021-01-11 10:07
Looks like this can be closed as it sounds like a GCP issue that can be solved by rotating the server certificate and recreating the client certificates. 🎊

**Closed by Jolg42** 2021-01-11 10:07 UTC
Labels: bug/0-needs-info, kind/bug, topic: macos bigsur

**Comment by RoyBkker** [comment] 2021-01-14 13:22
Same issue here, just updated to Big Sur. 
Can it harm production environments by rotating the server certificate and recreating the client certificates?

In other words, do I need to take care of other steps?
Thanks in advance.

**Comment by magne4000** [comment] 2021-01-14 15:38
I cannot speak for your use case, but ours were really simple, and I had nothing more to do than what I described.

**Comment by pantharshit00** [comment] 2021-01-15 08:35
> Can it harm production environments by rotating the server certificate and recreating the client certificates?

It should not as long as you are passing the correct certificates. Also, workaround is documented by GCP itself I am pretty confident that it is safe.

**Comment by ChipClark** [comment] 2021-03-10 11:52
I just upgraded @prisma/cli 2.17 to prisma 2.18 - and I'm getting this error. 

Nothing on the sql side has changed - and other than the upgrade nothing on the API side has changed.

**Comment by pantharshit00** [comment] 2021-03-10 12:08
@ChipClark Please open a new issue with a minimal reproduction.

**Comment by ChipClark** [comment] 2021-03-11 19:43
I was able to resolve this issue by adding: 

trustServerCertificate=true;

to the  DATABASE_URL

**Comment by madebyfabian** [comment] 2022-12-08 08:28
For anyone having this issue with Supabase, I fixed it by restarting the supabase instance in the admin ui. Don't know if this is a permanent fix.
