### ISSUE TITLE
Tracing operation duration bug under stress test

### ISSUE THREAD

**Issue by JakubKoralewski** [prisma/prisma#16980] opened 2022-12-22 10:17 UTC
### Discussed in https://github.com/prisma/prisma/discussions/16966

Moved to a bug issue as suggested by @janpio 

<div type='discussions-op-text'>

<sup>Originally posted by **JakubKoralewski** December 21, 2022</sup>
Here is a get request trace from Jaeger:
![obraz](https://user-images.githubusercontent.com/43069023/208980523-5fa9974f-837d-41f3-a2a7-af87e0c39676.png)
Prisma query seems to be taking 574ms. It's a findMany of posts. However, the only accounted subtraces cover the first few milliseconds. Are the `db_query`ies just covering the creation of the query and not the actual execution? Or does the database really return from the query in less than 1ms?

How do I find out what is causing Prisma to not return for the remaining 500ms? I guess this is a feature request/bug report for the tracing feature? 

Don't be fully alarmed by the very long time of the request, I picked the slowest query of my stress tests. Please stay half-alarmed only.

I'd appreciate any help :) 🎅 </div>

### Reproduction repo
https://github.com/JakubKoralewski/prisma-tracing-repro

I used pnpm in the stress testing script, so I think it will throw error if you don't use pnpm.

The problem did not appear when not using next-auth and the getSession call in the api handlers. getSession actually makes an HTTP request and is not supposed to be used in server side api handling as it creates HTTP request from server to server. I suspect this causes the connection part to take a long time under stress tests, but in the Jaeger trace it shows the connection to take only few microseconds? 

### Steps to reproduce

1. Run docker compose to start db and Jaeger.
2. Run pnpm install.
3. Run pnpm run trace. This sets up the db and calls the tracing/stress testing script.
4. Open Jaeger http://localhost:16686
5. Pick prisma-tracing-repro service, last 5 minutes, Min Duration 1s, Limit results 1000. Click Find Traces.
6. Sort by longest. Click on longest trace.
7. `prisma:client:operation` does not have all the duration covered.

**Comment by barryhagan** [comment] 2023-01-12 17:59
While the gaps look different, we are seeing similar issues where parts of the `prisma:client:operation` span are not accounted  for with child spans.   This leaves us at a dead end for the sporadic performance issues we are observing.   Our belief is this is happening when there are concurrent prisma client operations, and likely high contention in the engine's connection pool (This is exacerbated by our use of graphql+dataloader and the likelihood that multiple fields are being resolved in parallel, each requiring a database query).

Here are a couple examples of gaps between `prisma:client:serialize` and `prisma:engine` as well as between `prisma:engine:serialize` and the completion of the `prisma:client:operation`.  We would like to know what is happening in these gaps.  Is it possible these are GC pauses?
![pre-engine-gap](https://user-images.githubusercontent.com/3193577/212143499-036b7e95-59b7-41c2-a42d-28204f1d2f21.png)

**Comment by janpio** [comment] 2023-01-16 17:09
Your second screenshot actually looks similar as the previously posted ones @barryhagan - activity first and then (nothing). 
Your first one where there is a long time the middle of some spans of one trace with no attribution looks different though.

Optimal for us would be a reproduction - what do we have to do to semi reliably reproduce these invalid traces?

**Comment by trevorr** [comment] 2023-01-16 20:20
We're having the [same issue](https://prisma.slack.com/archives/C044YLSN49E/p1673893324682059), but the durations are more extreme. Here's a query that spends 30ms in the Prisma engine, but takes 1.3s to start running there:

<img width="1485" alt="Screen Shot 2023-01-16 at 12 12 44 PM" src="https://user-images.githubusercontent.com/928766/212759232-bc4b26f8-47d1-47c6-9115-5acd27fde262.png">

This is from a local dev instance with `PRISMA_SHOW_ALL_TRACES=true` that was otherwise idle.

**Comment by shroudedcode** [comment] 2023-01-31 13:24
Unfortunately, my team still hasn't been able to reproduce the issue outside of our production environment. Still, we have discovered a new datapoint that might be of interest: The durations of the top-level Prisma spans always seem to be very close to full seconds.

<img width="1362" alt="image" src="https://user-images.githubusercontent.com/29176678/215765986-4fa0b0bf-2f96-4851-bb8f-d0141634753a.png">

Note how in the heatmap above, many of the durations are very close to either 1, 2, or 3 seconds. There are outliers, but the pattern seems clear enough that something must be happening here. Maybe some timeout or delay in the Prisma engine?

Also, here are a few more details about our setup in case it helps:

- we're using Prisma 4.9.0 (but tried all 4.x versions and couldn't change the behavior)
- we're using Node.js 18
- our production app runs on Google Cloud Run
- we currently use the following connection params: `connection_limit=20&pool_timeout=10&max_idle_connection_lifetime=0`
- the database is PostgreSQL 14 and is hosted on Google Cloud SQL
- we're connecting to the database using Cloud SQL Proxy
- we can't reproduce the issue even when connecting to the database using Cloud SQL Proxy

**Comment by shroudedcode** [comment] 2023-02-27 19:16
Hi everyone; my team was finally able to resolve this issue for us, and I wanted to share the solution in case it applies to anyone else (because it was quite an unexpected one):

### Sentry Tracing issue

It turns out that Prisma wasn't actually the culprit here (or at least not the only one). After unsuccessfully trying to replicate the behavior locally for a long time, we were suddenly able to also get the super long response times in development last week. We were completely confused as to what had changed about our setup at first until we realized that the engineer who had replicated it **had currently enabled Sentry locally** for testing purposes.

We specifically narrowed it down to Sentry's tracing feature, which we had enabled a while ago without thinking about it too much. It turns out that it somehow interfered with Prisma queries causing all of them to kind of "stack up" until Sentry made until Sentry presumably submitted some data to their API, at which point all of them would go through.

The fact that, at the same time, we were _also_ collecting traces using OpenTelemetry (those were the ones I posted screenshots of above) could've added to the issue, but we didn't test that in isolation. We generally didn't look into the cause further from here. Removing Sentry tracing, including all of its instrumentations and middleware, fixed the issue completely for us.

**Comment by janpio** [comment] 2023-02-27 23:56
@trevorr @barryhagan @JakubKoralewski Any Sentry involved for you?

**Comment by JakubKoralewski** [comment] 2023-02-28 05:32
> Thanks for the feedback @shroudedcode.
> 
> @trevorr @barryhagan @JakubKoralewski Any Sentry involved for you?

Not for me. The repro didn't have Sentry and it triggered the bug. It did have that incorrect usage of next-auth so maybe some side effect is needed to trigger.

**Comment by trevorr** [comment] 2023-03-01 00:29
We do use Sentry for error reporting, but I don't think we use its tracing feature.

**Comment by xoapit** [comment] 2024-09-19 17:00
@niklashigi Are you using max_idle_connection_lifetime=0 in the production env? Are there any issues with that?

**Comment by aqrln** [comment] 2024-11-07 09:59
This is most likely caused by concurrency. Right now we set the `spanId` and `parentSpanId` via the internal Span constructor for the engine spans re-created in the `@prisma/instrumentation` package so the engine subtree is correct itself, but it's not guaranteed that it's being attached to the correct `prisma:client:operation` client span because we're not actually setting the parent ID for the top level engine span, we're relying on us being in the correct client span at the time we receive the spans in the engine logs which is actually not true when there are concurrent queries.

I will check if this is the case and let you all know the result.

We are also fixing how the engine to client span conversion works, so if this is the cause, it's going to be fixed soon.

(https://github.com/prisma/prisma/issues/19580#issuecomment-2461798257)

**Closed** 2024-12-16 11:08 UTC
Labels: bug/1-unconfirmed, kind/bug, topic: prisma-client, topic: previewFeatures, domain/client, topic: tracing
