### ISSUE TITLE
[Beta2]Eager Loading Causes Typescript Error

### ISSUE THREAD

**Issue by zzyyzz1992** [prisma/prisma#2161] opened 2020-04-10 15:30 UTC
Env: Win10 WSL2, Beta2, Mysql
Schema:
```
model Meeting {
    id        Int   @id @default(autoincrement())
    name      String 
    attendee  User[] @relation("UserMeeting",references:[id])
    createdAt   DateTime @default(now())
}

model User {
    id        Int   @id @default(autoincrement())
    createdAt   DateTime @default(now())
    attendedMeetings Meeting[] @relation("UserMeeting",references:[id])

    name  String
    idCardNo String @unique
  sex String
  nation String?
  birth String?
  address String?
  authority String? 
  validDate String?
  headB64 String?

  phoneNo String?
  remark String?

  images Image[]
}
model UserMeeting {
  meeting Meeting @relation(fields: [meetingId], references: [id])
  meetingId Int
  user User @relation(fields: [userId], references: [id])
  userId Int
  
  checkinTime DateTime @default(now())
  roomNo String?

  remark String?
  @@id([meetingId, userId])
}
enum ImageType {
  ID1
  ID2
  PassCard
  OTHER
}
model Image {
  id        Int   @id @default(autoincrement())
  user User  @relation(fields: [userId], references: [id])
  userId Int @map("user")
  type ImageType
  base64Data String // TEXT?? mediumtext
  createdAt   DateTime @default(now())

```

Code:
```
const userMeeting = await prisma.userMeeting.findOne({
      where: {
        meetingId_userId: {
          meetingId: meetingId,
          userId: userId
        }
      },
      include: {
        user: {
          include: {
            images: true
          }
        }
      }
    })!;
    res.json({
      result: true,
      userMeeting,
      user: userMeeting!.user
    })
```
When using beta1, everything just fine:
![image](https://user-images.githubusercontent.com/3894825/79002334-d05de200-7b82-11ea-8600-d5c96911c7a9.png)

When upgraded to beta2,  and regenerated the prisma node_module by "npx prisma generate" this eager loading code not compilable anymore:
![image](https://user-images.githubusercontent.com/3894825/79002377-eec3dd80-7b82-11ea-9a05-fee959383f75.png)

**Comment by pantharshit00** [comment] 2020-04-14 09:45
Hi,

Thanks for reporting this! It has already been reported before, so I am going to close this as a duplicate of https://github.com/prisma/prisma/issues/2141

**Closed by pantharshit00** 2020-04-14 09:45 UTC
