### ISSUE TITLE
Upsert seems to increment pk id by 3 in postgres

### ISSUE THREAD

**Issue by dirtandgrass** [prisma/prisma#20442] opened 2023-07-28 16:25 UTC
### Bug description

1st of all I'm new to prisma, so it could be my error

Problem, if i upsert on a unique key, (with 3 columns) it increments the pk by 3 for each new record. This isn't breaking, but it is annoying!

### Expected behavior

the primary key auto increment should increase by 1

### Prisma information

```prisma
generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

/// This model contains row level security and requires additional setup for migrations. Visit https://pris.ly/d/row-level-security for more info.
model name {
  name_id                               Int           @id(map: "name_pk") @default(autoincrement())
  name                                  String        @db.VarChar
  male                                  Boolean       @default(false)
  female                                Boolean       @default(false)
  rating                                rating[]
  similar_similar_name_idToname         similar[]     @relation("similar_name_idToname")
  similar_similar_similar_name_idToname similar[]     @relation("similar_similar_name_idToname")
  source_name                           source_name[]
}

model source {
  source_id   Int           @id(map: "source_pk") @default(autoincrement())
  name        String
  url         String?       @db.VarChar
  description String?       @db.VarChar
  source_name source_name[]
}

model source_name {
  source_name_id Int    @id(map: "source_name_pk") @default(autoincrement())
  name_id        Int
  source_id      Int
  name           name   @relation(fields: [name_id], references: [name_id], onDelete: NoAction, onUpdate: NoAction, map: "source_name_fk")
  source         source @relation(fields: [source_id], references: [source_id], onDelete: NoAction, onUpdate: NoAction, map: "source_name_fk_1")
}

/// This model or at least one of its fields has comments in the database, and requires an additional setup for migrations: Read more: https://pris.ly/d/database-comments
model similar {
  similar_id                         Int  @id(map: "name_name_pk") @default(autoincrement())
  name_id                            Int
  similar_name_id                    Int
  name_similar_name_idToname         name @relation("similar_name_idToname", fields: [name_id], references: [name_id], onDelete: NoAction, onUpdate: NoAction, map: "name_name_fk")
  name_similar_similar_name_idToname name @relation("similar_similar_name_idToname", fields: [similar_name_id], references: [name_id], onDelete: NoAction, onUpdate: NoAction, map: "name_name_fk_1")

  @@unique([name_id, similar_name_id], map: "similar_un")
}

model session {
  session_id Int      @id(map: "session_pk") @default(autoincrement())
  user_id    Int
  hash       String   @db.VarChar(256)
  created    DateTime @default(now()) @db.Timestamp(6)
  expires    DateTime @default(dbgenerated("(CURRENT_TIMESTAMP + '14 days'::interval)")) @db.Timestamp(6)
  user       user     @relation(fields: [user_id], references: [user_id], onDelete: NoAction, onUpdate: NoAction, map: "session_fk")
}

model user {
  user_id         Int       @id(map: "user_pk") @default(autoincrement())
  username        String    @db.VarChar
  email           String    @unique(map: "user_un") @db.VarChar
  hash            String    @db.VarChar(256)
  date_created    DateTime  @default(dbgenerated("CURRENT_DATE")) @db.Date
  validated       Boolean   @default(false)
  validation_code String?   @db.VarChar(256)
  group           group[]
  rating          rating[]
  session         session[]
}

model rating {
  rating_id Int     @id(map: "name_rating_pk") @default(autoincrement())
  user_id   Int
  name_id   Int
  rating    Decimal @db.Decimal
  group_id  Int
  name      name    @relation(fields: [name_id], references: [name_id], onDelete: NoAction, onUpdate: NoAction, map: "name_rating_fk")
  user      user    @relation(fields: [user_id], references: [user_id], onDelete: NoAction, onUpdate: NoAction, map: "name_rating_fk_1")
  group     group   @relation(fields: [group_id], references: [group_id], onDelete: NoAction, onUpdate: NoAction, map: "rating_fk")

  @@unique([user_id, name_id, group_id], map: "rating_un")
}

model group {
  group_id      Int      @id(map: "group_pk") @default(autoincrement())
  name          String?  @db.VarChar
  owner_user_id Int
  user          user     @relation(fields: [owner_user_id], references: [user_id], onDelete: NoAction, onUpdate: NoAction, map: "group_fk")
  rating        rating[]
}

```

```ts
static async rateName(name_id: number, rating: number, group_id: number = 1): Promise<{ message: string, success: boolean }> {

    const user_id = AuthUser?.user_id || 0;

    if (user_id === 0) return { "message": "not logged in", "success": false };

    if (!Number.isInteger(name_id) || rating > 1 || rating < 0 || (!Number.isInteger(group_id) && group_id)) {
      return { "message": "invalid data", "success": false };
    }

    try {
      const result = await prisma.rating.upsert({
        where: { user_id_name_id_group_id: { name_id, user_id, group_id } },
        update: { rating },
        create: { name_id, user_id, group_id, rating }
      });
    } catch (e) {
      console.log(e);
      return { "message": "unable to update rating", "success": false };
    }
    return { "message": "success", "success": true };
  }

```

### Environment & setup

- OS: windows
- Database: PostgreSQL/supabase
- Node.js version: 18.16.0

### Prisma Version

```
5.0.0
```

**Comment by janpio** [comment] 2023-07-28 18:37
Are yu maybe supplying the `name_id` value that is used in `create` yourself to `rateName`? Where does that value come from? When you supply the primary key value that is usually to be auto incremented by the database, it usually just takes the value you provide instead of the value that would be next in the sequence. Possible or did I misunderstand?

**Comment by dirtandgrass** [comment] 2023-07-28 19:23
> Are yu maybe supplying the `name_id` value that is used in `create` yourself to `rateName`? Where does that value come from? When you supply the primary key value that is usually to be auto incremented by the database, it usually just takes the value you provide instead of the value that would be next in the sequence. Possible or did I misunderstand?

the rating_id (not specified in query) is incremented by 3 each time upsert adds a new record, name_id is a fk for a record in the name table.


for context: this structure is in support of a "team baby name picker" - the name table, is literally thousands of names, each user can rate each name in the context of a group

**Comment by janpio** [comment] 2023-07-29 01:18
Yes, that makes more sense. Can you maybe create a minimal reproduction and put it on GitHub so we can look at it ourselves? Thanks.

**Comment by livthomas** [comment] 2023-08-02 09:32
I can confirm that I'm seeing the same behaviour in my application that also uses PostgreSQL. I have a DB table with only 238 records. I'm calling upsert on this table every time my app is deployed. There's only a single new record added once in a while. But the `id` of the latest record is already 11052. The previous one is 10986, then 9354, 8610, etc.

This is just a small table but I have others with millions of records where I will run out of possible values in `INTEGER` type over time unless this bug is fixed.

**Comment by aqrln** [comment] 2023-08-03 13:51
I couldn't reproduce neither with 5.0.0 nor with latest `main` with the provided schema and query. One related thing I could see was that the initial value of `rating_id` jumped right to 2 in an empty database on the first `upsert`, but I can't reproduce this again after resetting the db 😕
Further values were always incremented by one each time I tried.

**Comment by livthomas** [comment] 2023-08-03 17:00
Here's a simple reproducer that clearly demonstrates this bug: https://github.com/RBFLabs/bug-reproducers/tree/main/prisma/prisma/postgres-upsert-increment

**Comment by aqrln** [comment] 2023-08-03 19:12
@livthomas indeed, I can reproduce this with your example. However, if you look at the logged queries, Prisma does not create the new ID, the database does:

```
prisma:query INSERT INTO "public"."entity" ("slug") VALUES ($1) ON CONFLICT ("slug") DO UPDATE SET "slug" = $2 WHERE ("public"."entity"."slug" = $3 AND 1=1) RETURNING "public"."entity"."id", "public"."entity"."slug"
```

Apparently Postgres advances the sequence each time an `INSERT` statement is executed regardless of whether a new row was inserted or not. In fact, this happens even with the regular `INSERT` statement (e.g. when the row is not inserted due to the constraint violation) and not just with `INSERT ... ON CONFLICT`:

```
$ pgcli postgres://prisma:prisma@localhost:5432/repro-current
Server: PostgreSQL 10.21 (Debian 10.21-1.pgdg90+1)
Version: 3.5.0
Home: http://pgcli.com
repro-current> select * from entity;
+----+------+
| id | slug |
|----+------|
| 1  | 1    |
| 3  | 2    |
| 6  | 3    |
+----+------+
SELECT 3
Time: 0.017s
repro-current> insert into entity (slug) values ('1') on conflict (slug) do nothing returning id, slug;
+----+------+
| id | slug |
|----+------|
+----+------+
INSERT 0 0
Time: 0.016s
repro-current> insert into entity (slug) values ('4') on conflict (slug) do nothing returning id, slug;
+----+------+
| id | slug |
|----+------|
| 8  | 4    |
+----+------+
INSERT 0 1
Time: 0.018s
repro-current> insert into entity (slug) values ('1');
duplicate key value violates unique constraint "entity_slug_key"
DETAIL:  Key (slug)=(1) already exists.
Time: 0.009s
repro-current> insert into entity (slug) values ('5') returning id, slug;
+----+------+
| id | slug |
|----+------|
| 10 | 5    |
+----+------+
INSERT 0 1
Time: 0.014s
```

I can see how this can be problematic in scenarios where `upsert` happens to update more often than insert, but it doesn't look specific to Prisma in any way, and the same problem would happen when using another ORM or writing the SQL queries by hand, wouldn't it? Do you have any suggestion about what you'd prefer Prisma to do here?

**Comment by livthomas** [comment] 2023-08-04 06:44
@aqrln Thanks for looking into this!

Couldn't Prisma use a different SQL query? The following one would bypass this problem:
```sql
INSERT INTO "public"."entity" ("slug")
  SELECT $1 WHERE NOT EXISTS (SELECT FROM "public"."entity" WHERE "slug" = $2)
  RETURNING "public"."entity"."id", "public"."entity"."slug"
```

This would probably be only possible if `update` field is left empty which is quite common.

**Comment by Jolg42** [comment] 2023-08-07 08:26
Some explanation on how this is "by design" in PostgreSQL:
https://stackoverflow.com/a/37206177/1345244
Note that "The only thing a sequence guarantees is that it never generates the same number twice."

**Comment by aqrln** [comment] 2023-08-10 20:27
@livthomas the problem with your suggested query is that it may fail with unique constraint violation on concurrent insert as there is a race condition: a new record with the same `"slug"` may be inserted after the `SELECT` subquery but before the `INSERT` main query.

You can reproduce it fairly easily: start a bunch of parallel threads or processes (e.g. as much as you have parallel workers in postgres), open a separate connection in each of them and run a loop that tries to upsert records with the same `slug` in parallel. You'll run into errors right away:

```
DETAIL: Key (slug)=(0) already exists.
db error: ERROR: duplicate key value violates unique constraint "entity_slug_key"
DETAIL: Key (slug)=(0) already exists.
db error: ERROR: duplicate key value violates unique constraint "entity_slug_key"
DETAIL: Key (slug)=(1) already exists.
db error: ERROR: duplicate key value violates unique constraint "entity_slug_key"
DETAIL: Key (slug)=(1) already exists.
db error: ERROR: duplicate key value violates unique constraint "entity_slug_key"
DETAIL: Key (slug)=(2) already exists.
db error: ERROR: duplicate key value violates unique constraint "entity_slug_key"
DETAIL: Key (slug)=(2) already exists.
db error: ERROR: duplicate key value violates unique constraint "entity_slug_key"
DETAIL: Key (slug)=(3) already exists.
db error: ERROR: duplicate key value violates unique constraint "entity_slug_key"
DETAIL: Key (slug)=(5) already exists.
db error: ERROR: duplicate key value violates unique constraint "entity_slug_key"
DETAIL: Key (slug)=(6) already exists.
```

This will not happen with `INSERT ... ON CONFLICT` though.

**Comment by aqrln** [comment] 2023-08-11 13:47
I'm going to go ahead and close this issue as I believe it is not a bug. The way `upsert` is implemented in Prisma (i.e. which SQL query it produces) is IMO how most users would expect it to work in most cases, and other alternatives would come with correctness or performance implications in general case. The fact that the sequence works like that in Postgres is not something we control.

If it's critical to use sequential IDs and ensure they are contiguous, and it is acceptable to trade off some performance for it, it's always possible to use different queries more appropriate for a specific use case in a transaction with sufficient isolation level from within user code.

Please open `kind/feature` or `kind/improvement` issues if you see how Prisma could help with this, or if it could generate better or more appropriate queries in specific cases.

Also please let me know if you believe this was a mistake and this issue should be reopened.

**Closed by aqrln** 2023-08-11 13:47 UTC
Labels: bug/1-unconfirmed, kind/bug, team/client, topic: postgresql, topic: upsert

**Comment by janpio** [comment] 2024-02-15 23:21
@livthomas Do you maybe want to open an issue over at https://github.com/prisma/docs, optimally with a suggestion on where such a mention would fit in our documentation? Thanks.

**Comment by firsturdiev** [comment] 2025-02-11 13:30
It's implemented now?
