### ISSUE TITLE
Prisma 4.6.0 drops and recreates enum field when running db push even if the field has not changed

### ISSUE THREAD

**Issue by alexisbellido** [prisma/prisma#16180] opened 2022-11-08 19:45 UTC
### Bug description

I just updated from Prisma 4.5.0 to 4.6.0 and now every time I run `npx prisma db push`, even if I haven't changed anything in `schema.prisma`, Prisma wants to drop and recreate an enum field. I get this message:

```
The `roles` column on the `User` table would be dropped and recreated. This will lead to data loss
```

If I choose to ignore the warning all my data in the `roles` column is reset.

After testing with multiple changes to my schema and simplifying it to the most basic form (included below) I downgraded to Prisma 4.5.0 and everything works as expected there. I've reconfirmed the problem exists by going back to Prisma 4.6.0.

### How to reproduce

1. Use the provided basic `schema.prisma.` Pay attention to the `roles` field, which is an enum.
2. Create at least one row in the user table containing a value for the `roles` field.
3. Run `npx prisma db push` multiple times without changing anything in `schema.prisma`.
4. You will see `The `roles` column on the `User` table would be dropped and recreated. This will lead to data loss`, and if you accept the warning the data in the `roles` column will be reset.

### Expected behavior

The `roles` enum column is not being changed in `schema.prisma` so it shouldn't be dropped and recreated when running `npx prisma db push`.

### Prisma information

```prisma
model User {
  id                    Int               @id @default(autoincrement())
  username              String            @unique @db.VarChar(32)
  roles                 Role[]            @default([COLLECTOR])
}

enum Role {
  ADMIN
  COLLECTOR
}
```

```ts
// Add your code using Prisma Client
```

### Environment & setup

- OS: Ubuntu Linux 
- Database: PostgreSQL 14.2 
- Node.js version: 18.0.0 

### Prisma Version

```
4.6.0
```

**Comment by bsproul** [comment] 2022-11-08 21:29
Seeing the same behavior here

**Comment by davidlumley** [comment] 2022-11-09 06:14
Running into the same issue with a similar schema:

```
enum NotificationEntityType {
  buy_order
  sell_order
  product_update

  @@map("notification_entity_type")
}
```

Resulting migration looks like this:
```
-- CreateEnum
CREATE TYPE "NotificationEntityType" AS ENUM ('buy_order', 'sell_order', 'product_update');

-- DropEnum
DROP TYPE "notification_entity_type";
```

**Comment by tomhoule** [comment] 2022-11-09 08:11
Hi there :wave: Quick update from the Prisma folks: we are working on this. There is indeed a regression with enums in 4.6.0, and here's a PR to fix it https://github.com/prisma/prisma-engines/pull/3368

The bug appears when the following two conditions are met:

1. Provider is `postgresql` or `cockroachdb`
2. You use `@@map` on enums.

The regression is that we started using the name of the enum instead of the mapped name (more details in the PR). This is a very embarassing gap in our tests.

**If you experience a regression with `db push` or `migrate dev` or `migrate diff` in 4.6.0 outside of the two conditions named above, please post here with as much detail as possible, because you are experiencing a different regression that will not be fixed by the PR in this comment.**

**Comment by tomhoule** [comment] 2022-11-09 08:13
@alexisbellido I tried reproducing first using your instructions and could not observe any bad behaviour. Can you try again and confirm if you can really observe undesirable migrations __without @@map on the enum__?

**Comment by hoghweed** [comment] 2022-11-09 09:47
On my team, we have precisely the same behavior

**Comment by tomhoule** [comment] 2022-11-09 09:52
@hoghweed the behaviour described by @alexisbellido (without `@@map`) or the behaviour described by @bsproul and @davidlumley ?

**Comment by hoghweed** [comment] 2022-11-09 09:59
> @hoghweed the behaviour described by @alexisbellido (without `@@map`) or the behaviour described by @bsproul and @davidlumley ?

The one without the `@@map` on the `@enum`

**Comment by tomhoule** [comment] 2022-11-09 10:05
Ok that's concerning, we can't reproduce what @alexisbellido described, do you have more details that would help us reproduce the issue?

**Comment by janpio** [comment] 2022-11-09 10:34
To make it explicit @hoghweed: We need your help to understand the case where an `enum` without `@@map` leads to migrations being created all the time. We can currently not reproduce ourselves.

**Comment by hoghweed** [comment] 2022-11-09 10:43
@janpio I know that, unfortunately, as I was saying to Nikolas Burk on Twitter, unfortunately it is very hard to give a context to make this reproducible. Our schema is a simple one with enums, but I'm not sure what is context I can give you.

I can just tell you how we found the bug:
- applied prisma update to 4.6.0
- applied previous migrations to the underlying database in Test
- it started to ask for what name to give to a new migration, that migration was including just enums columns already included in previous migrations (we didn't change those columns from weeks)
- even if we create such a new migration, each time we've applied migrations to the database, Prisma has asked to create a new migration with the above enum columns
- this could go ahead with no limit - only for testing it asked to create 3 times the same migration

This is the only context I can give without giving you the full schema
Ho this help

**Comment by janpio** [comment] 2022-11-09 10:52
Can you run this command please?
```
npx prisma migrate diff --from-schema-datamodel ./prisma/schema.prisma --to-url "$DATABASE_URL" --exit-code
``` 
(make sure that `DATABASE_URL` is set before running this)

This should output something like https://github.com/prisma/prisma/issues/16180#issuecomment-1307851002

Can you then please also share the Prisma schema snippets that define these `enum`s and the models around them? Thanks.

**Comment by hoghweed** [comment] 2022-11-09 11:08
The command result is
```bash
[*] Changed the `Action` table
  [*] Column `result` would be dropped and recreated (type changed)

[*] Changed the `ActionLog` table
  [*] Column `kind` would be dropped and recreated (type changed)
```
This is the Prisma snippet.
```
enum Kind {
  info
  warning
  error
}

enum Result {
  succeeded
  failed
}
```

Consider we don't change those from 5 months, the only change made to the tables was just an indentation change.

**Comment by tomhoule** [comment] 2022-11-09 11:08
Thanks! We'll try to dig deeper.

**Comment by janpio** [comment] 2022-11-09 11:45
Thanks indeed @hoghweed.

What database are you using (make and version)?
What do the models look like where you use those enums?
Anything "happening" with these enums or the fields using them? (index, relation, or anything else besides just cleanly using them as the type for a field)

Can you maybe share your schema file privately with us at schemas@prisma.io? (Happy to sign NDA if necessary)

**Comment by tomhoule** [comment] 2022-11-09 11:45
(the few last migrations would also be helpful clues)

**Comment by Jolg42** [comment] 2022-11-09 11:59
Notes
I tried the reproductions steps from the description, using Prisma version `4.6.0` and `postgres:14.2` docker image but could not reproduce the issue.
For the data I used
```sql
INSERT INTO "public"."User" ("username", "roles") VALUES ('someusername', '{COLLECTOR}');
```

**Comment by tomhoule** [comment] 2022-11-09 12:27
Quick update on this: we think we have a reproduction for the second problem, we're confirming that and working on a PR.

**Comment by tomhoule** [comment] 2022-11-09 13:37
We have a fix for the second regression: https://github.com/prisma/prisma-engines/pull/3374 — I'll keep this issue updated once it hits a Prisma release.

**Comment by alexisbellido** [comment] 2022-11-09 15:21
> 

Hi, I can reproduce with the steps and schema in my original description and Prisma 4.6.0. As you can see from my basic schema I'm not using @@map at all. But from I've read it looks like a few others have experienced the same issue.

Thank you for looking into this.

**Comment by jameyhart** [comment] 2022-11-09 16:03
Hi @janpio,
We're experiencing the same issue here at Jisc.

We'll provide the details you asked for above.

Database: Postgres v12.8
Models: We use various enums across our database but here is an example:-
```prisma
model Account {
    id                     String              @id @default(cuid())
    name                   String
    type                   AccountType         @default(TRIAL)
    sector                 Sector?
    ...
}

model SurveyReport {
    id                String       @id @default(cuid())
    surveyId          String
    survey            Survey       @relation(fields: [surveyId], references: [id], onDelete: SetNull)
    reportType        SurveyReportType
    ...
}

enum AccountType {
    ORGANISATION
    TRIAL
    ...
}

enum Sector {
    PRIVATE_SECTOR
    PUBLIC_SECTOR
    ...
}

enum SurveyReportType {
    SPAM
    OTHER
    ...
}
```

We were creating a new migration based off the latest Prisma validation error:
![image](https://user-images.githubusercontent.com/26539686/200877888-fe2f4a1a-cd3a-469a-8a0f-209d7f52bc93.png)

Here is a screenshot of the diff between the changes we tried to make:
![image](https://user-images.githubusercontent.com/26539686/200878161-85ce9565-4f03-435c-ab04-4146dc9c5dfe.png)

This ultimately resulted in a migration file, which attempted to drop rows within other models that referenced enums.

Interestingly, the migration file created on v4.6.0 attempts to drop rows that reference the enum `SECTOR`, which happens to be optional.
However, does not make any changes to the AccountType, which is a required field and has a default value set.

**Comment by alexisbellido** [comment] 2022-11-09 16:18
Hey, @tomhoule ,

I couldn't replicate the original issue with the sample schema I provided (without @@map) so I gradually re-added the other fields and models from my application and I could reproduce it.

Here's the basic schema to try.

```
model User {
  id                    Int               @id @default(autoincrement())
  username              String            @unique @db.VarChar(32)
  roles                 Role[]            @default([COLLECTOR])
  nfts                  NFT[]
}

enum Role {
  ADMIN
  COLLECTOR
}

model NFT {
  id            Int           @id @default(autoincrement())
  owner         User          @relation(fields: [ownerId], references: [id])
  ownerId       Int           @unique
  images        NFTImage[]
}

model NFTImage {
  id           Int              @id @default(autoincrement())
  nft          NFT              @relation(fields: [nftId], references: [id])
  nftId        Int
  title        String?          @db.VarChar(64)
  src          String?          @db.VarChar(128) // URL pointing to image
  alt          String?          @db.VarChar(64)
  orientation  ImageOrientation @default(VERTICAL)
}

enum ImageOrientation {
  HORIZONTAL
  VERTICAL
}
```

Then reset with this.

```
npx prisma db push --force-reset
```

and insert one row to the `User` table.

```
INSERT INTO "User" (username, roles) VALUES ('someusername', '{COLLECTOR, ADMIN}');
```

now, and without changing anything else, run `npx prisma db push` and you will see Prisma trying to drop and recreate the `roles` column.

Here's my  output from `npx prisma migrate diff --from-schema-datamodel ./prisma/schema.prisma --to-url "$DATABASE_URL" --exit-code`.

```
[*] Changed the `NFTImage` table
  [*] Column `orientation` would be dropped and recreated (type changed)

[*] Changed the `User` table
  [*] Column `roles` would be dropped and recreated (type changed)
```

I think I started seeing the problem again when I added the relations between `User`, `NFT` and `NFTImage` (which has its own enum for the `orientation` column. I wonder if the two enum columns in different models (`roles` and `orientation`) may be confusing the engine.

**Comment by tomhoule** [comment] 2022-11-09 16:42
Hi @alexisbellido — I confirmed in a test with your example schema that https://github.com/prisma/prisma-engines/commit/b4992e9e5cd68f256154172941977a3708320bda fixes the issue. Stay tuned for the patch release.

**Comment by janpio** [comment] 2022-11-09 17:43
@jameyhart It seems to me you are experiencing two things here at the same time: We changed our validations around `SetNull` - and then when you try to fix that, you hit the problem that is discussed in this thread. Can you please open a new issue for the `SetNull` change? I will want to discuss that with you and ask a few follow up questions. Thanks!

**Comment by BigBrainAFK** [comment] 2022-11-09 18:15
`@@map` in enum is also ignored when generating migrations. It just uses the enum name itself instead of the `@@map` name

**Comment by rcbevans** [comment] 2022-11-09 21:39
Came here looking for this because I just bumped to 4.6 to get Postgres native upserts (yay!) but now I'm seeing the same issue with Prisma attempting to drop and recreate all enum fields after trying to add a new migration to our schema.  Glad it's already on the radar with a fix pending.

**Comment by rcbevans** [comment] 2022-11-09 21:47
> Hi there wave Quick update from the Prisma folks: we are working on this. There is indeed a regression with enums in 4.6.0, and here's a PR to fix it [prisma/prisma-engines#3368](https://github.com/prisma/prisma-engines/pull/3368)
> 
> The bug appears when the following two conditions are met:
> 
>     1. Provider is `postgresql` or `cockroachdb`
> 
>     2. You use `@@map` on enums.
> 
> 
> The regression is that we started using the name of the enum instead of the mapped name (more details in the PR). This is a very embarassing gap in our tests.
> 
> **If you experience a regression with `db push` or `migrate dev` or `migrate diff` in 4.6.0 outside of the two conditions named above, please post here with as much detail as possible, because you are experiencing a different regression that will not be fixed by the PR in this comment.**

Is this comment still applicable,  I do not have @@map in my schema,  and am hitting this issue with 4.6.0.

**Comment by alexisbellido** [comment] 2022-11-09 22:16
Hello, @rcbevans , I'm not using @@map either so I think we're experiening similar problems and a few comments above @tomhoule confirmed the patch fixes it.

**Comment by rcbevans** [comment] 2022-11-09 22:32
Thanks @alexisbellido.  Fingers crossed it's the same underlying issue and 4.7 will resolve the issue for us also.  Thankfully I caught this before any of the team made any schema changes.

**Comment by Jolg42** [comment] 2022-11-09 22:56
@alexisbellido @rcbevans @bsproul @hoghweed @davidlumley
Could you try to update `prisma` and `@prisma/client` to the `4.6.1-dev.1` internal patch version that includes the fixes and let us know if that solves your issue?

We will wait for some confirmations before we publish the official patch to latest.

**Comment by jansedlon** [comment] 2022-11-10 08:48
@Jolg42 `4.6.1-dev.1` fixed it for me

**Comment by alexisbellido** [comment] 2022-11-10 15:07
@Jolg42 , I just tested `4.6.1-dev.1` and it fixes the issue for me too.

Thank you so much, Prisma team.

**Comment by Jolg42** [comment] 2022-11-10 15:09
The official patch is out in [`4.6.1`](https://github.com/prisma/prisma/releases/tag/4.6.1)

**Closed by Jolg42** 2022-11-10 15:09 UTC
Labels: bug/2-confirmed, kind/bug, team/schema, topic: prisma db push, topic: enums
