### ISSUE TITLE
OR Filter always constructs AND SQL Query

### ISSUE THREAD

**Issue by garytube** [prisma/prisma#8619] opened 2021-08-06 13:18 UTC
### Bug description

The OR Filter does not construct a WHERE clause with OR

### How to reproduce

query something and try to filter with OR[] https://www.prisma.io/docs/reference/api-reference/prisma-client-reference/#or

### Expected behavior

The **AND** clause is wrong. It should be **OR**.

### Prisma information

````js
// get every report that either has a lastUpdate  timestamp or the solvedAt date is in the future
const inProgressQuery: Query = await db.report.findMany({
		where: {
			OR: {
				solvedAt: {
					gt: new Date()
				},
				lastUpdate: {
					not: null
				}
			}
		}
	})
```

The Constructed Query (Prisma Log) looks like this

```sql
SELECT
    "public"."stov_reports"."id",
    "public"."stov_reports"."message",
    "public"."stov_reports"."status",
    "public"."stov_reports"."author",
    "public"."stov_reports"."createdAt",
    "public"."stov_reports"."solvedAt",
    "public"."stov_reports"."lastUpdate"
FROM
    "public"."stov_reports"
WHERE
    (
        "public"."stov_reports"."solvedAt" > $1
        AND "public"."stov_reports"."lastUpdate" IS NOT NULL
    ) 
```

No matter how I construct the query I always  get **AND** insted **OR**


$1 = new Date()

Schema
```
model Report {
  id         Int               @id @default(autoincrement())
  message    String
  status     String
  author     String?           @default("System")
  createdAt  DateTime          @default(now())
  solvedAt   DateTime?
  lastUpdate DateTime?

  @@index([id], name: "stov_reports.id_index")
}
```

### Environment & setup

- OS: Win / Linux (WSL)
- Database: PostgreSQL
- Node.js version:  14.5


### Prisma Version

```
"prisma": "^2.28.0",
```

**Comment by pantharshit00** [comment] 2021-08-06 13:33
You need to provide keys inside of an array which you want to be joined via OR. Keys inside single array item inside OR are joined via AND to allow composition.  

Here is what you need to do:
```ts
const inProgressQuery: Query = await db.report.findMany({
  where: {
    OR: [
      {
        solvedAt: {
          gt: new Date(),
        },
      },
      {
        lastUpdate: {
          not: null,
        },
      },
    ],
  },
});
```

Closing as duplicate of https://github.com/prisma/prisma/issues/4831

**Closed by pantharshit00** 2021-08-06 13:33 UTC
Labels: kind/bug
