### ISSUE TITLE
When using multiple schemes on existing DB can't run first deploy. 

### ISSUE THREAD

**Issue by blazestudios23** [prisma/prisma#18049] opened 2023-02-22 19:20 UTC
### Bug description

I am using 3 schemas in my schema.prisma file because the 3 schemas have interconnected tables. 

I am able to run:
```bash
prisma migrate dev --name initial-migration --create-only
```

I copied a dump of my DB to the migration.sql file so it actually matches my database, there were some things off and the database is quite large so we easier just to copy the file. 

### How to reproduce

When I run:

```bash
prisma migrate dev --name deploy
```

It asks, "Do you want to continue? All data will be lost. › (y/N)"

Then I get the following error:
 
```bash
The underlying table for model `_prisma_migrations` does not exist.
```

### Expected behavior

For the migration to succeed. 

### Prisma information

```prisma
generator client {
  provider        = "prisma-client-js"
  previewFeatures = ["multiSchema"]
}

datasource db {
  provider = "postgres"
  url      = env("DATABASE_URL_PRISMA")
  schemas  = ["catalog", "public", "saas",]
}
```

### Environment & setup

- OS: macOS
- Database: PostgreSQL
- Node.js version: 16.16

### Prisma Version

```bash
prisma                  : 4.10.1
@prisma/client          : 4.10.1
Current platform        : darwin-arm64
Query Engine (Node-API) : libquery-engine aead147aa326ccb985dcfed5b065b4fdabd44b19 (at ../../../node_modules/@prisma/engines/libquery_engine-darwin-arm64.dylib.node)
Migration Engine        : migration-engine-cli aead147aa326ccb985dcfed5b065b4fdabd44b19 (at ../../../node_modules/@prisma/engines/migration-engine-darwin-arm64)
Format Wasm             : @prisma/prisma-fmt-wasm 4.10.1-1.80b351cc7c06d352abe81be19b8a89e9c6b7c110
Default Engines Hash    : aead147aa326ccb985dcfed5b065b4fdabd44b19
Studio                  : 0.481.0
Preview Features        : multiSchema
```

**Comment by blazestudios23** [comment] 2023-02-24 17:35
I found that that error is being caused by this:
```migration.sql
SELECT pg_catalog.set_config('search_path', '', false);
```

**Comment by janpio** [comment] 2023-03-02 01:18
Did removing that line fully resolve your problem @blazestudios23?

**Comment by Jolg42** [comment] 2023-06-13 10:40
This is a duplicate of https://github.com/prisma/prisma/issues/13269

```
SELECT pg_catalog.set_config('search_path', '', false);
```

Most probably this line here comes from `pg_dump` which always adds it to a dump. (see https://github.com/prisma/prisma/issues/13269#issuecomment-1123932218)

It's something we should probably mention in our docs: it needs to be removed for the dump to be usable in a (baseline) migration.

**Closed by Jolg42** 2023-06-13 10:40 UTC
Labels: bug/1-unconfirmed, kind/bug, team/schema, topic: prisma migrate dev, topic: multiSchema

**Comment by Jolg42** [comment] 2023-06-13 10:54
Note: I created a docs isssue: https://github.com/prisma/docs/issues/4906
