### ISSUE TITLE
Prisma errors when using ngrok

### ISSUE THREAD

**Issue by camjw** [prisma/prisma#4240] opened 2019-03-21 22:19 UTC
Prisma can't deploy when [ngrok](https://github.com/inconshreveable/ngrok) is running.

I'm running Prisma using Docker and Postgres and I've got a pretty standard `prisma.yml`, and everything works fine usually. When I run it with ngrok running in the background (on a completely random port) then I get the following error:

```
pg_container is up-to-date
prisma_container is up-to-date
 ▸    Could not connect to server at http://localhost:4040. Please check if your
 ▸    server is running.
```
I get a similar error when I try to query the running api, the api says it can't find my endpoint.

When I turn ngrok off again then everything works fine. 

This is obviously pretty niche, but I wonder if there is anything I can do to use ngrok and prisma at the same time?

**Comment by divyenduz** [comment] 2019-03-22 10:53
Can you share the output of `docker ps` command? Normally, Prisma server runs on `4466` port by default and the correct ngrok command would be `ngrok http 4466`. Please let me know if that works?

**Comment by camjw** [comment] 2019-03-22 17:18
Hi, sorry I've been a bit unclear maybe. I'm not trying to tunnel my prisma instance through ngrok, I was trying to use ngrok for something completely unrelated.

My prisma instance runs on port `4040`, but when I had ngrok running I couldn't connect to it at all. I can share my docker ps in a couple of hours.

**Comment by divyenduz** [comment] 2019-03-22 17:21
Interesting, so you mean when any tunnel is turned on even at a non Prisma port, prisma stops working? What ports were you actually tunneling though, maybe there is a co-relation.

**Comment by camjw** [comment] 2019-03-23 14:18
Exactly yeah, I was running prisma on `4040`, then I had a graphql-yoga server running on port `4000`, and I was ngrok-ing `8070`.

**Comment by divyenduz** [comment] 2019-03-29 15:59
@camjw I was unable to reproduce this issue, I was able to using `ngrok` on other port and still access Prisma and also using `ngrok` on Prisma directly.

**Comment by divyenduz** [comment] 2019-04-08 14:18
I am closing this issue, I am unable to reproduce and have been using `ngrok` around / with Prisma with no issues. Please re-open the issue if the problem persists for you.

**Closed by divyenduz** 2019-04-08 14:18 UTC
Labels: area/deploy, bug/0-needs-info
