### ISSUE TITLE
Scalability performance issue

### ISSUE THREAD

**Issue by mark0vsk1** [prisma/prisma#8970] opened 2021-08-27 13:41 UTC
### Bug description

Hello,

We have a prisma client connected to mysql database. We run it on Rancher with Haproxy ingress. With different scale of containers I am getting different results. I am running benchmarks with simple query and getting the following results:

1 container = 238 req/s = 1.8 CPU Load - avg response time = 1.1s
2 container = 468 req/s = 4.2 CPU Load - avg response time = 0.6s
3 container = 660 req/s = 6 CPU Load - avg response time = 0.73s
4 container = 831 req/s = 7.8 CPU Load - avg response time = 0.59s
5 container = 950 req/s = 10 CPU Load - avg response time = 0.72s
6 container = 1020 req/s = 16 CPU Load - avg response time = 0.78s

My server performance is 16 CPU, 32 GB RAM memory

The tests are performed with wrk.

My question is: Why the req/s increases with scaling of the containers? Isn't supposed to get stright away 1000 req/s with 1 container?

Thank you

### How to reproduce

N/A

### Expected behavior

It should have same req/s with 1 container.

### Prisma information

```
query {
  findManyUser {
    id
    username
  }
}
```

### Environment & setup

- OS: Debian 10 (Docker container)
- Database: MySQL
- Node.js version: v16.8.0

### Prisma Version

2.29.1

**Comment by jkomyno** [comment] 2023-07-13 15:41
Hey @mark0vsk1, looking back at this issue for bookkeeping purposes. This looks like a duplicate of https://github.com/prisma/prisma/issues/7165. Recent Prisma versions have heavily improved the overall query performance.
Would you like to try again with the [recently released](https://www.prisma.io/blog/prisma-5-f66prwkjx72s) `prisma@5.0.0` version, and report here any concerning performance results? We believe this issue is already solved now. Thanks!

**Comment by jkomyno** [comment] 2023-07-25 23:59
Hey @mark0vsk1, would you confirm that the comment above fixes this issue? Thanks.

**Comment by mark0vsk1** [comment] 2023-07-26 14:03
Unfortunatelly I can’t test it anymore. We moved to different stack with
hasura.

**Comment by janpio** [comment] 2023-07-27 09:43
Ok, thanks for the update.

I will close the issue then, as we won't be able to confirm that this is fixed without more information - but we have a _very_ strong hunch it is.

If anyone, even you @mark0vsk1 in a future project using Prisma, has any similar observations, don't hesitate to comment here or even better open a new issue with all the information our issue template asks for. We are eager to look at these, to understand and fix any problems. Thanks!

**Closed by janpio** 2023-07-27 09:43 UTC
Labels: bug/0-unknown, kind/bug, topic: performance, team/client
