### ISSUE TITLE
PANIC in query-engine/connectors/sql-query-connector/src/database/operations/write.rs:73:22Could not figure out an ID in create

### ISSUE THREAD

**Issue by Stallion67** [prisma/prisma#15067] opened 2022-08-29 17:49 UTC
Hi Prisma Team! My Prisma Client just crashed. This is the report:
## Versions

| Name            | Version            |
|-----------------|--------------------|
| Node            | v12.21.0           | 
| OS              | rhel-openssl-1.0.x |
| Prisma Client   | 2.30.3             |
| Query Engine    | query-engine b8c35d44de987a9691890b3ddf3e2e7effb9bf20|
| Database        | undefined|

## Logs
```
0A++++FarmAcreage%0A++++password_old%0A++++password%0A++++id_no%0A++++services%0A++++phone_activation_code%0A++++phone_status%0A++++email_activation_code%0A++++email_status%0A++++account_status%0A++++subscription_status%0A++++wallet_amount%0A++++password_reset_key%0A++++online_status%0A++++last_seen%0A++++search_rank%0A++++old_email%0A++++deleted%0A++++country%0A++++gender%0A++++dob%0A++++pro_dealin%0A++++size_scale%0A++++looking_for%0A++++cover_picture%0A++++profile_picture%0A++++other_contacts%0A++++website%0A++++user_documents%0A++++address%0A++++reg_time%0A++%7D%0A%7D%0A%60%60%60%0A&title=PANIC+in+query-engine%2Fconnectors%2Fsql-query-connector%2Fsrc%2Fdatabase%2Foperations%2Fwrite.rs%3A73%3A22%0ACould+not+figure+out+an+ID+in+create&template=bug_report.md

If you want the Prisma team to look into it, please open the link above 🙏
To increase the chance of success, please post your schema and a snippet of
how you used Prisma Client in the issue. 

    at BinaryEngine.throwAsyncErrorIfExists (/app/node_modules/@prisma/client/runtime/index.js:30038:21)
    at BinaryEngine.handleRequestError (/app/node_modules/@prisma/client/runtime/index.js:29358:16)
    at BinaryEngine.request (/app/node_modules/@prisma/client/runtime/index.js:29959:20)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
prisma:engine { cwd: '/app/prisma' }
prisma:engine Search for Query Engine in /app/node_modules/.prisma/client
plusX Execution permissions of /app/node_modules/.prisma/client/query-engine-rhel-openssl-1.0.x are fine
prisma:engine { flags: [ '--enable-raw-queries', '--port', '45811' ] }
prisma:engine stdout  Starting a mysql pool with 3 connections.
prisma:engine stdout  Started http server on http://127.0.0.1:45811
prisma:engine Search for Query Engine in /app/node_modules/.prisma/client
plusX Execution permissions of /app/node_modules/.prisma/client/query-engine-rhel-openssl-1.0.x are fine
prisma:engine Client Version: 2.30.3
prisma:engine Engine Version: query-engine b8c35d44de987a9691890b3ddf3e2e7effb9bf20
prisma:engine Active provider: mysql
prisma:engine stdout  PANIC in query-engine/connectors/sql-query-connector/src/database/operations/write.rs:73:22
Could not figure out an ID in create
prisma:engine {
  error: SocketError: other side closed
      at Socket.onSocketEnd (/app/node_modules/@prisma/client/runtime/index.js:27696:24)
      at Socket.emit (events.js:326:22)
      at Socket.EventEmitter.emit (domain.js:483:12)
      at endReadableNT (_stream_readable.js:1241:12)
      at processTicksAndRejections (internal/process/task_queues.js:84:21) {
    code: 'UND_ERR_SOCKET'
  }
}
prisma:engine { cwd: '/app/prisma' }
prisma:engine Search for Query Engine in /app/node_modules/.prisma/client
plusX Execution permissions of /app/node_modules/.prisma/client/query-engine-rhel-openssl-1.0.x are fine
prisma:engine { flags: [ '--enable-raw-queries', '--port', '37245' ] }
prisma:engine stdout  Starting a mysql pool with 3 connections.
prisma:engine stdout  Started http server on http://127.0.0.1:37245
prisma:engine Search for Query Engine in /app/node_modules/.prisma/client
plusX Execution permissions of /app/node_modules/.prisma/client/query-engine-rhel-openssl-1.0.x are fine
prisma:engine Client Version: 2.30.3
prisma:engine Engine Version: query-engine b8c35d44de987a9691890b3ddf3e2e7effb9bf20
prisma:engine Active provider: mysql
prisma:engine stdout  PANIC in query-engine/connectors/sql-query-connector/src/database/operations/write.rs:73:22
Could not figure out an ID in create
prisma:engine {
  error: SocketError: other side closed
      at Socket.onSocketEnd (/app/node_modules/@prisma/client/runtime/index.js:27696:24)
      at Socket.emit (events.js:326:22)
      at Socket.EventEmitter.emit (domain.js:483:12)
      at endReadableNT (_stream_readable.js:1241:12)
      at processTicksAndRejections (internal/process/task_queues.js:84:21) {
    code: 'UND_ERR_SOCKET'
  }
}
prisma:engine {
  error: Error: connect ECONNREFUSED 127.0.0.1:37245
      at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1144:16) {
    errno: 'ECONNREFUSED',
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '127.0.0.1',
    port: 37245
  }
}
```

## Client Snippet
```ts
// PLEASE FILL YOUR CODE SNIPPET HERE
```

## Schema
```prisma
// PLEASE ADD YOUR SCHEMA HERE IF POSSIBLE
```

## Prisma Engine Query
```
}
```

**Comment by janpio** [comment] 2022-08-29 20:52
Duplicate of https://github.com/prisma/prisma/issues/15066

**Closed by janpio** 2022-08-29 20:52 UTC
