### ISSUE TITLE
Error in Schema engine

### ISSUE THREAD

**Issue by khai-pi** [prisma/prisma#25934] opened 2024-12-26 16:17 UTC
### Bug description

Error when try to use prisma postgres. Following starter set up and encountered this
Error in Schema engine.
Reason: [/Users/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/ws_stream_tungstenite-0.14.0/src/tung_websocket.rs:540:13] internal error: entered unreachable code: protocol error from tungstenite on send is a bug in ws_stream_tungstenite, please report at http://github.com/najamelan/ws_stream_tungstenite/issues. The error from tungstenite is Sending after closing is not allowed

### How to reproduce

1. Download project
`npx try-prisma@latest --template databases/prisma-postgres --name hello-prisma --install npm`
2. Set up database access in .env
3. Setup database
`npx prisma migrate dev --name init`

### Expected behavior

Database schemas are migrated

### Prisma information

```
generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

model User {
  id      Int      @id @default(autoincrement())
  email   String   @unique
  name    String?
  posts   Post[]
}

model Post {
  id        Int     @id @default(autoincrement())
  title     String
  content   String?
  published Boolean @default(false)
  author    User?   @relation(fields: [authorId], references: [id])
  authorId  Int?
}
```

### Environment & setup

- OS: macOS M2
- Database:  Prisma Postgres
- Node.js version: v20.18.1

### Prisma Version

```
prisma                  : 5.22.0
@prisma/client          : 5.22.0
Computed binaryTarget   : darwin-arm64
Operating System        : darwin
Architecture            : arm64
Node.js                 : v20.18.1
Query Engine (Node-API) : libquery-engine 605197351a3c8bdd595af2d2a9bc3025bca48ea2 (at node_modules/@prisma/engines/libquery_engine-darwin-arm64.dylib.node)
Schema Engine           : schema-engine-cli 605197351a3c8bdd595af2d2a9bc3025bca48ea2 (at node_modules/@prisma/engines/schema-engine-darwin-arm64)
Schema Wasm             : @prisma/prisma-schema-wasm 5.22.0-44.605197351a3c8bdd595af2d2a9bc3025bca48ea2
Default Engines Hash    : 605197351a3c8bdd595af2d2a9bc3025bca48ea2
Studio                  : 0.503.0
```

**Comment by jkomyno** [comment] 2024-12-30 15:23
Closing this as a duplicate of https://github.com/prisma/prisma/issues/25543.

Please try out [this recommendation](https://github.com/prisma/prisma/issues/25543#issuecomment-2471822640). Thanks!

**Closed by jkomyno** 2024-12-30 15:23 UTC
Labels: kind/bug
