### ISSUE TITLE
Prisma Migrate errors with `Environment is non-interactive` when `VERCEL` env var is defined

### ISSUE THREAD

**Issue by testerez** [prisma/prisma#22380] opened 2023-12-13 20:53 UTC
### Bug description

Since I updated from `prisma@5.6.0` to `prisma@5.7.0`, I'm getting this error message even though I'm running in a regular interactive terminal:
```
Error: Prisma Migrate has detected that the environment is non-interactive, which is not supported.
```

### How to reproduce

1. Install `prisma@5.7.0`
2. run `prisma migrate dev`
3. I'm getting the above error

### Prisma information

Not relevant

### Environment & setup

- OS: macOS
- Database: PostgreSQL
- Node.js version: v20.10.0

### Prisma Version

```
prisma                  : 5.7.0
@prisma/client          : 5.7.0
Computed binaryTarget   : darwin-arm64
Operating System        : darwin
Architecture            : arm64
Node.js                 : v20.10.0
Query Engine (Node-API) : libquery-engine 79fb5193cf0a8fdbef536e4b4a159cad677ab1b9 (at ../../Library/pnpm/global/5/.pnpm/@prisma+engines@5.7.0/node_modules/@prisma/engines/libquery_engine-darwin-arm64.dylib.node)
Schema Engine           : schema-engine-cli 79fb5193cf0a8fdbef536e4b4a159cad677ab1b9 (at ../../Library/pnpm/global/5/.pnpm/@prisma+engines@5.7.0/node_modules/@prisma/engines/schema-engine-darwin-arm64)
Schema Wasm             : @prisma/prisma-schema-wasm 5.7.0-41.79fb5193cf0a8fdbef536e4b4a159cad677ab1b9
Default Engines Hash    : 79fb5193cf0a8fdbef536e4b4a159cad677ab1b9
Studio                  : 0.495.0
Preview Features        : views
```

**Comment by jeff-an** [comment] 2023-12-14 02:02
+1, happening to me as well. a regression from https://github.com/prisma/prisma/issues/4669?

**Comment by samuelcole** [comment] 2023-12-14 16:29
happening to me: i'm running `yarn workspace foo prisma migrate dev` using yarn workspaces in vscode's terminal

**Comment by aqrln** [comment] 2023-12-15 09:51
I'm on macOS but I can't reproduce this. Could you share some more details please? Which terminal emulator are you using? Could you post the output of `npx prisma debug`?

**Comment by testerez** [comment] 2023-12-15 10:22
I think it fails only in certains situations. I can't make it fail right now. Though, if I change something in my schema, it won't prompt for the migration name as usual. It creates the migration directly with no name:

```
Applying migration `20231215101702_`

The following migration(s) have been created and applied from new schema changes:

migrations/
  └─ 20231215101702_/
    └─ migration.sql

Your database is now in sync with your schema.
```

I guess "CI detected" is the issue: 
```
> npx prisma debug

Environment variables loaded from .env
-- Prisma schema --
Path: /Users/***/prisma/schema.prisma

-- Local cache directory for engines files --
Path: /Users/***/.cache/prisma

-- Environment variables --
When not set, the line is dimmed and no value is displayed.
When set, the line is bold and the value is inside the `` backticks.

For general debugging
- CI:
- DEBUG:
- NODE_ENV:
- RUST_LOG:
- RUST_BACKTRACE:
- NO_COLOR:
- TERM: `xterm-256color`
- NODE_TLS_REJECT_UNAUTHORIZED:
- NO_PROXY:
- http_proxy:
- HTTP_PROXY:
- https_proxy:
- HTTPS_PROXY:

For more information about Prisma environment variables:
See https://www.prisma.io/docs/reference/api-reference/environment-variables-reference

For hiding messages
- PRISMA_DISABLE_WARNINGS:
- PRISMA_HIDE_PREVIEW_FLAG_WARNINGS:
- PRISMA_HIDE_UPDATE_MESSAGE:

For downloading engines
- PRISMA_ENGINES_MIRROR:
- PRISMA_BINARIES_MIRROR (deprecated):
- PRISMA_ENGINES_CHECKSUM_IGNORE_MISSING:
- BINARY_DOWNLOAD_VERSION:

For configuring the Query Engine Type
- PRISMA_CLI_QUERY_ENGINE_TYPE:
- PRISMA_CLIENT_ENGINE_TYPE:

For custom engines
- PRISMA_QUERY_ENGINE_BINARY:
- PRISMA_QUERY_ENGINE_LIBRARY:
- PRISMA_SCHEMA_ENGINE_BINARY:
- PRISMA_MIGRATION_ENGINE_BINARY:

For the "postinstall" npm hook
- PRISMA_GENERATE_SKIP_AUTOINSTALL:
- PRISMA_SKIP_POSTINSTALL_GENERATE:
- PRISMA_GENERATE_IN_POSTINSTALL:

For "prisma generate"
- PRISMA_GENERATE_DATAPROXY:
- PRISMA_GENERATE_NO_ENGINE:

For Prisma Client
- PRISMA_SHOW_ALL_TRACES:
- PRISMA_CLIENT_NO_RETRY (Binary engine only):}

For Prisma Migrate
- PRISMA_SCHEMA_DISABLE_ADVISORY_LOCK:
- PRISMA_MIGRATE_SKIP_GENERATE:
- PRISMA_MIGRATE_SKIP_SEED:

For Prisma Studio
- BROWSER:

-- Terminal is interactive? --
true

-- CI detected? --
true
```

**Comment by Jolg42** [comment] 2023-12-15 12:22
Hi there! I probably caused this with https://github.com/prisma/prisma/pull/22175 
Let's try to identify if that's the cause together.

If this is the cause
- the CI detection would only be `true` for `5.7.0` and up. (Lower versions should not be affected.)
- Check out the list of environment variable from https://github.com/prisma/prisma/blob/main/packages/internals/src/utils/isCi.ts
- Run `node -e "console.log(process.env)"`
	- Do you see any environment variable defined at runtime that are checked in `isCi`?
- Check your `.env` file(e) if you have any
	- Do you see any environment variable defined at runtime that are checked in `isCi`?

**Comment by Jolg42** [comment] 2023-12-15 12:26
One easy way to check the env vars would be for you to run the following
```
npm install ci-info
node -e "var ci = require('ci-info'); console.log(ci)"
```

**Comment by testerez** [comment] 2023-12-15 13:58
Here is the result:

```
{
  name: null,
  isPR: null,
  AGOLA: false,
  APPCIRCLE: false,
  APPVEYOR: false,
  CODEBUILD: false,
  AZURE_PIPELINES: false,
  BAMBOO: false,
  BITBUCKET: false,
  BITRISE: false,
  BUDDY: false,
  BUILDKITE: false,
  CIRCLE: false,
  CIRRUS: false,
  CODEFRESH: false,
  CODEMAGIC: false,
  CODESHIP: false,
  DRONE: false,
  DSARI: false,
  EARTHLY: false,
  EAS: false,
  GERRIT: false,
  GITEA_ACTIONS: false,
  GITHUB_ACTIONS: false,
  GITLAB: false,
  GOCD: false,
  GOOGLE_CLOUD_BUILD: false,
  HARNESS: false,
  HEROKU: false,
  HUDSON: false,
  JENKINS: false,
  LAYERCI: false,
  MAGNUM: false,
  NETLIFY: false,
  NEVERCODE: false,
  PROW: false,
  RELEASEHUB: false,
  RENDER: false,
  SAIL: false,
  SCREWDRIVER: false,
  SEMAPHORE: false,
  SOURCEHUT: false,
  STRIDER: false,
  TASKCLUSTER: false,
  TEAMCITY: false,
  TRAVIS: false,
  VELA: false,
  VERCEL: false,
  APPCENTER: false,
  WOODPECKER: false,
  XCODE_CLOUD: false,
  XCODE_SERVER: false,
  isCI: false
}
```

**Comment by testerez** [comment] 2023-12-15 14:01
> Do you see any environment variable defined at runtime that are checked in isCi?

I do have `VERCEL="1"` in my `.env`

**Comment by samuelcole** [comment] 2023-12-15 16:09
indeed! i use [`vercel pull`](https://vercel.com/docs/cli/pull) to populate my local environment, which contains a bunch of vercel env vars:

```
VERCEL="1"
VERCEL_ENV="development"
VERCEL_GIT_COMMIT_AUTHOR_LOGIN=""
VERCEL_GIT_COMMIT_AUTHOR_NAME=""
VERCEL_GIT_COMMIT_MESSAGE=""
VERCEL_GIT_COMMIT_REF=""
VERCEL_GIT_COMMIT_SHA=""
VERCEL_GIT_PREVIOUS_SHA=""
VERCEL_GIT_PROVIDER=""
VERCEL_GIT_PULL_REQUEST_ID=""
VERCEL_GIT_REPO_ID=""
VERCEL_GIT_REPO_OWNER=""
VERCEL_GIT_REPO_SLUG=""
VERCEL_URL=""
```

**Comment by testerez** [comment] 2023-12-15 16:13
Same here, I'm using [vercel pull](https://vercel.com/docs/cli/pull)

**Comment by Jolg42** [comment] 2023-12-15 23:02
Thank you for, it looks like the common problem is the `VERCEL` env var here.
I opened a PR to remove it from the detection https://github.com/prisma/prisma/pull/22431

**Closed** 2023-12-16 10:12 UTC
Labels: kind/regression, topic: migrate, tech/typescript, topic: environment
