### ISSUE TITLE
[^1.14.0] Internal server error with specific filter

### ISSUE THREAD

**Issue by oxy88** [prisma/prisma#2971] opened 2018-08-29 07:32 UTC
**Describe the bug**
Whoops. Looks like an internal server error. Search your server logs

**To Reproduce**
https://github.com/oxy88/prisma_bug_report
this is my model 
Shop -> Owner -  One to One
Owner -> Fruit  - One to Many
Fruit -> Color    - One to One
```
type Shop {
  id: ID! @unique
  owner: Owner
}

type Owner {
  id: ID! @unique
  shop: Shop
  favoriteFruits: [Fruit!]!
}

type Fruit {
  id: ID! @unique
  owner: Owner
  color: Color
}

type Color {
  id: ID! @unique
  fruit: Fruit
}
```
1. https://us1.prisma.sh/public-jadekoala-720/bug_report/dev
2.
```
Steps to reproduce the behavior:
{
  shops(
    where: {
      owner: {
        favoriteFruits_some: {
          color: {
            id: "ANY_ID"
          }
        }
      }
    }
  ) {
    id
  }
}
```

**Expected behavior**
Works with prisma 1.13
Dosn't work with prisma 1.14 and 1.15

**Screenshots**

**Versions (please complete the following information):**
 - OS: [e.g. `Windows 10`, `OS X High Sierra`, `Ubuntu 16.04`] 
 - `prisma` CLI: [e.g. `prisma/1.9.0 (darwin-x64) node-v10.4.0`]
 - Prisma Server: [e.g. `1.9.0`]
 - `graphql-cli`, `prisma-binding`, `graphql-yoga`, etc. if applicable

**Additional context**

**Comment by timchambers** [comment] 2018-08-29 17:40
Hmm, I seem to be hitting this too after upgrading from 1.12.2 to 1.14.2 with a similar schema and query.

**Comment by marktani** [comment] 2018-08-30 07:56
Hey @oxy88 and @timchambers, are you using the Postgres or MySQL connector?

**Comment by oxy88** [comment] 2018-08-30 07:57
@marktani MySQL

**Comment by timchambers** [comment] 2018-08-30 08:12
@marktani MySQL

**Comment by marktani** [comment] 2018-08-30 10:06
Thanks a lot for the additional information! I'm closing this as duplicate of https://github.com/prisma/prisma/issues/2971. We'll look into this soon!

**Closed by marktani** 2018-08-30 10:06 UTC
Labels: connectors/mysql, reproduction-available

**Comment by timchambers** [comment] 2018-08-30 10:32
@marktani #2971 is this one, what’s the original issue?

**Comment by marktani** [comment] 2018-08-30 10:34
Sorry just updated my comment to the original issue 😄
