### ISSUE TITLE
These id fields were enriched with `@default(cuid())` information taken from the previous Prisma schema

### ISSUE THREAD

**Issue by omar-dulaimi** [prisma/prisma#5799] opened 2021-02-23 12:12 UTC
## Bug description

While in the process of upgrading from prisma 1.13, I usually run introspection after each step. so one warning kept showing even though I don't think there's a need for it, correct me please.

## How to reproduce

I just run 
```
npx prisma introspect
```

```
*** WARNING ***
These id fields were enriched with `@default(cuid())` information taken from the previous Prisma schema.
- Model "A", field: "id"
- Model "B", field: "id"
.
.
.etc

```
## Expected behavior

I think it should not be shown given the schema has actually been enriched

## Prisma information

```
model Item1 {
  id                  String                 @id @default(cuid()) @db.Char(30)
}

model Item2 {
  id                  String                 @id @default(cuid()) @db.Char(30)
}

```

## Environment & setup

OS: Ubuntu 18
Database: MySQL 5.7
Node.js version: 14.15.1
```
Prisma version:
prisma               : 2.17.0
@prisma/client       : 2.17.0
Current platform     : debian-openssl-1.1.x
Query Engine         : query-engine 3c463ebd78b1d21d8fdacdd27899e280cf686223 (at node_modules/@prisma/engines/query-engine-debian-openssl-1.1.x)
Migration Engine     : migration-engine-cli 3c463ebd78b1d21d8fdacdd27899e280cf686223 (at node_modules/@prisma/engines/migration-engine-debian-openssl-1.1.x)
Introspection Engine : introspection-core 3c463ebd78b1d21d8fdacdd27899e280cf686223 (at node_modules/@prisma/engines/introspection-engine-debian-openssl-1.1.x)
Format Binary        : prisma-fmt 3c463ebd78b1d21d8fdacdd27899e280cf686223 (at node_modules/@prisma/engines/prisma-fmt-debian-openssl-1.1.x)
Studio               : 0.353.0

```

**Comment by Jolg42** [comment] 2021-02-23 16:37
Originally posted on public Slack https://prisma.slack.com/archives/CKQTGR6T0/p1614079138142300

**Comment by pantharshit00** [comment] 2021-03-02 20:19
@omar-dulaimi Can you your database schema in SQL? 

I think you can safely ignore this warning but we can improve the detection if you can share the schema for a reproduction .

**Comment by omar-dulaimi** [comment] 2021-03-02 21:00
Hello @pantharshit00 
I can't share all of the schema, unfortunately, so here's one of the affected tables:

```
--
-- Table structure for table `Abuse`
--

DROP TABLE IF EXISTS `Abuse`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `Abuse` (
  `id` char(30) CHARACTER SET utf8 NOT NULL,
  `type` enum('USER','ITEM') COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'ITEM',
  `category` enum('INAPPROPRIATE_IMAGE_ITEM','INACCURATE_PRICE_ITEM','SOLD_UNAVAILABLE_ITEM','INVALID_LOCATION') COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'MISC_ITEM',
  `message` mediumtext COLLATE utf8mb4_unicode_ci,
  `updatedAt` datetime(3) NOT NULL,
  `createdAt` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `status` enum('PENDING_REVIEW','COMPLETED') COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'PENDING_REVIEW',
  `itemId` char(30) CHARACTER SET utf8 DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `id_UNIQUE` (`id`),
  KEY `itemId` (`itemId`),
  CONSTRAINT `Abuse_ibfk_3` FOREIGN KEY (`itemId`) REFERENCES `Item` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
```

**Comment by omar-dulaimi** [comment] 2021-03-02 21:01
There's also a similar warning about @updatedAt fields:


```
These DateTime fields were enriched with `@updatedAt` information taken from the previous Prisma schema.
- Model "Abuse", field: "updatedAt"
```

**Comment by janpio** [comment] 2021-03-03 12:03
These messages were added because you _could_ have removed or changed that in the database, and Prisma would still enrich the schema based on the old schema.

**Comment by omar-dulaimi** [comment] 2021-03-03 12:35
@janpio Why would it enrich it based on the old schema though? I'm not using the upgrade cli at this point, so introspection should have no idea what the old schema is, right?

**Comment by Jolg42** [comment] 2021-03-03 13:05
@omar-dulaimi You can actually disable this behavior with the `--force` flag like this `npx prisma introspect --force` which means "Ignore current Prisma schema file".

**Comment by omar-dulaimi** [comment] 2021-03-03 13:20
@Jolg42 doing that I lost the following attributes from the schema:
```
@default(cuid())
@updatedAt
```

Also relation fields names have changed to their models names, like reporter changed to AbuseReporter camelcase.

It basically messes the whole schema up and I have to go through the 700 lines schema line by line to fix the issues.

So I have no choice but to undo the --force

**Comment by janpio** [comment] 2021-03-03 14:59
> @janpio Why would it enrich it based on the old schema though? I'm not using the upgrade cli at this point, so introspection should have no idea what the old schema is, right?

This does not refer to the Prisma 1 schema, but the existing Prisma 2 schema file. You probably created that with the upgrade tool (if I follow you correctly, mentioning that you are upgrading from Prisma 1.13). But each time you run `prisma introspect` it will look at the existing schema file, to add some information to the updated schema file (that picks up changes you did on the database directly).

**Comment by omar-dulaimi** [comment] 2021-03-03 15:49
@janpio No, nothing is broken.

**Comment by janpio** [comment] 2021-03-03 18:04
Would the message make more sense to you if it would say `These id fields were enriched with `@default(cuid())` information taken from the previous 'schema.prisma'  file.`? Or would any other explanation help in understanding what is going on here?

**Comment by omar-dulaimi** [comment] 2021-03-03 20:21
I think it should explain that Prisma cannot tell if the field is for example cuid(), and thus these warnings have to be shown after every introspection.
In addition to that, it could also mention that this warning won't be shown again, but the same enriching behavior will occur at each introspection.

**Comment by gustawdaniel** [comment] 2021-08-07 09:37
I have similar problem with @updatedAt

I see warining

```
fields were enriched with `@updatedAt` information taken from the previous Prisma schema.
```

Expected behavior:

I execute

```
prisma db push
```

and then

```
prisma db pull
```

I do not see warinig, because of information from `@updatedAt` can be read from db schema.

Now `SHOW CREATE TABLE` shows for this field

```
  `updated_at` datetime NOT NULL,
```

There is article explaining how it can be done:

https://medium.com/@bengarvey/use-an-updated-at-column-in-your-mysql-table-and-make-it-update-automatically-6bf010873e6a

I meadn

```
  updated_at TIMESTAMP NOT NULL DEFAULT NOW() ON UPDATE now(),
```

**Comment by carlosbensant** [comment] 2022-02-20 03:55
They mentioned something about using the `@default(cuid())` and `@updatedAt` attributes here:
https://www.prisma.io/docs/guides/upgrade-guides/upgrade-from-prisma-1/schema-incompatibilities-postgres#manually-add-the-updatedat-attribute-to-the-prisma-model

They're well-known problems and are seen/provided as workarounds.

**Comment by janpio** [comment] 2022-11-17 09:57
I am closing this issue, as I think there is nothing wrong.

The database does not include some information, but the previous schema file does. So we keep the information around and tell you via that warning. If you want to get rid of it, remove it in the schema file and it will not appear again. If you want the functionality, Introspection will keep telling you about it.

**Closed by janpio** 2022-11-17 09:57 UTC
Labels: kind/improvement, topic: introspection, topic: prisma-upgrade, team/schema
