### ISSUE TITLE
Custom type for id

### ISSUE THREAD

**Issue by yovanoc** [prisma/prisma#2137] opened 2020-04-08 17:30 UTC
Hello,

When we have a custom type define like this

```
type CustomId =  Int @id @default(autoincrement())
```

and make a reference like this specified in the beta 1 changelog (while replacing the 2 ids by the custom type)

![image](https://user-images.githubusercontent.com/7302317/78814582-1ffbac80-79cf-11ea-8544-44c5af6f7f94.png)

Here's the error:

```
Error parsing attribute "@@relation": The type of the field `userId` in the model `Profile` is not matching the type of the referenced field `id` in model `User`.
```

but without the custom type it's working properly.

thanks

**Comment by deibeljc** [comment] 2020-04-08 18:34
@yovanoc it looks like they broke something in beta-2 around this. Without the explicit relation mapping nested creates do not work. beta-1 still seems to work fine however

**Comment by pantharshit00** [comment] 2020-04-09 09:07
I can reproduce this with `beta.2` and `2.0.0-alpha.1047`. 


Type alias are not being properly considered in schema validation right now.

**Comment by mavilein** [comment] 2020-04-16 14:33
fixed in: https://github.com/prisma/prisma-engines/pull/673

**Closed by mavilein** 2020-04-16 14:33 UTC
Labels: bug/2-confirmed, kind/bug, team/engines
