### ISSUE TITLE
Module '"@prisma/client"' has no exported member 'Prisma' on Docker image build

### ISSUE THREAD

**Issue by efrodriguez** [prisma/prisma#12417] opened 2022-03-17 21:38 UTC
### Bug description

When compiling from Typescript down to JS, I get the following error: `error TS2305: Module '"@prisma/client"' has no exported member 'Prisma'.`

This only happens when building a Docker image. When building locally on my host I have no issues.

Older versions of the Docker engine are not giving issues.

![Screen Shot 2022-03-17 at 9 58 53 AM](https://user-images.githubusercontent.com/49210729/158899380-423edad5-13de-4997-9f4a-5e3ef467b6cd.png)

![Screen Shot 2022-03-17 at 5 40 51 PM](https://user-images.githubusercontent.com/49210729/158899560-ff1bf94e-4320-4743-82e6-383c0b017690.png)

### How to reproduce

Dockerize your app on Docker engine `20.10.13`. After installing dependencies and trying to build the project, TS should complain about the above error.

### Expected behavior

The app should compile from TS to JS successfully.

### Environment & setup

- OS: `Mac OS (M1)`
- Docke engine version: `20.10.13`
- Node base image: `node:14.17.5-alpine`
- TypeScript version: `4.3.5`

### Prisma Version

`prisma: 2.29.1 and 3.11.0`
`@prisma/client: 2.29.1 and 3.11.0`

**Comment by fcoury** [comment] 2022-03-21 01:52
I am having this same issue. Same environment too.

**Comment by fcoury** [comment] 2022-03-21 20:21
@janpio not OP but I tried it and I get this error instead:

```
 => ERROR [builder 5/6] RUN yarn run prisma generate                                                                                                   1.0s
------                                                                                                                                                      
 > [builder 5/6] RUN yarn run prisma generate:                                                                                                              
#15 0.328 yarn run v1.22.18
#15 0.348 $ /app/node_modules/.bin/prisma generate
#15 0.938 Error: Unknown binaryTarget linux-arm64-openssl-undefined and no custom binaries were provided
#15 0.974 error Command failed with exit code 1.
#15 0.975 info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
------
```

**Comment by khuezy** [comment] 2022-03-22 03:22
@fcoury what does your schema.prisma look like? I recall having the same openssl issue in my docker

Adding this fixed it:
```
generator client {
  provider      = "prisma-client-js"
  binaryTargets = ["native", "rhel-openssl-1.0.x"]
}
```

**Comment by fcoury** [comment] 2022-03-22 03:45
@khuezy thank you so much for the suggestion. I just tried it with those changes and unfortunately I still got the same error:

```
 => ERROR [builder 5/6] RUN yarn run prisma generate                                                                                                                                            0.5s
------                                                                                                                                                                                               
 > [builder 5/6] RUN yarn run prisma generate:                                                                                                                                                       
#15 0.224 yarn run v1.22.18                                                                                                                                                                          
#15 0.243 $ /app/node_modules/.bin/prisma generate
#15 0.515 Error: Unknown binaryTarget linux-arm64-openssl-undefined and no custom binaries were provided
#15 0.530 error Command failed with exit code 1.
#15 0.530 info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
------
executor failed running [/bin/sh -c yarn run prisma generate]: exit code: 1
```

For reference, here's my schema.prisma file:

```typescript
// This is your Prisma schema file,
// learn more about it in the docs: https://pris.ly/d/prisma-schema

generator client {
  provider      = "prisma-client-js"
  binaryTargets = ["native"]
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

model Report {
  id           Int    @id @default(autoincrement())
  ticker       String
  balanceSheet Bytes
  income       Bytes
  cashFlow     Bytes
}
```

**Comment by khuezy** [comment] 2022-03-22 04:56
Hmm what does your `Dockerfile` look like? If you're using `-slim`, you'll need to install the `openssl`

eg: 
```
RUN apt-get install -y openssl
```

**Comment by fcoury** [comment] 2022-03-22 05:09
Just managed to make it work using `docker-buildx`:

```
docker buildx build --platform linux/amd64 -t partnerx .  
```

Should it be possible to build using Docker Desktop without buildx on a M1 Mac?

**Comment by pantharshit00** [comment] 2022-03-22 10:15
It might be related to https://github.com/prisma/prisma/issues/8478 if you are using M1 Mac. Prisma do require openssl to be installed so your images should have it.

**Comment by pantharshit00** [comment] 2022-03-22 10:16
Can you share a minimal reproduction here with contents of your Docker image?

**Comment by valerii15298** [comment] 2022-05-10 13:58
Same issue. Also for me it is happening kinda randomly. One time it works and another - no. That is the worst kind of problems...

**Comment by nilscam** [comment] 2022-07-11 15:07
The error appeared suddenly in our CI, but our docker image and our node/yarn/prisma version did not change since the last successful build. Unfortunately, we were unable to reproduce the bug locally.

**Comment by rafaell-lycan** [comment] 2022-08-01 15:21
Hey y'all,

I had the same issue a few days ago, and I've fixed it by simply using `npx prisma generate` before `yarn build` and after `npm install` .

I hope this can help you ;)

**Comment by stefantul** [comment] 2022-08-16 14:29
Can confirm that @rafaell-lycan 's solution works! Great explanation @aloknecessary

**Comment by aloknecessary** [comment] 2022-08-16 14:38
Thanks @stefantul, Just for the records, my explanation is no different. :)

**Comment by rafaell-lycan** [comment] 2022-08-17 09:06
@stefantul yes, it works. =)

**Comment by fevernova90** [comment] 2022-09-06 14:36
Managed to speed up medium-sized project building significantly via Apple Silicon for X86 linux server without the need to use `--platform=amd64` on all build layers.

What I did is separate the `prisma generate` from other stages. My existing Dockerfile is already multi-staged, so separating prisma or any other binary generating process does makes sense, if you're not doing multi-stages build, I recommend you to do so.

Below is a simplified example Dockerfile (this project is building Nextjs+Prisma).  Pay attention to the `FROM` line, only the binary-deps and runner (the end target) have `--platform=amd64` in it. 

Only those build lines inside that 2 stages will make your Apple Silicon machine runs emulation, other will run natively, this means npx prisma generate will detect x86 machine and download those Rust-compiled binary. The usual long-running command (npm/yarn install and npm/yarn build) will run natively. Why this works is because the compiled code (except the one generating binaries externally) doesn't really depends on the architecture during build, only during runtime (that's why the end stage does have `--platform=amd64`.   

```Dockerfile
##########
## DEPS ##
##########
FROM node:16-alpine AS deps
RUN apk add --no-cache libc6-compat

WORKDIR /app

# Install dependencies based on the preferred package manager
COPY package.json yarn.lock* package-lock.json* pnpm-lock.yaml* ./
RUN \
    if [ -f yarn.lock ]; then yarn --frozen-lockfile; \
    elif [ -f package-lock.json ]; then npm ci; \
    elif [ -f pnpm-lock.yaml ]; then yarn global add pnpm && pnpm i; \
    else echo "Lockfile not found." && exit 1; \
    fi


####################
## Native Binaries Deps ##
####################
FROM --platform=amd64 node:16-alpine AS binaries-deps
RUN apk add --no-cache libc6-compat

WORKDIR /app

# Prisma client
COPY --from=deps /app/node_modules ./node_modules
COPY prisma ./prisma
RUN npx prisma generate

# Put any other binary build process here if needed


#############
## BUILDER ##
#############
FROM node:16-alpine AS builder

WORKDIR /app

COPY --from=binaries-deps /app/node_modules ./node_modules

ENV NODE_ENV=production

COPY . .

RUN yarn build

############
## RUNNER ##
############
FROM --platform=amd64 node:16-alpine AS runner

WORKDIR /app

ENV NODE_ENV=production

RUN addgroup --system --gid 1001 nodejs
RUN adduser --system --uid 1001 nextjs

COPY --from=builder /app/next.config.js ./
COPY --from=builder /app/public ./public
COPY --from=builder /app/package.json ./package.json

# Automatically leverage output traces to reduce image size
# https://nextjs.org/docs/advanced-features/output-file-tracing
COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static

USER nextjs

# Entrypoint to run before the final CMD, 
# place any additional commands that can only be run during runtime,
# such as DB migration.
COPY --chown=nextjs:nodejs deployment/docker-entrypoint.sh .

EXPOSE 3000

ENV PORT 3000

ENTRYPOINT ["docker-entrypoint.sh"]

CMD ["node", "server.js"]

```

If you're still new to Dockerfile, ignore all those lines above, just focus on the `FROM`, `RUN npx prisma migrate` and `COPY --from=binaries-deps`.

Hope this helps, sorry for the long explanation.

**Comment by rafaell-lycan** [comment] 2022-09-28 10:15
@stefantul yeah, it works.

**Comment by eli-front** [comment] 2022-11-04 05:02
> Just managed to make it work using `docker-buildx`:
> 
> ```
> docker buildx build --platform linux/amd64 -t partnerx .  
> ```
> 
> Should it be possible to build using Docker Desktop without buildx on a M1 Mac?

This results in a very long build time. Any updates?

**Comment by Promise111** [comment] 2022-11-14 07:28
> Just managed to make it work using `docker-buildx`:
> 
> ```
> docker buildx build --platform linux/amd64 -t partnerx .  
> ```
> 
> Should it be possible to build using Docker Desktop without buildx on a M1 Mac?

can you explain this please? I do not know what I am looking at.

**Comment by eli-front** [comment] 2022-11-14 16:39
I got this to work use `FROM node:16.18-slim`

**Comment by georgegebbett** [comment] 2023-01-19 13:36
I ran into this issue when using a PNPM monorepo with Turborepo in a Docker image. After a lot of bashing my head against the problem I fixed it by adding a `.npmrc` file to the root of the monorepo and then `COPY`ing that file to the Docker container. 

The `.npmrc` file contained
```
node-linker=hoisted
public-hoist-pattern[]=*prisma*
prefer-symlinked-executables=false 
```

**Comment by aqrln** [comment] 2023-03-28 18:31
As far as I can see, the comments in this issue in which it is clear what happened fall into one of two categories:

1. The client wasn't generated with `prisma generate` during the build or the generated client wasn't copied to the Docker image if generated outside the Docker container (so, not a Prisma issue), or
2. The client failed to generate on ARM64 Alpine Linux.

The second problem was fixed in Prisma 4.10.0, so I am going to go ahead and close this issue to clean up the backlog a bit. Please let me know if I missed something, or open a new issue if you still run into a similar problem so that we can take a look!

**Closed by aqrln** 2023-03-28 18:31 UTC
Labels: bug/1-unconfirmed, kind/bug, topic: prisma generate, team/client, topic: docker, topic: openssl

**Comment by abhinavvsinhaa** [comment] 2023-04-27 22:19
I removed node_modules from .dockerignore, and worked perfectly fine for me!

**Comment by phongnguyenthl** [comment] 2024-10-11 05:15
> Hmm what does your `Dockerfile` look like? If you're using `-slim`, you'll need to install the `openssl`
> 
> eg:
> 
> ```
> RUN apt-get install -y openssl
> ```

I run docker on centos and this is solution for me. 

yum install -y openssl

thank you
