### ISSUE TITLE
Include option to get count with findMany for easier pagination

### ISSUE THREAD

**Issue by afulkersonApollo** [prisma/prisma#6553] opened 2021-04-13 16:48 UTC
## Problem

It would be nice if you could pass an option to findMany that also returned the total count to be used with pagination.

## Suggested solution

```
const result = prisma.model.findMany({
  skip: 200,
  take: 20,
  count: true
})
```

**Comment by pantharshit00** [comment] 2021-04-14 12:29
Hi,

Thanks for reporting this! It has already been reported before, so I am going to close this as a duplicate of https://github.com/prisma/prisma/issues/4990

**Closed by pantharshit00** 2021-04-14 12:29 UTC
