### ISSUE TITLE
Strange error message on wrong hostname in MySQL connection string

### ISSUE THREAD

**Issue by janpio** [prisma/prisma#2739] opened 2020-06-13 10:53 UTC
On wrong hostname in MySQL connection string:

```
C:\Users\Jan\Documents\chinook\express-app>yarn prisma introspect
yarn run v1.22.0
$ prisma introspect
Environment variables loaded from ./prisma/.env

Introspecting based on datasource defined in prisma\schema.prisma …
Error: Error in connector: Error querying the database: Error querying the database: Error querying the database: No such host is known. (os error 11001)

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

v2.0.0

**Comment by pantharshit00** [comment] 2020-06-17 12:16
Exact duplicate of https://github.com/prisma/prisma/issues/2750

**Comment by pantharshit00** [comment] 2020-06-17 12:17
Although this was opened earlier other one has more context now

**Closed by pantharshit00** 2020-06-17 12:16 UTC
