### ISSUE TITLE
Unexpected field not found (FieldNotFound) error

### ISSUE THREAD

**Issue by WesCossick** [prisma/prisma#3866] opened 2020-10-06 19:48 UTC
## Bug description

A field not found error is thrown unexpectedly during a `.findMany()` call. Specifically:

```
Ep [Error]: Error occurred during query execution:
DomainError(FieldNotFound { name: "account_id", model: "Field not found in record Record { values: [Int(1525718215)], parent_id: None }. Field names are: [\"id\"], looking for: \"account_id\"" })
```

## How to reproduce

We have the following interrelated models (they've been whittled down to just the pertinent details):

```
model Account {
  id Int @id @map("account_id")

  accountAddresses AccountAddress[]
  members          Member[]

  @@map("accounts")
}

model Member {
  id        Int     @id @map("member_id")
  accountID Int     @map("account_id")
  account   Account @relation(fields: [accountID], references: [id])

  @@map("members")
}

model Address {
  id Int @id @map("address_id")

  accountAddresses AccountAddress[]

  @@map("addresses")
}

model AccountAddress {
  accountID Int     @map("account_id")
  account   Account @relation(fields: [accountID], references: [id])
  addressID Int     @map("address_id")
  address   Address @relation(fields: [addressID], references: [id])

  @@id([accountID, addressID])
  @@map("account_addresses")
}
```

And we're making the following call:

```ts
const members = await prisma.member.findMany({
    select: {
        id: true,
        account: {
            select: {
                accountAddresses: {
                    select: {
                        address: {
                            select: {
                                id: true,
                            },
                        },
                    },
                },
            },
        },
    },
});
```

## Expected behavior

No error to be thrown.

## Environment & setup

- OS: macOS
- Database: MySQL
- Node.js version: v14.13.0
- Prisma version:

```
@prisma/cli          : 2.8.0
Current platform     : darwin
Query Engine         : query-engine e6c9b4b2b7fa162d0d459d1863321f547498fcfe (at node_modules/@prisma/cli/query-engine-darwin)
Migration Engine     : migration-engine-cli e6c9b4b2b7fa162d0d459d1863321f547498fcfe (at node_modules/@prisma/cli/migration-engine-darwin)
Introspection Engine : introspection-core e6c9b4b2b7fa162d0d459d1863321f547498fcfe (at node_modules/@prisma/cli/introspection-engine-darwin)
Format Binary        : prisma-fmt e6c9b4b2b7fa162d0d459d1863321f547498fcfe (at node_modules/@prisma/cli/prisma-fmt-darwin)
Studio               : 0.294.0
```

**Comment by WesCossick** [comment] 2020-10-06 19:50
The models and `.findMany()` call are a little more complex than what's included above, but I believe that what's included above is sufficient to reproduce the error. I'm working on creating an isolated environment to confirm this.

**Comment by WesCossick** [comment] 2020-10-06 20:22
I was able to confirm this bug in an isolated environment using the trimmed-down schema and `.findMany()` call mentioned above. However, the error only occurs if there's at least one `Member` & `Account`. There doesn't need to be any `AccountAddress` or `Address` in the database.

Here's the full debug output from that isolated environment:

```
2020-10-06T20:21:43.963Z prisma-client {
  engineConfig: {
    cwd: '/app/prisma',
    enableDebugLogs: false,
    enableEngineDebugMode: undefined,
    datamodelPath: '/app/node_modules/.prisma/client/schema.prisma',
    prismaPath: undefined,
    engineEndpoint: undefined,
    generator: {
      name: 'client',
      provider: 'prisma-client-js',
      output: '/app/node_modules/@prisma/client',
      binaryTargets: [],
      previewFeatures: [],
      config: {}
    },
    showColors: false,
    logLevel: undefined,
    logQueries: undefined,
    flags: [],
    clientVersion: '2.8.0',
    enableExperimental: [],
    useUds: undefined
  }
}
2020-10-06T20:21:43.990Z prisma-client Prisma Client call:
2020-10-06T20:21:43.992Z prisma-client prisma.member.findMany({
  select: {
    id: true,
    account: {
      select: {
        accountAddresses: {
          select: {
            address: {
              select: {
                id: true
              }
            }
          }
        }
      }
    }
  }
})
2020-10-06T20:21:43.992Z prisma-client Generated request:
2020-10-06T20:21:43.992Z prisma-client query {
  findManyMember {
    id
    account {
      accountAddresses {
        address {
          id
        }
      }
    }
  }
}

2020-10-06T20:21:43.994Z engine { cwd: '/app/prisma' }
2020-10-06T20:21:44.004Z engine {
  dotPrismaPath: '/app/node_modules/.prisma/client/query-engine-debian-openssl-1.1.x'
}
2020-10-06T20:21:44.005Z plusX Execution permissions of /app/node_modules/.prisma/client/query-engine-debian-openssl-1.1.x are fine
2020-10-06T20:21:44.006Z engine { flags: [ '--enable-raw-queries' ] }
2020-10-06T20:21:44.008Z engine port: 43887
2020-10-06T20:21:44.031Z engine stdout {
  timestamp: 'Oct 06 20:21:44.029',
  level: 'INFO',
  target: 'quaint::pooled',
  fields: { message: 'Starting a mysql pool with 9 connections.' }
}
2020-10-06T20:21:44.035Z engine stdout {
  timestamp: 'Oct 06 20:21:44.035',
  level: 'INFO',
  target: 'query_engine::server',
  fields: { message: 'Started http server' }
}
2020-10-06T20:21:44.044Z engine {
  dotPrismaPath: '/app/node_modules/.prisma/client/query-engine-debian-openssl-1.1.x'
}
2020-10-06T20:21:44.045Z plusX Execution permissions of /app/node_modules/.prisma/client/query-engine-debian-openssl-1.1.x are fine
2020-10-06T20:21:44.068Z engine {
  error: Ep [Error]: Error occurred during query execution:
  DomainError(FieldNotFound { name: "account_id", model: "Field not found in record Record { values: [Int(1)], parent_id: None }. Field names are: [\"id\"], looking for: \"account_id\"" })
      at Vy.graphQLToJSError (/app/node_modules/@prisma/client/runtime/index.js:129:4523)
      at /app/node_modules/@prisma/client/runtime/index.js:129:2901
      at processTicksAndRejections (internal/process/task_queues.js:97:5)
      at async qw.request (/app/node_modules/@prisma/client/runtime/index.js:209:3203)
      at async /app/entry.js:10:19
}
2020-10-06T20:21:44.069Z prisma-client Error: Error occurred during query execution:
DomainError(FieldNotFound { name: "account_id", model: "Field not found in record Record { values: [Int(1)], parent_id: None }. Field names are: [\"id\"], looking for: \"account_id\"" })
    at Vy.graphQLToJSError (/app/node_modules/@prisma/client/runtime/index.js:129:4523)
    at /app/node_modules/@prisma/client/runtime/index.js:129:2901
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async qw.request (/app/node_modules/@prisma/client/runtime/index.js:209:3203)
    at async /app/entry.js:10:19
2020-10-06T20:21:44.069Z engine Stopping Prisma engine4
2020-10-06T20:21:44.070Z engine Waiting for start promise
2020-10-06T20:21:44.070Z engine Done waiting for start promise
2020-10-06T20:21:44.077Z engine Client Version 2.8.0
2020-10-06T20:21:44.077Z engine Engine Version query-engine e6c9b4b2b7fa162d0d459d1863321f547498fcfe
/app/node_modules/@prisma/client/runtime/index.js:210
  `+f.message}throw h=this.sanitizeMessage(h),f.code?new ge.PrismaClientKnownRequestError(h,f.code,f.meta):f.isPanic?new ge.PrismaClientRustPanicError(h):f instanceof ge.PrismaClientUnknownRequestError?new ge.PrismaClientUnknownRequestError(h):f instanceof ge.PrismaClientInitializationError?new ge.PrismaClientInitializationError(h):f instanceof ge.PrismaClientRustPanicError?new ge.PrismaClientRustPanicError(h):f}}sanitizeMessage(e){return this.prisma._errorFormat&&this.prisma._errorFormat!=="pretty"?kd.default(e):e}unpack(e,t,r,n){t.data&&(t=t.data);const i=[];return n&&i.push(n),i.push(...r.filter(s=>s!=="select"&&s!=="include")),Tr({document:e,data:t,path:i})}}function $w(e){return e===He.DMMF.ModelAction.findMany||e===He.DMMF.ModelAction.findOne||e===He.DMMF.ModelAction.findFirst?"query":"mutation"}module.exports=Cs();
                                                                                                                                                                                                          ^

Ep [Error]: Error occurred during query execution:
DomainError(FieldNotFound { name: "account_id", model: "Field not found in record Record { values: [Int(1)], parent_id: None }. Field names are: [\"id\"], looking for: \"account_id\"" })
    at qw.request (/app/node_modules/@prisma/client/runtime/index.js:210:203)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

**Comment by pantharshit00** [comment] 2020-10-07 10:06
I can confirm this bug, looks like an issue with `@map` not being respected properly.

I created a minimal reproduction inside of git repo which someone working on query engine can use to easily pick this up: https://github.com/harshit-test-org/prisma-issue-3866

**Comment by dpetrick** [comment] 2020-10-08 06:08
Thanks for reporting. A fix is available from  `2.9.0-dev.53` onward. Will be included in the `2.9.0` release.

**Closed by dpetrick** 2020-10-08 06:08 UTC
Labels: bug/2-confirmed, kind/bug, team/engines, topic: broken query, topic: prisma-client
