### ISSUE TITLE
Unknown arg `parcel` in data.parcel for type ScanUncheckedCreateInput. Did you mean `id_parcel`?

### ISSUE THREAD

**Issue by TMInnovations** [prisma/prisma#10063] opened 2021-11-02 15:49 UTC
### Bug description

Prisma wants me to input a ScanUncheckedCreateInput instead of a ScanCreateInput. However, I defined to use an ScanCreateInput in my code. I know that it's related to prisma-nestjs-graphql but the error message origins from prisma in runtime.

If I give the @id of Customer a @default() value it works. Problem may be that a customer needs to have a number to be able to store it in the db and has no (because excluded from the input with @HideField). However, then a tsc error should be there to prevent accepting a ScanCreateInput for a Prisma.ScanCreateInput (maybe a prisma-nestjs-graphql or tsc problem).

Maybe strongly related to: #8776

### How to reproduce

Min Repo here (5 min.): https://github.com/TMInnovations/prisma-wrong-input-args

### Expected behavior

Prisma should tell me what the real problem is (that it has no customer.number but needs one).

### Prisma information

https://github.com/TMInnovations/prisma-wrong-input-args

### Environment & setup

=> package.json of https://github.com/TMInnovations/prisma-wrong-input-args

### Prisma Version

```
prisma                  : 3.2.1
@prisma/client          : 3.2.1
```

**Comment by janpio** [comment] 2023-09-06 15:13
Next step: Reconfirm bug again with most recent Prisma version, compare error message according to https://github.com/prisma/team-orm/issues/222.

**Comment by millsp** [comment] 2023-11-07 19:30
I can confirm that the error went from
```sh
Invalid `this.prisma.scan.create()` invocation in      
C:\Users\tm\TmiCloud\2_TMI\Projects\2021\01_DEAD_LAS2\03_Failing\prisma-\src\models\scan\scan.service.ts:17:29
  14 // CRUD
  15
  16 create(createScanInput: ScanCreateInput) {        
→ 17   return this.prisma.scan.create({
         data: {
           data: '2328570201',
           parcel: {
           ~~~~~~
             create: {
               customer: {
                 create: {}
               }
             }
           }
         }
       })

Unknown arg `parcel` in data.parcel for type ScanUncheckedCreateInput. Did you mean `id_parcel`? Available args:
type ScanUncheckedCreateInput {
  id?: String
  data: String
  id_parcel?: String | Null
}


    at Document.validate (C:\Users\tm\TmiCloud\2_TMI\Projects\2021\01_DEAD_LAS2\03_Failing\prisma-\node_modules\@prisma\client\runtime\index.js:37399:19)
    at PrismaService._executeRequest (C:\Users\tm\TmiCloud\2_TMI\Projects\2021\01_DEAD_LAS2\03_Failing\prisma-\node_modules\@prisma\client\runtime\index.js:39786:17)    at consumer (C:\Users\tm\TmiCloud\2_TMI\Projects\2021\01_DEAD_LAS2\03_Failing\prisma-\node_modules\@prisma\client\runtime\index.js:39731:23)
    at C:\Users\tm\TmiCloud\2_TMI\Projects\2021\01_DEAD_LAS2\03_Failing\prisma-\node_modules\@prisma\client\runtime\index.js:39733:47
    at AsyncResource.runInAsyncScope (async_hooks.js:197:9)
    at PrismaService._request (C:\Users\tm\TmiCloud\2_TMI\Projects\2021\01_DEAD_LAS2\03_Failing\prisma-\node_modules\@prisma\client\runtime\index.js:39733:25)       
    at request (C:\Users\tm\TmiCloud\2_TMI\Projects\2021\01_DEAD_LAS2\03_Failing\prisma-\node_modules\@prisma\client\runtime\index.js:39836:77)
    at _callback (C:\Users\tm\TmiCloud\2_TMI\Projects\2021\01_DEAD_LAS2\03_Failing\prisma-\node_modules\@prisma\client\runtime\index.js:40041:14)
    at PrismaPromise.then (C:\Users\tm\TmiCloud\2_TMI\Projects\2021\01_DEAD_LAS2\03_Failing\prisma-\node_modules\@prisma\client\runtime\index.js:40048:23)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
```

to a clearer error message pointing the issue
```ts
prisma:error 
Invalid `this.prisma.scan.create()` invocation in
/home/millsp/Throwaway/prisma-wrong-input-args/src/models/scan/scan.service.ts:17:29

  14 // CRUD
  15 
  16 create(createScanInput: ScanCreateInput) {
→ 17   return this.prisma.scan.create({
         data: {
           data: "2328570201",
           parcel: {
             create: {
               customer: {
                 create: {
       +           number: String
                 }
               }
             }
           }
         }
       })

Argument `number` is missing.
[Nest] 816095  - 11/07/2023, 9:19:48 AM   ERROR [ExceptionsHandler] 
Invalid `this.prisma.scan.create()` invocation in
/home/millsp/Throwaway/prisma-wrong-input-args/src/models/scan/scan.service.ts:17:29

  14 // CRUD
  15 
  16 create(createScanInput: ScanCreateInput) {
→ 17   return this.prisma.scan.create({
         data: {
           data: "2328570201",
           parcel: {
             create: {
               customer: {
                 create: {
       +           number: String
                 }
               }
             }
           }
         }
       })

Argument `number` is missing.
PrismaClientValidationError: 
Invalid `this.prisma.scan.create()` invocation in
/home/millsp/Throwaway/prisma-wrong-input-args/src/models/scan/scan.service.ts:17:29

  14 // CRUD
  15 
  16 create(createScanInput: ScanCreateInput) {
→ 17   return this.prisma.scan.create({
         data: {
           data: "2328570201",
           parcel: {
             create: {
               customer: {
                 create: {
       +           number: String
                 }
               }
             }
           }
         }
       })

Argument `number` is missing.
    at En (/home/millsp/Throwaway/prisma-wrong-input-args/node_modules/.pnpm/@prisma+client@5.5.2_prisma@5.5.2/node_modules/@prisma/client/runtime/library.js:116:5888)
    at Cn.handleRequestError (/home/millsp/Throwaway/prisma-wrong-input-args/node_modules/.pnpm/@prisma+client@5.5.2_prisma@5.5.2/node_modules/@prisma/client/runtime/library.js:123:6516)
    at Cn.handleAndLogRequestError (/home/millsp/Throwaway/prisma-wrong-input-args/node_modules/.pnpm/@prisma+client@5.5.2_prisma@5.5.2/node_modules/@prisma/client/runtime/library.js:123:6206)
    at Cn.request (/home/millsp/Throwaway/prisma-wrong-input-args/node_modules/.pnpm/@prisma+client@5.5.2_prisma@5.5.2/node_modules/@prisma/client/runtime/library.js:123:5926)
    at l (/home/millsp/Throwaway/prisma-wrong-input-args/node_modules/.pnpm/@prisma+client@5.5.2_prisma@5.5.2/node_modules/@prisma/client/runtime/library.js:128:9968)
    at target (/home/millsp/Throwaway/prisma-wrong-input-args/node_modules/.pnpm/@nestjs+core@8.4.7_@nestjs+common@8.4.7_@nestjs+platform-express@8.4.7_reflect-metadata@0.1.13_rxjs@7.8.1/node_modules/@nestjs/core/helpers/external-context-creator.js:77:28)
    at /home/millsp/Throwaway/prisma-wrong-input-args/node_modules/.pnpm/@nestjs+core@8.4.7_@nestjs+common@8.4.7_@nestjs+platform-express@8.4.7_reflect-metadata@0.1.13_rxjs@7.8.1/node_modules/@nestjs/core/helpers/external-proxy.js:9:24
```

You mentioned that the types could check this. Yes they could, however this would be an expensive operation and it is rather checked at runtime instead.

In order to reproduce, I upgrades your repro to the latest Prisma packages as well as your custom generator for Nest.js. A few things have changed since then, so I have skipped and tweaked a bit in order to get that runtime error again. Eventually, I could paste your gql query and got the better error. I am thus closing this issue. Thanks!

**Closed** 2023-11-07 19:30 UTC
Labels: bug/2-confirmed, kind/bug, topic: error, topic: client types, topic: uncheckedScalarInputs, team/client
