### ISSUE TITLE
Allow aliases for @@unique and composite @@id fields

### ISSUE THREAD

**Issue by wadetandy** [prisma/prisma#3748] opened 2020-09-23 21:23 UTC
## Problem
When defining a unique index or composite primary key, prisma introspects the name from the database. You can provide your own name instead, but upon reintrospecting the name will be overwritten. 

## Suggested solution
It would be nice to be able to map the name from the database to the prisma schema and resulting types, as this would allow us to name things to better match the domain and intent, especially when applying prisma to legacy databases.

``` prisma
model Thing {
  id Int
  userId Int
  customerId Int

  // Allow a new "map" key to reference the underlying db name, but can use name field for the javascript name
  @@unique([userId, customerId], name: "userAndCustomer", map: "user_customer_unique")

  // Allow a custom name for a composite id filter
  @@id([id, customerId], name: "idAndCustomer")
}
```

``` typescript
prisma.thing.findOne({
  where: {
    // friendlier to our domain AND our eslint rules for camel casing
    userAndCustomer: {
      userId,
      customerId,
   }
 }
})
```

## Alternatives
Using the names as defined in the database.

**Comment by pantharshit00** [comment] 2020-09-23 22:30
Hi,

Thanks for reporting this! It has already been reported before, so I am going to close this as a duplicate of https://github.com/prisma/prisma/issues/3193

**Closed by pantharshit00** 2020-09-23 22:30 UTC
