### ISSUE TITLE
[introspection-engine/connectors/sql-introspection-connector/src/commenting_out_guardrails.rs:50:35] called `Option::unwrap()` on a `None` value

### ISSUE THREAD

**Issue by braco** [prisma/prisma#2089] opened 2020-04-04 03:39 UTC
prisma introspect fails on existing mysql database.

## How to reproduce

```
$ DEBUG="*" prisma introspect

  prisma .env loaded from current directory +0ms
  getos { platform: 'darwin', libssl: undefined } +0ms
Introspecting based on datasource defined in schema.prisma …
  getos { platform: 'darwin', libssl: undefined } +5ms
  IntrospectionEngine:rpc starting introspection engine with binary: /Users/me/.nvm/versions/node/v13.6.0/lib/node_modules/@prisma/cli/introspection-engine-darwin +0ms
  download {
  download   cachedFile: '/Users/me/.cache/prisma/master/2accb9c7eacdc984874eaeb63377fe705dfd3203/darwin/query-engine'
  download } +0ms
  download {
  download   cachedFile: '/Users/me/.cache/prisma/master/2accb9c7eacdc984874eaeb63377fe705dfd3203/darwin/introspection-engine'
  download } +1ms
  download {
  download   cachedFile: '/Users/me/.cache/prisma/master/2accb9c7eacdc984874eaeb63377fe705dfd3203/darwin/migration-engine'
  download } +0ms
  IntrospectionEngine:rpc SENDING RPC CALL {"id":1,"jsonrpc":"2.0","method":"introspect","params":[{"schema":"// This is your Prisma schema file,\n// learn more about it in the docs: https://pris.ly/d/prisma-schema\n\ndatasource db {\n  provider = \"mysql\"\n  url      = env(\"DATABASE_URL\")\n}\n\ngenerator client {\n  provider = \"prisma-client-js\"\n}\n"}]} +9ms
  download { cachedFileSize: 16570608, targetFileSize: 16570608 } +2ms
  download { cachedFileSize: 11202264, targetFileSize: 11202264 } +6ms
  download { cachedFileSize: 14816616, targetFileSize: 14816616 } +3ms
  download Getting version of /Users/me/.nvm/versions/node/v13.6.0/lib/node_modules/@prisma/cli/query-engine-darwin. Result:  {
  command: '/Users/me/.nvm/versions/node/v13.6.0/lib/node_modules/@prisma/cli/query-engine-darwin --version',
  exitCode: 0,
  stdout: 'prisma 2accb9c7eacdc984874eaeb63377fe705dfd3203',
  stderr: '',
  all: undefined,
  failed: false,
  timedOut: false,
  isCanceled: false,
  killed: false
} +10ms
  download Getting version of /Users/me/.nvm/versions/node/v13.6.0/lib/node_modules/@prisma/cli/query-engine-darwin. Result:  prisma 2accb9c7eacdc984874eaeb63377fe705dfd3203 +1ms
  download { works: true } +0ms
  download { needsToBeDownloaded: false } +0ms
  download Getting version of /Users/me/.nvm/versions/node/v13.6.0/lib/node_modules/@prisma/cli/introspection-engine-darwin. Result:  {
  command: '/Users/me/.nvm/versions/node/v13.6.0/lib/node_modules/@prisma/cli/introspection-engine-darwin --version',
  exitCode: 0,
  stdout: 'introspection-core 2accb9c7eacdc984874eaeb63377fe705dfd3203',
  stderr: '',
  all: undefined,
  failed: false,
  timedOut: false,
  isCanceled: false,
  killed: false
} +2ms
  download Getting version of /Users/me/.nvm/versions/node/v13.6.0/lib/node_modules/@prisma/cli/introspection-engine-darwin. Result:  introspection-core 2accb9c7eacdc984874eaeb63377fe705dfd3203 +0ms
  download { works: true } +0ms
  download { needsToBeDownloaded: false } +1ms
  download Getting version of /Users/me/.nvm/versions/node/v13.6.0/lib/node_modules/@prisma/cli/migration-engine-darwin. Result:  {
  command: '/Users/me/.nvm/versions/node/v13.6.0/lib/node_modules/@prisma/cli/migration-engine-darwin --version',
  exitCode: 0,
  stdout: 'migration-engine-cli 2accb9c7eacdc984874eaeb63377fe705dfd3203',
  stderr: '',
  all: undefined,
  failed: false,
  timedOut: false,
  isCanceled: false,
  killed: false
} +3ms
  download Getting version of /Users/me/.nvm/versions/node/v13.6.0/lib/node_modules/@prisma/cli/migration-engine-darwin. Result:  migration-engine-cli 2accb9c7eacdc984874eaeb63377fe705dfd3203 +0ms
  download { works: true } +0ms
  download { needsToBeDownloaded: false } +1ms
  IntrospectionEngine:stderr {"is_panic":true,"message":"[introspection-engine/connectors/sql-introspection-connector/src/commenting_out_guardrails.rs:50:35] called `Option::unwrap()` on a `None` value","backtrace":"   0: backtrace::backtrace::trace\n   1: backtrace::capture::Backtrace::new\n   2: user_facing_errors::Error::new_in_panic_hook\n   3: user_facing_errors::panic_hook::set_panic_hook::{{closure}}\n   4: std::panicking::rust_panic_with_hook\n   5: rust_begin_unwind\n   6: core::panicking::panic_fmt\n   7: core::panicking::panic\n   8: sql_introspection_connector::commenting_out_guardrails::commenting_out_guardrails\n   9: sql_introspection_connector::calculate_datamodel::calculate_model\n  10: <std::future::GenFuture<T> as core::future::future::Future>::poll\n  11: <std::future::GenFuture<T> as core::future::future::Future>::poll\n  12: <futures_util::compat::compat03as01::Compat<Fut> as futures::future::Future>::poll\n  13: <futures::future::map::Map<A,F> as futures::future::Future>::poll\n  14: <futures::future::map_err::MapErr<A,F> as futures::future::Future>::poll\n  15: <futures::future::either::Either<A,B> as futures::future::Future>::poll\n  16: <futures::future::lazy::Lazy<F,R> as futures::future::Future>::poll\n  17: futures::future::chain::Chain<A,B,C>::poll\n  18: <futures::future::then::Then<A,B,F> as futures::future::Future>::poll\n  19: <futures::future::map::Map<A,F> as futures::future::Future>::poll\n  20: <futures::future::either::Either<A,B> as futures::future::Future>::poll\n  21: <futures::future::map::Map<A,F> as futures::future::Future>::poll\n  22: futures::task_impl::std::set\n  23: <std::future::GenFuture<T> as core::future::future::Future>::poll\n  24: tokio::runtime::enter::Enter::block_on\n  25: tokio::runtime::context::enter\n  26: tokio::runtime::handle::Handle::enter\n  27: introspection_engine::main\n  28: std::rt::lang_start::{{closure}}\n  29: std::panicking::try::do_call\n  30: __rust_maybe_catch_panic\n  31: std::rt::lang_start_internal\n  32: main\n"} +0ms
 ERROR  Oops, an unexpected error occured!
[introspection-engine/connectors/sql-introspection-connector/src/commenting_out_guardrails.rs:50:35] called `Option::unwrap()` on a `None` value
```

## Environment & setup

Mac OS

mysql  Ver 8.0.19 for osx10.15 on x86_64 (Homebrew)

@prisma/cli          : 2.0.0-alpha.1031
Current platform     : darwin
Query Engine         : prisma 15b42f2c499c65576f47fa77108e39d86645242b (at /Users/me/.nvm/versions/node/v13.6.0/lib/node_modules/@prisma/cli/query-engine-darwin)
Migration Engine     : migration-engine-cli 15b42f2c499c65576f47fa77108e39d86645242b (at /Users/me/.nvm/versions/node/v13.6.0/lib/node_modules/@prisma/cli/migration-engine-darwin)
Introspection Engine : introspection-core 15b42f2c499c65576f47fa77108e39d86645242b (at /Users/me/.nvm/versions/node/v13.6.0/lib/node_modules/@prisma/cli/introspection-engine-darwin)

node v13.6.0

**Comment by janpio** [comment] 2020-04-04 14:28
Did the CLI give you the option to submit this crash to our error reporting backend?
If not, can you maybe share your database schema here or via schemas@prisma.io? We would really like to reproduce this.

**Comment by braco** [comment] 2020-04-04 14:33
It did prompt and I did send it in. Let me know if there's anything else I can do. Does the above suggest that it connected to the database successfully?

**Comment by janpio** [comment] 2020-04-04 14:34
Do you happen to have the report ID it output? I will try to find it, but having the ID would make that easier ;)

**Comment by braco** [comment] 2020-05-11 00:54
Sorry I missed this @janpio, where can I send the schema?

**Comment by janpio** [comment] 2020-05-11 14:05
All information here: https://github.com/prisma/prisma/issues/757 Thanks!

**Comment by pantharshit00** [comment] 2020-05-14 12:34
Hey @braco

Can you please share a SQL dump? You have send a table description which not very helpful as we can't import it.


You can get a sql dump using the `mysqldump` tool. Instructions here: https://stackoverflow.com/questions/13484667/downloading-mysql-dump-from-command-line

**Comment by braco** [comment] 2020-06-01 23:17
Just following up with this, I migrated the database to Postgres and am still having the same problem.

**Comment by pantharshit00** [comment] 2020-06-03 16:32
Hey @braco 

I was looking at the email and looks like you have removed the pastebin. Can you please send that again :pray:

**Comment by do4gr** [comment] 2020-07-21 20:14
Does this still occur with the latest release @braco ?

**Comment by matthewmueller** [comment] 2020-08-24 10:23
Closing. We're happy to re-open if this problem is still affecting you @braco.

**Closed by matthewmueller** 2020-08-24 10:23 UTC
Labels: bug/0-needs-info, kind/bug, topic: introspection
