### ISSUE TITLE
called `Option::unwrap()` on a `None` value

### ISSUE THREAD

**Issue by GoodBoyNeon** [prisma/prisma#20312] opened 2023-07-20 15:10 UTC
Hi Prisma Team! My Prisma Client just crashed. This is the report:
## Versions

| Name            | Version            |
|-----------------|--------------------|
| Node            | v20.4.0            | 
| OS              | debian-openssl-3.0.x|
| Prisma Client   | in-memory          |
| Query Engine    | 6b0aef69b7cdfc787f822ecd7cdc76d5f1991584|
| Database        | mongodb            |

## Logs
```
prisma:client:libraryEngine sending request, this.libraryStarted: false
prisma:client:libraryEngine library starting
prisma:client:libraryEngine sending request, this.libraryStarted: false
prisma:client:libraryEngine library already starting, this.libraryStarted: false
prisma:client:libraryEngine library started
```

## Client Snippet
```ts
// PLEASE FILL YOUR CODE SNIPPET HERE
```

## Schema
```prisma
// PLEASE ADD YOUR SCHEMA HERE IF POSSIBLE
```

## Prisma Engine Query
```
{"X":true}}}
```

**Comment by GoodBoyNeon** [comment] 2023-07-20 15:12
My schema:
```prisma
model PromotionBlacklist {
  id        String      @id @default(auto()) @map("_id") @db.ObjectId
  userId    String      @unique
  indexData IndexData[]
}

model IndexData {
  id                 String             @id @default(auto()) @map("_id") @db.ObjectId
  channelId          String
  index              Int
  PromotionBlacklist PromotionBlacklist @relation(fields: [userId], references: [userId])
  userId             String

  @@unique([userId, channelId])
}
```

**Comment by GoodBoyNeon** [comment] 2023-07-21 11:03
I got that in Prisma Studio while viewing a model. So I'd say it should be `findMany()` that caused the error. Also, what does it mean to give a partial dataset? And how do I do that?

**Comment by millsp** [comment] 2023-07-21 14:08
I suppose that this error was originated because of a certain type of data in one of your database rows, which does not match the provided schema. Usually these are hard to reproduce so we would appreciate if you could help us reproducing it. Do you get this error consistently?

**Comment by GoodBoyNeon** [comment] 2023-07-21 14:51
Yes, I do get this consistently. And I'd love to help you reproduce, can you guide me through?

**Comment by millsp** [comment] 2023-07-21 15:00
Sure! The first thing I would do is to isolate which model produces this error. Ideally, we would get down to a simple `prisma.<model>.findMany()` query in a new ts/js file, that should be quick enough to try. I'd write one for each model and execute all of them to find out. If that isolates a specific table, then we need to look at the data of that table and then go deeper.

**Comment by janpio** [comment] 2023-08-06 12:36
Hey @GoodBoyNeon, did you see Pierre's response above? We would like to help you out here, but need your help in reproducing this so we can understand, reproduce and hopefully fix. Thanks.

**Comment by GoodBoyNeon** [comment] 2023-08-08 05:11
I am not able to reproduce the issue, it suddenly got fixed. I will inform if there are any updates

**Comment by SevInf** [comment] 2023-08-18 12:58
Thank @GoodBoyNeon, in that case, I am going to close the issue.  Thank you for getting back to use!

**Closed by SevInf** 2023-08-18 12:58 UTC
Labels: bug/0-unknown, kind/bug, topic: studio, tech/engines, topic: broken query, team/client, topic: mongodb, topic: unwrap error
