### ISSUE TITLE
When performing an update, Prisma is generating an extra select to find the row by primary key.

### ISSUE THREAD

**Issue by blevine** [prisma/prisma#9201] opened 2021-09-10 16:23 UTC
I am issuing the following update:

`prismaClient.ab_training_env.update({data: data, where: {job_id: job.id}});
`

I can see via logging that this generates the following:

> BEGIN
> SELECT "public"."ab_training_env"."id" FROM "public"."ab_training_env" WHERE "public"."ab_training_env"."job_id" = $1
> UPDATE "public"."ab_training_env" SET "status" = $1 WHERE "public"."ab_training_env"."id" IN ($2)
> 

Why isn't it generating a single `UPDATE WHERE job_id = $1` ?

This is the associated model:

```
model ab_training_env {
  id             String       @id @default(dbgenerated("gen_random_uuid()")) @db.Uuid
  created_at     DateTime?    @db.Timestamptz(6)
  updated_at     DateTime?    @db.Timestamptz(6)
  course_name    String       @db.VarChar(255)
  user_id        String       @db.VarChar(36)
  job_id         String?      @unique(map: "ab_training_env_job_id_unique") @db.VarChar(255)
  product_id     String?      @db.VarChar(255)
  status         status_type? @default(NOT_REQUESTED)
  status_message String?
  started_at     DateTime?    @db.Timestamptz(6)
  completed_at   DateTime?    @db.Timestamptz(6)
  user_entity    user_entity  @relation(fields: [user_id], references: [id], onDelete: NoAction, onUpdate: NoAction, map: "ab_training_env_user_id_foreign")

  @@unique([user_id, course_name], map: "ab_training_env_user_id_course_name_unique")
}

```

**Comment by xiaoyu-tamu** [comment] 2021-09-11 01:36
seems like this is not their priority

#5686 #8069

**Comment by blevine** [comment] 2021-09-12 13:11
@xiaoyu-tamu Those issues are related I suppose, but not the same problem  I've described here.

**Comment by pantharshit00** [comment] 2021-09-13 07:55
@blevine Yes, but this will get tackled alongside with them when we will do connector specific optimisation. Right now we are focusing on feature parity.

**Comment by blevine** [comment] 2021-09-13 11:48
So then this is still a bug and this issue should remain open unless it's a duplicate of another issue. Planning to address an issue is not a reason to close it. Furthermore, the fact that you're doing the extra select when you could just be doing the update just seems wrong.  What DB connector can't do the update directly and requires the extra select?

**Comment by pantharshit00** [comment] 2021-09-13 12:32
We can keep this open. The extra select is from the time when we don't used to support referential actions in the schema and we would manually make sure the record exists before updating. I would group this other similar optimisation tasks that we have on our plate but yeah sorry for my misleading initial comment. 

I will keep this open.

**Comment by hiramhuang** [comment] 2022-11-16 13:43
It seems those extra queries only occurred on relation models with `onUpdate` set to `NoAction`.

**Comment by janpio** [comment] 2022-11-16 19:13
If you are using `relationMode=prisma` then additional queries are expected (as we have to emulate database functionality in Prisma). If that is not the case, please open a new issue to describe what is happening to you @hiramhuang.

**Comment by laplab** [comment] 2024-01-30 13:03
Thanks to the work done in [Prisma 5.1.0 release](https://github.com/prisma/prisma/releases/tag/5.1.0), this issue no longer reproduces. This is because we use `RETURNING` statement, which enables us to skip the initial `SELECT` query.

Users might experience similar issues with nested updates as well as on MySQL and MSSQL. However, this is out of scope for this issue and will be addressed separately in https://github.com/prisma/prisma/issues/2157.

**Closed by laplab** 2024-01-30 13:03 UTC
Labels: kind/improvement, topic: performance, team/client, topic: performance/queries, topic: update()
