### ISSUE TITLE
(@prisma/client): Generate mapping of Models to allow mapped types

### ISSUE THREAD

**Issue by daniellwdb** [prisma/prisma#6820] opened 2021-04-27 12:39 UTC
## Problem

Because Prisma does not provide a solution for caching yet, I made use of middlewares like [this one](https://gist.github.com/daniellwdb/0c2dba8b5807393ac9bf1f48429c1f06). I added the option to provide default values and only cache a specific set of selected properties, however I cannot provide autocompletion for these keys because `Prisma.ModelName` is a union type of strings
```typescript
type CacheMiddlewareOptions = {
  model: Prisma.ModelName
  action: Prisma.PrismaAction
  keys?: string[]
  defaultValues?: Record<string, unknown>
  ttlInSeconds: number
}
```

## Suggested solution

It would be nice if each model would be mapped to their select options so we can do:
```typescript
export type ModelMap = {
  SomeModel: {
    select: // select type here
  }
}

export type ModelName = keyof ModelMap

type CacheMiddlewareOptions<T extends Prisma.ModelName> = {
  keys: Array<keyof Prisma.ModelMap[T]["select"]>
}
```

**Comment by pantharshit00** [comment] 2021-04-29 11:30
Closing as a duplicate of https://github.com/prisma/prisma/issues/5058. 

I added link to your comment there.

**Closed by pantharshit00** 2021-04-29 11:30 UTC
