### ISSUE TITLE
Attempting to use _count aggregate

### ISSUE THREAD

**Issue by Sam-Dvorack** [prisma/prisma#7281] opened 2021-05-26 13:15 UTC
Hi Prisma Team! My Prisma Client just crashed. This is the report:
## Versions

| Name            | Version            |
|-----------------|--------------------|
| Node            | v14.16.1           | 
| OS              | windows            |
| Prisma Client   | 2.23.0             |
| Query Engine    | query-engine adf5e8cba3daf12d456d911d72b6e9418681b28b|
| Database        | undefined|

## Query
```
query {
  findManyFstCheckpoint {
    FstCheckpointId
    Name
    FstCheckpointItems {
      FstCheckpointItem {
        FstCheckpointItemId
        FstChecklistTypeId
        IsActive
        Name
        Description
        _count {
          FstCheckpointItemQuestion
        }
      }
    }
  }
}
```

## Logs
```
mEnvironment variables loaded from D:\FST - Primsa\fst-node\.env  
  prisma:tryLoadEnv Environment variables loaded from D:\FST - Primsa\fst-node\.env  
  prisma:client clientVersion: 2.23.0  
  prisma:engine Search for Query Engine in D:\FST - Primsa\fst-node\node_modules\.prisma\client  
  prisma:engine { cwd: 'D:\\FST - Primsa\\fst-node\\src\\prisma' }  +3s
  prisma:engine Search for Query Engine in D:\FST - Primsa\fst-node\node_modules\.prisma\client  
  prisma:engine { flags: [ '--enable-raw-queries', '--port', '64823' ] }  
  prisma:engine stdout  Starting a mssql pool with 13 connections.  
  prisma:engine stdout  TLS encryption is not enabled. All traffic including the login credentials are not encrypted.  
  prisma:engine stdout  Database change from 'TonTracInternal' to 'master'  
  prisma:engine stdout  Changed database context to 'TonTracInternal'.  
  prisma:engine stdout  SQL collation change from None to None  
  prisma:engine stdout  Microsoft SQL Server version 3892510734  
  prisma:engine stdout  Packet size change from '4096' to '4096'  
  prisma:engine stdout  Started http server on http://127.0.0.1:64823  
  prisma:engine Search for Query Engine in D:\FST - Primsa\fst-node\node_modules\.prisma\client  
  prisma:engine stdout  PANIC in query-engine\core\src\query_graph_builder\read\utils.rs:52:85
called `Result::unwrap()` on an `Err` value: FieldNotFound { name: "_count", model: "FstCheckpointItem" }  
  prisma:engine {
  prisma:engine   error: Error: read ECONNRE

**Comment by pantharshit00** [comment] 2021-05-26 13:16
Hi,

Thanks for reporting this! It has already been reported before, so I am going to close this as a duplicate of https://github.com/prisma/prisma/issues/6543

**Closed by pantharshit00** 2021-05-26 13:16 UTC
