### ISSUE TITLE
Throw a handleable native Javascript error when RecordNotFound is thrown by query engine

### ISSUE THREAD

**Issue by JacobMuchow** [prisma/prisma#8198] opened 2021-07-09 20:52 UTC
## Problem

For CRUD actions in Prisma client, such as `.update()` or `.delete()`, if the record does not exist an error is thrown by the query engine, but it is not easily handleable. ex)

```
Error for binding '0': RecordNotFound("Record to delete does not exist.")
```

One must check `error.detail` or `error.code` to determine if this was a simple record not found issue or something else.

## Suggested solution

 It would be helpful for Prisma client to catch this scenario and throw a native JS error to is more easily handleable, like `RecordNotFoundError extends Error`.

## Alternatives

Return null instead of throwing

## Additional context

Related issues:
* https://github.com/prisma/prisma/discussions/4552
* https://github.com/prisma/prisma/issues/4072

**Comment by JacobMuchow** [comment] 2021-07-09 21:00
Something that came to mind for me earlier is for update/delete, if the record does not exist an error is thrown. But for get, the default behavior is to return null instead of throwing an error. You must enable `rejectOnNotFound()` when instantiating the prisma client to change the behavior for get().

Perhaps update/delete should follow / be added to this setting group to stay consistent.

**Comment by pantharshit00** [comment] 2021-07-11 21:39
Closing as duplicate of #5040 and this specific one is also opened as #4072 as you have mentioned. 

`rejectOnNotFound` doesn't make sense for `update/delete` because we will always throw an error here when record is not found as opposed to null. 

The problem here is really bad error we throw and we plan to rework errors.

**Closed by pantharshit00** 2021-07-11 21:39 UTC
