### ISSUE TITLE
`TypeError: Cannot destructure property 'clientVersion' of 'undefined'` for invalid queries when using `tslog` logging library

### ISSUE THREAD

**Issue by justinsmid** [prisma/prisma#20307] opened 2023-07-20 12:12 UTC
### Bug description

We have started getting the following ominous error when executing invalid queries:

```
TypeError: Cannot destructure property 'clientVersion' of 'undefined' as it is undefined.
     at new PrismaClientValidationError (/[REDACTED]/node_modules/@prisma/client-mysql/runtime/library.js:26:2545)
     at Logger._cloneError (/[REDACTED]/node_modules/.pnpm/tslog@4.8.2/node_modules/tslog/dist/cjs/BaseLogger.js:238:26)
     at Logger._recursiveCloneAndMaskValuesOfKeys (/[REDACTED]/node_modules/.pnpm/tslog@4.8.2/node_modules/tslog/dist/cjs/BaseLogger.js:183:41)
     at /[REDACTED]/node_modules/.pnpm/tslog@4.8.2/node_modules/tslog/dist/cjs/BaseLogger.js:157:25
     at Array.map (<anonymous>)
     at Logger._mask (/{REDACTED]/node_modules/.pnpm/tslog@4.8.2/node_modules/tslog/dist/cjs/BaseLogger.js:156:22)
     at Logger.log (/{REDACTED]/node_modules/.pnpm/tslog@4.8.2/node_modules/tslog/dist/cjs/BaseLogger.js:99:24)
     at Logger.error (/{REDACTED]/node_modules/.pnpm/tslog@4.8.2/node_modules/tslog/dist/cjs/index.js:29:22)
     at /{REDACTED]/node_modules/.pnpm/@blitzjs+rpc@2.0.0-beta.30_@tanstack+query-core@4.24.4_blitz@2.0.0-beta.30_next@13.4.9_react-dom@18.2.0_react@18.2.0/node_modules/@blitzjs/rpc/dist/index-server.cjs:326:15
     at Generator.throw (<anonymous>)
     at rejected (/{REDACTED]/node_modules/.pnpm/@blitzjs+rpc@2.0.0-beta.30_@tanstack+query-core@4.24.4_blitz@2.0.0-beta.30_next@13.4.9_react-dom@18.2.0_react@18.2.0/node_modules/@blitzjs/rpc/dist/index-server.cjs:127:29)     
```

It seems to be related to v5. Before we upgraded from `4.15.0` to `5.0.0`, this did not happen, and we would instead get the expected error:

```
 Unknown field `idd` for select statement on model `SomeModel`. Available options are listed in green.
```

[Looking at the code](https://github.com/prisma/prisma/blob/da282557b794908667886c460f6866d724197ed9/packages/client/src/runtime/core/errors/PrismaClientValidationError.ts#L6-L19), it appears that the constructor of `PrismaClientValidationError` sometimes gets passed `undefined` as its options, while the code assumes this doesn't happen and destructures the options.
As a temporary workaround, I found I am able to go into the `library.js` file mentioned in the stacktrace in my node_modules and add `= {}` after the destructuring to make it no longer crash, at which point it once again shows the expected errors.

I was unable to reproduce the issue in a simplified standalone repository, and I am not able to share the acutal repository where I am facing my issue. I tried to reproduce it by creating a new minimal prisma application and copy-pasting our exact prisma.schema and the query that is causing the error, but in that repository I **do** get the expected error.
We have a rather large (>6000 lines) prisma.schema, and a rather complex repository setup (pnpm monorepo with multiple packages).

I have provided some snippets of our schema and queries that are throwing this error (see `Prisma information` section), but it doesn't seem to be related to a specific entity or query, as I am able to reproduce it in our actual repo in **any** query by simply changing a property like `select` or `create` to be incorrect (such as changing `id: true` in a `select` to `idd: true`).

Here is the full output, with `DEBUG="*"` and `info` logging:

```
2023-07-20T12:01:42.755Z prisma:client  Prisma Client call:
2023-07-20T12:01:42.755Z prisma:client  prisma.modulePackage.findMany({
  where: {
    AND: {
      status: {
        code: {
          in: [
            "active",
            "inactive"
          ]
        }
      },
      companyProductId: 74
    },
    OR: [
      {
        translations: {
          some: {
            name: {
              contains: ""
            }
          }
        }
      }
    ]
  },
  select: {
    idd: true
  }
})
2023-07-20T12:01:42.755Z prisma:client  Generated request:
2023-07-20T12:01:42.755Z prisma:client  {
  "modelName": "ModulePackage",
  "action": "findMany",
  "query": {
    "arguments": {
      "where": {
        "AND": {
          "status": {
            "code": {
              "in": [
                "active",
                "inactive"
              ]
            }
          },
          "companyProductId": 74
        },
        "OR": [
          {
            "translations": {
              "some": {
                "name": {
                  "contains": ""
                }
              }
            }
          }
        ]
      }
    },
    "selection": {
      "idd": true
    }
  }
}

2023-07-20T12:01:42.755Z prisma:client:libraryEngine  sending request, this.libraryStarted: true
2023-07-20T12:01:42.757Z prisma:client:request_handler  PrismaClientKnownRequestError: Field 'idd' not found in enclosing type 'ModulePackage'
    at ko (/{REDACTED]/node_modules/@prisma/client-mysql/runtime/library.js:26:6409)
    at _t.buildQueryError (/{REDACTED]/node_modules/@prisma/client-mysql/runtime/library.js:104:902)
    at _t.request (/{REDACTED]/node_modules/@prisma/client-mysql/runtime/library.js:103:4117)
    at async Object.singleLoader (/{REDACTED]/node_modules/@prisma/client-mysql/runtime/library.js:122:6714)
    at async zr.request (/{REDACTED]/node_modules/@prisma/client-mysql/runtime/library.js:122:7206)
    at async eval (webpack-internal:///(api)/./src/modules/packages/admin/overview/queries/table.ts:78:18) {
  code: 'P2009',
  clientVersion: '5.0.0',
  meta: {
    kind: 'UnknownSelectionField',
    outputType: { name: 'ModulePackage', fields: [Array] },
    selectionPath: [ 'findManyModulePackage', 'idd' ]
  }
}


Error while processing the request
TypeError: Cannot destructure property 'clientVersion' of 'undefined' as it is undefined.
    at new PrismaClientValidationError (/{REDACTED]/node_modules/@prisma/client-mysql/runtime/library.js:26:2545)
    at Logger._cloneError (/{REDACTED]/node_modules/.pnpm/tslog@4.8.2/node_modules/tslog/dist/cjs/BaseLogger.js:238:26)
    at Logger._recursiveCloneAndMaskValuesOfKeys (/{REDACTED]/node_modules/.pnpm/tslog@4.8.2/node_modules/tslog/dist/cjs/BaseLogger.js:183:41)
    at /{REDACTED]/node_modules/.pnpm/tslog@4.8.2/node_modules/tslog/dist/cjs/BaseLogger.js:157:25
    at Array.map (<anonymous>)
    at Logger._mask (/{REDACTED]/node_modules/.pnpm/tslog@4.8.2/node_modules/tslog/dist/cjs/BaseLogger.js:156:22)
    at Logger.log (/{REDACTED]/node_modules/.pnpm/tslog@4.8.2/node_modules/tslog/dist/cjs/BaseLogger.js:99:24)
    at Logger.error (/{REDACTED]/node_modules/.pnpm/tslog@4.8.2/node_modules/tslog/dist/cjs/index.js:29:22)
    at /{REDACTED]/node_modules/.pnpm/@blitzjs+rpc@2.0.0-beta.30_@tanstack+query-core@4.24.4_blitz@2.0.0-beta.30_next@13.4.9_react-dom@18.2.0_react@18.2.0/node_modules/@blitzjs/rpc/dist/index-server.cjs:326:15
    at Generator.throw (<anonymous>)
    at rejected (/{REDACTED]/node_modules/.pnpm/@blitzjs+rpc@2.0.0-beta.30_@tanstack+query-core@4.24.4_blitz@2.0.0-beta.30_next@13.4.9_react-dom@18.2.0_react@18.2.0/node_modules/@blitzjs/rpc/dist/index-server.cjs:127:29)

```

### How to reproduce

Unable to reproduce in a separate repository. See `Bug description`.

### Expected behavior

The correct error should be thrown that actually shows what is wrong with the query, such as

```
 Unknown field `idd` for select statement on model `SomeModel`. Available options are listed in green.
```

### Prisma information

**Prisma schema:**

```prisma
datasource db {
  provider = "mysql"
  url      = env("MYSQL_DATABASE_URL")
}

generator client {
  provider      = "prisma-client-js"
  binaryTargets = ["native", "rhel-openssl-1.0.x"]
  output        = "../../node_modules/@prisma/client-mysql"
}

// ... a lot of unrelated models

model ModulePackage {
  id                              Int     @id @default(autoincrement())
  uuid                            String  @unique @default(uuid()) @db.VarChar(36)
  
  // a bunch of unrelated fields
  
  status   Status @relation(fields: [statusId], references: [id])
  statusId Int    @map("mrb_sys_status_id")

  companyProduct   CompanyProduct @relation(fields: [companyProductId], references: [id])
  companyProductId Int            @map("mrb_sys_company_product_id")

  createdAt DateTime @default(now()) @map("created")
  editedAt  DateTime @updatedAt @map("edited")

  @@unique([uuid, companyProductId])
  @@map("mrb_module_package")
}


model Status {
  id   Int    @id @default(autoincrement())
  code String @unique
  
  // a bunch of unrelated fields

  modulePackages                             ModulePackage[]

  @@map("mrb_sys_status")
}


model CompanyProduct {
  id                             Int                  @id @default(autoincrement())
  uuid                           String               @unique @default(uuid()) @db.VarChar(36)
  name                           String
  code                           String               @unique
  
  // a bunch of unrelated fields

  status   Status @relation(fields: [statusId], references: [id])
  statusId Int    @map("mrb_sys_status_id")

  modulePackages                             ModulePackage[]

  @@map("mrb_sys_company_product")
}


// ... a lot of unrelated models
```

**Query:**

```ts
await mysql.modulePackage.findMany({
      where: {
	    AND: {
	      status: { code: { in: ["active", "inactive"] } },
	      companyProductId: companyProduct.id,
	    },
	    OR: [
	      {
	        translations: {
	          some: {
	            name: { contains: search },
	          },
	        },
	      },
	    ],
	  },
      select: {
        idd: true,
      },
    })
```

### Environment & setup

- OS: `Cinnamon 5.0.7 wm: muffin dm: LightDM Distro: Linux Mint 20.2 Uma base: Ubuntu 20.04 focal `
- Database: MySQL
- Node.js version: `v16.16.0`

### Prisma Version

```
prisma                  : 5.0.0
@prisma/client          : 5.0.0
Current platform        : debian-openssl-1.1.x
Query Engine (Node-API) : libquery-engine 6b0aef69b7cdfc787f822ecd7cdc76d5f1991584 (at ../../node_modules/.pnpm/@prisma+engines@5.0.0/node_modules/@prisma/engines/libquery_engine-debian-openssl-1.1.x.so.node)
Schema Engine           : schema-engine-cli 6b0aef69b7cdfc787f822ecd7cdc76d5f1991584 (at ../../node_modules/.pnpm/@prisma+engines@5.0.0/node_modules/@prisma/engines/schema-engine-debian-openssl-1.1.x)
Schema Wasm             : @prisma/prisma-schema-wasm 4.17.0-26.6b0aef69b7cdfc787f822ecd7cdc76d5f1991584
Default Engines Hash    : 6b0aef69b7cdfc787f822ecd7cdc76d5f1991584
Studio                  : 0.487.0
```

**Comment by SevInf** [comment] 2023-07-20 13:51
Hey @justinsmid.
Thank for reporting the issue. Unfortinately, I can't reproduce it and search through our codebase shows that `clientVersion` gets passed down in all instances where `PrismaClientValidationError` is thrown. Looking at your stacktrace, it seems like the problem is in `tslog` package and they indeed have [an open issue](https://github.com/fullstack-build/tslog/issues/227) about it.

**Comment by justinsmid** [comment] 2023-07-25 11:48
Hi @SevInf, thanks for looking into it!

I have managed to reproduce the issue outside of my original repository. I followed [blitz's getting started](https://blitzjs.com/docs/get-started) steps, upgraded prisma to v5, and added a query with an invalid `select`. See: https://github.com/justinsmid/blitz-prisma-clientversion-error-reproduction

It does indeed seem like it's probably not an issue in prisma directly, but I still have some hope y'all might be able to help me out since the issue only occurs when using prisma v5 (`5.0.0`). I have tried to use the previous release of prisma (`4.16.2`), and it does **not** have the error and instead works as expected.

Would you have any idea as to why this happens in v5 specifically?

I'll go ahead and let the tslog & blitz people know about it as well in case they're able to be of any more help.

**Comment by Jolg42** [comment] 2023-07-25 11:55
@justinsmid Since v5 `PrismaClientValidationError` gets an additional constructor argument `clientVersion`
https://github.com/prisma/prisma/blob/main/packages/client/src/runtime/core/errors/PrismaClientValidationError.ts

It was passed in other errors before, so technically not a new problem in general, now this problem (which appears when using `tslog`) expanded to `PrismaClientValidationError`

**Comment by Weakky** [comment] 2024-07-25 09:52
Hey @justinsmid,

Since the issue on tslog's side is fixed, we're now closing this issue. Thanks 🙏

**Closed by Weakky** 2024-07-25 09:52 UTC
Labels: bug/1-unconfirmed, kind/bug, topic: error, tech/typescript, topic: validation, domain/client, topic: logging, 5.0.0

**Comment by vikas2705198** [comment] 2025-04-14 13:29
Cannot destructure property 'name' of 'undefined' as it is undefined.
    at normalizeSignal (C:\Users\DELL\Desktop\transactionalAnalysis\transactionalAnalysis\node_modules\@prisma\client\runtime\index.js:6211:9)
