### ISSUE TITLE
update() .data property type is not verified when multiple columns are updated at once

### ISSUE THREAD

**Issue by kukawskicorp** [prisma/prisma#25288] opened 2024-09-25 21:06 UTC
### Bug description

I came across a runtime error after dropping a column without Typescript compilation error.
I forgot to change code and remove the column from the update, but TS should not compile with invalid column name "email".
So I dig further and it turned out my TS acts strangely given different update input.
I think it's easiest to understand it by looking at VS Code screenshot with 2 different cases:
<img width="692" alt="Screenshot 2024-09-25 at 21 46 44" src="https://github.com/user-attachments/assets/e36c356e-964c-462d-8a2c-cd810911b236">
so you can see first update doesn't compile and it's underscored for "data" property of the update function. That's expected.
What's not expected is the 2nd update where there are is legal "display_name" but also "email" or "anythingReally" that just demonstrates that TS accepts anything there... 

### How to reproduce

run entity .update() with multiple data properties - 1 legal and 1 that doesn't exist

### Expected behavior

TS shouldnt compile and throw error on type mismatch

### Prisma information

```prisma
// Add your schema.prisma
```
// ...
model users {
  user_id Int @id @default(autoincrement())

  stripe_customer_id String? @db.VarChar(100)

  email String?  @db.VarChar(200) @unique

  spotify_user_id String? @db.VarChar(100) @unique

  created_at DateTime @default(now())
  updated_at DateTime @updatedAt @default(now())

  spotify_user spotify_users?
}

model spotify_users {
  spotify_user_id String @id @db.VarChar(100)
  profile_payload Json @default("{}")
  latest_token Json
  display_name String @default("")

  discoveries discoveries[]

  created_at DateTime @default(now())
  updated_at DateTime @updatedAt @default(now())

  user users @relation(fields: [spotify_user_id], references: [spotify_user_id])

}

//...

```ts
    const updateThatsCorrectlyNotCompiling = {
        email: "THIS_COLUMN_IS_GONE_FROM_SCHEMA"
    };
    const id = {
        spotify_user_id: profile.id,
    };

    prisma.spotify_users.update({
        data: updateThatsCorrectlyNotCompiling,
        where: id,
    });

    const updateThatsINCORRECTLYCompiling = {
        display_name: profile.display_name,
        email: "THIS_COLUMN_IS_GONE_FROM_SCHEMA",
        anythingReally: "WTF",
    };

    prisma.spotify_users.update({
        data: updateThatsINCORRECTLYCompiling, //WHY NO TS ERROR HERE????
        where: id,
    });
``````

### Environment & setup

- OS: macOS
- Database: PostgreSQL
- Node.js version: v22.8.0
- Typescript version: 5.6.2

### Prisma Version

```
prisma                  : 5.19.1
@prisma/client          : 5.19.1
Computed binaryTarget   : darwin
Operating System        : darwin
Architecture            : x64
Node.js                 : v22.8.0
Query Engine (Node-API) : libquery-engine 69d742ee20b815d88e17e54db4a2a7a3b30324e3 (at node_modules/@prisma/engines/libquery_engine-darwin.dylib.node)
Schema Engine           : schema-engine-cli 69d742ee20b815d88e17e54db4a2a7a3b30324e3 (at node_modules/@prisma/engines/schema-engine-darwin)
Schema Wasm             : @prisma/prisma-schema-wasm 5.19.1-2.69d742ee20b815d88e17e54db4a2a7a3b30324e3
Default Engines Hash    : 69d742ee20b815d88e17e54db4a2a7a3b30324e3
Studio                  : 0.502.0
```

**Comment by jkomyno** [comment] 2024-12-30 15:33
Closing this as a duplicate of https://github.com/prisma/prisma/issues/22445

**Closed by jkomyno** 2024-12-30 15:33 UTC
Labels: bug/1-unconfirmed, kind/bug, topic: client types, domain/client
