### ISSUE TITLE
Add .prisma syntax highlighting for IntelliJ

### ISSUE THREAD

**Issue by matthewmueller** [prisma/prisma#2339] opened 2020-04-30 15:39 UTC
## Problem

While we already have syntax highlighting for VSCode and GitHub, we should also add syntax highlighting to [IntelliJ](https://www.jetbrains.com/idea/)

**Comment by beeman** [comment] 2020-05-01 02:33
Related issue: https://github.com/prisma/prisma/issues/1788

**Comment by pantharshit00** [comment] 2020-05-02 12:29
Closing as a duplicate of #1788. This issue got opened when we split #2335 but issue about this already exists

**Closed by pantharshit00** 2020-05-02 12:29 UTC
