### ISSUE TITLE
Prefixed default values for model fields within the schema

### ISSUE THREAD

**Issue by mjyoung** [prisma/prisma#2396] opened 2020-05-08 15:49 UTC
## Problem

Sometimes I have the need to prefix a default value in my database models and I am unable to do so within the schema currently.

## Solution

I would like some sort of syntax made available to be able to specify a prefix, or suffix, to be added to the default values.

```
model User {
  id        String    @default("user_" + cuid()) @id
}
```

```
model Product {
  id        String    @default(cuid()) @id
  sku       String    @default("sku_" + cuid()) 
}
```

## Alternatives

The current alternative solution is to manually prefix using the prisma client, but I would like to be able to just define this in the schema and not have to use the client for this.

**Comment by janpio** [comment] 2021-05-29 17:00
Closing as duplicate of https://github.com/prisma/prisma/issues/3391

**Closed by janpio** 2021-05-29 17:00 UTC
Labels: kind/feature, team/client, topic: schema
