### ISSUE TITLE
Unable to import join & sql from `@prisma/client` after upgrading to 2.15

### ISSUE THREAD

**Issue by codeslayer1** [prisma/prisma#5285] opened 2021-01-26 17:22 UTC
## Bug description

I have a few raw queries being executed through Prisma using `sql` & `join` from `@prisma/client` using the steps mentioned [here](https://www.prisma.io/docs/concepts/components/prisma-client/raw-database-access#tagged-template-helpers). After upgrading to v2.15, I am getting this error in all my imports 
```
Module '"../../../node_modules/@prisma/client"' has no exported member 'join'
Module '"../../../node_modules/@prisma/client"' has no exported member 'sql'.
```
## How to reproduce
Try importing sql/join from @prisma/client

## Expected behavior
No import error

## Environment & setup

- OS: MacOS Catalina 10.15.1, Running inside docker `node:14.15.4-alpine`
- Database: PostgreSQL 
- Node.js version: v14.15.4 
- Prisma version:

```
@prisma/cli          : 2.15.0
@prisma/client       : 2.15.0
Current platform     : linux-musl
Query Engine         : query-engine e51dc3b5a9ee790a07104bec1c9477d51740fe54 (at node_modules/@prisma/engines/query-engine-linux-musl)
Migration Engine     : migration-engine-cli e51dc3b5a9ee790a07104bec1c9477d51740fe54 (at node_modules/@prisma/engines/migration-engine-linux-musl)
Introspection Engine : introspection-core e51dc3b5a9ee790a07104bec1c9477d51740fe54 (at node_modules/@prisma/engines/introspection-engine-linux-musl)
Format Binary        : prisma-fmt e51dc3b5a9ee790a07104bec1c9477d51740fe54 (at node_modules/@prisma/engines/prisma-fmt-linux-musl)
Studio               : 0.340.0
Preview Features     : nativeTypes
```

**Comment by belgattitude** [comment] 2021-01-27 18:23
Affected as well after updating from 2.14 to 2.15

**Comment by mloberg** [comment] 2021-01-27 19:15
related/same issue #5268

**Comment by pantharshit00** [comment] 2021-01-27 19:52
Closing as duplicate of #5268. 


Read: https://github.com/prisma/prisma/issues/5268#issuecomment-768536089

**Closed by pantharshit00** 2021-01-27 19:52 UTC
