### ISSUE TITLE
@readonly attribute for fields

### ISSUE THREAD

**Issue by madebysid** [prisma/prisma#3404] opened 2020-03-31 13:50 UTC
It came to my attention that in a model like so:

```
model Post {
  id        Int  @id
  title     String

  authorId  Int
  author    User @relation(fields: [authorId], references: [id])
}
```

the `authorId` field is currently readonly. In other words, scalar fields that are part of a relation are readonly right now.

It is my understanding that making them writeable is not an easy task, so they will likely remain readonly. It is also harmful for stability because overwriting it would break the relation in an unexpected manner.

I suggest we make this limitiation explicit in the schema by introducing a `@readonly` attribute / annotation to a field. This could additionally be enforced by the VSCode plugin & schema validation.

This will obviously need to be implemented separately though, since any field can be `@readonly`.

**Comment by pantharshit00** [comment] 2021-09-30 13:15
Closing as duplicate of https://github.com/prisma/prisma/issues/3401

**Closed by pantharshit00** 2021-09-30 13:15 UTC
Labels: kind/feature, topic: schema, team/client
