### ISSUE TITLE
Enhancement Request: Support Custom Error Messages in findFirstOrThrow Queries

### ISSUE THREAD

**Issue by prathamesh-dukare** [prisma/prisma#25814] opened 2024-12-07 14:08 UTC
## Problem
Currently, Prisma does not support throwing a custom error directly while querying data. For instance:

```
private db: PrismaService;

...

const user = await this.db.user.findFirst({
  where: {
    email: payload.email,
  },
  select: {
    id: true,
  },
});

if (!user) {
  throw new Error('User not found for the provided email');
}

```
In the example above, I need to manually check the result and throw a custom error if the record is not found. This adds boilerplate code and reduces readability and developer productivity.

## Suggested solution

It would be highly beneficial if Prisma allowed passing custom error details directly in the query itself, reducing the need for manual checks. For example:

```
const user = await this.db.user.findFirstOrThrow({
  where: {
    email: payload.email,
  },
  select: {
    id: true,
  },
  error: 'User not found for the provided email',
});

```

Benefits of This Approach:
1. Improved Code Readability
2. Reduced Boilerplate
3. Enhanced Developer Experience

Looking forward to a solution or feature update to address this!

**Comment by ludralph** [comment] 2024-12-23 09:30
Hi @prathamesh-dukare 

Thanks for raising this. 

This is a duplicate of this other [issue](https://github.com/prisma/prisma/issues/14091). So I'll be closing this in favour of it.

**Closed by ludralph** 2024-12-23 09:30 UTC

**Comment by prathamesh-dukare** [comment] 2024-12-24 12:04
Thank you @ludralph, looking forward to the resolution
