### ISSUE TITLE
`libquery_engine-linux-musl.so.node`, Library may be corrupt: `eval(...)` is not a function

### ISSUE THREAD

**Issue by philipp1992** [prisma/prisma#17036] opened 2022-12-27 16:55 UTC
### Bug description

Hi, 
using node 14.21 im getting the following error;

```
  prisma:client  dirname /app/dist +0ms
  prisma:client  relativePath ../../../prisma-sqlite +0ms
  prisma:client  cwd /app/dist +0ms
  prisma:client  clientVersion 4.8.0 +1ms
  prisma:client  clientEngineType library +0ms
  prisma:client:libraryEngine  internalSetup +0ms
  prisma:client:libraryEngine:loader  Searching for Query Engine Library in /.prisma/client +0ms
  prisma:client:libraryEngine:loader  loadEngine using /.prisma/client/libquery_engine-linux-musl.so.node +1ms
  prisma:client:request_handler  PrismaClientInitializationError: Unable to load Node-API Library from /.prisma/client/libquery_engine-linux-musl.so.node, Library may be corrupt: eval(...) is not a function
    at DefaultLibraryLoader._callee106$ (webpack:///./src/generated/db-client/runtime/index.js?:304:1280)
    at tryCatch (webpack:///./src/generated/db-client/runtime/index.js?:1:7766)
    at Generator.eval (webpack:///./src/generated/db-client/runtime/index.js?:1:10309)
    at Generator.eval [as next] (webpack:///./src/generated/db-client/runtime/index.js?:1:8540)
    at asyncGeneratorStep (webpack:///./src/generated/db-client/runtime/index.js?:1:17462)
    at _next (webpack:///./src/generated/db-client/runtime/index.js?:1:17776) {
  clientVersion: '4.8.0',
  errorCode: undefined
} +0ms
{"level":50,"time":1672160058447,"pid":426,"hostname":"bot-1-vector-node-5bdf45b9c8-7kd7m","name":"vector68BLebocmdstoKebtRc1kwvhheoQKeCG6fU3gMkkNAk4pgouFM","clientVersion":"4.8.0","stack":"Error: \nInvalid `prisma.nodeIndex.findMany()` inv
ocation:\n\n\nUnable to load Node-API Library from /.prisma/client/libquery_engine-linux-musl.so.node, Library may be corrupt: eval(...) is not a function\n    at RequestHandler.handleRequestError (webpack:///./src/generated/db-client/runti
me/index.js?:387:6403)\n    at RequestHandler.handleAndLogRequestError (webpack:///./src/generated/db-client/runtime/index.js?:387:5048)\n    at _callee125$ (webpack:///./src/generated/db-client/runtime/index.js?:393:2129)\n    at tryCatch
(webpack:///./src/generated/db-client/runtime/index.js?:1:7766)\n    at Generator.eval (webpack:///./src/generated/db-client/runtime/index.js?:1:10309)\n    at Generator.eval [as throw] (webpack:///./src/generated/db-client/runtime/index.js
?:1:8540)\n    at asyncGeneratorStep (webpack:///./src/generated/db-client/runtime/index.js?:1:17462)\n    at _throw (webpack:///./src/generated/db-client/runtime/index.js?:1:17863)","type":"Error","msg":"\nInvalid `prisma.nodeIndex.findMan
y()` invocation:\n\n\nUnable to load Node-API Library from /.prisma/client/libquery_engine-linux-musl.so.node, Library may be corrupt: eval(...) is not a function"}
  prisma:client:libraryEngine:exitHooks  exit event received: exit +0ms
```

### Prisma information

```prisma
// Add your schema.prisma
```

```ts
// Add your code using Prisma Client
```

### Environment & setup

- OS: 
- Database: 
- Node.js version: 

### Prisma Version

```

```

**Comment by philipp1992** [comment] 2022-12-27 19:12
im generating the prisma client and then running tsc to compile.
now i use webpack with the following webpack config:

```
const CopyPlugin = require("copy-webpack-plugin");
const path = require("path");

module.exports = {
  mode: "development",
  target: "node",


  context: path.join(__dirname, ".."),

  entry: path.join(__dirname, "../src/index.ts"),



  externals: {
    ".prisma/client": "commonjs2 .prisma/client",
    "@prisma/client": "commonjs2 @prisma/client",
    "pg-native": "commonjs2 pg-native", "stream/web": "stream/web", "util/types": "util/types",
    sqlite3: "commonjs2 sqlite3",
  },

  node: {
    __filename: false,
    __dirname: false,
  },

  resolve: {
    mainFields: ["main", "module"],
    extensions: [".js", ".wasm", ".ts", ".json"],
    symlinks: false,
  },

  output: {
    path: path.join(__dirname, "../dist"),
    filename: "bundle.js",
  },

  module: {
    rules: [
      {
        test: /\.js$/,
        exclude: /node_modules/,
        use: {
          loader: "babel-loader",
          options: {
            presets: ["@babel/env"],
          },
        },
      },
      {
        test: /\.ts$/,
        exclude: /node_modules/,
        use: {
          loader: "ts-loader",
          options: {
            configFile: path.join(__dirname, "../tsconfig.json"),
          },
        },
      },
      {
        test: /\.wasm$/,
        type: "javascript/auto",
        use: "wasm-loader",
      },
    ],
  },

  plugins: [
    new CopyPlugin({
      patterns: [
        {
          from: path.join(__dirname, "../node_modules/@connext/vector-contracts/dist/pure-evm_bg.wasm"),
          to: path.join(__dirname, "../dist/pure-evm_bg.wasm"),
        },
        {
          from: path.join(__dirname, "../prisma-postgres"),
          to: path.join(__dirname, "../dist/prisma-postgres"),
        },
        {
          from: path.join(__dirname, "../prisma-sqlite"),
          to: path.join(__dirname, "../dist/prisma-sqlite"),
        },
        {
          from: path.join(__dirname, "../src/generated"),
          to: path.join(__dirname, "../dist/generated"),
        },
      ],
    }),
  ],

  stats: { warnings: false },
};
```

When running the bundle, i get the following error,
```wvhheoQKeCG6fU3gMkkNAk4pgouFM","clientVersion":"4.8.0","stack":"Error: \nInvalid `prisma.nodeIndex.findMany()` invocation:\n\n\nUnable to load Node-API Library from /app/modules/server-node/src/generated/db-client/libquery_engine-linux-musl.so.node, Library may be corrupt: eval(...) is not a function\n    at RequestHandler.handleRequestError (webpack:///./src/generated/db-client/runtime/index.js?:387:6403)\n    at RequestHandler.handleAndLogRequestError (webpack:///./src/generated/db-client/runtime/index.js?:387:5048)\n    at _callee125$ (webpack:///./src/generated/db-client/runtime/index.js?:393:2129)\n    at tryCatch (webpack:///./src/generated/db-client/runtime/index.js?:1:7766)\n    at Generator.eval (webpack:///./src/generated/db-client/runtime/index.js?:1:10309)\n    at Generator.eval [as throw] (webpack:///./src/generated/db-client/runtime/index.js?:1:8540)\n    at asyncGeneratorStep (webpack:///./src/generated/db-client/runtime/index.js?:1:17462)\n    at _throw (webpack:///./src/generated/db-client/runtime/index.js?:1:17863)","type":"Error","msg":"\nInvalid `prisma.nodeIndex.findMany()` invocation:\n\n\nUnable to load Node-API Library from /app/modules/server-node/src/generated/db-client/libquery_engine-linux-musl.so.node, Library may be corrupt: eval(...) is not a function"}```

**Comment by jkomyno** [comment] 2022-12-28 10:30
Hi @philipp1992, what operating system are you using? It looks like you're running Prisma on Linux Alpine. Are you using Docker? If so, which Docker image are you running? You can paste your Dockerfile here if you may.

Moreover, what architecture does your system have? We currently support Linux alpine on `amd64` natively, with `arm64` support available only via `docker buildx` architecture emulation.

**Comment by jkomyno** [comment] 2022-12-28 10:34
Moreover, have you tried removing `commonjs2` from the `prisma` declarations in your Webpack config?

**Comment by philipp1992** [comment] 2022-12-28 15:23
yeah im using prisma 4.8 and removing the commonjs doesnt help

**Comment by philipp1992** [comment] 2022-12-28 15:50
its throwing the expection here in bundle.js at executing the eval("require") function

eval("require")(this.libQueryEnginePath));case 9:_context109.prev=9;_context109.t0=_context109["catch"](5);if(!import_fs6["default"].existsSync(this.libQueryEnginePath)){_context109.next=19;break;}if(!this.libQueryEnginePath.endsWith(".node")){_context109.next=16;break;}throw new _PrismaClientInitializationError("Unable to load Node-API Library from ".concat(import_chalk4["default"].dim(this.libQueryEnginePath),", Library may be corrupt: ").concat(_context109.t0.message),this.config.clientVersion);case 16:throw new _PrismaClientInitializationError("Expected an Node-API Library but received ".concat(import_chalk4["default"].dim(this.libQueryEnginePath)),this.

which is this piece of code.

    debug8(`loadEngine using ${this.libQueryEnginePath}`);
    try {
      return eval("require")(this.libQueryEnginePath);
    } catch (e2) {


why on earth does  my nodejs env think eval is not a function? eval works in normal context

**Comment by Jolg42** [comment] 2023-01-02 14:29
@philipp1992 
What is the environment (OS, Node.js version) when it fails with `eval(...) is not a function`?
Are you using a provider like Vercel for example?

**Comment by philipp1992** [comment] 2023-01-02 15:06
I think it has something to do with webpack. When I run it directly it works. The error happens on docker on my local machine using alpine nodejs and on a virtual machine.

**Comment by janpio** [comment] 2023-01-03 17:21
What is the minimal setup we need to run to reproduce this? Can you maybe create a reproduction repository on GitHub that we can just check out and run a few commands to see what you are seeing? That would be most helpful. Thanks!

**Comment by Weakky** [comment] 2023-07-13 13:05
Hey @philipp1992,

A reproduction repository would be helpful for us to move forward with that issue. Did you get a chance to create one?

Thank you 🙏

**Comment by petradonka** [comment] 2023-07-23 14:47
Hello @philipp1992, could you help us with more details on how to reproduce this issue? This will help us in in addressing the issue. Thank you!

**Comment by jharrell** [comment] 2023-08-07 15:35
Hi @philipp1992 unfortunately, we have to close this issue without more info. If you'd like, drop a comment with a reproduction and we'll happily re-open. 

Thank you!

**Closed by jharrell** 2023-08-07 15:35 UTC
Labels: bug/0-unknown, kind/bug, tech/typescript, team/client, topic: bundler, topic: webpack, topic: Unable to load ... Library may be corrupt
