### ISSUE TITLE
pnpm workspace + nextjs: `ENOENT: no such file or directory, open '...\.next\server\pages\api\schema.prisma'`

### ISSUE THREAD

**Issue by ineentho** [prisma/prisma#12853] opened 2022-04-16 15:42 UTC
### Bug description

I have a pnpm workspace with three projects:
- / -root project
- /packages/database - Prisma installed as a dependency, re-export generated prisma client
- /packages/next - A standard next.js typescript template, importing the database project

When I run the next project I get this error:
```
error - Error: ENOENT: no such file or directory, open 'C:\Users\hkhen\dev\pnpm-next\packages\next\.next\server\pages\api\schema.prisma'
```

I've tried a few variations: prisma and @prisma/client 3.12.0 and 3.13.0-dev.15, standard output directory and ` output   = "../src/generated/prisma"`, all give the same error.

It sounds like this is kind of the same error as #10361, but it seems like next.js does something special handling of dirname. Regular node-js server apps works fine with the same setup.

### How to reproduce

Terminal 1:
```
git clone git@github.com:ineentho/pnpm-nextjs-repro.git
cd pnpm-nextjs-repro
pnpm i # prisma generate runs as a postinstall hook
pnpm start # run next in dev-mode
```
Termnal 2:
```
curl localhost:3000/api/hello
```

The first terminal will log the error:

```
ready - started server on 0.0.0.0:3000, url: http://localhost:3000
wait  - compiling...
event - compiled client and server successfully in 643 ms (124 modules)
wait  - compiling /api/hello...
wait  - compiling...
warn  - ../database/src/generated/prisma/runtime/index.js
Module not found: Can't resolve 'encoding' in 'C:\Users\hkhen\dev\pnpm-nextjs-repro\packages\database\src\generated\prisma\runtime'
2022-04-16T15:35:50.611Z prisma:tryLoadEnv Environment variables not found at null
2022-04-16T15:35:50.612Z prisma:tryLoadEnv Environment variables not found at undefined
2022-04-16T15:35:50.612Z prisma:tryLoadEnv No Environment variables loaded
2022-04-16T15:35:50.631Z prisma:tryLoadEnv Environment variables not found at null
2022-04-16T15:35:50.631Z prisma:tryLoadEnv Environment variables not found at undefined
2022-04-16T15:35:50.631Z prisma:tryLoadEnv No Environment variables loaded
2022-04-16T15:35:50.631Z prisma:client dirname C:\Users\hkhen\dev\pnpm-nextjs-repro\packages\next\.next\server\pages\api
2022-04-16T15:35:50.631Z prisma:client relativePath ..\..\..\prisma
2022-04-16T15:35:50.632Z prisma:client cwd C:\Users\hkhen\dev\pnpm-nextjs-repro\packages\next\.next\server\pages\api
2022-04-16T15:35:50.634Z prisma:client clientVersion: 3.12.0
2022-04-16T15:35:50.634Z prisma:client clientEngineType: library
error - Error: ENOENT: no such file or directory, open 'C:\Users\hkhen\dev\pnpm-nextjs-repro\packages\next\.next\server\pages\api\schema.prisma'
warn  - ../database/src/generated/prisma/runtime/index.js
Module not found: Can't resolve 'encoding' in 'C:\Users\hkhen\dev\pnpm-nextjs-repro\packages\database\src\generated\prisma\runtime'
wait  - compiling /_error (client and server)...
wait  - compiling...
warn  - ../database/src/generated/prisma/runtime/index.js
Module not found: Can't resolve 'encoding' in 'C:\Users\hkhen\dev\pnpm-nextjs-repro\packages\database\src\generated\prisma\runtime'
2022-04-16T15:35:50.868Z compression no compression: not acceptable
```

### Environment & setup

- OS: Windows 10
- Database: Postgres
- Node.js version: v17.3.0

### Prisma Version

```
prisma                  : 3.12.0
@prisma/client          : 3.12.0
Current platform        : windows
Query Engine (Node-API) : libquery-engine 22b822189f46ef0dc5c5b503368d1bee01213980 (at ..\..\node_modules\.pnpm\@prisma+engines@3.12.0-37.22b822189f46ef0dc5c5b503368d1bee01213980\node_modules\@prisma\engines\query_engine-windows.dll.node)
Migration Engine        : migration-engine-cli 22b822189f46ef0dc5c5b503368d1bee01213980 (at ..\..\node_modules\.pnpm\@prisma+engines@3.12.0-37.22b822189f46ef0dc5c5b503368d1bee01213980\node_modules\@prisma\engines\migration-engine-windows.exe)
Introspection Engine    : introspection-core 22b822189f46ef0dc5c5b503368d1bee01213980 (at ..\..\node_modules\.pnpm\@prisma+engines@3.12.0-37.22b822189f46ef0dc5c5b503368d1bee01213980\node_modules\@prisma\engines\introspection-engine-windows.exe)
Format Binary           : prisma-fmt 22b822189f46ef0dc5c5b503368d1bee01213980 (at ..\..\node_modules\.pnpm\@prisma+engines@3.12.0-37.22b822189f46ef0dc5c5b503368d1bee01213980\node_modules\@prisma\engines\prisma-fmt-windows.exe)
Default Engines Hash    : 22b822189f46ef0dc5c5b503368d1bee01213980
Studio                  : 0.459.0
```

**Comment by garrensmith** [comment] 2022-04-20 15:27
just confirming that you are generating the client?
```
pnpx prisma generate
```

**Comment by ineentho** [comment] 2022-04-20 16:36
Thanks for the response! Yes, I am generating prisma in a postinstall hook:
```
packages/database postinstall$ prisma generate
│ Prisma schema loaded from prisma\schema.prisma
│ ✔ Generated Prisma Client (3.12.0 | library) to .\src\generated\prisma in 136ms
│ You can now start using Prisma Client in your code. Reference: https://pris.ly/d/client
│ ```
│ import { PrismaClient } from './src\generated\prisma'
│ const prisma = new PrismaClient()
│ ```
└─ Done in 1.5s
```

```
❯ cat ./packages/database/src/index.ts
export * from "./generated/prisma";

❯ ls ./packages/database/src/generated/prisma/
index.d.ts  index.js  index-browser.js  query_engine-windows.dll.node*  runtime/  schema.prisma
```

**Comment by orbiteleven** [comment] 2022-05-03 18:33
Seems related to https://github.com/prisma/prisma/issues/12921

**Comment by jld-adriano** [comment] 2022-11-29 11:21
> Possible workaround Context, I'm using PNPM workspaces and my prisma config is in a packages that is used by a Nest.js app. The Nest.js app bundle the generated Prisma build with. webpack.
> 
> In post build of `prisma generate`, I run the following script and it's doing the trick (for now). If `regularDirname` variable name is changed, the script will need an update
> 
> ```
> const fs = require("node:fs");
> 
> const generateLibPath = __dirname + "/../build/index.js";
> 
> const file = fs.readFileSync(generateLibPath);
> const lines = file.toString().split("\n");
> 
> const newLines = lines.map((line) =>
>   line.startsWith("const regularDirname")
>     ? "const regularDirname = path.dirname(require.resolve('.'))"
>     : line
> );
> 
> const joinedNewLine = newLines.join("\n");
> 
> fs.writeFileSync(generateLibPath, joinedNewLine);
> ```

This solution worked for me. Thanks

I have a yarn workspaces monorepo and am importing prisma from a different package into a nextjs project, so I don't believe this is a pnpm only issue

**Comment by lord007tn** [comment] 2022-12-23 10:25
I faced the same problem for the past 2 days and I make it work and i don't know why but here is the code of my singleton PrismaClient. 
```
import { PrismaClient } from "@prisma/client";

let prisma: PrismaClient;
declare module globalThis {
	// eslint-disable-next-line no-var
	let prisma: PrismaClient | undefined;
}

if (process.env.NODE_ENV === "production") {
	prisma = new PrismaClient({
		errorFormat: "minimal",
	});
} else {
	globalThis.prisma =
		globalThis.prisma ||
		new PrismaClient({
			errorFormat: "pretty",
		});
	prisma = globalThis.prisma;
}
export * from "./zod";
export * from "@prisma/client"; 
```

the previous singleton PrismaClient
```
import { PrismaClient } from "@prisma/client";

declare global {
	// eslint-disable-next-line no-var
	var prisma: PrismaClient | undefined;
}

export const prisma =
	globalThis.prisma ||
	new PrismaClient({
		log: process.env.NODE_ENV === "development" ? ["error", "warn"] : ["error"],
	});

if (process.env.NODE_ENV !== "production") {
	globalThis.prisma = prisma;
}
export default prisma;
export * from "./zod";
export * from "@prisma/client";
```

Environment
- Windows: 11
- Node 16.15.1
- Db: Mongodb
- PNPM 7.14.0

Could anyone explain why it worked ?

**Comment by janpio** [comment] 2023-01-27 00:38
Thank you for the excellent reproduction @ineentho, the problem was super easy to reproduce this way.

We are currently testing a workaround for this problem. Here is a PR that in our testing fixed your problem: https://github.com/ineentho/pnpm-nextjs-repro/pull/1/files Note that I needed to adapt your index.ts that re-exports the Client.

**Comment by janpio** [comment] 2023-01-27 00:43
@jean-smaug @jld-adriano We are currently working on a better workaround that does not need brittle modifying of the generated Prisma Client, see the comment above for an example. Please let us know if this works for you.

@lord007tn The singleton you are using should not have _any_ impact on this problem. But happy it worked for you although we do not understand why 😆

**Comment by TheUnlocked** [comment] 2023-01-28 21:43
For those looking for a quick solution _now_, I came up with a [PNPM patch](https://pnpm.io/cli/patch) which resolved the issue for me (no idea how portable it is, I haven't tried it on the repro yet)

Create `patches/@prisma__client@4.9.0.patch` at the root with:
```diff
diff --git a/generator-build/index.js b/generator-build/index.js
index 888e53268d94ba836cad78fd2d24e59066449657..33b9f49bf94f67caf5425851d84a272c70828847 100644
--- a/generator-build/index.js
+++ b/generator-build/index.js
@@ -23390,13 +23390,18 @@ const hasDirname = typeof __dirname !== 'undefined' && __dirname !== '/'
 // will work in most cases, ie. if the client has not been bundled
 const regularDirname = hasDirname && fs.existsSync(path.join(__dirname, 'schema.prisma')) && __dirname
 
+const dirnameCandidates = [
+  ${defaultRelativeOutdir ? `${JSON.stringify(defaultRelativeOutdir)},` : ""}
+  ${serverlessRelativeOutdir ? `${JSON.stringify(serverlessRelativeOutdir)},` : ""}
+];
+
 // if the client has been bundled, we need to look for the folders
-const foundDirname = !regularDirname && findSync(process.cwd(), [
-    ${defaultRelativeOutdir ? `${JSON.stringify(defaultRelativeOutdir)},` : ""}
-    ${serverlessRelativeOutdir ? `${JSON.stringify(serverlessRelativeOutdir)},` : ""}
-], ['d'], ['d'], 1)[0]
+const foundDirname = !regularDirname && findSync(process.cwd(), dirnameCandidates, ['d'], ['d'], 1)[0]
+
+// in monorepos, they could be at a higher level
+const monorepoFoundDirname = !regularDirname && !foundDirname && dirnameCandidates.map(x => path.join(process.cwd(), x)).find(x => fs.existsSync(path.join(x, 'schema.prisma')))
 
-const dirname = regularDirname || foundDirname || __dirname`;
+const dirname = regularDirname || foundDirname || monorepoFoundDirname || __dirname`;
 }
 __name(buildDirnameFind, "buildDirnameFind");
 function buildDirnameDefault() {
```
Then in your top-level `package.json` you'll want to add
```json
  "pnpm": {
    "patchedDependencies": {
      "@prisma/client@4.9.0": "patches/@prisma__client@4.9.0.patch"
    }
  }
```

And then `npx prisma generate` again. I also have `hoist-pattern[]=*prisma*` in my `.npmrc` which may be important, though I'm honestly not sure.

What I think is going on is that prisma is actually finding the right path, but since `.prisma/client` is in `node_modules/.pnpm` (which is in the root), the relative path (relative to the app folder) will have some backtracking which the `findSync` function doesn't seem to support. So the whole thing falls back to using `__dirname` to find the path, which Next.js lies about (that's why it ends up searching in `.next/server/pages`). However, I don't fully understand what prisma is doing and so it's possible that this is only working for me by some strange coincidence.

**Comment by j0hnm4r5** [comment] 2023-01-30 09:39
@TheUnlocked that patch worked for me (I did need to include the hoist pattern in `.npmrc`).

**Comment by millsp** [comment] 2023-01-30 13:47
@TheUnlocked are you able to successfully deploy to Vercel with the patch?

**Comment by millsp** [comment] 2023-01-30 13:50
Also, could you try this workaround without a patch to let us know if it worked for you? Replace `database` with the name of the package that contains the Prisma Client.

```ts
const path = require('path')

/** @type {import('next').NextConfig} */
module.exports = {
  output: 'standalone',
  experimental: {
    outputFileTracingRoot: path.join(__dirname, '../../'),
  },
  webpack: (config, { buildId, dev, isServer, defaultLoaders, webpack }) => {
    config.externals = [...config.externals, 'database']

    return config
  },
}
```

**Comment by TheUnlocked** [comment] 2023-01-30 14:56
@millsp Ah, not working on Vercel. Oh well.

That workaround is not going to work for me, though that's due to me doing things sort of "improperly" (basically I'm not building every package, I'm just leaving them as sources, automatically finding all of their names, and then feeding that list into `transpilePackages`). It's possible that it will work for others who being a bit more idiomatic about how they make monorepos.

**Comment by millsp** [comment] 2023-01-30 15:10
Interesting. Basically, what we currently understand is that this is not really a Prisma issue, although we want to help. Explanation:
* `outputFileTracingRoot: path.join(__dirname, '../../')`
This tells Next.js, hey your are in a monorepo, please also collect files that are higher above the Next.js package folder. By default Next.js behaves this way in monorepos. JS files will be collected correctly but not all the other files. https://nextjs.org/docs/advanced-features/output-file-tracing#caveats
* `config.externals = [...config.externals, 'database']`
Next.js always marks Prisma as external. However, because this is a local package, it will bundle it by default. So the solution is to treat that package as external.

That being said `transpilePackages` is a legitimate use case. Do you have ideas to make this work?

**Comment by j0hnm4r5** [comment] 2023-01-30 15:15
@millsp i was able to deploy it to Vercel without issue.

**Comment by millsp** [comment] 2023-01-30 15:18
Hey @j0hnm4r5 could you please share that working reproduction with me?

**Comment by janpio** [comment] 2023-01-30 22:31
@relsunkaev Can you share your project or a reproduction version of it? That would be amazing.

**Comment by TheUnlocked** [comment] 2023-01-31 03:44
I finally got something working! It relies on special-casing magic Vercel paths, but it works!

First, you _must_ add `public-hoist-pattern[]=*prisma*` to your `.npmrc`. [The default](https://pnpm.io/npmrc#public-hoist-pattern) is also to include `*eslint*` and `*prettier*` (though I don't use prettier so I left that one out). Overall, my `.npmrc` looks like this:

```npmrc
auto-install-peers=true
link-workspace-packages=deep
save-workspace-protocol=rolling

public-hoist-pattern[]=*eslint*
public-hoist-pattern[]=*prisma*
```

Here's the updated patch:
```diff
diff --git a/generator-build/index.js b/generator-build/index.js
index 888e53268d94ba836cad78fd2d24e59066449657..33b9f49bf94f67caf5425851d84a272c70828847 100644
--- a/generator-build/index.js
+++ b/generator-build/index.js
@@ -23390,13 +23390,18 @@ const hasDirname = typeof __dirname !== 'undefined' && __dirname !== '/'
 // will work in most cases, ie. if the client has not been bundled
 const regularDirname = hasDirname && fs.existsSync(path.join(__dirname, 'schema.prisma')) && __dirname
 
+const dirnameCandidates = [
+  ${defaultRelativeOutdir ? `${JSON.stringify(defaultRelativeOutdir)},` : ""}
+  ${serverlessRelativeOutdir ? `${JSON.stringify(serverlessRelativeOutdir)},` : ""}
+];
+
 // if the client has been bundled, we need to look for the folders
-const foundDirname = !regularDirname && findSync(process.cwd(), [
-    ${defaultRelativeOutdir ? `${JSON.stringify(defaultRelativeOutdir)},` : ""}
-    ${serverlessRelativeOutdir ? `${JSON.stringify(serverlessRelativeOutdir)},` : ""}
-], ['d'], ['d'], 1)[0]
+const foundDirname = !regularDirname && findSync(process.cwd(), dirnameCandidates, ['d'], ['d'], 1)[0]
+
+// in monorepos, they could be at a higher level
+const monorepoFoundDirname = !regularDirname && !foundDirname && dirnameCandidates.map(x => path.join(process.cwd(), x)).find(x => fs.existsSync(path.join(x, 'schema.prisma')))
 
-const dirname = regularDirname || foundDirname || __dirname`;
+const dirname = regularDirname || foundDirname || monorepoFoundDirname || __dirname`;
 }
 __name(buildDirnameFind, "buildDirnameFind");
 function buildDirnameDefault() {
diff --git a/runtime/index.js b/runtime/index.js
index db697a88c418f974ffa9fb3100809b0cd9c0aea6..5410cef01c7781122ce3de22e2ba1d00cd883570 100644
--- a/runtime/index.js
+++ b/runtime/index.js
@@ -24549,7 +24549,17 @@ var exitHooks = new ExitHooks();
 var LibraryEngine = class extends Engine {
   constructor(config2, loader = new DefaultLibraryLoader(config2)) {
     super();
-    this.datamodel = import_fs7.default.readFileSync(config2.datamodelPath, "utf-8");
+    if (!import_fs7.default.existsSync(config2.datamodelPath)) {
+      debug11(`Couldn't find datamodelPath '${config2.datamodelPath}', may be on Vercel.`);
+      if (import_fs7.default.existsSync('/var/task/node_modules/.pnpm')) {
+        const dotPnpmPackageName = import_fs7.readdirSync('/var/task/node_modules/.pnpm').find(x => x.startsWith('@prisma+client'));
+        config2.datamodelPath = `/var/task/node_modules/.pnpm/${dotPnpmPackageName}/node_modules/.prisma/client/schema.prisma`
+      }
+      else {
+        debug11(`Couldn't find '/var/task/node_modules/.pnpm', something is broken.`);
+      }
+    }
+    this.datamodel = import_fs7.default.readFileSync(datamodelPath, "utf-8");
     this.config = config2;
     this.libraryStarted = false;
     this.logQueries = config2.logQueries ?? false;
```
Basically, in addition to what the patch did previously (which works well for local development), if it can't find the file it will now check a known Vercel deployment path to see if it's there. This is obviously not an ideal solution, but if this issue is a complete blocker for you, it should at least help for the time being.

Some notes:
* This does _not_ work with `outputFileTracingRoot: path.join(__dirname, '../../')`. For some reason Vercel _isn't_ able to trace files correctly with it set (which is sort of counter-intuitive).
* PNPM patches are a bit buggy (or at least their interaction with caching is), so you'll probably need to redeploy without the build cache/delete some/all of your `node_modules` to re-apply. The lockfile can also get confused, but I find that if I `pnpm i @prisma/client` in the database package again it fixes it.
* Sometimes, especially when changing `hoist-pattern` and reinstalling, attempting to `npx prisma generate` would throw a mess of errors. I don't know whose fault that is but if you delete all of your `node_modules` (`npx rimraf **/node_modules`) _and_ your PNPM store, and then re-download/install everything, it fixes itself.
* In the patch, re-assigning `config2.datamodelPath` _is_ important. I don't know why, and the log outputs are kind of baffling when you don't re-assign it. The existence of the directory in `node_modules/.pnpm` seems to be dependent on it..?
* While I sincerely hope that all of this will work for others, keep in mind that this is wonky territory and it may be highly dependent on your particular monorepo configuration.

**Comment by j0hnm4r5** [comment] 2023-01-31 09:03
@TheUnlocked I changed my monorepo structure around a bit and that no longer works for me, so you're totally right with that caveat.

@millsp I don't have a working repro, but here's a not-working one if that's of any help: https://github.com/j0hnm4r5/prisma-nextauth-turbo-issue

**Comment by j0hnm4r5** [comment] 2023-02-01 06:24
Interesting note: [this repo](https://github.com/aiji42/turbo-with-prisma) works with the version of prisma it ships with (^4.1.1), but breaks when upgrading to latest.

Also, this seems to be happening with `npm` as well, not just `pnpm`.

**Comment by millsp** [comment] 2023-02-03 03:51
Hey guys, thanks for the feedback. We have been working on a simpler way to make things work for you, as the workaround we proposed had clear limitations for TS projects. We worked on an experimental webpack plugin that ensures your Prisma files are copied correctly. I'd love if you could give it a try (https://www.npmjs.com/package/experimental-prisma-webpack-plugin). We have tested it in many different scenarios, so we hope this works for you.

```ts
const { PrismaPlugin } = require('experimental-prisma-webpack-plugin')

module.exports = {
  output: 'standalone',
  webpack: (config, { isServer }) => {
    if (isServer) {
      config.plugins = [...config.plugins, new PrismaPlugin()]
    }

    return config
  },
}
```

**Comment by millsp** [comment] 2023-02-03 23:10
Thanks. I definitely not tested multiple clients with this experimental package. We should just make that work. And yes, I agree that transpiling with tsc isn't nice so we'll just try to make this work. I don't think your repro has that double client in it? I'll try to reproduce it myself but would appreciate if you can add that as a branch in your repro :pray:

**Comment by j0hnm4r5** [comment] 2023-02-04 08:13
That does seem to work on min right out of the box at least!

**Comment by spigelli** [comment] 2023-02-08 09:23
> We have been working on a simpler way to make things work for you, as the workaround we proposed had clear limitations for TS projects. We worked on an experimental webpack plugin that ensures your Prisma files are copied correctly. I'd love if you could give it a try (https://www.npmjs.com/package/experimental-prisma-webpack-plugin). We have tested it in many different scenarios, so we hope this works for you.
@millsp I'm using `pnpm link` rather than workspace and this along with `PRISMA_CLIENT_ENGINE_TYPE=binary` solved my issue 🙏

**Comment by millsp** [comment] 2023-02-18 01:42
Hey @relsunkaev, the webpack plugin I provided now supports multiple clients at once. You just need to make sure your clients have the same version, as only one engine will be copied.

**Comment by millsp** [comment] 2023-02-22 01:20
Thanks for the report, I will take a look.

**Comment by millsp** [comment] 2023-02-22 17:09
Hey @relsunkaev, would you have the time to create a minimal reproduction? I don't have android set up right now, so that would help. That said, I think there is a similar report [here](https://github.com/prisma/prisma/issues/12921#issuecomment-1437345309) (but with `getStaticProps`), so I am going to investigate that first.

**Closed** 2023-02-24 17:34 UTC
Labels: bug/2-confirmed, kind/bug, tech/typescript, topic: Next.js, team/client, topic: monorepo, topic: pnpm, topic: pnpm workspaces, topic: ENOENT schema.prisma

**Comment by millsp** [comment] 2023-02-24 17:39
For those using multiple Prisma Clients, we are going to schedule follow-up work via https://github.com/prisma/prisma/issues/18069. Please upvote it if you need multi-client support, and don't hesitate to share more information there.
