### ISSUE TITLE
Invalid response data: the query result was required, but an empty Object((Weak)) was returned instead (smf, MySQL)

### ISSUE THREAD

**Issue by janpio** [prisma/prisma#1826] opened 2020-03-11 20:25 UTC
```
020-03-11T13:57:08.683Z prisma-client prisma.smf_board_permissions.create({
  data: {
    add_deny: -605,
    id_group: 10,
    id_profile: 10,
    permission: '5bc06113-98c5-5f6b-a939-6ed5c80333ed'
  }
})
2020-03-11T13:57:08.683Z prisma-client Generated request:
2020-03-11T13:57:08.683Z prisma-client mutation {
  createOnesmf_board_permissions(data: {
    add_deny: -605
    id_group: 10
    id_profile: 10
    permission: "5bc06113-98c5-5f6b-a939-6ed5c80333ed"
  }) {
    add_deny
    id_group
    id_profile
    permission
  }
}

...

PrismaClientUnknownRequestError: 
Invalid `prisma.smf_board_permissions.create()` invocation in
/home/runner/work/introspection-engine-output/prisma-test-utils/src/static/seed.ts:935:45

Invalid response data: the query result was required, but an empty Object((Weak)) was returned instead.
```

```sql
CREATE TABLE `smf_board_permissions` (
  `id_group` smallint(5) NOT NULL DEFAULT '0',
  `id_profile` smallint(5) unsigned NOT NULL DEFAULT '0',
  `permission` varchar(30) NOT NULL DEFAULT '',
  `add_deny` tinyint(4) NOT NULL DEFAULT '1',
  PRIMARY KEY (`id_group`,`id_profile`,`permission`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;
```

**Comment by janpio** [comment] 2020-03-11 20:25
`add_deny: -605` and ``add_deny` tinyint(4) NOT NULL DEFAULT '1',` clash as max values are -127<->127.

**Comment by janpio** [comment] 2020-09-02 02:38
This should be confirmed with the Prisma Client query and SQL schema above. If the error message is better than `Invalid response data: the query result was required, but an empty Object((Weak)) was returned instead.`, this issue can be closed.

**Comment by pantharshit00** [comment] 2020-09-02 11:47
![image](https://user-images.githubusercontent.com/22195362/91977348-2c96ed80-ed40-11ea-912f-5bc8a37176a4.png)

We throw a much better error message now with reference to the column which exceeded the value.

I think we can close this.

**Closed by pantharshit00** 2020-09-02 11:47 UTC
Labels: bug/1-repro-available, kind/bug, status/needs-action, team/support, topic: errors, topic: test-utils

**Comment by eemmiillyy** [comment] 2020-09-02 12:07
<img width="878" alt="Screen Shot 2020-09-02 at 2 04 57 PM" src="https://user-images.githubusercontent.com/55739812/91979034-68708980-ed25-11ea-8792-79abd1341835.png">

I can also confirm that the error message was improved and that it makes sense to close this.

**Comment by chanlito** [comment] 2020-09-03 09:02
@eemmiillyy which version of prisma has this improved error message? It really hard to see what's going wrong right now when getting this error ` Invalid response data: the query result was required, but an empty Object((Weak)) was returned instead.`

**Comment by pantharshit00** [comment] 2020-09-03 10:48
@chanlito I tested this with version 2.6


Please make sure you ran `prisma generate` after upgrading

**Comment by chanlito** [comment] 2020-09-10 08:19
BTW @janpio I'm still getting this error `Error: Invalid response data: the query result was required, but an empty Object((Weak)) was returned instead.` 

I don't see any improved error message after upgrading to 2.6.1. 

Just this generic one which is very hard to figure out wants going wrong.

**Comment by pantharshit00** [comment] 2020-09-10 09:55
@chanlito Please open a new issue with a minimal reproduction. We can't triage this without a reproduction.

**Comment by chanlito** [comment] 2020-09-11 04:06
Hi @pantharshit00 it's really hard to create a reproduction, some parts of our application is still using Prisma 1 along side Prisma 2. 

Do you think this might be the cause of issue https://github.com/prisma/prisma-engines/issues/878 ? 

Maybe Prisma 2 trying to create a record with char(30) into a char(25) ?

**Comment by janpio** [comment] 2020-09-11 07:42
Yes, that can be the cause for errors. We have a guide how you update (and can keep using Prisma 1) here: https://www.prisma.io/docs/guides/upgrade-guides/upgrade-from-prisma-1/upgrading-the-prisma-layer/

**Comment by janpio** [comment] 2020-09-11 17:51
I created a test which tries to write a 30 character string into a `varchar(25)` field:

```
Invalid `prisma.foo.create()` invocation in
/home/runner/work/prisma/prisma/src/packages/cli/src/__tests__/integrate.mysql.test.ts:2219:32


  The provided value for the column is too long for the column's type. Column: p1_cuid
      at PrismaClientFetcher.request (tmp-mysql/src/runtime/getPrismaClient.ts:1181:15)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (internal/process/task_queues.js:97:5)
```
https://github.com/prisma/prisma/pull/3590

So what ever you are seeing is not caused by that @chanlito - so please definitely create a new issue at https://github.com/prisma/prisma/issues/new so we can investigate this. Thanks!

**Comment by eemmiillyy** [comment] 2020-09-23 10:11
Integration tests have been added for these with (https://github.com/prisma/prisma/pull/3683) in (https://github.com/prisma/prisma/commit/cd8361cf5a1e4c8786f40075db9888e188e701c1#diff-6e4bbddeca93b81ae24c82eaef9bbf5e)
