### ISSUE TITLE
Introspection: `byte index 1 is out of bounds of ''`

### ISSUE THREAD

**Issue by janpio** [prisma/prisma#3126] opened 2020-07-24 09:20 UTC
Command: `prisma introspect`
Version: `2.3.0`
Binary Version: `e11114fa1ea826f9e7b4fa1ced34e78892fe8e0e`
Report: https://prisma-errors.netlify.app/report/9256 
OS: `x64 linux 4.15.0-88-generic`

JS Stacktrace:
```
Error: [/rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7/src/libcore/str/mod.rs:1920:47] byte index 1 is out of bounds of ``
    at IntrospectionEngine.<anonymous> (/home/.../Desktop/.../apps/api-server/node_modules/@prisma/cli/build/index.js:2:1768173)
    at Generator.throw (<anonymous>)
    at rejected (/home/.../Desktop/.../apps/api-server/node_modules/@prisma/cli/build/index.js:2:1765186)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

Rust Stacktrace:
```
   0: user_facing_errors::Error::new_in_panic_hook
   1: user_facing_errors::panic_hook::set_panic_hook::{{closure}}
   2: std::panicking::rust_panic_with_hook
             at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7/src/libstd/panicking.rs:515
   3: rust_begin_unwind
             at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7/src/libstd/panicking.rs:419
   4: core::panicking::panic_fmt
             at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7/src/libcore/panicking.rs:111
   5: core::str::slice_error_fail
   6: core::str::traits::<impl core::slice::SliceIndex<str> for core::ops::range::Range<usize>>::index::{{closure}}
   7: sql_schema_describer::mysql::unescape_and_unquote_default_string
   8: <sql_schema_describer::mysql::SqlSchemaDescriber as sql_schema_describer::SqlSchemaDescriberBackend>::describe::__describe::{{closure}}
   9: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  10: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  11: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  12: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  13: <futures_util::compat::compat03as01::Compat<Fut> as futures::future::Future>::poll
  14: <futures::future::map::Map<A,F> as futures::future::Future>::poll
  15: <futures::future::either::Either<A,B> as futures::future::Future>::poll
  16: <futures::future::lazy::Lazy<F,R> as futures::future::Future>::poll
  17: futures::future::chain::Chain<A,B,C>::poll
  18: <futures::future::then::Then<A,B,F> as futures::future::Future>::poll
  19: <futures::future::map::Map<A,F> as futures::future::Future>::poll
  20: <futures::future::either::Either<A,B> as futures::future::Future>::poll
  21: <futures::future::map::Map<A,F> as futures::future::Future>::poll
  22: futures::task_impl::std::set
  23: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  24: tokio::runtime::enter::Enter::block_on
  25: tokio::runtime::context::enter
  26: tokio::runtime::handle::Handle::enter
  27: introspection_engine::main
  28: std::rt::lang_start::{{closure}}
  29: std::rt::lang_start_internal::{{closure}}
             at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7/src/libstd/rt.rs:52
      std::panicking::try::do_call
             at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7/src/libstd/panicking.rs:331
      std::panicking::try
             at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7/src/libstd/panicking.rs:274
      std::panic::catch_unwind
             at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7/src/libstd/panic.rs:394
      std::rt::lang_start_internal
             at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7/src/libstd/rt.rs:51
  30: main
  31: __libc_start_main
  32: <unknown>

```

**Comment by janpio** [comment] 2020-07-24 09:21
Further reports of similar errors with slightly different Rust Stacktrace:

```
   0: backtrace::backtrace::trace
   1: backtrace::capture::Backtrace::new
   2: user_facing_errors::Error::new_in_panic_hook
   3: user_facing_errors::panic_hook::set_panic_hook::{{closure}}
   4: std::panicking::rust_panic_with_hook
   5: _rust_begin_unwind
   6: core::panicking::panic_fmt
   7: core::str::slice_error_fail
   8: core::str::traits::<impl core::slice::SliceIndex<str> for core::ops::range::Range<usize>>::index::{{closure}}
   9: sql_schema_describer::mysql::unescape_and_unquote_default_string
  10: <sql_schema_describer::mysql::SqlSchemaDescriber as sql_schema_describer::SqlSchemaDescriberBackend>::describe::__describe::{{closure}}
  11: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  12: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  13: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  14: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  15: <futures_util::compat::compat03as01::Compat<Fut> as futures::future::Future>::poll
  16: <futures::future::map::Map<A,F> as futures::future::Future>::poll
  17: <futures::future::either::Either<A,B> as futures::future::Future>::poll
  18: futures::future::chain::Chain<A,B,C>::poll
  19: <futures::future::then::Then<A,B,F> as futures::future::Future>::poll
  20: <futures::future::map::Map<A,F> as futures::future::Future>::poll
  21: <futures::future::either::Either<A,B> as futures::future::Future>::poll
  22: <futures::future::map::Map<A,F> as futures::future::Future>::poll
  23: futures::task_impl::std::set
  24: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  25: tokio::runtime::enter::Enter::block_on
  26: tokio::runtime::context::enter
  27: tokio::runtime::handle::Handle::enter
  28: introspection_engine::main
  29: std::rt::lang_start::{{closure}}
  30: std::rt::lang_start_internal
  31: _main

```

https://prisma-errors.netlify.app/report/9259
https://prisma-errors.netlify.app/report/8865

**Comment by divyenduz** [comment] 2020-07-27 08:28
A related issue in migrate: https://github.com/prisma/migrate/issues/510

**Comment by pantharshit00** [comment] 2020-08-05 21:46
@divyenduz I think the issue you mentioned is unrelated as the other command is using migration engine as far as I know they don't use the same code. 

I was also unable to reproduce the other issue anyways.

Now, this is almost I will say impossible to reproduce with the error report. We have no schema as this was introspection failure and we don't collect a database. We also can't contact the user which submitted the report as those are anonymous(this is a good this :) )

I am not sure how I can move forward here. Maybe someone from backend can inspect the stacktrace.

**Comment by divyenduz** [comment] 2020-08-05 23:05
@pantharshit00 https://github.com/prisma/prisma/issues/3095#issuecomment-665596987 

Can you please try it with this specific version of MariaDB?

**Comment by pantharshit00** [comment] 2020-08-07 11:59
@divyenduz I am unable to reproduce it. See https://github.com/prisma/migrate/issues/510#issuecomment-670480085

**Comment by janpio** [comment] 2020-09-11 20:15
Many more reports for this from one user on 2.6.2:



Command: `prisma introspect`
Version: `2.6.2`
Binary Version: `6a8054bb549e4cc23f157b0010cb2e95cb2637fb`
Report: https://prisma-errors.netlify.app/report/11244 
OS: `x64 linux 4.19.79-microsoft-standard`

JS Stacktrace:
```
Error: [/rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9/src/libcore/str/mod.rs:1942:47] byte index 1 is out of bounds of ``
    at IntrospectionEngine.<anonymous> (/mnt/e/.../prisma-backend/node_modules/@prisma/cli/build/index.js:2:1828886)
    at Generator.throw (<anonymous>)
    at rejected (/mnt/e/.../prisma-backend/node_modules/@prisma/cli/build/index.js:2:1825889)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

Rust Stacktrace:
```
   0: user_facing_errors::Error::new_in_panic_hook
   1: user_facing_errors::panic_hook::set_panic_hook::{{closure}}
   2: std::panicking::rust_panic_with_hook
             at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9/src/libstd/panicking.rs:530
   3: rust_begin_unwind
             at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9/src/libstd/panicking.rs:437
   4: core::panicking::panic_fmt
             at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9/src/libcore/panicking.rs:85
   5: core::str::slice_error_fail
   6: core::str::traits::<impl core::slice::SliceIndex<str> for core::ops::range::Range<usize>>::index::{{closure}}
   7: sql_schema_describer::mysql::unescape_and_unquote_default_string
   8: <sql_schema_describer::mysql::SqlSchemaDescriber as sql_schema_describer::SqlSchemaDescriberBackend>::describe::__describe::{{closure}}
   9: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  10: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  11: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  12: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  13: <futures_util::compat::compat03as01::Compat<Fut> as futures::future::Future>::poll
  14: <futures::future::map::Map<A,F> as futures::future::Future>::poll
  15: <futures::future::either::Either<A,B> as futures::future::Future>::poll
  16: futures::future::chain::Chain<A,B,C>::poll
  17: <futures::future::then::Then<A,B,F> as futures::future::Future>::poll
  18: <futures::future::map::Map<A,F> as futures::future::Future>::poll
  19: <futures::future::either::Either<A,B> as futures::future::Future>::poll
  20: <futures::future::map::Map<A,F> as futures::future::Future>::poll
  21: futures::task_impl::std::set
  22: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  23: tokio::runtime::enter::Enter::block_on
  24: tokio::runtime::context::enter
  25: tokio::runtime::handle::Handle::enter
  26: introspection_engine::main
  27: std::rt::lang_start::{{closure}}
  28: std::rt::lang_start_internal::{{closure}}
             at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9/src/libstd/rt.rs:52
      std::panicking::try::do_call
             at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9/src/libstd/panicking.rs:348
      std::panicking::try
             at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9/src/libstd/panicking.rs:325
      std::panic::catch_unwind
             at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9/src/libstd/panic.rs:394
      std::rt::lang_start_internal
             at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9/src/libstd/rt.rs:51
  29: main
  30: __libc_start_main
  31: <unknown>

```

**Comment by do4gr** [comment] 2020-11-10 16:20
We recently implemented a fix for default value parsing on MySQL variants. Since then we cannot reproduce this anymore. I am closing this therefore.

**Closed by do4gr** 2020-11-10 16:20 UTC
Labels: 2.3, bug/0-needs-info, kind/bug, team/engines, topic: introspection
