### ISSUE TITLE
`libssl.so.1.1`: cannot open shared object file

### ISSUE THREAD

**Issue by mael-queau** [prisma/prisma#15505] opened 2022-09-24 14:17 UTC
### Bug description

Hi,

I'm having an issue that has already been described in other (closed) issues, but there isn't a solution anywhere for it.
Issue #13717 focuses on node being installed via `snap`, but this isn't the case, as you can see here:

```sh
$ whereis node
node: /home/mael/.local/share/fnm/node-versions/v18.9.1/installation/bin/node
```

```sh
$ whereis openssl
openssl: /usr/bin/openssl /home/linuxbrew/.linuxbrew/bin/openssl /usr/share/man/man1/openssl.1ssl.gz
```

Indeed, node isn't installed through `snap` but through `fnm`, an dI have tested various means of installing it (`nvm` for instance) to no avail.

[This comment](https://github.com/prisma/prisma/issues/13717#issuecomment-1186992358) has the same issue as me, but sadly didn't get an answer either.

So, here is my output trying to run `prisma generate` (it is in the `pnpm prepare` script, so automatically run by `pnpm install`):

```
 ~/Documents/Projects/roboct0 > pnpm i          
  corepack Reusing pnpm@7.12.1 +0ms
Scope: all 2 workspace projects
Lockfile is up to date, resolution step is skipped
Already up to date
packages/api prepare$ prisma generate
│ 2022-09-24T14:15:16.813Z prisma:engines  binaries to download libquery-engine, migration-engine, introspection-engine, prisma-fmt
│ 2022-09-24T14:15:17.144Z prisma:loadEnv  project root found at /home/mael/Documents/Projects/roboct0/packages/api/package.json
│ 2022-09-24T14:15:17.158Z prisma:tryLoadEnv  Environment variables loaded from /home/mael/Documents/Projects/roboct0/packages/api/.env
│ Environment variables loaded from .env
│ Prisma schema loaded from prisma/schema.prisma
│ 2022-09-24T14:15:17.361Z prisma:getConfig  Using CLI Query Engine (Node-API Library) at: /home/mael/Documents/Projects/roboct0/node_modules/.pnpm/prisma@4.3.1/node_modules/prisma/libquery_engi
│ 2022-09-24T14:15:17.362Z prisma:getConfig  error of type "connection-error" in getConfigNodeAPI:
│  {
│   reason: 'Unable to establish a connection to query-engine-node-api library. It seems there is a problem with your OpenSSL installation!',
│   error: Error: Unable to require(`/home/mael/Documents/Projects/roboct0/node_modules/.pnpm/prisma@4.3.1/node_modules/prisma/libquery_engine-debian-openssl-1.1.x.so.node`)
│    libssl.so.1.1: cannot open shared object file: No such file or directory
│       at load (/home/mael/Documents/Projects/roboct0/node_modules/.pnpm/prisma@4.3.1/node_modules/prisma/build/index.js:89300:11)
│       at error2 (/home/mael/Documents/Projects/roboct0/node_modules/.pnpm/prisma@4.3.1/node_modules/prisma/build/index.js:89366:13)
│       at tryCatch (/home/mael/Documents/Projects/roboct0/node_modules/.pnpm/prisma@4.3.1/node_modules/prisma/build/index.js:88832:19)
│       at loadNodeAPILibrary (/home/mael/Documents/Projects/roboct0/node_modules/.pnpm/prisma@4.3.1/node_modules/prisma/build/index.js:89365:5)
│       at getConfigNodeAPI (/home/mael/Documents/Projects/roboct0/node_modules/.pnpm/prisma@4.3.1/node_modules/prisma/build/index.js:89464:5)
│       at async getConfig (/home/mael/Documents/Projects/roboct0/node_modules/.pnpm/prisma@4.3.1/node_modules/prisma/build/index.js:89445:16)
│       at async getGenerators (/home/mael/Documents/Projects/roboct0/node_modules/.pnpm/prisma@4.3.1/node_modules/prisma/build/index.js:91517:18)
│       at async _Generate.parse (/home/mael/Documents/Projects/roboct0/node_modules/.pnpm/prisma@4.3.1/node_modules/prisma/build/index.js:96766:20)
│       at async main (/home/mael/Documents/Projects/roboct0/node_modules/.pnpm/prisma@4.3.1/node_modules/prisma/build/index.js:98499:18)
│ }
│ Error: Error: Unable to establish a connection to query-engine-node-api library. It seems there is a problem with your OpenSSL installation!
│ Details: Unable to require(`/home/mael/Documents/Projects/roboct0/node_modules/.pnpm/prisma@4.3.1/node_modules/prisma/libquery_engine-debian-openssl-1.1.x.so.node`)
│  libssl.so.1.1: cannot open shared object file: No such file or directory
│ [Context: getConfig]
│ Prisma CLI Version : 4.3.1
│     at /home/mael/Documents/Projects/roboct0/node_modules/.pnpm/prisma@4.3.1/node_modules/prisma/build/index.js:89533:12
│     at O.run (/home/mael/Documents/Projects/roboct0/node_modules/.pnpm/prisma@4.3.1/node_modules/prisma/build/index.js:86444:12)
│     at O.otherwise (/home/mael/Documents/Projects/roboct0/node_modules/.pnpm/prisma@4.3.1/node_modules/prisma/build/index.js:86421:115)
│     at getConfigNodeAPI (/home/mael/Documents/Projects/roboct0/node_modules/.pnpm/prisma@4.3.1/node_modules/prisma/build/index.js:89531:6)
│     at async getConfig (/home/mael/Documents/Projects/roboct0/node_modules/.pnpm/prisma@4.3.1/node_modules/prisma/build/index.js:89445:16)
│     at async getGenerators (/home/mael/Documents/Projects/roboct0/node_modules/.pnpm/prisma@4.3.1/node_modules/prisma/build/index.js:91517:18)
│     at async _Generate.parse (/home/mael/Documents/Projects/roboct0/node_modules/.pnpm/prisma@4.3.1/node_modules/prisma/build/index.js:96766:20)
│     at async main (/home/mael/Documents/Projects/roboct0/node_modules/.pnpm/prisma@4.3.1/node_modules/prisma/build/index.js:98499:18)
└─ Failed in 868ms
 ELIFECYCLE  Command failed with exit code 1.
```

I don't know what to do, I only just switched from Windows where everything was working just fine to Ubuntu and I can't seem to be able to use Prisma at all now. Of course, I didn't copy and paste anything, I used `git clone` to get my project in order to work on it on my newly installed Linux distro.

### How to reproduce

1. Do a fresh install of Ubuntu 22.04.1
2. Create a project using Prisma
3. Try to generate a schema

### Expected behavior

I expected it to generate the prisma client without a hitch, as it always had up until that point.

### Prisma information

```prisma
// This is your Prisma schema file,
// learn more about it in the docs: https://pris.ly/d/prisma-schema

generator client {
  provider        = "prisma-client-js"
  previewFeatures = ["fullTextSearch"]
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}
```

```ts
import { PrismaClient } from "@prisma/client";
const prisma = new PrismaClient();
```

### Environment & setup

- OS: Ubuntu 22.04.1 LTS
- Database: PostgreSQL
- Node.js version: v18.9.1

### Prisma Version

```
Error: Unable to require(`/home/mael/Documents/Projects/roboct0/node_modules/.pnpm/@prisma+engines@4.3.1/node_modules/@prisma/engines/libquery_engine-debian-openssl-1.1.x.so.node`)
 libssl.so.1.1: cannot open shared object file: No such file or directory
    at load (/home/mael/Documents/Projects/roboct0/node_modules/.pnpm/prisma@4.3.1/node_modules/prisma/build/index.js:89300:11)
    at getEngineVersion (/home/mael/Documents/Projects/roboct0/node_modules/.pnpm/prisma@4.3.1/node_modules/prisma/build/index.js:90023:16)
Error: Command failed with exit code 127: /home/mael/Documents/Projects/roboct0/node_modules/.pnpm/@prisma+engines@4.3.1/node_modules/@prisma/engines/migration-engine-debian-openssl-1.1.x --version
/home/mael/Documents/Projects/roboct0/node_modules/.pnpm/@prisma+engines@4.3.1/node_modules/@prisma/engines/migration-engine-debian-openssl-1.1.x: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory
    at makeError (/home/mael/Documents/Projects/roboct0/node_modules/.pnpm/prisma@4.3.1/node_modules/prisma/build/index.js:3641:18)
    at handlePromise (/home/mael/Documents/Projects/roboct0/node_modules/.pnpm/prisma@4.3.1/node_modules/prisma/build/index.js:4409:33)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async getEngineVersion (/home/mael/Documents/Projects/roboct0/node_modules/.pnpm/prisma@4.3.1/node_modules/prisma/build/index.js:90026:20) {
  shortMessage: 'Command failed with exit code 127: /home/mael/Documents/Projects/roboct0/node_modules/.pnpm/@prisma+engines@4.3.1/node_modules/@prisma/engines/migration-engine-debian-openssl-1.1.x --version',
  command: '/home/mael/Documents/Projects/roboct0/node_modules/.pnpm/@prisma+engines@4.3.1/node_modules/@prisma/engines/migration-engine-debian-openssl-1.1.x --version',
  escapedCommand: '"/home/mael/Documents/Projects/roboct0/node_modules/.pnpm/@prisma+engines@4.3.1/node_modules/@prisma/engines/migration-engine-debian-openssl-1.1.x" --version',
  exitCode: 127,
  signal: undefined,
  signalDescription: undefined,
  stdout: '',
  stderr: '/home/mael/Documents/Projects/roboct0/node_modules/.pnpm/@prisma+engines@4.3.1/node_modules/@prisma/engines/migration-engine-debian-openssl-1.1.x: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory',
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false
}
Error: Command failed with exit code 127: /home/mael/Documents/Projects/roboct0/node_modules/.pnpm/@prisma+engines@4.3.1/node_modules/@prisma/engines/introspection-engine-debian-openssl-1.1.x --version
/home/mael/Documents/Projects/roboct0/node_modules/.pnpm/@prisma+engines@4.3.1/node_modules/@prisma/engines/introspection-engine-debian-openssl-1.1.x: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory
    at makeError (/home/mael/Documents/Projects/roboct0/node_modules/.pnpm/prisma@4.3.1/node_modules/prisma/build/index.js:3641:18)
    at handlePromise (/home/mael/Documents/Projects/roboct0/node_modules/.pnpm/prisma@4.3.1/node_modules/prisma/build/index.js:4409:33)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async getEngineVersion (/home/mael/Documents/Projects/roboct0/node_modules/.pnpm/prisma@4.3.1/node_modules/prisma/build/index.js:90026:20) {
  shortMessage: 'Command failed with exit code 127: /home/mael/Documents/Projects/roboct0/node_modules/.pnpm/@prisma+engines@4.3.1/node_modules/@prisma/engines/introspection-engine-debian-openssl-1.1.x --version',
  command: '/home/mael/Documents/Projects/roboct0/node_modules/.pnpm/@prisma+engines@4.3.1/node_modules/@prisma/engines/introspection-engine-debian-openssl-1.1.x --version',
  escapedCommand: '"/home/mael/Documents/Projects/roboct0/node_modules/.pnpm/@prisma+engines@4.3.1/node_modules/@prisma/engines/introspection-engine-debian-openssl-1.1.x" --version',
  exitCode: 127,
  signal: undefined,
  signalDescription: undefined,
  stdout: '',
  stderr: '/home/mael/Documents/Projects/roboct0/node_modules/.pnpm/@prisma+engines@4.3.1/node_modules/@prisma/engines/introspection-engine-debian-openssl-1.1.x: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory',
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false
}
prisma                  : 4.3.1
@prisma/client          : 4.3.1
Current platform        : debian-openssl-1.1.x
Query Engine (Node-API) : E_CANNOT_RESOLVE_VERSION (at ../../node_modules/.pnpm/@prisma+engines@4.3.1/node_modules/@prisma/engines/libquery_engine-debian-openssl-1.1.x.so.node)
Migration Engine        : E_CANNOT_RESOLVE_VERSION (at ../../node_modules/.pnpm/@prisma+engines@4.3.1/node_modules/@prisma/engines/migration-engine-debian-openssl-1.1.x)
Introspection Engine    : E_CANNOT_RESOLVE_VERSION (at ../../node_modules/.pnpm/@prisma+engines@4.3.1/node_modules/@prisma/engines/introspection-engine-debian-openssl-1.1.x)
Format Binary           : prisma-fmt c875e43600dfe042452e0b868f7a48b817b9640b (at ../../node_modules/.pnpm/@prisma+engines@4.3.1/node_modules/@prisma/engines/prisma-fmt-debian-openssl-1.1.x)
Format Wasm             : @prisma/prisma-fmt-wasm 4.3.0-32.c875e43600dfe042452e0b868f7a48b817b9640b
Default Engines Hash    : c875e43600dfe042452e0b868f7a48b817b9640b
Studio                  : 0.473.0
```

**Comment by janpio** [comment] 2022-09-24 18:22
Please try to create a new project with `npm init` and then `npm install prisma && npx prisma init` (Note: Try to use Npm, not Pnpm) and see if that works. That let's us narrow the reason why things could not work for you.

**Comment by mael-queau** [comment] 2022-09-26 23:11
Of course, here it is:
![image](https://user-images.githubusercontent.com/100228262/192396505-ebfc23e5-daac-4b36-b244-62279143c18d.png)

As you can see, the exact same thing happens with npm and a freshly initialized project. I have a done a complete reinstallation of Ubuntu since opening this issue, so I don't believe that it could be linked to any configuration of conflicting software, for example.

**Comment by mael-queau** [comment] 2022-09-28 22:03
If there is anything I can do, please don't hesitate to ask!

**Comment by janpio** [comment] 2022-09-29 17:45
What is your `npx prisma -v` output?

Obviously somehow our engine or our logic can not detect your OpenSSL installation. What version of OpenSSL is actually installed?

**Comment by mael-queau** [comment] 2022-09-30 15:43
Here it is:

```sh
╭─ ~/Projects/_playground/TS/repro ─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────── ✔ ╱ 33s ╱ 17:40:53 
╰─ npx prisma -v
Environment variables loaded from .env
Error: Unable to require(`/home/mael/Projects/_playground/TS/repro/node_modules/@prisma/engines/libquery_engine-debian-openssl-1.1.x.so.node`)
 libssl.so.1.1: cannot open shared object file: No such file or directory
    at load (/home/mael/Projects/_playground/TS/repro/node_modules/prisma/build/index.js:89013:11)
    at getEngineVersion (/home/mael/Projects/_playground/TS/repro/node_modules/prisma/build/index.js:89736:16)
Error: Command failed with exit code 127: /home/mael/Projects/_playground/TS/repro/node_modules/@prisma/engines/migration-engine-debian-openssl-1.1.x --version
/home/mael/Projects/_playground/TS/repro/node_modules/@prisma/engines/migration-engine-debian-openssl-1.1.x: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory
    at makeError (/home/mael/Projects/_playground/TS/repro/node_modules/prisma/build/index.js:3641:18)
    at handlePromise (/home/mael/Projects/_playground/TS/repro/node_modules/prisma/build/index.js:4409:33)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async getEngineVersion (/home/mael/Projects/_playground/TS/repro/node_modules/prisma/build/index.js:89739:20) {
  shortMessage: 'Command failed with exit code 127: /home/mael/Projects/_playground/TS/repro/node_modules/@prisma/engines/migration-engine-debian-openssl-1.1.x --version',
  command: '/home/mael/Projects/_playground/TS/repro/node_modules/@prisma/engines/migration-engine-debian-openssl-1.1.x --version',
  escapedCommand: '"/home/mael/Projects/_playground/TS/repro/node_modules/@prisma/engines/migration-engine-debian-openssl-1.1.x" --version',
  exitCode: 127,
  signal: undefined,
  signalDescription: undefined,
  stdout: '',
  stderr: '/home/mael/Projects/_playground/TS/repro/node_modules/@prisma/engines/migration-engine-debian-openssl-1.1.x: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory',
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false
}
Error: Command failed with exit code 127: /home/mael/Projects/_playground/TS/repro/node_modules/@prisma/engines/introspection-engine-debian-openssl-1.1.x --version
/home/mael/Projects/_playground/TS/repro/node_modules/@prisma/engines/introspection-engine-debian-openssl-1.1.x: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory
    at makeError (/home/mael/Projects/_playground/TS/repro/node_modules/prisma/build/index.js:3641:18)
    at handlePromise (/home/mael/Projects/_playground/TS/repro/node_modules/prisma/build/index.js:4409:33)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async getEngineVersion (/home/mael/Projects/_playground/TS/repro/node_modules/prisma/build/index.js:89739:20) {
  shortMessage: 'Command failed with exit code 127: /home/mael/Projects/_playground/TS/repro/node_modules/@prisma/engines/introspection-engine-debian-openssl-1.1.x --version',
  command: '/home/mael/Projects/_playground/TS/repro/node_modules/@prisma/engines/introspection-engine-debian-openssl-1.1.x --version',
  escapedCommand: '"/home/mael/Projects/_playground/TS/repro/node_modules/@prisma/engines/introspection-engine-debian-openssl-1.1.x" --version',
  exitCode: 127,
  signal: undefined,
  signalDescription: undefined,
  stdout: '',
  stderr: '/home/mael/Projects/_playground/TS/repro/node_modules/@prisma/engines/introspection-engine-debian-openssl-1.1.x: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory',
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false
}
prisma                  : 4.4.0
@prisma/client          : 4.4.0
Current platform        : debian-openssl-1.1.x
Query Engine (Node-API) : E_CANNOT_RESOLVE_VERSION (at node_modules/@prisma/engines/libquery_engine-debian-openssl-1.1.x.so.node)
Migration Engine        : E_CANNOT_RESOLVE_VERSION (at node_modules/@prisma/engines/migration-engine-debian-openssl-1.1.x)
Introspection Engine    : E_CANNOT_RESOLVE_VERSION (at node_modules/@prisma/engines/introspection-engine-debian-openssl-1.1.x)
Format Binary           : prisma-fmt f352a33b70356f46311da8b00d83386dd9f145d6 (at node_modules/@prisma/engines/prisma-fmt-debian-openssl-1.1.x)
Format Wasm             : @prisma/prisma-fmt-wasm 4.4.0-66.f352a33b70356f46311da8b00d83386dd9f145d6
Default Engines Hash    : f352a33b70356f46311da8b00d83386dd9f145d6
Studio                  : 0.474.0
```

**Comment by mael-queau** [comment] 2022-09-30 15:46
Additionally, here is openssl's version on my machine:
```sh
╭─ ~/Projects/_playground/TS/repro ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────── ✔ ╱ 17:44:40 
╰─ openssl version
OpenSSL 1.1.1q  5 Jul 2022
╭─ ~/Projects/_playground/TS/repro ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────── ✔ ╱ 17:45:18 
╰─ whereis openssl
openssl: /usr/bin/openssl /home/linuxbrew/.linuxbrew/bin/openssl /usr/share/man/man1/openssl.1ssl.gz
```

**Comment by mael-queau** [comment] 2022-10-08 17:37
Well, the switch to Fedora 36 has been made, and the issue is still here, exactly the same as before...

**Comment by mael-queau** [comment] 2022-10-11 13:27
Well, after looking around for some kind of solution and rebuilding openssl from source a couple of times over, I found the solution in [this Reddit comment](https://www.reddit.com/r/Fedora/comments/uy1wxr/rust_libssl_issue/) (for Fedora at least). I don't know much about Rust but this seems to be related to it, so I don't know if I can close this issue or not. I'll leave it to you all :)
Thanks for the help either way !

**Comment by greendesertsnow** [comment] 2022-10-13 16:32
> npx prisma -v

I have the same issue with Windows too.

`Environment variables loaded from .env
Error: Unable to require(`C:\Users\pazar\Projects\vocabulary\node_modules\@prisma\engines\query_engine-windows.dll.node`)
 The specified module could not be found.
\\?\C:\Users\pazar\Projects\vocabulary\node_modules\@prisma\engines\query_engine-windows.dll.node
    at load (C:\Users\pazar\Projects\vocabulary\node_modules\prisma\build\index.js:89013:11)
    at getEngineVersion (C:\Users\pazar\Projects\vocabulary\node_modules\prisma\build\index.js:89736:16)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
Error: Command failed with exit code 3221225781: C:\Users\pazar\Projects\vocabulary\node_modules\@prisma\engines\migration-engine-windows.exe --version
    at makeError (C:\Users\pazar\Projects\vocabulary\node_modules\prisma\build\index.js:3641:18)
    at handlePromise (C:\Users\pazar\Projects\vocabulary\node_modules\prisma\build\index.js:4409:33)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async getEngineVersion (C:\Users\pazar\Projects\vocabulary\node_modules\prisma\build\index.js:89739:20) {
  shortMessage: 'Command failed with exit code 3221225781: C:\\Users\\pazar\\Projects\\vocabulary\\node_modules\\@prisma\\engines\\migration-engine-windows.exe --version',     
  command: 'C:\\Users\\pazar\\Projects\\vocabulary\\node_modules\\@prisma\\engines\\migration-engine-windows.exe --version',
  escapedCommand: '"C:\\Users\\pazar\\Projects\\vocabulary\\node_modules\\@prisma\\engines\\migration-engine-windows.exe" --version',
  exitCode: 3221225781,
  signal: undefined,
  signalDescription: undefined,
  stdout: '',
  stderr: '',
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false
}
prisma                  : 4.4.0
@prisma/client          : 4.4.0
Current platform        : windows
Query Engine (Node-API) : E_CANNOT_RESOLVE_VERSION (at node_modules\@prisma\engines\query_engine-windows.dll.node)
Migration Engine        : E_CANNOT_RESOLVE_VERSION (at node_modules\@prisma\engines\migration-engine-windows.exe)
Introspection Engine    : E_CANNOT_RESOLVE_VERSION (at node_modules\@prisma\engines\introspection-engine-windows.exe)
Format Binary           : E_CANNOT_RESOLVE_VERSION (at node_modules\@prisma\engines\prisma-fmt-windows.exe)
Format Wasm             : @prisma/prisma-fmt-wasm 4.4.0-66.f352a33b70356f46311da8b00d83386dd9f145d6
Default Engines Hash    : f352a33b70356f46311da8b00d83386dd9f145d6
Studio                  : 0.474.0`

**Comment by janpio** [comment] 2022-10-13 16:48
Yours is different @greendesertsnow , have a look at these issues: https://github.com/prisma/prisma/issues?q=is%3Aissue+is%3Aopen+3221225781

**Comment by John-Dennehy** [comment] 2022-10-23 15:24
Getting similar errors as @mael-queau on PopOs 22.04 trining to pnpm install:
``` pnpm install
Lockfile is up to date, resolution step is skipped
Already up to date

> template@0.1.0 postinstall /home/jd/Projects/zlist
> prisma generate

Environment variables loaded from .env
Prisma schema loaded from prisma/schema.prisma
Error: Unable to establish a connection to query-engine-node-api library. It seems there is a problem with your OpenSSL installation!
Details: Unable to require(`/home/jd/Projects/zlist/node_modules/.pnpm/prisma@4.5.0/node_modules/prisma/libquery_engine-debian-openssl-1
.1.x.so.node`)
 libssl.so.1.1: cannot open shared object file: No such file or directory
[Context: getConfig]

Prisma CLI Version : 4.5.0
 ELIFECYCLE  Command failed with exit code 1.
```


`which openssl` returns: `/home/linuxbrew/.linuxbrew/bin/openssl`

`whereis openssl` returns: `openssl: /usr/bin/openssl /home/linuxbrew/.linuxbrew/bin/openssl /usr/share/man/man1/openssl.1ssl.gz
` 

`npx prisma -v` returns:
```Environment variables loaded from .env
Error: Unable to require(`/home/jd/Projects/zlist/node_modules/.pnpm/@prisma+engines@4.5.0/node_modules/@prisma/engines/libquery_engine-
debian-openssl-1.1.x.so.node`)
 libssl.so.1.1: cannot open shared object file: No such file or directory
    at load (/home/jd/Projects/zlist/node_modules/.pnpm/prisma@4.5.0/node_modules/prisma/build/index.js:89179:11)
    at getEngineVersion (/home/jd/Projects/zlist/node_modules/.pnpm/prisma@4.5.0/node_modules/prisma/build/index.js:89902:16)
Error: Command failed with exit code 127: /home/jd/Projects/zlist/node_modules/.pnpm/@prisma+engines@4.5.0/node_modules/@prisma/engines/
migration-engine-debian-openssl-1.1.x --version
/home/jd/Projects/zlist/node_modules/.pnpm/@prisma+engines@4.5.0/node_modules/@prisma/engines/migration-engine-debian-openssl-1.1.x: err
or while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory
    at makeError (/home/jd/Projects/zlist/node_modules/.pnpm/prisma@4.5.0/node_modules/prisma/build/index.js:3641:18)
    at handlePromise (/home/jd/Projects/zlist/node_modules/.pnpm/prisma@4.5.0/node_modules/prisma/build/index.js:4409:33)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async getEngineVersion (/home/jd/Projects/zlist/node_modules/.pnpm/prisma@4.5.0/node_modules/prisma/build/index.js:89905:20) {
  shortMessage: 'Command failed with exit code 127: /home/jd/Projects/zlist/node_modules/.pnpm/@prisma+engines@4.5.0/node_modules/@prism
a/engines/migration-engine-debian-openssl-1.1.x --version',
  command: '/home/jd/Projects/zlist/node_modules/.pnpm/@prisma+engines@4.5.0/node_modules/@prisma/engines/migration-engine-debian-openss
l-1.1.x --version',
  escapedCommand: '"/home/jd/Projects/zlist/node_modules/.pnpm/@prisma+engines@4.5.0/node_modules/@prisma/engines/migration-engine-debia
n-openssl-1.1.x" --version',
  exitCode: 127,
  signal: undefined,
  signalDescription: undefined,
  stdout: '',
  stderr: '/home/jd/Projects/zlist/node_modules/.pnpm/@prisma+engines@4.5.0/node_modules/@prisma/engines/migration-engine-debian-openssl
-1.1.x: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory',
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false
}
Error: Command failed with exit code 127: /home/jd/Projects/zlist/node_modules/.pnpm/@prisma+engines@4.5.0/node_modules/@prisma/engines/
introspection-engine-debian-openssl-1.1.x --version
/home/jd/Projects/zlist/node_modules/.pnpm/@prisma+engines@4.5.0/node_modules/@prisma/engines/introspection-engine-debian-openssl-1.1.x:
 error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory
    at makeError (/home/jd/Projects/zlist/node_modules/.pnpm/prisma@4.5.0/node_modules/prisma/build/index.js:3641:18)
    at handlePromise (/home/jd/Projects/zlist/node_modules/.pnpm/prisma@4.5.0/node_modules/prisma/build/index.js:4409:33)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async getEngineVersion (/home/jd/Projects/zlist/node_modules/.pnpm/prisma@4.5.0/node_modules/prisma/build/index.js:89905:20) {
  shortMessage: 'Command failed with exit code 127: /home/jd/Projects/zlist/node_modules/.pnpm/@prisma+engines@4.5.0/node_modules/@prism
a/engines/introspection-engine-debian-openssl-1.1.x --version',
  command: '/home/jd/Projects/zlist/node_modules/.pnpm/@prisma+engines@4.5.0/node_modules/@prisma/engines/introspection-engine-debian-op
enssl-1.1.x --version',
  escapedCommand: '"/home/jd/Projects/zlist/node_modules/.pnpm/@prisma+engines@4.5.0/node_modules/@prisma/engines/introspection-engine-d
ebian-openssl-1.1.x" --version',
  exitCode: 127,
  signal: undefined,
  signalDescription: undefined,
  stdout: '',
  stderr: '/home/jd/Projects/zlist/node_modules/.pnpm/@prisma+engines@4.5.0/node_modules/@prisma/engines/introspection-engine-debian-ope
nssl-1.1.x: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory',
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false
}
prisma                  : 4.5.0
@prisma/client          : 4.5.0
Current platform        : debian-openssl-1.1.x
Query Engine (Node-API) : E_CANNOT_RESOLVE_VERSION (at node_modules/.pnpm/@prisma+engines@4.5.0/node_modules/@prisma/engines/libquery_en
gine-debian-openssl-1.1.x.so.node)
Migration Engine        : E_CANNOT_RESOLVE_VERSION (at node_modules/.pnpm/@prisma+engines@4.5.0/node_modules/@prisma/engines/migration-e
ngine-debian-openssl-1.1.x)
Introspection Engine    : E_CANNOT_RESOLVE_VERSION (at node_modules/.pnpm/@prisma+engines@4.5.0/node_modules/@prisma/engines/introspecti
on-engine-debian-openssl-1.1.x)
Format Binary           : prisma-fmt 0362da9eebca54d94c8ef5edd3b2e90af99ba452 (at node_modules/.pnpm/@prisma+engines@4.5.0/node_modules/
@prisma/engines/prisma-fmt-debian-openssl-1.1.x)
Format Wasm             : @prisma/prisma-fmt-wasm 4.5.0-43.0362da9eebca54d94c8ef5edd3b2e90af99ba452
Default Engines Hash    : 0362da9eebca54d94c8ef5edd3b2e90af99ba452
Studio                  : 0.476.0
```

**Comment by jakeklassen** [comment] 2022-10-29 17:10
I found [this](https://stackoverflow.com/a/73604364/1687494) setup useful on Ubuntu 22.04 on WSL 2.

```
$ mkdir $HOME/opt && cd $HOME/opt
$ wget https://www.openssl.org/source/openssl-1.1.1o.tar.gz
$ tar -zxvf openssl-1.1.1o.tar.gz
$ cd openssl-1.1.1o
$ ./config && make && make test
$ mkdir $HOME/opt/lib
$ mv $HOME/opt/openssl-1.1.1o/libcrypto.so.1.1 $HOME/opt/lib/
$ mv $HOME/opt/openssl-1.1.1o/libssl.so.1.1 $HOME/opt/lib/
```

And then

```
export LD_LIBRARY_PATH=$HOME/opt/lib:$LD_LIBRARY_PATH
```

When you need to use it.

**Comment by jkomyno** [comment] 2023-01-04 23:38
Hey @mael-queau, could you please share a reproduction of your Fedora environment where Prisma needs an explicitly installed version of `openssl` to run? Thanks.

**Comment by jkomyno** [comment] 2023-01-04 23:41
Hey @jakeklassen, for Ubuntu, no such setup should be needed as of `prisma@4.8.0`.
Here's a [Dockerfile](https://github.com/prisma/ecosystem-tests/blob/8e1eb547b78c2f5781e597838afb8d984c246c5e/docker/ubuntu-22.04-amd64-openssl-3.0.x/Dockerfile) from our docker test suite, no explicitly installed `openssl-1.1.x` is needed on Ubuntu 22.04, as Prisma is able to detect the `openssl-3.0.x` version installed in the system by default.

**Comment by NigelGreenway** [comment] 2023-03-27 16:06
I've managed to solve this issue by temporarily removing `/home/linuxbrew/.linuxbrew/bin/openssl`. This has been the main difference between my current install of Ubuntu and my previous laptop - as in, using homebrew to install applications. Once this was removed I was able to run `npx prisma generate` without any issues.

```
/etc/*release

DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=22.04
DISTRIB_CODENAME=jammy
DISTRIB_DESCRIPTION="Ubuntu 22.04.2 LTS"
PRETTY_NAME="Ubuntu 22.04.2 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.2 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
```

This was tried on Node versions 

```
v14.21.1
v16.19.1
v18.15.0
```

Hope this helps?

**Comment by aqrln** [comment] 2023-03-28 11:59
Thank you for the response and for the initial report @mael-queau! The problem should be fixed as of Prisma 4.9.0 or later, so I'm going to go ahead and close this issue. Please open a new issue if you still run into any problems.

**Closed by aqrln** 2023-03-28 11:59 UTC
Labels: bug/1-unconfirmed, kind/bug, topic: prisma generate, team/client, topic: linux, topic: openssl

**Comment by mael-queau** [comment] 2023-03-29 07:44
Thank you very much!

**Comment by paschendale** [comment] 2025-01-03 11:47
I've encountered the same problem running my Prisma instance in a Docker container.

It seems like the latest `node:*` images has been missing some OpenSSL files, so, what I did was install it mannually in the Dockerfile:

```
FROM node:lts-alpine

RUN apk add --no-cache openssl 
```

I don't know what caused this issue, but images built after mid-December are all failing, be with the alpine, bookworm or bullseye versions.

This problem won't occur in Docker `linux/arm64` containers, only on `linux/amd64`, so, Mac users that port their software to Linux servers as myself won't have this problem during development but will have them once running in a Debian-based environment.

**Comment by jdrydn** [comment] 2025-11-03 11:27
> It seems like the latest `node:*` images has been missing some OpenSSL files, so, what I did was install it mannually in the Dockerfile

Thank you for sharing @paschendale, I had a similar issue updating a project from `node:20.16-alpine` to `node:20.19-alpine` for exactly this reason, and `RUN apk add --no-cache openssl` resolved it ❤️ Worth noting I'm working with a `linux/arm64` Docker image & `ARM64` AWS ECS deployment, didn't have any problems during build but no Prisma queries worked during runtime until this was resolved.
