### ISSUE TITLE
Prisma errors in index.d.ts whenever I compile

### ISSUE THREAD

**Issue by tecshaun** [prisma/prisma#12040] opened 2022-02-25 14:53 UTC
### Bug description

While starting a new project with the latest version of every package I can't compile and get these errors:

```

[8:51:37 PM] Starting compilation in watch mode...

node_modules/.prisma/client/index.d.ts:11:33 - error TS1110: Type expected.

11   [K in keyof Tuple]: K extends `${number}` ? Tuple[K] extends PrismaPromise<infer X> ? X : UnwrapPromise<Tuple[K]> : UnwrapPromise<Tuple[K]>
                                   ~~~

node_modules/.prisma/client/index.d.ts:11:56 - error TS1005: ':' expected.

11   [K in keyof Tuple]: K extends `${number}` ? Tuple[K] extends PrismaPromise<infer X> ? X : UnwrapPromise<Tuple[K]> : UnwrapPromise<Tuple[K]>
                                                          ~~~~~~~

node_modules/.prisma/client/index.d.ts:11:87 - error TS1005: '(' expected.

11   [K in keyof Tuple]: K extends `${number}` ? Tuple[K] extends PrismaPromise<infer X> ? X : UnwrapPromise<Tuple[K]> : UnwrapPromise<Tuple[K]>
                                                                                         ~

node_modules/.prisma/client/index.d.ts:11:91 - error TS1005: ',' expected.

11   [K in keyof Tuple]: K extends `${number}` ? Tuple[K] extends PrismaPromise<infer X> ? X : UnwrapPromise<Tuple[K]> : UnwrapPromise<Tuple[K]>
                                                                                             ~

node_modules/.prisma/client/index.d.ts:11:117 - error TS1005: '(' expected.

11   [K in keyof Tuple]: K extends `${number}` ? Tuple[K] extends PrismaPromise<infer X> ? X : UnwrapPromise<Tuple[K]> : UnwrapPromise<Tuple[K]>
                                                                                                                       ~

node_modules/.prisma/client/index.d.ts:12:1 - error TS1005: '(' expected.

12 };
   ~

node_modules/.prisma/client/index.d.ts:12:2 - error TS1005: ')' expected.

12 };
    ~

node_modules/.prisma/client/index.d.ts:620:60 - error TS1110: Type expected.

620   type ExcludeUnderscoreKeys<T extends string> = T extends `_${string}` ? never : T
                                                               ~~~~

node_modules/.prisma/client/index.d.ts:1371:15 - error TS1110: Type expected.

1371             ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
                   ~~~~~~~~~~~~~~~~~

node_modules/.prisma/client/index.d.ts:1372:13 - error TS1128: Declaration or statement expected.

1372             : [
                 ~

node_modules/.prisma/client/index.d.ts:1379:7 - error TS1128: Declaration or statement expected.

1379       : 'take' extends Keys<T>
           ~

node_modules/.prisma/client/index.d.ts:1379:16 - error TS1005: ';' expected.

1379       : 'take' extends Keys<T>
                    ~~~~~~~

node_modules/.prisma/client/index.d.ts:1380:7 - error TS1005: '(' expected.

1380       ? 'orderBy' extends Keys<T>
           ~

node_modules/.prisma/client/index.d.ts:1380:19 - error TS1005: ',' expected.

1380       ? 'orderBy' extends Keys<T>
                       ~~~~~~~

node_modules/.prisma/client/index.d.ts:1381:9 - error TS1005: '(' expected.

1381         ? ByValid extends True
             ~

node_modules/.prisma/client/index.d.ts:1381:19 - error TS1005: ',' expected.

1381         ? ByValid extends True
                       ~~~~~~~

node_modules/.prisma/client/index.d.ts:1384:37 - error TS1005: ',' expected.

1384               [P in OrderFields]: P extends ByFields
                                         ~~~~~~~

node_modules/.prisma/client/index.d.ts:1384:45 - error TS1005: ':' expected.

1384               [P in OrderFields]: P extends ByFields
                                                 ~~~~~~~~

node_modules/.prisma/client/index.d.ts:1388:9 - error TS1005: ',' expected.

1388         : 'Error: If you provide "take", you also need to provide "orderBy"'
             ~

node_modules/.prisma/client/index.d.ts:1389:7 - error TS1005: ',' expected.

1389       : 'skip' extends Keys<T>
           ~

node_modules/.prisma/client/index.d.ts:1389:16 - error TS1005: ',' expected.

1389       : 'skip' extends Keys<T>
                    ~~~~~~~

node_modules/.prisma/client/index.d.ts:1390:7 - error TS1005: '(' expected.

1390       ? 'orderBy' extends Keys<T>
           ~

node_modules/.prisma/client/index.d.ts:1390:19 - error TS1005: ',' expected.

1390       ? 'orderBy' extends Keys<T>
                       ~~~~~~~

node_modules/.prisma/client/index.d.ts:1391:9 - error TS1005: '(' expected.

1391         ? ByValid extends True
             ~

node_modules/.prisma/client/index.d.ts:1391:19 - error TS1005: ',' expected.

1391         ? ByValid extends True
                       ~~~~~~~

node_modules/.prisma/client/index.d.ts:1394:37 - error TS1005: ',' expected.

1394               [P in OrderFields]: P extends ByFields
                                         ~~~~~~~

node_modules/.prisma/client/index.d.ts:1394:45 - error TS1005: ':' expected.

1394               [P in OrderFields]: P extends ByFields
                                                 ~~~~~~~~

node_modules/.prisma/client/index.d.ts:1398:9 - error TS1005: ',' expected.

1398         : 'Error: If you provide "skip", you also need to provide "orderBy"'
             ~

node_modules/.prisma/client/index.d.ts:1399:7 - error TS1005: ',' expected.

1399       : ByValid extends True
           ~

node_modules/.prisma/client/index.d.ts:1399:17 - error TS1005: ',' expected.

1399       : ByValid extends True
                     ~~~~~~~

node_modules/.prisma/client/index.d.ts:1402:33 - error TS1005: ',' expected.

1402           [P in OrderFields]: P extends ByFields
                                     ~~~~~~~

node_modules/.prisma/client/index.d.ts:1402:41 - error TS1005: ':' expected.

1402           [P in OrderFields]: P extends ByFields
                                             ~~~~~~~~

node_modules/.prisma/client/index.d.ts:1406:11 - error TS1005: ')' expected.

1406     >(args: SubsetIntersection<T, PostGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetPostGroupByPayload<T> : PrismaPromise<InputErrors>
               ~

node_modules/.prisma/client/index.d.ts:1406:64 - error TS1005: '(' expected.

1406     >(args: SubsetIntersection<T, PostGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetPostGroupByPayload<T> : PrismaPromise<InputErrors>
                                                                    ~

node_modules/.prisma/client/index.d.ts:1406:78 - error TS1005: ',' expected.

1406     >(args: SubsetIntersection<T, PostGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetPostGroupByPayload<T> : PrismaPromise<InputErrors>
                                                                                  ~

node_modules/.prisma/client/index.d.ts:1406:83 - error TS1005: ',' expected.

1406     >(args: SubsetIntersection<T, PostGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetPostGroupByPayload<T> : PrismaPromise<InputErrors>
                                                                                       ~~~~~~~

node_modules/.prisma/client/index.d.ts:1406:130 - error TS1005: '(' expected.

1406     >(args: SubsetIntersection<T, PostGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetPostGroupByPayload<T> : PrismaPromise<InputErrors>
                                                                                                                                      ~

node_modules/.prisma/client/index.d.ts:1407:3 - error TS1005: '(' expected.

1407   }
       ~

node_modules/.prisma/client/index.d.ts:1415:3 - error TS1135: Argument expression expected.

1415   export class Prisma__PostClient<T> implements PrismaPromise<T> {
       ~~~~~~

node_modules/.prisma/client/index.d.ts:2257:15 - error TS1110: Type expected.

2257             ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
                   ~~~~~~~~~~~~~~~~~

node_modules/.prisma/client/index.d.ts:2258:13 - error TS1128: Declaration or statement expected.

2258             : [
                 ~

node_modules/.prisma/client/index.d.ts:2264:9 - error TS1128: Declaration or statement expected.

2264         }[HavingFields]
             ~

node_modules/.prisma/client/index.d.ts:2265:7 - error TS1128: Declaration or statement expected.

2265       : 'take' extends Keys<T>
           ~

node_modules/.prisma/client/index.d.ts:2265:16 - error TS1005: ';' expected.

2265       : 'take' extends Keys<T>
                    ~~~~~~~

node_modules/.prisma/client/index.d.ts:2266:7 - error TS1005: '(' expected.

2266       ? 'orderBy' extends Keys<T>
           ~

node_modules/.prisma/client/index.d.ts:2266:19 - error TS1005: ',' expected.

2266       ? 'orderBy' extends Keys<T>
                       ~~~~~~~

node_modules/.prisma/client/index.d.ts:2267:9 - error TS1005: '(' expected.

2267         ? ByValid extends True
             ~

node_modules/.prisma/client/index.d.ts:2267:19 - error TS1005: ',' expected.

2267         ? ByValid extends True
                       ~~~~~~~

node_modules/.prisma/client/index.d.ts:2270:37 - error TS1005: ',' expected.

2270               [P in OrderFields]: P extends ByFields
                                         ~~~~~~~

node_modules/.prisma/client/index.d.ts:2270:45 - error TS1005: ':' expected.

2270               [P in OrderFields]: P extends ByFields
                                                 ~~~~~~~~

node_modules/.prisma/client/index.d.ts:2274:9 - error TS1005: ',' expected.

2274         : 'Error: If you provide "take", you also need to provide "orderBy"'
             ~

node_modules/.prisma/client/index.d.ts:2275:7 - error TS1005: ',' expected.

2275       : 'skip' extends Keys<T>
           ~

node_modules/.prisma/client/index.d.ts:2275:16 - error TS1005: ',' expected.

2275       : 'skip' extends Keys<T>
                    ~~~~~~~

node_modules/.prisma/client/index.d.ts:2276:7 - error TS1005: '(' expected.

2276       ? 'orderBy' extends Keys<T>
           ~

node_modules/.prisma/client/index.d.ts:2276:19 - error TS1005: ',' expected.

2276       ? 'orderBy' extends Keys<T>
                       ~~~~~~~

node_modules/.prisma/client/index.d.ts:2277:9 - error TS1005: '(' expected.

2277         ? ByValid extends True
             ~

node_modules/.prisma/client/index.d.ts:2277:19 - error TS1005: ',' expected.

2277         ? ByValid extends True
                       ~~~~~~~

node_modules/.prisma/client/index.d.ts:2280:37 - error TS1005: ',' expected.

2280               [P in OrderFields]: P extends ByFields
                                         ~~~~~~~

node_modules/.prisma/client/index.d.ts:2280:45 - error TS1005: ':' expected.

2280               [P in OrderFields]: P extends ByFields
                                                 ~~~~~~~~

node_modules/.prisma/client/index.d.ts:2284:9 - error TS1005: ',' expected.

2284         : 'Error: If you provide "skip", you also need to provide "orderBy"'
             ~

node_modules/.prisma/client/index.d.ts:2285:7 - error TS1005: ',' expected.

2285       : ByValid extends True
           ~

node_modules/.prisma/client/index.d.ts:2285:17 - error TS1005: ',' expected.

2285       : ByValid extends True
                     ~~~~~~~

node_modules/.prisma/client/index.d.ts:2288:33 - error TS1005: ',' expected.

2288           [P in OrderFields]: P extends ByFields
                                     ~~~~~~~

node_modules/.prisma/client/index.d.ts:2288:41 - error TS1005: ':' expected.

2288           [P in OrderFields]: P extends ByFields
                                             ~~~~~~~~

node_modules/.prisma/client/index.d.ts:2292:11 - error TS1005: ')' expected.

2292     >(args: SubsetIntersection<T, ProfileGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetProfileGroupByPayload<T> : PrismaPromise<InputErrors>
               ~

node_modules/.prisma/client/index.d.ts:2292:67 - error TS1005: '(' expected.

2292     >(args: SubsetIntersection<T, ProfileGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetProfileGroupByPayload<T> : PrismaPromise<InputErrors>
                                                                       ~

node_modules/.prisma/client/index.d.ts:2292:81 - error TS1005: ',' expected.

2292     >(args: SubsetIntersection<T, ProfileGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetProfileGroupByPayload<T> : PrismaPromise<InputErrors>
                                                                                     ~

node_modules/.prisma/client/index.d.ts:2292:86 - error TS1005: ',' expected.

2292     >(args: SubsetIntersection<T, ProfileGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetProfileGroupByPayload<T> : PrismaPromise<InputErrors>
                                                                                          ~~~~~~~

node_modules/.prisma/client/index.d.ts:2292:136 - error TS1005: '(' expected.

2292     >(args: SubsetIntersection<T, ProfileGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetProfileGroupByPayload<T> : PrismaPromise<InputErrors>
                                                                                                                                            ~

node_modules/.prisma/client/index.d.ts:2293:3 - error TS1005: '(' expected.

2293   }
       ~

node_modules/.prisma/client/index.d.ts:2301:3 - error TS1135: Argument expression expected.

2301   export class Prisma__ProfileClient<T> implements PrismaPromise<T> {
       ~~~~~~

node_modules/.prisma/client/index.d.ts:3147:15 - error TS1110: Type expected.

3147             ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
                   ~~~~~~~~~~~~~~~~~

node_modules/.prisma/client/index.d.ts:3148:13 - error TS1128: Declaration or statement expected.

3148             : [
                 ~

node_modules/.prisma/client/index.d.ts:3154:9 - error TS1128: Declaration or statement expected.

3154         }[HavingFields]
             ~

node_modules/.prisma/client/index.d.ts:3155:7 - error TS1128: Declaration or statement expected.

3155       : 'take' extends Keys<T>
           ~

node_modules/.prisma/client/index.d.ts:3155:16 - error TS1005: ';' expected.

3155       : 'take' extends Keys<T>
                    ~~~~~~~

node_modules/.prisma/client/index.d.ts:3156:7 - error TS1005: '(' expected.

3156       ? 'orderBy' extends Keys<T>
           ~

node_modules/.prisma/client/index.d.ts:3156:19 - error TS1005: ',' expected.

3156       ? 'orderBy' extends Keys<T>
                       ~~~~~~~

node_modules/.prisma/client/index.d.ts:3157:9 - error TS1005: '(' expected.

3157         ? ByValid extends True
             ~

node_modules/.prisma/client/index.d.ts:3157:19 - error TS1005: ',' expected.

3157         ? ByValid extends True
                       ~~~~~~~

node_modules/.prisma/client/index.d.ts:3160:37 - error TS1005: ',' expected.

3160               [P in OrderFields]: P extends ByFields
                                         ~~~~~~~

node_modules/.prisma/client/index.d.ts:3160:45 - error TS1005: ':' expected.

3160               [P in OrderFields]: P extends ByFields
                                                 ~~~~~~~~

node_modules/.prisma/client/index.d.ts:3164:9 - error TS1005: ',' expected.

3164         : 'Error: If you provide "take", you also need to provide "orderBy"'
             ~

node_modules/.prisma/client/index.d.ts:3165:7 - error TS1005: ',' expected.

3165       : 'skip' extends Keys<T>
           ~

node_modules/.prisma/client/index.d.ts:3165:16 - error TS1005: ',' expected.

3165       : 'skip' extends Keys<T>
                    ~~~~~~~

node_modules/.prisma/client/index.d.ts:3166:7 - error TS1005: '(' expected.

3166       ? 'orderBy' extends Keys<T>
           ~

node_modules/.prisma/client/index.d.ts:3166:19 - error TS1005: ',' expected.

3166       ? 'orderBy' extends Keys<T>
                       ~~~~~~~

node_modules/.prisma/client/index.d.ts:3167:9 - error TS1005: '(' expected.

3167         ? ByValid extends True
             ~

node_modules/.prisma/client/index.d.ts:3167:19 - error TS1005: ',' expected.

3167         ? ByValid extends True
                       ~~~~~~~

node_modules/.prisma/client/index.d.ts:3170:37 - error TS1005: ',' expected.

3170               [P in OrderFields]: P extends ByFields
                                         ~~~~~~~

node_modules/.prisma/client/index.d.ts:3170:45 - error TS1005: ':' expected.

3170               [P in OrderFields]: P extends ByFields
                                                 ~~~~~~~~

node_modules/.prisma/client/index.d.ts:3174:9 - error TS1005: ',' expected.

3174         : 'Error: If you provide "skip", you also need to provide "orderBy"'
             ~

node_modules/.prisma/client/index.d.ts:3175:7 - error TS1005: ',' expected.

3175       : ByValid extends True
           ~

node_modules/.prisma/client/index.d.ts:3175:17 - error TS1005: ',' expected.

3175       : ByValid extends True
                     ~~~~~~~

node_modules/.prisma/client/index.d.ts:3178:33 - error TS1005: ',' expected.

3178           [P in OrderFields]: P extends ByFields
                                     ~~~~~~~

node_modules/.prisma/client/index.d.ts:3178:41 - error TS1005: ':' expected.

3178           [P in OrderFields]: P extends ByFields
                                             ~~~~~~~~

node_modules/.prisma/client/index.d.ts:3182:11 - error TS1005: ')' expected.

3182     >(args: SubsetIntersection<T, UserGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetUserGroupByPayload<T> : PrismaPromise<InputErrors>
               ~

node_modules/.prisma/client/index.d.ts:3182:64 - error TS1005: '(' expected.

3182     >(args: SubsetIntersection<T, UserGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetUserGroupByPayload<T> : PrismaPromise<InputErrors>
                                                                    ~

node_modules/.prisma/client/index.d.ts:3182:78 - error TS1005: ',' expected.

3182     >(args: SubsetIntersection<T, UserGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetUserGroupByPayload<T> : PrismaPromise<InputErrors>
                                                                                  ~

node_modules/.prisma/client/index.d.ts:3182:83 - error TS1005: ',' expected.

3182     >(args: SubsetIntersection<T, UserGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetUserGroupByPayload<T> : PrismaPromise<InputErrors>
                                                                                       ~~~~~~~

node_modules/.prisma/client/index.d.ts:3182:130 - error TS1005: '(' expected.

3182     >(args: SubsetIntersection<T, UserGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetUserGroupByPayload<T> : PrismaPromise<InputErrors>
                                                                                                                                      ~

node_modules/.prisma/client/index.d.ts:3183:3 - error TS1005: '(' expected.

3183   }
       ~

node_modules/.prisma/client/index.d.ts:3191:3 - error TS1135: Argument expression expected.

3191   export class Prisma__UserClient<T> implements PrismaPromise<T> {
       ~~~~~~

node_modules/.prisma/client/index.d.ts:4618:1 - error TS1128: Declaration or statement expected.

4618 }
     ~

node_modules/graphql/NotSupportedTSVersion.d.ts:1:63 - error TS1003: Identifier expected.

```

This is my package.json file

```

{
  "name": "Backend",
  "version": "1.0.0",
  "main": "index.js",
  "license": "MIT",
  "dependencies": {
    "@graphql-tools/schema": "^8.3.2",
    "@prisma/client": "^3.10.0",
    "express": "^4.17.3",
    "express-graphql": "^0.12.0",
    "graphql": "^16.3.0"
  },
  "devDependencies": {
    "@types/express": "^4.17.13",
    "@types/node": "^17.0.21",
    "prisma": "3.10.0",
    "ts-node": "^10.5.0",
    "typescript": "^4.5.5"
  }
}

```

And here is my index.ts file:

```

import { graphqlHTTP } from 'express-graphql';
import { makeExecutableSchema } from '@graphql-tools/schema';
import { PrismaClient } from '@prisma/client'

const prisma = new PrismaClient()
const express = require('express');
const app = express();
const port = 3000;

async function main() {
  // ... you will write your Prisma Client queries here
}

main()
  .catch((e) => {
    throw e
  })
  .finally(async () => {
    await prisma.$disconnect()
  })

const typeDefs = `
  type User {
    email: String!
    name: String
  }
  
  type Query {
    allUsers: [User!]
  }`;

const resolvers = {
};

export const schema = makeExecutableSchema ({
  resolvers, 
  typeDefs
});

app.use('/graphql', graphqlHTTP({
  schema,
}));

app.get('/', function (req, res) {
  res.send('Hello World');
});

app.listen(port, () => {
  console.log(`Server started on port: ${port}`);
});


```

### How to reproduce

run tsc -w 

### Prisma information

```
generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

model Post {
  id        Int      @id @default(autoincrement())
  createdAt DateTime @default(now())
  updatedAt DateTime @updatedAt
  title     String   @db.VarChar(255)
  content   String?
  published Boolean  @default(false)
  author    User     @relation(fields: [authorId], references: [id])
  authorId  Int
}

model Profile {
  id     Int     @id @default(autoincrement())
  bio    String?
  user   User    @relation(fields: [userId], references: [id])
  userId Int     @unique
}

model User {
  id      Int      @id @default(autoincrement())
  email   String   @unique
  name    String?
  posts   Post[]
  profile Profile?
}
```

### Environment & setup

- OS: MacOS
- Database: Postgres
- Node.js version: 16.14.0

### Prisma Version

```
3.10.0
```

**Comment by pantharshit00** [comment] 2022-03-03 09:44
I am unable to reproduce this. I ran the TS compiler in the project and found no error after fixing the `express` import from require JS to ES modules import. Can you please try cleaning your `node_modules` and trying this again?

**Comment by garrensmith** [comment] 2022-05-06 13:48
Hi @tecshaun I'm going to close this since it doesn't seem to be a Prisma bug. Please open again if you still experiencing this.

**Closed by garrensmith** 2022-05-06 13:48 UTC
Labels: bug/0-unknown, kind/bug, topic: client types, team/client
