### ISSUE TITLE
 Client Version Error 4.0.0 In NextJS in the API Route

### ISSUE THREAD

**Issue by einKnuffy** [prisma/prisma#14113] opened 2022-07-02 17:24 UTC
### Bug description

Hello, a week before I could simply make an axios request an create/register/login an user. Apparently after updating to prisma/4.0.0 and @prisma/client@4.0.0 this weird bug or error appeared.

So instead of getting a success and creating the user, this happened: (look out for console and then the res.data.error)

![image](https://user-images.githubusercontent.com/66639485/177010120-278098da-542b-4369-a4c2-b3f7218be231.png)

### Expected behavior

I expect to get a success: true and the successful creation of the user

### Prisma information

This is my schema
```
generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "mongodb"
 // I am not gonna include the url here (but it works)
}

model User {
  id        String   @id @default(auto()) @map("_id") @db.ObjectId
  email     String   @unique(map: "email_1")
  favorites String[] 
  lastVisited Json[]
  password  String
  ratings   Json[]
  token     String   @unique(map: "token_1")
  userName  String   @unique(map: "userName_1")
  //items     Item[]   
}
```

Those are my queries:
```
(await prisma.user.findUnique({
        where: {
          email: credentials.email,
        },
      })) || null;
```
And:
`(await prisma.user.create({ data: credentials })) || null`

### Environment & setup

- OS: Windows
- Database: MongoDB
- Node.js version: Latest

### Prisma Version

```
prisma                  : 4.0.0
@prisma/client          : 4.0.0
Current platform        : windows
Query Engine (Node-API) : libquery-engine da41d2bb3406da22087b849f0e911199ba4fbf11 (at node_modules\@prisma\engines\query_engine-windows.dll.node)
Migration Engine        : migration-engine-cli da41d2bb3406da22087b849f0e911199ba4fbf11 (at node_modules\@prisma\engines\migration-engine-windows.exe)
Introspection Engine    : introspection-core da41d2bb3406da22087b849f0e911199ba4fbf11 (at node_modules\@prisma\engines\introspection-engine-windows.exe)
Format Binary           : prisma-fmt da41d2bb3406da22087b849f0e911199ba4fbf11 (at node_modules\@prisma\engines\prisma-fmt-windows.exe)
Default Engines Hash    : da41d2bb3406da22087b849f0e911199ba4fbf11
Studio                  : 0.465.0
```

**Comment by janpio** [comment] 2022-07-04 12:45
From the little I can see in the screenshot, it seems that you are getting a unique constraint error from `token_1`, which would mean your database already has the same value that you are trying to create in the `token` field.

**Comment by janpio** [comment] 2022-07-06 21:29
Please add a comment to this issue and help us to figure out a reproduction of this: https://github.com/prisma/prisma/issues/12814 Thanks.

Your original issue is solved? Then please close this isuse. Thanks.

**Comment by jereloh** [comment] 2022-07-20 04:37
Hi, I am facing a similar issue using Next.js but this only happens in /api, in server side rendering (SSR) it behaves correctly

Code logic 
1. findUnique, where: {id}
2. if not exist (null), use create data:{id,...some other data}

In /api routes
I've found that using findUnique automatically creates an entry in my database in /api routes which cause the .create function to fail because there is already an entry created, thus unique constrain error.

However same code logic works fine in nextjs server side rendering (SSR). 

My current work around is 
1. findUnique, where: {id}
2. if not exist (null), use **upsert** data:{id,...some other data}
Upsert updates the other data parts if the id exist and creates if id does not exist.

**Comment by pantharshit00** [comment] 2022-07-25 14:19
This bug was confirmed here: https://github.com/prisma/prisma/issues/12814#issuecomment-1191703145

I will close this as a duplicate now

**Closed by pantharshit00** 2022-07-25 14:19 UTC
Labels: bug/1-unconfirmed, kind/bug, team/client, priority/unknown, size/unknown
