### ISSUE TITLE
Error opening a TLS connection - prisma couldn't connect to db

### ISSUE THREAD

**Issue by itsma8di** [prisma/prisma#23675] opened 2024-03-31 12:54 UTC
### Bug description

so basically i entered my connection string and got this error:
used biganimal postgresql db

Error: P1011: Error opening a TLS connection: The message received was unexpected or badly formatted. (os error -2146893018)

### How to reproduce

```prisma migrate dev --name init```

### Prisma information

```prisma
generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "postgresql"
  url = "postgresql://USERNAME:XXXX@HOSTNAME.biganimal.io/DB_NAME"
}

model Group {
  id        String   @id @default(cuid())
  name      String?
  users     User[]
  createdAt DateTime @default(now())
  updatedAt DateTime @updatedAt
}
```

### Environment & setup

- OS:  Windows
- Database:  PostgreSQL
- Node.js version:  20

### Prisma Version

```
5.11.0
```

**Comment by jkomyno** [comment] 2024-04-03 10:24
Hi @itsma8di, that's odd, are you using a Cloud provider to host your Postgres instance? If so, which one?
May you also please try Prisma + Postgres on another non-Windows machine?
For context, "The message received was unexpected or badly formatted" seems to be a Windows-specific TLS handshake error.

Also, what happens if you attempt to establish a connection to your database with e.g. [`pg`](https://github.com/brianc/node-postgres) from your Windows machine? 

Please report back with the results, so we can investigate this issue further. Thanks!

**Comment by Jolg42** [comment] 2024-05-28 08:57
Hey @itsma8di, could you take a look at the questions @jkomyno asked in the previous comment, and please let us know about the missing information? This will help us to identify the problem. Thanks!

**Comment by SevInf** [comment] 2024-06-20 08:55
Hey @itsma8di ,
 

With the lack of information and our inability to reproduce this issue, we're now closing it. Feel free to comment if you have any updates about it.
 
Thank you 🙏

**Closed by SevInf** 2024-06-20 08:55 UTC
Labels: bug/0-unknown, kind/bug, topic: connections, domain/client, topic: postgresql
