### ISSUE TITLE
Postgres migration ERROR: function uuid_generate_v4() does not exist

### ISSUE THREAD

**Issue by Christian24** [prisma/prisma#7235] opened 2021-05-23 18:21 UTC
### Bug description

I created a migration with a schema similar to the one below. Running `prisma migrate dev --name init` fails with the following error:

````
  Command failed: npm run migrate:init
    Error: P3018
    
    A migration failed to apply. New migrations can not be applied before the error is recovered from. Read more about how to resolve migration issues in a production database: https://pris.ly/d/migrate-resolve
    
    Migration name: 20210523181052_init
    
    Database error code: 42883
    
    Database error:
    db error: ERROR: function uuid_generate_v4() does not exist
    HINT: No function matches the given name and argument types. You might need to add explicit type casts.
    



 FAIL  src/media/images/images.service.spec.ts
  ● Test suite failed to run

    Command failed: npm run migrate:init
    Error: P3018
    
    A migration failed to apply. New migrations can not be applied before the error is recovered from. Read more about how to resolve migration issues in a production database: https://pris.ly/d/migrate-resolve
    
    Migration name: 20210523181052_init
    
    Database error code: 42883
    
    Database error:
    db error: ERROR: function uuid_generate_v4() does not exist
    HINT: No function matches the given name and argument types. You might need to add explicit type casts.

````

### How to reproduce

1. Run `prisma migrate dev --name init` with schema similar to the one linked below.

### Expected behavior

No error when executing the command. 

### Prisma information

This is an except from my Prisma schema, which probably causes the error:
````
model lists {
  author     String          @unique @db.VarChar
  /// The value of this field is generated by the database as: `uuid_generate_v4()`.
  id         String          @id @default(dbgenerated("uuid_generate_v4()")) @db.Uuid
  visibility list_visibility @default(public)
  users      users           @relation(fields: [author], references: [username])
  items      items[]
}

````

### Environment & setup

- OS: Mac OS
- Database: PostgreSQL
- Node.js version: 15.14.4

### Prisma Version

```
2.23.0
```

**Comment by simonppg** [comment] 2021-05-25 18:32
@Christian24 pobably you need to create this module first `CREATE EXTENSION "uuid-ossp";`. I'm not sure if prisma can created by itselft, something similar happend to me before https://github.com/prisma/prisma/issues/6776, and that was part of my solution.

**Comment by pantharshit00** [comment] 2021-05-25 23:58
Indeed, I will consider this as duplicate of https://github.com/prisma/prisma/issues/6822

**Closed by pantharshit00** 2021-05-25 23:58 UTC
Labels: kind/bug

**Comment by KrishnaBiyyapu** [comment] 2023-03-23 16:29
CREATE EXTENSION IF NOT EXISTS "uuid-ossp"; worked for me
