### ISSUE TITLE
 `upsert` issues 2nd SELECT against read slave (in master/slave cluster with proxysql)

### ISSUE THREAD

**Issue by saimonmoore** [prisma/prisma#10208] opened 2021-11-11 10:49 UTC
### Bug description

We noticed that a `prisma.upsert` when executed against a galera mysql cluster (with proxysql) seems to not be sending the entirety of the operations to the write master.

E.g. What we are seeing is that in our preview and production environments (that are running the galera cluster) the upsert requests occasionally pass and fail.

When we activated the general log in mysql we see the following:

When we execute an upsert on a single mysql 5.7 server, everything works fine:

When record doesn't exist:
```
xss_app                                | prisma:query BEGIN
xss_app                                | prisma:query SELECT fooId, barId FROM bazTable WHERE (`fooId` = ? AND `barId` = ?)
xss_app                                | prisma:query INSERT INTO `bazTable` (`fooId`,`barId`,`bif, `bof`) VALUES (?,?,?,?)
xss_app                                | prisma:query SELECT * FROM bazTable WHERE (`fooId` = ? AND `barId` = ?) LIMIT 1 OFFSET 0
xss_app                                | prisma:query COMMIT
```

When record exists:
```
xss_app                                | prisma:query BEGIN
xss_app                                | prisma:query SELECT fooId, barId FROM bazTable WHERE (`fooId` = ? AND `barId` = ?)
xss_app                                | prisma:query UPDATE `bazTable` SET `fooId` = ?, `barId` = ?, `bif` = ?, `bof` = ? WHERE (`fooId`,`barId`) IN ((?,?))
xss_app                                | prisma:query SELECT * FROM bazTable WHERE (`fooId` = ? AND `barId` = ?) LIMIT 1 OFFSET 0
xss_app                                | prisma:query COMMIT
```

However, when we execute the same upsert against a mysql 5.7 master/slave cluster then we are seeing the following:

When upsert works:
```
[MASTER] xss_app                                | prisma:query BEGIN
[MASTER] xss_app                                | prisma:query SELECT fooId, barId FROM bazTable WHERE (`fooId` = ? AND `barId` = ?)
[MASTER] xss_app                                | prisma:query INSERT INTO `bazTable` (`fooId`,`barId`,`bif, `bof`) VALUES (?,?,?,?)
[MASTER] xss_app                                | prisma:query SELECT * FROM bazTable WHERE (`fooId` = ? AND `barId` = ?) LIMIT 1 OFFSET 0
[MASTER] xss_app                                | prisma:query COMMIT
```

When upsert fails:
```
[MASTER] xss_app                                | prisma:query BEGIN
[MASTER] xss_app                                | prisma:query SELECT fooId, barId FROM bazTable WHERE (`fooId` = ? AND `barId` = ?)
[MASTER] xss_app                                | prisma:query INSERT INTO `bazTable` (`fooId`,`barId`,`bif, `bof`) VALUES (?,?,?,?)

[SLAVE] xss_app                                 | prisma:query SELECT * FROM bazTable WHERE (`fooId` = ? AND `barId` = ?) LIMIT 1 OFFSET 0

[MASTER] xss_app                                | prisma:query ROLLBACK
```
(and the following error:
`prisma:client:fetcher Error: Query upsertOneBazTable is required to return data, but found no record(s).)
`
So we tried to work around this by separating the upsert into a separate `findOne`, `create` & then another `findOne` but we are seeing that `create` is failing in exactly the same way as it also issues it's own `select` which is sometimes going to a different server, ending up in the tx being rolled back. :(

This is unfortunate, since we wanted to trailblaze the use of prisma within the organization and this is happening for the very 1st entity we migrated to prisma.

We have tried executating the pure sql block, using a simple db client against the same cluster and that works fine. We also tried implementing the same sql block using TypeORM (our current orm) whereby we start a transaction, do a find, a create/update, then another find (and rollback if the 2nd find doesn't return the record). Both of these cases, work as expected in the same cluster setup.

### How to reproduce

1. Setup a mysql 5.7 master/slave setup with galera (https://galeracluster.com/) & proxysql (https://proxysql.com/)
2. Setup the DATABASE_URL to point to the proxy host of the cluster.
3. Enable general log on mysql servers
3. Execute a basic `upsert` command
4. Observe that sometimes the BEGIN/SELECT/INSERT/SELECT/COMMIT block is all sent to the write master and sometimes the 2nd SELECT is sent to the slave which is not running in the same tx and as such returns no records so prisma returns a prisma:client:fetcher Error: Query upsertOneBazTable is required to return data, but found no record(s)..

### Expected behavior

All 3 operations go to the write master.

### Prisma information

Issue is not specific to the schema. Any `upsert` with this version reproduces this behaviour.

### Environment & setup

- OS: Ubuntu Focal
- Database: Mysql 5.7 running Galera master/slave setup and proxySql.
- Node.js version: v12.22.6

### Prisma Version

Executed on localhost with latest code

```
prisma                  : 3.0.2
@prisma/client          : 3.0.2
Current platform        : debian-openssl-1.1.x
Query Engine (Node-API) : libquery-engine 2452cc6313d52b8b9a96999ac0e974d0aedf88db (at node_modules/@prisma/engines/libquery_engine-debian-openssl-1.1.x.so.node)
Migration Engine        : migration-engine-cli 2452cc6313d52b8b9a96999ac0e974d0aedf88db (at node_modules/@prisma/engines/migration-engine-debian-openssl-1.1.x)
Introspection Engine    : introspection-core 2452cc6313d52b8b9a96999ac0e974d0aedf88db (at node_modules/@prisma/engines/introspection-engine-debian-openssl-1.1.x)
Format Binary           : prisma-fmt 2452cc6313d52b8b9a96999ac0e974d0aedf88db (at node_modules/@prisma/engines/prisma-fmt-debian-openssl-1.1.x)
Default Engines Hash    : 2452cc6313d52b8b9a96999ac0e974d0aedf88db
Studio                  : 0.423.0
Done in 0.78s.
```

Also reproduced with v3.4.2

#### Addendum

Just a suggestion, our DBA says it may be more performant to do a:

```
insert ... on duplicate key update
```

Is this related to https://github.com/prisma/prisma/issues/5866 ?

**Comment by janpio** [comment] 2021-11-12 14:52
> 5\. Observe that sometimes the BEGIN/SELECT/INSERT/SELECT/COMMIT block is all sent to the write master and sometimes the 2nd SELECT is sent to the slave which is not running in the same tx and as such returns no records so prisma returns a prisma:client:fetcher Error: Query upsertOneBazTable is required to return data, but found no record(s)..

Who makes the decision where to send a query? 
Prisma only knows a connection string and sends all queries to a connection created via that connection string. When Prisma opens a connection, it expects all queries during that transaction of course to be run on the same underlying connection. Is that not the case?

Can you isolate if this is caused by galera or proxysql?

**Comment by saimonmoore** [comment] 2021-11-12 16:05
We have an open ticket with the DBA's to try and determine this. As I mentioned in #5866, right now we've worked around this by rerouting all db requests to the write master (a short term mitigation to unblock development) buowevert we have a staging environment with another proxysql/galera cluster where we are trying to debug the issue.

From the proxysql logs we have, what you are saying is what we are seeing i.e. a single client connection starts sending the full tx but somehow the 2nd select ends up on a different server (which points to this being an issue with proxysql/galera).

However, we noticed that this 2nd select is also the only operation that appears not to be prepared. And there is more contradictory data:

- When we issue the exact same tx block against the same cluster using a pure sql db client (e.g.dbeaver), then we do not observe the behaviour
- We also tried to reproduce the same upsert behaviour using typeorm (e.g. start transaction, find, insert/update, find, commit/rollback) against the same cluster and again we don't observe the issue. (It is notable that typeorm does not use prepared statements)

Our internal ticket is ongoing so as more data appears I'll update this issue as we are extremely interested in either confirming or ruling out prisma in this case. Our production server, has low traffic but high paying customers so we're not overly happy with the workaround and as such the sooner we find the root cause, the sooner it can be fixed.

**Comment by saimonmoore** [comment] 2021-11-12 16:06
Btw as I mentioned in the description, we are seeing the exact same behaviour with `prisma.create` and `prisma.update` since these both also execute the additional select to return the record.

**Comment by janpio** [comment] 2021-11-12 17:06
Something I just remembered: In PgBouncer, an ProxySQL equivalent for PostgreSQL instead of MySQL, you can configure the pooling mode: https://www.pgbouncer.org/features.html For it to work with Prisma you need to enable Transaction Pooling (With Session Mode you loose the benefits of using a Pooler, and with Statement Mode you get behavior similar to what you describe!)

**Comment by saimonmoore** [comment] 2021-11-15 09:13
This is very useful information. I will pass it along. Thanks @janpio

**Comment by SevInf** [comment] 2023-07-24 09:55
Hey @saimonmoore  ,

Did you get a chance to confirm that issue is solved? If we'll not hear back from you, we are going to close the issue.

Thank you!

**Comment by SevInf** [comment] 2023-07-31 13:38
Hey @saimonmoore ,
 
Since we haven't heard back from you, we are going to assume that the problem was solved in the end and close the issue as completed. Feel free to comment if you have any update on it.
 
Thank you 🙏

**Closed by SevInf** 2023-07-31 13:38 UTC
Labels: bug/0-unknown, kind/bug, team/client, topic: upsert, topic: proxysql
