### ISSUE TITLE
Introspection removes inline comments

### ISSUE THREAD

**Issue by divyenduz** [prisma/prisma#9194] opened 2021-09-10 08:30 UTC
### Bug description

`prisma db pull` removes inline comments from a schema. 

Related https://github.com/prisma/prisma/issues/1370

### How to reproduce

1. Create this `schema.prisma` file
```prisma
datasource ds {
    provider = "sqlite"
    url      = "file:./file.db"
}

model User {
    id   String @id
    name String // Full name
}
```
2. Run `yarn prisma db push`.
3. Run `yarn prisma db pull`.
4. The comment "Full name" is removed.

### Expected behavior

The comment should be preserved

### Prisma information

NA

### Environment & setup

- Database: Tested with SQLite and Postgres

### Prisma Version

```
prisma                  : 3.0.2
@prisma/client          : 3.0.2
Current platform        : darwin-arm64
Query Engine (Node-API) : libquery-engine 2452cc6313d52b8b9a96999ac0e974d0aedf88db (at node_modules/@prisma/engines/libquery_engine-darwin-arm64.dylib.node)
Migration Engine        : migration-engine-cli 2452cc6313d52b8b9a96999ac0e974d0aedf88db (at node_modules/@prisma/engines/migration-engine-darwin-arm64)
Introspection Engine    : introspection-core 2452cc6313d52b8b9a96999ac0e974d0aedf88db (at node_modules/@prisma/engines/introspection-engine-darwin-arm64)
Format Binary           : prisma-fmt 2452cc6313d52b8b9a96999ac0e974d0aedf88db (at node_modules/@prisma/engines/prisma-fmt-darwin-arm64)
Default Engines Hash    : 2452cc6313d52b8b9a96999ac0e974d0aedf88db
Studio                  : 0.423.0
```

**Comment by pantharshit00** [comment] 2022-02-02 12:19
Closing as duplicate of #1370

**Closed by pantharshit00** 2022-02-02 12:19 UTC
Labels: bug/1-unconfirmed, kind/bug, topic: re-introspection, topic: comments, team/migrations
