### ISSUE TITLE
prisma migrate dev is taking a really long time these days

### ISSUE THREAD

**Issue by amcjen** [prisma/prisma#9888] opened 2021-10-21 14:21 UTC
### Discussed in https://github.com/prisma/prisma/discussions/9840

<div type='discussions-op-text'>

<sup>Originally posted by **amcjen** October 18, 2021</sup>
We're running 3.2.0 and have 101 migrations. Whenever we run `prisma migrate dev` to create a new migration with changes to our schema, it's taking a really long time--like go-get-a-cup-of-coffee-and-enjoy-the-cup-of-coffee-before-it's-done-running long.

Screenshot showing the time it took for our most recent migrate (920 seconds).

Anything we can do to mitigate this? 

![Screen Shot 2021-10-18 at 3 22 19 PM](https://user-images.githubusercontent.com/175249/137815290-c085ef98-591d-4e9e-9e9b-939b924edd04.png)
</div>

Trying to add a bit more context. We have 26 tables. Nothing too crazy, and no table has more than ~100 rows as this is a development db that frequently gets reset with default data from seed.

When we run `npx prisma migrate reset --force`, it takes about 3.5 minutes to run all the migrations. I can watch each migration occur, and understandably, ones where CUIDs were introduced, or foreign keys were changed seem to take the longest.  

However, it's specifically `npx prisma migrate dev` that takes over 15 minutes now.  Since the migrations themselves only seem to take ~3 minutes, I'm not sure how to probe for what's happening the other time during the migration.  

Happy to provide additional information as needed!

**Comment by amcjen** [comment] 2021-11-03 13:52
Sent off the info asked for. Confirming you received it?

**Comment by tomhoule** [comment] 2021-11-04 10:16
We have a good picture of what's unnecessarily slow in `migrate dev`. How long does it take if you use `migrate deploy` with the same migrations on an empty database?

**Comment by floelhoeffel** [comment] 2021-11-04 11:19
@amcjen I just checked -  we have received the schema folder. Thanks for sending it over!

**Comment by janpio** [comment] 2021-11-04 13:20
Other relevant information we already know:
- Database: MySQL
- Prisma version: 3.2.0

What operating system are you on @amcjen?
What MySQL version?
What Node version?

Thanks.

**Comment by amcjen** [comment] 2021-11-04 19:17
> We have a good picture of what's unnecessarily slow in `migrate dev`. How long does it take if you use `migrate deploy` with the same migrations on an empty database?

Awesome! 

Assuming you meant no tables existing in the database except for `_prisma_migrations`, I ran `migrate deploy` and it returned nearly immediately--presumably b/c no tables existed, and non were created from running the command.

In case you meant tables existing, but merely truncated, I ran `migrate deploy` and it also ran immediately, but returned `No pending migrations to apply.`

Not sure that's what you were looking for?

**Comment by amcjen** [comment] 2021-11-04 19:23
> Other relevant information we already know:
> 
> * Database: MySQL
> * Prisma version: 3.2.0
> 
> What operating system are you on
macOS 11.6 on an M1 processor

>  What MySQL version? 
MariaDB 10.6.4 arm64 (via Homebrew)

> What Node version?
v16.6.2

**Comment by floelhoeffel** [comment] 2021-11-05 11:27
Hey @amcjen -

We did run your migrations on

Linux which took
- ~30s for `migrate deploy`
- ~1m30s for `migrate dev`

and on Mac (8 core i9 2019)
- ~3m30s for `migrate deploy`
- ~10m30s for `migrate dev`

which (especially on a Mac is unreasonably slow. We created an issue and are going to investigate further as soon as we have some bandwidth:  https://github.com/prisma/prisma/issues/10130

Sorry for the inconvenience!

**Comment by amcjen** [comment] 2021-11-05 19:38
Hi @floelhoeffel!

> which (especially on a Mac) is unreasonably slow. We created an issue and are going to investigate further as soon as we have some bandwidth: #10130
> 
> Sorry for the inconvenience!

Ah, well good to know it hopefully wasn't something silly we were doing on our side. Appreciate your quick replies and clear communication (so so so nice to know an important toolmaker is listening!)

Do let me know if you need additional information in the meantime.

**Comment by floelhoeffel** [comment] 2021-11-17 15:50
We are doing a spike this sprint (ends today in two weeks with release of 3.6.0) and will report back what we find.

**Comment by amcjen** [comment] 2021-11-17 15:53
Sounds great, looking forward to hearing what you find. 🙌

**Comment by BBSCDigital** [comment] 2022-03-04 13:15
> Hey @amcjen -
> 
> We did run your migrations on
> 
> Linux which took
> 
> * ~30s for `migrate deploy`
> * ~1m30s for `migrate dev`
> 
> and on Mac (8 core i9 2019)
> 
> * ~3m30s for `migrate deploy`
> * ~10m30s for `migrate dev`
> 
> which (especially on a Mac) is unreasonably slow. We created an issue and are going to investigate further as soon as we have some bandwidth: #10130
> 
> Sorry for the inconvenience!

I have the same problem using raspberry pi 4 as a database server.
I develop on Windows and do `migrate dev` to MySQL from raspberry which is on the same network.
Could it be some kind of incompatibility with ARM processors?
When doing the `migrate dev` and `migrate deploy` to the VPS(linux) everything is normal.

**Comment by amcjen** [comment] 2022-03-07 20:41
> Could it be some kind of incompatibility with ARM processors?
> When doing the `migrate dev` and `migrate deploy` to the VPS(linux) everything is normal.

No idea of the root cause (though I suspect something to do with how the lastest macOS deals with file sync issues at the filesystem level).  
The foolproof way to resolve this particular slowness though is to run your MariaDB instance inside of a Docker instance. A bit more setup, but guaranteed to resolve performance issues.

**Comment by floelhoeffel** [comment] 2022-03-09 20:14
Duplicate of #10130

**Closed by floelhoeffel** 2022-03-09 20:14 UTC
Labels: bug/1-unconfirmed, kind/bug, topic: migrate, topic: performance, team/migrations, topic: prisma migrate dev
