### ISSUE TITLE
Reset command for Prisma2 CLI

### ISSUE THREAD

**Issue by sashman** [prisma/prisma#2180] opened 2020-04-14 11:40 UTC
## Problem

Prisma 1 has the `reset` command which is incredibly handy for rapidly iterating your DB schema. 

## Solution

Add an equivalent command to Prisma 2 cli.

## Alternatives

An option is to drop the database and run:

```
prisma migrate save --experimental
```

**Comment by pantharshit00** [comment] 2020-04-15 12:08
Hi,

Thanks for reporting this! It has already been reported before, so I am going to close this as a duplicate of https://github.com/prisma/prisma/issues/742

**Closed by pantharshit00** 2020-04-15 12:08 UTC

**Comment by riezahughes** [comment] 2020-10-19 19:45
Is there any word on this at all?
