### ISSUE TITLE
Generate fails on 5.2 with unsupported type

### ISSUE THREAD

**Issue by HillaryManning** [prisma/prisma#20993] opened 2023-09-06 15:52 UTC
Hi Prisma Team! The following command just crashed. 

## Command

`generate`

## Versions
      
| Name        | Version            |
|-------------|--------------------|
| Platform    | darwin-arm64       | 
| Node        | v18.17.1           | 
| Prisma CLI  | 5.2.0              | 
| Engine      | 2804dc98259d2ea960602aca6b8e7fdc03c1758f| 

```
prisma                  : 5.2.0
@prisma/client          : 5.2.0
Current platform        : darwin-arm64
Query Engine (Node-API) : libquery-engine 2804dc98259d2ea960602aca6b8e7fdc03c1758f (at node_modules/@prisma/engines/libquery_engine-darwin-arm64.dylib.node)
Schema Engine           : schema-engine-cli 2804dc98259d2ea960602aca6b8e7fdc03c1758f (at node_modules/@prisma/engines/schema-engine-darwin-arm64)
Schema Wasm             : @prisma/prisma-schema-wasm 5.2.0-25.2804dc98259d2ea960602aca6b8e7fdc03c1758f
Default Engines Hash    : 2804dc98259d2ea960602aca6b8e7fdc03c1758f
Studio                  : 0.494.0
```
## Error
```
RustPanic: RuntimeError: panicked at 'internal error: entered unreachable code: No unsupported field should reach that path', query-engine/schema/src/build/input_types/mod.rs:26:40
```

## Description
Trying to do a version update from 4.14 to 5.2, no errors in 4.14 but seeing this crash on update. Postgres version is 14.1.0.62, hosting with Supabase, cloud provider AWS. We are using the type "Unsupported("geometry(Point, 4326)")" to support postGIS, and I saw there is some history of unsupported types (particularly when used as indices) causing trouble in previous versions.
https://github.com/prisma/prisma/issues/18517
https://github.com/prisma/prisma-engines/pull/3960

**I have confirmed that if I temporarily remove the unsupported fields, the generate command succeeds** (but not if I just remove the indices). We are using 'unsupported' as follows:
```
coords              Unsupported("geometry(Point, 4326)")?

@@index([coords], map: "location_coords", type: Gist)
```

**Comment by aqrln** [comment] 2023-09-08 12:27
I couldn't reproduce with this schema snippet, but I could reproduce it with the schema from the other issue that also triggers the same error: https://github.com/prisma/prisma/issues/20986 (it also uses an unsupported type in an index).

I can also confirm that it's a regression in 4.16.0.

**Comment by aqrln** [comment] 2023-09-08 19:04
After diving into the code I'm not sure this is exactly the same issue as https://github.com/prisma/prisma/issues/20986 anymore as this issue mentions `@@index` and not `@@unique`.

@HillaryManning is there any chance you could isolate a minimal reproduction so we could take a look?

**Comment by HillaryManning** [comment] 2023-09-12 18:44
@aqrln I haven't had a chance yet but I will get you a minimal reproduction! Thanks for looking into this.

**Comment by aqrln** [comment] 2023-09-13 13:41
@HillaryManning if it will save time, you can also test if Prisma 5.3.0 fixes the issue for you. If it does, then we can close it and the reproduction will not be required (though still much appreciated so we can add a test if necessary), and if not, then we'll definitely need a reproduction to investigate.

**Comment by HillaryManning** [comment] 2023-10-06 14:43
@aqrln apologies for the delay:  I confirmed this morning that I am able to generate successfully with version 5.4.1.  Minimal reproducible with  5.2.0  involves a unique constrain on unsupported AND another value (tried string and float types, both failed). If I remove either field from the unique constraint, it generates successfully.

```
model Location {
  id        String   @id @default(dbgenerated("gen_random_uuid()")) @db.Uuid
  desc String?
  coords      Unsupported("geometry(Point, 4326)")

  @@unique([coords, desc])
  @@map("locations")
}

```

**Comment by aqrln** [comment] 2023-10-06 17:57
@HillaryManning thank you for checking this and for following up! Then it is indeed the same issue that was fixed by https://github.com/prisma/prisma-engines/pull/4219. I'll go ahead and close this issue as fixed.

**Closed by aqrln** 2023-10-06 17:57 UTC
Labels: bug/0-unknown, kind/bug, kind/regression, tech/engines, team/client, topic: rust panic, topic: Unsupported
