### ISSUE TITLE
sqlite timeout error multiple queries run one after another

### ISSUE THREAD

**Issue by pkellner** [prisma/prisma#10306] opened 2021-11-16 23:32 UTC
### Bug description

I've got a self contained project that runs with NextJS 12 using the API for routing and client side for updates.

I consistently get connection errors like this when the seeding happens when the app first runs, and also when doing simple multiple queries like 3 deletes in a row of different rows. It's easy to reproduce by building this app and then generating and migrating.  The seeding fails.  Then, if you seed manually, all you have to do is run the app and delete the 3 note cards showing and you'll see the errors generated.

I'm attaching a zip of the project as well as two videos.  One shows no errors with 2.28 and the other with 3.5 causing the errors doing exactly the same deletes.

### Expected behavior

```
Error occurred during query execution:
ConnectorError(ConnectorError { user_facing_error: None, kind: ConnectionError(Timed out during query execution.) })
```

[peter-kellner-sqlite-problems-clip-99-final.zip](https://github.com/prisma/prisma/files/7550550/peter-kellner-sqlite-problems-clip-99-final.zip]

https://user-images.githubusercontent.com/241170/142082631-a97735b6-8a0d-48cf-ada0-833640191050.mp4

https://user-images.githubusercontent.com/241170/142084736-8ade24f9-5dc4-483d-828d-5bde42b3557b.mp4

https://user-images.githubusercontent.com/241170/142084736-8ade24f9-5dc4-483d-828d-5bde42b3557b.mp4

)

### Environment & setup

- OS: MacOS
- Database: SQLite
- Node.js version: 16.5.0

### Prisma Version

```
3.5 (see description of bug)
```
[](url)

**Comment by pantharshit00** [comment] 2021-11-17 09:27
Hello @pkellner 

Looks like you are running into https://github.com/prisma/prisma/issues/10194 which is a known bug. The execution of seed script from `npx prisma migrate dev` seems to be failing. Here is a quick workaround for this: 
`resetdb.sh`
```sh
rm prisma/dev.db
npx prisma generate
npx prisma migrate dev --skip-seed
npx prisma db seed
```

Here instead of using the seed script execution from `migrate` we are going to skip it and explicitly execute the seed script. I tried this out in your projects and I am getting no errors now. 

Let me know if this helps and then we can probably close this issue as a duplicate.

**Comment by pkellner** [comment] 2021-11-17 11:39
> Hello @pkellner 
> 
> 
> 
> Looks like you are running into https://github.com/prisma/prisma/issues/10194 which is a known bug. The execution of seed script from `npx prisma migrate dev` seems to be failing. Here is a quick workaround for this: 
> 
> `resetdb.sh`
> 
> ```sh
> 
> rm prisma/dev.db
> 
> npx prisma generate
> 
> npx prisma migrate dev --skip-seed
> 
> npx prisma db seed
> 
> ```
> 
> 
> 
> Here instead of using the seed script execution from `migrate` we are going to skip it and explicitly execute the seed script. I tried this out in your projects and I am getting no errors now. 
> 
> 
> 
> Let me know if this helps and then we can probably close this issue as a duplicate.  

The other part of this bug report with timeouts happening on consecutive sql deletes is the more important error that may or not be related.  Please don't close.

**Comment by pantharshit00** [comment] 2021-11-17 14:53
Ah, I missed that one while debugging the seeding part. I will take another look.

**Comment by pkellner** [comment] 2021-11-18 17:49
@pantharshit00 sny update on this?

**Comment by pantharshit00** [comment] 2021-11-18 21:52
Hello @pkellner 

I have opened https://github.com/prisma/prisma/pull/10343 which should fix both issues here. What is happening here is we are running the seed script in the cli code before terminating the migration engine which was retaining lock on the sqlite database resulting in `dev.db-journal` left in the filesystem which is basically transaction logs and locks which sqlite keeps tracks of. 

Now since this file was not cleaned up, any new transactions like your delete operation was failing with the same timeout error as sqlite was still processing the old lock. Only one process can write to a sqlite database at a time. 

So please wait while we merge the fixes here.

**Comment by pkellner** [comment] 2021-11-19 00:55
@pantharshit00 thanks for the efforts here.  However, I don't think you've got the problem isolated quite yet.  If the error were entirely around seeding then it would follow that if I don't seed at all, but instead start with an empty set of tables, the error would not happen (yet it still happens).  I'll paste a video showing that so you can verify for yourself that completely skipping seeding does not solve my second problem

https://user-images.githubusercontent.com/241170/142520172-fb4f4e7e-1b06-4792-a141-390ceae2c324.mp4

.

**Comment by pkellner** [comment] 2021-11-19 18:05
Hi @pantharshit00 .  Any update on the second part of this issue as it seems it's not the locking problem you mentioned?  I'm finalizing my course this weekend and if there was a work around for the delete error I'm getting, I'd include it instead of releasing the course with version 2 of Prisma.   -thanks

**Comment by pkellner** [comment] 2021-11-22 01:16
Any update @pantharshit00 ?

**Comment by pkellner** [comment] 2021-11-22 14:32
I've confirmed this problem exists in both windows and mac versions

**Comment by pkellner** [comment] 2021-11-22 15:43
@Jolg42 I understand you just closed the bug that has to do with seeding and the sqlite error.  Does that fix also fix the same error I reported here with sqlite timeout failures when I delete multiple records (failed in 3.5 but worked in v2.28).  Is there a NPM version string I can test with?

**Comment by Jolg42** [comment] 2021-11-22 15:56
@pkellner The fix included in the PR is now available in our dev version `3.6.0-dev.19` (not recommended for production)

Let me know if it fixes it, it will be part of 3.6.0 release on next Tuesday.

**Comment by pkellner** [comment] 2021-11-22 16:08
@Jolg42 sadly, no.  Fails very quickly running my app and this time, for the first time, I saw an error generated on insert I think. Always the same sqlite timeout error. The zip code is listed at the top of this issue to the app.  It's a trivial self contained app that uses NextJS 12 with the API Routes API.  I'm using it in courseware so it's very simple and straight forward.

Also, seeding still fails with the same error.  Here is the script I run that works with lines 3 and 4 uncommented and line 5 commented.

```
rm prisma/dev.db
npx prisma generate
#npx prisma migrate dev --name init --skip-seed
#npx prisma db seed
npx prisma migrate dev --name init
```

My test was to remove my node_modules folder and run `npm install` after that, then run the resetdb.sh script.

Here is my current `package.json` file

```
{
  "name": "nextjs-primsa-pluralsight-course",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "dev": "next",
    "build": "next build",
    "start": "next start"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "dependencies": {
    "@prisma/client": "^3.6.0-dev.19",
    "axios": "^0.24.0",
    "next": "^12.0.4",
    "react": "^17.0.2",
    "react-dom": "^17.0.2",
    "react-toastify": "^8.1.0",
    "uuid": "^8.3.2"
  },
  "devDependencies": {
    "eslint": "^7.22.0",
    "eslint-config-next": "^12.0.4",
    "eslint-plugin-react": "^7.23.1",
    "eslint-plugin-react-hooks": "^4.2.0",
    "prisma": "^3.6.0-dev.19"
  },
  "prisma": {
    "seed": "node prisma/seed.js"
  }
}
```

**Comment by pkellner** [comment] 2021-11-22 16:11
@Jolg42   Here is the zip file I'm using now. It's very close to the same as the zip at the start, but just some cleanup on my end as it's the end of my course demo now.

[clip-12-adding-optimistic-ui-for-better-user-experience-final.zip](https://github.com/prisma/prisma/files/7582605/clip-12-adding-optimistic-ui-for-better-user-experience-final.zip)

**Comment by Jolg42** [comment] 2021-11-22 16:51
Ok, thanks for the details I'll let @pantharshit00 checks this

**Comment by Azarattum** [comment] 2022-06-15 08:21
Today I also got the `Timed out during query execution` which completely **crashed my production server** (it has been working for month without an issue until that). I am processing user requests asynchronously, so I guess I was very unlucky and got two consecutive requests which caused the crash according to this issue.

Please, investigate the problem and fix the issue as soon as possible. Meanwhile I need to implement a better error handling for my system...

**Comment by Azarattum** [comment] 2022-06-15 08:22
I was using `@prisma/client: 3.12.0`, btw

**Comment by kebian** [comment] 2022-06-22 21:21
I'm also experiencing these connection errors when processing large amounts of async inserts / upserts with sqlite3.

```
Error handling onItemListed PrismaClientUnknownRequestError: 
Invalid `prisma.collection.upsert()` invocation:


  Error occurred during query execution:
ConnectorError(ConnectorError { user_facing_error: None, kind: ConnectionError(Timed out during query execution.) })
    at RequestHandler.request (/Users/robs/dev/xxx/poc/node_modules/@prisma/client/runtime/index.js:49026:15)
    at async PrismaClient._request (/Users/robs/dev/xxx/poc/node_modules/@prisma/client/runtime/index.js:49919:18) {
  clientVersion: '3.15.2'
}
```

**Comment by NikxDa** [comment] 2022-08-03 17:58
I'm experiencing the same issues as @kebian in the latest Prisma version.

**Comment by janpio** [comment] 2022-09-09 18:59
@Azarattum @kebian @NikxDa Are you also using SQlite and the error occurs when running `db seed`? If not, please include the necessary information so we can possibly reproduce your cases. Thanks.

**Comment by janpio** [comment] 2022-09-09 19:25
Ok, took a shot at reproducing with the zip file you supplied @pkellner:
https://github.com/prisma/prisma/issues/10306#issuecomment-975682984

With `3.6.0-integration-undici-4.1` that the project comes with it indeed fails:
```
PS C:\Users\Jan\Downloads\clip-12-adding-optimistic-ui-for-better-user-experience-final (1)\clip-12-adding-optimistic-ui-for-better-user-experience-final> npx prisma migrate dev --name init
Prisma schema loaded from prisma\schema.prisma
Datasource "db": SQLite database "dev.db" at "file:./dev.db"

SQLite database dev.db created at file:./dev.db

Applying migration `20211119160401_init`
Applying migration `20211119161037_init`

The following migration(s) have been applied:

migrations/
  └─ 20211119160401_init/
    └─ migration.sql
  └─ 20211119161037_init/
    └─ migration.sql

Running seed command `node prisma/seed.js` ...
Starting Seeding...
PrismaClientUnknownRequestError: 
Invalid `prisma.note.create()` invocation in
C:\Users\Jan\Downloads\clip-12-adding-optimistic-ui-for-better-user-experience-final (1)\clip-12-adding-optimistic-ui-for-better-user-experience-final\prisma\seed.js:15:23      

  12 console.log("Starting Seeding...");
  13
  14 for (const rec of notesData) {
→ 15   await prisma.note.create(
  Error occurred during query execution:
ConnectorError(ConnectorError { user_facing_error: None, kind: ConnectionError(Timed out during query execution.) })
    at cb (C:\Users\Jan\Downloads\clip-12-adding-optimistic-ui-for-better-user-experience-final (1)\clip-12-adding-optimistic-ui-for-better-user-experience-final\node_modules\@prisma\client\runtime\index.js:43333:17)
    at async main (C:\Users\Jan\Downloads\clip-12-adding-optimistic-ui-for-better-user-experience-final (1)\clip-12-adding-optimistic-ui-for-better-user-experience-final\prisma\seed.js:15:5) {
  clientVersion: '3.6.0-integration-undici-4.1'
}

An error occured while running the seed command:
Error: Command failed with exit code 1: node prisma/seed.js


Your database is now in sync with your schema.

✔ Generated Prisma Client (3.6.0-integration-undici-4.1) to .\node_modules\@prisma\client in 140ms


┌─────────────────────────────────────────────────────────┐
│  Update available 3.6.0-integration-undici-4.1 -> 4.3.1 │
│                                                         │
│  This is a major update - please follow the guide at    │
│  https://pris.ly/d/major-version-upgrade                │
│                                                         │
│  Run the following to update                            │
│    npm i @prisma/client@latest                          │
└─────────────────────────────────────────────────────────┘
```

By upgrading to `@latest` I can avoid this:
```
PS C:\Users\Jan\Downloads\clip-12-adding-optimistic-ui-for-better-user-experience-final (1)\clip-12-adding-optimistic-ui-for-better-user-experience-final> npx prisma migrate dev --name foo
Prisma schema loaded from prisma\schema.prisma
Datasource "db": SQLite database "dev.db" at "file:./dev.db"

SQLite database dev.db created at file:./dev.db

Applying migration `20211119160401_init`
Applying migration `20211119161037_init`

The following migration(s) have been applied:

migrations/
  └─ 20211119160401_init/
    └─ migration.sql
  └─ 20211119161037_init/
    └─ migration.sql

Your database is now in sync with your schema.

✔ Generated Prisma Client (4.3.1 | library) to .\node_modules\@prisma\client in 76ms


Running seed command `node prisma/seed.js` ...
Starting Seeding...

The seed command has been executed.
```

Then I also had a look at the UI via `npm run dev`, and I can indeed get that to fail - but mostly if I create something, then e.g. hit the star and then directly delete it. The optimistic UI seems to send a `PUT` to update that still _after_ the delete went through and hence fails.

Can you describe again please how exactly you could cause this error of a timeout via the UI and deleting things?

**Comment by janpio** [comment] 2022-09-09 19:40
Ok, I _can_ create the `ConnectorError(ConnectorError { user_facing_error: None, kind: ConnectionError(Timed out during query execution.) })` _sometimes_ with the newest Prisma version in the UI when one of the cards has additional attributes like being marked with the star. When I then delete multiple notes quick after each other, I get that error as well for one of those requests.

<img width="912" alt="image" src="https://user-images.githubusercontent.com/183673/189430561-b03e94a4-8a23-4450-8b1e-6965f22cc878.png">
<img width="1671" alt="image" src="https://user-images.githubusercontent.com/183673/189430613-34c6af56-5e45-446a-baeb-ff6ece95ef46.png">

It looks like your app is sending multiple HTTP queries quickly after each other or in parallel, and then when executing these queries one of them instantly fails with this error message.

**Comment by janpio** [comment] 2022-09-09 22:11
Note: there are multiple issues about this now all grouped under https://github.com/prisma/prisma/issues?q=is%3Aissue+is%3Aopen+label%3A%22topic%3A+Timed+out+during+query+execution%22 One of them is https://github.com/prisma/prisma/issues/10403 which points out that our error message here is currently highly misleading and should be changed/fixed.

**Comment by ansemjo** [comment] 2023-03-20 14:23
I just hit this issue as well and luckily found the "fix" of adding `?connection_limit=1` to the connection string [in another comment](https://github.com/prisma/prisma/issues/9562#issuecomment-1242491767). I'm commenting here because this thread has a nice list of possible reproducers for this issue. And while I don't think I can easily reduce my application to a full example I can post, I can at least describe the relevant parts.

It's an Express application, which uses [Passport.js](https://www.passportjs.org/) and [`@quixo3/prisma-session-store`](https://github.com/kleydon/prisma-session-store).

```prisma
datasource db {
  provider = "sqlite"
  url      = env("DATABASE_URL")
}

// ...
/// session storage for @quixo3/prisma-session-store
model Session {
  id        String   @id
  sid       String   @unique
  data      String
  expiresAt DateTime
}
```

The bit that configures the session storage:
```ts
import Session from 'express-session';
import { PrismaSessionStore } from "@quixo3/prisma-session-store";
import { PrismaClient } from "@prisma/client";
import { random } from './fn/random.js';
import { log } from './logging.js';

// name of the cookie
export const SessionCookie = "SESSION";

// return a session middleware for express
export function SessionStorage(prisma: PrismaClient, key: string | undefined) {

  // use a random secret if none given
  if (key === undefined) {
    log.warn('using random session secret');
    key = random();
  }

  return Session({
    name: SessionCookie,
    cookie: {
      maxAge: 7 * 24 * 60 * 60 * 1000, // ms, 7 days
      sameSite: "strict",
      secure: "auto",
    },
    secret: key,
    resave: false,
    saveUninitialized: false,
    unset: "destroy",
    store: new PrismaSessionStore(prisma, {
      checkPeriod: 10 * 60 * 1000, // ms, 10 minutes
      dbRecordIdIsSessionId: true,
      dbRecordIdFunction: undefined,
    }),
  });

}
```

I'm not exactly sure why (since I disabled `resave`) but this configuration causes `UPDATE`s on the `Session` table on *every single HTTP request*. The app is deployed on a simple [K3s.io Kubernetes](https://k3s.io/) instance and uses the default `traefik` Ingress. This means that a single HTTP/2 connection to the Ingress will cause multiple simultaneous HTTP/1.1 connections to the application.

Combined, this pretty reliably caused the container to crash very quickly by just browsing the page and navigating a few routes.

(While writing this up, I found that `prisma-session-store` apparently already had a workaround and I just wasn't on the latest version: https://github.com/kleydon/prisma-session-store/issues/88. Maybe this information will still prove useful.)

**Comment by Nedi11** [comment] 2023-08-16 08:07
Bump

**Comment by jkomyno** [comment] 2024-06-12 08:30
Hi @pkellner, @NikxDa, and others, we believe we have a fix for this issue.

We plan on releasing it with the next stable version of Prisma (`5.16.0`), but in the meantime, we'd like to collect some early feedback directly from the impacted users. Can you please try installing Prisma `5.16.0-integration-sqlite-fix.1`, and confirm that you can no longer experience this bug with it? Thanks!

```sh
pnpm install -D prisma@5.16.0-integration-sqlite-fix.1
pnpm install @prisma/client@5.16.0-integration-sqlite-fix.1
```

(Please note that this Prisma version is __unstable__, so we don't recommend running it in production.)

**Closed** 2024-06-18 13:53 UTC
Labels: bug/2-confirmed, kind/bug, topic: sqlite, domain/client, topic: prisma db seed, topic: seeding, topic: Timed out during query execution
