### ISSUE TITLE
Usage of NODE_ENV for switching .env files

### ISSUE THREAD

**Issue by maartenraes** [prisma/prisma#1717] opened 2020-02-26 16:09 UTC
We have 5 different environments local dev, testing environment, a deployed development environment, an acceptance environment and a production environment, each environment take it's own set of environment. We try to keep everything within it's own environment, so acceptance only talks with acceptance apps etc. 

We use dotenv to load in our .env files, an important one is ofcourse our database URL's. We use .env as a fallback for variables that are okay to set in all environments.
```
let path;
switch (process.env.NODE_ENV) {
    case "test":
        path = ".env.test";
        break;
    case "production":
        path = ".env.production";
        break;
    case "acceptance":
        path = ".env.acceptance";
        break;
    default:
        path = ".env.development";
}

// set variables will not be overridden / updated by second config call
// load .env.{NODE_ENV}
dotenv.config({ path });
// load .env for defaults
dotenv.config();
```

The latest switch to a seperate .env file for prisma makes it harder to use this since we can't use the dotenv package to switch between env variables, we have to set our postgres url global during build to not break pipelines, same thing for deployements, we set a global system url instead of using the `/prisma/.env` file because it doesn't make any sense to maintain multiple environments files next to the 5 we already have.

**Comment by janpio** [comment] 2020-02-26 16:47
> The latest switch to a seperate .env file for prisma makes it harder to use this since we can't use the dotenv package to switch between env variables

What do you refer to here exactly? 

The `.env` next to your `schema.prisma` is just a convenience feature, that allows you to set ENV vars without calling any `dotenv` code. If you want to have your ENV vars somwhere else, like in the code snippet you pasted above, then you are absolutely free to do that - you just have to take care of the loading (`dotenv.config();`) yourself.

Or am I missing something here?

**Comment by maartenraes** [comment] 2020-02-27 08:35
> The latest switch to a seperate .env file for prisma makes it harder to use this since we can't use the dotenv package to switch between env variable

This is related to https://github.com/prisma/prisma2/issues/800 because we can't load in a .env file during `prisma2 generate`

But still, if you ever want to support other variables in the `prisma.schema` and use different dotenv environments there should be support in some way for it

**Comment by janpio** [comment] 2020-02-27 09:45
Ok, #800 has to and will be fixed.

> But still, if you ever want to support other variables in the `prisma.schema` and use different dotenv environments there should be support in some way for it

Can you elaborate? I do not understand what the problem there is or would be.

**Comment by janpio** [comment] 2020-06-29 17:39
@maartenraes Is this still something that you would be interested in seeing or did closing #800 solve this for your?

**Comment by janpio** [comment] 2021-04-06 16:50
Duplicate of https://github.com/prisma/prisma/issues/3865, continued there.

**Closed by janpio** 2021-04-06 16:50 UTC
Labels: kind/feature, topic: env
