### ISSUE TITLE
"Migration troubleshooting in production" documentation offers conflicting info about editing migrations

### ISSUE THREAD

**Issue by ruohola** [prisma/prisma#11376] opened 2022-01-24 21:00 UTC
[Migration troubleshooting in production](https://www.prisma.io/docs/guides/database/production-troubleshooting) documentation states two conflicting advices if one has to edit a migration file manually to fix deploying migrations in production:

> If you modify the migration, make sure you copy it back to source control to ensure that state of your production database is reflected exactly in development.

> `prisma migrate deploy` issues a warning if an already applied migration has been edited - however, it does not stop the migration process. To remove the warnings, restore the original migration from source control.

The former to me seems like the obvious correct one, since storing broken migration files in source control seems like terrible advice. But then how should one actually get rid of the "WARNING The following migrations have been modified since they were applied:" warning after editing a failed migration by hand and running `prisma migrate resolve --rolled-back`?

**Comment by floelhoeffel** [comment] 2022-01-25 15:35
@ruohola this is a good find, thanks for reporting. We will remove the warning for rolled-back migrations.

We are also considering removing the warning in `migrate deploy` altogether. A common reason for applied migration files to change (hash in migrations table and has of file in filesystem differ) is reformatting or adding a comment. 

What do you think, would it be ok to remove the warning even for applied migrations? (You would still have `migrate status` that would warn about the diff.)

**Comment by floelhoeffel** [comment] 2022-01-25 15:37
https://github.com/prisma/prisma/issues/9829

**Comment by ruohola** [comment] 2022-01-25 15:42
> @ruohola this is a good find, thanks for reporting. We will remove the warning for rolled-back migrations.

👍 Great, so it was just as I thought. I simply now deleted the failed row from my `_prisma_migrations` table.

> We are also considering removing the warning in `migrate deploy` altogether. A common reason for applied migration files to change (hash in migrations table and has of file in filesystem differ) is reformatting or adding a comment.
> 
> What do you think, would it be ok to remove the warning even for applied migrations? (You would still have `migrate status` that would warn about the diff.)

I would agree with this, I think it should be clear for everyone that `migrate deploy` will not rerun a migration, so I don't think anyone would think otherwise and wonder why their edited migration is not getting applied. It's incovenient now since one really cannot run a formatter for the .sql files, since if the autoformatting would change even a bit at any point, one would be eternally stuck with the warning.

**Comment by floelhoeffel** [comment] 2022-01-26 11:52
Duplicate of #9829

**Closed** 2022-02-04 15:43 UTC
Labels: team/migrations, topic: migrate resolve
