### ISSUE TITLE
Downloading binaries in Private organisation in VPN networks

### ISSUE THREAD

**Issue by rpateld** [prisma/prisma#834] opened 2019-10-23 13:56 UTC
Downloading windows binary for query-engine and migration-engine [ ] 0% Error: incorrect header check

![image](https://user-images.githubusercontent.com/56134077/67400129-35912d00-f57b-11e9-8873-524a90b49d1e.png)

**Comment by pantharshit00** [comment] 2019-10-28 08:56
![image](https://user-images.githubusercontent.com/22195362/67665027-23dbcb00-f969-11e9-97a5-b18b601f384f.png)


I am unable to reproduce this on macOS and as well as in windows. 
Can you please try again?

**Comment by rpateld** [comment] 2019-10-28 14:30
Look Like it's not working in a Private organization in VPN network! 

I'm hoping for some way to resolve this for all our big banks, governments and other companies where we don't blindly trust executables download off the internet.

I don't know much about the logic behind, but I noticed the CLI is binary, so if that is the problem, please split the package into 2 different NPM packages. I won't be needing the CLI anyway.

**Comment by pantharshit00** [comment] 2019-10-28 14:45
Yes, we download the prisma2 binary from S3. 

I think we will need to think about this use case more carefully.

**Comment by matthewmueller** [comment] 2019-10-28 17:25
Internal note: Dropping for this sprint. Bring it up again in 2 weeks.

**Comment by LongLiveCHIEF** [comment] 2019-11-14 15:19
related https://github.com/prisma/prisma2/issues/931

**Comment by LongLiveCHIEF** [comment] 2019-11-15 19:37
I think we should close this in favor of #938 and make it one of the requirements for that one. I have some suggestions on ways to handle this, and I'll update comments in that issue.

**Comment by LongLiveCHIEF** [comment] 2020-02-19 14:16
I'm thinking we can take a page out of electron's book, and implement a `npm_config_prisma_*` set of configs that allow users to specify a mirror or host url via [npm-config](https://docs.npmjs.com/misc/config) heirarchy.  (global .npmrc => NPM_CONFIG env var -> local .npmrc)

Here's how [electron implements](https://github.com/electron/get/blob/master/src/artifact-utils.ts) the ability to specify various binary download options.

The MVP here would be looking for a supplied `PRISMA_BASE_URL_MIRROR` that the prisma install scripts would swap out with just the `<base_url>` part of the [binary schema](https://github.com/prisma/specs/blob/master/binaries/Readme.md#s3-url-schema).

If this sounds like something you'd like to see in a PoC, just say the word and I'll start working a PR.

**Comment by pantharshit00** [comment] 2021-05-16 13:33
We support `PRISMA_BINARIES_MIRROR` for quite some time now: https://www.prisma.io/docs/reference/api-reference/environment-variables-reference/#prisma_binaries_mirror

I think this can be closed now.

**Closed by pantharshit00** 2021-05-16 13:33 UTC
Labels: bug/0-needs-info, kind/bug, team/client, topic: enterprise
