### ISSUE TITLE
Client extensions in interactive transactions are bound to the base client

### ISSUE THREAD

**Issue by robere2** [prisma/prisma#17948] opened 2023-02-16 04:06 UTC
### Bug description

Extensions to the Prisma client have `this` bound to the base client as opposed to the transaction. I was not experiencing this problem in 4.9.0.

### How to reproduce

1. Create a Prisma client extension which uses `this` in some way.
2. Create an interactive transaction from that extended client.
3. Use the extension method within your transaction.
4. `this` will be the base Prisma client instead of the transaction client.

### Expected behavior

When client extensions are used within a transaction, `this` should be bound to the transaction client instead of the original Prisma client.

### Prisma information

Schema does not appear to be relevant.

```ts
const xprisma = prisma.$extends({
    client: {
        isTransaction(): boolean {
            return typeof this.$use !== "function";
        },
    }
});

console.log(xprisma.isTransaction()) // false
await xprisma.$transaction(async (tx) => {
    console.log(tx.isTransaction()); // false. Should be true
})
````

### Environment & setup

- OS: Windows 11 22H2
- Database: PostgreSQL
- Node.js version: 18.14.0

### Prisma Version

```
4.10.1
```

**Comment by robere2** [comment] 2023-02-16 04:30
Hmm... I've downgraded to 4.9.0 and am still experiencing this issue. Perhaps it was working before for some other reason in one of my recent changes, or I've not correctly downgraded.

Regardless, I do think this is an issue, but maybe it should be re-tagged as a feature request?

**Comment by janpio** [comment] 2023-02-16 12:54
Still a bug potentially, just not a regression. We'll take a look.

**Comment by ke-interel** [comment] 2023-03-30 11:12
Is there a timeline for when a fix is planned?

**Comment by janpio** [comment] 2023-03-30 22:36
No, we never commit to timelines publicly because plans change. `clientExtensions` is a preview feature that has a few bugs right now, and we will want to resolve these before the feature can be made generally available. I expect that we push in that direction soon.

**Comment by joeka36** [comment] 2023-04-11 23:24
Are there any other workaround to mitigate this for the time-being? Also running into the same issue.

**Comment by marcus13371337** [comment] 2023-04-25 11:40
I'm experiencing the same issue!

**Comment by MichalLytek** [comment] 2023-05-18 10:22
I'm also suffering from this issue:
https://github.com/prisma/prisma/issues/5022#issuecomment-1441651458

It's blocking me from migrating to use client extensions instead of generating code for custom db repositories.

**Comment by SevInf** [comment] 2023-06-05 10:51
This is fixed in #19565 and will be available in the next prisma release.
For those of you who'd like to test a fix sooner - you can use `4.16.0-dev.17` snapshot version. Be aware that dev version is not considered stable and is not recommended for production usage, but it should be enough to verify that fix is working for you.

**Closed by SevInf** 2023-06-05 10:51 UTC
Labels: bug/2-confirmed, kind/bug, topic: transaction, team/client, topic: interactiveTransactions, topic: clientExtensions

**Comment by marcus13371337** [comment] 2023-06-07 07:53
Tried it and it seems to have fixed the tests I written for my client extensions regarding transactions 🎉

However a little heads up, it seems as if it broke some other tests, and the error I'm getting:
```js
error TypeError: 'get' on proxy: property '_extensions' is a read-only and non-configurable data property on the proxy target but the proxy did not return its actual value (expected '#<et>' but got '#<et>')
    at ru (/node_modules/.pnpm/@prisma+client@4.16.0-dev.17_prisma@4.16.0-dev.17/node_modules/@prisma/client/runtime/library.js:162:11145)
    at a (/node_modules/.pnpm/@prisma+client@4.16.0-dev.17_prisma@4.16.0-dev.17/node_modules/@prisma/client/runtime/library.js:177:10309)
    at /node_modules/.pnpm/@prisma+client@4.16.0-dev.17_prisma@4.16.0-dev.17/node_modules/@prisma/client/runtime/library.js:177:10445
    at AsyncResource.runInAsyncScope (node:async_hooks:203:9)
    at /node_modules/.pnpm/@prisma+client@4.16.0-dev.17_prisma@4.16.0-dev.17/node_modules/@prisma/client/runtime/library.js:177:10425
    at Proxy.runInChildSpan (/node_modules/.pnpm/@prisma+client@4.16.0-dev.17_prisma@4.16.0-dev.17/node_modules/@prisma/client/runtime/library.js:174:1343)
    at Proxy.<anonymous> (/node_modules/.pnpm/@prisma+client@4.16.0-dev.17_prisma@4.16.0-dev.17/node_modules/@prisma/client/runtime/library.js:178:848)
    at Proxy._request (/node_modules/.pnpm/@prisma+client@4.16.0-dev.17_prisma@4.16.0-dev.17/node_modules/@prisma/client/runtime/library.js:177:10348)
    at Proxy.<anonymous> (/node_modules/.pnpm/@prisma+client@4.16.0-dev.17_prisma@4.16.0-dev.17/node_modules/@prisma/client/runtime/library.js:178:848)
    at Proxy.$queryRawInternal (/node_modules/.pnpm/@prisma+client@4.16.0-dev.17_prisma@4.16.0-dev.17/node_modules/@prisma/client/runtime/library.js:177:7988)
```

Will see if I can come up with a minimal reproduction for the issue

**Comment by marcus13371337** [comment] 2023-06-07 08:03
`$queryRaw*` on transactions seems to be broken in this version, here is a minimal reproduction (note, I've added some extensions to my Prisma client). Should I report this in a separate issue? @SevInf 
```ts
  describe("error", () => {
    test("breaks if using $queryRawUnsafe", async () => {
      const result = await prisma.$transaction(async (tx) => {
        return tx.$queryRawUnsafe(`SELECT * FROM machine_user;`);
      });

      expect(result).toEqual({});
    });

    test("breaks if using $queryRaw", async () => {
      const result = await prisma.$transaction(async (tx) => {
        return tx.$queryRaw<unknown>`SELECT * FROM machine_user;`;
      });

      expect(result).toEqual({});
    });
  });
```

**Comment by Jolg42** [comment] 2023-06-07 10:38
Thanks @marcus13371337! If you can create a new issue, that would be great 🙌🏼

**Comment by marcus13371337** [comment] 2023-06-07 11:03
Issue created [here](https://github.com/prisma/prisma/issues/19651)

**Comment by marcus13371337** [comment] 2023-06-21 13:09
I was very excited and bumped my prisma verison to 4.16 but to realize that my extensions does still not work in transactions. Should I create another issue?
