### ISSUE TITLE
Occurance of Error: (0 , KSe.isError) is not a function

### ISSUE THREAD

**Issue by kumarchetan-1** [prisma/prisma#25951] opened 2024-12-30 17:27 UTC
### Bug description

This error is throwing when we are running `npx prisma init` command.

### Expected behavior

It should create a file _schema.prisma_ in _prisma_ directory.

### Prisma information

```prisma
// Add your schema.prisma
```

```ts
// Add your code using Prisma Client
```

### Environment & setup

- OS: 
- Database: 
- Node.js version: 

### Prisma Version

```
prisma                  : 6.1.0
@prisma/client          : Not found
Computed binaryTarget   : darwin-arm64
Operating System        : darwin
Architecture            : arm64
Node.js                 : v23.4.0
Query Engine (Node-API) : libquery-engine 11f085a2012c0f4778414c8db2651556ee0ef959 (at ../../../../../../opt/homebrew/lib/node_modules/prisma/node_modules/@prisma/engines/libquery_engine-darwin-arm64.dylib.node)
Schema Engine           : schema-engine-cli 11f085a2012c0f4778414c8db2651556ee0ef959 (at ../../../../../../opt/homebrew/lib/node_modules/prisma/node_modules/@prisma/engines/schema-engine-darwin-arm64)
Schema Wasm             : @prisma/prisma-schema-wasm 6.1.0-21.11f085a2012c0f4778414c8db2651556ee0ef959
Default Engines Hash    : 11f085a2012c0f4778414c8db2651556ee0ef959
Studio                  : 0.503.0
```

**Comment by aqrln** [comment] 2024-12-31 16:18
We only officially support Node.js LTS releases (i.e. 18.x, 20.x and 22.x). This problem with Node.js 23 is a known issue, so I'll close this one as a duplicate of https://github.com/prisma/prisma/issues/25463.

**Closed by aqrln** 2024-12-31 16:18 UTC
Labels: kind/bug
