### ISSUE TITLE
Fulltext search does not use index

### ISSUE THREAD

**Issue by joshribakoff-sm** [prisma/prisma#12334] opened 2022-03-14 22:01 UTC
### Bug description

I added a GIN index to a column, but Prisma does not use the precomputed index at all, and instead queries like this:

```
to_tsvector(concat_ws(' ', "public"."products"."name")) @@ to_tsquery('a')
```

### How to reproduce

```
CREATE INDEX product_name
   ON products USING GIN (to_tsvector('english', name));
```

```
prisma.products.findMany({where: {name: {search}})}
```

### Expected behavior

Instead I expect it to send this query, which uses the precomputed index:

```
"public"."products"."name" @@ to_tsquery('english', 'a')
```

Compared with the "actual" query above, I am omitting `to_tsvector` and passing `english`, per https://www.postgresql.org/docs/12/textsearch-tables.html

> only a query reference that uses the 2-argument version of to_tsvector with the same configuration name will use that index

### Prisma information

```
model products {
  id            String                       @id
  name String 
}
```

I also tried this, but it breaks Prisma completely (column cannot be inserted or updated, etc.)
```
model products {
  id            String                       @id
 name Unsupported("tsvector")
}
```

```
CREATE INDEX product_name
   ON products USING GIN (to_tsvector('english', name));
```

```
prisma.products.findMany({where: {name: {search}})}
```

### Environment & setup

- OS: Mac
- Database: Postgres
- Node.js version: Node 16

### Prisma Version

3.10.0

**Comment by joshribakoff-sm** [comment] 2022-03-14 22:04
Also, I would personally like to see https://github.com/prisma/prisma/issues/12279 prioritized over this one. With raw SQL expressions I could easily control this without rewriting my whole query into raw SQL

**Comment by janpio** [comment] 2022-03-14 22:46
Duplicate of https://github.com/prisma/prisma/issues/8950

**Closed by janpio** 2022-03-14 22:46 UTC
Labels: kind/bug
