### ISSUE TITLE
[Beta.2] Omission of relation field causes unclear rust error message at generate

### ISSUE THREAD

**Issue by alexvilchis** [prisma/prisma#2139] opened 2020-04-08 18:46 UTC
## Bug description
The generate module will fail with a rust error message if given a schema like this:
```

model HourRange {
  id          String   @default(cuid()) @id
  createdAt   DateTime @default(now())
  updatedAt   DateTime @updatedAt
  startHour   Int
  startMinute Int
  endHour     Int
  endMinute   Int
  dayId       String?
}


model Day {
  id         String      @default(cuid()) @id
  createdAt  DateTime    @default(now())
  updatedAt  DateTime    @updatedAt
  hourRanges HourRange[]
  day        String
}
```

Error message:
```
Error: Schema parsing
thread 'main' panicked at 'Expected exactly one data source field for ScalarFieldTemplate.', libs/prisma-models/src/datamodel_converter.rs:109:40
stack backtrace:
   0: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
   1: core::fmt::write
   2: std::io::Write::write_fmt
   3: std::panicking::default_hook::{{closure}}
   4: std::panicking::default_hook
   5: std::panicking::rust_panic_with_hook
   6: rust_begin_unwind
   7: core::panicking::panic_fmt
   8: core::option::expect_failed
   9: <core::iter::adapters::Map<I,F> as core::iter::traits::iterator::Iterator>::fold
  10: <core::iter::adapters::Map<I,F> as core::iter::traits::iterator::Iterator>::fold
  11: prisma_models::datamodel_converter::DatamodelConverter::convert
  12: query_engine::cli::CliCommand::dmmf
  13: query_engine::main::{{closure}}
  14: <std::future::GenFuture<T> as core::future::future::Future>::poll
  15: tokio::runtime::enter::Enter::block_on
  16: tokio::runtime::context::enter
  17: tokio::runtime::handle::Handle::enter
  18: query_engine::main
  19: std::rt::lang_start::{{closure}}
  20: std::panicking::try::do_call
  21: __rust_maybe_catch_panic
  22: std::rt::l
```

I believe this message can be improved to reflect the omission of the relation field (Day in this case).

## How to reproduce
Run `prisma generate` with a model that omits a relation field.

## Expected behavior
Error message that explains the schema error.

## Prisma information
- Version: 2.0.0-beta.2

## Environment & setup

- OS: MacOS Catalina
- Database: MySQL
- Prisma version: Beta.2
- Node.js version: v12.16.1

**Comment by greguintow** [comment] 2020-04-08 19:06
I think it's because of this commit [Link to the pull request #655](https://github.com/prisma/prisma-engines/pull/655/commits/a3d851cf85519a13e4b3d5b91f592a55f08f120d#diff-7371661d086f56496bfb72d13f494b29)

**Comment by pantharshit00** [comment] 2020-04-09 09:05
I can reproduce this. Schema validation needs to be improved for this case.

**Comment by tylerjbainbridge** [comment] 2020-04-10 20:20
Running into this now- with a large schema it can be very difficult to track the origin.

**Comment by alexvilchis** [comment] 2020-04-10 21:54
@tylerjbainbridge The way I quickly noticed this is by formatting the model with the VS Code Prisma extension twice. The first time it will add only the foreign key field (userId String, for example) to the models that need it. And the second time, it will try to add it again, which then will mark errors because  of the duplication.

**Comment by mavilein** [comment] 2020-04-17 14:42
fixed in: https://github.com/prisma/prisma-engines/pull/687

**Closed by mavilein** 2020-04-17 14:42 UTC
Labels: bug/2-confirmed, kind/bug, team/engines
