### ISSUE TITLE
`$extends` TS error: "Inferred type of this node exceeds the maximum length the compiler will serialize" with `"declaration": true` in `tsconfig`

### ISSUE THREAD

**Issue by mshd** [prisma/prisma#16536] opened 2022-11-30 04:50 UTC
`The inferred type of this node exceeds the maximum length the compiler will serialize. An explicit type annotation is needed.`

This error also showed up in another project.

![Screenshot from 2022-11-30 12-46-59](https://user-images.githubusercontent.com/17379661/204709905-938c5035-ac95-4cdb-b5bc-38c9ccf2a8b8.png)

[Source file](https://github.com/codeledge/entitree-monorepo/blob/main/apps/entitree-images/prisma/prismaClient.ts). To reproduce, check out main, and upgrade to Prisma 4.7

**Comment by eviefp** [comment] 2022-11-30 07:55
Can you confirm this is a regression from `4.6.x`, as in, it used to work and it's no longer working?

**Comment by mshd** [comment] 2022-11-30 08:29
> Can you confirm this is a regression from `4.6.x`, as in, it used to work and it's no longer working?

Um no, I'm just trying this feature for the first time as it was just released in version 4.7.0

**Comment by yovanoc** [comment] 2022-11-30 10:45
I confirm a regression, I have this too on just a new PrismaClient()

**Comment by miguelff** [comment] 2022-11-30 11:07
Hey, @mshd we need the schema to be able to reproduce the problem. So far, I have been able to successfully generate the client using the following schema:

```js
// This is your Prisma schema file,
// learn more about it in the docs: https://pris.ly/d/prisma-schema

generator client {
  provider        = "prisma-client-js"
  previewFeatures = ["clientExtensions"]
}

datasource db {
  provider = "sqlite"
  url      = env("DATABASE_URL")
}

model Image {
  id       Int     @id @default(autoincrement())
  imageUrl String? @unique
}
```

And to extend it to compute the image URL from the id:

```ts
import { PrismaClient } from '@prisma/client'
export const prismaClient = new PrismaClient().$extends({
    result: {
        image: {
            imageUrl: {
                needs: { id: true },
                compute: ({ id }) => {
                    return `https://storage.googleapis.com/entitree-images/${id}.jpg`;
                },
            }
        }
    }
})

async function main() {
    await prismaClient.image.create({ data: {} })
    const image = await prismaClient.image.findFirst()
    console.log(image?.imageUrl)
}

main()
    .then(async () => {
        await prismaClient.$disconnect()
    })
    .catch(async (e) => {
        console.error(e)
        await prismaClient.$disconnect()
        process.exit(1)
    })
```

<img width="472" alt="Screenshot 2022-11-30 at 12 06 23" src="https://user-images.githubusercontent.com/210307/204780423-47a132dc-38a9-4ac0-843d-a2e941725cd4.png">

**Comment by miguelff** [comment] 2022-11-30 11:45
I also tried using [This schema](https://github.com/codeledge/entitree-monorepo/blob/main/apps/entitree-images/prisma/schema.prisma), and both generation and execution against postgres worked correctly too.

**Comment by aqrln** [comment] 2022-11-30 12:12
Hi @mshd and thank you for your report! This error is related to failure to emit declarations — notice that despite the error, if you hover the mouse over the variable in your editor, you can still see that TypeScript infers a type. Adding

```json
"compilerOptions": {
  "declaration": false
}
```

to `tsconfig.json` prevents the issue, so this is the workaround for now. We will work on investigating and fixing the root cause, as of course the functionality should work regardless of this compiler option. Thanks for bringing this to our attention.

**Comment by aqrln** [comment] 2022-11-30 12:41
@yovanoc I can't reproduce this with just `new PrismaClient()` without `$extends` even under the conditions where this happens for the OP. Could you please open a new issue with details and reproduction? Thank you!

**Comment by yovanoc** [comment] 2022-11-30 12:51
@aqrln Ok can't reproduce after deleting node_modules and the project. But found another interesting error

https://github.com/prisma/prisma/issues/16545

**Comment by millsp** [comment] 2022-12-01 03:41
Hey @mshd I am not able to reproduce this exact same error. However, after taking a look at the generated types, I found that there is a clash with our `Metric` type (which is part of the `metrics` preview feature). What I am seeing is a broken `index.d.ts` file, but I cannot get the error you're showing. Could you:
1. Try to comment out any `Metric` related models/enums in your schema and re-generate to see if the error persists
2. If the error persists, could you give us instructions to reproduce this on your repository? Thanks

**Comment by mshd** [comment] 2022-12-01 04:30
@millsp I think it's only related to declaration: true.
@aqrln Thanks so much, this solved it for now.
@miguelff By using your repro.zip and adding declaration: true in tsconfig.json, you can reproduce the error.

**Comment by adamhamlin** [comment] 2023-07-07 18:47
Any movement here? Or a workaround other than `declaration: false`? (we're using a composite project, so I think a non-starter for us).

Currently seeing this against `4.16.x`. For reference, using a single extension specifying `$allModels` (and we have ~90 models, so it makes sense it would be a lengthy type):

<img width="933" alt="image" src="https://github.com/prisma/prisma/assets/18332856/ec872128-ed5e-4639-9a11-d12354b2a404">

**Comment by janpio** [comment] 2023-07-07 19:10
Any additional information you can give us @adamhamlin to reproduce and understand what is going on? We thought this was fixed in December :/

**Comment by adamhamlin** [comment] 2023-07-07 19:19
> Any additional information you can give us @adamhamlin to reproduce and understand what is going on? We thought this was fixed in December :/

@janpio I kind of alluded to it, but my suspicion is that the use of `$allModels` + a non-trivial number of models sort of explodes the type size. But I'll try to post a minimal reproducible example

**Comment by millsp** [comment] 2023-07-07 19:33
@adamhamlin You are correct, or at least from my first investigation performance issues are arising with how we deal with intersections, which are inefficient, on $allModels. Currently, I consider your issue to be 100% related to what's been reported at  https://github.com/prisma/prisma/issues/19999

**Comment by millsp** [comment] 2023-07-07 19:42
At the moment, my minimal reproduction is the following. Could you confirm this also fails on your end?

```ts
const prisma = new PrismaClient().$extends({
    model: {
        $allModels: {
            async paginate<T, A>(
                this: T, args: Prisma.Exact<A, Prisma.Args<T, "findMany">>
            ) {
                return {} as Prisma.Result<T, A, "findMany">
            }
        }
    }
})
```

**Comment by adamhamlin** [comment] 2023-07-07 19:46
> At the moment, my minimal reproduction is the following. Could you confirm this also fails on your end?
> 
> ```ts
> const prisma = new PrismaClient().$extends({
>     model: {
>         $allModels: {
>             async paginate<T, A>(
>                 this: T, args: Prisma.Exact<A, Prisma.Args<T, "findMany">>
>             ) {
>                 return {} as Prisma.Result<T, A, "findMany">
>             }
>         }
>     }
> })
> ```

@millsp yes, confirming the same issue using your example

**Comment by millsp** [comment] 2023-07-11 23:02
Hey @adamhamlin, we have a branch/fix for you to try over [here](https://github.com/prisma/prisma/issues/19999#issuecomment-1631613871). If you have some time, please give it a try and let me know if that helped.

**Comment by adamhamlin** [comment] 2023-07-12 14:36
> Hey @adamhamlin, we have a branch/fix for you to try over [here](https://github.com/prisma/prisma/issues/19999#issuecomment-1631613871). If you have some time, I'd love if you could give it a try and let me know if that helped. Thanks.

@millsp interestingly the new branch resolved the issue when using your minimal/toy example, but it did not when using my actual extension. I'll just go ahead and post my extension here in case that helps (it's more or less copied/adapted from [this](https://github.com/prisma/prisma/issues/8131#issuecomment-1486334609)). Also, no change if using `Prisma.defineExtension` or putting the object directly into `$extends(...)`.

```ts
const createManyAndReturnWithIdsExtension = Prisma.defineExtension((client) => {
    return client.$extends({
        name: 'createManyAndReturnWithIds',
        model: {
            $allModels: {
                /**
                 * Bulk insert the specified inputs and return with ID information
                 */
                async createManyAndReturnWithIds<T, A>(
                    this: T,
                    args: Prisma.Exact<A, Omit<Prisma.Args<T, 'createMany'>, 'skipDuplicates'>>,
                ): Promise<Array<Prisma.Result<T, A, 'create'> & { id: number }>> {
                    const thisCast = this as any;
                    const argsCast = args as any;

                    argsCast.data.forEach((record) => {
                        if (record.id) {
                            throw new Error('Cannot provide explicit IDs when using createManyAndReturnWithIds');
                        }
                    });

                    const ctx = Prisma.getExtensionContext(this);
                    const tableName = _.kebabCase(ctx.name);
                    const numRecords = argsCast.data.length;

                    const ids = (
                        await client.$queryRaw<Array<{ id: bigint }>>`
                            SELECT nextval(pg_get_serial_sequence(${tableName}, 'id')) AS id
                            FROM generate_series(1, ${numRecords})
                        `
                    ).map((row) => Number(row.id));

                    const newRecords = argsCast.data.map((record, idx) => {
                        return {
                            id: ids[idx],
                            ...record,
                        };
                    });

                    await thisCast.createMany({
                        ...argsCast,
                        data: newRecords,
                    });

                    return newRecords;
                },
            },
        },
    });
});

```

**Comment by millsp** [comment] 2023-07-12 14:53
Thanks for sharing, I'll take a look.

**Comment by liqMats** [comment] 2023-07-18 06:59
Hello, unfortunately we have a similar problem. Prisma client $extension with `$allModels` and `$allOperations` results in a JavaScript heap out of memory error. But this only happens when declarations is set to `true`. If declarations are set to `false`, it works. Using TypeScript 5.1.6.

Thanks for your effort and best regards

**Comment by millsp** [comment] 2023-07-21 21:38
Thanks for your reproduction @adamhamlin, I can confirm that it will be fixed.

**Closed** 2023-07-26 20:08 UTC
Labels: bug/2-confirmed, kind/bug, topic: prisma-client, topic: previewFeatures, team/client, topic: clientExtensions

**Comment by micobarac** [comment] 2025-02-20 11:41
I have the same problem again with Prisma 6.4.0 and NestJS 11.0.4.
