### ISSUE TITLE
Filtering ignores date keys

### ISSUE THREAD

**Issue by WesCossick** [prisma/prisma#4029] opened 2020-10-23 17:15 UTC
## Bug description

Prisma seems to be ignoring `Date` keys when filtering.

## How to reproduce

1. Create the following table with some sample data:

```sql
CREATE TABLE `stats` (
  `type` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL,
  `date` date NOT NULL COMMENT 'Interpreted as America/Chicago',
  `value` float NOT NULL,
  `processed` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO `stats` (`type`, `date`, `value`, `processed`) VALUES
('total_members', '2020-10-21', 12, '2020-10-23 16:27:57'),
('total_members', '2020-10-22', 13, '2020-10-23 16:27:37'),
('total_members', '2020-10-23', 14, '2020-10-23 16:27:57'),
('total_websites', '2020-10-21', 3, '2020-10-23 16:27:57'),
('total_websites', '2020-10-22', 4, '2020-10-23 16:27:37'),
('total_websites', '2020-10-23', 5, '2020-10-23 16:27:57');

ALTER TABLE `stats`
  ADD PRIMARY KEY (`type`,`date`);
```

2. Use the following Prisma schema:

```
generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "mysql"
  url      = env("DATABASE_URL")
}

model Stat {
  @@map("stats")

  type      String
  date      DateTime
  value     Float
  processed DateTime

  @@id([type, date])
}
```

3. Make the following Prisma call and log the result:

```ts
const stats = await prisma.stat.findMany({
	where: {
		date: new Date('2020-10-22'),
		type: 'total_websites',
	},
});

console.log(stats);
```

4. See output that contains other dates:

```
[
  {
    type: 'total_websites',
    date: 2020-10-21T00:00:00.000Z,
    value: 3,
    processed: 2020-10-23T16:27:57.000Z
  },
  {
    type: 'total_websites',
    date: 2020-10-22T00:00:00.000Z,
    value: 4,
    processed: 2020-10-23T16:27:37.000Z
  },
  {
    type: 'total_websites',
    date: 2020-10-23T00:00:00.000Z,
    value: 5,
    processed: 2020-10-23T16:27:57.000Z
  }
]
```

For what it's worth, explicitly using `AND` (like below) does not fix the issue.

```ts
where: {
	AND: {
		date: new Date('2020-10-22'),
		type: 'total_websites',
	}
},
```

## Expected behavior

To only return the `total_websites` result from `2020-10-22`:

```
[
  {
    type: 'total_websites',
    date: 2020-10-22T00:00:00.000Z,
    value: 4,
    processed: 2020-10-23T16:27:37.000Z
  }
]
```

## Environment & setup

- OS: Distroless
- Database: MySQL
- Node.js version: v12
- Prisma version: 2.9.0

**Comment by WesCossick** [comment] 2020-10-23 17:15
For the time being, I found that you can work around the issue by using `equals`:

```ts
const stats = await prisma.stat.findMany({
	where: {
		date: {
			equals: new Date('2020-10-22'),
		},
		type: 'total_websites',
	},
});

console.log(stats);
```

...which produces the correct result:

```
[
  {
    type: 'total_websites',
    date: 2020-10-22T00:00:00.000Z,
    value: 4,
    processed: 2020-10-23T16:27:37.000Z
  }
]
```

**Comment by WesCossick** [comment] 2020-11-02 18:38
Hey @janpio, this seems like a pretty significant bug (to me); is a fix being looked into?

**Comment by pantharshit00** [comment] 2020-11-02 20:40
Hi,

Thanks for reporting this! It has already been reported before, so I am going to close this as a duplicate of https://github.com/prisma/prisma/issues/3985#issuecomment-719595170

**Closed by pantharshit00** 2020-11-02 20:40 UTC
