### ISSUE TITLE
Error opening a TLS connection: unknown Cert Authority

### ISSUE THREAD

**Issue by danhollick** [prisma/prisma#2676] opened 2020-06-06 12:04 UTC
## Bug description

When connecting to a [ScaleGrid](https://scalegrid.io/) Postgres database with SSL enabled I get the following error despite having explicitly set `sslaccept=accept_invalid_certs` in the connection string:
```
Error opening a TLS connection: unknown Cert Authority
```

I'm pretty new to a lot of the SSL stuff so i'll walk through how I went about creating the certificates as it might be something I am doing wrong:

### Download root ca certificate from ScaleGrid.
ScaleGrid provides root certificates for the database server but they are **self signed**.
This is kept in the `prisma` folder and linked to in the connection url `sslcert=rootca.cert`

### Create self-signed client certificate
I followed the guide in [this blog post](https://msol.io/blog/tech/create-a-self-signed-ssl-certificate-with-openssl/).

1. Generate 2048-bit RSA private key:
`openssl genrsa -out key.pem 2048`
2. Generate a Certificate Signing Request:
`openssl req -new -sha256 -key key.pem -out csr.csr`
3. Generate a self-signed x509 certificate suitable for use on web servers.
`openssl req -x509 -sha256 -days 365 -key key.pem -in csr.csr -out certificate.pem`
4. Create  SSL identity file in PKCS12 as mentioned [here](https://github.com/prisma/prisma/issues/1433#issuecomment-578646902)
`openssl pkcs12 -export -out client-identity.p12 -inkey key.pem -in certificate.pem`
5. Connect to the database:
My connection string looked as follows:
```
postgresql://user:XX@serverAddress:port/dbname?&sslmode=require&sslaccept=accept_invalid_certs&sslidentity=client-identity.p12&sslpassword=XXXX&sslcert=rootca.cert&connection_limit=3"
```

### Prisma information
@prisma/client": "2.0.0-beta.7"

**Comment by danhollick** [comment] 2020-06-21 10:13
Ended up moving to CloudSQL from GCP and managed to get it working.

**Comment by pantharshit00** [comment] 2020-06-22 09:38
Hi @danhollick 

I can reproduce and I also don't see anything wrong in the steps that have mentioned.

**Comment by gevuong** [comment] 2021-01-13 20:25
I tried the steps listed to generate the PKCS12 file, thinking my issue may be from the way the PKCS12 file was generated, and used the following database connection string for MySQL RDS:
`DATABASE_URL="mysql://USER:PASS@xxx.rds.amazonaws.com:3306/DATABASE&sslidentity=client-identity.p12&sslpassword=SSLPASS&sslcert=server-ca-cert.pem"`

but it continues to throw the same error: `Error: P1000 Authentication failed`. 
I'm certain that the username, pw, host, port, database, and CA cert are correct because I tested it using DBeaver (a SQL Client GUI) to test connection and it worked. 

More info about my error and debugging process can be found in Discussion [here](https://github.com/prisma/prisma/discussions/5038).

**Comment by matthewmueller** [comment] 2021-02-22 15:59
@gevuong I think you'll need to set `sslaccept=accept_invalid_certs` since you're using a self-signed certificate.

**Comment by matthewmueller** [comment] 2021-02-24 13:02
If you use a cloud provider, you'll need to follow the instructions to generate a valid certificate on their end. For RDS, it's here: https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/UsingWithRDS.SSL.html. For GCP's Cloud SQL it's here: https://cloud.google.com/sql/docs/mysql/configure-ssl-instance

If you self-sign the certificate, you can still connect, but you'll need `sslaccept=accept_invalid_certs`, since your self-signed certificate is not recognized by Amazon or Google.

Closing because I think this is working as expected. Happy to re-open if you're still running into problems though after trying this.

**Comment by gevuong** [comment] 2021-02-27 16:16
Hi @matthewmueller, 

Instead of setting `sslmode=require`, I tried your suggestion and set `sslaccept=accept_invalid_certs`. This appeared to work when connecting to my own RDS MySQL instance, even when SSL was required for admin (discussed [here](https://github.com/prisma/prisma/issues/5132#issuecomment-769954608)). 

Now, the RDS MySQL instance I need to actually connect to won't be available till Monday. I will try again and follow up. But the results from this test look promising. My issue is related to #5132. 

Thanks for your feedback!

**Closed** 2021-03-01 11:29 UTC
Labels: bug/2-confirmed, kind/bug, team/client, topic: ssl
