### ISSUE TITLE
Ignore dynamically created tables that have nothing to do with prisma schema

### ISSUE THREAD

**Issue by markibanez** [prisma/prisma#19241] opened 2023-05-15 01:10 UTC
## Problem

I have tables in my database that have nothing to do with prisma. It is super frustrating when prisma wants to drop these tables when I do a db push. These tables btw are dynamically generated and have dynamic table names so db pull is not viable

## Suggested solution

Add a way to ignore certain tables via wild card. In my case, I want to be able to ignore table names like documents_3347074906 and documents_396766771 by specifying somewhere in the schema to ignore table with names documents_*

**Comment by Jolg42** [comment] 2023-05-31 10:07
Thanks for the context.
I'll close this as a duplicate of https://github.com/prisma/prisma/issues/8864 where I added your use case.

**Closed by Jolg42** 2023-05-31 10:07 UTC
Labels: kind/feature, team/schema, topic: prisma db push
