### ISSUE TITLE
IBM DB2 Support

### ISSUE THREAD

**Issue by norraell** [prisma/prisma#6605] opened 2021-04-15 19:07 UTC
Are you considering support for IBM DB2 for Prisma 2?

Thanks for your great efforts and this stellar product.

**Comment by pimeys** [comment] 2021-04-22 09:32
This would probably be easier to make due to db2 having a docker container and not that restrictive licensing on can you build a custom client to it compared to Oracle, so this might be easier to do...

The rust driver support is a bit iffy. There's a sync one that doesn't really fit to our async model. Although, we basically rewrote the whole SQL Server driver anyhow, so I don't see any other problems than time to make a DB2 connector to happen.

https://github.com/ibmdb/rust-ibm_db

**Comment by dorudumitru-hh** [comment] 2022-03-18 07:46
Any news on this?

**Comment by Ajetski** [comment] 2022-07-15 17:01
I'd be willing to contribute to making this possible

**Comment by BioSs54** [comment] 2024-09-10 16:09
I am also interested in the subject, I will delve deeper to understand how to implement this data source in Prisma

**Comment by jkomyno** [comment] 2024-12-11 10:35
Hi there,

As part of our effort to clean up our GitHub repo, we’re closing this issue to help focus on features and improvements that align with our focus areas and those of our community. 

If this is issue is still important to you, feel free to reopen the issue and get like-minded users to upvote as we will prioritize fixing issues based on community interest. If you do reopen the issue, please ensure that there’s a clear method for us to reproduce it. 

For more insight into our priorities and how we’re thinking about the future of the Prisma ORM, please see our recent blog post: https://www.prisma.io/blog/prisma-orm-manifesto.

Thank you for your understanding and support!

**Closed by jkomyno** 2024-12-11 10:35 UTC
Labels: kind/feature, topic: schema, topic: connector, domain/schema, domain/client
