### ISSUE TITLE
Upgrade to Prisma 4.0 → WeakRef is not defined

### ISSUE THREAD

**Issue by luminous8** [prisma/prisma#15478] opened 2022-09-23 06:20 UTC
### Bug description

Hi, 

I've recently switched to prisma 4 (didn't did it before because of the Explicit @unique constraints on one-to-one relations)

Everything works fine in my local env (my computer mac os 12.6 / node 16.5) but when I reload my server (An ubuntu VPS on linode - Ubuntu 22.04.1 LTS) I get this message

```
9|xxxxxxxxxx-back  | You have triggered an unhandledRejection, you may have forgotten to catch a Promise rejection:
9|xxxxxxxxxx-back  | ReferenceError: WeakRef is not defined
9|xxxxxxxxxx-back  |     at LibraryEngine.loadEngine (/srv/xxxxxxxxxx/api/node_modules/@prisma/client/runtime/index.js:26097:26)
9|xxxxxxxxxx-back  |     at async LibraryEngine.instantiateLibrary (/srv/xxxxxxxxxx/api/node_modules/@prisma/client/runtime/index.js:26051:5)
9|xxxxxxxxxx-back  |     at async LibraryEngine.getConfig (/srv/xxxxxxxxxx/api/node_modules/@prisma/client/runtime/index.js:26263:5)
9|xxxxxxxxxx-back  |     at async PrismaClient._getActiveProvider (/srv/xxxxxxxxxx/api/node_modules/@prisma/client/runtime/index.js:30525:30)
```

### How to reproduce

/

### Prisma information

/

### Environment & setup

- OS: Ubuntu 22.04.1 LTS
- Database: MySQL
- Node.js version: v16.15.0

### Prisma Version

```
prisma                  : 4.3.1
@prisma/client          : 4.3.1
Current platform        : debian-openssl-1.1.x
Query Engine (Node-API) : libquery-engine c875e43600dfe042452e0b868f7a48b817b9640b (at node_modules/@prisma/engines/libquery_engine-debian-openssl-1.1.x.so.node)
Migration Engine        : migration-engine-cli c875e43600dfe042452e0b868f7a48b817b9640b (at node_modules/@prisma/engines/migration-engine-debian-openssl-1.1.x)
Introspection Engine    : introspection-core c875e43600dfe042452e0b868f7a48b817b9640b (at node_modules/@prisma/engines/introspection-engine-debian-openssl-1.1.x)
Format Binary           : prisma-fmt c875e43600dfe042452e0b868f7a48b817b9640b (at node_modules/@prisma/engines/prisma-fmt-debian-openssl-1.1.x)
Format Wasm             : @prisma/prisma-fmt-wasm 4.3.0-32.c875e43600dfe042452e0b868f7a48b817b9640b
Default Engines Hash    : c875e43600dfe042452e0b868f7a48b817b9640b
Studio                  : 0.473.0
Preview Features        : fullTextSearch, fullTextIndex
```

**Comment by janpio** [comment] 2022-09-23 13:15
What node version are you using on that server? https://stackoverflow.com/questions/73415549/prisma-client-weakref-is-not-defined sounds related and seems to habe been cauesd by the Node version.

**Comment by luminous8** [comment] 2022-09-23 13:34
I've seen that ticket but I'm using node 16.15.0

**Comment by millsp** [comment] 2022-09-23 15:26
I am not able to reproduce this, could you please make sure that your server (or container) is indeed running with node 14.6+?

**Comment by luminous8** [comment] 2022-09-23 15:53
I'm pretty sure, I have a .nvnmrc file and did node -v from the server and the output was v16.15.0

**Comment by millsp** [comment] 2022-09-23 23:23
We can look into it if we have some form of reproduction that we can work and experiment with. We'll be able to help you with that.

**Comment by luminous8** [comment] 2022-09-25 08:55
Found the issue, I'm using pm2 and even if you update the node version, you need to refresh pm2 with pm2 update to use the node version installed

**Comment by millsp** [comment] 2022-09-26 13:27
Thanks for letting us now! I am therefore closing this issue.

**Closed by millsp** 2022-09-26 13:27 UTC
Labels: bug/0-unknown, kind/bug, tech/typescript, team/client, topic: node-api
