### ISSUE TITLE
Erro in migration

### ISSUE THREAD

**Issue by GabrielBarbosa07** [prisma/prisma#15352] opened 2022-09-15 22:35 UTC
Hi Prisma Team! The following command just crashed.

## Command

`migrate reset`

## Versions
      
| Name        | Version            |
|-------------|--------------------|
| Platform    | windows            | 
| Node        | v16.13.2           | 
| Prisma CLI  | 4.3.1              | 
| Engine      | c875e43600dfe042452e0b868f7a48b817b9640b| 

## Error
```
Error: Error in migration engine.
Reason: [migration-engine\connectors\sql-migration-connector\src\flavour\sqlite.rs:256:46] failed to truncate sqlite file: Os { code: 5, kind: PermissionDenied, message: "Acesso negado." }

Please create an issue with your `schema.prisma` at
https://github.com/prisma/prisma/issues/new

```

**Comment by denilsonpy** [comment] 2022-09-15 23:04
Hi Gabriel, the error asks you to open the issue with your `schema.prisma` (Make sure to remove your sensitive data).

The error informs that your bank access credentials are not valid, check if they are correct.

**Comment by denilsonpy** [comment] 2022-09-15 23:11
Duplicate of #13991

**Closed** 2022-09-16 08:45 UTC
