### ISSUE TITLE
[Feat]: Add Pagination Information for FindMany

### ISSUE THREAD

**Issue by johannesschobel** [prisma/prisma#5620] opened 2021-02-12 12:14 UTC
Dear all,

## Problem

For my application I will return data in a paginated way, i.e., the client can request via http query parameters the amount of items he would like to have on one page (like `?limit=20`). 
This parameter, along with filter information (i.e., `where: { isActive: true } }`) should be passed to the `prisma.findMany()` method.

However, the `findMany` method does not return information required for pagination, like the total amount of items found, and so on. This information, in turn, may be required for clients to automatically generate paginated lists or tables (i.e., _"currently showing items 21-40 of 200"_).

The most advanced solution, i have come up so far is using `transactions` and running 2 queries, like so:

```ts
async paginate(data: Prisma.PostFindManyArgs) {
    const [items, count] = await this.prisma.$transaction([
      this.prisma.post.findMany(data),
      this.prisma.post.count({ where: data.where }),
    ]);

    return {
      data: items,
      meta: {
        totalCount: count,
        count: items.length,
        totalPages: Math.ceil(count / data.take),
        page: (data.skip / data.take) + 1,
      },
    };
  }
```

Do you think, there is the need for an additional `paginate` method in prisma, like described above? Or is this "out of scope" because this can be easily added by the developer himself, if he needs to?

All the best and thanks a lot for reviewing this request,
Johannes

**Comment by pantharshit00** [comment] 2021-03-02 13:59
Hey @johannesschobel 

Sorry for the late reply here. I think what you are describing here is duplicate of https://github.com/prisma/prisma/issues/4990 so I am going to close this.

**Closed by pantharshit00** 2021-03-02 13:59 UTC

**Comment by johannesschobel** [comment] 2021-03-05 08:19
Dear @pantharshit00 ,

thanks for the response. Looks similar, yes. Do you have an estimated timeframe for the proposed solution?

All the best,
Johannes

**Comment by pantharshit00** [comment] 2021-03-06 10:44
It is not planned currently in the roadmap. Please subscribe to the issue for any updates.
