### ISSUE TITLE
Prisma query annotation for multi-tenant applications

### ISSUE THREAD

**Issue by florianmartens** [prisma/prisma#2851] opened 2020-06-25 10:50 UTC
## Problem
Multi-tenant solutions that share one database have become quite popular. However, this requires the ability to enforce strong isolation at the application level. Currently, no node ORM addresses this issue. 

## Suggested solution
The ability to annotate all queries for a model. The annotated model would become a TenantModel and queries like e. g. `findOne()` and `find()` are automatically annotated with an additional where condition e. g. `findOne({ where: { tenantId } })`

This would require all query methods to additionally call a method that can be overwritten like `getQueryset()` or `getQuery()`

**Comment by pantharshit00** [comment] 2020-06-26 06:35
Please checkout https://github.com/errorname/prisma-multi-tenant which implements some of these features.

**Comment by matthewmueller** [comment] 2020-07-08 12:32
I think this is a duplicate of #1187 ?

**Comment by pantharshit00** [comment] 2020-07-09 21:21
Yeah, I am going to close this as a duplicate of #1187

**Closed by pantharshit00** 2020-07-09 21:21 UTC
Labels: kind/feature
