### ISSUE TITLE
RustPanic on `db push`

### ISSUE THREAD

**Issue by beckerkadji** [prisma/prisma#23601] opened 2024-03-23 11:12 UTC
Hi Prisma Team! The following command just crashed.

## Command

`db push`

## Versions
      
| Name        | Version            |
|-------------|--------------------|
| Platform    | darwin             | 
| Node        | v20.10.0           | 
| Prisma CLI  | 5.6.0              | 
| Engine      | e95e739751f42d8ca026f6b910f5a2dc5adeaeee| 

## Error
```
RustPanic: Error in Schema engine.
Reason: [quaint/src/connector/result_set/result_row.rs:59:75] index out of bounds: the len is 1 but the index is 1

```

**Comment by Druue** [comment] 2024-03-27 11:54
Hey @beckerkadji,

Could you please provide us with your Prisma Schema and some more information about what you were doing in the schema up until `db push` crashed?
- Do you exclusively use `db push` or are there also migrations involved?

Thank you 🙏

**Comment by jkomyno** [comment] 2024-05-17 12:13
Hi @beckerkadji, since we got no reply with information that could help us reproducing this issue, we're closing this issue.
Should you or another user bump into the same problem and provide a reproduction, we will consider reopening this issue. Thanks!

**Closed by jkomyno** 2024-05-17 12:13 UTC
Labels: bug/0-unknown, kind/bug, team/schema, topic: prisma db push, topic: rust panic
