### ISSUE TITLE
Prisma Migrate: false positive drift detection on `foreign keys` when is used with an existing database

### ISSUE THREAD

**Issue by Gamote** [prisma/prisma#8124] opened 2021-07-06 22:20 UTC
### Bug description

When trying to use Prisma with an existing database I can get the migrations in sync without being forced to reset the database. I have a big DB schema but I will refer just to one table called `user`, because the issue is the same for all `foreign keys` and `unique indexes`.

After I run `prisma migrate dev --name initial-migration --create-only`, I get the following error:
```
? Drift detected: Your database schema is not in sync with your migration history.

[+] Added tables
  - user

[*] Changed the `user` table
  [+] Added unique index on columns (email)
  [+] Added foreign key on columns (profileId)

We need to reset the PostgreSQL database "my_database" at "localhost:5432".
Do you want to continue? All data will be lost. › (y/N)
```

The closest I got to the desired behaviour was:
1. Export just the data with `pg_dump`
2. `prisma migrate dev --name initial-migration --create-only` and press `y` to allow my database to be formatted
3. Import my data back

Now everything is working but I don't want to do this in production as we have a database with 100GB+ of data and I am not sure if something was affected.

Another weird thing is that, I have compared the database schema created by Prisma with my old one and no change. Same for `schema.prisma`. So I am inclined to think that it's a bug.

### Extra details
- After I fixed everything, as I described above, I've decided to delete the migrations + the prima migration table. And to try one more time to see if the database schema was the problem but I got the same error. So it seems that `migrate` is rejecting any foreign key if it's not in its migration files. Just an assumption, maybe it will help you.
- I use `DataGrip` as a viewer for the data and even with their [differences viewer](https://www.jetbrains.com/help/datagrip/differences-viewer-for-database-objects.html) tool I couldn't detect any difference between my old schema and the one pushed by Prisma.

PS: I can fix the "Added unique index on columns" error by changing the index name. But the one with `foreign key` I have no clue on what's wrong. As stated above, I have double checked my constrain vs the one generated by Prisma. 0 differences.

### Steps followed
1. `prisma init`
2. `prisma introspect` - the `schema.prisma` is generated
3. `prisma generate`
4. `prisma migrate dev --name initial-migration --create-only`

### Expected behavior

Is expected that Prisma will generate the migration file after running `prisma migrate dev --name initial-migration --create-only`.

### Prisma information

A simple table of `users` with an `id`, `email` (w/ a unique constraint) and a `profileId` which is a foreign key to the second table called `profiles` which contains an `id` and a `name` field.

### Environment & setup

- OS: Mac OS
- Database: PostgreSQL
- Node.js version: v14.17.2

### Prisma Version

Tested with `v2.23.0` until `v2.26.0`

**Comment by pantharshit00** [comment] 2021-07-29 15:10
Can you share a dump with us? It would be hard to reproduce this without it. Also, try again with latest version once.

**Comment by Gamote** [comment] 2021-08-06 11:06
> Can you share a dump with us? It would be hard to reproduce this without it. Also, try again with latest version once.

@pantharshit00 I've tried the last version, I have the same issue. I will try to create a new database and generate a dump. Although you can reproduce the issue with any existing database that have a table with a foreign key.

**Comment by tomhoule** [comment] 2021-08-31 08:24
>_Now everything is working but I don't want to do this in production as we have a database with 100GB+ of data and I am not sure if something was affected.

As an aside, in production you should never use `migrate dev`, but `migrate deploy`, which will only apply migrations, and never do things like detecting drift or asking you to reset the database.

**Comment by Gamote** [comment] 2021-09-15 18:35
Hi @pantharshit00 / @tomhoule, I finally got some time to get back to you. Below you can find a step-by-step guide to reproduce this issue entirely.

## ℹ️ Environment details
- OS: macOS Big Sur `v11.2.3 (20D91)`
- Node `v14.17.2`
- NPM `v6.14.13`
- Yarn `v1.22.10`
- PostgreSQL `v13.1`
- Prisma CLI `v2.23.0` to `v3.0.2`
- Prisma Client `v2.23.0` to `v3.0.2`

## ☑️ Steps

### Part 1 - The issue

1. Create a project: `mkdir prisma_issue && cd ./prisma_issue`
2. Install `prisma` and `@prisma/client`:
    ```
    yarn add -D prisma
    yarn add @prisma/client
    ```
3. Initialise Prisma: `yarn prisma init`
4. Create the PostgreSQL database: `CREATE DATABASE prisma_issue;`
5. Update the `.env` file with the database credentials:
    ```
    DATABASE_URL="postgresql://postgres:postgres@localhost:5432/prisma_issue?schema=public"`
    ```
6. Populate your database with the SQL dump provided below in order to simulate an existing PostgreSQL database. The SQL dump contains the schemas with one row in each table to demonstrate the data loss.
    <details>
      <summary>dump.sql</summary>

      ```postgresql
      --
      -- PostgreSQL database dump
      --
      
      -- Dumped from database version 13.1 (Debian 13.1-1.pgdg100+1)
      -- Dumped by pg_dump version 13.1
      
      SET statement_timeout = 0;
      SET lock_timeout = 0;
      SET idle_in_transaction_session_timeout = 0;
      SET client_encoding = 'UTF8';
      SET standard_conforming_strings = on;
      SELECT pg_catalog.set_config('search_path', '', false);
      SET check_function_bodies = false;
      SET xmloption = content;
      SET client_min_messages = warning;
      SET row_security = off;
      
      SET default_tablespace = '';
      
      SET default_table_access_method = heap;
      
      --
      -- Name: profiles; Type: TABLE; Schema: public; Owner: postgres
      --
      
      CREATE TABLE public.profiles (
      id integer NOT NULL,
      name character varying(50) NOT NULL,
      "userId" integer NOT NULL
      );
      
      
      ALTER TABLE public.profiles OWNER TO postgres;
      
      --
      -- Name: profiles_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
      --
      
      CREATE SEQUENCE public.profiles_id_seq
      AS integer
      START WITH 1
      INCREMENT BY 1
      NO MINVALUE
      NO MAXVALUE
      CACHE 1;
      
      
      ALTER TABLE public.profiles_id_seq OWNER TO postgres;
      
      --
      -- Name: profiles_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
      --
      
      ALTER SEQUENCE public.profiles_id_seq OWNED BY public.profiles.id;
      
      
      --
      -- Name: users; Type: TABLE; Schema: public; Owner: postgres
      --
      
      CREATE TABLE public.users (
      id integer NOT NULL,
      email character varying(250) NOT NULL
      );
      
      
      ALTER TABLE public.users OWNER TO postgres;
      
      --
      -- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
      --
      
      CREATE SEQUENCE public.users_id_seq
      AS integer
      START WITH 1
      INCREMENT BY 1
      NO MINVALUE
      NO MAXVALUE
      CACHE 1;
      
      
      ALTER TABLE public.users_id_seq OWNER TO postgres;
      
      --
      -- Name: users_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
      --
      
      ALTER SEQUENCE public.users_id_seq OWNED BY public.users.id;
      
      
      --
      -- Name: profiles id; Type: DEFAULT; Schema: public; Owner: postgres
      --
      
      ALTER TABLE ONLY public.profiles ALTER COLUMN id SET DEFAULT nextval('public.profiles_id_seq'::regclass);
      
      
      --
      -- Name: users id; Type: DEFAULT; Schema: public; Owner: postgres
      --
      
      ALTER TABLE ONLY public.users ALTER COLUMN id SET DEFAULT nextval('public.users_id_seq'::regclass);
      

      --
      -- Data for Name: profiles; Type: TABLE DATA; Schema: public; Owner: postgres
      --
      
      INSERT INTO public.profiles (id, name, "userId") VALUES (1, 'Support', 1);
      
      
      --
      -- Data for Name: users; Type: TABLE DATA; Schema: public; Owner: postgres
      --
      
      INSERT INTO public.users (id, email) VALUES (1, 'support@prisma.com');
      
      --
      -- Name: profiles_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
      --
      
      SELECT pg_catalog.setval('public.profiles_id_seq', 1, true);
      
      
      --
      -- Name: users_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
      --
      
      SELECT pg_catalog.setval('public.users_id_seq', 1, true);
      
      
      --
      -- Name: profiles profiles_pk; Type: CONSTRAINT; Schema: public; Owner: postgres
      --
      
      ALTER TABLE ONLY public.profiles
      ADD CONSTRAINT profiles_pk PRIMARY KEY (id);
      
      
      --
      -- Name: users users_pk; Type: CONSTRAINT; Schema: public; Owner: postgres
      --
      
      ALTER TABLE ONLY public.users
      ADD CONSTRAINT users_pk PRIMARY KEY (id);
      
      
      --
      -- Name: users_email_uindex; Type: INDEX; Schema: public; Owner: postgres
      --
      
      CREATE UNIQUE INDEX users_email_uindex ON public.users USING btree (email);
      
      
      --
      -- Name: profiles profiles_users_id_fk; Type: FK CONSTRAINT; Schema: public; Owner: postgres
      --
      
      ALTER TABLE ONLY public.profiles
      ADD CONSTRAINT profiles_users_id_fk FOREIGN KEY ("userId") REFERENCES public.users(id) ON DELETE CASCADE;
      
      
      --
      -- PostgreSQL database dump complete
      --
      ```
    </details>
7. Pull the database schema: `yarn prisma db pull`
    <details>
      <summary>schema.prisma</summary>

      ```
      generator client {
         provider = "prisma-client-js"
      }
      
      datasource db {
         provider = "postgresql"
         url      = env("DATABASE_URL")
      }
      
      model profiles {
         id     Int    @id(map: "profiles_pk") @default(autoincrement())
         name   String @db.VarChar(50)
         userId Int
         users  users  @relation(fields: [userId], references: [id], onDelete: Cascade, onUpdate: NoAction, map: "profiles_users_id_fk")
      }
      
      model users {
         id       Int        @id(map: "users_pk") @default(autoincrement())
         email    String     @unique(map: "users_email_uindex") @db.VarChar(250)
         profiles profiles[]
      }
      ```
    </details>
8. *(optional)* Generate the client: `yarn prisma generate`
9. Generate the initial migration: `yarn prisma migrate dev --name initial-migration --create-only`
    ```
    Environment variables loaded from .env
    Prisma schema loaded from prisma/schema.prisma
    Datasource "db": PostgreSQL database "prisma_issue", schema "public" at "localhost:5432"
    
    ? Drift detected: Your database schema is not in sync with your migration history.
    
    The following is a summary of the differences between the expected database schema given your migrations files, and the actual schema of the database.
    
    It should be understood as the set of changes to get from the expected schema to the actual schema.
    
    [+] Added tables
      - profiles
      - users
    
    [*] Changed the `profiles` table
      [+] Added foreign key on columns (userId)
    
    [*] Changed the `users` table
      [+] Added unique index on columns (email)
    
    
    We need to reset the PostgreSQL database "prisma_issue" at "localhost:5432".
    Do you want to continue? All data will be lost. › (y/N)
    ```

On our production environments we can't go further than this step, but in this case I will allow Prisma to reset the database. This way I can share with you the dump of the database generated by Prisma.

### Part 2 - The result

10. Press `y` to allow Prisma to reset the database. Here are the files generated in the `prisma/migrations` directory:
    <details>
      <summary>20210915154549_initial_migration/migration.sql</summary>

      ```postgresql
      -- CreateTable
      CREATE TABLE "profiles" (
      "id" SERIAL NOT NULL,
      "name" VARCHAR(50) NOT NULL,
      "userId" INTEGER NOT NULL,
      
          CONSTRAINT "profiles_pk" PRIMARY KEY ("id")
      );
      
      -- CreateTable
      CREATE TABLE "users" (
      "id" SERIAL NOT NULL,
      "email" VARCHAR(250) NOT NULL,
      
          CONSTRAINT "users_pk" PRIMARY KEY ("id")
      );
      
      -- CreateIndex
      CREATE UNIQUE INDEX "users_email_uindex" ON "users"("email");
      
      -- AddForeignKey
      ALTER TABLE "profiles" ADD CONSTRAINT "profiles_users_id_fk" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION;
      ```
    </details>
    <details>
      <summary>migration_lock.toml</summary>

      ```toml
      # Please do not edit this file manually
      # It should be added in your version-control system (i.e. Git)
      provider = "postgresql"
      ```
    </details>

11. Apply the migration: `yarn prisma migrate dev`. The database is now in sync with Prisma's schema. Here is the current state of the database:
    <details>
      <summary>dump.sql</summary>

      ```postgresql
      --
      -- PostgreSQL database dump
      --
      
      -- Dumped from database version 13.1 (Debian 13.1-1.pgdg100+1)
      -- Dumped by pg_dump version 13.1
      
      SET statement_timeout = 0;
      SET lock_timeout = 0;
      SET idle_in_transaction_session_timeout = 0;
      SET client_encoding = 'UTF8';
      SET standard_conforming_strings = on;
      SELECT pg_catalog.set_config('search_path', '', false);
      SET check_function_bodies = false;
      SET xmloption = content;
      SET client_min_messages = warning;
      SET row_security = off;
      
      SET default_tablespace = '';
      
      SET default_table_access_method = heap;
      
      --
      -- Name: _prisma_migrations; Type: TABLE; Schema: public; Owner: postgres
      --
      
      CREATE TABLE public._prisma_migrations (
      id character varying(36) NOT NULL,
      checksum character varying(64) NOT NULL,
      finished_at timestamp with time zone,
      migration_name character varying(255) NOT NULL,
      logs text,
      rolled_back_at timestamp with time zone,
      started_at timestamp with time zone DEFAULT now() NOT NULL,
      applied_steps_count integer DEFAULT 0 NOT NULL
      );
      
      
      ALTER TABLE public._prisma_migrations OWNER TO postgres;
      
      --
      -- Name: profiles; Type: TABLE; Schema: public; Owner: postgres
      --
      
      CREATE TABLE public.profiles (
      id integer NOT NULL,
      name character varying(50) NOT NULL,
      "userId" integer NOT NULL
      );
      
      
      ALTER TABLE public.profiles OWNER TO postgres;
      
      --
      -- Name: profiles_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
      --
      
      CREATE SEQUENCE public.profiles_id_seq
      AS integer
      START WITH 1
      INCREMENT BY 1
      NO MINVALUE
      NO MAXVALUE
      CACHE 1;
      
      
      ALTER TABLE public.profiles_id_seq OWNER TO postgres;
      
      --
      -- Name: profiles_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
      --
      
      ALTER SEQUENCE public.profiles_id_seq OWNED BY public.profiles.id;
      
      
      --
      -- Name: users; Type: TABLE; Schema: public; Owner: postgres
      --
      
      CREATE TABLE public.users (
      id integer NOT NULL,
      email character varying(250) NOT NULL
      );
      
      
      ALTER TABLE public.users OWNER TO postgres;
      
      --
      -- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
      --
      
      CREATE SEQUENCE public.users_id_seq
      AS integer
      START WITH 1
      INCREMENT BY 1
      NO MINVALUE
      NO MAXVALUE
      CACHE 1;
      
      
      ALTER TABLE public.users_id_seq OWNER TO postgres;
      
      --
      -- Name: users_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
      --
      
      ALTER SEQUENCE public.users_id_seq OWNED BY public.users.id;
      
      
      --
      -- Name: profiles id; Type: DEFAULT; Schema: public; Owner: postgres
      --
      
      ALTER TABLE ONLY public.profiles ALTER COLUMN id SET DEFAULT nextval('public.profiles_id_seq'::regclass);
      
      
      --
      -- Name: users id; Type: DEFAULT; Schema: public; Owner: postgres
      --
      
      ALTER TABLE ONLY public.users ALTER COLUMN id SET DEFAULT nextval('public.users_id_seq'::regclass);
      
      
      --
      -- Data for Name: _prisma_migrations; Type: TABLE DATA; Schema: public; Owner: postgres
      --
      
      INSERT INTO public._prisma_migrations (id, checksum, finished_at, migration_name, logs, rolled_back_at, started_at, applied_steps_count) VALUES ('91a3409f-fee2-4b77-9543-736863e5c5ed', '68e08b1b931b6886401eee502b6f03aebcf02807ce931fd453a30022eb3c0036', '2021-09-15 15:54:49.205199+00', '20210915154549_initial_migration', NULL, NULL, '2021-09-15 15:54:49.191328+00', 1);
      
      
      --
      -- Name: profiles_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
      --
      
      SELECT pg_catalog.setval('public.profiles_id_seq', 1, false);
      
      
      --
      -- Name: users_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
      --
      
      SELECT pg_catalog.setval('public.users_id_seq', 1, false);
      
      
      --
      -- Name: _prisma_migrations _prisma_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
      --
      
      ALTER TABLE ONLY public._prisma_migrations
      ADD CONSTRAINT _prisma_migrations_pkey PRIMARY KEY (id);
      
      
      --
      -- Name: profiles profiles_pk; Type: CONSTRAINT; Schema: public; Owner: postgres
      --
      
      ALTER TABLE ONLY public.profiles
      ADD CONSTRAINT profiles_pk PRIMARY KEY (id);
      
      
      --
      -- Name: users users_pk; Type: CONSTRAINT; Schema: public; Owner: postgres
      --
      
      ALTER TABLE ONLY public.users
      ADD CONSTRAINT users_pk PRIMARY KEY (id);
      
      
      --
      -- Name: users_email_uindex; Type: INDEX; Schema: public; Owner: postgres
      --
      
      CREATE UNIQUE INDEX users_email_uindex ON public.users USING btree (email);
      
      
      --
      -- Name: profiles profiles_users_id_fk; Type: FK CONSTRAINT; Schema: public; Owner: postgres
      --
      
      ALTER TABLE ONLY public.profiles
      ADD CONSTRAINT profiles_users_id_fk FOREIGN KEY ("userId") REFERENCES public.users(id) ON DELETE CASCADE;
      
      
      --
      -- PostgreSQL database dump complete
      --
      ```
    </details>

Now you will notice that beside the `_prisma_migrations` table the SQL dump is the same with the one provided at the **step 6**. So in theory, if we repeat the **steps 6** to **9** (using the SQL dump from **step 11** omitting the SQL commands related to the `_prisma_migrations` table) we should be able to recreate the issue presented in **step 9**. Let's try it just to make sure.

### Part 3 - The confirmation

12. Press `n` to stop Prisma resetting the database.

13. Delete the `prisma` directory: `rm -rf ./prisma`

14. Initialise Prisma: `yarn prisma init`

15. Drop the database and recreate it:

    ```postgresql
    DROP DATABASE prisma_issue;
    CREATE DATABASE prisma_issue;
    ```

16. Populate your database with the SQL dump provided at **step 11** but omit the SQL commands related to the `_prisma_migrations` table:
    <details>
      <summary>dump.sql</summary>

      ```postgresql
      --
      -- PostgreSQL database dump
      --
      
      -- Dumped from database version 13.1 (Debian 13.1-1.pgdg100+1)
      -- Dumped by pg_dump version 13.1
      
      SET statement_timeout = 0;
      SET lock_timeout = 0;
      SET idle_in_transaction_session_timeout = 0;
      SET client_encoding = 'UTF8';
      SET standard_conforming_strings = on;
      SELECT pg_catalog.set_config('search_path', '', false);
      SET check_function_bodies = false;
      SET xmloption = content;
      SET client_min_messages = warning;
      SET row_security = off;
      
      SET default_tablespace = '';
      
      SET default_table_access_method = heap;
      
      --
      -- Name: profiles; Type: TABLE; Schema: public; Owner: postgres
      --
      
      CREATE TABLE public.profiles (
      id integer NOT NULL,
      name character varying(50) NOT NULL,
      "userId" integer NOT NULL
      );
      
      
      ALTER TABLE public.profiles OWNER TO postgres;
      
      --
      -- Name: profiles_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
      --
      
      CREATE SEQUENCE public.profiles_id_seq
      AS integer
      START WITH 1
      INCREMENT BY 1
      NO MINVALUE
      NO MAXVALUE
      CACHE 1;
      
      
      ALTER TABLE public.profiles_id_seq OWNER TO postgres;
      
      --
      -- Name: profiles_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
      --
      
      ALTER SEQUENCE public.profiles_id_seq OWNED BY public.profiles.id;
      
      
      --
      -- Name: users; Type: TABLE; Schema: public; Owner: postgres
      --
      
      CREATE TABLE public.users (
      id integer NOT NULL,
      email character varying(250) NOT NULL
      );
      
      
      ALTER TABLE public.users OWNER TO postgres;
      
      --
      -- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
      --
      
      CREATE SEQUENCE public.users_id_seq
      AS integer
      START WITH 1
      INCREMENT BY 1
      NO MINVALUE
      NO MAXVALUE
      CACHE 1;
      
      
      ALTER TABLE public.users_id_seq OWNER TO postgres;
      
      --
      -- Name: users_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
      --
      
      ALTER SEQUENCE public.users_id_seq OWNED BY public.users.id;
      
      
      --
      -- Name: profiles id; Type: DEFAULT; Schema: public; Owner: postgres
      --
      
      ALTER TABLE ONLY public.profiles ALTER COLUMN id SET DEFAULT nextval('public.profiles_id_seq'::regclass);
      
      
      --
      -- Name: users id; Type: DEFAULT; Schema: public; Owner: postgres
      --
      
      ALTER TABLE ONLY public.users ALTER COLUMN id SET DEFAULT nextval('public.users_id_seq'::regclass);
      
      
      --
      -- Data for Name: profiles; Type: TABLE DATA; Schema: public; Owner: postgres
      --
      
      
      
      --
      -- Data for Name: users; Type: TABLE DATA; Schema: public; Owner: postgres
      --
      
      
      
      --
      -- Name: profiles_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
      --
      
      SELECT pg_catalog.setval('public.profiles_id_seq', 1, false);
      
      
      --
      -- Name: users_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
      --
      
      SELECT pg_catalog.setval('public.users_id_seq', 1, false);
      
      
      --
      -- Name: profiles profiles_pk; Type: CONSTRAINT; Schema: public; Owner: postgres
      --
      
      ALTER TABLE ONLY public.profiles
      ADD CONSTRAINT profiles_pk PRIMARY KEY (id);
      
      
      --
      -- Name: users users_pk; Type: CONSTRAINT; Schema: public; Owner: postgres
      --
      
      ALTER TABLE ONLY public.users
      ADD CONSTRAINT users_pk PRIMARY KEY (id);
      
      
      --
      -- Name: users_email_uindex; Type: INDEX; Schema: public; Owner: postgres
      --
      
      CREATE UNIQUE INDEX users_email_uindex ON public.users USING btree (email);
      
      
      --
      -- Name: profiles profiles_users_id_fk; Type: FK CONSTRAINT; Schema: public; Owner: postgres
      --
      
      ALTER TABLE ONLY public.profiles
      ADD CONSTRAINT profiles_users_id_fk FOREIGN KEY ("userId") REFERENCES public.users(id) ON DELETE CASCADE;
      
      
      --
      -- PostgreSQL database dump complete
      --
      ```
    </details>

17. Pull the database schema: `yarn prisma db pull`. The schema generated is the same with the one provided at **step 7**.
    <details>
      <summary>schema.prisma</summary>

      ```
      generator client {
        provider = "prisma-client-js"
      }
      
      datasource db {
        provider = "postgresql"
        url      = env("DATABASE_URL")
      }
      
      model profiles {
        id     Int    @id(map: "profiles_pk") @default(autoincrement())
        name   String @db.VarChar(50)
        userId Int
        users  users  @relation(fields: [userId], references: [id], onDelete: Cascade, onUpdate: NoAction, map: "profiles_users_id_fk")
      }
      
      model users {
        id       Int        @id(map: "users_pk") @default(autoincrement())
        email    String     @unique(map: "users_email_uindex") @db.VarChar(250)
        profiles profiles[]
      }
      ```
    </details>

18. *(optional)* Generate the client: `yarn prisma generate`

19. Generate the initial migration: `yarn prisma migrate dev --name initial-migration --create-only`. Yup, same issue:
    <details>
      <summary>Logs</summary>

      ```
      Environment variables loaded from .env
      Prisma schema loaded from prisma/schema.prisma
      Datasource "db": PostgreSQL database "prisma_issue", schema "public" at "localhost:5432"
      
      ? Drift detected: Your database schema is not in sync with your migration history.
      
      The following is a summary of the differences between the expected database schema given your migrations files, and the actual schema of the database.
      
      It should be understood as the set of changes to get from the expected schema to the actual schema.
      
      [+] Added tables
        - profiles
        - users
      
      [*] Changed the `profiles` table
        [+] Added foreign key on columns (userId)
      
      [*] Changed the `users` table
        [+] Added unique index on columns (email)
      
      
      We need to reset the PostgreSQL database "prisma_issue" at "localhost:5432".
      Do you want to continue? All data will be lost. › (y/N)
      ```
    </details>

At this point I thought that something created by Prisma is not getting dumped properly and that we lose important data on importing. So I decided to leave the database as it is (except for the `_prisma_migrations` table), delete the migration files and try again.

### Part 4 - The investigation

20. Delete the `migrations` directory: `rm -rf ./prisma/migrations`

21. Drop the `_prisma_migrations` table:

    ```postgresql
    DROP TABLE _prisma_migrations;
    ```

22. Generate the initial migration: `yarn prisma migrate dev --name initial-migration --create-only`. Nope, same issue:
    <details>
      <summary>Logs</summary>

      ```
      Environment variables loaded from .env
      Prisma schema loaded from prisma/schema.prisma
      Datasource "db": PostgreSQL database "prisma_issue", schema "public" at "localhost:5432"
      
      ? Drift detected: Your database schema is not in sync with your migration history.
      
      The following is a summary of the differences between the expected database schema given your migrations files, and the actual schema of the database.
      
      It should be understood as the set of changes to get from the expected schema to the actual schema.
      
      [+] Added tables
        - profiles
        - users
      
      [*] Changed the `profiles` table
        [+] Added foreign key on columns (userId)
      
      [*] Changed the `users` table
        [+] Added unique index on columns (email)
      
      
      We need to reset the PostgreSQL database "prisma_issue" at "localhost:5432".
      Do you want to continue? All data will be lost. › (y/N)
      ```
    </details>

The only way I got this to work was by faking the migration. See the steps below.

### Part 5 - The workaround

23. Press `y` to allow Prisma to reset the database. Generated files have the same content with the ones from **step 10** but different timestamps.

24. Apply the migration: `yarn prisma migrate dev`

25. Make an SQL dumb of the `_prisma_migrations` table.

26. Drop the database and recreate it:

    ```postgresql
    DROP DATABASE prisma_issue;
    CREATE DATABASE prisma_issue;
    ```

27. Repopulate it with the original data. Basically **step 6**.

28. Run the SQL dumb containing the `_prisma_migrations` table.
    <details>
      <summary>_prisma_migrations_dump.sql</summary>

      ```postgresql
      --
      -- PostgreSQL database dump
      --
      
      -- Dumped from database version 13.1 (Debian 13.1-1.pgdg100+1)
      -- Dumped by pg_dump version 13.1
      
      SET statement_timeout = 0;
      SET lock_timeout = 0;
      SET idle_in_transaction_session_timeout = 0;
      SET client_encoding = 'UTF8';
      SET standard_conforming_strings = on;
      SELECT pg_catalog.set_config('search_path', '', false);
      SET check_function_bodies = false;
      SET xmloption = content;
      SET client_min_messages = warning;
      SET row_security = off;
      
      SET default_tablespace = '';
      
      SET default_table_access_method = heap;
      
      --
      -- Name: _prisma_migrations; Type: TABLE; Schema: public; Owner: postgres
      --
      
      CREATE TABLE public._prisma_migrations (
      id character varying(36) NOT NULL,
      checksum character varying(64) NOT NULL,
      finished_at timestamp with time zone,
      migration_name character varying(255) NOT NULL,
      logs text,
      rolled_back_at timestamp with time zone,
      started_at timestamp with time zone DEFAULT now() NOT NULL,
      applied_steps_count integer DEFAULT 0 NOT NULL
      );
      
      
      ALTER TABLE public._prisma_migrations OWNER TO postgres;
      
      --
      -- Data for Name: _prisma_migrations; Type: TABLE DATA; Schema: public; Owner: postgres
      --
      
      INSERT INTO public._prisma_migrations (id, checksum, finished_at, migration_name, logs, rolled_back_at, started_at, applied_steps_count) VALUES ('eb8b85d3-494d-4286-a993-7e9c37f2a568', '68e08b1b931b6886401eee502b6f03aebcf02807ce931fd453a30022eb3c0036', '2021-09-15 17:26:00.752322+00', '20210915172537_initial_migration', NULL, NULL, '2021-09-15 17:26:00.736703+00', 1);
      
      
      --
      -- Name: _prisma_migrations _prisma_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
      --
      
      ALTER TABLE ONLY public._prisma_migrations
      ADD CONSTRAINT _prisma_migrations_pkey PRIMARY KEY (id);
      
      
      --
      -- PostgreSQL database dump complete
      --
      ```
    </details>

29. Try to apply the migration to check the status: `yarn prisma migrate dev`. Success! 😅
    ```
    Environment variables loaded from .env
    Prisma schema loaded from prisma/schema.prisma
    Datasource "db": PostgreSQL database "prisma_issue", schema "public" at "localhost:5432"
    
    Already in sync, no schema change or pending migration was found.
    
    ✔ Generated Prisma Client (3.0.2) to ./node_modules/@prisma/client in 60ms
    
    ✨  Done in 3.83s.
    ```

## 🤔 Some thoughts

Now, this workaround made me ask myself if I could do the same thing in production, but I've dismissed that idea immediately as we have several huge databases. It will be slow, dangerous, and it will introduce downtime.

The second thought was to push these migrations and manually run the `_prisma_migrations_dump.sql` file on the staging and production databases, but again, I don't think this will be a long term solution as I don't know if similar issues could occur in future migration.

Hope you have all the necessary data to recreate and solve the issue. 🤞🏻 I know our projects will be very happy to take full advantage of what Prisma has to offer.

**Thank your for this awesome OS library.**

**Comment by janpio** [comment] 2021-09-15 19:17
Wow, what an amazing post. I just skimmed it, someone else will read it in more detail, but a thought:
Are you trying to baseline your database in step 9? https://www.prisma.io/docs/guides/database/developing-with-prisma-migrate/baselining Or are you just trying to use the tools you know about in Prisma land and then you end up in the situation you describe?

**Comment by Gamote** [comment] 2021-09-15 19:38
> Wow, what an amazing post. I just skimmed it, someone else will read it in more detail, but a thought:
> Are you trying to baseline your database in step 9? https://www.prisma.io/docs/guides/database/developing-with-prisma-migrate/baselining Or are you just trying to use the tools you know about in Prisma land and then you end up in the situation you describe?

@janpio Yup, I'm trying to baseline.

**Comment by janpio** [comment] 2021-09-16 11:38
Then I think what is missing here after part 2 is you possibly using `prisma migrate resolve` to let Prisma know, in a new database with your existing tables, that the first migration represents the state of that and it should use _that_ migration to see if there is any drift. Then it would not detect any drift any more but just be happy and let you create and executed further migrations.

**Comment by tomhoule** [comment] 2021-09-16 11:39
Thanks for the detailed reproduction, let me try to understand and address the problem:

> Part 1 - The issue
>
> ...

All the steps here are working as expected. `migrate dev --create-only` asks you to reset because it sees that the database schema is not empty, but you have no migration file. It's one of these situations where the best way to get your database and your migrations back in sync is to reset, so that's why migrate dev asks for that.

It should not be a problem in production, because `migrate dev` shouldn't be used there, only `resolve` (for baselining), then `deploy` (for new migrations).

> Part 2

At this point I think my mental model may be diverging, because there are unexpected side-effects to moving the `_prisma_migrations` table. I suspect this line from the dump is derailing everything:

```sql
INSERT INTO public._prisma_migrations (id, checksum, finished_at, migration_name, logs, rolled_back_at, started_at, applied_steps_count) VALUES ('91a3409f-fee2-4b77-9543-736863e5c5ed', '68e08b1b931b6886401eee502b6f03aebcf02807ce931fd453a30022eb3c0036', '2021-09-15 15:54:49.205199+00', '20210915154549_initial_migration', NULL, NULL, '2021-09-15 15:54:49.191328+00', 1);
```
We should document this better, but the baseline migration should contain no data in general, and in particular no migrations from the migrations table.

> Part 3

So you did exactly what I was alluding to in Part 2, and the result is the expected one (same as in Part 1). If you do not want to reset the development database at this stage, one possibility would be going through the baselining flow (using `migrate resolve --applied <the-migration-name`) locally. We don't encourage that, because that leads to inconsistencies if the migration you marked as applied does not exactly match the current state of your dev database.

---

What I am taking as a conclusion from reading this is that `migrate dev` is working as expected, but it's super confusing. It matches a _lot_ of other feedback we had, so thanks for taking the time to expose your exact situation.

The foreign keys part of the drift _could_ be a bug, let's try to produce a minimal repro. I'll candidate the issue so we can spend time on this.

**Comment by tomhoule** [comment] 2021-09-16 11:41
> (I think the mention of the "foreign keys" in the drift message is just a normal part of the message when it does detect any drift - it is just listing tables and foreign keys separately)

Yes that's normal. It's an implementation detail, but migrate first creates tables without foreign keys, then add them in a second step. Where I think there might be something weird is in the original issue message, where it's not the whole schema that is detected as drift (that would be expected) but parts of it.

**Comment by tomhoule** [comment] 2021-09-16 11:50
Also just to reiterate, `migrate dev` is only to keep your disposable development databases in sync with your migrations history and creating new migration. It shouldn't be used on production databases. `migrate deploy` is what migrations are applied with, and it's much simpler than dev.

**Comment by Gamote** [comment] 2021-09-16 16:54
> What I am taking as a conclusion from reading this is that migrate dev is working as expected, but it's super confusing.

Ok, so I was trying baselining with the wrong tools...

I thought that (and it was wrong) the `yarn prisma migrate dev --name initial-migration --create-only` command will check the **current database schema** vs **schema.prisma** to see if they have the same structure and if yes, the files will be created and on `yarn prisma migrate dev` the `_prisma_migrations` table will be generated.

But now I totally get it, `resolve` is what I was looking for... So to achieve what I want it looks like I should:
1. Have the same DB structure locally as on production (which I do)
2. Run `yarn prisma migrate dev --name initial-migration` and reset the local database
3. On production run `prisma migrate resolve --applied XXXXXXXXXXX_initial-migration` and from here use `yarn prisma deploy` to push all the future locally created migrations.

Is it right?

**Comment by tomhoule** [comment] 2021-09-17 09:34
Exactly, yes

**Comment by Gamote** [comment] 2021-09-17 09:36
Ok, thank you for the info. 🙏 

Can I close the issue or do you have any other things to investigate in here?

**Comment by tomhoule** [comment] 2021-09-17 12:29
I think it can be closed, yes. We'll follow up with issues about ergonomics.

**Closed** 2021-09-17 14:37 UTC
Labels: bug/0-needs-info, kind/bug, process/candidate, team/migrations, topic: migrate dev
