### ISSUE TITLE
Support table which contains tsvector column

### ISSUE THREAD

**Issue by ejoebstl** [prisma/prisma#5034] opened 2020-03-14 16:59 UTC
I've attempted to query all items in a postgres table. The table contains a column of type `tsvector`, which seems to be the cause of this crash.

```
(node:52874) UnhandledPromiseRejectionWarning: Error: 
Invalid `prisma.article.findMany()` invocation in
/home/emi/Projects/prisma-playground/index.ts:5:16

  1 import { PrismaClient } from '@prisma/client'
  2 
  3 const prisma = new PrismaClient()
  4 
→ 5 prisma.article.findMany().then((x) => 

Error occurred during query execution:
ConnectorError(ConnectorError { user_facing_error: None, kind: QueryError(Error { kind: FromSql(19), cause: Some(WrongType { postgres: TsVector, rust: "core::option::Option<alloc::string::String>" }) }) })
    at PrismaClientFetcher.request (/home/emi/Projects/prisma-playground/node_modules/@prisma/client/runtime/index.js:1:47490)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:52874) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:52874) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Please note that it's very uncommon fetch the value of `tsvector` columns, it is rather used for building full text indices.

Here is the table schema, for your convenience: 

```
CREATE TABLE public."Article" (
	title text NOT NULL,
	text_index tsvector NULL,
);
```

Version information:

```
$ /home/emi/Projects/prisma-playground/node_modules/.bin/prisma2 version
prisma2@2.0.0-preview024, binary version: 377df4fe30aa992f13f1ba152cf83d5770bdbc85
```

**Comment by albertoperdomo** [comment] 2021-02-03 15:15
Related to https://github.com/prisma/prisma/issues/5027.

**Comment by janpio** [comment] 2021-05-29 17:25
Closing as duplicate of https://github.com/prisma/prisma/issues/5027 - please follow that issue.

**Closed by janpio** 2021-05-29 17:25 UTC
Labels: kind/feature, team/migrations, topic: native database types
