### ISSUE TITLE
Prisma seems to stringify unsigned BIGINT

### ISSUE THREAD

**Issue by apathetic** [prisma/prisma#20084] opened 2023-07-06 02:55 UTC
### Bug description

I'm getting an error when I try to upsert to a MYSQL db using Prisma. 

> Query parsing failure: A number used in the query does not fit into a 64 bit signed integer. Consider using `BigInt` as field type if you're trying to store large integers.

Notably, it's failing because the `id` I'm providing is larger than a _signed_ `bigint`, but smaller than an _unsigned_ `bigint`.  I don't know why I'm encountering this error with my schema, which has `@db.UnsignedBigInt`.

Also, I can confirm that the schema is correctly applied. A `show create table ` from the db: 
```sql
CREATE TABLE `Story` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  ...
```

What's interesting is that, when I log everything out / use DEBUG="*", I see the `bigint` that I've provided... but Prisma seems to be parsing it or transforming it somehow.  A snippet from the logs: 

```
Processing:  12345678931100828653n

  prisma:client:engines:resolveEnginePath  enginePath <...>/.prisma/client/libquery_engine-darwin.dylib.node +0ms
  prisma:client:libraryEngine  library starting +8ms
  prisma:client:libraryEngine  library started +218ms
  prisma:client  Prisma Client call: +250ms
  prisma:client  prisma.story.upsert({
  where: {
    id: '12345678931100828653'
  },
  update: {
    id: '12345678931100828653',
  ...
```

### How to reproduce

```javascript
  const id = BigInt(12345678931100828653);
  const story = {
    id,
    ...
  };

  console.log('Processing: ', story.id);

  await prisma.Story.upsert({
    where: { id: story.id },
    update: story,
    create: story
  });
```

### Expected behavior

The ORM should handle unsigned `bigint` s. 

### Prisma information

```prisma
model Story {
  id         BigInt    @db.UnsignedBigInt @id @default(autoincrement())
  ...
```

### Environment & setup

- OS: macOS
- Database: PlanetScale
- Node.js version: v18.4.0

### Prisma Version

```
4.16.2
```

**Comment by Jolg42** [comment] 2023-07-06 08:09
Note: probably a duplicate of
- https://github.com/prisma/prisma/issues/14231
- https://github.com/prisma/prisma/issues/14632

**Comment by apathetic** [comment] 2023-07-06 18:24
> Note: probably a duplicate of
> 
> * [Problem with using unsigned bigints with MySQL / MariaDB #14231](https://github.com/prisma/prisma/issues/14231)
> * [`bigint(20) UNSIGNED` got signed bigint bound error #14632](https://github.com/prisma/prisma/issues/14632)

Ah yes - looks like this is a dupe. Thanks 🙏

**Closed** 2023-07-06 23:20 UTC
Labels: bug/1-unconfirmed, kind/bug, topic: prisma-client, topic: bigints, team/client, topic: upsert, topic: database-provider/planetscale, topic: unsigned
