### ISSUE TITLE
read environment variables from  env.* files 

### ISSUE THREAD

**Issue by s-kris** [prisma/prisma#6184] opened 2021-03-19 13:15 UTC
## Problem
I have multiple .env files (env.development, env.production). As prisma seems to be reading from only .env file, it's not great dx and not safe to manually override just the DATABASE_URL variable with .env file.

**Comment by pantharshit00** [comment] 2021-03-19 13:53
Hi,

Thanks for reporting this! It has already been reported before, so I am going to close this as a duplicate of https://github.com/prisma/prisma/issues/3865

**Closed by pantharshit00** 2021-03-19 13:53 UTC
