### ISSUE TITLE
Error update Type-to-Type relation

### ISSUE THREAD

**Issue by Fi1osof** [prisma/prisma#1793] opened 2018-01-31 16:22 UTC
# Bug Report

**Current behavior**
prisma/1.1.2 (linux-x64) node-v9.4.0 local 

**Reproduction**
```Schema:
type Company {
  id: ID! @unique
  name: String!
  name_suffix: String
  # Company by Company
  parent: Company
}
```

Connect parent is OK
```
mutation setCompanyParent(
  $parent: ID!
  $child: ID!
){
  parent: updateCompany(
    data: {
      parent: {
        connect: {
          id: $parent
        }
      }
    }
    where: {
      id: $child
    }
  ){
    id
    name
  }
}
```

Result:
```
{
  "data": {
    "parent": {
      "id": "cjd398wos00bn0197z2ywbn0l",
      "name": "Dr Loder rgergregerg",
      "parent": {
        "id": "cjd398pkg00bj0197fn8ek1ir",
        "name": "Dr Loder"
      }
    }
  }
}
```

Update parent is error
```
mutation updateCompanyParent(
  $parent: ID!
  $child: ID!
){
  parent: updateCompany(
    data: {
      parent: {
        update: {
          data: {
            name:"Sdfsdf"
          }
          where: {
          	id: $parent
          }
        }
      }
    }
    where: {
      id: $child
    }
  ){
    id
    name
  }
}
```

Disconnect error to
```
mutation unsetCompanyParent(
  $parent: ID!
  $child: ID!
){
  parent: updateCompany(
    data: {
      parent: {
        disconnect: {
          id: $parent
        }
      }
    }
    where: {
      id: $child
    }
  ){
    id
    name
  }
}
```

Error:
```
{
  "data": {
    "parent": null
  },
  "errors": [
    {
      "locations": [
        {
          "line": 64,
          "column": 3
        }
      ],
      "path": [
        "parent"
      ],
      "code": 3041,
      "message": "The relation CompanyToCompany has no Node for the model Company with value `cjd398wos00bn0197z2ywbn0l` for id connected to a Node for the model Company with value `cjd398pkg00bj0197fn8ek1ir` for id",
      "requestId": "api:api:cjd39zibu00e201972wh74qet"
    }
  ]
}
```

Type to another Type requests is OK.

**Comment by Fi1osof** [comment] 2018-01-31 16:58
Ithink it`s bug because searching both child and parent by A column.
```
select 
	case when exists (
        select * from `sportpoisk@dev`.`_CompanyToCompany` 
        	where `A` = (
            	Select `id` from `sportpoisk@dev`.`Company`where `id` = 'cjd398pkg00bj0197fn8ek1ir'
			) 
        	AND `A` = (
            	Select `id` from `sportpoisk@dev`.`Company`where `id` = 'cjd398wos00bn0197z2ywbn0l')
    		) then 1 
    	else (
        select COLUMN_NAME from information_schema.columns where table_schema = 'sportpoisk@dev' AND TABLE_NAME = '_
CompanyToCompany'
    )end
```
Should be
```
select 
	case when exists (
        select * from `sportpoisk@dev`.`_CompanyToCompany` 
        	where `B` = (
            	Select `id` from `sportpoisk@dev`.`Company`where `id` = 'cjd398pkg00bj0197fn8ek1ir'
			) 
        	AND `A` = (
            	Select `id` from `sportpoisk@dev`.`Company`where `id` = 'cjd398wos00bn0197z2ywbn0l')
    		) then 1 
    	else (
        select COLUMN_NAME from information_schema.columns where table_schema = 'sportpoisk@dev' AND TABLE_NAME = '_
CompanyToCompany'
    )end
```

**Comment by carlgrundberg** [comment] 2018-02-13 13:19
@marktani has this been confirmed as a bug? I'm experiencing the same error when disconnecting a child from it's parent.  When I use the child id in both places I get no error, but the relation is not removed, so it seems like the bug is just checking A instead of B.

**Comment by marktani** [comment] 2018-04-13 13:38
Thanks for the report, @Fi1osof and @carlgrundberg. 
I can reproduce this on `1.6.0`. Note that the mutation API for `to-one` relations has been changed, which I considered in the following mutations.

```graphql
mutation d {
  parent: updateCompany(
    data: {
      parent: {
        update: {
          name: "abcd"
        }
      }
    }
    where: {
      id: "cjfxzsxu2xqrj0b26ilfkb7c7"
    }
  ){
    id
    name
  }
}
```

results in

> The relation CompanyToCompany has no node for the model Company with the value 'cjfxzsxu2xqrj0b26ilfkb7c7' for the field 'id' connected to a node for the model Company on your mutation path.

That happens when supplying the id of the child. If supplying the id of the parent, it works.

**Comment by mhabegger** [comment] 2019-01-20 07:08
Why are things closed if they are a confirmed bug ?

**Comment by pantharshit00** [comment] 2019-01-20 13:34
Sorry, we had some issue with the labels. That caused closing of this.

**Comment by pantharshit00** [comment] 2019-04-04 11:10
I can't reproduce now and API has also changed a bit so this issue is not relevant now. 

I used the following queries

```graphql
mutation unsetCompanyParent($child: ID!) {
  parent: updateCompany(
    data: { parent: { disconnect: true } }
    where: { id: $child }
  ) {
    id
    name
  }
}


mutation updateCompanyParent($child: ID!) {
  parent: updateCompany(
    data: { parent: { update: { name: "asd" } } }
    where: { id: $child }
  ) {
    id
    name
  }
}


mutation setCompanyParent(
  $parent: ID!
  $child: ID!
){
  parent: updateCompany(
    data: {
      parent: {
        connect: {
          id: $parent
        }
      }
    }
    where: {
      id: $child
    }
  ){
    id
    name
  }
}
```

**Closed by pantharshit00** 2019-04-04 11:11 UTC
Labels: area/api, bug/2-confirmed
