### ISSUE TITLE
Slow queries, connection pool timeout and can't create more than max_prepared_stmt_count statements

### ISSUE THREAD

**Issue by cclaflin89** [prisma/prisma#16235] opened 2022-11-11 05:33 UTC
### Bug description

With the default `connection_limit` and `pool_timeout` (not setting these parameter), it's getting the connection pool timeout issue consistently.

```
[GraphQLError [Object]: Timed out fetching a new connection from the connection pool. More info: http://pris.ly/d/connection-pool (Current connection pool timeout: 10, connection limit: 5)] 
```

After increasing these limits (`connection_limit=30&pool_timeout=60`), it sometimes get above error, but facing another issues.

1. Some time after the server starts(sometimes a couple of hours, or sometimes a day), the prisma queries starts getting slower whether they are simple or complicated.
Most of queries are run more than 2s and some takes more than 10s to run.

It is running on aws beanstalk and currently have 3 instances. It uses aws RDS (mysql) and in RDS performance monitoring page, it is reported all queries are run in less than 0.01s, cpu usage is under 5%, #of connections are under 100.
I also think the app is not getting heavy requests (generally under 2~3 requests/s per instance).

It's designed for mobile api and due to this issue, some contents in the mobile app takes too long to load and getting a lot of customer error reports, and had to restart the server instances (a few times a day)

2. Another issue is it's getting below mysql error.
```
Code: `1461`. Message: `Can't create more than max_prepared_stmt_count statements (current value: 16382)`
```

Due to above issues, I tried different combination of `connection_limit`, `pool_timeout`, and `statement_cache_size`, but no luck. 

I'm limited to debug the underlying issue and requesting help to troubleshoot the issue.

### How to reproduce

I don't think it can be easily reproduced in sample apps. It's also not easy to prepare a demo app that can reproduce the issue for me, but we can discuss.

### Expected behavior

It should not get the connection pool timeout or the mysql error, and expecting the queries run at least in 1s.

### Prisma information

```prisma
// Add your schema.prisma
// It's one simple model, but the query takes more than 2s when started slowing down

model Boost {
  id        Int      @id @default(autoincrement())
  userId    Int?
  startedAt DateTime @default(now()) @db.Timestamp(0)
  endAt     DateTime @default(now()) @db.Timestamp(0)
  user      User?     @relation(fields: [userId], references: [id], onDelete: Cascade, map: "boost_user_id")

  @@index([userId], map: "boost_user_id_idx")
}
```

```ts
// Add your code using Prisma Client
SELECT `DB`.`Boost`.`id`, `DB`.`Boost`.`userId`, `DB`.`Boost`.`startedAt`, `DB`.`Boost`.`endAt` FROM `DB`.`Boost` WHERE `DB`.`Boost`.`userId` = ? ORDER BY `DB`.`Boost`.`id` DESC LIMIT ? OFFSET ?
```

### Environment & setup

- OS:  Amazon Linux 4.17.13
- Database: MySQL 8.0.28
- Node.js version: 12.22.8

### Prisma Version

```
apollo-server-express 3.5.0
express 4.17.2
@prisma/client 3.7.0
nexus 1.0.0
nexus-plugin-prisma 0.35.0
```

**Comment by garrensmith** [comment] 2022-11-11 06:35
@cclaflin89 we had a connection pool issue we fixed in a later Prisma version. Could you update to `4.6.1` that should hopefully resolve your connection issues.

**Comment by cclaflin89** [comment] 2022-11-11 06:39
@garrensmith I tried to update prisma client to 4.6.0, but yarn install takes forever. And will it resolve the slow queries?

**Comment by garrensmith** [comment] 2022-11-11 07:19
@cclaflin89 can you show what the prisma query is that you are trying to execute? `4.6.1` should resolve the connection issue. I need to know more around the slow query issue before I could help.

**Comment by cclaflin89** [comment] 2022-11-11 07:39
@garrensmith It doesn't happen to specific queries, but here are some examples.

```
took 3184ms
prisma.notification.findMany({
            where: {
                notifierId: userId,
                appMode,
                object: {
                    entityType: {
                        in : ['ProfileLike', 'PostLike', 'PhotoLike']
                    }
                }
            },
            cursor: cursorValue,
            take: takeValue,
            skip: skipValue,
            orderBy: {
                createdAt: 'desc'
            }
        });
```

```
took 2690ms or more
const boosts = await ctx.prisma.boost.findMany({
                    where: {
                        userId: id
                    },
                    take: 1,
                    orderBy: {
                        id: 'desc'
                    }
                });
```

**Comment by SevInf** [comment] 2023-07-24 09:49
Hey @cclaflin89.
Did you have a chance to look at my previous message? It will help us to decide if it's a duplicate of #18975 or a sepaarte issue. If we don't hear back from you, I think we are going to assume it's the same issue and close this one as a duplicate.

Thank you!

**Comment by SevInf** [comment] 2023-07-31 13:42
Closing it as a duplicate of #18975 for now. Feel free to comment if you have any update on the issue.

**Closed by SevInf** 2023-07-31 13:42 UTC
Labels: bug/0-unknown, kind/bug, topic: mysql, team/client, topic: connection pool, topic: max_prepared_stmt_count

**Comment by pablojsx** [comment] 2024-01-21 18:04
![Captura de pantalla 2024-01-21 150352](https://github.com/prisma/prisma/assets/40902487/6dec189b-dcbb-4367-b278-de17e6c71d9e)
same here
