### ISSUE TITLE
Support for INCLUDE clauses on index definitions

### ISSUE THREAD

**Issue by tomhoule** [prisma/prisma#14699] opened 2022-08-08 14:00 UTC
MSSQL: https://docs.microsoft.com/en-us/sql/t-sql/statements/create-index-transact-sql?view=sql-server-ver16#include-column---n--	
Postgres: https://www.postgresql.org/docs/14/sql-createindex.html

Suggested PSL representation:

```prisma
@@index([a, b], include: [c])
```

## Related issues

- https://github.com/prisma/prisma-engines/pull/3108

**Comment by nvanbenschoten** [comment] 2022-09-21 20:38
Is this a duplicate of https://github.com/prisma/prisma/issues/8584?

**Comment by tomhoule** [comment] 2022-09-22 05:26
Looks like it indeed, thanks for pointing it out. Let's close this one as duplicate.

**Closed** 2022-09-22 05:26 UTC
Labels: kind/feature, topic: indexes, topic: sql server, team/schema, topic: postgresql, team/psl-wg
