### ISSUE TITLE
Timed out fetching a new connection, even with high connection_limit

### ISSUE THREAD

**Issue by arcticmatt** [prisma/prisma#12858] opened 2022-04-16 18:33 UTC
### Bug description

When I kick off many queries concurrently, I get this issue:

```
Timed out fetching a new connection from the connection pool. More info: http://pris.ly/d/connection-pool (Current connection pool timeout: 1, connection limit: 100)
```

I expect to NOT get this issue

### How to reproduce

```
async function example() {
  const prisma = getPrisma('some_url?connection_limit=100&pool_timeout=1');

  const range = [...Array(10).keys()];
  await Promise.all(range.map(async (val) => {
    await prisma.nft.findMany({take: 10});
  }));

  console.log("done!");
}
```

When I run this code, I get this error:

```
Timed out fetching a new connection from the connection pool. More info: http://pris.ly/d/connection-pool (Current connection pool timeout: 1, connection limit: 100)
```

However, based on the [Prisma docs](https://www.prisma.io/docs/concepts/components/prisma-client/working-with-prismaclient/connection-pool#how-the-connection-pool-works), it seems like I should not be running into this.

> If there are no idle connections available in the connection pool, the query engine opens additional database connections and adds them to the connection pool until the number of database connections reaches the limit defined by connection_limit.

Since my `connection_limit` (100) is much higher than the number of queries I'm kicking off (10), I don't get why I'm running into this issue.

Also, my DB supports a maximum of over 3000 connections

One more note: weirdly, if I use `connection_limit=1`, I get no errors

### Expected behavior

I expect all my queries to execute successfully

### Prisma information

Not needed

### Environment & setup

- OS: Mac OS
- Database: PostgreSQL
- Node.js version: 16.7.0

### Prisma Version

```
prisma                  : 3.8.1
@prisma/client          : 3.8.1
Current platform        : darwin
Query Engine (Node-API) : libquery-engine 34df67547cf5598f5a6cd3eb45f14ee70c3fb86f (at ../../node_modules/@prisma/engines/libquery_engine-darwin.dylib.node)
Migration Engine        : migration-engine-cli 34df67547cf5598f5a6cd3eb45f14ee70c3fb86f (at ../../node_modules/@prisma/engines/migration-engine-darwin)
Introspection Engine    : introspection-core 34df67547cf5598f5a6cd3eb45f14ee70c3fb86f (at ../../node_modules/@prisma/engines/introspection-engine-darwin)
Format Binary           : prisma-fmt 34df67547cf5598f5a6cd3eb45f14ee70c3fb86f (at ../../node_modules/@prisma/engines/prisma-fmt-darwin)
Default Engines Hash    : 34df67547cf5598f5a6cd3eb45f14ee70c3fb86f
Studio                  : 0.452.0
Preview Features        : interactiveTransactions
```

**Comment by garrensmith** [comment] 2022-04-20 15:25
Hi @arcticmatt, could you update to the latest version of Prisma. We have some fixes in the connection pool that could resolve this issue for you.

**Comment by janpio** [comment] 2022-04-20 17:21
Another thought: Is it possible that connection _creation_ plus query time sometimes take longer than the currently configured timeout? Often connection creation is pretty slow - but following queries then are fast. If you have this in a testing environment, it would be interesting to test out what happens when you temporarily increase the `pool_timeout` to a higher value and then log how long each Prisma Client query takes to answer.

**Comment by bit-cmdr** [comment] 2022-05-10 02:32
I am seeing this same behavior in version 3.13.0, this issue wasn't present in version 2.27.0

**Comment by janpio** [comment] 2022-05-12 19:20
Can you please open a new issue @bit-cmdr and actually describe your full setup and situation? Or is your code really that similar to what @arcticmatt posted that this would not be useful?

**Comment by chanlito** [comment] 2022-09-07 07:47
Any updates on this?

**Comment by janpio** [comment] 2022-09-07 09:07
No, as you can see above there are open questions and no working reproduction or further information supplied - we can not do anything with that state. 

Do you have more inforamtion @chanlito? Can you help us understand what is going on?

**Comment by chanlito** [comment] 2022-09-07 11:44
@janpio we're trying to figure out why all of the sudden, all our api starts getting pool timed out errors as well.

**Comment by janpio** [comment] 2022-09-07 14:05
Then I think you should open a new issue or discussion and indeed provide the needed information, then we are happy to help. This error can have a million reasons. This issue is not a good place to figure out your situation.

**Comment by chanlito** [comment] 2022-09-08 06:40
We've upgraded to 4.31 our `pool timed out` & `max_prepared_stmt_count` errors seems to have been resolved.

**Comment by janpio** [comment] 2022-09-23 16:45
Did you open these issues @chanlito and @bit-cmdr?

@arcticmatt Did you try updating your Prisma version? Or did the problem just go away?

**Comment by janpio** [comment] 2022-10-19 16:32
Hey @chanlito, @bit-cmdr and @arcticmatt - Can you help us out here? With the current information we unfortunately will need to close the issue as it is not enough to understand what is going on and reproduce it. Thanks!

**Comment by normandeaup** [comment] 2022-10-22 20:11
@janpio I'm having the same issue on https://kirka.io

My PostgreSQL database allows 1000 connections and with those Prisma options: connection_limit=800&pool_timeout=10, I'm randomly getting about once every 15 minutes, **Timed out fetching a new connection from the connection pool.** before Prisma reaches the 800 connections limit, if I understand correctly, Prisma would need to use all the connections available (800) before sending the Timeout error?

![image](https://user-images.githubusercontent.com/34383316/197360313-dc9b6015-58f2-4123-a0f7-6d82b74caacd.png)

My database logs also show that everything is fine, and the api server isn't lagging.

Version: 3.15.0 (I tried multiple version for prisma 3)

I can provide any information needed, this issue has been annoying me for a couple days now, let me know if you need me to test anything particular.

Thank you

**Comment by janpio** [comment] 2022-10-23 08:35
Please open a new issue for your problem @normandeaup and then we can discuss all the details of this.

> Prisma would need to use all the connections available (800) before sending the Timeout error?

Prisma can also send a timeout error any time the connection creation takes too long, that the timeout is hit. When all connections are in use, you will get a different error from the database that tells you explicitly about this.

First reply to your issue will be to use Prisma 4.x as we improved the connection pool behavior, and maybe also increase the timeout to see if for some (probably network) reason it just takes a bit longer sometimes to create the connection.

**Comment by janpio** [comment] 2022-11-25 00:16
Closing then until someone provides more information. Please comment or open a new issue. Thanks!

**Closed by janpio** 2022-11-25 00:16 UTC
Labels: bug/1-unconfirmed, kind/bug, topic: performance, tech/engines, topic: connections, team/client, topic: connection pool

**Comment by divmgl** [comment] 2023-11-03 02:09
Also running into this now, shame that there was no follow-up. I'm currently on GCP running into this problem on an async consumer we have. I tried setting `?connection_limit=10&pool_timeout=20` but the connection limit stays the same when the error is printed out.

**Comment by janpio** [comment] 2023-11-03 09:11
Please open a new issue and describe the full problem @divmgl. If the change to the connecion string does not have any effect, something is wrong.

**Comment by divmgl** [comment] 2023-11-03 17:04
> Please open a new issue and describe the full problem @divmgl. If the change to the connecion string does not have any effect, something is wrong.

We were incorrect. Connection limit and pool timeouts are working as intended and we were looking at the wrong logs. Apologies for the terse message, we're dealing with an outage and are trying to figure out what's wrong.

The issue is that our entire server process is crashing when running a very long query with Prisma. I'll open a separate issue if I can get some reproduction steps but it'll be difficult because we're dealing with production data and it only happens in a populated production environment. Anyhow, thanks again.

**Comment by janpio** [comment] 2023-11-03 17:33
All good, we know how frustrating it is when things just don't work as they should. We hope we can provide better tools here soon, but for now our only way to debug things is to ask questions and dig into things via comments.

Good luck!
