### ISSUE TITLE
Interactive transaction not seeing own updates

### ISSUE THREAD

**Issue by balabanshik** [prisma/prisma#20283] opened 2023-07-18 19:35 UTC
### Bug description

When in an interactive transaction, writes to rows are not seen by subsequent reads, at least sometimes.

### How to reproduce

Code snippet in question:
```
// This is inside an interactive transaction

      await txn.conditionReport.update({
        where: { tenantId_id: { tenantId, id: reportId } },
        data: { submittedAt: new Date() },
      });

      const t = await txn.conditionReport.findUniqueOrThrow({
        where: { tenantId_id: { tenantId, id: reportId } },
        select: { submittedAt: true },
      });

      console.log('**** submitted at: ', t.submittedAt);

== Output ==
**** submitted at:  null
```

### Expected behavior

After doing a write (and `await`-ing for it to finish), I would expect the subsequent read of the same row inside the same transaction to read the updated value. This behaviour is claimed by both Prisma documentation on transactions and PostgreSQL documentation on transactions.
Isolation levels could theoretically have some effect on this, but the bug has been observed on a local DB without any other concurrent operations going on.

### Prisma information

Relevant bits of the schema:
```prisma
model ConditionReport {
  tenant   Tenant @relation(fields: [tenantId], references: [id])
  tenantId Int
  id       Int    @default(autoincrement())

  room        InventoryRoom @relation(fields: [tenantId, roomId], references: [tenantId, id])
  roomId      Int
  bed         InventoryBed? @relation(fields: [tenantId, bedId], references: [tenantId, id])
  bedId       Int?
  residency   Residency?    @relation(fields: [tenantId, residencyId], references: [tenantId, id])
  residencyId Int?

  baseReport   ConditionReport? @relation(name: "Base", fields: [tenantId, baseReportId], references: [tenantId, id])
  baseReportId Int?

  assignee      Profile   @relation(fields: [tenantId, assigneeId], references: [tenantId, id])
  assigneeId    Int
  isAdminReport Boolean
  createdAt     DateTime
  submittedAt   DateTime?
  dueBy         DateTime?

  comment String?

  items        ConditionReportItem[]
  childReports ConditionReport[]     @relation("Base")

  @@id([tenantId, id])
  @@index([tenantId, roomId])
  @@index([tenantId, bedId])
  @@index([tenantId, residencyId])
  @@index([tenantId, assigneeId])
}

```

### Environment & setup

- OS: Windows
- Database: PostgreSQL
- Node.js version: v18.14.2

### Prisma Version

```
prisma                  : 4.16.2
@prisma/client          : 4.16.2
Current platform        : windows
Query Engine (Node-API) : libquery-engine 4bc8b6e1b66cb932731fb1bdbbc550d1e010de81 (at node_modules\@prisma\engines\query_engine-windows.dll.node)
Migration Engine        : migration-engine-cli 4bc8b6e1b66cb932731fb1bdbbc550d1e010de81 (at node_modules\@prisma\engines\migration-engine-windows.exe)
Format Wasm             : @prisma/prisma-fmt-wasm 4.16.1-1.4bc8b6e1b66cb932731fb1bdbbc550d1e010de81
Default Engines Hash    : 4bc8b6e1b66cb932731fb1bdbbc550d1e010de81
Studio                  : 0.484.0
Preview Features        : extendedWhereUnique, jsonProtocol
```

**Comment by millsp** [comment] 2023-07-19 01:16
Hey @balabanshik, I was not able to reproduce this. Could you please help us with a reproduction?

**Comment by janpio** [comment] 2023-08-06 12:35
Hey @balabanshik, did you see Pierre's response? Would be super helpful if you could give us some more information. Thanks!

**Comment by SevInf** [comment] 2023-08-18 12:54
Hey @balabanshik ,
 

With the lack of information and our inability to reproduce this issue, we're now closing it. Feel free to comment if you have any updates about it.
 
Thank you 🙏

**Closed by SevInf** 2023-08-18 12:54 UTC
Labels: bug/0-unknown, kind/bug, tech/engines, team/client, topic: interactiveTransactions
