### ISSUE TITLE
Prisma Introspection command transform string int column name into int in the prisma schema

### ISSUE THREAD

**Issue by Valetek** [prisma/prisma#20819] opened 2023-08-23 13:04 UTC
### Bug description

I m currently facing this situation when using prisma integration tools on a Mongo database where column field are string int 

Here is a exemple of what was given by prisma right after schema generation 

<img width="557" alt="image" src="https://github.com/prisma/prisma/assets/34715110/0a02bf9a-906b-4c46-8607-911e4aae5ec6">

And which data was used to generate this code

```json 
{ "_id" : "0320804239612", "images" : {  "2" : { "sizes" : { "full" : { "h" : 477, "w" : 2620 } } } } }
```

### How to reproduce

1. run prisma introspection command against a mongoDB with string int column name
2. look for the commented field in the prisma schema

### Expected behavior

string int should not be a int, maybe by adding the name of the parents to it

### Prisma information

```prisma
type ProductsImages {
  /// This field was commented out because of an invalid name. Please provide a valid one that matches [a-zA-Z][a-zA-Z0-9_]*
  // 1 ProductsImages1? @map("1")
  }
```

### Environment & setup

- OS: Ubuntu 21
- Database: MongoDB
- Node.js version: v20.4.0

### Prisma Version

```
v5.1.1
```

**Comment by janpio** [comment] 2023-08-23 21:08
Thanks, I don't think that is actually a bug - just how things work. In MongoDB you can have strings or ints as "keys" - which translate to field names in Prisma. But Prisma only has strings, and a string is still not allowed to _start_ with a number. But that is exactly the case for the field names `1` or `2`. You should be able to uncomment this and replace `1` with `one` for example - then this should work.

**Comment by Valetek** [comment] 2023-08-24 17:14
I already did edit the commented int field myself, as the mapping is done correctly it's do work

Just wanted to raise this "case" as it's can appear as a "bug", but yes it do work as intented 

Don't know if it could be customisable somewhere in the schema or prisma parameters, or just be added in the document as a "warning" for new users

Actually just a little warning could be the best I think

Thanks for the answer 👍

**Comment by janpio** [comment] 2023-08-24 23:19
Feel free to open a PR for our docs if you find a good place. I would not be sure where to put it honestly.

I am closing this issue for now as this is indeed not a bug but intended behavior right now, although not the most obvious one.

**Comment by Valetek** [comment] 2023-08-25 15:50
Sure, gonna do that next week 👍

**Closed** 2023-08-25 17:44 UTC
Labels: bug/1-unconfirmed, kind/bug, topic: re-introspection, tech/engines/introspection engine, team/schema, topic: mongodb
