### ISSUE TITLE
Prisma not seed on Docker container (Windows platform)

### ISSUE THREAD

**Issue by l2D** [prisma/prisma#7268] opened 2021-05-25 20:40 UTC
### Bug description

Hello @prisma,

After I asked about seeding on #7199 . I got a new problem with seeding on windows.
When I run ```npx prisma migrate dev``` and ```npx migrate reset``` , I got ```Running seed from "prisma\seed.js" ...```
but no response from seed files and the database has no update records. (either ```npx prisma db seed --preview-feature``` )

### How to reproduce

1. run ```docker compose -f docker-compose.yaml -f docker-compose.dev.yaml up -d --build```
2. after container run. ``` npx prisma migrate dev```
3. Run  ```npx prisma migrate reset ```
4. See an error (```Running seed from "prisma\seed.js" ...```)
5. try ```npx prisma db seed --preview-feature```
6. See an another error (something like ``` Your database has seed already ```)

### Expected behavior

🌱 Start seeding ...
✅ ✨ Created Restaurants : [Res1]
Seeding finished. 🌱

### Prisma information

```javascript 
//schema.prisma
model Restaurants {
  restaurant_id Int       @id @default(autoincrement())
  merchant_id   Int
  name          String
  image_url     String
  products      Json
  location_lat  Decimal   @db.Decimal(12, 7)
  location_lng  Decimal   @db.Decimal(12, 7)
  open_hour     String
  close_hour    String
  open_days     Json
  created_at    DateTime  @default(now())
  updated_at    DateTime  @updatedAt
  delete_flag   Boolean   @default(false)
  Merchant      Merchants @relation(fields: [merchant_id], references: [merchant_id])
  Jobs          Jobs[]
}
```
```javascript 
// seed.js
const restaurantsData = [
  {
    Merchant: {
      connect: { merchant_id: 1 },
    },
    name: "[Name1]",
    image_url: "PATH",
    products: [
      {
        product_id: 1,
        product_name: "[Food 1]",
        product_price: 50,
        product_discount: 0,
        product_image_url: "PATH",
        product_status: "Available",
      },
      {
        product_id: 2,
        product_name: "[Food 2]",
        product_price: 60,
        product_discount: 20,
        product_image_url: "PATH",
        product_status: "Available",
      },
      {
        product_id: 3,
        product_name: "[Food 3]",
        product_price: 60,
        product_discount: 0,
        product_image_url: "PATH",
        product_status: "Unavailable",
      },
    ],
    location_lat: 13.8649955,
    location_lng: 100.5196122,
    open_hour: "10.00 - 21.00",
    close_hour: "21.00 - 10.00",
    open_days: {
      Mon: false,
      Tue: true,
      Wed: true,
      Thu: true,
      Fri: true,
      Sat: true,
      Sun: true,
    },
  },
];
async function main() {
for (const data of restaurantsData) {
const restaurant = await prisma.restaurants.create({
data: data,
});
}


main()
.catch((e) => {
console.error(e);
process.exit(1);
})
.finally(async () => {
await prisma.$disconnect();
});
```
### Environment & setup

- OS: Windows
- Database: PostgreSQL 13
- Node.js version: 14.16.0 (on Docker container), 14.15.4 (on Windows)

```yaml
// DockerFile
FROM node:14.16

WORKDIR /app

COPY package.json .

ARG NODE_ENV
RUN if [ "$NODE_ENV" = "development" ]; \
    then npm install; \
    else npm install --production; \
    fi

COPY . ./

RUN npx prisma generate;

ENV HOST 0.0.0.0
ENV PORT 3000
EXPOSE 3000

CMD ["npm", "run", "dev"]
```

```yaml
// docker-compose.yaml
version: "3"
services:
    node:
        build: .
        restart: always
        ports:
            - "3000:3000"
        environment:
            - PORT=3000
        depends_on:
            - db
    db:
        image: postgres
        restart: always
        expose:
            - "5432"
        ports:
            - "5432:5432"
        environment:
            POSTGRES_DB: ####
            POSTGRES_USER: ####
            POSTGRES_PASSWORD: ####
            POSTGRES_HOST_AUTH: trust
        volumes:
            - postgres-db:/var/lib/postgresql/data
    redis:
        image: redis
        expose:
            - "6379"
        ports:
            - "6379:6379"


volumes:
    postgres-db:
    redis-service:
```
```yaml
// docker-compose.dev.yaml
version: "3"
services:
    node:
        build:
            context: .
            args:
                NODE_ENV: development
        volumes:
            - ./:/app
            - /app/node_modules
        environment:
            - NODE_ENV=development
            - POSTGRES_USER=####
            - POSTGRES_PASSWORD=####
        command: npm run dev
    db:
        environment:
            - POSTGRES_DB=###
            - POSTGRES_HOST_AUTH=trust
```

### Prisma Version

```bash
Environment variables loaded from .env
prisma               : 2.23.0
@prisma/client       : 2.23.0
Current platform     : windows
Query Engine         : query-engine adf5e8cba3daf12d456d911d72b6e9418681b28b (at node_modules\@prisma\engines\query-engine-windows.exe)
Migration Engine     : migration-engine-cli adf5e8cba3daf12d456d911d72b6e9418681b28b (at node_modules\@prisma\engines\migration-engine-windows.exe)
Introspection Engine : introspection-core adf5e8cba3daf12d456d911d72b6e9418681b28b (at node_modules\@prisma\engines\introspection-engine-windows.exe)
Format Binary        : prisma-fmt adf5e8cba3daf12d456d911d72b6e9418681b28b (at node_modules\@prisma\engines\prisma-fmt-windows.exe)
Default Engines Hash : adf5e8cba3daf12d456d911d72b6e9418681b28b
Studio               : 0.393.0
Preview Features     : filterJson
```

**Comment by pantharshit00** [comment] 2021-05-25 23:08
Can you please share you seed script? Ideally put the reproduction inside of a git repository.

**Comment by l2D** [comment] 2021-05-25 23:10
> Can you please share you seed script? Ideally put the reproduction inside of a git repository.


Here's my seed script.

```javascript

const restaurantsData = [
  {
    Merchant: {
      connect: { merchant_id: 1 },
    },
    name: "[Name1]",
    image_url: "PATH",
    products: [
      {
        product_id: 1,
        product_name: "[Food 1]",
        product_price: 50,
        product_discount: 0,
        product_image_url: "PATH",
        product_status: "Available",
      },
      {
        product_id: 2,
        product_name: "[Food 2]",
        product_price: 60,
        product_discount: 20,
        product_image_url: "PATH",
        product_status: "Available",
      },
      {
        product_id: 3,
        product_name: "[Food 3]",
        product_price: 60,
        product_discount: 0,
        product_image_url: "PATH",
        product_status: "Unavailable",
      },
    ],
    location_lat: 13.8649955,
    location_lng: 100.5196122,
    open_hour: "10.00 - 21.00",
    close_hour: "21.00 - 10.00",
    open_days: {
      Mon: false,
      Tue: true,
      Wed: true,
      Thu: true,
      Fri: true,
      Sat: true,
      Sun: true,
    },
  },
];
async function main() {
for (const data of restaurantsData) {
const restaurant = await prisma.restaurants.create({
data: data,
});
}


main()
.catch((e) => {
console.error(e);
process.exit(1);
})
.finally(async () => {
await prisma.$disconnect();
});

```

**Comment by bencun** [comment] 2021-05-26 22:59
Same happens for me on Windows running Prisma 2.23.0. Seed file doesn't do anything.
NestJS app using Prisma works well, tho.

**Comment by bencun** [comment] 2021-05-26 23:01
Reverting to 2.22.1 confirmed to fix the issue.

**Comment by l2D** [comment] 2021-05-27 10:09
> Reverting to 2.22.1 confirmed to fix the issue on Windows.

I revert to 2.22.0 on Windows, confirmed to fix this issue too. In macOS, 2.23.0 not faced this issue.

I Hope Prisma fixes this soon. 😄

**Comment by pantharshit00** [comment] 2021-05-27 14:26
I think this is a duplicate of https://github.com/prisma/prisma/issues/7176

I will still keep this open so that we can make sure this is also fixed after the first issue is patched.

**Comment by bencun** [comment] 2021-06-30 10:05
I see that this was added to the 2.26.0 milestone, was it fixed? Release notes do not seem to mention this issue.

**Comment by Jolg42** [comment] 2021-06-30 11:52
@bencun We use the milestone to gather what we want to work on usually but it also happens often that we don't get to close all issues in the milestone.
It's only an indication that we want to work on it.

The milestone is then useful once the issue has been closed to know in which milestone it got closed.

**Comment by stianl** [comment] 2021-08-05 15:45
Seeing this was added and removed from 2.27.0 milestone, and now 2.28.0 has been released maybe it could be added to 2.29.0 milestone?

**Comment by Jolg42** [comment] 2021-08-13 15:42
🗒️ We heard the feedback and we are planning a redesign of `db seed` (currently planned to be released early September)

How it will work is that a `prisma.seed` property in the package.json of your project will be required if you want to use `prisma db seed`.

This property is where you will be able to put any command you want to execute your seed script.

More info/details & how to try it out now in:
https://github.com/prisma/prisma/issues/8732

**Comment by janpio** [comment] 2021-09-09 12:22
The redesign of `db seed` was released with Prisma 3. Please try it, this problem should be gone.

**Closed by janpio** 2021-09-09 12:22 UTC
Labels: bug/1-repro-available, kind/bug, topic: windows, team/migrations, topic: db seed
