### ISSUE TITLE
Prisma $transaction

### ISSUE THREAD

**Issue by vrg-success** [prisma/prisma#3955] opened 2020-10-17 07:29 UTC
## Problem
Not flexibility

## Suggested solution
Make async callback for prisma.$transaction like in typeorm

## Alternatives
Case from real project
```ts
  await getConnection().transaction(async manager => {
    const insertedRow = await manager.insert(UsersEntity, {
      username,
      email,
      password: bcrypt.hashSync(password, USER_PASS_SALT),
    });
    const userId = insertedRow.raw[0].id;

    await manager.insert(SettingsNotificationsEntity, {
      userId,
      subs: true,
      followers: true,
      postComments: true,
      postLikes: true,
      messages: true,
    });
    await EmailService.sendConfirmEmail(req, userId, email, manager);
  });
```

## Additional context
If the feature will support, I will go crazy with happiness

**Comment by vrg-success** [comment] 2020-10-17 07:46
I really liked prisma, but without transaction I have go back to typeorm.... because transaction very important for me, I want cry...

**Comment by P4sca1** [comment] 2020-10-17 14:42
While its true that Prisma is less flexible with transactions than TypeORM, in your case the nested write feature of prisma might be what you want: https://www.prisma.io/docs/reference/tools-and-interfaces/prisma-client/transactions#how-prisma-client-supports-transactions-today

**Comment by pantharshit00** [comment] 2020-10-19 10:47
Hi,

Thanks for reporting this! It has already been reported before, so I am going to close this as a duplicate of https://github.com/prisma/prisma/issues/1844

It has quite a lot of discussion on this.

**Closed by pantharshit00** 2020-10-19 10:47 UTC
