### ISSUE TITLE
Strongly typed `Json` fields

### ISSUE THREAD

**Issue by ajmnz** [prisma/prisma#13446] opened 2022-05-22 17:26 UTC
## Problem

Right now, `Json` fields are loosely typed in order to match `JSON.parse`'s behavior, which is understandable. But what if we could define a new structure in the schema, such as `type` or `interface` and assign that instead of `Json`?

## Suggested solution

The new structure would pretty much resemble TypeScript's `interface`, but much more simplified and only allowing JSON primitive data types (string, number, object — another interface, array, boolean, nullable fields).

```prisma
// Probably mandatory to (automatically?) prefix them with `I` in order to not
// collide or create confusion with models

interface IChatMessage {
  sender    Number // or number
  message   String // or string
  timestamp Number
}

model Conversation {
  id           Int            @id @default(autoincrement())
  participants User[]
  messages     IChatMessage[]
}
```

And what about nested objects? We can simply assign another interface as the type definition.

```prisma
interface IChatMessageMedia {
  type String
  url  String?
}

interface IChatMessage {
  sender    Number
  message   String
  timestamp Number
  media     IChatMessageMedia[]
}
```

And `enum`s? Same thing!

```prisma
enum MediaType {
  IMAGE
  VIDEO
  LINK
}

interface IChatMessageMedia {
  type MediaType
  url  String?
}
```

## Gotchas

As far as I'm aware, Postgres and other databases don't allow strongly typed JSON fields, so Prisma would be drifting away from only enforcing database rules, which might be out of the scope of its purpose (?). One solution could be to only apply type-checking and use it only to improve DX instead of enforcing it on a database level, but then the developer still should manually validate that the type matches the actual data, which defeats the whole purpose of this feature.

Another issue would be schema file length. I don't think such a feature can be introduced or even planned without first tackling #2377. While `Json` fields might not generally be the most used within a database, having interfaces, enums and models all mixed in a single file can get messy really quick.

## Alternatives

You can just manually validate the data and give it the desired type.

```ts
const isValidMessage = (message: Prisma.JsonValue): message is ChatMessage => {
  return true;
}

const getChatMessages = async (chatId: number): Promise<ChatMessage[]> => {
  const rawMessages = await chatProvider.getMessages({ chatId });
  
  if (!Array.isArray(rawMessages)) {
    return [];
  }

  const messages: ChatMessage[] = [];

  for (const message of rawMessages) {
    if (isValidMessage(message)) {
      messages.push(message);
    }
  }

  return messages;
}

```

**Comment by pantharshit00** [comment] 2022-05-23 13:21
I think this is a duplicate of https://github.com/prisma/prisma/issues/3219

**Comment by pantharshit00** [comment] 2022-05-27 11:54
You can probably paste your suggestions over in that issue. I am going to close this now.

**Closed by pantharshit00** 2022-05-27 11:54 UTC
Labels: kind/feature, topic: json, team/schema
