### ISSUE TITLE
prisma/generated/type-graphql/resolvers/inputs/UserUpdateManyMutationInput.ts:3:21 - error TS2305: Module '"../../../../../node_modules/@prisma/client"' has no exported member 'InputJsonValue'.

### ISSUE THREAD

**Issue by drcyph3r** [prisma/prisma#5360] opened 2021-01-30 06:36 UTC
Upgraded the Prisma to version 2.15, ran the command `npx tsc` and the below error occured

## Bug description
@prisma/client"' has no exported member 'InputJsonValue.

## Prisma information

```
datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

generator client {
  binaryTargets = ["native", "debian-openssl-1.1.x"]
  provider      = "prisma-client-js"
}

generator typegraphql {
  provider = "typegraphql-prisma"
  output   = "../prisma/generated/type-graphql"
}

model User {
  id               String            @id @default(cuid())
  email            String            @unique
  name             String?
  profilePic       String?
  commitments      Commitment[]
  updates          Update[]
  comments         Comment[]
  commentReactions CommentReaction[]
  updateReactions  UpdateReaction[]
  notifications    Notifications[]   @relation("target-user")
  reached          Notifications[]   @relation("notified-user")
}
```

## Environment & setup

- OS:  Mac OS
- Database:  Postgres
- Node.js version: 14.15.4
- Prisma version: 2.15

```
@prisma/cli          : 2.14.0
@prisma/client       : 2.15.0
Current platform     : darwin
Query Engine         : query-engine 5d491261d382a2a5ffdc71de17072b0e409f1cc1 (at ../../../.config/yarn/global/node_modules/@prisma/engines/query-engine-darwin)
Migration Engine     : migration-engine-cli 5d491261d382a2a5ffdc71de17072b0e409f1cc1 (at ../../../.config/yarn/global/node_modules/@prisma/engines/migration-engine-darwin)
Introspection Engine : introspection-core 5d491261d382a2a5ffdc71de17072b0e409f1cc1 (at ../../../.config/yarn/global/node_modules/@prisma/engines/introspection-engine-darwin)
Format Binary        : prisma-fmt 5d491261d382a2a5ffdc71de17072b0e409f1cc1 (at ../../../.config/yarn/global/node_modules/@prisma/engines/prisma-fmt-darwin)
Studio               : 0.332.0
```

**Comment by drcyph3r** [comment] 2021-01-30 06:39
my previous prisma/client was 2.12 and it was working fine.

**Comment by Jolg42** [comment] 2021-02-02 15:03
Which version of `typegraphql-prisma` do you have?

Also it seems that the cli and client are not on the same version, that can cause problems sometimes:
```
@prisma/cli          : 2.14.0
@prisma/client       : 2.15.0
```

**Comment by pevers** [comment] 2021-02-19 16:44
This is caused by a bug regarding the relation name containing dashes. Related issue: https://github.com/prisma/prisma/issues/3193

Prisma will generate invalid JS if your constraint contains characters that are invalid JS properties (like dash or a dot).

**Comment by AmreeshTyagi** [comment] 2021-03-23 00:44
I confirm that it is not because of above bug. It is coming after upgrade. My prisma schema has no special characters in relation name or in map. Though default values has special characters `@default("en-us")`, but that should not be problem here.

My previous version was `@prisma/cli          : 2.15.0, 
@prisma/client       : 2.14.0`

Current upgraded version is `prisma               : 2.19.0
@prisma/client       : 2.19.0`

Getting this issue (No graphql): 
`Module '"../../../node_modules/@prisma/client"' has no exported member 'InputJsonValue'.`

**Comment by AmreeshTyagi** [comment] 2021-03-23 01:07
Simply replaced
`import type { InputJsonValue, JsonValue, Prisma } from '@prisma/client';`
with 
`import type { Prisma } from '@prisma/client';`

and using `Prisma.InputJsonValue` everywhere in my code.
Resolved.

**Comment by pantharshit00** [comment] 2021-05-16 13:24
Is anyone still facing this which is not related to https://github.com/prisma/prisma/issues/3193?

I guess we can close this one here and please comment if anyone is still facing this.

**Closed by pantharshit00** 2021-05-16 13:24 UTC
Labels: bug/0-needs-info, kind/bug, team/client, tech/typescript, topic: prisma-client
