### ISSUE TITLE
Query produces `WHERE` clause with 1=0 as condition

### ISSUE THREAD

**Issue by nikolasburk** [prisma/prisma#5575] opened 2021-02-10 13:10 UTC
## Bug description

I'm not sure if I'm misunderstanding something but I'm running into a weird issue where a Prisma Client `findMany` query produces a `WHERE` clause with `1=0` as a condition and consequently always fails and returns no records.
 
## How to reproduce

The following TypeScript script produces the query:

```ts
import { PrismaClient } from '@prisma/client'

const prisma = new PrismaClient({
  log: ['query'],
})

// A `main` function so that we can use async/await
async function main() {
  const searchString: string | null = null
  const posts = await prisma.post.findMany({
    where: {
      OR: [
        { title: { contains: searchString || undefined } },
        { content: { contains: searchString || undefined } },
      ],
    },
  })
  console.log(posts)
}

main()
  .catch((e) => {
    console.error(e)
    process.exit(1)
  })
  .finally(async () => {
    await prisma.$disconnect()
  })
```

Prisma Client submits the following SQL query:

```sql
SELECT `dev`.`Post`.`id`, `dev`.`Post`.`title`, `dev`.`Post`.`content`, `dev`.`Post`.`published`, `dev`.`Post`.`authorId` FROM `dev`.`Post` WHERE 1=0 LIMIT ? OFFSET ?
```

As far as I understand, the `1=0` condition in the `WHERE` clause means that there will never be any records returned because the `WHERE` clause will always be evaluated to `false`.

Is this behaviour intentional? 

## Expected behavior

In my case, I would have expected it to return all posts because no `searchString` has been provided.

## Prisma information

Prisma schema:

```prisma
generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "sqlite"
  url      = "file:./dev.db"
}

model User {
  id    Int     @id @default(autoincrement())
  email String  @unique
  name  String?
  posts Post[]
}

model Post {
  id        Int      @id @default(autoincrement())
  createdAt DateTime @default(now())
  updatedAt DateTime @updatedAt
  title     String
  content   String?
  published Boolean  @default(false)
  viewCount Int      @default(0)
  authorId  Int?
  author    User?    @relation(fields: [authorId], references: [id])
}
```

## Environment & setup

```
$ npx prisma -v
prisma               : 2.16.0
@prisma/client       : 2.16.0
Current platform     : darwin
Query Engine         : query-engine 854c8ba7f0dce66f115af36af24e66989a8c02a1 (at node_modules/@prisma/engines/query-engine-darwin)
Migration Engine     : migration-engine-cli 854c8ba7f0dce66f115af36af24e66989a8c02a1 (at node_modules/@prisma/engines/migration-engine-darwin)
Introspection Engine : introspection-core 854c8ba7f0dce66f115af36af24e66989a8c02a1 (at node_modules/@prisma/engines/introspection-engine-darwin)
Format Binary        : prisma-fmt 854c8ba7f0dce66f115af36af24e66989a8c02a1 (at node_modules/@prisma/engines/prisma-fmt-darwin)
Studio               : 0.346.0
```

**Comment by nikolasburk** [comment] 2021-02-10 13:10
[graphql-debug.zip](https://github.com/prisma/prisma/files/5958369/graphql-debug.zip)

**Comment by nikolasburk** [comment] 2021-02-10 13:30
Here's a runnable reproduction of the issue:

[script.zip](https://github.com/prisma/prisma/files/5958461/script.zip)

**Comment by nikolasburk** [comment] 2021-02-10 14:35
After some internal discussion, it seems like this behaviour, though maybe counterintuitive, is actually intentional according to this spec:

![image](https://user-images.githubusercontent.com/4058327/107523857-77514700-6bb5-11eb-9e23-a5e23720256e.png)

For a bit more context, I'm running into this problem in the context of a GraphQL server here: https://github.com/prisma/prisma-examples/blob/cleanup/remove-nexus-plugin-prisma/typescript/graphql/src/schema.ts#L38 

If no `searchString` argument is provided to the GraphQL query, all records should be returned. But with the current behaviour I'm unsure how this can possibly be achieved 🤔

**Comment by matthewmueller** [comment] 2021-02-24 17:45
Thanks @nikolasburk. There's also more information about this in [this comment](https://github.com/prisma/prisma/issues/4784#issuecomment-779845616). 

Closing as this is working as intended.

**Closed by matthewmueller** 2021-02-24 17:45 UTC
Labels: kind/improvement, team/client, topic: broken query
