### ISSUE TITLE
Error: Could not parse schema engine response: SyntaxError: Unexpected token '/'

### ISSUE THREAD

**Issue by OussemaChercheri** [prisma/prisma#25233] opened 2024-09-16 17:06 UTC
### Bug description

 I am encountering an issue when running npx prisma migrate dev --name init. The error message indicates a problem with parsing the schema engine response due to an unexpected token.

### How to reproduce

Create a Prisma schema file (schema.prisma) with the following content:

prisma

generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

model User {
  id              Int             @id @default(autoincrement())
  fullname        String
  avatarUrl       String?
  email           String          @unique
  password        String
  createdAt       DateTime        @default(now())
  updatedAt       DateTime        @updatedAt
  chatrooms       Chatroom[]      @relation("ChatroomUsers")
  messages        Message[]
  ChatroomUsers   ChatroomUsers[]
}

model Chatroom {
  id            Int             @id @default(autoincrement())
  name          String
  createdAt     DateTime        @default(now())
  updatedAt     DateTime        @updatedAt
  users         User[]          @relation("ChatroomUsers")
  messages      Message[]
  ChatroomUsers ChatroomUsers[]
}

model Message {
  id         Int      @id @default(autoincrement())
  content    String
  imageUrl   String?
  userId     Int
  chatroomId Int
  createdAt  DateTime @default(now())
  updatedAt  DateTime @updatedAt
  user       User     @relation(fields: [userId], references: [id], onDelete: Cascade)
  chatroom   Chatroom @relation(fields: [chatroomId], references: [id], onDelete: Cascade)
}

model ChatroomUsers {
  chatroomId Int
  userId     Int
  createdAt  DateTime @default(now())
  updatedAt  DateTime @updatedAt
  user       User     @relation(fields: [userId], references: [id], onDelete: Cascade)
  chatroom   Chatroom @relation(fields: [chatroomId], references: [id], onDelete: Cascade)

  @@id([chatroomId, userId])
}

Run npx prisma migrate dev --name init command.
Observe the error message.

### Expected behavior

The migration command should execute successfully and create the necessary migrations for the Prisma schema.

### Prisma information

generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

model User {
  id              Int             @id @default(autoincrement())
  fullname        String
  avatarUrl       String?
  email           String          @unique
  password        String
  createdAt       DateTime        @default(now())
  updatedAt       DateTime        @updatedAt
  chatrooms       Chatroom[]      @relation("ChatroomUsers")
  messages        Message[]
  ChatroomUsers   ChatroomUsers[]
}

model Chatroom {
  id            Int             @id @default(autoincrement())
  name          String
  createdAt     DateTime        @default(now())
  updatedAt     DateTime        @updatedAt
  users         User[]          @relation("ChatroomUsers")
  messages      Message[]
  ChatroomUsers ChatroomUsers[]
}

model Message {
  id         Int      @id @default(autoincrement())
  content    String
  imageUrl   String?
  userId     Int
  chatroomId Int
  createdAt  DateTime @default(now())
  updatedAt  DateTime @updatedAt
  user       User     @relation(fields: [userId], references: [id], onDelete: Cascade)
  chatroom   Chatroom @relation(fields: [chatroomId], references: [id], onDelete: Cascade)
}

model ChatroomUsers {
  chatroomId Int
  userId     Int
  createdAt  DateTime @default(now())
  updatedAt  DateTime @updatedAt
  user       User     @relation(fields: [userId], references: [id], onDelete: Cascade)
  chatroom   Chatroom @relation(fields: [chatroomId], references: [id], onDelete: Cascade)

  @@id([chatroomId, userId])
}

### Environment & setup

- OS: UBUNTU 22
- Database: PostgreSQL
- Node.js version: 20.17.0

### Prisma Version

```5.19.1

```

**Comment by SevInf** [comment] 2024-09-27 15:28
Hi @OussemaChercheri.
Please fill in `Prisma Information` box in our issue template. From the looks of it, it looks like your `@prisma/client` and `prisma` versions don't match.

**Comment by SevInf** [comment] 2024-10-15 15:16
Hey @OussemaChercheri ,
 

With the lack of information and our inability to reproduce this issue, we're now closing it. Feel free to comment if you have any updates about it.
 
Thank you 🙏

**Closed by SevInf** 2024-10-15 15:16 UTC
Labels: bug/0-unknown, kind/bug, domain/schema, topic: prisma migrate dev
