### ISSUE TITLE
Migrate in production - drift after adding data to db

### ISSUE THREAD

**Issue by yazer79** [prisma/prisma#7563] opened 2021-06-09 10:57 UTC
### Bug description

w10 - nodejs - mysql - prisma CLI - v2.23

I have a production database running locally for development and i had prisma fine and applied some migrations before
After adding a new model to the schema and using CLI trying to apply it with "npx prisma migrate dev", I got an error:
```
The migration `...........` failed.
- Drift detected: Your database schema is not in sync with your migration history.
```
The CLI warned that the migration cannot be added except after the problem was resolved, but I actually saw the new table being created in the db

### How to reproduce

1. After 4 successful migrations
2. Added relations
3. Added data to the db
3. Edited prisma schema to add a new table

### Expected behavior

The migration to proceed adding the table without errors
or the table is not created and the migration fails

### Environment & setup

- OS: W10
- Database: MySQL
- Node.js version: v12.14.1

### Prisma Version

 Prisma: 2.23

**Comment by yazer79** [comment] 2021-06-09 11:19
I tried rolling back and here is what happens via CLI:
$ npx prisma migrate resolve --rolled-back '.............'
-> marked as rolled back.
$ npx prisma migrate deploy
error->
Error: P3018

A migration failed to apply. New migrations can not be applied before the error is recovered from. Read more about how to 
resolve migration issues in a production database: https://pris.ly/d/migrate-resolve

Migration name: ......................

Database error code: 1050

Database error:
Table '..........' already exists

**Comment by tomhoule** [comment] 2021-06-09 11:56
Hi @yazer79 , thanks for the issue. Would it be possible to share your prisma schema and/or your migration files? It's hard to know if there is a bug without a path to reproduction of the issue.

**Comment by yazer79** [comment] 2021-06-09 12:12
Unfortunately I can't share the exact db and schema as it's a production website

**Comment by yazer79** [comment] 2021-06-09 12:15
When I do a rollback and delete the migration added table and do another prisma migrate deploy, I get error:
Error: P3018

A migration failed to apply. New migrations can not be applied before the error is recovered from. Read more about how to 
resolve migration issues in a production database: https://pris.ly/d/migrate-resolve

Migration name: .......

Database error code: 1452

Database error:
Cannot add or update a child row: a foreign key constraint fails (`db_name`.`#sql-6c8_f1e`, CONSTRAINT `#sql-6c8_f1e_ibfk_1` FOREIGN KEY (`foreign_id`) REFERENCES `table_xx` (`id`) ON DELETE CASCADE ON UPDATE CASCADE)

**Comment by yazer79** [comment] 2021-06-10 11:06
I have found the problems:

- Prisma create the model in db, then an error occurs in subsequent migration sql. Prisma doesn't check if the whole procedure is valid and rolls back as stated. Partially executed migration causes more errors later on.

- Prisma fails to execute the migration as in my db I have:
1. Missing "parent" ids that are listed as child foreign keys, causing failure in the join
2. Different mysql storage engine: Prisma creates new tables as MyISAM and my original tables are InnoDB.
These cause the  "Database error code: 1452" error - foreign key constraint fails

**Comment by janpio** [comment] 2021-09-09 09:53
What version of MySQL are/were you using @yazer79?

**Comment by yazer79** [comment] 2021-09-09 10:16
@janpio MySQL 5.7.19

**Comment by floelhoeffel** [comment] 2021-12-03 12:43
Hey @yazer79 - we have a proposal for some new migrate tooling that helps with failed migrations. Would be awesome if you would take a look and give us some feedback: https://github.com/prisma/prisma/issues/10561

**Comment by jkomyno** [comment] 2023-07-13 13:21
Hey @yazer79, can you please try to reproduce the issue you were running into with recent Prisma versions, like `prisma@4.16.2` or `prisma@5.0.0`? Looks like we have introduced improvements that hopefully addressed this issue along the years. Thanks!

**Comment by jkomyno** [comment] 2023-07-25 23:42
Hey @yazer79, could you please confirm that the comment above fixes this issue? Thanks.

**Comment by jkomyno** [comment] 2023-08-10 09:18
Hi @yazer79, as we were not able to get a response, we're closing this issue. Feel free to leave a comment asking to re-open it, should you have more info to share with us as per the comments above. Thanks!

**Closed by jkomyno** 2023-08-10 09:18 UTC
Labels: bug/0-unknown, kind/bug, topic: windows, tech/engines, status/needs-action, topic: mysql, team/schema, topic: drift
