### ISSUE TITLE
Prisma silently misses nested elements on MariaDB when it triggers a huge IN clause

### ISSUE THREAD

**Issue by alexandresoro** [prisma/prisma#12338] opened 2022-03-14 22:48 UTC
### Bug description

I stumbled upon an issue when trying to perform a `findMany` query that included nested relations. 

What I tried to achieve is to retrieve the list of number of "Donnee" per "Commune which are related via "Inventaire" and "Lieudit".

See my query below for reference.

The issue I am facing is that at no matching "Donnee" is returned at all. 
No log related to the engine is displayed at all, so it fails silently.

I have spent a lot of time investigating and found the following:
- I noticed that the latest generated query was containing a `WHERE` clause with thousands of values in the `IN` parameter. This is expected given the base I am using.
- While trying to find a similar issue, like https://github.com/prisma/prisma/issues/9132 I have found that setting `QUERY_BATCH_SIZE=999` was working while `QUERY_BATCH_SIZE=1000` was not.

So after a bit of digging with the engine code ( https://github.com/prisma/prisma-engines/pull/2293 ) and MariaDB doc, I found out that my issue was related to the following MariaDB parameter:
https://mariadb.com/docs/reference/mdb/system-variables/in_predicate_conversion_threshold/
which is 1000 by default.

This parameter seems specific to MariaDB >=10.3.
My understanding is that once the number of parameters in the `IN` clause reaches this threshold, it internally generates subqueries that so not seem to be handled properly by the Prisma engine.

In order to validate this, I changed this threshold to 10000 : `set in_predicate_conversion_threshold=10000;` and managed to have the request successfully working until `QUERY_BATCH_SIZE=9999`.

My understanding is that the default value for `QUERY_BATCH_SIZE` is currently set here : https://github.com/prisma/prisma-engines/blob/c9f86866d2fb27b2066e5447ee7f6f65c46c5707/query-engine/connectors/sql-query-connector/src/sql_info.rs#L48

So the issue could be resolved by lowering this value, however it would probably not make sense for MySQL users. Another way would be to investigate why these subqueries are not handled properly by the engine.

### How to reproduce

1. Setup any MariaDB instance with default parameters
2. Create 4 tables A, B , C and D where A is related to B , B to C and C to D
3. Perform any findManyQuery that includes nested elements and that will trigger a `IN` clause with more than 1000 parameters.

### Expected behavior

The nested related are properly returned without workaround on `QUERY_BATCH_SIZE`

### Prisma information

Relevant excerpt of the schema:

```

model Donnee {
  id                   Int                   @id @default(autoincrement()) @db.UnsignedMediumInt
  inventaireId         Int                   @map("inventaire_id") @db.UnsignedMediumInt
  inventaire           Inventaire            @relation(fields: [inventaireId], references: [id], onDelete: Cascade, onUpdate: Restrict, map: "fk_donnee_inventaire_id")

  @@index([inventaireId], map: "fk_donnee_inventaire_id")
}

model Inventaire {
  id                 Int                  @id @default(autoincrement()) @db.UnsignedMediumInt
  lieuDitId          Int                  @map("lieudit_id") @db.UnsignedMediumInt
  lieuDit            Lieudit              @relation(fields: [lieuDitId], references: [id], onDelete: Cascade, onUpdate: Restrict, map: "fk_inventaire_lieudit_id")
  donnee             Donnee[]

  @@index([lieuDitId], map: "fk_inventaire_lieudit_id")
}

model Lieudit {
  id                Int               @id @default(autoincrement()) @db.UnsignedMediumInt
  communeId         Int               @map("commune_id") @db.UnsignedSmallInt
  commune           Commune           @relation(fields: [communeId], references: [id], onDelete: Cascade, onUpdate: Restrict, map: "fk_lieudit_commune_id")
  inventaire        Inventaire[]

  @@unique([communeId, nom], map: "unique_commune_nom")
}

model Commune {
  id            Int         @id @default(autoincrement()) @db.UnsignedSmallInt
  lieudit       Lieudit[]
}

```

Example of query that silently fails by returning empty nested relations:

```
prisma.commune.findMany({
    select: {
      id: true,
      lieudit: {
        select: {
          inventaire: {
            select: {
              _count: {
                select: {
                  donnee: true
                }
              }
            }
          }
        }
      }
    }
  });
```

### Environment & setup

- OS: MacOS
- Database: MariaDB 10.7.3
- Node.js version: 16.14.0

### Prisma Version

```
prisma                  : 3.10.0
@prisma/client          : 3.10.0
Current platform        : darwin-arm64
Query Engine (Node-API) : libquery-engine 73e60b76d394f8d37d8ebd1f8918c79029f0db86 (at node_modules/@prisma/engines/libquery_engine-darwin-arm64.dylib.node)
Migration Engine        : migration-engine-cli 73e60b76d394f8d37d8ebd1f8918c79029f0db86 (at node_modules/@prisma/engines/migration-engine-darwin-arm64)
Introspection Engine    : introspection-core 73e60b76d394f8d37d8ebd1f8918c79029f0db86 (at node_modules/@prisma/engines/introspection-engine-darwin-arm64)
Format Binary           : prisma-fmt 73e60b76d394f8d37d8ebd1f8918c79029f0db86 (at node_modules/@prisma/engines/prisma-fmt-darwin-arm64)
Default Engines Hash    : 73e60b76d394f8d37d8ebd1f8918c79029f0db86
Studio                  : 0.458.0
```

**Comment by JonasRothmann** [comment] 2022-04-18 22:52
been experiencing this for 2 months too

**Comment by janpio** [comment] 2022-04-20 17:43
Can you help us to get to a reproduction? A seed script for the database schema that @alexandresoro shared would be most helpful for example. That would make it easier for us to confirm this, and then prioritize the work on it. Thanks.

**Comment by HendrikJan** [comment] 2022-05-13 20:19
I've got a reproduction here:

1. git clone https://github.com/HendrikJan/prisma-error-demo
2. docker-compose up
3. See the result which is `[null, null, null, null, null, null, null, null, null, null, ...]` while it should be an array of StaffMembers

Migration is done in `/prisma/migrations/20220513195949_initialize/migration.sql`

I don't know how to create seeders for Prisma so filling the database is done in `/index.ts`

The code that tries to get 1000 vacancies and the 1000 related staffMembers (and tails) is also in `/index.ts`

**Comment by antoineanorra** [comment] 2022-06-03 12:26
It's not only the subqueries, it's for all queries with >= 1000 WHERE IN.
However the query works with PhpMyAdmin & HeidiSQL.

So I tried MySQL 8 and it works.
So there is a problem with Prisma and MariaDB !

**Comment by JonasRothmann** [comment] 2022-06-03 13:00
> It's not only the subqueries, it's for all queries with >= 1000 WHERE IN. However the query works with PhpMyAdmin & HeidiSQL.
> 
> So I tried MySQL 8 and it works. So there is a problem with Prisma and MariaDB !

Settings following env variable solved it for me by the way: QUERY_BATCH_SIZE=999

**Comment by d-Rickyy-b** [comment] 2022-07-26 20:35
Hi, I randomly stumbled across this GitHub issue, because I was having similar issues with `WHERE IN ()` statements where the IN clause contains more than 1000 values. I found the MariaDB bug tracker and it seems like this is not related to any ORM (I am using Golang & Gorm), but only to MariaDB.

See https://jira.mariadb.org/browse/MDEV-27937

It seems to only affect prepared statements. The bug seems to be fixed in these versions: 10.3.35, 10.4.25, 10.5.16, 10.6.8, 10.7.4, 10.8.3.

Hope this helps.

**Comment by kkomelin** [comment] 2022-09-01 10:50
> Hi, I randomly stumbled across this GitHub issue, because I was having similar issues with WHERE IN () statements where the IN clause contains >= 1000 values. I found the MariaDB bug tracker and it seems like this is not related to any ORM (I am using Golang & Gorm), but only to MariaDB.
> See https://jira.mariadb.org/browse/MDEV-27937
> It seems to only affect prepared statements. The bug seems to be fixed in these versions: 10.3.35, 10.4.25, 10.5.16, 10.6.8, 10.7.4, 10.8.3.
> Hope this helps.

Thanks so much @d-Rickyy-b. I have just upgraded my db server from Mariadb 10.7.3 to 10.7.5 and it helped. Still testing things but so far so good.

**Comment by jkomyno** [comment] 2022-09-02 09:54
Closing this issue as it's independent of Prisma: it's instead related to a bug in some MariaDB versions.
[This reproduction](https://github.com/jkomyno/reprod-14539) runs test cases inspired by issue #14539 (which comprises #12338 and #14019 as well) on a "bugged" MariaDB instance (`mariadb:10.7.3`), on a "stable" MariaDB instance (`mariadb:10.8.4`), and on a recent MySQL instance (`mysql:8.0.30`).

Thanks to @kkomelin and @HendrikJan for their independent reproductions, and to @d-Rickyy-b for spotting https://jira.mariadb.org/browse/MDEV-27937.

**Closed by jkomyno** 2022-09-02 09:54 UTC
Labels: bug/1-unconfirmed, kind/bug, topic: mariadb, team/client, topic: query-crash, priority/high, size/unknown

**Comment by janpio** [comment] 2022-09-06 20:39
Just for bookkeeping: We consider this a duplicate of https://github.com/prisma/prisma/issues/14019

**Comment by pbrickell** [comment] 2022-09-17 07:59
Lot's of people referring to "Settings following env variable solved it for me by the way: QUERY_BATCH_SIZE=999". Where does this need to be set. Is it in the env where the code running the Prisma query is running or the DB env? I cannot find this documented anywhere.

**Comment by JonasRothmann** [comment] 2022-09-17 08:57
> Lot's of people referring to "Settings following env variable solved it for me by the way: QUERY_BATCH_SIZE=999". Where does this need to be set. Is it in the env where the code running the Prisma query is running or the DB env? I cannot find this documented anywhere.

_Ended up writing more of a guide to environment variables instead but should help most people who need to change the env variable. (Wrote on phone, sry if format is weird)_

Yes the environment variable would have to be set in your node.js application. This is usually done by using a .env file, depending on your setup you might need to use the npm package "dotenv". You can also change your script in the "scripts" section of your package.json file.

Say you have the following script:

`"scripts": {
  "run": "node server.js"
}`

You can change it to the following to set the environment variable:

`"scripts": {
  "run": "QUERY_BATCH_SIZE=999 node server.js"
}`

Utilising .env files for permanent/required env variables is very recommended as your package.json would quickly become hard to manage and you could expose secret information in your version control.

Using these files you should create a .env file with the following content (remember to add it to .gitignore or equivalent)

`QUERY_BATCH_SIZE=999`

Again depending on your specific setup you may or may not need to use dotenv. If you do then use the following after creating the .env file and installing the "dotenv-cli" npm package:

`"scripts": {
  "run": "dotenv -e .env node server.js"
}`

**Comment by janpio** [comment] 2022-09-17 14:38
Please read the previous comment https://github.com/prisma/prisma/issues/12338#issuecomment-1235303536. This issue is related to a MariaDB bug, that can be avoided by changing the version. No workaround needed at all. `QUERY_BATCH_SIZE` also is not a supported, official setting of Prisma so might just stop working one day. (It should also _never_ be necessary)

**Comment by JonasRothmann** [comment] 2022-09-17 17:31
> Please read the previous comment [#12338 (comment)](https://github.com/prisma/prisma/issues/12338#issuecomment-1235303536). This issue is related to a MariaDB bug, that can be avoided by changing the version. No workaround needed at all. `QUERY_BATCH_SIZE` also is not a supported, official setting of Prisma so might just stop working one day. (It should also _never_ be necessary)

Not everyone has the possibility of changing the version (we are slowly replacing a legacy app), so we have to use this as upgrading isn't an option.

Your statement is obvs relevant to everyone not in this situation.

**Comment by janpio** [comment] 2022-09-19 09:34
Ok, that is good input - we will take this into consideration when we mess with this feature. Sometimes easy to miss these details.
