### ISSUE TITLE
Ability to sort by average.

### ISSUE THREAD

**Issue by AndreyKarapetyan** [prisma/prisma#10825] opened 2021-12-22 13:50 UTC
Say you have a Post which can have many Rating-s. Add ability to 
orderBy: {
  rating: {
    _avg: 'desc'
  }
}

**Comment by pantharshit00** [comment] 2021-12-22 22:33
Hi,

Thanks for reporting this! It has already been reported before, so I am going to close this as a duplicate of https://github.com/prisma/prisma/issues/5837

**Closed by pantharshit00** 2021-12-22 22:33 UTC
