### ISSUE TITLE
Prisma client is forcing me to add many-to-one for relation

### ISSUE THREAD

**Issue by jeremygottfried** [prisma/prisma#6223] opened 2021-03-24 00:28 UTC
## Bug description

After I updated to prisma 2.19.0 from 2.18.0, my migrations are failing because I didn't have one-to-many relations explicitly defined in my schema. 

For example:
```prisma

model BrandImage {
  createdAt DateTime  @default(now()) @map(name: "created_at")
  updatedAt DateTime  @updatedAt @map(name: "updated_at")
  brand     Brand     @relation(fields: [brandId], references: [id])
  brandId   String // relation scalar field (used in the `@relation` attribute above)
  image     Image     @relation(fields: [imageId], references: [id])
  imageId   String // relation scalar field (used in the `@relation` attribute above)
  deletedAt DateTime? @map(name: "deleted_at")

  @@unique([brandId, imageId])
  @@map(name: "brand_images")
}

model Image {
  createdAt DateTime @default(now()) @map(name: "created_at")
  updatedAt DateTime @default(now()) @updatedAt @map(name: "updated_at")
  id        String   @id @default(uuid())
  filename  String
  key       String
  url       String   @unique
  creator   User?    @relation(fields: [creatorId], references: [id])
  creatorId String?  @map(name: "creator_id")

  @@map(name: "images")

  // PRISMA IS NOW FORCING ME TO ADD THIS
  BrandImages      BrandImage[]
}
```

If I run `prisma migrate` without adding `BrandImages` to the `Image` model, I get this error:
> error: Error validating field `image` in model `BrandImage`: The relation field `image` on Model `BrandImage` is missing an opposite relation field on the model `Image`. Either run `prisma format` or add it manually.

It's not really a breaking change per se because I can run `prisma format` to fix the schema, but I'd rather have the option of *not* explicitly adding all the associations to my `Image` model. Prisma was already annoying in this regard because it doesn't allow polymorphic associations, so this makes it even more of a pain to define a model that is associated with many models.

## Environment & setup

- OS: Mac OS
- Database: PostgreSQL
- Node.js version: 12
- Prisma version: 2.19.0

**Comment by pantharshit00** [comment] 2021-05-28 15:11
I don't think we will revert this as this is expected. Without adding, opposite side, we will have to make assumption whether `BrandImage` is one to one or one to many. Making this implicit has caused a lot of trouble in the past. 


In any case, this would be a duplicate of https://github.com/prisma/prisma/issues/2018

**Closed by pantharshit00** 2021-05-28 15:11 UTC
Labels: status/needs-action

**Comment by janpio** [comment] 2021-05-28 16:58
> Prisma was already annoying in this regard because it doesn't allow polymorphic associations, so this makes it even more of a pain to define a model that is associated with many models.

Please open an issue about this issue and what is causing this new error message if you have a strong point and want to have this changed. We take all feedback seriously, but need to have it explicitly spelled out to do so. Thanks.

**Comment by jeremygottfried** [comment] 2021-05-28 18:17
@janpio I think it's covered here: https://github.com/prisma/prisma/issues/2505
