### ISSUE TITLE
Prisma Client not finding query-engine after electron packages everything

### ISSUE THREAD

**Issue by Tiago-0liveira** [prisma/prisma#7630] opened 2021-06-13 00:33 UTC
So im making a project using electron and prisma (within others that we dont have to worry about) and i am trying to solve this error for hours, i cant get prisma to find the query-engine  executable, and i've tried a BUNCH of things i found on internet but still nothing.

here is me trying to set where prisma will find the query-engine (i found this "solution"(at least not for me) at https://github.com/prisma/prisma/discussions/5200) ![image](https://user-images.githubusercontent.com/13068239/121791688-7b818580-cbe4-11eb-9584-cb4679a74c1c.png)

this is my prisma schema ![image](https://user-images.githubusercontent.com/13068239/121791728-e8951b00-cbe4-11eb-83be-00b8fce27a40.png)

i am using webpack to compile both electron and react, so i set the schema generate to the electron folder that webpack will then compile to the "dist" folder, i used the [copy-webpack-plugin](https://webpack.js.org/plugins/copy-webpack-plugin/) to copy both schema.prisma and the query-engine-windows.exe (wich is my os) and after all that i get this error :
![image](https://user-images.githubusercontent.com/13068239/121791854-686fb500-cbe6-11eb-8cfb-74b0fbf37d3e.png)

event using this setup to get the app path and setting the path exactly where the qe (query-engine) is it says its not there..?? 
![image](https://user-images.githubusercontent.com/13068239/121792314-39a80d80-cbeb-11eb-9f1d-9e9a2bd2444f.png)
and to make sure i wasnt crazy i took the path it said it wanst there and threw it to the console and it ran!!! so something is wrong here. 
this is the output for this QE path change : 
![image](https://user-images.githubusercontent.com/13068239/121792348-8d1a5b80-cbeb-11eb-8525-2a3c760f2f3e.png)

if u have some questions about how some files look  u can check at my repo [this project repo](https://github.com/Tiago-0liveira/electron-prisma-react-ts-passwordkeeper) 

if u want to get the error and try out urself to get the error just clone the repo, do yarn and run "yarn package:exe" wich will compile the main folder wich is electron and then the src folder wich is react and right after that it will bundle it for electron and then execute it right away,
- `yarn package:exe` will webpack-(all)>electron->execute
thanks for reading everything 👍 hope u can help me 💯 .
If u need any more details just ask for them, Thanks in advance.

**Comment by janpio** [comment] 2021-06-14 09:05
Can you provide a small, minimal reproduction of your project setup without any workarounds applied so we can get an idea what you are trying to achieve? Obviously an object `__internal` is... internal and not really meant to be used for public things.

**Comment by Tiago-0liveira** [comment] 2021-06-14 11:17
So as u may have understood i am trying to run an electron app that uses prisma. 
Before the electron packages everything the project is compiled with webpack to the folder called `dist`
In the beginning prisma was throwing some errors like `where is schema.prisma ?` so i used [copy-webpack-plugin](https://webpack.js.org/plugins/copy-webpack-plugin/) and copied the file to the dist directory after webpack has finnished compiling.
After i fixed that problem prisma started to throw another one, this time is where is the query-engine ? So i did the same as i did with the schema.prisma file i used [copy-webpack-plugin](https://webpack.js.org/plugins/copy-webpack-plugin/) to copy the query-engine to the dist folder. This time i didn't succeed, the error kept appearing saying it isnt there (inside the app.asar folder) so i unpacked the asar and yes i found the query-engine right there, after searching a little bit i found out that files inside app.asar can only be read and not executed so i had to tell electron to asarUnpack that executable so i did the first workaround wich was on the `package.json` on the `
"build": { ..., "asarUnpack": [ "dist/query-engine-windows.exe" ] ,`  `dist/query-engine-windows.exe` is where the query engine is located, after that the query-engine-windows is now inside `app.asar.unpacked` instead of `app.asar`, i kept getting the same error so i searched a little bit more and i found this repo (https://github.com/prisma/prisma/discussions/5200) and that's why i did that part where i use `__internal` and set the binaryPath to the ´app.asar.unpacked/dist/query-engine-windows.exe`, still didnt work and at some point i got the error telling me to open an issue and so i did

**Comment by Tiago-0liveira** [comment] 2021-07-05 21:49
any progress so far ?

**Comment by janpio** [comment] 2021-07-06 21:57
It is unfortunately not very high on our priority list as this is an edge case (the query engine missing) on an edge case (using in Electron). As much as we would like to be able to investigate all the bug reports instantly, that is just not possible. Maybe some other user has the same problem, find this issue and then figures out a solution and posts about it as well 👍

**Comment by Tiago-0liveira** [comment] 2021-07-06 22:51
Sure! I completely understand but i just really wanted to have someone tell me something about it, i mean this kind of message u just sent me, at least now i know i probably wont have an answer so soon. Thanks!

**Comment by pantharshit00** [comment] 2021-07-12 12:33
Check binary permissions one and check if it is executable.

**Comment by Tiago-0liveira** [comment] 2021-07-12 12:43
how can i check those binary permissions ??
i tested and yes it is executable.

**Comment by pantharshit00** [comment] 2021-07-29 11:13
cc @madebysid Looks like electron binary packaging. Maybe you can help here.

**Comment by florianbepunkt** [comment] 2022-01-20 09:26
Here is a starter for Electron: https://github.com/florianbepunkt/electron-prisma

@janpio It is probably not an edge case. As far as I know, Prisma is the only viable solution for Electron/Tauri apps that need an SQLite query builder/ORM. At least for electron other solutions like TypeORM won't work in a secure Electron architecture (without nodeIntegration set to true). So this could be a USP for data-heavy local applications (I'm working on one, using prisma)

**Comment by janpio** [comment] 2022-01-20 10:01
From our perspective it still is an edge case, as <1% of our users probably want to do that. But I see how this could be an interesting use case to double down on. This is also why we are collecting these issues and the `electron` label and trying to help as good as possible already: https://github.com/prisma/prisma/issues?q=is%3Aopen+label%3A%22topic%3A+electron%22+sort%3Aupdated-desc

**Comment by garrensmith** [comment] 2022-08-22 13:25
@Tiago-0liveira could you try again? We fixed a bug in our __internal.

**Comment by millsp** [comment] 2023-05-16 21:05
`__internal.engine.binaryPath` is internal so it could break anytime. That said, the path must be fully specified and contain the engine file name as well, not just the directory. You can achieve the same thing by setting an env var before you initialize the Prisma Client https://www.prisma.io/docs/reference/api-reference/environment-variables-reference#prisma_query_engine_library. It also needs a fully specified path.

Also, the Prisma Client will first look at `__dirname` then fallback to `process.cwd()` to find the schema and the engine. Since `__dirname` behaves differently in electron, that can be something to take a look at.

I am closing the issue, as I don't think there is anything actionable on our end besides the information I just gave you. But happy to help if needed :) Thanks.

**Closed by millsp** 2023-05-16 21:05 UTC
Labels: bug/1-unconfirmed, kind/bug, team/client, topic: electron, topic: Query engine ... could not be found.
