### ISSUE TITLE
Help us improve the Re-Introspection Workflow by sharing your Prisma Schema and SQL schemas 🙏

### ISSUE THREAD

**Issue by do4gr** [prisma/prisma#2711] opened 2020-06-10 14:19 UTC
Hey everyone 👋

We want to remove one of the remaining big pain points of Introspection: 
If you manually adjusted your data model after introspection (to rename fields or models, or add default IDs for example) these changes are currently lost once you introspect again ("re-introspect",  for example, because your database was changed manually or migrated by another tool).

It would, therefore, be a tremendous help for us if you could share your projects where you encountered this problem! The information we need is the following: 

1. Your **Prisma 2 schema** that you manually modified after a previous introspection 
2. Your current **SQL schema** which when introspected again currently leads to loss of manually added information in the Prisma 2 Schema. 

Please submit your database schemas and Prisma Schemas to [schemas@prisma.io](mailto:schemas@prisma.io).

---

Also, note that **we're happily signing NDAs if your schemas and data models need to be treated confidently**! If you like Prisma and want to see it succeed, please consider sharing your schema and data model or talking to your boss if that's needed to be able to share your information! 🙂

---

Thanks for helping us making Prisma better 🙌

**Comment by theRocket** [comment] 2020-06-11 05:59
I don't think Prisma 1 set up my enums as a column property in MySQL, so I had to add those back after an introspection. Now, I think if I introspected, it might find them. I also switched from MySQL 5.7 to 8 (the main impetus for upgrading the Prisma 2, the timing of the G.A. was just fortuitous), so I'm not sure where that enum feature evolved exactly.

**Comment by janpio** [comment] 2020-06-11 10:58
@theRocket I am happy to investigate this in more detail and possibly give you some pointers (we have an upgrade tool for P1->P2 for example) - best create an issue and link to it here (or @ mention me).

**Comment by theRocket** [comment] 2020-06-11 17:21
Thanks, @janpio. I did use the prisma-upgrade tool, but I think I may have discovered it after already running one introspection. That tool has good instructions for the correct order of operation, but I think that first introspect dropped the enums since 5.7 didn't have them in schema. I have all this in branches and containers, so I could reproduce it.

**Comment by janpio** [comment] 2020-06-11 18:23
Sweet, just post the issue link here then after creating it and we can take a deeper look.

**Comment by louisrli** [comment] 2020-06-14 10:13
I think I ran into this issue as well with IDs. Basically after a second re-introspection of a postgres database, this happened to all my IDs:
```
-  id                                    String          @default(cuid()) @id
+  id                                    String          @id
```
this to my timestamps:
```
-  createdTimestamp        DateTime           @default(now())
+  createdTimestamp        DateTime

-  updatedTimestamp DateTime          @updatedAt
+  updatedTimestamp DateTime
```
which I don't think is what I want...

**Comment by louisrli** [comment] 2020-06-14 10:15
I think it's related to this one (and the one below)
https://www.prisma.io/docs/guides/upgrade-from-prisma-1/schema-incompatibilities-postgres#generated-cuids-as-id-values-arent-represented-in-database

but it's be really nice if introspection could be smart enough to leave any @id annotations with the same column name untouched if there's such additional annotations.

**Comment by janpio** [comment] 2020-06-14 23:20
If you could send us your SQL and Prisma schemas to schemas@prisma.io that would be great - then we will add your schema to our CI system that will make sure we get better on this over time @louisrli 👍

**Comment by Akxe** [comment] 2020-06-19 13:41
@janpio @do4gr Do you need anything other than what I provided?

**Comment by harryttd** [comment] 2020-06-30 04:24
For `id` field, original introspection yields: `id String @default(dbgenerated()) @id`.
I modified it to be `id String @default(uuid()) @id`.
Re-introspecting brings it back to `id String @default(dbgenerated()) @id`.

Also, I believe it was mentioned in another issue, but I need to manually set `@updatedAt` on the updatedAt column as it is not set by the original introspection. Re-introspecting removes it.

**Comment by janpio** [comment] 2020-06-30 09:35
We shipped an initial version of Re-Introspection behind a feature flag:
https://github.com/prisma/prisma/issues/2829
This will only cover some of your use cases, but maybe try it out and report back to us if it does solve one of your problems or if you encounter any (new) bugs. Thanks!

**Comment by divyenduz** [comment] 2020-06-30 14:38
@harryttd Can you please share the SQL and the database (Postgres or MySQL?) that you are using?

**Comment by harryttd** [comment] 2020-06-30 17:01
@janpio Apologies, I neglected to mention that I am using the `--experimental-reintrospection`.

Also, I just realized that comments are wiped from the schema file. Found this out when I commented out my schema tables in order to get new SQL and generated schema for you guys to reproduce.

@divyenduz 
`postgres --version`: 12.3
`yarn prisma -v` : 2.1.3

SQL
```sql
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

CREATE TABLE IF NOT EXISTS public.user (
  "id" UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  "updated_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  "user_name" VARCHAR(128) UNIQUE NOT NULL,
);
```

schema.prisma
```prisma
generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

model user {
  created_at DateTime @default(now())
  id         String   @default(dbgenerated()) @id
  updated_at DateTime @default(now())
  user_name  String   @unique
}
```

Update model `user` to:
```prisma
model User {
  createdAt DateTime @default(now()) @map("created_at")
  id        String   @default(uuid()) @id
  updatedAt DateTime @updatedAt @default(now()) @map("updated_at")
  userName  String   @unique @map("user_name")

  @@map("user")
}
```

Run: `prisma introspect --experimental-reintrospection`

`User` model result:
```prisma
model User {
  createdAt DateTime @default(now()) @map("created_at")
  id        String   @default(dbgenerated()) @id
  updatedAt DateTime @default(now()) @map("updated_at")
  userName  String   @map("user_name") @unique

  @@map("user")
}
```

Notice three things after running `prisma introspect --experimental-reintrospection`:
1. `uuid()` goes back to `dbgenerated()`
2. `@updatedAt` attribute is gone
3. `@unique` attribute is placed at the end of the line of `userName` field.

**Comment by janpio** [comment] 2020-06-30 17:10
Can you quickly transform your initial comment and the follow up comment into a new issue and then edit your second comment into a link to that? Then we can keep things a bit more separated. Thanks-

**Comment by janpio** [comment] 2020-08-17 15:58
All your Re-Introspection problems fixed with what we released in https://github.com/prisma/prisma/issues/2711#issuecomment-651681194? If not, please open a new issue so we can discuss the problem and find a solution.

**Closed by janpio** 2020-08-17 15:58 UTC
Labels: kind/improvement, topic: re-introspection

**Comment by janpio** [comment] 2020-08-20 16:29
Big update over at https://github.com/prisma/prisma/issues/2829#issuecomment-677768679
