### ISSUE TITLE
`migrate diff --from-schema-datasource [redacted] --to-schema-datamodel [redacted] --script` errored with `[schema-engine\connectors\sql-schema-connector\src\sql_schema_calculator.rs:198:32] no entry found for key`

### ISSUE THREAD

**Issue by Onfire7** [prisma/prisma#21222] opened 2023-09-25 20:15 UTC
Hi Prisma Team! The following command just crashed.

## Command

`migrate diff --from-schema-datasource [redacted] --to-schema-datamodel [redacted] --script`

## Versions
      
| Name        | Version            |
|-------------|--------------------|
| Platform    | windows            | 
| Node        | v18.16.0           | 
| Prisma CLI  | 5.3.0              | 
| Engine      | e90b936d84779543cbe0e494bc8b9d7337fad8e4| 

## Error
```
RustPanic: Error in Schema engine.
Reason: [schema-engine\connectors\sql-schema-connector\src\sql_schema_calculator.rs:198:32] no entry found for key

```

**Comment by Jolg42** [comment] 2023-09-29 16:04
Could be a duplicate of https://github.com/prisma/prisma/issues/19249

**Comment by Jolg42** [comment] 2023-09-29 16:05
@Onfire7 Are you using the `views` preview feature?
And could you share your schema, so we can try a reproduction?

**Comment by millsp** [comment] 2023-11-07 02:55
@Onfire7  did you see the message from @Jolg42 ? Without additional information to be able to reproduce, we would later close this issue as part of our issue process.

**Comment by SevInf** [comment] 2023-11-22 11:52
Hey @Onfire7 ,
 

With the lack of information and our inability to reproduce this issue, we're now closing it. Feel free to comment if you have any updates about it.
 
Thank you 🙏

**Closed by SevInf** 2023-11-22 11:52 UTC
Labels: bug/0-unknown, kind/bug, topic: migrate, topic: error reporting, team/schema, topic: prisma migrate diff
