### ISSUE TITLE
Improve Error Handling & Messages

### ISSUE THREAD

**Issue by flybayer** [prisma/prisma#2122] opened 2020-04-07 14:06 UTC
## Problem

1. There is currently no easy way to handle different types of errors thrown by prisma client.
	- Currently it appears that all errors thrown by prisma client have `error.name = 'Error'`
2. The content of `error.message` can vary a lot depending on the configured `errorFormat`. This makes it hard to consistently handle messages.
3. There is no way to know all the possible errors that will be thrown

## Solution

1. All errors thrown by prisma client should have a descriptive name 
2. Add a field on all errors that always have a minimal error format regardless of the `errorFormat` config.
	- Example: `error.shortMessage`
3. All possible errors should be clearly documented

## Examples

```
error.name === 'PrismaInputError'
error.shortMessage === 'Argument where of type ProductWhereUniqueInput needs at least one argument'
error.message === " /* ... long error message ... */"
```

```
error.name === 'PrismaConnectionError'
error.shortMessage === 'Failed to connect to database blah blah'
error.message === " /* ... long error message ... */"
```

```
error.name === 'PrismaDatabaseViolation'
error.shortMessage === 'unique constraint violated, id = 1 already exists, blah blah'
error.message === " /* ... long error message ... */"
```

**Comment by Sytten** [comment] 2020-04-07 15:42
Duplicate of https://github.com/prisma/prisma-client-js/issues/618

**Comment by pantharshit00** [comment] 2020-04-08 08:36
Indeed this is now a duplicate of prisma/prisma-client-js#618. @flybayer I would appreciate if you can add your suggestions to that issue.

**Closed by pantharshit00** 2020-04-08 08:36 UTC
