### ISSUE TITLE
Can't findOne using a field that is part of an @@unique declaration

### ISSUE THREAD

**Issue by madebysid** [prisma/prisma#2667] opened 2020-06-05 09:42 UTC
## Problem

So given this schema:
```
model User {
  id       Int @id
  name     String
  email    String

  @@unique([name, email])
}
```

I would like this query to work: 
```
prisma.user.findOne({
    where: {
        name: "Something"
    }
})
```

Currently, it looks like I cannot query using only `name` if it is part of an `@@unique` declaration, I can only do so in this way:
```
prisma.user.findOne({
    where: {
        name_email: {
            name: "Something",
            email: "test@example.com"
        }
    }
})
```
which means I am forced to include an `email` query too.

I can query using only `name` in a `findMany`, but not in a `findOne`. So this works:
```
prisma.user.findMany({
    where: {
        name: "Something"
    }
})
```

## Suggested solution

The following query should be allowed:

```
prisma.user.findOne({
    where: {
        name: "Something"
    }
})
```

**Comment by madebysid** [comment] 2020-06-05 09:44
The same applies to fields in an `@@id` declaration too.

**Comment by bummey** [comment] 2020-06-09 15:12
Isn't that expected? Only the combination of the name and email is unique. Just providing one can return multiple results, thus only available for the findMany fn.

**Comment by Sytten** [comment] 2020-06-09 15:19
Yeah I agree with @bummey, I think this is just a duplicate of https://github.com/prisma/prisma/issues/1924

**Comment by pantharshit00** [comment] 2020-06-10 03:16
Yes, the current API implementation is expected as combination is unique rather than the field. If you want the field to show up the filter, mark it unique separately.

I am going to close this.

**Closed by pantharshit00** 2020-06-10 03:16 UTC

**Comment by madebysid** [comment] 2020-06-10 09:24
For clarification, I was hoping that if multiple rows match a given criteria, the function would either throw or return any one of them (without making any guarantees about which one). I’m not sure where this expectation comes from, maybe an old tool that I used. 

I do agree that I can probably use a findMany in my case, or apply a unique constraint to fields I want to filter by!
