### ISSUE TITLE
unable to run migrations in an empty PostGIS db

### ISSUE THREAD

**Issue by bkiac** [prisma/prisma#4745] opened 2020-12-20 09:44 UTC
## Bug description

Copied from https://github.com/prisma/prisma/discussions/4732

I'm struggling to use the migration tool after I upgraded to 2.13.0.
I have a few spatial columns that I manage with scripts besides the Prisma migration tool.

My pipeline used to be this:
1. apply Prisma migrations
2. run manual migrations and add / alter spatial columns if needed

but with 2.13.0, I can no longer run any Prisma migration on a fresh PostGIS database because of this error:
```
Error: P3005

The database schema for `localhost:5432` is not empty. Read more about how to baseline an existing production database: https://pris.ly/d/migrate-baseline
```

Enabling PostGIS creates a `spatial_ref_sys` table, so technically the database is not empty, but it should not affect migrations.
I know Prisma does not yet support the PostGIS extension, but I'm looking for a workaround.

I'm also a Nexus and nexus-plugin-prisma user which doesn't support 2.12.x, so I can't downgrade reliably.

## How to reproduce

1. Have an empty PostGIS database (I used https://hub.docker.com/r/postgis/postgis)
1. Run `prisma migrate dev --preview-feature`
1. See error

## Expected behavior

Migrations run without an error.

## Environment & setup

- OS: PopOS
- Database: PostgreSQL with PostGIS
- Node.js version: v14.13.0
- Prisma version:
```
@prisma/cli          : 2.13.0
@prisma/client       : 2.13.0
Current platform     : debian-openssl-1.1.x
Query Engine         : query-engine 833ab05d2a20e822f6736a39a27de4fc8f6b3e49 (at node_modules/@prisma/engines/query-engine-debian-openssl-1.1.x)
Migration Engine     : migration-engine-cli 833ab05d2a20e822f6736a39a27de4fc8f6b3e49 (at node_modules/@prisma/engines/migration-engine-debian-openssl-1.1.x)
Introspection Engine : introspection-core 833ab05d2a20e822f6736a39a27de4fc8f6b3e49 (at node_modules/@prisma/engines/introspection-engine-debian-openssl-1.1.x)
Format Binary        : prisma-fmt 833ab05d2a20e822f6736a39a27de4fc8f6b3e49 (at node_modules/@prisma/engines/prisma-fmt-debian-openssl-1.1.x)
Studio               : 0.329.0
```

**Comment by pantharshit00** [comment] 2020-12-24 19:18
I can confirm this after running the `create extension if not exists "postgis";`

I think we should ignore this table

**Comment by Kay2dan** [comment] 2020-12-25 13:38
I am having the same issue with postgres new instance. It refuses to apply the migrations with error: 'database is not empty'.

**Comment by TheAschr** [comment] 2020-12-29 16:20
Are there any workarounds for this?

**Comment by TheAschr** [comment] 2020-12-29 17:40
It looks like the ignored tables function call got removed in the version of prisma engine that is referenced by prisma-cli:

https://github.com/prisma/prisma/blob/master/src/packages/cli/package.json#L133

https://github.com/prisma/prisma-engines/blob/2.14.0-dev.26/migration-engine/connectors/sql-migration-connector/src/sql_imperative_migration_persistence.rs#L27

However the master branch of prisma engine has re-added it back in:

https://github.com/prisma/prisma-engines/blob/master/migration-engine/connectors/sql-migration-connector/src/sql_imperative_migration_persistence.rs#L28-L30

Is it possible that updating the prisma engine dependency in prisma-cli will fix the issue?

**Comment by mcamac** [comment] 2020-12-29 21:05
If useful, a manual fix to get around this - manually apply the first SQL migration to your database, and then use `prisma migrate resolve --applied "FIRST_MIGRATION_NAME" --preview-feature`  to mark it as resolved. You can then apply the rest normally via `prisma migrate deploy`.

**Comment by tomhoule** [comment] 2021-01-04 13:28
This should be fixed by https://github.com/prisma/prisma-engines/pull/1478, to be released tomorrow.

**Closed** 2021-01-05 10:00 UTC
Labels: bug/2-confirmed, kind/bug, process/candidate, team/migrations
