### ISSUE TITLE
Prisma SDK's `getDMMF` function fails to parse and return instances of `@@index` 

### ISSUE THREAD

**Issue by moaazsidat** [prisma/prisma#10302] opened 2021-11-16 19:29 UTC
## Problem

Prisma SDK's `getDMMF` function fails to parse and return instances of `@@index` defined on the model. The same function does return instances of `@@unique`, so missing `@@index` seems like missing functionality. 

## Suggested solution
Extend the `getDMMF` parser to include `@@index` defined as part of a Prisma schema.

## Additional context
Came across this while writing a generator / plugin that can generate supplemental models and add fields to existing models defined in a Prisma schema file. 

Here's a quick test

```javascript

const datamodel = `
  datasource db {
    provider = "postgresql"
    url      = env("DATABASE_URL")
  }

  model User {
    id              Int       @id @default(autoincrement())
    email           String    @unique
    firstName       String
    lastName        String
    fooVersions     UserFooVersion[]

    @@index([email], name: "idx_users_email")
    @@unique([firstName, lastName])
  }
`;

const result = await getDMMF({ datamodel });
console.log('result should include index info', result) 
```

**Comment by janpio** [comment] 2021-11-19 17:31
If this is the case, reasoning is probably that indexes usually do not influence the Client functionality. But it sounds reasonable to add the information anyway - so this is a reasonable feature request.

**Comment by janpio** [comment] 2022-03-22 16:17
Closing this as a duplicate of https://github.com/prisma/prisma/issues/3998 for now.

**Closed by janpio** 2022-03-22 16:17 UTC
Labels: kind/feature, topic: dmmf, team/client
