### ISSUE TITLE
Make Prisma client work without a Prisma server 

### ISSUE THREAD

**Issue by nikolasburk** [prisma/prisma#3761] opened 2018-12-22 13:50 UTC
Right now, using the Prisma client always requires the deployment of an extra Prisma server that sits between the database and API server (or another program that needs to access the database). Prisma servers can be deployed with Docker.

![](https://imgur.com/OyIQQxF.png)

While the Prisma server is great for scalability and performance, it is a notable barrier for people that are just getting started with Prisma. Developers that want to get to know Prisma as an ORM replacement are often surprised because other ORMs don't require this additional setup step.

In an effort of making Prisma more approachable, Prisma servers should be considered _optional complexity_ and there should be a way to use the Prisma client without them.

**Comment by pantharshit00** [comment] 2019-02-11 09:37
Closing as duplicate of #2992

**Closed by pantharshit00** 2019-02-11 09:37 UTC
Labels: area/client, kind/feature, rfc/0-needs-spec
