### ISSUE TITLE
Introspection for existing Prisma 1 databases

### ISSUE THREAD

**Issue by nikolasburk** [prisma/prisma#781] opened 2019-10-18 09:05 UTC
This is a tracking issue for supporting introspection against database from existing Prisma 1 projects. 

We could even think about having a dedicated CLI command since this feature will mostly be used during upgrade processes, so we might consider adding something like a `prisma2 upgrade` that picks up an existing `prisma.yml` and performs the introspection automatically.

**Comment by janpio** [comment] 2019-12-15 10:25
Right now it looks like we will focus on introspecting Prisma1 databases directly from SQL, so no `prisma.yml` support or similar will be provided. But we have to test this and make sure our Introspection actually like P1 SQL databases.

**Comment by janpio** [comment] 2019-12-15 13:45
Next step: @divyenduz creates a DB server with all the P1 schemas we have.

**Comment by divyenduz** [comment] 2019-12-30 09:59
We have the required server/infra to test any Prisma 1 schemas easily now. Please contact me internally to find out how that can be done :)

**Comment by divyenduz** [comment] 2020-02-04 12:30
@janpio what is the action item on this one? We already have all the P1 schemas that I am aware of in our system. IMO this can be closed.

**Comment by janpio** [comment] 2020-02-13 15:22
Action Item: Test 1-x Prisma 1 schemas and see if everything is introspected correctly.

**Comment by divyenduz** [comment] 2020-03-24 05:09
@janpio Is there any further action item on this one?

**Comment by nikolasburk** [comment] 2020-03-24 05:33
It depends on what we want to offer as an upgrade path. Yesterday @janpio had the idea of an upgrade flow where we first use additional information from the Prisma 1 datamodel that doesn't manifest in the database schema (e.g. `@default` values or  `@updatedAt`) and add it to the DB schema so that it can be picked up by Prisma 2 introspection.

It's of course a capacity question but I'd be very much in favor of providing an upgrade path that is able to factor in information from the Prisma 1 datamodel (however that's done in the end), otherwise upgrading will probably become a huge pain for existing Prisma 1 users.

**Comment by janpio** [comment] 2020-03-24 11:18
This is being discussed off GitHub now. We will come up with a plan here soon.

**Comment by williamluke4** [comment] 2020-03-24 16:14
Another thing to consider is that currently join tables are show when introspecting a P1 database. I don't know if this is also the case with P2 but it would be nice if they were abstracted away again :)

**Comment by janpio** [comment] 2020-03-24 17:20
This should not be the case any more @williamluke4 with the current `alpha` - can you try and confirm that ?

**Comment by williamluke4** [comment] 2020-03-24 18:11
I can confirm that it no longer shows join tables

**Comment by divyenduz** [comment] 2020-04-08 17:03
Closing this in favor of https://github.com/prisma/prisma/issues/1937

Please subscribe to #1937 to stay up to date on P1 -> P2 upgrade scenarios.

**Closed by divyenduz** 2020-04-08 17:03 UTC
Labels: kind/feature, topic: introspection, topic: prisma1
