### ISSUE TITLE
Create initial migration file without having running database

### ISSUE THREAD

**Issue by janpio** [prisma/prisma#8313] opened 2021-07-16 11:56 UTC
When I have a schema, I want to be able to create the initial SQL to create that schema in a database, without having to have a running database. This is not possible with `migrate dev` or `migrate dev --create-only` for example.

Use case: I get a schema from someone and want to quickly see what Prisma Migrate would make out of it so I can evaluate, if Migrate is a viable Migration tool.

**Comment by Jolg42** [comment] 2021-07-29 11:40
Closing as duplicate of https://github.com/prisma/prisma/issues/8056

**Closed by Jolg42** 2021-07-29 11:40 UTC
Labels: kind/feature, team/migrations, topic: migrate dev
