### ISSUE TITLE
Go client doesn't fetch enum values

### ISSUE THREAD

**Issue by nikolasburk** [prisma/prisma#3493] opened 2018-11-13 09:29 UTC
**Describe the bug**

This is what my datamodel looks like:

```graphql
type Post {
  id: ID! @unique
  createdAt: DateTime!
  updatedAt: DateTime!
  title: String!
  published: Boolean! @default(value: "false")
  author: User
  comments: [Comment!]!
}

type User {
  id: ID! @unique
  name: String
  email: String! @unique
  role: Role! @default(value: "USER")
  posts: [Post!]!
  comments: [Comment!]!
}

type Comment {
  id: ID! @unique
  createdAt: DateTime!
  text: String!
  post: Post!
  writtenBy: User!
}

enum Role {
  USER
  ADMIN
}
```

Whenever I'm fetching users, e.g. using the following code:

```go
email := "alice@prisma.io"
user, err := client.User(prisma.UserWhereUniqueInput{
    Email: &email,
}).Exec(ctx)
```

The `role` enum is not part of the result:

```go
&prisma.User{ID:"cjofizq76ykpl09116fdakz9t", Name:(*string)(0xc0002b8150), Email:"alice@prisma.io"}
```

**Comment by schickling** [comment] 2018-11-13 10:03
Duplicate of #3385

**Closed by schickling** 2018-11-13 10:03 UTC
Labels: component/client/go, kind/bug
