### ISSUE TITLE
Editors often don't pick up a newly generated prisma client

### ISSUE THREAD

**Issue by steebchen** [prisma/prisma#2771] opened 2020-06-16 07:58 UTC
I have heard repeatedly that sometimes editors don’t pick up changes when you change the prisma schema and then re-generate. They just don’t pick it up somehow. It seems the only way to fix it is to navigate manually to node_modules/.prisma/index.d.ts and then somehow the editors picks up the changes. This happened in both IntelliJ Ultimate and in VS Code. It’s not after a specific change, so it’s hard to reproduce – it just happens sometimes. I’m not sure if we can do anything against that, but it’s for sure frustrating for our users.

**Comment by hi019** [comment] 2020-06-17 04:24
This happens to me every time I do `prisma generate`, with VSCode. Usually I just do `CTRL SHIFT P -> Developer: Reload Window`.

A similar issue occurs with Apollo Codegen, which generates types for GraphQL API's. VSCode does not seem to know about these new types unless I open the generated files manually.

**Comment by pantharshit00** [comment] 2020-06-17 06:01
This is actually easy to reproduce and I can reproduce it with vim as well.

Here is a small demo video: https://www.youtube.com/watch?v=z8AX6_KrBhw

I think it is related to typescript language server

**Comment by janpio** [comment] 2020-06-17 08:05
Related internal discussion with insight from Labs team: https://prisma-company.slack.com/archives/CEYCG2MCN/p1592287882166100

**Comment by steebchen** [comment] 2020-07-08 05:08
It seems this also happens to generated go code. That means it could also be an editor problem in general, not just the TS server.

**Comment by janpio** [comment] 2020-07-08 05:45
For TS, I just [read a related discussion](https://blitzjs.slack.com/archives/C011EQ0J75M/p1594157842232000) that mentioned that the beta of TS@4 might improve the behavior. If you can reproduce this easily @pantharshit00, might be worth to try out if that is ture.

**Comment by nikolasburk** [comment] 2020-07-08 08:17
For everyone running into this, you can fix this also by **restarting the TypeScript server inside of VS Code** which you can do e.g. via the _command palette_.

On a Mac, you open the command palette via <kbd>CMD</kbd>+<kbd>SHIFT</kbd>+<kbd>P</kbd>. Then you can just start typing "Restart" and the correct command should show up:

![image](https://user-images.githubusercontent.com/4058327/86895063-3b786f80-c104-11ea-9163-07a70ee505d6.png)

**Comment by pantharshit00** [comment] 2020-07-08 11:30
It is the same with TS v4 in my testing. I made sure that editor used the v4 language server but it still doesn't work

**Comment by carmenberndt** [comment] 2020-07-28 15:33
For everyone using VSCode, this is fixed by https://github.com/prisma/language-tools/pull/357 in the Prisma VSCode extension.

**Comment by pantharshit00** [comment] 2021-05-04 14:06
We might be able to close this since we have properly fixed this for vscode and for other editor, people will need to remove `.prisma/client` from indexing exclusion list.

**Comment by matthewmueller** [comment] 2021-06-02 13:46
Closing since it's fixed in VSCode with a workaround for the other editors. If you run into this problem again, please open a separate issue for your IDE!

**Closed by matthewmueller** 2021-06-02 13:46 UTC
Labels: bug/2-confirmed, kind/bug, team/client, tech/typescript, topic: editor

**Comment by Jolg42** [comment] 2021-06-02 14:41
Use Prisma official VS Code extension https://marketplace.visualstudio.com/items?itemName=Prisma.prisma

**Comment by thunderfalco** [comment] 2023-11-19 15:40
I am using neovim with prisma-language-server, when execute primsa generate, there is not newly generated client recognized, there is not code competition when I call new model, What should I do  to solve this problem?

**Comment by janpio** [comment] 2023-11-21 17:09
Not pot in a 3 year old issue, but create a new discusison or issue please. Thanks.

**Comment by jmcmichael** [comment] 2025-06-13 18:14
For JetBrains IDEs, find the `@prisma/client` directory in the Project pane, right-click on it, and select `Mark Directory As -> Cancel Exclusion`. Or include it via the Directories pane in Settings.
