### ISSUE TITLE
`prisma db push` generating identifier names longer than 64 characters

### ISSUE THREAD

**Issue by JoJk0** [prisma/prisma#5344] opened 2021-01-29 10:42 UTC
## Bug description

I have relations between complex objects that generates long identifier names.
While executing `prisma db push` Prisma appends '_ibfk_1' even if it will have more than 64 characters after appending. My use case is to be used by Jest for pushing the schema into test database.

It rejects promise:

```
Promise {
        <rejected> Error: Command failed: /Users/../../../node_modules/.bin/prisma db push --preview-feature
        Error: Database error: Error querying the database: Server error: `ERROR 42000 (1059): Identifier name 'foundation_variable_set_foundation_configuration_values_aud_ibfk_1' is too long'
           0: sql_migration_connector::sql_database_step_applier::apply_step
                   with index=0
                     at migration-engine/connectors/sql-migration-connector/src/sql_database_step_applier.rs:14
           1: migration_core::api::SchemaPush
                     at migration-engine/core/src/api.rs:166
```

## How to reproduce

1. Have a Prisma schema in which there are table names with length larger than 57 characters (64 - 7) as '_ibfk_1' has 7 characters.
2. run `prisma db push --preview-feature`
3. Expect an error to be thrown

## Expected behavior

Generate an alternative name which is shorter than 64 characters, or
Let the user choose custom name for the identifier

In my case I can't really change the MySQL schema and I need to work with what I have. 
I know these names are unnecessary and repetitive but that's what Prisma generates.

## Prisma information

The schema is pretty big so I include the part of it:

```
model foundation_variable_set_foundation_configuration_values_aud {
  REV                Int
  CompanyVariable_id Int
  valueList_id       Int
  REVTYPE            Int?
  DeviceVariable_id  Int
  GroupVariable_id   Int
  revinfo            revinfo @relation(fields: [REV], references: [REV])

  @@id([REV, GroupVariable_id, valueList_id])
}
```

## Environment & setup

- OS: MacOS 
- Database: MySQL 
- Node.js version: 12.16.1 
- Prisma version: 12.15.0

```

```

**Comment by pantharshit00** [comment] 2021-02-03 13:17
I can confirm this. I think either we should ask the user to put the name of the fk in the schema or we should trim the name of the generated fk name. 

Below schema reproduced the crash for me. Max limit of mysql foreign key name length is 64 as mentioned by you. So had to add one more character to the shared schema for reproduction. 
```prisma

model foundation_variable_set_foundation_configuration_values_aud_ {
  REV                Int
  CompanyVariable_id Int
  valueList_id       Int
  REVTYPE            Int?
  DeviceVariable_id  Int
  GroupVariable_id   Int
  test               User @relation(fields: [userId], references: [id])

  userId String
  @@id([REV, GroupVariable_id, valueList_id])
}

model User {
  id   String @id @default(uuid())
  name String

 field foundation_variable_set_foundation_configuration_values_aud_?
}

```

**Comment by pantharshit00** [comment] 2021-05-04 15:59
This is still reproducible in `2.22`

**Comment by MurzNN** [comment] 2021-06-25 09:00
I catch this problem when trying to create relation, that joins model name with field name, as result composing string with more than 64 characters.

What do you think about implementing workaround via reserve last symbol to number, and iterate all long names with unique numbers?

**Comment by tomhoule** [comment] 2021-06-25 09:04
This is currently being worked on, expect a preview feature to make it into a release soon.

**Comment by do4gr** [comment] 2021-08-11 12:51
A fix for this issue is now available via the `namedConstraints` preview flag since 2.29. It implements both solutions mentioned above, a default name generation that respects db name length limits and the option for user-specified names. 

See https://www.prisma.io/docs/guides/upgrade-guides/upgrading-to-use-preview-features/enabling-named-constraints

**Closed** 2021-08-11 13:01 UTC
Labels: bug/2-confirmed, kind/bug, topic: schema, topic: migrate, team/migrations
