### ISSUE TITLE
Why is VSCode not telling me with red squiggly line that `invoice` does not exist on `customer`?

### ISSUE THREAD

**Issue by janpio** [prisma/prisma#2743] opened 2020-06-13 22:41 UTC
![image](https://user-images.githubusercontent.com/183673/84580463-948c0680-add7-11ea-840a-7b226c6d84eb.png)

After fixing and introspecting updated schema with 2.0.0 for https://github.com/prisma/chinook/tree/master/express-app

Schema is updated, `npx prisma generate` has been run. 
Fixing it to `Invoices` as indicated in the error message fixes it.

**Comment by pantharshit00** [comment] 2020-06-17 12:13
It tells me with a red squiggly line:
<img width="889" alt="image" src="https://user-images.githubusercontent.com/22195362/84896652-f3949880-b0c1-11ea-8374-8fe3fa20e8a7.png">


<img width="1041" alt="image" src="https://user-images.githubusercontent.com/22195362/84896566-ce078f00-b0c1-11ea-868d-72c3c1c6fe35.png">

I think this is just a duplicate of #2771 and just need to restart tsserver

**Closed** 2021-03-23 19:15 UTC
Labels: bug/0-needs-info, kind/bug, status/needs-action
