### ISSUE TITLE
Error: Unknown binaryTarget linux-arm64-openssl-undefined and no custom engine files were provided                               

### ISSUE THREAD

**Issue by janpio** [prisma/prisma#16232] opened 2022-11-10 21:17 UTC
>         @janpio  I've recreated it with the following minimal setup.
> 
> Dockerfile
> 
> ```
> ARG FUNCTION_DIR="/var/task"
> FROM node:16-slim
> 
> # Include global arg in this stage of the build
> ARG FUNCTION_DIR
> 
> WORKDIR ${FUNCTION_DIR}
> COPY . ${FUNCTION_DIR}
> 
> RUN yarn add prisma
> RUN yarn prisma generate
> ```
> 
> prisma.schema
> ```
> // This is your Prisma schema file,
> // learn more about it in the docs: https://pris.ly/d/prisma-schema
> 
> generator client {
>   provider      = "prisma-client-js"
>   binaryTargets = ["rhel-openssl-1.0.x", "linux-arm64-openssl-1.0.x"]
> }
> 
> datasource db {
>   provider = "mongodb"
>   url      = env("DATABASE_URL")
> }
> 
> model User {
>    objectID  String   @id @default(auto()) @map("_id") @db.ObjectId
> }
> ```
> 
> docker-compose.yml
> ```
> version: "3.9"
> services:
>   api:
>     build: .
>     volumes:
>       - ./:/var/task
> ```
> 
> When running `docker compose build` you should get this error
> 
> ```
> Error: Unknown binaryTarget linux-arm64-openssl-undefined and no custom engine files were provided                               
> #0 1.446 error Command failed with exit code 1.
> ```

_Originally posted by @jcampbell05 in https://github.com/prisma/prisma/issues/861#issuecomment-1310206111_

**Comment by jcampbell05** [comment] 2022-11-14 10:30
So this error is unrelated to ARM and is caused by a lack of an installed SSL library. Some slim Docker images no longer come with a SSL library installed by default in order to keep the image as small as possible. This is why switching to a full sized image resolves this issue.

The fix is to simply install a SSL library.

Unfortunately the error from Prisma doesn't provide any context that this is the issue. So I would suggest the following change:

- Change the name of the Linux based package to indicate the number in the name is supposed to represent the version of the locally installed SSL library i.e "linux-rhel-ssl-1.0.0". Wasn't clear that this version was related to that.
- When a linux library has been selected (Either manually or automatically via "native") then if a SSL library isn't installed rather than return "undefined" as the version number. Throw an error indicating that they lack a SSL library.

**Comment by hotrungnhan** [comment] 2022-11-16 17:13
i fixed it by installing openssl  in alpine image 
```bash
.....
RUN apk add openssl --no-cache
.....
```

**Comment by jcampbell05** [comment] 2022-11-22 12:04
To add to this some distro's appear to install the library in non-standard locations, when installing libssl-dev on the node:16-slim dockerfile the library is installed at `/usr/lib/aarch64-linux-gnu/` 

There doesn't seem to be an environmental variable that can be set to provide this non-standard location to the getPlatform function.

**Comment by jcampbell05** [comment] 2022-11-22 12:11
To add to this some distro's appear to install the library in non-standard locations, when installing libssl-dev on the node:16-slim dockerfile the library is installed at /usr/lib/aarch64-linux-gnu/

There doesn't seem to be an environmental variable that can be set to provide this non-standard location to the getPlatform function.

For these distro one has to install the openssl package along side the ssl library so that Prisma can use it to determine the version.

**Comment by cesarvspr** [comment] 2022-11-22 20:07
any workaround this issue?

**Comment by jcampbell05** [comment] 2022-11-23 10:12
@cesarvspr Yes I had to add the following line to my Dockerfile when using the `node:16-slim` image.

```
RUN apt-get update && apt-get install -y openssl libssl-dev
```

You may need to adjust this command for your distro if it uses another package manager.

**Comment by JameelKhan9** [comment] 2022-11-30 05:33
Getting the same error when using `node:16-alpine` image.

Added `RUN apk add libressl-dev` command to the docker file with no success.

**Comment by jcampbell05** [comment] 2022-12-01 17:28
@JameelKhan9  you also need to install openssl as Prisma needs the command line tool that installs to determine the version if it cannot do it via the headers.

**Comment by shide1989** [comment] 2022-12-04 18:08
for me it worked using node:16-slim version : 
```
FROM node:16-slim
RUN apt-get update
RUN apt-get install -y openssl
```

**Comment by joao-moonward** [comment] 2022-12-08 06:40
@shide1989 worked for me, thanks

**Comment by jkomyno** [comment] 2023-01-05 14:48
Hi, I'm on of the Prisma maintainers. This issue happens when no `libssl` / `openssl` is detected in a Linux system (specifically, one running on the `arm64` architecture).

Popular Docker images like `node:16-slim` or `node:lts-buster-slim` rely on Linux Debian 10.x (Buster), which doesn't have `openssl` installed, and requires you to install it manually. Please refer to [this comment](https://github.com/prisma/prisma/issues/16182#issuecomment-1371283457).

We're also working on improving the documentation about Prisma's system requirements and how to use Prisma on Docker.

**Comment by hotrungnhan** [comment] 2023-01-05 15:34
> Hi, I'm on of the Prisma maintainers. This issue happens when no `libssl` / `openssl` is detected in a Linux system (specifically, one running on the `arm64` architecture).
> 
> Popular Docker images like `node:16-slim` or `node:lts-buster-slim` rely on Linux Debian 10.x (Buster), which doesn't have `openssl` installed, and requires you to install it manually. Please refer to [this comment](https://github.com/prisma/prisma/issues/16182#issuecomment-1371283457).
> 
> We're also working on improving the documentation about Prisma's system requirements and how to use Prisma on Docker.

do you guy have any plan for support alpine with arm64 architechure ?

**Comment by damsog** [comment] 2023-02-18 18:01
> @JameelKhan9 you also need to install `openssl` as Prisma needs the command line tool that installs to determine the version if it cannot do it via the headers.

i tried `RUN apk add --update openssl && apk add --update libressl-dev && rm -rf /var/cache/apk/*` to install openssl and libressl-dev but still didn't work for alpine, had to change the base image to slim instead

**Comment by jkomyno** [comment] 2023-02-20 09:26
Hi @damsog, manually adding `openssl` is no longer necessary in newer Prisma versions.
Please install `prisma@4.10.1` and try again without the additional Docker `RUN` command you've mentioned [above](https://github.com/prisma/prisma/issues/16232#issuecomment-1435728982).

@hotrungnhan, `prisma@4.10.1` natively supports Linux Alpine on `arm64` :)

**Comment by jcampbell05** [comment] 2023-02-20 23:20
Should we closed this as solved ?

**Comment by Joseph-Alley** [comment] 2023-02-21 01:57
Didn't work for me. I updated to 4.10.1, then got the following error instead:

```
# This file contains the result of Yarn building a package (sensor-skins@workspace:.)
# Script name: postinstall

Prisma schema loaded from prisma/schema.prisma
Error: Not Found https://binaries.prisma.sh/all_commits/272861e07ab64f234d3ffc4094e32bd61775599c/linux-musl-arm64-openssl-1.1.x/libquery_engine.so.node.gz
```

**Comment by ADanilychevJr** [comment] 2023-02-21 18:28
We were having the issues this thread addresses (`node:16.16-alpine3.16`), Updated to 4.10.1 and the previous issues in CI were fixed, but then got the following:
```
 Error: Not Found https://binaries.prisma.sh/all_commits/d6e67a83f971b175a593ccc12e15c4a757f93ffe/linux-musl-arm64-openssl-1.1.x/libquery_engine.so.node.gz
```

**Comment by janpio** [comment] 2023-02-24 23:26
Can you provide some additional information what exactly you are doing @Joseph-Alley? Optimal with an example on how to reproduce this. Thanks.

**Comment by Joseph-Alley** [comment] 2023-02-28 23:23
@janpio I've spent several hours trying to replicate this, but I'm not getting this error anymore. I haven't changed anything on my end, so I'm not sure whether some other dependency was updated, or whether my computer was just caching something poorly.

But in either scenario, you should be free to close this. I can create a new ticket if I run into similar issues in the future.

**Comment by jkomyno** [comment] 2023-02-28 23:34
Hi @Joseph-Alley, that's great to hear! Let's close this issue as solved.

**Closed by jkomyno** 2023-02-28 23:34 UTC
Labels: bug/1-unconfirmed, kind/bug, team/client, topic: arm, topic: binaryTargets, topic: openssl

**Comment by prescindivel** [comment] 2024-01-31 13:28
> Hi @damsog, manually adding `openssl` is no longer necessary in newer Prisma versions. Please install `prisma@4.10.1` and try again without the additional Docker `RUN` command you've mentioned [above](https://github.com/prisma/prisma/issues/16232#issuecomment-1435728982).
> 
> @hotrungnhan, `prisma@4.10.1` natively supports Linux Alpine on `arm64` :)

This is work for me!
