### ISSUE TITLE
PANIC in query-engine/connectors/sql-query-connector/src/database/operations/write.rs:73:22 Could not figure out an ID in create

### ISSUE THREAD

**Issue by Stallion67** [prisma/prisma#15075] opened 2022-08-30 05:38 UTC
Hi Prisma Team! My Prisma Client just crashed. This is the report:
## Versions

| Name            | Version            |
|-----------------|--------------------|
| Node            | v12.21.0           | 
| OS              | rhel-openssl-1.0.x |
| Prisma Client   | 2.30.3             |
| Query Engine    | query-engine b8c35d44de987a9691890b3ddf3e2e7effb9bf20|
| Database        | undefined|

## Logs
```
2-08-30T05:35:54.392Z prisma:client:fetcher Error: The column `famunera_db.testimonials.deleted` does not exist in the current database.
    at BinaryEngine.graphQLToJSError (/app/node_modules/@prisma/client/runtime/index.js:30059:16)
    at BinaryEngine.request (/app/node_modules/@prisma/client/runtime/index.js:29944:24)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async cb (/app/node_modules/@prisma/client/runtime/index.js:36464:26)
prisma:client:fetcher Error: The column `famunera_db.testimonials.deleted` does not exist in the current database.
    at BinaryEngine.graphQLToJSError (/app/node_modules/@prisma/client/runtime/index.js:30059:16)
    at BinaryEngine.request (/app/node_modules/@prisma/client/runtime/index.js:29944:24)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async cb (/app/node_modules/@prisma/client/runtime/index.js:36464:26)
prisma:engine stdout  PANIC in query-engine/connectors/sql-query-connector/src/database/operations/write.rs:73:22
Could not figure out an ID in create
prisma:engine {
  error: SocketError: other side closed
      at Socket.onSocketEnd (/app/node_modules/@prisma/client/runtime/index.js:27696:24)
      at Socket.emit (events.js:326:22)
      at Socket.EventEmitter.emit (domain.js:483:12)
      at endReadableNT (_stream_readable.js:1241:12)
      at processTicksAndRejections (internal/process/task_queues.js:84:21) {
    code: 'UND_ERR_SOCKET'
  }
}
prisma:engine { cwd: '/app/prisma' }
prisma:engine Search for Query Engine in /app/node_modules/.prisma/client
plusX Execution permissions of /app/node_modules/.prisma/client/query-engine-rhel-openssl-1.0.x are fine
prisma:engine { flags: [ '--enable-raw-queries', '--port', '40269' ] }
prisma:engine stdout  Starting a mysql pool with 3 connections.
prisma:engine stdout  Started http server on http://127.0.0.1:40269
prisma:engine Search for Query Engine in /app/node_modules/.prisma/client
plusX Execution permissions of /app/node_modules/.prisma/client/query-engine-rhel-openssl-1.0.x are fine
prisma:engine Client Version: 2.30.3
prisma:engine Engine Version: query-engine b8c35d44de987a9691890b3ddf3e2e7effb9bf20
prisma:engine Active provider: mysql
prisma:engine stdout  PANIC in query-engine/connectors/sql-query-connector/src/database/operations/write.rs:73:22
Could not figure out an ID in create
prisma:engine {
  error: SocketError: other side closed
      at Socket.onSocketEnd (/app/node_modules/@prisma/client/runtime/index.js:27696:24)
      at Socket.emit (events.js:326:22)
      at Socket.EventEmitter.emit (domain.js:483:12)
      at endReadableNT (_stream_readable.js:1241:12)
      at processTicksAndRejections (internal/process/task_queues.js:84:21) {
    code: 'UND_ERR_SOCKET'
  }
}
prisma:engine { cwd: '/app/prisma' }
prisma:engine Search for Query Engine in /app/node_modules/.prisma/client
plusX Execution permissions of /app/node_modules/.prisma/client/query-engine-rhel-openssl-1.0.x are fine
prisma:engine { flags: [ '--enable-raw-queries', '--port', '43325' ] }
prisma:engine stdout  Starting a mysql pool with 3 connections.
prisma:engine stdout  Started http server on http://127.0.0.1:43325
prisma:engine Search for Query Engine in /app/node_modules/.prisma/client
plusX Execution permissions of /app/node_modules/.prisma/client/query-engine-rhel-openssl-1.0.x are fine
prisma:engine Client Version: 2.30.3
prisma:engine Engine Version: query-engine b8c35d44de987a9691890b3ddf3e2e7effb9bf20
prisma:engine Active provider: mysql
prisma:engine stdout  PANIC in query-engine/connectors/sql-query-connector/src/database/operations/write.rs:73:22
Could not figure out an ID in create
prisma:engine {
  error: SocketError: other side closed
      at Socket.onSocketEnd (/app/node_modules/@prisma/client/runtime/index.js:27696:24)
      at Socket.emit (events.js:326:22)
      at Socket.EventEmitter.emit (domain.js:483:12)
      at endReadableNT (_stream_readable.js:1241:12)
      at processTicksAndRejections (internal/process/task_queues.js:84:21) {
    code: 'UND_ERR_SOCKET'
  }
}
```

## Client Snippet
```ts
// PLEASE FILL YOUR CODE SNIPPET HERE
```

## Schema
```prisma
// PLEASE ADD YOUR SCHEMA HERE IF POSSIBLE
```

## Prisma Engine Query
```
mutation {
  createOneusers(data: {
    email: "X"
    email_activation_code: "X"
    role: "X"
    id_no: "X"
    phone: "X"
    phone_activation_code: "X"
    country: "X"
    fullname: "X"
    password: "X"
    reg_time: "X"
    username: "X"
    partnerId: 5
  }) {
    ID
    username
    fullname
    email
    phone
    role
    partnerId
    IsOutGrower
    IsAggregator
    aggregatorID
    FarmAcreage
    password_old
    password
    id_no
    services
    phone_activation_code
    phone_status
    email_activation_code
    email_status
    account_status
    subscription_status
    wallet_amount
    password_reset_key
    online_status
    last_seen
    search_rank
    old_email
    deleted
    country
    gender
    dob
    pro_dealin
    size_scale
    looking_for
    cover_picture
    profile_picture
    other_contacts
    website
    user_documents
    address
    reg_time
  }
}
```

**Comment by Stallion67** [comment] 2022-08-30 05:39
the problem seems to be around the primary key

**Comment by danstarns** [comment] 2022-09-06 15:33
@Stallion67 is this related ? https://github.com/prisma/prisma/issues/15066

**Comment by janpio** [comment] 2022-09-07 08:13
The underlying error from the error message seems to be 
```
2-08-30T05:35:54.392Z prisma:client:fetcher Error: The column `famunera_db.testimonials.deleted` does not exist in the current database.
```

Is that indeed correct @Stallion67? Does `famunera_db.testimonials.deleted` not exist?

What is your Prisma Client query?
What is your Prisma schema?
Can you share the SQL to your database?

**Comment by janpio** [comment] 2022-09-23 16:38
Ping @Stallion67 - can you help us out with this information so we can help you fix this problem please? Thanks.

**Comment by janpio** [comment] 2022-10-19 17:30
Ping @Stallion67 - can you confirm this was caused by a mismatch between your database and schema? That would mean we can close this issue. Thanks.

**Comment by janpio** [comment] 2022-11-25 00:15
Closing then until someone provides more information. Please comment or open a new issue. Thanks!

**Closed by janpio** 2022-11-25 00:15 UTC
Labels: bug/0-unknown, kind/bug, team/client, topic: rust panic
