### ISSUE TITLE
Prisma migrate is quite slow?

### ISSUE THREAD

**Issue by PanMan** [prisma/prisma#15523] opened 2022-09-26 13:25 UTC
### Bug description

I really like prisma migrate, but it always takes a few minutes to run. I think this is abnormal, and should be faster? Obviously not high prio - it works - but still might be useful/would be a better experience if faster. I also believe it's faster for other users?

### How to reproduce

The output from running prisma migrate (removed the verbose models):
Note, just starting the RPC engine takes almost 4 minutes ( 12:22:46 to 12:26:31):
```
panman@Martijns-MacBook-Air project-api % DEBUG="prisma:migrate*" npx prisma migrate dev --name="none"
Environment variables loaded from .env
Prisma schema loaded from prisma/schema.prisma
Datasource "db": MySQL database "project_migrate" at "localhost:3306"

  prisma:migrateEngine:rpc starting migration engine with binary: /Users/panman/Dropbox/Backup/Code/project-api/node_modules/@prisma/engines/migration-engine-darwin-arm64 +0ms
  prisma:migrateEngine:rpc SENDING RPC CALL {"id":1,"jsonrpc":"2.0","method":"devDiagnostic","params":{"migrationsDirectoryPath":"/Users/panman/Dropbox/Backup/Code/project-api/prisma/migrations"}} +4ms
  prisma:migrateEngine:stderr {"timestamp":"2022-09-26T12:22:46.027178Z","level":"INFO","fields":{"message":"Starting migration engine RPC server","git_hash":"efdf9b1183dddfd4258cd181a72125755215ab7b"},"target":"migration_engine"} +0ms
  prisma:migrate:dev {
  prisma:migrate:dev   devDiagnostic: '{\n  "action": {\n    "tag": "createMigration"\n  }\n}'
  prisma:migrate:dev } +0ms
  prisma:migrateEngine:rpc SENDING RPC CALL {"id":2,"jsonrpc":"2.0","method":"applyMigrations","params":{"migrationsDirectoryPath":"/Users/panman/Dropbox/Backup/Code/project-api/prisma/migrations"}} +4m
  prisma:migrateEngine:stderr {"timestamp":"2022-09-26T12:26:31.646199Z","level":"INFO","fields":{"message":"Analysis run in 117ms","analysis_duration_ms":117},"target":"migration_core::commands::apply_migrations","span":{"name":"ApplyMigrations"},"spans":[{"name":"ApplyMigrations"}]} +4m
  prisma:migrateEngine:stderr {"timestamp":"2022-09-26T12:26:31.646213Z","level":"INFO","fields":{"message":"All the migrations executed in 0ms","apply_migrations_duration_ms":0},"target":"migration_core::commands::apply_migrations","span":{"name":"ApplyMigrations"},"spans":[{"name":"ApplyMigrations"}]} +1ms
  prisma:migrateEngine:rpc SENDING RPC CALL {"id":3,"jsonrpc":"2.0","method":"evaluateDataLoss","params":{"migrationsDirectoryPath":"/Users/panman/Dropbox/Backup/Code/project-api/prisma/migrations","prismaSchema":"generator client {\n  provider = \"prisma-client-js\"\n}\n\ndatasource db {\n  provider          = \"mysql\"\n  url               = env(\"JAWSDB_URL\")\n  shadowDatabaseUrl = env(\"SHADOW_DATABASE_URL\")\n}\n\n[....MODEL PROPERTIES REMOVED FOR EXAMPLE....]} +145ms
  prisma:migrate:dev {
  prisma:migrate:dev   evaluateDataLossResult: { migrationSteps: 0, unexecutableSteps: [], warnings: [] }
  prisma:migrate:dev } +2m
  prisma:migrateEngine:rpc SENDING RPC CALL {"id":4,"jsonrpc":"2.0","method":"createMigration","params":{"migrationsDirectoryPath":"/Users/panman/Dropbox/Backup/Code/project-api/prisma/migrations","migrationName":"","draft":false,"prismaSchema":"generator client {\n  provider = \"prisma-client-js\"\n}\n\ndatasource db {\n  provider          = \"mysql\"\n  url               = env(\"JAWSDB_URL\")\n  shadowDatabaseUrl = env(\"SHADOW_DATABASE_URL\")\n}\n\nmodel [....MODEL PROPERTIES REMOVED FOR EXAMPLE....]"}} +2m
  prisma:migrateEngine:stderr {"timestamp":"2022-09-26T12:31:02.422464Z","level":"INFO","fields":{"message":"Database is up-to-date, returning without creating new migration."},"target":"migration_core::commands::create_migration","span":{"draft":false,"migration_name":"","name":"CreateMigration"},"spans":[{"draft":false,"migration_name":"","name":"CreateMigration"}]} +5m
  prisma:migrate:dev { createMigrationResult: { generatedMigrationName: null } } +3m
  prisma:migrateEngine:rpc SENDING RPC CALL {"id":5,"jsonrpc":"2.0","method":"applyMigrations","params":{"migrationsDirectoryPath":"/Users/panman/Dropbox/Backup/Code/project-api/prisma/migrations"}} +3m
  prisma:migrateEngine:stderr {"timestamp":"2022-09-26T12:31:02.569263Z","level":"INFO","fields":{"message":"Analysis run in 105ms","analysis_duration_ms":105},"target":"migration_core::commands::apply_migrations","span":{"name":"ApplyMigrations"},"spans":[{"name":"ApplyMigrations"}]} +136ms
  prisma:migrateEngine:stderr {"timestamp":"2022-09-26T12:31:02.569303Z","level":"INFO","fields":{"message":"All the migrations executed in 0ms","apply_migrations_duration_ms":0},"target":"migration_core::commands::apply_migrations","span":{"name":"ApplyMigrations"},"spans":[{"name":"ApplyMigrations"}]} +1ms
Already in sync, no schema change or pending migration was found.

✔ Generated Prisma Client (3.13.0 | library) to ./node_modules/@prisma/client in 949ms

### Expected behavior

the same result, but faster :)

### Prisma information

happens for all prisma schemas

### Environment & setup

- OS: OSX
- Database: MySQL
- Node.js version: v18.0.0 - happend on earlier versions too.


### Prisma Version

```
3.13
```

**Comment by annibuliful** [comment] 2022-09-27 00:30
Could you upgrade prisma version to V4?

**Comment by miguelff** [comment] 2023-07-17 17:05
@PanMan are you observing the same behavior with latest versions of prisma as suggested [above](https://github.com/prisma/prisma/issues/15523#issuecomment-1258819625)?

I'm closing the issue for the moment, but if this is still a problem, please don't hesitate to comment below, ideally with a reproduction repository we can try and execute, so we can help you better.

**Closed by miguelff** 2023-07-17 17:05 UTC
Labels: bug/0-unknown, kind/bug, topic: migrate, topic: performance, team/schema, topic: prisma migrate dev

**Comment by Jolg42** [comment] 2023-07-18 07:54
Probably duplicate of https://github.com/prisma/prisma/issues/12229
