### ISSUE TITLE
Order by nulls preview feature not generating type stubs

### ISSUE THREAD

**Issue by jason-s-yu** [prisma/prisma#17081] opened 2022-12-31 20:33 UTC
Hi all. I've been unable to get the `orderByNulls` preview feature to work, following both the documentation example and implementing custom examples.

schema.prisma
```prisma
generator client {
  provider = "prisma-client-js"
  previewFeatures = ["orderByNulls"]
}

datasource db {
  provider = "mongodb"
  url      = env("DATABASE_URL")
}

model User {
  id               String      @id @default(auto()) @map("_id") @db.ObjectId
  name             String?
  phone            String
  email            String?
  timestamp            DateTime?
}
```

user.service.ts
```ts
...
prisma.user.findMany({
  where: { /* conditions */ },
  orderBy: {
    timestamp: { sort: 'asc', nulls: 'last' }
  }
});
```

Upon further inspection, the type stubs in `node_modules/.prisma/index.d.ts` show no definitions for `SortOrderInput` which is the [correct type referenced in the documentation](https://www.prisma.io/docs/reference/api-reference/prisma-client-reference#reference-19). 

The error does not go away after any of these actions: regenerating the client, a clean `node_modules` install (followed by `prisma generate`), and removing `node_modules/.prisma` and regenerating. 

I also tested this out in the [playground](https://playground.prisma.io/examples/reading/find/find-all?host=playground.prisma.io&path=examples). You can reproduce this quickly there by adding the `"orderByNulls"` preview feature to the end of the preview features list and changing any of the scalar values under any model to optional. For instance, making the `name` field optional and running this code in `index.js` will highlight an error under `orderBy` and will fail to run:

```js
import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

const posts = await prisma.post.findMany({
  orderBy: {
    author: {
      name: { sort: 'asc', nulls: 'first' },
    },
  },
})

console.log(posts);
```

The above code snippet uses the code directly from the [documentation](https://www.prisma.io/docs/reference/api-reference/prisma-client-reference#sort-post-by-the-related-user-records-name-with-null-records-first), but you can see that the error still is there with a simpler query (e.g. `prisma.user.findMany({ orderBy: { name: { sort: 'asc', nulls: 'first' } } });`)

On version 4.8.0 (latest as of this post) AND tested on 4.1.0, which is when the feature was added.

Has anyone successfully gotten this preview feature to work? Thanks in advance.

**Comment by Jolg42** [comment] 2023-01-02 15:28
Note: Docs page https://www.prisma.io/docs/concepts/components/prisma-client/filtering-and-sorting#sort-with-null-records-first-or-last
Some tests can be found in https://github.com/prisma/prisma/tree/main/packages/client/tests/functional/order-by-null
But not for MongoDB, I created an issue for that here: https://github.com/prisma/prisma/issues/17100

Next step: someone needs to reproduce/confirm the bug on MongoDB

**Comment by jason-s-yu** [comment] 2023-01-02 21:14
> Next step: someone needs to reproduce/confirm the bug on MongoDB


I reproduced the issue in both Postgres (in the playground) and mongo (local)

**Comment by Weakky** [comment] 2023-05-25 09:48
Hey @jason-s-yu,

MongoDB was intentionally cut out of scope when implementing the feature because it requires too many hacks to support it at the moment.

We might reconsider this in the future. Meanwhile, I'll close your issue in favor of https://github.com/prisma/prisma/issues/16728, which counts as a feature request and not a bug.

Thank you 🙏

**Closed by Weakky** 2023-05-25 09:48 UTC
Labels: bug/1-unconfirmed, kind/bug, topic: previewFeatures, team/client, topic: postgresql, topic: mongodb, topic: orderByNulls
