### ISSUE TITLE
Relation filter operator 'every' does not work correctly

### ISSUE THREAD

**Issue by haond10adp** [prisma/prisma#6456] opened 2021-04-08 02:18 UTC
### Relation filter.
Relation filter operator 'every' does not work correctly.
'Every' will return records in case there's no related record (relation field of that record is an empty array) regardless of filter conditions

### Schema 
Similar to this
[Client API Reference](https://www.prisma.io/docs/reference/api-reference/prisma-client-reference)
```prisma
model ExtendedProfile {
  id        Int    @id @default(autoincrement())
  biography String
  user      User   @relation(fields: userId, references: id)
  userId    Int
}
model User {
  id           Int             @id @default(autoincrement())
  name         String?
  email        String          @unique
  profileViews Int             @default(0)
  role         Role            @default(USER)
  coinflips    Boolean[]
  posts        Post[]
  profile      ExtendedProfile?
}
model Post {
  id         Int        @id @default(autoincrement())
  title      String
  published  Boolean    @default(true)
  author     User       @relation(fields: [authorId], references: [id])
  authorId   Int
  comments   Json?
  views      Int        @default(0)
  likes      Int        @default(0)
  categories Category[]
}
model Category {
  id    Int    @id @default(autoincrement())
  name  String @unique
  posts Post[]
}
enum Role {
  USER
  ADMIN
}
```

### Query
```javascript
const result = await prisma.user.findMany({
    where: {
      posts: {
        // add 'some' here will explicitly fix
        // some: {},
        every: {
          views: {
            gt: 10,
          },
        },
      },
    },
  });
```
### Result
Assuming that user id 11 has no post
![image](https://user-images.githubusercontent.com/39975444/113957474-7d784280-9849-11eb-9f4e-9b3b2c0dc053.png)
the `result` still includes it

## Environment & setup

- OS: , Windows
- Database: PostgreSQL,
- Node.js version: 14.5.5
- Prisma version: 

```
Environment variables loaded from .env
prisma               : 2.20.1
@prisma/client       : 2.20.1
Current platform     : windows
Query Engine         : query-engine 60ba6551f29b17d7d6ce479e5733c70d9c00860e (at node_modules\@prisma\engines\query-engine-windows.exe)
Migration Engine     : migration-engine-cli 60ba6551f29b17d7d6ce479e5733c70d9c00860e (at node_modules\@prisma\engines\migration-engine-windows.exe)
Introspection Engine : introspection-core 60ba6551f29b17d7d6ce479e5733c70d9c00860e (at node_modules\@prisma\engines\introspection-engine-windows.exe)
Format Binary        : prisma-fmt 60ba6551f29b17d7d6ce479e5733c70d9c00860e (at node_modules\@prisma\engines\prisma-fmt-windows.exe)
Default Engines Hash : 60ba6551f29b17d7d6ce479e5733c70d9c00860e
Studio               : 0.365.0
```

**Comment by pantharshit00** [comment] 2021-04-14 12:54
I can confirm this bug, user with no posts are also being returned from that query.

**Comment by pantharshit00** [comment] 2021-04-14 12:56
Another duplicate bug report: https://github.com/prisma/prisma/issues/6441

**Comment by matthewmueller** [comment] 2021-04-14 14:34
This is definitely confusing but the current state is by design. We may consider re-defining behavior:

- Every will return all related records that match or have no relations. 

Next Steps:

- See what SQL does

**Comment by dpetrick** [comment] 2021-04-22 10:20
I looked into the issue and discovered that the generated SQL is not really intuitive:
```sql
SELECT
    "public"."ModelA"."id"
FROM
    "public"."ModelA"
WHERE
    ("public"."ModelA"."id") NOT IN (
        SELECT
            "t0"."id"
        FROM
            "public"."ModelA" AS "t0"
            INNER JOIN "public"."ModelB" AS "j0" ON ("j0"."a_id") = ("t0"."id")
        WHERE
            (
                (NOT "j0"."counter" >= 0)
                AND "t0"."id" IS NOT NULL
            )
    )
```

Intuitively, the SQL should (simplified) be:
```sql
SELECT
    "t0"."id"
FROM
    "public"."ModelA" AS "t0"
    INNER JOIN "public"."ModelB" AS "j0" ON ("j0"."a_id") = ("t0"."id")
WHERE
      "j0"."counter" >= 0
```

Note that the current version inverts the filter condition `(NOT "j0"."counter" >= 0)`, which is odd. I will ask around why that's the case. Straight up changing the behavior is hard, I will schedule follow-up work on this.

**Comment by mentos1386** [comment] 2021-06-21 08:43
Is there any workaround for this issue?

**Comment by aqrln** [comment] 2022-09-02 12:19
Related: https://github.com/prisma/prisma/issues/14847, https://github.com/prisma/prisma/issues/11819

**Comment by SevInf** [comment] 2022-09-06 09:05
As mentioned earlier in this thread, this is not a bug, this an expected behaviour.  In JS, for example `[].every(anything)` will also return `true` and so will do sql `ALL` statement.

If you need to ensure that relationship has at least some records, adding `some: {}` to the query is the way to go.

I am going to close this as duplicate of #11819, let's continue discussion there.

**Closed by SevInf** 2022-09-06 09:05 UTC
Labels: bug/2-confirmed, kind/bug, tech/engines, team/client
