### ISSUE TITLE
`prisma introspect` overwrites a 1:1 mapping as 1:many

### ISSUE THREAD

**Issue by magicmark** [prisma/prisma#3775] opened 2020-09-27 23:46 UTC
It's possible I'm misunderstanding how to model this correctly, but...

## Bug description

From the official docs (https://www.prisma.io/docs/reference/tools-and-interfaces/prisma-schema/relations#one-to-many-relations):

```
model User {
  id      Int      @id @default(autoincrement())
  profile Profile?
}

model Profile {
  id      Int     @id @default(autoincrement())
  user    User    @relation(fields: [userId], references: [id])
  userId  Int     // relation scalar field (used in the `@relation` attribute above)
}
```

Currently, `prisma introspect` is overwriting this as `profile Profile?` as `profile Profile[]`

## How to reproduce

I put together a minimal repro to demonstrate this:  https://github.com/magicmark/repro-prisma-introspection

If you run `prisma introspect`, you get the following diff:

```
$ git diff | cat
diff --git prisma/schema.prisma prisma/schema.prisma
index c87ff7b..06a7841 100644
--- prisma/schema.prisma
+++ prisma/schema.prisma
@@ -9,11 +9,11 @@ datasource db {

 model User {
   id      Int       @default(autoincrement()) @id
-  profile Profile?
+  profile Profile[]
 }

 model Profile {
   id     Int  @default(autoincrement()) @id
-  user   User @relation(fields: [userId], references: [id])
   userId Int
+  user   User @relation(fields: [userId], references: [id])
 }
```

## Expected behavior

No diff to be produced.

## Prisma information

```sql
CREATE TABLE "public"."User" (
  "id" SERIAL PRIMARY KEY
) WITH (OIDS = FALSE);


CREATE TABLE "public"."Profile" (
  "id" SERIAL PRIMARY KEY,
  "userId" INT NOT NULL UNIQUE,
  FOREIGN KEY ("userId") REFERENCES "public"."User"(id)
) WITH (OIDS = FALSE);
```

## Environment & setup

- OS: macOS
- Database: PostgreSQL
- Node.js version: v14.5.0
- Prisma version:
  ```
  $ prisma -v
  Environment variables loaded from prisma/.env
  @prisma/cli          : 2.7.1
  Current platform     : darwin
  Query Engine         : query-engine 5c2ad460cf4fe8c9330e6640b266c046542c8b6a (at node_modules/@prisma/cli/query-engine-darwin)
  Migration Engine     : migration-engine-cli 5c2ad460cf4fe8c9330e6640b266c046542c8b6a (at node_modules/@prisma/cli/migration-engine-darwin)
  Introspection Engine : introspection-core 5c2ad460cf4fe8c9330e6640b266c046542c8b6a (at node_modules/@prisma/cli/introspection-engine-darwin)
  Format Binary        : prisma-fmt 5c2ad460cf4fe8c9330e6640b266c046542c8b6a (at node_modules/@prisma/cli/prisma-fmt-darwin)
  Studio               : 0.288.0
```

**Comment by pantharshit00** [comment] 2020-09-28 14:42
Thanks for the detailed reproduction @magicmark. I can confirm this bug.

This bug is very similar to https://github.com/prisma/prisma/issues/3237 but I am not going to close this as a duplicate for now as your schema doesn't involved a unique keyword on the primary key(It might be because unique is implied by `PRIMARY KEY` but still we should investigate.)

**Comment by do4gr** [comment] 2020-10-01 12:50
Hey, thanks for reporting this. I tried reproducing with the sql you provided here in the issue:

```sql
CREATE TABLE "public"."User" (
  "id" SERIAL PRIMARY KEY
) WITH (OIDS = FALSE);

CREATE TABLE "public"."Profile" (
  "id" SERIAL PRIMARY KEY,
  "userId" INT NOT NULL UNIQUE,
  FOREIGN KEY ("userId") REFERENCES "public"."User"(id)
) WITH (OIDS = FALSE);
```

but got the expected

```prisma
model Profile {
  id     Int  @id @default(autoincrement())
  userId Int @unique
  User   User @relation(fields: [userId], references: [id])
}

model User {
  id      Int       @id @default(autoincrement())
  Profile Profile?
}
```

Your linked reproduction repo has different sql though, this time missing the unique constraint on the userId column. 

```sql
CREATE TABLE "public"."User" (
  "id" SERIAL PRIMARY KEY
) WITH (OIDS = FALSE);


CREATE TABLE "public"."Profile" (
  "id" SERIAL PRIMARY KEY,
  "userId" INT NOT NULL,
  FOREIGN KEY ("userId") REFERENCES "public"."User"(id)
) WITH (OIDS = FALSE);
```

This makes this a 1:M relation which introspection returns. 

```prisma
model Profile {
  id     Int  @id @default(autoincrement())
  userId Int
  User   User @relation(fields: [userId], references: [id])
}

model User {
  id      Int       @id @default(autoincrement())
  Profile Profile[]
}
```

So I think this is working as intended. 

One thing your issue made me realize though is, that in our docs the example schema is missing the @unique on the userId as shown. 

```prisma
model User {
  id      Int      @id @default(autoincrement())
  profile Profile?
}

model Profile {
  id      Int     @id @default(autoincrement())
  user    User    @relation(fields: [userId], references: [id])
  userId  Int     // relation scalar field (used in the `@relation` attribute above)
}
``` 

When migrating this schema we will still create the unique constraint in the database since it is needed to guarantee the 1:1 relation. And when introspecting again we will show it. But that the uniqueness of a scalar field underlying a relationfield and the arity of the relationfield match should be improved in the docs and maybe even be part of a schema validation. 

I'll open separate issues for these though. Sorry for the confusion, I hope this clears it up.

**Closed by do4gr** 2020-10-01 12:50 UTC
Labels: bug/2-confirmed, kind/bug, team/engines, topic: introspection
