### ISSUE TITLE
Schema File Not Found in non monorepo with custom `output`

### ISSUE THREAD

**Issue by MatsG23** [prisma/prisma#10433] opened 2021-11-24 20:07 UTC
### Bug description

Prisma can't find the schema file (schema.prisma). The client can't be used.

Error message:
```
error - Error: ENOENT: no such file or directory, open '...\.next\cache\webpack\client-development\schema.prisma'
```

### How to reproduce

1. Clone https://github.com/MatsG23/prisma-reproducible-example
2. Run `yarn prisma generate`
2. Run `yarn dev`
3. Click on the link NextJS gives you

### Expected behavior

It should find the schema file.

### Prisma information

I set a custom output directory but also import the client from there (how it should be).

### Environment & setup

- OS: Windows
- Database: default values - not even trying to connect
- Node.js version: 17.1.0
- NextJS version: 12.0.4 (uses Webpack 5 and SWC)

### Prisma Version

```
prisma                  : 3.5.0
@prisma/client          : 3.5.0
Current platform        : windows
Query Engine (Node-API) : libquery-engine 78a5df6def6943431f4c022e1428dbc3e833cf8e (at node_modules\@prisma\engines\query_engine-windows.dll.node)
Migration Engine        : migration-engine-cli 78a5df6def6943431f4c022e1428dbc3e833cf8e (at node_modules\@prisma\engines\migration-engine-windows.exe)
Introspection Engine    : introspection-core 78a5df6def6943431f4c022e1428dbc3e833cf8e (at node_modules\@prisma\engines\introspection-engine-windows.exe)
Format Binary           : prisma-fmt 78a5df6def6943431f4c022e1428dbc3e833cf8e (at node_modules\@prisma\engines\prisma-fmt-windows.exe)
Default Engines Hash    : 78a5df6def6943431f4c022e1428dbc3e833cf8e
Studio                  : 0.439.0
```

**Comment by MatsG23** [comment] 2021-11-24 20:08
Is there something I'm doing wrong? I mean, there's an extra page telling Prisma can run with Next.JS:
https://www.prisma.io/nextjs

**Comment by MatsG23** [comment] 2021-11-27 15:00
Magically disappeared after deleting every yarn cache and package folder and removing the custom output path.

**Comment by njmaeff** [comment] 2022-02-27 17:56
I have this issue too and it is related to this line of code and the `findSync` function. The .next directory is read first and if your relative output matches any subdirectories (like mine do with keywords like "server", and "client"), then it selects the wrong `dirname` for the configuration.

https://github.com/prisma/prisma/blob/e679b61111a9dca7200c7e0626b08a3d8cc44c9b/packages/client/src/generation/utils/buildDirname.ts#L38-L41

**Comment by pantharshit00** [comment] 2022-02-28 09:51
@njmaeff Can you please provide a reproduction?

**Comment by njmaeff** [comment] 2022-02-28 16:22
@pantharshit00 

Try this repro.
[https://github.com/njmaeff/prisma-issue-10433](https://github.com/njmaeff/prisma-issue-10433)

**Comment by xygengcn** [comment] 2022-03-12 08:46
3.10.0 same problem，how to solve

**Comment by SomeoneWeird** [comment] 2022-03-30 02:37
I am also running into this now. I am using lerna to manage a monorepo, with prisma schema + client being instantiated in one package, and being required into another package which is a NextJS project.

**Comment by SomeoneWeird** [comment] 2022-03-30 12:32
> Optimally open a new issue with a description of your specific cas @SomeoneWeird, if it is not identical to the one described above. A reproduction repository is optimal, so we can just run this ourselves and see (and later also test our potential fixes).

Rgr, opened https://github.com/prisma/prisma/issues/12588

**Comment by liamross** [comment] 2022-09-26 15:07
My workaround is to copy the `schema.prisma` file from it's location and paste it into `/.../.next/cache/webpack/client-development/schema.prisma`. It'll persist across dev runs, and then if the cache ever is reset I do it again. Not exactly the ideal workaround but simpler than modifying the `runtime/index.js` file which is rebuilt every time.

I'm not entirely sure if this is a Next.js issue or a Prisma issue.

**Comment by roxkstar74** [comment] 2022-10-02 16:59
Hi I am the guy that figured this out, here's some more help for people in the future

> Just coming here to share a workaround by one of our community members who recently ran into this issue and shared their [workaround in the public Prisma Slack](https://prisma.slack.com/archives/CCWDULGUW/p1663644045180299):
> 
> > I just had to manually edit the generated index.js file
> > Exact error message was:
> > `error - Error: ENOENT: no such file or directory, open '/Users/roxworks/projects/dashboard/apps/<myprojectname>/.next/server/pages/api/auth/schema.prisma'`
> > to fix I had to open the generated runtime/index.js file from this
> > ![image](https://user-images.githubusercontent.com/4058327/191222424-da5c51f3-8c75-4a3a-84c2-aec5008b75ae.png)
> > to this:
> > ![image](https://user-images.githubusercontent.com/4058327/191222274-81b6982f-f5d2-4ef5-8628-2cda0f24ee2c.png)

I wrote a script that I keep on my top level that does these edits for me using sed (on most unix boxes which should work wherever you're deployed)

the strategy I used involved pulling out each DB to its own super simple package with just a client.ts

then run this command for each of those packages (i just copy paste this line like 5x and replaced the package for each db)
(I think you might only need this npm run dev)

`
sed -i 's/this.datamodel = import_fs6.default.readFileSync(config2.datamodelPath, "utf-8");/const myPath = config2.generator.output.value + "\/schema.prisma";this.datamodel = import_fs6.default.readFileSync(myPath, "utf-8");/g' packages/YOUR_DB_PACKAGE_NAME/YOUR_GENERATE_OUTPUT_PATH/runtime/index.js;
`

for all of your apps you'll also need to do this, but this gets even MORE confusing because you'll need to edit the next.js bundle files

luckily though it's a similar line, for each app you'll want this

`
sed -i 's/this.datamodel = import_fs6.default.readFileSync(config2.datamodelPath, "utf-8");/const myPath = config2.generator.output.value + "\/schema.prisma";this.datamodel = import_fs6.default.readFileSync(myPath, "utf-8");/g' apps/YOUR_APP_NAME/.next/server/chunks/*.js
`

I take these two commands, and copy paste for each DB/app as many times as needed into my `fixprisma.sh` file

Then, finally, I added to my turbo.json file after my prisma generate step to run `bash fixprisma.sh` as just a straight terminal command. You'll also want to run it after your build step so it picks up the new next.js compiled files

GO FORTH AND PROSPER MY FRIENDS

**Comment by TheoBr** [comment] 2022-10-20 03:32
@roxkstar74 this is absolute chaos and I respect you immensely

Prisma homies, let's get this one fixed 🙏 happy to get y'all in touch w/ Turborepo folks during NextConf

**Comment by gualopezb** [comment] 2022-10-25 15:21
**Fixed with symlinks without having to implement a bash script.**

I was running into this same issue from a turborepo project. The files structure looks like below:

```
.
├── apps
│   └── service
└── packages
    └── database
```

* `packages/database` is a workspace exposing all the database-related functionality through the use of prisma ORM. Instead of transpiling the TypeScript files from the package itself, we follow the [internal packages pattern](https://turborepo.org/docs/handbook/sharing-code/internal-packages) so that the apps and other packages where it's imported from can build the source code from `database` as well. That being said, this is how the `main` and `types` keys in the `packages/database/package.json` file look like:

```
"main": "index.ts",
"types": "index.ts",
```

* `apps/service` is an express.js application built with the serverless framework and it's a consumer of the `database` package mentioned above. This app is compiled using the serverless-esbuild plugin and the javascript files are created into the `apps/service/.esbuild/.build/src` directory. 

The prisma client was generated as expected into `node_modules/.prisma/client`. However, when the `service` app got up and running, it was outputting the following error:

```
ENOENT: no such file or directory, open 'service/.esbuild/.build/src/schema.prisma'
```

Solution:

I managed to get rid of this problem by adding symbolic links for the schema.prisma and engine files inside `apps/service/.esbuild/.build/src` to point where the prisma client actually is.

```
cd apps/service/.esbuild/.build/src
ln -s ../../../../../node_modules/.prisma/client/schema.prisma schema.prisma
ln -s ../../../../../node_modules/.prisma/client/libquery_engine-darwin-arm64.dylib.node libquery_engine-darwin-arm64.dylib.node
```

Lastly, make sure you track both of these symlinks as part of the git repo:
```
git add schema.prisma libquery_engine-darwin-arm64.dylib.node -f
```

**Comment by lottamus** [comment] 2022-11-06 00:11
If you're using nextjs, try adding prisma to the `serverComponentsExternalPackages` in your config:

```js
// next.config.js
const nextConfig = {
  experimental: {
    appDir: true,
    serverComponentsExternalPackages: ['@prisma/client'],
  },
};
```

https://beta.nextjs.org/docs/api-reference/next.config.js#servercomponentsexternalpackages

<img width="781" alt="image" src="https://user-images.githubusercontent.com/7423098/200148019-afdf552a-73ee-4aa8-a9de-0cd2e90aa1c7.png">

**Comment by msmps** [comment] 2022-11-20 19:14
> Hi I am the guy that figured this out, here's some more help for people in the future
> 
> > Just coming here to share a workaround by one of our community members who recently ran into this issue and shared their [workaround in the public Prisma Slack](https://prisma.slack.com/archives/CCWDULGUW/p1663644045180299):
>
> ....

Thanks for this solution, @roxworks! I've had success with this locally, but upon deploying to Vercel, I'm met with the issue again. Is this something you've had success with on Vercel?

![image](https://user-images.githubusercontent.com/7691252/202921295-6e54ce5c-a7f0-4018-9a70-d4b6ea650b38.png)

**Comment by roxworks** [comment] 2022-11-21 18:38
> Thanks for this solution, @roxworks! I've had success with this locally, but upon deploying to Vercel, I'm met with the issue again. Is this something you've had success with on Vercel?

Nope! I gave up on vercel and went to a digitalocean droplet

**Comment by bazo** [comment] 2022-11-24 09:10
why is this file needed after the client has been generated? makes no sense

**Comment by trentonsnyder** [comment] 2022-12-01 20:23
> Thanks for this solution, @roxworks! I've had success with this locally, but upon deploying to Vercel, I'm met with the issue again. Is this something you've had success with on Vercel?

@msmps Locally I have also had success with the @roxworks solution and am continuing to use it during development but for deploying to Vercel I came up with a workaround similar to @gualopezb solution.

After I run `vercel build`  I have a script to place the `schema.prisma` and binary file in the correct place in all the generated function folders in `.vercel/output`. I'm just putting it where the `config2.datamodelPath` variable assumes it will be.

```bash
yes | unzip ./scripts/libquery_engine-rhel-openssl-1.0.x.so.node -d ./scripts/

# slug func
cp ./packages/database/prisma/schema.prisma './.vercel/output/functions/[slug].func/apps/myapp/.next/server/pages/'
cp ./scripts/libquery_engine-rhel-openssl-1.0.x.so.node './.vercel/output/functions/[slug].func/apps/myapp/.next/server/pages/'

# api route func
cp ./packages/database/prisma/schema.prisma './.vercel/output/functions/api/route.func/apps/myapp/.next/server/pages/'
cp ./scripts/libquery_engine-rhel-openssl-1.0.x.so.node './.vercel/output/functions/api/route.func/apps/myapp/.next/server/pages/'
```

Then I'm able to run `vercel deploy --prebuilt`.

I got prisma to give me the proper binary file by adding these lines to the `generator client`. I moved it to my `scripts` folder and zipped it. You don't need these lines afterwards.
```
  engineType    = "library"
  binaryTargets = ["rhel-openssl-1.0.x"]
```

I'm also using a custom output folder for the types and not the `node_modules` default.

Seems like it works so far. But I'll update if I run into any other issues with this approach.

**Comment by soulchild** [comment] 2022-12-12 10:01
Insane how many open issues I came across in all the different libraries (Prisma, TurboRepo, Next.js, pnpm) while googling for this problem. I'm using all of them (it's basically a create-t3-turbo app) and I'm still not sure what the root cause is:

- Is it [pnpm](https://github.com/prisma/prisma/issues/12921#issuecomment-1152901509)? Oh, I need to add `public-hoist-pattern[]=*prisma*` to my `.npmrc`. Too bad: It's already there - not helping … [anymore?](https://github.com/prisma/prisma/issues/12921#issuecomment-1283386023)
- Is it the new [`appDir` feature](https://github.com/prisma/prisma/issues/16117) of Next 13? No, I'm not using that.
- Is it not having `serverComponentsExternalPackages` configured? Oh wait no, that's something Next.js [takes care of automatically now for Prisma](https://github.com/vercel/next.js/blob/canary/packages/next/lib/server-external-packages.ts), so it doesn't help putting `prisma` and `@prisma/client` there
- Is it [Prisma's heuristic](https://github.com/prisma/prisma/issues/10433) for finding the schema.prisma file or one of the other [22 open](https://github.com/prisma/prisma/issues?q=enoent+schema+is%3Aopen) Prisma issues regarding missing schema files?

My current approach for our Docker deployment is a custom output directory in `schema.prisma`: 

```prisma
generator client {
  provider = "prisma-client-js"
  output   = "../../../node_modules/.prisma/client"
}
```

…and a symlink in my Dockerfile:

```
RUN ln -s /app/node_modules/.prisma/client/schema.prisma /app/apps/my-nextjs-app/.next/server/chunks/schema.prisma

CMD ["node", "apps/my-nextjs-app/server.js"]
```

😞

**Comment by millsp** [comment] 2022-12-12 14:05
We have prioritized this issue and we are actively investigating the root causes.

**Comment by soulchild** [comment] 2022-12-12 14:15
Sorry, if my comment sounded a bit rude! After spending hours looking for a solution I was seriously thinking about just abandoning pnpm and TurboRepo and going back to good old npm + Next.js + Prisma, which in my experience works just fine. Good to know that you guys are looking into this.

**Comment by kristinlindquist** [comment] 2022-12-12 14:33
In case it helps anyone, I used the copy plugin to copy around schema.prisma:

```
const CopyPlugin = require('copy-webpack-plugin');

const copyPrismaSchema = (file) => ({
  from: '../../packages/datalab-prisma/lib/prisma/schema.prisma',
  to: path.join(__dirname, file),
});

const moduleExports = {
  webpack: (_config, options) => {
      config.plugins.push(
        new CopyPlugin({
          patterns: [
            copyPrismaSchema('.next/cache/webpack/client-development/'),
            copyPrismaSchema('.next/cache/webpack/server-development/'),
          ],
        })
      );
      return config;
   },
  ...
}
```

**Comment by soulchild** [comment] 2022-12-15 15:37
FWIW, we ditched pnpm (for now) in favor of npm and the problem went away.

**Comment by djedlajn** [comment] 2022-12-28 21:42
Symlinking seems to work but that is such a hack. PNPM does not work with the 4.8.x version but works with 3.x.x. Without looking to deep into Prisma internals why do we need a schema file after the client is generated and at runtime?

**Comment by serg06** [comment] 2022-12-31 05:34
I had the same issue with my serverless + serverless-esbuild app. It was pointing to the directory of my lambda entrypoint. Strangely, I was able to solve it by modifying adapting @lottamus 's solution to my `esbuild.config.js`:

```js
module.exports = (serverless) => {
  return {
    external: [
      '@prisma/client'  // This line
    ],
  };
};
```

**Comment by sneko** [comment] 2023-01-10 14:09
Using `pnpm`, it's a huge pain because no solution above worked for me :/ 

Any progress on this?

**Comment by serg06** [comment] 2023-01-10 19:17
@sneko You could always patch the library and hardcode the correct path

**Comment by hpiaia** [comment] 2023-01-11 19:06
@sneko Looks like prisma doesn't play nice with pnpm by default. The symbolic links of pnpm breaks everything.

A solution that worked for me was adding both those lines that to **.npmrc**

That changes the symbolic links for normal npm directories.
`node-linker=hoisted`

And that to cache Prisma correctly.
`public-hoist-pattern[]=*prisma*`

**Comment by jrr** [comment] 2023-01-18 16:23
I'm *really* looking forward to having a better solution, but for now we're copying the schema to a bunch of different places (thanks @kristinlindquist [^](https://github.com/prisma/prisma/issues/10433#issuecomment-1346613212)):

```js
const copyThePrismaSchemaHere = [
  "./server/pages/foo",
  "./server/pages/bar",
  "./server/pages",
  "./server/chunks",
];

/** @type {import('next').NextConfig} */
const nextConfig = {
  /* ... */
  webpack: (config) => {
    config.plugins.push(
      new CopyWebpackPlugin({
        patterns: copyThePrismaSchemaHere.map((loc) => ({
          from: "../prisma-client.gen/schema.prisma",
          to: loc,
        })),
      })
    );
    return config;
  },
};
```

Each time I use Prisma from a new location I get a new error. I roll my eyes, add the path to the list, check this GitHub issue, and keep moving. 🤭

**Comment by Osman-Sodefa** [comment] 2023-01-18 16:28
Just let us define the path ourselves in `new PrismaClient()` or with an environment variable, please.

**Comment by janpio** [comment] 2023-01-27 01:24
Thanks @njmaeff for your excellent reproduction (and not deleting it after all this time) - I could confirm the problem with that easily. As @MatsG23 had written, removing the custom `output` path in your `schema.prisma` resolves the error in your reproduction as a workaround.

---

Everyone else, if your project is using Next.js but a monorepo, or no custom `output` setting, then this issue is technically not the correct one for you. We have collected similar issues under the `topic: ENOENT schema.prisma` label, and also added the `topic: monorepo` label to many of them: https://github.com/prisma/prisma/issues?q=is%3Aopen+label%3A%22topic%3A+ENOENT+schema.prisma%22+sort%3Aupdated-desc Please subscribe to or comment a reproduction to one of these to be updated about updates. We are currently working on a workaround and close to share that for feedback 🔜 

If your project is _not_ using Next.js (@serg06?), please definitely open a new issue - optimally with a reproduction we can try ourselves. Thanks.

**Comment by maxime4000** [comment] 2023-02-06 20:41
So I had a similar issue. I'm using Nx, I made a package nestjs:library and add the schema in the package folder. I did install @nx-tools/nx-prisma and generated init on the lib just made. 

I had 2 issues : I was needed to use this path in project.json schema: "package/lib-prisma/prisma/schema.prisma"
In my index.ts, I was exporting : `export * from "../dist/client/"` and generator's output was "../dist/client". 

This was working for me, not my colleague. I was using yarn and yarn was working with the schema path said earlier. 
Removing yarn.lock, nx was calling npm instead and the path required was `prisma/schema.prisma`. That being said, when calling the package lib-prisma from our other apps (NestJS/NextJS), I was getting this error.
```
error - Error: ENOENT: no such file or directory, open 
'/Users/maxime/Repo/monorepo/node_modules/.prisma/client/schema.prisma'
```

Yarn was the issue where the default setup wasn't working, but was fixing this error. On npm, I wasn't able to make that work, so I decide to remove the output param in the generator and `export * from "@prisma/client"` instead. I wish I could have make this work, because if we need to have a second prisma package, I expect this error to haunt us again...

**Comment by millsp** [comment] 2023-02-06 21:20
Hey @maxime4000 could you provide us with a reproduction? Maybe we could help, as we have been working on a webpack [plugin to help copying the engines and the schema](https://github.com/prisma/prisma/issues/12921#issuecomment-1414839304). Your case seems more complex, as we've only looked into helping Next.js users for now. A repro would be much appreciated.

**Comment by maxime4000** [comment] 2023-02-06 22:33
So it's not an exact replica of what we have. I cut corner to make this quick. Things are more complicated in our repo than it is here. Tbh the error I see in the reproduction repo is the similar but not the same as our working repo, remove the @nestjs/schematics part and the call stack that is different. Close enough to think it should suffice.

https://github.com/maxime4000/prisma-schema-nx

**Comment by millsp** [comment] 2023-05-12 16:54
Generally we have fixed most Next.js + schema not found issues via `@prisma/nextjs-monorepo-workaround-plugin` (feedback [here](https://github.com/prisma/prisma/issues/18069)), and fixed client mismatches with `findSync` have also been fixed. If something is still off for you, please create an issue. Thanks!

**Closed by millsp** 2023-05-12 16:54 UTC
Labels: bug/1-unconfirmed, kind/bug, tech/typescript, topic: Next.js, team/client, topic: turborepo, topic: ENOENT schema.prisma
