### ISSUE TITLE
Instead of Json datatype we specify a model but save as json in DB Level

### ISSUE THREAD

**Issue by sandbox-apps** [prisma/prisma#8466] opened 2021-07-27 15:53 UTC
## Problem
One of the biggest strength of Prisma is "Auto-generated and type-safe query builder for Node.js & TypeScript" which is really true `type-safe`. The problem was the json data type data type which loses all the purpose of Type-safety.

Current
```graphql
model Something {
  x Json
  y Json?
  z Json[]
}
```

## Suggested solution
We must be atleast type-safe on prisma level which will benefit the client query generation because now it can infer the types because of the schema given and most specially it will benefit mongoDB users as they will work in `NoSQL` structure

Suggestion:
```graphql
json X {
  a String
  b Int
  c Boolean
  d DateTime
}

json Y {
  a String
  b Int
  c Boolean
  d DateTime
}

json Z {
  a String
  b Int
  c Boolean
  d DateTime
}

model Something {
  x X
  y Y?
  z Z[]
}
```

After all maybe we can have some more benefits here like using this following at the json level definition:
`@default('Hello World')`
`@default('123')`
`@default(false)`
`@default(cuid())`

## Alternatives
If you have seen or known mongoose, Mongoose is the ODM/ORM for MongoDB a NoSQL database. Mongoose lets as specify a schema even if is working with JSON data. So we shouldn't be loosing type-safety when working with JSON.

**Comment by pantharshit00** [comment] 2021-07-28 20:09
Closing as duplicate of https://github.com/prisma/prisma/issues/3219

**Closed by pantharshit00** 2021-07-28 20:09 UTC
