### ISSUE TITLE
Prisma DB Seed not working on Windows

### ISSUE THREAD

**Issue by ruheni** [prisma/prisma#7648] opened 2021-06-14 14:35 UTC
### Bug description

Seeding the DB on Windows 10 doesn't seem to work - from the Prisma examples.

### How to reproduce

Clone example:
```bash
curl https://codeload.github.com/prisma/prisma-examples/tar.gz/latest | tar -xz --strip=2 prisma-examples-latest/javascript/graphql-sdl-first
```

Install dependencies:
```bash
cd graphql-sdl-first
npm install
```
Run migration and seed DB
```bash
npx prisma migrate dev --name init
npx prisma db seed --preview-feature
```

The output is as follows:
```bash
Prisma schema loaded from prisma\schema.prisma
Running seed from "prisma\seed.js" ...

Your database has been seeded.
```

On running `npx prisma studio`, all the tables are empty.

### Expected behavior

The output of the command is expected to be:

```bash
Prisma schema loaded from prisma/schema.prisma
Running seed from "prisma/seed.js" ...
Result:
Start seeding ...
Created user with id: 1
Created user with id: 2
Created user with id: 3
Seeding finished.

🌱  Your database has been seeded.
```

### Prisma information

```groovy
generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "sqlite"
  url      = "file:./dev.db"
}

model User {
  id    Int     @id @default(autoincrement())
  email String  @unique
  name  String?
  posts Post[]
}

model Post {
  id        Int      @id @default(autoincrement())
  createdAt DateTime @default(now())
  updatedAt DateTime @updatedAt
  title     String
  content   String?
  published Boolean  @default(false)
  viewCount Int      @default(0)
  author    User?    @relation(fields: [authorId], references: [id])
  authorId  Int?
}

```

### Environment & setup

- OS:  Windows
- Database: SQLite
- Node.js version: 12.16.0, 15.8.0 [Original GH Issue](https://github.com/prisma/prisma-examples/issues/2923#issuecomment-860712620)

### Prisma Version

```bash
prisma               : 2.24.1
@prisma/client       : 2.24.1
Current platform     : debian-openssl-1.1.x
Query Engine         : query-engine 18095475d5ee64536e2f93995e48ad800737a9e4 (at node_modules/@prisma/engines/query-engine-debian-openssl-1.1.x)
Migration Engine     : migration-engine-cli 18095475d5ee64536e2f93995e48ad800737a9e4 (at node_modules/@prisma/engines/migration-engine-debian-openssl-1.1.x)
Introspection Engine : introspection-core 18095475d5ee64536e2f93995e48ad800737a9e4 (at node_modules/@prisma/engines/introspection-engine-debian-openssl-1.1.x)
Format Binary        : prisma-fmt 18095475d5ee64536e2f93995e48ad800737a9e4 (at node_modules/@prisma/engines/prisma-fmt-debian-openssl-1.1.x)
Default Engines Hash : 18095475d5ee64536e2f93995e48ad800737a9e4
Studio               : 0.397.0
```

**Comment by davidchalifoux** [comment] 2021-06-14 14:39
This is currently being tracked in https://github.com/prisma/prisma/issues/7176

**Comment by janpio** [comment] 2021-06-14 19:19
Duplicate of https://github.com/prisma/prisma/issues/7176 then - thanks for making the connection @davidchalifoux!

**Closed by janpio** 2021-06-14 19:19 UTC
Labels: kind/bug
