### ISSUE TITLE
introspect: Unhandled promise and duplicated output on Error

### ISSUE THREAD

**Issue by janpio** [prisma/prisma#1923] opened 2020-03-24 18:21 UTC
When reproducing https://github.com/prisma/prisma2/issues/1648 this happens:

This is what it looks like on crash:
```
C:\Users\Jan\Documents\throwaway\1649>prisma2 introspect
Introspecting based on datasource defined in prisma\schema.prisma …
 ERROR  Oops, an unexpected error occured!
[libs/sql-schema-describer/src/sqlite.rs:309:37] to
Please help us improve Prisma 2 by submitting an error report.
Error reports never contain personal or other sensitive information.
Learn more: https://pris.ly/d/telemetry

┌─ Submit error report ────────────────────────────────────────────────────────┐  
│                                                                              │  
│ > Yes            Send error report once                                      │  
│   No             Don't send error report                                     │  
│                                                                              │  
└──────────────────────────────────────────────────────────────────────────────┘  
(node:15536) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
![image](https://user-images.githubusercontent.com/183673/77462307-408b0a80-6e04-11ea-8eae-96a83c129d4b.png)

And this after switching to "No":

```
C:\Users\Jan\Documents\throwaway\1649>prisma2 introspect
Introspecting based on datasource defined in prisma\schema.prisma …
 ERROR  Oops, an unexpected error occured!
[libs/sql-schema-describer/src/sqlite.rs:309:37] to
Please help us improve Prisma 2 by submitting an error report.
 ERROR  Oops, an unexpected error occured!
[libs/sql-schema-describer/src/sqlite.rs:309:37] to
Please help us improve Prisma 2 by submitting an error report.
Error reports never contain personal or other sensitive information.
Learn more: https://pris.ly/d/telemetry

┌─ Submit error report ────────────────────────────────────────────────────────┐  
│                                                                              │  
│   Yes            Send error report once                                      │  
│ > No             Don't send error report                                     │  
│                                                                              │  
└──────────────────────────────────────────────────────────────────────────────┘  

```

![image](https://user-images.githubusercontent.com/183673/77462370-57316180-6e04-11ea-8130-b4cf34db6fb7.png)

And this when sending:
```
C:\Users\Jan\Documents\throwaway\1649>prisma2 introspect
Introspecting based on datasource defined in prisma\schema.prisma …
 ERROR  Oops, an unexpected error occured!
[libs/sql-schema-describer/src/sqlite.rs:309:37] to
Please help us improve Prisma 2 by submitting an error report.
[libs/sql-schema-describer/src/sqlite.rs:309:37] to
We successfully received the error report
To help us even more, please create an issue at https://github.com/prisma/prisma2/issues/new
mentioning the report id 2317.

Thanks a lot for your help! �🙏                                                   

C:\Users\Jan\Documents\throwaway\1649>
```
![image](https://user-images.githubusercontent.com/183673/77462494-7a5c1100-6e04-11ea-8056-9984f450b91c.png)

The error was indeed sent successfully, so this is just a tiny cosmetic problem.

**Comment by pantharshit00** [comment] 2020-03-26 10:32
I was unable to reproduce this on a Mac. It correctly displays data.
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/22195362/77637118-2b84b780-6f7b-11ea-9d9d-a0e73549f268.png">

This might be windows specific so I think I will test this in windows.

**Comment by pantharshit00** [comment] 2020-07-24 11:04
Looks like #1648 is fixed now and I tested it again on windows and mac and it doesn't crash on the latest version.

I am going to close this now.

**Closed by pantharshit00** 2020-07-24 11:04 UTC
Labels: bug/1-repro-available, kind/bug, status/needs-action, topic: cli-introspect
