### ISSUE TITLE
PANIC: called `Option::unwrap()` on a `None` value in query-engine/core/src/query_document/parser.rs:250:87

### ISSUE THREAD

**Issue by eduardondev** [prisma/prisma#11321] opened 2022-01-22 01:46 UTC
Hi Prisma Team! My Prisma Client just crashed. This is the report:
## Versions

| Name            | Version            |
|-----------------|--------------------|
| Node            | v16.13.1           | 
| OS              | debian-openssl-1.1.x|
| Prisma Client   | 3.5.0              |
| Query Engine    | 0.1.0              |
| Database        | mysql              |

## Logs
```
  prisma:tryLoadEnv Environment variables loaded from /mnt/c/Users/Avell A52/Desktop/Programação/tiny-transportadoras/.env  
  prisma:tryLoadEnv Environment variables loaded from /mnt/c/Users/Avell A52/Desktop/Programação/tiny-transportadoras/.env  
  prisma:client clientVersion: 3.5.0  
  prisma:client:libraryEngine internalSetup  
  prisma:client:libraryEngine Search for Query Engine Library in /mnt/c/Users/Avell A52/Desktop/Programação/tiny-transportadoras/node_modules/.prisma/client  
  prisma:client:libraryEngine loadEngine using /mnt/c/Users/Avell A52/Desktop/Programação/tiny-transportadoras/node_modules/.prisma/client/libquery_engine-debian-openssl-1.1.x.so.node  
  prisma:client:libraryEngine sending request, this.libraryStarted: false  +33s
  prisma:client:libraryEngine library starting  
  prisma:client:libraryEngine library started  +2s
  prisma:client:libraryEngine sending request, this.libraryStarted: true  +7s
  prisma:client:libraryEngine sending request, this.libraryStarted: true  +7s
  prisma:client:libraryEngine sending request, this.libraryStarted: true  +1s
  prisma:client:libraryEngine sending request, this.libraryStarted: true  +3s
  prisma:client:libraryEngine sending request, this.libraryStarted: true  +4s
  prisma:client:libraryEngine sending request, this.libraryStarted: true  +3s
  prisma:client:libraryEngine sending request, this.libraryStarted: true  +3s
  prisma:client:libraryEngine sending request, this.libraryStarted: true  +11s
  prisma:client:libraryEngine sending request, this.libraryStarted: true  +4s
  prisma:client:libraryEngine sending request, this.libraryStarted: true  +2s
  prisma:client:libraryEngine sending request, this.libraryStarted: true  +9s
  prisma:client:libraryEngine sending request, this.libraryStarted: true  +7s
  prisma:client:libraryEngine sending request, this.libraryStarted: true  +13s
  prisma:client:libraryEngine sending request, this.libraryStarted: true  +5s
  prisma:client:libraryEngine sending request, this.libraryStarted: true  +2s
  prisma:client:libraryEngine sending request, this.libraryStarted: true  +3s
  prisma:client:libraryEngine sending request, this.libraryStarted: true  +3s
  prisma:client:libraryEngine sending request, this.libraryStarted: true  +19s
  prisma:client:libraryEngine sending request, this.libraryStarted: true  +3s
  prisma:client:libraryEngine sending request, this.libraryStarted: true  +4s
  prisma:client:libraryEngine sending request, this.libraryStarted: true  +17s
  prisma:client:libraryEngine sending request, this.libraryStarted: true  +8s
```

## Client Snippet
```ts
 const verifyLastStatus = await prisma.tracking.findMany({
        where: {
          shipping: order.shipping,
          nf: order.tracker,
          ocurrencyStatus: order.ocurrency.statusLast,
        },
      })
```

## Schema
```prisma
// This is your Prisma schema file,
// learn more about it in the docs: https://pris.ly/d/prisma-schema

generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "mysql"
  url      = env("DB_URL")
}

model Tracking {
  id          Int     @id @default(autoincrement())
  createdAt   DateTime? @default(now())
  shipping    String
  nf          Int
  lastStatus  String
  ocurrencyStatus Int @default(0)
}

model Emails {
  id          Int      @id @default(autoincrement())
  createdAt   DateTime @default(now())
  trackingId  Int   @unique
  success     Int
}

```

## Prisma Engine Query
```
{"X":{}}
```

**Comment by matthewmueller** [comment] 2022-01-28 14:50
Hey @eduardondev, what data did you send in:

```
 const verifyLastStatus = await prisma.tracking.findMany({
        where: {
          shipping: order.shipping,
          nf: order.tracker,
          ocurrencyStatus: order.ocurrency.statusLast,
        },
      })
```

What's `order.shipping`, `order.tracker`, `order.ocurrency.statusLast`?

**Comment by dpetrick** [comment] 2022-03-25 14:53
Duplicate of https://github.com/prisma/prisma/issues/10586

**Closed by dpetrick** 2022-03-25 14:53 UTC
Labels: bug/0-unknown, kind/bug, team/client, topic: query-crash
