### ISSUE TITLE
Generated types for `client.$on(...)` are out of sync

### ISSUE THREAD

**Issue by millsp** [prisma/prisma#8291] opened 2021-07-14 23:18 UTC
### Bug description

The generated client is only accepting (ts) calls like:

```ts
client.$on('beforeExit', () => ...)
```

But internally, we support
```ts
'query' | 'info' | 'warn' | 'error' | 'beforeExit'
```

### How to reproduce

```ts
client.$on('query', () => ...)
```

### Expected behavior

We should accept all `EngineEventType`s

### Environment & setup

- OS: N/A
- Database: N/A
- Node.js version: N/A

### Prisma Version

```
2.27.0
```

(cc @dac09)

**Comment by pantharshit00** [comment] 2021-07-16 15:48
I think this works already, you need to enable them first in order to use them as we narrow types via a generic: 

```ts
  const prisma = new PrismaClient({
    log: [{ emit: "event", level: "query" }],
  });

  prisma.$on("query", (e) => {
    //e.params
  });
```

![image](https://user-images.githubusercontent.com/22195362/125974290-ec59cc95-020a-4cc6-936a-2947ce8b4249.png)


But we have don't have this setup for "info", "warn" and "error" so still there is some work remaining here.

**Comment by irbian** [comment] 2021-08-10 22:29
I can confirm this is broken on 2.29

**Comment by tg970** [comment] 2021-09-16 15:19
Just updated to v3.0.2 and this is still broken: 

![image](https://user-images.githubusercontent.com/32203310/133639051-c8c6c03f-7d07-4c1f-ba17-63b6e44a549f.png)

It also appears events are NOT being emitted at all - the `stdout` setting works for the logger but not `event`s.

**Comment by janpio** [comment] 2021-09-16 16:42
> It also appears events are NOT being emitted at all - the `stdout` setting works for `query`, `info` but not getting errors on the `stdout` or `event`s for any log.

That sounds like it deserves a separate issue. Please open one and provide all the information and optimally a way to reproduce this. Thanks.

**Comment by SevInf** [comment] 2022-05-04 15:38
Checked in 3.13 and it appears to be working right now

**Closed** 2022-05-06 08:32 UTC
Labels: bug/2-confirmed, kind/bug, topic: client types, tech/typescript, team/client

**Comment by janpio** [comment] 2022-05-06 18:59
Sure @SevInf? I see similar to what @pantharshit00 posted before: 
<img width="455" alt="image" src="https://user-images.githubusercontent.com/183673/167201167-5f29a09b-5a39-4786-9f0b-af2504c11af0.png">

**Comment by SevInf** [comment] 2022-05-07 07:37
@janpio autocompletetion/typechecking for events other than `beforeExit` will work only if you enable corresponding events in the `log` config. In your example, you get `beforeExit` event because it's always emitted and `info` because you configured it. In order to get other events you have to enable them as well. Or am I misunderstanding the way it is supposed to work?

**Comment by janpio** [comment] 2022-05-09 10:47
Yes, this is what this issue is about. Quote from Harshit's message above:

> But we have don't have this setup for "info", "warn" and "error" so still there is some work remaining here.

**Comment by SevInf** [comment] 2022-05-09 11:12
@janpio sorry, I still don't quite understand. What does "we don't have this setup" mean? If I configure client like this:

```ts
const client = new PrismaClient({
  log: [
    {level: 'info', emit: 'event' },
    {level: 'warn', emit: 'event' },
    {level: 'error', emit: 'event' },
  ]
})

```

I'll get autocomplete for all the events:

![image](https://user-images.githubusercontent.com/603056/167398071-c2681a46-a276-485a-bcc0-b3678e00550e.png)

Is that not how it's supposed to work? The [docs](https://www.prisma.io/docs/concepts/components/prisma-client/working-with-prismaclient/logging) give me the impression that it is, i.e. `info` level is not supposed to enable all underlying events as well.

**Comment by janpio** [comment] 2022-05-09 12:25
Then this goes back to the original messages from @millsp and @pantharshit00 being unclear what should actually be changed here. I read both Pierre's and Harshit's message that the autocompletion should list all options even when not enabled. If that is not the case, we should confirm this explicitly and make sure the documentation does not indicate otherwise (or explicitly mentions this in some way).

**Comment by millsp** [comment] 2022-05-09 14:16
It might be that the docs were unclear back then, but I double checked now and it is properly documented. Other theory: I might have assumed during onboarding that doing `$on('<event>')` was the only thing to do. So probably more of a DX issue in the end?
