### ISSUE TITLE
Using the @unique constraint gives an error when Hasura tries to track the tables that use it

### ISSUE THREAD

**Issue by xanxuz** [prisma/prisma#6292] opened 2021-03-28 22:23 UTC
## Bug description

When I use an @unique constraint on a field (required or optional) and then try to use the table containing that field in Hasura, it gives an error saying:

### Adding existing table/view failed
**"cannot include model.field_unique" in the GraphQL schema because it is not a valid GraphQL identifier"** 

> model => the model name
> field => the name of the field with the constraint @unique

## How to reproduce

1. Create two models to confirm

```prisma
model RequiredUnique {
  id    String  @id @default(uuid())
  email String @unique
}

model OptionalUnique {
  id    String  @id @default(uuid())
  email String? @unique
}
```

2. Push the changes to a local/remote Postgres instance
```bash
prisma db push --preview-feature
```
3. Use local/remote Hasura instance
4. Add the Postgres instance as a datasource to the Hasura instance
5. Search for the created schema in Hasura
6. Track the RequiredUnique or OptionalUnique tables
![image](https://user-images.githubusercontent.com/11968584/112769536-a13cbc80-8fef-11eb-9a74-00d0f26385e3.png)
![image](https://user-images.githubusercontent.com/11968584/112769547-b0236f00-8fef-11eb-82bb-639a8b8f05de.png)

According to Phpstorm, the tables are being created with the following SQL:
```sql
-- auto-generated definition
create table "RequiredUniqueTest"
(
    id    text not null
        constraint "RequiredUniqueTest_pkey"
            primary key,
    email text not null
);

alter table "RequiredUniqueTest"
    owner to postgres;

create unique index "RequiredUniqueTest.email_unique"
    on "RequiredUniqueTest" (email);
```
```sql
-- auto-generated definition
create table "OptionalUniqueTest"
(
    id    text not null
        constraint "OptionalUniqueTest_pkey"
            primary key,
    email text
);

alter table "OptionalUniqueTest"
    owner to postgres;

create unique index "OptionalUniqueTest.email_unique"
    on "OptionalUniqueTest" (email);

```

From what I see, the error that Hasura gives is because the index is being created with a "." instead of "\_", and that's weird because in the [docs](https://www.prisma.io/docs/guides/general-guides/database-workflows/unique-constraints-and-indexes/postgresql) you always use "_", never "." when creating a unique index. 

_The unique constraint works well with the Prisma client, the problem only arises in this case._

## Expected behavior

Use the @unique constraint without problem when a service such as Hasura tries to use the same Postgres DB that Prisma has migrated.

## Environment & setup

- OS: Windows 10
- Database: PostgreSQL
- Node.js version: v14.15.1
- Prisma version:
```
Environment variables loaded from .env
prisma               : 2.19.0
@prisma/client       : 2.19.0
Current platform     : windows
Query Engine         : query-engine c1455d0b443d66b0d9db9bcb1bb9ee0d5bbc511d (at node_modules\@prisma\engines\query-engine-windows.exe)
Migration Engine     : migration-engine-cli c1455d0b443d66b0d9db9bcb1bb9ee0d5bbc511d (at node_modules\@prisma\engines\migration-engine-windows.exe)
Introspection Engine : introspection-core c1455d0b443d66b0d9db9bcb1bb9ee0d5bbc511d (at node_modules\@prisma\engines\introspection-engine-windows.exe)
Format Binary        : prisma-fmt c1455d0b443d66b0d9db9bcb1bb9ee0d5bbc511d (at node_modules\@prisma\engines\prisma-fmt-windows.exe)
Studio               : 0.358.0
Preview Features     : createMany
```

**Comment by janpio** [comment] 2021-03-29 19:00
Interesting, did I assume correctly that you are using `prisma db push` to push these changes to your database?

**Comment by xanxuz** [comment] 2021-03-29 19:14
Yes @janpio , give me a second and I will add it to the issue description

**Comment by xanxuz** [comment] 2021-03-29 19:20
@janpio let me know if you need more info 🙂

**Comment by tomhoule** [comment] 2021-03-31 08:13
Hi @xanxuz — we are currently working on a principled stance on index names.

Would something like `@@unique([email], name: "my_index")` work?

**Comment by xanxuz** [comment] 2021-03-31 14:02
> Hi @xanxuz — we are currently working on a principled stance on index names.
> 
> Would something like `@@unique([email], name: "my_index")` work?

The solution is simpler than that @tomhoule , you just have to fix the generated constraint on Postgres.

### Example

From
```sql
create unique index "table.field_unique" on "table" (field);
```

To (the only difference is **table_field** instead of **table.field**) 
```sql
create unique index "table_field_unique" on "table" (field);
```

Even in the examples on your docs, you use "_", never a dot.

![image](https://user-images.githubusercontent.com/11968584/113147143-77a5b000-91fe-11eb-8996-a77ca51d6e36.png)

**Comment by xanxuz** [comment] 2021-03-31 17:35
I have tried changing the dot for an underscore with SQL using Phpstorm and it works, so the solution is definitely to change the dot to an underscore in the Postgre generator.

![image](https://user-images.githubusercontent.com/11968584/113186410-9ff4d500-9225-11eb-956d-ce2475ac8310.png)
![image](https://user-images.githubusercontent.com/11968584/113186594-dd596280-9225-11eb-9be3-1b821f84b260.png)

**Comment by pantharshit00** [comment] 2021-05-16 13:57
Related: https://github.com/prisma/prisma/issues/6680

**Comment by stonymahony** [comment] 2021-06-06 13:53
I suffer from the same problem and can confirm the cause, is there a fix planned for this?

**Comment by janpio** [comment] 2021-06-06 20:10
Yes, https://github.com/prisma/prisma/issues/6680 is being worked on and will change the index naming in a way that should make it compatible with Hasura.

**Comment by do4gr** [comment] 2021-08-11 12:48
A fix for this issue is now available via the `namedConstraints` preview flag since 2.29. We now have a default naming convention without invalid characters. See https://www.prisma.io/docs/guides/upgrade-guides/upgrading-to-use-preview-features/enabling-named-constraints

**Closed by do4gr** 2021-08-11 12:48 UTC
Labels: bug/0-needs-info, kind/bug, team/migrations, topic: db push, topic: namedConstraints
