### ISSUE TITLE
`prisma generate` uses `query-engine-debian-openssl-1.0.x` instead of `linux-arm-openssl-1.0.x` for my ARM based machine

### ISSUE THREAD

**Issue by owen26** [prisma/prisma#5547] opened 2021-02-08 22:47 UTC
## Bug description

Glad to hear Prisma started to support ARM binaries. But I'm still not be able to run it on my Synology DSM distribution which is arm based.

Error message:

```
query-engine-debian-openssl-1.0.x: cannot execute binary file
```

## How to reproduce

- npm install prisma
- create a dummy `schema.prisma` file, set binaryTargets = ["linux-arm-openssl-1.0.x"]
- run `prisma generate`

Above error shown.

## Expected behavior

`prisma generate` be able to run

## Environment & setup

Synology DSM

`uname -a` output:

```
Linux DS218j 3.10.105 #25426 SMP Mon Dec 14 18:44:29 CST 2020 armv7l GNU/Linux synology_armada38x_ds218j
```

`@prisma/get-platform` output:

```
debian-openssl-1.0.x
```

@prisma/client@2.16.1

**Comment by pantharshit00** [comment] 2021-02-09 10:53
armv7l is 32bit. We have only launched support for arm64(also known as aarch64) so this is kind of expected. You will need to build the engines yourself here. 


Closing as duplicate of https://github.com/prisma/prisma/issues/5497

**Closed by pantharshit00** 2021-02-09 10:53 UTC
