### ISSUE TITLE
TS client: Wrong return type for `prima.model( where: ..`

### ISSUE THREAD

**Issue by LarsJK** [prisma/prisma#4305] opened 2019-04-04 08:12 UTC
**Describe the bug**

If I have a model User and try to fetch one that does not exist, with this method:

`user: (where: UserWhereUniqueInput) => UserPromise`

TypeScript does not warn me that the user might be null:

```ts
const user = await prisma.user({ id: '123' }); // null
user.name // TypeScript does not warn me about this.
```

The generated type should be something like:
`user: (where: UserWhereUniqueInput) => UserPromise | Promise<null>`

**To Reproduce**
1. Given the datamodel:
  ```graphql
  type User {
    id: ID! @unique
    name: String!
  }
  ```
2. Fetch a user that does not exist:
  ```ts
  const user = await prisma.user({ id: '123' }) // There is no user with the ID 123!
  ```
3. Observe the type of user.
  It is `User`.

**Expected behavior**
The expected type would be `User | null`

**Screenshots**

**Versions (please complete the following information):**
 - Connector: `Postgres`
 - Prisma Server: `1.29`
 - `prisma` CLI: `prisma/1.29.2 (darwin-x64) node-v11.10.1`
 - OS: `OS X High Sierra`

**Comment by pantharshit00** [comment] 2019-04-04 13:53
Closing as a duplicate of #3372

**Closed by pantharshit00** 2019-04-04 13:53 UTC
Labels: area/client/ts, bug/2-confirmed
