### ISSUE TITLE
Prisma doesnt work with ESM (.mjs) on node v15.5.0

### ISSUE THREAD

**Issue by anonrig** [prisma/prisma#4816] opened 2020-12-29 18:08 UTC
## Bug description

ESM support is missing, and prevents our company from migrating into Prisma, in our microservices.

## How to reproduce

prisma.mjs file

```javascript
import { PrismaClient } from '@prisma/client'

export default new PrismaClient()

```

receives the error

```
import { PrismaClient } from '@prisma/client'
         ^^^^^^^^^^^^
SyntaxError: Named export 'PrismaClient' not found. The requested module '@prisma/client' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from '@prisma/client';
const { PrismaClient } = pkg;
```

## Expected behavior

It should support ESM modules since it's released on latest node versions. take a look into: https://nodejs.org/api/esm.html

**Comment by pantharshit00** [comment] 2020-12-31 15:27
There is on going work for esm support: https://github.com/prisma/prisma/pull/4265

**Comment by pantharshit00** [comment] 2020-12-31 15:27
Closing this as a duplicate of https://github.com/prisma/prisma-client-js/issues/539

**Closed by pantharshit00** 2020-12-31 15:27 UTC
Labels: kind/feature, team/client

**Comment by timsuchanek** [comment] 2021-01-08 15:03
@anonrig please follow the advice in the error message in the meantime and just import it like so:
```ts
import Prisma from '@prisma/client';
const { PrismaClient } = Prisma;
```

**Comment by Jolg42** [comment] 2021-09-03 14:38
See https://github.com/prisma/prisma/issues/5030#issuecomment-912588323

**Comment by mkreuzmayr** [comment] 2023-01-23 08:30
Here is the type-safe ESM ready solution I came up with.

https://github.com/prisma/prisma/issues/5030#issuecomment-1398076317
> 
> ```typescript
> import type { PrismaClient as ImportedPrismaClient } from '@prisma/client';
> import { createRequire } from 'module';
> 
> const require = createRequire(import.meta.url ?? __filename);
> 
> const { PrismaClient: RequiredPrismaClient } = require('@prisma/client');
> 
> const _PrismaClient: typeof ImportedPrismaClient = RequiredPrismaClient;
> 
> export class PrismaClient extends _PrismaClient {}
> ```

**Comment by cassepipe** [comment] 2023-07-05 14:44
For those like me wondering what is 
```js
import { createRequire } from 'module';
```
"module", like "path", is part of the node API : https://nodejs.org/api/module.html#modulecreaterequirefilename

**Comment by cassepipe** [comment] 2023-07-05 19:50
@timsuchanek What if you need the `Prisma` types ?
https://www.prisma.io/docs/concepts/components/prisma-client/advanced-type-safety

**Comment by mkreuzmayr** [comment] 2023-07-06 05:26
> @timsuchanek What if you need the `Prisma` types ? [prisma.io/docs/concepts/components/prisma-client/advanced-type-safety](https://www.prisma.io/docs/concepts/components/prisma-client/advanced-type-safety)

You could create a `d.ts` file that exports all types.

> For those like me wondering what is
> 
> ```js
> import { createRequire } from 'module';
> ```
> 
> `"module"`, like `"path"`, is part of the node API : [nodejs.org/api/module.html#modulecreaterequirefilename](https://nodejs.org/api/module.html#modulecreaterequirefilename)
> 
> My guess is that we don't have `require` in an esm module and so we have call in the node API instead. Is this correct ? @mkreuzmayr

Kinda. `require` is not available anymore in esm and you can emulate its functionality via the `createRequire` function.
