### ISSUE TITLE
rawQuery returns error on to_tsvector parameter

### ISSUE THREAD

**Issue by u007** [prisma/prisma#9055] opened 2021-09-01 07:20 UTC
### Bug description

```
const content = `blabla bla
with multiple line
"haha"
& other text`;
const id = 1;
const res = await prisma.$queryRaw(`UPDATE ${schema}."TSTable" SET content=to_tsvector('simple', ?), 
    "updatedAt"=now() where job_id=?`, content, id);
```
```
Raw query failed. Code: `42601`. Message: `db error: ERROR: syntax error at or near ")"`
    at cb (/home/james/www/kbe/node_modules/@prisma/client/runtime/index.js:36374:17)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
...
```

### Expected behavior

it should replaced string ? with content and second ? with id

### Prisma information

```
model TSTable {
  id          Int                      @id @default(autoincrement())
  job_id      Int?
  content     Unsupported("tsvector")?
  createdAt   DateTime                 @db.Timestamptz(6)
  updatedAt   DateTime                 @db.Timestamptz(6)
  JobPostings JobPostings?             @relation(fields: [job_id], references: [id])
}

```

### Environment & setup

- OS: PopOS 20.04
- Database: PostgreSQL 12
- Node.js version: v14.17.3

### Prisma Version

```
prisma                : 2.30.0
@prisma/client        : 2.29.1
Current platform      : debian-openssl-1.1.x
Query Engine (Binary) : query-engine 60b19f4a1de4fe95741da371b4c44a92f4d1adcb (at node_modules/@prisma/engines/query-engine-debian-openssl-1.1.x)
Migration Engine      : migration-engine-cli 60b19f4a1de4fe95741da371b4c44a92f4d1adcb (at node_modules/@prisma/engines/migration-engine-debian-openssl-1.1.x)
Introspection Engine  : introspection-core 60b19f4a1de4fe95741da371b4c44a92f4d1adcb (at node_modules/@prisma/engines/introspection-engine-debian-openssl-1.1.x)
Format Binary         : prisma-fmt 60b19f4a1de4fe95741da371b4c44a92f4d1adcb (at node_modules/@prisma/engines/prisma-fmt-debian-openssl-1.1.x)
Default Engines Hash  : 60b19f4a1de4fe95741da371b4c44a92f4d1adcb
Studio                : 0.422.0

```

**Comment by janpio** [comment] 2021-11-08 17:39
Hey @u007, sorry for getting back to you so late. I think in current versions of Prisma this already works! 

See this reproduction:

```prisma
model Foo {
  id      Int                      @id @default(autoincrement())
  content Unsupported("tsvector")?
}
```

```ts
  const content = `another
  multiline
  text`;
  const id = 1;
  const res = await prisma.$queryRaw`UPDATE "Foo" SET content=to_tsvector('simple', ${content}) where id=${id};`
```

Resulting data screenshot from DBeaver:
![image](https://user-images.githubusercontent.com/183673/140791053-62e5fa28-fd32-43da-ae09-4271e96c301d.png)

```
λ npx prisma -v
Environment variables loaded from .env
prisma                  : 3.4.1
@prisma/client          : 3.4.1
Current platform        : windows
Query Engine (Node-API) : libquery-engine 57771c0558568c7d08bd34c7248af5244ae16bd9 (at node_modules\@prisma\engines\query_engine-windows.dll.node)
Migration Engine        : migration-engine-cli 57771c0558568c7d08bd34c7248af5244ae16bd9 (at node_modules\@prisma\engines\migration-engine-windows.exe)
Introspection Engine    : introspection-core 57771c0558568c7d08bd34c7248af5244ae16bd9 (at node_modules\@prisma\engines\introspection-engine-windows.exe)
Format Binary           : prisma-fmt 57771c0558568c7d08bd34c7248af5244ae16bd9 (at node_modules\@prisma\engines\prisma-fmt-windows.exe)
Default Engines Hash    : 57771c0558568c7d08bd34c7248af5244ae16bd9
Studio                  : 0.438.0
```

**Comment by Weakky** [comment] 2022-05-06 08:50
Hey @u007,

Query parameters on Postgres are numbered and prefixed with a dollar sign. eg: $1, $2, $3. This is the root cause of your syntax error.

What @janpio suggested is the correct fix though, since it will automatically replace each of your variables with the correct query parameter placeholders.

I'm closing this issue, feel free to ask more questions if needed or re-open it if that doesn't fix your issue.

Thanks 🙏

**Closed by Weakky** 2022-05-06 08:50 UTC
Labels: bug/0-unknown, kind/bug, topic: raw, team/client

**Comment by u007** [comment] 2022-05-06 09:37
ok, so instead of 
```
to_tsvector('simple', ?
```
change to 
```
to_tsvector('simple', $1
```
?
