### ISSUE TITLE
Incorrect InputJsonValue type

### ISSUE THREAD

**Issue by wanjas** [prisma/prisma#9247] opened 2021-09-14 09:32 UTC
### Bug description

Hello!

Right now `JsonValue` is not assignable to `InputJsonValue` and I think it is incorrect because I believe `InputJsonValue` is supposed to be a wider type.

Probably 
``` typescript
export type InputJsonValue = string | number | boolean | InputJsonObject | InputJsonArray
// should be 
export type InputJsonValue = string | number | boolean | InputJsonObject | InputJsonArray | null
```

### How to reproduce

Get any model that has a JSON field and try to use this field in for example in `update` and see 

```
Type 'JsonValue' is not assignable to type 'InputJsonValue'.
Type 'null' is not assignable to type 'InputJsonValue'.
```

### Expected behavior

`JsonValue` being assignable to `InputJsonValue` 

### Prisma information

```
model AnyModel {
 ...
 jsonField Json
 ...
}
```
```typescript
const rec = prisma.anyModel.findUnique({});
prisma.anyModel.update({  data: { jsonField: rec.jsonField  } });

```

### Environment & setup

Typescritp: 4.4.3 `{ "strict": true }`

### Prisma Version

```
prisma                  : 3.0.2
@prisma/client          : 3.0.2
Current platform        : debian-openssl-1.1.x
Query Engine (Node-API) : libquery-engine 2452cc6313d52b8b9a96999ac0e974d0aedf88db (at ../../node_modules/@prisma/engines/libquery_engine-debian-openssl-1.1.x.so.node)
Migration Engine        : migration-engine-cli 2452cc6313d52b8b9a96999ac0e974d0aedf88db (at ../../node_modules/@prisma/engines/migration-engine-debian-openssl-1.1.x)
Introspection Engine    : introspection-core 2452cc6313d52b8b9a96999ac0e974d0aedf88db (at ../../node_modules/@prisma/engines/introspection-engine-debian-openssl-1.1.x)
Format Binary           : prisma-fmt 2452cc6313d52b8b9a96999ac0e974d0aedf88db (at ../../node_modules/@prisma/engines/prisma-fmt-debian-openssl-1.1.x)
Default Engines Hash    : 2452cc6313d52b8b9a96999ac0e974d0aedf88db
Studio                  : 0.423.0
Preview Features        : orderByRelation

```

**Comment by pantharshit00** [comment] 2021-09-15 11:52
Thanks for reporting this, this does look like a bug in type generation.

**Comment by matthewmueller** [comment] 2021-09-21 15:24
Thanks for the issue. For now, the workaround is:

```ts
import { Prisma } from "@prisma/client"

const rec = prisma.anyModel.findUnique({});
if (rec.jsonField != null) {
  prisma.anyModel.update({  data: { jsonField: rec.jsonField  } })
} else {
  // decide on the type of 
  // https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-by-null-values
  prisma.anyModel.update({  data: { jsonField: Prisma.JsonNull  } })
}
```

**Comment by neongreen** [comment] 2021-12-10 16:11
```
   * `null` cannot be used as the value of a JSON field because its meaning
   * would be ambiguous. Use `Prisma.JsonNull` to store the JSON null value or
   * `Prisma.DbNull` to clear the JSON value and set the field to the database
   * NULL value instead.
```

It seems like this is actually intentional, but then it's hard to update a single field of a JsonObject and write the result back into the database — any field might be "null" and the workaround above doesn't work.

**Comment by neongreen** [comment] 2021-12-10 16:13
I think InputJsonObject should allow nulls as its keys even if InputJsonValue does not allow null.

**Comment by GeeWee** [comment] 2021-12-27 08:41
Just want to confirm this bug still exists in `3.7.0` and I just stumbled upon it today.

**Comment by bennyk9y** [comment] 2021-12-30 14:31
Any updates on that? I'm wondering how this issue is not prioritized and have more traction here, because we just updated from 2.3.0 to 3.7.0 and all our code is full with this problem (yes, we have many Json columns :( ).

**Comment by LeoDupont** [comment] 2021-12-30 17:26
> Thanks for the issue. For now, the workaround is:
> 
> ```ts
> import { Prisma } from "@prisma/client"
> 
> const rec = prisma.anyModel.findUnique({});
> if (rec.jsonField != null) {
>   prisma.anyModel.update({  data: { jsonField: rec.jsonField  } })
> } else {
>   // decide on the type of 
>   // https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-by-null-values
>   prisma.anyModel.update({  data: { jsonField: Prisma.JsonNull  } })
> }
> ```

Did not work for me, instead, I'm typing the value as a `Prisma.JsonObject`:
```ts
prisma.anyModel.update({
  data: {
    jsonField: rec.jsonField as Prisma.JsonObject
  }
})
```

Not sure if it works with every use case, though...

**Comment by joonatanvanhala** [comment] 2022-04-15 15:26
Any updates on this? I also was able to figure out workaround but just interested if a fix is coming

**Comment by yanavery** [comment] 2022-04-24 16:04
Bump, also running into this issue. Is a fix coming out soon?

**Comment by initplatform** [comment] 2022-04-29 14:57
work around using spread:

```typescript
        savedUser = await prisma().user.update({
            where: {
                id: user.id,
            },
            data: {
                ...user,
                postMetaData: user.postMetaData as Prisma.JsonObject,
            },
            include: userForAuthenticationInclude,
        });
```

This is quite annoying... if I don't do this I get -> 

      Types of property 'postMetaData' are incompatible.
        Type 'JsonValue' is not assignable to type 'string | number | boolean | InputJsonObject | InputJsonArray | undefined'.
          Type 'null' is not assignable to type 'string | number | boolean | InputJsonObject | InputJsonArray | undefined'


Full code for context:

```typescript
export const saveUser = async function (
    request: FastifyRequest,
    userForAuthentication: UserForAuthentication,
    verifyOrg = false
): Promise<UserForAuthentication> {
    if (verifyOrg) {
        verifyOrganizationInMemberships(request, userForAuthentication.memberships);
    }
    // Need to remove included relations before saving data object
    // eslint-disable-next-line
    const { auth, memberships, ...user } = userForAuthentication;
    let savedUser: UserForAuthentication | null;
    try {
        savedUser = await prisma().user.update({
            where: {
                id: user.id,
            },
            data: {
                ...user,
                postMetaData: user.postMetaData as Prisma.JsonObject,
            },
            include: userForAuthenticationInclude,
        });
    } catch (error) {
        throw request.generateError<SaveUserErrorCodes>(
            httpCodes.INTERNAL_SERVER_ERROR,
            'ERROR_SAVING_USER',
            error
        );
    }

    return savedUser;
};
```

and then in `user.model.ts`

```typescript
import { Prisma } from '@prisma/client';

import { MembershipWithOrgSelect } from '#public-types/membership';

export type AuthInclude = {
    authFacebook: true;
    authGithub: true;
    authGoogle: true;
    authLocal: true;
    authTwitter: true;
};
export type UserForAuthentication = Prisma.UserGetPayload<{
    include: {
        auth: {
            include: AuthInclude;
        };
        memberships: {
            select: MembershipWithOrgSelect;
        };
    };
}>;

export const userForAuthenticationInclude = {
    auth: {
        include: {
            authFacebook: true,
            authGithub: true,
            authGoogle: true,
            authLocal: true,
            authTwitter: true,
        },
    },
    memberships: {
        select: {
            id: true,
            organizationId: true,
            organization: {
                select: {
                    name: true,
                },
            },
            role: {
                select: {
                    name: true,
                },
            },
            groups: {
                select: {
                    id: true,
                    name: true,
                },
            },
        },
    },
};
```

**Comment by ToothpickFactory** [comment] 2022-09-04 01:18
Bump. Same issue here with "@prisma/client": "^4.3.1".

@initplatform, thanks for the workaround!

**Comment by janpio** [comment] 2022-09-15 21:27
Current reproduction:

```prisma
generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

model User {
  id        Int     @id @default(autoincrement())
  email     String
  name      String?
  jsonField Json
}
```

`script.ts`:
```ts
import { PrismaClient, Prisma } from '@prisma/client'

const prisma = new PrismaClient()

async function main() {
    await prisma.user.create({
        data: {
            name: "foo",
            email: "bar",
            jsonField: { meh: "kuh" }
        }
    })
    const rec = await prisma.user.findFirst();
    console.log({ rec })
    await prisma.user.update({ data: { jsonField: rec.jsonField }, where: { id: 1 }});
}

main()
    .then(async () => {
        await prisma.$disconnect()
    })
    .catch(async (e) => {
        console.error(e)
        await prisma.$disconnect()
        process.exit(1)
    })
```

Running this with `npx ts-node .\script.ts` indeed fails similar to described above:
```
PS C:\Users\Jan\Documents\throwaway\client-types\9247> npx ts-node .\script.ts
C:\Users\Jan\Documents\throwaway\client-types\9247\node_modules\ts-node\src\index.ts:859
    return new TSError(diagnosticText, diagnosticCodes, diagnostics);
           ^
TSError: ⨯ Unable to compile TypeScript:
script.ts:15:40 - error TS2322: Type 'JsonValue' is not assignable to type 'JsonNull | InputJsonValue | undefined'.
  Type 'null' is not assignable to type 'JsonNull | InputJsonValue | undefined'.

15     await prisma.user.update({ data: { jsonField: rec.jsonField }, where: { id: 1 }});
                                          ~~~~~~~~~

  node_modules/.prisma/client/index.d.ts:1841:5
    1841     jsonField?: JsonNullValueInput | InputJsonValue
             ~~~~~~~~~
    The expected type comes from property 'jsonField' which is declared here on type '(Without<UserUpdateInput, UserUncheckedUpdateInput> & UserUncheckedUpdateInput) | (Without<...> & UserUpdateInput)'
script.ts:15:51 - error TS2531: Object is possibly 'null'.

15     await prisma.user.update({ data: { jsonField: rec.jsonField }, where: { id: 1 }});
                                                     ~~~

    at createTSError (C:\Users\Jan\Documents\throwaway\client-types\9247\node_modules\ts-node\src\index.ts:859:12)
    at reportTSError (C:\Users\Jan\Documents\throwaway\client-types\9247\node_modules\ts-node\src\index.ts:863:19)
    at getOutput (C:\Users\Jan\Documents\throwaway\client-types\9247\node_modules\ts-node\src\index.ts:1077:36)
    at Object.compile (C:\Users\Jan\Documents\throwaway\client-types\9247\node_modules\ts-node\src\index.ts:1433:41)
    at Module.m._compile (C:\Users\Jan\Documents\throwaway\client-types\9247\node_modules\ts-node\src\index.ts:1617:30)
    at Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Object.require.extensions.<computed> [as .ts] (C:\Users\Jan\Documents\throwaway\client-types\9247\node_modules\ts-node\src\index.ts:1621:12)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:79:12) {
  diagnosticCodes: [ 2322, 2531 ]
}
```

And without types, via `npx ts-node --transpile-only .\script.ts`, it just works:
```
PS C:\Users\Jan\Documents\throwaway\client-types\9247> npx ts-node --transpile-only .\script.ts
{
  rec: { id: 3, email: 'bar', name: 'foo', jsonField: { meh: 'kuh' } }
}
```

You can achieve the same by replacing the `update` line with the following as a workaround:
```
    await prisma.user.update({ data: { jsonField: rec!.jsonField as Prisma.JsonObject }, where: { id: 1 }});
```

But that of course is not obvious and opens other problems.

**Comment by aqrln** [comment] 2022-09-16 12:50
This is not a bug, we explicitly designed the API this way — but it's now clear that it might not be optimal or convenient in all cases.

What would have been a bug, though, is if _nested_ `null` values inside a JSON value were prohibited:

```ts
  const data = await prisma.data.create({
    data: {
      json: {
        property: null,
      },
    },
  })
```

However, this is not the case — the snippet above works fine and doesn't produce any errors.

As for the top-level `null`s in JSON fields, they are prohibited due to being ambiguous. Instead, you have to explicitly specify `Prisma.DbNull` or `Prisma.JsonNull` to choose the kind of "null" you want, so Prisma knows what you mean.

We should make the [documentation about it](https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-by-null-values) more discoverable, because the title of the section refers to "Filtering by `null` values", while this also applies to `create`, `insert` and `upsert` — which is also explicitly stated in the documentation, but I understand it might be hard to find it.

Now, as for it not being possible to re-use the value that you got from the database — I agree that it is not very ergonomic. The problem here is that we lose information when retrieving the value from the DB: Prisma returns JavaScript `null` for both JSON `null` and DB `NULL`, while our insert operations are more strict. However, returning `Prisma.DbNull` and `Prisma.JsonNull` in results would come with even more ergonomics and DX implications. What we should do here and how we should change it in the future major versions is a subject for discussion, but for now it's what the API contract is.

The correct way to do this is like this:

```ts
const record = await prisma.data.findFirst()

await prisma.data.update({
  where: { id: 1 },
  data: {
    ...record,
    json: record.json !== null
      ? record.json
      : Prisma.JsonNull, // or `Prisma.DbNull` — depending on what you need
  },
})
```

**Do not** override the type system and cast it (i.e., `jsonField: record.jsonField as Prisma.JsonObject`) like some of the workarounds above suggest. The types are **correct** and represent the actual expectations — what those workarounds suggest will fail at run time if `jsonField` is `null`. If `null` is accepted by runtime validation — please let us know, that would be a bug!

Finally, none of this is relevant to MongoDB, and `null` must be accepted at the top level there. Please open an issue if that's not the case for you, and you encounter this issue with MongoDB.

I'll update the issue description and change the labels accordingly.

**Comment by aqrln** [comment] 2022-09-19 14:36
Reverting the changes to title and labels for posterity, I'll close this issue and open new ones instead.

**Closed by aqrln** 2022-09-19 14:36 UTC
Labels: bug/2-confirmed, kind/bug, topic: client types, tech/typescript, topic: json, team/client

**Comment by golergka** [comment] 2023-08-16 22:19
This behaviour makes duplicating documents in mongo very cumbersome. I want to do this:

```Typescript
prisma.content.create({
  data: {
    ...currentDocument
    // change some of it's fields
  }
})
```

But because of this difference in types I have to manually go through all the json fields. May be I should do this differently?

**Comment by shahinghasemi** [comment] 2025-08-09 12:55
Still exists, any workaround?

**Comment by jeevenmotion** [comment] 2025-09-05 04:19
Still running into this issue
