### ISSUE TITLE
MongoDB `findUnique()` or `findUniqueOrThrow()` leads to COLLSCAN if multiple queries happen at the same time

### ISSUE THREAD

**Issue by macrozone** [prisma/prisma#22812] opened 2024-01-25 13:26 UTC
### Bug description

in mongodb a simple findUnique or findUniqueOrThrow can lead to a colscan if multiple queries to the same collection happen at the same time:

```
prisma.user
    .findUnique({
      where: {
        id: "some-id"
      },
      select: {
        roles: true,
      },
    })

prisma.user
    .findUnique({
      where: {
        id: "some-id-2"
      },
 
    })
```

it creates this query:

```

[
      {
        "$match": {
          "$expr": {
            "$and": [
              {
                "$in": [
                  "$_id",
                  {
                    "$literal": [
                      "some-id",
                      "some-id-2"
                    ]
                  }
                ]
              },
              {
                "$ne": [
                  "$_id",
                  "$$REMOVE"
                ]
              }
            ]
          }
        }
      },
      {
        "$project": {
          "_id": 1,
          //...
        }
      }
    ],
      
  ```

which leads to a colscan because of this bug: https://github.com/prisma/prisma/issues/21453 which can take several seconds depending on the collection size and load

while this query which you would expect takes only some miliseconds:

```
{
    
          "$expr": {
            "$and": [
              {
               "_id": "some-id"
              },
              {
                "$ne": [
                  "$_id",
                  "$$REMOVE"
                ]
              }
            ]
          }
        
}
```
 
findUnique or findUniqueOrThrow do not have this problem

### How to reproduce

The error happens if there are multiple queries at the same time

**i assume this is because an attempted optimization in prisma:** prisma batches multiple queries on the same collection and this leads to a `id: {$in: [..]}` aggregation. This is slow in prisma https://github.com/prisma/prisma/issues/21453

This repo here shows the behavior: https://github.com/macrozone/prisma-mongodb-collscan-repro

### Expected behavior

findUnique and findUniqueOrThrow never do a colscan. They are expected to be fast and efficient

### Prisma information

see above

### Environment & setup

- OS: macos
- Database: mongodb atlas
- Node.js version: 18

### Prisma Version

```
prisma                  : 5.9.1
@prisma/client          : 5.9.1
Computed binaryTarget   : darwin-arm64
Operating System        : darwin
Architecture            : arm64
Node.js                 : v20.11.0
Query Engine (Node-API) : libquery-engine 23fdc5965b1e05fc54e5f26ed3de66776b93de64 (at node_modules/@prisma/engines/libquery_engine-darwin-arm64.dylib.node)
Schema Engine           : schema-engine-cli 23fdc5965b1e05fc54e5f26ed3de66776b93de64 (at node_modules/@prisma/engines/schema-engine-darwin-arm64)
Schema Wasm             : @prisma/prisma-schema-wasm 5.9.0-32.23fdc5965b1e05fc54e5f26ed3de66776b93de64
Default Engines Hash    : 23fdc5965b1e05fc54e5f26ed3de66776b93de64
Studio                  : 0.497.0
```

**Comment by macrozone** [comment] 2024-01-25 15:24
seems like the same problem as mentioned here https://github.com/prisma/prisma/issues/17142#issuecomment-1648791852

this is shocking to say the least. How can a simple findUnique ON THE ID lead to a collscan? And how can such a serious problem land in a release version of prisma?

**Comment by macrozone** [comment] 2024-01-25 16:19
i did further research and it seems removing select does not fix it.

it seems the bug is that prisma accidentially passes the same id multiple times:

````
db.users.aggregate([ { $match: { $expr: { $and: [ { $in: [ "$_id", { $literal: [ "some-id", "some-id", ], }, ], }, { $ne: [ "$_id", "$$REMOVE", ], }, ], }, }, }, { $project: { _id: 1, /* other fields...*/ }, }, ])
^[

```

**Comment by macrozone** [comment] 2024-01-25 16:48
another one for https://github.com/prisma/prisma/issues/14871 ...

**Comment by macrozone** [comment] 2024-02-05 16:38
its a very weird bug and now i also observed it with findUniqueOrThrow. It seems to be some concurrency problem and definitly a serious bug in the query engine. If there are multiple queries at the same time, they sometijmes receive multiple ids. I think this is an attempt of optimization so that multiple queries at the same time do not lead to multiple requests

however due to very poor optimizations of mongodb queries in prisma this leads to a full table scan (colscan)

**Comment by macrozone** [comment] 2024-02-06 08:20
@Druue i saw that you labeled the issue. I just wanted to inform you that i added more information and i have a possible explanation why this happens (prisma's batching attempt going wrong). I think its critical issue and I really hoped this gets fixed with priority

**Comment by janpio** [comment] 2024-02-19 20:06
Now that you understand the problem, can you please describe it again in clear words? 

Does this only happen when Prisma's batching kicks in? Or also in other cases? If yes, what is is a good reproduction scenario to see this ourselves? We would like to run one query and see it being fast, and then another set of queries where we can see it is slow.

If it is indeed the batching, we can possibly just disable it for these cases where this leads to problems.

**Comment by macrozone** [comment] 2024-02-20 09:23
> Now that you understand the problem, can you please describe it again in clear words?
> 
> Does this only happen when Prisma's batching kicks in? Or also in other cases? If yes, what is is a good reproduction scenario to see this ourselves? We would like to run one query and see it being fast, and then another set of queries where we can see it is slow.
> 
> If it is indeed the batching, we can possibly just disable it for these cases where this leads to problems.

I am pretty sure its batching, so it should be easy to reproduce by just calling multiple findUnique on the same collection without awaiting them

- set 

```
export const prisma = new PrismaClient({
  log: ["query"],
});
```
- then: 
- 
```
await Promise.all(["id1", "id2", "id3"].map(id => prisma.MyModel.findUnique({where: {id}})))`
```

you then see that it creates quite complicated queries using `$in` in a way that cannot use the index ($in can use the index, but not how prisma generates those queries)

to see that those queries are indeed lead to a colscan, you can force mongodb to not allow colscan https://www.mongodb.com/docs/manual/reference/parameters/#param.notablescan

then, compare that with using `findFirst`. Those queries do not use $in, since they can't be batched the same way.

Instead of disabling batching, it would actually be better to fix the underlying issue which is documented here https://github.com/prisma/prisma/issues/19955

i understand that mongodb queries are harder to optimize when multiple collections need to be accessed at the same time.

But in cases where an indexed field is in the selector, they should be never a colscan. Colscan can be devasting not only for performance but also for costs.

**Comment by macrozone** [comment] 2024-04-03 11:47
@janpio is it possible to disable batching? This bug is very serious and we need to take immediate action

**Comment by SevInf** [comment] 2024-04-03 13:22
@macrozone if you want to opt out of batching, you can use `findFirst(OrThrow)` instead of `findUnique(OrThrow)`.

If you are using composite unique you will need to flatten `where`:

```ts
prisma.model.findUnique({
  where: {
     name_email: {
         name,
         email
     }
  }
})
```

becomes:

```ts
prisma.model.findUnique({
  where: {
      name,
      email
  }
})
```

For plain unique, just replacing `findUnique` with `findFirst` is enough.

**Comment by macrozone** [comment] 2024-04-03 13:26
> @macrozone if you want to opt out of batching, you can use `findFirst(OrThrow)` instead of `findUnique(OrThrow)`.
> 
> If you are using composite unique you will need to flatten `where`:
> 
> ```ts
> prisma.model.findUnique({
>   where: {
>      name_email: {
>          name,
>          email
>      }
>   }
> })
> ```
> 
> becomes:
> 
> ```ts
> prisma.model.findUnique({
>   where: {
>       name,
>       email
>   }
> })
> ```
> 
> For plain unique, just replacing `findUnique` with `findFirst` is enough.

yeah thank you, I had the same observation.

However i would like to know whether there is a way to disable it completly, because It's hard to explain to devs why they should not use findUnique when using mongodb. Also when this bug is fixed, I would like to revert it back. So disabling it on the client level would be nice.

**Comment by SevInf** [comment] 2024-04-03 13:48
@macrozone you could do [a client extension](https://www.prisma.io/docs/orm/prisma-client/client-extensions/query) that would convert `findUnique` to `findFirst` automatically.

**Comment by macrozone** [comment] 2024-04-03 14:04
> @macrozone you could do [a client extension](https://www.prisma.io/docs/orm/prisma-client/client-extensions/query) that would convert `findUnique` to `findFirst` automatically.

yeah, i also thought about that, or creating a custom eslint rule ;-)

**Comment by macrozone** [comment] 2024-04-03 14:05
but i think prisma should just just disable the batching for mongodb until https://github.com/prisma/prisma/issues/19955 is fixed

**Comment by janpio** [comment] 2024-04-04 13:00
@macrozone If the queries are also slow when not being batched, please look for existing issues that refer to that case or open a new one with the full information. Thank you.

**Comment by macrozone** [comment] 2024-04-04 13:11
> @macrozone If the queries are also slow when not being batched, please look for existing issues that refer to that case or open a new one with the full information. Thank you.

Thank you @janpio 

I removed all `findUnique` calls and replaced them with `findFirst`, but I still see slow query logs like this. The codebase has no findUnique anymore. Those are guaranteed `findFirst` (or `findFirstOrThrow`) calls. However I can't reproduce it locally, there i don't see those queries (by using prisma's log feature). 

If prisma would at least create $eq expressions instead of $in if there is only one _id, it would already mitigate this problem, since mongodb would then use the index.

I think a developer of the query engine needs to look at this, since its probably a rather easy fix. Also they probably know under which conditions a `$in` is used (batching or some attempted optimization).

**Comment by janpio** [comment] 2024-04-04 14:03
I remember our discussions.

I am serious though, a quick issue from you with a plain and obvious reproduction would go a long way. You clearly have a reproduction case now, and as a new issue we would also try to reproduce and then potentially prioritize that.

**Comment by macrozone** [comment] 2024-04-05 18:07
> I am serious though, a quick issue from you with a plain and obvious reproduction would go a long way. You clearly have a reproduction case now, and as a new issue we would also try to reproduce and then potentially prioritize that.


The initial description is still correct. findUnique(OrThrow) lead to a colscan due to wrongly implemented batching.  I hope its clear how problematic this issue is. (and many of the other reported and well documented mongodb performance problems.

I can offer to create a repo with some test cases though, if the prisma team does not have a setup to test mongodb.

**Comment by cassiohub** [comment] 2024-04-08 09:49
We are facing similar issues with these non-optimized queries. Some of our collection grew a lot in the recent weeks and now these `COLLSCAN` became a serious issue. A simple `findUnique` is taking +30 seconds to resolve on a 2.5mi records collection.

By enabling the debug on Prisma queries, we can tell all of it is due to the misusage of `$expr` + `$in`. Seems like any Prisma query will lazily just wrap your query with the `$expr` command instead of building a more specific query.

As a workaround, we manage to replace some of our queries with a Prisma `OR` operator. 

So instead of something like 
```javascript
prisma.users.findMany({ where: { id: { in: sortedMemberIds } })
```
We replaced with 
```javascript
prisma.users.findMany({ where: { OR: sortedMemberIds.map((id) => ({ id })) }})
```

It's a silly workaround and doesn't work for all the cases, but it helps for now. The problem is even worse in our project since we expose a GraphQL endpoint, and rely on Prisma/Nexus/PalJS generated resolvers. All of those will generate the offender queries. To mitigate, we introduced custom resolvers that will do the workaround query described above. It's a huge drawback to the project, as we need to handle each individual resolver manually now. 

From quickly scanning Prisma engine codebase, I think [calls](https://github.com/prisma/prisma-engines/blob/efd2449663b3d73d637ea1fd226bafbcf45b3102/query-engine/connectors/mongodb-query-connector/src/join.rs#L149) [like](https://github.com/prisma/prisma-engines/blob/efd2449663b3d73d637ea1fd226bafbcf45b3102/query-engine/connectors/mongodb-query-connector/src/root_queries/write.rs#L297) [these](https://github.com/prisma/prisma-engines/blob/efd2449663b3d73d637ea1fd226bafbcf45b3102/query-engine/connectors/mongodb-query-connector/src/query_builder/read_query_builder.rs#L197) [here](https://github.com/prisma/prisma-engines/blob/efd2449663b3d73d637ea1fd226bafbcf45b3102/query-engine/connectors/mongodb-query-connector/src/join.rs#L102-L116) are the culprit (I'm nowhere near to understand Rust code 😅). Instead of just passing the query to the `$expr` command, it should be building the `mongodb` specific query depending on the requested filters. Not a trivial task, I guess, but it's what I'd expect from a data access library.

Overall, we had a bunch of drawback with the Prisma + MongoDB integration. We manage to work around some of them, but it's becoming unsustainable. It was first introduced because we wanted to better integrate with our new GraphQL services and not having to write resolvers manually for everything. As it stands now, we are back on writing new code with mongoose.

**Comment by janpio** [comment] 2024-04-08 12:35
> findUnique(OrThrow) lead to a colscan due to wrongly implemented batching.

I don't understand. I thought you replaced all `findUnique()` queries (which are batched) with other queries that are not batched, and you are still seing the problem - which indicates that batching is not at fault. What am I missing?

> I can offer to create a repo with some test cases though, maybe i can do that over the weekend.

That would be very welcome, thank you.

**Comment by macrozone** [comment] 2024-04-08 12:48
> I don't understand. I thought you replaced all findUnique() queries (which are batched) with other queries that are not batched, and you are still seing the problem - which indicates that batching is not at fault. What am I missing?

I still see colscans on production for unique ids without having findUnique. (only findFirst and firndFirstAndThrow).

But i could not reproduce that locally yet, while I could reproduce the findUnique cases. 

So I would argue that we should keep the issue here about findUnique(andThrow), were there is strong evidence and a guess why this happens (batching).
My hope is that this bug here is fixed in a short time, since it is rather obvious and will affect all users of prisma and mongodb.

In the meantime I check why I still see collscans for "findFirst" and if i find other evidence and will open a new issue for that.

**Comment by macrozone** [comment] 2024-04-08 13:17
I checked the logs again from the production, made sure that it does not run any old version of the code where findUnique or findUniqueAndThrow is used and still see quite a lot of COLLSCANS from $in-queries on the primary key. I created therefore a separate issue https://github.com/prisma/prisma/issues/23775

**Comment by macrozone** [comment] 2024-04-08 13:46
@janpio i created a repo that show the bug described here. it also shows that findFirst should not have this issue

https://github.com/macrozone/prisma-mongodb-collscan-repro

Why i still have https://github.com/prisma/prisma/issues/23775 is up for investigation

**Comment by janpio** [comment] 2024-05-15 12:48
Our release 5.14.0 significantly improved the performance of certain queries when using MongoDB, specifically ones with `include` and `in` should now not cause a collection scan anymore and use an index instead to find the correct documents. I assume this was also the underlying problem that was reported in this issue - so I am going to close this for now.

If you still encounter any performance problems with Prisma and MongoDB, please open a new GitHub bug issue. Thanks!

**Closed by janpio** 2024-05-15 12:48 UTC
Labels: bug/0-unknown, kind/bug, topic: performance, team/client, topic: mongodb, topic: performance/queries, topic: findUnique(), topic: batching
