### ISSUE TITLE
Using Prisma with Rollup or Webpack in Node causes a runtime error

### ISSUE THREAD

**Issue by f0rr0** [prisma/prisma#5250] opened 2021-01-23 11:33 UTC
## Bug description

I have traced this to `node-fetch` v 2.x which is a dependency of the fetch engine. 

https://github.com/node-fetch/node-fetch/blob/b5e2e41b2b50bf2997720d6125accaf0dd68c0ab/src/body.js#L14

https://github.com/node-fetch/node-fetch/issues/412

`encoding` seems to be a peer dependency for `node-fetch`. A bundler like webpack or rollup will include the require and crash at runtime since `encoding` is not installed. 

Either prisma should upgrade the `node-fetch` dependency to v3 which does away with this or include a cautionary note in the README like `node-fetch` did : https://github.com/node-fetch/node-fetch/blob/2.x/README.md#bodytextconverted

Other repos depending on `node-fetch` 2.x also faced a similar issue https://github.com/netlify/create-react-app-lambda/issues/24

**Comment by pantharshit00** [comment] 2021-01-27 14:40
Can you share a simple reproduction? Then we can confirm this and maybe replace node-fetch with something else as it is not a very core dependency.

We have some e2e tests for bundlers which havent failed so maybe you can look them as an example: https://github.com/prisma/e2e-tests/tree/dev/bundlers

**Comment by f0rr0** [comment] 2021-01-27 14:47
I’ll create a reproduction. The e2e tests are not failing because this test is basically ignoring everything under node_modules when bundling through webpack-node-externals plugin. I can’t do that for my use case. I need to provide a single archive of my app to lambda including all dependencies so I need to bundle them.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by f0rr0** [comment] 2021-01-27 15:38
Here is the reproduction
https://github.com/prisma/e2e-tests/pull/1314

**Comment by pantharshit00** [comment] 2021-02-03 12:25
THanks for that. Marking this as confirmed. We can try eliminating this dep.

**Comment by matthewmueller** [comment] 2021-06-02 13:41
If you try bundling node_modules all together in one output JS file, you get a runtime error trying to run that output JS file. Am I understanding this correctly? [Context](https://github.com/prisma/e2e-tests/pull/1314/files)

Also, what is the runtime error that you're seeing @f0rr0?

**Comment by f0rr0** [comment] 2021-06-02 14:43
Use case is generating a single asset that I can distribute to serverless environments. without the need to manage things like lambda layers. Also the generated asset is run through a minifier to reduce size and gain marginal improvement in startup perf.

The error is basically that a dependency of prisma has an implicit dependency on a module called `encoding`. This dependency is not installed when installing prisma. Neither is it mentioned in the prisma readme. Under normal circumstances the code path never reaches the `require` for that dependency but when bundled it does causing an error. 

Ideally considering the reach and popularity of this project, it will be better to not have such implicit dependencies or make assumptions about the modules available at runtime. I suggest to either add a note in the docs or better yet replace this dependency with a more sensible choice.

**Comment by dvins** [comment] 2021-06-02 20:44
Closely related to this is the ESM support. See https://github.com/prisma/prisma/issues/5030 and https://github.com/prisma/prisma/pull/4920.

**Comment by f0rr0** [comment] 2021-06-04 02:27
Tbh I don't fully understand why/how the crash happens and it's been a while since I encountered it. I was able to resolve it by making modifications to the bundler config.

A guess is that perhaps the bundler hoists the require calls.

**Comment by f0rr0** [comment] 2021-06-04 02:30
This is the config that worked for me: https://github.com/prisma/prisma/issues/2303#issuecomment-768358529

**Comment by janpio** [comment] 2021-06-04 19:30
Why isn't renovate suggesting an update to `node-fetch@3` here anyway @Jolg42?

**Comment by Jolg42** [comment] 2021-06-07 08:06
Because v3 in not on latest but on next.
https://www.npmjs.com/package/node-fetch
<img width="970" alt="Screen Shot 2021-06-07 at 10 02 09" src="https://user-images.githubusercontent.com/1328733/120980985-78673f00-c777-11eb-9ba5-d1ec38ecd84a.png">

I re-configured Renovate, it should open a PR soon https://github.com/prisma/prisma/commit/3c009903614eb6143e94313bd7fc8af08c57f167

**Comment by janpio** [comment] 2021-06-07 20:51
Ugh, so the README at https://github.com/node-fetch/node-fetch lies to us :/

**Comment by Jolg42** [comment] 2021-06-08 07:22
Indeed... README is incorrect `Current stable release (3.x)` should be 2.x here
I found the v3 roadmap issue herehttps://github.com/node-fetch/node-fetch/issues/668

**Comment by mbalc** [comment] 2021-09-08 12:37
what can I do to circumvent this issue?

**Comment by millsp** [comment] 2021-09-08 19:03
You can mark this dependency as [external](https://webpack.js.org/configuration/externals/) for now.

**Comment by matthewmueller** [comment] 2022-01-11 17:32
It seems like the current workaround is to [mark the dependency as external](https://github.com/prisma/prisma/issues/5250#issuecomment-915494165). 

The longer-term fix is to [upgrade to node-fetch 3.x](https://github.com/prisma/prisma/pull/11074), which is currently blocked by https://github.com/prisma/prisma/issues/7618.

**Comment by millsp** [comment] 2022-06-08 21:56
Closing this as this is not an issue anymore
https://github.com/prisma/ecosystem-tests/pull/2857

**Closed by millsp** 2022-06-08 21:56 UTC
Labels: bug/2-confirmed, kind/bug, tech/typescript, topic: serverless, topic: dependencies, status/needs-action, team/client, topic: webpack
