### ISSUE TITLE
Many to Many self-relation seems to generate the wrong `*CreateWithout*Input`

### ISSUE THREAD

**Issue by shmuelsochet** [prisma/prisma#10901] opened 2021-12-29 20:59 UTC
### Bug description

I think the gist of the issue is that the `following` relationship on the `Follows` table generates a `FollowsCreateWithoutFollowingInput` and I don't believe that makes sense. It should create a `FollowsCreateWithoutFollowerInput` since when a `Person` has people they're `following` then they are the `follower` and we just don't know who the `Person` that they're `following` is, so the input should contain the value for the `Person` they're `following`

### How to reproduce

1. Add these two models to schema.prisma

```prisma
model Person {
  id         Int       @id @default(autoincrement())
  name       String?
  followers  Follows[] @relation("follower")
  following  Follows[] @relation("following")
}

model Follows {
  follower    Person @relation("follower", fields: [followerId], references: [id])
  followerId  Int
  following   Person @relation("following", fields: [followingId], references: [id])
  followingId Int

  @@id([followerId, followingId])
}
```

2. Run the migration `npx prisma migrate dev`
3. Manually add a `Person` to the db to use as the `Person` you will be  `following`
4. Run the below code to get the error

```typescript
const person = await prisma.person.create({
    data: {
      following: {
        create: [
          { following: { connect: { id: 1 } } }
        ]
      }
    }
  });
```

You should see the error.

```
/usr/src/app/node_modules/@prisma/client/runtime/index.js:34755
     const error2 = new PrismaClientValidationError(renderErrorStr(validationCallsite));
                    ^
 
 PrismaClientValidationError: Unknown arg `following` in data.following.create.0.following for type FollowsCreateWithoutFollowingInput. Did you mean `follower`?
 Argument follower for data.following.create.0.follower is missing.
 
     at Object.validate (/usr/src/app/node_modules/@prisma/client/runtime/index.js:34755:20)
     at PrismaClient._executeRequest (/usr/src/app/node_modules/@prisma/client/runtime/index.js:39749:17)
     at consumer (/usr/src/app/node_modules/@prisma/client/runtime/index.js:39690:23)
     at /usr/src/app/node_modules/@prisma/client/runtime/index.js:39694:49
     at AsyncResource.runInAsyncScope (node:async_hooks:199:9)
     at PrismaClient._request (/usr/src/app/node_modules/@prisma/client/runtime/index.js:39694:27)
     at request (/usr/src/app/node_modules/@prisma/client/runtime/index.js:39799:77)
     at _callback (/usr/src/app/node_modules/@prisma/client/runtime/index.js:40007:14)
     at PrismaPromise.then (/usr/src/app/node_modules/@prisma/client/runtime/index.js:40014:23) {
     clientVersion: '3.7.0'
 }
```

### Expected behavior

Since I'm trying to create a `Person` with people they're `following`, I expect to input (`connect`) a `Person` that they're `following` not who the `follower` is. The `Person` I'm trying to create is the `follower` of this `following[]` relationship.

When prisma generates types from the schema, for the relationship `following[]` it should create `FollowsCreateWithoutFollowerInput` instead of `FollowsCreateWithoutFollowingInput`.

More details about this issue can be found here:

1. https://stackoverflow.com/questions/70520589/prisma-many-to-many-self-relation-error-due-to-relation-and-generated-type-inpu
2. https://prisma.slack.com/archives/CA491RJH0/p1640787469302900

### Prisma information

```prisma
generator client {
  provider      = "prisma-client-js"
  binaryTargets = ["native", "linux-musl"]
}

datasource db {
  provider = "sqlserver"
  url      = env("DATABASE_URL")
}

model Person {
  id         Int       @id @default(autoincrement())
  name       String?
  followers  Follows[] @relation("follower")
  following  Follows[] @relation("following")
}

model Follows {
  follower    Person @relation("follower", fields: [followerId], references: [id])
  followerId  Int
  following   Person @relation("following", fields: [followingId], references: [id])
  followingId Int

  @@id([followerId, followingId])
}
```

```typescript
const person = await prisma.person.create({
    data: {
      following: {
        create: [
          { following: { connect: { id: 1 } } }
        ]
      }
    }
  });
```

### Environment & setup

- OS: `Docker node:16-alpine`
- Database: `SQLServer`
- Node.js version: `v16.13.1`

### Prisma Version

```
prisma                  : 3.7.0
@prisma/client          : 3.7.0
Current platform        : linux-musl
Query Engine (Node-API) : libquery-engine 8746e055198f517658c08a0c426c7eec87f5a85f (at node_modules/@prisma/engines/libquery_engine-linux-musl.so.node)
Migration Engine        : migration-engine-cli 8746e055198f517658c08a0c426c7eec87f5a85f (at node_modules/@prisma/engines/migration-engine-linux-musl)
Introspection Engine    : introspection-core 8746e055198f517658c08a0c426c7eec87f5a85f (at node_modules/@prisma/engines/introspection-engine-linux-musl)
Format Binary           : prisma-fmt 8746e055198f517658c08a0c426c7eec87f5a85f (at node_modules/@prisma/engines/prisma-fmt-linux-musl)
Default Engines Hash    : 8746e055198f517658c08a0c426c7eec87f5a85f
Studio                  : 0.445.0
```

**Comment by p-kuen** [comment] 2022-01-11 18:35
I think this error also exists when querying many-to-many relations. It also throws the "Unknown args" error even if the type check seems okay.

**Comment by janpio** [comment] 2022-01-11 19:55
@p-kuen Reproduction welcome as well of course 👍

**Comment by renken** [comment] 2022-01-21 02:46
As far as I can tell, the docs are wrong here. To correctly map a many-to-many self-relation `followers` on `User` needs to map to `following` in the `Follows` table, and `following` on `User` to `follower` in `Follows`.

If you do it as the docs suggest, your underlying data will be incorrect as well. You'll notice the ids in your relation table will be flipped.

**Comment by janpio** [comment] 2022-01-22 12:38
Which docs are you referring to exactly @renken? We have a few relation examples in there.

**Comment by renken** [comment] 2022-01-22 20:53
See the explicit many-to-many example [here](https://www.prisma.io/docs/concepts/components/prisma-schema/relations/self-relations#many-to-many-self-relations).

**Comment by claudiowilson** [comment] 2022-07-19 22:40
I can confirm this tripped me up I have a many to many self relation and I had to swap it out vs what was written in the docs

> As far as I can tell, the docs are wrong here. To correctly map a many-to-many self-relation `followers` on `User` needs to map to `following` in the `Follows` table, and `following` on `User` to `follower` in `Follows`.
> 
> If you do it as the docs suggest, your underlying data will be incorrect as well. You'll notice the ids in your relation table will be flipped.

Confirming this tripped me up, I also have a many to many self relation which I had to fix by flipping the @relation

**Comment by janpio** [comment] 2022-07-30 21:05
What section of the docs _exactly_ are we taking about here?
There was a change recently that potentially could be related: https://github.com/prisma/docs/pull/3166/files

**Comment by eviefp** [comment] 2022-11-29 14:10
I think this is working as intended. Let me start by showcasing the code that does work on the example:

```typescript
  const first = await prisma.person.create({
    data: {
      following: {
        create: [
          { follower: { connect: { id: 1 } } }
        ]
      }
    }
  })

  const second = await prisma.person.create({
    data: {
      followers: {
        create: [
          { following: { connect: { id: 1 } } }
        ]
      }
    }
  })
```

Note the difference here:
- if we're defining a new person by its `following`, we need to define who it is that is the `follower`
- if we're defining a new person by its `followers`, we need to define those who are doing the `following`

This is because we need to construct a `Follow` entry/row, and the "current" person can be either a `follower`, or a `following`. Depending on which side of the relation we start, we need to fill in the other.

Hopefully that's clear!

**Closed** 2022-11-29 16:13 UTC
Labels: bug/1-unconfirmed, kind/bug, topic: client types, topic: self relations, team/client, topic: m:n

**Comment by 0x1nexus** [comment] 2023-03-07 03:32
how about if the person is already existing and via the update?
