### ISSUE TITLE
Update n rows in `updateMany()`

### ISSUE THREAD

**Issue by reidbuzby** [prisma/prisma#8957] opened 2021-08-26 21:53 UTC
## Problem

I would like to be able to update `n` number of rows in one `updateMany` transaction. This would be similar to the `take` field that you can add to the `findMany` query. So the query would update the first `take` number of rows. Something like:

```javascript
prisma.table_name.updateMany({
  where: { field: true },
  data: { newField: 'asdf' },
  take: 100
})
```

Where this query would update the first 100 rows where `field === true`. 

The way I am doing this at the moment is by first calling `findMany` with `take` and then updating the results:

```javascript
const results = await prisma.table_name.findMany({
  where: { field: true },
  take: 100
});

await this.table_name.updateMany({
  where: { id: { in: results.map(r => r.id) } },
  data: { newField: 'asdf' }
});
```

I want to be able to do this in one transaction to prevent race conditions if there is another call to find and update the same rows.
## Suggested solution

```javascript
prisma.table_name.updateMany({
  where: { field: true },
  data: { newField: 'asdf' },
  take: 100
})
```

This query would update the first 100 rows where `field === true`. 

## Alternatives

I have tried using the interactive transactions (in preview) feature to be able to do this in one transaction, but I have run into issues with the new feature when increasing load. It seems to be too unstable at the moment to reliably use in production.

**Comment by janpio** [comment] 2024-02-01 15:05
Closing this as a duplicate of https://github.com/prisma/prisma/issues/6957 - if you are interested, please subscribe to that issue and/or leave a 👍 reaction on the original message. Thanks.

**Closed by janpio** 2024-02-01 15:05 UTC
Labels: kind/feature, team/client, topic: client api, topic: updateMany(), topic: take
