### ISSUE TITLE
Invalid `PrismaClient.user.findUnique()` invocation with 5.6.0

### ISSUE THREAD

**Issue by dyangcoding** [prisma/prisma#22271] opened 2023-12-05 18:42 UTC
### Bug description

Trying to find the unique user by email which is an unique field defined in the prisma schema file.
Upgrading Prisma from 4.6.1 to 5.6.0 results in the mentioned error.
It works fine when downgrading to the previous version (4.6.1).

### How to reproduce

Tried following methods that result all in the mentioned error:

- findUnque
- findUniqueOrThrow
- findFirst

### Expected behavior

It should return an unique object with prisma 5.6.0 as the previous version.

### Prisma information

```prisma
// Add your schema.prisma
```

```ts
Invalid `PrismaClient.userInfo.findFirst()` invocation in
/app/src/controllers/AuthController.ts:150:42

→ 150   user = await PrismaClient.userInfo.findUnique(
data did not match any variant of untagged enum GraphQlBody
```

### Environment & setup

- OS: macOS
- Database: PostgreSQL
- Node.js version: v18.17.0

### Prisma Version

```
5.6.0
```

**Comment by SevInf** [comment] 2024-01-15 10:05
Hey @dyangcoding ,

Did you get a chance to have a look at @aqrln  comment? It'd be helpful for us to move your issue forward.

Without further information, we'll have to close this issue. Thank you 🙏

**Comment by aqrln** [comment] 2024-02-02 20:09
Hi @dyangcoding,

Since we couldn't reach out to you to get more information necessary for reproduction and investigation, we unfortunately have to close this issue at this time. Please open a new issue with more details if you are still facing this problem.

**Closed by aqrln** 2024-02-02 20:09 UTC
Labels: bug/0-unknown, kind/bug, team/client, topic: engine
