### ISSUE TITLE
Remove obsolete `experimentalFeatures` generator property

### ISSUE THREAD

**Issue by Druue** [prisma/prisma#19540] opened 2023-05-31 13:39 UTC
PRs
- https://github.com/prisma/prisma/pull/19544
- https://github.com/prisma/prisma-engines/pull/4010

**Comment by Jolg42** [comment] 2023-06-09 12:01
Closing as duplicate of https://github.com/prisma/prisma/issues/16294

**Closed by Jolg42** 2023-06-09 12:01 UTC
Labels: tech/engines, kind/tech, team/schema, topic: breaking change, topic: prisma5
