### ISSUE TITLE
Prisma client does not clean up itself after test

### ISSUE THREAD

**Issue by ogroppo** [prisma/prisma#13575] opened 2022-05-31 01:04 UTC
### Bug description

It has been noticed that using prisma client in integration tests (jest), leads to memory usage building up and never being released (--logHeapUsage)

the $disconnect method seems not to have the desired effect, still the error is 
```
 FAIL  tests/memory.test.ts
  ● Test suite failed to run

    EXPERIMENTAL FEATURE!
    Your test suite is leaking memory. Please ensure all references are cleaned.

    There is a number of things that can leak memory:
      - Async operations that have not finished (e.g. fs.readFile).
      - Timers not properly mocked (e.g. setInterval, setTimeout).
      - Keeping references to the global scope.

      at onResult (node_modules/.pnpm/@jest+core@28.1.0/node_modules/@jest/core/build/TestScheduler.js:188:18)
      at node_modules/.pnpm/@jest+core@28.1.0/node_modules/@jest/core/build/TestScheduler.js:300:17
      at node_modules/.pnpm/emittery@0.10.2/node_modules/emittery/index.js:311:13
          at Array.map (<anonymous>)
      at Emittery.emit (node_modules/.pnpm/emittery@0.10.2/node_modules/emittery/index.js:309:23)
```

Similar issues 
https://github.com/prisma/prisma/issues/12153
https://github.com/prisma/prisma/issues/8989

### How to reproduce

minimal repo:
https://github.com/codeledge/prisma-memory-leak-repro

Just `pnpm i && pnpm t` it runs a simple test with jest and the `--detectLeaks` flag

### Expected behavior

the client should be destroyed and leave no traces after test process finishes

### Prisma information

https://github.com/codeledge/prisma-memory-leak-repro

### Environment & setup

- OS: OSX
- Database: Postgres
- Node.js version: 16

### Prisma Version

prisma                  : 3.14.0
@prisma/client          : 3.14.0
Current platform        : darwin

**Comment by garrensmith** [comment] 2022-06-30 12:59
Thanks for reporting this. We are aware of the issue. I'm closing this issue. You can follow along https://github.com/prisma/prisma/issues/12339

**Comment by janpio** [comment] 2023-09-02 16:53
Reopening as it has its own reproduction that hopefully will help us understand the issue properly.

**Comment by Jolg42** [comment] 2023-11-02 14:13
I tried https://github.com/codeledge/prisma-memory-leak-repro as is on Node.js v20.8.1
And I could reproduce the same output.
But, I did not succeed in having it passing without Prisma

I replaced the contents of `memory.test.ts` by the following
```
describe("schema", () => {
  test("something", async () => {
  });
});
```

And then ran `pnpm t` which told me there was a memory leak
```
> jest --detectLeaks

ts-jest[config] (WARN) message TS151001: If you have issues related to imports, you should consider setting `esModuleInterop` to `true` in your TypeScript configuration file (usually `tsconfig.json`). See https://blogs.msdn.microsoft.com/typescript/2018/01/31/announcing-typescript-2-7/#easier-ecmascript-module-interoperability for more information.
 FAIL  tests/memory.test.ts
  ● Test suite failed to run

    EXPERIMENTAL FEATURE!
    Your test suite is leaking memory. Please ensure all references are cleaned.

    There is a number of things that can leak memory:
      - Async operations that have not finished (e.g. fs.readFile).
      - Timers not properly mocked (e.g. setInterval, setTimeout).
      - Keeping references to the global scope.

      at onResult (node_modules/.pnpm/@jest+core@28.1.0/node_modules/@jest/core/build/TestScheduler.js:188:18)
      at node_modules/.pnpm/@jest+core@28.1.0/node_modules/@jest/core/build/TestScheduler.js:300:17
      at node_modules/.pnpm/emittery@0.10.2/node_modules/emittery/index.js:311:13
          at Array.map (<anonymous>)
      at Emittery.emit (node_modules/.pnpm/emittery@0.10.2/node_modules/emittery/index.js:309:23)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        2.365 s
Ran all test suites.
Segmentation fault (core dumped)
 ELIFECYCLE  Test failed. See above for more details.
```

I tried upgrading the dependencies with ``
But I got the same result.

I now switched to Node.js `v18.18.2` and finally got a passing test when empty
```
> jest --detectLeaks

ts-jest[config] (WARN) message TS151001: If you have issues related to imports, you should consider setting `esModuleInterop` to `true` in your TypeScript configuration file (usually `tsconfig.json`). See https://blogs.msdn.microsoft.com/typescript/2018/01/31/announcing-typescript-2-7/#easier-ecmascript-module-interoperability for more information.
 PASS  tests/memory.test.ts
  schema
    ✓ something (1 ms)

Test Suites: 1 passed, 1 total
Tests:       1 passed, 1 total
Snapshots:   0 total
Time:        1.749 s, estimated 2 s
Ran all test suites.
```

and failing with the following, more minimalist test:
```ts
import { PrismaClient } from "@prisma/client";

describe("schema", () => {
  afterAll(async () => {
    const prismaClient = new PrismaClient();
  });

  test("empty test", async () => {
  });
});
```
with
```
> jest --detectLeaks

ts-jest[config] (WARN) message TS151001: If you have issues related to imports, you should consider setting `esModuleInterop` to `true` in your TypeScript configuration file (usually `tsconfig.json`). See https://blogs.msdn.microsoft.com/typescript/2018/01/31/announcing-typescript-2-7/#easier-ecmascript-module-interoperability for more information.
 FAIL  tests/memory.test.ts
  ● Test suite failed to run

    EXPERIMENTAL FEATURE!
    Your test suite is leaking memory. Please ensure all references are cleaned.

    There is a number of things that can leak memory:
      - Async operations that have not finished (e.g. fs.readFile).
      - Timers not properly mocked (e.g. setInterval, setTimeout).
      - Keeping references to the global scope.

      at onResult (node_modules/.pnpm/@jest+core@29.7.0/node_modules/@jest/core/build/TestScheduler.js:150:18)
      at node_modules/.pnpm/@jest+core@29.7.0/node_modules/@jest/core/build/TestScheduler.js:254:19
      at node_modules/.pnpm/emittery@0.13.1/node_modules/emittery/index.js:363:13
          at Array.map (<anonymous>)
      at Emittery.emit (node_modules/.pnpm/emittery@0.13.1/node_modules/emittery/index.js:361:23)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        1.665 s
Ran all test suites.
 ELIFECYCLE  Test failed. See above for more details.
```

**Comment by Druue** [comment] 2024-01-03 00:21
Hey @ogroppo
I cloned your repo:
```
$ pnpm i

dependencies:
+ @prisma/client 3.14.0
+ prisma 3.14.0

devDependencies:
+ @types/jest 27.5.1
+ jest 28.1.0
+ ts-jest 28.0.3
+ typescript 4.7.2
+ weak-napi 2.0.2
```

Test on Node `v16.19.1`, pnpm `v8.6.12`

```ts
import prismaClient from "../prisma/prismaClient";

describe("schema", () => {
  afterAll(async () => {
    await prismaClient.$disconnect();
  });

  test("Deleting parent row in 1-to-n trows error", async () => {
    const user = await prismaClient.user.findFirst();
    expect(user).toBeFalsy();
  });
});
```

Yields
```
❯ pnpm t              
> jest --detectLeaks

ts-jest[config] (WARN) message TS151001: If you have issues related to imports, you should consider setting `esModuleInterop` to `true` in your TypeScript configuration file (usually `tsconfig.json`). See https://blogs.msdn.microsoft.com/typescript/2018/01/31/announcing-typescript-2-7/#easier-ecmascript-module-interoperability for more information.
 FAIL  tests/memory.test.ts
  ● Test suite failed to run

    EXPERIMENTAL FEATURE!
    Your test suite is leaking memory. Please ensure all references are cleaned.

    There is a number of things that can leak memory:
      - Async operations that have not finished (e.g. fs.readFile).
      - Timers not properly mocked (e.g. setInterval, setTimeout).
      - Keeping references to the global scope.

      at onResult (node_modules/.pnpm/@jest+core@28.1.0/node_modules/@jest/core/build/TestScheduler.js:188:18)
      at node_modules/.pnpm/@jest+core@28.1.0/node_modules/@jest/core/build/TestScheduler.js:300:17
      at node_modules/.pnpm/emittery@0.10.2/node_modules/emittery/index.js:311:13
          at Array.map (<anonymous>)
      at Emittery.emit (node_modules/.pnpm/emittery@0.10.2/node_modules/emittery/index.js:309:23)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        1.128 s
Ran all test suites.
zsh: segmentation fault  pnpm t
```

The following causes the test to pass.
```ts
import prismaClient from "../prisma/prismaClient";

describe("schema", () => {
  test("Deleting parent row in 1-to-n trows error", async () => {});
});
```

```
❯ pnpm t              
> jest --detectLeaks

ts-jest[config] (WARN) message TS151001: If you have issues related to imports, you should consider setting `esModuleInterop` to `true` in your TypeScript configuration file (usually `tsconfig.json`). See https://blogs.msdn.microsoft.com/typescript/2018/01/31/announcing-typescript-2-7/#easier-ecmascript-module-interoperability for more information.
 PASS  tests/memory.test.ts
  schema
    ✓ Deleting parent row in 1-to-n trows error (1 ms)

Test Suites: 1 passed, 1 total
Tests:       1 passed, 1 total
Snapshots:   0 total
Time:        0.761 s, estimated 1 s
Ran all test suites.
```

I tried downgrading to pnpm `v7.0.0` & node `v16.13.2` which made no difference

---

On node `v20.10.0` with the following test as @Jolg42 used
```ts
import { PrismaClient } from "@prisma/client";

describe("schema", () => {
  afterAll(async () => {
    const prismaClient = new PrismaClient();
  });

  test("empty test", async () => {});
});
```

I run into the following error:
```
❯ pnpm t              
> jest --detectLeaks

ts-jest[config] (WARN) message TS151001: If you have issues related to imports, you should consider setting `esModuleInterop` to `true` in your TypeScript configuration file (usually `tsconfig.json`). See https://blogs.msdn.microsoft.com/typescript/2018/01/31/announcing-typescript-2-7/#easier-ecmascript-module-interoperability for more information.
 FAIL  tests/memory.test.ts
  ● Test suite failed to run

    EXPERIMENTAL FEATURE!
    Your test suite is leaking memory. Please ensure all references are cleaned.

    There is a number of things that can leak memory:
      - Async operations that have not finished (e.g. fs.readFile).
      - Timers not properly mocked (e.g. setInterval, setTimeout).
      - Keeping references to the global scope.

      at onResult (node_modules/.pnpm/@jest+core@28.1.0/node_modules/@jest/core/build/TestScheduler.js:188:18)
      at node_modules/.pnpm/@jest+core@28.1.0/node_modules/@jest/core/build/TestScheduler.js:300:17
      at node_modules/.pnpm/emittery@0.10.2/node_modules/emittery/index.js:311:13
          at Array.map (<anonymous>)
      at Emittery.emit (node_modules/.pnpm/emittery@0.10.2/node_modules/emittery/index.js:309:23)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        0.36 s
Ran all test suites.
zsh: segmentation fault  pnpm t
```

Commenting out the client yields a passing test.
```
import { PrismaClient } from "@prisma/client";

describe("schema", () => {
  afterAll(async () => {
    // const prismaClient = new PrismaClient();
  });

  test("empty test", async () => {});
});
```

---

Updating to Prisma `v5.7.1` didn't affect output here:
```ts
import { PrismaClient } from "@prisma/client";

describe("schema", () => {
  afterAll(async () => {
    const prismaClient = new PrismaClient();
  });

  test("empty test", async () => {});
});

```

Yielded:
```
❯ pnpm t

> prisma-destroy-bug@1.0.0 test /Users/soph/src/repros/prisma-memory-leak-repro
> jest --detectLeaks

ts-jest[config] (WARN) message TS151001: If you have issues related to imports, you should consider setting `esModuleInterop` to `true` in your TypeScript configuration file (usually `tsconfig.json`). See https://blogs.msdn.microsoft.com/typescript/2018/01/31/announcing-typescript-2-7/#easier-ecmascript-module-interoperability for more information.
 FAIL  tests/memory.test.ts
  ● Test suite failed to run

    EXPERIMENTAL FEATURE!
    Your test suite is leaking memory. Please ensure all references are cleaned.

    There is a number of things that can leak memory:
      - Async operations that have not finished (e.g. fs.readFile).
      - Timers not properly mocked (e.g. setInterval, setTimeout).
      - Keeping references to the global scope.

      at onResult (node_modules/.pnpm/@jest+core@28.1.0/node_modules/@jest/core/build/TestScheduler.js:188:18)
      at node_modules/.pnpm/@jest+core@28.1.0/node_modules/@jest/core/build/TestScheduler.js:300:17
      at node_modules/.pnpm/emittery@0.10.2/node_modules/emittery/index.js:311:13
          at Array.map (<anonymous>)
      at Emittery.emit (node_modules/.pnpm/emittery@0.10.2/node_modules/emittery/index.js:309:23)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        0.493 s, estimated 1 s
Ran all test suites.
zsh: segmentation fault  pnpm t
```

While the following passed
```ts
import { PrismaClient } from "@prisma/client";

describe("schema", () => {
  afterAll(async () => {
    // const prismaClient = new PrismaClient();
  });

  test("empty test", async () => {});
});
```
```ts
describe("schema", () => {
  memoryLogger.log();

  afterAll(async () => {
    await prismaClient.$disconnect();
  });

  for (let i = 0; i < 100000; i++) {
    memoryLogger.log();
    test("test", async () => {
      const user = await prismaClient.user.findFirst();
      expect(user).toBeFalsy();
    });

    memoryLogger.log();
  }
});
```

Seems to indicate a possible memory leak
<img width="1044" alt="image" src="https://github.com/prisma/prisma/assets/29753584/0fc2b21d-5ea0-4367-8743-e1f94ab387ad">

**Comment by Jolg42** [comment] 2024-01-04 13:19
@ogroppo It's been a while since you opened this issue. As you can see, we investigated and posted results, but we didn't find an actual memory leak.

Jest `--detectLeaks` is an experimental feature, which is undocumented, and from our experience it's too often unreliable. You can see that similar results can be obtained without using Prisma.

If you have a reproduction where a memory leak can be observed, we will be happy to attempt a reproduction and investigate again.

I hope I can create a code template in the future with some guidelines to help with potential memory leaks issue in the future (to be done)

**Closed by Jolg42** 2024-01-04 13:19 UTC
Labels: bug/0-unknown, kind/bug, team/client, topic: jest, topic: performance/memory, topic: memory leak
