### ISSUE TITLE
NixOS support

### ISSUE THREAD

**Issue by arjunv27** [prisma/prisma#2305] opened 2020-04-26 14:16 UTC
## Problem
Unable to use Prisma on NixOS, receiving "Error: Get config" due to binaryTargets, documentation provides no options for NixOS

## Solution
Develop with Prisma successfully on NixOS

**Comment by Jolg42** [comment] 2020-04-27 16:15
From what I see in https://github.com/NixOS/docker/blob/master/Dockerfile

It is here based on alpine and we do not provide binaries from alpine at the moment see #702

**Comment by pantharshit00** [comment] 2020-05-24 22:36
Hey @arjunv27 

Since we support alpine and musl based systems now, can you please try this again?

**Comment by husseinraoouf** [comment] 2020-05-25 09:58
@pantharshit00 
I have tried and still the same error 
the fetch binaries script downloads the `debian-openssl-1.1.x` binaries I think because it couldn't detect NixOS

also, I don't think NixOS is based on alpine ( but I am not sure )

**Comment by Jolg42** [comment] 2020-05-25 12:35
@husseinraoouf Thanks for the update!

Do you know how I could reproduce what you have her? (I guess a setup of NixOS? If you have an example that would be awesome! because I never tried NixOS)

**Comment by Jolg42** [comment] 2020-05-25 14:11
So it looks like I was able to get NixOS running on VirtualBox but I have no idea what to do next to reproduce the error 🤷‍♂️ (I guess I need to install Node first any idea how?)

**Comment by pantharshit00** [comment] 2020-05-25 14:15
I did some research on nix and it is whole config based. You will need to add nodejs to your nix config in order to install it.


See: https://nixos.org/nixos/manual/index.html#sec-package-management and maybe go through the manual otherwise, I will mail you a vmdk with a installation

**Comment by Jolg42** [comment] 2020-05-25 16:45
Looks like this worked `nix-shell -p nodejs` I can now reproduce 🎊

**Comment by Jolg42** [comment] 2020-05-26 09:32
So it will now output a warning message saying that pre-compiled binaries are not available for nixos, so it's easier to understand what's happening here.

We do not have plan to provide pre-compiled binaries for NixOS for now.

See these 2 issues for more info
https://github.com/prisma/prisma/issues/2146
https://github.com/prisma/prisma/issues/1840

**Comment by husseinraoouf** [comment] 2020-05-26 16:18
@Jolg42 
that is better than the old error message for sure

I have managed to get the CLI working  by compiling the rust binaries from source and copying them to the package folder in node_modules

I have also packaged the cli as nix package for anyone else wanting to use Prisma in NixOS 
at https://gitlab.com/husseinraoouf/nur-repository you can use it by directly importing my git repo or wait till it is in NUR Repos :smiley:

I think this issue could be closed now and maybe update the documentation about the support of NixOS

**Comment by Jolg42** [comment] 2020-05-27 08:47
Awesome! I will keep this open for now as it's not an official support and no decision was taken yet on this.

Thanks for posting your nix package it will probably be useful for other people 👍

**Comment by husseinraoouf** [comment] 2020-05-27 16:06
@Jolg42 
I can't do `prisma generate` after updating to Beta.6 it shows this error
```
Error: Unknown binaryTargets nixos-openssl-1.1.x
```

I think because the cli now can recognize NixOS, the binary target became  `nixos-openssl-1.1.x` instead of the default fallback `debian-openssl-1.1.x`

I think it could be solved by adding  `nixos-openssl-1.1.x` to the possible values of binaryTargets

**Comment by Jolg42** [comment] 2020-05-28 08:34
@husseinraoouf Indeed!
I just fixed that in the latest alpha, you can try it like this `npx @prisma/cli@2.0.0-alpha.1258`

Let me know if this solves it or not.

**Comment by husseinraoouf** [comment] 2020-05-28 15:53
Thank you it works now :tada:

**Comment by Jolg42** [comment] 2020-07-15 13:25
Closing this was unblocked.

Tracking providing pre-built binaries in https://github.com/prisma/prisma/issues/3026

**Closed by Jolg42** 2020-07-15 13:25 UTC
Labels: kind/feature, topic: deployment-platforms
