### ISSUE TITLE
Expected parent IDs to be set when ordering by parent ID.

### ISSUE THREAD

**Issue by RomanticCoder** [prisma/prisma#25007] opened 2024-08-12 21:27 UTC
Hi Prisma Team! My Prisma Client just crashed. This is the report:
## Versions

| Name            | Version            |
|-----------------|--------------------|
| Node            | v18.18.2           | 
| OS              | windows            |
| Prisma Client   | 5.3.1              |
| Query Engine    | 61e140623197a131c2a6189271ffee05a7aa9a59|
| Database        | mysql              |

## Logs
```
PlatformCaching:postinstall false
prisma:client checkPlatformCaching:ciName 
prisma:tryLoadEnv Environment variables loaded from C:\Users\bnxto\OneDrive\Documents\GitHub\shared\.env
prisma:client dirname C:\Users\bnxto\OneDrive\Documents\GitHub\shared\node_modules\.prisma\client
prisma:client relativePath ../../../prisma
prisma:client cwd C:\Users\bnxto\OneDrive\Documents\GitHub\shared\prisma
prisma:client clientVersion 5.3.1
prisma:client:libraryEngine internalSetup
prisma:client:engines:resolveEnginePath enginePath C:\Users\bnxto\OneDrive\Documents\GitHub\shared\node_modules\.prisma\client\query_engine-windows.dll.node
prisma:client:libraryEngine sending request, this.libraryStarted: false
prisma:client:libraryEngine sending request, this.libraryStarted: false
prisma:client:libraryEngine library starting
prisma:client:libraryEngine library already starting, this.libraryStarted: false
prisma:client:libraryEngine library started
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client checkPlatformCaching:postinstall false
prisma:client checkPlatformCaching:ciName 
prisma:tryLoadEnv Environment variables loaded from C:\Users\bnxto\OneDrive\Documents\GitHub\shared\.env
prisma:client dirname C:\Users\bnxto\OneDrive\Documents\GitHub\shared\node_modules\.prisma\client
prisma:client relativePath ../../../prisma
prisma:client cwd C:\Users\bnxto\OneDrive\Documents\GitHub\shared\prisma
prisma:client clientVersion 5.3.1
prisma:client:libraryEngine internalSetup
prisma:client:engines:resolveEnginePath enginePath C:\Users\bnxto\OneDrive\Documents\GitHub\shared\node_modules\.prisma\client\query_engine-windows.dll.node
prisma:client:libraryEngine sending request, this.libraryStarted: false
prisma:client:libraryEngine sending request, this.libraryStarted: false
prisma:client:libraryEngine library starting
prisma:client:libraryEngine library already starting, this.libraryStarted: false
prisma:client:libraryEngine library started
prisma:client checkPlatformCaching:postinstall false
prisma:client checkPlatformCaching:ciName 
prisma:tryLoadEnv Environment variables loaded from C:\Users\bnxto\OneDrive\Documents\GitHub\shared\.env
prisma:client dirname C:\Users\bnxto\OneDrive\Documents\GitHub\shared\node_modules\.prisma\client
prisma:client relativePath ../../../prisma
prisma:client cwd C:\Users\bnxto\OneDrive\Documents\GitHub\shared\prisma
prisma:client clientVersion 5.3.1
prisma:client:libraryEngine internalSetup
prisma:client:engines:resolveEnginePath enginePath C:\Users\bnxto\OneDrive\Documents\GitHub\shared\node_modules\.prisma\client\query_engine-windows.dll.node
prisma:client:libraryEngine sending request, this.libraryStarted: false
prisma:client:libraryEngine sending request, this.libraryStarted: false
prisma:client:libraryEngine library starting
prisma:client:libraryEngine library already starting, this.libraryStarted: false
prisma:client:libraryEngine library started
prisma:client checkPlatformCaching:postinstall false
prisma:client checkPlatformCaching:ciName 
prisma:tryLoadEnv Environment variables loaded from C:\Users\bnxto\OneDrive\Documents\GitHub\shared\.env
prisma:client dirname C:\Users\bnxto\OneDrive\Documents\GitHub\shared\node_modules\.prisma\client
prisma:client relativePath ../../../prisma
prisma:client cwd C:\Users\bnxto\OneDrive\Documents\GitHub\shared\prisma
prisma:client clientVersion 5.3.1
prisma:client:libraryEngine internalSetup
prisma:client:engines:resolveEnginePath enginePath C:\Users\bnxto\OneDrive\Documents\GitHub\shared\node_modules\.prisma\client\query_engine-windows.dll.node
prisma:client:libraryEngine sending request, this.libraryStarted: false
prisma:client:libraryEngine sending request, this.libraryStarted: false
prisma:client:libraryEngine library starting
prisma:client:libraryEngine library already starting, this.libraryStarted: false
prisma:client:libraryEngine library started
prisma:client checkPlatformCaching:postinstall false
prisma:client checkPlatformCaching:ciName 
prisma:tryLoadEnv Environment variables loaded from C:\Users\bnxto\OneDrive\Documents\GitHub\shared\.env
prisma:client dirname C:\Users\bnxto\OneDrive\Documents\GitHub\shared\node_modules\.prisma\client
prisma:client relativePath ../../../prisma
prisma:client cwd C:\Users\bnxto\OneDrive\Documents\GitHub\shared\prisma
prisma:client clientVersion 5.3.1
prisma:client:libraryEngine internalSetup
prisma:client:engines:resolveEnginePath enginePath C:\Users\bnxto\OneDrive\Documents\GitHub\shared\node_modules\.prisma\client\query_engine-windows.dll.node
prisma:client:libraryEngine sending request, this.libraryStarted: false
prisma:client:libraryEngine sending request, this.libraryStarted: false
prisma:client:libraryEngine library starting
prisma:client:libraryEngine library already starting, this.libraryStarted: false
prisma:client:libraryEngine library started
prisma:client:request_handler {"name":"PrismaClientRustPanicError","clientVersion":"5.3.1"}
prisma:client checkPlatformCaching:postinstall false
prisma:client checkPlatformCaching:ciName 
prisma:tryLoadEnv Environment variables loaded from C:\Users\bnxto\OneDrive\Documents\GitHub\shared\.env
prisma:client dirname C:\Users\bnxto\OneDrive\Documents\GitHub\shared\node_modules\.prisma\client
prisma:client relativePath ../../../prisma
prisma:client cwd C:\Users\bnxto\OneDrive\Documents\GitHub\shared\prisma
prisma:client clientVersion 5.3.1
prisma:client:libraryEngine internalSetup
prisma:client:engines:resolveEnginePath enginePath C:\Users\bnxto\OneDrive\Documents\GitHub\shared\node_modules\.prisma\client\query_engine-windows.dll.node
prisma:client:libraryEngine sending request, this.libraryStarted: false
prisma:client:libraryEngine library starting
prisma:client:libraryEngine library started
```

## Client Snippet
```ts
// PLEASE FILL YOUR CODE SNIPPET HERE
```

## Schema
```prisma
// PLEASE ADD YOUR SCHEMA HERE IF POSSIBLE
```

## Prisma Engine Query
```
{"X":true}}}
```

**Comment by Weakky** [comment] 2024-08-13 07:51
Hey @RomanticCoder, I'm closing this issue is a duplicate of https://github.com/prisma/prisma/issues/15745. Feel free to subscribe to it. Thanks!

**Closed by Weakky** 2024-08-13 07:51 UTC
