### ISSUE TITLE
MySQL DECIMAL(X, 5) returns incorrect precision. 

### ISSUE THREAD

**Issue by Ustice** [prisma/prisma#13156] opened 2022-05-04 13:55 UTC
### Bug description

When I set a field to `@db.Decimal(20,5)` and I save a value—say 12—to the table and read it out, I get something like `12.000000000000002`. Not that this does _not_ happen for for other values of decimal precision (I have tried 2, 3, 4, and 6). 

### How to reproduce

See above. 

### Expected behavior

I understand that floating point arithmetic has precision issues, but I would expect consistent behavior between different levels of precision. Preferably rounding to the precision level. 

### Environment & setup

- OS: using the `node:fermium-buster-slim` docker image
- Database: MySQL
- Node.js version: 16.14.2

### Prisma Version

3.12.0

**Comment by SevInf** [comment] 2022-09-05 14:02
This specific case is a duplicate of #5925 and is fixed by the same patch.   I am going to close this for now, other, unrelated, decimal precision issues are tracked in #8160.

**Closed by SevInf** 2022-09-05 14:02 UTC
Labels: bug/1-unconfirmed, kind/bug, team/client, topic: Decimal, priority/unknown, size/unknown
