### ISSUE TITLE
Maximum Call Stack Size Exceeded When Inserting large Array Object

### ISSUE THREAD

**Issue by seanemmer** [prisma/prisma#15033] opened 2022-08-26 20:03 UTC
### Bug description

Running the prismaClient.create command with an object with an embedded string array of high length (750,000 elements) causes an error "Maximum Call Stack Size Exceeded"

### How to reproduce

Schema:

```
model User {
   id   String @id
   stringArray  String[]
}

```

Application Code
```
const stringArray = []
for(let i = 0, i< 750000, i++) {
     stringArray.push('ABC123')
}


prisma.user.create({data: {
     id: '123',
     stringArray
}})
```

### Expected behavior

Query succeeds

### Prisma information

See repro above

### Environment & setup

NodeJS 14
Postgres 13
Mac OS

### Prisma Version

3.13

**Comment by danstarns** [comment] 2022-08-30 11:43
You may be running into a limitation in Nodejs, have you tried playing around with some command line options like https://nodejs.org/api/cli.html#--max-old-space-sizesize-in-megabytes? I will mark this as a bug, I suggest you batch the create operations in the meantime.

**Comment by SevInf** [comment] 2022-09-08 10:27
Duplicate of #9372

**Closed by SevInf** 2022-09-08 10:27 UTC
Labels: bug/1-unconfirmed, kind/bug, topic: performance, team/client, topic: RangeError Maximum call stack size exceeded, size/unknown
