### ISSUE TITLE
/bin/sh: mongodb: command not found

### ISSUE THREAD

**Issue by csellis** [prisma/prisma#16363] opened 2022-11-20 07:36 UTC
### Bug description

When following the Prisma YT connection tutorials, I'm getting `/bin/sh: mongodb: command not found` when trying to connect to a remote repository.

Error
```
mac:apply-sveltekit/ (main✗) $ npx prisma generate                                                                                            [7:27:09]
Environment variables loaded from .env
Prisma schema loaded from prisma/schema.prisma
Error: Generator at mongodb could not start:

/bin/sh: mongodb: command not found
```

### How to reproduce

1. Follow instructions here [https://www.youtube.com/watch?v=BwVOIRX3VXk&ab_channel=Prisma](https://www.youtube.com/watch?v=BwVOIRX3VXk&ab_channel=Prisma)
2. Install homebrew
3. Install mongo-community@4.4 as described
4. Add to zsh `export PATH=/opt/homebrew/Cellar/mongodb-community@4.4.16/bin:$PATH`
6. set `.env` 
```
DATABASE_URL="mongodb+srv://<usr>:<password>@sumfin.onMongodb.mongodb.net/TABLE"
```

### Expected behavior

I expect it would generate my Prisma types

### Prisma information

```
generator client {
  provider = "mongodb"
}

datasource db {
  provider = "mongodb"
  url      = env("DATABASE_URL")
}
```

### Environment & setup

- OS: M1 MacOS
- Database: MongoDB hosted
- Node.js version: Now using node v16.18.0 (npm v9.1.2)

### Prisma Version

```
using npx
```

**Comment by miguelff** [comment] 2022-11-21 11:18
This is not a bug in prisma, but instead a problem with MongoDB shell setup. I followed the instructions and was able to complete the tutorial on my M1 Mac. Also, the tutorial is to set up a local mongo setup. I saw you provided an existing atlas URL for your connection string which means you will have to sync your `prisma.schema` with the remote mongo database using `prisma db:pull`

Did you add `export PATH=/opt/homebrew/Cellar/mongodb-community@4.4.16/bin:$PATH` to your shell dotfiles? (eg `~/.zshrc`) Otherwise, if you had closed your terminal or open a different session, the binary would not be found in the path. 

Are your .env keys being exported into the shell?

Closing as this is not an issue with prisma, please create a [discussion](https://github.com/prisma/prisma/discussions) if you need further support.

**Closed by miguelff** 2022-11-21 11:18 UTC
Labels: kind/bug

**Comment by janpio** [comment] 2022-11-22 00:40
Hey, there is actually a super simple mistake in the schema file: You also edited `provider = "prisma-client-js"` in the `generator client` block. This now tries to executed `mongodb` as a command under the hood, which also does not seem to work - but would _never_ be a valid generator for the Prisma CLI anyway.

Set that back to `  provider = "prisma-client-js"` and everything should work @csellis

**Comment by csellis** [comment] 2022-11-22 05:21
Oh wow @janpio, thank you so much, and good spot. It's working now.
