### ISSUE TITLE
Using _sum on findmany function

### ISSUE THREAD

**Issue by volkankorkmaz** [prisma/prisma#8639] opened 2021-08-07 12:23 UTC
### Discussed in https://github.com/prisma/prisma/discussions/8590

<div type='discussions-op-text'>

<sup>Originally posted by **volkankorkmaz** August  5, 2021</sup>
Hi everybody,

I have 2 tables as the below:

- Invoice
- InvoiceItem ( invoiceId, amount) 

I want to get the sum(amount) from InvoiceItem! Can you help me? Thx

Code:
```ts
list = ctx.prisma.invoice.findMany({
              skip: take * skip,
              take,
              where: {
                AND: [{ storeId }, { isDelete: false }, { supplierId }],
              },
              include: {                
                invoiceItems: {
                  select: {
                    _sum: {
                      amount: true,
                      as: 'totalAmount',
                    },
                    groupBy: {
                      invoice: true,
                    },
                  },
                },             
                location: true,
              },
              orderBy: [{ comment: sortType }],
            })
```

Query:
```graphql
query getInvoicesByFilter($input: byFilterInputPurchaseInvoice) {
  getInvoicesByFilter(input: $input) {
    list {
      id
      invoiceDate
      invoiceNumber
      TotalAmount
      comment          
    }
    totalCount
    responseCode
    responseMessage
  }
}
```</div>

**Comment by sandbox-apps** [comment] 2021-08-07 12:43
The sum aliasing using `as`
```ts
_sum: {
  amount: true,
  as: 'totalAmount',
},
```

is related to this one https://github.com/prisma/prisma/issues/8428

**Comment by pantharshit00** [comment] 2021-08-09 12:43
Yeah, I think we close this as duplicate of #8428 

Do manual aliasing for now.

**Closed by pantharshit00** 2021-08-09 12:43 UTC

**Comment by irvanherz** [comment] 2022-07-25 04:08
> Yeah, I think we close this as duplicate of #8428
> 
> Do manual aliasing for now.

No. Aliasing is not the point. But the point is how to "sum" multiple result in findMany?
