### ISSUE TITLE
One way relationships

### ISSUE THREAD

**Issue by kierangilliam** [prisma/prisma#3045] opened 2020-07-16 20:27 UTC
## Problem
It would be nice to be able to specify a one way relationship. For example, `A` has field `b` that is of type `B` but `B` does not have a backlink to an `A`. Currently, saving a `schema.prisma` file will automatically add a relation field on the `B` field. 

**This is what I am looking for**
```
model A {
	id String
	b B @relation(fields: [bID])
	bID String
}

model B {
	id String
}
```

**Comment by pantharshit00** [comment] 2020-07-23 11:52
I will consider this as a duplicate of #2018 

Feel free to comment your suggestion in that issue.

**Closed by pantharshit00** 2020-07-23 11:52 UTC
