### ISSUE TITLE
 Prisma core crashes when trying to get the number of relations for a nested query

### ISSUE THREAD

**Issue by DenisVASI9** [prisma/prisma#7304] opened 2021-05-27 09:54 UTC
### Bug description

Return the number of relations for a group entity within devices

### How to reproduce

1) run this
const groups = await this.prisma.group.findMany({
      include: {
        devices: { 
          include: {
            _count: {
              select: {
                groups: true
              }
            }
          }
        },
      },
    });
2) Get kernel panic :)    

### Prisma information

// This is your Prisma schema file,
// learn more about it in the docs: https://pris.ly/d/prisma-schema

datasource db {
  provider = "postgresql"
  url      = "<>"
}

generator client {
  provider = "prisma-client-js"
}

model device {
  id   String  @id @db.Uuid
  mac  String  @unique @db.VarChar(255)
  ipv4 String  @db.Inet
  ipv6 String? @db.Inet

  groups group[]
  disk   disk[]
  boot   boot[]
}

model group {
  id   Int    @id @default(autoincrement())
  name String @db.VarChar(255)

  devices device[]
}

model association {
  id         Int    @id @default(autoincrement())
  lunid      Int    @db.Integer
  targetData target @relation(fields: [target], references: [id])
  target     Int    @db.Integer
  extentData extent @relation(fields: [extent], references: [id])
  extent     Int    @db.Integer

  disk disk[]
}

model disk {
  id            Int         @id @default(autoincrement())
  bootable      Boolean     @db.Boolean
  enabled       Boolean     @db.Boolean
  priority      Int         @default(0) @db.Integer
  name          String      @db.VarChar(255)
  association   association @relation(fields: [associationId], references: [id])
  associationId Int
  device        device      @relation(fields: [deviceId], references: [id])
  deviceId      String      @db.Uuid

  actions dd[] @relation("actions")
}

model extent {
  id              Int     @id @default(autoincrement())
  name            String  @db.VarChar(255)
  serial          String  @db.VarChar(255)
  type            String  @db.VarChar(255)
  path            String  @db.VarChar(255)
  filesize        String  @db.VarChar(255)
  enabled         Boolean @db.Boolean
  pblocksize      Boolean @db.Boolean
  avail_threshold Int?    @db.Integer
  naa             String  @db.VarChar(255)
  comment         String  @db.VarChar(255)
  xen             Boolean @db.Boolean
  rpm             String  @db.VarChar(255)
  ro              Boolean @db.Boolean
  vendor          String  @db.VarChar(255)
  disk            String? @db.VarChar(255)
  locked          Boolean @db.Boolean

  association association[]
}

model target {
  id     Int      @id @default(autoincrement())
  name   String   @db.VarChar(255)
  alias  String   @db.VarChar(255)
  mode   String   @db.VarChar(255)
  groups String[] @db.VarChar(255)

  association association[]
  boot        boot[]
}

model boot {
  id       Int    @id @default(autoincrement())
  path     String @db.VarChar(255)
  device   device @relation(fields: [deviceId], references: [id])
  deviceId String @unique @db.Uuid
  target   target @relation(fields: [targetId], references: [id])
  targetId Int    @unique @db.Integer
}

model dd {
  id         Int    @id @default(autoincrement())
  bytes      String @db.VarChar(255)
  mb         String @db.VarChar(255)
  mib        String @db.VarChar(255)
  transfered String @db.VarChar(255)
  speed      String @db.VarChar(255)
  percent    Float  @db.DoublePrecision
  actions    disk   @relation("actions", fields: [toId], references: [id])
  toId       Int    @db.Integer
}

### Environment & setup

- OS: Arch
- Database: PostgreSQL
- Node.js version: v14.15.4

### Prisma Version

```
prisma               : 2.22.1
@prisma/client       : 2.22.1
Current platform     : debian-openssl-1.1.x
Query Engine         : query-engine 60cc71d884972ab4e897f0277c4b84383dddaf6c (at node_modules/@prisma/engines/query-engine-debian-openssl-1.1.x)
Migration Engine     : migration-engine-cli 60cc71d884972ab4e897f0277c4b84383dddaf6c (at node_modules/@prisma/engines/migration-engine-debian-openssl-1.1.x)
Introspection Engine : introspection-core 60cc71d884972ab4e897f0277c4b84383dddaf6c (at node_modules/@prisma/engines/introspection-engine-debian-openssl-1.1.x)
Format Binary        : prisma-fmt 60cc71d884972ab4e897f0277c4b84383dddaf6c (at node_modules/@prisma/engines/prisma-fmt-debian-openssl-1.1.x)
Default Engines Hash : 60cc71d884972ab4e897f0277c4b84383dddaf6c
Studio               : 0.379.0

```

**Comment by pantharshit00** [comment] 2021-05-27 13:31
Firstly, this is not a kernel panic but a Prisma binary panic. 

This has been already reported actually so I will close this as a duplicate of https://github.com/prisma/prisma/issues/6543

**Closed by pantharshit00** 2021-05-27 13:31 UTC
Labels: kind/bug
