### ISSUE TITLE
`referentialIntegrity` on PlanetScale fails to delete relationship inside of `update()`

### ISSUE THREAD

**Issue by jonahallibone** [prisma/prisma#10995] opened 2022-01-06 22:53 UTC
### Bug description

I believe I am having trouble with this same issue in my schema. I have a Menu model and a Section model and `1:M` from Menu -> Section

```
generator client {
  provider        = "prisma-client-js"
  previewFeatures = ["referentialIntegrity"]
}

datasource db {
  provider             = "mysql"
  url                  = env("DATABASE_URL")
  referentialIntegrity = "prisma"
}

model Menu {
  id        String     @id @default(cuid())
  title     String
  userId    String
  language  String
  currency  String
  createdAt DateTime   @default(now())
  updatedAt DateTime   @updatedAt
  theme     String?
  published Boolean    @default(false)
  user      User       @relation(fields: [userId], references: [id], onDelete: Cascade)
  sections  Section[]
  items     MenuItem[]

  @@unique(fields: [id, userId], name: "menuId_userId_unique")
}

model Section {
  id        String                @id @default(cuid())
  menuId    String
  hidden    Boolean               @default(false)
  deleted   Boolean               @default(false)
  title     String
  order     Int                   @default(0)
  createdAt DateTime              @default(now())
  updatedAt DateTime              @updatedAt
  menu      Menu                  @relation(fields: [menuId], references: [id], onDelete: Cascade, onUpdate: NoAction)
  addons    SectionAddOn[]
  items     MenuItemsOnSections[]

  @@index([menuId])
}
```

When I try to perform an update/delete on a section
```
const menu = await prisma.menu.update({
  where: {
    menuId_userId_unique: {
      id,
      userId: session.user.id,
    },
  },
  data: {
    sections: {
      delete: {
        id: sectionId,
      },
    },
  },
  include: {
    sections: {
      include: {
        items: {
          include: {
            menuItem: true,
          },
        },
      },
    },
  },
});
```

I get them following error:
```
Invalid `prisma.menu.update()` invocation:

Error occurred during query execution:
ConnectorError(ConnectorError { user_facing_error: None, kind: QueryError(Server(ServerError { code: 1105, message: "symbol `example-db`.Section.id not found", state: "HY000" })) })
```

I've tried to follow previous advice by adding `onUpdate: NoAction` to my relations, however, this does not seem to remedy this issue with deletes. Is there something more I should be doing to make this delete behavior work with PlanetScale?

I have ensured the passed `id` for `sectionId` does in fact exist, and I am able to pull it using `findUnique`, as well as see it in Prisma Studio

### How to reproduce

Create a schema with a 1:M relationship and attempt to remove an item from the parent model via `update()` and `delete`

### Expected behavior

The relationship should be removed from the database

### Prisma information

```
generator client {
  provider        = "prisma-client-js"
  previewFeatures = ["referentialIntegrity"]
}

datasource db {
  provider             = "mysql"
  url                  = env("DATABASE_URL")
  referentialIntegrity = "prisma"
}

model Account {
  id                       String  @id @default(cuid())
  userId                   String
  type                     String
  provider                 String
  providerAccountId        String
  refresh_token            String?
  refresh_token_expires_in Int?
  access_token             String?
  expires_at               Int?
  token_type               String?
  scope                    String?
  id_token                 String?
  session_state            String?
  oauth_token_secret       String?
  oauth_token              String?

  user User @relation(fields: [userId], references: [id], onDelete: Cascade)

  @@unique([provider, providerAccountId])
}

model Session {
  id           String   @id @default(cuid())
  sessionToken String   @unique
  userId       String
  expires      DateTime
  user         User     @relation(fields: [userId], references: [id], onDelete: Cascade)
}

model User {
  id            String    @id @default(cuid())
  name          String?
  email         String?   @unique
  emailVerified DateTime?
  image         String?
  accounts      Account[]
  sessions      Session[]
  menus         Menu[]
}

model VerificationToken {
  identifier String
  token      String   @unique
  expires    DateTime

  @@unique([identifier, token])
}

model Menu {
  id        String     @id @default(cuid())
  title     String
  userId    String
  language  String
  currency  String
  createdAt DateTime   @default(now())
  updatedAt DateTime   @updatedAt
  theme     String?
  published Boolean    @default(false)
  user      User       @relation(fields: [userId], references: [id], onDelete: Cascade)
  sections  Section[]
  items     MenuItem[]

  @@unique(fields: [id, userId], name: "menuId_userId_unique")
}

model Section {
  id        String                @id @default(cuid())
  menuId    String
  hidden    Boolean               @default(false)
  deleted   Boolean               @default(false)
  title     String
  order     Int                   @default(0)
  createdAt DateTime              @default(now())
  updatedAt DateTime              @updatedAt
  menu      Menu                  @relation(fields: [menuId], references: [id], onDelete: Cascade, onUpdate: NoAction)
  addons    SectionAddOn[]
  items     MenuItemsOnSections[]

  @@index([menuId])
}

model MenuItem {
  id             String                @id @default(cuid())
  hidden         Boolean               @default(false)
  deleted        Boolean               @default(false)
  title          String
  description    String?
  extra          String?
  isFeaturedItem Boolean               @default(false)
  createdAt      DateTime              @default(now())
  updatedAt      DateTime              @updatedAt
  menuId         String
  menu           Menu                  @relation(fields: [menuId], references: [id], onDelete: Cascade, onUpdate: NoAction)
  prices         Price[]
  addons         ItemAddOn[]
  foodLabels     FoodLabelsOnItems[]
  sections       MenuItemsOnSections[]
}

model MenuItemsOnSections {
  menuItemId String
  sectionId  String
  order      Int
  menuItem   MenuItem @relation(fields: [menuItemId], references: [id], onDelete: Cascade, onUpdate: NoAction)
  section    Section  @relation(fields: [sectionId], references: [id], onDelete: Cascade, onUpdate: NoAction)

  @@id([menuItemId, sectionId])
}

model FoodLabel {
  id        String              @id @default(cuid())
  title     String              @unique
  isActive  Boolean             @default(true)
  createdAt DateTime            @default(now())
  updatedAt DateTime            @updatedAt
  items     FoodLabelsOnItems[]
}

model FoodLabelsOnItems {
  foodLabelId String
  itemId      String
  assignedAt  DateTime  @default(now())
  foodLabel   FoodLabel @relation(fields: [foodLabelId], references: [id], onDelete: Cascade, onUpdate: NoAction)
  item        MenuItem  @relation(fields: [itemId], references: [id], onDelete: Cascade, onUpdate: NoAction)

  @@id([foodLabelId, itemId])
}

model SectionAddOn {
  id        String   @id @default(cuid())
  name      String
  price     Float
  sectionId String
  createdAt DateTime @default(now())
  updatedAt DateTime @updatedAt
  deleted   Boolean  @default(false)
  section   Section  @relation(fields: [sectionId], references: [id], onDelete: Cascade, onUpdate: NoAction)
}

model ItemAddOn {
  id        String   @id @default(cuid())
  title     String
  price     Float
  itemId    String
  createdAt DateTime @default(now())
  updatedAt DateTime @updatedAt
  deleted   Boolean  @default(false)
  item      MenuItem @relation(fields: [itemId], references: [id], onDelete: Cascade, onUpdate: NoAction)
}

model Price {
  id        String   @id @default(cuid())
  itemId    String
  title     String?
  price     Float
  createdAt DateTime @default(now())
  updatedAt DateTime @updatedAt
  deleted   Boolean  @default(false)
  item      MenuItem @relation(fields: [itemId], references: [id], onDelete: Cascade, onUpdate: NoAction)
}
```

### Environment & setup

- OS: macOS
- Database: PlanetScale
- Node.js version: v14.17.0

### Prisma Version

```
prisma                  : 3.7.0
@prisma/client          : 3.7.0
Current platform        : darwin
Query Engine (Node-API) : libquery-engine 8746e055198f517658c08a0c426c7eec87f5a85f (at node_modules/@prisma/engines/libquery_engine-darwin.dylib.node)
Migration Engine        : migration-engine-cli 8746e055198f517658c08a0c426c7eec87f5a85f (at node_modules/@prisma/engines/migration-engine-darwin)
Introspection Engine    : introspection-core 8746e055198f517658c08a0c426c7eec87f5a85f (at node_modules/@prisma/engines/introspection-engine-darwin)
Format Binary           : prisma-fmt 8746e055198f517658c08a0c426c7eec87f5a85f (at node_modules/@prisma/engines/prisma-fmt-darwin)
Default Engines Hash    : 8746e055198f517658c08a0c426c7eec87f5a85f
Studio                  : 0.445.0
Preview Features        : referentialIntegrity
```

**Comment by janpio** [comment] 2022-01-07 02:26
The error message sounds awfully like https://github.com/prisma/prisma/issues/10758, but probably in a slightly different combination. Can you maybe simplify your schema and query to the absolute minimum needed to trigger the problem? That would be helpful.

**Comment by jde** [comment] 2022-01-07 10:32
The `onDelete: Cascade` instructions are still prompting prisma to generate the queries that reference the foreign id in a way that prisma rejects. Try removing all the instances of `onDelete: Cascade`.

**Comment by pantharshit00** [comment] 2022-01-07 10:38
I can reproduce this and yeah I would consider this as duplicate of #10758. Workaround suggested by @jde should work here.

**Closed by pantharshit00** 2022-01-07 10:38 UTC
Labels: bug/1-repro-available, kind/bug, topic: broken query, team/client, topic: referential actions, topic: referentialIntegrity

**Comment by jonahallibone** [comment] 2022-01-07 20:58
Does prisma support any referential actions with PlanetScale at all right now?

**Comment by janpio** [comment] 2022-01-07 21:21
Technically `NoAction` is a referential action and works - and that definitely works - but I see that is not what you are asking for.

We do not have a full test coverage of the emulated referential actions as they are a preview feature - and what is broken is exactly the feedback we are hoping for. The `onDelete` on in _theory_ should also work fine, but it seems that is not fully the case as this issue here shows.
