### ISSUE TITLE
Error in schema.prisma for enums  with multiple database schemas

### ISSUE THREAD

**Issue by joelrb** [prisma/prisma#23081] opened 2024-02-12 09:13 UTC
### Bug description

Why would an enum needs a schema? Error without it.

enum UserRole {
  SUPERADMIN
  ADMIN
  USER
  @@schema("sc_users")
}

model User {
  id                    String                 @id @default(cuid())
  role                  UserRole  
  @@schema("sc_users")
}

![Screenshot 2024-02-12 170606](https://github.com/prisma/prisma/assets/225284/8c731bbb-6dca-4ad0-a1f2-d4efd97b0329)

### How to reproduce

Add models in prisma.schema file.

### Expected behavior

No error for enums.

### Prisma information

```prisma
// Add your schema.prisma
```

```ts
// Add your code using Prisma Client
```

### Environment & setup

- OS: Windows
- Database: PostgreSQL
- Node.js version: v21.5.0
- NextJS version: v14

### Prisma Version

```
^5.9.1
```

**Comment by jkomyno** [comment] 2024-02-12 09:53
Hi @joelrb, what you're reporting is working as intended. `ENUM` declarations are not global: they live in a database schema. Hence, indicating which schema they belong to is required when working with multiple database schemas, like in your case.

I hope this helps! I'm closing this as "not an issue", but if you have further comments, please add them below here. Thanks :)

**Closed by jkomyno** 2024-02-12 09:53 UTC
Labels: kind/bug
