### ISSUE TITLE
DeprecationWarning: OutgoingMessage.prototype._headers is deprecated

### ISSUE THREAD

**Issue by rhuankarlus** [prisma/prisma#4710] opened 2019-07-01 11:44 UTC
**Describe the bug**
When I try to run `prisma deploy` I get the following error:

```
 ▸    Could not connect to server at http://localhost:4466. Please check if your server is running.

Get in touch if you need help: https://spectrum.chat/prisma
To get more detailed output, run $ export DEBUG="*"
(node:27978) [DEP0066] DeprecationWarning: OutgoingMessage.prototype._headers is deprecated
```

I'm running it on POP-OS (ubuntu based), and everything works fine for node applications. I'm behind an internal proxy server but all my system is connected and NPM is configured to use it. I would like to try prisma because I think we can use it at the company, so I'm implementing some GraphQL tutorials such as https://www.howtographql.com/graphql-js/0-introduction/

**To Reproduce**
1. Go to my project at https://github.com/rhuankarlus/hackernews-node
2. Clone it
3. cd <project-folder>
4. Run `prisma deploy` and try to to anything like run it from docker or run it on a database installed on your machine.

**Expected behavior**
Given that I'm trying to run it connected to the prisma server I think that the default behaviour would be to create endpoints for my Link model (there's a model called Link on my project).

**Screenshots**
![image](https://user-images.githubusercontent.com/4607181/60433920-51438280-9bdc-11e9-8728-824c9d900dff.png)

**Versions (please complete the following information):**
 - Node version: v12.1.0
 - NPM version: 6.9.0
 - OS: Pop-OS (ubuntu based)

**Comment by pantharshit00** [comment] 2019-07-01 13:05
@rhuankarlus 

First of all please double check, you have started your docker instance using `docker-compose up -d`. Then go to http://localhost:4466 and see whether you see a GraphQL Playground there.


It takes roughly 10secs for Prisma to boot up that might be the issue as I was unable to reproduce this.

**Comment by rhuankarlus** [comment] 2019-07-01 13:31
Yes @pantharshit00 the application is running with a graphql-yoga server at port 4466. And I didn't run my application using docker, but if it's necessary to use prisma, I can run it. But I don't think it is mandatory to use the API to a database such as prisma.

**Comment by rhuankarlus** [comment] 2019-07-01 13:50
@pantharshit00 just to clarify, I didn't start this project using `prisma init`. I've started a new node project from scratch and them, I've added the `prisma` folder with the data model and configuration contents.

From this, I ran the command `prisma deploy` as mentioned.

**Comment by pantharshit00** [comment] 2019-07-01 15:59
Ok, If you don't want to use docker and just want an ORM, please look into Prisma 2: https://www.prisma.io/blog/announcing-prisma-2-zq1s745db8i5/

We have eliminated the use of docker there. Basically works like a normal ORM without an additional server to manage.

I think I can close this now.

**Closed by pantharshit00** 2019-07-01 15:59 UTC
Labels: area/deploy, bug/0-needs-info

**Comment by JOHNFLEURIMOND** [comment] 2019-11-03 16:28
@pantharshit00 quick question, if you had a older application and you were trying to deploy now and received this message, do i have to scrap this one and make a new one via prisma2?

**Comment by JOHNFLEURIMOND** [comment] 2019-11-03 16:31
@pantharshit00 https://github.com/JOHNFLEURIMOND/ReactGraphQL I am referring to this code
