### ISSUE TITLE
nest sort issue

### ISSUE THREAD

**Issue by hatemragab** [prisma/prisma#5147] opened 2021-01-18 11:37 UTC
my model 
```
model User {
  id        Int        @id @default(autoincrement())
  email     String     @unique
  userRooms UserRoom[]
  name      String
  password  String
  createdAt String
  MessageStatus MessageStatus[]
  Message       Message[]
}

model Room {
  id    Int    @id @default(autoincrement())
  title String
  userRoom  UserRoom[]
  image     String
  creator   Int
  roomType  String     @default("single")
  createdAt String
  Message Message[]
}

model UserRoom {
  id Int @id @default(autoincrement())
  user   User @relation(fields: [userId], references: [id])
  userId Int
  room   Room @relation(fields: [roomId], references: [id])
  roomId Int
  isMuted   Int @default(0)
  isDeleted Int @default(0)
  isBlocked Int @default(0)

}

model Message {
  id            Int             @id @default(autoincrement())
  sender        User            @relation(fields: [senderId], references: [id])
  senderId      Int
  room          Room            @relation(fields: [roomId], references: [id])
  roomId        Int
  content       String
  messageType   String          @default("text")
  createdAt     String
  MessageStatus MessageStatus[]
}

model MessageStatus {
  id         Int     @id @default(autoincrement())
  message    Message @relation(fields: [messageId], references: [id])
  messageId  Int
  senderId   Int
  receiverId Int
  status     Int
  createdAt  String
  seenAt     String
  User   User? @relation(fields: [userId], references: [id])
  userId Int?
}
```
from UserRoom, I want to get all users room with its last message I got it but the problem is rooms not order by last message time 

```
    return this.prisma.userRoom.findMany({
      where: {
        userId: 1,
      },
      select: {
        isBlocked: true,
        room: {
          select: {
            id: true,
            Message: {
              orderBy: {
                createdAt: 'desc',
              },
            },
          },
        },
      },
    });
```
messages only sorted but not the rooms how can I perform like that in mongoose i can do it by 
```
  {$sort: {"lastMessage._id": -1}},
```
the sort applied for all docs not just message 

response is 
```
[
    {
        "isBlocked": 0,
        "room": {
            "id": 1,
            "Message": [
                {
                    "id": 2,
                    "senderId": 1,
                    "roomId": 1,
                    "content": "2",
                    "messageType": "text",
                    "createdAt": "2"
                },
                {
                    "id": 1,
                    "senderId": 1,
                    "roomId": 1,
                    "content": "fadf",
                    "messageType": "text",
                    "createdAt": "1"
                }
            ]
        }
    },
    {
        "isBlocked": 0,
        "room": {
            "id": 2,
            "Message": [
                {
                    "id": 3,
                    "senderId": 1,
                    "roomId": 2,
                    "content": "3",
                    "messageType": "text",
                    "createdAt": "3"
                }
            ]
        }
    }
]
```
what I want to get is 

```
[

    {
        "isBlocked": 0,
        "room": {
            "id": 2,
            "Message": [
                {
                    "id": 3,
                    "senderId": 1,
                    "roomId": 2,
                    "content": "3",
                    "messageType": "text",
                    "createdAt": "3"
                }
            ]
        }
    },
    {
        "isBlocked": 0,
        "room": {
            "id": 1,
            "Message": [
                {
                    "id": 2,
                    "senderId": 1,
                    "roomId": 1,
                    "content": "2",
                    "messageType": "text",
                    "createdAt": "2"
                },
                {
                    "id": 1,
                    "senderId": 1,
                    "roomId": 1,
                    "content": "fadf",
                    "messageType": "text",
                    "createdAt": "1"
                }
            ]
        }
    }

]
```
because this message is the last message send or received 
```
       "Message": [
                {
                    "id": 3,
                    "senderId": 1,
                    "roomId": 2,
                    "content": "3",
                    "messageType": "text",
                    "createdAt": "3"
                }
            ]
```

**Comment by pantharshit00** [comment] 2021-01-21 15:37
Hi,

Thanks for reporting this! It has already been reported before, so I am going to close this as a duplicate of https://github.com/prisma/prisma/issues/5008

**Closed by pantharshit00** 2021-01-21 15:37 UTC
