### ISSUE TITLE
Linux 'void' Distro Not Recognized for Prisma Engines

### ISSUE THREAD

**Issue by rojasricor** [prisma/prisma#21551] opened 2023-10-18 23:09 UTC
### Bug description

Prisma is unable to recognize the Linux 'void' distribution and falls back to Prisma engines built for 'debian,' which results in errors during the installation process.

### How to reproduce

1. Use Prisma on a Linux 'void' distribution.
2. Observe the warning messages and error as mentioned below.

### Prisma information

```prisma
// This is your Prisma schema file,
// learn more about it in the docs: https://pris.ly/d/prisma-schema

generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider  = "postgresql"
  url       = env("POSTGRES_PRISMA_URL") // uses connection pooling
  directUrl = env("POSTGRES_URL_NON_POOLING") // uses a direct connection
}

model User {
  id            Int    @id @default(autoincrement())
  document_type String 
  document      String @unique
  first_name    String
  last_name     String
  phone_number  String @unique
  email         String @unique
  password      String
  createdAt     DateTime @default(now())
  updatedAt     DateTime @updatedAt
}

```

### Environment & setup

- OS: Void Linux distribution.
- Node.js version: v18.16.0

### Prisma Version

"prisma": "^5.3.1"

**Comment by jkomyno** [comment] 2023-10-19 06:29
> Observe the warning messages and error as mentioned below.

Hi, we do not see any error message pasted in the issue above. We expect however you to see a warning

> prisma:warn Prisma doesn't know which engines to download for the Linux distro "void". Falling back to Prisma engines built "debian".

which can safely be ignored as long as no errors occur. If that's not the case, please leave a comment with any errors you're seeing. Thanks!

**Comment by janpio** [comment] 2023-10-19 09:00
Duplicate of https://github.com/prisma/prisma/issues/20434 probably?

**Closed** 2023-10-22 17:50 UTC
Labels: bug/0-unknown, kind/bug, team/schema
