### ISSUE TITLE
Prisma queries match only on key fields

### ISSUE THREAD

**Issue by cyrusae** [prisma/prisma#12859] opened 2022-04-17 12:41 UTC
### Bug description

I have a route that does a raw SQL query for the minimum value in a column (in this case, `lastSeenAsInt`) and then uses a normal Prisma query to find the first record with that value. I have confirmed that the SQL query is returning the correct value but the subsequent Prisma query does not return the record it's attached to.

In general, it appears that when making queries on Int fields, Prisma does not actually run any comparisons about fields that are not the table ID. i.e., I can fetch a statement in the Statements table by statementID, but `findFirst` for an occurrence of a value in another column fails.

I would rewrite to just be raw SQL, but according to other issues on here Prisma can't handle queries in raw SQL to a SQLite database containing variables, which is why I'm passing it back and forth to begin with. [Here is the issue on my own repository](https://github.com/cyrusae/highlighter-public/issues/25) for more context; I am trying to navigate through the sample records in this way and as is one of them appears to be permanently unreachable despite/because it has the low `lastSeenAsInt` I'm looking for. (The reason it's checking that the statementIDs aren't equal to the currently-displayed one is that when I removed that criteria, not only did Prisma not find the correct record, it would just give me three copies of the same one each time.)

### How to reproduce

1. Create a Prisma SQLite db with a model containing one or more columns that are not the key and four or more records with values in that column.
2. Use raw SQL to find the MIN() and MAX() values of one of those columns.
3. Attempt to `findFirst` the records to which those MIN() and MAX() values belonged.

### Expected behavior

Searching for the first occurrence of `lastSeenAsInt` equaling 1 should return the record with `lastSeenAsInt = 1`, not a random other record.

### Prisma information

[Full schema here](https://github.com/cyrusae/highlighter-public/blob/main/backend/prisma/schema.prisma). Relevant model:
```prisma
model Statement {
  statementID Int                @unique
  content     String
  plainText   String? 
  coded       Boolean            @default(false)
  updatedAt   DateTime           @default(now()) @updatedAt
  lastSeenAsInt   Int @default(0)
  comments    String?
  Encoding    Encoding[]
  Context     StatementContext? 
  Abstract    StatementAbstract? 
}
```
Relevant queries:
```js
 const { statementID } = req.params as any;
 const big = await prisma.$queryRaw<Statement[]>`SELECT MAX(lastSeenAsInt) FROM Statement`;
 const mostRecent = big[0].lastSeenAsInt;

 const small = await prisma.$queryRaw<Statement[]>`SELECT MIN(lastSeenAsInt) FROM Statement`;
 const leastRecent = small[0].lastSeenAsInt;

 try 
 {{const statement = await prisma.statement.findUnique({
  where: {
   statementID: (parseInt(statementID, 10)),
  }
 });
const prevStatement = await prisma.statement.findFirst({
 where: {
  lastSeenAsInt: {
   gte: big[0].lastSeenAsInt,
   not: statement.lastSeenAsInt
  },
  statementID: {
   not: statement.statementID
  }
 },
 select: {
  statementID: true,
 },
 rejectOnNotFound: true,
})
const prevID = prevStatement.statementID;
const nextStatement = await prisma.statement.findFirst({
 where: {
  lastSeenAsInt: {
   lte: small[0].lastSeenAsInt,
   equals: leastRecent
  },
 statementID: {
  not: prevID,
  notIn: [statement.statementID]
 },
  select: {
   statementID: true,
  },
 rejectOnNotFound: true,
 });
 const nextID = nextStatement.statementID;
```
(The reason for the dual `not`/`notIn` checks is because I had been testing whether I could get the correct response if there weren't multiple variables in a single condition before I gave up and filed this bug report.)

### Environment & setup

- OS: Mac OS 11.6
- Database: SQLite
- Node.js version: v17.3.1

### Prisma Version

```
8.3.1
```

**Comment by cyrusae** [comment] 2022-04-17 12:43
[Here's an example of the raw SQL query output versus the actual Prisma response](https://github.com/cyrusae/highlighter-public/issues/25#issuecomment-1100865534), if that helps.

**Comment by do4gr** [comment] 2022-09-07 14:21
Hello @cyrusae, 

thanks for opening the issue. I've tried reproducing and think Prisma is not broken in this case. 

```
 const big = await prisma.$queryRaw<Statement[]>`SELECT MAX(lastSeenAsInt) FROM Statement`;
 ```
 
 will return a result of the shape `[ { min: 1 } ]` (or max if you call the max function)
 
 You are then trying to access the `lastSeenInt` property which will yield an `undefined`. 
 
 If you use Prisma to find a row whose value for `lastSeenInt` equals `undefined` all rows will evaluate to hits (See[ here](https://www.prisma.io/docs/concepts/components/prisma-client/null-and-undefined#the-effect-of-null-and-undefined-on-conditionals)). Since you are using a findFirst Prisma just picks the first one. 
 
 In my testing if accessing the correct `min` or `max` property on the result of the raw query I actually got an Int value which then yielded the correct row when used in the `findFirst`.

Please try this out and let me know whether that solves your problem. 

I am closing this as not a bug, but if you disagree please post here.

**Closed by do4gr** 2022-09-07 14:21 UTC
Labels: bug/1-unconfirmed, kind/bug, topic: sqlite, tech/engines, topic: findFirst, team/client, priority/low, size/unknown
