### ISSUE TITLE
Support for CockroachDB in Prisma ORM

### ISSUE THREAD

**Issue by albertoperdomo** [prisma/prisma#2523] opened 2020-05-20 09:47 UTC
Note: Prisma Client, which is the part which queries the data, already works with Cockroach with the Postgres mode.

**Comment by flybayer** [comment] 2020-05-22 08:40
I'm definitely interested in this too 👀

**Comment by pantharshit00** [comment] 2020-05-24 22:32
A bit more context here: https://github.com/prisma/migrate/issues/426

**Comment by vy-ton** [comment] 2020-08-05 14:27
Hi, product manager at Cockroach Labs here. We are interested in improving support for CockroachDB. What would the next step be? Looks like more info on building your own connector is [coming](https://www.prisma.io/docs/more/faq#will-prisma-client-support-more-databases-and-other-data-sources-in-the-future)?

**Comment by pantharshit00** [comment] 2020-08-05 15:12
@vy-ton Prisma client which is part which queries the data already works with Cockroach with the postgres mode. 

The part which doesn't work right now is Prisma Migrate(see prisma/migrate#426). Migrate queries the information schema to figure out the state of the database and it is using some postgres functions which are not supported by cockroach.

Right now there is not really an API for creating a custom Prisma connector for the public. So that way is not really feasible right now.

We are also overhauling migrate, making quite a lot of changes to it so that we can take it out from the experimental state so this will not be a priority for us until then.

**Comment by janpio** [comment] 2020-08-05 18:30
On the other hand we just prioritized an issue https://github.com/prisma/prisma-engines/issues/900 that will (temporarily) add CockroachDB to our test suite, so we are more certain what is failing and why. If we learn anything unexpected (e.g. the problem not being caused by https://github.com/cockroachdb/cockroach/issues/50734) we will update here.

**Comment by janpio** [comment] 2020-09-22 14:08
We investigated by trying to run our current test suite on CockroackDB. This is what our developer commented:

> Got the tests to run in CI and they failed; it seems pretty clear there are implementation differences between Postgres and Cockroach. This means this is as far as Engineering can take it for now, and it's up to Product to decide if and how we would want to support Cockroach.

_Originally posted by @yoshuawuyts in https://github.com/prisma/prisma-engines/issues/900#issuecomment-696735967_

**Comment by vy-ton** [comment] 2020-09-22 16:21
> it's up to Product to decide if and how we would want to support Cockroach

Hi, as mentioned above, I'm a product manager for CockroachDB. Please let me know if the Prisma Product/Engineering team has any further questions as they consider adding CockroachDB support to their roadmap. The CockroachDB team is very interested in collaborating to add support.

**Comment by gogoout** [comment] 2020-12-14 00:54
I've tried a bit on running CockroachDB with Prisma, the query side seems so far so good. Introspect is not working due to the following errors:
```
IntrospectionEngine:stderr {"is_panic":true,"message":"[libs/sql-schema-describer/src/getters.rs:21:14] called `Result::unwrap()` on an `Err` value: \"Getting is_identity from Resultrow ResultRow { columns: [\\\"table_name\\\", \\\"column_name\\\", \\\"formatted_type\\\", \\\"numeric_precision\\\", \\\"numeric_scale\\\", \\\"numeric_precision_radix\\\", \\\"datetime_precision\\\", \\\"data_type\\\", \\\"full_data_type\\\", \\\"column_default\\\", \\\"is_nullable\\\", \\\"is_identity\\\", \\\"data_type\\\", \\\"character_maximum_length\\\"], values: [Text(Some(\\\"uvdb_aspirations\\\")), Text(Some(\\\"id\\\")), Text(Some(\\\"bigint\\\")), Integer(Some(64)), Integer(Some(0)), Integer(Some(2)), Integer(None), Text(Some(\\\"bigint\\\")), Text(Some(\\\"int8\\\")), Text(Some(\\\"nextval(\\\\\\'uvdb_aspirations_auto_inc\\\\\\':::STRING)\\\")), Text(Some(\\\"NO\\\")), Text(None), Text(Some(\\\"bigint\\\")), Integer(None)] } as String failed\"","backtrace":"   0: backtrace::backtrace::trace\n   1: backtrace::capture::Backtrace::new\n   2: user_facing_errors::Error::new_in_panic_hook\n   3: user_facing_errors::panic_hook::set_panic_hook::{{closure}}\n   4: std::panicking::rust_panic_with_hook\n   5: std::panicking::begin_panic_handler::{{closure}}\n   6: std::sys_common::backtrace::__rust_end_short_backtrace\n   7: _rust_begin_unwind\n   8: core::panicking::panic_fmt\n   9: core::option::expect_none_failed\n  10: <quaint::connector::result_set::result_row::ResultRow as sql_schema_describer::getters::Getter>::get_expect_string\n  11: <sql_schema_describer::postgres::SqlSchemaDescriber as sql_schema_describer::SqlSchemaDescriberBackend>::describe::__describe::{{closure}}::{{closure}}\n  12: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll\n  13: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll\n  14: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll\n  15: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll\n  16: <futures_util::compat::compat03as01::Compat<Fut> as futures::future::Future>::poll\n  17: <futures::future::map::Map<A,F> as futures::future::Future>::poll\n  18: <futures::future::either::Either<A,B> as futures::future::Future>::poll\n  19: <futures::future::lazy::Lazy<F,R> as futures::future::Future>::poll\n  20: futures::future::chain::Chain<A,B,C>::poll\n  21: <futures::future::then::Then<A,B,F> as futures::future::Future>::poll\n  22: <futures::future::map::Map<A,F> as futures::future::Future>::poll\n  23: <futures::future::either::Either<A,B> as futures::future::Future>::poll\n  24: <futures::future::map::Map<A,F> as futures::future::Future>::poll\n  25: futures::task_impl::std::set\n  26: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll\n  27: tokio::runtime::thread_pool::ThreadPool::block_on\n  28: tokio::runtime::context::enter\n  29: tokio::runtime::Runtime::block_on\n  30: introspection_engine::main\n  31: std::sys_common::backtrace::__rust_begin_short_backtrace\n  32: std::rt::lang_start::{{closure}}\n  33: std::rt::lang_start_internal\n  34: _main\n"}
```
And seems it's due to some of the info is unimplemented on CockroachDB side: https://github.com/cockroachdb/cockroach/blob/53b08837cf5e76504e437bad80c97e05989d2c60/pkg/sql/information_schema.go#L470

**Comment by avetisk** [comment] 2021-01-26 17:40
This is definitively something I would love to see!

Esp. knowing that TypeORM is supporting it...👀

**Comment by janpio** [comment] 2021-03-23 18:47
Note for future testing attempts:
https://github.com/prisma/prisma-engines/pull/1024/files
https://github.com/prisma/engineer/pull/16/files
https://github.com/cockroachlabs-field/docker-examples/blob/master/example-single-node/docker-compose.yml

**Comment by JuniorDEVed** [comment] 2021-06-30 10:21
Does anyone know if cockroach is supported yet?

**Comment by VinayaSathyanarayana** [comment] 2021-07-14 08:21
Any updates on this?

**Comment by janpio** [comment] 2021-07-14 09:16
Very rough summary:
- You can currently not use Prisma Migrate and Introspection with CockroachDB as it behaves different than PostgreSQL.
- You can most probably use Prisma Client (and Query Engine) with a CockroachDB database (both hosted locally or in the Cloud). You just need to create a Prisma schema of the database schema (either by writing it by hand, or introspecting the same schema on a plain PostgreSQL database for example). There might be bugs and problem though that we do not know about yet, as it is not a fully supported database we test and try to find bugs actively. But we have users doing exactly that who are pretty happy.

**Comment by janpio** [comment] 2021-09-17 11:24
If you want play with [Cockroach Cloud](https://cockroachlabs.cloud/) despite the incompatibilities mentioned above, please not that the "Connection String" in the "Connect" modal will not work. Go to "Connection parameters" instead and construct the connection string manually from that. (Note the different "database name" that also includes information about the cluster, vs. how it is a param to the provided connection string)

**Comment by bezreyhan** [comment] 2021-09-17 16:49
Is there a roadmap or timeline to support Cockroach?

**Comment by matthewmueller** [comment] 2021-11-30 21:54
Just a note: I've removed the milestone here, but rest assured, we're actively working on supporting CockroachDB and we're tracking the work in [this epic](https://github.com/prisma/prisma/issues/10491), which contains more specific issues with milestones.

**Comment by floelhoeffel** [comment] 2022-02-08 13:34
Duplicate of #10491 

As of `3.9.0` we released a dedicated cockroachdb connector with support for introspection. Migrations support follows.

**Closed by floelhoeffel** 2022-02-08 13:34 UTC
Labels: kind/feature, topic: connector, team/migrations, team/client, topic: cockroachdb
