### ISSUE TITLE
called `Option::unwrap()` on a `None` value

### ISSUE THREAD

**Issue by teddylimecommerce** [prisma/prisma#23922] opened 2024-04-23 05:46 UTC
Hi Prisma Team! My Prisma Client just crashed. This is the report:
## Versions

| Name            | Version            |
|-----------------|--------------------|
| Node            | v18.18.2           | 
| OS              | debian-openssl-3.0.x|
| Prisma Client   | 4.9.0              |
| Query Engine    | ceb5c99003b99c9ee2c1d2e618e359c14aef2ea5|
| Database        | mysql              |

## Logs
```
prisma:tryLoadEnv Environment variables loaded from /mnt/data/stagingapi/.env
prisma:tryLoadEnv Environment variables loaded from /mnt/data/stagingapi/.env
prisma:client dirname /mnt/data/stagingapi/node_modules/.prisma/client
prisma:client relativePath ../../../prisma
prisma:client cwd /mnt/data/stagingapi/prisma
prisma:client clientVersion 4.9.0
prisma:client clientEngineType library
prisma:client:libraryEngine internalSetup
prisma:get-platform Command "uname -m" successfully returned "x86_64
"
prisma:get-platform Trying platform-specific paths for "debian" (and "ubuntu")
prisma:get-platform Command "ls /usr/lib/x86_64-linux-gnu | grep libssl.so" successfully returned "libssl.so.3
"
prisma:get-platform Found libssl.so file using platform-specific paths: libssl.so.3

prisma:get-platform The parsed libssl version is: 3.0.x
prisma:get-platform Command "uname -m" successfully returned "x86_64
"
prisma:get-platform Trying platform-specific paths for "debian" (and "ubuntu")
prisma:get-platform Command "ls /usr/lib/x86_64-linux-gnu | grep libssl.so" successfully returned "libssl.so.3
"
prisma:get-platform Found libssl.so file using platform-specific paths: libssl.so.3

prisma:get-platform The parsed libssl version is: 3.0.x
prisma:get-platform Command "uname -m" successfully returned "x86_64
"
prisma:get-platform Trying platform-specific paths for "debian" (and "ubuntu")
prisma:get-platform Command "ls /usr/lib/x86_64-linux-gnu | grep libssl.so" successfully returned "libssl.so.3
"
prisma:get-platform Found libssl.so file using platform-specific paths: libssl.so.3

prisma:get-platform The parsed libssl version is: 3.0.x
prisma:client:libraryEngine:loader Searching for Query Engine Library in /mnt/data/stagingapi/node_modules/.prisma/client
prisma:client:libraryEngine:loader loadEngine using /mnt/data/stagingapi/node_modules/.prisma/client/libquery_engine-debian-openssl-3.0.x.so.node
prisma:client:libraryEngine library starting
prisma:client:libraryEngine library started
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
```

## Client Snippet
```ts
// PLEASE FILL YOUR CODE SNIPPET HERE
```

## Schema
```prisma
// PLEASE ADD YOUR SCHEMA HERE IF POSSIBLE
```

## Prisma Engine Query
```
{"X":{}}
```

**Comment by Weakky** [comment] 2024-04-24 09:00
Hey @teddylimecommerce,

Would you mind sharing any additional information so that we can reproduce your issue? Your datamodel and some Prisma Client query that reproduces this bug is capital for us to work on the issue.

Thank you! 🙏

**Comment by SevInf** [comment] 2024-05-03 09:30
Hey @teddylimecommerce  ,

Did you get a chance to have a look at my collegues comment? It'd be helpful for us to move your issue forward.

Without further information, we'll have to close this issue. Thank you 🙏

**Comment by jkomyno** [comment] 2024-05-17 12:13
Hi @teddylimecommerce, since we got no reply with information that could help us reproducing this issue, we're closing this issue.
Should you or another user bump into the same problem and provide a reproduction, we will consider reopening this issue. Thanks!

**Closed by jkomyno** 2024-05-17 12:13 UTC
Labels: bug/0-unknown, kind/bug, tech/engines, tech/engines/query engine, team/client
