### ISSUE TITLE
DELETE RETURNING clause in PostgreSQL

### ISSUE THREAD

**Issue by Abdel-Monaam-Aouini** [prisma/prisma#19134] opened 2023-05-08 09:30 UTC
![image](https://user-images.githubusercontent.com/52112750/236789001-ea2d6db1-2754-4ab9-8b13-717a96951f5e.png)
![image](https://user-images.githubusercontent.com/52112750/236789070-f42b88ba-8b1a-4b45-9fc9-a6024e276ec9.png)
In your code, you can process the returned rows in the same way as you would process the results of an SQL query. For example, you may log the data that have been deleted.

`deleteMany`

**Comment by Jolg42** [comment] 2023-05-09 08:13
Thanks @Abdel-Monaam-Aouini for this issue!

It looks like a duplicate of https://github.com/prisma/prisma/issues/13596, so I'll close it.

Feel free to follow that issue and comment there with the use case that you are interested in.

**Closed by Jolg42** 2023-05-09 08:13 UTC
