### ISSUE TITLE
Rename the following items: - "model Transaction" after upgrade from 2.1 to 2.2

### ISSUE THREAD

**Issue by aarshaw** [prisma/prisma#3049] opened 2020-07-17 06:19 UTC
The schema contains the model "Transaction" - this was fine in `2.1.3` but after upgrading to `2.2.2`  - we're now receiving the following error:

```
Error: 
Error: The schema at "/Users/aaron/Desktop/Ember/prisma/schema.prisma" contains reserved keywords.
       Rename the following items:
         - "model Transaction"
To learn more about how to rename models, check out https://pris.ly/d/naming-models
```

Feels like it could have something to do with the `transactionsApi` - is this expected?

**Comment by janpio** [comment] 2020-07-18 22:24
Yes, that is indeed a side effect we are currently discussing internally as well.

Does this happen both with the `transactionsApi` feature flag enabled and disabled?

**Comment by aarshaw** [comment] 2020-07-20 09:01
We don't have the `transactionsApi` enabled. Was this expected? Feels like a breaking change...

**Comment by pantharshit00** [comment] 2020-07-20 12:48
We are exploring how we want to deal with new client methods in a non breaking way. Please disable the experiment for now if this is breaking for you.

You can also do this if you want keep the name in the database for now:
```prisma
model _Transaction {
// fields here
@@map("Transaction")
}
```

This is really a duplicate of https://github.com/prisma/prisma-engines/issues/892#issuecomment-656141929 but I will keep this open here as that repository is rarely searched by our users.

**Comment by janpio** [comment] 2020-07-20 18:34
As it turns out the denylist was not behind the feature flag @pantharshit00 - so this is a very different bug. It hsould not have affected @aarshaw without enabling the feature flag which he did not do.

**Closed** 2020-07-21 09:58 UTC
Labels: bug/2-confirmed, kind/bug, topic: experimentalFeatures, topic: transactionApi
