### ISSUE TITLE
Env variables from same folder as schema file not loaded anymore when sharing a schema file with multiple clients

### ISSUE THREAD

**Issue by woondossier** [prisma/prisma#20456] opened 2023-07-31 12:29 UTC
### Bug description

We have three applications in different folders using the same database, so we share the schema file between these three by setting the path in the package.json for two of them. 

Before updating to Prisma 5, the prisma clients would load the shared .env file in the same folder as the shared schema file but now they don't do that anymore.

But when I try to generate etc something from the CLI it does include it and complains about "duplicate data that's different"

### How to reproduce

1. define path to different folder with schema file in package.json
2. generate client
3. copy client to other folders node_modules/.primsa folder so they all have it
4. start program and it will complain about the DATABASE_URL env missing because it's not loaded from the schema folder.

### Expected behavior

Prisma should load the shared .env because now I need to comment/uncomment the entries every time I want to do something

### Prisma information

```prisma
// Add your schema.prisma
```

```ts
// Add your code using Prisma Client
```

### Environment & setup

- OS: Windows
- Database: MariaDB
- Node.js version: 18.16.0

### Prisma Version

```
Environment variables loaded from .env
Environment variables loaded from ..\prisma\.env
prisma                  : 5.0.0
@prisma/client          : 5.0.0
Current platform        : windows
Query Engine (Node-API) : libquery-engine 6b0aef69b7cdfc787f822ecd7cdc76d5f1991584 (at node_modules\@prisma\engines\query_engine-windows.dll.node)
Schema Engine           : schema-engine-cli 6b0aef69b7cdfc787f822ecd7cdc76d5f1991584 (at node_modules\@prisma\engines\schema-engine-windows.exe)
Schema Wasm             : @prisma/prisma-schema-wasm 4.17.0-26.6b0aef69b7cdfc787f822ecd7cdc76d5f1991584
Default Engines Hash    : 6b0aef69b7cdfc787f822ecd7cdc76d5f1991584
Studio                  : 0.487.0

```

**Comment by Jolg42** [comment] 2023-08-09 09:46
The CLI is showing:
```
Environment variables loaded from .env
Environment variables loaded from ..\prisma\.env
```
So it looks like it loads env vars from 2 different paths.

**Comment by Jolg42** [comment] 2023-08-09 09:46
For me this step is unexpected: "copy client to other folders node_modules/.prisma folder so they all have it", what are you doing here and why?

**Comment by Jolg42** [comment] 2023-08-09 09:48
@woondossier We would need help to reproduce this.

- What's the version that was working before?  
- Did you try using `4.16.2` (last version before v5)?
- Add an example for the Prisma Schema
- Provide the commands you are running in "how to reproduce"
- Try using `DEBUG=prisma*` when running your script to see which .env files are used by Prisma Client
- Provide logs for the version before and after so we can compare.
- Which package manager are you using?

**Comment by janpio** [comment] 2023-10-29 21:24
Did you see Joel's message @woondossier? We need your help here. Thanks.

**Comment by millsp** [comment] 2023-11-07 01:08
Hey @woondossier, without your input we cannot move this issue forward, so I am closing it. Please provide us with the missing information so we understand how to treat this, and we will happily re-open it.

**Closed by millsp** 2023-11-07 01:08 UTC
Labels: bug/0-unknown, kind/bug, topic: env, team/client
