### ISSUE TITLE
Json filtering `array_contains` doesn't match string partially in string array.

### ISSUE THREAD

**Issue by cody-ta** [prisma/prisma#18621] opened 2023-04-04 08:44 UTC
### Bug description

JSON data example:
```json
{
	"status": "ready",
	"data": ["This is a string", "Another string"]
}
```

### Using `string_contains`:
```ts
where: {
	json_field: {
		path: ["status"],
		string_contains: "ead", // this what "contains" means.
	},
},
```
✅ match.

### Using `array_contains`:
```ts
where: {
	json_field: {
		path: ["data"],
		array_contains: ["This is a string"],  // this should be array_equals
	},
},
```
✅ match.

```ts
where: {
	json_field: {
		path: ["data"],
		array_contains: ["Another string"],  // this should be array_equals
	},
},
```
✅ match.

but

```ts
where: {
	json_field: {
		path: ["data"],
		array_contains: [" string"],  // doesn't even the entry in string array contains "string"
	},
},
```
🚫 doesn't match anything.

### How to reproduce

Use query like shown.

### Expected behavior

```ts
prisma.document_files.findFirst({
	where: {
		json_field: {
			path: ["data"],
			array_contains: [" string"], // doesn't even the entry in string array contains "string"
		},
	},
});
```

### Prisma information

```prisma
model document_files {
  json_field Json?           @db.Json
}
```

```ts
prisma.document_files.findFirst({
	where: {
		json_field: {
			path: ["data"],
			array_contains: "string", // 
		},
	},
});
```

### Environment & setup

- OS: MacOS
- Database: PostgreSQL
- Node.js version: 18

### Prisma Version

```
v4.12.0
```

**Comment by alvis** [comment] 2023-10-03 14:48
I disagree that `array_contains: "string"` should return any match.
`array_contains` implies an exact equal, so the current implementation is right.

However, I'd argue the following should return a match
```ts
prisma.document_files.findFirst({
  where: {
    json_field: {
      path: ["data"],
      string_contains: "string",
    },
  },
});
```

**Comment by Weakky** [comment] 2024-08-08 09:59
Hey @cody-ta and @alvis, this is expected behavior. Even what you posted @alvis is not expected to work by design. Your path points to an array but you use the `string_*` operators. This will yield nothing. If anything, this issue should be converted to a feature request.
If you still need this feature, please open another issue. For now though, I'm closing this one. Thanks for the report anyway 🙏

**Closed by Weakky** 2024-08-08 09:59 UTC
Labels: bug/1-unconfirmed, kind/bug, domain/client
