### ISSUE TITLE
Real-time updates eg. streamlistener

### ISSUE THREAD

**Issue by jimodelid** [prisma/prisma#4766] opened 2020-12-22 09:30 UTC
## Problem
Out of the box there does not seem to be a function for the topic using Prisma. I believe it would increase the UX and coding experience by a great deal seeing as how we need to reload the page to see the new DB items added or add a bunch of Ajax code to bloat the app pretty much everywhere we want the functionality.

I would see this function shine especially for comments for products and blog posts, any comments in general, chat services, and similar areas where users communicate or expect information in real-time.

## Suggested solution
Adding some sort of stream listener to easily add the live reload to specific DB connections so the data added is shown for all users/visitors in real time without a page  reload.

Example, I know the syntax is not 100%:
`prisma.product.streamlistener.findMany({“get latest 10”})`

So if a user then add a total of 11 products in the example it will automatically hide the first product and display products 2-11 for everyone on the site without a page reload.

## Alternatives
The only alternative I see is using another service that already supports this or adding Ajax everywhere as mentioned above.

## Additional context
Google Firebase/Firestore has similar functionality where they use streamlistener to push data to users when the database sense a entry change if the programmer has added the streamlistener to the DB function in the app, it might be a good place to fish for information to achieve possible solutions.

Thanks in advance!
Kind regards
Jim

**Comment by pantharshit00** [comment] 2020-12-22 15:11
Related even possibly a duplicate of https://github.com/prisma/prisma/issues/298

**Comment by TasinIshmam** [comment] 2022-11-07 16:24
Hi folks 👋, 

Tasin from Prisma here. 

We are launching a [Design Partner Program](https://prismaio.notion.site/Prisma-Design-Partner-Program-a286c25e47fb44e199038ca71dce36a1) where external teams can collaborate with us to shape Prisma's future. In this program, we will collaborate with you on defining solutions to the following problems: 

- **Listening and reacting to database changes in real-time**
- Data projections for denormalization or data integration purposes
- Caching
- Serverless workflow orchestration

**If you’re struggling with subscriptions/real-time functionality, especially in a serverless environment, you might be a great fit for this program!**  Your team can take advantage of new Prisma features that you won’t have to build or maintain yourselves. As you invest time in partnering with us, we will also offer you free credits once anything coming out of this program reaches production.

**You can [check out the program in more detail](https://prismaio.notion.site/Prisma-Design-Partner-Program-a286c25e47fb44e199038ca71dce36a1) to see the kinds of activities we’re planning. To apply to this program, [fill out the form](https://docs.google.com/forms/d/e/1FAIpQLSdfadMO7qVOMlOgmeYevpM-olpjku2-3sVzMvVQiHITmZf4dA/viewform)**.

We’re looking forward to hearing from you!

**Comment by janpio** [comment] 2024-01-15 22:10
Closing this now, as I think it is better and adequately represented by #298. Thanks for opening it back in the day!

**Closed by janpio** 2024-01-15 22:10 UTC
Labels: kind/feature, team/client, topic: realtime
