### ISSUE TITLE
Query engine binary could not be found on netlify deployment with Next

### ISSUE THREAD

**Issue by s-kris** [prisma/prisma#6051] opened 2021-03-10 17:16 UTC
## Bug description
```
Query engine binary for current platform "rhel-openssl-1.0.x" could not be found. This probably happens, because you built Prisma Client on a different platform. (Prisma Client looked in "/query-engine-rhel-openssl-1.0.x") Searched Locations: /.prisma/client /opt/build/repo/node_modules/@prisma/client / /var/task/node_modules/.prisma/client /var/task /var/task/node_modules/.prisma/client You already added the platforms "native", "rhel-openssl-1.0.x", "darwin" to the "generator" block in the "schema.prisma" file as described in https://pris.ly/d/client-generator, but something went wrong. That's suboptimal. Please create an issue at https://github.com/prisma/prisma-client-js/issues/new
```

**Note:**
checked the following:
https://github.com/netlify/zip-it-and-ship-it/issues/81  
https://github.com/prisma/prisma/issues/1015 
https://github.com/netlify/build/issues/730#issuecomment-615177926

## How to reproduce
Deploy a simply nextjs + prisma app to netlify 

## Expected behavior
Prisma client should do CRUD as usually. 

## Prisma information
```prisma
generator client {
  provider = "prisma-client-js"
  binaryTargets = ["native", "rhel-openssl-1.0.x", "darwin"]
  previewFeatures = ["createMany"]
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}
```

## Environment & setup

- OS:  Netlify 
- Database: Postgres
- Node.js version: 12.18.0
- Prisma version: 2.18.0

**Comment by janpio** [comment] 2021-03-10 17:28
Did you read and follow https://www.prisma.io/docs/guides/deployment/deploying-to-netlify?

**Comment by s-kris** [comment] 2021-03-10 17:44
Yes, I did.

**Comment by laugharn** [comment] 2021-03-10 21:10
Did you set your target in next.config.js to experimental-serverless-trace? Source: https://github.com/netlify/next-on-netlify#1-set-nextjs-target-to-serverless

**Comment by s-kris** [comment] 2021-03-11 01:44
That plugin is deprecated now. And the new plugin needs zero config.

But I already tried manual config and with experimental serverless trace, the build is failing with dependency error.

**Comment by s-kris** [comment] 2021-03-11 13:15
The build fails even after adding the babel/core dependency as mentioned in the error.

**Comment by s-kris** [comment] 2021-03-13 19:34
Minimal repo https://github.com/s-kris/test-prisma-netlify

**Comment by pantharshit00** [comment] 2021-03-18 11:12
I wasn't able to reproduce this error message but I was able to reproduce a webpack error with this setup deployed here: https://reverent-jennings-0639a0.netlify.app/api/prisma-test

We might need to send patch to netlify plugin like we have some code in vercel nft for the engines.

**Comment by s-kris** [comment] 2021-03-18 12:54
repo: https://github.com/s-kris/test-prisma-netlify

hey @pantharshit00 looks like `Query engine binary` is with `2.18.0`
Link: https://cocky-babbage-06fac3.netlify.app/api/prisma-test
branch: master

I'm able to reproduce the `TypError: Debug lib is not a function` with `2.19.0` 
Link: https://60533b09c4bfae0007861e2c--cocky-babbage-06fac3.netlify.app/api/prisma-test 
branch: p2.19
 

Thanks for your time :)

**Comment by pantharshit00** [comment] 2021-03-19 06:38
It is reproducible, we will patch it or document a workaround. Stay tuned.

**Comment by jhackett1** [comment] 2021-03-22 15:29
also having this issue with a [next.js app deployed to netlify](https://github.com/jhackett1/railsy-nextjs-prisma-example). 

are we any closer to a resolution or workaround?

**Comment by s-kris** [comment] 2021-03-24 15:22
As @jhackett1 mentioned, the deploy (two branches) works on vercel perfectly. (both `2.18.0` and `2.19.0`)
https://github.com/s-kris/test-prisma-netlify

**Comment by meotimdihia** [comment] 2021-03-25 03:03
> repo: https://github.com/s-kris/test-prisma-netlify
> 
> hey @pantharshit00 looks like `Query engine binary` is with `2.18.0`
> Link: https://cocky-babbage-06fac3.netlify.app/api/prisma-test
> branch: master
> 
> I'm able to reproduce the `TypeError: debugLib is not a function` with `2.19.0`
> Link: https://60533b09c4bfae0007861e2c--cocky-babbage-06fac3.netlify.app/api/prisma-test
> branch: p2.19
> 
> Thanks for your time :)
```
 Build error occurred
TypeError: debugLib is not a function
```
this error is happening on localhost Windows 10 too.

**Comment by gavrichards** [comment] 2021-03-26 09:39
I've had `TypeError: debugLib is not a function ` happening locally. Next.js (latest version), macOS. Downgrading Prisma to `2.18.0` fixed it.

**Comment by janpio** [comment] 2021-03-26 18:20
We have an idea what might be going on and are investigating.

**Comment by timsuchanek** [comment] 2021-03-30 09:54
Thanks everyone, in the latest dev version, we fixed the `debugLib is not a function` problem.
It'll get released in `2.20.0` today.

The original error reported in this issue `binary for current platform "rhel-openssl-1.0.x" could not be found` is not fixed by this though. We will continue investigating that next sprint.

**Comment by gavrichards** [comment] 2021-03-30 17:17
Confirmed `TypeError: debugLib is not a function` is no longer happening. Thanks for the fix!

**Comment by jhackett1** [comment] 2021-04-03 21:21
i seem to still be getting the original issue on version `2.20.1` :(


```
https://next-auth.js.org/errors#get_user_by_provider_account_id_error PrismaClientInitializationError2 [PrismaClientInitializationError]: Query engine binary for current platform "rhel-openssl-1.0.x" could not be found.
This probably happens, because you built Prisma Client on a different platform.
(Prisma Client looked in "/query-engine-rhel-openssl-1.0.x")

Searched Locations:

  /.prisma/client
  /opt/build/repo/node_modules/@prisma/client
  /
  /var/task/node_modules/.prisma/client
  /var/task
  /var/task/node_modules/.prisma/client

You already added the platforms "native", "rhel-openssl-1.0.x" to the "generator" block
in the "schema.prisma" file as described in https://pris.ly/d/client-generator,
but something went wrong. That's suboptimal.

Please create an issue at https://github.com/prisma/prisma/issues/new
    at cb (/var/task/src/nextPage/index.js:116764:17) {
  clientVersion: '2.20.1',
  errorCode: undefined
}
```

**Comment by s-kris** [comment] 2021-04-04 02:15
@jhackett1 it's actually one step backwards, haha.
@timsuchanek mentioned above that they will look into this in the next sprint. Probably by April 13th as per the  milestone, we should get a solution.

**Comment by webnoob** [comment] 2021-04-05 13:09
I'm not using netlify and am getting this issue:

```
14:06:03 - Found 0 errors. Watching for file changes.
C:\SourceCode\proj\node_modules\.prisma\client\index.js:21
const debug = debugLib('prisma-client')
              ^

TypeError: debugLib is not a function
    at Object.<anonymous> (C:\SourceCode\proj\node_modules\.prisma\client\index.js:21:15)
    at Module._compile (internal/modules/cjs/loader.js:956:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
    at Module.load (internal/modules/cjs/loader.js:812:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Module.require (internal/modules/cjs/loader.js:849:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (C:\SourceCode\proj\node_modules\@prisma\client\index.js:1:16)
    at Module._compile (internal/modules/cjs/loader.js:956:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
```

**Comment by webnoob** [comment] 2021-04-14 06:49
Any news / movement on this issue? I need to upgrade to 2.20 but am being held back by the fact it just doesn't work...

**Comment by pantharshit00** [comment] 2021-04-14 12:21
@webnoob Can you try with 2.21 once?

**Comment by webnoob** [comment] 2021-04-14 12:25
> @webnoob Can you try with 2.21 once?

On it.

**Comment by webnoob** [comment] 2021-04-14 12:29
@pantharshit00 Exact same error:

```
C:\SourceCode\proj\node_modules\.prisma\client\index.js:21
const debug = debugLib('prisma-client')
              ^

TypeError: debugLib is not a function
    at Object.<anonymous> (C:\SourceCode\proj\node_modules\.prisma\client\index.js:21:15)
    at Module._compile (internal/modules/cjs/loader.js:956:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
    at Module.load (internal/modules/cjs/loader.js:812:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Module.require (internal/modules/cjs/loader.js:849:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (C:\SourceCode\proj\node_modules\@prisma\client\index.js:1:16)
    at Module._compile (internal/modules/cjs/loader.js:956:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
```

**Comment by webnoob** [comment] 2021-04-14 12:34
Ok, completely deleting node_modules / yarn.lock seems to have resolved it!

**Comment by Jolg42** [comment] 2021-04-14 12:41
@webnoob since this issue is about `Query engine binary could not be found on netlify deployment` I will mark the `debugLib is not a function` messages off topic to keep the issue clean.

Glad you're unblocked!

**Comment by bmcilw1** [comment] 2021-04-22 16:39
Is there a way to force specify the path for the query engine binary? My binary is there, just not in one of the paths its looking for. Seems like by allowing us to control where the path is looking we should be able to avoid a ton of these problems with "can't find query engine" stuff.

**Comment by millsp** [comment] 2021-05-03 09:22
Netlify's bundling tool `zip-it-and-ship-it` includes your dependency files into the zip file by looking at your imports. Since `next` rewrites all imports with `webpack`, `zip-it-and-ship-it` will not see the import and files such as binaries won't be bundled. Netlify is working on a general solution for these kind of issues, but without any concrete date yet. I propose this workaround, where we simply exclude `@prisma/client` from being bundled:

*next.config.js*
```ts
module.exports = {
    webpack: (config, { isServer } ) => {
        if (isServer) {
            config.externals.push('@prisma/client')
        }

        return config
    },
    target: "serverless"
}
```

**Comment by matthewmueller** [comment] 2021-06-14 13:32
Can someone confirm that marking `@prisma/client` as external fixes the problem of deploying a Next.js + Prisma app on Netlify?

**Comment by matthewmueller** [comment] 2021-06-14 14:14
Just to recap since it took me awhile:

The problem is that webpack is removing import `@prisma/client` so `zip-it-and-ship-it` can't find that import. Because it can't find that import, it doesn't know how to link the binaries.

So the solution is:
- Marking it as external prevents webpack from mangling the `@prisma/client`  import
- `zip-it-and-ship-it` can then discover `@prisma/client` and add the binaries to the zip.

I'm going to close this one since there's not much more we can do on our side. I've [opened a docs issue](https://github.com/prisma/docs/issues/1879) to get this documented. Thanks everyone!

**Closed** 2021-06-14 14:18 UTC
Labels: bug/2-confirmed, kind/bug, team/client, topic: binary, topic: prisma-client
