### ISSUE TITLE
Prisma Migrate Reset without exectung seed script

### ISSUE THREAD

**Issue by BjoernRave** [prisma/prisma#5372] opened 2021-01-31 18:14 UTC
I would like to be able to run `prisma migrate reset --preview-feature` without running the seed script. Ideally I could add a flag to disable it. 

The reason is, that I plan to use `prisma migrate reset --preview-feature -f` as part of my CI process, where I want to handle seeding by myself

**Comment by pantharshit00** [comment] 2021-02-01 12:06
Hi,

Thanks for reporting this! It has already been reported before, so I am going to close this as a duplicate of https://github.com/prisma/prisma/issues/5317

**Closed by pantharshit00** 2021-02-01 12:06 UTC
