### ISSUE TITLE
Prisma Cloud and managementApiSecret incompatible? 

### ISSUE THREAD

**Issue by danielmahon** [prisma/prisma#2955] opened 2018-08-22 16:55 UTC
**Describe the bug**
After following the tutorial for installing the prisma server on Digital Ocean via docker-machine`prisma deploy` fails with `ERROR: Authentication token is invalid: Token can't be decoded: Invalid signature for this token or wrong algorithm.` when trying to redeploy to existing service. It also only seems to happen when logged in to prisma cloud via the cli and `config.yml` contains the cloud key. If I run `prisma logout` and make sure `config.yml` is reset to `clusters: {}` I don't get the error anymore...

**To Reproduce**
1. Set `managementApiSecret` in `docker-compose.yml`
2. Set  `PRISMA_MANAGEMENT_API_SECRET` in `.env`
3. Run `docker-compose up -d`
4. Run `prisma login`
5. Run `prisma deploy`

**Expected behavior**
I expect `prisma deploy` to use the proper secret to access the server.

**Versions (please complete the following information):**
 - OS: `OS X High Sierra`
 - `prisma` CLI: prisma/1.14.2 (darwin-x64) node-v8.11.3
 - Prisma Server: 1.14.2

**Additional context**

**Comment by abhiaiyer91** [comment] 2018-08-22 17:01
Hey there @danielmahon! After adding setting the managment secret, did you re `docker-compose up` to your droplet?

**Comment by danielmahon** [comment] 2018-08-22 17:03
@abhiaiyer91 yes, I forgot to add it to the steps however

**Comment by danielmahon** [comment] 2018-08-22 17:25
Yea it doesn't seem to be doing much anymore, but it does seem to hold the CLOUD KEY when you run `prisma login`. And for whatever the reason, if that key is there, `prisma deploy` fails for me.

**Comment by marktani** [comment] 2018-08-22 18:45
@danielmahon is the server connected to your Prisma Cloud account or not?

**Comment by danielmahon** [comment] 2018-08-22 18:48
@marktani Yes, but I want to say I tried it after removing the server from Prisma Cloud as well (though I could be wrong).

**Comment by abhiaiyer91** [comment] 2018-08-23 13:56
@danielmahon I went through the docker machine tutorial, following your steps and was unable to reproduce the deploy issue.

Is there a chance when running prisma deploy that your .env file was not applied?

**Comment by ZakSingh** [comment] 2018-08-30 02:38
Exact same issue here, but I'm using AWS Fargate.

**Comment by danielmahon** [comment] 2018-08-30 13:51
Just updated to `1.15.1` and same issue. Server was already in cloud, upgraded remote machine and cli to `1.15.1`. Successfully run `prisma deploy`. Then ran `prisma login`. Logged in. Tried `prisma deploy` again and it failed with same error. Ran `prisma logout`, and then `prisma deploy` works again.

**Comment by marktani** [comment] 2018-10-19 11:40
> If I run prisma logout and make sure config.yml is reset to clusters: {} I don't get the error anymore

This is the expected configuration anyway. As this issue is due to an incorrect configuration, I'll close this error.

**Closed by marktani** 2018-10-19 11:40 UTC
Labels: component/cloud-api, kind/bug, reproduction-available
