### ISSUE TITLE
Using findUnique on 4.8.0 with nested `where` and `include` produces an object that doesn't include entities you specify in `include`

### ISSUE THREAD

**Issue by TenkoSpirit** [prisma/prisma#17030] opened 2022-12-27 12:35 UTC
### Bug description

When I use `findUnique` and specify `where` condition values for a multi column unique constraint and specify data to `include`, the resulting object will produce all the data but the types are going to be wrong and typescript will not show the data I specified in my `include`. If anyone could come up with a better wording, please, let me know! :D

This issue was not present in 4.7.1 but was introduced in 4.8.0

### How to reproduce

Use findUnique() and provide it with `where` and `include`, `where` must depend on multi column unique constraint.

### Expected behavior

The resulting object must contain data I specified in `include`

### Prisma information

Schema can be found [here](https://github.com/TenkoSpirit/genshin.academy/blob/78ea9a42b8618a1ac668ec8ba24b536924768fc6/prisma/schema.prisma)

Using Prisma 4.8.0
```ts
const info = await prisma.characterInfo.findUnique({
  where: {
    entryLanguage_characterId: {
      entryLanguage: "en",
      characterId: params.id,
    },
  },
  include: {
    details: {
      include: {
        assets: true,
      },
    },
  },
});

console.log(info?.details);  // Property 'details' does not exist on type 'CharacterInfo'.
```

Using Prisma 4.7.1 this is not happening.

### Environment & setup

- OS: Arch Linux x86_64, kernel 6.1.1-zen1-1-zen
- Database: PostgreSQL 14.6
- Node.js version: v18.12.1

### Prisma Version

```
prisma                  : 4.8.0
@prisma/client          : 4.8.0
Current platform        : debian-openssl-3.0.x
Query Engine (Node-API) : libquery-engine d6e67a83f971b175a593ccc12e15c4a757f93ffe (at node_modules/@prisma/engines/libquery_engine-debian-openssl-3.0.x.so.node)
Migration Engine        : migration-engine-cli d6e67a83f971b175a593ccc12e15c4a757f93ffe (at node_modules/@prisma/engines/migration-engine-debian-openssl-3.0.x)
Introspection Engine    : introspection-core d6e67a83f971b175a593ccc12e15c4a757f93ffe (at node_modules/@prisma/engines/introspection-engine-debian-openssl-3.0.x)
Format Binary           : prisma-fmt d6e67a83f971b175a593ccc12e15c4a757f93ffe (at node_modules/@prisma/engines/prisma-fmt-debian-openssl-3.0.x)
Format Wasm             : @prisma/prisma-fmt-wasm 4.8.0-61.d6e67a83f971b175a593ccc12e15c4a757f93ffe
Default Engines Hash    : d6e67a83f971b175a593ccc12e15c4a757f93ffe
Studio                  : 0.479.0
Preview Features        : fullTextSearch, postgresqlExtensions
Done in 0.42s.
```

**Comment by infix** [comment] 2022-12-30 22:47
Managed to fix this issue will open a PR tomorrow after I update the test cases

**Comment by SevInf** [comment] 2023-01-03 11:30
Hi @infix ! Thanks for the report and the pull request.
In my tests, it seems that the error happens not because `include` types are incorrect, but because generated TS file for this case is invalid. The issue seems to be fixed with #17101. I'll let you know when the fix would be merged and published.

**Comment by infix** [comment] 2023-01-03 13:21
@SevInf great work man, closed my PR. Hopefully this gets merged soon

**Closed** 2023-01-05 11:47 UTC
Labels: bug/1-unconfirmed, kind/bug, kind/regression, topic: prisma-client, topic: client types, tech/typescript, team/client, topic: findUnique

**Comment by SevInf** [comment] 2023-01-05 11:59
Fix will be released in 4.8.1 later today

**Comment by petrbela** [comment] 2023-01-21 14:52
The same error seems to be back in 4.9.0, albeit starting from one nested level down.

```ts
  const meeting = await prisma.meeting.findUnique({
    where: { id: meetingId },
    include: {
      participants: {
        where: { role: 'HOST' }, // it's fine without this line
        include: { user: true },
      },
    },
  })

  meeting?.participants.find((p) => p.user) // <-- property 'user' does not exist
```

**Comment by Mystilund** [comment] 2023-01-23 12:24
Like petrbela, I had a similar problem
![image](https://user-images.githubusercontent.com/1996606/214038463-c5b7302e-a922-455d-91f0-d2ef2927197e.png)

I was using v4.8.0 and it was working, didn't work after upgrading to v4.9.0, I downgraded to v4.8.1 to be sure
Looks like the same issue but if it was working for me with the 4.8.0, it may be a different bug, idk

**Comment by SevInf** [comment] 2023-01-24 10:46
Hi @petrbela and @Mystilund.
Thank you for the report. Even though symptoms might appear to be similar, it does not seem related to this issue. Unfortunately, I was unable to reproduce it with the code snippets you've provided. Would you mind opening a separate issue and filling out the template, including the schema, DB you are using and TS version?

Thank you!
