### ISSUE TITLE
PANIC in libs/prisma-models/src/record.rs:161:30Invalid coercion encountered: ConversionFailure("Float(BigDecimal(\"40\"))", "Decimal")

### ISSUE THREAD

**Issue by jrlim** [prisma/prisma#7997] opened 2021-07-02 08:58 UTC
Hi Prisma Team! My Prisma Client just crashed. This is the report:
## Versions

| Name            | Version            |
|-----------------|--------------------|
| Node            | v14.17.1           | 
| OS              | darwin             |
| Prisma Client   | 2.23.0             |
| Query Engine    | query-engine adf5e8cba3daf12d456d911d72b6e9418681b28b|
| Database        | undefined|

## Query
```
query {
  findManytb_issue_accagepay(where: {
    REG_DATE: {
      gte: "X"
      lte: "X"
    }
    HOS_NM: "X"
  }) {
    REG_DATE
    CUST_ID
    GENDER
    AGE
    HOS_NM
    PAY_CNT
  }
}
```

## Logs
```
;5;78;1mprisma:engine {
  prisma:engine   cwd: '/Users/imjonglyeong/Documents/workspace/med2-backend-rodan/prisma'
  prisma:engine }  
  prisma:engine Search for Query Engine in /Users/imjonglyeong/Documents/workspace/med2-backend-rodan/node_modules/.prisma/client  
  plusX Execution permissions of /Users/imjonglyeong/Documents/workspace/med2-backend-rodan/node_modules/.prisma/client/query-engine-darwin are fine  
  plusX Execution permissions of /Users/imjonglyeong/Documents/workspace/med2-backend-rodan/node_modules/.prisma/client/query-engine-darwin are fine  
  prisma:engine { flags: [ '--enable-raw-queries', '--port', '53091' ] }  
  prisma:engine stdout  Starting a mysql pool with 5 connections.  
  prisma:engine stdout  Started http server on http://127.0.0.1:53091  
  prisma:engine Search for Query Engine in /Users/imjonglyeong/Documents/workspace/med2-backend-rodan/node_modules/.prisma/client  
  plusX Execution permissions of /Users/imjonglyeong/Documents/workspace/med2-backend-rodan/node_modules/.prisma/client/query-engine-darwin are fine  
  prisma:engine Client Version: 2.23.0  +1s
  prisma:engine Engine Version: query-engine adf5e8cba3daf12d456d911d72b6e9418681b28b  
  prisma:engine Active provider: mysql  
  prisma:engine stdout  PANIC in libs/prisma-models/src/record.rs:161:30
Invalid coercion encountered: ConversionFailure("Float(BigDecimal(\"40\"))", "Decimal")  +19s
  prisma:engine {
  prisma:engine   error: SocketError: other side closed
  prisma:engine       at Socket.onSocketEnd (/Users/imjonglyeong/Documents/workspace/med2-backend-rodan/node_modules/@prisma/client/runtime/index.js:25530:24)
  prisma:engine       at Socket.emit (events.js:387:35)
  prisma:engine       at endReadableNT (internal/streams/readable.js:1317:12)
  prisma:engine       at processTicksAndRejections (internal/process/task_queues.js:82:21) {
  prisma:engine     code: 'UND_ERR_SOCKET'
  prisma:engine   }
  prisma:engine }  
  prisma:engine {
  prisma:engine   error: Error: connect ECONNREFUSED 127.0.0.1:53091
  prisma:engine       at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1148:16) {
  prisma:engine     errno: -61,
  prisma:engine     code: 'ECONNREFUSED',
  prisma:engine     syscall: 'connect',
  prisma:engine     address: '127.0.0.1',
  prisma:engine     port: 53091
  prisma:engine   }
  prisma:engine }  
  prisma:engine {
  prisma:engine   cwd: '/Users/imjonglyeong/Documents/workspace/med2-backend-rodan/prisma'
  prisma:engine }  
  prisma:engine Search for Query Engine in /Users/imjonglyeong/Documents/workspace/med2-backend-rodan/node_modules/.prisma/client  
  plusX Execution permissions of /Users/imjonglyeong/Documents/workspace/med2-backend-rodan/node_modules/.prisma/client/query-engine-darwin are fine  +20s
  prisma:engine { flags: [ '--enable-raw-queries', '--port', '53184' ] }  
  prisma:engine stdout  Starting a mysql pool with 5 connections.  
  prisma:engine stdout  Started http server on http://127.0.0.1:53184  
  prisma:engine Search for Query Engine in /Users/imjonglyeong/Documents/workspace/med2-backend-rodan/node_modules/.prisma/client  
  plusX Execution permissions of /Users/imjonglyeong/Documents/workspace/med2-backend-rodan/node_modules/.prisma/client/query-engine-darwin are fine  
  prisma:engine Client Version: 2.23.0  
  prisma:engine Engine Version: query-engine adf5e8cba3daf12d456d911d72b6e9418681b28b  
  prisma:engine Active provider: mysql  
  prisma:engine stdout  PANIC in libs/prisma-models/src/record.rs:161:30
Invalid coercion encountered: ConversionFailure("Float(BigDecimal(\"40\"))", "Decimal")  
  prisma:engine {
  prisma:engine   error: SocketError: other side closed
  prisma:engine       at Socket.onSocketEnd (/Users/imjonglyeong/Documents/workspace/med2-backend-rodan/node_modules/@prisma/client/runtime/index.js:25530:24)
  prisma:engine       at Socket.emit (events.js:387:35)
  prisma:engine       at endReadableNT (internal/streams/readable.js:1317:12)
  prisma:engine       at processTicksAndRejections (internal/process/task_queues.js:82:21) {
  prisma:engine     code: 'UND_ERR_SOCKET'
  prisma:engine   }
  prisma:engine }  
```

## Client Snippet
```ts
this.prisma.tb_issue_accagepay.findMany({
      where: {
        REG_DATE: REG_DATE_CONDITION,
        HOS_NM: hosNm,
      },
    });
```

## Schema
```prisma

model tb_issue_accagepay {
  REG_DATE String   @db.VarChar(8)
  CUST_ID  String   @default("") @db.VarChar(64)
  GENDER   String   @default("") @db.VarChar(1)
  AGE      Decimal  @default(0) @db.Decimal(23, 0)
  HOS_NM   String   @default("") @db.VarChar(100)
  PAY_CNT  Decimal? @db.Decimal(23, 0)

  @@id([REG_DATE, CUST_ID, GENDER, AGE])
}

```

**Comment by pantharshit00** [comment] 2021-07-23 18:02
Hi,

Thanks for reporting this! It has already been reported before, so I am going to close this as a duplicate of https://github.com/prisma/prisma/issues/7580

**Closed by pantharshit00** 2021-07-23 18:02 UTC
