### ISSUE TITLE
Generated columns (MySQL) [Unable to correctly insert into table with `GENERATED` columns]

### ISSUE THREAD

**Issue by Akxe** [prisma/prisma#3001] opened 2020-07-12 09:17 UTC
## Bug description

Prisma does not save information if the column is generated. As such, it will give the user the option to insert value to it. But in case that the generated column is part of the primary key, it begins to be a huge problem.

## How to reproduce

1) Create this (mysql) table:
```sql
CREATE TABLE `example` (
  `idZak` smallint(5) unsigned NOT NULL,
  `idObdobi` smallint(5) unsigned NOT NULL,
  `idSkup` smallint(5) unsigned DEFAULT NULL,
  `idSkupFilled` smallint(5) GENERATED ALWAYS AS (coalesce(`idSkup`,0)) STORED NOT NULL,
  PRIMARY KEY (`idZak`,`idObdobi`,`idSkupFilled`)
  /*CONSTRAINT `vylep_skupina` FOREIGN KEY (`idSkup`) REFERENCES `skupiny` (`idSkup`),CASCADE*/
);
```
2) Generate prisma schema (prisma introspect)
3) Try to insert new value into this table

```ts
prisma.example.create({
  data: {
    idZak: 1,
    idObdobi: 1,
    //idSkup: 1, // Not required, but should be due to how this table is set up,
    idSkupFilled: 1, // Is required, but should not, generated columns should be read-only
  }
})
```

## Expected behavior

The schema will not generate insert/update keys for generated columns. If the column is part of a primary key, it will also let the user tell (or possibly guess?) what column(s) it is supplementing.

## Prisma information

```graphql
model example {
  idObdobi     Int
  idSkup       Int?
  idSkupFilled Int
  idZak        Int

  @@id([idZak, idObdobi, idSkupFilled])
}
```

## Environment & setup

- OS: Windows
- Database: MySQL, but this is true to PostgreSQL too.
- Prisma version: 
```
@prisma/cli          : 2.2.0
Current platform     : windows
Query Engine         : query-engine 45c4da4dd3ccd6a322796b228bdf937c7ce884e8 (at C:\Users\akxe\Documents\Programming\rita\node_modules\@prisma\cli\query-engine-windows.exe)
Migration Engine     : migration-engine-cli 45c4da4dd3ccd6a322796b228bdf937c7ce884e8 (at C:\Users\akxe\Documents\Programming\rita\node_modules\@prisma\cli\migration-engine-windows.exe)
Introspection Engine : introspection-core 45c4da4dd3ccd6a322796b228bdf937c7ce884e8 (at C:\Users\akxe\Documents\Programming\rita\node_modules\@prisma\cli\introspection-engine-windows.exe)
Format Binary        : prisma-fmt 45c4da4dd3ccd6a322796b228bdf937c7ce884e8 (at C:\Users\akxe\Documents\Programming\rita\node_modules\@prisma\cli\prisma-fmt-windows.exe)
```
- Node.js version: 12.x.x and 14.x.x

**Comment by janpio** [comment] 2020-07-13 12:18
Generated MySQL columns are indeed not supported right now.

Background information: https://dev.mysql.com/doc/refman/5.7/en/create-table-generated-columns.html

**Comment by Akxe** [comment] 2020-07-13 12:24
@janpio That's ok. Prisma 2 is pretty new, I just wanted this to be here along with this example. The example table I provided is the (to me) best solution to a nullable primary key.

**Comment by janpio** [comment] 2020-07-13 13:13
You can always use the raw methods to interact with tables with unsupported features and write raw SQL.

If you can make your example schema work with normal Prisma functions I am not sure. Even if you find a way, future `introspect` calls would most probably break that schema again.

**Comment by Akxe** [comment] 2020-08-28 12:36
@janpio Is there any plan to get it working? It is one of our key tables. Maybe adding `@readonly` and `@writeTo(columnName)` could solve it nicely?

**Comment by janpio** [comment] 2024-05-21 17:18
I am closing this issue as a duplicate of https://github.com/prisma/prisma/issues/3001. 

This will help us actually prioritize the issue, as we are not distracted by having multiple ones that compete for attention. Please make sure you left a 👍 reaction on the original issue description over there, and leave a comment if any aspect of the feature has not been talked about yet. Thank you!

**Closed by janpio** 2024-05-21 17:18 UTC
Labels: kind/feature, topic: database-functionality, topic: mysql, team/schema, team/client, topic: generated columns
