### ISSUE TITLE
MongoDB: Using `tlsCAFile` fails

### ISSUE THREAD

**Issue by janpio** [prisma/prisma#9072] opened 2021-09-01 18:52 UTC
Using `tlsCAFile` locally always fails with an error message including `The system cannot find the file specified. (os error 2)`.

See more details below.

**Comment by janpio** [comment] 2021-09-01 19:18
The same can now also be observed via our e2e tests, where we now test both `library` and `binary`:
https://github.com/prisma/e2e-tests/runs/3488293724
https://github.com/prisma/e2e-tests/runs/3488293771
![image](https://user-images.githubusercontent.com/183673/131730708-667fedd0-2aa5-44c2-8b87-4ce9a93a4157.png)

**Comment by janpio** [comment] 2021-09-01 19:18
Problem: 

In an isolated environment this _always_ fails with the error from above:
https://github.com/prisma/issue-repro-9072
https://github.com/prisma/issue-repro-9072/actions/runs/1191454219

It also always fails locally on my machine:

```
PrismaClientInitializationError:
Invalid `prisma.user.deleteMany()` invocation:


  Database error. error code: unknown, error message: Server selection timeout: No available servers. Topology: { Type: ReplicaSetNoPrimary, Servers: [ { Address: db-mongodb-nyc3-2-b2a9f917.mongo.ondigitalocean.com:27017, Type: Unknown, Error: The system cannot find the file specified. (os error 2) }, ] }
    at cb (C:\Users\Jan\Documents\throwaway\mongoDO\node_modules\@prisma\client\runtime\index.js:36942:17)
    at processTicksAndRejections (internal/process/task_queues.js:95:5) {
  clientVersion: '2.31.0-dev.36',
  errorCode: undefined
}
```

**Comment by pantharshit00** [comment] 2021-09-02 09:15
I can reproduce this both on Windows and Mac. I wasn't able connect using either the binary or library.

**Comment by janpio** [comment] 2022-02-14 18:41
Still reproducible

```
C:\Users\Jan\Documents\throwaway\issue-repro-9072>npx ts-node script.ts
PrismaClientInitializationError:
Invalid `client.user.deleteMany()` invocation in
C:\Users\Jan\Documents\throwaway\issue-repro-9072\script.ts:7:21

   4
   5 // A `main` function so that we can use async/await
   6 async function main() {
→  7   await client.user.deleteMany(
  Database error. error code: unknown, error message: Server selection timeout: No available servers. Topology: { Type: ReplicaSetNoPrimary, Servers: [ { Address: db-mongodb-nyc3-2-9de4abcf.mongo.ondigitalocean.com:27017, Type: Unknown, Error: The system cannot find the file specified. (os error 2) }, ] }
    at cb (C:\Users\Jan\Documents\throwaway\issue-repro-9072\node_modules\@prisma\client\runtime\index.js:38713:17)
    at async PrismaClient._request (C:\Users\Jan\Documents\throwaway\issue-repro-9072\node_modules\@prisma\client\runtime\index.js:40863:18) {
  clientVersion: '3.10.0-dev.39',
  errorCode: undefined
}
```

with `engineType=binary`:
```
C:\Users\Jan\Documents\throwaway\issue-repro-9072>npx ts-node script.ts
PrismaClientInitializationError: 
Invalid `client.user.deleteMany()` invocation in
C:\Users\Jan\Documents\throwaway\issue-repro-9072\script.ts:7:21

   4
   5 // A `main` function so that we can use async/await
   6 async function main() {
→  7   await client.user.deleteMany(
  Database error. error code: unknown, error message: Server selection timeout: No available servers. Topology: { Type: ReplicaSetNoPrimary, Servers: [ { Address: db-mongodb-nyc3-2-9de4abcf.mongo.ondigitalocean.com:27017, Type: Unknown, Error: The system cannot find the file specified. (os error 2) }, ] }
    at cb (C:\Users\Jan\Documents\throwaway\issue-repro-9072\node_modules\@prisma\client\runtime\index.js:38713:17)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async PrismaClient._request (C:\Users\Jan\Documents\throwaway\issue-repro-9072\node_modules\@prisma\client\runtime\index.js:40863:18) {
  clientVersion: '3.10.0-dev.39',
  errorCode: undefined
}
```

```
C:\Users\Jan\Documents\throwaway\issue-repro-9072>npx prisma -v
Environment variables loaded from .env
prisma                  : 3.10.0-dev.39
@prisma/client          : 3.10.0-dev.39
Current platform        : windows
Query Engine (Node-API) : libquery-engine 34c0995fcfd0aad58922d72470d74b34b232a879 (at node_modules\@prisma\engines\query_engine-windows.dll.node)
Migration Engine        : migration-engine-cli 34c0995fcfd0aad58922d72470d74b34b232a879 (at node_modules\@prisma\engines\migration-engine-windows.exe)
Introspection Engine    : introspection-core 34c0995fcfd0aad58922d72470d74b34b232a879 (at node_modules\@prisma\engines\introspection-engine-windows.exe)       
Format Binary           : prisma-fmt 34c0995fcfd0aad58922d72470d74b34b232a879 (at node_modules\@prisma\engines\prisma-fmt-windows.exe)
Default Engines Hash    : 34c0995fcfd0aad58922d72470d74b34b232a879
Studio                  : 0.458.0
Preview Features        : mongoDb
```

**Comment by janpio** [comment] 2022-02-14 18:52
The (private) reproduction has been updated with an definitely working connection string and certificate, and the Prisma version in the repo also has been updated. I can locally connect to that database using MongoDB Compass using the `.crt` file: 
![image](https://user-images.githubusercontent.com/183673/153927616-80c53e5d-c970-42b0-bbe4-4eacf872413a.png)

**Comment by janpio** [comment] 2022-02-17 13:43
The same is also happening for Introspection:

```
$ npx prisma db pull
Prisma schema loaded from prisma/schema.prisma
Environment variables loaded from .env
Datasource "db"

Introspecting based on datasource defined in prisma/schema.prisma …

Error: Error in connector: Error querying the database: Server selection timeout: No available servers. Topology: { Type: ReplicaSetNoPrimary, Servers: [ { Address: db-mongodb-nyc3-f6bed3e5.mongo.ondigitalocean.com:27017, Type: Unknown, Error: No such file or directory (os error 2) }, ] }
```

It does not matter if the certificate is in the root of the project or the `prisma` folder.

**Comment by do4gr** [comment] 2022-03-09 11:11
The engines expect a path relative to the .prisma/ folder. Fixing that solves the repro issue. See https://www.prisma.io/docs/concepts/components/prisma-schema/data-sources#securing-database-connections

One remaining issue to investigate is that using the library query engine seems to be using a different working directory and does not work with the file in that position. I'll keep investigating that one.

**Comment by janpio** [comment] 2022-03-09 11:27
When this is resolved, we can also remove this e2e tests exclusion: https://github.com/prisma/e2e-tests/blob/45b0d2eea2e56eb2b44856212dd8b960cd5c5c41/.github/workflows/test.yaml#L960-L962

**Comment by janpio** [comment] 2022-03-11 11:55
Current workaround: Set `engineType = "binary"` in your `generator` block in your `schema.prisma` file and generate a new Client. This should make SSL via `tlsCAFile` work at the cost of using a different Engine implementation (that might be a bit slower or show different characteristics than the default `library`). 

We are still looking into how to fix this properly.

**Comment by pimeys** [comment] 2022-03-11 14:11
Fixed in main.

**Closed by pimeys** 2022-03-11 14:11 UTC
Labels: bug/2-confirmed, kind/bug, tech/engines, team/migrations, team/client, topic: mongodb

**Comment by janpio** [comment] 2022-03-11 17:55
I can confirm that the reproduction from https://github.com/prisma/prisma/issues/9072#issuecomment-910613369 now passes with `prisma@3.11.0-dev.50`. This will be fixed in the next release.
