### ISSUE TITLE
PrismaClient proxy create an infinite loop

### ISSUE THREAD

**Issue by JinYuSha0** [prisma/prisma#21615] opened 2023-10-25 12:51 UTC
### Bug description

I use Prisma with nestjs, when my service access the PrismaClient  instance enter an infinite loop. causing the service to hang.

I found through the debugger that the infinite loop occurred in @prisma/client/runtime/libary

https://github.com/prisma/prisma/assets/20939091/06c2ce03-31cc-423c-a10d-fc374437b62a

I'm sure I didn't use it improperly, Don't know what causes this problem

### How to reproduce

```
@Injectable()
export class RegisterBackend {
  constructor(private readonly prisma: PrismaService) {}

  @Loader()
  async loader(@RemixArgs() _remixArgs: LoaderFunctionArgs) {
    console.log(this) // just access
    return {};
  }

  @Action()
  async post(@Body() body: RegisterDto) {
    return {};
  }
}
```

### Prisma information

```prisma
// This is your Prisma schema file,
// learn more about it in the docs: https://pris.ly/d/prisma-schema

generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "mongodb"
  url      = env("DATABASE_URL")
}

model User {
  id          String      @id @default(auto()) @map("_id") @db.ObjectId
  email       String      @unique
  nickname    String
  gender      String
  birthday    DateTime
  password    String
  validated   Boolean
}
```

### Environment & setup

- OS: macOS
- Database: MongoDB
- bun version: 1.0.4
- 

### Prisma Version

```
"@prisma/client": "^5.5.0",
"prisma": "^5.5.0",
```

**Comment by janpio** [comment] 2023-10-26 18:15
Are you effectively reporting the same problem as https://github.com/prisma/prisma/issues/18292?

**Comment by JinYuSha0** [comment] 2023-10-27 03:01
> Are you effectively reporting the same problem as #18292?

I guess so, not sure if this is a problem with nestjs compatibility, I tried to locate the problem, it seems that the _engine attribute is always undefined, Node addons seem to be unable to load, when I switch to singleton pattern everything is fine.

```typescript
import { PrismaClient } from '@prisma/client'

const prisma = new PrismaClient()

prisma.$connect().then(() => {
	console.log('prisma connected')
})

export default prisma
```

**Comment by millsp** [comment] 2023-11-07 02:15
Hey @JinYuSha0, could you please provide us with a reproduction? Without it we will not be able to make progress and will end up closing the issue via our internal process. Thanks :pray:

**Comment by SevInf** [comment] 2023-11-22 11:57
Hey @JinYuSha0  ,

Did you get a chance to have a look at @millsp's previous comment? It'd be helpful for us to move your issue forward.

Without further information, we'll have to close this issue. Thank you 🙏

**Comment by JinYuSha0** [comment] 2023-11-22 12:22
@millsp @SevInf 
I'd like to help you, But I can't provide a code repository. If you want to reproduce the issue, try wrapping prisma in a Nest provider, inject it into any service, and access it.

This problem is still there, I can provide code snippets

```typescript
// PrismaProvider.ts
import { Provider } from '@nestjs/common';
import { ConfigService } from '@nestjs/config';
import { PrismaClient } from '@prisma/client';

export const PRISMA = Symbol('PrismaSymbol');

export const PrismaProvider: Provider = {
  provide: PRISMA,
  useFactory: (configService: ConfigService) => {
    return new PrismaClient();
  },
  inject: [ConfigService],
};
```

```typescript
// CommonModule.ts
import { PrismaProvider } from '@/common/prisma.provider';

@Global()
@Module({
  imports: [CacheModule],
  providers: [
    PrismaProvider,
  ],
  exports: [
    PrismaProvider,
  ],
})
export class CommonModule {}
```

```typescript
// SomeService.ts
@Injectable()
export class SomeService {
 constructor(
    @Inject(PRISMA) private readonly prisma: typeof Prisma,
  ) {}

  public async someMethod() {
    this.prisma;  // just access
  }
}
```

**Comment by janpio** [comment] 2024-03-04 17:12
https://github.com/prisma/prisma/pull/23228 could have fixed this and will be included in the next release, but of course a confirmation of it now working as intended would be nice. Could you please try to temporarily install `prisma@dev` and `@prisma/client@dev` in your project and see if this fixes the problem?

**Comment by YoannBuzenet** [comment] 2024-03-07 14:07
Hey, I have the bug currently and would like to try `prisma@dev` and `@prisma/client@dev` but I have this message : 
![Screenshot from 2024-03-07 15-07-33](https://github.com/prisma/prisma/assets/28066290/2ca69fee-76c3-408e-b064-6ff7e6abf37c)

How can I do it ?

**Comment by YoannBuzenet** [comment] 2024-03-07 14:21
I did 
`npm install prisma@dev @prisma/client@dev`
and I'm happy to say it works. Thank you !

**Comment by SevInf** [comment] 2024-03-18 09:42
@JinYuSha0 could you confirm that the issue is fixed in 5.11 as well?
Thank you.

**Comment by JinYuSha0** [comment] 2024-04-12 06:32
@jkomyno @SevInf Sorry I haven't followed that project for a while, I'll take a look at it over the weekend

**Comment by SevInf** [comment] 2024-05-03 09:28
I am going to close the issue for now. If it still happens for you for prisma 5.11 or creater, feel free to open a new one.
Thank you!

**Closed by SevInf** 2024-05-03 09:28 UTC
Labels: bug/0-unknown, kind/bug, topic: prisma-client, team/client, topic: logging, topic: NestJS
