### ISSUE TITLE
Can't pull image

### ISSUE THREAD

**Issue by humbertocruz** [prisma/prisma#4049] opened 2019-02-13 18:53 UTC
**Describe the bug**
Can't pull image

**To Reproduce**
docker-compose up -d after prisma init

**Expected behavior**
The https://registry-1.docker.io/v2/prismagraphql/prisma/manifests/latest is asking for authorization

**Comment by pantharshit00** [comment] 2019-02-14 10:20
Hi @humbertocruz 


We current dont publish the latest tag but there is an issue about it #3244 

Please use `1.26` tag right now

**Comment by pantharshit00** [comment] 2019-02-14 10:20
Closing as a duplicate of #3244

**Closed by pantharshit00** 2019-02-14 10:20 UTC
