### ISSUE TITLE
$transaction doesn't roll back in NestJS when we pass method from external service

### ISSUE THREAD

**Issue by revivalme** [prisma/prisma#5730] opened 2021-02-18 15:27 UTC
## Bug description
$transaction works incorrectly in NestJS when we pass method from external service, but works well if it uses method from current service.
It doesn't roll back as expected.

Example:

```javascript
// UserService
@Injectable()
export class UserService {
  constructor(private readonly prismaService: PrismaService) {}

  addMoney(userId: number, value: number) {
    return this.prismaService.user.update({
      where: { id: userId },
      data: {
        money: {
          increment: value,
        },
      },
    });
  }
}

// InventoryService
@Injectable()
export class InventoryService {
  constructor(
    private readonly prismaService: PrismaService,
    private readonly userService: UserService,
  ) {}

  async sell(userId: number, itemId: number) {
    const write1 = this.prismaService.userItem.delete({
      where: { ... },
    });

    // external service method
    const write2 = this.userService.addMoney(...);

    await this.prismaService.$transaction([write1, write2]);
  }

  addMoney(userId: number, value: number) {
    return this.prismaService.user.update({
      where: { id: userId },
      data: {
        money: {
          increment: value,
        },
      },
    });
  }
}
```
If write2 will fail - write1 doesn't rollback.
But... rollback will work as expected if write2 refers to the current service method. (this.addMoney)

## How to reproduce
https://github.com/revivalme/nestjs-prisma-transaction-test
Bug reproduction section

## Expected behavior
Transaction write1 should rollback as transaction write2 failed.

## Environment & setup

- OS: Windows 10
- Database: SQLite, PostgreSQL
- Node.js version: v14.15.4
- Prisma version: 

```
prisma               : 2.17.0
@prisma/client       : 2.17.0
Current platform     : windows
Query Engine         : query-engine 3c463ebd78b1d21d8fdacdd27899e280cf686223 (at node_modules\@prisma\engines\query-engine-windows.exe)
Migration Engine     : migration-engine-cli 3c463ebd78b1d21d8fdacdd27899e280cf686223 (at node_modules\@prisma\engines\migration-engine-windows.exe)
Introspection Engine : introspection-core 3c463ebd78b1d21d8fdacdd27899e280cf686223 (at node_modules\@prisma\engines\introspection-engine-windows.exe)
Format Binary        : prisma-fmt 3c463ebd78b1d21d8fdacdd27899e280cf686223 (at node_modules\@prisma\engines\prisma-fmt-windows.exe)
Studio               : 0.353.0
```

[Conversation from Public Slack here](https://prisma.slack.com/archives/CKQTGR6T0/p1612273504412300)

**Comment by timsuchanek** [comment] 2021-02-18 16:09
Thanks @revivalme for the report. We'll have a look at this!

**Comment by pantharshit00** [comment] 2021-03-02 14:53
I can confirm this. From the logs, it looks like transaction flag is not set correctly here and writes are not running in a transaction. 

![image](https://user-images.githubusercontent.com/22195362/109666337-1b1a8b00-7b95-11eb-92c5-c9ad2050912f.png)

**Comment by williamluke4** [comment] 2021-03-17 09:50
@revivalme Could you try out [williamluke4:patch-1](https://github.com/revivalme/nestjs-prisma-transaction-test/compare/master...williamluke4:patch-1)

**Comment by revivalme** [comment] 2021-03-17 14:18
> @revivalme Could you try out [williamluke4:patch-1](https://github.com/revivalme/nestjs-prisma-transaction-test/compare/master...williamluke4:patch-1) ?

Yeah, for some unknown reason it works, but shouldn't. UserModule has exports array with UserService, so whenever I import UserModule into other modules - I already have access to UserService without manually add this service to providers array.

(same info here https://docs.nestjs.com/modules#shared-modules)

The especially weird part of this is that in both cases, with/without manually add service to providers array, addMoney method of UserService invokes.

Also both cases have similar errors:

[Just with module import]
```
Invalid `prisma.user.update()` invocation:


  An operation failed because it depends on one or more records that were required but not found. Record to update not found. +5117ms
Error: 
Invalid `prisma.user.update()` invocation:


  An operation failed because it depends on one or more records that were required but not found. Record to update not found.
    at cb (C:\Users\revivalme\Desktop\nestjs-prisma-transaction-test\node_modules\@prisma\client\runtime\index.js:78689:17)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Promise.all (index 1)
    at async InventoryService.sellItem (C:\Users\revivalme\Desktop\nestjs-prisma-transaction-test\dist\src\inventory\inventory.service.js:56:9)
    at async C:\Users\revivalme\Desktop\nestjs-prisma-transaction-test\node_modules\@nestjs\core\router\router-execution-context.js:46:28
    at async C:\Users\revivalme\Desktop\nestjs-prisma-transaction-test\node_modules\@nestjs\core\router\router-proxy.js:9:17
```

[Module import with manual add service to providers]
```
InterpretationError("Error for binding \'0\'", Some(QueryGraphBuilderError(RecordNotFound("Record to update not found.")))) +5902ms
Error: Error occurred during query execution:
InterpretationError("Error for binding \'0\'", Some(QueryGraphBuilderError(RecordNotFound("Record to update not found."))))
    at C:\Users\revivalme\Desktop\nestjs-prisma-transaction-test\node_modules\@prisma\client\runtime\index.js:27103:19
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

So, given the above, guess it's too early to close this issue

**Comment by williamluke4** [comment] 2021-03-18 07:58
@revivalme Both your logs above seem unrelated to this issue. They seem to be a result of you trying to update a record that does not exist in the database
> An operation failed because it depends on one or more records that were required but not found.

And 
> Record to update not found.

**Comment by williamluke4** [comment] 2021-03-22 10:38
Hey @revivalme, I'm going to close this issue, if you feel like the problems you are experiencing are still related to this specific issue then feel free to reopen it explaining why.

**Closed by williamluke4** 2021-03-22 10:38 UTC
Labels: bug/2-confirmed, kind/bug, team/client, topic: prisma-client, topic: transaction
