### ISSUE TITLE
The requested module '@prisma/client' is a CommonJS module,

### ISSUE THREAD

**Issue by luozhang002** [prisma/prisma#23668] opened 2024-03-30 04:50 UTC
### Bug description

```
file:///xxxx/evalService.js:1
import { PrismaClient } from '@prisma/client';
         ^^^^^^^^^^^^
SyntaxError: Named export 'PrismaClient' not found. The requested module '@prisma/client' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from '@prisma/client';
const { PrismaClient } = pkg;
```

### Prisma information

```prisma
// Add your schema.prisma
```

```ts
// Add your code using Prisma Client
```

### Environment & setup

- OS: 
- Database: 
- Node.js version: 

### Prisma Version

```

```

**Comment by jkomyno** [comment] 2024-04-02 16:56
Prisma currently doesn't support EcmaScript Modules out of the box.
You can still run `import { PrismaClient } from '@prisma/client'`, but depending on your execution environment, you may need something else to make it work out of the box.

Can you please fill in the "Environment & setup" input field above? Are you using Node.js, or some other JavaScript runtime? Are you using TypeScript or pure JavaScript?
Can you please share your `package.json` file and `tsconfig.json` file? Thank you.

**Comment by daniel-nagy** [comment] 2024-04-13 15:44
I just noticed you can get this error if you try to run your app before running `prisma generate`.

I had a build script that would generate my GraphQL schema before running `prisma generate`. Generating my schema required evaluating the source code (since I use TypeGraphQL). This would fail with this error when I imported an enum type from @prisma/client.

The fix was to run `prisma generate` before generating my GraphQL schema. This was pretty tricky to debug 🙁.

**Comment by Jolg42** [comment] 2024-05-28 08:54
With the lack of information and our inability to reproduce this issue, we're now closing it. Feel free to comment if you have any updates about it.

Thank you 🙏

**Closed by Jolg42** 2024-05-28 08:54 UTC
Labels: bug/0-unknown, kind/bug, team/client, topic: esm
