### ISSUE TITLE
Prisma studio crashes after upgrading to 2.0.0-beta.7

### ISSUE THREAD

**Issue by yantakus** [prisma/prisma#2626] opened 2020-06-01 07:52 UTC
Getting the following error:

![image](https://user-images.githubusercontent.com/2179726/83387703-dd19ec00-a3f5-11ea-8e4f-1c310c29e377.png)

**Comment by pantharshit00** [comment] 2020-06-01 09:06
Hi,

Thanks for reporting this! It has already been reported before, so I am going to close this as a duplicate of #2611

**Closed by pantharshit00** 2020-06-01 09:06 UTC
