### ISSUE TITLE
`CreateInput` and `UpdateInput` have different typings for optional relations

### ISSUE THREAD

**Issue by RafaelKr** [prisma/prisma#2839] opened 2020-06-24 13:07 UTC
Note: I just upgraded from prisma `2.0.0-preview021` to `2.1.0`

## Bug description
I'm using an upsert call to update an entry or create it if it doesn't exist. Unfortunately I get an error because `CreateInput` and `UpdateInput` have different typings for optional relations (see **Prisma information** below).

```
error TS2322: Type 'JobContactCreateInput' is not assignable to type 'JobContactUpdateInput'.
  Types of property 'location' are incompatible.
    Type 'JobContactLocationCreateOneWithoutJobContactInput | null | undefined' is not assignable to type 'JobContactLocationUpdateOneWithoutJobContactInput | undefined'.
      Type 'null' is not assignable to type 'JobContactLocationUpdateOneWithoutJobContactInput | undefined'.

167     update: jobContact,
```

It works for relations which are required. I only get the error for `location`, not for `phone`.

I can temporarily work around it when I use
`update: jobContact as JobContactUpdateInput,`

## How to reproduce

```typescript
const jobContact: JobContactCreateInput // I'm calling a function which returns a variable of type JobContactCreateInput

const upsertResult = await prisma.jobContact.upsert({
  create: jobContact,
  update: jobContact,
  select: {
    id: true,
  },
  where: {
    foreignId: jobContact.foreignId,
  },
})
```

## Expected behavior

`CreateInput` and `UpdateInput` should use the same typings for optional relations.

## Prisma information

schema.prisma
```prisma
model JobContact {
  id          String   @default(cuid()) @id
  foreignId   String   @unique
  
  /// [...] unimportant fields

  phoneId     String
  phone       JobContactPhone      @relation(fields: [phoneId], references: [id])
  locationId  String?
  location    JobContactLocation?  @relation(fields: [locationId], references: [id])
}

model JobContactPhone {
  id          String   @default(cuid()) @id
  areaCode    String
  prefix      String
  lineNumber  String
}

model JobContactLocation {
  id      String  @default(cuid()) @id
  zip     String?
  city    String?
  street  String?
}
```

generated typings from @prisma/client
```typescript
export type JobContactCreateInput = {
  id?: string
  foreignId: string
  // [...] unimportant fields
  phone: JobContactPhoneCreateOneWithoutJobContactInput
  location?: JobContactLocationCreateOneWithoutJobContactInput | null
  JobOffer?: JobOfferCreateManyWithoutContactInput | null
}

export type JobContactUpdateInput = {
  id?: string
  foreignId?: string
  // [...] unimportant fields
  phone?: JobContactPhoneUpdateOneRequiredWithoutJobContactInput
  location?: JobContactLocationUpdateOneWithoutJobContactInput
  JobOffer?: JobOfferUpdateManyWithoutContactInput
}
```

## Environment & setup

- **TypeScript: 3.7.5**
- OS: Linux Mint 19.2 Cinnamon
- Database: PostgreSQL
- Node.js version: v13.7.0
- Prisma version:
```
Environment variables loaded from prisma/.env
@prisma/cli          : 2.1.0
Current platform     : debian-openssl-1.1.x
Query Engine         : query-engine 4440772035795a0424be62040e2295c56e5c6ad0 (at /home/rafael/[...]/node_modules/@prisma/cli/query-engine-debian-openssl-1.1.x)
Migration Engine     : migration-engine-cli 4440772035795a0424be62040e2295c56e5c6ad0 (at /home/rafael/[...]/node_modules/@prisma/cli/migration-engine-debian-openssl-1.1.x)
Introspection Engine : introspection-core 4440772035795a0424be62040e2295c56e5c6ad0 (at /home/rafael/[...]/node_modules/@prisma/cli/introspection-engine-debian-openssl-1.1.x)
Format Binary        : prisma-fmt 4440772035795a0424be62040e2295c56e5c6ad0 (at /home/rafael/[...]/node_modules/@prisma/cli/prisma-fmt-debian-openssl-1.1.x)
```

**Comment by pantharshit00** [comment] 2020-06-24 13:35
I suspect this is part of null vs undefined work we did: https://github.com/prisma/prisma-engines/issues/678

Since you are upgrading for a very old version it would be a breaking change for you.

Also, update input if full optional because you can supply partial data to it.

**Comment by RafaelKr** [comment] 2020-06-24 13:43
Hi Harshit! Sorry, I didn't understand if that last sentence is for the prisma team or if this is an info for me and something I should change.

**Comment by pantharshit00** [comment] 2020-06-24 14:06
Are you referring to this? 

> Also, update input is fully optional because you can supply partial data to it.

This was just meant to inform you that why create and update inputs are different.

**Comment by steebchen** [comment] 2020-06-24 14:45
What @RafaelKr probably meant: For this code:

```
export type JobContactCreateInput = {
  id?: string
  foreignId: string
  // [...] unimportant fields
  phone: JobContactPhoneCreateOneWithoutJobContactInput
  location?: JobContactLocationCreateOneWithoutJobContactInput | null
  JobOffer?: JobOfferCreateManyWithoutContactInput | null
}
export type JobContactUpdateInput = {
  id?: string
  foreignId?: string
  // [...] unimportant fields
  phone?: JobContactPhoneUpdateOneRequiredWithoutJobContactInput
  location?: JobContactLocationUpdateOneWithoutJobContactInput
  JobOffer?: JobOfferUpdateManyWithoutContactInput
}
```

Why is it `| null` in create, but not in update? If you can set it to null, doesn’t that mean it should be also possible to set it to null in update? This seems like a bug to me.

**Comment by pantharshit00** [comment] 2020-06-24 14:51
Oh, yeah I missed that part. That is indeed a bug.

**Comment by steebchen** [comment] 2020-06-29 18:45
The fix is published and seems to have solved the main issue. However, there's still one difference, and I don't understand why. More specifically, the `phone` field can be undefined in CreateInput, but can be undefined OR null in UpdateInput. The field is required, so I don't understand why you can set it to null in UpdateInput.

```ts
export type JobContactCreateInput = {
  id?: string
  companaId: string
  salutation: string
  email: string
  firstName: string
  lastName: string
  phone: JobContactPhoneCreateOneWithoutJobContactInput
  location?: JobContactLocationCreateOneWithoutJobContactInput | null
  JobOffer?: JobOfferCreateManyWithoutContactInput | null
}

export type JobContactUpdateInput = {
  id?: string
  companaId?: string
  salutation?: string
  email?: string
  firstName?: string
  lastName?: string
  phone?: JobContactPhoneUpdateOneRequiredWithoutJobContactInput | null // <- here
  location?: JobContactLocationUpdateOneWithoutJobContactInput | null
  JobOffer?: JobOfferUpdateManyWithoutContactInput | null
}
```

I think the `| null` in the `phone` field needs to be removed as well in the UpdateInput.

**Comment by dpetrick** [comment] 2020-06-29 19:36
> I think the | null in the phone field needs to be removed as well in the UpdateInput.

This came from the requirement in the JS client (can't dig up the ticket right now, but it was an explicit implementation requirement because of how the call chains wove into each other) - if you supply null, it effectively ignores the field, hence the possibility to do so. 

>  the phone field can be undefined in CreateInput

You probably mistyped / misread, but it can't. The relation is required, so we know on a type level already that if you create a new record that you need to do something with the relation.

**Comment by steebchen** [comment] 2020-06-29 19:45
> You probably mistyped / misread

Yep, sorry, I edited that in my comment.

The main confusion here is that in UpdateInput, the `phone` field should be just `phone?: JobContactPhoneUpdateOneRequiredWithoutJobContactInput`. I don't understand why the `| null` is added here but no in the CreateInput. undefined/? already tells that it's settableoptionally, but when it's set it can't be set to null since the field is not nullable, so in theory no `| null` should be needed.

I also remember something with ? and null in the past. Maybe @timsuchanek can clarify?

**Comment by RafaelKr** [comment] 2020-06-30 07:37
As @steebchen already said the bug why I created this issue is solved. With the `@dev` version I can now pass the `CreateInput` to update.

Yesterday I discussed this with @steebchen in private and for both of us it wasn't clear why this `| null` is added on a required field like `phone`.
It would be good to know where this is coming from and maybe it should be documented somewhere in the spec (or at least as a comment in the code which generates the `UpdateInput`).

Anyway thanks for fixing it!

**Comment by janpio** [comment] 2020-06-30 08:41
Can you open a new issue for this remaining open question? Then we can close this one here and people need to read less context for that discussion.

**Comment by RafaelKr** [comment] 2020-06-30 12:29
Sorry for being unclear, I don't have the problem anymore but I think the solution you implemented is not completely right. So I would like to keep it in this issue.

Trying to make it more clear:
- The problem was that **optional** fields (type modifier `?`) were typed **without** `| null` on `UpdateInput`. This was only for relations, simple fields were correct. But from my understanding all fields with a `?` in the schema should be nullable, so it must be possible to pass null. This was already correct for `CreateInput`.
- You guys fixed this issue by adding `| null` to all relation fields, also the required ones. This is probably wrong, as it doesn't have to do with the relation itself, it is related to the type modifier `?`.

[The prisma docs](https://www.prisma.io/docs/reference/tools-and-interfaces/prisma-schema/models#optional-vs-required) are defining that
- When **not** annotating a field with the `?` type modifier, the field will be required on every record of the model.
- **Database**: Required fields are represented via NOT NULL constraints in the underlying database.

I'll try to explain it further with an example. For simplicity I will give a schema which has nothing to do with relations as I think it should be the same for simple fields and also for relations:

`schema.prisma`
```prisma
model Demo {
  requiredField  String
  optionalField  String?
}
```

From my understanding this should generate the following types:
```typescript
export type DemoCreateInput = {
  // this field is defined as NOT NULL on database level => must be defined in all cases
  requiredField: string

  // this field is optional => will be set to a database NULL when either not specified (undefined) or specified as null
  optionalField?: string | null
}

export type DemoUpdateInput = {
  // this field is defined as NOT NULL on database level => it can be undefined, then it won't change on update. But it should be NOT NULL
  requiredField?: string // <- no `| null` here!

  // this field is optional and has two options
  // undefined: unchanged on update
  // null: is explicitly set to null on update
  optionalField?: string | null
}
```

@dpetrick said
> This came from the requirement in the JS client (can't dig up the ticket right now, but it was an explicit implementation requirement because of how the call chains wove into each other)

Maybe this is something important for n:n relations for reasons I currently don't see. It would be very interesting for me to know, if there are reasons why you implemented it like this.

Anyway, I think it's a good idea to rethink all of this before implementing a "wrong" fix where the context will be lost in some weeks/months/years.

**Comment by RafaelKr** [comment] 2020-06-30 12:56
Addendum:

@dpetrick also wrote
> if you supply null, it effectively ignores the field, hence the possibility to do so. I'm not saying that the sense of it is not debatable, but I believe back then I was convinced that the added ergonomics for the client justified this.

In my opinion it doesn't make sense to have different `null` tyings for `CreateInput` and `UpdateInput` for consistency reasons. "added ergonomics" should be secondary in this case. But as you said, this is of course debatable.

**Comment by RafaelKr** [comment] 2020-06-30 14:55
Addendum 2:

I wrote
> From my understanding this should generate the following types:

and just saw that it DOES generate the typings as I outlined in the TypeScript-Snippet for Scalars, just not for relations.

I think it does make the most sense to keep it as simple as this:

With `?` type modifier:
- CreateInput: `undefined` and `null`
- UpdateInput: `undefined` and `null`

Without `?` type modifier:
- CreateInput: always required
- UpdateInput: `undefined` => the field is ignored (unchanged) on update

There's a reason why there's a difference between `undefined` and `null` in JavaScript and I think it would be best to use exactly this methodology for Prisma. Everything else could lead to confusion, at least for me.

I also don't see a use-case where it would make it easier to to be able to pass `null` instead of `undefined`. Additionally it also wasn't possible before the typing change for this issue was made, so it also won't break something if it is not implemented now. It would only break something if there should be a reason to remove it later when once implemented.

And if someone comes up with a good use-case later it still can be implemented. But removing it would be a breaking change.

**Comment by steebchen** [comment] 2020-07-01 09:01
Thanks a lot for all the detailed input @RafaelKr. It's indeed a bug, we'll make sure to fix it soon.

**Comment by tomhoule** [comment] 2020-07-28 11:33
This should be addressed by https://github.com/prisma/prisma-engines/pull/924 - it can currently be tested in the latest dev releases.

**Closed** 2020-07-30 07:37 UTC
Labels: bug/2-confirmed, kind/bug, team/engines

**Comment by RafaelKr** [comment] 2020-07-30 08:22
@tomhoule Thank you! I just checked `2.4.0-dev.7` and it works now. At least my server is starting without the `as *UpdateInput` "cast" now and the typings are looking fine.

I see you removed `null` for relations at all. I'm curious what happens if you pass `null` for example from unchecked user input? Does it get ignored or does it disconnect?

**Comment by tomhoule** [comment] 2020-07-30 08:42
It gets ignored. We decided to disallow nulls there because it's ambiguous for users of the API: you could interpret it as "disconnect" but in fact it does nothing (that did not change).

**Comment by tomhoule** [comment] 2020-07-30 09:26
Ah sorry, I just remembered that it's not ignored anymore, it will return a runtime error instead, after the PR above.

**Comment by RafaelKr** [comment] 2020-07-30 09:33
@tomhoule Pity, I was already looking forward to the noop solution!

In my case it's no problem as I'm using GraphQL, but I just thought about what happens when you're using a JSON REST API without checking if something is `undefined` or `null`. So if the frontend or API consumer passes `null` it now will suddenly result in a runtime error. IMO the noop would be much better than a runtime error. Just forbidding it with the typing should be enough.

**Comment by RafaelKr** [comment] 2020-07-30 12:18
@tomhoule Okay, just thought about it again. Not nullable should really mean not nullable. It's good to handle it as runtime error :+1:

**Comment by chrisjaimes** [comment] 2020-08-16 13:48
has this fix been deployed? I'm getting the following error trying to assign a string value to an enum

```
Types of property '<propertyname>' are incompatible.
Type 'string' is not assignable to type <type_Input>
```

This is the code and the error happens in `data`
`return` await Promise.all([ ... ].map(notification => prisma.table.create({ data: notification })))`

**Comment by pantharshit00** [comment] 2020-08-17 12:33
Yes, it was deployed in 2.4.1

Can you please a new issue with a minimal reproduction? If your project is using nexus, you can open an issue here instead: https://github.com/graphql-nexus/nexus
