### ISSUE TITLE
PANIC in query-engine\core\src\query_document\parser.rs:250:87called `Option::unwrap()` on a `None` value

### ISSUE THREAD

**Issue by joseywoermann** [prisma/prisma#7778] opened 2021-06-20 19:26 UTC
Hi Prisma Team! My Prisma Client just crashed. This is the report:
## Versions

| Name            | Version            |
|-----------------|--------------------|
| Node            | v14.16.0           | 
| OS              | windows            |
| Prisma Client   | 2.25.0             |
| Query Engine    | query-engine c838e79f39885bc8e1611849b1eb28b5bb5bc922|
| Database        | undefined| 

## Query
```
mutation {
  createOneServer(data: {
    id: 5
    name: "X"
    icon: "X"
    memberCount: 5e+21
    inviteURL: "X"
  }) {
    id
    name
    icon
    memberCount
    inviteURL
  }
}
```

## Logs
```
78;1mprisma:engine Search for Query Engine in G:\p00rtal\api\node_modules\.prisma\client  
  prisma:engine Client Version: 2.25.0  
  prisma:engine Engine Version: query-engine c838e79f39885bc8e1611849b1eb28b5bb5bc922  
  prisma:engine Active provider: postgresql  
  prisma:tryLoadEnv Environment variables loaded from G:\p00rtal\api\.env  +1m
  prisma:client clientVersion: 2.25.0  +1m
  prisma:engine Search for Query Engine in G:\p00rtal\api\node_modules\.prisma\client  +1m
  prisma:engine { cwd: 'G:\\p00rtal\\api\\prisma' }  
  prisma:engine Search for Query Engine in G:\p00rtal\api\node_modules\.prisma\client  
  prisma:engine { flags: [ '--enable-raw-queries', '--port', '52332' ] }  
  prisma:engine stdout  Starting a postgresql pool with 9 connections.  
  prisma:engine stdout  Started http server on http://127.0.0.1:52332  
  prisma:engine Search for Query Engine in G:\p00rtal\api\node_modules\.prisma\client  
  prisma:engine Client Version: 2.25.0  
  prisma:engine Engine Version: query-engine c838e79f39885bc8e1611849b1eb28b5bb5bc922  
  prisma:engine Active provider: postgresql  
  prisma:tryLoadEnv Environment variables loaded from G:\p00rtal\api\.env  +16s
  prisma:client clientVersion: 2.25.0  +16s
  prisma:engine Search for Query Engine in G:\p00rtal\api\node_modules\.prisma\client  +16s
  prisma:engine { cwd: 'G:\\p00rtal\\api\\prisma' }  
  prisma:engine Search for Query Engine in G:\p00rtal\api\node_modules\.prisma\client  
  prisma:engine { flags: [ '--enable-raw-queries', '--port', '57487' ] }  
  prisma:engine stdout  Starting a postgresql pool with 9 connections.  
  prisma:engine stdout  Started http server on http://127.0.0.1:57487  
  prisma:engine Search for Query Engine in G:\p00rtal\api\node_modules\.prisma\client  
  prisma:engine stdout  PANIC in query-engine\core\src\query_document\parser.rs:250:87
called `Option::unwrap()` on a `None` value  
  prisma:engine {
  prisma:engine   error: Error: read ECONNRESET
  prisma:engine       at TCP.onStreamRead (internal/stream_base_commons.js:209:20) {
  prisma:engine     errno: -4077,
  prisma:engine     code: 'ECONNRESET',
  prisma:engine     syscall: 'read'
  prisma:engine   }
  prisma:engine }  
  prisma:engine Client Version: 2.25.0  
  prisma:engine Engine Version: query-engine c838e79f39885bc8e1611849b1eb28b5bb5bc922  
  prisma:engine Active provider: postgresql  
  prisma:engine {
  prisma:engine   error: Error: connect ECONNREFUSED 127.0.0.1:57487
  prisma:engine       at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1146:16) {
  prisma:engine     errno: -4078,
  prisma:engine     code: 'ECONNREFUSED',
  prisma:engine     syscall: 'connect',
  prisma:engine     address: '127.0.0.1',
  prisma:engine     port: 57487
  prisma:engine   }
  prisma:engine }  
  prisma:engine There is a child that still runs and we want to start again  
  prisma:engine { cwd: 'G:\\p00rtal\\api\\prisma' }  
  prisma:engine Search for Query Engine in G:\p00rtal\api\node_modules\.prisma\client  
  prisma:engine { flags: [ '--enable-raw-queries', '--port', '57491' ] }  
  prisma:engine stdout  Starting a postgresql pool with 9 connections.  
  prisma:engine stdout  Started http server on http://127.0.0.1:57491  
  prisma:engine Search for Query Engine in G:\p00rtal\api\node_modules\.prisma\client  
  prisma:engine stdout  PANIC in query-engine\core\src\query_document\parser.rs:250:87
called `Option::unwrap()` on a `None` value  
  prisma:engine {
  prisma:engine   error: Error: read ECONNRESET
  prisma:engine       at TCP.onStreamRead (internal/stream_base_commons.js:209:20) {
  prisma:engine     errno: -4077,
  prisma:engine     code: 'ECONNRESET',
  prisma:engine     syscall: 'read'
  prisma:engine   }
  prisma:engine }  
```

## Client Snippet
```ts
const newServer = await prisma.server.create({
  data: {
    id: 2,
    name: "Example server 2",
    icon: "https://definitely.real.url/icons/2",
    memberCount: 5615614541684846485418,
    inviteURL: "https://invite.to/server/2",
  },
});

const allServers = await prisma.server.findMany();
console.log(allServers);
```

## Schema
```prisma
// This is your Prisma schema file,
// learn more about it in the docs: https://pris.ly/d/prisma-schema

datasource db {
    provider = "postgresql"
    url      = env("DATABASE_URL")
}

generator client {
    provider = "prisma-client-js"
}

model Server {
    id          Int    @id
    name        String
    icon        String
    memberCount Int
    inviteURL   String @unique
}

// https://vercel.com/guides/nextjs-prisma-postgres#step-3.-create-your-database-schema-with-prisma

```

**Comment by pantharshit00** [comment] 2021-06-21 13:37
Hi,

Thanks for reporting this! It has already been reported before, so I am going to close this as a duplicate of https://github.com/prisma/prisma/issues/6487

Try passing full number instead of 5e+21 as a workaround for now.

**Closed by pantharshit00** 2021-06-21 13:37 UTC
