### ISSUE TITLE
Prisma introspects Postgres not null generated columns as required fields.

### ISSUE THREAD

**Issue by nickkang1** [prisma/prisma#4849] opened 2021-01-02 06:30 UTC
## Bug description

It's not possible to insert a value into Postgres generated columns. When Prisma introspects a table with a not null generated column, it makes the corresponding model field as required. At the minimum it should be optional.

## How to reproduce

```sql
CREATE TABLE person (
    primary key (person_id),
    person_id      bigint,
    first_name     text not null,
    last_name      text not null,
    full_name      text NOT NULL GENERATED ALWAYS AS (first_name || ' ' || last_name)
);
```

When you run `prisma introspect`, you get

```prisma
model person {
  person_id         Int             @id
  first_name        String
  last_name         String
  full_name         String
}
```

Postgres will throw an error when you try to insert a person since you can't insert into the `full_name` column.

## Expected behavior

`prisma introspect` should mark `NOT NULL GENERATED ALWAYS AS` columns with a `@default` tag. Or an optional tag as a temporary workaround.

## Environment & setup

- OS: Debian
- Database: PostgreSQL
- Node.js version: 15.0.1
- Prisma version:

```
@prisma/cli          : 2.13.1
@prisma/client       : 2.13.1
Current platform     : debian-openssl-1.1.x
Query Engine         : query-engine fcbc4bb2d306c86c28014f596b1e8c7980af8bd4 (at node_modules/@prisma/engines/query-engine-debian-openssl-1.1.x)
Migration Engine     : migration-engine-cli fcbc4bb2d306c86c28014f596b1e8c7980af8bd4 (at node_modules/@prisma/engines/migration-engine-debian-openssl-1.1.x)
Introspection Engine : introspection-core fcbc4bb2d306c86c28014f596b1e8c7980af8bd4 (at node_modules/@prisma/engines/introspection-engine-debian-openssl-1.1.x)
Format Binary        : prisma-fmt fcbc4bb2d306c86c28014f596b1e8c7980af8bd4 (at node_modules/@prisma/engines/prisma-fmt-debian-openssl-1.1.x)
Studio               : 0.329.0
```

**Comment by do4gr** [comment] 2021-01-04 15:30
Fixing this in the introspection engine would be a first step, but technically the QE should also know to not expose that field as writable then. For that we currently do not have a schema language capability.

**Comment by xiaoyu-tamu** [comment] 2021-07-13 17:12
I'm experiencing the same issue.

**Comment by janpio** [comment] 2024-05-21 17:19
I am closing this issue as a duplicate of https://github.com/prisma/prisma/issues/3001. 

This will help us actually prioritize the issue, as we are not distracted by having multiple ones that compete for attention. Please make sure you left a 👍 reaction on the original issue description over there, and leave a comment if any aspect of the feature has not been talked about yet. Thank you!

**Closed by janpio** 2024-05-21 17:19 UTC
Labels: kind/feature, topic: prisma-client, topic: schema, topic: introspection, tech/engines/query engine, tech/engines/introspection engine, team/schema, team/client, topic: postgresql, team/psl-wg, topic: generated columns
