### ISSUE TITLE
Please remove red text color for non-errors in "post deploy" section of "prisma deploy" output.

### ISSUE THREAD

**Issue by zxol** [prisma/prisma#3977] opened 2019-02-02 02:22 UTC
Red text in the console should be reserved for (serious) errors.
Unnecessary heartbeat elevation for your users :)

**Comment by Mercurial** [comment] 2019-02-02 09:46
agreed ahaha!

**Comment by divyenduz** [comment] 2019-02-21 08:22
This is available in the latest `beta` - `1.27.0-beta.12`, please install it via `npm install -g prisma@beta`.

**Comment by divyenduz** [comment] 2019-03-07 17:35
This is available in the latest `stable` - `1.28.0`, please install it via `npm install -g prisma`. I am closing this issue, please open a new issue, if necessary.

**Comment by garmjs** [comment] 2019-03-10 22:01
I'm on prisma/1.28.2 and the red color on the success message is still here, it's better if we change with green

![Screen Shot 2019-03-10 at 10 51 14 PM](https://user-images.githubusercontent.com/5017156/54092109-7e97c680-4388-11e9-9867-f930e66d5958.png)

**Comment by divyenduz** [comment] 2019-03-21 10:54
![image](https://user-images.githubusercontent.com/746482/54747729-f4ddc980-4bcf-11e9-9a29-92832d56e8a2.png)

@garmjs : I am unable to reproduce, are you sure that the command that you are running doesn't yield an error status code or write to `stderr`? Can you please share your `prisma.yml` file or provide a minimal reproduction?

**Comment by garmjs** [comment] 2019-03-21 14:33
@divyenduz I'm not using prisma generate should i use instead of `graphql get-schema -p prisma`, this is prisma.yml file

```
endpoint: ${env:PRISMA_ENDPOINT}
datamodel: datamodel.prisma
hooks:
  post-deploy:
    - graphql get-schema -p prisma
    - graphql codegen
```

**Comment by divyenduz** [comment] 2019-03-21 14:59
@garmjs : Yes, that is recommended, most likely this is a bug in `graphql-cli` and it writes to `stderr` or ends with a non-zero status code. 

Please try a command like `echo "Running post-deploy hook"` using the following `prisma.yml` file to confirm this fix. 

```
endpoint: ${env:PRISMA_ENDPOINT}
datamodel: datamodel.prisma
hooks:
  post-deploy:
    - echo "Running post-deploy hook"
```

if that works without any red lines, please let me know and I will close the issue :) 

Please feel free to open a separate issue in `graphql-cli` package.

**Comment by garmjs** [comment] 2019-03-21 15:11
No red warning when I remove `graphql get-schema -p prisma`,  is there a way to get schema after deploy using Prisma CLI

**Comment by divyenduz** [comment] 2019-03-21 15:16
Yes, please search for `graphql-schema` [here](https://www.prisma.io/docs/prisma-cli-and-configuration/cli-command-reference/prisma-generate-xcv2/#prisma-generate). 

I am closing this issue as the schema generation is a separate topic. 

Please find me on our slack (my handle is `divyenduz`) if you still need help with schema generation.

**Closed by divyenduz** 2019-03-21 15:16 UTC
Labels: area/client, kind/feature
