### ISSUE TITLE
Error in migration engine

### ISSUE THREAD

**Issue by fmbetancourt** [prisma/prisma#11016] opened 2022-01-07 13:22 UTC
Hi Prisma Team! Prisma Migrate just crashed. 

## Command

`db push`

## Versions
      
| Name        | Version            |
|-------------|--------------------|
| Platform    | debian-openssl-1.1.x| 
| Node        | v14.17.6           | 
| Prisma CLI  | 3.7.0              | 
| Engine      | 8746e055198f517658c08a0c426c7eec87f5a85f| 

## Error
```
Error: Error in migration engine.
Reason: [libs/datamodel/connectors/datamodel-connector/src/walker_ext_traits.rs:159:42] internal error: entered unreachable code

Please create an issue with your `schema.prisma` at
https://github.com/prisma/prisma/issues/new

```

**Comment by janpio** [comment] 2022-01-07 18:16
I think this was a duplicate of https://github.com/prisma/prisma/issues/11013 - which is already closed, so this should be fixed in the `dev` version and be released to everyone next Tuesday.

**Closed by janpio** 2022-01-07 18:16 UTC
