### ISSUE TITLE
issue on mongo seeding when user already exist

### ISSUE THREAD

**Issue by kordkheili** [prisma/prisma#19213] opened 2023-05-12 07:35 UTC
//seed.js

```
const users = [
    {
      name: "alireza",
      email: "mkalireza.ir@gmail.com",
      password: "$2a$10$bd9GpPt7oP6LrqcIKYvnRuLjNmMjJnSsgcVI8vye8X61ECHqCT7G2",
    },
  ];
```

```
users.forEach(async (user) => {
    await prisma.user.upsert({
      where: { email: user.email },
      update: {},
      create: {
        name: user.name,
        email: user.email,
        password:
          "$2a$10$bd9GpPt7oP6LrqcIKYvnRuLjNmMjJnSsgcVI8vye8X61ECHqCT7G2",
      },
    });
  });
```

Hi Prisma Team! My Prisma Client just crashed. This is the report:
## Versions

| Name            | Version            |
|-----------------|--------------------|
| Node            | v18.16.0           | 
| OS              | windows            |
| Prisma Client   | 4.13.0             |
| Query Engine    | 1e7af066ee9cb95cf3a403c78d9aab3e6b04f37a|
| Database        | mongodb            |

## Logs
```
prisma:client:libraryEngine:loader Searching for Query Engine Library in D:\WORK\agp-express\node_modules\.prisma\client
prisma:client:libraryEngine:loader loadEngine using D:\WORK\agp-express\node_modules\.prisma\client\query_engine-windows.dll.node
prisma:client:libraryEngine library starting
prisma:client:libraryEngine library started
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client%

**Comment by Jolg42** [comment] 2023-05-12 13:28
@mkalireza-ir is there an error message? How does it look like when it crashes? (is that all in this issue already?)

**Comment by janpio** [comment] 2024-04-29 17:01
Ping @kordkheili, any information to add that would help us reproduce this?

**Comment by jkomyno** [comment] 2024-05-17 12:12
Hi @kordkheili, since we got no reply with information that could help us reproducing this issue, we're closing this issue.
Should you or another user bump into the same problem and provide a reproduction, we will consider reopening this issue. Thanks!

**Closed by jkomyno** 2024-05-17 12:12 UTC
Labels: bug/0-unknown, kind/bug, topic: prisma-client, team/client, topic: basic error report, topic: mongodb, topic: seeding, topic: upsert()
