### ISSUE TITLE
[Prisma5] UniqueInput with more than one unique field

### ISSUE THREAD

**Issue by marticrespi** [prisma/prisma#20619] opened 2023-08-09 12:38 UTC
Hello, when you have an id (PK) and a unique field (code) why in 5 version you must to declare both properties as mandatory? I'm using nestjs and I don't know how can solve it.  The first pic shows the code generated by prisma-generate and it requires id and code (both) but I have my own class as both optional (one or the other) in the second pic. This was working on version 4. Do you know how can I solve it? I can't set both mandatory! If I set both as mandatory, it compiles as expected. It only happens with unique inputs with more than one unique field.

![image](https://github.com/prisma/prisma/assets/6670879/50e94aa2-4aa7-457b-b5d8-b17938c18d87)
![image](https://github.com/prisma/prisma/assets/6670879/31143461-1444-414a-af92-67194ee6f981)
![image](https://github.com/prisma/prisma/assets/6670879/f1f99bcf-dbe5-4d75-a761-8462f532eec1)
![image](https://github.com/prisma/prisma/assets/6670879/08a702da-2ddc-4f00-ba07-af6cb97d3373)
![image](https://github.com/prisma/prisma/assets/6670879/4309ed14-05d9-4c34-867f-dba0cd417f04)

**Comment by Jolg42** [comment] 2023-08-09 13:51
@marticrespi 🤔 To me based on the Prisma schema this is correct as both are required there.
If you want to make `code` optional, then you would need to change it to `String?`. Is that an option for you?

**Comment by Jolg42** [comment] 2023-08-09 14:23
@marticrespi To take a step back, what are you trying to do here? What's the Prisma query you want to do?
It looks like from your screenshot that `prisma.suppliers.findMany()` fails?

Note that `Prisma.AtLeast` actually changes the type, it makes it that either `id` or `code` needs to be provided at a minimum. (you would only get an error if both are not provided)

**Comment by alexandersdickinson** [comment] 2023-08-09 15:09
I'm seeing a similar issue, but using NexusJS instead of NestJS. I think the problem is that there's a mismatch between Prisma generated filter types and filter types created as arguments for query resolvers, which wasn't a problem in older versions of Prisma. In the context of Nexus, if you want to create a query field that just returns a single instance of some entity, e.g. a post, you might write:
```
t.field('post', {
      type: 'Post',
      args: {
        where: arg({ type: nonNull('PostWhereUniqueInput') }),
      },
      resolve: (_, args, context) => {
        return context.prisma.post.findUnique(args)
      },
    })
```
For `args`, you have to then define a Nexus type that mirrors the input type of `findUnique`. `where` in this case should be able to take any unique property defined in the Prisma model, but not all are required, as that wouldn't make sense if you only need one unique identifier to find an instance of something. So your Nexus type might look something like this:
```
const PostWhereUniqueInput = inputObjectType({
  name: "PostWhereUniqueInput",
  definition(t) {
    t.int("id")
    t.string("name")
  }
});
```
This approach is suggested in NexusJS docs for migrating off of nexus-plugin-prisma.

**Comment by marticrespi** [comment] 2023-08-10 05:26
> @marticrespi To take a step back, what are you trying to do here? What's the Prisma query you want to do? It looks like from your screenshot that `prisma.suppliers.findMany()` fails?
> 
> Note that `Prisma.AtLeast` actually changes the type, it makes it that either `id` or `code` needs to be provided at a minimum. (you would only get an error if both are not provided)

This is the idea, but I have to set my `SupplierWhereUniqueInput` with both properties as mandatories to skip the error, and It's not the right way. For example, I set both in `SupplierWhereUniqueInput` as optional (first message), as you said, findMany fails showing me the error `Property 'id' is optional in type 'PartnerWhereUniqueInput' but required in type '{ id: string | number; odooCode: string | number; orgCode: string | number; }'.`

![image](https://github.com/prisma/prisma/assets/6670879/e57801ec-b3bc-4af5-862d-4121ff53931c)


If I set both as mandatory, all the errors disappear.

![image](https://github.com/prisma/prisma/assets/6670879/1bae9558-1f09-4ada-adb1-418b4bb798ea)

![image](https://github.com/prisma/prisma/assets/6670879/d6aca787-7d82-4a07-8b3b-e72160ea6d28)


But I cant do that, because when it generates the schema and you want you use findUnique for example, grapqhl validity fails (as expected) because you set both as mandatory, to use this uniqueInput or you send both properties or fails. You are talking about `.AtLeast` and I think it should throw an error if you dont send one or other field, but it's actually validating that you have 
set as mandatory both properties, and it shouldn't. This code was working like a charm on 4.11.0! 😢 



> @marticrespi 🤔 To me based on the Prisma schema this is correct as both are required there. If you want to make `code` optional, then you would need to change it to `String?`. Is that an option for you?

I can't set code as `String?` in the model file, is a strong field in database and not null, only is in the `filter` because there are more than one that is unique. I have more UniqueInputs that only has ID (as PK) and they has no problem.

**Comment by Jolg42** [comment] 2023-08-10 10:32
Something that needs to be clarified: what do you mean exactly by an older version of Prisma? Please give a full version.

**Comment by Jolg42** [comment] 2023-08-10 10:34
> This code was working like a charm on 4.14.0! 😢
@marticrespi do you mean that this is the last version that works for you? Did you try `4.15.0` & `4.16.2`?

**Comment by marticrespi** [comment] 2023-08-10 11:58
Sorry with 4.14.0 version works well, it's a bug or change on 5.x version!

**Comment by Jolg42** [comment] 2023-08-10 13:31
If this started with 5.0.0 then I guess the suspect is `extendedWhereUnique` going GA here.

**Comment by marticrespi** [comment] 2023-08-11 04:56
Yes as @shane-abcya confirms, it throws same error on 4.14.0 with `extendedWhereUnique` feature. Thanks!

**Comment by shawnjones253** [comment] 2023-08-15 02:33
FYI, this breaks a lot of the functionality in the typegraphql-prisma integration

**Comment by marticrespi** [comment] 2023-08-16 05:37
@shawnjones253 sure, I'm using nestjs generating all classes with typegraphql-prisma plugin. Waiting if it will be solved in the next version.

**Comment by marticrespi** [comment] 2023-08-24 04:46
I wanted to try it when I saw the new release, but I read your message before :(  If this bug is not fixed, I can't update to 5 version.

**Comment by isaacpz** [comment] 2023-09-19 02:09
This is also preventing us from upgrading to the latest Prisma version. Looks like [users of prisma-nestjs-graphql](https://github.com/unlight/prisma-nestjs-graphql/issues/177) are also impacted

**Comment by marticrespi** [comment] 2023-09-19 07:35
If they work with tags/labels to filter and fixing bugs, they should change bug1-unconfirmed tag because is more than confirmed.  Any news @Jolg42?

**Comment by janpio** [comment] 2023-09-19 21:06
No it is not, as that would require someone from the team to confirm the problem themselves. That has not happened, so the label is correct.

**Comment by alexandersdickinson** [comment] 2023-10-09 18:28
This no longer seems to be an issue for us.

**Comment by SheaBelsky** [comment] 2023-10-09 18:40
@alexandersdickinson What version of Prisma are you on? Did this get fixed in 5.4.2?

**Comment by alexandersdickinson** [comment] 2023-10-09 18:59
@SheaBelsky 5.4.1

**Comment by alexandersdickinson** [comment] 2023-10-09 20:20
Turns out I was incorrect about this being fixed. This problem is still present for version 5.4.2, as well.

**Comment by SheaBelsky** [comment] 2023-10-09 23:25
Is it fixed for you in 5.4.1 and broken in 5.4.2? Or broken in all 5.x versions?

**Comment by alexandersdickinson** [comment] 2023-10-10 03:27
@SheaBelsky All 5.x versions.

**Comment by SevInf** [comment] 2023-10-13 14:42
Hey, everyone. I believe the confusion here comes from misreading what `Prisma.AtLeast` means. 

```ts
Prisma.AtLeast<{ id?: number, email?: string }, 'id' | 'email' >
```

This does not mean that both `id`` and `email` are required. This means that *either* `id` or `email` is required. So, the following inputs are valid:

- specifying only `id`
- specifying only `email`
- specifying both `id` and `email`

The only thing that is disallowed is omitting both fields.

Now, tricky part here is that this kind of validation is not expressible in GraphQL directly. You have 2 choices:

1. Make both fields optional and rely on runtime error:

```ts
@InputType()
export class UserWhereUniqueInput {
  @Field((type) => Int)
  id: number | undefined;

  @Field((type) => String)
  @IsEmail()
  email: string | undefined;
}

@Resolver(User)
class UserResolver {
  @Query((returns) => User, { nullable: true })
  user(@Args('where') where: UserWhereUniqueInput) {
    ensureAtLeast(where, ['id', 'email'])
    return this.prismaService.user.findUnique({
      where,
    });
  }
}

function ensureAtLeast<T extends object, K extends keyof T & string>(
  value: T,
  keys: Array<K>,
): asserts value is Prisma.AtLeast<T, K> {
  for (const key of keys) {
    if (value[key] != null) {
      return;
    }
  }
  throw new Error(`Expected at least one of the keys set: ${keys.join(', ')}`);
}
```
It's important that ` | undefined` is a part of field type's definition: `null` will be treated as DB level `NULL` and won't work in this case.

Upside of this option is that the shape of your GraphQL query will match the shape of Prisma query. Downside is, validation rule about at least one unique field being present in the query is not enforced on a type level.

2. Split extra options into separate arguments and have one query per unique input:

```ts
@InputType()
export class UserByIdExtraInput {
  @Field((type) => String)
  @IsEmail()
  email: string | undefined;
}

@InputType()
export class UserByEmailExtraInput {
  @Field((type) => Int)
  id: number | undefined;
}

@Resolver(User)
class UserResolver {
  @Query((returns) => User, { nullable: true })
  userById(
    @Args('id', { type: () => Int }) id: number,
    @Args('where', { nullable: true }) where?: UserByIdExtraInput,
  ) {
    return this.prismaService.user.findUnique({
      where: {
        id,
        ...where,
      },
    });
  }

  @Query((returns) => User, { nullable: true })
  userByEmail(
    @Args('email') email: string,
    @Args('where', { nullable: true }) where?: UserByEmailExtraInput,
  ) {
    return this.prismaService.user.findUnique({
      where: {
        email,
        ...where,
      },
    });
  }
}
```

Advantages and disadvantages of this variant are opposite of option 1: you'd get the valid input enforced on type level, but it would be slightly different from how prisma query looks like.

**Comment by SevInf** [comment] 2023-10-14 06:52
Just couple of additions to what is said above:

1. If `@ts-ignore` is acceptable in your codebase, putting it above `where` line would essentially achieve what I suggested as option 1: Prisma still performs validation in runtime and will throw the exception if input contains no unique fields at all.
2. If you are not using any GraphQL frameworks and still experience the issues - please, let us know.

**Comment by marticrespi** [comment] 2023-10-20 09:13
> Hey, everyone. I believe the confusion here comes from misreading what `Prisma.AtLeast` means.
> 
> ```ts
> Prisma.AtLeast<{ id?: number, email?: string }, 'id' | 'email' >
> ```
> 
> This does not mean that both `id` and `email` are required. This means that _either_ `id` or `email` is required. So, the following inputs are valid:
> 
> * specifying only `id`
> * specifying only `email`
> * specifying both `id` and `email`
> 
> The only thing that is disallowed is omitting both fields.
> 
> Now, tricky part here is that this kind of validation is not expressible in GraphQL directly. You have 2 choices:
> 
> 1. Make both fields optional and rely on runtime error:
>    ```ts
>    @InputType()
>    export class UserWhereUniqueInput {
>      @Field((type) => Int)
>      id?: number;
>    
>      @Field((type) => String)
>      @IsEmail()
>      email?: string;
>    }
>    
>    @Resolver(User)
>    class UserResolver {
>      @Query((returns) => User, { nullable: true })
>      user(@Args('where') where: UserWhereUniqueInput) {
>        ensureAtLeast(where, ['id', 'email'])
>        return this.prismaService.user.findUnique({
>          where,
>        });
>      }
>    }
>    
>    function ensureAtLeast<T extends object, K extends keyof T & string>(
>      value: T,
>      keys: Array<K>,
>    ): asserts value is Prisma.AtLeast<T, K> {
>      for (const key of keys) {
>        if (value[key] != null) {
>          return;
>        }
>      }
>      throw new Error(`Expected at least one of the keys set: ${keys.join(', ')}`);
>    }


I'm using Nestjs+Prisma and I was using in 4.x.x option 1 (without ensureAtLeast), but is not possible right now. Compilation throws an error.

![image](https://github.com/prisma/prisma/assets/6670879/4623af9f-55a8-4108-8136-3b86c8b2c268)

As you can see I have both properties as optional in whereUniqueInput and a global getSupplier and its throw an error saying this:

![image](https://github.com/prisma/prisma/assets/6670879/72e8068a-975a-4e9b-b1ad-a7be574e0b45)

And the code generated by prisma with `prisma-generate` about this input is here:

![image](https://github.com/prisma/prisma/assets/6670879/adac6a4d-add3-4ec0-8b6b-0062c3b903bc)

So I don't understand why it's telling me that is required by the prisma generated type because it has both properties as optional. If I put one property on my input as mandatory, all errors dissapear. But I can't do that because I use `code first` approach (nestjs has schema or code first approach and I use the second where you define the classes and then the framework generate the schema.gql file automatically when compiles) and if I do that it will generate the schema with some property input as mandatory and that's not real.

**Comment by marticrespi** [comment] 2023-10-27 04:50
> You are getting the error because if both fields are optional, it implies that suppplying neither `id` nor `code` is a valid input. It is not and the code won't compile until you ensure that at least one of those fields is set.

Hi @SevInf I understand it, but how can I set the properties to compile without set as mandatory any field and then check it with `ensureAtLeast` function? As you in option 1, you have one input with these two properties as optional and checking by `ensureAtLeast`, that's what I need and I tried in my previous post example.

Thanks!

**Comment by marticrespi** [comment] 2023-10-27 05:42
Hi @SevInf , I have all gets resolved with ensureAtLeast function, but I have problems with create nested entities. For example, I have an entity called BillingAccount that is from a Partner, and then, when I have to create one, I need to pass Partner>connect object (it's a PartnerWhereUniqueInput as in get function) but it doesn't work.

In get function works and compiles

![image](https://github.com/prisma/prisma/assets/6670879/18ea52c6-a242-4514-afd3-e07929350c5a)

But in create nested entity doenst work in the same way

![image](https://github.com/prisma/prisma/assets/6670879/3ea2f71f-2b45-4373-93f5-3a276a76c05b)

Here I try to ensure that createInput>Partner>Connect (PartnerWhereUniqueInput with 3 unique properties)

**Comment by marticrespi** [comment] 2023-11-07 05:46
@SevInf any help? I don't understand why it doesn't work in the same way..

**Comment by SevInf** [comment] 2023-11-07 15:38
@marticrespi Try splitting `connect` into separate variable:

```ts
const connect = data?.Partner?.connect
ensureAtLeast(connect, ['id'])
await prisma.billingAccount.create({
   data: {
      ...data
      Partner: {
         ...data.Partner
         connect,
      }
   }
})
```

I would also kindly ask you to post your code as [copy-pasteble text blocks](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks), rather than screenshots - it makes it much easier for other to try it out and refine. Thank you!

**Comment by shawnjones253** [comment] 2023-12-19 23:54
@SevInf  is there any way to programmatically get the unique field names for a prisma type, so that i can use `ensureAtLeast` without manually listing the field names (hoping to at least make this automated for where the schema changes)

**Comment by Weakky** [comment] 2024-01-19 14:37
Since the original topic is not a bug and the issue has shifted towards GraphQL-related schema design issues, I'm now closing the issue. 

If you need any more help, please open a GitHub discussion. Thanks! 🙏

**Closed by Weakky** 2024-01-19 14:37 UTC
Labels: bug/1-unconfirmed, kind/bug, topic: prisma-client, topic: client types, team/client, topic: extendedWhereUnique, topic: unique, 5.0.0
