### ISSUE TITLE
Error: Error creating a database connection. 0: sql_migration_connector::flavour::mssql::connection::describe_schema

### ISSUE THREAD

**Issue by Giarry156** [prisma/prisma#18244] opened 2023-03-07 11:36 UTC
### Bug description

I'm trying to pull a database schema from an MS SQL Server service with a connection string like this:
"sqlserver://host:port;user=username;password=password;trustServerCertificate=true;database=database_name;"

When I try to do an npx prisma db pull, I get this error:
```
Error: Error creating a database connection.
   0: sql_migration_connector::flavour::mssql::connection::describe_schema
           with namespaces=None
             at migration-engine\connectors\sql-migration-connector\src\flavour\mssql\connection.rs:27
```

### How to reproduce

The situation is this:
I have a multi-prisma schema project and one of these is used to apply on its migrations etc. When I have completed my changes I push them on the other schemas.
I created .bak files of the database's subject of pushes, not migrated, and restored them on another server.
Then I instantiated on another server a service that must use those databases. At this point, I need their schema but I find the bug described in the previous paragraph.

### Expected behavior

When I pull schema the .prisma schema file must be filled with the db schema.

### Prisma information

```prisma
I can't reach this point.
```

```ts
I can't reach this point.
```

### Environment & setup

- OS: Windows Server 2019
- Database: MS SQL Server
- Node.js version: 19.7.0

### Prisma Version

```
prisma                  : 4.11.0
@prisma/client          : 4.11.0
Current platform        : windows
Query Engine (Node-API) : libquery-engine 8fde8fef4033376662cad983758335009d522acb (at ..\..\..\..\AppData\Roaming\npm\node_modules\prisma\node_modules\@prisma\engines\query_engine-windows.dll.node)
Migration Engine        : migration-engine-cli 8fde8fef4033376662cad983758335009d522acb (at ..\..\..\..\AppData\Roaming\npm\node_modules\prisma\node_modules\@prisma\engines\migration-engine-windows.exe)
Format Wasm             : @prisma/prisma-fmt-wasm 4.11.0-57.8fde8fef4033376662cad983758335009d522acb
Default Engines Hash    : 8fde8fef4033376662cad983758335009d522acb
Studio                  : 0.483.0
```

**Comment by janpio** [comment] 2024-05-23 16:14
> I'm trying to pull a database schema from an MS SQL Server service with a connection string like this:
> "sqlserver://host:port;user=username;password=password;trustServerCertificate=true;database=database_name;"

That connection string looks pretty standard, and is what Prisma usually uses for SQL Server. 
Did you have this problem only with this database server and connection string and could work with other SQL Server instances, or was this a general problem?

Right now this would not be enough information for us to do anything with this issue. Can you please provide some additional information that might help us @Giarry156? Thanks.

**Comment by SevInf** [comment] 2024-06-20 08:44
Hey @Giarry156 ,

Did you get a chance to have a look at my collegues comment? It'd be helpful for us to move your issue forward.

Without further information, we'll have to close this issue. Thank you 🙏

**Comment by jkomyno** [comment] 2024-07-10 12:30
We're closing this issue due to inactivity. Please leave a comment below, ideally with a reproduction repository, if you have more actionable feedback about this issue. Thanks!

**Closed by jkomyno** 2024-07-10 12:30 UTC
Labels: bug/0-unknown, kind/bug, topic: sql server, domain/schema, topic: prisma db pull
