### ISSUE TITLE
Using relation fields as ID on a Prisma model doesn't work

### ISSUE THREAD

**Issue by martineboh** [prisma/prisma#1884] opened 2020-03-19 17:37 UTC
@nikolasburk  The example given in the release `2.0.0-preview024`: **Use relation fields as ID on a Prisma model** didn't work when I added directly to my **schema.prisma** file.
`prisma2@2.0.0-preview023, binary version: d3b0ceed5d87544b9d2decb70e08664f9047bb73`
```
generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

model Movie {
  director Director @id
  title    String
}

model Director {
  id Int @id @default(autoincrement())
  name String
}
```

**throws Error:**

```
 ERROR  Oops, an unexpected error occured!
Failure during a migration command: Connector error. (error: Error querying the database: Error querying the database: Error querying the database: db error: ERROR: foreign key constraint "Movie_director_fkey" cannot be implemented)

Please help us improve Prisma 2 by submitting an error report.
Error reports never contain personal or other sensitive information.
Learn more: https://pris.ly/d/telemetry
```

**Comment by pantharshit00** [comment] 2020-03-23 17:56
I am unable to reproduce the issue with migrate in preview024 and as well as in preview023.

I was also able to query the data in preview024. It doesn't work in preview023 as expected as support for this feature was released in preview024.

So please try again this with a fresh database using preview024.

**Comment by pantharshit00** [comment] 2020-07-24 12:03
@martineboh I am going to close this as its been 3 months now and there is no activity here. 

Please reply if you want us to take another look.

**Closed by pantharshit00** 2020-07-24 12:03 UTC
Labels: bug/0-needs-info, kind/bug, status/needs-action

**Comment by FrankSandqvist** [comment] 2020-10-26 11:39
I'm getting this error with this model. I believe there are no errors here

```
model FormPipeline {
  id                              String            @id @default(uuid())
  slug                            String
  title                           String
  salesDomainId                   String
  salesDomain                     SalesDomain       @relation(fields: [salesDomainId], references: [id])
  body                            Json
  changedAt                       DateTime
  formPipelineDependencyIds       String[]
  formPipelineDependencies        FormPipeline[]    @relation("FormPipelineFormPipelineDependency", fields: [formPipelineDependencyIds])
  processPipelineDependencies     ProcessPipeline[]
  constantDependencies            Constant[]
  tableDependencies               Table[]           @relation("FormPipelineTableDependency")
  dependantFormPipelineIds        String[]
  dependantFormPipelines          FormPipeline[]    @relation("FormPipelineFormPipelineDependency", fields: [dependantFormPipelineIds])
  dependantOfferingsAsPayload     Offering[]        @relation("OfferingPayloadFormPipelineDependency")
  dependantOfferingsAsQuoteResult Offering[]        @relation("OfferingQuoteResultFormPipelineDependency")
  dependantOfferingsAsOrderResult Offering[]        @relation("OfferingOrderResultFormPipelineDependency")
}
```

**Comment by janpio** [comment] 2020-10-26 13:08
Please open a new issue @FrankSandqvist and we are happy to look into this. Tjanks.
