### ISSUE TITLE
PANIC in query-engine

### ISSUE THREAD

**Issue by franciscocamposchimal** [prisma/prisma#5159] opened 2021-01-18 17:38 UTC
Hi Prisma Team! My Prisma Client just crashed. This is the report:
## Versions

| Name            | Version            |
|-----------------|--------------------|
| Node            | v12.18.3           | 
| OS              | darwin             |
| Prisma Client   | 2.15.0-dev.15      |
| Query Engine    | query-engine c9c2ad73afb6d3375f265c44f1a172eff67300dc|
| Database        | Postgres|

## Query
```
query {
  findManyNote(
    where: {
      AND: [
        {
          enterprise: {
            id: "X"
          }
        }
      ]
    }
    orderBy: [
      {
        createdAt: desc
      }
    ]
  ) {
    id
    content
    type
    userTags {
      id
    }
    contact {
      id
      name
    }
    company {
      id
      name
    }
    deal {
      id
      title
    }
    user {
      id
      user {
        id
        name
        lastName
      }
    }
    createdAt
  }
}
```

## Logs
```
0m    '/tmp/prisma-d497e9feccaa268e6b1192b1.sock'
  engine   ]
  engine }  
  engine stdout  Starting a postgresql pool with 9 connections.  
  engine stdout  Started http server on http+unix:///private/tmp/prisma-d497e9feccaa268e6b1192b1.sock  
  engine Search for Query Engine in /Users/danielcampos/Desktop/cervus-project/back-cervus/prisma/.prisma/client  
  engine Search for Query Engine in /Users/danielcampos/Desktop/cervus-project/back-cervus/prisma/generated/client  
  plusX Execution permissions of /Users/danielcampos/Desktop/cervus-project/back-cervus/prisma/generated/client/query-engine-darwin are fine  
  engine Client Version: 2.15.0-dev.15  
  engine Engine Version: query-engine c9c2ad73afb6d3375f265c44f1a172eff67300dc  
  engine Active provider: postgresql  
  engine stdout  PANIC in query-engine/core/src/interpreter/query_interpreters/nested_read.rs:78:56
1  +3m
  engine TypeError: this.currentRequestPromise.cancel is not a function
  engine     at NodeEngine.handlePanic (/Users/danielcampos/Desktop/cervus-project/back-cervus/prisma/generated/client/runtime/index.js:26395:36)
  engine     at NodeEngine.setError (/Users/danielcampos/Desktop/cervus-project/back-cervus/prisma/generated/client/runtime/index.js:26341:16)
  engine     at LineStream.<anonymous> (/Users/danielcampos/Desktop/cervus-project/back-cervus/prisma/generated/client/runtime/index.js:26636:24)
  engine     at LineStream.emit (events.js:315:20)
  engine     at addChunk (_stream_readable.js:295:12)
  engine     at readableAddChunk (_stream_readable.js:271:9)
  engine     at LineStream.Readable.push (_stream_readable.js:212:10)
  engine     at LineStream.Transform.push (_stream_transform.js:152:32)
  engine     at LineStream._pushBuffer (/Users/danielcampos/Desktop/cervus-project/back-cervus/prisma/generated/client/runtime/index.js:23721:19)
  engine     at LineStream._transform (/Users/danielcampos/Desktop/cervus-project/back-cervus/prisma/generated/client/runtime/index.js:23715:10)
  engine     at LineStream.Transform._read (_stream_transform.js:191:10)
  engine     at LineStream.Transform._write (_stream_transform.js:179:12)
  engine     at doWrite (_stream_writable.js:403:12)
  engine     at writeOrBuffer (_stream_writable.js:387:5)
  engine     at LineStream.Writable.write (_stream_writable.js:318:11)
  engine     at Socket.ondata (_stream_readable.js:716:22)
  engine     at Socket.emit (events.js:315:20)
  engine     at addChunk (_stream_readable.js:295:12)
  engine     at readableAddChunk (_stream_readable.js:271:9)
  engine     at Socket.Readable.push (_stream_readable.js:212:10)
  engine     at Pipe.onStreamRead (internal/stream_base_commons.js:186:23)  {"timestamp":"Jan 18 11:30:55.546","level":"ERROR","fields":{"message":"PANIC","reason":"1","file":"query-engine/core/src/interpreter/query_interpreters/nested_read.rs","line":78,"column":56},"target":"query_engine"}  
  engine {
  engine   error: SocketError: other side closed
  engine       at Socket.onSocketEnd (/Users/danielcampos/Desktop/cervus-project/back-cervus/prisma/generated/client/runtime/index.js:24818:25)
  engine       at Socket.emit (events.js:327:22)
  engine       at endReadableNT (_stream_readable.js:1220:12)
  engine       at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  engine     code: 'UND_ERR_SOCKET'
  engine   }
  engine }  
  engine {
  engine   error: Error: connect ECONNREFUSED /tmp/prisma-d497e9feccaa268e6b1192b1.sock
  engine       at PipeConnectWrap.afterConnect [as oncomplete] (net.js:1141:16) {
  engine     errno: 'ECONNREFUSED',
  engine     code: 'ECONNREFUSED',
  engine     syscall: 'connect',
  engine     address: '/tmp/prisma-d497e9feccaa268e6b1192b1.sock'
  engine   }
  engine }  
  engine {
  engine   error: Error: connect ECONNREFUSED /tmp/prisma-d497e9feccaa268e6b1192b1.sock
  engine       at PipeConnectWrap.afterConnect [as oncomplete] (net.js:1141:16) {
  engine     errno: 'ECONNREFUSED',
  engine     code: 'ECONNREFUSED',
  engine     syscall: 'connect',
  engine     address: '/tmp/prisma-d497e9feccaa268e6b1192b1.sock'
  engine   }
  engine }  
```

## Client Snippet
```ts
await this.prisma.note.findMany({
            ...options,
            select: {
                id: true,
                content: true,
                type: true,
                userTags: { select: { id: true } },
                contact: { select: { id: true, name: true } },
                company: { select: { id: true, name: true } },
                deal: { select: { id: true, title: true } },
                user: {
                    select: {
                        id: true,
                        user: { select: { id: true, name: true, lastName: true } },
                    },
                },
                createdAt: true,
            }
        });
```

## Schema
```prisma
model Note {
  id               String      @id @default(cuid())
  content          String?
  type             Json[]
  companyId        String?     
  contactId        String?     
  dealId           String?     
  enterpriseId     String?     
  userEnterpriseId String?     
  company      Company?         @relation(fields: [companyId], references: [id])
  contact      Contact?         @relation(fields: [contactId], references: [id])
  deal         Deal?            @relation(fields: [dealId], references: [id])
  enterprise   Enterprise?      @relation(fields: [enterpriseId], references: [id])
  user         UserEnterprise?  @relation(fields: [userEnterpriseId], references: [id])
  comments     NoteComment[]   
  userTags     UserEnterprise[] @relation("commentsByUser")
  isDelete     Boolean?         @default(false)
  modifiedBy    Int?
  createdBy    Int?
  createdAt    DateTime         @default(now())
  updatedAt    DateTime         @updatedAt
}

model UserEnterprise {
  id                     String                  @id @default(cuid())
  jobTitle               String?
  signature              String?                 @default("")
  emailTemplatesOrder    String[]
  isActive               TypeAccount  
  enterpriseId           String?                              
  groupId                String?                              
  planId                 String?                              
  roleId                 String?                              
  suscriptionId          String?                              
  userId                 String?                              
  enterprise             Enterprise?              @relation(fields: [enterpriseId], references: [id])
  group                  Group?                   @relation(fields: [groupId], references: [id])
  plan                   Plan?                    @relation(fields: [planId], references: [id])
  role                   Role?                    @relation(fields: [roleId], references: [id])
  suscription            Suscription?             @relation(fields: [suscriptionId], references: [id])
  user                   User?                    @relation(fields: [userId], references: [id])
  companies              Company[]
  contacts               Contact[]
  filters                 CustomFilter[]
  deals                  Deal[]
  notes                  Note[]                   @relation("commentsByUser")
  noteComments           NoteComment[]            @relation("noteCommentsByUser")
  emailTemplates         EmailTemplate[]
  events                 Event[]
  headers                HeaderSetting[]
  integrations           Integration[]
  suscriptionsStandBy    SuscriptionStandBy[]
  noteCommentTags        NoteComment[]                  
  noteTags               Note[]
  isDelete               Boolean?                   @default(false)
  modifiedBy              Int?
  createdBy              Int?
  createdAt              DateTime                   @default(now())
  updatedAt              DateTime                   @updatedAt
}

```

**Comment by pantharshit00** [comment] 2021-01-29 14:20
Hey @franciscocamposchimal 

This should be fixed in 2.16 via https://github.com/prisma/prisma-engines/pull/1495

Closing as duplicate of https://github.com/prisma/prisma/issues/5092

**Closed by pantharshit00** 2021-01-29 14:20 UTC
