### ISSUE TITLE
Running queries in Promise.all() leads to idle zombie database sessions

### ISSUE THREAD

**Issue by mmahdigh** [prisma/prisma#24552] opened 2024-06-16 18:36 UTC
### Bug description

So Below you see two instances of writing a logic. One uses `Promise.all()` parallelly and the other is sequential.

```ts
  @Get('/test/pa2')
  async testtest2() {
    const userId = 48;
    const collectionId = 170;

    const [variable1, variable2, variable3, variable4, variable5, variable6] =
      await Promise.all([
        this.flowService.isCollectionAttested(userId, collectionId),
        this.flowService.isCollectionFinished(userId, collectionId),
        this.flowService.hasThresholdVotes(collectionId, userId),
        this.flowService.isCollectionStarted(userId, collectionId),
        this.flowService.isCollectionFiltered(userId, collectionId),
        this.prismaService.projectInclusion.findFirst({
          where: { userId, project: { parentId: collectionId } },
        }),
      ]);
    return { variable1, variable2, variable3, variable4, variable5, variable6 };
  }

```

```ts
  @Get('/test/pa')
  async testtest() {
    const userId = 48;
    const collectionId = 170;

    const variable1 = await this.flowService.isCollectionAttested(
      userId,
      collectionId,
    );
    const variable2 = await this.flowService.isCollectionFinished(
      userId,
      collectionId,
    );
    const variable3 = await this.flowService.hasThresholdVotes(
      collectionId,
      userId,
    );
    const variable4 = await this.flowService.isCollectionStarted(
      userId,
      collectionId,
    );
    const variable5 = await this.flowService.isCollectionFiltered(
      userId,
      collectionId,
    );
    const variable6 = await this.prismaService.projectInclusion.findFirst({
      where: { userId, project: { parentId: collectionId } },
    });

    return { variable1, variable2, variable3, variable4, variable5, variable6 };
  }
```

Now here are the database sessions after calling the first version endpoint:

![Screenshot 2024-06-16 at 9 53 22 PM](https://github.com/prisma/prisma/assets/46849131/d4b0ed50-748a-44b1-b6ec-fe80445e32a3)

And now the second version:

![Screenshot 2024-06-16 at 9 56 53 PM](https://github.com/prisma/prisma/assets/46849131/11d42ebc-d079-4484-a228-63494858dadf)

And until I close my node.js application, these database sessions will stay idle.

### How to reproduce

You can see the codebase in here: https://github.com/GeneralMagicio/pw-backend

### Expected behavior

It's expected that the connections will be released. After 10-20 of these endpoints are called, PostgreSQL's maximum database session limit (i.e., `100`) will be reached.

### Prisma information

It's not needed I guess.

### Environment & setup

- OS: macOS
- Database: PostgreSQL
- Node.js version: 22.1.0

### Prisma Version

```
prisma: 5.0.0
```

**Comment by SevInf** [comment] 2024-06-17 10:22
Hi @mmahdigh .
I suggest you check out our [connection pooling docs](https://www.prisma.io/docs/orm/prisma-client/setup-and-configuration/databases-connections/connection-pool). What you observing is an expected behavior: prisma keeps a capped pool of open DB connections and tries to reuse them as much as possible instead of opening new connection for every request.

- before starting a query, we will check if there is a free connection in the pool. If there is one, it will be used. If there is none and the limit is not reached, new one will be opened. If the limit is reached, request will be queued.
- after query is done, connection will be returned to the pool.

So, when you execute connections sequentially, only one connection is used, after each request it gets returned to the pool and can be reused for the next query. When you are executing queries in parallel, however, multiple connections would need to be opened. 

If you are getting an error from your database telling you that connection limit is reached, you'd need to configure `connection_limit` parameter in your DB connection string to match Postgres settings. So, if your Postgres is configured to accept no more than 100 connection, your connection string will need to reflect that as well `postgres://example.com/db?connection_limit=100` (or below)

**Comment by SevInf** [comment] 2024-06-17 10:23
Since there is no bug here, I am closing the issue. Feel free to open [a discussion](https://github.com/prisma/prisma/discussions) if you need further help configuring connection pool.

**Closed by SevInf** 2024-06-17 10:23 UTC
Labels: kind/bug
