### ISSUE TITLE
Prisma + Docker =  Query engine library for current platform "linux-arm64-openssl-1.1.x" could not be found.

### ISSUE THREAD

**Issue by allangrds** [prisma/prisma#17680] opened 2023-02-01 15:00 UTC
### Bug description

When I run `docker-compose up`, after up postgres container and api container, the error bellow appears:

![Captura de Tela 2023-02-01 às 11 57 08](https://user-images.githubusercontent.com/4103305/216077843-566e2067-1137-4bb7-95e0-d991114ea977.png)

### How to reproduce

**Dockerfile**
```dockerfile
FROM node:18 As development

# Required for Prisma Client to work in container
RUN apt-get update && apt-get install -y openssl

WORKDIR /usr/src/app

COPY --chown=node:node package*.json ./

RUN npm ci

COPY --chown=node:node . .

RUN npm run prisma:generate

USER node
```

**docker-compose**
```yml
services:
  api:
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
      - .:/usr/src/app
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}?schema=public
    command: npm run start:dev
    ports:
      - 3000:3000
    depends_on:
      - postgres
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - 5432:5432
    volumes:
      - docker-nest-postgres:/var/lib/postgresql/data

volumes:
  docker-nest-postgres:
```

### Expected behavior

To generate prisma client correctly.

### Prisma information

```prisma
// This is your Prisma schema file,
// learn more about it in the docs: https://pris.ly/d/prisma-schema

generator client {
  provider = "prisma-client-js"
  binaryTargets = ["native", "darwin-arm64", "linux-musl", "linux-arm64-openssl-1.1.x"]
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

model Notification {
  id          String    @id
  recipientId String
  content     String
  category    String
  readAt      DateTime?
  createdAt   DateTime  @default(now())
  updatedAt   DateTime  @default(now())

  @@index([recipientId])
}

```

### Environment & setup

- OS: macOS Ventura 13.2, M1 Pro

### Prisma Version

```
"@prisma/client": "^4.9.0",
"prisma": "^4.9.0",
```

**Comment by allangrds** [comment] 2023-02-01 17:23
Hi @aqrln.

1. I'm receiving this error message althought inserted `linux-arm64-openssl-1.1.x` inside `binaryTargets`.
2. Yes. Why?

**Comment by mcbethio** [comment] 2023-02-13 12:02
Hey @allangrds,

We're just trying to reproduce and it worked ok for us. We did however notice that re-running `docker-compose up` did not regenerate prisma client because the generate command in your example is only in the Dockerfile and it is not rebuilt when using docker-compose. 

We worked around it by changing line 12 in your docker-compose file to also contain the prisma:generate command like 
`command: sh -c "npm run prisma:generate && npm run start:dev"`

Our theory is that you added the binaryTarget after you had run docker-compose initially and the generate command was not run afterwards.

Please can you try that and see what you get?

**Comment by daviddalmaso** [comment] 2023-03-17 00:11
I ran into this issue as well. It was being caused by mounting my current directory into the container, similar to what you did with this line
```
    volumes:
      - .:/usr/src/app
```

The issue is that the docker container kept picking up the prisma client generated on my host. The workaround for me was to ignore the `node_modules` directory when doing the mounting, so I changed the volumes section to look like this
```
    volumes:
      - .:/usr/src/app
      - /user/src/app/node_modules
```
(credit https://stackoverflow.com/questions/29181032/add-a-volume-to-docker-but-exclude-a-sub-folder for excluding that folder)

**Comment by millsp** [comment] 2023-05-16 20:25
Hey @allangrds, since we did not hear back from you, I will close this issue. That said, we will be improving in this area, so you will be provided better and more useful errors in the future. We can always re-open this issue if you provide us with more [info](https://github.com/prisma/prisma/issues/17680#issuecomment-1427825624). Thanks.

**Closed by millsp** 2023-05-16 20:25 UTC
Labels: bug/0-unknown, kind/bug, team/client, topic: arm, topic: docker, topic: NestJS, topic: Query engine ... could not be found.

**Comment by Rudrava-fleapo** [comment] 2023-09-25 09:20
> I ran into this issue as well. It was being caused by mounting my current directory into the container, similar to what you did with this line
> 
> ```
>     volumes:
>       - .:/usr/src/app
> ```
> 
> The issue is that the docker container kept picking up the prisma client generated on my host. The workaround for me was to ignore the `node_modules` directory when doing the mounting, so I changed the volumes section to look like this
> 
> ```
>     volumes:
>       - .:/usr/src/app
>       - /user/src/app/node_modules
> ```
> 
> (credit https://stackoverflow.com/questions/29181032/add-a-volume-to-docker-but-exclude-a-sub-folder for excluding that folder)

Hey this works, Thanks
