### ISSUE TITLE
Object with null value missing when using findMany and filtering using "not" lookup

### ISSUE THREAD

**Issue by nilsdet** [prisma/prisma#11648] opened 2022-02-05 10:00 UTC
### Bug description

I want to use the "not" lookup in findMany to exclude objects whose attribute is not a specific value, like this:

```typescript
const viewerId = 1;

await prisma.product.findMany({
    where: { userId: { not: viewerId } }
})
```

This currently returns only products whose userId is set to another user's id, **but not those whose userId is set to null.**

### How to reproduce

1. Go to https://codesandbox.io/s/prisma-null-values-issue-hpmtr?file=/package.json
2. Open a terminal
3. Run `yarn start`
4. See failed assertion

### Expected behavior

I would expect filtering by `{ userId: { not: 1 } }` would return every object whose userId is not 1.

### Prisma information

See codesandbox reproduction.

### Environment & setup
- OS: Debian GNU/Linux 10 (buster)
- Database: SQLite
- Node.js version: v14.18.1

### Prisma Version

```
prisma                  : 3.9.1
@prisma/client          : 3.9.1
Current platform        : debian-openssl-1.1.x
Query Engine (Node-API) : libquery-engine bcc2ff906db47790ee902e7bbc76d7ffb1893009 (at node_modules/@prisma/engines/libquery_engine-debian-openssl-1.1.x.so.node)
Migration Engine        : migration-engine-cli bcc2ff906db47790ee902e7bbc76d7ffb1893009 (at node_modules/@prisma/engines/migration-engine-debian-openssl-1.1.x)
Introspection Engine    : introspection-core bcc2ff906db47790ee902e7bbc76d7ffb1893009 (at node_modules/@prisma/engines/introspection-engine-debian-openssl-1.1.x)
Format Binary           : prisma-fmt bcc2ff906db47790ee902e7bbc76d7ffb1893009 (at node_modules/@prisma/engines/prisma-fmt-debian-openssl-1.1.x)
Default Engines Hash    : bcc2ff906db47790ee902e7bbc76d7ffb1893009
Studio                  : 0.457.0
```

**Comment by danstarns** [comment] 2022-09-08 14:15
**Internal** find reproduction here: https://github.com/prisma/reproductions/tree/main/gh-11648

**Comment by Weakky** [comment] 2022-09-22 16:22
Hey @nilsdet,

This is working as expected. While I do understand your confusion, the behaviour you're witnessing comes from the database and not Prisma. In most relational databases, `NULL` is a special value. It cannot be compared against anything else. In fact `NULL == NULL == false`. This is why those databases have the `IS` operator to specifically check whether a value is `NULL`.

Now, in practice, what that means is that `col != 1` does _not_ return `NULL` values because `col == NULL` will never return true.

If you want to include `NULL` values in your result, you have to manually say so. eg:

```ts
await prisma.product.findMany({
  where: {
    OR: [
      { userId: { not: 1 } },
      { userId: null }
    ]
  }
})
```

This maps 1-1 to the underlying SQL query that you'd have to write if you wanted to get the same result:

```sql
SELECT ... FROM ... WHERE userId != 1 OR userId IS NULL 
```

However, we can improve our documentation to make this clearer. We've [opened an issue](https://github.com/prisma/docs/issues/3812) to follow up on yours.

Hopefully that clarifies things, I'm closing this now.

Thanks for reporting 🙏

**Closed by Weakky** 2022-09-22 16:22 UTC
Labels: bug/2-confirmed, kind/bug, tech/engines, topic: null, team/client
