### ISSUE TITLE
Could Enumerable be defined as `T | ReadonlyArray<T>` in WhereInput

### ISSUE THREAD

**Issue by Yaojian** [prisma/prisma#5743] opened 2021-02-19 11:37 UTC
## Problem

When using Prisma to implement the GraphQL DataLoader, the `keys` passed in is a `ReadonlyArray<string>` while Prisma requires an mutable array, so typecasting is required in each DataLoader.

For example:

Prisma generated field `BlogEntityWhereInput.id` is defined as a mutable array:
```
  export type BlogEntityWhereInput = {
    id?: StringFilter | string
    // ...
  }

  export type StringFilter = {
    in?: Enumerable<string>
    // ...
  }

  export type Enumerable<T> = T | Array<T>;
```
while DataLoader declares its batch loader function as
```
export type BatchLoadFn<K, V> = (keys: ReadonlyArray<K>) => PromiseLike<ArrayLike<V | Error>>;
```

So, in a DataLoader, I have cast the `blogIds` to `string[]`:
```
  blogs = new DataLoader<string, BlogEntity>(async (blogIds: ReadonlyArray<string>) => {
    const allBlogs = await this.db.blogEntity.findMany({ where: { id: { in: blogIds as string[] } } });
    return blogIds.map((blogId) => allBlogs.find((blog) => blog.id === blogId) || new Error(`NO blog for ${blogId}`));
  });
```

## Suggested solution

Since there is no need to change the input field values, they may be defined as `T | ReadonlyArray<T>` .

Or, defines `id` as Readonly<Enumerable<T>> ?

**Comment by pantharshit00** [comment] 2021-03-02 14:56
Hi,

Thanks for reporting this! It has already been reported before, so I am going to close this as a duplicate of https://github.com/prisma/prisma/issues/5025

**Closed by pantharshit00** 2021-03-02 14:56 UTC
