### ISSUE TITLE
Setting rejectOnNotFound globally doesn't provide type safety

### ISSUE THREAD

**Issue by ahmedosama7450** [prisma/prisma#6774] opened 2021-04-25 17:37 UTC
## Bug description

Setting `rejectOnNotFound` globally doesn't change the typing of `findUnique` or `findFirst`
```
const prisma = new PrismaClient({
  rejectOnNotFound: true,
});
```
Then when I use `findUnique`,  It still returns `Prisma.Prisma__UserClient<User | null>` instead of `Prisma.Prisma__UserClient<User>`

## Expected behavior

It will be better if it's typed. This might mean, generating types at runtime just like `nexus` does. But a better approach will be to just include this property `rejectOnNotFound ` in the prisma schema itself within the generator block like this:
```
generator client {
  provider = "prisma-client-js"
  rejectOnNotFound = true
}

``` 
## Environment & setup

- OS:  Windows
- Database:  PostgreSQL
- Node.js version:  14.16.1
- Prisma version:

```
 2.21.2
```

**Comment by bombillazo** [comment] 2021-04-27 06:12
Hey @ahmedosama7450 , following up this issue from Slack, I saw [in the docs](https://www.prisma.io/docs/reference/api-reference/prisma-client-reference#rejectonnotfound) you _can_ globally turn on rejectOnNotFound:
```
const prisma = new PrismaClient({
  rejectOnNotFound: true,
})
```
I tried to replicate your original use-case and here are the results:
```
// Schema
model User {
  id                  Int                      @id @default(autoincrement())
  personalProfile     PersonalProfile[]
}

model PersonalProfile {
  id        Int       @id @default(autoincrement())
  userId    Int
  user      User      @relation(fields: [userId], references: [id])
}
```

**User:** Without rejectOnNotFound: OK
![image](https://user-images.githubusercontent.com/44002321/116191169-db39d500-a6f9-11eb-9735-10a2c63f4fd8.png)
**User:** With rejectOnNotFound: OK
![image](https://user-images.githubusercontent.com/44002321/116191005-93b34900-a6f9-11eb-911d-229efdbdd621.png)
**User->Profile:** With and without rejectOnNotFound: OK
![image](https://user-images.githubusercontent.com/44002321/116191309-15a37200-a6fa-11eb-9b8b-5284d7ae331e.png)
**Profile:** Without rejectOnNotFound: OK
![image](https://user-images.githubusercontent.com/44002321/116191479-5d29fe00-a6fa-11eb-9482-427893b8a857.png)
**Profile:** With rejectOnNotFound: OK
![image](https://user-images.githubusercontent.com/44002321/116191517-759a1880-a6fa-11eb-8a66-4f3394c83fe4.png)
**Profile-User:** With and Without rejectOnNotFound: WRONG!
![image](https://user-images.githubusercontent.com/44002321/116191561-88145200-a6fa-11eb-8a01-a5959d3f2901.png)
![image](https://user-images.githubusercontent.com/44002321/116191590-9498aa80-a6fa-11eb-94cf-09ed3559dbe4.png)

Inspecting the function type:
![image](https://user-images.githubusercontent.com/44002321/116193338-315c4780-a6fd-11eb-9dc7-d6a189be8191.png)

The return type seems to be hardcoded into the generated client:
![image](https://user-images.githubusercontent.com/44002321/116193824-f0b0fe00-a6fd-11eb-9bc0-124fa420efee.png)

Perhaps the generator option is a good solution, if you want it globally but would not function on a call by call basis.

**Comment by ahmedosama7450** [comment] 2021-04-27 14:59
Hey @bombillazo I think you go a little bit confused here. This has nothing to do with the fluent api problem we talked about on slack. I haven't yet opened an issue for that problem.
Sorry for the inconvenience.

**Comment by pantharshit00** [comment] 2021-04-29 08:13
@ahmedosama7450 I wasn't able to reproduce your issue. 

![image](https://user-images.githubusercontent.com/22195362/116520367-42b97580-a8f0-11eb-9894-29c676055658.png)


If you using a class service in framework like nest, please pass `rejectOnNotFound` to the `PrismaClientOptions` generic.

If you still can't prevent this, please post a minimal reproduction here. 



@bombillazo Fluent API issue is known: https://github.com/prisma/prisma/issues/5715. It will be fixed.

**Comment by toy-crane** [comment] 2021-06-29 02:02
i`ve got same issue.

```
import { PrismaClient } from "@prisma/client";

export const createPrismaClient = (): PrismaClient => {
	const prisma = new PrismaClient({
		rejectOnNotFound: true,
	});
	return prisma;
};

```

<img width="1172" alt="Screen Shot 2021-06-29 at 10 55 41 AM" src="https://user-images.githubusercontent.com/3426196/123725164-93395900-d8c8-11eb-835f-1f97ff43d76d.png">

when I apply rejectOnNotFound to global, it is fail

but apply rejectonNotFound option to findUnique directly, it works.
<img width="1130" alt="Screen Shot 2021-06-29 at 10 59 54 AM" src="https://user-images.githubusercontent.com/3426196/123725530-28d4e880-d8c9-11eb-85eb-afce935f7abd.png">

is there something to set more option at Prisma Client?

##  Environment & setup
- OS: Windows
- Database: PostgreSQL
- Node.js version: 14.16.1
- Prisma version: 2.25.0

**Comment by pantharshit00** [comment] 2021-07-08 14:41
@toy-crane You need to do the following:
```ts
import { PrismaClient } from "@prisma/client";

export const createPrismaClient = (): PrismaClient<{
  rejectOnNotFound: true;
}> => {
  const prisma = new PrismaClient({
    rejectOnNotFound: true,
  });
  return prisma;
};

```

**Comment by tomaskallup** [comment] 2021-07-15 11:05
> @toy-crane You need to do the following:
> 
> ```ts
> import { PrismaClient } from "@prisma/client";
> 
> export const createPrismaClient = (): PrismaClient<{
>   rejectOnNotFound: true;
> }> => {
>   const prisma = new PrismaClient({
>     rejectOnNotFound: true,
>   });
>   return prisma;
> };
> ```

Or he could just remove the return type of the function, typescript should be able to infer it correctly.

**Comment by pantharshit00** [comment] 2021-07-19 09:35
@tomaskallup Good point!

**Comment by ahmedosama7450** [comment] 2021-07-19 10:45
@pantharshit00 I think this should be noted in the docs.

Also, I just want to be able to import prisma from '@prisma/client` and expect it to have correct types
I think It's better to include `rejectOnNotFound` in the prisma schema itself within the generator block like I mentioned in the issue
```
generator client {
  provider = "prisma-client-js"
  rejectOnNotFound = true
}
```

**Comment by pantharshit00** [comment] 2021-07-20 20:19
@ahmedosama7450 I don't think we can have this option in the schema as people can do multiple instances of the client with different `rejectOnNotFound` option (eg. when sharing client in a monorepo) and the schema approach restricts that. 


I opened a documentation issue about the generic usage: https://github.com/prisma/docs/issues/1564#issuecomment-883668535

**Closed** 2021-07-20 21:52 UTC
Labels: bug/0-needs-info, kind/bug, team/client, topic: rejectOnNotFound
