### ISSUE TITLE
Add support for "has-many-through" relationship

### ISSUE THREAD

**Issue by jferrettiboke** [prisma/prisma#4910] opened 2021-01-07 01:33 UTC
It would be great to have a "has-many-through" relationship in Prisma, similar to Laravel.

The Prisma Client should make this easy for us.

[Read this](https://laravel.com/docs/8.x/eloquent-relationships#has-many-through) for more info about the "has-many-through" relationship in Laravel.

**Comment by albertoperdomo** [comment] 2021-02-02 14:30
I think this is a duplicate of https://github.com/prisma/prisma/issues/2186

**Comment by janpio** [comment] 2024-03-02 09:40
It is indeed a duplicate for the same problem and solution, and as it has no additional upvotes or comments, I am closing this now.

Thanks for opening the issue back in the day @jferrettiboke!

**Closed by janpio** 2024-03-02 09:40 UTC
Labels: kind/feature, topic: schema, topic: relations, team/client
