### ISSUE TITLE
Error: [introspection-engine\connectors\sql-introspection-connector\src\introspection_helpers.rs:188:64] called `Option::unwrap()` on a `None` value 

### ISSUE THREAD

**Issue by tomhoule** [prisma/prisma#6738] opened 2021-04-23 08:49 UTC
Command: `prisma introspect`
Version: `2.21.2`
Binary Version: `e421996c87d5f3c8f7eeadd502d4ad402c89464d`
Report: https://prisma-errors.netlify.app/report/13243 
OS: `x64 win32 10.0.19042`

JS Stacktrace:
```
Error: [introspection-engine\connectors\sql-introspection-connector\src\introspection_helpers.rs:188:64] called `Option::unwrap()` on a `None` value
    at ChildProcess.<anonymous> (D:\PJ\fym2\node_modules\prisma\build\index.js:39953:28)
    at ChildProcess.emit (events.js:315:20)
    at ChildProcess.EventEmitter.emit (domain.js:467:12)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
```

Rust Stacktrace:
```
   0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: <unknown>
   7: <unknown>
   8: <unknown>
   9: <unknown>
  10: <unknown>
  11: <unknown>
  12: <unknown>
  13: <unknown>
  14: <unknown>
  15: <unknown>
  16: <unknown>
  17: <unknown>
  18: <unknown>
  19: <unknown>
  20: <unknown>
  21: <unknown>
  22: <unknown>
  23: <unknown>
  24: <unknown>
  25: <unknown>
  26: <unknown>
  27: BaseThreadInitThunk
  28: RtlUserThreadStart

```

**Comment by pimeys** [comment] 2021-06-07 16:39
A possible duplicate of: https://github.com/prisma/prisma/issues/6982

**Comment by pantharshit00** [comment] 2021-06-08 13:52
Trace is exactly the same, I will close this one and reference it there.

**Closed by pantharshit00** 2021-06-08 13:52 UTC
Labels: bug/1-repro-available, kind/bug, team/migrations, topic: error reporting, topic: introspection
