### ISSUE TITLE
consider adding range type

### ISSUE THREAD

**Issue by budyclub** [prisma/prisma#13759] opened 2022-06-11 09:11 UTC
## Suggested solution
add range type

**Comment by janpio** [comment] 2022-06-11 10:45
I think we already have an issue for that: https://github.com/prisma/prisma/issues/3287 
Do you agree? Then please close this issue @budyclub.

**Comment by jkomyno** [comment] 2022-09-05 16:01
Closing this as a duplicate of #3287.

**Closed by jkomyno** 2022-09-05 16:01 UTC
Labels: kind/feature, team/schema
