### ISSUE TITLE
`findUnique` does not work with models using `BigInt`

### ISSUE THREAD

**Issue by kwesterfeld2** [prisma/prisma#19737] opened 2023-06-13 13:59 UTC
### Bug description

Please see discussion: https://github.com/prisma/prisma/discussions/17824

As the title of this issue mentions, using `findUnique()` to locate an object with Prisma does not work if the model's id or key is `BigInt`.   The API always returns null.  Oddly, `findUniqueOrThrow()` does work, but semantically is not desirable.

### How to reproduce

Per discussion, any model that uses BigInt as an id or composite id component does not work when calling findUnique.  The same exact code DOES work with findUniqueOrThrow.  Changing the model to use `Int` for its id also is a fix--but not at all desirable because that would be a mismatch with the database.

The model that easily reproduces this is here (please note the BigInt for id):  

```
generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "sqlite"
  url      = env("DATABASE_URL")
}

model User {
  id      BigInt    @id @default(autoincrement())
  email   String    @unique
  name    String?
  posts   Post[]
}

model Post {
  id        Int       @id @default(autoincrement())
  title     String
  content   String?
  published Boolean   @default(false)
  author    User?     @relation(fields: [authorId], references: [id])
  authorId  BigInt?
}

```

### Expected behavior

Expecting BigInt to work with `findUnique`.  Currently, any call to this function that uses BigInt returns null.

### Prisma information

Please see https://github.com/prisma/prisma/discussions/17824

### Environment & setup

Please see https://github.com/prisma/prisma/discussions/17824

### Prisma Version

4.10.1 and 4.12.0 were tested

**Comment by Druue** [comment] 2023-06-16 12:00
Hey, could you please provide a minimal typescript reproduction of this error?
I can't reproduce this locally

**Comment by SevInf** [comment] 2023-08-18 15:26
I can confirm issue on 4.10.1 with the following code:

```ts
  const prisma = new PrismaClient()

  await prisma.user.deleteMany()
  await prisma.user.create({ data: { id: 1n } })
  await prisma.user.create({ data: { id: 2n } })

  const result = await Promise.all([
    prisma.user.findUnique({ where: { id: 1n } }),
    prisma.user.findUnique({ where: { id: 2n } }),
  ])

  console.log(result)
```

this outputs `[null, null]`.

However, as of 4.12.0 and later issue [is fixed](https://github.com/prisma/prisma-engines/pull/3818).

@kwesterfeld2 If it still happens for you on 4.12.0+, we'd ask to see a reproduction, as my colleague mentioned - unfortunately, information in this issue and discussion is not enough to reproduce it newer version. If we won't hear back from you, we'd have to close the issue as non-reproducible.
Thank you!

**Comment by kwesterfeld2** [comment] 2023-08-21 18:24
@SevInf I can confirm that upgrading from 4.11 to 4.16 fixed this issue for me, thanks!

I apologize as I believe my original statement that I was using 4.12 was incorrect, as the upgrade I attempted apparently didn't work and I was using 4.11 in my test.  Appreciate that you looked into this so carefully.

**Closed** 2023-08-22 07:19 UTC
Labels: bug/1-unconfirmed, kind/bug, topic: bigints, topic: indexes, team/client, topic: findUnique
