### ISSUE TITLE
internal error: entered unreachable code

### ISSUE THREAD

**Issue by joykamlomo** [prisma/prisma#23259] opened 2024-02-23 06:49 UTC
Hi Prisma Team! My Prisma Client just crashed. This is the report:
## Versions

| Name            | Version            |
|-----------------|--------------------|
| Node            | v21.6.1            | 
| OS              | windows            |
| Prisma Client   | 5.10.2             |
| Query Engine    | 5a9203d0590c951969e85a7d07215503f4672eb9|
| Database        | sqlite             |

## Logs
```
tarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:request_handler {"name":"PrismaClientRustPanicError","clientVersion":"5.10.2"}
prisma:client:request_handler {"name":"PrismaClientRustPanicError","clientVersion":"5.10.2"}
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
```

## Client Snippet
```ts
const { PrismaClient } = require("@prisma/client");
const { payrollHistoryService } = require("./payroll.history.service");
const { compesationHistoryService } = require("./compesation.history.service");
const { generateUniqueId } = require("../utils/uuid.util");
const { getFormattedDate } = require("../utils/date.util");
const {
  calculateTax,
  calculatePension,
  calculateTevetLevy,
  calculateAllowances,
  calculateDeductions,
} = require("./functions/payroll.calculations");

const prisma = new PrismaClient();
const taxBrackets = require("../models/malawi.tax.brackets");
const logger = require("../utils/logger.util");

const payrollProcessingService = async () => {
  const formattedDate = getFormattedDate();

  const payrollId = generateUniqueId();

  // fetch all active persons
  const persons = await prisma.person.findMany({
    where: { status: true },
  });
  for (const person of persons) {
    const personIdentinty = person.id;
    try {
      // fetch salaries for each person
      const salary = await prisma.salary.findMany({
        where: { personId: parseInt(person.id) },
      });

      // log salary amount
      const income = salary[0].amount;

      // calculate tevet levy
      const tevetLevy = calculateTevetLevy(income, 0.01);

      // calculate pension
      const pension = await prisma.pension.findUnique({
        where: { id: 1 },
      });

      const percentage = pension.percentage;

      const pensionAmount = calculatePension(income, percentage);

      // calculate allowances
      const totalAllowances = await calculateAllowances(personIdentinty);

      const grossSalaryTaxable = income + totalAllowances;

      // calculate tax
      const taxAmount = calculateTax(grossSalaryTaxable, taxBrackets);

      // calculate deductions
      const totalDeductions = await calculateDeductions(personIdentinty);

      const totalBenefits = 0;

      // calculate net salary
      const netSalary = grossSalaryTaxable - totalDeductions;

      // save to pay history
      await prisma.payHistory.create({
        data: {
          base_salary: income,
          gross_salary: grossSalaryTaxable,
          net_salary: netSalary, // Use the calculated net salary
          tevet_levy: tevetLevy,
          pension_amount: pensionAmount,
          tax_amount: taxAmount,
          total_allowances: totalAllowances,
          total_deductions: totalDeductions,
          total_benefits: totalBenefits,
          payrollId: payrollId,
          created_on: formattedDate,
          person: {
            connect: {
              id: personIdentinty,
            },
          },
        },
      });

      await compesationHistoryService(payrollId);
    } catch (error) {
      logger.error("Something happened!", error.message);
      throw error;
    }
  }

  await payrollHistoryService(payrollId);
  return {
    success: true,
    message: "Payroll processed successfully",
  };
};

module.exports = { payrollProcessingService };

```

## Schema
```prisma
// This is your Prisma schema file,
// learn more about it in the docs: https://pris.ly/d/prisma-schema

// Looking for ways to speed up your queries, or scale easily with your serverless or edge functions?
// Try Prisma Accelerate: https://pris.ly/cli/accelerate-init

generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "sqlite"
  url      = "file:../data/dev.db"
}

model Person {
  id                 Int                  @id @default(autoincrement())
  name               String
  email              String
  mobile_number      String               @default("n/a")
  gender             String
  dob                String
  salutation         String
  branch             String
  position           String
  department         String               @default("n/a")
  reports_to         String
  grade              String
  employment_type    String
  status             Boolean
  start              String
  end                String
  Salary             Salary[]
  Allowances         Allowances[]
  Benefits           Benefits[]
  Deductions         Deductions[]
  CompesationHistory CompesationHistory[]
  payHistory         payHistory[]
}

model Salary {
  id       Int    @id @default(autoincrement())
  amount   Float
  type     String @default("SALARY")
  currency String @default("MWK")
  person   Person @relation(fields: [personId], references: [id])
  personId Int
}

model Allowances {
  id           Int      @id @default(autoincrement())
  description  String
  amount       Float
  type         String   @default("EARNING")
  isPercentage Boolean
  created_on   DateTime @default(now())
  person       Person?  @relation(fields: [personId], references: [id])
  personId     Int
}

model Benefits {
  id           Int      @id @default(autoincrement())
  description  String
  amount       Float
  type         String   @default("BENEFITS")
  isPercentage Boolean
  created_on   DateTime @default(now())
  person       Person   @relation(fields: [personId], references: [id])
  personId     Int
}

model Deductions {
  id           Int      @id @default(autoincrement())
  description  String
  amount       Float
  type         String   @default("DEDUTIONS")
  isPercentage Boolean
  created_on   DateTime @default(now())
  person       Person   @relation(fields: [personId], references: [id])
  personId     Int
}

model CompesationHistory {
  id           Int     @id @default(autoincrement())
  description  String
  amount       Float
  isType       String
  isPercentage Boolean // New field to indicate if the amount is a percentage
  payrollId    String
  created_on   String
  person       Person? @relation(fields: [personId], references: [id])
  personId     Int
}

model payHistory {
  id               Int     @id @default(autoincrement())
  base_salary      Float
  gross_salary     Float
  net_salary       Float
  tevet_levy       Float
  pension_amount   Float
  tax_amount       Float
  total_allowances Float
  total_deductions Float
  total_benefits   Float
  payrollId        String
  created_on       String
  person           Person @relation(fields: [personId], references: [id])
  personId         Int
}

model PayrollHistory {
  id               Int    @id @default(autoincrement())
  total_gross      Float
  total_net        Float
  total_tax        Float
  total_pension    Float
  total_earnings   Float
  total_allowances Float
  total_deductions Float
  total_benefits   Float
  total_amount     Float
  total_people     Float
  payrollId        String
  created_on       String
}

```

## Prisma Engine Query
```
{"X":true}}}
```

**Comment by miguelff** [comment] 2024-02-23 13:59
Hello @joykamlomo. Thanks for the issue report!

Can you please describe whether the database you were using was previously filled with data, and you pulled the schema? or did you setup the DB with prisma itself?

I took the schema, `db pushed`, initialized a prisma client with the offending versions and issued `person` and `salary` `findMany` queries; and a `payHistory.create` but could not reproduce the issue. 

It would help us a lot reproducing the problem if you could create a GitHub repository (if possible with a `../data/dev.db` sqlite file) reproducing the problem. Would you be so kind to provide us with that? It can be a private repo where you add @janpio and/or @miguelff as collaborators.

**Comment by nikitamalinov** [comment] 2024-02-27 03:16
@autopilot please create a PR for this

**Comment by Weakky** [comment] 2024-05-23 09:34
Hey @joykamlomo,

Have you checked @miguelff's message? We need more information in order for us to move this forward and reproduce your issue. Thank you 🙏

**Comment by Jolg42** [comment] 2024-05-28 08:52
With the lack of information and our inability to reproduce this issue, we're now closing this issue.

**Closed by Jolg42** 2024-05-28 08:52 UTC
Labels: bug/0-unknown, kind/bug, tech/engines, team/client, topic: rust panic, topic: entered unreachable code
