### ISSUE TITLE
Error: Failure during a migration command: Connector error. (error: Error querying the database: Error querying the database: db error: ERROR: cannot drop type country_status_enum because other objects depend on it 

### ISSUE THREAD

**Issue by divyenduz** [prisma/prisma#4675] opened 2020-08-07 09:46 UTC
Command: `prisma migrate up --experimental --verbose`
Version: `2.3.0`
Binary Version: `e11114fa1ea826f9e7b4fa1ced34e78892fe8e0e`
Report: https://prisma-errors.netlify.app/report/9746 
OS: `x64 darwin 19.5.0`

JS Stacktrace:
```
Error: Failure during a migration command: Connector error. (error: Error querying the database: Error querying the database: db error: ERROR: cannot drop type country_status_enum because other objects depend on it
   0: migration_core::api::ApplyMigration
           with migration_id="20200803181634-init"
             at migration-engine/core/src/api.rs:77)
    at Object.<anonymous> (/Users/arubaito/thelab/10factory/elibro-api/node_modules/@prisma/cli/build/index.js:2:2135004)
    at MigrateEngine.handleResponse (/Users/arubaito/thelab/10factory/elibro-api/node_modules/@prisma/cli/build/index.js:2:2133212)
    at LineStream.<anonymous> (/Users/arubaito/thelab/10factory/elibro-api/node_modules/@prisma/cli/build/index.js:2:2134669)
    at LineStream.emit (events.js:314:20)
    at addChunk (_stream_readable.js:304:12)
    at readableAddChunk (_stream_readable.js:280:9)
    at LineStream.Readable.push (_stream_readable.js:219:10)
    at LineStream.Transform.push (_stream_transform.js:166:32)
    at LineStream._pushBuffer (/Users/arubaito/thelab/10factory/elibro-api/node_modules/@prisma/cli/build/index.js:2:1819384)
    at LineStream._transform (/Users/arubaito/thelab/10factory/elibro-api/node_modules/@prisma/cli/build/index.js:2:1819205)
```

Rust Stacktrace:
```
Failure during a migration command: Connector error. (error: Error querying the database: Error querying the database: db error: ERROR: cannot drop type country_status_enum because other objects depend on it
   0: migration_core::api::ApplyMigration
           with migration_id="20200803181634-init"
             at migration-engine/core/src/api.rs:77)
```

**Comment by tomhoule** [comment] 2021-02-17 09:55
Could be a duplicate of the one about not being able to drop enums used in default values.

**Closed by tomhoule** 2021-02-17 09:55 UTC
Labels: bug/2-confirmed, kind/bug, process/candidate, team/migrations, tech/engines, topic: migrate

**Comment by AHBruns** [comment] 2021-02-21 04:25
Seeing this, and what's really annoying is I can't even do `prisma migrate reset --preview-feature`. I get the following:

```
alexbruns@Alexs-MacBook-Pro autodidactv3 % npx prisma migrate reset --preview-feature                                                
Environment variables loaded from .env
Prisma schema loaded from prisma/schema.prisma
Datasource "db": PostgreSQL database "prisma", schema "public" at "development-db-psql-0001-do-user-5046031-0.b.db.ondigitalocean.com:25060"


✔ Are you sure you want to reset your database? All data will be lost. … yes
Error: Database error: Error querying the database: db error: ERROR: cannot drop type "NotificationStatus" because other objects depend on it
DETAIL: column status of table "Notification" depends on type "NotificationStatus"
HINT: Use DROP ... CASCADE to drop the dependent objects too.
   0: sql_migration_connector::sql_database_step_applier::apply_migration
             at migration-engine/connectors/sql-migration-connector/src/sql_database_step_applier.rs:14
   1: sql_migration_connector::best_effort_reset
           with connection=Connection(Postgres(PostgresUrl { url: Url { scheme: "postgresql", host: Some(Domain("development-db-psql-0001-do-user-5046031-0.b.db.ondigitalocean.com")), port: Some(25060), path: "/prisma", query: Some("sslmode=require&statement_cache_size=0"), fragment: None }, query_params: PostgresUrlQueryParams { ssl_params: SslParams { certificate_file: None, identity_file: None, identity_password: <HIDDEN>, ssl_accept_mode: AcceptInvalidCerts }, connection_limit: None, schema: "public", ssl_mode: Require, pg_bouncer: false, host: None, socket_timeout: None, connect_timeout: Some(5s), pool_timeout: Some(5s), statement_cache_size: 0 } }))
             at migration-engine/connectors/sql-migration-connector/src/lib.rs:104
   2: migration_core::api::Reset
             at migration-engine/core/src/api.rs:139
```

Here's my schema if it helps: 

```prisma
datasource db {
  provider = "postgresql"
  url = env("DIRECT_PUBLIC_CONNECTION_STRING")
  shadowDatabaseUrl = env("SHADOW_DB_PUBLIC_CONNECTION_STRING")
}

generator client {
  provider = "prisma-client-js"
}

model Notification {
  id String @unique
  text String
  date DateTime
  status NotificationStatus
  owner User @relation(fields: [ownerId], references: [id])
  ownerId Int
}

model Document {
  id String @unique
  name String
  owner User @relation(fields: [ownerId], references: [id])
  ownerId Int
}

model Right {
  id String @default(cuid()) @id
  name String
  owner User @relation(fields: [ownerId], references: [id])
  ownerId Int
}

model License {
  id String @default(cuid()) @id
  startDate DateTime
  contract Contract @relation(fields: [contractId], references: [id])
  contractId String
  iProperty IProperty @relation(fields: [iPropertyId], references: [id])
  iPropertyId String
  rights Right[]
  notifications Notification[]
  owner User @relation(fields: [ownerId], references: [id])
  ownerId Int
}

model Contract {
  id String @default(cuid()) @id
  name String
  description String
  signingDate DateTime
  licenses License[]
  documents Document[]
  notifications Notification[]
  owner User @relation(fields: [ownerId], references: [id])
  ownerId Int
}

model IProperty {
  id String @default(cuid()) @id
  name String
  description String?
  licenses License[]
  owner User @relation(fields: [ownerId], references: [id])
  ownerId Int
}

model User {
  id Int @default(autoincrement()) @id
  name String?
  email String? @unique
  emailVerified DateTime? @map(name: "email_verified")
  image String?
  createdAt DateTime @default(now()) @map(name: "created_at")
  updatedAt DateTime @updatedAt @map(name: "updated_at")
  ips IProperty[]
  contracts Contract[]
  licenses License[]
  documents Document[]
  notifications Notification[]
  rights Right[]

  @@map(name: "users")
}

model Account {
  id                 Int       @default(autoincrement()) @id
  compoundId         String    @unique @map(name: "compound_id")
  userId             Int       @map(name: "user_id")
  providerType       String    @map(name: "provider_type")
  providerId         String    @map(name: "provider_id")
  providerAccountId  String    @map(name: "provider_account_id")
  refreshToken       String?   @map(name: "refresh_token")
  accessToken        String?   @map(name: "access_token")
  accessTokenExpires DateTime? @map(name: "access_token_expires")
  createdAt          DateTime  @default(now()) @map(name: "created_at")
  updatedAt          DateTime  @default(now()) @map(name: "updated_at")

  @@index([providerAccountId], name: "providerAccountId")
  @@index([providerId], name: "providerId")
  @@index([userId], name: "userId")

  @@map(name: "accounts")
}

model Session {
  id           Int      @default(autoincrement()) @id
  userId       Int      @map(name: "user_id")
  expires      DateTime
  sessionToken String   @unique @map(name: "session_token")
  accessToken  String   @unique @map(name: "access_token")
  createdAt    DateTime @default(now()) @map(name: "created_at")
  updatedAt    DateTime @default(now()) @map(name: "updated_at")

  @@map(name: "sessions")
}

model VerificationRequest {
  id         Int      @default(autoincrement()) @id
  identifier String
  token      String   @unique
  expires    DateTime
  createdAt  DateTime  @default(now()) @map(name: "created_at")
  updatedAt  DateTime  @default(now()) @map(name: "updated_at")

  @@map(name: "verification_requests")
}

enum NotificationStatus {
  ACTIVE
  INACTIVE
}
```

**Comment by tomhoule** [comment] 2021-02-22 07:42
@AHBruns comments in closed issues tend to be overlooked, bu thanks for reporting. I think what you are seeing is this issue: https://github.com/prisma/prisma/issues/4696 — we plan on fixing this before next release.
