### ISSUE TITLE
Mac M2 uses the wrong version of node for primsa to operate

### ISSUE THREAD

**Issue by MincePie** [prisma/prisma#24466] opened 2023-08-05 09:16 UTC
### Bug description

This thread sets out a problem that mac users are encountering with prisma: https://github.com/prisma/prisma/issues/17869

I'm trying to solve it by replacing node /deleting node_modules, but I can't find the configuration required to let prisma run on mac.

I can see from the other thread that this is not a prisma issue, but any help figuring out what to do to find a way to use it on mac would be very much appreciated.

### How to reproduce

Try using prisma commands in mac m2 with node 

```
node -v  v18.17.0
node -e 'console.log(process.arch)' x64
arch i386
```

### Expected behavior

trying to run prisma commands. they fail with this error message:

```
assertion failed [block != nullptr]: BasicBlock requested for unrecognized address
(BuilderBase.h:550 block_for_offset)
error Command failed with signal "SIGABRT".
```

### Prisma information

prisma@5.1.1

### Environment & setup

- OS:  Mac OS, Ventura
- Database: MySQL

**Comment by janpio** [comment] 2024-06-07 14:18
Closing this as a duplicate of https://github.com/prisma/prisma/issues/17869 - let's continue the conversation and discussion there.

**Closed by janpio** 2024-06-07 14:18 UTC
Labels: kind/bug
