### ISSUE TITLE
`prisma migrate dev` fails repeatedly for PlanetScale

### ISSUE THREAD

**Issue by obibring** [prisma/prisma#13136] opened 2022-05-03 22:48 UTC
### Bug description

I'm attempting to migrate my database and continuously receiving the same error message using `prisma@3.13.0`:
```
Error: held locks released: vttablet: rpc error: code = Aborted desc = transaction 1651614596363662552: ended at 2022-05-03 22:38:12.305 UTC (exceeded timeout: 20s) (CallerID: planetscale-admin)
   0: migration_core::state::ApplyMigrations
             at migration-engine/core/src/state.rs:185
```

### Expected behavior

The migration should succeed.

### Prisma information

Happy to provide this privately

### Environment & setup

- OS: Mac OS Monterey 12.0
- Database: PlanetScale (MySQL)
- Node.js version: 14.17.0

### Prisma Version

```
prisma                  : 3.13.0
@prisma/client          : 3.13.0
Current platform        : darwin
Query Engine (Node-API) : libquery-engine efdf9b1183dddfd4258cd181a72125755215ab7b (at ../../../node_modules/.pnpm/@prisma+engines@3.13.0-17.efdf9b1183dddfd4258cd181a72125755215ab7b/node_modules/@prisma/engines/libquery_engine-darwin.dylib.node)
Migration Engine        : migration-engine-cli efdf9b1183dddfd4258cd181a72125755215ab7b (at ../../../node_modules/.pnpm/@prisma+engines@3.13.0-17.efdf9b1183dddfd4258cd181a72125755215ab7b/node_modules/@prisma/engines/migration-engine-darwin)
Introspection Engine    : introspection-core efdf9b1183dddfd4258cd181a72125755215ab7b (at ../../../node_modules/.pnpm/@prisma+engines@3.13.0-17.efdf9b1183dddfd4258cd181a72125755215ab7b/node_modules/@prisma/engines/introspection-engine-darwin)
Format Binary           : prisma-fmt efdf9b1183dddfd4258cd181a72125755215ab7b (at ../../../node_modules/.pnpm/@prisma+engines@3.13.0-17.efdf9b1183dddfd4258cd181a72125755215ab7b/node_modules/@prisma/engines/prisma-fmt-darwin)
Default Engines Hash    : efdf9b1183dddfd4258cd181a72125755215ab7b
Studio                  : 0.459.0
Preview Features        : referentialIntegrity
```

**Comment by obibring** [comment] 2022-05-03 22:49
@janpio as requested

**Comment by janpio** [comment] 2022-05-03 22:52
What command are you running to migrate your database?
Is this the production branch or another one?
Could you run migrations on PlanetScale before successfully?
What are you doing in this migration?

**Comment by obibring** [comment] 2022-05-04 18:33
Hi Jan, 

#### Command
The command to migrate the DB is `prisma migrate dev`.

#### Branch
The database is __not__ a production PlanetScale DB. 

#### Previous Migrations
Yes, I was previously able to run migrations. But the errors have been occurring more and more frequently over time, until yesterday, where I haven't been able to successfully complete the migration. Perhaps this is related to the # of previously applied migrations?

#### Migration Details
I'm adding a single value to an enum. 

I looked at the DB details in the PlanetScale UI and noticed that the migration _was_ applied, but the prisma cli produces the error mentioned above.

**Comment by janpio** [comment] 2022-05-12 12:17
Thanks @obibring - we are honestly a bit clueless how and why this is happening. Is it still happening to you when you migrate? Can you maybe shared your schema and migration history with us so we can just try to reproduce it with the same data you are using? We are happy to accept that data at schemas@prisma.io - if necessary we can also sign a mutual NDA to make sure the data stays private.

**Comment by janpio** [comment] 2022-05-12 12:30
Additional question @obibring, how are you connection to PlanetScale - connection string with `.psdb.cloud` or via `pscale` CLI and then a `localhost` hostname?

**Comment by obibring** [comment] 2022-05-12 22:01
Hi @janpio , I'm using the `pscale` CLI w/ a `localhost` hostname.

**Comment by JannikZed** [comment] 2022-07-21 09:16
Facing the same issue all the time. I'm using a "testing" branch at planetscale to run all the migrations. At first, everything went fine, but for some weeks, it always fails like this: 
```
✔ Enter a name for the new migration: … order_date
Error: held locks released: vttablet: rpc error: code = Aborted desc = transaction 1658372746247315291: ended at 2022-07-21 09:11:56.309 UTC (exceeded timeout: 20s) (CallerID: planetscale-admin)
   0: migration_core::state::ApplyMigrations
             at migration-engine/core/src/state.rs:185
```
Using the pscale CLI and localhost as well. Prisma `4.1.0`

**Comment by janpio** [comment] 2022-07-30 21:24
Can you help us to get to a reproduction somehow? What is the minimal code or project you need locally, and setup, to get this to happen? If we can reproduce this, we can actually try to understand what is happening and hopefully fix it.

**Comment by Jolg42** [comment] 2023-01-03 12:32
I think we could try to reproduce like:
- change schema.prisma
- `npx prisma migrate dev` to create a migration
- wait for +20s before entering the name for the migration
- See it fail?

**Comment by jakeleventhal** [comment] 2023-04-24 20:59
```typescript
await prisma.transaction(async tx => {
	await Promise.all(rows.map(async row => {
		// make queries with tx
		
		// make writes with tx
	}));
})
```
I am doing something like this with hundreds of rows. This ends up taking >20s but i need atomic writes. 

similar issue, but different use-case

**Comment by Jolg42** [comment] 2023-04-25 14:04
Note: I could not reproduce with what I thought from my previous comment.

This seems to be an issue only when a transaction takes longer than 20s

create a migration and add the following sql
```sql
START TRANSACTION;

DO SLEEP(25);

COMMIT;
```

then `npx prisma@4.13.0 migrate dev` will result in:
```
npx prisma@4.13.0 migrate dev
...
Error: P3006

Migration `20230425132448_test78` failed to apply cleanly to the shadow database. 
Error code: P3018
Error:
A migration failed to apply. New migrations cannot be applied before the error is recovered from. Read more about how to resolve migration issues in a production database: https://pris.ly/d/migrate-resolve

Migration name: 20230425132448_test78

Database error code: 1105

Database error:
target: test4321.-.primary: vttablet: (errno 2013) due to context deadline exceeded, elapsed time: 20.000601153s, killing query ID 1355 (CallerID: nvin3yg0sixr462qdte2)

Please check the query number 2 from the migration file.
```

Which is expected since it is a limitation from PlanetScale: https://github.com/prisma/prisma/issues/18909#issuecomment-1520876713

**Comment by Jolg42** [comment] 2023-04-25 14:04
Is that what was happening to you @obibring ?
Do you still have this issue with a recent version of Prisma?

**Comment by Jolg42** [comment] 2023-04-25 16:39
Since I cannot reproduce it with the old versions mentioned and the latest one and that the last time someone reported this was last year, I'll close this for now.
Happy to reopen it if someone can get a reproduction of the issue mentioned in the description!

**Closed by Jolg42** 2023-04-25 16:39 UTC
Labels: bug/0-unknown, kind/bug, team/schema, topic: prisma migrate dev, topic: database-provider/planetscale
