### ISSUE TITLE
Prisma client can't reach database server from time to time

### ISSUE THREAD

**Issue by Dammmien** [prisma/prisma#12305] opened 2022-03-13 15:35 UTC
### Bug description

Hi,

We are running a very classic NodeJS Express API connected to a PostgreSQL database via the Prisma client, and from time to time we have requests failing with the error P1001 :
```
Can't reach database server at ...
Please make sure your database server is running at ...
```
And everything is ok in the previous or following requests few milliseconds apart:

<img width="846" alt="Capture d’écran 2022-03-13 à 16 46 24" src="https://user-images.githubusercontent.com/3051737/158067883-cccd32c4-706d-4be5-b509-b9ad00e4a2e0.png">

I checked on the infrastructure side, and the database seems reachable from the server with no issues of connection pool,  overload, high CPU, high memory or whatever else.

Is there something I can check or try to solve that ?

### How to reproduce

I didn't find any way to reproduce it constantly but it seems to happen a little bit more during low traffic periods like night. And it seems that sending queries every 20 seconds reduce a lot the issue. So it's maybe linked to idle timeout or something similar.

### Expected behavior

No more requests failing with this error of course 😅 !
I don't expect a fix or whatever, but more at advices or things I can take a look to to move forward in solving this problem.

### Prisma information

It happens with different queries, we even have very basic health checks failing from time to time due to this error:
```ts
export default async function () {
  await client.$queryRaw`SELECT 0`;
}
```

### Environment & setup

- OS: Ubuntu
- Database: PostgreSQL
- Node.js version: 16.13.0

### Prisma Version

```
3.10.0
```

**Comment by janpio** [comment] 2022-03-13 18:46
Do you possibly have database side logging for that time and can see if the requests really reach the database? 
Could it potentially be a temporary network thing that affects only some connection attempts?

You could increase the timeout and see if that changes something. Potentially slightly slower requests are preferrable to these errors. Alternatively you could add retries for these queries with this error message. Does the second attempt work then?

**Comment by Dammmien** [comment] 2022-03-14 09:51
- **Do you possibly have database side logging for that time and can see if the requests really reach the database?**
I can't see specifically if these requests reached the database or not, but I see that there is a lot of disconnection / connection in one minute between the apps ands the database (I don't know if it's an expected behavior or not ):

![Capture d’écran 2022-03-12 à 17 51 06](https://user-images.githubusercontent.com/3051737/158143911-1a9246eb-40f1-4f6a-88c3-cd4c2a2bddc2.png)

- **Could it potentially be a temporary network thing that affects only some connection attempts?**
I don't think so, I have another very similar app (a NodeJS Express API) with the same infrastructure but which use Sequelize and I don't have this kind of errors.

- **You could increase the timeout and see if that changes something.**
Sounds interesting, how can I do that ?

Also, we are now running a very basic health check every minute:
```ts
export default async function () {
  await client.$queryRaw`SELECT 0`;
}
```
And it's seems to fix the issue, but it's more a dirty patch, I would like to know and fix the root cause.
The connection should remain open, even if there is no request for 30 seconds, no ?

I see that a lot of pg_conf settings like `idle_session_timeout`, `tcp_keepalives_idle`, `tcp_keepalives_interval` or `idle_in_transaction_session_timeout` exist, is it something I should look into or the default values are ok ?

**Comment by drewcorlin1** [comment] 2022-03-15 03:03
I'm seeing similar behavior across 4 services. They are node services talking to an RDS aurora instance. It seems to happen equally across those service. I am also using prisma in other node services that talk to an RDS postgres instance and I haven't seen it happen there, though the sample size isn't huge. On the Aurora side my CPU, memory nor connections never spike to anywhere near the limits either.

It seems to happen using both `prisma.<model>.findMany(...)` and `prisma.$queryRaw(...)` for me. I'm also running inot the issue wiht various versions of prisma across those services: 3.1.1, 3.5.0 and 3.7.0.

**Comment by Dammmien** [comment] 2022-03-15 14:20
@janpio I see in the Prisma doc there is this kind of settings, is it something I should look into or the default values are ok ?

![Capture d’écran 2022-03-15 à 12 47 17](https://user-images.githubusercontent.com/3051737/158371445-c812bab3-cf51-41e9-9beb-d3a61fcf17d1.png)

**Comment by janpio** [comment] 2022-03-15 21:27
> is it something I should look into or the default values are ok ?

@Dammmien The Prisma chosen defaults are usually fine, you can increase the `connect_timeout` for example to see if the connection sometimes just needs a bit longer to connect.

> And if you can tell me where is manage the connection / reconnection logic in the client source code, I can take a look.

There is none, that is something that would need to be implemented in your application or via a Prisma middleware.

**Comment by janpio** [comment] 2022-03-15 21:28
> It seems to happen equally across those services. 

@drewcorlin1 At the same time or just over time?

> I am also using prisma in other node services that talk to an RDS postgres instance and I haven't seen it happen there

Can you pinpoint what is different in these services vs. the one where it does happen and fail?

**Comment by drewcorlin1** [comment] 2022-03-16 00:44
@janpio Over time its relatively equal per service. At the times that the issue has cropped up it seems to happen in groups, with about half of those groups being confined to a single service and half of them being spread across multiple services. I guess this may indicate that it's on the RDS side? 

The only consistent thing that is different between these services seems to be Aurora vs Postgres.

Is there any extra logging that I'm able to add/enable in the prisma client? I'm adding better logging + monitoring on the RDS side and just want to try to cover all my bases

**Comment by janpio** [comment] 2022-03-16 11:17
> At the times that the issue has cropped up it seems to happen in groups, with about half of those groups being confined to a single service and half of them being spread across multiple services. I guess this may indicate that it's on the RDS side?

It at least indicates a correlation across different Prisma Client deployments that have no communication channel - so it might be network or RDS side indeed.

There is unfortunately no additional possible logging. The error message is thrown when the timeout is not enough to create a connection. Prisma does not have further information why that is not the case. (Possible reasons of course are: Local load, network, database side, phase of the moon.)

**Comment by Dammmien** [comment] 2022-03-16 11:38
@janpio when I:
- turn off my database locally
- run a query (it fails)
- turn on my database locally
- run a query (it succeeds)

So there is a reconnection logic somewhere...

Also I tried to reconnect manually and retry the query in a middleware:
```ts
prisma.$use(async (params, next) => {
  try {
    const result = await next(params);

    return result;
  } catch (error) {
    await prisma.$disconnect();
    await prisma.$connect();
    const result = await next(params);
    return result;
  }
});
```
But the client is completely fucked up and never reconnect if the `prisma.$connect();` fails again ...
Also I noticed that if the first `prisma.$connect` fails, the client never reconnect
No matter if I call it explicitly or with the first request

**Comment by janpio** [comment] 2022-03-16 12:26
Ok, I misunderstand your ask for "retry" logic then - which we do not have. If a connection in unhealthy, it should be removed from the connection pool and then the next query or `$connect` would request a new one.  (The code sits in prisma/quaint btw and is not something you should ever have to look at)

(`$disconnect` and `$connect` should actually completely restart Prisma and then get a completely empty connection pool - so what you are describing is pretty weird from that perspective.)

**Comment by drewcorlin1** [comment] 2022-03-16 13:28
@janpio Thanks for the info! Just want to confirm 1 thing:
> The error message is thrown when the timeout is not enough to create a connection

This is explicitly when trying to establish a new connection to the DB, not when attempting to get a connection from Prisma's pool right?

**Comment by Dammmien** [comment] 2022-03-16 14:43
@janpio by taking a look into the code, it seems to be linked to `this.libraryStartingPromise` which is not set to undefined in the catch, so it do not try to reconnect:
https://github.com/prisma/prisma/blob/757a9c44b41a16482eab7b26ed5d14f123ea771d/packages/engine-core/src/library/LibraryEngine.ts#L324-L355

**Comment by janpio** [comment] 2022-03-16 20:22
Nice, there are other issues and PRs about something like this (https://github.com/prisma/prisma/pull/12066 + https://github.com/prisma/prisma/issues/12028)
But is that related to your original issue here?

**Comment by janpio** [comment] 2022-03-17 01:46
> This is explicitly when trying to establish a new connection to the DB, not when attempting to get a connection from Prisma's pool right?

The way you ask makes me scared to answer @drewcorlin1 😆 But yes, fundamentally you should get a different answer for the connection pool, a connection pool timeout or other message that mentions the connection pool.

**Comment by Dammmien** [comment] 2022-03-17 11:21
> But is that related to your original issue here?
Not exactly, but with this fix, in case of error I could try to disconnect / reconnect the client and retry the query.
Without the fix if I try to reconnect and it fails the client is completely stuck

**Comment by garrensmith** [comment] 2022-04-01 07:50
Hi, https://github.com/prisma/prisma/pull/12066 is merged and should hopefully fix this issue. Would you be able to test with `prisma@dev` and see if your issue is resolved.

**Comment by pantharshit00** [comment] 2022-06-02 11:39
Hey @Dammmien, Did you get a chance to test this out again? The fix should be now in the latest version.

**Comment by Dammmien** [comment] 2022-06-02 13:07
Hi @pantharshit00 ,

Yes I noticed there was several fixes / improvements of the connection in the last Prisma client versions, many thanks 🙏🏻 !

We also did some changes on our sides: opened support ticket to our hosting provider, add a health check to the connection between our API and the databases, upgraded to the latest versions of the Prisma client ... and the errors rate drops from 10 per days to 10 during the last month.

So it's better 👍🏻 even if I can't say it's clearly linked to the Prisma client upgrade.

**Comment by pantharshit00** [comment] 2022-06-02 17:43
I think we can close this issue now. Many thanks!

**Closed** 2022-06-02 17:43 UTC
Labels: bug/0-unknown, kind/bug, topic: connections, team/client

**Comment by mattkindy** [comment] 2022-08-02 12:46
Hate to bring this one back up, but I still see this on 3.14.0 frequently enough. I'm not sure exactly what triggers it (seems vaguely related to our deployments), but it persists until the affected node is recycled. I'm looking to move up to 4.x for other reasons, so hopefully I'll see it resolved there, but wanted to mention.

**Comment by ejames17** [comment] 2022-08-21 11:13
I am also seeing this issue with the latest prisma client

**Comment by garrensmith** [comment] 2022-08-31 08:18
@ejames17 and @mattkindy could you open new issues with as much details as possible. What is the situation that causes this. If you could create a reproduction that would also help a lot.

**Comment by suraj5969** [comment] 2022-11-03 13:09
I am also facing the same issue, prisma sometime connects to postgres DB correctly and someimes not.
I tested it on 2 providers( render, heroku) but I am still getting this problem.
It normally occurs while calling findMany function.

the error thrown is: 
 Can't reach database server at ...
Please make sure your database server is running at ...

**Comment by CodeWithOz** [comment] 2023-03-18 10:47
I had a similar error and ran `npm update prisma` and that seems to have fixed it. Oddly nothing changed in my `package.json`, though that command reported that it changed 2 packages, so they were probably nested dependencies.

**Comment by IsraPerez98** [comment] 2023-03-25 11:47
I'm facing the following error "sometimes", is there a way to automagically handle this error and reconnect?

PrismaClientKnownRequestError:
Invalid prismaClient_1.default.flight.findUnique() invocation in
/dist/database/flight.js:24:64

21 /
22 function getFlightInfo(flightId) {
23 return __awaiter(this, void 0, void 0, function () {
→ 24 const flightInfo = yield prismaClient_1.default.flight.findUnique(
Can't reach database server at ************.rds.amazonaws.com:3306

Please make sure your database server is running at ************.rds.amazonaws.com:3306.
at Zr.handleRequestError (/node_modules/@prisma/client/runtime/library.js:171:6414)
at Zr.handleAndLogRequestError (/node_modules/@prisma/client/runtime/library.js:171:5948)
at Zr.request (/node_modules/@prisma/client/runtime/library.js:171:5786)
at async t._request (/node_modules/@prisma/client/runtime/library.js:174:10455) {
code: 'P1001',
clientVersion: '4.11.0',
meta: {
database_host: '************.rds.amazonaws.com',
database_port: 3306
}
}

**Comment by danimadmolil** [comment] 2023-05-25 10:29
I also get this error frequenly 
Can't reach database server at ************.****.com:3306

**Comment by fewjative** [comment] 2023-05-30 08:06
@danimadmolil is your DB hosted with neon?

**Comment by hclj37** [comment] 2023-06-06 04:12
It seems that increasing the value of `connect_timeout` can solve this problem.

```
postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}?schema=public&connect_timeout=30
```

**Comment by babycommando** [comment] 2023-06-16 18:42
@hclj37 legendary.

**Comment by babycommando** [comment] 2023-06-16 23:33
Because this have a high SEO, I would add that it is important to verify if you are dealing correctly with a lot of connections on the database connection pool. Make sure to use disconnect method `await prisma.$disconnect();` after you finish your query or mutation.

**Comment by Nitish-cy** [comment] 2024-01-28 15:48
Hi ,
I am getting this erro , could any one explain me why this is ossuring and what will be the solution for the same ?
Can't reach database server at `52.205.07.05`:`3706`

Please make sure your database server is running at `52.205.07.05`:`3706`.
frontend\node_modules\next\dist\compiled\next-server\app-route.runtime.dev.js:6:62609 {
  code: 'P1001',
  clientVersion: '5.8.1',
  meta: {
    modelName: 'locations',
    database_host: '52.205.07.05',
    database_port: 3706
