### ISSUE TITLE
MySQL JSON data type

### ISSUE THREAD

**Issue by robmurtagh** [prisma/prisma#465] opened 2019-08-29 17:16 UTC
Starting a new issue for this use case as per Slack suggestion from @schickling.

We're migrating a db from Mongo to MySQL. As such we have a number of fields which were modelled as JSON throughout the application and which we'd like to preserve in JSON format. We've chosen MySQL so we can have reasonable support for these fields.

```
model StatusType {
  criteria  Json

  @@map("status_type")
}
```

or (not quite sure about the syntax using field attributes?)

```
type Json = Json @ms.json(precision: 5, scale: 2)

model StatusType {
  criteria  Json

  @@map("status_type")
}
```

Associated issues
#186

**Comment by janpio** [comment] 2020-04-11 21:02
Closing as duplicate of https://github.com/prisma/prisma/issues/186 which is being tackled soon.

**Closed by janpio** 2020-04-11 21:02 UTC
Labels: kind/feature, topic: native database types
