### ISSUE TITLE
feature:Mongo don't have OR to query

### ISSUE THREAD

**Issue by huang12zheng** [prisma/prisma#4698] opened 2019-06-25 12:38 UTC
> Mongo don't have OR to query

```graphql
# query CheckRepositories($args:[UserWhereInput!]) 
{
  users(where:{OR:[{userName: "Z"}]}){
    _id
    userName
    
}
}
```
```bash
"Variable '$where' expected value of type 'UserWhereInput' but got: {\"OR\":[{\"userName\":\"Z\"}]}. Reason: 'OR' Field 'OR' is not defined in the input type 'UserWhereInput'. (line 1, column 8):\nquery ($where: UserWhereInput) {\n       ^"
```

**Comment by pantharshit00** [comment] 2019-07-01 12:15
Closing as a duplicate of #3897

**Closed by pantharshit00** 2019-07-01 12:15 UTC
