### ISSUE TITLE
Order by aggregate group always returns empty group as last

### ISSUE THREAD

**Issue by mlbiche** [prisma/prisma#20154] opened 2023-07-10 15:15 UTC
### Bug description

When querying a model with a group-by based on a column that can have empty values, with an aggregate and a sort on this aggregate, the empty value group is always returned last even if the aggregate result is greater than other groups.

### How to reproduce

```js
res = [
  { _count: 2, familySituation: "Divorced" },
  { _count: 1, familySituation: "CoupleWithChildren" },
  { _count: 8, familySituation: null }
]
```

### Expected behavior

```js
res = [
  { _count: 8, familySituation: null },
  { _count: 2, familySituation: "Divorced" },
  { _count: 1, familySituation: "CoupleWithChildren" }
]
```

### Prisma information

```prisma
generator client {
  provider        = "prisma-client-js"
  previewFeatures = ["fullTextSearch", "filteredRelationCount"]
  binaryTargets   = ["native", "debian-openssl-1.1.x"]
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

enum BeneficiaryFamilySituation {
  Married
  Single
  Widow
  Cohabitation
  CivilUnion
  CoupleWithChildren
  Divorced
  Separated
  SingleParentWithChildren
  Other
}

model Beneficiary {
  id String @id @default(uuid()) @db.Uuid
  
  familySituation                    BeneficiaryFamilySituation?   @map("family_situation")

  @@map("beneficiary")
}
```

An example really closed to [the documentation example](https://www.prisma.io/docs/concepts/components/prisma-client/aggregation-grouping-summarizing?query=alias&page=1#filter-groups-with-having):
```ts
const res = await prismaClient.beneficiary.groupBy({
    by: ['familySituation'],
    _count: true,
    orderBy: { _count: { familySituation: 'desc' } }
  })
```

The executed SQL query is:
```sql
SELECT COUNT(*), "public"."beneficiary"."family_situation" FROM "public"."beneficiary" GROUP BY "public"."beneficiary"."family_situation" ORDER BY COUNT("public"."beneficiary"."family_situation") DESC;
```

The following SQL query returns the correct result:
```sql
SELECT COUNT(*) as count, "public"."beneficiary"."family_situation" FROM "public"."beneficiary" GROUP BY "public"."beneficiary"."family_situation" ORDER BY count DESC;
```

### Environment & setup

- OS: macOS
- Database: PostgreSQL
- Node.js version: v18.14.2

### Prisma Version

```
prisma                  : 4.13.0
@prisma/client          : 4.13.0
Current platform        : darwin
Query Engine (Node-API) : libquery-engine 1e7af066ee9cb95cf3a403c78d9aab3e6b04f37a (at node_modules/.pnpm/@prisma+engines@4.13.0/node_modules/@prisma/engines/libquery_engine-darwin.dylib.node)
Migration Engine        : migration-engine-cli 1e7af066ee9cb95cf3a403c78d9aab3e6b04f37a (at node_modules/.pnpm/@prisma+engines@4.13.0/node_modules/@prisma/engines/migration-engine-darwin)
Format Wasm             : @prisma/prisma-fmt-wasm 4.13.0-50.1e7af066ee9cb95cf3a403c78d9aab3e6b04f37a
Default Engines Hash    : 1e7af066ee9cb95cf3a403c78d9aab3e6b04f37a
Studio                  : 0.484.0
Preview Features        : fullTextSearch, filteredRelationCount
```

**Comment by janpio** [comment] 2023-07-10 16:31
Might this help here? https://www.prisma.io/docs/concepts/components/prisma-client/filtering-and-sorting#sort-with-null-records-first-or-last

**Comment by mlbiche** [comment] 2023-07-10 16:40
Not sure because in my case, null record could be first or last based on their occurrence.

**Comment by millsp** [comment] 2023-07-10 18:02
@mlbiche could you please elaborate on your use-case to explain to us why the proposed solution in the documentation does not fit your use-case? Could you please give it a try? Thanks :)

**Comment by janpio** [comment] 2023-07-10 19:31
@mlbiche 

> An example really closed to [the documentation example](https://www.prisma.io/docs/concepts/components/prisma-client/aggregation-grouping-summarizing?query=alias&page=1#filter-groups-with-having):
> 
> ```ts
> const res = await prismaClient.beneficiary.groupBy({
>     by: ['familySituation'],
>     _count: true,
>     orderBy: { _count: { familySituation: 'desc' } }
>   })
> ```

Is this the code you ran to get your results, or is that something you want to be able to use?

**Comment by mlbiche** [comment] 2023-07-12 14:57
@janpio @millsp I am not sure I can define `nulls` on `_count` order-by. Because when I check the `orderBy._count` type, `familySituation` is of type `Prisma.SortOrder | undefined` and not `Prisma.SortOrder | Prisma.SortOderInput | undefined`, as it is for columns of the model. How would you write it?

In other words, I can write:
```ts
prismaClient.beneficiary.groupBy({
  by: ['familySituation'],
  _count: true,
  orderBy: { familySituation: { sort: 'desc', nulls: 'first } }
})
```

but not:

```ts
prismaClient.beneficiary.groupBy({
  by: ['familySituation'],
  _count: true,
  orderBy: { _count: { familySituation: { sort: 'desc', nulls: 'first' } } }
})
```

@janpio It is the code I am running to get the unexpected result in the **How to reproduce** section of my issue.

**Comment by janpio** [comment] 2023-07-12 17:04
So you want to order by the count, but move the count to the end when is `familySituation == null`?

**Comment by mlbiche** [comment] 2023-07-13 07:45
I may not be clear. What I want to achieve, is to order by count, no matter if the value is `null`. So I want to have the following results:

```js
res = [
  { _count: 8, familySituation: null },
  { _count: 2, familySituation: "Divorced" },
  { _count: 1, familySituation: "CoupleWithChildren" }
]

res = [
  { _count: 8, familySituation: "Divorced" },
  { _count: 2, familySituation: null },
  { _count: 1, familySituation: "CoupleWithChildren" }
]

res = [
  { _count: 8, familySituation: "Divorced" },
  { _count: 2, familySituation: "CoupleWithChildren" }
  { _count: 1, familySituation: null },
]
```

To get these results, I use the following query:

```js
const res = await prismaClient.beneficiary.groupBy({
    by: ['familySituation'],
    _count: true,
    orderBy: { _count: { familySituation: 'desc' } }
  })
```

But the results I actually gets are:
```
res = [
  { _count: 2, familySituation: "Divorced" },
  { _count: 1, familySituation: "CoupleWithChildren" },
  { _count: 8, familySituation: null }
]

res = [
  { _count: 8, familySituation: "Divorced" },
  { _count: 1, familySituation: "CoupleWithChildren" },
  { _count: 2, familySituation: null },
]

res = [
  { _count: 8, familySituation: "Divorced" },
  { _count: 2, familySituation: "CoupleWithChildren" }
  { _count: 1, familySituation: null },
]
```

I remind that I am running with Prisma v4.13.0. Yesterday, I tried to update to v4.16.0 but I struggled with type issues (unreleated to this issue).

**Comment by janpio** [comment] 2023-07-13 17:18
Thanks, I definitely misunderstood you initially. Sorry.

**Comment by janpio** [comment] 2023-07-13 17:36
I can confirm what you are seeing. We seem to apply the wrong `ORDER BY` when trying to sort by the aggregate.

**Comment by mlbiche** [comment] 2023-10-17 15:34
Any update for this one?
Cheers 🤙

**Comment by janpio** [comment] 2023-10-17 16:54
Unfortunately not. We will leave a comment here when we tackle this.

**Comment by mlbiche** [comment] 2023-10-18 07:16
I have seen in Prisma `CONTRIBUTION.md` that most of the development is done by the Prisma team. But for such a minor fix, are external contributions welcomed? If the fixed SQL query I propose in the issue seems ok to you, I could open a PR for this (if I am right, it should be in https://github.com/prisma/prisma-engines repo?).

**Comment by janpio** [comment] 2023-10-18 09:59
Yes, of course - that is exactly the kind of contributions that we are able to handle and that are happening quite frequently.

**Comment by jacek-prisma** [comment] 2024-11-26 13:48
Hi @mlbiche,

The behavior in your example might be confusing, but I don't think it's a bug.
To clarify, the `_count: true` and `_count: { familySituation: 'desc' }` options have different implications:
* **`_count: true`**: Counts all rows, including those with null values for the specified column.
* **`_count: { familySituation: 'desc' }`**: Counts only rows with non-null values for the `familySituation` column.

To highlight the issue, it might be worth considering slightly modified code that selects the column in both cases:
```ts
await prisma.beneficiary.groupBy({
    by: ['familySituation'],
    _count: { familySituation: true },
    orderBy: { _count: { familySituation: 'desc' } },
})
```
<details>
<summary>Output before</summary>
<pre>
[
  { _count: 2, familySituation: 'Divorced' },
  { _count: 1, familySituation: 'CoupleWithChildren' },
  { _count: 8, familySituation: null }
]
</pre>
</details>
<details>
<summary>Output after</summary>
<pre>
[
  { _count: { familySituation: 2 }, familySituation: 'Divorced' },
  {
    _count: { familySituation: 1 },
    familySituation: 'CoupleWithChildren'
  },
  { _count: { familySituation: 0 }, familySituation: null }
]
</pre>
</details>
In the modified example, the ordering of the results is consistent with the counts returned, because both will ignore null values.


I think this bug report actually highlights a potential missing feature, not a bug: being able to count all rows inside of `orderBy`, something like this (invented, currently unsupported syntax):
```ts
await prisma.beneficiary.groupBy({
    by: ['familySituation'],
    _count: true,
    orderBy: { _count: { "*": "desc" } },
})
```

**Comment by aqrln** [comment] 2024-11-27 11:08
Hey @mlbiche, as @jacek-prisma wrote above, the result is confusing because you're actually ordering on one value and selecting a different value, as `_count: true` (or, equivalently, `_count: { _all: true }`) and `_count: { someColumn: true }` have very different meaning.

Selecting both of them nicely demonstrates what happens and why the null group is last after ordering:

```diff
  const res = await prismaClient.beneficiary.groupBy({
    by: ['familySituation'],
-   _count: true,
+   _count: {
+     _all: true,
+      familySituation: true,
+   },
    orderBy: { _count: { familySituation: 'desc' } }
  })
```

```
res = [
  { _count: { _all: 2, familySituation: 2 }, familySituation: "Divorced" },
  { _count: { _all: 1, familySituation: 1 }, familySituation: "CoupleWithChildren" },
  { _count: { _all: 8, familySituation: 0 }, familySituation: null }
]
```

What you want is being able to write `orderBy: { _count: 'desc' }` or `orderBy: { _count: { _all: 'desc' } }` but this isn't currently allowed by the Prisma API unfortunately, and I can't find existing feature requests for it, so please go ahead and create one if it is still relevant for you.

As for this issue, I'm going to go ahead and close it since it's not a bug and works as expected.

**Closed by aqrln** 2024-11-27 11:08 UTC
Labels: bug/2-confirmed, kind/bug, tech/engines, topic: null, domain/client, topic: enum, topic: orderByAggregateGroup, topic: aggregate
