### ISSUE TITLE
Internal error: Attempted to serialize empty result.

### ISSUE THREAD

**Issue by christian-valadez** [prisma/prisma#17279] opened 2023-01-12 22:35 UTC
Hi Prisma Team! My Prisma Client just crashed. This is the report:
## Versions

| Name            | Version            |
|-----------------|--------------------|
| Node            | v16.16.0           | 
| OS              | rhel-openssl-1.0.x |
| Prisma Client   | 4.8.0              |
| Query Engine    | d6e67a83f971b175a593ccc12e15c4a757f93ffe|
| Database        | mysql              |

## Logs
```
prisma:tryLoadEnv Environment variables loaded from /var/task/.env
prisma:tryLoadEnv Environment variables not found at /var/task/packages/db/.env
prisma:tryLoadEnv Environment variables loaded from /var/task/.env
prisma:tryLoadEnv Environment variables not found at /var/task/packages/db/.env
prisma:client dirname /var/task/node_modules/.prisma/client
prisma:client relativePath ../../../packages/db/prisma
prisma:client cwd /var/task/node_modules/.prisma/client
prisma:client clientVersion 4.8.0
prisma:client clientEngineType library
prisma:client:libraryEngine internalSetup
prisma:client:libraryEngine:loader Searching for Query Engine Library in /var/task/node_modules/.prisma/client
prisma:client:libraryEngine:loader loadEngine using /var/task/node_modules/.prisma/client/libquery_engine-rhel-openssl-1.0.x.so.node
prisma:client:libraryEngine library starting
prisma:client:libraryEngine library started
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
```

## Client Snippet
```ts
await prisma.muxAsset.upsert({
    where: {
      id: sectionMeeting?.muxRecordingId!,
    },
    update: {
      assetId: muxAsset.id,
      status: 'created',
    },
    create: {
      assetId: muxAsset.id,
      status: 'created',
      sectionMeeting: {
        connect: {
          meetingId,
        },
      },
    },
  });
```

## Schema
```prisma

/// A meeting instance for a class section
model SectionMeeting {
  meetingId    Int          @id @default(autoincrement())
  sectionId    Int
  classSection ClassSection @relation(fields: [sectionId], references: [sectionId], onUpdate: NoAction)

  /// If there's a recording for this meeting, it will be stored here.
  muxRecordingId Int?      @unique
  muxRecording   MuxAsset? @relation(fields: [muxRecordingId], references: [id], onUpdate: NoAction)

  @@index([sectionId])
}

model MuxAsset {
  id    Int     @id @default(autoincrement())
  title String?

  /// The assetId in the Mux API. Defined once upload is done and asset is created.
  assetId String? @unique

  status MuxAssetStatus

  /// The duration of the asset in seconds.
  duration Float?

  /// A Daily Class Video Recording that has been stored in Mux
  sectionMeeting SectionMeeting?
}
```

## Prisma Engine Query
```
{"X":{}}
```

**Comment by christian-valadez** [comment] 2023-01-12 22:36
It seems like this could be a build issue - it works fine in dev but when I deploy to Vercel, it breaks.

**Comment by mcbethio** [comment] 2023-01-13 12:38
Hey @christian-valadez,

Please could you send us some sample/mock data that you are trying upsert?

Just some more clarification for us also - when you say a build issue, in your dev environment everything builds and executes correctly? You only hit an issue upserting in vercel right?

**Comment by christian-valadez** [comment] 2023-01-13 19:32
> Hey @christian-valadez,
> 
> Please could you send us some sample/mock data that you are trying upsert?
> 
> Just some more clarification for us also - when you say a build issue, in your dev environment everything builds and executes correctly? You only hit an issue upserting in vercel right?

Yes, that's correct - I only hit the issue on Vercel. 

Sure, some mock data: 
```
await prisma.muxAsset.upsert({
    where: {
      id: 10, 
    },
    update: {
      assetId: 5,
      status: 'created',
    },
    create: {
      assetId: 5,
      status: 'created',
      sectionMeeting: {
        connect: {
          meetingId: 4,
        },
      },
    },
  });
  ```

**Comment by christian-valadez** [comment] 2023-01-13 19:34
> Are you talking to a database with same data on dev than on production/Vercel @christian-valadez?

Yes - it's the same database, hosted on Planetscale. I'm using the same DATABASE_URL on both Vercel and in dev.

**Comment by christian-valadez** [comment] 2023-01-13 19:54
Related issue: https://github.com/prisma/prisma/issues/17305

**Comment by christian-valadez** [comment] 2023-01-13 22:14
Downgrading to 4.5.0 fixes this issue for me.

**Comment by jde** [comment] 2023-07-03 17:07
Thanks for finding this Christian. I'm having the same issue over here https://github.com/prisma/prisma/issues/20042

Downgrading to 4.5.0 and reverting to the deprecated "referentialIntegrity" feature has fixed this for me too. Hoping that this is fixed so that we can take advantage of later version.

**Comment by millsp** [comment] 2023-07-13 13:25
Hey @christian-valadez @jde, we were not able to reproduce this issue. Could you please try again with the latest version of Prisma? Also, has the been happening consistently in such a way that you could provide us with a repro, or was it a one-off?

**Comment by millsp** [comment] 2023-07-27 13:44
Gentle ping for @christian-valadez and @jde, could you please help us with the missing information? Thanks.

**Comment by millsp** [comment] 2023-08-01 22:11
Hey @christian-valadez @jde, I am closing this issue as we did not hear back from you. Just ping us and we can re-open it when we have the missing information. Thanks!

**Closed by millsp** 2023-08-01 22:11 UTC
Labels: bug/0-unknown, kind/bug, topic: mysql, team/client, topic: rust panic, topic: upsert, topic: deployment/vercel
