### ISSUE TITLE
Prisma + `netlify dev`: `Cannot read, EISDIR: illegal operation on a directory`

### ISSUE THREAD

**Issue by M-W1995** [prisma/prisma#16708] opened 2022-12-08 22:59 UTC
### Bug description

Unable to use prisma with netlify.

I've tried making other projects from scratch just following the documentations, incase I had messed up somewhere, but I always end bumping into the same error, causing my app to crash. 

```
NestedError: Cannot read from `[PROJECT PATH]/node_modules/.prisma`: 
EISDIR: illegal operation on a directory, read
/netlify-cli/node_modules/cp-file/fs.js:21:9)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at copyFileAsync (file:///C:/Users/skunk/AppData/Roaming/npm/node_modules/netlify-cli/node_modules/cp-file/index.js:11:21)
    at C:\Users\skunk\AppData\Roaming\npm\node_modules\netlify-cli\node_modules\p-map\index.js:57:22
Caused By: Error: EISDIR: illegal operation on a directory, read {
  nested: [Error: EISDIR: illegal operation on a directory, read] {
    errno: -4068,
    code: 'EISDIR',
    syscall: 'read'
  },
  errno: -4068,
  code: 'EISDIR',
  syscall: 'read',
  name: 'CopyFileError'
}
```

From what I understand, netlify expects .prisma to be a file and is trying to read it, when it is a folder.
Stack trace seems to come from this line : https://github.dev/sindresorhus/cp-file/blob/a98bdff6d7dd7005370e05f84537c58d1caf1fd5/fs.js#L21

### How to reproduce

1. Make a new netlify project (along with Astro in this case)
2. Install prisma and prisma client 
3. `netlify dev` in terminal
Note that at this point, no function using Prisma actually is called.
4. App crashes, giving the error message above
5. Non profit :( 

### Expected behavior

I do expect my app to run without crashing.

### Prisma information

```prisma
generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "mysql"
  url      = env("DATABASE_URL")
}

model user {
  id       Int    @id @default(autoincrement())
  username String @db.VarChar(255)
}
```

```ts
// app crashes before it even reaches this 

import { PrismaClient } from '@prisma/client'

const prisma = new PrismaClient()

export const handler = async (event, context) => {

    const users = await prisma.user.findMany()

    return {
        statusCode: 200,
        body: JSON.stringify(users)
    }

}
```

### Environment & setup

- OS: Windows 10
- Database: MySQL
- Node.js version: 16.13.1

### Prisma Version

```
prisma                  : 4.7.1
@prisma/client          : 4.7.1
Current platform        : windows
Query Engine (Node-API) : libquery-engine 272861e07ab64f234d3ffc4094e32bd61775599c (at node_modules\@prisma\engines\query_engine-windows.dll.node)
Migration Engine        : migration-engine-cli 272861e07ab64f234d3ffc4094e32bd61775599c (at node_modules\@prisma\engines\migration-engine-windows.exe)
Introspection Engine    : introspection-core 272861e07ab64f234d3ffc4094e32bd61775599c (at node_modules\@prisma\engines\introspection-engine-windows.exe)
Format Binary           : prisma-fmt 272861e07ab64f234d3ffc4094e32bd61775599c (at node_modules\@prisma\engines\prisma-fmt-windows.exe)
Format Wasm             : @prisma/prisma-fmt-wasm 4.7.1-1.272861e07ab64f234d3ffc4094e32bd61775599c
Default Engines Hash    : 272861e07ab64f234d3ffc4094e32bd61775599c
Studio                  : 0.477.0
```

Test repository : https://github.com/M-W1995/prisma-netlify-astro

**Comment by M-W1995** [comment] 2022-12-09 10:34
> The Astro part (and whatever build process that has) is most probably causing this. Can you tell us more about this, or optimally create a minimal reproduction project and put it on GitHub? Thanks.

Hello, there you go : https://github.com/M-W1995/prisma-netlify-astro

**Comment by janpio** [comment] 2022-12-09 17:05
Hm, with your repro actually everything works for me (on Gitpod):
<img width="660" alt="image" src="https://user-images.githubusercontent.com/183673/206753989-f908981a-1e74-48cf-bc7f-4f382667bded.png">

This is what you describe and experience as failing, correct?

**Comment by janpio** [comment] 2022-12-09 17:09
(Also works on local checkout on Windows for me)

**Comment by M-W1995** [comment] 2022-12-09 21:59
Weird. I can confirm that I still get the same error using this exact repo. Where could the problem come from ?

```
NestedError: Cannot read from `C:/Users/skunk/Desktop/dev/prisma-netlify-astro/node_modules/.prisma`: EISDIR: illegal operation on a directory, read
    at Module.createReadStream (file:///C:/Users/skunk/AppData/Roaming/npm/node_modules/netlify-cli/node_modules/cp-file/fs.js:21:9)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at copyFileAsync (file:///C:/Users/skunk/AppData/Roaming/npm/node_modules/netlify-cli/node_modules/cp-file/index.js:11:21)
    at C:\Users\skunk\AppData\Roaming\npm\node_modules\netlify-cli\node_modules\p-map\index.js:57:22
Caused By: Error: EISDIR: illegal operation on a directory, read {
  nested: [Error: EISDIR: illegal operation on a directory, read] {
    errno: -4068,
    code: 'EISDIR',
    syscall: 'read'
  },
  errno: -4068,
  code: 'EISDIR',
  syscall: 'read',
  name: 'CopyFileError'
}
```

**Comment by janpio** [comment] 2022-12-09 22:29
Pure guessing now: Where you project is located (`Desktop`) or how your Npm works and is installed (`Appdata/Roaming`). Maybe try `npm install netlify-cli` and run it via `npx netlify dev` instead. Or put your project in another folder somewhere on your hard disk.

**Comment by M-W1995** [comment] 2022-12-09 22:49
Tried `npx netlify dev` and moving my folder directly in C:\, no success ; still getting the same error.

For testing purpose I've tried building other astro+prisma projects (located on Desktop aswell), but this time using vercel instead of netlify and they run smoothly.

**Comment by janpio** [comment] 2022-12-09 23:01
Did you delete your `node_modules` already completely and run `npm install`? Something is off with the folder here for some reason, or how `netlify dev` interacts with that folder.

**Comment by janpio** [comment] 2022-12-11 20:30
Maybe you can open an issue over at https://github.com/netlify/cli/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc? It seems your `netlify dev` somehow is doing something it is not allowed to do when acting on the `.prisma` folder. From our side I see no way to change this.

Ah, typing that actually gave me a possible idea for a workaround: https://www.prisma.io/docs/concepts/components/prisma-client/working-with-prismaclient/generating-prisma-client#using-a-custom-output-path This makes Prisma use a different location, maybe that will let your `netlify dev` succeed.

**Comment by janpio** [comment] 2022-12-11 21:20
Here is a related issue: https://github.com/prisma/prisma/issues/16021

**Comment by janpio** [comment] 2022-12-11 21:29
Found are related issue in the Netlify CLI repository (also by a Prisma user, which is using Windows) so wrote a comment to connect all this together: https://github.com/netlify/cli/issues/5183#issuecomment-1345661059

**Comment by janpio** [comment] 2022-12-11 21:45
And my suggested workaround with `output` folder indeed works: https://github.com/prisma/prisma/issues/16021#issuecomment-1345664685

(The reproduction for the related issue indeed did work for me on Windows surprisingly, so I could both confirm the problem with `netlify dev` and then also verify my suggested workaround)

**Comment by janpio** [comment] 2022-12-11 21:48
As I could reproduce in the other issue, but not here, I will close this issue now and track the problem over at https://github.com/prisma/prisma/issues/16021. It's not really a Prisma problem, but we are interested in driving this forward anyway of course.

**Closed by janpio** 2022-12-11 21:48 UTC
Labels: bug/2-confirmed, kind/bug, topic: prisma-client, topic: windows, topic: serverless, team/client, topic: deployment/netlify

**Comment by janpio** [comment] 2022-12-11 21:53
@M-W1995 For the other issue my suggested workaround did not work, but it might for you, so maybe try the steps decsribed here and let me know if this works for you: https://github.com/prisma/prisma/issues/16021#issuecomment-1345664685
