### ISSUE TITLE
2x worse performance when running raw queries in Prisma vs `pg`

### ISSUE THREAD

**Issue by srujun** [prisma/prisma#23573] opened 2024-03-21 01:27 UTC
### Bug description

We've been having trouble with bad performance with our database queries. We have spent multiple weeks on this issue on implementing tracing, checking Postgres performance, rewriting/reducing our queries, etc. but have only had marginal improvements in performance. The only piece of our stack which we haven't changed much is Prisma, so I wrote a simple benchmark script comparing Prisma's performance with the `pg` library.

I took one of our worst performing Graphql queries and wrote out all the raw SQL queries the corresponding resolver and nested resolvers make. There are about 300 individual SELECT queries that are executed in chunks, and each chunk is executed concurrently. With `pg` I am creating a connection pool of size 40. And with Prisma, I am using `$queryRawUnsafe` to execute the query and setting `?connection_limit=40`.

The expectation would be that query performance is close to equivalent between the two, but the difference is quite spectacular with the Prisma benchmark taking **twice** as long as `pg`.

`pg`:
```
$ node benchmark_pg.mjs
Concurrency: 10
Execution time: 2.1500 seconds
All queries executed successfully.

Concurrency: 20
Execution time: 1.2770 seconds
All queries executed successfully.

Concurrency: 40
Execution time: 0.7930 seconds
All queries executed successfully.

Concurrency: 80
Execution time: 0.7440 seconds
All queries executed successfully.

Concurrency: 160
Execution time: 0.7220 seconds
All queries executed successfully.
```

Prisma:
```
$ node benchmark_prisma.mjs
Concurrency: 10
Execution time: 4.3470 seconds
All queries executed successfully.

Concurrency: 20
Execution time: 2.3690 seconds
All queries executed successfully.

Concurrency: 40
Execution time: 1.4500 seconds
All queries executed successfully.

Concurrency: 80
Execution time: 1.4120 seconds
All queries executed successfully.

Concurrency: 160
Execution time: 1.3750 seconds
All queries executed successfully.
```

I expect the likely issue is in how we configure Prisma, otherwise this big of a performance drop is unexpected. What is the problem here? We would like the benefits of Prisma's ORM but the performance drop is too large for us.

### How to reproduce

The benchmark script looks like so:

```typescript
import fs from 'fs'
import pg from 'pg'

function createPool() {
  const pool = new pg.Pool({
    user: 'postgres',
    host: 'X.X.X.X',
    database: 'stagingDb',
    password: '...',
    port: 5432,
    max: 40,
  })
  return pool
}

// Function to read SQL queries from a file
function readSqlFromFile(filePath) {
  return new Promise((resolve, reject) => {
    fs.readFile(filePath, { encoding: 'utf-8' }, (err, data) => {
      if (err) reject(err)
      else resolve(data)
    })
  })
}

// Function to execute a chunk of queries concurrently
async function executeQueryChunk(pool, queries) {
  await Promise.all(
    queries.map((query) => {
      if (query) {
        return pool.query(query)
      }
      return Promise.reject()
    })
  )
}

// Function to execute your queries
async function executeQueries(filePath, concurrencyLimit) {
  console.log('\nConcurrency:', concurrencyLimit)

  const pool = createPool()

  try {
    const queriesString = await readSqlFromFile(filePath)
    const queries = queriesString
      .split(';') // Splitting queries by ';'
      .map((query) => query.trim())
      .filter((query) => query) // Ensure no empty queries

    const start = Date.now()

    for (let i = 0; i < queries.length; i += concurrencyLimit) {
      // Create a chunk of queries to run concurrently
      const queryChunk = queries.slice(i, i + concurrencyLimit)
      await executeQueryChunk(pool, queryChunk)
    }

    const end = Date.now()
    console.log(`Execution time: ${((end - start) / 1000).toFixed(4)} seconds`)

    console.log('All queries executed successfully.')
  } catch (error) {
    console.error('Error executing queries:', error)
  } finally {
    await pool.end() // Close the pool
  }
}

const concurrencyLimits = [10, 20, 40, 80, 160]
for (const limit of concurrencyLimits) {
  await executeQueries('./benchmark.sql', limit)
}
```

And the corresponding changes for the Prisma test script is:

```typescript
import { PrismaClient } from '@prisma/client'

function createClient() {
  const client = new PrismaClient({
    datasources: {
      db: {
        url: 'postgresql://postgres:...@X.X.X.X:5432/stagingDb?connection_limit=40',
      },
    },
  })
  return client
}

// Function to execute a chunk of queries concurrently
async function executeQueryChunk(client, queries) {
  await Promise.all(
    queries.map((query) => {
      if (query) {
        return client.$queryRawUnsafe(query)
      }
      return Promise.reject()
    })
  )
}

// ...

const client = createClient()
await client.$connect()
```

### Prisma information

```
datasource db {
  provider = "postgresql"
  url      = env("PRISMA_POSTGRES_URL")
}

generator client {
  provider        = "prisma-client-js"
  previewFeatures = ["relationJoins", "tracing"]
}

// bunch of model and enum definitions ...
```

### Environment & setup

- Database: PostgreSQL 12.17
- Node.js version: v18.12.1

### Prisma Version

```
npx prisma -v
Environment variables loaded from .env
prisma                  : 5.10.2
@prisma/client          : 5.10.2
Computed binaryTarget   : darwin-arm64
Operating System        : darwin
Architecture            : arm64
Node.js                 : v18.12.1
Query Engine (Node-API) : libquery-engine 5a9203d0590c951969e85a7d07215503f4672eb9 (at node_modules/@prisma/engines/libquery_engine-darwin-arm64.dylib.node)
Schema Engine           : schema-engine-cli 5a9203d0590c951969e85a7d07215503f4672eb9 (at node_modules/@prisma/engines/schema-engine-darwin-arm64)
Schema Wasm             : @prisma/prisma-schema-wasm 5.10.0-34.5a9203d0590c951969e85a7d07215503f4672eb9
Default Engines Hash    : 5a9203d0590c951969e85a7d07215503f4672eb9
Studio                  : 0.499.0
Preview Features        : tracing, relationJoins
```

**Comment by SevInf** [comment] 2024-03-21 06:11
`pg` and prisma have different default when it comes to TLS handshake when establishing connection. Prisma defaults to `sslmode=prefer` while `pg` defaults to `sslmode=disable`. If you either switch Prisma to `disable` or `pg` to `prefer`, you should get similar results. You can do this by adding `sslmode` parameter with corresponding value to the connection string.
Let me know if that works for you!

**Comment by srujun** [comment] 2024-03-21 08:22
Adding `sslmode=disable` to the connection string for Prisma only improved things marginally (around 5-10%):

```
$ node benchmark_prisma.mjs
Concurrency: 10
Execution time: 3.7980 seconds
All queries executed successfully.

Concurrency: 20
Execution time: 2.1860 seconds
All queries executed successfully.

Concurrency: 40
Execution time: 1.2240 seconds
All queries executed successfully.

Concurrency: 80
Execution time: 1.1800 seconds
All queries executed successfully.

Concurrency: 160
Execution time: 1.1330 seconds
All queries executed successfully.
```

This is still considerably slower than `pg`.

**Comment by peterHakio** [comment] 2024-03-21 08:36
We are having similar expereiences between Kysely and prisma. Just with a bigger difference

**Comment by peterHakio** [comment] 2024-03-21 09:13
Is it connected to https://github.com/prisma/prisma/issues/19886 
And @srujun great work, but just for completness could you also run the test with currency=1?

**Comment by srujun** [comment] 2024-03-22 13:37
Is there any update on this? I am pretty convinced that it is just the individual query that takes Prisma almost twice as long to execute. I enabled Opentelemetry and the traces confirm this.

pg:
<img width="1024" alt="Screenshot 2024-03-22 at 6 31 16 AM" src="https://github.com/prisma/prisma/assets/536115/31e82dc8-e301-4b02-ac0b-d288e5c5f9fa">

Prisma:
<img width="1024" alt="Screenshot 2024-03-22 at 6 35 28 AM" src="https://github.com/prisma/prisma/assets/536115/46a88dc1-5ed4-4dbb-a8aa-3f7ccf945752">

**Comment by peterHakio** [comment] 2024-03-22 20:44
We did some detailed performance of prisma vs kysely, which underlying using pg. We found that data heavy queries performed up to 5 times worse on prisma. Based on this investigation we think there is something in the serialization in the prisma engine that is slowing it down heavily

**Comment by arnmishra** [comment] 2024-03-28 18:12
@Prisma team @SevInf  (I work on the same team as @srujun)

This is a P0 issue for us. We are actively having to build hacks into our platform to cover up Prisma's problems and therefore we are have actively exploring getting rid of Prisma given how poor the performance has been. I can't fathom how an ORM would cause a 2x dropoff in performance of even extremely simple queries so until now I've been assuming it is a setup issue _on our end_. However, we've spoken with others (and there are others on this very thread) and have heard myriad issues ranging from connection pooling to very similar performance issues that collectively have quickly degraded our faith in Prisma as a enterprise-ready tool.

We very much need this to be a prioritized issue that gets addressed ASAP. Our team is available to jump on calls or do whatever it takes to get this resolved. Let me know what we can do to work on this together.

**Comment by petradonka** [comment] 2024-03-28 20:10
Performance parity with `pg` is currently not highly prioritized due to addressing the broader interests of our userbase. We may get closer, no promises.

As we've been in touch over email with @srujun, happy to continue the conversation there and provide additional context.

**Comment by srujun** [comment] 2024-04-04 01:06
We still have not been able to resolve this performance issue, and the delta is even larger when running the query from within the same network as the Postgres database. In this case, we are using Google Cloud SQL's managed Postgres database and running the benchmark in a Google Cloud Compute VM within the same VPC.

I have attached the actual benchmark scripts and the results:

1. [benchmark_pg.mjs.txt](https://github.com/prisma/prisma/files/14860059/benchmark_pg.mjs.txt)
2. [benchmark_prisma.mjs.txt](https://github.com/prisma/prisma/files/14860061/benchmark_prisma.mjs.txt)
3. [benchmark_pg_results.txt](https://github.com/prisma/prisma/files/14860054/benchmark_pg_results.txt)
4. [benchmark_prisma_results.txt](https://github.com/prisma/prisma/files/14860060/benchmark_prisma_results.txt)
5. [benchmark.sql.txt](https://github.com/prisma/prisma/files/14860062/benchmark.sql.txt)

**Comment by laplab** [comment] 2024-04-11 14:12
Thank you for reporting the issue, @arnmishra @srujun.

To make further progress here, we will need data the benchmark is running on. Any random data that reproduces the regression is fine.

**Comment by laplab** [comment] 2024-04-24 14:07
@arnmishra @srujun Since we do not have the data to reproduce the issue and no schema to try to reproduce the issue with random data, I am going to close it for now. Feel free to reopen it in the future, but please provide us with data to run benchmarks against.

**Comment by srujun** [comment] 2024-04-24 14:14
@laplab apologies for missing this. To create random data, we can use pgbench to seed the database:

```
$ pgbench -i -s 50 -h localhost -p 5432 -U postgres pgbench_test
```

And then here is a SQL file with random queries that can be used in the benchmark: [benchmark.txt](https://github.com/prisma/prisma/files/15095613/benchmark2.txt). Can you please reopen this issue?

**Comment by laplab** [comment] 2024-04-24 14:18
@srujun We still do not have the database schema to populate with `pgbench`. We need the schema to populate tables.

**Comment by srujun** [comment] 2024-04-24 14:20
pgbench creates the schema in the database name you provide (which is `pgbench_test` in my command above). It is a standard schema of 4 tables. See reference: https://www.postgresql.org/docs/current/pgbench.html

**Comment by laplab** [comment] 2024-04-24 14:53
I was able to confirm that Prisma indeed performs much worse than PG on a variety of pool configurations. In the chart below Y-axis is milliseconds, lower is better.

![PG vs Prisma from Google Sheets](https://github.com/prisma/prisma/assets/5737185/e58d2c30-8446-4311-b4c3-82562042b6e7)

Here is the raw data from running the benchmarks:

<details>
<summary>pg</summary>

```
PoolSize=10	Concurrency=1	Time=70ms
PoolSize=10	Concurrency=10	Time=26ms
PoolSize=10	Concurrency=20	Time=21ms
PoolSize=10	Concurrency=40	Time=20ms
PoolSize=10	Concurrency=80	Time=18ms
PoolSize=10	Concurrency=160	Time=17ms
PoolSize=20	Concurrency=1	Time=52ms
PoolSize=20	Concurrency=10	Time=22ms
PoolSize=20	Concurrency=20	Time=25ms
PoolSize=20	Concurrency=40	Time=24ms
PoolSize=20	Concurrency=80	Time=21ms
PoolSize=20	Concurrency=160	Time=17ms
PoolSize=40	Concurrency=1	Time=50ms
PoolSize=40	Concurrency=10	Time=23ms
PoolSize=40	Concurrency=20	Time=23ms
PoolSize=40	Concurrency=40	Time=25ms
PoolSize=40	Concurrency=80	Time=23ms
PoolSize=40	Concurrency=160	Time=21ms
PoolSize=80	Concurrency=1	Time=51ms
PoolSize=80	Concurrency=10	Time=21ms
PoolSize=80	Concurrency=20	Time=23ms
PoolSize=80	Concurrency=40	Time=28ms
PoolSize=80	Concurrency=80	Time=38ms
PoolSize=80	Concurrency=160	Time=31ms
```
</details>

<details>
<summary>Prisma</summary>

```
PoolSize=10	Concurrency=1	Time=374ms
PoolSize=10	Concurrency=10	Time=107ms
PoolSize=10	Concurrency=20	Time=67ms
PoolSize=10	Concurrency=40	Time=51ms
PoolSize=10	Concurrency=80	Time=38ms
PoolSize=10	Concurrency=160	Time=35ms
PoolSize=20	Concurrency=1	Time=129ms
PoolSize=20	Concurrency=10	Time=48ms
PoolSize=20	Concurrency=20	Time=45ms
PoolSize=20	Concurrency=40	Time=40ms
PoolSize=20	Concurrency=80	Time=41ms
PoolSize=20	Concurrency=160	Time=33ms
PoolSize=40	Concurrency=1	Time=128ms
PoolSize=40	Concurrency=10	Time=48ms
PoolSize=40	Concurrency=20	Time=44ms
PoolSize=40	Concurrency=40	Time=49ms
PoolSize=40	Concurrency=80	Time=41ms
PoolSize=40	Concurrency=160	Time=40ms
PoolSize=80	Concurrency=1	Time=131ms
PoolSize=80	Concurrency=10	Time=48ms
PoolSize=80	Concurrency=20	Time=44ms
PoolSize=80	Concurrency=40	Time=49ms
PoolSize=80	Concurrency=80	Time=56ms
PoolSize=80	Concurrency=160	Time=47ms
```
</details>

**Comment by srujun** [comment] 2024-04-24 16:55
Thank you for confirming this. It seems like at lower concurrency levels the performance is much worse, indicating that the query initialization cost is somehow much higher in Prisma. Either ways, what are the next steps here? We have been suffering these performance issues for a while and will be happy to help to get this resolved as soon as possible.

**Comment by srujun** [comment] 2024-05-08 04:40
@laplab was there any update on this performance issue?

**Comment by arnmishra** [comment] 2024-05-14 01:35
@laplab pinging again here

**Comment by apolanc** [comment] 2024-05-16 17:21
Hello @srujun and @arnmishra!

I appreciate your efforts in sharing the details needed to reproduce the issue. As mentioned by @laplab, we've also verified the results on our end.

This is not currently in our top priority and we are currently working on many other important and impactful initiatives. Therefore, we cannot guarantee a resolution that meets your expectations as we will not be working on this anytime soon. Additionally, an expected performance close to or equal to `pg` is highly unlikely to happen.

We'll keep this issue open will use it to follow up in the future. Thanks once again for the time invested!

**Comment by StoneCypher** [comment] 2024-06-04 02:00
@arnmishra 

> Our team is available to jump on calls or do whatever it takes to get this resolved. Let me know what we can do to work on this together.

dude open a PR

**Comment by Weakky** [comment] 2024-07-16 10:07
Hey folks, we're about to release Prisma 5.17.0 and it comes with performance improvements on queryRaw.

On our side, we've measured up to 2x perf improvements compared to Prisma 5.16.0, as well as improved memory usage. Here's a similar graph that @laplab did with the new improvements, based on the same pgbench dataset 👇. Please, keep in mind that we won't ever be as fast as a bare driver.

![image](https://github.com/user-attachments/assets/d26878d0-a202-441d-851a-6b7b38c31e97)

We hope these improvements show promising results on your side as well. With that, I'm closing the issue 🙏

**Closed by Weakky** 2024-07-16 10:07 UTC
Labels: bug/2-confirmed, kind/bug, topic: performance, domain/client, topic: postgresql

**Comment by jeremyisatrecharm** [comment] 2024-11-18 03:16
I have also encountered ~5x slowdown on `Prisma` raw vs `pg` (500ms vs ~2-3secs). Pretty disappointing I basically have to also use `pg` now https://discord.com/channels/937751382725886062/1307897113312497747

**Comment by 0xdevalias** [comment] 2024-11-26 03:17
See also:

- https://github.com/prisma/prisma/issues/19886
