### ISSUE TITLE
Error in PostgreSQL connection: Error { kind: Io, cause: Some(Os { code: 104, kind: ConnectionReset, message: "Connection reset by peer" }) }

### ISSUE THREAD

**Issue by splacentino** [prisma/prisma#5554] opened 2021-02-09 11:13 UTC
Hi Prisma Team! My Prisma Client just crashed. This is the report:
## Versions

| Name            | Version            |
|-----------------|--------------------|
| Node            | v15.8.0            | 
| OS              | linux-musl         |
| Prisma Client   | 2.16.0             |
| Query Engine    | query-engine 854c8ba7f0dce66f115af36af24e66989a8c02a1|
| Database        | undefined|

## Query
```
mutation {
  updateOneRecord(
    where: {
      id: 5
    }
    data: {
      recordId: "X"
    }
  ) {
    id
  }
}
```

## Logs
```
prisma-client Prisma Client call:
engine stdout  Error in PostgreSQL connection: Error { kind: Closed, cause: None }
engine {
  error: PrismaClientUnknownRequestError2 [PrismaClientUnknownRequestError]: Error in connector: Error querying the database: connection closed
      at NodeEngine.graphQLToJSError (/usr/src/app/node_modules/@prisma/client/runtime/index.js:27077:14)
      at NodeEngine.request (/usr/src/app/node_modules/@prisma/client/runtime/index.js:26973:24)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (node:internal/process/task_queues:94:5)
      at PrismaClientFetcher.request (/usr/src/app/node_modules/@prisma/client/runtime/index.js:78434:24)
      at Object.updateRecordId (/usr/src/app/data/src/repositories/record-repository.ts:321:3)
{
    clientVersion: '2.16.0'
  }
}
engine stdout  Error in PostgreSQL connection: Error { kind: Io, cause: Some(Os { code: 104, kind: ConnectionReset, message: "Connection reset by peer" }) }
engine {
  error: PrismaClientUnknownRequestError2 [PrismaClientUnknownRequestError]: Error in connector: Error querying the database: connection closed
      at NodeEngine.graphQLToJSError (/usr/src/app/node_modules/@prisma/client/runtime/index.js:27077:14)
      at NodeEngine.request (/usr/src/app/node_modules/@prisma/client/runtime/index.js:26973:24)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (node:internal/process/task_queues:94:5)
      at PrismaClientFetcher.request (/usr/src/app/node_modules/@prisma/client/runtime/index.js:78434:24)
      at Object.updateRecordId (/usr/src/app/data/src/repositories/record-repository.ts:321:3)
{
    clientVersion: '2.16.0'
  }
}
engine {
  error: PrismaClientUnknownRequestError2 [PrismaClientUnknownRequestError]: Error in connector: Error querying the database: connection closed
      at NodeEngine.graphQLToJSError (/usr/src/app/node_modules/@prisma/client/runtime/index.js:27077:14)
      at NodeEngine.request (/usr/src/app/node_modules/@prisma/client/runtime/index.js:26973:24)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (node:internal/process/task_queues:94:5)
      at PrismaClientFetcher.request (/usr/src/app/node_modules/@prisma/client/runtime/index.js:78434:24)
      at Object.updateRecordId (/usr/src/app/data/src/repositories/record-repository.ts:321:3)
{
    clientVersion: '2.16.0'
  }
}
```

## Client Snippet
```ts
export async function updateRecordId(
  id: Record["id"],
  recordId: string
): Promise<void> {
  await database.record.update({
    where: {
      id
    },
    data: {
      recordId
    }
  });
}
```

## Schema
```prisma
model Record {
  id               Int                      @id @default(autoincrement())
  createdAt        DateTime                 @default(now())
  recordId         String?
}
```

**Comment by pantharshit00** [comment] 2021-03-10 10:28
Hey @splacentino 

Sorry for late reply here? Can you please tell me more about where your database is hosted? I can't reproduce connection issues locally. Also, please try again with the latest version once.

**Comment by splacentino** [comment] 2021-03-15 17:32
@pantharshit00 Postgre hosted on GCP SQL.

Issue is not yet appearing in last version. I'll give it more load tomorrow.

**Comment by pantharshit00** [comment] 2021-03-16 12:01
I am going to close this as you mentioned it is not reproducible in latest version. If this happens again, comment here and we can reopen.

**Closed by pantharshit00** 2021-03-16 12:01 UTC
Labels: bug/0-needs-info, kind/bug, team/client, topic: connections

**Comment by Sytten** [comment] 2021-03-19 00:16
Root bug is the same as https://github.com/prisma/prisma/issues/5976
