### ISSUE TITLE
its been 2 years since #1274

### ISSUE THREAD

**Issue by Grayson-code** [prisma/prisma#12311] opened 2022-03-14 04:18 UTC
## Problem

Its been almost 2 years since The request for multiple database, And its havent been implemented yet.
When will it be

## Suggested solution

I am asking for a solution...

## Alternatives

```ts
generator client {
  provider = "prisma-client-js"
}

datasource litebans {
  provider = "mysql"
  url      = env("DATABASE_URL")
}


datasource playerData {
  provider = "mysql"
  url      = env("DATABASE_URL_UUID")
}
```
This is My current code and it doesnt work... so want a solution to access 2 different databases

**Comment by matthewmueller** [comment] 2022-03-14 05:55
Hi @Grayson-code, multiple database support is something we are planning, but no ETA right now. Rest assured, we'll get to it eventually.

Closing as a duplicate of #1274.

**Closed by matthewmueller** 2022-03-14 05:55 UTC
