### ISSUE TITLE
The client fetches Scalar list fields as [] while they behave as if the value is NULL.

### ISSUE THREAD

**Issue by lskuper** [prisma/prisma#13859] opened 2022-06-16 16:22 UTC
### Bug description

Item with scalar list field of value NULL comes as empty list from the prismaClient.
This makes when consuming data, impossible to differentiate between empty lists and NULL value lists.

### How to reproduce

Running:
```
const blogPost0 = await prismaClient.blogPost.create({});
const blogPost1 = await prismaClient.blogPost.create({ tags: [] });
console.log({ blogPost0, blogPost1 });

// Logs
// { 
//  blogPost0: {
//    "id": "3b7a0ff6-dbe5-450a-a10f-af9aa0f0adff",
//    "createdAt": "2022-06-16T15:23:19.856Z",
//    "tags": [],  // The item behaves as if the value is NULL, but is fetched as empty list.
//  },
//  blogPost1: {
//    "id": "248f05b8-590a-4342-af9b-651aa5831df0",
//    "createdAt": "2022-06-16T15:23:19.875Z",
//    "tags": [],
//  }
//}

const blogPostsWithoutTag = await prismaClient.blogPost.findMany({
  where: {
    tag: {
      isEmpty: true,
    },
  },
});
console.log(blogPostsWithoutTag);

// Logs
//  [{
//    "id": "248f05b8-590a-4342-af9b-651aa5831df0",
//    "createdAt": "2022-06-16T15:23:19.875Z",
//    "tags": [],
//  }]
// This proofs that the item 'blogPost0' behaves as if the value of the 'tag' field is 'NULL' and not an empty list.

```

### Prisma information

```
datasource db {
  provider = "postgresql"
  url      = env("POSTGRES_URL")
}

generator client {
  provider = "prisma-client-js"
  output   = "../generated/client"
  previewFeatures = []
}

model BlogPost {
  id                   String               @id @default(uuid())
  createdAt            DateTime             @default(now())
  tags                 String[]
}
```

### Environment & setup

- OS: Mac OS
- Database: PostgreSQL
- Node.js version: v16.13.0

### Prisma Version

```
3.15.0
```

**Comment by matthewmueller** [comment] 2022-06-16 20:51
Hey @lskuper, thanks for raising this. I assume you already had nullable lists in an existing database that you'd like to differentiate with Prisma?

Unfortunately, we don't yet support syntax like `tags String[]?`, so if you're just using Prisma, you wouldn't encounter this situation. 

Of course this is something we'd like to fix. I'm going to close this as a duplicate of https://github.com/prisma/prisma/issues/4729 though.

**Comment by lskuper** [comment] 2022-06-17 06:51
Hey @matthewmueller, thanks for your reply!
No I didn't have nullable lists in the database before. It was a greenfield migration in that I added that field. The 'blogPost' table affected by that migration did contain data before.

Its totally fine that prisma doesn't support optional scalar lists yet, that's also not what I did describe in that issue.

The issue I ran into, is that the prismaClient does fetch the data as an empty list, although it (as far as I understand) is NULL in the database.

blogPost0 should be imo:
//  blogPost0: {
//    "id": "3b7a0ff6-dbe5-450a-a10f-af9aa0f0adff",
//    "createdAt": "2022-06-16T15:23:19.856Z",
//    "tags": NULL,
//  },
but is:
//  blogPost0: {
//    "id": "3b7a0ff6-dbe5-450a-a10f-af9aa0f0adff",
//    "createdAt": "2022-06-16T15:23:19.856Z",
//    "tags": [],
//  },

Or to describe it from another perspective: 

If nullable scalar lists are not supported yet, the prismaClient should prevent the creation of entities, when there is no valid value provided for a scalar list field.

**Comment by lskuper** [comment] 2022-06-17 15:50
The migration.sql that has been created out of the above schema does contain:
```ALTER TABLE "BlogPost" ADD COLUMN     "tags" TEXT[];```

So for my perception
a) the client must be able to deliver those `NULL` fields instead of `[]` (as pointed out above, they already do behave under the hood as if their value is `NULL` in queries). Here I assume its the client translating `NULL` erronously to `[]`
b) the schema for the current way scalar lists are implemented should rather be String[]? instead of String[]

**Comment by matthewmueller** [comment] 2022-06-17 16:06
Thanks @lskuper for helping me understand this problem better. I think I just covered all the angles in #13880. Do you mind having a read and making sure that covers this issue?

**Comment by matthewmueller** [comment] 2022-06-21 23:29
Closing in favor of #13880

**Closed by matthewmueller** 2022-06-21 23:29 UTC
Labels: kind/bug, team/client
