### ISSUE TITLE
Duplicate identifier in generated types

### ISSUE THREAD

**Issue by itsgiacoliketaco** [prisma/prisma#17118] opened 2023-01-03 18:12 UTC
### Bug description

Given the following schema, Prisma 4.8 will generate two different `type MemberRoleArgs` lines in `.prisma/client/index.d.ts`.  The first `MemberRoleArgs` type corresponds with the `MemberRole` model.  The second type corresponds with the `Member.role` field.

```prisma
model Member {
  id String @id
  role MemberRole? @relation(fields: [roleId], references: [id])
  roleId String?
}

model MemberRole {
  id String @id
  members Member[]
}
```

This issue is new as of Prisma 4.8.0; it does not affect 4.7.0 or below.

### How to reproduce

1. Use the above prisma schema.
2. Run `prisma generate`
3. Run `tsc --noEmit`
4. See TypeScript error:
    ```
    error TS2300: Duplicate identifier 'MemberRoleArgs'
    ```

### Expected behavior

Prisma always generates unique identifiers for helper types.

Perhaps the type for `Member.role` could be named `Member_RoleArgs` instead!

### Prisma information

Minimal Prisma schema to produce this error is given above.  

### Environment & setup

- OS: macOS
- Database: PostgreSQL
- Node.js version: 16.15.1

### Prisma Version

```
4.8.0
```

**Comment by jkomyno** [comment] 2023-01-04 10:25
Hi @itsgiacoliketaco, closing this is as a duplicate of https://github.com/prisma/prisma/issues/17005. This was indeed a regression introduced in `prisma@4.8.0` that should be fixed by the next release

**Closed by jkomyno** 2023-01-04 10:25 UTC
Labels: kind/bug

**Comment by itsgiacoliketaco** [comment] 2023-01-04 14:50
Great news, thank you!
