### ISSUE TITLE
The type of `where` part of `delete` or `update` function is wrong when using `@@unique`

### ISSUE THREAD

**Issue by rostamiani** [prisma/prisma#11284] opened 2022-01-20 11:54 UTC
### Bug description

I have a model containing `@@unique` index. When I want to add `where` section to `delete` function it's type is wrong.

### How to reproduce

Generate this model:
```prisma
model User {
  id        Int       @id @default(autoincrement())
  email     String    @unique
  password  String
  createdAt DateTime  @default(now())
  updatedAt DateTime  @updatedAt
  remarks   String?
  Channels  Channel[]
}

model Channel {
  id     Int    @id @default(autoincrement())
  name   String
  userId Int
  user   User   @relation(fields: [userId], references: [id])

  @@unique([userId, name])
  @@index([name])
}
```
It generates this class:
```ts
  export type ChannelDeleteArgs = {
    select?: ChannelSelect | null
    include?: ChannelInclude | null
    where: ChannelWhereUniqueInput
  }

  export type ChannelWhereUniqueInput = {
    id?: number
    userId_name?: ChannelUserIdNameCompoundUniqueInput
  }
```
The `where` part is different from `find` and `create` commands and does not have `channel` fields. Now I see this error:
```bash
'userId' does not exist in type 'ChannelWhereUniqueInput'
```

### Expected behavior

I want to delete a channel with this comand:
```ts
await this.prisma.channel.delete({ where: { id: 1, userId:1 } });
```

### Environment & setup

- OS: Ubuntu 21.10
- Database: PostgreSQL
- Node.js version: v16.13.1

### Prisma Version

```
3.8.1
```

**Comment by unsady** [comment] 2022-01-20 12:36
Hello! The correct query should be: 

```javascript
await this.prisma.channel.delete({ where: { userId_name: { userId: 1, name: 'John' } });
```

You can use editor suggestions (CTRL+space for vscode) to see available options.

If you need to delete rows by channel id and userId then you should create a unique index  `@@unique([userId, id])`. Where condition should be:

```javascript
await this.prisma.channel.delete({ where: { userId_id: { userId: 1, id: 1 } });
```

**Comment by rostamiani** [comment] 2022-01-21 02:22
I want to delete just one single row and only if it's belongs to a specific user. But I don't know the name
Why is it this complicated?
Why I cannot delete or update with my needed columns like this?:

```ts
this.prisma.channel.update({ where: { id: request.id, userId }, data:{name:'new Name'} });
this.prisma.channel.u({ where: { id: request.id, userId } });
```

**Comment by ruohola** [comment] 2022-01-24 21:42
> I want to delete just one single row and only if it's belongs to a specific user. But I don't know the name Why is it this complicated? Why I cannot delete or update with my needed columns like this?:
> 
> ```ts
> this.prisma.channel.update({ where: { id: request.id, userId }, data:{name:'new Name'} });
> this.prisma.channel.u({ where: { id: request.id, userId } });
> ```

This is duplicate of https://github.com/prisma/prisma/issues/7290

**Comment by matthewmueller** [comment] 2022-01-28 02:03
Thanks @ruohola, closing as a duplicate of #7290

**Closed by matthewmueller** 2022-01-28 02:03 UTC
Labels: kind/bug
