### ISSUE TITLE
Can we deploy both prisma1 and prisma2 scema to same db of MYSQL.

### ISSUE THREAD

**Issue by rahulybisen** [prisma/prisma#5490] opened 2021-02-05 13:30 UTC
I am having one application with prisma1  there i am deploying schema to MYSQL.

in another application i am using Prisma2 i want to deploy my schema to same Db which i used to deploy for Prisma1.

I tried same scenario  but at migration time of Prisma2 all table related to prisma1 is deleting and I am getting only prisma2 migration related table.

Help me to handle this scenario.

Thanks

**Comment by janpio** [comment] 2021-02-05 23:22
Duplicate of https://github.com/prisma/prisma/discussions/5492

**Closed by janpio** 2021-02-05 23:22 UTC
